### PR TITLE
BUG: spatial: fix ckdtree build problem

### LINKED ISSUE #5311: Build failure: error compiling ckdtree.
With Mac OS X 10.9.5, python 2.7.10, numpy 1.9.2, I get compilation errors when I build scipy.  I assume it is the result of https://github.com/scipy/scipy/pull/5293;  looks like `isinf` is referred to when it isn't defined.  For what it's worth:

```
$ g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

Here's the relevant part of the output that shows the compilation errors:

```
building 'scipy.spatial.ckdtree' extension
compiling C++ sources
C compiler: g++ -fno-strict-aliasing -I/Users/warren/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall

creating build/temp.macosx-10.5-x86_64-2.7/scipy/spatial/ckdtree
creating build/temp.macosx-10.5-x86_64-2.7/scipy/spatial/ckdtree/src
compile options: '-I/Users/warren/anaconda/include/python2.7 -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include -Iscipy/spatial/ckdtree/src -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/warren/anaconda/include/python2.7 -c'
g++: scipy/spatial/ckdtree/src/ckdtree_globals.cxx
g++: scipy/spatial/ckdtree/ckdtree.cxx
In file included from scipy/spatial/ckdtree/ckdtree.cxx:250:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
In file included from scipy/spatial/ckdtree/ckdtree.cxx:254:
scipy/spatial/ckdtree/src/ckdtree_cpp_methods.h:138:14: error: use of undeclared identifier 'isinf'
    else if (npy_isinf(p)) {
             ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4264:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4270:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_upper_bound) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4327:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4391:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_self->p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4702:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4778:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5422:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5428:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_upper_bound) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5485:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5549:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_self->p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5810:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5896:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:16903:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:16926:23: error: use of undeclared identifier 'isinf'
      __pyx_t_1 = ((!(npy_isinf((*__Pyx_BufPtrCContig1d(__pyx_t_5numpy_float64_t *, __pyx_pybuffernd_real_r.rcbuffer->pybuffer.buf, __pyx_t_15, __pyx_pybuffernd_real_r.diminfo[0].strides))) != 0)) != 0);
                      ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:17454:29: error: use of undeclared identifier 'isinf'
            __pyx_t_6 = ((!(npy_isinf(__pyx_v_tracker->p) != 0)) != 0);
                            ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
1 warning and 16 errors generated.
In file included from scipy/spatial/ckdtree/ckdtree.cxx:250:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
In file included from scipy/spatial/ckdtree/ckdtree.cxx:254:
scipy/spatial/ckdtree/src/ckdtree_cpp_methods.h:138:14: error: use of undeclared identifier 'isinf'
    else if (npy_isinf(p)) {
             ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4264:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4270:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_upper_bound) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4327:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4391:16: error: use of undeclared identifier 'isinf'
  __pyx_t_3 = (npy_isinf(__pyx_v_self->p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4702:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:4778:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5422:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5428:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_upper_bound) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5485:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5549:16: error: use of undeclared identifier 'isinf'
  __pyx_t_2 = (npy_isinf(__pyx_v_self->p) != 0);
               ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5810:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:5896:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_self->p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:16903:19: error: use of undeclared identifier 'isinf'
  __pyx_t_1 = ((!(npy_isinf(__pyx_v_p) != 0)) != 0);
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:16926:23: error: use of undeclared identifier 'isinf'
      __pyx_t_1 = ((!(npy_isinf((*__Pyx_BufPtrCContig1d(__pyx_t_5numpy_float64_t *, __pyx_pybuffernd_real_r.rcbuffer->pybuffer.buf, __pyx_t_15, __pyx_pybuffernd_real_r.diminfo[0].strides))) != 0)) != 0);
                      ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
scipy/spatial/ckdtree/ckdtree.cxx:17454:29: error: use of undeclared identifier 'isinf'
            __pyx_t_6 = ((!(npy_isinf(__pyx_v_tracker->p) != 0)) != 0);
                            ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:201:34: note: expanded from macro 'npy_isinf'
            #define npy_isinf(x) isinf((x))
                                 ^
1 warning and 16 errors generated.
error: Command "g++ -fno-strict-aliasing -I/Users/warren/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/warren/anaconda/include/python2.7 -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include -Iscipy/spatial/ckdtree/src -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/warren/anaconda/include/python2.7 -c scipy/spatial/ckdtree/ckdtree.cxx -o build/temp.macosx-10.5-x86_64-2.7/scipy/spatial/ckdtree/ckdtree.o" failed with exit status 1
```

### PR DESCRIPTION
**Pull request by larsmans**
Should fix gh-5311. @WarrenWeckesser please try to build this on a Mac.

See comment in `ckdtree_cpp_methods.h` for explanation.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Thanks Lars, this works for me.   It would be good to have another set of eyes take a look. @pv? @sturlamolden?

I didn't try to unwind how `isinf` was accessed, but a bit of googling showed that `isinf` is only standard in C99 and C++11.  If there is a problem with `npy_isinf`, should there be a corresponding issue filed with numpy?

**Comment by pv** [comment]
I'm surprised only this part fails, as `isinf` is used also elsewhere. Is this due to g++ using older c++ standard, whereas gcc uses c99?

**Comment by sturlamolden** [comment]
Well, I cannot replicate the build failure on my Mac, and I don't understand why ```npy_isinf``` fails only here.

The purpose of ```npy_isinf``` instead of ```isinf``` is to avoid a dependency on C99 or C++11. If there is a bug in the NumPy headers an issue should be filed upstream.

**Comment by sturlamolden** [comment]
The problem might be that "g++" on his Mac is actually an Apple hack where clang++ is using g++ 4.2.1 headers, and no g++ at all. And as clang++ defaults to C++11 but uses C++98 headers, it fails to build. The cure would be to use a real g++ (e.g. binaries from the gfortran wiki) or to do this:
```
$ export CC=clang
$ export CXX=clang++
```

**Comment by sturlamolden** [comment]
The comment in the code is wrong. NumPy is doing it correctly. A compiler that reports to use C++11 must define ```isinf``` in ```math.h```. It is not optional. It is not a bug in NumPy that Apple forgot to add ```-std=c++98``` to their g++ hack. The bug report should be filed to Apple.

**Comment by sturlamolden** [comment]
I think we can use @larsmans code, but the comment must be changed to properly place blame on who is to blame.

**Comment by sturlamolden** [comment]
On the other hand I am not sure if we should try to silcence a compiler bug, because it will show up whenever we use npy_math to avoid C++11 or C99.

**Comment by sturlamolden** [comment]
Another thing we can do is to add the appropriate compiler flags ourselves, because we know that C90 with GNU extensions [GNU extensions are actually used on OSX] and C++98 are the smallest common denominators on which SciPy should compile on OSX. We can just have setup.py add ```-std=gnu90``` to ```CFLAGS``` and ```std=gnu++98``` to ```CXXFLAGS``` when compiling on Mac.

**Comment by WarrenWeckesser** [comment]
For C and C++, I'm using the stock command line tools provided by Apple.

If this is, in fact, a compiler bug, I'd like to understand it better.  I can compile a C program that includes math.h and uses isinf, and I can compile a C++ program that includes cmath and uses std::isinf.  What would I need to do to demonstrate the "bug" in a simple C or C++ program?

**Comment by larsmans** [comment]
I changed the comment.

**Comment by WarrenWeckesser** [comment]
(I originally put this comment in the wrong issue...)

Here's a simple C++ program, `check_isinf.cxx`, that uses `std::isinf`:

```
#include <iostream>
#include <cmath>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << std::isinf(x) << std::endl;

    return 0;
}
```
I can compile it with no extra command line arguments:
```
$ g++ check_isinf.cxx -o check_isinf
$ ./check_isinf 
0
```
A similar C program that includes `math.h` also works fine.

@sturlamolden:  What would be a similarly simple C or C++ program that should demonstrate the "bug"?

**Comment by sturlamolden** [comment]
@WarrenWeckesser You need to test ```npy_isinf``` compiled with numpy.disutils.

**Comment by sturlamolden** [comment]
This is very strange.

@WarrenWeckesser Can you really use ```isinf``` in C++ (not std::isinf) but not use ```npy_isinf``` even though ```npy_isinf``` is defined as ```isinf``` in ```numpy/npy_math.h``` with your configuration?

**Comment by WarrenWeckesser** [comment]
I just tried using `isinf` instead of `std::isinf`, without `using namespace std;`, in a C++ program, and it also worked.  I don't know if that is expected or not (I was surprised, but I'm no C++ guru).

Here's the demo:
```
$ cat check_isinf.cxx
#include <iostream>
#include <cmath>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << isinf(x) << std::endl;

    return 0;
}
$ g++ check_isinf.cxx -o check_isinf
$ ./check_isinf 
0
```

**Comment by WarrenWeckesser** [comment]
Also, for what it's worth:

```
$ cat check_npy_isinf.cxx
#include <iostream>
#include <Python.h>
#include <numpy/npy_math.h>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << npy_isinf(x) << std::endl;

    return 0;
}
```
Compiling with the appropriate `-I` flags gives no errors:
``` 
$ gcc -c -I/Users/warren/anaconda/include/python2.7  -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include check_npy_isinf.cxx
$
```

**Comment by sturlamolden** [comment]
That is interesting. Now try to compile this:

```
$ cat check_npy_isinf.cxx
#include <iostream>
#include <Python.h>
#include <cmath>
#include <numpy/npy_math.h>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << npy_isinf(x) << std::endl;

    return 0;
}
```

If this fails to compile, the real culprit is a common macro guard in cmath and math.h.

**Comment by WarrenWeckesser** [comment]
@sturlamolden That code compiles with no errors.

**Comment by sturlamolden** [comment]
Good it should. Now remove Python.h and try again.

**Comment by sturlamolden** [comment]
What about this one?

```
#include <iostream>
#include <Python.h>
#include "numpy/arrayobject.h"
#include "numpy/npy_math.h"
#include <cmath>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << npy_isinf(x) << std::endl;

    return 0;
}
```

**Comment by WarrenWeckesser** [comment]
That doesn't work because `npy_math.h` requires definitions from `Python.h`:

```
$ cat check_npy_isinf_sturla.cxx 
#include <iostream>
//#include <Python.h>
#include <cmath>
#include <numpy/npy_math.h>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << npy_isinf(x) << std::endl;

    return 0;
}
$ g++ -c -I/Users/warren/anaconda/include/python2.7  -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include check_npy_isinf_sturla.cxx
In file included from check_npy_isinf_sturla.cxx:4:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:15:
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:164:9: error: unknown type name 'Py_intptr_t'
typedef Py_intptr_t npy_intp;
        ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:165:9: error: unknown type name 'Py_uintptr_t'; did you mean
      'uintptr_t'?
typedef Py_uintptr_t npy_uintp;
        ^~~~~~~~~~~~
        uintptr_t
/usr/include/sys/_types/_uintptr_t.h:30:24: note: 'uintptr_t' declared here
typedef unsigned long           uintptr_t;
                                ^
In file included from check_npy_isinf_sturla.cxx:4:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:15:
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:301:2: error: Must use Python with unicode enabled.
#error Must use Python with unicode enabled.
 ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:949:9: error: unknown type name 'npy_uint16'
typedef npy_uint16 npy_half;
        ^
In file included from check_npy_isinf_sturla.cxx:4:
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:26:19: error: unknown type name 'npy_uint32'
    const union { npy_uint32 __i; float __f;} __bint = {0x7f800000UL};
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:32:19: error: unknown type name 'npy_uint32'
    const union { npy_uint32 __i; float __f;} __bint = {0x7fc00000UL};
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:38:19: error: unknown type name 'npy_uint32'
    const union { npy_uint32 __i; float __f;} __bint = {0x00000000UL};
                  ^
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h:44:19: error: unknown type name 'npy_uint32'
    const union { npy_uint32 __i; float __f;} __bint = {0x80000000UL};
                  ^
8 errors generated.
$ 
```

**Comment by sturlamolden** [comment]
But what if we include arrayobject.h before npy_math.h?

**Comment by WarrenWeckesser** [comment]
> But what if we include arrayobject.h before npy_math.h?

Deprecation warning, but no errors:
```
$ cat check_npy_isinf_sturla2.cxx 
#include <iostream>
#include <Python.h>
#include "numpy/arrayobject.h"
#include "numpy/npy_math.h"
#include <cmath>

int main(int argc, char *argv[])
{
    double x = 1.0;

    std::cout << npy_isinf(x) << std::endl;

    return 0;
}
$ g++ -c -I/Users/warren/anaconda/include/python2.7  -I/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include check_npy_isinf_sturla2.cxx
In file included from check_npy_isinf_sturla2.cxx:3:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
In file included from /Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:
/Users/warren/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: 
      "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
1 warning generated.
$
```

**Comment by WarrenWeckesser** [comment]
I'll be away for a bit, but I can poke around some more this evening.

**Comment by sturlamolden** [comment]
I am not sure I understand what is going on. 

We have to be able to use npy_math in SciPy. Just writing around the build error is not enough.

This patch should in any case be pulled because it is needed for performance. We cannot have the distance function generate an excessive numbers of library calls.

**Comment by larsmans** [comment]
I'll merge it now as a stopgap measure.

**Pull request merged**
