### PR TITLE
DOC: Add example for special.bdtr

### PR DESCRIPTION
**Pull request by OmarManzoor**
#### Reference issue

Towards gh-7168

#### What does this implement/fix?

- Adds an example for the `bdtr` function in `scipy.special`.

### CODE REVIEW

**Comment by mdhaber** [comment]
The question makes sense. I have a few thoughts.

- I think this information should be in stats, and probably in a tutorial page about the binomial distribution. However, now is not a good time to begin adding it because there is major distribution infrastructure work and, separately, tutorial infrastructure work underway. It would need to be rewritten twice (when each of those improvements are added) if it were added now.
- I ambivalent about whether it should also be in special. I do think it would be helpful, but then there would be a lot of duplication between stats and special.
- There isn't much precedent for this sort of conceptual content about distributions in either stats or special. I don't think we should add it to just one special function or stats distribution without a commitment to adding it accross the board. I would not commit to that at this time.
- I'm beginning to lean toward short API reference examples that are just about the code and more realistic usage example in in an _notebook_ tutorial example linked from the API reference. There is infrastructure for this under development, but it's not in widespread use yet.

**Comment by OmarManzoor** [comment]
@mdhaber Thanks for the feedback. It is true that this might result in duplication because pretty much the same function might be used inside the actual distributions. I think we can close this PR. If I want to work on other examples I should chose ones that are not directly linked to a distribution because I think I saw two beta distribution functions as well in the list.

**Comment by j-bowhay** [comment]
@mdhaber I general I actually quite like the more detailed expositions however in this case I think this should be slimed down. I think it makes more sense for the detailed examples to live in stats and have brief examples in special. Otherwise I think it gets confusing about which set of functions the majority of people should be using. For example we could condense this example to something like:
```
    Given the probability of an event is 0.20 we can use the `bdtr` function to calculate the probabilty
    that this event occurs fewer that 5 times from 15 samples.
    >>> from scipy.special import bdtr
    >>> n = 15
    >>> p = 0.2
    >>> k = 4
    >>> bdtr(k, n, p)
    0.8357662760632321
```

**Comment by OmarManzoor** [comment]
> @mdhaber I general I actually quite like the more detailed expositions however in this case I think this should be slimed down. I think it makes more sense for the detailed examples to live in stats and have brief examples in special. Otherwise I think it gets confusing about which set of functions the majority of people should be using. For example we could condense this example to something like:
> 
> ```
>     Given the probability of an event is 0.20 we can use the `bdtr` function to calculate the probabilty
>     that this event occurs fewer that 5 times from 15 samples.
>     >>> from scipy.special import bdtr
>     >>> n = 15
>     >>> p = 0.2
>     >>> k = 4
>     >>> bdtr(k, n, p)
>     0.8357662760632321
> ```

I think this looks good.

**Comment by rlucas7** [comment]
@mdhaber Am I misremembering, wasn't the plan to swap out the ceph cdf special functions in favor of boost? (the `bdtr` would fit into that bucket). Did that plan change?

**Comment by WarrenWeckesser** [comment]
@rlucas7, the public API doesn't necessarily change when the implementation is changed to use boost.

**Comment by dschmitz89** [comment]
A few months back I started PR to add docs to more beta distribution related special functions: #17421 . As `bdtr` is deprecated in favor of `betainc` (see #17697) in the long run, that one was closed. The same applies to this PR: it probably does not make sense to invest much more time into documenting the `xxdtr` functions which will be replaced in the long run.

**Comment by dschmitz89** [comment]
@OmarManzoor : I am sorry, I mixed up `btdtr` and `bdtr`. `bdtr` is not at all deprecated, so your example is more than welcome :). Again, sorry for the confusion.

**Pull request closed without merging**
