### PR TITLE
Added many missing special functions to docs

### PR DESCRIPTION
**Pull request by aarchiba**
fixes bug #4782 (in the short term). Need some kind of test or auto-generation to avoid boilerplate bugs like this.

### CODE REVIEW

**Comment by ev-br** [comment]
re test: there's tools/refguide_check.py, does it do it?

**Comment by aarchiba** [comment]
There are a few false positives but it's a good start. Maybe with a __norefguide__ to list things that shouldn't be in the refguide the refguide_check could be made part of the test suite?

**Comment by argriffing** [comment]
`poch` has already been merged in https://github.com/scipy/scipy/pull/4728, but I agree that automation would be the way to go.

**Comment by aarchiba** [comment]
One option would be to automatically add all functions not already present in the refguide to an unsorted section at the end; the idea would be that this would get them documented as soon as they existed but hopefully embarrass authors into putting them somewhere topical.

Another option would be to put enough configurability into refguide_check.py that it would produce no false positives, then make it part of the test suite. This isn't as outrageous as "no false positives" makes it sound; anything marked as deprecated could automatically be ignored, and an alias decorator also wouldn't be hard to add. Might not even need a list of exceptions next to __all__.

**Comment by argriffing** [comment]
btw this PR needs some git attention before it can be merged

**Comment by rgommers** [comment]
``refguide_check.py`` doesn't belong in the test suite I think, but we could run it as a separate check on TravisCI. The same run as ``pep8`` and ``pyflakes`` should work.

**Comment by aarchiba** [comment]
Okay I have no idea how to make git happy with this. I updated my local repository, rebased, and tried to push the branch again; error about not being a fast-forward. I tried the recommended git pull, re-resolved the conflict, and pushed again; still apparently problems.

**Comment by charris** [comment]
@aarchiba I'm guessing that you have changed the history and need to force push:
```
git push -f origin HEAD
```

**Comment by charris** [comment]
Only using the shorthand `HEAD` when the branch is checked out.

**Comment by argriffing** [comment]
@aarchiba in https://github.com/scipy/scipy/pull/4294#issuecomment-67648414 I learned to be less squeamish about the git force flag.

**Comment by charris** [comment]
Looks like you also did a merge from master, which pulled in some extraneous stuff. Try `git rebase master` to see if that cleans it up any. You can also use `git rebase -i HEAD~<n>` to clean stuff up, I think you can undo merges with it among other things. All of those actions require a force push after.

**Comment by rgommers** [comment]
Merged, thanks @aarchiba

**Pull request merged**
