### PR TITLE
DOC: add a little note about the Normal survival function (Q-function)

### PR DESCRIPTION
**Pull request by mirca**
As prompted in the mailing list, I'm adding this note which hopefully will be helpful for anyone looking for an implementation of the Q-function.

Is this place ok or should this note go elsewhere (too)?

### CODE REVIEW

**Comment by ev-br** [comment]
The other way around: *"The survival function, ``norm.sf``, is also referred to as a Q-function in some contexts (see, e.g., [some reference])".*

Rationale: The term "Q-function" is ambiguous, http://mathworld.wolfram.com/Q-Function.html

**Comment by mirca** [comment]
@ev-br :+1:

**Comment by ev-br** [comment]
Could you squash the two commits please. `$ git rebase -i HEAD~2`, then change the second "pick" to "squash" and edit the commit message to start with "DOC".

**Comment by mirca** [comment]
@ev-br I'm not fluent in git, so I think I messed things up here, sorry.

**Comment by ev-br** [comment]
No problem, a first rebase is always a mess... Two issues here: do not go too far into the history (this picks up earlier commits which should not be here), and a merge -- better rebase, don't merge. To fix it up: `$git fetch upstream`, then `git rebase upstream/master`. Then `git rebase -i upstream/master`, and edit the commits. If in doubt, delete the hashes in the editor, this will abort the rebase, also `git rebase --abort`.

**Comment by ev-br** [comment]
@mirca Something like this:

```
$ git fetch upstream                # <<<<------
remote: Counting objects: 256, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 256 (delta 206), reused 187 (delta 187), pack-reused 20
Receiving objects: 100% (256/256), 230.70 KiB, done.
Resolving deltas: 100% (212/212), completed with 114 local objects.
From https://github.com/scipy/scipy
   94ee2c4..340ada7  master     -> upstream/master
 <... some more... stuff specific to my setup...>
$
$ git rebase upstream/master                           # <<<<<<---- 
First, rewinding head to replay your work on top of it...
Applying: add a little note about the Q-function
Applying: add a little note about the normal survival function
Applying: BUG: fix stats.ttest_ind_from_stats to handle arrays.
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: add a little note about the Q-function
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
$
$ # now git log only shows your two commits
$ 
$ git rebase -i HEAD~2       # <<<<<<-------
$  # .... edit the commit messages: pick --> squash etc
$ git push origin HEAD -f     # <<<<<<< -----   Note the -f switch
$
```

The result is the top commit at https://github.com/ev-br/scipy/commits/pr/5864 --- you can either take it over or repeat the steps above, whichever you prefer.

**Comment by mirca** [comment]
@ev-br I redo your steps, still no success. An empty vim window shows up after ``git rebase -i HEAD~2``. I think I messed up something in my first tentative for squashing. Anyways, how do I take that [top commit](https://github.com/ev-br/scipy/commits/pr/5864) over?

**Comment by ev-br** [comment]
FTR, the canonic way to grab somebody else's tree is https://github.com/scipy/scipy/pull/5859#issuecomment-186613589

In this case though, it's probably easier to merge this directly than to keep wrangling with git. 
Which I did: https://github.com/scipy/scipy/commit/426619468ee712bbeffdb20cb2baf570273f541c is the merge commit and https://github.com/scipy/scipy/commit/41054d1f12d09fae681fbe5de3c92ff617953508 lists the actual author for posterity. Thank you @mirca and keep them coming!

**Comment by mirca** [comment]
@ev-br Thanks!

**Pull request closed without merging**
