### PR TITLE
MAINT: multi backports for 1.2.0rc2

### PR DESCRIPTION
**Pull request by tylerjereddy**
* backports for `1.2.0rc2`: gh-9541, gh-9549,
gh-9550, gh-9561

* appropriate release note updates for the above
backports, and some release note updates from
the rc1 backports I missed

* increment rc version number and set as unreleased

### CODE REVIEW

**Comment by rgommers** [comment]
Merged, thanks @tylerjereddy 

In the future, better keep commits separate - 1 commit per backported PR is best usually.

**Comment by tylerjereddy** [comment]
That's a direct contradiction to [your advice](https://github.com/scipy/scipy/pull/9532#issuecomment-441402163) from 9 days ago when you indicated:

> Merged. For next backports I'd suggest to do multiple in a single PR, rather than all separate - easier on CI, and keeps the history cleaner.

Generally I would do one at a time, but I assumed that I would follow that recent request.

**Comment by rgommers** [comment]
It's not - a single PR, but separate commits. That just avoids the many merge commits

**Comment by tylerjereddy** [comment]
Ah ok. I thought I usually noticed separate PRs for individual backports on NumPy so maybe I get confused by that.

**Comment by rgommers** [comment]
That's because Chuck likes to backport PRs quickly after they get merged. I tend to avoid that for two reasons: it's more work than in one go, and if there's something wrong with a PR (not uncommon) it's now wrong in 2 branches. Or maybe it's lazyness :)

**Pull request merged**
