### PR TITLE
ENH: Port of most of the dd_real part of the qd high-precision package.

### PR DESCRIPTION
**Pull request by pvanmulbregt**
Some accuracy issues in special/cephes/kolmogorov.c require some
computations to be performed in enhanced precision.
This PR is a C port of most of the dd_real part of the C++ qd package.

### CODE REVIEW

**Comment by pv** [comment]
Most compilers can decide themselves whether static functions should be
inlined. So this can be simplified:

DD_INLINE -> "static"

Drop "DD_INLINE_IS_EXTERN" (always false) and "DD_TRY_INLINE".

Remove dd_idecls.h.

**Comment by pv** [comment]
The Appveyor failures seem to be something unrelated.

**Comment by pvanmulbregt** [comment]
1. Thanks on the inline.   It may introduce a lot of warnings about unused static functions in any file that includes it, which is one reason I'd ported the C++ inline functions into C inline functions.  But just making everything static in the header files will simplify the code.
2. I also didn't see any reason for the Appveyor failures.  If the `dd_real` code compiles and doesn't cause linkage failures, it shouldn't have any impact on runtime, as the `dd_real` code is not yet used with this PR.
3. Lack of `NAN` caused one change from the real C++ qd, in that some constants such as `DD_C_NAN`, can't always be constant.  `NPY_NAN` isn't a compile-time replacement for `NAN` in pre-C99 compilers.  For those compilers, `DD_C_NAN` became a macro.  OK?
4. Physical location inside `special/cephes` OK?  Or move into `special/c_misc`?  `double2.h` is currently included by `special/_round.h` and `special/c_misc/struve.c`; `dd_real` will be used be `special/cephes/kolmogorov.c`.  My presumption is that you'd like to see just one copy of double-double functionality, and the current use of `double2.h` should be replaced with `dd_real`.  Is that correct?

**Comment by person142** [comment]
> Physical location inside special/cephes OK? Or move into special/c_misc

Long term I'm hoping we can move the stuff in `c_misc` into `cephes`, so I vote for `special/cephes`.

> My presumption is that you'd like to see just one copy of double-double functionality, and the current use of double2.h should be replaced with dd_real

That sounds right. Maybe it should be done in this PR? Then we will also get some confirmation that everything is functioning correctly.

**Review by pv — APPROVED** [review]
By reading this, LGTM, although it's not possible to know if this is fully correct without test coverage.

Here's a commit that replaces the old double2_t with this one: https://github.com/pvanmulbregt/scipy/compare/doubledouble...pv:struve-ddouble

All tests seem to pass, and `_precompute/struve_convergence.py` retains the old convergence regions --- with the exception of a difference in overflow handling (nan vs inf) for the power series (doesn't matter for the actual function return value however), due to reasons we discussed earlier. This small difference shouldn't matter.

**Comment by pv** [comment]
Pushed commits updating license blurb + removing the old double2 code.

**Comment by pv** [comment]
Ok, thanks, merged.

**Pull request merged**
