### PR TITLE
MAINT: pchanial's improvement of input validation in sparse's __mul__

### PR DESCRIPTION
**Pull request by argriffing**
Retry of @pchanial's https://github.com/scipy/scipy/pull/4066, this time with tests and in its own PR branch.  Also changed `raise NotImplemented` to `raise NotImplementedError`.

### CODE REVIEW

**Comment by argriffing** [comment]
If I understand correctly, the decision holding up this PR is what to do when a sparse matrix is multiplied by a high-dimensional array.

The original behavior was
```python
raise ValueError('could not interpret dimensions')
```

@pchanial changed this to
```python
raise NotImplemented
```

which is a typo of some sort because `NotImplemented` is not a value that should be raised.  I interpreted this as
```python
raise NotImplementedError
```

@larsmans suggested a correction which I had overlooked:
> Shouldn't this return `NotImplemented` instead of raising an error? In any case, `NotImplementedError` is the wrong exception. That's for stub methods in class hierarchies indicating that a subclass should be used instead.

@pv was not so sure about this change:
> Not sure about returning `NotImplemented` here. AFAIK, it's supposed to be
returned if the *type* of the input argument is such that it cannot be
handled, and IIRC results to Python raising a `TypeError` later on. Here,
however, the type is handled, however partially...

Right now I guess I'm waiting for input on this decision, because I don't have much experience with the subtleties involved in convincing Python to dispatch binary operations of mixed types to the correct function.

**Comment by larsmans** [comment]
Regarding the `NotImplemented` issue: what if a subclass of `np.ndarray` has an overloaded `__mul__` that can multiply a sparse matrix both on the left and on the right, regardless of its own shape?

(This would make for an interesting unit test, too.)

**Comment by pchanial** [comment]
It is very important to return NotImplemented instead of raising an
exception:
in the operation A * B, if A.__mul__ returns NotImplemented, then it leaves
the possibility to call B.__rmul__.


2015-01-21 23:27 GMT+01:00 Lars <notifications@github.com>:

> Regarding the NotImplemented issue: what if a subclass of np.ndarray has
> an overloaded __mul__ that can multiply a sparse matrix both on the left
> and on the right, regardless of its own shape?
>
> (This would make for an interesting unit test, too.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/pull/4294#issuecomment-70934704>.
>



-- 
La propagande est à la démocratie ce que la violence est à la dictature.
Noam Chomsky

**Comment by argriffing** [comment]
>It is very important to return NotImplemented instead of raising an exception

So this PR is ready to be merged?

**Comment by pchanial** [comment]
If this is a question for me : yes, in the sense that the existing tests
succeed.

2015-01-22 0:39 GMT+01:00 argriffing <notifications@github.com>:

> It is very important to return NotImplemented instead of raising an
> exception
>
> So this PR is ready to be merged?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/pull/4294#issuecomment-70944785>.
>



-- 
La propagande est à la démocratie ce que la violence est à la dictature.
Noam Chomsky

**Comment by argriffing** [comment]
> Regarding the `NotImplemented` issue: what if a subclass of `np.ndarray` has an overloaded `__mul__` that can multiply a sparse matrix both on the left and on the right, regardless of its own shape?
(This would make for an interesting unit test, too.)

My current understanding is that @pchanial's original `return NotImplementedError` was just a typo and that `return NotImplemented` was intended (as you've corrected in an earlier comment).  Do you think more work should be added to this PR before merging?

**Comment by argriffing** [comment]
> If this is a question for me : yes, in the sense that the existing tests succeed.

Just to clarify, by this you mean the scipy TravisCI tests succeed, and you're not referring to other possible integration tests that might involve this PR like maybe PyOperators tests?

**Comment by argriffing** [comment]
> Regarding the NotImplemented issue: what if a subclass of np.ndarray has an overloaded __mul__ that can multiply a sparse matrix both on the left and on the right, regardless of its own shape?
(This would make for an interesting unit test, too.)

Maybe this was a rhetorical question, but I made a test for it:
```python
def test_matmat_object_two_sided_shape_independent_mul(self):
        # From a github comment:
        # "what if a subclass of np.ndarray has an overloaded __mul__
        # that can multiply a sparse matrix both on the left and on the right,
        # regardless of its own shape?"
        class OperatorStub(np.ndarray):
            def __rmul__(self, other):
                return other
            def __mul__(self, other):
                return other
            @property
            def A(self):
                return 42
        A = self.spmatrix(matrix([[3,0,0],[0,1,0],[2,0,3.0],[2,3,0]]))

        def array_mul(a, b):
            # for testing exceptions
            c = a * b
            print(type(a))
            print(type(b))
            print(type(c))
            print(c)
            print()
            return c.A

        B = OperatorStub((3, 3))
        assert_array_equal(array_mul(A, B), A.A)
        assert_array_equal(array_mul(B, A), A.A)

        B = OperatorStub((3, 4))
        assert_array_equal(array_mul(A, B), A.A)
        assert_raises(ValueError, array_mul, B, A)

        B = OperatorStub((4, 3))
        assert_array_equal(array_mul(B, A), A.A)
        assert_raises(ValueError, array_mul, A, B)

        B = OperatorStub((10, 20))
        assert_raises(ValueError, array_mul, A, B)
        assert_raises(ValueError, array_mul, B, A)
```

The outcome seems to be that a `np.ndarray` is produced so the test fails when it tries to get the `.A` property of a `np.ndarray`.  I assume this means that `np.asarray` has been called on a scipy sparse matrix, which is always or nearly always an error but which silently gives an almost certainly undesired output.

@larsmans, @pchanial do you guys have opinions about how to address this, or to ignore it?

**Comment by argriffing** [comment]
> Regarding the `NotImplemented` issue: what if a subclass of `np.ndarray` has an overloaded `__mul__` that can multiply a sparse matrix both on the left and on the right, regardless of its own shape?

I've looked at this again, and I agree that things seem to go badly.  Would handling this case be a requirement for merging this PR?

**Comment by rgommers** [comment]
This looks close to being ready, but not much progress recently and not required for 0.16.0, so removing the milestone.

**Comment by argriffing** [comment]
I'm not sure what progress would be needed.  Maybe close this PR and re-open the original one?  The discussion gives me the feeling that my earlier mis-correction of @pchanial's `raise NotImplemented` typo has somehow tainted this PR.

**Comment by argriffing** [comment]
closing https://mail.scipy.org/pipermail/numpy-discussion/2016-January/074810.html

**Pull request closed without merging**
