### PR TITLE
BLD/REL: on Windows use numpy 1.22.3 as the version to build wheels against

### LINKED ISSUE #16787: BUG: Can't build 1.10 with mingw-w64 toolchain and numpy 1.21.6 in Python 3.10
### Describe your issue.

When trying to meson build Scipy 1.10 on Windows AMD64 with Python 3.10 and the mingw-w64 toolchain the build process:

- installs numpy 1.21.6
- all pyd files that try to link against npymath have this error in the build log 
```
2022-08-05T10:44:53.8879877Z   [910/1556] Linking target scipy/stats/_biasedurn.cp310-win_amd64.pyd
2022-08-05T10:44:53.8880183Z   Warning: corrupt .drectve at end of def file
2022-08-05T10:44:53.8880459Z   Warning: corrupt .drectve at end of def file
```
- those pyd files aren't loadable/importable.

this is probably related to https://github.com/MacPython/numpy-wheels/issues/145, https://github.com/numpy/numpy/issues/20880, https://github.com/numpy/numpy/issues/21629

Those issues arise from numpy wheels using a more recent version of vc142, which mingw isn't interoperable with.

### Reproducing Code Example

```python
a
```

### Error message

```shell
2022-08-05T10:44:53.8879877Z   [910/1556] Linking target scipy/stats/_biasedurn.cp310-win_amd64.pyd
2022-08-05T10:44:53.8880183Z   Warning: corrupt .drectve at end of def file
2022-08-05T10:44:53.8880459Z   Warning: corrupt .drectve at end of def file
```
 The error experienced during loading the PYD is:
```shell
ImportError: DLL load failed while importing _biasedurn: %1 is not a valid Win32 application.
```

### SciPy/NumPy/Python version information

Python 3.10, numpy-1.21.6, scipy 1.10

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-16787

`[ci skip]`

_Please don't merge yet, I still need to test on the `oldest-supported-numpy` repo, which has CI for these conditions_

### CODE REVIEW

**Comment by andyfaff** [comment]
I'll try running  1.22.3 on the cibw branch

**Comment by andyfaff** [comment]
The cibuildwheel works for 0

**Comment by andyfaff** [comment]
Oops, accidentally closed on by fat fingers on my phone. 1.22.3 looks good for Python 3.10 on windows amd64

**Review by andyfaff — APPROVED** [review]

**Comment by rgommers** [comment]
I tested this now (and found a bug) - it should be good to go now. Also added Python 3.11 update now that numpy has 3.11 wheels on PyPI.

The second commit here needs backporting, the first one not.

**Comment by andyfaff** [comment]
Aargh, I think it needs to be 1.22.3 for win_amd64 as well, not just win32.

**Comment by rgommers** [comment]
No, `win32` is the specifier for both platforms. And yes, that can be problematic - but we should be fine here.

**Comment by andyfaff** [comment]
https://github.com/scipy/scipy/runs/7854253531?check_suite_focus=true shows that the win_amd64 DLL aren't importable on 3.10 with this version, 1.22.3 works.

**Comment by rgommers** [comment]
Hmm yes, that does still select: `Collecting numpy==1.21.6`. It looks like the specifier should/may be `'Windows'`, not `'win32'` (at least according to the test in `oldest-supported-numpy`). According to https://peps.python.org/pep-0345/#environment-markers it is `win32`, but the mistake in this PR is that it uses `platform_machine` rather than `platform_system`.

Maybe easier to iterate in your cibuildhweel PR, before trying here again? Can you try `platform_system=='win32'` or else platform_system=='Windows'`?

**Comment by andyfaff** [comment]
https://github.com/scipy/scipy/pull/16842/commits/c8047d926d9c819aae3734854ad7bdb8f2a830de#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R41

"numpy==1.22.3; python_version=='3.10' and platform_system=='Windows' and platform_python_implementation != 'PyPy'"

seems to work. i.e. `platform_system`

**Comment by rgommers** [comment]
This fix was included in the `cibuildwheel` PR (gh-16842)

**Pull request merged**
