### PR TITLE
DOC: show how to use solve_ivp with one arg

### PR DESCRIPTION
**Pull request by kozachynskyi**
#### Reference issue

Closes issue in stackoverflow https://stackoverflow.com/questions/53262552/cant-integrate-with-dblquad

#### What does this implement/fix?
Tell user, that if they have only one argument, they cannot simply use tuple. Because in python (a) != (a,)

### CODE REVIEW

**Comment by tupui** [comment]
Hi, thanks for contributing!

Sorry but this is out of scope as more of a Python syntax thing. The documentation is already stating that it needs a tuple so this does not add anything. At most we could add a validation of the parameter itself to check that it can be unpacked. But as is I would close this.

If you would like to propose a validation check instead, let me know. Otherwise, I will close.

**Comment by WarrenWeckesser** [comment]
@tupui, I understand your comment--this adds a hint about an elementary Python behavior.  However, I've seen enough people stumble over this in stackoverflow questions that my immediate response to the added line was "Yes, that will be helpful."   However (that's a level 2 "however"), if we include it here because it will help avoid a common mistake, we should include it in the docstrings of all the functions that accept an `args` argument like this.   I wouldn't be against that, but I'm not sure what other devs would think.

**Comment by ev-br** [comment]
ISTM, (1) this is a good change, this syntax often trips python beginners; (2) we can treat these comments piecemeal and add these comments when looking at code for some other reason.

**Comment by tupui** [comment]
I would prefer to have a better error message, so have this on the validation of the arguments side (as we now tend to validate all arguments). But if this is really a pain point, why not. We should decide on a concise message and do it at one for all occurrences.

**Comment by kozachynskyi** [comment]
I agree, that better error description is the way. No one reads docs anyway ) Here is my try (however I haven't done full tests, too much things to learn for me from your Contribution guide) #14142

**Comment by tupui** [comment]
Thanks @kozachynskyi but as I said in your new PR, we did not really decide yet on how we should proceed.

In such cases, we could probably just add `args = np.atleast_1d(args)`. What do you all think?

**Comment by mdhaber** [comment]
I don't see a problem with `np.atleast_1d`, @tupui.

**Comment by mdhaber** [comment]
But let's decide in a separate issue because there are tons of places where this is relevant.
The same could be said of gh-14142, but current practice (right or wrong) is for error handling to be handled ad hoc, so I think it's OK to do something while this bigger issue is being discussed.

**Comment by mdhaber** [comment]
Let's discuss in gh-15994. Thanks @kozachynskyi!

**Pull request closed without merging**
