### PR TITLE
ENH: scipy.special: Improving sph_harm function 

### PR DESCRIPTION
**Pull request by jennystone**
The sph_harm function used for calculating spherical harmonic at present is written in Python and it uses the routine lpmn to calculate the required Associated Legendre function. The routine lpmn iteratively evaluates the function for all values <= m,n every time it is passed, the value required by the sph_harm is just that of the function at m and n (and not at <m,n)
Therefore the routine is substituted by another similar existing routine lpmv, thus avoiding the unnecessary iterations and increasing the speed of the function.
Further the function is rewritten in Cython to increase the speed.

### CODE REVIEW

**Comment by scholich** [comment]
I have a related question on the docstring of [lpmv 0.14](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.lpmv.html#scipy.special.lpmv) as I am using scipy 0.14 but the docstring does not appear to have changed [lpmv 0.15.1](http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.lpmv.html). According to this the first argument is the order and the second the degree. When comparing to the definition used in [Wikipedia](http://en.wikipedia.org/wiki/Associated_Legendre_polynomials#The_first_few_associated_Legendre_functions) which employs the Condon-Shortley Phase I therfore expect `lpmv(1, -1, 0) = 0.5`.
When I test it, however, I see that the order must be reversed:

    from scipy import special as sp
    import scipy
    print scipy.__version__
    # prints 0.14.0
    print sp.lpmv(1, -1, 0)  # If docstring is true: should be 0.5
    # prints 0.0
    # reversing arguments gives correct result
    print sp.lpmv(-1, 1, 0)
    # prints 0.5

So I guess there is an error in the docstring. Can anyone confirm this?
Also, there is no error reported when the degree is out of bounds but zero is returned:

    print sp.lpmv(2, 1, 0)    
    # prints 0.0
    print sp.lpmv(1, 2, 0)
    # prints -0.0

**Comment by pv** [comment]
The first argument is the order, the second is the degree.
lpmv(0, n, x) are the legendre polynomials.

**Comment by scholich** [comment]
As I see it you should expect `lpmv(1, -1, x) = 0.5 * (1 - x) ** 0.5` (second in the list at wikipedia with the fourth substituted) which gives 0.5 for x=0. How do you arrive at your result?

**Comment by pv** [comment]
The superscript m in wikipedia is the *order*, the subscript l is the *degree*.
The second entry in the wikipedia table says `P^{-1}_1(x) = 0.5 * (1 - x) ** 0.5`

**Comment by scholich** [comment]
Ah, ok. So then the error is in the bounds, which lead to the confusion. 
The docstring says:

    Parameters:	
    m : int
        Order
    v : real
        Degree. Must be v>-m-1 or v<m

but should probably read

    Parameters:	
    m : int
        Order. Must be m>-v-1 or m<v
    v : real
        Degree.

**Comment by pv** [comment]
Please file a separate issue for that

**Pull request closed without merging**
