### PR TITLE
DOC: Add example to scipy.signal.hilbert

### PR DESCRIPTION
**Pull request by FRidh**
Add example showing how to determine the amplitude envelope and
instantaneous frequency of a signal.

### CODE REVIEW

**Comment by FRidh** [comment]
Travis build failed because it stalled.

**Comment by ewmoore** [comment]
Thats okay; this is a documentation only change.

**Comment by ewmoore** [comment]
I think adding an example like this is a fine plan.  I think the example could be better.  For instance, the `frequency_modulation` variable is confusing since there is no frequency modulation in the waveform you create.  The dips in the plot frequency vs. time are not due to frequency modulation, but due to the amplitude dropping to zero at those points.

I think that using a wave with moderate-depth, non sinusoidal amplitude modulation and some moderate frequency modulation would make a better example.   

It may also be worth noting that when dealing with real signals, np.diff is probably not what you want.

**Comment by FRidh** [comment]
Thanks for the feedback.

It is indeed only amplitude-modulation, the name `frequency_modulation` is
confusing. Perhaps `frequency_of_modulation` would have been better. I've
changed the example, which is now an amplitude-modulated chirp.

**Comment by ewmoore** [comment]
LGTM.  I canceled the CI run, since this is documentation only.

**Comment by ewmoore** [comment]
Thanks!

**Pull request merged**
