### PR TITLE
ENH: Added wrappers for LAPACK <s,d>stev

### LINKED ISSUE #6149: How can I call lapack routine dstev from scipy
In Scipy, I can directly access lapack routines, like `zheev`, with `scipy.linalg.lapack.zheev`. But it seems not working with some lapack routines like [dstev](http://www.netlib.org/lapack/explore-html/d7/d48/dstev_8f.html), which is used to diagonalize real, symmetric tridiagonal matrix.

Any comment is appreciated.

### PR DESCRIPTION
**Pull request by ilayn**
Closes #6149

I was just passing by the open linalg issues and this is easy enough to fix.

### CODE REVIEW

**Comment by ilayn** [comment]
Apparently sporadic threadsafe stuff happened again... Do you mind restarting the test?

**Comment by ev-br** [comment]
restarted

**Comment by ilayn** [comment]
Is that an OSX run denoted as `no language set`? all green but I'm just curious.

**Comment by andyfaff** [comment]
> Is that an OSX run denoted as no language set? all green but I'm just curious.

Yes. For travis OSX tests you have to do [this](https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages))

**Pull request merged**
