### PR TITLE
MAINT: spatial: reimplement distance_wrap in Cython

### PR DESCRIPTION
**Pull request by larsmans**
Just a straight translation for now, but if someone wants to do memoryviews in spatial.distance, they get a head start.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Looks good to me, especially the net change of -773 LOC. We should probably add a benchmark to https://github.com/scipy/scipy/blob/master/benchmarks/benchmarks/spatial.py to make sure we avoid any performance regressions here.

**Comment by larsmans** [comment]
Yeah, I haven't benchmarked anything yet.

**Comment by tylerjereddy** [comment]
@perimosocordiae Is it still true that the corresponding `asv` benchmarks are missing? I think `cdist` is covered now, but maybe not `pdist` yet. So, we need to add the latter to accompany the work here? That should be low-hanging fruit if true (I can probably do it).

**Comment by perimosocordiae** [comment]
Looks like they were added by gh-6702. I think the `cdist` benchmarks we have now are probably good enough to see the impact of this PR, but I certainly wouldn't argue about adding similar benchmarks for `pdist`.

For this PR, we just need to rebase and run the existing asv benches.

**Comment by rgommers** [comment]
This PR has been superceded by gh-13907, which rewrites the pdist/cdist infrastructure in C++. So I'll close this. Thanks for all the effort you put into this @larsmans.

**Pull request closed without merging**
