### PR TITLE
Fix #3258 (Frechet distributions are incorrect)

### LINKED ISSUE #3258: Frechet distributions incorrect
The documentation and code in scipy.stats.distributions claims the following  equivalencies:

```
 weibull_max == frechet_l
 weibull_min == frechet_r
```

But this is a mistake, and in fact the Frechet distributions are incorrectly specified.

To see the problem, consider the cdf, and compare with http://en.wikipedia.org/wiki/Fr%C3%A9chet_distribution. (Note that the wikipedia version is consistent with, e.g., Johnson & Kotz) 

```
frechet_r: 1-exp(-x**c)
wiki:  exp(-x**(-c))
```

The distribution frechet_l is  a reversed version of the incorrect frechet_r, and so is also incorrect.

However, the weibull_min and weibull_max distributions version are correct, save for their documentation which incorrectly relates them to the Frechet distributions.

I have need of a correct frechet distribution and have written the corresponding code, though I'm not very interested in supplying different _r and _l versions (the version with support on R+ is the standard one).  

-Ethan Ligon

### PR DESCRIPTION
**Pull request by ligon**
I've made changes to correct problems with a number of related distributions in `stats._continuous_distributions`; discussed in #3258.
- Renamed `frechet_l` to `weibull_max`;
- Renamed `frechet_r` to `weibull_min`;
- Wrote new `frechet` (differs from both `frechet_l` and `frechet_r`);
- Reinstantiated new `frechet_l` and `frechet_r` as deprecated versions of `weibull_max` and `weibull_min`;
- Made suitable changes to documentation.

### CODE REVIEW

**Comment by johannes-mueller** [comment]
Any news on this?

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/issues/3276 seems to indicate that the original author is unlikely to pick it up. Any takers?

**Comment by WarrenWeckesser** [comment]
I'll work on getting this done for 0.19.

**Comment by WarrenWeckesser** [comment]
It looks like the last commit in this PR changes the sign of the `c` parameter in `genextreme`.
The docstring for `genextreme` explains that it uses a sign convention for the shape parameter that is the opposite of what appears to be more common.  So the sign convention might be unfortunate, but we can't change it now, because that would break backwards compatibility.

We could introduce a new distribution, say `genextremeval`, that is identical to `genextreme` except that it uses the more common convention for the sign of the shape parameter.  `genextreme` could then be deprecated in favor of the new distribution.

**Comment by WarrenWeckesser** [comment]
I don't think I have enough git-fu (or patience) to get this PR cleaned up and up-to-date with master while preserving @ligon's commits.  I'll try, but I might end up with a new PR written from scratch.

**Comment by josef-pkt** [comment]
I have no opinion about whether changing the sign of a parameter is worth a deprecation detour.
IIRC, I got confused also across articles or books or distributions about signs in extreme value theory.
`genextremeval` looks difficult to read without space between words, what `eval`?

**Comment by WarrenWeckesser** [comment]
> `genextremeval` looks difficult to read without space between words...

I agree.  If we were to go with this idea, I would be fine with `gen_extreme_val`, but some folks balk at more than one underscore.  But since we're using underscores, how about `gen_extreme`?  Whatever, this is premature bikeshedding.  The more fundamental question is whether or not to "fix" the reversed sign convention, and if so, how to do it in a way that preserves backwards compatibility.

**Comment by ev-br** [comment]
Warren, do you still want it to make it to 0.19.0?

**Comment by WarrenWeckesser** [comment]
I'm working on it today.

**Comment by WarrenWeckesser** [comment]
>  I'm working on it today.

... but it looks like I won't get this done in time for 0.19.

**Comment by rgommers** [comment]
The rename of ``frechet_r``/``frechet_l`` to ``weibull_min``/``weibull_max`` was done in gh-7838. The rest of this PR was updated in gh-7190 already. This PR isn't going to be worked on anymore, so closing. Thanks @ligon, all!

**Pull request closed without merging**
