### PR TITLE
BLD: fix issue in linalg ``*lange`` wrappers for g77 builds.

### PR DESCRIPTION
**Pull request by rgommers**
Fixes the first issue identified in gh-4829.

### CODE REVIEW

**Comment by pv** [comment]
Oh, the code was in a pyf file, not just in a fortran file. I don't think the fix is correct in this case: f2py needs to know the size of the array, in order to allocate it.

It might work if you declare a new `integer, intent(hide) k = MAX(1,m)`, and then `<ftype2> dimension(*)`; probably `k` needs to be added to the f2py argument list.

**Comment by rgommers** [comment]
@pv I've tried a number of variations of what you suggest, for example:

    @@ -2764,15 +2764,16 @@ function <prefix2>lange(norm,m,n,a,lda,work) result(n2)
         ! element of largest absolute value of a real matrix A.
         <ftype2> <prefix2>lange, n2
         fortranname <wrap2>lange
    -    callstatement (*f2py_func)(&<prefix2>lange,norm,&m,&n,a,&m,work)
    -    callprotoargument <ctype2>*,char*,int*,int*,<ctype2>*,int*,<ctype2>*
    +    callstatement (*f2py_func)(&<prefix2>lange,norm,&m,&n,a,&m,work,k)   # tried with and without these
    +    callprotoargument <ctype2>*,char*,int*,int*,<ctype2>*,int*,<ctype2>*,int*
     
         character intent(in),check(*norm=='M'||*norm=='m'||*norm=='1'||*norm=='O'||*norm=='o'||*norm=='I'||
         integer intent(hide),depend(a,n) :: m = shape(a,0)
         integer intent(hide),depend(a) :: lda = shape(a,0)
         integer intent(hide),depend(a) :: n = shape(a,1)
         <ftype2> dimension(m,n),intent(in) :: a
    -    <ftype2> dimension(MAX(m,1)),intent(cache,hide) :: work
    +    integer intent(aux),depend(m) :: k = MAX(m,1)
    +    <ftype2> dimension(*), intent(cache,hide) :: work   # also tried to add depend(k)
     end function <prefix2>lange

I can't make any of them work even on Linux though - I either get compile errors or test errors like:

    ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (-1,)

By looking at the generated wrapper I kind of see what the ``callstatement`` and ``intent`` do, but no matter what I do, the ``k = MAX(m,1)`` expression never appears in the generated ``_flapack-f2pywrappers.f``.

Generated code looks like:

     21       subroutine f2pywrapslange (slangef2pywrap, norm, m, n, a, ld
     22      &a, work)
     23       external wslange
     24       integer m
     25       integer n
     26       integer lda
     27       character norm
     28       real a(m,n)
     29       real work(*)
     30       real slangef2pywrap, wslange
     31       slangef2pywrap = wslange(norm, m, n, a, lda, work)
     32       end

**Comment by rgommers** [comment]
Okay, starting to see what goes into ``_flapackmodule.c``. At least getting the right expressions there now, just in the wrong order:

    41621 /*frompyobj*/
    41622   /* Processing auxiliary variable k */
    41623   k = MAX(m,1);
    41641   /* Processing variable n */
    41642   n = shape(a,1);
    41643   /* Processing variable m */
    41644   m = shape(a,0);
    41645   /* Processing variable work */
    41646   work_Dims[0]=k;

guess that's what the ``depend`` is for

**Comment by pv** [comment]
The MAX(k,1) expression should not appear in the generated fortran file.
It however must appear in the generated C file which does the memory
allocation.

**Comment by pv** [comment]
Looks like f2py bugs then, what I suggested doesn't seem doable. The
stuff inside dimension(...) seems to be pasted verbatim both to C and
fortran.
.
Maybe best to settle dimension(m+1) or just go with dimension(m) --- it
cause an exception to be raised on 0-dim arrays, but probably nobody
cares about that.

**Comment by rgommers** [comment]
``m+1`` should be a bit safer then right, and not cost significant performance?

**Comment by rgommers** [comment]
Okay, done. ``m+1`` works on Linux and doesn't make ``g77`` angry.

**Comment by pv** [comment]
`m` is should also be safe --- I don't think it will crash, but just
reject 0-sized dimensions.

**Comment by rgommers** [comment]
@pv true. so doesn't matter really then. Sounds like you don't have a preference, so leave this as is?

**Comment by rgommers** [comment]
Need this in for 0.16.x, so merging.

**Comment by rgommers** [comment]
Thanks for the pointers @pv

**Pull request merged**
