### PR TITLE
DEP: special: remove legacy kwarg from special.comb and switch to kwarg-only

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

#15765
towards https://github.com/scipy/scipy/issues/15722

#### What does this implement/fix?

scheduled for this release

### CODE REVIEW

**Review by lucascolley — COMMENTED** [review]
LGTM, thanks Jake! Just to check, @h-vetinari suggested deprecating non-integer input with `exact=True` in the linked issue - are we fine to raise an error here?

**Comment by j-bowhay** [comment]
> LGTM, thanks Jake! Just to check, @h-vetinari suggested deprecating non-integer input with `exact=True` in the linked issue - are we fine to raise an error here?

Yes, looking again I have been a bit over-eager here!

**Comment by lucascolley** [comment]
Are you wanting to leave the new deprecation for a separate PR?

**Comment by j-bowhay** [comment]
> Are you wanting to leave the new deprecation for a separate PR?

Yes I think so let's leave the issue open with a note about what's left

**Review by lucascolley — APPROVED** [review]
LGTM, thanks Jake!

**Pull request merged**
