### PR TITLE
DEV: use Meson for doc CI

### PR DESCRIPTION
**Pull request by tupui**
Supersede part of https://github.com/scipy/scipy/pull/13917

* Use Meson as build system for doc/bench
* Add ccache for build caching

### CODE REVIEW

**Comment by tupui** [comment]
Oh! I found the issue with the benchmarks, it's because `asv dev` is using `--quick` which is not in the `dev.py`. For now I will not use `dev.py`.

**Comment by tupui** [comment]
Ok even using the debug version did not do anything.

**Comment by tupui** [comment]
@rgommers seems like it's not just interpolator which is very slow, looking at benchs needing seconds, lot of things from linalg are also taking too much time.

Ex.
```
# this PR

[ 11.79%] ··· ...ench.time_det ok
[ 11.79%] ··· ====== ============ ======== ==========
               size   contiguous   module            
              ------ ------------ -------- ----------
                20      contig     numpy    1.64±0ms 
                20      contig     scipy    121±0ms  
                20      nocont     numpy    298±0μs  
                20      nocont     scipy    186±0ms  
               100      contig     numpy    3.74±0s  
               100      contig     scipy    1.54±0s  
               100      nocont     numpy    4.24±0s  
               100      nocont     scipy    1.45±0s  
               500      contig     numpy      n/a    
               500      contig     scipy    16.3±0s  
               500      nocont     numpy      n/a    
               500      nocont     scipy    18.3±0s  
               1000     contig     numpy      n/a    
               1000     contig     scipy    26.3±0s  
               1000     nocont     numpy      n/a    
               1000     nocont     scipy    27.6±0s  
              ====== ============ ======== ==========

# another job

[ 11.79%] ··· ...ench.time_det ok
[ 11.79%] ··· ====== ============ ======== ==========
               size   contiguous   module            
              ------ ------------ -------- ----------
                20      contig     numpy    307±0μs  
                20      contig     scipy    517±0μs  
                20      nocont     numpy    293±0μs  
                20      nocont     scipy    497±0μs  
               100      contig     numpy    4.72±0s  
               100      contig     scipy    742±0μs  
               100      nocont     numpy    6.59±0s  
               100      nocont     scipy    766±0μs  
               500      contig     numpy      n/a    
               500      contig     scipy    11.4±0ms 
               500      nocont     numpy      n/a    
               500      nocont     scipy    14.1±0ms 
               1000     contig     numpy      n/a    
               1000     contig     scipy    86.9±0ms 
               1000     nocont     numpy      n/a    
               1000     nocont     scipy    72.5±0ms 
              ====== ============ ======== ==========
```

**Comment by rgommers** [comment]
That makes very little sense to me. That's an order of magnitude slower than what I see locally:
```
[100.00%] ··· linalg.Bench.time_det                                                      ok
[100.00%] ··· ====== ============ ============= =============
              --                             module          
              ------------------- ---------------------------
               size   contiguous      numpy         scipy    
              ====== ============ ============= =============
                20      contig     6.13±0.06μs   9.85±0.04μs 
                20      nocont     6.22±0.09μs    10.6±0.2μs 
               100      contig       133±1μs      67.4±0.6μs 
               100      nocont       130±1μs      71.2±0.6μs 
               500      contig         n/a       3.02±0.04ms 
               500      nocont         n/a       2.90±0.08ms 
               1000     contig         n/a        16.8±0.4ms 
               1000     nocont         n/a        17.1±0.5ms 
              ====== ============ ============= =============
```

OpenBLAS is getting installed and used in the build on CircleCI. It's a 2 year old version of OpenBLAS (`0.3.8`), but that should be recent enough I'd think. Although we do want a more recent version anyway to avoid some bugs.

I can't think of good suggestions for where to look next.

**Comment by tupui** [comment]
Maybe something related to the infrastructure then. What about if I moved this job to GH actions?

**Comment by larsoner** [comment]
Yes browsing artifacts is easiest with CircleCI.

We could try using a machine executor rather than docker to see if it helps with speed: https://circleci.com/docs/2.0/executor-types/#using-machine , e.g.:
```
jobs:
  build:
    machine:
      image: ubuntu-2004:current
```
Also setting the OPENBLAS_NUM_THREADS=1 in the env might help (if it's not using `runtests.py`, which I think might already do this?).

**Comment by rgommers** [comment]
> Also setting the OPENBLAS_NUM_THREADS=1 in the env might help

Ah that could be it, good catch. Consistently installing `threadpoolctl` as a test dependency is the other way to manage this.

**Comment by tupui** [comment]
oh! So just installing `threadpoolctl` is enough or I need to set the env variable as well?

**Comment by rgommers** [comment]
> oh! So just installing `threadpoolctl` is enough or I need to set the env variable as well?

That should be enough, see `scipy/conftest.py`. Hardcoding the env var can be done in CI jobs because we never get more than 2 vCPU's per job, but doing it in `runtests.py`/`dev.py` is not great because it limits the performance for local development for no good reason.

**Comment by larsoner** [comment]
Is `conftest.py` used when running asv, though?

**Comment by rgommers** [comment]
> Is `conftest.py` used when running asv, though?

You ask a lot of good questions:) ... no it isn't

**Comment by tupui** [comment]
> > Is `conftest.py` used when running asv, though?
> 
> You ask a lot of good questions:) ... no it isn't

Also only OMP_NUM_THREADS is set there not OPENBLAS_NUM_THREADS. If that makes a difference.

I added OPENBLAS_NUM_THREADS=1 in the CI job. Let's see 🤞

**Comment by tupui** [comment]
Oh victory! Thank you both for helping!

Since this is working now, I propose to move to use `dev.py` (will just revert another commit). And I will change the name of the cache to invalidate it and have something green here.

**Comment by larsoner** [comment]
CircleCI doc build is red

**Comment by tupui** [comment]
> CircleCI doc build is red

Yes, just fixed it. At some point we fixed `dev.py` to set the PYTHONPATH for the `--doc`, but another update moved this down in `dev.py` so it's again not working. I put again PYTHONPATH then on this part.

**Comment by larsoner** [comment]
Looks like it has ran for ~42 minutes, only made it to `42.52%] ··· Running (stats.BinnedStatisticDD...`. Looking at this list, none take longer than 41:

https://app.circleci.com/pipelines/github/scipy/scipy?branch=main&filter=all

I'm not sure why this PR would be so much worse :(

It probably won't make a ~20 minute difference, but could you try the machine executor config I mentioned above? https://github.com/scipy/scipy/pull/15686#issuecomment-1072490880

**Comment by tupui** [comment]
> Looks like it has ran for ~42 minutes, only made it to `42.52%] ··· Running (stats.BinnedStatisticDD...`. Looking at this list, none take longer than 41:
> 
> [app.circleci.com/pipelines/github/scipy/scipy?branch=main&filter=all](https://app.circleci.com/pipelines/github/scipy/scipy?branch=main&filter=all)
> 
> I'm not sure why this PR would be so much worse :(
> 
> It probably won't make a ~20 minute difference, 

From what I see in other runs, the count goes to 50% (ex [here](https://app.circleci.com/pipelines/github/scipy/scipy/12022/workflows/8c863564-8da9-4630-bda0-dffca4b891fc/jobs/44896)) and then it's another step which finishes the job. Here the output is a bit different so I thought it might just print everything and the reason of the failure. So I wanted to try to increase the output timeout.

It does seem to take too long as the job which went through above was over under 20 minutes. But now the difference is between calling with dev.py or directly asv.

> but could you try the machine executor config I mentioned above? [#15686 (comment)](https://github.com/scipy/scipy/pull/15686#issuecomment-1072490880)

It should not be necessary now, above I have a run which ran just fine but was just not using `dev.py`.

**Comment by tupui** [comment]
Ok yes we have a difference in the arguments of asv. We need `--quick`. I thought I checked it correctly last time, must have missed something or it changed, I don't remember now. Anyway, either way I revert to use plain asv (will do this now, changing dev can be done after since we are in a rewrite there too) or we fix this in dev.py.

**Comment by larsoner** [comment]
> It should not be necessary now, above I have a run which ran just fine but was just not using dev.py.

Yes but in principle I think it should still be better/faster, so might as well add it here if possible!

**Comment by larsoner** [comment]
... but I guess we could do it in another PR if you want to stop working on this :)

**Comment by tupui** [comment]
> Yes but in principle I think it should still be better/faster, so might as well add it here if possible!

Ah ok sure then!

> ... but I guess we could do it in another PR if you want to stop working on this :)

Haha I am, but I am also very stubborn so I don't mind continuing 😅 I will do this tmr then.

**Comment by larsoner** [comment]
Not sure if it will help, but this is how I ended up making an env using a `cimg` docker image (should be similar to the machine image)

https://github.com/mne-tools/mne-python/blob/72841b35551bf85d332468b486a496c97f0fc2a9/.circleci/config.yml#L114-L117

**Comment by tupui** [comment]
> Not sure if it will help, but this is how I ended up making an env using a `cimg` docker image (should be similar to the machine image)
> 
> [mne-tools/mne-python@`72841b3`/.circleci/config.yml#L114-L117](https://github.com/mne-tools/mne-python/blob/72841b35551bf85d332468b486a496c97f0fc2a9/.circleci/config.yml#L114-L117)

I will have a look, thank you. I was about to explicitly call `python3.8, python3.8 -m pip` now.

**Comment by tupui** [comment]
> Not sure if it will help, but this is how I ended up making an env using a `cimg` docker image (should be similar to the machine image)
> 
> [mne-tools/mne-python@`72841b3`/.circleci/config.yml#L114-L117](https://github.com/mne-tools/mne-python/blob/72841b35551bf85d332468b486a496c97f0fc2a9/.circleci/config.yml#L114-L117)

@larsoner I tried to do this (changes here but I also connected with SSH to the node and exported PATH and made a symlink as you did) but Meson does not like it:

```
scipy/meson.build:48:0: ERROR: Tried to form an absolute path to a source dir.
You should not do that but use relative paths instead.

To get include path to any directory relative to the current dir do

incdir = include_directories(dirname)

After this incdir will contain both the current source dir as well as the
corresponding build dir. It can then be used in any subdirectory and
Meson will take care of all the busywork to make paths work.

Dirname can even be '.' to mark the current directory. Though you should
remember that the current source and build directories are always
put in the include directories by default so you only need to do
include_directories('.') if you intend to use the result in a
different subdirectory.
```

I will revert the use of a venv and try again without. At least it was compiling but not finding SciPy right after. I will see if I find something if I SSH after the build. Otherwise I will revert the change to machine.

**Comment by tupui** [comment]
@larsoner I did not manage to use the machine executor. I never used pyenv and installing another python is very slow with that. And even after that, I still got issues.

So I propose to leave this for later (and someone who knows better what to do maybe 😅)

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge

**Comment by larsoner** [comment]
Okay nobody else objects and this seems to be working well so let's get it in. Thanks @tupui !

**Pull request merged**
