### PR TITLE
Refractor

### PR DESCRIPTION
**Pull request by JonanOribe**
Refractor made on 3 files. There were several repeated values that could be easily converted to constants

### CODE REVIEW

**Comment by tupui** [comment]
Hi, thanks for contributing to SciPy.

We usually discourage very small fixes like these as explained in our contributing documentation: https://scipy.github.io/devdocs/dev/hacking.html#maintaining-existing-code
The reasoning behind it being that every contribution needs to be reviewed and incur maintainers (we are all volunteers) time and effort.

Could you maybe find more things like these to have something more substantial to contribute here?

**Comment by JonanOribe** [comment]
Ok @tupui , no problem. I saw a lot of things that can be refractorized. So I will prepare a bunch of small fixes all in one.

**Comment by mdhaber** [comment]
@JonanOribe the idea is that refactorizing code in a way that does not improve performance is typically undesirable. We do want to improve the style of the code base over time, but changes like this would need to be accompanied by some that e.g. fix a bug, improve accuracy, or make things measurably faster in the code being changed.

**Comment by rgommers** [comment]
Indeed, what @tupui and @mdhaber said. Thanks for contributing though @JonanOribe. We'd love to get actual bug fixes or performance or feature enhancements.

Given that we prefer not to have such refactoring PRs, as explained in the note that @tupui linked to, I will close this PR. Please do open new PRs though if you can @JonanOribe.

**Pull request closed without merging**
