### PR TITLE
DOC: document the changes of the sparse.linalg.svds (optional returns)

### PR DESCRIPTION
**Pull request by ev-br**
This is a doc-only follow-up to https://github.com/scipy/scipy/pull/4504#issuecomment-75769576
attempting to better document the changes to `sparse.linalg.svds`.

[ci skip]

### CODE REVIEW

**Comment by ev-br** [comment]
@ewmoore @argriffing how does this wording look?

**Comment by argriffing** [comment]
I'm curious about the cases where the argument is something like `False` or if the presence of `None` in the return values is affected by the fatness vs. tallness of the matrix.  I just finished saying something wrong in an earlier github comment so I'm holding back on speculation without running code...

**Comment by ewmoore** [comment]
Looks fine to me.

**Comment by ewmoore** [comment]
There have been no more comments, so merging.

**Pull request merged**
