### PR TITLE
MAINT: integrate._tanhsinh: improvements after further testing 

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-18650

#### What does this implement/fix?
- `_tanhsinh` would perform a full iteration even if NaNs were present in the limits of integration or the function evaluated at the midpoint of the limits of integration. d93ee4f9aef01615dd167e50b42f4595ca6c3597 fixes that.
- `_tanhsinh` generated a `ComplexWarning` if the first integral evaluated had a complex result type and subsequent integrals were real. (This was caused by complex abscissae and weights being cached and converted to reals.) 81874e12297717834320d206a956769db1d986d4 fixes that.
- `_tansinh` previously used `rtol=1e-12` regardless of dtype, but this is unrealistic for lower-precision float types. 84a0cbaf47196440f6f29067e411bdf78284299f makes the `rtol` depend on the dtype.
- `_tanhsinh` produced an error with size-0 input. 33dc64450ab5f71de24084f1ce9e830563d543e0 fixes that.
- During review, it was suggested that "fixed-precision" in the docsstring should be "finite-precision". d36b27eff0bb45b4e74177713cd04b59fa81b5e5 fixes that.

### CODE REVIEW

**Review by steppi — APPROVED** [review]
All of the fixes look good to me. I think this is ready to merge.

**Comment by mdhaber** [comment]
Me too! Thanks for taking a look.

**Comment by mdhaber** [comment]
Oops looks like there were runtime warnings on one platform.

**Comment by steppi** [comment]
> Oops looks like there were runtime warnings on one platform.

ah, right. i've gotten used to CI always having something broken and glossed over that that was relevant

**Comment by mdhaber** [comment]
Yes, me too. 
I think this will do the trick.

**Comment by mdhaber** [comment]
@steppi Looks like the failure is unrelated this time.

**Pull request merged**
