### PR TITLE
API: Changes to least_squares API

### PR DESCRIPTION
**Pull request by nmayorov**
The two changes were discussed in #5696

When ready to merge, I'll send updated ipython notebooks for tutorial to https://github.com/pv/SciPy-CookBook

@ev-br @anntzer

### CODE REVIEW

**Comment by rgommers** [comment]
This still needs to go into 0.17.0 right?

**Comment by nmayorov** [comment]
@rgommers I believe that is how Evgeni planed it.

**Comment by rgommers** [comment]
ok thanks, just wanted to make sure. This change looks fine to me.

**Comment by ev-br** [comment]
Indeed, this is 0.17 material. LGTM too. Thanks Nikolay, Ralf, @anntzer

**Comment by nmayorov** [comment]
OK, starting to tweaking tutorial examples.

**Comment by ev-br** [comment]
Backported in b17a59d3462c0ff1dc4270736f993baa7a505d48 and f232df17178d63efd1157ab2ee496083b0f19b88.

**Comment by anntzer** [comment]
Sorry for dropping the ball on that part, and thanks for taking my suggestions into account!

**Comment by nmayorov** [comment]
Perhaps the parameters can be ordered in a more logical / convenient way? @anntzer do you have any proposal to reorder them?

**Comment by anntzer** [comment]
If it was only up to me I would make everything except `fun` and `x0` keyword-only (side-stepping the issue) but this is too much pointless code in Python2 to make it worth it IMO.
Otherwise, I'd look at `leastsq`/`minimize`/`minimize_scalar` to get some inspiration there (and see that they're a mess).  The only thing that may matter (as in, the only args that I may think I'd even pass positionally rather than by keyword) are `args` and `kwargs`, which I'd put right after `x0`.

**Comment by nmayorov** [comment]
@anntzer I conclude that it's fine to keep the order as it is.

Another (rather stupid) issue: setting the default tolerances to eps**0.5 wasn't perhaps too wise, because it generates annoyingly many digits in documentation and hides the actual value in parameter's description.

@ev-br is it possible to change the default to `1e-8` now? Is it worth it?

**Comment by anntzer** [comment]
You could use something like
```
class _namedfloat(float):
    def __new__(cls, value, name):
        self = super().__new__(cls, value)
        self._name = name
        return self

    def __repr__(self):
        return "<{}>".format(self._name)
```
and `_namedfloat(EPS ** .5, "sqrt(eps)")` as a default.  Then the doc would look much better (at least pydoc, but I guess the generated HTML would also be improved).

**Comment by nmayorov** [comment]
@anntzer thanks for this suggestion, but it becomes unclear what is the actual value. Probably easier to change it.

@ev-br, again asking for your maintenance / release expertise.

**Comment by ev-br** [comment]
I don't have anything against changing the default value from `1.4901161193847656e-08` to `1e-8`, if that's what you're asking :-).

W.r.t. Antony's `_namedfloat`: this is super cool :-). Whether we want this or not depends on 
*  if we do it, do the html/pdf docs render the way we want them render? I've no idea if Sphinx picks up `__repr__` or not. 
* how does it look with ipython magic `least_squares??`

**Comment by nmayorov** [comment]
@ev-br my concerns were about changing default values after the release. I conclude from your answer that it is not going to be a problem.

As for named float, I don't like that the exact value won't be shown anywhere, and people have to search for EPS value (and then compute sqrt from it).

So I'm going to send a PR with the change to 1e-8.

**Comment by anntzer** [comment]
Sphinx and ipython's func?? picks up `__repr__` perfectly well.  The only issue is that the `source` entry in `func??` is a bit more longer.

**Comment by ev-br** [comment]
If this trickery is handled well by both sphinx doc builders and ipython's machinery, I guess I'm +0.5 for rolling this in across `scipy.optimize`. However for changes to the whole package, I defer to @dlax.

**Comment by dlax** [comment]
Evgeni Burovski wrote:
> If this trickery is handled well by both sphinx doc builders and
> ipython's machinery, I guess I'm +0.5 for rolling this in across
> |scipy.optimize|. However for changes to the whole package, I defer to
> @dlax <https://github.com/dlax>.

At first glance, I cannot see a clear benefit of setting tolerance to 
this "named float" everywhere. Is there any other package where this has 
been done?

1e-8 is probably fine, this is a common value (for instance, it's used 
in Numpy comparison functions).

**Pull request merged**
