### PR TITLE
BUG: adding Buhring's analytic continuation method to special.hyp2f1 (redux)

### LINKED ISSUE #8054: Gauss Hypergeometric function (hyp2f1) diverges in two small regions of the complex plane
There are two narrow wedges in the complex plane where gauss's hypergeometric function (hyp2f1) gives implausibly large values when the function there is well defined.  In polar coordinates these wedges are approximately given by:

0.9 < r < 1.0
pi/3 < theta < pi/2

0.9 < r < 1.0
-pi/2 < theta < -pi/3

When I looked at the source code (the subroutine HYGFZ in scipy/special/specfun/specfun.f), I noticed that in the half annulus defined by 0.9 < |z| < 1.0 and real(z)>0, HYGFZ attempts to use the "1-z" transformation (see [eq 15.8.4](http://dlmf.nist.gov/15.8)) to evaluate the hypergeometric function. However the series associated with this transformation only converges when |1-z|<1. In the wedge regions given above, |1-z|>1 and so the method fails. 

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy.special import hyp2f1
>>> theta=np.linspace(np.pi/3.0,np.pi/2.0,10,dtype=np.float)
>>> z=0.95*np.exp(1.j*theta)
>>> hyp2f1(1.54,1.67,5.21,z)
array([ -2.14630605e+03 +6.71599145e+03j,
        -2.31991069e+14 +1.69689842e+14j,
        -2.50252397e+24 -3.16737713e+23j,
        -2.97640356e+33 -4.56037250e+33j,
         1.21082099e+42 -3.00909950e+42j,
         5.82402044e+50 -8.54809272e+49j,
         2.01184470e+58 +2.92349095e+58j,
        -4.16032387e+65 +6.43973917e+65j,
        -6.17050365e+72 -1.47233313e+72j,  -1.20089983e+78 -2.12896064e+79j])
```
In contrast, the first value in the z array should be (according to mpmath):
```
>>> import mpmath
>>> mpmath.hyp2f1(1.54,1.67,5.21,z[0])
mpc(real='0.9894407614789662', imag='0.52327754379886682')
```

### Scipy/Numpy/Python version information:
scipy, numpy, sys versions
```
>>> print sc.__version__,np.__version__,sys.version_info
1.0.0.dev0+b579459 1.13.1 sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

### LINKED ISSUE #8083: special.hyp2f1 returns the wrong values when c-a-b is an integer (for 0.9<|z|<1.0)
The hypergeometric function hyp2f1(a,b,c,z) gets the wrong values when c-a-b=integer and z is in the region of the complex plane given by:

0.9<|z|<1.0 and real(z)>0

The source code for hyp2f1 can definitely handle the case of integer differences between the a,b,c parameters, but in this case the code doesn't correctly calculate the integer corresponding to c-a-b.
Specifically, this bug is caused by a couple of lines in specfun.f in which the integer is determined by the expression
```
M=INT(C-A-B)
```
For some values of a,b,c this might be 3.9999 which gets cast to the integer *3* instead of *4*.  Using a conversion of the form 
```
M=INT(C-A-B+EPS*DSIGN(1.0D0,C-A-B))
```
where EPS is a small value like 1e-8 or 1e-15 should fix this issue (this is at least what specfun.f does elsewhere in HYGFZ when determining an integer from real values). 

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy.special import hyp2f1 
>>> import mpmath
>>> a=1.45
>>> b=0.6
>>> c=6.05
>>> c-a-b
3.9999999999999996
>>> z=0.9*np.exp(1.j*(-0.2*np.pi))
>>> hyp2f1(a,b,c,z)
(5.670408102465732-0.76807186486958579j)
>>> mpmath.hyp2f1(a,b,c,z)
mpc(real='1.1053555735636691', imag='-0.11840327506397474')
```
In the above test case, HYGFZ is using *3* instead of *4* for c-a-b which is why it gets the wrong answer as compared with mpmath.

### Scipy/Numpy/Python version information:
```
>>> print scipy.__version__,np.__version__,sys.version_info
1.0.0.dev0+b579459 1.13.1 sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by h-vetinari**
There's been no activity in #8151 for about a year. @FormerPhysicist has not been active much (according to his GH profile), and @person142 was not able to find the time to pick up the PR. I thought I'll give it a try.

Closes #8054
Closes #8083
Closes #8151

Note that https://github.com/scipy/scipy/commit/5cfdcbf94f6208777375fd5355ea9ec21fe9520b is obsolete since #12792.

Description from OP of #8151:
> 
> ## Overview
> 
> This pull request adds a new method of calculating the hypergeometric function hyp2f1 in the region where the standard transformation formulas for hyp2f1 fail. This method is based on the analytic continuation series given in _W. Buhring, An Analytic Continuation of the Hypergeometric Series, SIAM J. Math. Anal., Vol. 18, No. 3, May 1987_.
> 
> This new method is applied to the region of the complex plane given by:
> 0.9 <= |z| <= 1.1 and Re(z) >= 0.0 and |z-1.0| >= 0.75
> ## Summary of what methods are used in each region of the complex plane
> 
> |z| > 1.1 ............................................................................ 1/z transformation
> |z| <= 1.1 and Re(z) < 0.0 ................................................ z/(z-1) transformation
> |z| < 0.9 and Re(z) >= 0.0 ................................................. defining Taylor series for hyp2f1
> 0.9 <= |z| <= 1.1 and |z-1.0| < 0.75 .................................. 1-z transformation
> 0.9 <= |z| <= 1.1 and Re(z) >= 0.0 and |z-1.0| >= 0.75 .... Buhring's analytic continuation series
> 
> Note that the transformations for hyp2f1 discussed above are given [here](http://dlmf.nist.gov/15.8). (They're also listed in _Handbook of Mathematical Functions, M. Abramowitz and I. Stegun_)
> ## Expanded region that uses 1-z and z/(z-1) transformations
> 
> Besides implementing Buhring's series in the region where hyp2f1 was failing, I also slightly extended the region where the 1-z and z/(z-1) transformations are used so that both transformations are now used (in their appropriate regions) **when |z| <= 1.1** instead of when |z| <= 1.0
> 
> My main motivation for this small expansion is the fact that the three methods that would get used in the ring 1.0 < |z| < 1.1 (i.e., Buhring's series, the 1-z and z/(z-1) transformations, see previous summary) all converge much sooner and are much faster than the 1/z transformation.
> 
> The only potential (but ultimately fixable) downside that I could find with the expansion of the 1-z region is related to the values we return for hyp2f1 on the branch cut (1, inf). Specifically, on the branch cut of hyp2f1, the 1-z transformation converges to a different branch of hyp2f1 than the 1/z transformation does.
> 
> From a mathematical point of view this is okay since hyp2f1 is essentially multi-valued on the branch cut but it does mean that if one were to plot the real/imaginary parts of hyp2f1 on the real axis (1,inf), one would see a discontinuity at x=1.1. To fix this, I've also added some code to the 1-z method so that it converges to the same branch of hyp2f1 that the 1/z transformation converges to (when z is on the branch cut). This amounts to multiplying some prefactors in the method by a constant complex value. I can give more details about this as needed.
> ## Related issues
> 
> Closes #8054
> Closes #8083

### CODE REVIEW

**Comment by FormerPhysicist** [comment]
I'm still lurking around and willing to respond to reviewer comments. 
As I remember, the development for all of my various hypergeometric PRs
was complete, at least in terms of functionality/implementation of the
quoted algorithms and in unit test coverage of the new algorithms.  I
was just waiting for a expert reviewer.

That said, I do think that *now* there are stylistic issues and other
issues that need to be addressed to get the PRs to pass
Travis/ci/circleci.  I'm not familiar with scipy's CI/CD pipelines, but
I'm guessing you guys updated something since 3 years ago when I first
opened my PRs (and when my PRs were passing Travis etc.)

In fact, over the summer I actually did try briefly to troubleshoot one
of my stale PRs*. It had a unit test from a completely unrelated module
that was failing in a specific environment in Travis.  I was never able
to reproduce the error locally in my laptop so I sorta gave up. Probably
should of reached out to the email list...

Adam (FormerPhysicist)

* This one: https://github.com/scipy/scipy/pull/8548

**Comment by h-vetinari** [comment]
Hey Adam

Happy to close this PR if you want to pick up yours. I guess to make it seem like the PR is still active, it helps to keep it conflict-free and with green CI, but even more importantly: to respond to pings from the maintainers here (I'm not one of them). ;-)

**Comment by FormerPhysicist** [comment]
I actually would lean more towards just letting you push your changes to my original branch and just have one PR that we share. I won't necessarily have time to fix these issues for another couple of months.

But before we do anything, why don't I ask the developer mailing list what the procedure should be?  (If you aren't on that list, you might want to subscribe [here](https://mail.python.org/mailman/listinfo/scipy-dev))

**Comment by h-vetinari** [comment]
Sure, if you want to, I can push these changes to your PR (provided you make me a collaborator on your fork of scipy) - otherwise you can take the commits from this branch and push them to yours yourself.

I think there's really not much more than what I mentioned (conflict-free, green CI, responded to all review / pings), but feel free to reach out to the mailing list. Also, several devs are obviously very active on GH (holiday season notwithstanding), so you'd probably get faster feedback from pinging `@rgommers` or `@tylerjereddy`...

**Comment by FormerPhysicist** [comment]
@h-vetinari I've added you as a collaborator on my fork of scipy.  You can close this PR and just push your changes to my original PR.

**Comment by h-vetinari** [comment]
Moving this work back to #8151.

**Pull request closed without merging**
