### PR TITLE
BUG: sparse: csc_matrix.argmax() integer overflow

### LINKED ISSUE #13646: Sparse matrix argmax() integer overflow on Windows 10
When running on Windows 10, the sparse.csc_matrix.argmax() function can silently overflow the int data type and return the wrong value with sufficiently large matrices. This issue does not occur on Linux.

#### Reproducing code example:

```
import numpy
from scipy import sparse

dim = (100000, 100000)
mat = sparse.lil_matrix(dim)
mat[99998, 99998] = 1
mat = sparse.csc_matrix(mat)

idx = mat.argmax()
idx_unravelled = numpy.unravel_index(idx, dim)

print(idx_unravelled)
print(mat[idx_unravelled])
print(mat[99998, 99998])
```

Expected output:

```
(99998, 99998)
1.0
1.0
```

Actual output:

```
(14099, 65406)
0.0
1.0
```

Workaround:

```
maxval = mat.max()
if idx < 0:
    idx += 1 << 32
idx_unravelled = numpy.unravel_index(idx, dim)
while mat[idx_unravelled] < maxval:
    idx += 1 << 32
    idx_unravelled = numpy.unravel_index(idx, dim)

print(idx_unravelled)
print(mat[idx_unravelled])
```

#### Scipy/Numpy/Python version information:
```
1.6.1 1.18.4 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

Again, I am only having this problem on Windows. The same code runs with SciPy 1.6.1 on Ubuntu 20.04 with no problem.

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

- closes gh-13646 

#### What does this implement/fix?

- explicitly casts integer as Python `int` type to catch any potential overflows for large sparse matrices

### CODE REVIEW

**Comment by mckib2** [comment]
@mdhaber @WarrenWeckesser  The only worry I would have is if the variable I cast to `int` might ever be an array.  I think it's always a scalar, but having some more sets of eyes on this will hopefully prevent any regression

**Comment by mdhaber** [comment]
If there's concern, maybe casting `mat.shape[1]` would be safer. Assuming the shape attribute is the usual tuple, it will always be scalar.

**Comment by mckib2** [comment]
> Looks like there are still problems on 32-bit though.

I'm debugging in a 32-bit Docker image right now it looks like these failures are due to using an older version of numpy.  Overflow errors using `unravel_index` were fixed in https://github.com/numpy/numpy/pull/13439, so the test probably just needs to be updated to not use `np.unravel_index`

**Comment by mckib2** [comment]
> Without digging too deep, maybe casting mat.shape[1] would be safer. mat is a coo matrix, so the shape attribute should be the usual 2-tuple, and so mat.shape[1] will always be scalar.

Just casting `mat.shape[1]` is not enough here, both expressions appear to need an explicit cast to Python integer for the new tests to pass on 32-bit architectures

**Review by rgommers — APPROVED** [review]
LGTM, thanks @mckib2

**Pull request merged**
