### PR TITLE
ENH: Add test for encoding

### LINKED ISSUE #9606: SyntaxError: Non-ASCII character '\xe2' in file scipy/stats/_continuous_distns.py on line 3346, but no encoding declared
I get syntax errors due to source code encodings when importing scipy 1.2.0. The error only seems to occur if `pyc` files are missing.

The issue originates from https://github.com/scipy/scipy/blob/v1.2.0/scipy/stats/_continuous_distns.py#L3345. The dash/hyphen used there isn't a regular dash/hyphen, but instead the line reads as `'    pp. 1\xe2\x80\x9313, 1997.\n'`

### Reproducing code example:

```Dockerfile
FROM python:2.7

RUN pip install --no-cache-dir scipy

# Without the following line, I can't reproduce the problem.
RUN find /usr/local/lib/python2.7/site-packages/scipy/ -name '*.pyc' -delete

RUN python -c "import scipy.stats"
```

### Error message:

```
Step 1/4 : FROM python:2.7
 ---> f67e752245d6
Step 2/4 : RUN pip install --no-cache-dir scipy
 ---> Using cache
 ---> e8adb88b0f15
Step 3/4 : RUN find /usr/local/lib/python2.7/site-packages/scipy/ -name '*.pyc' -delete
 ---> Running in 6e46e320f24d
Removing intermediate container 6e46e320f24d
 ---> ed5be7afd25a
Step 4/4 : RUN python -c "import scipy.stats"
 ---> Running in 8c8ea36e3284
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/stats.py", line 173, in <module>
    from . import distributions
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 3345
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.2.0', '1.15.4', sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0))
```

### PR DESCRIPTION
**Pull request by larsoner**
Closes #9606.

First commit should flag as red on the fast Travis build. Once it does, I'll correct the errors it's pointing out.

### CODE REVIEW

**Comment by larsoner** [comment]
On the first commit I killed all CIs except for Azure (no account there for me yet) and the one relevant [Travis run](https://travis-ci.org/scipy/scipy/jobs/470081686) which yielded:
```
$ grep -rlIP '[^\x00-\x7F]' scipy | grep '\.pyx\?' | sort > unicode.out; grep -rlI '# -\*- coding: \(utf-8\|latin-1\) -\*-' scipy | grep '\.pyx\?' | sort > coding.out; comm -23 unicode.out coding.out > test_code.out; cat test_code.out;  test \! -s test_code.out
scipy/io/__init__.py
scipy/stats/_continuous_distns.py
scipy/stats/_stats_mstats_common.py
The command "grep -rlIP '[^-]' scipy | grep '\.pyx\?' | sort > unicode.out; grep -rlI '# -\*- coding: \(utf-8\|latin-1\) -\*-' scipy | grep '\.pyx\?' | sort > coding.out; comm -23 unicode.out coding.out > test_code.out; cat test_code.out;  test \! -s test_code.out
" exited with 1.
```
Now re-running with all CIs, should be ready for review/merge as they should come back green since the [only job that should be affected is green](https://travis-ci.org/scipy/scipy/jobs/470084390).

**Comment by larsoner** [comment]
I added a commit to remove the en-dashes in functions where we had `r"""` docstrings, and added one or two `u` prefixes to docstrings that used unicode. This should make it backport-able to the 1.2 / Python2 LTS release.

**Comment by rgommers** [comment]
Works for me, thanks @larsoner.

@tylerjereddy seems okay to me as backport, will leave that to you to decide though.

**Comment by WarrenWeckesser** [comment]
Given that we no longer support Python 2, is the check for unicode characters still necessary?  I'm working on a pull request in which a test docstring refers to π (the actual value of π) and `np.pi` (the floating point approximation of π).  Using the symbol π makes the comments easier to read.

**Comment by rgommers** [comment]
> Given that we no longer support Python 2, is the check for unicode characters still necessary?

It's not, we can remove it. It took a while to find: [PEP 3120](https://www.python.org/dev/peps/pep-3120/) specifies that UTF-8 is the default encoding for Python 3.x, and so we can use UTF-8 characters without having to declare an encoding or cause any issues.

@WarrenWeckesser if you do this, could you do some sanity checking that there's no surprises (e.g. ipython and python interpreters show docstring fine)?

**Comment by WarrenWeckesser** [comment]
Last year (two comments up from here) I asked about removing this check.  @rgommers confirmed that we can remove it, but suggested looking into how programs such as ipython handle Unicode characters in docstring.  This never made it to the top of my to-do list, but since then there has been some work in NumPy that looks relevant.

Over in https://github.com/numpy/numpy/pull/15666, @rossbar added the use of Unicode characters in the string representation of NumPy's polynomial.  It turns out that using Unicode in a Windows terminal can cause problems; see the discussion starting at https://github.com/numpy/numpy/pull/15666#issuecomment-601327484.  The problem is that the font used by the terminal might not have full Unicode support.

**Pull request merged**
