### PR TITLE
CI: build and upload docs on Travis-CI

### PR DESCRIPTION
**Pull request by pv**
Builds dev version of documentation on Travis-CI and uploads to https://github.com/scipy/devdocs
visible as https://scipy.github.io/devdocs/

Similar solution as what matplotlib uses.

Addresses gh-4214

The encrypted deploy key is set up following the travis-ci encrypted file instructions. It won't work for pull requests, as the encrypted key will not be available for them --- due to security reasons (running untrusted code, would be trivial to steal the secret key).

### CODE REVIEW

**Comment by pv** [comment]
Not directly testable except maybe in a branch in the main repository.
However, the set of upload commands has been tested manually.

**Comment by ev-br** [comment]
Cool! Let's put this in right away.

**Comment by pv** [comment]
Didn't work on first try :/
Trying to fix it in e54a24d3c

**Comment by pv** [comment]
Ok, works now.

**Pull request merged**
