### PR TITLE
Update THANKS.txt

### PR DESCRIPTION
**Pull request by borhan-kazimipour**
Redundant newlines are removed.

### CODE REVIEW

**Comment by ilayn** [comment]
Thanks @borhan-kazimipour Those are not redundant but actually following a particular style such that files can be viewed in editors without the soft/hard wrap functionalities.

**Comment by borhan-kazimipour** [comment]
Thanks @ilayn 
Makes sense.

**Comment by charris** [comment]
Close/reopen

**Comment by rgommers** [comment]
this is a change we prefer not to have, so closing. thanks anyway @borhan-kazimipour

**Pull request closed without merging**
