### PR TITLE
BUG: stats: A few distributions didn't accept lists as arguments.

### LINKED ISSUE #12178: BUG: stats: Some discrete distributions don't accept lists of numbers.
The discrete distributions `boltzmann`, `hypergeom` and `randint` don't accepts lists as arguments to all their methods.

For example,
```
In [2]: from scipy.stats import boltzmann, hypergeom, randint

In [3]: boltzmann.pmf(0, 2, [10, 11])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-759dbc29a72d> in <module>
----> 1 boltzmann.pmf(0, 2, [10, 11])

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+23b6191-py3.7-macosx-10.7-x86_64.egg/scipy/stats/_distn_infrastructure.py in pmf(self, k, *args, **kwds)
   3018         """
   3019         args, loc, _ = self._parse_args(*args, **kwds)
-> 3020         _a, _b = self._get_support(*args)
   3021         k, loc = map(asarray, (k, loc))
   3022         args = tuple(map(asarray, args))

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+23b6191-py3.7-macosx-10.7-x86_64.egg/scipy/stats/_discrete_distns.py in _get_support(self, lambda_, N)
    730 
    731     def _get_support(self, lambda_, N):
--> 732         return self.a, N - 1
    733 
    734     def _pmf(self, k, lambda_, N):

TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

```
In [4]: hypergeom.pmf(0, [10, 11], 5, 9)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-e2e0fdcbda3b> in <module>
----> 1 hypergeom.pmf(0, [10, 11], 5, 9)

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+23b6191-py3.7-macosx-10.7-x86_64.egg/scipy/stats/_distn_infrastructure.py in pmf(self, k, *args, **kwds)
   3018         """
   3019         args, loc, _ = self._parse_args(*args, **kwds)
-> 3020         _a, _b = self._get_support(*args)
   3021         k, loc = map(asarray, (k, loc))
   3022         args = tuple(map(asarray, args))

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+23b6191-py3.7-macosx-10.7-x86_64.egg/scipy/stats/_discrete_distns.py in _get_support(self, M, n, N)
    432 
    433     def _get_support(self, M, n, N):
--> 434         return np.maximum(N-(M-n), 0), np.minimum(n, N)
    435 
    436     def _argcheck(self, M, n, N):

TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

```
In [5]: randint.pmf(0, 0, [10, 11])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-401f972d40d8> in <module>
----> 1 randint.pmf(0, 0, [10, 11])

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+23b6191-py3.7-macosx-10.7-x86_64.egg/scipy/stats/_distn_infrastructure.py in pmf(self, k, *args, **kwds)
   3018         """
   3019         args, loc, _ = self._parse_args(*args, **kwds)
-> 3020         _a, _b = self._get_support(*args)
   3021         k, loc = map(asarray, (k, loc))
   3022         args = tuple(map(asarray, args))

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+23b6191-py3.7-macosx-10.7-x86_64.egg/scipy/stats/_discrete_distns.py in _get_support(self, low, high)
    793 
    794     def _get_support(self, low, high):
--> 795         return low, high-1
    796 
    797     def _pmf(self, k, low, high):

TypeError: unsupported operand type(s) for -: 'list' and 'int'
```

The SciPy version
```
In [6]: import scipy

In [7]: scipy.__version__                                                                                                  
Out[7]: '1.5.0.dev0+23b6191'
```

I will submit a pull request with a fix.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Expressions such as

    >>> boltzmann.pmf(0, 2, [10, 11])
    >>> hypergeom.pmf(0, [10, 11], 5, 9)
    >>> randint.pmf(0, 0, [10, 11])

would raise

    TypeError: unsupported operand type(s) for -: 'list' and 'int'

Some of the continuous distributions also raise a TypeError when given a list, such as

    >>> genextreme.cdf(0.1, [1, 2])

which raises

    TypeError: '>' not supported between instances of 'list' and 'int'

The problem is the calculations in `_get_support(*args)` generally assume that the arguments are numpy arrays, so it should be called after the arguments have been passed through `asarray`. 

Closes gh-12178.

### CODE REVIEW

**Comment by josef-pkt** [comment]
private methods shouldn't need to do this. shape handling and conversion should be in the main methodds

AFAICS, Based on the traceback in the issue, the existing asarray just needs to be moved a few lines higher
`3022         args = tuple(map(asarray, args))`

**Comment by WarrenWeckesser** [comment]
@josef-pkt, good point.  I'm looking into how to make this change more generic.

**Comment by WarrenWeckesser** [comment]
I marked this PR as "draft" for now.  A better solution is to move the `asarray` calls into `_parse_args`, so we're not repeating `asarray` so much.  I have this working locally; once I've cleaned it up, I'll update the PR.

**Comment by WarrenWeckesser** [comment]
Earlier I said

>  A better solution is to move the asarray calls into _parse_args...

and I have a working branch where I did that, but the changes are big enough that it will probably require a few rounds of review before merging.  In the interest of getting gh-12178 fixed for 1.5, this version is the simple fix:  call `_get_support(*args)` *after* the args have been passed through `asarray`.

The "better" (IMHO) fix can wait until after 1.5 is branched.

**Comment by josef-pkt** [comment]
lgtm

**Comment by mdhaber** [comment]
@WarrenWeckesser is the fact that
```
import scipy.stats
scipy.stats.norm.moment(n=1, loc=[1,2,3], scale=1)
```
doesn't work a separate issue?
According to the documentation, `loc` and `scale` should accept array-like. They actually don't even accept arrays.

**Comment by WarrenWeckesser** [comment]
@mdhaber, I'd call that a separate issue.  It looks like `moment` code doesn't handle broadcasting at all.

**Comment by tylerjereddy** [comment]
@WarrenWeckesser I assume you've noticed the `stats` test failures in Travis for latest NumPy pre-wheels? Those do seem potentially connected.

**Comment by WarrenWeckesser** [comment]
@tylerjereddy, yes, I'm fixing that now.

**Comment by WarrenWeckesser** [comment]
In the last update, I fixed a PEP-8 issue and changed the floating point comparisons of the new tests to use `assert_allclose`.  All tests are now green.

**Comment by tylerjereddy** [comment]
CI is green and @josef-pkt seemed happy with the changes, so merging thanks all.

**Pull request merged**
