### PR TITLE
MAINT: special: Accommodate changed integer handling in NumPy 2.0.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
* Add the 'p' character to the typecodes recognized by the script `_generate_pyx.py`.  This code corresponds to the integer types `npy_intp` and `Py_ssize_t`.
* In Cython code:
  * Change the fused type `dl_number_t` to `dlp_number_t`, and include `Py_ssize_t` in the types it fuses.
  * Change other uses of `long` to `Py_ssize_t`.
* In the type signatures of ufuncs configured in `functions.json`, change occurrences of `i` or `l` in an input to `p`.
* Change use of `int` in the wrappers of `xsf` functions to `Py_ssize_t`. The thin wrappers cast this to `int` before calling the `xsf` function.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
IIUC, without a fix for the issue we're literally failing the testsuite on Windows with stable releases of NumPy 2.x, right? So, a fix for this is a mandatory backport before we can do `1.14.1`, no?

**Comment by WarrenWeckesser** [comment]
> IIUC, without a fix for the issue we're literally failing the testsuite on Windows with stable releases of NumPy 2.x, right? So, a fix for this is a mandatory backport before we can do 1.14.1, no?

That's my understanding.

**Comment by WarrenWeckesser** [comment]
All green, even with an additional casting test.  This might require refinements or tweaking, but I think it is ready for review.

**Comment by lucascolley** [comment]
@seberg would you be able to take a look?

**Review by steppi — APPROVED** [review]
Thanks @WarrenWeckesser for working on this. I just want to recap to make sure I understand everything.

* NumPy's default integer used to be a `long` but now it is 32 bit on 32 bit systems and 64 bit on 64 bit systems. 
* On Windows, a `long` is 32 bits, but on all other supported platforms a long is 64 bits.
* Thus if you try to pass a NumPy default int or an array of them into a ufunc that expects longs on 64 bit Windows, then the ufuncs scalar kernel expects 32 bit integers, and passing a 64 bit NumPy default int requires an unsafe cast.
* `np.intp` will be a NumPy default int on all platforms and the corresponding C type is `Py_ssize_t`, which is like a platform independent version of the Posix `ssize_t`.
* For all ufuncs that expect integer input, you've changed the character code to `'p'` for `npy_intp`, and the C data type to `Py_ssize_t`, which means that ufuncs take the platform's NumPy default int.

Your solution looks correct to me, and I don't think there need to be any tweaks. I'm OK with merging if you give the OK. I have one question: do we need to consider the case where someone passes a 64 bit int on a 32 bit system. My guess is no.

**Comment by seberg** [comment]
Agreed, this sounds good.  I'll note two small things:
* `p` does not strictly correspond to `Py_ssize_t`, it rather is pointer sized `intptr_t`.  In NumPy there were once people trying to compile NumPy for niche platforms where this made a difference.
  It may make sense to note somewhere that `p` is a work-around.  If such niche platform comes around, it should be adjusted.  (unless you want to define  `l` or `q` depending on the platform.)
* You could of course also use `q` and `long long`.  Which would allow users can pass `int64` on 32bit platforms.  The downside is typical casting on those same platforms.
  (This is *not* a regression, though!)

In either case, I don't think either of those things is much to worry about, more something to be aware of when it comes up.
(The first actually means you can only compile for either NumPy 1.x or NumPy 2 on such platforms, which seemed fine considering how presumably everyone has to compile locally anyway for them.)

**Comment by steppi** [comment]
Thanks @seberg for the heads up on these things and for vetting the proposed solution. I'm to go ahead and merge this. Thanks @WarrenWeckesser

**Comment by WarrenWeckesser** [comment]
Thanks @steppi and @seberg.

**Comment by tylerjereddy** [comment]
oof on the merge conflicts! `special` has been active..

**Comment by jan-david-fischbach** [comment]
Hey All (@WarrenWeckesser), with [treams](https://github.com/tfp-photonics/treams) we make heavy use of cython_special functions (spherical Bessel and Hankel functions in particular). Unfortunately the change from long to Py_ssize_t breaks function signature compatibility between compiled binaries for us. How can we best create compatibility to previous and current versions of scipy? Best Regards JD

**Comment by tylerjereddy** [comment]
@jan-david-fischbach you might want to create a new issue for visibility, though I'm not sure there's much SciPy can do on its end and perhaps this is a usage more than dev issue.

**Pull request merged**
