### PR TITLE
Backports for 0.18.1

### PR DESCRIPTION
**Pull request by ev-br**
Backports for 0.18.1. <s>Need to add gh-6543 and gh-6545: review/merge to master, then backport.</s>

### CODE REVIEW

**Comment by rgommers** [comment]
Commits look good, so in it goes.

@ev-br I think you now have to add tag ``v0.18.0-2`` with some explanation to commit f9de0c47c

**Comment by ev-br** [comment]
Not sure what would be the benefit of that tag, can you elaborate?

**Comment by pv** [comment]
In principle f9de0c4 should not have been included in the backport PR 
--- now there are two "REL: bump version to 0.18.0" commits in the branch.
.
But never mind, it's clear from the commit graph that the later one is a 
bogus one.

**Comment by ev-br** [comment]
Darn! Indeed, mea culpa.

I'm still unsure how an extra tag would help though. I see three options:

1. Force-edit the history and remove the duplicate commit.
2. Revert the duplicate
3. Accept the artifact being there, do nothing and tag 0.18.1 with what is in the branch.

Thoughts?

**Comment by ev-br** [comment]
@johschmitz, @kleskjr Do you want to tell me your names so that we can add them to the release notes? Otherwise it'll have to be your github handles.

**Comment by johschmitz** [comment]
Johannes Schmitz

**Comment by rgommers** [comment]
Hmm, I think the commit for the old tag was already detached after your earlier surgery. Because I shouldn't be able to merge your PR with a green button if it doesn't merge cleanly with the HEAD of 0.18.x.

At this point I prefer (3) over more history editing.

**Comment by pv** [comment]
It probably merged cleanly, because it's an exact copy of the actually 
tagged release commit, which occurs after the branch point of the PR. 
Anyway, probably not worth the trouble to resolve it.

**Pull request merged**
