### PR TITLE
DOC: Add warnings of inversed order of y and t in f = dy/dt for ode a…

### PR DESCRIPTION
**Pull request by germannp**
…nd odeint.

Add warning to the parameter description in the "entry level interface" odeint
and more prominently to the more sophisticated ode interface, on which users
fall back when needing more control.

This has been discussed in #1446.

### CODE REVIEW

**Comment by rgommers** [comment]
Looks ok to me, can be merged soon unless someone objects. I noted this change on gh-1446.

**Comment by WarrenWeckesser** [comment]
+1 for adding a note about this to the docstrings.  However, the editor in me objects to the colloquialism "Buyer beware".  How about "Note that ..." or, if it is felt that more emphasis is need, "Important note! ...", or something similar?

**Comment by philipp-germann** [comment]
@WarrenWeckesser, I used this formulation because it is used in similar case elsewhere in the scipy docs. No feelings involved from my side.

**Comment by pv** [comment]
The docs should aim for neutral language, so "s/buyer beware/note that/g"

**Comment by WarrenWeckesser** [comment]
@philipp-germann Will you be able to update this with edited text, or should one of us take over?

**Comment by WarrenWeckesser** [comment]
Alternative PR: https://github.com/scipy/scipy/pull/5459

**Comment by WarrenWeckesser** [comment]
https://github.com/scipy/scipy/pull/5459 includes comments about the differing conventions of `odeint` and the `ode` class, so this PR can be closed.

**Pull request closed without merging**
