### PR TITLE
BUG/ENH: stats: updates for cauchy.

### LINKED ISSUE #20761: ENH: stats.cauchy: improve cdf and quantile accuracy in tail
### Is your feature request related to a problem? Please describe.

I have found that there is a problem with calculation accuracy in the tail of the Cauchy distribution.

https://github.com/scipy/scipy/blob/4edfcaa3ce8a387450b6efce968572def71be089/scipy/stats/_continuous_distns.py#L1382-L1392

I would like to see this improved based on boost implementation.
https://www.boost.org/doc/libs/1_85_0/libs/math/doc/html/math_toolkit/dist_ref/dists/cauchy_dist.html

### Describe the solution you'd like.

_No response_

### Describe alternatives you've considered.

_No response_

### Additional context (e.g. screenshots, GIFs)

_No response_

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
* Simplify the expressions for the CDF and SF by using arctan2. The new expressions give good precision over the entire domain.
* Wrap Boost functions to use in the _ppf and _isf methods.

Closes gh-20761.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The CI failures are not related to the changes in this PR.

**Comment by fancidev** [comment]
I looked at the [boost source](https://www.boost.org/doc/libs/1_84_0/boost/math/distributions/cauchy.hpp) and it looks very straightforward. How about coding the logic in Python in SciPy instead of wrapping it through `special`? I think this would make the SciPy code simpler and more transparent.

Btw, I’m a bit skeptical about the boost code. Firstly, the code contains a lot of `if (false == condition)` blocks, which is seen as an anti-pattern by some style guides. Secondly, its `quantile_imp(p)` function first “chops” `p` by setting `p = p - floor(p)`. This has two problems: (1) It accepts quantiles out of the range `[0,1]`, which is not mathematically correct (as far as I understand), and (2) it would return `-inf` for `p=1`, which is wrong (should return `+inf`).

**Comment by WarrenWeckesser** [comment]
Re: Boost code: Take another look at the Boost code.  `p` is validated in `detail::check_probability(function, p, &result, Policy())`, so it does not allow values outside of [0, 1]. (This wouldn't matter in `_cauchy_ppf` anyway, since we only use this private function in a place where `p` has already been validated.)  I'm note sure why that use of `p - floor(p)` is there; @jzmaddock, is that needed? Also note that it computes `-scale / tan(constants::pi<RealType>() * P)`, where `P` was computed above; `P` is not `p`.  If you take a look at the tests that I include in the PR, you'll see that the precision is good.  Did you find a case where it is not?

The Boost code *is* relatively simple in this case, but will still require conditionals if we implement the same method as the Boost code, which means it should really be implemented as a ufunc in a compiled language.  So we might as well use the existing code in Boost.

If there are any problems in the Boost code, we can create an issue for it at the boost/math github page.

**Review by dschmitz89 — APPROVED** [review]
LGTM, let's just wait if Boost folks answer about the issue raised there.

**Comment by jzmaddock** [comment]
> LGTM, let's just wait if Boost folks answer about the issue raised there.

I've seen your message, I just haven't had a chance to look into anything yet!

**Comment by dschmitz89** [comment]
> > LGTM, let's just wait if Boost folks answer about the issue raised there.
> 
> I've seen your message, I just haven't had a chance to look into anything yet!

No worries, take your time ;).

**Comment by WarrenWeckesser** [comment]
Fine to wait, but note that the Boost issue that I created is not to report a bug.  I don't think the calculation is wrong. I just suspect that the call of `floor(p)` is superfluous, and if that is the case, removing it won't change anything compared to the current version.

**Comment by fancidev** [comment]
Thanks for the reply and thanks for opening the issue in boost @WarrenWeckesser. While a redundant line has no effect on the result (other than requiring that the `floor` function be defined for `RealType`), it might confuse the reader as for the preconditions of the function.

I think the accuracy is good with the boost implementation. The code handles `p=0.5`, so the relative error for this input is zero. The code doesn’t handle `p=0.25` and the result is inexact but within one ulp. A proper `cotPi` function might offer improved accuracy (on the scale of 1 ulp), but it is probably more of theoretical than practical utility. (Plus, I’m not aware of an existing “proper” implementation of `cotPi` that does better than `1/tan` except for the special inputs.)

A corner case for the boost function is `p=5e-324`, which overflows. I’m not sure whether the boost `policy` handles/is supposed to handle this case, but fortunately this is of no concern to SciPy as SciPy expects it to silently overflow.

I’m not sure where to draw the line between “a simple expression that can be coded in Python” and “a complex expression/subroutine that may as well be wrapped”; after all this might be more about preference than else.

**Comment by steppi** [comment]
@fancidev, I've spent time studying Boost Math's code base and documentation, and my impression is that the quality is consistently pretty high. @jzmaddock and @mborland have always been responsive to issues [1] and are both highly knowledgeable and capable. I think it's important not to develop unreasonable expectations for large and sophisticated open source projects maintained by only a handful of developers. In large projects where maintainers must budget their time carefully, there's a lot of ways that superfluous lines or other code style issues can work their way into functions which are otherwise reliable and accurate. I'd hate to think that someone would be skeptical to use SciPy because of code style issues buried in our many lines of legacy code, expecting us to go over everything with a fine tooth comb. That just can't be a priority, given the many more pressing things there are to work on.

Using Boost here fits in well with how these things are typically done in `stats`. There's no sense in duplicating effort if an actively maintained project already has a quality implementation of something, and we've already paid the upfront costs of being able to wrap Boost functions in `stats`, so adding another doesn't really pose any additional maintenance burden.

Also, fyi, Boost's handling of `5e-324`, the smallest IEEE 754 double subnormal, is correct. From mpmath

```python

from mpmath import mp

# set dps high enough that 5e-324 - 0.5 can be computed.
mp.dps = 325

result = mp.tan(mp.pi*(mp.mpf(5e-324) - 0.5))
result
# mp.mpf('-67910890959664488207227276014646400664432274938268186332936844073597587140521399412467025083466631534943557183740723444627834866709243394597774122333171615796876821382242554818974304268233855183634540082045787435784718190024759024461615967607349956776028802373117561992963170991790585498278925074443105214894785214174106785.875')

# The result is too big to fit in a double.
float(result)
# -inf
```

[1] The superfluous line you've pointed out has already been removed https://github.com/boostorg/math/pull/1174.

**Comment by fancidev** [comment]
Thanks for the explanations @steppi ! I’m gladly surprised and impressed that the spurious line gets removed so quickly, which I didn’t expect for a large project like boost!

I understand that boost is probably *the* most widely used and tested C++ library. In addition, unlike some of the modules that are specific to the C++ language, boost/math provides quality reference implementation that are highly valuable for general use. I’d be honored if I could contribute to the boost code base!

Maybe along with this high expectation comes my scrutiny for code style. But I don’t intend to make a big deal of it because the value of a library is its functionality rather than its style, and style preference is subjective anyway.

My point about `5e-324` is that the function takes a policy argument, and there is code that optionally throws an overflow error (depending on the policy) if `p` is equal to 0 or 1. But the code does not check the policy for small `p`, such as `5e324`, that would overflow numerically. I don’t know if the policy argument is supposed to handle this sort of corner case (which are quite difficult to handle systematically), so I don’t see it as an obvious bug. (For this particular case, because tan(x) = x + o(x), 1/tan(x) will only overflow for subnormal x, which is somewhat contrived.)

**Comment by steppi** [comment]
> My point about `5e-324` is that the function takes a policy argument, and there is code that optionally throws an overflow error (depending on the policy) if `p` is equal to 0 or 1. But the code does not check the policy for small `p`, such as `5e324`, that would overflow numerically. I don’t know if the policy argument is supposed to handle this sort of corner case (which are quite difficult to handle systematically), so I don’t see it as an obvious bug. (For this particular case, because tan(x) = x + o(x), 1/tan(x) will only overflow for subnormal x, which is somewhat contrived.)

Just speculating, because I haven't actually looked closely at this, but I think what's going on there is that if you check for the cases `p == 0` or `p == 1` and directly return an answer, an overflow error won't be raised just because you returned + or - infinity. However, an overflow error will occur if an overflow occurs when computing an actual expression. If you think there's actually a problem here though, I'd suggest testing out locally if it behaves as you'd expect for `5e-324`, and if not, submitting an issue to Boost.

**Pull request merged**
