### PR TITLE
MAINT: optimize Cython code for speed and size

### PR DESCRIPTION
**Pull request by larsmans**
I think there's a few memory leaks in the `csgraph` code too; will fix those later.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Changes look good so far. Might be beneficial to add type info for the parameters of the functions that you converted from `def` to `cpdef`.

**Comment by larsmans** [comment]
They return `object`, which is the default, so I didn't bother.

**Comment by perimosocordiae** [comment]
I was thinking something like:
```
cpdef breadth_first_order(csgraph, int i_start,
                          bint directed=True, bint return_predecessors=True):
```

(Perhaps using better dtypes, like intp instead of int).

**Comment by larsmans** [comment]
Ah! Tried that, but it produces larger C files.

**Comment by larsmans** [comment]
No idea what's happening on Travis, I don't get any segfaults locally.

**Comment by larsmans** [comment]
Seems `PyArray_Size` doesn't work reliably. Looks like it gets passed NULL pointers within the csgraph code, not sure why.

**Comment by larsmans** [comment]
This is strange. The line

```cy
Nk = np.sum(csgraph > 0)
```

fails in Python 3 (only).

**Comment by perimosocordiae** [comment]
That very strange, considering that line wasn't changed in this PR. Even if the preceding condition somehow failed to catch sparse matrices, it still wouldn't give you that error.

**Comment by larsmans** [comment]
Actually there's a `cdef` for `Nk` a few lines up.

**Comment by larsmans** [comment]
@perimosocordiae merge?

**Comment by perimosocordiae** [comment]
I'm still not sure about the `Nk` issue on Python 3, but that shouldn't block merging this. Thanks!

**Pull request merged**
