### PR TITLE
BUG: fix NaN handing of stats.rankdata, stats.spearmanr, and stats.wilcoxon

### LINKED ISSUE #11790: NaN handling of stats.rankdata
I think NaN handling of stats.rankdata is not correct. 

#### Reproducing code example:

Current code is

```
rankdata([0, 2, 3, 2, np.nan, np.nan])
> [1.  2.5 4.  2.5 5.  6. ]
```

However, I think it should be

```
rankdata([0, 2, 3, 2, np.nan, np.nan])
> [1.  2.5 4.  2.5 np.nan  np.nan ]
```

or 

return nan

or

raise an exception.

#### Scipy/Numpy/Python version information:
Python: 3.7.7
scipy: 1.7.1

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
Fix #11790 and #11409 

#### What does this implement/fix?
fix NaN handing of stats.rankdata with adding "nan_policy" optional argument like other functions in stats.
Also, fix stats.spearmanr function for changing rankdata, because rankdata return "nan" when input has "nan" because of this PR. This change is needed for CI tests pass.

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
There is related issue #11409. I will try to fix it in this PR.

**Comment by AtsushiSakai** [comment]
@chrisb83 PTAL

**Comment by AtsushiSakai** [comment]
conflict was fixed.

**Comment by AtsushiSakai** [comment]
I think I should close this PR, because of same reason of #11747 
I should wait @WarrenWeckesser 's edge cases and nan_policy handling library is ready.

**Comment by mdhaber** [comment]
@AtsushiSakai are you interested in picking this up again? @WarrenWeckesser's guide is [here](http://scipy.github.io/devdocs/dev/api-dev/nan_policy.html).

**Comment by AtsushiSakai** [comment]
OK. I will try this again.

**Comment by AtsushiSakai** [comment]
I split this PR, fix #11790 in #13215, fix #11409 in #13223

**Pull request closed without merging**
