### PR TITLE
BUG: improve exceptions for private attributes in refactored `__all__` dicts

### LINKED ISSUE #15719: BUG: Extra entries in __all__/dir(...)
### Describe your issue.

It seem like the following entries in `__all__` are extraneous as they don't exists in the corresponding submodules.

This seem to come after the recent 1.8 refactor. It look like the point was to:
either fails is the name is not in `__all__` with a good explanation message, 
or have a shim with a warning to change imports. 

Unfortunately we end up with the warning and the attribute error, without the better error message.

### Reproducing Code Example

```python
import importlib
mod_attr  = [
    ('scipy.linalg.basic','decomp'),
    ('scipy.linalg.basic','decomp_svd'),
    ('scipy.interpolate.fitpack2','fitpack'),
    ('scipy.interpolate.interpolate','fitpack'),
    ('scipy.sparse.compressed','asmatrix'),
    ('scipy.sparse.compressed','dia_matrix'),
    ('scipy.sparse.compressed','matrix'),
    ('scipy.sparse.coo','matrix'),
    ('scipy.sparse.dia','matrix'),
    ('scipy.sparse.lil','asmatrix')]
import warnings
warnings.filterwarnings('ignore')

for mod_name, attr in  mod_attr:
    mod = importlib.import_module(mod_name)
    print(attr in dir(mod), hasattr(mod, attr)) # all print True, False should either be True/True, or False/False.
```

### Error message

```shell
N/A attribute error in another project that inspects arbitrary modules.
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1646.defbc28 1.22.3 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0), (Mars 8th, defbc282bcedc777bdd65951653bbe66e560a8ea)

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #15719 

I used the following python script to generate all the bugs in API:
<details>
<summary> Code </summary>
<p>

```py
import pkgutil
import scipy
import sys
import importlib

print("Scipy version: ", scipy.__version__)

def is_expected(name):
    if '._' in name or '.tests' in name or '.setup' in name:
        return False

    return True

bugs = []
for _, modname, ispkg in pkgutil.walk_packages(path=scipy.__path__,
                                               prefix=scipy.__name__ + '.',
                                               onerror=None):
    if is_expected(modname):
        print(modname)
        mod = importlib.import_module(modname)
        for attr in dir(mod):
            if not hasattr(mod, attr):
                bugs.append(modname + ": " + attr)

bugs_w = '\n'.join(bugs)
with open('bugs_api.txt', 'w') as f:
    f.write(bugs_w)
print(len(bugs))
```

</p>
</details>

cc @rgommers

### CODE REVIEW

**Comment by ilayn** [comment]
I am not sure if this is doing the right thing. For example for linalg, the extras are `decomp` and `decomp_svd` not the `float_factorial`

**Comment by Smit-create** [comment]
> float_factorial

This is for `sparse/linalg`

**Comment by ilayn** [comment]
Ah my bad. Apologies for the noise.

**Comment by Carreau** [comment]
I came up independently with the same list. +1.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @Smit-create, @Carreau and @ilayn

**Pull request merged**
