### PR TITLE
ENH: Simplify _cos_win, document it, add symmetric/periodic arg

### PR DESCRIPTION
**Pull request by endolith**
Should this become a public function?

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I don't expect there to me many public uses for such a function, since people will mostly want to use proper named / conventional windows. Or do you think people will need it?

**Comment by Eric89GXL** [comment]
I'd say let's leave it private for now and decide how to make a public API later when people are motivated to tackle that

**Comment by endolith** [comment]
Ok with me

**Comment by Eric89GXL** [comment]
You all done here, then? Is this to help your other PR #6483?

**Comment by endolith** [comment]
Yes I'm done with it, and it's a continuation from https://github.com/scipy/scipy/pull/6465

**Comment by Eric89GXL** [comment]
Thanks @endolith

**Comment by endolith** [comment]
> I'd say let's leave it private for now and decide how to make a public API later when people are motivated to tackle that

(Just linking this to https://github.com/scipy/scipy/pull/8534, which turned it into a public `general_cosine` function)

**Pull request merged**
