### PR TITLE
MAINT:  Begin translation of  hyp2f1 for complex numbers into Cython.

### LINKED ISSUE #7340: SciPy Hypergeometric function hyp2f1 producing infinities
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
The SciPy hypergeometric function special.hyp2f1 seems to be producing infinities for instances where third argument is negative, and fourth argument is complex. The corresponding implementation in MATLAB gives reasonable finite outputs. See for instance,

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```
In [2]: special.hyp2f1(-2,-3,-19,3.4+0.4j)
Out[2]: (inf+0j)

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
scipy version: 0.19.0

<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

This closes gh-7340 and is a prelude towards closing gh-8054, gh-8083, and gh-4894, as well fixing other defects in the current implementation of hyp2f1 for complex arguments for which issues have yet been made.
#### What does this implement/fix?

This is a mostly faithful translation of parts of the Fortran implementation of hyp2f1 for complex numbers (the function HYGFZ which lives in [scipy/scipy/special/specfun/specfun.f](https://github.com/scipy/scipy/blob/master/scipy/special/specfun/specfun.f)) into Cython. Numerical computation of Gauss's hypergeometric function, hyp2f1, involves handling a patchwork of special cases. Some of the cases have been translated into Cython with a fallback to the original Fortran implementation for cases that are not yet handled. The cases that are now handled in Cython are

1. c a negative integer, z != 0, and not c <= a <= 0 for a an integer nor  c <= b <= 0 for b an integer. (diverges). Note: This is the case that was incorrectly handled in the original implementation leading to gh-7340.
2. real(z) < 1 and c < a + b (diverges).
3. z = 0 or a = 0 or b = 0 (equals 1).
4. z = 1 and c - a - b > 0  ([DLMF 15.4.20](https://dlmf.nist.gov/15.4#E20))
5. z ~ -1 and c ~ 1 + a - b ([DLMF 15.4.26](https://dlmf.nist.gov/15.4#E26))
6. One of a or b a negative integer (Series reduces to polynomial).
7. One of c - a or c - b a negative integer. (Series reduces to polynomial after Euler hypergeometric transformation) ([DLMF 15.8.1](https://dlmf.nist.gov/15.8#E1))
8. |z| < 0.9 and real(z) >= 0. (Use defining Maclaurin Series.)

This implementation falls back to the Fortran implementation for all other cases. This translation of hypergeometric functions into Cython is along the lines of @Person142's work in #10636 and is a partial fulfillment of my promise at https://github.com/scipy/scipy/pull/8151#issuecomment-845232775. I've tried to add comments that explain the workings of the implementation and have added corresponding comments to the original Fortran file `specfun.f`  to make it easier to compare with the Fortran original.

#### Additional information

The goal is to make scipy's implementation of hyp2f1 easier to maintain, and make it easier to begin correcting the many defects in the Fortran implementation.  PRs #8110 and #8151 have been submitted by @FormerPhysicist with attempted fixes for defects in the current implementation of hyp2f1,  but they have languished due to a scarcity of reviewers capable of reviewing dense Fortran code for highly technical special function computations.  From what I understand, only @person142 is qualified and he is often very busy. The current PR fixes issue gh-7340 which was also addressed in the open PR #8110. A future PR will address the issues considered by #8151.

A script, `scipy.special._precompute.hyp2f1_data` has been added for testing against the `mpmath` implementation of hyp2f1 for a grid of parameter values against a grid of values for the argument z. Test cases have been cherry picked from among the cases computed in this script, with an eye towards picking difficult examples.

For cases 4. and 5. above, where the hypergeometric function reduces to a ratio of products of gamma functions, the computation has been updated to try again with logs if the output value underflows or overflows.

I envision future PRs being made to
1. Handle the regions uncovered by any of the standard transformations seen in gh-8054.
2. Translate the cases where different transformations apply into Cython one by one.
3. Adjust the regions in which the transformations are used. The 1/z transformation is currently used when |z| > 1, but this is much too wide a region. Convergence is bad for |z| near 1.
4. Handle larger values of parameters a and b by using recurrence relations and Miller's algorithm. I'm unsure if I'll ever get to this honestly, it appears to be more difficult than the other items in this list, and @person142, I guess it's really up to you if you'd even be interested in reviewing such a thing.

I plan to make a post in the mailing list this weekend for discussing this PR.

### CODE REVIEW

**Comment by rgommers** [comment]
This is a great idea, thanks for working on it @steppi!

**Comment by steppi** [comment]
Thanks @rgommers. Credit for the idea should go to @person142, but I'm happy to work on it!

**Comment by person142** [comment]
Fair bit of code here and I'm in a particularly busy time right now, so it might take me a while to review this. If no review in a few weeks ping me and I'll either review or ask for another ping in a few more weeks...

**Comment by steppi** [comment]
@person142 Sounds good! No rush

**Comment by steppi** [comment]
@person142 would you like me to break this down into several smaller PRs? We could have the following level of granularity

1. Just the _precompute script to test against mpmath and the tests, marking as xfail any tests that will fail without the other changes.
2. Just enough to fix gh-7340, the cases where any of a, b, or c are negative integers.
3. The cases z = 1, c - a - b > 0, z = -1, c = 1 + a - b
4. The case |z| < 0.9, real(z) >= 0 where the defining Taylor series is used directly.

**Comment by person142** [comment]
If you can break it down cleanly then yes-I will be able to review the pieces much more quickly. (Finding enough time to review a couple hundred lines of code is much easier.)

**Comment by steppi** [comment]
OK, cool. I'll break it down and trickle them in to keep from overwhelming you. I'll go ahead and close this one.

**Pull request closed without merging**
