### PR TITLE
DOC: Add examples for common Bessel functions

### PR DESCRIPTION
**Pull request by dschmitz89**
#### Reference issue
Towards gh-7168

#### What does this implement/fix?
Provides examples for all functions listed unter [Common Bessel functions](https://docs.scipy.org/doc/scipy/reference/special.html#faster-versions-of-common-bessel-functions) .

#### Additional information
I have rarely used these myself, my last theoretical encounter with Bessel functions was almost ten years ago. If something is missing or mathematically misleading, let me know.

Edit: apologies for again forgetting to add the skip CI flags.

[skip actions][skip azp]

### CODE REVIEW

**Comment by dschmitz89** [comment]
Ready for review from my side

**Review by j-bowhay — APPROVED** [review]
Examples seem reasonable to me :+1:

**Comment by dschmitz89** [comment]
CC @person142 : anything more to do here? :)

**Comment by dschmitz89** [comment]
@tupui : could you rerun the refguide check for this PR? Was not aware before that it was not executed when I had added the skip CI flags.

Or is there a way for contributors to trigger CI again?

**Comment by tupui** [comment]
Sorry I don't have access to Azure, only CircleCI and GH actions. You can retrigger by doing a force push and change the commit message. (Note that we ask contributors to not force push and rebase before discussing with reviewers as it breaks GH history/links as it's based on hashes)

**Comment by dschmitz89** [comment]
DId a minor adjustment to shorten the explanation what the exponentially scaled functions are good for. Ready to go in now I think , tests are passing.

**Review by tupui — APPROVED** [review]
Thanks LGTM

**Pull request merged**
