### PR TITLE
MAINT: Clean up 32-bit platform xfail markers

### LINKED ISSUE #2254: linalg.eig test failure (test_singular) (Trac #1735)
_Original ticket http://projects.scipy.org/scipy/ticket/1735 on 2012-09-22 by @rgommers, assigned to unknown._

See http://article.gmane.org/gmane.comp.python.scientific.user/32362 and follow up mails to that one.

This is not just a sign difference like Matthew had observed, values are actually different.

```
I installed rc2 on Python 2.7.3.  Same problem.  I get the test_singular
error on some, but not all, of the runs.  Both are win32-superpack from
http://sourceforge.net/projects/scipy/files/scipy/0.11.0rc2/.

The error occurs on less than half but more than 1/3 (based on a very
small sample) of the runs on both 2.7 and 3.2.

I've been working on computers for more than 50 years.  Somehow, I had
developed the delusion that they were deterministic .....
john

------------- Python 2.7 --------------------
 >>> import scipy
 >>> scipy.test()
Running unit tests for scipy
NumPy version 1.6.2
NumPy is installed in C:\Python27\lib\site-packages\numpy
SciPy version 0.11.0rc2
SciPy is installed in C:\Python27\lib\site-packages\scipy
Python version 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit
(Intel)]
nose version 0.11.2

======================================================================
FAIL: test_decomp.TestEig.test_singular
Test singular pair
----------------------------------------------------------------------
Traceback (most recent call last):
   File
"C:\Python27\lib\site-packages\nose-0.11.2-py2.7.egg\nose\case.py", line
186, in runTest
     self.test(*self.arg)
   File
"C:\Python27\lib\site-packages\scipy\linalg\tests\test_decomp.py", line
201, in test_singular
     self._check_gen_eig(A, B)
   File
"C:\Python27\lib\site-packages\scipy\linalg\tests\test_decomp.py", line
188, in _check_gen_eig
     err_msg=msg)
   File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line
800, in assert_array_almost_equal
     header=('Arrays are not almost equal to %d decimals' % decimal))
   File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line
636, in assert_array_compare
     raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

array([[22, 34, 31, 31, 17],
        [45, 45, 42, 19, 29],
        [39, 47, 49, 26, 34],
        [27, 31, 26, 21, 15],
        [38, 44, 44, 24, 30]])
array([[13, 26, 25, 17, 24],
        [31, 46, 40, 26, 37],
        [26, 40, 19, 25, 25],
        [16, 25, 27, 14, 23],
        [24, 35, 18, 21, 22]])
(mismatch 25.0%)
  x: array([ -2.45037885e-01 +0.00000000e+00j,
          5.17637463e-16 -4.01120590e-08j,
          5.17637463e-16 +4.01120590e-08j,   2.00000000e+00
+0.00000000e+00j])
  y: array([ -3.74550285e-01 +0.00000000e+00j,
         -5.17716907e-17 -1.15230800e-08j,
         -5.17716907e-17 +1.15230800e-08j,   2.00000000e+00
+0.00000000e+00j])

----------------------------------------------------------------------
Ran 5490 tests in 103.250s

FAILED (KNOWNFAIL=14, SKIP=36, failures=1)
<nose.result.TextTestResult run=5490 errors=0 failures=1>
 >>>

-------------- Python 3.2 --------------
 >>> scipy.test()
Running unit tests for scipy
NumPy version 1.6.2
NumPy is installed in C:\Python32\lib\site-packages\numpy
SciPy version 0.11.0rc2
SciPy is installed in C:\Python32\lib\site-packages\scipy
Python version 3.2.3 (default, Apr 11 2012, 07:15:24) [MSC v.1500 32 bit
(Intel)]
nose version 1.0.0

======================================================================
FAIL: test_decomp.TestEig.test_singular
----------------------------------------------------------------------
Traceback (most recent call last):
   File
"C:\Python32\lib\site-packages\nose-1.0.0-py3.2.egg\nose\case.py", line
188, in runTest
     self.test(*self.arg)
   File
"C:\Python32\lib\site-packages\scipy\linalg\tests\test_decomp.py", line
201, in test_singular
     self._check_gen_eig(A, B)
   File
"C:\Python32\lib\site-packages\scipy\linalg\tests\test_decomp.py", line
188, in _check_gen_eig
     err_msg=msg)
   File "C:\Python32\lib\site-packages\numpy\testing\utils.py", line
800, in assert_array_almost_equal
     header=('Arrays are not almost equal to %d decimals' % decimal))
   File "C:\Python32\lib\site-packages\numpy\testing\utils.py", line
636, in assert_array_compare
     raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 6 decimals

array([[22, 34, 31, 31, 17],
        [45, 45, 42, 19, 29],
        [39, 47, 49, 26, 34],
        [27, 31, 26, 21, 15],
        [38, 44, 44, 24, 30]])
array([[13, 26, 25, 17, 24],
        [31, 46, 40, 26, 37],
        [26, 40, 19, 25, 25],
        [16, 25, 27, 14, 23],
        [24, 35, 18, 21, 22]])
(mismatch 25.0%)
  x: array([ -2.450e-01 +0.000e+00j,   5.176e-16 -4.011e-08j, 5.176e-16
+4.011e-08j,
          2.000e+00 +0.000e+00j])
  y: array([ -3.746e-01 +0.000e+00j,  -5.177e-17 -1.152e-08j, -5.177e-17
+1.152e-08j,
          2.000e+00 +0.000e+00j])
```

### PR DESCRIPTION
**Pull request by larsoner**
Inspired by #2254

Let's see if this upsets Azure.

### CODE REVIEW

**Comment by larsoner** [comment]
Azure seems to have concluded that this is a 32-bit vs 64-bit issue.

**Comment by rgommers** [comment]
So for now change the `xfail` to depend on `is_32bit_platform`?

**Comment by larsoner** [comment]
Looks like I should have waited to see what Travis did before drawing any conclusions. It's broken on most of the Linux builds, too:

https://travis-ci.org/scipy/scipy/builds/569949127

This PR still has a potentially useful unification of `xfail_on_32bit`, though, so I can revert the original intended change (i.e., put the global skip back in) and then just have this PR be a little test refactor/unification.

**Comment by pv** [comment]
Ok, yes, the Travis runs are I guess still on old atlas/lapack. So I guess we'll just give up for now and keep the issue open. I think it is likely a lapack issue in the end.

(Also, I think for these failures it's not actually 32-bitness that is the issue, but it just happened to correlate with some other thing occurring on the platforms we were testing at the time.)

**Comment by rgommers** [comment]
Message looks clear now, so this is a simple cleanup. Merging, thanks @larsoner and @pv

**Pull request merged**
