### PR TITLE
 Add a custom query to be run at LGTM.com

### PR DESCRIPTION
**Pull request by RasmusSemmle**
I had the idea to define a number of queries that look for problematic numerical calculations. This one looks for `sqrt(a**2 + b**2)` which could be replaced with `hypot(a, b)`.
A run against a recent snapshot can be seen here: https://lgtm.com/query/1506571736017/

Some of the results appear to be in test files, it is possible to exclude those.

If the results seem like noise to you or if you have suggestions for more important numerical errors to look for, I am quite interested to hear about it.

### CODE REVIEW

**Comment by rth** [comment]
That's a nice idea! Is there a way for different projects to re-use the same query without including it in the repo (e.g. if it's included in a third party repository)? For instance this could be quite useful for numpy or scikit-learn as well, but maintaining multiple copies of this script doesn't sound ideal.

**Comment by RasmusSemmle** [comment]
You are quite right, and we do have a concept of query packs. However, we a re not yet able to share these between projects, that feature should land sometime mid 2019. So for now, copying is the way to go.

**Comment by rgommers** [comment]
Thanks @RasmusSemmle. I'd be interested in using such queries in queries, but given how long and unreadable the query is I think maintaining them as CI scripts within SciPy looks like more effort than it's worth. 

This one also only turned up instances in test and benchmark code only, where the performance difference isn't really interesting. So for now I'm -0.5 on this.

**Comment by RasmusSemmle** [comment]
@rgommers I think two of the instances are not in test code. I have made the query filter out the other results to make that clear.
I also added some comments to hopefully make the code easier to read, let me know what you think.
You can see a run of the updated query here: https://lgtm.com/query/1506632226012/

**Comment by rgommers** [comment]
Thanks @RasmusSemmle, that looks a bit clearer. And you're right, 2 instances in `lsqr.py`.

**Comment by rgommers** [comment]
I'd personally still prefer to wait for the feature to share between projects, so this can be maintained externally. If other devs want to maintain this I won't oppose it though - let's see what others think.

**Comment by RasmusSemmle** [comment]
Btw, when run on LGTM.com, test files are automatically filtered out, so I removed this check from the PR (I had left it in along with the comments). As you can see, [the benchmark directory is empty](https://lgtm.com/projects/g/scipy/scipy/latest/files/benchmarks/) until you click `Show excluded files`.

**Comment by rgommers** [comment]
Going through the PR list, I am closing this. Thanks for the idea though @RasmusSemmle. 

I do want to figure out how we feel about running LGTM for PRs - NumPy has done that for a while, and it's been unobtrusive and useful in some cases I think.

- We don't want to maintain custom queries
- We don't want to get triggers for the full list of defects (there's a lot of better ignored ones and issues in vendored code that we don't want to fix in https://lgtm.com/projects/g/scipy/scipy/alerts/?mode=list)
- We **may** want to do the same as NumPy, looking at alerts for added/changed lines of code.

@tylerjereddy @eric-wieser @charris I'm interested in your thoughts in how useful this has been for numpy. 

Setup seems easy enough, just a webhook and no config file.

**Comment by larsoner** [comment]
I've found it useful in other repos, it has found real issues. You can use a config file to tweak some things, including what you actually want it to check, see for example [this file](https://github.com/mne-tools/mne-python/blob/master/.lgtm.yml).

**Comment by tylerjereddy** [comment]
I guess it is pretty rare lately that we use it for finding issues in NumPy, probably because the default is generally not to fail CI. But one can look in its results and find things that are probably useful to fix over time.

I've had less success trying to get low-level static analyzers beyond LGTM to detect useful things for NumPy, but I'd still like to see that improve someday.

**Pull request closed without merging**
