### PR TITLE
MAINT: prevent overwriting of x in minimize

### LINKED ISSUE #13740: Scipy.optimize x0 out of bounds when it is within bounds.
This error is the same as in #11403 and #13556, but here I have a concrete example when the error occurs.

The error is as stated, `scipy.optimize.minimize` raises an error that says that `x0` is out of bounds, when it is within bounds.
Additionally, I checked that `minimize` throws the error after multiple iterations, so it is not about `x0` at all.

#### Reproducing code example:
First, you need to download `emissions.npy` from [here](https://dl.dropboxusercontent.com/s/9jab8cjnhgrihkl/emissions.npy).

```python
#!/usr/bin/env python3

import scipy
import scipy.optimize
import numpy as np
import sys

print('Python version:', sys.version_info)
print('Scipy version: ', scipy.__version__)
print('Numpy version: ', np.__version__)

with open('emissions.npy', 'rb') as f:
    emission_matrix = np.load(f)

def minus_lik(fractions):
    fractions -= scipy.special.logsumexp(fractions)
    return -np.sum(scipy.special.logsumexp(fractions[:, np.newaxis] + emission_matrix, axis=0))

n_rows = emission_matrix.shape[0]
x0 = np.full(n_rows, -np.log(n_rows))
bounds = np.zeros((n_rows, 2))
bounds[:, 0] = np.log(1e-5)
assert np.all(bounds[:, 0] < x0) and np.all(x0 < bounds[:, 1])

sol = scipy.optimize.minimize(minus_lik, x0=x0, bounds=bounds, method='L-BFGS-B')
```

#### Error message:
```
Traceback (most recent call last):
  File "./test.py", line 25, in <module>
    sol = scipy.optimize.minimize(minus_lik, x0=x0, bounds=bounds, method='L-BFGS-B')
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 620, in minimize
    callback=callback, **options)
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 360, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 261, in fun_and_grad
    self._update_grad()
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 231, in _update_grad
    self._update_grad_impl()
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_differentiable_functions.py", line 152, in update_grad
    **finite_diff_options)
  File "/home/timofey/.miniconda3/envs/py37/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 451, in approx_derivative
    raise ValueError("`x0` violates bound constraints.")
ValueError: `x0` violates bound constraints.
```

#### Scipy/Numpy/Python version information:
```
Python version: sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)
Scipy version:  1.6.1
Numpy version:  1.19.2
```

### PR DESCRIPTION
**Pull request by andyfaff**
Closes #13740.

In that issue the user function was overwriting the `x` vector it was supplied with. This means that `x` and `fun(x)` are no longer in the correct functional relationship within the minimizer. This would break most of the methods in `minimize`. This PR copies `x` before it's sent to the user function. It will add overhead, the only alternative is to post a big notice saying don't overwrite `x` in your user function because it will break the minimizer functionality.

Luckily, now that most, if not all, minimizers use `ScalarFunction` it's just a case of making the changes to one file.

### CODE REVIEW

**Comment by tupui** [comment]
I am not sure about copying as you said it introduce some overhead. Another possibility would be to make the array read only with `x.flags.writeable = False`. What do you think?

**Comment by andyfaff** [comment]
It's an extra couple of lines over the copy. Copying a `(30,)` array on my computer only takes 1.5 us, so I'd probably say a copy was preferable. Copying also allows the user to alter the array if they wanted to.

**Comment by tupui** [comment]
True it's for the params so it would always be relatively small. I guess it's fine then if we don't want to force the user into something.

**Review by tupui — COMMENTED** [review]
What about adding a test with an optimizer instead? This way we could pass all optimizers and check that they all pass.

**Review by tupui — APPROVED** [review]
LGTM with the new test. Thanks!

**Comment by tupui** [comment]
Do you want to wait for another review or should we merge?

**Comment by andyfaff** [comment]
I'm reasonably happy with it. If you're happy to merge it, then I'm happy for you to do that.

**Pull request merged**
