### PR TITLE
MAINT: basinhopping callback for initial mininmisation

### LINKED ISSUE #13011: Callback is not called with local minima of initial guess in basinhopping algorithm
My issue is about ...

As far as I understand, callback function is called when a local minima is found. When I use basinhopping global minimization algorithm, I have observed that the callback function is not called when local minima is found for initial guess. I have tried to reproduce this issue with the following example:

```
from scipy.optimize import basinhopping
import numpy as np

def func(x):
    print("Objective function count: " + str(func.counter))
    func.counter += 1
    return np.random.rand(1)*1000

def callback_func(x, f, accepted):
    print("Callback count: " + str(callback_func.counter))
    callback_func.counter += 1

func.counter = 0
callback_func.counter = 0    
x0 = 2000

minimizer_kwargs = {"method": "COBYLA", "options":{"maxiter": 1}}
optimizer = basinhopping(func, x0, minimizer_kwargs=minimizer_kwargs, niter=2, callback=callback_func)
```

It produces following result:

```
Objective function count: 0
Objective function count: 1
Callback count: 0
Objective function count: 2
Callback count: 1
```
For the above mentioned example, both callback function and the objective function should have been called thrice but callback is called only twice.

#### Scipy/Numpy/Python version information:
 1.2.1 1.16.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by andyfaff**
Closes gh-13011

### CODE REVIEW

**Comment by andyfaff** [comment]
Construction of the BasinHoppingRunner causes the local minimizer to run. The callback isn't called with the results of that initial minimisation. This PR corrects that.

**Comment by rgommers** [comment]
The refguide check failure is real.

**Comment by andyfaff** [comment]
@rgommers, fixed the refguide check and rebased. Hopefully this should be a quick merge now.

**Review by rgommers — APPROVED** [review]
Thanks @andyfaff, LGTM now.

**Pull request merged**
