### PR TITLE
TST:special:Add partial tests for nrdtrimn and nrdtrisd

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Related : #19953 

#### What does this implement/fix?
Adds partial tests for special functions. 

It seems to me that the generic testing infra we have right now is not suitable for customization of parameter domains and it is a bit convoluted. It takes quite some investigation to see what is going on and debugging what failed. Hence I think there is domain expertise needed for the rewrite of the testing suite.

But at least it is better than nothing for now.

### CODE REVIEW

**Comment by ilayn** [comment]
Failures don't seem relevant.

**Review by steppi — APPROVED** [review]
Thanks @ilayn. The tests look good. I've been planning to work on improving the test infrastructure stuff for special functions and will find some time to fit it in over the next couple months. Did you mean to include the noncentral t updates here? If so, can you split the PR into two commits, one for the tests, and one for the noncentral t updates? After that, I'll do a regular merge.

**Comment by ilayn** [comment]
Ah yes looks like I used the wrong branch for fixes. Will fix

**Comment by ilayn** [comment]
Let me get this in so we don't have merge conflicts for other additions, thanks @steppi !

**Pull request merged**
