### PR TITLE
BLD: enforce utf-8 in tools/cythonize.py, and some cleanups

### PR DESCRIPTION
**Pull request by ilayn**
#### What does this implement/fix?
Since until Python 3.15 there is no default `utf-8` encoding in file `open` handles, the CI jobs use whatever encoding they prefer locally (one GH job prefers `cp1252`). This results with strange `UnicodeError` exceptions even in files that are not changed but only opened from *NIX to Win or vice versa. Here if opened in text mode, all files are opened via 'utf-8' encoding to normalize the file handling. 

Also some PEP8 cleanup to streamline the business logic.

### CODE REVIEW

**Comment by rgommers** [comment]
This seems fine to me to refactor if that's useful to you @ilayn  (maybe for reuse elsewhere?) and it passes the `Windows tests / cp310 (setup.py bdist_wheel)` CI job. I'm not sure though if you noticed that this is no longer used in the Meson build, and we'll delete it together with `setup.py` files at some point in the not-so-far future?

**Comment by ilayn** [comment]
Yes sure, just to get it out of the way of PRs. I am indeed looking forward that we get rid of these things but until then tiny cleanup here, a bit ironing there.

**Comment by eli-schwartz** [comment]
Since the PR title mentions enforcement rather than just "using" utf-8, I figured I would mention how I solved the same general problem in meson: https://github.com/mesonbuild/meson/pull/10050

Sadly due to the intentional inefficiency of CPython itself, I needed to add runtime-installed code to the mesonbuild module to actually perform filtering -- `$PYTHONWARNINGS` and `python -W` are... not useless, but very crippled.

Basically, the testsuite sets up two environment variables so that:
- python emits warnings whenever you don't specify an encoding at all
- meson installs a warning filter to make EncodingWarning a fatal error

The testsuite will then fail with an exception every time `open` handles are created without specifying an encoding -- even for cases that aren't as easily greppable as `open(`, such as the two meson cases I fixed which used `ConfigParser().read()`.

**Comment by rgommers** [comment]
That does seem like a good idea @eli-schwartz, thanks for sharing. I'll open a follow-up issue for that, to see if there's a volunteer for implementing that.

**Review by rgommers — APPROVED** [review]
This all LGTM, thanks @ilayn.

**Pull request merged**
