### PR TITLE
DOC: _binomtest.py: Add clearer error messages

### PR DESCRIPTION
**Pull request by EwoutH**
Print actual values if `ValueError`s occur in `stats/_binomtest.py`.

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]

**Review by lucascolley — CHANGES_REQUESTED** [review]
CI failures are real as there are regex tests which need to be updated.

**Comment by mdhaber** [comment]
I was waiting to merge until CI passes. I figured that some error message tests might fail.

**Comment by EwoutH** [comment]
You guys are very fast with reviewing, thanks!

I can take a look at the tests tomorrow morning (CET time), but I see you already started, which is perfect by me.

**Comment by mdhaber** [comment]
@lucascolley I went ahead and updated the tests. Care to take a look?

**Review by lucascolley — APPROVED** [review]

**Comment by lucascolley** [comment]
thanks @EwoutH !

**Comment by EwoutH** [comment]
Thanks for reviewing, updating the tests and merging so quickly!

**Pull request merged**
