### PR TITLE
TST: parameterize the test cases in test_ndimage.py

### PR DESCRIPTION
**Pull request by grlee77**
#### Reference issue

@rgommers, @stefanv:  This PR is related to our NumFOCUS Small Development Grant. I will be working on the actual fixes to boundary handling, etc. in subsequent, smaller PRs.

Do you think it is worth opening a new issue related to the proposal to keep links to the relevant issues and PRs all in one place?

#### What does this implement/fix?

This PR refactors the huge number of tests in `test_ndimage.py` so that they are parameterized. This will make it much easier to see which specific cases are failing while working on other parts of the proposal.

It is probably easiest to review these as individual commits. There are a ton of lines changed, but they are almost all just basic replacement of for loops by parameterization.  There should be no changes to the existing test behavior with the following two exceptions (fixing bugs in the existing tests):

1.) A number of the `test_rotate*` cases had a for loop over `order`, but never actually passed the order on to `ndimage.rotate`. This has been fixed by f7aa8297.

2.) Several of the `distance_transform` test cases had improper indentation in the loop over dtypes. Only the array creation was within the loop, but the actual tests should have been as well. This has also been fixed along with the other dtype changes in bc09de2.

#### Additional information

A downside of this refactoring is that it increases the test duration a bit due to some additional duplication of effort on array creation, etc. For the whole ndimage module, the time to run all tests increases from ~2.1 seconds to ~5.3 seconds on my machine. I think this 3 second increase is acceptable.

Two additional things I am considering, but wanted to get some feedback on whether it is desirable first:
1.) This `test_ndimage.py` file is nearly 5000 lines of code. I think it would make sense to split these tests across:
`test_filters.py`, `test_interpolation.py`, `test_measurements.py`, `test_morphology.py` and `test_fourier.py`.

2.) Given that most of these tests do not share common parameters, we don't gain anything by having them grouped in a class like this (i.e. there is no common setup code). Should we just make most of these standalone functions instead?

### CODE REVIEW

**Comment by stefanv** [comment]
@grlee77 I'll leave some feedback, but since I have been out of a loop with SciPy for a while these are mere suggestions.

- Yes, I think a meta-issue to track your work would be valuable as a central overview.
- Yes, I think breaking up the test suite organized by functionality makes sense (there's no need to have such large files hanging around, it just complicates editing).
- The parameterized code reads more cleanly to me; i.t.o. slowdown, can you use fixtures to speed things up?

**Comment by rgommers** [comment]
Thanks Greg, this looks good!

+1 on the tracking issue, that will be useful.

> A downside of this refactoring is that it increases the test duration a bit due to some additional duplication of effort on array creation, etc. For the whole ndimage module, the time to run all tests increases from ~2.1 seconds to ~5.3 seconds on my machine. I think this 3 second increase is acceptable.

I agree, I wouldn't worry about this. The `'full'` test suite now takes 2 seconds; for other scipy modules it's many times more - a few seconds increase is easier to recover by, e.g., speeding up some `stats` function rather than spending a lot of effort here.

> Yes, I think breaking up the test suite organized by functionality makes sense (there's no need to have such large files hanging around, it just complicates editing).

I agree

> Given that most of these tests do not share common parameters, we don't gain anything by having them grouped in a class like this (i.e. there is no common setup code). Should we just make most of these standalone functions instead?

I've just had a brief browse through test files, and most tests are in functions while the ones that don't seem to have some commonality. So not sure how many tests you're talking about. If you're already touching those tests and it's a matter of "delete `class TestXxx:` line, deindent code" then please go for it.

**Comment by grlee77** [comment]
> I've just had a brief browse through test files, and most tests are in functions while the ones that don't seem to have some commonality. So not sure how many tests you're talking about. If you're already touching those tests and it's a matter of "delete class TestXxx: line, deindent code" then please go for it.

This is true for some of the files, but not `test_ndimage.py`. Here is a class with >4000 lines of code within it. `setup_method` was removed in this PR when refactoring to use parametrization over dtypes.
https://github.com/scipy/scipy/blob/d3416c7675d45c81bd19dfed36267832ddc453b9/scipy/ndimage/tests/test_ndimage.py#L51-L63, so there is no common setup at all for the test methods in the class.

There are blocks of 5-10 test methods that use the same input data, etc that could be grouped into a class with a common `setup_class` method, but doing that manually for the whole file is likely to be pretty time consuming so I have not attempted it for now.

**Comment by grlee77** [comment]
Thanks for the feedback. I have now split up the tests:

- Commit de5eca8 breaks up the test suite, moving all tests from `test_ndimage.py` to corresponding files matching the submodule names (e.g. test_interpolation.py, test_filters.py, etc). No changes to test behavior were made.

- Commit efc172b moves the handful of test cases in `test_regression.py` to these same files. (Note: the move for `test_byte_order_median` accidentally got committed along with the other changes in de5eca8 which is why it appears missing from the diff for this commit).

**Comment by larsoner** [comment]
Instead of using setup_class, I would have then all make use of a single pytest fixture that supplies the parametrized data. Then they can stay as functions but also follow DRY.

**Comment by grlee77** [comment]
> I would have then all make use of a single pytest fixture that supplies the parametrized data. Then they can stay as functions but also follow DRY.

I think the issue with this is that there are a few hundred test functions with only small subsets sharing the same data and/or kernels as input. For that reason it seems like a test fixture returning a dictionary containing all of these input arrays (probably dozens of them) would be harder to read and understand than the current state where the user can at least see the data array directly in the test case itself and more quickly reason about what is being tested. This is especially true given that most of these test cases do not have descriptive names (e.g. `test_correlate22`, etc.) so only by looking at the inputs is it obvious what aspect is being tested. Ideally these tests would be renamed to something more descriptive, but that would also be fairly time consuming and we have only a limited amount of effort funded under the proposal.

A second caveat is that many of the parameterized tests would still need to cast the data to another `dtype`, so it may not actually save all that much time to pregenerate it. Given that we are only talking about a couple of seconds gain at most it did not seem worth the effort.

**Review by rgommers — APPROVED** [review]
This all looks good. Code coverage of `ndimage` files is unchanged, so nothing got lost. Bug fixes to the tests are nice, and I agree that fixtures aren't needed (or even desirable).

CI seems happy, modulo an unrelated failure in `signal`. Let's get this in. Thanks @grlee77!

**Comment by grlee77** [comment]
Thanks @rgommers, now I can rebase the other boundary handling PRs and add tests there without having to deal with conflicts

**Pull request merged**
