### PR TITLE
DEP: interpolate: remove incidental imports from private modules

### PR DESCRIPTION
**Pull request by j-bowhay**
Follow up to https://github.com/scipy/scipy/pull/20612 and https://github.com/scipy/scipy/pull/21754

These two pr introduced new deprecated submodules through the use of `_sub_module_deprecation`. Now the deprecation is over, we can clear up the things that shouldn't be importable.

### CODE REVIEW

**Comment by j-bowhay** [comment]
Xref #22159 for mypy failures

**Comment by h-vetinari** [comment]
> Follow up to #20612 and #21754

The latter PR only landed in 1.15. Shouldn't we wait for another release for that part?

**Comment by j-bowhay** [comment]
> > Follow up to #20612 and #21754
> 
> The latter PR only landed in 1.15. Shouldn't we wait for another release for that part?

Good point thanks, will adjust

**Comment by mdhaber** [comment]
I confirmed that all the functions removed from `__all__` should not be importable and that the message for `dfitpack.py` states that these will be removed in 1.16.0. I think this PR will be good to go when the `interpnd.py` stuff is removed?

**Review by mdhaber — APPROVED** [review]

**Comment by mdhaber** [comment]
Feel free to self-merge when tests pass.

**Pull request merged**
