### PR TITLE
Fix defaut value for 'mode' in 'ndimage.shift' in the doc

### LINKED ISSUE #9383: Default value for "mode" in "ndimage.shift"
In scipy.ndimage.shift the mode's default value is 'constant', but [in the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.shift.html#scipy.ndimage.shift) it says Default is 'reflect'.
Which of the two is wrong?

### PR DESCRIPTION
**Pull request by lbellomo**
This PR references this issue I submitted earlier.

Fixes #9383

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
Thanks! This looks good and matches the suggested fix from @ilayn. I think Ilhan has also been working hard on the CI issues, which here appear to be unrelated to the simple doc change.

Also, worth noting that we normally prefix commits and PR titles related to documentation with `DOC:`. For other changes, [there's a list here](https://docs.scipy.org/doc/numpy-1.15.0/dev/gitwash/development_workflow.html#writing-the-commit-message).

Probably good to go, but I'll let Ilhan confirm / merge.

**Comment by ilayn** [comment]
Thanks a lot @lbellomo for reporting it and for the PR. It is indeed good to go. Keep them coming 😃

**Comment by lbellomo** [comment]
I did not know about prefixes, I'll be more attentive for the next time.

**Comment by ilayn** [comment]
Oops we basically forgot to check the other use cases. Ralf mentioned it in #9262 but we overlooked it here. I'll close that one as a duplicate.

**Pull request merged**
