### PR TITLE
MAINT:  1.12.0rc2 prep

### PR DESCRIPTION
**Pull request by tylerjereddy**
Backports included (so far):

1. gh-19735
2. gh-19748
3. gh-19751
4. gh-19761
5. gh-19709
6. gh-19779
7. gh-19785
8. gh-19800
9. gh-19806 (merge conflicts resolved manually on the second commit)
10. gh-19830
11. gh-19842
12. gh-19859

TODO:

- [x] depend on a stable release of Pythran that pulls in `setuptools` per gh-19795
- [x] confirm that conda-forge release manager is happy; a few test tol bumps may still be needed I think cc @h-vetinari 
- [x] gradually turn the CI back on, and eventually test the wheel builds here again, but for now cirrus and circle are both skipped (full doc build still passing locally and full suite passing on x86_64 Linux locally; and so far backports are small patches)

### CODE REVIEW

**Comment by h-vetinari** [comment]
> * a few test tol bumps may still be needed I think cc @h-vetinari

Opened a PR: #19800 
(we can manage even if it doesn't get backported, but would be nice to have)

**Comment by h-vetinari** [comment]
If we want compatibility with pytest 8.0 (the just released rc1 shows up in the prerelease job), we also need the first two commits from https://github.com/scipy/scipy/pull/19806 (I want to avoid squash-merging it for reasons explained in the PR).

**Comment by dschmitz89** [comment]
One more backport candidate as it fixes a bug in my opinion: https://github.com/scipy/scipy/pull/19779

**Comment by tylerjereddy** [comment]
Ok, I'll be sure to carefully make the requested additional backports. If you think it should be backported and doesn't have the label yet, it is also useful to add it. I can always remove it if there's a gruesome merge conflict or something like that.

**Comment by lucascolley** [comment]
gh-19830 updated the copyright to 2024

**Review by rgommers — APPROVED** [review]
All changes and the plan for next steps LGTM

**Review by h-vetinari — APPROVED** [review]

**Comment by tylerjereddy** [comment]
See gh-19846 and gh-19847 for what is going on with the pre-release job, which is actually using NumPy `1.26.3` with `pytest` pre-release at the moment. I think I'll probably disable the pre-release job here, we often do that on maintenance branches, and it is particularly chaotic with pre-release NumPy 2.0 and `pytest` 8.x happening at the same time.

**Comment by lucascolley** [comment]
damn, the bot is playing up again. I don't have time to look into it in the next few days unfortunately.

**Comment by tylerjereddy** [comment]
I'm not sure what to make of the Python `3.11` Windows sdist job failure in the absence of Pythran. I see a few things in the log like `..\scipy\meson.build:482: WARNING: The variable(s) 'PYTHRAN_INCDIR', 'PYTHRAN_VERSION' in the input file 'scipy\__config__.py.in' are not present in the given configuration data.` and `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '.\\.mesonpy-feqwgwl_\\meson-private\\cmake_scipy-openblas\\CMakeFiles\\CMakeScratch`.

That failure persisted through a restart of the job, and `scipy-openblas` isn't actually being used according to the config stage (assuming that path refers to the package on PyPI..).

**Comment by h-vetinari** [comment]
> I'm not sure what to make of the Python `3.11` Windows sdist job failure in the absence of Pythran.

This looks pretty unrelated to pythran, or perhaps it's triggering a bug somewhere else (e.g. somehow, a race or duplication for creating scratch space for scipy-openblas).
```
+ meson dist --allow-dirty --no-tests --formats gztar
WARNING: Repository has uncommitted changes that will not be included in the dist tarball
Created D:\a\scipy\scipy\.mesonpy-sgr84eaw\meson-dist\SciPy-1.12.0rc2.tar.gz
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\shutil.py", line 624, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '.\\.mesonpy-sgr84eaw\\meson-private\\cmake_scipy-openblas\\CMakeFiles\\CMakeScratch'
```

**Comment by tylerjereddy** [comment]
It is showing up in PRs against `main` now too, so I think it is "ok" for me to proceed with testing wheel builds and considering this non-specific to the release branch: gh-19852

**Comment by tylerjereddy** [comment]
@mdhaber do you recognize the MacOS ARM wheel test failures for `TestRankData` related to `np.nan` handling? I tried locally with NumPy `1.22.4` during build phase, and latest stable NumPy during test phase, with the same version of Python on Mac ARM, and didn't immediately reproduce.

**Comment by tylerjereddy** [comment]
Studying the MacOS ARM64 Python `3.9` failure, in particular for `test_nan_policy_omit_3d`, `rankdata` appears to be returning an integer type array instead of float64, where there are zeros instead of `np.nan` at various locations. We do deviate from `main` on `rankdata`, but only via an enhancement in gh-19776, not via a bugfix. It is also a bit hard to imagine why this would start failing in RC2 vs. RC1.

I did do some side-by-side log diffing against a previous success in Cirrus, and nothing immediately stood out to me re: dependency versions that were suspiciously different. Matching the versions of the deps locally on an ARM Mac still isn't reproducing for me either.

**Comment by tylerjereddy** [comment]
Maybe I'll give https://github.com/cirruslabs/cirrus-cli a go in the morning, to see if I can get some traction locally.

**Comment by rgommers** [comment]
> in particular for `test_nan_policy_omit_3d`, `rankdata` appears to be returning an integer type array instead of float64, where there are zeros instead of `np.nan` at various locations

I don't see the cause of the problem here yet (and can't reproduce with cython 3.0.8 and numpy 1.22.4 on macOS arm64), but the `rankdata` behavior doesn't look good. The dtype of the returned array should not be depending on both the value of the `method` keyword and the values in the array (it's always `float64` if `nan`s are present, and it may be integer if no `nan`s).

In `main` the way the function has been written has been improved, but in 1.12.x there's additionally a not so great recursive implementation using `np.apply_along_axis` that interplays with the lack of type stability. The bug comes down to this:
```python
>>> import numpy as np
>>> def func(x):
...     if np.isnan(x).any():
...         return x.astype(np.float64)
...     else:
...         return x.astype(np.int64)
...
>>> np.apply_along_axis(func, 0, np.array([[0, np.nan], [1, 2]])).dtype
dtype('int64')
>>> np.apply_along_axis(func, 0, np.array([[np.nan, 0], [1, 2]])).dtype
dtype('float64')
```

Final problem is probably that the random numbers used in the test aren't stable (`hash('falafel')` is not a fixed seed!), so the above issue occurring is going to depend on details of how `hash` is implemented for the given CPython version and platform.

Since the implementation already has been improved in `main`, I recommend to change the seed to a fixed value that makes the test pass in 1.12.x in this PR - if it has a `nan` in position [0, 0] things should work.

**Comment by rgommers** [comment]
That seeding problem is more widespread. I'll turn this into a new issue for `rankdata` and will fix up the problems in `main`.

**Comment by tylerjereddy** [comment]
Two more backports were added in (updated the original list above), a random seed fix for `test_nan_policy_omit_3d` was added thanks to Ralf's analysis above, and the release notes were updated again.

After checking that full test suite and doc build pass locally, I've proceeded straight to another test of the full wheel builds, to see where we stand now.

**Comment by tylerjereddy** [comment]
CI is fully green, including regular + wheel builds, in it goes.

**Comment by h-vetinari** [comment]
FWIW, [testing](https://github.com/conda-forge/scipy-feedstock/pull/262) of rc2 in conda-forge is looking good!

**Pull request merged**
