### PR TITLE
ENH: stats: trying to figure out how to wrap a simple C++ class

### PR DESCRIPTION
**Pull request by mdhaber**
I'm trying to figure out how to wrap a simple C++ class. I've added the files from the [Using C++ in Python](https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html) tutorial, but I don't understand how to make it all build with the rest of SciPy.  I'm sure there are examples elsewhere in SciPy, but I haven't found one that is simple enough to adapt.

@mckib2 I've started to read your [guide](https://github.com/scipy/scipy/wiki/Cython-Wrappers#id3) and I think it could be really helpful. One thing that would help me to see in there would be to start with a simple Hello World example, maybe like this Rectangle class but simpler - like literally just a Hello World function. For example, I wrote [this](http://scipy.github.io/devdocs/dev/contributor/cython.html) for speeding up Python code with Cython.  (If there is one already, I apologize - but it all looks generic right now; it doesn't look like I can actually build the example code provided, right?)

_Update: for the record, I intended for this to be a PR on my own repo's master. Sorry for the noise._

### CODE REVIEW

**Comment by mdhaber** [comment]
I'll read gh-8575 more closely.

**Comment by rgommers** [comment]
Depending on how large the thing is you're intending to wrap, you may want to look at whether to use Cython or Pybind11 as the wrapping tool - we already have both in SciPy.

**Comment by ev-br** [comment]
Feel free to ping me for wrapping with cython

**Comment by mdhaber** [comment]
Thanks @ev-br. I've gotten this basic example working, and I'll reach out if I have trouble with the noncentral hypergeometric distribution code that I'm really trying to wrap.

**Comment by larsoner** [comment]
@mdhaber it would be great if you could document the process somewhere (dev docs?) so that the next time we need to do it, there is at some basic template to follow.

**Comment by mdhaber** [comment]
Yes, we will.

**Pull request closed without merging**
