### PR TITLE
DOC: Add building command in Dev quickstart

### LINKED ISSUE #14785: BUG: Conda installation not working
### Describe your issue.

While following the [development quickstart for installing scipy](https://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html#quickerstart-conda), I always encounter the following message error while importing scipy : 

```bash
$ python -c "import scipy"

Traceback (most recent call last):
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 126, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 131, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.
```

### Reproducing Code Example

Just run the installation guide : 

```bash
# Create an environment with all development dependencies
conda env create -f environment.yml  # works with `mamba` too
conda activate scipy-dev

# Initialize git submodules
git submodule update --init

# Build SciPy for development work plus run tests
python runtests.py    # Alternatively, it's fine to use `python setup.py develop`

# Install SciPy in develop mode in conda
conda develop .

```

and then try to import SciPy : 
```
python -c "import scipy"
```
### Error message

```shell
Traceback (most recent call last):
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 126, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 131, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.
```

### SciPy/NumPy/Python version information

```bash
python -c "import sys, numpy; print(numpy.__version__, sys.version_info)"
1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
```

### Additional information
I tried to put the `$PYTHONPATH` variable to successively : 
* `~/miniconda3/envs/scipy-dev/lib/python3.9`
* `path-to/scipy`

I tried some other issues on GitHub or Stackoverflow, but it doesn't appear to be correlated to this one

### PR DESCRIPTION
**Pull request by V0lantis**
#### Reference issue

Closes gh-14785

#### What does this implement/fix?

Add a command line in the DOC.

#### Additional information

For more informations, read issue gh-14785.

Maybe `conda develop .` is not working as intended and should have a fix. I didn't find any documentation on [*conda.io*](https://conda.io).

### CODE REVIEW

**Review by tupui — APPROVED** [review]
LGTM, thanks @V0lantis. I will let this open until Friday (feel free to ping me if I forget) in case others want to pitch in.

**Review by rgommers — COMMENTED** [review]
The issue here is not limited to this one place. The trouble is that `runtests.py` was introduced as a "friendly" wrapper to make life easy and have a single interface for all development-related tasks. However, the extra level of indirection can be annoying, that's why we also have in-place build instructions floating around. Which then becomes more confusing.

However, the better fix is probably to keep `runtests.py` as the interface (also because there will be no such thing as an in-place build for Meson). So the better fix here would be to adjust `conda develop .`. I think it should be something like `conda develop build/testenv` (not tested).

**Comment by ev-br** [comment]
The beauty of `runtests.py` is that there is no need to look inside of it :-). All the black magic is contained inside, and we can just run it.

**Comment by ev-br** [comment]
> python tools/refguide_check.py --doctests ndimage

`$ python runtests.py -s ndimage --refguide-check`

**Comment by ev-br** [comment]
> My point is that this is not documented somewhere and one needs to look into the available options to see this for someone who is new.

Doc PR is very very welcome! Seriously,  as you recently figured it out, you are in the best position for it.

**Comment by rgommers** [comment]
I read through this again, the correct thing to do here seems to be to just delete these two lines:
```

    # Install SciPy in develop mode in conda
    conda develop .
```
They serve no purpose here.

**Comment by tupui** [comment]
Sorry I am not sure I follow, I thought we said we should not use `setup.py` to build but `runtest.py` and `conda develop ...` to set the path correctly?

**Comment by rgommers** [comment]
> I think that this could be confusing and would need some extra note. What about adding a print of the path to add in the PYTHONPATH when the build script runs?

I think this is the worst place for that. It's the "how to get started the fastest way possible". Teaching two incompatible methods there doesn't really make sense.

I just checked `build_ext` usage througout the docs, and unfortunately it's wrong pretty much everywhere. The place where it's explained best is https://numpy.org/devdocs/dev/development_environment.html. 

The tl;dr is: either use `runtests.py` always, or never. If always, no need for `conda develop .` or `PYTHONPATH`. If never, then use your regular workflow for in-place builds.

**Comment by tupui** [comment]
Ok thanks. I understand your rational and agree that this is not the best place.

**Comment by V0lantis** [comment]
Thank you all for the comment. I apologize for the long time for updating, it got out of my mind. I removed the `conda devlop . ` line as requested

**Comment by rgommers** [comment]
Thanks @V0lantis. Your update still mixed the two methods, so I went ahead and removed the inplace build part. Let me merge this, the issue is addressed then.

**Pull request merged**
