### PR TITLE
CI: update CircleCI config for `master` to `main` branch rename

### PR DESCRIPTION
**Pull request by rgommers**
Let's see if this comes back green ....

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge once CircleCI comes back happy.

FYI in the future you can push with `[skip actions] [skip azp]` to save some other CI cycles

**Comment by rgommers** [comment]
> FYI in the future you can push with `[skip actions] [skip azp]` to save some other CI cycles

I know, but in this case I do want to see all CI because we just renamed `master` to `main` - it could all be broken.

**Comment by jarrodmillman** [comment]
I thought I took care of this in #15314.

**Comment by rgommers** [comment]
> I thought I took care of this in #15314.

Ah yes you did, I got my wires crossed on branches when looking for a quick PR to trigger CI. Missed a `git pull` after setting up my `main` locally. Leaving this open to see CI status, then I'll close.

**Comment by jarrodmillman** [comment]
@rgommers I merged https://github.com/scipy/scipy.org/pull/430 and am ready to update netlify for scipy.org as soon as you rename its default branch.

**Comment by charris** [comment]
Might want to check scipy-wheels as well, especially nightly builds of master. I forget what other changes may be needed.

**Comment by rgommers** [comment]
> Might want to check scipy-wheels as well, especially nightly builds of master. I forget what other changes may be needed.

Probably best to leave the MacPython repos alone. Hopefully we're migrating away from them soon, and testing them is fragile. There's only a few users, so it's not really relevant.

**Comment by rgommers** [comment]
Okay, this is all happy, including docs deployment via https://github.com/scipy/devdocs. Closing.

**Pull request closed without merging**
