### PR TITLE
BUG: Use nogil contexts in cKDTree

### LINKED ISSUE #10514: cKDTree GIL handling is incorrect
I believe #9915 has introduced errors in ```cKDTree``` GIL handling.

Declaring a C++ function ```nogil``` in Cython does not ensure that the GIL is automatically released and reaquired. It only declares that it is allowed to call the function in a nogil context.

Releasing the GIL in Cython is accomplished with a ```with nogil:``` statement. There is no such statement in ```ckdtree.pyx```. Therefore, ```cKDTree``` does not release the GIL and all multithreading code is now defective.

We must either revert #9915 to keep GIL release and exception translation in C++ or fix ```ckdtree.pyx``` to actually release the gil.

### PR DESCRIPTION
**Pull request by sturlamolden**
#### Reference issue
Closes gh-10514

#### What does this implement/fix?
Ensures that the GIL is released in Cython before calling C++

#### Additional information
gh-9915 broke thread handling code when moving GIL handling to Cython

### CODE REVIEW

**Comment by sturlamolden** [comment]
The checks seem to be hanging. Is it possible to restart them? @rgommers

**Comment by rgommers** [comment]
all green now. good catch, thanks for fixing this @sturlamolden. I'll wait for @rainwoodman to review

**Review by larsoner — APPROVED** [review]

**Comment by sturlamolden** [comment]
Don't merge this yet, there is one thing I muct check first.

**Comment by sturlamolden** [comment]
No, it is ok :)

**Comment by sturlamolden** [comment]
We should have a "defect" label on this, not just maintenence, because all multithreading is broken. Also we should consider to backport to 1.3.x because the defect is present there as well.

**Comment by rainwoodman** [comment]
I only had one comment about the use of pointers, and @sturlamolden has explained it to me on https://github.com/scipy/scipy/issues/10514#issuecomment-514909192 .

**Comment by rgommers** [comment]
Great, in it goes. Thanks @sturlamolden! and @rainwoodman for the review

**Pull request merged**
