### PR TITLE
BLD: version-script handling in setup.py

### LINKED ISSUE #8680: scipy fails compilation when building from source
[scipy_build_tail.log](https://github.com/scipy/scipy/files/1876872/scipy_build_tail.log)

Building the scipy source from tip fails when compiling : 
This might be the offending line: Dont know how the line in BLOCK text showed up
**-L"Using built-in specs**

`
/opt/amba/cv22_third/tv2/exe/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.5/scipy/integrate/_quadpackmodule.o -L/opt/amba/cv22_third/tv2/release/atlas/3.10.3/lib -L"Using built-in specs.
`

PLEASE HELP. BLOCKING DEVELOPMENT 

### Error message:
```
building 'scipy.integrate._odepack' extension
compiling C sources
C compiler: gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -v -fPIC

```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'scipy' has no attribute '__version__'

```

### PR DESCRIPTION
**Pull request by tylerjereddy**
(apparently) Fixes #8680

### CODE REVIEW

**Comment by tylerjereddy** [comment]
@rc What do you think about the (stochastic?)`lobpcg` Windows Python 3.5 failure here?

**Comment by rgommers** [comment]
> @rc What do you think about the (stochastic?)lobpcg Windows Python 3.5 failure here?

looks like just a missing random seed, I'll send a PR now.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @tylerjereddy and @zerothi

**Comment by rc** [comment]
Wow, you are fast! :)

**Pull request merged**
