### PR TITLE
scipy.stats.pearsonr overflows with high values of x and y. #8980

### PR DESCRIPTION
**Pull request by antoinecarme**
Reorganized some computations to avoid overflows.

### CODE REVIEW

**Comment by antoinecarme** [comment]
https://circleci.com/gh/scipy/scipy/7710#tests/containers/0

Two pearsonr tests started failing following this change

test_r_exactly_pos1 and test_r_exactly_neg1

sample log : 
```
Items are not equal:
 ACTUAL: -0.9999999999999998
 DESIRED: -1.0
```

The pearsonr computation is now approximate. This very small difference is due to the fact that we separated the two sqrt computations. sqrt(2 * 2) and sqrt(2) * sqrt(2) are slightly different.

Not sure what was the original intent of these two tests. So if you are reviewing this, your feedback is welcome.

**Comment by antoinecarme** [comment]
The two failures are linked with this commit : 

```
BUG: stats: Eliminate the 'TINY' hack in pearsonr, so perfect correlttions return probability=0. Also allow for numerical errors that could make the computed value of r be less than -1.
```

https://github.com/scipy/scipy/commit/42c7426e9889adfef2dc55ed96a48ee4115974e6

**Comment by chrisb83** [comment]
Unfortunately, the simple test that `pearsonr(x, x) == 1.0` fails even for the simple choice of x in the test, which would lead to a new bug. Same for `pearsonr(x, -x) == -1.0`. 
I haven't thought about a solution...

**Comment by antoinecarme** [comment]
@chrisb83 

Thanks for your feedback.

We all agree that pearson(x. x) is 1.0 , at least on paper. But machine floating point arithmetic is , by design, not exact arithmetic. This is what I wanted to note by saying that   sqrt(2 * 2) and sqrt(2) * sqrt(2) are different (but not on paper, of course ;).

Statistically speaking, relying on exact equality of r with 1.0 does not make too much sense for assessing perfect correlation (r being above 0.9999 is more reliable as a test). Hope not a lot of scipy users rely on exact equality in their software.

To me , the problem is to know why these two tests required exact equality and not very approximate one (assert_equal versus assert_allclose(r, 1.0, atol=1e-12) for example). Adapting these two tests solves the problem. A feedback from the original test writer can be more efficient for choosing this solution.

**Comment by chrisb83** [comment]
Yes, i agree it is nothing critical but before the change the result was 1.0, it would bei nice to keep that. 

What about the following change to the original code: if there is an overflow error, one calls `pearsonr` again with suitably rescaled vectors (one option would be to devide by the maximum absolute value), otherwise continue as before. That Just came to my mind, maybe there are better ways.

**Comment by antoinecarme** [comment]
I also agree that there is no emergency. Just wanted to help, and if this PR is not merged , that's OK for me. There are failing tests after all.

For your proposition : 

1. testing if there is an overflow , I don't know how to do that, except by catching an exception. Catching an exception inside a computation is the last thing to do. The performance will decrease,

2. Rescaling the original vector : this is almost what is done when reorganizing the code in this PR. We divide x and y and sqrt(squm_sqrt_x) and sqrt(squm_sqrt_y) before summing and not after the summation. sqrt(squm_sqrt_x) has the same order of magnitude as abs(x) as you proposed.

Probably there is no solution, don't care. Is there a process to solve this kind of bug ? For me, this is rather  a statistical bug not software one.

**Comment by chrisb83** [comment]
I hope i did not discourage you, your help to close this issue is appreciated.
Regarding your last comment
1. Catching exceptions is sometimes used in other functions (as an example, i recently looked at `stats.ks_2samp`). But of course, there might be a better solution

2. Your solution is similar, but leads to sqrt * sqrt. It looks like this must be avoided.

We can also discuss further ideas in the thread of the issue where others had some suggestions.

**Comment by WarrenWeckesser** [comment]
@antoinecarme, thanks for working on this.  `pearsonr` was rewritten in https://github.com/scipy/scipy/pull/9562, which closed gh-8980 and several other issues related to overflow and underflow in the calculation.  This pull request looks redundant now, so I'm closing it.

**Pull request closed without merging**
