### PR TITLE
BUG: fix return type of erlang_gen._argcheck

### PR DESCRIPTION
**Pull request by armanbilge**
Should return condition array, not scalar, according to docs for `rv_continuous`.

### CODE REVIEW

**Review by tylerjereddy — CHANGES_REQUESTED** [review]
This entire code block is missed by unit tests, so a bug seems possible--the stats reviewers can confirm that.

I suspect they will ask for a regression test if they agree that this is a defect, especially given the current lack of coverage.

**Comment by ev-br** [comment]
Yup, looks like a bug. 

```
In [3]: from scipy.stats import gamma, erlang

In [4]: erlang.pdf(0.5, a=[1, -1])
Out[4]: nan

In [5]: gamma.pdf(0.5, a=[1, -1])
Out[5]: array([ 0.60653066,         nan])
```
A test case would be nice indeed (should go to e,g. scipy/stats/tests/test_distributions.py)

**Review by chrisb83 — APPROVED** [review]
Change makes sense, `_argcheck` should return a vector.

**Comment by armanbilge** [comment]
@tylerjereddy I added @ev-br's test case

**Comment by ev-br** [comment]
LGTM, thanks @armanbilge. Keep them coming :-)

**Pull request merged**
