### PR TITLE
MAINT: bundle Mathjax with built docs

### PR DESCRIPTION
**Pull request by pv**
Alternative to gh-7358

The bundled Mathjax is 5M, smaller than the generated images. Not sure about cross-browser friendliness.

Before merging, the scipy-mathjax submodule should be moved under the scipy organization, and we need also to decide whether we want to do it this way.

circleci: https://circle-artifacts.com/gh/scipy/scipy/2713/artifacts/0/home/ubuntu/scipy/doc/build/html-scipyorg/index.html

The scipy-mathjax repository (added as a submodule): https://github.com/scipy/scipy-mathjax
The `rebuild.sh` script there rebuilds (and commits) the stripped-down Mathjax package from scratch, so the rebuild process hopefully is reproducible in future if we need to update the bundled library.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
The [signal processing page](https://2713-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/tutorial/signal.html) renders pretty quickly on my desktop. It takes a couple of seconds on mobile. One minor disadvantage is in the "make mobile friendly" option in my browser, it doesn't render at all, whereas the static SVG from #7358 renders normally. But I do like that we don't have to ship as many binaries, so I don't have a strong opinion either way. If I had to choose one I'd go +0.5 for this (bundle-mathjax) method.

**Comment by pv** [comment]
ok, moved the submodule under scipy organization, so this is no longer WIP

However, the move seems to have confused circleci --- it looks like it's caching the old submodule from the previous build...

**Comment by Eric89GXL** [comment]
You can force it to rebuild without cache from the CircleCI UI. I'll do that now.

**Comment by pv** [comment]
That doesn't seem to affect the cached submodule.

**Comment by pv** [comment]
Travis-ci manages to check it out just fine, so this seems to be just circleci flaking out.

**Comment by Eric89GXL** [comment]
It looks like the "no cache" option doesn't prevent it from using the source cache `scipy/.git`, so that's probably the source of the(ir) problem.

**Comment by pv** [comment]
I'll close this PR and start a new one.

**Pull request closed without merging**
