### PR TITLE
MAINT: Add Python 3.8 to pyproject.toml

### PR DESCRIPTION
**Pull request by TheGreatCabbage**
#### What does this implement/fix?

Numpy 1.17.3 has now been released, with support for Python 3.8. 

This pull request adds Python 3.8 to `pyproject.toml` with Numpy 1.17.3.

### CODE REVIEW

**Comment by larsoner** [comment]
This has essentially the same changeset as #10930, @rgommers feel free to merge this one first if you want and I can rebase

**Comment by rgommers** [comment]
All right, done. Thanks @TheGreatCabbage and @larsoner

**Comment by grlee77** [comment]
Don't we also need to specify a higher Cython minimum version for Python 3.8?
I know there was a 3.8-related fix as recently as `0.29.12`, but I'm not sure if there was anything 3.8-specific in `0.29.13`

**Comment by rgommers** [comment]
It may require Cython master actually, not sure. @charris can you comment? what did you use for NumPy 1.17.3?

**Comment by charris** [comment]
```
charris@fc [numpy.git (master)]$ python3 -mcython --version
Cython version 0.29.13
```
IIRC, the fixes in that version are needed.

**Comment by tylerjereddy** [comment]
adding backport label on assumption this may be needed for 3.8 support in SciPy 1.3.2--please remove label if I don't need it.

**Pull request merged**
