### PR TITLE
BUG: linalg: fix eigh(1x1 array, driver='evd') f2py check

### LINKED ISSUE #20512: BUG: `eigh` fails for size 1 array with driver=evd
### Describe your issue.

Hi! I found that `evd` driver crashes for size-1 array due to lwork computation. Other drivers are fine.

I think the simplest would be to deal with size 1 at the same moment as size 0.

### Reproducing Code Example

```python
import numpy as np
import scipy.linalg as la

a = np.ones((1, 1))
s, u = la.eigh(a, driver="evd")
```

### Error message

```shell
error: (lwork>=(compute_v?1+6*n+2*n*n:2*n+1)) failed for 3rd keyword lwork: dsyevd:lwork=1
```

### SciPy/NumPy/Python version and system information

```shell
python `3.10.10`
numpy `1.23.5`
scipy `1.10.1` # (also present in dev)
```

### PR DESCRIPTION
**Pull request by ev-br**
f2py check was just too strict;
LAPACK docs indicate that for N=1, lwork>=1 is acceptable:

```
*  LWORK   (input) INTEGER
*          The dimension of the array WORK.
*          If N <= 1,               LWORK must be at least 1.
*          If JOBZ = 'N' and N > 1, LWORK must be at least 2*N+1.
*          If JOBZ = 'V' and N > 1, LWORK must be at least
*                                                1 + 6*N + 2*N**2.
```

https://www.netlib.org/lapack/explore-3.1.1-html/ssyevd.f.html

closes gh-20512

The issue is not new, observed with scipy 1.9.1 at least.

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
LGTM!

**Comment by ogauthe** [comment]
Thank you for the quick fix. I found that `lwork` computation also crashes for size-0 arrays for `syevr` and `syevx`. Thanks to #20372 it is no more called in such a case and `eigh` returns early, so I don't know if it is worth fixing `lwork`.

**Comment by ogauthe** [comment]
Also, the same issue affects `heevd`. So I think the same fix should be applied at line 183

**Comment by ev-br** [comment]
size-0 arrays are probably not worth it. The invariant is that lapack should never see arrays with `.size == 0`, they all should be filtered out at the python level.

**Comment by ev-br** [comment]
> Also, the same issue affects heevd. So I think the same fix should be applied at line 183

Indeed. PR updated.

**Review by tylerjereddy — APPROVED** [review]
I verified that reverting either of the checks individually is sufficient to trigger regression test failure, so that seems pretty robust.

**Comment by tylerjereddy** [comment]
Squash-merged for backporting, thanks.

**Pull request merged**
