### PR TITLE
MAINT: Remove Python2 module init

### PR DESCRIPTION
**Pull request by sethtroisi**
Continued work on Python2 code cleanups #11584

### CODE REVIEW

**Comment by sethtroisi** [comment]
Failure is from test timeout (at 98%). Would you like me to close / open to rerun tests are is it clear that this change is good from compilation and most tests passing.

**Comment by sethtroisi** [comment]
Friendly ping, this is green and only delete codes

**Review by tylerjereddy — APPROVED** [review]
Ok, I've reviewed all the changes & they look ok + CI is green. Thanks @sethtroisi

**Comment by sethtroisi** [comment]
Thanks Tyler

**Pull request merged**
