### PR TITLE
Actually propagate nans through stats functions with nan_policy="propagate"

### LINKED ISSUE #5817: BUG: skew, kurtosis return np.nan instead of "propagate"
Initial guess

I thought "propagate" just calculates with nans in the arrays, like np.sum, so we get the correct shape with just some extra nans.

Instead we get a scalar nan back
https://github.com/scipy/scipy/blame/v0.17.0/scipy/stats/stats.py#L1319

possible candidate for 
https://github.com/statsmodels/statsmodels/pull/2800

```
>>> aa = np.arange(5 * 4.).reshape(5,4)
>>> aa[0,1] = np.nan
>>> np.sum(aa, 0)
array([ 40.,  nan,  50.,  55.])
>>> from scipy import stats
>>> stats.kurtosis(aa, axis=0)
array([-1.3,  nan, -1.3, -1.3])
>>> stats.skew(aa, axis=0)
array([  0.,  nan,   0.,   0.])
```

```
>>> scipy.__version__
'0.15.1'
```

### PR DESCRIPTION
**Pull request by ev-br**
Stop special-casing nan_policy="propagate" in reduction functions, so that the shape of the result does not depend on whether inputs contain nans or not.

closes gh-5817

### CODE REVIEW

**Comment by ev-br** [comment]
This has been confirmed to fix the failure in statsmodels, https://github.com/statsmodels/statsmodels/pull/2800#issuecomment-196437080. Would still be nice to have a second pair of eyes on it

**Comment by Eric89GXL** [comment]
I looked and it makes sense to me to the extent I understand the idea (which is not so well). Maybe ping a statsmodel person to look?

**Comment by ev-br** [comment]
I did, in the link above

**Comment by Eric89GXL** [comment]
Any idea what the original intent was of all the `if contains_nan and nan_policy == 'propagate':` lines? That's the thing that's bothering me, seems like someone put in effort to put all those there. But maybe it was just a lot of copypaste.

**Comment by ev-br** [comment]
Not really. Maybe @rgommers or @aeklant would remember. AFAICS, these shortcuts would make perfect sense for scalar only arguments. Otherwise, contains_nan != is_all_nans for vector inputs.

**Comment by Eric89GXL** [comment]
That would make sense. +1 for merge from me, but I won't be offended if you
wait for another set of eyes more familiar with these functions

**Comment by ev-br** [comment]
Has been a while. I'm going to merge this soon (tm) unless further comments.

**Comment by josef-pkt** [comment]
Looks good to me. Sorry for being a bit absent.

The initial idea was to "ignore" nans, which is what this looks like now.

**Comment by ev-br** [comment]
Merging. 
Thanks Josef, Eric.

**Comment by WarrenWeckesser** [comment]
It was a mistake to remove the special case handling of `nan_policy='propagate'` from `scipy.stats.spearmanr`.  Don't take `'propagate'` to literally mean "do the calculation and let the chips fall where they may".  In the case of `spearmanr`, the function is documented to return `nan` when the data contains `nan` and `nan_policy` is `'propagate`.  Now it returns results that are basically meaningless.  (If you know the details of the implementation and how `nan` is handled when an array is sorted, you can assign a meaning to the result, but I don't see how that would be useful to anyone.)

**Comment by josef-pkt** [comment]
@WarrenWeckesser   It is cheap to check for nans in `rankdata` because they will be sorted to the end (i.e. just check last row when axis=0). So instead of changing propagate in spearmanr, it might be better to add `propagate` to rankdata, and maybe add general nanhandling option to it.

**Comment by WarrenWeckesser** [comment]
If there is a better way to fix the problem, great.  My only point is that `spearmanr` should return `nan`s when the input contains `nan`s and `nan_policy` is `'propagate'`.

**Pull request merged**
