### PR TITLE
DOC: sparse.csgraph simple examples.

### PR DESCRIPTION
**Pull request by peterSweter**
I have created simple  examples for the following sparse.csgraph functions:

sparse.csgraph (18)
    connected_components
    shortest_path
    floyd_warshall
    dijkstra
    bellman_ford
    johnson
    breadth_first_order
    depth_first_order
    reverse_cuthill_mckee
    maximum_bipartite_matching
    structural_rank
    construct_dist_matrix
    reconstruct_path
    csgraph_masked_from_dense
    csgraph_from_dense
    csgraph_from_masked
    csgraph_to_dense
    csgraph_to_masked

### CODE REVIEW

**Comment by peterSweter** [comment]
I don't understand why Travis CI is failing. The log says:

```
Failed example:
    csgraph_masked_from_dense(graph)
Expected:
    masked_array(data =
     [[-- 1 2 --]
     [-- -- -- 1]
     [-- -- -- 3]
     [-- -- -- --]],
                 mask =
     [[ True False False  True]
     [ True  True  True False]
     [ True  True  True False]
     [ True  True  True  True]],
           fill_value = 0)
Got:
    masked_array(
      data=[[--, 1, 2, --],
            [--, --, --, 1],
            [--, --, --, 3],
            [--, --, --, --]],
      mask=[[ True, False, False,  True],
            [ True,  True,  True, False],
            [ True,  True,  True, False],
            [ True,  True,  True,  True]],
      fill_value=0)
```

When I run the test locally I have masked_array printed without commas separating elements in the array. In Numpy masked_array examples, masked_array is printed without commas: https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

**Comment by rgommers** [comment]
That will depend on the numpy version you use I think. The documentation checker on TravisCI uses the latest version, so 1.14.4. In numpy 1.13.x-1.14.x there was quite a mess with array formatting changes.

Just changing it in your example to the "Expected" format above should be fine.

**Comment by rgommers** [comment]
Thanks @peterSweter, these examples look good!

**Comment by pv** [comment]
Depends on numpy version, the tests use latest (1.14.4).

pe 8. kesäkuuta 2018 klo 13.05 Piotr Uchwat <notifications@github.com>
kirjoitti:

**Comment by rgommers** [comment]
LGTM now, merging. Thanks @peterSweter

**Pull request merged**
