### PR TITLE
BLD: meson, explicitly add xsimd as dependency

### LINKED ISSUE #15698: BLD: meson build failure - missing `xsimd.hpp`
### Describe your issue.

Using `environment_meson.yml`. 
Ubuntu: 20.4
python 3.10
Conda: 4.11.0

Build fails with missing `hpp` file  
`python dev.py --build-only`

```
In file included from scipy/stats/_hypotests_pythran.cpp:24:
/home/eduardo/miniconda3/envs/scipy-meson/lib/python3.10/site-packages/pythran/pythonic/include/numpy/ceil.hpp:8:10: fatal error: xsimd/xsimd.hpp: No such file or directory
    8 | #include <xsimd/xsimd.hpp>
```

I noticed the compilation command includes: `-I"${CONDA_PREFIX}"/include/python3.10` but the `xsimd` files are located at `${CONDA_PREFIX}"/include` (notice the path on command  has an extra `python3.10` in path).

### Reproducing Code Example

```python
python dev.py --build-only                             (scipy-meson) 
The Meson build system
Version: 0.61.2
Source dir: /home/eduardo/work/scipy/scipy-doit
Build dir: /home/eduardo/work/scipy/scipy-doit/build
Build type: native build
Project name: SciPy
Project version: 1.9.0.dev0
C compiler for the host machine: cc (gcc 9.4.0 "cc (GCC) 9.4.0")
C linker for the host machine: cc ld.bfd 2.36.1
C++ compiler for the host machine: c++ (gcc 9.4.0 "c++ (GCC) 9.4.0")
C++ linker for the host machine: c++ ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Library m found: YES
Fortran compiler for the host machine: gfortran (gcc 9.4.0 "GNU Fortran (GCC) 9.4.0")
Fortran linker for the host machine: gfortran ld.bfd 2.36.1
Program cython found: YES (/home/eduardo/miniconda3/envs/scipy-meson/bin/cython)
Program pythran found: YES (/home/eduardo/miniconda3/envs/scipy-meson/bin/pythran)
Program cp found: YES (/usr/bin/cp)
Program python3 found: YES (/home/eduardo/miniconda3/envs/scipy-meson/bin/python3.10)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Found pkg-config: /home/eduardo/miniconda3/envs/scipy-meson/bin/pkg-config (0.29.2)
Library npymath found: YES
Library npyrandom found: YES
Run-time dependency openblas found: YES 0.3.18
Dependency openblas found: YES 0.3.18 (cached)
Program _build_utils/cythoner.py found: YES (/home/eduardo/miniconda3/envs/scipy-meson/bin/python3.10 /home/eduardo/work/scipy/scipy-doit/scipy/_build_utils/cythoner.py)
Checking for function "open_memstream" : NO 
Configuring messagestream_config.h using configuration
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Checking for size of "void*" : 8
Run-time dependency threads found: YES
Checking for size of "void*" : 8
Dependency threads found: YES unknown (cached)
Compiler for C++ supports arguments -fvisibility=hidden: YES (cached)
Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
Compiler for C++ supports arguments -Wno-format-truncation: YES 
Compiler for C++ supports arguments -Wno-class-memaccess: YES 
Build targets in project: 196

SciPy 1.9.0.dev0

  User defined options
    prefix: /home/eduardo/work/scipy/scipy-doit/build-install
```

### Error message

```shell
Meson build setup OK
ninja: Entering directory `build'
[794/1557] Compiling C++ object scipy/stats/_h....p/meson-generated_..__hypotests_pythran.cpp.o
FAILED: scipy/stats/_hypotests_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__hypotests_pythran.cpp.o 
c++ -Iscipy/stats/_hypotests_pythran.cpython-310-x86_64-linux-gnu.so.p -Iscipy/stats -I../scipy/stats -I/home/eduardo/miniconda3/envs/scipy-meson/lib/python3.10/site-packages/pythran -I/home/eduardo/miniconda3/envs/scipy-meson/lib/python3.10/site-packages/numpy/core/include -I/home/eduardo/miniconda3/envs/scipy-meson/include/python3.10 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -O2 -g -fPIC -Wno-unused-function -Wno-unused-variable -Wno-deprecated-declarations -Wno-int-in-bool-context -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -MD -MQ scipy/stats/_hypotests_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__hypotests_pythran.cpp.o -MF scipy/stats/_hypotests_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__hypotests_pythran.cpp.o.d -o scipy/stats/_hypotests_pythran.cpython-310-x86_64-linux-gnu.so.p/meson-generated_..__hypotests_pythran.cpp.o -c scipy/stats/_hypotests_pythran.cpp
In file included from scipy/stats/_hypotests_pythran.cpp:24:
/home/eduardo/miniconda3/envs/scipy-meson/lib/python3.10/site-packages/pythran/pythonic/include/numpy/ceil.hpp:8:10: fatal error: xsimd/xsimd.hpp: No such file or directory
    8 | #include <xsimd/xsimd.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
[803/1557] Compiling C++ object scipy/sparse/s...ls.cpython-310-x86_64-linux-gnu.so.p/bsr.cxx.o
ninja: build stopped: subcommand failed.
Build failed!
```

### SciPy/NumPy/Python version information

(1.9.0.dev0', '1.22.2', sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by schettino72**
#### Reference issue
Closes gh-15698

#### What does this implement/fix?
Fix build error.

#### Additional information
First time I use meson, not sure this is the best approach!

### CODE REVIEW

**Comment by ev-br** [comment]
1) how is gh-15698 related? 
2) what is the problem thus PR means to address? 
3) what is xsimd, why it is needed universally?

**Comment by ev-br** [comment]
CI is unhappy:

```
Run-time dependency xsimd found: NO (tried pkgconfig and cmake)

scipy/meson.build:89:2: ERROR: Dependency "xsimd" not found, tried pkgconfig and cmake
```

**Comment by schettino72** [comment]
xsimd is a development dependency of pythram.

I got the error using CONDA as documented here: https://scipy.github.io/devdocs/dev/contributor/meson.html

Surprised to see that CI is using pip instead of conda. 
Is meson build using pip supposed to be supported as well?
I have not tried meson build using pip yet...

**Comment by ev-br** [comment]
> Surprised to see that CI is using pip instead of conda.
> Is meson build using pip supposed to be supported as well?

It certainly is supported and it does work just fine. So the issue here seems to be conda-specific

**Comment by ev-br** [comment]
Actually, cannot repro the original issue even with conda: https://github.com/scipy/scipy/issues/15698#issuecomment-1065873321

**Comment by schettino72** [comment]
It was an easy fix to make it work on pip based environments as well.

I guess that CI failures now are not related.
Let me know if you think there is anything else that needs work.

**Comment by ev-br** [comment]
Okay, CI being green modulo expected timeouts is a good sign, I've removed the needs-work label. 

I don't really understand what's going on here, so I'm going to defer to Ralf or Matthew about this PR.

**Review by rgommers — COMMENTED** [review]
Thanks @schettino72 for digging into this issue. I haven't seen it yet, it seems to be a conda(-forge) bug. Adding a direct dependency on `xsimd` is not really something we want, at best it's a workaround for a packaging bug. Let's try and get to a conclusion about what is going on exactly on gh-15698 before deciding on whether to (temporarily) merge this PR or not.

The way you added the dependency looks correct by the way.

**Comment by schettino72** [comment]
Turns out this problem was caused by incorrect setup of conda environment using FISH.

**Pull request closed without merging**
