### PR TITLE
TST: Speedup test_pascal which is VERY slow on Azure

### PR DESCRIPTION
**Pull request by sethtroisi**
#### What does this implement/fix?

This test takes an average of *10 minutes!!!!* on azure, yet locally it takes only ~2 seconds!

### CODE REVIEW

**Comment by person142** [comment]
Hm based on your changes is it falling back to software handling of denormal numbers or something?

**Comment by sethtroisi** [comment]
@person142 I don't know know this test is 100x slower. Most of the other tests are in the range of 2-10x slower on Azure than my PC.

**Comment by tylerjereddy** [comment]
See also: https://github.com/scipy/scipy/issues/11704

**Comment by rgommers** [comment]
Can't hurt, so let's merge this one. Thanks @sethtroisi

**Pull request merged**
