### PR TITLE
ENH: improve scipy.interpolate.RegularGridInterpolator performance

### PR DESCRIPTION
**Pull request by zebengberg**
#### What does this implement/fix?

This PR reimplements the `scipy.interpolate.RegularGridInterpolator._evaluate_linear` method to be slightly more performant.

To compute linear interpolation over an n-dimensional grid, the `_evaluate_linear` method iterates over the vertices of an n-d hypercube. The previous implementation uses `np.where` to determine the "weights" to attach to the grid values at a vertex. These weights can instead be directly inferred from the vertex iteration order. The proposed implementation included here takes this approach, eliminating the unnecessary call to `np.where`. This change gives a nontrivial speedup in most situations.

#### Additional information

I wrote a set of benchmarks specifically for the `RegularGridInterpolator`. Below are the results of running the benchmarks locally.

*Previous implementation*

```
              --                                          n_samples
              ----------------------- --------------------------------------------------
               ndim   max_coord_size       10        100          1000         10000
              ====== ================ =========== ========== ============= =============
                2           10          177±7μs    213±20μs     311±40μs    1.03±0.03ms
                2           40         160±0.8μs   197±9μs      338±10μs    1.31±0.05ms
                2          200          177±7μs    184±9μs      356±20μs     1.89±0.2ms
                3           10          291±20μs   318±10μs     462±30μs     1.88±0.1ms
                3           40          309±10μs   339±20μs     589±20μs     2.29±0.2ms
                3          200          310±7μs    311±3μs      678±70μs     3.26±0.1ms
                4           10          544±30μs   566±10μs    1.05±0.1ms    3.80±0.3ms
                4           40          601±40μs   601±20μs    976±100μs     4.10±0.7ms
                4          200          661±10μs   744±50μs   1.38±0.03ms    9.26±0.3ms
```

*New implementation this PR aims to merge*

```
              --                                        n_samples
              ----------------------- ----------------------------------------------
               ndim   max_coord_size      10        100        1000        10000
              ====== ================ ========== ========== ========== =============
                2           10         142±8μs    151±4μs    229±5μs      907±20μs
                2           40         136±10μs   153±30μs   260±8μs     1.20±0.1ms
                2          200         146±9μs    152±7μs    289±20μs    1.54±0.2ms
                3           10         239±40μs   255±30μs   401±80μs    1.58±0.3ms
                3           40         204±10μs   223±10μs   401±80μs    1.85±0.2ms
                3          200         205±20μs   262±30μs   533±60μs    2.63±0.1ms
                4           10         311±20μs   316±9μs    565±20μs   2.36±0.06ms
                4           40         298±20μs   354±20μs   687±20μs    3.75±0.3ms
                4          200         395±30μs   423±10μs   910±70μs    7.65±0.4ms
```

### CODE REVIEW

**Comment by Kai-Striega** [comment]
> I haven't noticed that particular issue for my use cases. With the RegularGridInterpolator, I find that if the grid itself can fit into memory, then I can readily interpolator over it. 

I tried your example, it works fine for me too. The example in gh-7663 does not work for me, despite working with a smaller array. Weird. Maybe it has something to do with meshgrid? 

I'm trying to figure out why this benchmark runs so much quicker than my benchmark in gh-7663. Sorry to be a pain, but could you give that benchmark a go?

> If you do Cythonize the _evaluate_linear method, know that it does n * 2^n iterations in the double for-loop, where n is dimension of the underlying grid. I've found the slowest step is the fancy indexing (self.values[edge_indices] in the source code).

Thanks. I'll keep that in mind. I don't think there's much we can do to improve the n * 2^n part is there?

**Comment by zebengberg** [comment]
> I tried your example, it works fine for me too. The example in [gh-7663](https://github.com/scipy/scipy/issues/7663) does not work for me, despite working with a smaller array. Weird. Maybe it has something to do with meshgrid?
> 
> I'm trying to figure out why this benchmark runs so much quicker than my benchmark in [gh-7663](https://github.com/scipy/scipy/issues/7663). Sorry to be a pain, but could you give that benchmark a go?

I checked out your benchmarks in #7663 . I'm definitely seeing a memory explosion when `n` gets large. The RGI calls down to [`_ndim_coords_from_arrays`](https://github.com/scipy/scipy/blob/b4857872e7ccbcfa86ad06e001c10334843dc0b7/scipy/interpolate/interpnd.pyx#L157), which broadcasts the arrays `xg` and `yg` against each other. In other words, you'd see the same memory footprint as if you created `xg` and `yg` with `np.meshgrid(..., sparse=False)`.

I think the RGI is most useful when the input `xi` into the`__call__` method is somewhat small relative to the size of the underlying grid. This is the case with my example in the thread above ... there, the underlying grid has shape `(30000, 30000)`, whereas the `xi` only has one million entries ... small relative to the `30000 x 30000` size of the grid.

I also looked at the implementation of `interp2d`. I'm seeing a memory explosion when the [`regrid_smth`](https://github.com/scipy/scipy/blob/b4857872e7ccbcfa86ad06e001c10334843dc0b7/scipy/interpolate/src/fitpack.pyf#L630) subroutine is called. I don't really understand what's happening there, but for me, it chewed up 3x the memory of `z` grid itself. This may be causing your unexpected crashes.

> I don't think there's much we can do to improve the n * 2^n part is there?
Right ... that seems intrinsic to the algorithm!

**Review by Kai-Striega — APPROVED** [review]
The changes look good to me. I've run the changes locally and seen similar performance improvements. @ev-br is there anything you see that's stopping us from merging?

**Comment by ev-br** [comment]
Nope, this looks great, go for it @Kai-Striega !

**Comment by Kai-Striega** [comment]
Great work @zebengberg, thanks for taking the time to contribute!

**Pull request merged**
