### PR TITLE
EHN: Update constants.codata to CODATA 2014

### PR DESCRIPTION
**Pull request by sargas**
Straightforward inclusion of the newest CODATA recommendations. This doesn't appear to affect any tests. Fixes issue #5047.

### CODE REVIEW

**Comment by charris** [comment]
Not sure what is going on with the one failing test. Might want to take a look at the test output by hitting the `Details` button above.

**Comment by pv** [comment]
The tests notice the value quoted in the docstring of precision() needs to be updated.

OTOH, in the examples one should also change
```
>>> from scipy.constants import codata
>>> codata.value('elementary charge')
```
to
```
>>> from scipy import constants
>>> constants.value('elementary charge')
```

**Comment by sargas** [comment]
Thanks, I forgot to run the doctests. They actually bug out on my computer (159 errors, 197 fails), but the latest commit seems to pass the doctests in `scipy.constants`.

**Comment by pv** [comment]
Do you mean `python runtests.py --refguide-check` fails for you (with matplotlib and Pillow installed)? If so, the failures could be interesting to know (e.g. paste in gist.github.com).

If doctests are run from standard doctest runner, failures are expected, since some custom processing is used to ignore e.g. matplotlib return values.

**Comment by sargas** [comment]
I didn't realize the doctests aren't supposed to be run with `python runtests.py --doctests`. I have no errors running `python2 runtests.py --refguide-check`.

**Comment by charris** [comment]
Oops, slipped through the cracks. Thanks @sargas .

**Pull request merged**
