### PR TITLE
WIP: optimize: added (dense) interpolative decomposition redundancy removal to linprog

### PR DESCRIPTION
**Pull request by mdhaber**
Thanks @pv and @inducer for bringing the interpolative decomposition to my attention.

For most problems, the interpolative decomposition is a faster way to identify redundant rows in an equality constraint matrix than the routines currently in `linprog`. 

Here is a plot of the _total_ `linprog` solution time (dense, interior-point) on my computer for several Netlib problems (featuring redundancy) with 

1. interpolative decomposition-based redundancy removal (current PR) and
2. pivot-based redundancy removal (master*).

image

\* pivot-based redundancy removal results are from #9636/#9263, which is not strictly the master branch. However, there is no reason to suspect that the times for today's master would be significantly different.

Note that the old pivot-based redundancy removal routine produced incorrect results for problem "SHELL"; the interpolative decomposition removes the redundant rows correctly.

For problems without redundancy, this PR should not affect execution time at all.

The results above include the _total_ `linprog` execution time, so the difference looks small. @touqir14 and I have been working on comparing results for problems from the SJSU Singular Matrix Database; the improvement can be substantial.

### CODE REVIEW

**Comment by mdhaber** [comment]
Note: tests used randomized interpolative decomposition because of #9793. I intend to expose this and use of the old redundancy removal routines as an option.

**Comment by mdhaber** [comment]
Holding off on this to finish the paper. 
Also doing tests to determine whether it's faster to do a rank test + randomized ID or a single (deterministic) rank-revealing QR (which also identifies redundant rows).

**Comment by Kai-Striega** [comment]
Sorry I missed this PR. I think it looks good 👍. W.R.T randomised vs not, do you know if it will effect the performance (other than being reproducible?). I'll take a look at #9793 if you like.

**Comment by mdhaber** [comment]
@Kai-Striega thanks for taking a look. The randomized version should be faster, but I don't know how much faster. Thanks for offering to take a look at #9793. I would appreciate that, but there's not a rush. I imagine it's easy, as there is an obvious workaround, but it might be nice to trace the problem to its root.

**Comment by Kai-Striega** [comment]
@mdhaber as the issue has been patched, would you take a look at merging this?

**Comment by mdhaber** [comment]
I could, but I will probably want to mess with it again after we (@touqir14 and I) do more thorough tests. 

Also, rather than removing the pivot-based routine, I'd rather expose the redundancy removal method as an option.

So I'd rather let this sit or close it for now, if you think that is better.

**Comment by mdhaber** [comment]
Tests are ongoing, so I won't choose the default behavior, but I will add to this PR the ability to select the RR method with an option.

**Comment by touqir14** [comment]
I think its worth adding an option for indicating whether the input A is a symmetric positive semidefinite matrix. For symmetric PSD matrices, there is a way to find independent rows/collumns using cholesky decomposition much faster than ID and RRQR.

**Comment by mdhaber** [comment]
OK. After this is merged, a mechanism for selecting the redundancy removal will be available, and then I'd be happy to review a PR for a PSD-specific redundancy removal option.

**Comment by ilayn** [comment]
Cholesky won't help for semidefinite matrices. I think you meant [LDLt](https://scipy.github.io/devdocs/generated/scipy.linalg.ldl.html)

**Comment by touqir14** [comment]
Yes I meant about the LDL decomposition, a variant of cholesky

**Comment by touqir14** [comment]
@mdhaber , I have been comparing the speeds of (deterministic) ID and RRQR and from what I have seen, RRQR is a faster algorithm whenever the rank is not small compared to min(m,n) where A is a m by n matrix. For example, for large enough matrices ID needs the rank to be about an order smaller than min(m,n) to perform similarly or faster than RRQR. Removing rows of a 10000 * 1000 matrix of rank 140 takes almost the same time for ID and RRQR. Keeping the ratio of rank to min(m,n) a constant and increasing the matrix size widens the performance gap between RRQR and ID which is why I am guessing RRQR will be used more often for large matrices. One approach would be to compute the rank of A to decide whether to use ID or RRQR. The numpy.linalg.matrix_rank method's speed is mostly comparable to performing an RRQR on A while other times a bit slower. Recently, I have devised an algorithm for finding the rank using the LDL decomposition (works for any real matrix - not necessarily PSD) which is a drastic improvement over the SVD approach generally leading to performance speedups of more than an order. I will post a PR soon on this.

**Comment by ilayn** [comment]
For rank revealing purposes, cholesky or ldlt are not suitable. It will be in general ill-conditioned or even numerically unstable.

**Comment by touqir14** [comment]
Scipy's LDL decomposition is reasonably stable and resistant to ill-conditioning. I was experimenting with different condition numbers. On my machine, it remained unaffected uptil a bit more than a condition number of 1e+17. LDL decomposition's complexity is O(n^3) with better constants than SVD's. So far based on my experiments, the rank computation approach based on LDL decomposition is accurate for reasonably conditioned matrices. There are some cases where I have seen it fail for highly ill-conditioned matrices and I am trying to see if it can be made accurate for those cases.

**Comment by mdhaber** [comment]
@touqir14 

> So far based on my experiments, the rank computation approach based on LDL decomposition is accurate for reasonably conditioned matrices.

We're talking about working with singular matrices, so the condition number is infinite, right?

>  I have been comparing the speeds of (deterministic) ID and RRQR 

Isn't deterministic ID computed from the results of RRQR? If so, how could deterministic ID be faster?

**Comment by mdhaber** [comment]
Superseded by gh-11249.

**Pull request closed without merging**
