### PR TITLE
clarify scipy.cluster.hierarchy.linkage usage

### PR DESCRIPTION
**Pull request by argriffing**
should address https://github.com/scipy/scipy/issues/2614 and https://github.com/scipy/scipy/issues/3401

### CODE REVIEW

**Comment by argriffing** [comment]
I've tried rebasing this PR in light of https://github.com/scipy/scipy/issues/5508.

**Comment by argriffing** [comment]
closing https://mail.scipy.org/pipermail/numpy-discussion/2016-January/074810.html

**Comment by perimosocordiae** [comment]
This PR deserves to be merged, so I'm reopening.

**Comment by perimosocordiae** [comment]
The rebased PR is up at #6342.

**Pull request closed without merging**
