### PR TITLE
ENH: vectorize along samples `stats.special_ortho_group.rvs`

### PR DESCRIPTION
**Pull request by Gattocrucco**
#### Reference issue

#16344

#### What does this implement/fix?

Currently `stats.special_ortho_group.rvs` loops in python over each random matrix to output. This PR vectorizes the algorithm to operate on all samples at once. For producing many 2x2 matrices, the speed increase is 120x.

### CODE REVIEW

**Comment by mdhaber** [comment]
To start, please consider how my feedback from https://github.com/scipy/scipy/pull/16574#pullrequestreview-1039755470 would apply here. Thanks!

**Comment by Gattocrucco** [comment]
Ok @mdhaber, I interpreted your comment as a request to add comments in the code about how the vectorization works.

**Comment by Gattocrucco** [comment]
@mdhaber ?

**Review by mdhaber — COMMENTED** [review]
I've gone through line by line. It all looks right, as far as I can tell, and I wasn't able to simplify individual lines much. 

Do you know whether this would be correct, though?
```python3
rvs = stats.ortho_group.rvs(dim, size, random_state)
return rvs *= np.linalg.det(rvs)[..., np.newaxis, np.newaxis]
```
I realize that naive intuition might be incorrect here, but it would be simpler and it seems to be faster in higher dimensions.

**Comment by Gattocrucco** [comment]
I think it is probably wrong, but I need to think about it. First thoughts:

1) Since Mezzadri's paper distinguishes O(n) and U(n) from S*(n) I think that he would have used this trick if it was ok.

2) For even n, you can't change the sign of the determinant multiplying by a constant diagonal matrix

3) If it worked, you need to round the determinant to the nearest integer, because the determinant calculation is not in general exact

**Comment by Gattocrucco** [comment]
After thinking a moment, apart from the even n problem, it should be right, because the component with negative determinant of O(n) is a reflection times SO(n). So

1. Multiply the first row by -1 if det < 0 instead of multiplying everything by the determinant
2. In principle computing the determinant should be slower, it's faster because of the handwritten algorithm, so we need to check if there is a relevant performance regression for intermediate sizes (I expect not)

**Comment by Gattocrucco** [comment]
@mdhaber I propose that you merge this as-is because it does not change the random stream, we are sure it works, and you have already reviewed it, in the meanwhile I can try out the determinant trick.

**Pull request merged**
