### PR TITLE
CI: Run the Azure Windows Python36 32bit tests with mode 'fast'

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
I'll just put this in for now, thanks @WarrenWeckesser 

When we see 7-8 minutes to download/install 32-bit mingw it seems like we have a pretty strong case to petition for addition of that package to the base Azure image, since NumPy and SciPy combined seems like a big enough surface area to justify, but that's a longer-term thing to propose on the Azure tracker. I should try to do that soon.

The 64-bit runs aren't exactly fast either, and there also seem to be pretty wide fluctuations in run times and I often see much faster times on my fork for whatever reason. 64-bit benefits from not having to download mingw since it is already in the base image.

**Comment by tylerjereddy** [comment]
Note that the 32-bit job is still likely to be a bigger pain because the mingw download step is prone to failure, regardless of how fast the tests run.. I'll try to open the issue upstream soon-ish.

**Comment by WarrenWeckesser** [comment]
OK, thanks Tyler.

**Comment by tylerjereddy** [comment]
I will aim to backport this for 1.5.x CI as well--related timeouts observed in #12397

**Pull request merged**
