### PR TITLE
Add tolerance statement to CoC.

### PR DESCRIPTION
**Pull request by hameerabbasi**

### CODE REVIEW

**Comment by rgommers** [comment]
thanks Hameer. link to the last version under discussion on the numpy mailing list: https://mail.python.org/pipermail/numpy-discussion/2018-August/078532.html

Note that this needs to hit the SciPy list as well (not in parallel, only after the numpy discussion has settled) before merging.

**Comment by matthew-brett** [comment]
OK with me.

**Comment by stefanv** [comment]
With me too.

**Comment by rgommers** [comment]
Thanks. Sent an email to scipy-dev about intention to merge this PR soon.

**Comment by tylerjereddy** [comment]
+1

**Comment by rgommers** [comment]
No comment for a couple of days, so merging. Thanks all!

**Pull request merged**
