### PR TITLE
Feature request.  Add furthest site Voronoi diagrams to scipy.spatial.plotutils.

### PR DESCRIPTION
**Pull request by rtshort**
This two line change adds furthest site diagrams to voronoi_plot_2d.

The following is a sample.  The code can be found at https://github.com/rtshort/voronoi.

exampl1

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The CI failure specific to Python 3.7 / Windows is pretty strange:

```
================================== FAILURES ===================================
______________________ interpolate/tests/test_fitpack.py ______________________
[gw1] win32 -- Python 3.7.4 C:\hostedtoolcache\windows\Python\3.7.4\x64\python.exe
worker 'gw1' crashed while running 'interpolate/tests/test_fitpack.py::TestBisplrep::test_cache_argument'
```

**Comment by pv** [comment]
probably unrelated, cf gh-10560

**Comment by rtshort** [comment]
Hi Tyler.

I have no way of testing any of this on Windows.  I use the stable version of debian and that is about all I can do.

Bob

**Comment by pv** [comment]
Thanks, merged, this looks correct to me.

**Pull request merged**
