### PR TITLE
BUG: integrate: fix handling of banded Jacobians in odeint, plus add some nicer error handling

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
See the descriptions in the individual commits for details.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
`<rant>`
%@^#$!%$ pep8!
```
    c = array([[-205, 0.01, 0.00,  0.0],
               [0.1, -2.50, 0.02,  0.0],
               [1e-3, 0.01, -2.0,  0.01],
               [0.0,  0.00,  0.1, -1.0]])
```
Of course, the `pep8` program doesn't like the extra spaces after the commas, but, gosh darn it, it's a table of numbers!  Aligning the columns improves readability in this case, and PEP8 (the text, not the program) says:
```
 Some other good reasons to ignore a particular guideline:

    1. When applying the guideline would make the code less readable, even for
       someone who is used to reading code that follows this PEP. 
```
`</rant>`

**Comment by argriffing** [comment]
I wouldn't complain if the pep8 bot went away.

**Comment by WarrenWeckesser** [comment]
My rant is done, and I feel better now. :)  It was easy enough to fix the spaces in the table.

Overall, I think the benefit of the pep8 bot outweighs the drawbacks.  The code is in much better shape than it was a few years ago.  I'd like to see stay that way, and I think the pep8 bot will help.

**Comment by rgommers** [comment]
@WarrenWeckesser agreed. It's annoying sometimes, but most of the code is now of acceptable quality, which is also good for teaching new contributors. A few years ago when looking at the majority of code you could instantly tell it was in poor shape.

**Comment by ev-br** [comment]
FWIW, I wouldn't mind if pep8 report were a *recommendation* not a failure. Not sure if our CI allow that though.

**Comment by rgommers** [comment]
I think there's no such thing on TravisCI, it's green or red (determined by any test script having exit code 0 or non-zero).

**Comment by WarrenWeckesser** [comment]
The improved error checking in this PR would have saved several people some debugging time, e.g.:

* http://stackoverflow.com/questions/15709933/object-too-deep-for-desired-array-scipy-integrate-odeint
* http://stackoverflow.com/questions/16001341/having-trouble-while-using-scipy-integrate-odeint-with-python
* http://stackoverflow.com/questions/27820725/how-to-solve-diff-eq-using-scipy-integrate-odeint/27822347

**Comment by argriffing** [comment]
Merged, thanks Warren!

**Comment by WarrenWeckesser** [comment]
I just noticed some pointless (but harmless) code in the Fortran test file `banded5x5.f`.  I'll start another PR to clean that up.

The only comments so far were about PEP 8, so I'm not sure this PR got a good review.  If anyone sees any problems post-merge, let me know.

**Comment by WarrenWeckesser** [comment]
https://github.com/scipy/scipy/pull/4377 removes the unnecessary loop in `banded5x5.f`.

**Comment by argriffing** [comment]
Sorry if I was too merge-happy with this PR.  As you know, there is some balance between merging things without careful enough review vs. discouraging other contributors who point out the backlog of PRs that "sit around unmerged for months."

**Comment by WarrenWeckesser** [comment]
@argriffing No worries.  I'm probably too far on the other end the spectrum when it comes to merging--just ask @Eric89GXL or @endolith (see https://github.com/scipy/scipy/pull/3717).

**Comment by Eric89GXL** [comment]
The iterations on #3717 have been really productive -- but of course @argriffing if you want to take some of your merge-happiness over to that PR I'm not going to stop you :)

**Comment by rgommers** [comment]
@WarrenWeckesser the setup.py construct without a ``pyf`` file here is a bit unusual. I ran into it because of the Bento build not knowing about it, but I think I'd also like to have a ``.pyf`` file to make the distutils build less susceptable to regressions.

**Comment by WarrenWeckesser** [comment]
>  a .pyf file to make the distutils build less susceptable to regressions.

Could you elaborate on that?  `numpy.distutils` is supposed to run f2py automatically on Fortran sources (see, e.g., http://docs.scipy.org/doc/numpy-dev/f2py/distutils.html), and the Fortran test file `banded5x5.f` is already annotated with `cf2py` comments, so adding a `.pyf` file for the sake of `numpy.distutils` should be unnecessary.

I haven't been using Bento, and I completely forgot about it when creating this PR--mea culpa!  I'll get started on a PR to update the Bento configuration.

**Comment by rgommers** [comment]
I know it's supposed to, but because there are no other places I could find that rely on this feature it's better avoided I think. Every other extension has a ``.pyf`` file it looks like.

**Comment by rgommers** [comment]
No worries about forgetting Bento, I can't really complain if I don't set up CI for it first .....

**Comment by rgommers** [comment]
And I can fix it if you don't feel like installing it.

**Comment by WarrenWeckesser** [comment]
> I know it's supposed to, but because there are no other places I could find that rely on this feature

See the `futil` module in scipy.stats.  Personally, I'd rather not add unnecessary boilerplate, but see the following...

> And I can fix it if you don't feel like installing it.

I installed bento, but my bento-fu is not strong, and the documentation of the "hooks" in bento is pretty sparse.  My few attempts (probably combined with some dumb mistakes) failed to get a working build of the test module using bento.  So if you can fix it, I'll go with whatever solution you prefer.

**Comment by rgommers** [comment]
Thanks, ``futil`` indeed does the same. So it has worked reliably for a long time - I won't touch it then.

Fixed the Bento build in a4d4cea.

**Comment by WarrenWeckesser** [comment]
Thanks Ralf.

**Pull request merged**
