### PR TITLE
MAINT: few scipy cleanups

### LINKED ISSUE #21405: MAINT: a few potential minor cleanups
While grepping around:

1) I think we can rename `meson_options.txt` to `meson.options` to match modern expectations per https://mesonbuild.com/Build-options.html.
2) For linting I think we can bump to match min supported Python:

<details>

```diff
--- a/tools/lint.toml
+++ b/tools/lint.toml
@@ -8,8 +8,8 @@ force-exclude = true
 
 line-length = 88
 
-# Assume Python 3.9
-target-version = "py39"
+# Assume Python 3.10
+target-version = "py310"
```
</details>

3) There's a bunch of code in `_arffread` that looks dead/related to `nose` testing/testing via direct module incantation which we don't do anymore I don't think:

<details>

```diff
--- a/scipy/io/arff/_arffread.py
+++ b/scipy/io/arff/_arffread.py
@@ -870,38 +870,3 @@ def _loadarff(ofile):
     # No error should happen here: it is a bug otherwise
     data = np.array(a, [(a.name, a.dtype) for a in attr])
     return data, meta
-
-
-# ----
-# Misc
-# ----
-def basic_stats(data):
-    nbfac = data.size * 1. / (data.size - 1)
-    return np.nanmin(data), np.nanmax(data), np.mean(data), np.std(data) * nbfac
-
-
-def print_attribute(name, tp, data):
-    type = tp.type_name
-    if type == 'numeric' or type == 'real' or type == 'integer':
-        min, max, mean, std = basic_stats(data)
-        print(f"{name},{type},{min:f},{max:f},{mean:f},{std:f}")
-    else:
-        print(str(tp))
-
-
-def test_weka(filename):
-    data, meta = loadarff(filename)
-    print(len(data.dtype))
-    print(data.size)
-    for i in meta:
-        print_attribute(i, meta[i], data[i])
-
-
-# make sure nose does not find this as a test
-test_weka.__test__ = False
-
-
-if __name__ == '__main__':
-    import sys
-    filename = sys.argv[1]
-    test_weka(filename)
```

</details>

4. A bunch more content related to `nose` can be purged I think:

<details>

```diff
diff --git a/scipy/io/matlab/tests/test_mio.py b/scipy/io/matlab/tests/test_mio.py
index 079dcab6d4..ff79174c3b 100644
--- a/scipy/io/matlab/tests/test_mio.py
+++ b/scipy/io/matlab/tests/test_mio.py
@@ -1,8 +1,3 @@
-''' Nose test generators
-
-Need function load / save / roundtrip tests
-
-'''
 import os
 from collections import OrderedDict
 from os.path import join as pjoin, dirname
diff --git a/scipy/optimize/tests/test_optimize.py b/scipy/optimize/tests/test_optimize.py
index 0ee21185ac..c6b4cfa412 100644
--- a/scipy/optimize/tests/test_optimize.py
+++ b/scipy/optimize/tests/test_optimize.py
@@ -5,9 +5,6 @@ Authors:
    Ed Schofield, Nov 2005
    Andrew Straw, April 2008
 
-To run it in its simplest form::
-  nosetests test_optimize.py
-
 """
 import itertools
 import platform
diff --git a/scipy/optimize/tests/test_trustregion.py b/scipy/optimize/tests/test_trustregion.py
index 24663f18de..e62d1045e7 100644
--- a/scipy/optimize/tests/test_trustregion.py
+++ b/scipy/optimize/tests/test_trustregion.py
@@ -1,9 +1,6 @@
 """
 Unit tests for trust-region optimization routines.
 
-To run it in its simplest form::
-  nosetests test_optimize.py
-
 """
 import pytest
 import numpy as np
diff --git a/scipy/optimize/tests/test_trustregion_exact.py b/scipy/optimize/tests/test_trustregion_exact.py
index b48e4153d0..020b6d883a 100644
--- a/scipy/optimize/tests/test_trustregion_exact.py
+++ b/scipy/optimize/tests/test_trustregion_exact.py
@@ -1,9 +1,6 @@
 """
 Unit tests for trust-region iterative subproblem.
 
-To run it in its simplest form::
-  nosetests test_optimize.py
-
 """
 import pytest
 import numpy as np
diff --git a/scipy/optimize/tests/test_trustregion_krylov.py b/scipy/optimize/tests/test_trustregion_krylov.py
index b130362323..f2c18f931a 100644
--- a/scipy/optimize/tests/test_trustregion_krylov.py
+++ b/scipy/optimize/tests/test_trustregion_krylov.py
@@ -1,9 +1,6 @@
 """
 Unit tests for Krylov space trust-region subproblem solver.
 
-To run it in its simplest form::
-  nosetests test_optimize.py
-
 """
 import numpy as np
 from scipy.optimize._trlib import (get_trlib_quadratic_subproblem)
```
</details>

### PR DESCRIPTION
**Pull request by dannyi96**
#### Reference issue
closes #21405 

#### What does this implement/fix?

1. Rename of `meson_options.txt` to `meson.options`
2. Linting: python bumped from 3.9 to 3.10
3. Dead code removal in `_arffread.py`
4. Removal of content mentioning `nose` tests.

### CODE REVIEW

**Comment by j-bowhay** [comment]
Thanks @dannyi96 is this still in draft status or is it ready to review?

**Comment by dannyi96** [comment]
thanks @j-bowhay , yes I've just converted the PR from draft to ready for review state.

**Review by tylerjereddy — APPROVED** [review]
This seems fine to me, and the CI is happy, thanks.

**Comment by j-bowhay** [comment]
Thanks for your first contribution @dannyi96

**Pull request merged**
