### PR TITLE
BUG: stats.unuran: fix support for old compilers

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### What does this implement/fix?

try to address failers pointed out in #14631. I have tried to remove definitions that enabled the use of C99/C95 functions. TBD if we want to merge this or gh-14631

#### Additional information

### CODE REVIEW

**Comment by rgommers** [comment]
> I have tried to remove definitions that enabled the use of C99/C95 functions.

You can use C99 functionality. It just needs an explicit flag for older compilers (in particular gcc 4.x, which we anyway should drop soon). You can do this via:
```python
from scipy._build_utils.compiler_helper import set_c_flags_hook
```
(see `scipy/special/setup.py` for an example).

**Comment by mckib2** [comment]
Yes, echoing Ralph here -- I recall making a similar fix for one of the HiGHS libraries in gh-13089

**Comment by tirthasheshpatel** [comment]
> Yes, echoing Ralph here -- I recall making a similar fix for one of the HiGHS libraries in [gh-13089](https://github.com/scipy/scipy/pull/13089)

I already do that in the pre-build hook. Looking at the [build logs](https://dev.azure.com/numpy/27346c6a-2774-4eac-bf85-e068127c0ccc/_apis/build/builds/19164/logs/47), it seems like the `-std=c99` flag is never added. Not sure why is that the case.

**Comment by isuruf** [comment]
See https://github.com/scipy/scipy/pull/14631/files for the correct fix

**Comment by tirthasheshpatel** [comment]
Closing this in favor of #14631. Please feel free to add your reviews on #14631, thanks!

**Pull request closed without merging**
