### PR TITLE
MAINT: signal: Add matplotlib import to the lombscargle example.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Without the import, the plot was not being generated in the HTML docs.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
One the tests stalled.  Let's try this again.

**Comment by rgommers** [comment]
Thanks @WarrenWeckesser, merged.

**Comment by rgommers** [comment]
no need to run the tests at all by the way for a doc-only PR. that's what ``[ci skip]`` in a commit message is for.

**Comment by rgommers** [comment]
and backported in 6f07362

**Comment by WarrenWeckesser** [comment]
> no need to run the tests at all by the way for a doc-only PR. that's what [ci skip] in a commit message is for.

Probably true. On the other hand,  I could bore you with a war story about an untested *comment*-only change that broke a client's installation.  An experience like that biases me towards running the tests for any change to a .py file, even a doc-only change.

**Comment by rgommers** [comment]
could actually be a fun story. but we'll test PRs many more times after they're merged and before they're in a release, so even if this did happen it wouldn't be that bad....

**Pull request merged**
