### PR TITLE
TST: added nist test case (Norris) to `stats.linregress`.

### PR DESCRIPTION
**Pull request by aeklant**
Addresses part of gh-629

### CODE REVIEW

**Comment by aeklant** [comment]
I added the Norris NIST test case since it is the only one that aligns with `stats.linregress` as noted in gh-629.

I also added the `.dat` file but just for reference. I didn't bother to automate the retrieval of data because it is only one test case and each input has only 36 values.

**Comment by rgommers** [comment]
@aeklant the NIST test looks fine, but this PR doesn't actually close the issue yet. I had a number of suggestions: https://github.com/scipy/scipy/issues/629#issuecomment-125849417 and https://github.com/scipy/scipy/issues/629#issuecomment-125850616

**Comment by aeklant** [comment]
Items addressed:
* Explicitly raising `ValueError` on empty input
* Added test for empty input
* Added test for nan input (The current implementation returns nan although this is a byproduct of `np.abs(np.nan)`. I left it as is for now and silenced the `RuntimeWarning` in the test).
* Mention linear least squares in summary line.
* Added `optimize.curve_fit` and `optimize.leastsq` to `See also` section.
* Added `stats.linregress` to `optimize.curve_fit`s `See also` section.

**Comment by rgommers** [comment]
@aeklant this all looks good, so I'm merging it now. I'm leaving gh-629 open, because there are a few things left to do.

**Comment by rgommers** [comment]
Nice work. Hope you settled into your new environment!

**Pull request merged**
