### PR TITLE
DOC: Fix erroneous latex characters in tutorial/optimize.

### PR DESCRIPTION
**Pull request by rmcgibbo**
Fix for #4585

### CODE REVIEW

**Comment by rmcgibbo** [comment]
The same issue is also present in the [linalg](http://docs.scipy.org/doc/scipy-0.15.1/reference/tutorial/linalg.html) tutorial. I've updated the PR to fix that too.

**Comment by pv** [comment]
You may also need to remove the `:nowrap:` options (http://sphinx-doc.org/latest/ext/math.html) in case having them breaks latex. You can try to do "cd doc; make dist"

**Comment by rmcgibbo** [comment]
It looks fine to me. I built them using `python setup.py build_sphinx`. I pushed them up to my university website, see. http://stanford.edu/~rmcgibbo/scipy/tutorial/linalg.html These are built from 764a2cd7.

**Comment by rgommers** [comment]
LGTM too, merging. Thanks @rmcgibbo!

**Comment by argriffing** [comment]
Thanks, I just noticed this in the docs http://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html which hasn't been updated.

**Comment by pv** [comment]
As I noted above, this change breaks the PDF build, see the corresponding parts in the generated PDF https://docs.scipy.org/doc/scipy-dev/scipy-ref.pdf  (`python setup.py build_sphinx` doesn't build the PDF docs, only the html ones.)

Sphinx+mathjax doesn't care about the `:nowrap:` option, but leaving it in makes sphinx produce invalid latex output. Excrept from `scipy-ref.tex` corresponding to the the first change above:
```
using \code{A.I} if \code{A} is a Matrix. For example, let
 \mathbf{A=}\left[\begin{array}{ccc} 1 & 3 & 5\\ 2 & 5 & 1\\ 2 & 3 & 8\end{array}\right]
then
 \mathbf{A^{-1}=\frac{1}{25}\left[\begin{array}{ccc} -37 & 9 & 22\\ 14 & 2 & -9\\ 4 & -3 & 1\end{array}\right]=\left[\begin{array}{ccc} -1.48 & 0.36 & 0.88\\ 0.56 & 0.08 & -0.36\\ 0.16 & -0.12 & 0.04\end{array}\right].}
The following example demonstrates this computation in SciPy
```
The `:nowrap:` directives should be removed if the math does not contain latex math environment directives.

**Pull request merged**
