### PR TITLE
ENH: Support Bounds class in shgo

### PR DESCRIPTION
**Pull request by dschmitz89**
#### What does this implement/fix?
Adds support for the Bounds class to the global optimizer shgo for a more uniform API across scipy.optimize.

### CODE REVIEW

**Review by tupui — APPROVED** [review]
Thanks @dschmitz89. LGTM and the changes are the same as with #15453

**Comment by mdhaber** [comment]
@dschmitz89 Were you done here? As we discussed in gh-15453, the test would be much stronger if the bounds affected the problem being solved.

**Comment by tupui** [comment]
But why should it be different than the current test? The feature is just allowing an existing keyword to be formatted differently. So not breaking by running twice the same problem and getting the same result should be enough no?

**Comment by mdhaber** [comment]
It confirms that providing a `Bounds` object instead of a sequence of tuples does not immediately _break_ anything, yes. It does not provide much evidence that the `Bounds` data is used correctly because bounds do not affect the solution to this problem. 

For instance, 
```
        lb = [-1e9, -1e9]
        ub = [1e9, 1e9]
        bounds_old = list(zip(lb, ub))
        res_old_bounds = shgo(f, bounds_old)
```
finds the same solution.

Without knowing how the algorithm works, we'd expect the same result if the bounds were not used internally at all. 

A stronger test would give evidence that the Bounds are treated correctly without relying on our knowledge of how the function works. See how the test in gh-15453 does this.

**Comment by tupui** [comment]
ok I see 👍 If you want I can make a PR to change the example with this.

**Comment by dschmitz89** [comment]
@mdhaber : I was barely aware that this PR was merged. :D
Can add a follow-up PR to strengthen the test, no problem.

**Pull request merged**
