### PR TITLE
BENCH: sparse.linalg: check accuracy properly in LOBPCG benchmarks

### PR DESCRIPTION
**Pull request by lobpcg**
#### Reference issue
N/A

#### What does this implement/fix?
Makes check accuracy in LOBPCG benchmarks consistent with that in 
https://github.com/scipy/scipy/pull/19361

#### Additional information
The current code uses asserts to check accuracy in LOBPCG benchmarks which are apparently being ignored by ASV, so
they are substituted with 
```
            if accuracy > tol:
                time.sleep(20)
```
to force the benchmark run out of time and thus mark it as failed, just as in  https://github.com/scipy/scipy/pull/19361

### CODE REVIEW

**Comment by lobpcg** [comment]
@j-bowhay could you please review this since you have just merged the sister PR #21220 ?

**Review by j-bowhay — CHANGES_REQUESTED** [review]
Thanks @lobpcg, I understand the motivation for these changes but I am not sure relying on timing the benchmark out is acceptable as this would increase CI time too much. Is there a reason an exception cannot be raised instead?

**Comment by lobpcg** [comment]
> Thanks @lobpcg, I understand the motivation for these changes but I am not sure relying on timing the benchmark out is acceptable as this would increase CI time too much. Is there a reason an exception cannot be raised instead?

Thanks for reviewing! An exception just crashes the rest of the benchmark to my recollection. The delay is the only solution I have found that does the trick to generate the desired output. 

Benchmarks is a special part of CI in terms of timing, as far as I remember. 

Unfortunately, it's been long enough since I wrote it so my recollections may not be 💯

**Comment by j-bowhay** [comment]
@lobpcg I pushed a commit to use `SkipNotImplmented` instead as this has the same effect as `time.sleep` without the long wait. Please see the output comparison bellow. If you are happy with this change I can merge now and also review https://github.com/scipy/scipy/pull/19361


Before:
```
[16.67%] ··· sparse_linalg_lobpcg.Bench.time_mikota                                                                                                                                                               ok
[16.67%] ··· ====== ========== ========== ==========
             --                  solver             
             ------ --------------------------------
               n      lobpcg     eigsh      lapack  
             ====== ========== ========== ==========
              128    6.85±0ms   2.22±0ms   1.62±0ms 
              256    9.49±0ms   2.35±0ms   3.96±0ms 
              512    10.7±0ms   2.27±0ms   16.9±0ms 
              1024   13.2±0ms   3.29±0ms     n/a    
              2048   20.7±0ms   4.40±0ms     n/a    
             ====== ========== ========== ==========

[16.67%] ···· For parameters: 1024, 'lapack'
              asv: skipped: NotImplementedError()
              
              For parameters: 2048, 'lapack'
              asv: skipped: NotImplementedError()

[33.33%] ··· sparse_linalg_lobpcg.Bench.time_sakurai                                                                                                                                                              ok
[33.33%] ··· ==== ========= ========= =========
             --               solver           
             ---- -----------------------------
              n     lobpcg    eigsh     lapack 
             ==== ========= ========= =========
              50   276±0ms   303±0ms   630±0μs 
             ==== ========= ========= =========

[50.00%] ··· sparse_linalg_lobpcg.Bench.time_sakurai_inverse                                                                                                                                              2/6 failed
[50.00%] ··· ====== ========== ========== ========
             --                 solver            
             ------ ------------------------------
               n      lobpcg     eigsh     lapack 
             ====== ========== ========== ========
              500    5.57±0ms   1.31±0ms   failed 
              1000   14.5±0ms   3.25±0ms   failed 
             ====== ========== ========== ========
             For parameters: 500, 'lapack'
             
             
             asv: benchmark timed out (timeout 20s)
             
             For parameters: 1000, 'lapack'
             
             
             asv: benchmark timed out (timeout 20s)

[50.00%] ···· For parameters: 500, 'lapack'
              
```
After:
```
[ 0.00%] ·· Benchmarking existing-py_home_jakeb_miniconda3_envs_scipy-dev-pytorch_bin_python
[16.67%] ··· sparse_linalg_lobpcg.Bench.time_mikota                                                                                                                                                               ok
[16.67%] ··· ====== ========== ========== ==========
             --                  solver             
             ------ --------------------------------
               n      lobpcg     eigsh      lapack  
             ====== ========== ========== ==========
              128    6.91±0ms   2.21±0ms   1.67±0ms 
              256    8.20±0ms   2.33±0ms   3.95±0ms 
              512    10.0±0ms   2.22±0ms   16.6±0ms 
              1024   13.3±0ms   3.13±0ms     n/a    
              2048   20.4±0ms   4.08±0ms     n/a    
             ====== ========== ========== ==========

[16.67%] ···· For parameters: 1024, 'lapack'
              asv: skipped: SkipNotImplemented('lapack too slow to benchmark with n=1024.')
              
              For parameters: 2048, 'lapack'
              asv: skipped: SkipNotImplemented('lapack too slow to benchmark with n=2048.')

[33.33%] ··· sparse_linalg_lobpcg.Bench.time_sakurai                                                                                                                                                              ok
[33.33%] ··· ==== ========= ========= =========
             --               solver           
             ---- -----------------------------
              n     lobpcg    eigsh     lapack 
             ==== ========= ========= =========
              50   275±0ms   307±0ms   627±0μs 
             ==== ========= ========= =========

[50.00%] ··· sparse_linalg_lobpcg.Bench.time_sakurai_inverse                                                                                                                                                      ok
[50.00%] ··· ====== ========== ========== ========
             --                 solver            
             ------ ------------------------------
               n      lobpcg     eigsh     lapack 
             ====== ========== ========== ========
              500    5.50±0ms   1.28±0ms    n/a   
              1000   7.26±0ms   1.57±0ms    n/a   
             ====== ========== ========== ========
```

**Comment by lobpcg** [comment]
@j-bowhay fantastic, thanks so much!

**Review by j-bowhay — APPROVED** [review]

**Pull request merged**
