### PR TITLE
fix docstring of NearestNDInterpolator

### PR DESCRIPTION
**Pull request by megies**
There's a mismatch in args names:

screenshot from 2017-03-09 11 44 11

### CODE REVIEW

**Comment by rgommers** [comment]
thanks @megies, merged.

**Comment by ev-br** [comment]
This seems to need a forward port from maintenance/0.18.x to master.

**Comment by megies** [comment]
Yeah.. I wasn't sure what your policy is.. merge it into master and backport or merge it into maintainance and forward port to master. I guess a simple cherry-pick on master will do? Let me know if you need me to do something.

**Comment by rgommers** [comment]
Sorry about that, completely missed that this PR was against 0.18.x. That's not an issue, so let's leave 0.18.x as is. Forward ported in gh-7156.

**Comment by megies** [comment]
Thanks for taking care of things!

**Pull request merged**
