### PR TITLE
MAINT: Remove unnecessary 'from __future__ import ...' statements

### PR DESCRIPTION
**Pull request by sethtroisi**
#### Reference issue

Continued work on Python2 code cleanups #11584

This is 556 changes, In #11623 I did only one module/directory and If that's preferred I'm happy to do that but it seems faster to do all these (easy) changes at once.

---

I double checked this with

To make sure that all files are deletions
```shell
$ git diff upstream/master --stat | grep -v -e '2 --$' -e '1 -$'
 scipy/integrate/tests/test_banded_ode_solvers.py                      | 3 ---
 scipy/linalg/_generate_pyx.py                                         | 4 ----
 scipy/special/_generate_pyx.py                                        | 4 ----
 scipy/stats/mstats_extras.py                                          | 3 ---
 556 files changed, 1072 deletions(-)
$ git diff upstream/master -- scipy/integrate/tests/test_banded_ode_solvers.py scipy/special/_generate_pyx.py scipy/linalg/_generate_pyx.py scipy/stats/mstats_extras.py
```

To make sure I'm ovly removing `from __future__` lines
```shell
$ git diff upstream/master | grep '^[-+][^-+]' | sort -u
-from __future__ import absolute_import
-from __future__ import absolute_import, division, print_function
-from __future__ import division
-from __future__ import division, absolute_import, print_function
-from __future__ import division, print_function, absolute_import
-from __future__ import print_function
-from __future__ import print_function, division, absolute_import
```

### CODE REVIEW

**Comment by EverLookNeverSee** [comment]
@rgommers What is your opinion about number of changed files in this PR?

**Comment by sethtroisi** [comment]
```shell
$ git diff upstream/master --name-only  | cut -f1-2 -d'/' | sort | uniq -c | sort -nr
     88 scipy/sparse
     83 scipy/optimize
     61 scipy/special
     44 scipy/linalg
     39 scipy/io
     37 scipy/stats
     35 scipy/signal
     27 scipy/interpolate
     23 scipy/spatial
     23 scipy/integrate
     19 scipy/_lib
     18 scipy/ndimage
     12 scipy/fftpack
      8 scipy/cluster
      6 scipy/misc
      6 scipy/fft
      6 scipy/constants
      5 scipy/odr
      4 scipy/_build_utils
      2 doc/source
... (individual files in tool/ scipy/)
```
I'm happy to break out the 276 of the 556 files from the top four modules, but IMHO 280 files doesn't seem very different from 556

**Comment by rgommers** [comment]
This is fine as a single commit, thanks for asking.

Changes LGTM. I have a vague memory of someone mentioning an issue with removing this (can't think what though), so I'll leave it open for a bit just in case.

**Review by miladsade96 — APPROVED** [review]
Thanks @sethtroisi for this PR
LGTM , feel free to merge it if @rgommers is also satisfied.

**Review by rgommers — APPROVED** [review]

**Comment by rgommers** [comment]
Merged, thanks @sethtroisi

**Pull request merged**
