### PR TITLE
BUG: Fix M_PI

### PR DESCRIPTION
**Pull request by larsoner**
Might fix https://ci.appveyor.com/project/scipy/scipy/builds/32959985 and related failures:
```
  scipy\stats\_stats.c(19781): error C2065: 'M_PI': undeclared identifier
```
Seems like this must be an underlying Cython issue (?), but maybe this will allow us to work around it.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The definition of `M_PI` in `math.h` is not standard.  Perhaps what we really need is to define `_USE_MATH_DEFINES` when build with a Microsoft compiler: https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=vs-2019

**Comment by larsoner** [comment]
It seems like something that Cython should take care of when you use `libc.math`, no?

In any case, it seems to have succeeded building with this:

https://ci.appveyor.com/project/scipy/scipy/builds/32961266

Might be worth merging this as-is to get things back to green, then if someone has a more principled solution, that can undo the change here (if desired, it seems fairly harmless).

**Comment by larsoner** [comment]
The build passed but it's not functional, trying to fix the shim...

**Comment by larsoner** [comment]
Actually it looks like elsewhere in the codebase we solve this in various different ways. It seems like the most expedient here would be just to use `PI` from `numpy.math`, which is already `cimport`ed. Let's see if that one passes.

**Comment by larsoner** [comment]
Seems to have fixed AppVeyor https://ci.appveyor.com/project/scipy/scipy/builds/32962123

**Review by WarrenWeckesser — APPROVED** [review]
Even simpler than the first version!

**Comment by WarrenWeckesser** [comment]
Any idea why there is no Travis-CI run?

**Comment by larsoner** [comment]
Could be just some slow status update issue (or maybe someone restarted it?), but it's there now and green

**Comment by WarrenWeckesser** [comment]
Yes, I guess it is just very slow getting started. It wasn't even in the list when I made my comment

**Comment by WarrenWeckesser** [comment]
Merged.  Thanks, @larsoner.

**Pull request merged**
