### PR TITLE
REV: restore wminkowski

### PR DESCRIPTION
**Pull request by apbard**
Restores old `wminkowski` as requested in Issue #7893 to keep retro-compatibility.
Updates the documentation for release 1.0 
Fix a bug in `_rand_split` by ensuring weights are float

### CODE REVIEW

**Comment by apbard** [comment]
@lesteve, @rgommers this should solve #7893. Please have a look.

**Comment by lesteve** [comment]
I am wondering whether it would not be slightly better to reuse the `minkowski` function inside `vminkowski`. IIRC `vminkowski(u, v, p, w) = minkowski(u, v, p, w**p)`.

**Comment by apbard** [comment]
@lesteve you are right, thanks. I have just done it.

**Comment by rgommers** [comment]
LGTM, thanks @apbard! I made some minor changes to the release note entry, otherwise good to go.

**Comment by rgommers** [comment]
In it goes, thanks @apbard and @lesteve

**Comment by lesteve** [comment]
Great thanks a lot! FYI I double-checked that the scikit-learn failures on our scipy-dev have gone.

**Comment by rgommers** [comment]
Backport in gh-7938

**Pull request merged**
