### PR TITLE
BUG: optimize: check tolerance >= 0 in brent

### LINKED ISSUE #4140: "Brent" solver dies with UnboundLocalError
I am attempting (without success so far) to find the moment of maximum altitude of an Earth satellite passing overhead using the various minimize routines in `optimize` and have encountered the problem that when the Brent solver is started, it dies in the line:

    deltax = rat

in `Brent.optimize` in `optimize.py` because `rat` is not set anywhere in the function above that line. Here is the line in the current version of `optimize.py`:

https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L1771

Here is a notebook where you can see the live exception (scroll down to `In[133]`):

http://nbviewer.ipython.org/github/brandon-rhodes/astronomy-notebooks/blob/e6ad1e384af03e3ad26f6bce94843df68c8e14b9/Solvers/Earth-Satellite-Passes.ipynb

### PR DESCRIPTION
**Pull request by larsmans**
Fixes gh-4140.

### CODE REVIEW

**Comment by larsmans** [comment]
@dlax Would it be a bad thing to merge this as a hotfix, and leave the general issue for later? I could add a comment to indicate that the code may be broken.

**Comment by dlax** [comment]
Lars a écrit :
> @dlax <https://github.com/dlax> Would it be a bad thing to merge this as
> a hotfix, and leave the general issue for later? I could add a comment
> to indicate that the code may be broken.


Probably not a "bad thing". I was just suggesting a possible better way 
to solve the issue but I perfectly understand that you may not have the 
resources for this.

**Comment by larsmans** [comment]
@dlax Pushed a comment in 00120b4c9cf06b70243639e6e5dd0d38fec870f0.

**Comment by larsmans** [comment]
I saw an ok from @argriffing and interpreted @dlax's comment as an ok too, so I merged.

**Pull request merged**
