### PR TITLE
Add example for application of gaussian filter

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by ev-br** [comment]
Test failure is real if trivial: the example needs `>>> from scipy.ndimage import gaussian_filter`. The only implicit import is `numpy as np`, everything else must be imported explicitly.

**Comment by MartinThoma** [comment]
@ev-br Thank you, I wasn't aware of that. I fixed it. So you're running doctests? How do you make the implicit import of numpy?

**Comment by ev-br** [comment]
Yes, it's a (modified) doctester, which executes doctests in a namespace which has the symbol `np`.
https://github.com/scipy/scipy/blob/master/tools/refguide_check.py#L419

To run it localy, do `$ python runtests --refguide-check -s <submodule>`.

**Comment by MartinThoma** [comment]
I just ran `python runtests.py --refguide-check -s ndimage` - seems to work.

Thank you for the explanation!

**Comment by ev-br** [comment]
All green, looks good --- merging it in. Thank you @MartinThoma !

**Pull request merged**
