### PR TITLE
BUG: off by one errors in thin_qr_insert_row

### PR DESCRIPTION
**Pull request by ewmoore**

### CODE REVIEW

**Comment by rgommers** [comment]
This didn't fix an existing failure, so does it need a new regression test?

**Comment by ewmoore** [comment]
It could I guess.  I'm not sure how to write such a test.  This fixes writing past the bounds of the array, so nominally the existing tests cover it, but no failure was triggered.  I found this via valgrind. The test suite isn't entirely clean under it, but the test failures on 32-bit don't seem to be this kind of problem (valgrind didn't report anything anyway.)

There will be another small patch at least here, if you can wait until tomorrow.  Hopefully when I have a few minutes then I can figure out the failures.

**Comment by rgommers** [comment]
It was just a quick question without looking at the code in detail - agree that a regression test for this doesn't really make sense.

I'll wait with merging this then. Won't be creating the beta release till tomorrow late in the evening - still need to look at fixing the Windows blas/lapack binaries first.

**Comment by rgommers** [comment]
Had a look at this, the ``n-j-1`` makes sense to me.

**Comment by Eric89GXL** [comment]
This fixes some issues for me referenced in #4885

**Comment by rgommers** [comment]
Thanks for checking @Eric89GXL. Did it fix the errors or the failures?

**Comment by Eric89GXL** [comment]
No, post update coming once I test one more condition...

**Comment by rgommers** [comment]
Okay, I'm going to merge this so it can go into 0.16.0b2. There is more to do here though, these functions not working with MKL for 64-bit also is a blocker.

**Comment by rgommers** [comment]
backported to 0.16.x in 9a8eca2

**Pull request merged**
