### PR TITLE
ENH:stats: arcsine distribution additions

### PR DESCRIPTION
**Pull request by OmarManzoor**
#### Reference issue

Towards: gh-17832

#### What does this implement/fix?

arcsine distribition adjusments:
- Simplified definition of _cdf method
- Added the _sf method to override the default.

#### Additional information

None

### CODE REVIEW

**Comment by mdhaber** [comment]
What are the advantages of this formulation compared to that in main?

**Comment by OmarManzoor** [comment]
> What are the advantages of this formulation compared to that in main?

Removal of the sqrt operation.

**Comment by mdhaber** [comment]
Let's test it. I would prefer for the improvement to be substantial to justify the development time. 

<details>

```python
from time import perf_counter
import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng()
t = []
t2 = []
ns = np.logspace(0, 7).astype(int)
for n in ns:
  x = rng.random(size=n)
  tic = perf_counter()
  y = 2.0/np.pi*np.arcsin(np.sqrt(x))
  toc = perf_counter()
  t.append(toc-tic)
  tic = perf_counter()
  y = np.arcsin(2*x-1) / np.pi + 0.5
  toc = perf_counter()
  t2.append(toc-tic)

plt.plot(ns, t, ns, t2)
plt.legend(['main', 'pr'])
plt.title('arcsine.cdf performance comparison')
plt.xlabel('array size')
plt.ylabel('execution time (s)')
```

<\details>

**Comment by OmarManzoor** [comment]
> Let's test it. I would prefer for the improvement to be substantial to justify the development time.
> 
> Locally and on Colab, the performance change I'm seeing is mostly negative.
> 
> image
> 
> Even if the graphs were reversed, I would suggest that there are other distributions with greater need. Even if the changes are easy to implement, review of these is generally not trivial.

Thank you for the analysis. I understand your point. Could you kindly suggest another distribution that would be more suitable to work on?

**Comment by dschmitz89** [comment]
> > Let's test it. I would prefer for the improvement to be substantial to justify the development time.
> > Locally and on Colab, the performance change I'm seeing is mostly negative.
> > image
> > Even if the graphs were reversed, I would suggest that there are other distributions with greater need. Even if the changes are easy to implement, review of these is generally not trivial.
> 
> Thank you for the analysis. I understand your point. Could you kindly suggest another distribution that would be more suitable to work on?

Thanks for your enthusiasm @OmarManzoor ! One thing that comes to my mind here is the betaprime distribution: https://scipy.github.io/devdocs/reference/generated/scipy.stats.betaprime.html#scipy.stats.betaprime

Some of its methods (e. g. survival function, inverse survival function, entropy) could be overwritten by just using the methods of the F distribution. The docs state:

> The beta prime distribution is a reparametrized version of the F distribution. The beta prime distribution with shape parameters a and b and scale = s is equivalent to the F distribution with parameters d1 = 2*a, d2 = 2*b and scale = (a/b)*s

**Comment by OmarManzoor** [comment]
@dschmitz89 

I tried out the beta prime survival function using the f distribution survival function. It turns out that it seems to be slower than what is currently in main.

image

<details>
<summary>Code</summary>
```python
from scipy import stats
from scipy._lib._util import _lazywhere
import numpy as np
from time import perf_counter
import matplotlib.pyplot as plt
rng = np.random.default_rng()

def betaprime_cdf(x, a, b):
    return _lazywhere(
      x > 1, [x, a, b],
      lambda x_, a_, b_: stats.beta._sf(1/(1+x_), b_, a_),
      f2=lambda x_, a_, b_: stats.beta._cdf(x_/(1+x_), a_, b_)
    )

ns = np.logspace(0, 7).astype(int)
t = []
t2 = []
y1 = []
y2 = []
for n in ns:
    x = rng.random(size=n)
    tic = perf_counter()
    y = 1 - betaprime_cdf(x, a, b)
    toc = perf_counter()
    t.append(toc-tic)
    y1.append(y)
    tic = perf_counter()
    y = stats.f._sf(x * (b / a), 2*a, 2*b)
    toc = perf_counter()
    t2.append(toc-tic)
    y2.append(y)

plt.plot(ns, t, ns, t2)
plt.legend(['main', 'pr'])
plt.title('BetaPrime sf performance comparison')
plt.xlabel('array size')
plt.ylabel('execution time (s)')
```
</details>

Could this be because the beta distribution uses the boost library.

**Comment by mdhaber** [comment]
This might be OK if they are more accurate.

**Comment by dschmitz89** [comment]
> @dschmitz89
> 
> I tried out the beta prime survival function using the f distribution survival function. It turns out that it seems to be slower than what is currently in main. Could this be because of the fact that the cdf of the beta prime distribution uses the beta distribution and the beta distribution uses the boost library.
> 
> image
> 
> Code

Even more important than performance is accuracy. The betaprime survival function becomes imprecise in the tails very quickly:

<details><summary>Code</summary>
<p>

```python
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

a, b = 1, 2
x = np.logspace(-5, 30)
plt.loglog(x, stats.betaprime.sf(x, a, b), label="betaprime main", ls="dashed")
plt.loglog(x, stats.f.sf(x, 2 * a, 2 * b, scale= a/b), label="betaprime using f dist. survival function", ls="dashdot")
plt.legend()
plt.show()

``` 


</p>
</details> 

image

**Comment by OmarManzoor** [comment]
> > @dschmitz89
> > I tried out the beta prime survival function using the f distribution survival function. It turns out that it seems to be slower than what is currently in main. Could this be because of the fact that the cdf of the beta prime distribution uses the beta distribution and the beta distribution uses the boost library.
> > image
> > Code
> 
> Even more important than performance is accuracy. The betaprime survival function becomes imprecise in the tails very quickly:
> 
> Code
> image
> 
> Reusing the F distribution methods also lowers future maintenance cost. My suggestion would be to start with survival function. For testing we could add two tests against the "regular" betaprime formula implemented in mpmath. As the F distribution ideally should test the accuracy of the implementation we do not need very extensive testing.

Thank you for the explanation.

**Pull request closed without merging**
