### PR TITLE
MAINT: special: fix msvc build by using `new` and `delete` for `cwrk`

### LINKED ISSUE #20860: BUG/BLD: scipy-1.13.1 fails to build with msvc
Building scipy-1.13.1 from source on Windows using the latest C compiler from Visual Studio 2022 (17.10.1) fails to compile amos.h at line 2449:

https://github.com/scipy/scipy/blob/44e4ebaac992fde33f04638b99629d23973cb9b2/scipy/special/special/amos/amos.h#L2448-L2450

```
  "cl" "-Iscipy\special\cython_special.cp311-win_amd64.pyd.p" "-Iscipy\special" "-I..\scipy\special" "-Iscipy\_lib" "-I..\scipy\_lib" "-I..\scipy\_build_utils\src" "-I..\scipy\special\cephes" "-IX:\Python311\Lib\site-packages\numpy\_core\include" "-Iscipy" "-I..\scipy" "-IX:\Python311\Include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/EHsc" "/std:c++17" "/permissive-" "/O2" "/Gw" "-DMS_WIN64=" "-DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION" "/Fdscipy\special\cython_special.cp311-win_amd64.pyd.p\amos_wrappers.cpp.pdb" /Foscipy/special/cython_special.cp311-win_amd64.pyd.p/amos_wrappers.cpp.obj "/c" ../scipy/special/amos_wrappers.cpp
  
<snip>  

  scipy\special\special/amos/amos.h(2449): error C2131: expression did not evaluate to a constant
  scipy\special\special/amos/amos.h(2449): note: failure was caused by a read of a variable outside its lifetime
  scipy\special\special/amos/amos.h(2449): note: see usage of 'n'
```

A work-around is to use clang-cl from LLVM instead.

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Reference issue

Closes https://github.com/scipy/scipy/issues/20860

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @czgdp1807. Looks reasonable to me. I'll leave the review to @steppi.

**Comment by ilayn** [comment]
I think if I understood correctly, the reason new and delete is avoided is to avoid the dynamic memory allocation because GPU reasons. So this might be going against that. Indeed @steppi and @izaid should know better than my vague memory.

**Comment by rgommers** [comment]
Nothing to do with GPUs, the old code just doesn't compile with MSVC. The traceback is in gh-20860.

**Comment by ilayn** [comment]
Yes what I mean is that the reason why amos did not use new and delete is that they are similar to malloc and free dynamic memory. https://github.com/scipy/scipy/pull/20258 For some reason they did not like that linking back to a discussion about cupy or something. 

How is this leading to an error on MSVC is my issue that I did not understand what the error says

**Comment by czgdp1807** [comment]
> How is this leading to an error on MSVC is my issue that I did not understand what the error says

MSVC is not advanced enough to create arrays on stack which have sizes dependent on variables (doesn't matter if it's an input argument). Ideally, if the size of an array is dependent only on input argument and constants then array can be created on stack without any issues. MSVC is unable to do that. So I had to use `new` and `delete` for making the code MSVC compatible. However, if it's dependent on local variables then creation on heap is the only way.

**Comment by ilayn** [comment]
I see. That's really unfortunate. There are certain places in amos and specfun that stack would be unnecessarily large hence I was siding with heap allocation but apparently folks have portability concerns over CUDA applications. I did not pursue further to understand the nature of it though.

**Comment by czgdp1807** [comment]
Yes. This is the only option I was able to figure out. Even I wanted MSVC to be good enough to process the original code but it is what it is. There are more instances where I have seen other compilers able to do things which MSVC can't. Hopefully, it will be better in the future.

**Comment by WarrenWeckesser** [comment]
>>    How is this leading to an error on MSVC is my issue that I did not understand what the error says

> MSVC is not advanced enough to create arrays on stack which have sizes dependent on variables

Pedantic clarification: a declaration such as `std::complex<double> cwrk[n];` is known in the C world as a variable length array (VLA).  These are allowed in C99.  But `amos.h` is a C++ file, and variable length arrays are not allowed in *standard* C++.  If it compiles, it is because the compiler provides a nonstandard extension.  MSVC does not provide this extension.

With `g++` you can detect this with, for example, the command line option `-pedantic-errors`, which will tell you that you are trying to use a C99 feature that is not part of C++. For example,

`foo.cpp`:

```
void foo(int n) {
    int x[n];
}
```

```
% g++ -pedantic-errors -c foo.cpp
foo.cpp:2:11: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
    int x[n];
          ^
1 error generated.
```

**Comment by ilayn** [comment]
Ah OK, then that explains why I did not encounter during Fortran translation to C since I used `-wall -wextra -wpedantic` and did not encounter anything related to that.

**Comment by steppi** [comment]
> With `g++` you can detect this with, for example, the command line option `-pedantic-errors`, which will tell you that you are trying to use a C99 feature that is not part of C++. For example,

Thanks @WarrenWeckesser. @czgdp1807, can you add `--pedantic-errors` to the `-Csetup-args` here?

https://github.com/scipy/scipy/blob/a95defcd0f0f9509feac3198dc9100908bff5492/.github/workflows/linux.yml#L536

This job was intended to give a reasonably strict check for compiler warnings, so I think this would be a good fit here.

**Comment by steppi** [comment]
> Yes what I mean is that the reason why amos did not use new and delete is that they are similar to malloc and free dynamic memory. #20258 For some reason they (albert and irwin) did not like that linking back to a discussion about cupy or something.

It looks like we might need to use conditional compilation to have a separate code path for these arrays on CUDA. I'll look into that later on.

**Review by steppi — APPROVED** [review]
Let's get this in for now, and we'll see what can be done about making this work on CUDA later on. Thanks @czgdp1807.

I'd mentioned adding `--pedantic-errors` to a CI job I'd just added for catching build warnings, but I can follow up with that.

**Pull request merged**
