### PR TITLE
TST: sparse: mark some test64bit methods as xslow.

### PR DESCRIPTION
**Pull request by dschult**
**Proposal:**
Mark some Test64Bit tests as xslow to allow them to be run occasionally but not in CI for every push.

**Details:**
After #20895 the sparse `test_base.py` tests are run on sparray and spmatrix. Despite much of the code being the same, the differences between interfaces is becoming sufficient to have bugs creep in due to only testing one set of classes. But now, the tests have grown from taking 35s to 62s (on my laptop). The approach taken for that PR is to restrict the changes to adding new tests. So we added tests for sparray and did not remove any for spmatrix.

Most of the additional time comes from the Test64Bit class where we rerun the entire test suite for each mutated version of the `get_index_dtype` function. The Test64Bit class runs 9 methods each of which take 5s. 4 methods run on sparray classes and 5 on spmatrix (the 5th tests downcasting indices for small index values which sparray doesn't allow).

This PR considers which if any of the tests we could remove. It is restricted only to the 9 methods which rerun the rest of the test suite. One test `test_no_64` is only run for spmatrix. Two seemingly out of date tests are `test_resiliency_random` for sparray and also for spmatrix. The remaining 6 are sparray and spmatrix versions of 3 test methods: `test_resiliency_limit_10`, `test_resiliency_all_32`, and `test_resiliency_all_64`. Each method takes ~5.5s to run all the tests in the rest of the test suite. Most of the tests are testing the same code for sparray and spmatrix classes. Outside of Test64Bit, all the tests are run via the normal test suite using the actual `get_index_dtype` function. These Test64Bit methods change that function to e.g. "return 64-bit if shape is bigger than 10 in any dimension", or "return 32-bit for all cases". 

Two method types deserve special treatment: `test_no_64` and `test_resiliency_random`.

The `test_no_64` method only makes sense for spmatrix because sparray does not choose index dtype based on index values -- no value based dtype choice. This is the method within Test64Bit that seems to appear most often in Issues and PRs over the years, though not as much lately.  So we should run that for spmatrix only and we should continue to run it. 

The two `test_resiliency_random` cases generate 32-bit or 64-bit dtypes randomly changing the result even for the same situation. It seems tricky to think about what that would test. But comments in the code indicate that BSR format in 2014 had a method `eliminate_zeros` which assumed that indices were not copied when using the csr constructor. By making the dtype "random" the test is forcing the code to change dtype fairly often which forces copies to be made. The BSR method was fixed by Spring 2016. But the tests remain untouched since 2014. This makes me feel that the tests are no longer effective, and given their cost we should remove them. We are no longer testing for the case that the test was created for.

The other three method cases (6 methods) should likely be run only for one of sparray or spmatrix, with the other being run occasionally to check for bugs that only arise in one or the other. The spmatrix code will change less moving forward so it makes sense to run those methods occasionally for spmatrix, relying on the sparray tests to catch most if not all introduced bugs. Up until #20895 the tests were only run on spmatrix because of code overlap. It seems like a good time to switch to only CI testing them on sparray. The spmatrix versions can be marked xslow to allow them to be run occasionally.

**`slow` vs `xslow`:** 
The [continuous integration](https://docs.scipy.org/doc/scipy/dev/contributor/continuous_integration.html#:~:text=Marking%20the%20test%20as%20slow,parts%20of%20it%20as%20slow.) doc page states that tests be marked `slow` if they can be considered tested after running on only a few systems. This is not the case for `Test64Bit` tests as the point is to run them over all system types (especially 32-bit vs 64-bit). So I propose we remove the `slow` marks created in #20895.  The above CI doc page also says that `xslow` should be used for tests that don't need to run for every PR, but can be run occasionally. This is the treatment I propose for tests we want to avoid running for every push. They can still be run occasionally.

**The resulting proposal** (implemented in this PR) does the following:
- for spmatrix: run `test_no_64` normally in CI
- for spmatrix: mark as xslow the other Test64Bit test methods
- for sparray: mark `test_resiliency_random` as xslow (or remove it completely)
- for sparray: run the other methods normally in CI.

The result will be 4 methods run for each push (1 spmatrix and 3 sparray). The other 5 methods will be marked `xslow` (4 spmatrix and 1 sparray). If we choose to remove `test_resiliency_random` it would be 3 `xslow` methods all using spmatrix.

Comparing to `main` before #20895 which ran only the spmatrix suite of 5 methods, we have added the sparray suite (outside of `Test64Bit`) and reduced the `Test64Bit` methods to 4 methods. Note: adding sparray tests reruns the suite once so adds ~5s to the time for tests. Actually, there is still ~4s addition because of the `NonCanonical` test classes which are not rerun in `Test64Bit` but are run for sparray in addition to their previous runs for spmatrix.

**The total time for normal CI runs should be approximately the same between before #20895 and after this PR.**

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Thanks for putting this together. I hope we won't need to merge it, because hopefully the CI will tolerate the increased test load, and eventually we can eliminate the extra tests once spmatrix finally gets deprecated.

**Review by rgommers — COMMENTED** [review]
Thanks for looking at this @dschult! Switching around array and matrix testing, preferring array, seems right by now indeed.
 
> This is not the case for `Test64Bit` tests as the point is to run them over all system types (especially 32-bit vs 64-bit). So I propose we remove the `slow` marks created in #20895.

We only have a single 32-bit CI job, so I don't think this is a particularly convincing argument. I'd keep the `slow` mark and ensure the test runs in the 32-bit job (it's in `.github/workflows/linux.yml`) instead.

The parametrization of these tests is massive - `test_base.py` alone is >13,000 tests out of a total of ~75,000 tests in SciPy as a whole. What I'd suggest is to also have a look at the `cases_64_bit` generator. The most important tests are for CSR/CSC/COO, so I think running those more often makes sense. The DOK/LIL/DIA formats are (a) very rarely used and (b) mostly defer to CSR anyway, so I think marking those as `xslow` would be reasonable.

We've also never had a bug report for `Test64BitMatrix` or `Test64BitArray` I think (unless GitHub search is deceiving me), so this isn't particularly fragile or platform-specific code. `Test64BitArray` alone takes about 8% of the runtime of a default test suite run with `python dev.py test` (and `sparse/tests/` takes ~20%, 50s out of 250s on macOS arm64), so I'd say we should not be too liberal in duplicating test execution.

**Comment by dschult** [comment]
Thanks @rgommers for these comments!

The tip to focus on the 32-bit CI job is intriguing. That makes it easier to focus where we test it.

And limiting or splitting `cases_64_bit` could be a nice way to reduce the explosion rate. Formats `DOK` and `LIL` already have comments there that they are only included because they convert to the others. Also, there are ~700 tests yielded by `cases_64_bit` that don't result in a call to `get_index_dtype`, so removing them somehow from the stream would be helpful too.

Looking for past bug reports probably should search for `Test64Bit` rather than the recent names `Test64BitArray` and `Test64BitMatrix`. But my quick search shows ~15 Issues and ~15 PRs most of which are not specific to these classes, but are included with identical failures on the non-64Bit versions of the test.

Also, moving the Test64Bit classes into a separate module might help ease test specification, especially for local testing. 

I'll look into all these approaches. Thanks!

**Comment by dschult** [comment]
I'm going to move this conversation to #21743 which supersedes this work.

**Pull request closed without merging**
