### PR TITLE
Update scipy/signal/ltisys.py

### PR DESCRIPTION
**Pull request by Xprez000**
The proposed modification concerns step, step2 and dstep. It adds an argument M for an arbitrary step amplitude (by default, M=1). For many linearized non-linear systems, a step amplitude M=1 is too large.

### CODE REVIEW

**Comment by ilayn** [comment]
@Xprez000 Thank you for the PR. This is indeed a good feature. However, currently your PR can't be added because you are modifying the keyword order which will break backwards compatibility of the existing code. If need be the simplest workaorund is to scale the system or use d/lsim with a scaled input. 

In general, step is overwhelmingly accepted as a 1. input though. Hence, there will probably be resistance to change this.

**Review by tylerjereddy — COMMENTED** [review]
Some unit tests would likely be suitable too, but probably contingent on some kind of consensus about whether an extra argument can be added without much controversy.

**Comment by Xprez000** [comment]
@ilayn Thank you for your quick reply. I agree that the enhancement I proposed can be seen as a duplicate of what can easily be done with d/lsim with an arbitrary input u. The pull request can be closed, unless others see an advantage in having such a feature for step.

**Comment by larsoner** [comment]
I'll close then, thanks for looking into it @Xprez000 @ilayn

**Pull request closed without merging**
