### PR TITLE
DOC : let PDF be with better bookmarks (and TOC) for Tutorial chapter

### PR DESCRIPTION
**Pull request by jfbu**
This adds to PDF suitable bookmarks for the sections in the tutorial, and also in the main table of contents at start of document.

### CODE REVIEW

**Comment by jfbu** [comment]
here is how it looks like, on left the (opened) PDF bookmarks (shown in Skim.app on Mac OS), on the right a part of the TOC.

capture d ecran 2018-04-02 a 01 02 12

**Comment by ilayn** [comment]
Thanks @jfbu !

**Comment by pv** [comment]
If the index TOC depth can be changed separately from what gets printed, then it could be increased to the maximum depth. Pdf readers usually show this as a collapsable tree anyway.

**Comment by jfbu** [comment]
Yes it is possible to influence the PDF bookmarks depth independently of what gets printed in the document itself. Good idea indeed to increase it to maximum. I will investigate.

**Comment by jfbu** [comment]
@pv PDF with maximal depth bookmarks done at #8660

**Pull request merged**
