### PR TITLE
ENH: add a unique function for sparse matrices

### PR DESCRIPTION
**Pull request by duncanka**
I was surprised a while back to find that while there's a [`numpy.unique`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html) function, there was no equivalent function for sparse SciPy matrices. So I wrote one. :slightly_smiling_face:

After I'd built it for the application I was working on, it was already close to in shape for submission, so I figured I might as well share first and discuss later. Happy to implement any suggested changes, of course.

The basic strategy is to convert to a CSR matrix, run `numpy.unique` on the `.data` attribute of that matrix, and modify the results to account for all the missing zeros.

I had to make one important modification to the `numpy.unique` interface: when returning `unique_inverse`, the indices to reconstruct the original array from the unique array, it doesn't make sense for a sparse matrix to return the indices of all those zeros. Instead, I return a 2 x n array, where the first row gives the linearized indices of the nonzero elements in the original matrix, and the second row gives the indices into the uniques array where those nonzero elements' values can be found.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Your remaining TravisCI failures are due to (a) examples in docstrings need to be runnable and you have some undefined variables, and (b) we need to be compatible with numpy 1.8.2, which doesn't support the `return_counts` keyword argument.

But aside from that, let's talk about design and use-cases. I can see the use of a sparse-compatible `unique` function, and I think you've added it to a good location. I'm not entirely convinced that the `return_index` and `return_inverse` arguments are worth the added complexity, though. It doesn't make a lot of sense (to me) to use linearized indices for a sparse matrix that must always be two-dimensional and doesn't support linear indexing. Do you have a use-case for that part, or are you looking to emulate the numpy API?

I also think it might be reasonable to ignore structural (i.e., non-stored) zeros in the returned unique values. Again, I'd need to look at some use-cases to see what makes sense.

Finally, be careful when dealing with non-canonical sparse matrix inputs (with duplicate values). The current test cases for `test_extract.py` don't include this, but it's possible for some formats including CSR to store multiple values at the same index. These duplicates are summed when computing the final value, which can make code operating directly on the `.data` member difficult to get right. This method is probably what you want to use:
https://github.com/scipy/scipy/blob/676da8f65d38cd62c89799aec7444df227424e04/scipy/sparse/data.py#L32

**Comment by duncanka** [comment]
I was definitely looking to emulate the numpy API, but I did also have a specific use case in mind. I was trying to resample a highly class-imbalanced dataset. To that end, I wanted to know:
- The unique set of labels
- The indices in the dataset (and the corresponding label vector) of each label
- How many times each label appeared

I ultimately realized my label array wasn't sparse enough to merit a sparse matrix. Also, there's now an imbalanced-learn contrib package. But I could imagine such use cases being useful in the future.

**Comment by jnothman** [comment]
I agree that including structural zeros in `return_inverse` seems pointless, but I disagree with @perimosocordiae that we should generally ignore structural zeros. It gets back to the question of sparse matrix semantics: whether we are using it as a matrix substitute or a masked array substitute. Currently we should always assume the latter unless we have an explicit switch for it.

In the case where 0 is also the minimum value in the matrix, `return_inverse` could return a sparse matrix, but this might be madness. I think it might be best not to support `return_inverse` for now, as a fundamentally non-sparse structure.

Btw, these days, numpy.unique also supports `return_counts` and `axis`... At least the latter would be useful here!

**Comment by WarrenWeckesser** [comment]
> ... whether we are using it as a matrix substitute or a masked array substitute. Currently we should always assume the latter unless we have an explicit switch for it.

Wait, what?  Did you really mean "the latter"?  The default semantics of a sparse matrix should be a matrix with lots of *zeros*, not a matrix with lots of masked values.  But maybe I'm not seeing the full context of that comment.

**Comment by jnothman** [comment]
No, I did not :) I meant the former.

**Comment by WarrenWeckesser** [comment]
OK, that's good to know. :)

**Comment by jnothman** [comment]
(Note however that [csgraph](https://docs.scipy.org/doc/scipy/reference/sparse.csgraph.html) routines do treat sparse matrices as masked arrays, with explicit 0-values being interpreted as 0-weighted edges and implicit structural zeros as disconnection.)

**Pull request closed without merging**
