### PR TITLE
CI: don't run GitHub Actions on fork or in cron job

### LINKED ISSUE #12917: GitHub Actions nightly build triggered on forks
It turns out nightly builds have been running on my fork for 5 months, so since commit eb3717130a probably. I only recently started noticing, because I happened to have the most recent commit on master being one that was failing. I suspect nightly builds are running on all forks.

I'm not yet very familiar with GitHub Actions, but it looks like we're missing something important here. Any ideas @andyfaff, @tylerjereddy?

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-12917

~From reading the docs this is the right invocation. Seems like every step needs skipping individually. Looks like a poor design, but there's no way currently to skip the whole action.~ EDIT: the `if` conditional apparently can be one level up from what the docs say.

### CODE REVIEW

**Comment by larsoner** [comment]
I was [able to put the conditional a level up](https://github.com/scipy/scipy/pull/8779/files#diff-74f2c76ca60a3d580c65343df39da81eR15) when developing #8779 and it seemed to work on my local fork

**Comment by larsoner** [comment]
(feel free to take the entire conditional from #8779 and put it here and just add this extra condition to it, and I can rebase #8779 )

**Comment by rgommers** [comment]
Thanks Eric, let me give that a try.

**Comment by andyfaff** [comment]
I think that the wasteful part here is mainly the schedule line. Can we just get rid of that to start with? I think it can be valuable retaining the ability to run ci on personal forks. Sometimes when I'm making a PR with a lot of changes I use the ci run on my personal fork to fix most of the issues before submitting a PR. Personal ci runs will only occur if people are making commits to their fork, which isnt a large number of people.

**Comment by rgommers** [comment]
It happens each time you push to `master` though, which happens (a) for people like me who keep their forks up to date, and (b) for newbies who develop on master. I think if you want to run CI on master of your own fork you can just delete this line as the explicit trigger?

You can also run TravisCI or other CI on your own fork, but it's all opt-in. I'm not sure why we'd want this to be opt-out instead.

**Review by larsoner — APPROVED** [review]

**Comment by rgommers** [comment]
I still get two emails with failures every night, so merging this. Thanks for the feedback all. As another follow-up we may document how to run CI on a fork. I'd think TravisCI or Azure would be most useful in catching issues, because of platform support.

**Comment by andyfaff** [comment]
Nice one.
GitHub actions runs Linux, windows, macOS, but not arm at the moment.

**Comment by rgommers** [comment]
The GH Actions workflows we have just run macOS though, plus a now-unnecessary build against `python3.9-dev`?

**Comment by andyfaff** [comment]
The point I was trying to make is that gh actions  has as many platforms as the others.
`3.10-dev` might be possible now.

**Comment by rgommers** [comment]
> The point I was trying to make is that gh actions has as many platforms as the others.

It does (almost), but we're not using it. I think if there's really value in running CI on a fork to catch failures, it would be good to make that easy/efficient, so it actually catches the most common issues without running a ton of tests (because then you may as well open a PR straight away). I think a reasonable subset would be:

- the `lint` job
- the doc build
- one Windows build
- one `aarch64` build

> `3.10-dev` might be possible now.

We should probably leave that alone for at least 9 months, it's very early in the release cycle so failures are most likely going to be Python or NumPy bugs or changes that will be reverted.

**Pull request merged**
