### PR TITLE
DOC: Remove double section and too long header underline.

### PR DESCRIPTION
**Pull request by Carreau**
Numpydoc choke on the double section, the longer header is mostly
aesthetic.

### CODE REVIEW

**Review by WarrenWeckesser — APPROVED** [review]
Looks good, thanks.

**Comment by WarrenWeckesser** [comment]
I'm not sure why a bunch of the tests were cancelled.

**Comment by ilayn** [comment]
I did it. Waiting for the artifact for last second check then will merge

**Comment by ilayn** [comment]
All good thanks @Carreau @WarrenWeckesser

**Pull request merged**
