### PR TITLE
MAINT: 1.8.0 rc3 backports round 1

### PR DESCRIPTION
**Pull request by tylerjereddy**
- we have accumulated 20 merged backport PRs and they have all
been cherry-picked into here, along with a specific request for [author
list update](https://github.com/scipy/scipy/pull/15161#issuecomment-999216314)
- decent chance a bit of effort will be needed to get the CI green on maintenance
branch
- why is `1.8.0` taking a while?
  - `PROPACK` challenges here: https://github.com/conda-forge/scipy-feedstock/pull/198
  - doc deploy issues, maybe we can just try Ralf's idea: https://github.com/scipy/scipy/issues/14267#issuecomment-1003380812

### CODE REVIEW

**Comment by ev-br** [comment]
I actually wonder if we should disable propack in 1.8.0, or make it opt-in, at least the sigfaulting functionality.

**Comment by tylerjereddy** [comment]
Thoughts on ignoring the linter complaints? I think the `undefined name` issues are b/c the linter cannot handle `importlib` when used instead of `import`?

```
scipy/_build_utils/_fortran.py:146:9: E128 continuation line under-indented for visual indent
scipy/signal/tests/test_filter_design.py:33:80: E501 line too long (91 > 79 characters)
scipy/sparse/tests/test_base.py:4824:80: E501 line too long (81 > 79 characters)
scipy/special/_testutils.py:27:80: E501 line too long (91 > 79 characters)
setup.py:27:1: E402 module level import not at top of file
setup.py:237:16: F821 undefined name '_pep440'
setup.py:237:53: F821 undefined name '_pep440'
setup.py:349:16: F821 undefined name '_pep440'
setup.py:349:49: F821 undefined name '_pep440'
tools/cythonize.py:87:80: E501 line too long (81 > 79 characters) 
```

**Comment by rgommers** [comment]
That's fine, `Lint` issues can pretty much always be ignored.

**Comment by tylerjereddy** [comment]
32-bit linux `stats` test fails pasted below the fold:

@mdhaber these have shown up recently maybe? was there a patch for it?

<details>

```
2022-01-16T22:07:17.9426107Z =================================== FAILURES ===================================
2022-01-16T22:07:17.9426790Z __________ TestStudentizedRange.test_moment_against_mp[case_result1] ___________
2022-01-16T22:07:17.9428314Z [gw1] linux -- Python 3.8.0 /usr/bin/python3.8
2022-01-16T22:07:17.9428938Z scipy/stats/tests/test_distributions.py:4655: in test_moment_against_mp
2022-01-16T22:07:17.9429507Z     res = stats.studentized_range.moment(*mkv)
2022-01-16T22:07:17.9430529Z         case_result = {'mp_result': 1.8342745127927962, 'src_case': {'expected_atol': 1e-09, 'expected_rtol': 1e-09, 'k': 3, 'm': 1, ...}}
2022-01-16T22:07:17.9431269Z         mkv        = (1, 3, 10)
2022-01-16T22:07:17.9431736Z         mp_result  = 1.8342745127927962
2022-01-16T22:07:17.9432301Z         self       = <scipy.stats.tests.test_distributions.TestStudentizedRange object at 0xd28650d0>
2022-01-16T22:07:17.9433253Z         src_case   = {'expected_atol': 1e-09, 'expected_rtol': 1e-09, 'k': 3, 'm': 1, ...}
2022-01-16T22:07:17.9434038Z scipy/stats/_distn_infrastructure.py:1297: in moment
2022-01-16T22:07:17.9434554Z     val[...] = _moment_from_stats(n, mu, mu2, g1, g2, self._munp, shapes)
2022-01-16T22:07:17.9435096Z         args       = [array([3]), array([10]), array([0]), array([1])]
2022-01-16T22:07:17.9435559Z         g1         = None
2022-01-16T22:07:17.9435961Z         g2         = None
2022-01-16T22:07:17.9436343Z         i0         = True
2022-01-16T22:07:17.9436745Z         i1         = True
2022-01-16T22:07:17.9437124Z         i2         = False
2022-01-16T22:07:17.9437520Z         kwds       = {}
2022-01-16T22:07:17.9437923Z         loc        = array([0])
2022-01-16T22:07:17.9438532Z         mdict      = {'moments': 'm'}
2022-01-16T22:07:17.9438987Z         mu         = None
2022-01-16T22:07:17.9439374Z         mu2        = None
2022-01-16T22:07:17.9439788Z         n          = 1
2022-01-16T22:07:17.9440255Z         scale      = array([1])
2022-01-16T22:07:17.9440962Z         self       = <scipy.stats._continuous_distns.studentized_range_gen object at 0xebb2b3e8>
2022-01-16T22:07:17.9441531Z         shapes     = [array([3]), array([10])]
2022-01-16T22:07:17.9442525Z         val        = array([1.])
2022-01-16T22:07:17.9445367Z scipy/stats/_distn_infrastructure.py:371: in _moment_from_stats
2022-01-16T22:07:17.9445967Z     val = moment_func(1, *args)
2022-01-16T22:07:17.9446884Z         args       = [array([3]), array([10])]
2022-01-16T22:07:17.9447340Z         g1         = None
2022-01-16T22:07:17.9447770Z         g2         = None
2022-01-16T22:07:17.9448370Z         moment_func = <bound method studentized_range_gen._munp of <scipy.stats._continuous_distns.studentized_range_gen object at 0xebb2b3e8>>
2022-01-16T22:07:17.9448998Z         mu         = None
2022-01-16T22:07:17.9449421Z         mu2        = None
2022-01-16T22:07:17.9449830Z         n          = 1
2022-01-16T22:07:17.9450369Z scipy/stats/_continuous_distns.py:9549: in _munp
2022-01-16T22:07:17.9450868Z     return np.float64(ufunc(K, k, df))
2022-01-16T22:07:17.9451395Z E   RuntimeWarning: invalid value encountered in ? (vectorized)
2022-01-16T22:07:17.9451878Z         K          = 1
2022-01-16T22:07:17.9452316Z         _a         = 0
2022-01-16T22:07:17.9452737Z         _b         = inf
2022-01-16T22:07:17.9453285Z         _single_moment = <function studentized_range_gen._munp.<locals>._single_moment at 0xd283efa0>
2022-01-16T22:07:17.9454452Z         cython_symbol = '_studentized_range_moment'
2022-01-16T22:07:17.9454955Z         df         = array([10])
2022-01-16T22:07:17.9455409Z         k          = array([3])
2022-01-16T22:07:17.9455950Z         self       = <scipy.stats._continuous_distns.studentized_range_gen object at 0xebb2b3e8>
2022-01-16T22:07:17.9456763Z         ufunc      = <ufunc '? (vectorized)'>
2022-01-16T22:07:17.9457402Z ________________ TestStudentizedRange.test_moment_vectorization ________________
2022-01-16T22:07:17.9458161Z [gw1] linux -- Python 3.8.0 /usr/bin/python3.8
2022-01-16T22:07:17.9458882Z scipy/stats/tests/test_distributions.py:4694: in test_moment_vectorization
2022-01-16T22:07:17.9459457Z     m = stats.studentized_range._munp([1, 2], [4, 5], [10, 11])
2022-01-16T22:07:17.9460072Z         self       = <scipy.stats.tests.test_distributions.TestStudentizedRange object at 0xd256dca0>
2022-01-16T22:07:17.9460672Z scipy/stats/_continuous_distns.py:9549: in _munp
2022-01-16T22:07:17.9461181Z     return np.float64(ufunc(K, k, df))
2022-01-16T22:07:17.9461704Z E   RuntimeWarning: invalid value encountered in ? (vectorized)
2022-01-16T22:07:17.9462195Z         K          = [1, 2]
2022-01-16T22:07:17.9462623Z         _a         = 0
2022-01-16T22:07:17.9463071Z         _b         = inf
2022-01-16T22:07:17.9463625Z         _single_moment = <function studentized_range_gen._munp.<locals>._single_moment at 0xd2a78bb0>
2022-01-16T22:07:17.9464414Z         cython_symbol = '_studentized_range_moment'
2022-01-16T22:07:17.9464919Z         df         = [10, 11]
2022-01-16T22:07:17.9465359Z         k          = [4, 5]
2022-01-16T22:07:17.9465895Z         self       = <scipy.stats._continuous_distns.studentized_range_gen object at 0xebb2b3e8>
2022-01-16T22:07:17.9466656Z         ufunc      = <ufunc '? (vectorized)'>
2022-01-16T22:07:17.9467488Z - generated xml file: /scipy/build/testenv/lib/python3.8/site-packages/junit/test-results.xml -
```

</details>

**Comment by tylerjereddy** [comment]
It looks like the 32-bit stats failures are somewhat stochastic.. the CI now just has the timeouts and lint issues, so probably ok. I may merge tomorrow morning and then deal with the bigger problems with a somewhat cleaner backporting slate.

**Pull request merged**
