### PR TITLE
TST: fix a bug in the circular import test.

### PR DESCRIPTION
**Pull request by rgommers**
Apparently we don't run it too often....

### CODE REVIEW

**Comment by larsoner** [comment]
This seems to suggest that it is not run by CIs, otherwise it should have failed. Worth looking into/fixing here?

**Comment by pv** [comment]
Wild guess: underscore in module name...

**Comment by rgommers** [comment]
yes worth looking into. I think Pauli's guess is right. no time in the next few days though, in proposal writing mode. can leave this open for a bit, it's not super urgent

**Comment by larsoner** [comment]
I think that the tests in `scipy/_lib` work because I saw them fail on CIs recently I think. I suspect the `runtests.py` process does include `scipy/_lib` (it's necessary for `scipy` functionality) in what gets built and then tested, but not `scipy/_build_utils` (because it's presumably only necessary during build time).

If this is the right trail to go down, maybe we should move any tests from `_build_utils` to `_lib`.

**Comment by pv** [comment]
@larsoner: yes, the `_build_utils/tests` directory is missing. So should be solvable by some `setup.py` editing.

**Comment by larsoner** [comment]
> So should be solvable by some setup.py editing.

I take this to mean we should change things to include `scipy._build_utils` as a submodule like we include `scipy._lib`. I'm not sure this is the right idea, though, since users shouldn't need this code to actually run SciPy. It seems cleaner to just move the tests to `scipy/_lib/tests` rather than add a module solely for the purposes of getting those tests to run. Unless there are other reasons to include it...?

**Comment by larsoner** [comment]
... never mind, looks like `config.add_subpackage('_build_utils')` is already in `setup.py`. I'll see if I can figure out why the tests are not included.

**Comment by peterbell10** [comment]
I think `_build_utils` is missing a `setup.py` file which adds the `tests` folder as a data directory.

**Comment by larsoner** [comment]
@peterbell10 I agree, opening a PR now that should fail without @rgommers's commit

**Pull request merged**
