### PR TITLE
TST: Add tests for signal.residue

### PR DESCRIPTION
**Pull request by Psirus**
#### Reference issue
This is a start on #4464.

#### What does this implement/fix?
I've added four tests for `residue` suggested in the above issue. Before I add further tests (for `residuez` etc.) I would like to know
- a) whether the format is okay?
- b) which of the many given examples to implement?

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @Psirus. The format of your tests looks fine. Note that the 32-bit Linux test failure on Azure is real. 

Did you see gh-4591? That seems to be stalled, but would be good to build on top of it. The test failure may be related to it.

**Comment by Psirus** [comment]
Okay, I'll have a look at the test failure later, although it seems curious that Windows 3.6, and Linux 64bit 3.6 (under Travis) work. Any quick idea what I should be looking for?

As for the other PR, no I did not see it before. It seems indeed preferable to continue this work. I'll wait for a response to your comment there. If none comes, what would be the best course of action, just copying the code to my branch?

**Comment by larsoner** [comment]
The failure is here:

https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=3422&view=logs&jobId=dca3794b-c3dc-52e6-709a-3545ea017448

The numbers are correct but in a different order. I would try to understand first why the order differs based on architecture (maybe just slight numerical differences?)

**Comment by Psirus** [comment]
So changing `cmplx_sort` in the same way as in #4591 will make the failure go away. But as discussed in the other PR, this changes `unique_roots`, which additionally seems to be broken for complex inputs. I guess a proper fix would involve addressing that.

**Comment by rgommers** [comment]
Can the two issues be separated, or does that give another problem/inconsistency? I mean, rename the current `cmplx_sort` to a private name and change `unique_roots` to use that? And then introduce a new `cmplx_sort` with the fix that makes your tests pass.

**Comment by Psirus** [comment]
No, that introduces an inconsistency. The functions `invres` and `invresz` use both `cmplx_sort` and `unique_roots`, and the tests fail if the sort used in `unique_roots` is not the same as in `invres`.

**Comment by rgommers** [comment]
That's too bad. Okay then I'm not sure, hope that one of our `signal` experts has time to take a closer look.

**Comment by larsoner** [comment]
Closing as superseded by #10997, but @Psirus let me know if you disagree

**Pull request closed without merging**
