### PR TITLE
DEP: stats: improve deprecation of private but present modules

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

Part of https://github.com/scipy/scipy/issues/18279
#### What does this implement/fix?

Finishes #18835 for the rest of stats

### CODE REVIEW

**Review by mdhaber — CHANGES_REQUESTED** [review]
Looks pretty good but:
- I'm surprised the linter didn't fail since there are some files that don't end with a blank line.
- Should `import scipy.stats.morestats` emit a deprecation warning? It never has before, but it probably should.
- I think we forgot a condition when things *are* supposed to be imported from a sub-sub-package. Example below.

```python3
from scipy.stats.mstats_basic import brunnermunzel
``` 
currently emits 
> DeprecationWarning: Please import `brunnermunzel` from the `scipy.stats` namespace; the `scipy.stats.mstats_basic` namespace is deprecated and will be removed in SciPy 2.0.0.

This is a bit misleading because there are two versions of `brunnermunzel`, and the one that was in `mstats_basic` before is actually in `stats.mstats` now, not `stats`.  Besides the message, this is actually importing `scipy.stats.brunnermunzel` whereas is should import `scipy.stats.mstats.brunnermunzel`.

Similarly,
```python3
from scipy.stats.mstats_basic import msign
```
emits

> DeprecationWarning: `scipy.stats.mstats_basic.msign` is deprecated along with the `scipy.stats.mstats_basic` namespace. `scipy.stats.mstats_basic.msign` will be removed in SciPy 1.13.0, and the `scipy.stats.mstats_basic` namespace will be removed in SciPy 2.0.0.

but it really should import `scipy.stats.mstats.msign` and emit a warning like:

> DeprecationWarning: Please import `msign` from the `scipy.stats.mstats` namespace; the `scipy.stats.mstats_basic` namespace is deprecated and will be removed in SciPy 2.0.0.

**Comment by j-bowhay** [comment]
Thanks @mdhaber, I have addressed points 1 & 3. I agree in principle that `import scipy.stats.morestats` should raise a warning. The obvious way to do this is just to add a `warning.warn` to the file but then `from scipy.stats.morestats import  brunnermunzel` would end up with two warnings (one from executing the file at import time and the other from the `__getattr__`). It looks like there is some [magic](https://stackoverflow.com/a/19308270/3320221) you can do to detect what type of import is being used but I am not sure if that would be a good idea.

**Comment by tupui** [comment]
I think the inconvenience would be ok vs trying to craft some magic. Whether it's one or two warnings, on the user side the resolution should be the same with a filter which should catch both.

**Review by mdhaber — APPROVED** [review]
This looks better now. I do think we should emit when importing one of these modules, but that is a separate issue and can be handled in a separate PR.

**Pull request merged**
