### PR TITLE
DEP: deprecate planck distribution in scipy.stats

### LINKED ISSUE #9359: Planck distribution is a geometric distribution
`stats.planck` is just a geometric distribution `stats.geom` with `p = 1 - exp(-lambda)`. I am not aware that Planck distribution is a known name for it.

Currently, `planck` is incorrectly defined for negative `lambda` as well (see #9358).

Should `planck` be deprecated?

### PR DESCRIPTION
**Pull request by chrisb83**
Closes #9359 

Probably the standards tests of the distributions still need to be adjusted to handle the deprecation warning.

### CODE REVIEW

**Comment by rgommers** [comment]
CI failures are real.

Could you propose this deprecation on the mailing list? `planck` has existed for a long time, so not sure what the background or usage is.

**Comment by ev-br** [comment]
Can you add a precise equivalence to the deprecation message. 

Rationale: if we're making people fix up their undermaintained code, let's make it as easy as possible for them.

**Comment by chrisb83** [comment]
> Can you add a precise equivalence to the deprecation message.

Agree, I will add further details. Let's wait for feedback from the mailing list.

**Comment by rlucas7** [comment]
Is a sentence in the docstring for geom that explains s how to make a Planck distribution warranted? 

I could see this go either way, could make a long uninformative docstring for some distributions with lots of relationships and also it could be useful for a user of scipy.stats. 

Sincerely, 

-Lucas Roberts

**Comment by chrisb83** [comment]
> Is a sentence in the docstring for geom that explains s how to make a Planck distribution warranted?

No, neither docstring mentions the other distribution.

**Comment by rlucas7** [comment]
I agree neither docstring mentions the other distribution now. Once the Planck dist is deprecated though someone might want to implement one, someone new to scipy.stats. 
Is it reasonable to assume they should know how to do this themselves (or ask on SO or the user mailing list)?

Sincerely, 

-Lucas Roberts

**Comment by rkern** [comment]
If this PR gets approved, the docstring modifications should be done in this PR, not put off for later.

**Comment by chrisb83** [comment]
Discussion on mailing list: leave Planck in stats, add reference to geom in docstring.

Closing this PR, I will create a new one to update the documentation.

**Pull request closed without merging**
