### PR TITLE
MAINT: sparse: increase test coverage

### PR DESCRIPTION
**Pull request by perimosocordiae**
Also removes some dead code. There are still many uncovered lines, but this was an easy start.

### CODE REVIEW

**Comment by larsmans** [comment]
Why are the tests not running?

**Comment by perimosocordiae** [comment]
No idea, I hadn't even noticed. Should I close/reopen, or is there a better way to trigger Travis?

**Comment by rgommers** [comment]
don't think that there's a better way; rerunning the tests is a button click, but now there's nothing to start with

**Comment by rgommers** [comment]
triggered now

**Comment by perimosocordiae** [comment]
Tests failed on Python 3.4 for CSR/CSC matrices with `bool` dtypes. This looks to be a real error, though I'm not sure why it failed on that test but not any others. Here's a quick repro:

```python
In [2]: x = ss.csr_matrix([[True, False],[False, True]], dtype=bool)

In [3]: (0 - x).todense()
Out[3]:
matrix([[False, False],
        [False, False]], dtype=bool)

In [4]: (-x).todense()
Out[4]:
matrix([[False, False],
        [False, False]], dtype=bool)

In [5]: 0 - x.todense()
Out[5]:
matrix([[-1,  0],
        [ 0, -1]])

In [6]: -x.todense()
Out[6]:
matrix([[False,  True],
        [ True, False]], dtype=bool)
```

**Comment by pv** [comment]
Mark booleans as known failure, merge this PR, and fix the booleans later?

**Comment by perimosocordiae** [comment]
Apparently boolean subtraction was deprecated in numpy 1.9.0, which explains why only some of the Travis runs failed. The existing `test_rsub` has this condition:

```python
        for dtype in self.math_dtypes:
            if (dtype == np.dtype('bool')) and (
                    NumpyVersion(np.__version__) >= '1.9.0.dev'):
                # boolean array subtraction deprecated in 1.9.0
                continue

            yield check, dtype
```

Should I just remove the version check and call it good enough?

**Comment by pv** [comment]
If it's deprecated in Numpy, then we probably should not try to replicate the behavior, so just removing the corresponding tests sounds OK.

**Comment by perimosocordiae** [comment]
Travis is green, so I think this is ready to merge.

**Pull request merged**
