### PR TITLE
MAINT: special: rename C++ library to `xsf`

### PR DESCRIPTION
**Pull request by izaid**
This PR is renaming the internal C++ parts of special to be called xsf (meaning "X special functions"). That particular name has been discussed, particularly with @steppi, but it's also for internal code only and totally invisible to Python. The standard C++ library refers to its special function extension as "sf", so we thought "xsf" made sense.

It really needs this because this internal C++ library is currently called "special", putting us in the situation of having "special/special/..." as has been remarked by many others.

### CODE REVIEW

**Comment by izaid** [comment]
@steppi This is totally done, CI green, and good to go.

**Comment by steppi** [comment]
At a glance, looks good except that `special_wrappers.h` and `special_wrappers.cpp` should be changed to `xsf_wrappers.h` and `xsf_wrappers.cpp`. There's also a header `special.h` that I guess should be `xsf.h`.

**Comment by izaid** [comment]
> At a glance, looks good except that `special_wrappers.h` and `special_wrappers.cpp` should be changed to `xsf_wrappers.h` and `xsf_wrappers.cpp`. There's also a header `special.h` that I guess should be `xsf.h`.

I've just renamed `special_wrappers.h` and `special_wrappers.cpp` to be `xsf`. The header `special.h` is, in fact, to replicate old behaviors for SciPy functions. So think it should rename as is.

In the future, we can make all the names of the C wrappers be `xsf_`, but they are very scrambled at the moment.

**Comment by steppi** [comment]
> I've just renamed `special_wrappers.h` and `special_wrappers.cpp` to be `xsf`. The header `special.h` is, in fact, to replicate old behaviors for SciPy functions. So think it should remain as is.

I see, `scipy/special/xsf.h` isn't a great name either then, but `scipy/special/special.h` is pretty confusing imo. It makes it sound like the header plays a much more prominent role than it actually does. I suggest calling it `xsf_special.h` and putting a comment at the top saying what it does.

**Review by steppi — APPROVED** [review]
Thanks @izaid! This looks good and goes a long way towards making the structure of special more comprehensible.

**Pull request merged**
