### PR TITLE
BUG: The pytest decorator for conditional skipping is 'skipif'

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
LGTM

**Comment by tylerjereddy** [comment]
I wonder if the Python debug CI failure is sporadic: `FAILED scipy/stats/tests/test_sampling.py::test_threading_behaviour`

I don't see it in your other recent PR: gh-15176

**Comment by WarrenWeckesser** [comment]
@tylerjereddy, the failure of the debug build is a mystery to me.  The other failures are the same ones happening elsewhere, and are not related to this PR.

**Comment by WarrenWeckesser** [comment]
> I wonder if the Python debug CI failure is sporadic...

I restarted the github actions, and that check passed.

**Comment by tylerjereddy** [comment]
thanks!

**Pull request merged**
