### PR TITLE
Brent bound

### PR DESCRIPTION
**Pull request by horta**
Function domain (bounds) support for Brent. Guarantee that proposed solutions lie within
the specified range.

### CODE REVIEW

**Comment by person142** [comment]
If the bracket you provide `brent` is a triple `(xa, xb, xc)` with `xa < xb < xc` and `f(xa) > f(xb) < f(xc)` then the solution is (IIRC) guaranteed to lie in the correct interval. So you should be able to get these changes by just changing `bracket` (and passing some keyword parameters on to the internal `bracket` call).

**Comment by Horta** [comment]
Checking on that!

**Comment by josef-pkt** [comment]
In general, I didn't look at the details

#5422 In my use case I found out that the bracket search outside of xa, xb (which I thought were fixed bound xa, xc) worked better than the restricted search. We, scipy.stats.distribution. and statsmodels have or had *expanding* bracket search because the bounds were In some extreme cases too small and needed to be extended.

So, I think being able to use possibly large bound with suggested narrow bounds might be a useful use case, and at least the two point version seems to work that way.

**Comment by person142** [comment]
@Horta: Brent's method is a bracketing method, i.e. you provide an initial bracket `(xa, xb, xc)` with `f(xa) > f(xb) < f(xc)` and at each iteration it computes a (uniformly) smaller bracket contained in the previous one. IOW it always finds a minimum inside the initial interval `(xa, xc)`. (If it doesn't that's a bug.)

Using Brent's method requires finding a bracket, and Scipy's `brent` tries to alleviate that burden by allowing you to provide a (possibly) non-bracketing interval which it tries to upgrade to a bracketing interval by calling `bracket`. It seems reasonable to be able to provide bounds which `bracket` should stay inside, but I haven't read the source carefully enough to know what it's doing. (It seems like `grow_limit` should be related?) It could be that if there are hard bounds a different algorithm would be more appropriate.

**Comment by Horta** [comment]
Thanks for all the input. I have been working on the raised issues. I really need Brent to be reliable in what it should do and preserve some properties that it already has in the current implementation. Namely, user-provided bracket interval as the starting points where Brent fits is parabolic and try to use it to do the next step but also the possibility of Brent leaving the bracket interval. (I try to provide very tight bracket intervals because the function being evaluated, in my case, is way less computational expensive when evaluated on nearby points, but at the same time I cannot guarantee that the solution lies within this tight bracket interval, which is fine for the current Brent implementation.)

Anyway, I will be updating the pull request here and asking for more feedback.

Thank you guys!

**Comment by Horta** [comment]
Please, refer to this new PR: https://github.com/scipy/scipy/pull/6470
I'm suggesting another Brent's method implementation.

**Pull request closed without merging**
