### PR TITLE
DOC: add Examples for interpolate.barycentric_interpolate(), krogh_interpolate(), pchip_interpolate() docstrings

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
fix a part of #7168

#### What does this implement/fix?
add Examples for interpolate.barycentric_interpolate(), krogh_interpolate(), pchip_interpolate() docstrings

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
I updated “see also” in docstrings because there are html issues due to description missing.

**Comment by rgommers** [comment]
See Also changes and `pchip_interpolate` example look good. For the `krogh_interpolate` example there's edge effects:

image

If those are there on purpose, then you should probably say a few words about it in the example.

**Comment by ev-br** [comment]
If the Krogh example is meant to show the Runge effect, then maybe show the Runge function, 1/(1 +25 x**2) ?

**Comment by ev-br** [comment]
If the Krogh example is meant to show the Runge effect, then maybe show the Runge function, 1/(1 +25 x**2) ?

**Comment by AtsushiSakai** [comment]
Thank you for you guys comment. 

> If those are there on purpose,

Honestly, I didn't. There are Runge phenomenons in the example. I think discussing runge phenomenon is useful for some users, but I think it is too much for API document. I think it should be in a tutorial. I can do that in another PR. So, I changed the observed data to a sin curve samples which does' not have the runge effect.

**Comment by rgommers** [comment]
Agreed, that's tutorial-like content, the new `krogh_interpolate` example looks good. However `barycentric_interpolate` has an issue as well (sorry missed that one the first time around):

image

The example code looks fine, not sure what's going on with that output.

**Comment by pv** [comment]
Maybe due to integer arrays. If so, that's a bug in BarycentricInterpolator

**Comment by AtsushiSakai** [comment]
Thay you guys for feedbacks. I think the new 3 API docs should use a same simple sin curve data for consistency. I fixed it. PTAL.

**Comment by rgommers** [comment]
>  think the new 3 API docs should use a same simple sin curve data for consistency

good idea.

LGTM now, merging. Thanks @AtsushiSakai

**Pull request merged**
