### PR TITLE
TST: tolerance bumps for the conda-forge builds

### PR DESCRIPTION
**Pull request by ev-br**
#### Reference issue

addresses three items reported in https://github.com/scipy/scipy/issues/20472

#### What does this implement/fix?

Two RGI tolerance bumps are benign, can be expected, and are due to RGI doing sparse linear algebra under the hood, which is new in SciPy 1.13. Hence am tentatively labeling as backport-candidate. 

The RBF failure is less clear-cut: a test which is apparently flaky checks that pickling and unickling of an RBF instance does not change the evaluated result using an exact equality. I honestly don't know if we can/should really guarantee exact equality. So this PR changes the test to compare results to agree up to ~machine epsilon.
There is nothing in SciPy 1.13 itself to change the behavior, so I'd handwave that it's due to new versions of compilers or linalg libraries.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks so much for the quick response! 🙏
Testing this out in https://github.com/conda-forge/scipy-feedstock/pull/273.

**Comment by h-vetinari** [comment]
FWIW, I think we could also bump the atol in
https://github.com/scipy/scipy/blob/23eb838254cb9dca1df333bcfc54f2967ef68a9d/scipy/sparse/linalg/_eigen/tests/test_svds.py#L269
to 1e-9. That's a single-line change and would take care of one more failure from #20472 (on win+blis).

**Review by j-bowhay — APPROVED** [review]
LGTM but will wait for a response to https://github.com/scipy/scipy/pull/20474#issuecomment-2054269010 before merging

**Comment by ev-br** [comment]
OK, added the `_check_svds` tolerance bump.

**Review by thalassemia — APPROVED** [review]
This also fixes one test failure in gh-20510. Merging now.

**Pull request merged**
