### PR TITLE
BUG: result for insufficient neighbours from cKDTree is wrong.

### LINKED ISSUE #6425: cKDTree INF bug
I'm running into a problem with cKDTree with scipy 0.18.0 on both Windows and Linux.  It doesn't calculate the expected query like KDTree does.  It seems to behave consistently across Python versions as well.

I've tested this on scipy 0.18.0 using Python 2.7, 3.4, and 3.5.  Scipy 0.17.1 and 0.16.0 work with no problems.

Any ideas?

    import numpy as np
    import scipy
    import scipy.spatial

    xyz = np.array([
        [ 0.,   0.,   0.],
        [ 1.01, 0.,   0.],
        [ 0.,   1.,   0.],
        [ 0.,   1.01, 0.],
        [ 1.,   0.,   0.],
        [ 1.,   1.,   0.],],
    dtype='float32')

    ckdt = scipy.spatial.cKDTree(xyz)

    deq, ieq = ckdt.query(xyz, k=4, distance_upper_bound=0.2)
    print(deq)

    #>>> [[ inf  inf  inf  inf]
    # [ inf  inf  inf  inf]
    # [ inf  inf  inf  inf]
    # [ inf  inf  inf  inf]
    # [ inf  inf  inf  inf]
    # [ inf  inf  inf  inf]]

    kdt = scipy.spatial.KDTree(xyz)
    deq2, ieq2 = kdt.query(xyz, k=4, distance_upper_bound=0.2)
    print(deq2)

    #>>> [[ 0.                 inf         inf         inf]
    # [ 0.          0.00999999         inf         inf]
    # [ 0.          0.00999999         inf         inf]
    # [ 0.          0.00999999         inf         inf]
    # [ 0.          0.00999999         inf         inf]
    # [ 0.                 inf         inf         inf]]

### PR DESCRIPTION
**Pull request by rainwoodman**
This shall fixes #6425.

I will add a test case for this too.

### CODE REVIEW

**Comment by ev-br** [comment]
Needs a rebase

**Comment by rainwoodman** [comment]
rebased.

**Comment by ev-br** [comment]
OK, TravisCI is green, so let's merge this. Thanks @rainwoodman

**Comment by rainwoodman** [comment]
Thanks. This reminds me I really need to get back to #5647 at some point..

**Comment by ev-br** [comment]
backported in gh-6557

**Pull request merged**
