### PR TITLE
MAINT: line.startswith shouldn't be bytes

### LINKED ISSUE #11107: scipy.io.mmread generated an error "TypeError: startswith first arg must be str or a tuple of str, not bytes"
scipy.io.mmread generated an error "TypeError: startswith first arg must be str or a tuple of str, not bytes"

For the downloaded matrix-market file; young1c.mtx, from https://math nist.gov/MatrixMarket/data/Harwell-Boeing/acoust/young1c.html,    scipy.io. generated an error. I am working on Windows 10.

What I experienced was:

```
C:\home\textd\Matrices>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> fn = open("young1c.mtx","r")
>>> import scipy.io
>>> x = scipy.io.mmread(fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\scipy\io\mmio.py", line 75, in mmread
    return MMFile().read(source)
  File "C:\Python37\lib\site-packages\scipy\io\mmio.py", line 420, in read
    self._parse_header(stream)
  File "C:\Python37\lib\site-packages\scipy\io\mmio.py", line 484, in _parse_header
    self.__class__.info(stream)
  File "C:\Python37\lib\site-packages\scipy\io\mmio.py", line 246, in info
    while line.startswith(b'%'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

Is there anything wrong with me?

regards,

### PR DESCRIPTION
**Pull request by andyfaff**
closes #11107

### CODE REVIEW

**Comment by andyfaff** [comment]
Only failing on ppc64, which is unrelated.

**Comment by andyfaff** [comment]
instead of `line.startswith('%')` or `line.startswith(b'%')` I've gone for `if line and line[0] in ['%', 37]` because sometimes the file is opened in binary mode, and sometimes as text.

**Comment by andyfaff** [comment]
pinging for a review.

**Review by tylerjereddy — COMMENTED** [review]
I checked with the original issue report file and it seems ok (fixes the error, anyway). I suppose we may not want to include that file in our test suite.

That said, any reason not to provide a simple regression guard:

```python
import scipy.io
import io

scipy.io.mmread(io.StringIO("""%%MatrixMarket matrix coordinate complex symmetric\n
1 1 1\n
1 1 -2.1846000000000e+02  0.0000000000000e+00"""))
```

I have no idea if that is a valid MM file mimic, but it does fail before/pass after for the same reason as the cognate issue.

**Comment by andyfaff** [comment]
Added test

**Comment by andyfaff** [comment]
Test failures are unrelated.

**Comment by tylerjereddy** [comment]
LGTM now, thanks @andyfaff

**Pull request merged**
