### PR TITLE
Fast permutation one-way anova

### PR DESCRIPTION
**Pull request by mortonjt**
This PR is to address extending f_oneway via permutation tests as addressed in https://github.com/scipy/scipy/issues/4399

This algorithm is similar to the t-test found in https://github.com/scipy/scipy/pull/4440

### CODE REVIEW

**Comment by mortonjt** [comment]
Not sure what happened in the last run.  It doesn't look like the tests were completed.

**Comment by ev-br** [comment]
I've restarted the build

**Comment by mortonjt** [comment]
Thanks!

**Comment by josef-pkt** [comment]
Sorry, I don't have any comments at the moment. 
It requires too much thinking, and I am currently not in this neighborhood of statistics.
(similar applies to the related features in statsmodels which also stalled.)

**Comment by mdhaber** [comment]
Closed by gh-13899.

**Pull request closed without merging**
