### PR TITLE
#7557 : fix example code in periodogram

### PR DESCRIPTION
**Pull request by daxlab**

### CODE REVIEW

**Comment by rgommers** [comment]
Test failure is real:

    File "build/testenv/lib/python2.7/site-packages/scipy/signal/spectral.py", line 241, in periodogram
    Failed example:
        np.mean(Pxx_den[10000:])
    Expected:
        0.00099830549215597321
    Got:
        0.0020144678659752865

A factor 2 is missing, commented on gh-7557 as well. Needs an explanation.

**Comment by daxlab** [comment]
@rgommers test passing now.

**Comment by rgommers** [comment]
@daxlab thanks, but we still need an explanation for the factor 2 to resolve what is pointed out in gh-7557

**Comment by thuehlinger** [comment]
```Pxx_den[10000:]```still includes the signal peak. This is way the mean value does not match with the explanation. To be consistent with the text explaining the example, one should take the mean over the second half of Pxx_den, i.e. Pxx_den[25000:], which has a mean of 0.0010036891496647748.

**Comment by rgommers** [comment]
Thanks @thuehlinger. @daxlab could you update this again?

**Comment by daxlab** [comment]
@rgommers mean is coming to be `0.00099728892368242854` for me.

**Comment by rgommers** [comment]
Merged, thanks @daxlab and @thuehlinger

**Pull request merged**
