### PR TITLE
MAINT: differentiable fns respect float width.  Closes #15602

### LINKED ISSUE #15602: ENH: optimize: maintain user dtype
### Is your feature request related to a problem? Please describe.

The functions defined in `optimize/_differentiable_functions.py` all cast the inputs to float64 before evaluation. This is a problem if you want to work at an arbitrarily chosen precision format or change the precision format dynamically to speed up computation. Moreover these casts generates a significant overhead if the inputs in purposely not already in float64. 

### Describe the solution you'd like.

Remove all the the (useless) calls to `astype(float)` from `optimize/_differentiable_functions.py `

### Describe alternatives you've considered.

Add a param allowing to keep the format provided by the user

### Additional context (e.g. screenshots, GIFs)

NA

### PR DESCRIPTION
**Pull request by andyfaff**
`ScalarFunction` and `VectorFunction` now send the same floating point type that was used to construct the differentiable function to the user supplied function.

`approx_derivative` is also updated to send the appropriate floating point type to the function to be differentiated.

`approx_derivative` (and by extension `ScalarFunction.grad`/`VectorFunction.jac`) still currently return`np.float64`. I'm not sure of the ramifications of changing the output of `approx_derivative` to match the most precise floating point type of the input and output.
For example `approx_derivative` could be called with `x0.dtype == np.float32`, but `fun(x0).dtype` could be `np.float64`, so it seemed natural to me to keep `np.float64` as the output. But If both input and output are `np.float32` then the return of `approx_derivative` could possibly be changed to `np.float32`. I'm not sure what effect this would have on the downstream consumers of `approx_derivative`.

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Thanks @andyfaff for the PR. Could you not use `np.asfarray`? It's not array API compatible and we should try now to converge towards using array API compatible functions.

**Comment by andyfaff** [comment]
We'll need to write a version of `asfarray` that is compatible then.

**Comment by andyfaff** [comment]
@tupui @rgommers if working towards numpy array API compatibility is a factor in future PRs is there a guide as to what we need to work to? 

Besides if I go to https://github.com/numpy/numpy/blob/main/numpy/lib/type_check.py#L83-L113 it's not clear what about the `asfarray` function would not be compatible with the API standard.

**Comment by rgommers** [comment]
I think for now the only guidance is "use idiomatic numpy functions", when there's a choice between multiple. It looks to me like `asfarray` is fine to use right now. 
```python
def asfarray(a, dtype=_nx.float_):
    if not _nx.issubdtype(dtype, _nx.inexact):
        dtype = _nx.float_
    return asarray(a, dtype=dtype)
```
If that's the semantics you need here, go ahead and use it. In the future it's simple to replace with an equivalent function, which I'd write as:
```python
def as_float_array(x, xp, /, *, dtype=None):
    # If dtype is not given and x does not have a floating-point dtype,
    # cast it to float64, otherwise preserve it:
    if xp.isdtype(x.dtype, 'real floating'):
        return x

    if dtype=None:
        dtype = xp.float64
    return xp.asarray(x, dtype=dtype)
```

The semantics are not completely identical, but that's because I don't think what `asfarray` does is reasonable; `dtype` is optional but you must supply it or it will incorrectly convert lower-precision float arrays to `float64`.

**Comment by andyfaff** [comment]
@tupui, I've changed all the usages of `np.asfarray` to `np.ndarray.astype`. Hopefully those are compatible with the array API? Can you review again?

**Review by tupui — COMMENTED** [review]
Thanks @andyfaff for the update.

One main change with following the standard is that you would change use of method for functions. `x.astype` would become `xp.astype`.

`issubdtype` is I am afraid not available and you would have to rely on [xp.isdtype](https://data-apis.org/array-api/latest/API_specification/generated/array_api.isdtype.html#array_api.isdtype).

`copy` and `at least_1d` are also not available. For the latter we have a helper function now in `scipy/_lib/_array_api.py`

---

I don't think it's necessary that you deal with that in this PR though.

As it is, the code should be easy to convert if someone want to have a go at converting `scipy.optimize` as a whole.

**Comment by andyfaff** [comment]
@tupui, made some more modifications. Those files aren't array-api clean, but the changeset I made should be compatible.

**Comment by andyfaff** [comment]
Couple of questions about array-api compat. Should we create an `xp.copy` utility function? I note that `xp.astype` has copy semantics, so we could use that.

Secondly, what would be the array-api version of making sure that a function returned a scalar value?:
```python
            fx = fun(np.copy(x), *args)
            # Make sure the function returns a true scalar
            if not np.isscalar(fx):
                try:
                    fx = np.asarray(fx).item()
                except (TypeError, ValueError) as e:
                    raise ValueError(
                        "The user-provided objective function "
                        "must return a scalar value."
                    ) from e

```

**Review by tupui — APPROVED** [review]
Thank you @andyfaff for going the extra miles here (and thank you for raising the PR about copy).

Tests are green and LGTM overall so I am going to merge.

FYI I will be away for 3 weeks and not be able to help or probably even respond

**Comment by j-bowhay** [comment]
Can #15602 be closed?

**Pull request merged**
