### PR TITLE
MAINT,TST: update and run scipy/special/utils/convert.py

### PR DESCRIPTION
**Pull request by sethtroisi**
Run the boost test_data importer.

Added new tests for [special functions](https://docs.scipy.org/doc/scipy/reference/special.html) `ivp`, `jvp`, `kvp`, `yvp`

---

This should be reproducible with

```
git clone --depth=1 https://github.com/boostorg/math.git boostmath

rm -rf scipy/special/tests/data/boost/*
python scipy/special/utils/convert.py

# List all files then check if they appear in scipy/scipy/special/tests/test_data.py
find scipy/special/tests/data/boost -type f | sed 's!scipy/special/tests/data/boost/!        # TODO    !' | sort -r

# Verify all the new files are used in test_data.py
git diff --stat HEAD~ | grep "Bin 0"
git diff upstream/master -- scipy/special/tests/test_data.py
```

This results in a BIG diff because many tabs were converted to spaces,
```
git diff -a HEAD~ | wc
  86048  354276 13779286
git diff -a -w HEAD~ | wc
  29414  123487 4599674
```
To keep the diff smaller I revert any whitespace-only change via this hack
```
git diff -a -w HEAD~ > test.patch
git reset --hard HEAD~
git apply test.patch
git add scipy/special/tests/data/boost
git commit -m 'MAINT,TST: Run scipy/special/utils/convert.py'
```

I could probably reduces the number of lines change by another 30% if I reverted changes of `1` to `1.0` and `0` to `0.0` in a number of "updated" files but I didn't see any easy way to do this (maybe running `sed` over a hand curated list of files?)

Ideally this wouldn't be squashed, so inspecting the diff of `convert.py` and `test_data.py` would be easier. the tests would be broken by the first commit but fixed when the second commit is submitted.

I'm sorry the diff is such a mess, I'd suggest looking at the diff of the first commit only. Also I don't understand many of the pieces I touched (e.g. how is `jn` different from `jv`) so a semantic review of `test_data.py` would appreciated.

### CODE REVIEW

**Comment by sethtroisi** [comment]
The lint test fails because I'm copied the style of the other tests in the file.

```
data(ivp, 'bessel_i_prime_int_data_ipp-bessel_i_prime_int_data', (0,1j), 2, rtol=1.2e-13, atol=1e-300),
```
`(0,1j)` should maybe have a space and should maybe line wrap but it is in the style of the file.

**Comment by larsoner** [comment]
In theory you should be able to make exceptions when justified, e.g., `# noqa: E501` for the line with the line length problem, and do something similar for the other. At least you can for flake8 as a tool, haven't looked into how our diff lint works

**Comment by rgommers** [comment]
I think the whitespace and `0` -> `0.0` changes here are fine, given that they're in data files and generated code. The first commit in this PR is tidy enough. The thing left to do is verify that no tests got dropped by the regex change - should be a matter of comparing test count in master vs in this PR.

**Comment by rgommers** [comment]
> In theory you should be able to make exceptions when justified, e.g., # noqa: E501 for the line with the line length problem, and do something similar for the other. At least you can for flake8 as a tool, haven't looked into how our diff lint works

I don't think there's a need for that, if one decides that ignoring the flake8 output is fine (e.g. because style is consistent within the file), then we can just commit it. Subsequent PRs won't fail on it, that's the nice part of the new diffing tool.

**Comment by sethtroisi** [comment]
> I think the whitespace and `0` -> `0.0` changes here are fine, given that they're in data files and generated code. The first commit in this PR is tidy enough. The thing left to do is verify that no tests got dropped by the regex change - should be a matter of comparing test count in master vs in this PR.

You can also look at https://github.com/scipy/scipy/pull/12357/files#diff-a49868d52c69e2d53c607534a4572a8e and see that I only add lines :)

**Comment by person142** [comment]
I wouldn't add tests for `sinc`. Our `sinc` is just NumPy's sinc, and NumPy's sinc is not good.

Now if you want to reimplement sinc along the lines of https://github.com/numpy/numpy/pull/12924 then that would be great.

**Comment by person142** [comment]
... and to go into more detail: you're matching Boost's definition by doing

```python
def sinc_x(x):
    return sinc(x / np.pi)
```

but numerically speaking, `sin(pi * x) / (pi * x)` and `sin(x) / x` have very different properties. This is because `sin(pi * x)` and `sin(x)` are very different-the former can easily be computed to ~1 ULP of accuracy (see e.g. our implementation in `special`), while that is not true for the latter (with any practical implementation). So this doesn't end up being an apples-to-apples comparison.

**Comment by sethtroisi** [comment]
@person142 These are really solid comments. I pulled out the sinc changes and we can discuss in a followup PR.

**Comment by sethtroisi** [comment]
@rgommers I think this can go in; one test failure is lint, the other is timeout.

After this goes in I'll have a 2nd pass to use some of the new test data files (sinc, ive, iv`)

**Review by rgommers — APPROVED** [review]
Okay let's give this a go. Added tests look useful, and script looks clearer after these changes. Thanks @sethtroisi.

**Comment by sethtroisi** [comment]
Thanks @rgommers  :)

**Pull request merged**
