### PR TITLE
TST: fix special test that was importing `np.testing.utils` (deprecated)

### PR DESCRIPTION
**Pull request by rgommers**
This fixes the CI failures with numpy master.

### CODE REVIEW

**Review by charris — APPROVED** [review]

**Comment by pv** [comment]
Problems on older numpy releases...

I think the routine is equivalent to `assert_allclose(...)`. Indeed, this code predates `assert_allclose`.

**Comment by charris** [comment]
I'd happily undo the warning at some point if that would help, It was intended to help find these cases, which it looks like it is doing 8-)

**Comment by pv** [comment]
Pushed a commit that replaces the function with assert_allclose.

**Comment by ev-br** [comment]
Am going to hit the green button to unblock the CI. Thanks all.

**Pull request merged**
