### PR TITLE
ENH: Move FFT zero-padding calculation from signaltools to fftpack

### PR DESCRIPTION
**Pull request by endolith**
Pulled this out of https://github.com/scipy/scipy/pull/4607 so it can be merged sooner.

The calculation is specific to fftpack (as opposed to FFTW or CUDA etc), so should be in that submodule, so it can be [monkeypatched along with everything else](https://hgomersall.github.io/pyFFTW/sphinx/tutorial.html#monkey-patching-3rd-party-libraries) by pyfftw, etc.

Renamed more generically to "next optimal length", since "[regular numbers](https://en.wikipedia.org/wiki/Regular_number)" are specific to FFTPACK

### CODE REVIEW

**Comment by endolith** [comment]
(Can I notify @hgomersall from here?)

**Comment by endolith** [comment]
Also, should this be made into a public function?

**Comment by hgomersall** [comment]
Yes, I was notified :)

I guess it doesn't really matter if it's public or not. I do wonder what the optimal strategy for FFTW is though. I suspect powers of two + copy is not better than many other sizes, but it's not clear to me which those are. This should prob be discussed over on pyFFTW...

**Comment by hgomersall** [comment]
Also, I hadn't twigged that numpy fft is used in certain paths. What's the rationale there?

**Comment by endolith** [comment]
FFTW wants prime factors up to 13, by default.  We discussed it here previously https://github.com/scipy/scipy/pull/4607#issuecomment-158425830  :)

[Also](http://www.fftw.org/fftw2_doc/fftw_6.html#SEC72):

> If you know that you will only use transforms of a certain size (say, powers of 2) and want to reduce the size of the library, you can reconfigure FFTW to support only those sizes you are interested in.  You may even generate code to enable efficient transforms of a size not supported by the default distribution.  The default distribution supports transforms of any size, but not all sizes are equally fast. The default installation of FFTW is best at handling sizes of the form 2<sup>a</sup> 3<sup>b</sup> 5<sup>c</sup> 7<sup>d</sup> 11<sup>e</sup> 13<sup>f</sup>, where e+f is either 0 or 1, and the other exponents are arbitrary.  Other sizes are computed by means of a slow, general-purpose routine.  However, if you have an application that requires fast transforms of size, say, <code>17</code>, there is a way to generate specialized code to handle that.


fftconvolve uses numpy's rfft for real input because scipy's is not N-dimensional.

**Comment by hgomersall** [comment]
That's actually the FFTW 2 manual. [FFTW3](http://www.fftw.org/fftw3_doc/Introduction.html#Introduction) talks about "small primes (2, 3, 5, and 7)". Other sizes can be built in at compile time.

**Comment by Eric89GXL** [comment]
This looks like it's copy-paste to fit namespaces better, plus a PEP8 fix or two. Is that right, or did you make other substantial changes?

+1 for making that function public, I have lost track of how many times I've seen code with something like `np.ceil(np.log2(len(x)))` to get the next optimal length.

**Comment by endolith** [comment]
Yeah, I just moved it and changed some names.

Good point on making it public to encourage use.  Is `next_opt_len` a good name?

Should it be N-D?  Currently fftconvolve takes care of that (`fshape = [_next_regular(int(d)) for d in shape]`), but it could be built-in.  And public function needs to be more careful of input types, etc.

It should probably be made more generic, too, like `for factor in (5, 3):` so it can be easily adapted to fftw, etc.

Making it public should probably be a separate PR to avoid delays.

**Comment by Eric89GXL** [comment]
> Is next_opt_len a good name?

I slightly prefer `next_best_len` because it uses a full word instead of an abbreviation, but doesn't make a big difference.

> Should it be N-D?

For the first version I'd make it only 1D. We can always expand to ND later.

> It should probably be made more generic, too, like for factor in (5, 3): so it can be easily adapted to fftw, etc.

Can this also be done later as a backward-compatible enhancement?

> Making it public should probably be a separate PR to avoid delays.

Sure. I'll wait a couple of days to see if anyone else wants to chime in with suggestions then merge.

**Comment by endolith** [comment]
>Can this also be done later as a backward-compatible enhancement?

Yes I just mean to change the way the loop  is written for clarity.

**Comment by Eric89GXL** [comment]
Thanks @endolith. I like this from a reorganization perspective, but I'm curious what the motivation is -- better PyFFTW integration?

**Comment by endolith** [comment]
Yes that's the main motivation. Fftw has different optimal sizes so it should overwrite this  function when it overwrites everything else in fftpack

**Comment by endolith** [comment]
> I slightly prefer next_best_len because it uses a full word instead of an abbreviation, but doesn't make a big difference.

How about `next_fast_len`?

http://www.univie.ac.at/nuhag-php/mmodule/m-files/nextfastfft.m

**Comment by Eric89GXL** [comment]
Sounds good to me

**Pull request merged**
