### PR TITLE
BUG: vq.kmeans() compares signed diff to a threshold.

### PR DESCRIPTION
**Pull request by StrahinjaLukic**
In l. 316 of `vq.py`, `diff` is calculated as **signed** difference between the last two values of the average distance. In l. 308, `diff` is compared to the threshold (the default value for the threshold is 1e-5). This is fine as long as the average distance decreases from an iteration to another. However, kmeans is not a classical minimization algorithm and the average distance may increase in an iteration, even in several successive iterations. With the present code the function exits if the average distance grows in an iteration regardless how large is the positive difference. This problem was pointed out by @richardtsai in issue #2279. This PR corrects the bug by rewriting l. 316 so that `diff` is calculated as the **absolute value** of the difference between the last two values of the average distance.

The following trivial example illustrates the difference in the code behavior before and after the correction. 

With previous code:

    >>> import numpy as np
    >>> from scipy.cluster.vq import *
    >>> obs = np.array([-3, -1, 0, 1, 1, 8], float)
    >>> kmeans(obs, np.array([-3., 0.99]))
    (array([-2. ,  2.5]), 1.9333333333333333)
    >>> kmeans(obs, np.array([-3., 1.8]))
    (array([-1.33333333,  3.33333333]), 2.0833333333333335)
    >>> kmeans(obs, np.array([1., 8.]))
    (array([-0.4,  8. ]), 1.0666666666666667)

In this example with a short 1D array and 2 clusters, kmeans returns three different clustering results depending on the initial guess provided for the cluster centroids. In the first two cases the signed `diff` the average distance initially grows and the function exits prematurely.

This PR:

    >>> import numpy as np
    >>> from scipy.cluster.vq import *
    >>> obs = np.array([-3, -1, 0, 1, 1, 8], float)
    >>> kmeans(obs, np.array([-3., 0.99]))
    (array([-0.4,  8. ]), 1.0666666666666667)
    >>> kmeans(obs, np.array([-3., 1.8]))
    (array([-0.4,  8. ]), 1.0666666666666667)
    >>> kmeans(obs, np.array([1., 8.]))
    (array([-0.4,  8. ]), 1.0666666666666667)

Now the algorithm continues until the **absolute value** of `diff` drops below 
the threshold and thus finds the correct solution regardless of the initial 
conditions.

### CODE REVIEW

**Comment by mdhaber** [comment]
@StrahinjaLukic Seems right to me.

**Comment by StrahinjaLukic** [comment]
Ok. This makes sense. Let me go over your suggestions in the next few days.

**Comment by rgommers** [comment]
Hmm, this stalled and fixes a clear bug. Would be nice to get it merged. @StrahinjaLukic would you want to get back to this? No need to look at references, just a simple regression test is enough to get this merged.

**Comment by StrahinjaLukic** [comment]
@rgommers Yes. Thanks for the nudge.

**Comment by StrahinjaLukic** [comment]
Added a simple regression test.

**Review by j-bowhay — APPROVED** [review]
Thanks @StrahinjaLukic, suggestions have been addressed and this matches reference values from sklearn:
```
In [8]: from sklearn.cluster import KMeans

In [9]: import numpy as np

In [10]: obs = np.array([-3, -1, 0, 1, 1, 8], float)

In [11]: KMeans(n_clusters=2, random_state=0, n_init="auto").fit(obs.reshape(-1,1)).cluster_centers_
Out[11]: 
array([[-0.4],
       [ 8. ]])
```

I will rebase and merge if all comes back green

**Pull request merged**
