### PR TITLE
CI: add 3.8-dev to travis

### PR DESCRIPTION
**Pull request by andyfaff**
Meant to submit against my own fork first, to reduce load on CI, but obviously made a mistake.

Python 3.8 will be released in a few months and we should start running our CI against it.

### CODE REVIEW

**Comment by andyfaff** [comment]
numpy on 3.8 says:

> Downstream developers should use Cython >= 0.29.11 for Python 3.8 support and OpenBLAS >= 3.7 (not currently out) to avoid problems on the Skylake architecture. The NumPy wheels on PyPI are built from the OpenBLAS development branch in order to avoid those problems.

Not sure what the implications are here. I'm guessing that the CI will have to compile numpy as well, unless there are some dev wheels somewhere.

**Comment by tylerjereddy** [comment]
> I'm guessing that the CI will have to compile numpy as well, unless there are some dev wheels somewhere.

There are nightly NumPy wheels for some platforms on the rackspace server, but they probably won't help since those are just updates for the latest NumPy master, not expansions in the wheel build matrix to include new Python versions.

So yes, probably a build from source of NumPy for the beta Python version.

**Comment by andyfaff** [comment]
It seems to get through to the test suite, with the main failure [being](https://travis-ci.org/scipy/scipy/jobs/564536705#L1028):

> DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats

From what I can see all the failures are due to the same issue.

**Comment by andyfaff** [comment]
I'd say the issue is [here](https://github.com/scipy/scipy/blob/master/scipy/odr/__odrpack.c#L500) and also L514. I'm not sure how to go about fixing.
Various googling leads me to:

> Note For all # variants of formats (s#, y#, etc.), the type of the length argument (int or Py_ssize_t) is controlled by defining the macro PY_SSIZE_T_CLEAN before including Python.h. If the macro was defined, length is a Py_ssize_t rather than an int. This behavior will change in a future Python version to only support Py_ssize_t and drop int support. It is best to always define PY_SSIZE_T_CLEAN.

So I'm guessing some of the parameters to the functions need to be changed from int to `Py_ssize_t`, and for `#define PY_SSIZE_T_CLEAN` to be defined at the top of `odrpack.h`.

@rkern, you're the author of `__odrpack.c`, can you shed any light on which variables need to be changed?

**Comment by andyfaff** [comment]
I *think* I figured out the issue, and the test suite passes on travis. Yay!

**Review by larsoner — APPROVED** [review]
Looks good to me

**Comment by andyfaff** [comment]
I think this is good to go. I don't think the test failures are caused by this PR.

**Comment by larsoner** [comment]
If it's easy can you rebase? I think master is clean right now and it's nice to see CI changing PRs (in particular) green

**Comment by andyfaff** [comment]
Rebased. Although it required a forced push for some reason

**Comment by larsoner** [comment]
Rebases rewrite history so always require a force push (assuming they actually do rebase and it's not a no-op / you are not already up to date). Merging with master OTOH would not have required it, maybe that's what you're used to.

**Review by larsoner — APPROVED** [review]
+1 for merge when CIs come back green. Nice to see it's such a small diff!

**Pull request merged**
