### PR TITLE
ENH: stats: add `axis` tuple and `nan_policy` to `skew`

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### Reference issue

gh-14651

#### What does this implement/fix?

Adds `_axis_nan_policy_factory` to `skew`. `skew` tests looked quite strong so I didn't add any special tests.

#### Additional information

I wrote an additional test with Hypothesis to tests for various edge cases and confirm the results are consistent. It passed for both `kurtosis` and `skew` (sorry, it's a little ugly right now because I was playing around and it was too much work to simplify). 

<details>

<summary>Additional tests with Hypothesis</summary>

```py
import numpy as np
import pytest
import hypothesis
from hypothesis import strategies as st
from hypothesis.extra import numpy as npst
from scipy import stats
from scipy.stats.tests.test_axis_nan_policy import axis_nan_policy_cases

# Writing more comprehensive tests with Hypothesis.
# The below tests check if functions using axis_nan_policy work for kurtosis and skew
# inputs with nans, masks, nans and masks, etc.
@hypothesis.given(data=st.data())
@hypothesis.seed(123)
@hypothesis.settings(max_examples=100, deadline=None)
@pytest.mark.parametrize("function, args, kwds, num_samples, num_outputs, paired, unpacker_function", axis_nan_policy_cases[7:])
def test_axis_nan_policy_with_hypothesis(function, args, kwds, num_samples, num_outputs, paired, unpacker_function, data):
    shapes = data.draw(npst.mutually_broadcastable_shapes(num_shapes=num_samples,
                                                          max_dims=6,
                                                          max_side=3))
    if len(shapes.result_shape) >= 1:
        axes = data.draw(npst.valid_tuple_axes(ndim=len(shapes.result_shape), min_size=1))
    else:
        axes = None

    samples = []
    nan_samples = []
    masked_samples = []
    nan_masked_samples = []

    for i in range(num_samples):
        sample = data.draw(npst.arrays(dtype=float, shape=shapes.input_shapes[i]))
        mask1 = np.random.rand(*sample.shape) < 0.2
        mask2 = np.random.rand(*sample.shape) < 0.15
        nan_sample = sample.copy()
        nan_sample[mask1|mask2] = np.nan
        masked_sample = np.ma.masked_array(sample, mask=mask1|mask2)
        nan_masked_sample = sample.copy()
        nan_masked_sample[mask1] = np.nan
        nan_masked_sample = np.ma.masked_array(nan_masked_sample, mask=mask2)
        samples.append(sample)
        nan_samples.append(nan_sample)
        masked_samples.append(masked_sample)
        nan_masked_samples.append(nan_masked_sample)

    with np.errstate(all='ignore'):
        with np.testing.suppress_warnings() as sup:
            sup.filter(RuntimeWarning)

            res_expected = function(*samples, *args, **kwds, _no_deco=True)
            res = function(*samples, *args, **kwds)
            np.testing.assert_allclose(res, res_expected)

            res1 = function(*nan_samples, *args, **kwds, axis=axes, nan_policy='omit')
            res2 = function(*masked_samples, *args, **kwds, axis=axes, nan_policy='omit')
            res3 = function(*nan_masked_samples, *args, **kwds, axis=axes, nan_policy='omit')
            np.testing.assert_allclose(res1, res2)
            np.testing.assert_allclose(res1, res3)
```

... or I didn't simplify because I got a little lazy 🙃

</details>

### CODE REVIEW

**Review by tupui — APPROVED** [review]
Thanks @tirthasheshpatel.

On my side I am +1 to not add more tests for these. It's heavily tested on other functions (unit tests and integration ones). So the probability that it breaks (or in a future other addition like that) while the CI is still green is very unlikely IMO. I mean, at some point we will not be able to add things to the CI so we better try to restrict ourselves.

I will let others have a look before merging. (Also please remember to add an entry in the release notes about these)

**Review by Kai-Striega — COMMENTED** [review]
LGTM! Thanks @tirthasheshpatel

There was one test failure but I think it is unrelated to the changes ;)

**Review by Kai-Striega — APPROVED** [review]

**Review by mdhaber — APPROVED** [review]
Yup, even though `skew` has `axis` and `nan_policy`, the decorator gives the same advantages as it did for `kurtosis`.

* Axis tuples are now supported.
* Previously, masked arrays were accepted without warning, but the masked values were included in the calculation; now they are accepted and the calculation is performed correctly.
* `nan_policy='omit'` no longer converts the output to a masked array.

<details>

```python3
import numpy as np
from scipy import stats
from numpy.ma import masked_array as ma

fun = stats.skew

def try_case(x, message, kwds):
    try:
        print(message)
        res = fun(x, **kwds)
        print(res)
        print(type(res), res.dtype)
    except AttributeError:
        print(type(res))
    except Exception as e:
        print(f"{type(e)}: {str(e)}")

    try:
        print("vs (master)")
        res = fun(x, **kwds,_no_deco=True)
        print(res)
        print(type(res), res.dtype)
    except AttributeError:
        print(type(res))
    except Exception as e:
        print(f"{type(e)}: {str(e)}")

    print("----")

np.random.seed(0)
random_array = np.random.rand(4, 6)
random_mask = np.random.rand(4, 6) > 0.8
random_nan_array = random_array.copy()
random_nan_array[random_mask] = np.nan
random_ma = np.ma.masked_array(random_array, mask=random_mask)
random_ma32 = np.ma.masked_array(random_array, mask=random_mask, dtype=np.float32)

cases = [
          ([], 'Zero Observations:', {}),
          ([1.], 'One Observation:', {}),
          ([1., 2.], 'Two Observations', {}),
          (random_array, '2D Array, no axis', {}),
          (random_array, '2D Array, axis=0', {'axis': 0}),
          (random_array, '2D Array, axis=1', {'axis': 1}),
          (np.matrix(random_array), 'Matrix, axis=1', {'axis': 1}, ),
          (random_array, '2D Array, axis=None', {'axis': None}),
          (random_array, '2D Array, axis=(0,1)', {'axis': (0, 1)}),
          ([np.nan, 1., 2., 3.], '1D Array with NaN, No nan_policy', {}),
          ([np.nan, 1., 2., 3.], '1D Array with NaN, raise', {'nan_policy': 'raise'}),
          ([np.nan, 1., 2., 3.], '1D Array with NaN, propagate', {'nan_policy': 'propagate'}),
          ([np.nan, 1., 2., 3.], '1D Array with NaN, omit', {'nan_policy': 'omit'}),
          ([np.nan, np.nan, np.nan], '1D Array with All NaNs, omit', {'nan_policy': 'omit'}),
          ([np.nan, np.nan, 3.], '1D Array with all but one NaN, omit', {'nan_policy': 'omit'}),
          (ma([0., 1., 2., 3.], mask=[True, False, False, False]), '1D Masked array, one masked', {}),
          (ma([1., 2., 3.], mask=[True, True, True]), '1D Masked array, all masked', {}),
          (ma([1., 2., 3.], mask=[True, True, False]), '1D Masked array, all but one masked', {}),
          (random_nan_array, '2D Array with NaNs, propagate, axis=1', {'axis': 1, 'nan_policy': 'propagate'}, ),
          (random_nan_array, '2D Array with NaNs, omit, axis=1', {'axis': 1, 'nan_policy': 'omit'}, ),
          (random_ma, '2D Masked array, axis=1', {'axis': 1}, ),
          (random_array.astype(np.float32), '2D Array, float32, axis=1', {'axis': 1}),
          (random_nan_array.astype(np.float32), '2D Array with NaNs, float32, propagate, axis=1', {'axis': 1, 'nan_policy': 'propagate'}, ),
          (random_ma32, '2D Masked Array, float32, axis=1', {'axis': 1}, ),
          ]

for case in cases:
    try_case(*case)
```
prints:
```
Zero Observations:
nan
<class 'float'>
vs (master)
nan
<class 'float'>
----
One Observation:
0.0
<class 'float'>
vs (master)
0.0
<class 'float'>
----
Two Observations
0.0
<class 'float'>
vs (master)
0.0
<class 'float'>
----
2D Array, no axis
[ 0.57446104 -0.94627859 -0.67033591 -0.10992121 -0.19869901 -0.27054031]
<class 'numpy.ndarray'> float64
vs (master)
[ 0.57446104 -0.94627859 -0.67033591 -0.10992121 -0.19869901 -0.27054031]
<class 'numpy.ndarray'> float64
----
2D Array, axis=0
[ 0.57446104 -0.94627859 -0.67033591 -0.10992121 -0.19869901 -0.27054031]
<class 'numpy.ndarray'> float64
vs (master)
[ 0.57446104 -0.94627859 -0.67033591 -0.10992121 -0.19869901 -0.27054031]
<class 'numpy.ndarray'> float64
----
2D Array, axis=1
[-0.25501147  0.03831401  0.20966483 -0.96946629]
<class 'numpy.ndarray'> float64
vs (master)
[-0.25501147  0.03831401  0.20966483 -0.96946629]
<class 'numpy.ndarray'> float64
----
Matrix, axis=1
[-0.25501147  0.03831401  0.20966483 -0.96946629]
<class 'numpy.ndarray'> float64
vs (master)
[-0.25501147  0.03831401  0.20966483 -0.96946629]
<class 'numpy.ndarray'> float64
----
2D Array, axis=None
-0.7003469849409386
<class 'float'>
vs (master)
-0.7003469849409386
<class 'float'>
----
2D Array, axis=(0,1)
-0.7003469849409386
<class 'float'>
vs (master)
<class 'TypeError'>: tuple indices must be integers or slices, not tuple
----
1D Array with NaN, No nan_policy
nan
<class 'numpy.float64'> float64
vs (master)
nan
<class 'float'>
----
1D Array with NaN, raise
<class 'ValueError'>: The input contains nan values
vs (master)
<class 'ValueError'>: The input contains nan values
----
1D Array with NaN, propagate
nan
<class 'numpy.float64'> float64
vs (master)
nan
<class 'float'>
----
1D Array with NaN, omit
0.0
<class 'float'>
vs (master)
0.0
<class 'numpy.ma.core.MaskedArray'> float64
----
1D Array with All NaNs, omit
nan
<class 'float'>
vs (master)
--
<class 'numpy.ma.core.MaskedArray'> int32
----
1D Array with all but one NaN, omit
0.0
<class 'float'>
vs (master)
0.0
<class 'numpy.ma.core.MaskedArray'> float64
----
1D Masked array, one masked
0.0
<class 'float'>
vs (master)
0.0
<class 'float'>
----
1D Masked array, all masked
nan
<class 'float'>
vs (master)
0.0
<class 'float'>
----
1D Masked array, all but one masked
0.0
<class 'float'>
vs (master)
0.0
<class 'float'>
----
2D Array with NaNs, propagate, axis=1
[        nan  0.03831401         nan -0.96946629]
<class 'numpy.ndarray'> float64
vs (master)
[        nan  0.03831401         nan -0.96946629]
<class 'numpy.ndarray'> float64
----
2D Array with NaNs, omit, axis=1
[-0.45040877  0.03831401 -0.14964198 -0.96946629]
<class 'numpy.ndarray'> float64
vs (master)
[-0.45040877  0.03831401 -0.14964198 -0.96946629]
<class 'numpy.ma.core.MaskedArray'> float64
----
2D Masked array, axis=1
[-0.45040877  0.03831401 -0.14964198 -0.96946629]
<class 'numpy.ndarray'> float64
vs (master)
[-0.25501147  0.03831401  0.20966483 -0.96946629]
<class 'numpy.ndarray'> float64
----
2D Array, float32, axis=1
[-0.2550118   0.03831322  0.20966476 -0.9694669 ]
<class 'numpy.ndarray'> float32
vs (master)
[-0.2550118   0.03831322  0.20966476 -0.9694669 ]
<class 'numpy.ndarray'> float32
----
2D Array with NaNs, float32, propagate, axis=1
[        nan  0.03831323         nan -0.96946696]
<class 'numpy.ndarray'> float64
vs (master)
[        nan  0.03831322         nan -0.9694669 ]
<class 'numpy.ndarray'> float32
----
2D Masked Array, float32, axis=1
[-0.45040901  0.03831399 -0.14964194 -0.96946651]
<class 'numpy.ndarray'> float64
vs (master)
[-0.2550118   0.03831322  0.20966476 -0.9694669 ]
<class 'numpy.ndarray'> float32
```

</details>

Thanks @tirthasheshpatel!

Next up, if you can give your opinion on gh-15423, I can submit the remaining patch for `mode` that should allow you to apply the decorator to it. In the meantime, `variation` might be a good candidate similar to `skew`/`kurtosis`, or you could continue down the list (`kstat` and `kstatvar`)?

**Comment by tirthasheshpatel** [comment]
Thanks @tupui, @Kai-Striega, and @mdhaber for the review!

I will review gh-15423 this weekend.

I tried to add the decorator for `variation` but the `keepdims` parameter causes some problems. There is some room for discussion before we can add the decorator to `variation`:

1. What will be the behavior of `keepdims` when tuple axis is passed? Would it just add 1's to each of the reduced axes?
2. Behavior of `keepdims` with `axis=None`? Currently, `variation` just returns 1D array (`array([value])`) when `keepdims=True` and `axis=None`. But, if we consider `axis=None` equivalent to `axis=(0, 1, ...)` (all axis) then, according to point 1 above, it should return an array of dimension `len(axis)` with one value (i.e. `array([[[...[value]...]]])`)

Also, seems like `variation` has some shape bugs:

```py
>>> import numpy as np
>>> from scipy.stats import variation
>>> x2 = np.array([[np.nan, 1, -10, np.nan],
...                [-20, -3, np.nan, np.nan]])
>>> variation([[1,2], [3,4]], axis=1, ddof=2).shape  # when ddof = input.shape, it doesn't reduce the axis
(2, 1)
```

One other thing, `variation` throws [`np.AxisError`](https://numpy.org/doc/stable/reference/generated/numpy.AxisError.html) when `axis` is out of bounds while the decorator throws a `ValueError`. In this case, I think the decorator should be updated to use `np.AxisError` since NumPy recommends its usage for invalid axis input. What do you think @mdhaber?

<details>

I discovered the shape bugs when I tried to add support for the `keepdims` parameter in the decorator.

<summary>Diff to add `keepdims` to the decorator</summary>

```diff
diff --git a/scipy/stats/_axis_nan_policy.py b/scipy/stats/_axis_nan_policy.py
index 8167e1132..8fc5afada 100644
--- a/scipy/stats/_axis_nan_policy.py
+++ b/scipy/stats/_axis_nan_policy.py
@@ -362,6 +362,10 @@ def _axis_nan_policy_factory(result_object, default_axis=0,
             # Consolidate other positional and keyword args into `kwds`
             kwds.update(d_args)
 
+            keepdims = kwds.get("keepdims")
+            if keepdims:
+                kwds.update({"keepdims": False})
+
             # rename avoids UnboundLocalError
             if callable(n_samples):
                 # Future refactoring idea: no need for callable n_samples.
@@ -398,10 +402,15 @@ def _axis_nan_policy_factory(result_object, default_axis=0,
 
             # standardize to always work along last axis
             if axis is None:
+                max_side = max([sample.shape for sample in samples])
+                reduced_axes = np.arange(len(max_side))
                 samples = [sample.ravel() for sample in samples]
             else:
                 samples = _broadcast_arrays(samples, axis=axis)
                 axis = np.atleast_1d(axis)
+                # this is the axis used by `expand_dims` to preserve axes that
+                # have been operated on (i.e. when keepdims=True)
+                reduced_axes = axis
                 n_axes = len(axis)
                 # move all axes in `axis` to the end to be raveled
                 samples = [np.moveaxis(sample, axis, range(-len(axis), 0))
@@ -447,7 +456,16 @@ def _axis_nan_policy_factory(result_object, default_axis=0,
 
                 if sentinel:
                     samples = _remove_sentinel(samples, paired, sentinel)
-                return hypotest_fun_out(*samples, **kwds)
+                res = hypotest_fun_out(*samples, **kwds)
+                if keepdims:
+                    if n_outputs == 1:
+                        for a in reduced_axes:
+                            res = np.expand_dims(res, a)
+                    else:
+                        for i in range(len(res)):
+                            for a in reduced_axes:
+                                res[i] = np.expand_dims(res[i], axis=a)
+                return res
 
             # check for empty input
             # ideally, move this to the top, but some existing functions raise
@@ -455,6 +473,9 @@ def _axis_nan_policy_factory(result_object, default_axis=0,
             # backward compatibility.
             empty_output = _check_empty_inputs(samples, axis)
             if empty_output is not None:
+                if keepdims:
+                    for a in reduced_axes:
+                        empty_output = np.expand_dims(empty_output, axis=a)
                 return result_object(*([empty_output.copy()
                                         for i in range(n_outputs)]))
 
@@ -469,7 +490,16 @@ def _axis_nan_policy_factory(result_object, default_axis=0,
                 scipy.stats._stats_py._contains_nan(x, nan_policy))
 
             if vectorized and not contains_nan and not sentinel:
-                return hypotest_fun_out(*samples, axis=axis, **kwds)
+                res = hypotest_fun_out(*samples, axis=axis, **kwds)
+                if keepdims:
+                    if n_outputs == 1:
+                        for a in reduced_axes:
+                            res = np.expand_dims(res, axis=a)
+                    else:
+                        for i in range(len(res)):
+                            for a in reduced_axes:
+                                res[i] = np.expand_dims(res[i], axis=a)
+                return res
 
             # Addresses nan_policy == "omit"
             if contains_nan and nan_policy == 'omit':
@@ -509,6 +539,14 @@ def _axis_nan_policy_factory(result_object, default_axis=0,
 
             x = np.moveaxis(x, axis, -1)
             res = np.apply_along_axis(hypotest_fun, axis=-1, arr=x)
+            if keepdims:
+                if n_outputs == 1:
+                    for a in reduced_axes:
+                        res = np.expand_dims(res, axis=a)
+                else:
+                    for i in range(len(res)):
+                        for a in reduced_axes:
+                            res[i] = np.expand_dims(res[i], axis=a)
             return result_object(*result_unpacker(res))
 
         doc = FunctionDoc(axis_nan_policy_wrapper)
diff --git a/scipy/stats/_variation.py b/scipy/stats/_variation.py
index be3acda86..2af0851f5 100644
--- a/scipy/stats/_variation.py
+++ b/scipy/stats/_variation.py
@@ -3,6 +3,7 @@ import numpy as np
 from numpy.core.multiarray import normalize_axis_index
 from scipy._lib._util import _nan_allsame
 from ._stats_py import _chk_asarray, _contains_nan
+from ._axis_nan_policy import _axis_nan_policy_factory
 
 
 def _nanvariation(a, *, axis=0, ddof=0, keepdims=False):
@@ -89,6 +90,9 @@ def _nanvariation(a, *, axis=0, ddof=0, keepdims=False):
     return result
 
 
+@_axis_nan_policy_factory(
+    lambda x: x, result_unpacker=lambda x: (x,), n_outputs=1
+)
 def variation(a, axis=0, nan_policy='propagate', ddof=0, *, keepdims=False):
     """
     Compute the coefficient of variation.
diff --git a/scipy/stats/tests/test_axis_nan_policy.py b/scipy/stats/tests/test_axis_nan_policy.py
index afbf11538..0748e6b69 100644
--- a/scipy/stats/tests/test_axis_nan_policy.py
+++ b/scipy/stats/tests/test_axis_nan_policy.py
@@ -28,6 +28,7 @@ axis_nan_policy_cases = [
     (stats.hmean, tuple(), dict(), 1, 1, False, lambda x: (x,)),
     (stats.kurtosis, tuple(), dict(), 1, 1, False, lambda x: (x,)),
     (stats.skew, tuple(), dict(), 1, 1, False, lambda x: (x,)),
+    (stats.variation, tuple(), dict(), 1, 1, False, lambda x: (x,)),
 ]
 
 # If the message is one of those expected, put nans in
```

</details>

**Comment by mdhaber** [comment]
Funny, you've basically reviewed gh-15423 unintentionally : ) These are the same issues we're having there.

1. Yes
2. Yes, the current behavior is wrong. I think I noted that in gh-15423. I decided against fixing it in gh-15423, but maybe we should reconsider.

Re: `np.AxisArror`, yes, I noticed this too. (I didn't know about it when first writing the decorator, so I just did `ValueError` across the board.) I don't remember why I didn't change it before, but it could be because we raise the same `ValueError` in multiple cases - not just ones in which we could be raising `np.AxisError`. Or maybe I was just lazy. But if it looks pretty straightforward, yes, we can certainly change it.

The easiest solution to all these might be to add `keepdims` as a part of the decorator, giving this parameter to all stats functions with the decorator. NumPy is pretty consistent about including it, so we might as well do it across the board, too. 

This is really easy to add to the decorator. The `axis` argument tells you which axes were consumed in the process. If `keepdims` is `True`, we just need to add them back at the very end.

**Pull request merged**
