### PR TITLE
DEP: special.comb: deprecate `exact=True` for non-integer intputs

### LINKED ISSUE #15722: DEP: special.comb: deprecate `exact=True` for non-integers
Following #15359, where we promise a change of behaviour by scipy 1.11.

* 1.11.0
  * `legacy is not None`:
    ```
                warnings.warn(
                    "Using legacy=True is deprecated and will raise an error "
                    "by Scipy 1.13.0. If you want to keep the legacy "
                    "behaviour, cast your inputs directly, "
                    "e.g. comb(int(your_N), int(your_k), exact=True).",
                    DeprecationWarning
                )
    ```
* 1.14.0 (due to out-of-band release of 1.13 and waiting for positional deprecation)
  * `legacy` kwarg removed
  * Also deprecate using `exact=True` for non-integer inputs.

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

closes https://github.com/scipy/scipy/issues/15722
#### What does this implement/fix?

Passing non-integers with `exact=True` silently returns the result as if `exact=False`. This PR deprecated this behaviour.

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]
LGTM. I'm just checking out the history before merging.

**Comment by mdhaber** [comment]
Oh but there should probably be a deprecation admonition in the documentation.

**Review by mdhaber — CHANGES_REQUESTED** [review]
Oops - needs an admonition in the documentation.

**Comment by mdhaber** [comment]
Were [@steppi's concerns](https://mail.python.org/archives/list/scipy-dev@python.org/thread/TP4PWZSC4TVMX2REI4N7UBXD5IYKHGGU/#RUAZ5HBZORL6DCSE2BNIZ67WGQ454O7M) about similar functions (e.g. `special.perm`) resolved? Is there a more recent discussion on the discussion forum or mailing list about this?

**Comment by j-bowhay** [comment]
> Were [@steppi's concern](https://mail.python.org/archives/list/scipy-dev@python.org/thread/TP4PWZSC4TVMX2REI4N7UBXD5IYKHGGU/#RUAZ5HBZORL6DCSE2BNIZ67WGQ454O7M) about similar functions (e.g. `special.perm`) resolved? Is there a more recent discussion on the discussion forum or mailing list about this?

This brings `comb` in line with `factorial`; `perm` is still a bit messy. Although I would double check with @h-vetinari 
```
In [1]: from scipy.special import factorial, comb, perm

In [2]: factorial(3.4, exact=True)
<ipython-input-2-03696a3b5729>:1: DeprecationWarning: Non-integer values of `n` together with `exact=True` are deprecated. Either ensure integer `n` or use `exact=False`.
  factorial(3.4, exact=True)
Out[2]: 10.136101851155138

In [3]: comb(4.6, 6, exact=True)
<ipython-input-3-b934d835cd70>:1: DeprecationWarning: `exact=True` is deprecated for non-integer `N` and `k` and will raise an error in SciPy 1.16.0
  comb(4.6, 6, exact=True)
Out[3]: 0.0

In [4]: perm(4.6, 6, exact=True)
Out[4]: 0

In [5]: perm(4.6, 3, exact=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 perm(4.6, 3, exact=True)

File ~/development/scipy/build-install/lib/python3.11/site-packages/scipy/special/_basic.py:2797, in perm(N, k, exact)
   2795     return 0
   2796 val = 1
-> 2797 for i in range(N - k + 1, N + 1):
   2798     val *= i
   2799 return val

TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by mdhaber** [comment]
Yeah I saw the deprecation message from `factorial` - but what will it do after the deprecation is over, and when will it expire? Looks like it could use an admonition in the documentation, too.

**Comment by h-vetinari** [comment]
> Were [@steppi's concern](https://mail.python.org/archives/list/scipy-dev@python.org/thread/TP4PWZSC4TVMX2REI4N7UBXD5IYKHGGU/#RUAZ5HBZORL6DCSE2BNIZ67WGQ454O7M) about similar functions (e.g. `special.perm`) resolved?

I haven't looked at `perm`, it's not surprising to me that it should be fixed (resp. float values for `exact=True`) in the same way.

> Yeah I saw the deprecation message from `factorial` - but what will it do after the deprecation is over, and when will it expire?

It's the standard deprecation period, so should be removed 2 releases (or ~1 year, in case there are out-of-band releases) later. I don't think we've consistently put announced versions into deprecation warnings (and where we did it got messed up by the out-of-band 1.13), so I think the safest way is to say: "this is deprecated, and will be removed", and then execute this in a timely manner (which is why we're doing the whole deprecation tracking).

**Comment by mdhaber** [comment]
I thought you spearheaded the push to include version numbers in deprecation warnings?

image

In any case, there was such a push, so I think a lot of the more recent deprecations have included version numbers so the timeline is obvious.

Will it give an error after the deprecation is over, or will the behavior change otherwise?

**Comment by h-vetinari** [comment]
> I thought you spearheaded the push to include version numbers in deprecation warnings?

Yeah, the idea was to hold ourselves accountable and be more diligent about executing removals, as well as giving more actionable context to users. However, that was before I realised that out-of-band releases can happen. OTOH, the condition for 1.13 were probably sufficiently rare that we don't really need to care about this, and can keep adding the version numbers. 🤷 

In any case, I think we can do the essential work on this (ensure that deprecations don't hang around forever) is done even if we don't put version numbers in the warning strings, so this shouldn't be a blocker here.

**Review by h-vetinari — APPROVED** [review]
I don't want this to miss 1.14. I propose to get this in, and deal with potential polishing later.

Also, we should open an issue for `perm`, because it seems we need the same kind of fixes there.

**Comment by mdhaber** [comment]
Yeah, this one is fine. I confirmed with @steppi that his concerns were resolved if the behavior after the deprecation period is to raise an error, as this PR documents. It's `factorial` that I think should document the versions and the intended behavior after the end of the deprecation period. I'd be happy to review a PR for that and for `perm` if you'd like to do that. I'd also appreciate a review of gh-20789, which I'd like to get into this release.

**Pull request merged**
