### PR TITLE
Rename imsave to imwrite while keeping backwards compatibility

### PR DESCRIPTION
**Pull request by chemelnucfin**
First commit - renamed imsave to imwrite to be opposite imread and also similar to openCV and MATLAB

Second commit - added tests and used local packages instead of library package

Made a new branch to submit the pull request

### CODE REVIEW

**Comment by rgommers** [comment]
Hmm, I don't think it's wise to rename this function. Both names are clear, so it's a very minor stylistic change but does push work onto users.

**Comment by rgommers** [comment]
Also note that you didn't actually deprecate the function, that's done with ``np.deprecate``. But maybe it was a doc-only deprecation on purpose?

**Comment by rgommers** [comment]
@chemelnucfin if you want to make a case for deprecation: that needs to be decided on on the scipy-dev mailing list. That's where we make all such decisions; it has a much wider readership than Github issues/PRs.

**Comment by chemelnucfin** [comment]
@rgommers 
 Thanks for letting me know about numpy.deprecate function.  I didn't know about the function.  I did it the way I did in order to not break anyone's code.  I was thinking after usage on the new function increases and the relative usage on the old function decreased, it can be slowly phased out.  I do feel that there is a case to be made on the renaming of that function, as it is natural to use imwrite after imread, and other packages also use imwrite and imread.
  I did start a message on scipy-dev.  Is there something I should do more formally to suggest the change as this is my first time contributing to scipy.  How does the usual decision process work?  Thanks.

**Comment by rgommers** [comment]
@chemelnucfin I do see your message now, missed it first time around - sorry about that. I will reply to it. There's nothing more formal needed than that email, although I'll ask you on the list to provide a bit more rationale.

Regarding how this works, if you'd write it down formally you'd get something like this: http://docs.scipy.org/doc/numpy-dev/dev/governance/governance.html#consensus-based-decision-making-by-the-community (that's for numpy but applies to scipy pretty much 1:1). That needs a translation to "this is how practical decision making happens day-to-day". I'm in the middle of writing stuff like that down in gh-5424.

**Comment by rgommers** [comment]
Mailing list thread: http://article.gmane.org/gmane.comp.python.scientific.devel/20063

**Comment by rgommers** [comment]
Outcome of mailing list discussion: some preference for ``imwrite`` over ``imsave``, but will only be done if we move the functions from ``misc`` to ``io`` or ``ndimage``. That's covered in gh-6242, so closing this.

Thanks for your contribution @chemelnucfin

**Pull request closed without merging**
