### PR TITLE
Compute KS p-values lazily.

### PR DESCRIPTION
**Pull request by anntzer**
In `kstest`, the computation of the p-value can take a surprisingly
large amount of time, even if the end user may only be (in certain
cases) only interested by the statistic itself.

Avoid paying the time for computing p by making it a lazy property.

In the test script below, before this commit, the calls to kstest take
~0.53s (second or third case), but redoing just the statistic->p-value
calculations (last case) already take ~0.45s.  After this patch, if one
just needs the statistic itself (second case), this only takes ~0.07s,
so nearly an order of magnitude is gained(!).

    from time import perf_counter
    import numpy as np
    from scipy.stats import distributions, kstest

    N = 1000
    repeats = 1000

    np.random.seed(0)
    start = perf_counter()
    for _ in range(repeats):
        x = np.random.random(N)
    generation_time = perf_counter() - start
    # time to generate random samples
    print(generation_time)

    np.random.seed(0)
    start = perf_counter()
    for _ in range(repeats):
        x = np.random.random(N)
        dp = kstest(x, lambda x: x)
        dp.statistic
    generation_and_ks_time = perf_counter() - start
    # time to get the ks-statistic
    print(generation_and_ks_time - generation_time)

    np.random.seed(0)
    start = perf_counter()
    for _ in range(repeats):
        x = np.random.random(N)
        D, p = kstest(x, lambda x: x)
    generation_and_ks_time = perf_counter() - start
    # time to get the ks-statistic and associated p-value
    print(generation_and_ks_time - generation_time)

    np.random.seed(0)
    start = perf_counter()
    for _ in range(repeats):
        x = np.random.random(N)
        D, p = kstest(x, lambda x: x)
        pval_two = distributions.kstwobign.sf(D * np.sqrt(N))
        if N > 2666 or pval_two > 0.80 - N*0.3/1000:
            pass
        else:
            distributions.ksone.sf(D, N)
    generation_and_ks_and_sf_time = perf_counter() - start
    # confirm separate timing for calculation of p-value
    print(generation_and_ks_and_sf_time - generation_and_ks_time)

------

Note that an alternative strategy may be to make `kstwobign` faster, but I haven't looked at that...

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Interesting idea, but your `_LazyTestResult` doesn't reproduce enough of the tuple API to be backwards compatible.  A tuple can be indexed, but `_LazyTestResult` doesn't support indexing.  For example, this code uses your pull request:

```
In [21]: x = np.arange(10)

In [22]: y = np.sin(0.5*x)

In [23]: result = ks_2samp(x, y)

In [24]: result[1]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-7b02dd6b597f> in <module>()
----> 1 result[1]

TypeError: 'Ks_2sampResult' object does not support indexing
```
Also, `None` in the following output is unexpected:

```
In [34]: result = ks_2samp(x, y)

In [35]: for val in result:
    ...:     print(val)
    ...:     
0.9
None
```

**Comment by WarrenWeckesser** [comment]
A different approach to solving the problem is to create a new function, say `ks_2samp_statistic`, that returns just the statistic.  Then there is no need to change the object returned by `ks_2samp`.  I'm not advocating that approach at the moment, just thinking out loud.  It might be a good idea to discuss the problem on the mailing list before writing more code.

**Comment by anntzer** [comment]
Fixing indexing isn't too hard (I just forgot to implement it, will do).
I'm not really convinced by adding more functions to the API when ks_2samp/kstest are already good enough (with admittedly a bit of magic behind); for example with this PR's strategy if I later decide I did want to p-value after all, I can get it out without changing the function call.

**Comment by WarrenWeckesser** [comment]
I wrote:
> Also, None in the following output is unexpected:

The function `compute_p` in `ks_2samp` is missing a `return` statement.

**Comment by WarrenWeckesser** [comment]
Indexing must also handle slices, e.g.:

```
In [22]: t = (1.2, 0.5)

In [23]: t[1:]
Out[23]: (0.5,)
```
But with the `_LazyTestResult`, we get
```
In [24]: result = ks_2samp(x, y)

In [25]: result[1:]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-25-4a9e07982577> in <module>()
----> 1 result[1:]

~/miniconda36/lib/python3.6/site-packages/scipy-1.3.0.dev0+1f5adf3-py3.6-macosx-10.7-x86_64.egg/scipy/stats/stats.py in __getitem__(self, idx)
   4297             return self.pvalue
   4298         else:
-> 4299             raise IndexError("index out of range")
   4300 
   4301 

IndexError: index out of range
```
Tuples can be concatenated with `+`, but `_LazyTestResult` can not:
```
In [26]: t + (4,)
Out[26]: (1.2, 0.5, 4)

In [27]: result + (4,)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-05d82af2d95e> in <module>()
----> 1 result + (4,)

TypeError: unsupported operand type(s) for +: 'Ks_2sampResult' and 'tuple'
```

The question we have to ask is "If we change the object returned by `ks_2samp` (and other functions), how much of the `tuple` API must we preserve?"  A very conservative answer is "all of it", and in that case, `_LazyTestResult` might be better implemented as a subclass of `namedtuple`.

This issue is another part of a long, ongoing issue in scipy about the return values of many functions, so it should really be discussed further on the mailing list.

**Comment by anntzer** [comment]
Obviously I can just copy-paste the whole list of dunders and make them all unlazify the tuple and forward them to the underlying tuple (i.e. `def __foo__(self, *args): return (self.statistic, self.pvalue).__foo__(*args)`; I guess the question is whether it's worth the trouble...
Right now I'll just copy-paste the separate KS code for my own work and leave this PR for whoever wants to pick it up, or alternatively you can close it if you prefer.

**Comment by pvanmulbregt** [comment]
The implementation underneath has changed a lot since this PR was first created.  The times may look quite different now.  Computing the statistic may take up a significant portion of the compute time.

```
>>> import numpy as np                                                                                                                                                                             
>>> from time import perf_counter                                                                                                                                                                  
>>> from scipy.stats import distributions, kstest                                                                                                                                                  
>>> np.random.seed(0)                                                                                                                                                                              
>>> N = 1000                                                                                                                                                                                       
>>> start = perf_counter(); rnds = np.array([np.random.random(N) for _ in range(repeats)]); print(perf_counter() - start)                                                                          
0.02466234599978634
>>> start = perf_counter(); statistics = np.array([kstest(rnds[_], lambda x: x)[0] for _ in range(repeats)])   ; print(perf_counter() - start)                                                     
0.47992737799995666
>>> start = perf_counter(); pvalues = distributions.kstwobign.sf(statistics*np.sqrt(N)) ; print(perf_counter() - start)                                                                            
0.0009833660001277167
>>> start = perf_counter(); pvalues = distributions.kstwo.sf(statistics, N) ; print(perf_counter() - start)                                                                                        
0.19960901100012052
```

**Comment by anntzer** [comment]
Certainly the situation has improved (thanks!); however AFAICT the computation of p-values still takes a sizeable fraction of the total time?  (not "nearly all of the total time", which is certainly already better)

**Comment by pvanmulbregt** [comment]
Could you perhaps elaborate some more on the use case? 
Is it computing the KS for many small-sized samples?  Or for large-size examples?
 
I upped the sample size to 100k and broke apart the various parts of the algorithm: sorting the input, computing the cdf, computing D+ and D-, computing the p-value. (Note the perf_counter times did vary a little over the course of the session.)
```
>>> import numpy as np                                                                                                                                                                             
>>> from time import perf_counter                                                                                                                                                                  
>>> from scipy.stats import distributions, kstest 
>>> import scipy, scipy.stats, scipy.stats.stats                                                                                                                                                 
>>> np.random.seed(0)                                                                                                                                                                              
>>> N=100000                                                                                                                                                                                       
>>> np.random.seed(0)                                                                                                                                                                              
>>> start = perf_counter(); rnds = np.array([np.random.random(N) for _ in range(repeats)]); print(perf_counter() - start)                                                                          
1.717522284000097

# Sorting takes about 8s
>>> start = perf_counter(); statistics = np.array([np.sort(rnds[_])[0] for _ in range(repeats)])   ; print(perf_counter() - start)                                                                 
7.87141273799989

# Sorting plus computing the cdf is about 11s
>>> start = perf_counter(); np.array([scipy.stats.uniform.cdf(np.sort(rnds[_])) for _ in range(repeats)])   ; print(perf_counter() - start)                                                        
11.082989980999855

# Computing D+ and D- (dminus dplus) is within the noise
>>> start = perf_counter(); dplus = [scipy.stats.stats._compute_dplus(scipy.stats.uniform.cdf(np.sort(rnds[_])))  for _ in range(repeats)]; print(perf_counter() - start)                          
10.591330766999818
>>> start = perf_counter(); dminus = [scipy.stats.stats._compute_dplus(scipy.stats.uniform.cdf(np.sort(rnds[_])))  for _ in range(repeats)]; print(perf_counter() - start)                         
10.655620163000094

# Asymptotic evaluation  of kstest adds a further 2s
>>> start = perf_counter(); statistics = np.array([kstest(rnds[_], scipy.stats.uniform.cdf, mode='asymp')[0] for _ in range(repeats)])   ; print(perf_counter() - start)                           
13.029898403999823
# Exact evaluation  of kstest would have added  6-7s
>>> start = perf_counter(); statistics = np.array([kstest(rnds[_], scipy.stats.uniform.cdf, mode='exact')[0] for _ in range(repeats)])   ; print(perf_counter() - start)                           
17.472737312000163

# The individual KS distributions do have quite a difference in computation requirements 
>>> statistics  = np.max([dplus, dminus], axis=0)                                                                                                                                                  
>>> np.shape(statistics)                                                                                                                                                                           
(1000,)
# asymp is tiny addition
>>> start = perf_counter(); pvalues = distributions.kstwobign.sf(statistics*np.sqrt(N)) ; print(perf_counter() - start)                                                                            
0.0014234300001589872
# exact takes more compute.
>>> start = perf_counter(); pvalues = distributions.kstwo.sf(statistics, N) ; print(perf_counter() - start)                                                                                        
19.099975488999917
```

It appears that computing the p-value adds a negligible amount for `mode=asymp`, and perhaps 50% for mode=`exact`.  And that is with using a very simple CDF fun --- in practice CDF funcs will require more computation.

If the statistic is the main thing of interest, and the added time computing the exact p-value is not desired in all cases, I could suggest computing `kstest(rvals, cdf, mode="asymp")` for each `rvals` sample, and then only recomputing the exact p-value for the statistics that require it.

**Comment by anntzer** [comment]
To be honest I don't really need this anymore (I ended up just implementing KS statistic computation myself).  The idea was to implement some variant over https://arxiv.org/pdf/0706.1062.pdf, which estimates the cutoff from which a power-law fit can be used by comparing KS statistics of partial fits of distribution tails.

As I moved on to other stuff, feel free to close this.  After all the fact that the asymptotic estimation is quite fast should be good enough for most cases (and otherwise you can just write your own KS).

**Comment by josef-pkt** [comment]
I also copied both Anderson-Darling and KS statistics as separate (mostly internal) functions in statsmodels, so they can be used for other cases, like tests for distributions with estimated parameters.
That would also allow for simulated or bootstrap p-values, but I haven't added that yet to statsmodels.

**Comment by pvanmulbregt** [comment]
Closing based on author's suggestion in https://github.com/scipy/scipy/pull/9473#issuecomment-640112597

**Pull request closed without merging**
