### PR TITLE
MAINT, BLD: cibuildwheel Linux start

### PR DESCRIPTION
**Pull request by tylerjereddy**
* we're interested in moving to the modern
[`cibuildwheel`](https://cibuildwheel.readthedocs.io/en/stable/) machinery for the release/wheel
build process, following NumPy/pandas, etc.

* add some initial infrastructure that successfully
builds Python 3.8, 3.9, and 3.10 Linux x86_64 SciPy wheels
locally for me on a Linux box when running
`cibuildwheel --platform linux`

```
    3 wheels produced in 42 minutes:
        scipy-1.9.0.dev0+1841.27195e4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
116,067 kB
        scipy-1.9.0.dev0+1841.27195e4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
115,656 kB
        scipy-1.9.0.dev0+1841.27195e4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
115,872 kB
```

* this intentionally leaves out CI and other
platforms for now, just getting started, and
borrowing liberally from NumPy when it helps

### CODE REVIEW

**Comment by andyfaff** [comment]
This is awesome.

**Review by rgommers — APPROVED** [review]
LGTM. Seems fine to me to start this incrementally with a local build, thanks @tylerjereddy.

We should switch to Meson in `pyproject.toml` within the next 1-2 weeks, and then that 42 minutes will be a whole lot faster locally.

**Comment by rgommers** [comment]
@tylerjereddy it would probably be useful to copy in larger chunks from NumPy though? The `cibw_before_build.sh` script leaves out the LICENSE parsing for example (and other files from `tools/wheels/`), so these wheels aren't actually complete.

**Comment by tylerjereddy** [comment]
That's true, I was just trying to vet it locally in smaller chunks. This doesn't run the tests either AFAICT.

If you want me to just grow this PR as I test the pieces that's fine.

**Comment by rgommers** [comment]
> If you want me to just grow this PR as I test the pieces that's fine.

Yes, that's going to be easier to review I think.

**Comment by tylerjereddy** [comment]
Slightly blocked here because of new network security protocol that results in `self signed certificate in certificate chain` when using tools like this and `act`, because the external Docker containers don't have our internal certificates, argh. I'll see what I can do..

**Comment by tylerjereddy** [comment]
I copied over some of the NumPy `cibuildwheel` testing infra. First point of divergence I noticed is that we don't seem to have a `test_requirements.txt`, though I believe we've had such files in the past for i.e., Appveyor or something.

 Actually, you might think that if things were really well organized, since `cibuildwheel` is already configured in `pyproject.toml` to some extent, that there might be a way to leverage the `test` info already in `[project.optional-dependencies]`. Looks like `CIBW_BEFORE_TEST` with a custom command may be fairly standard though.

**Comment by tylerjereddy** [comment]
* added a quick and dirty `test_requirements.txt` with no version pins
*  the test suite passed locally, and properly failed b/c I haven't added the license in to wheels yet, so that's good

**Comment by tylerjereddy** [comment]
Ok, the wheel build + test + license checks are passing locally for me on Linux now (see below). Not sure if other platforms can be tested locally so easily.

```
3 wheels produced in 100 minutes:
  scipy-1.9.0.dev0+1949.bc9c930-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   116,121 kB
  scipy-1.9.0.dev0+1949.bc9c930-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl     115,662 kB
  scipy-1.9.0.dev0+1949.bc9c930-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl     115,900 kB
```

**Comment by andyfaff** [comment]
Superseded by #16842

**Pull request closed without merging**
