### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by rgommers** [comment]
@KOLANICH this doesn't look like something we would want to add to the repo itself. There are many editors with their own config files, and devs all have their own preferences for what should be in config files. So such files should live outside the repo.

**Comment by KOLANICH** [comment]
@rgrommers, it is a single config for many editors

**Comment by rgommers** [comment]
which editors? and does it overwrite, append, or is lower precedence than everything else?

**Comment by KOLANICH** [comment]
1. [here is the list](https://editorconfig.org/#download)
2. implementation-defined

**Comment by ilayn** [comment]
@KOLANICH regardless note that this is a package repository. 

Why should we keep an editor configuration? The developers for sure don't use it. The end-users basically import this package. So who needs this?

**Comment by KOLANICH** [comment]
Everyone who uses a compatible editor and doesn't have its settings matching pep8.

**Comment by ilayn** [comment]
Who are those everyone? Certainly not the users.

**Comment by KOLANICH** [comment]
Yes, I meant devs. Other folks usually install from pypi.

**Comment by ilayn** [comment]
We explicitly require PEP8 in our TravisCI testing suite hence we automatically assume PEP8 compliance anyways whether you have this plugin or not. You should be free to do whatever you want with your own editor. Hence this is a burden on the user.

Instead the testing suite will complain if you forgot to put in the PEP8 compliant version otherwise we don't care what kind of editor is used with whatever settings.

**Comment by KOLANICH** [comment]
>We explicitly require PEP8 in our TravisCI testing suite hence we automatically assume PEP8 compliance anyways whether you have this plugin or not.

I know. But if you won't accept a PR not complying with pep8, so why not to add a file making that automatic? I mean when I contribute into a project without that file, I get an additional burden to copy that file. If I have written some code before I have noticed that, I additionally have to fix the code. We have unneeded problems from such insignificant thing as style. To avoid the situation every project requiring a certain style should cointain that file by default. Not necessarily with spaces, but with the settings making the complience to that style automatic for contributors.

**Comment by ilayn** [comment]
That's to leave people to their own devices. For example more and more people are using [`black`](https://github.com/ambv/black). So I can use whatever i want tab with 20 spaces 309 line character long  etc and then when it is ready I pass through the tool and I am done. Now you are dictating an editor choice that is only meant for a specific audience. We don't want to dictate any such thing.

**Comment by KOLANICH** [comment]
Good point.

**Pull request closed without merging**
