### PR TITLE
Minor fixes to dendrogram plotting

### PR DESCRIPTION
**Pull request by MaigoAkisame**
#### What does this implement/fix?
* Changed `aa > n` and `ab > n` to `aa >= n` and `ab >= n`: `n` is not a leaf node.
* Changed `count_sort` and `distance_sort` to `count_sort == True` and `distance_sort == True`: otherwise the string `'descending'` would also be regarded as `True`.

### CODE REVIEW

**Comment by MaigoAkisame** [comment]
Seems the Travis CI build has failed for many PRs recently. Could someone confirm that it's not broken by this PR?

**Comment by ilayn** [comment]
Yep you can ignore that one. We are trying to fix it.

**Comment by rgommers** [comment]
Thanks @MaigoAkisame. The fix looks correct to me. Normally we'd like a regression test for bug fixes, but for plotting that's a bit of a pain. Any more context may be useful though for future reference, do you have an example showing the issue or at least a description of how you noticed this?

**Comment by MaigoAkisame** [comment]
@rgommers 

I spotted these mistakes when I was playing with the arguments to see how they would affect the dendrogram.

Here's an example that would reveal the error caused by missing the `== True` part:
```
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import numpy as np

data = np.array([[0], [1], [3]])
Z = linkage(data)
dendrogram(Z, count_sort='descending')
plt.show()
```

For the `>=` vs `>` part, it actually happens to never cause wrong outputs.
But I spotted the wrong semantics when I was reading the code.

**Review by rgommers — APPROVED** [review]
Thanks for the example @MaigoAkisame. 

For this example, in current master the `count_sort` keyword has no effect indeed, while with the fix the order is reversed:
```
In [2]: dendrogram(Z, count_sort='descending')
Out[2]: 
{'icoord': [[5.0, 5.0, 15.0, 15.0], [10.0, 10.0, 25.0, 25.0]],
 'dcoord': [[0.0, 1.0, 1.0, 0.0], [1.0, 2.0, 2.0, 0.0]],
 'ivl': ['1', '0', '2'],
 'leaves': [1, 0, 2],
 'color_list': ['C1', 'C0'],
 'leaves_color_list': ['C1', 'C1', 'C0']}

In [3]: dendrogram(Z, count_sort='ascending')
Out[3]: 
{'icoord': [[15.0, 15.0, 25.0, 25.0], [5.0, 5.0, 20.0, 20.0]],
 'dcoord': [[0.0, 1.0, 1.0, 0.0], [0.0, 2.0, 2.0, 1.0]],
 'ivl': ['2', '0', '1'],
 'leaves': [2, 0, 1],
 'color_list': ['C1', 'C0'],
 'leaves_color_list': ['C0', 'C1', 'C1']}
```

image

**Pull request merged**
