### PR TITLE
cKDTree query_ball_point improvements

### PR DESCRIPTION
**Pull request by rainwoodman**
This PR improves query_ball_point of cKDTree in three aspects:

1. General code clean up:
    - Use cython's memoryview instead of the old ndarray syntax in all functions
    - Remove the cross dependency between ckdtree_decls.h and ckdtree.pyx
    - Simplify the threading framework
    - Some extra white spaces were removed
    - GIL and exception translation with Cython

2. Fix a bug regarding 'return_sorted=True' and scalar queries.

3. Add new mode to query_ball_point, return_length. return_length only computes the length of the returned indices list instead of allocating the array everytime.

### CODE REVIEW

**Comment by rainwoodman** [comment]
The test failure is unrelated -- could someone rerun it?

**Comment by tylerjereddy** [comment]
@rgommers may be able to -- I think the SciPy Appveyor accounts predate my project involvement. That said, the Appveyor test isn't too much to worry about here since the Windows stuff if pretty widely covered by the Azure suite now.

**Comment by rgommers** [comment]
yeah just ignore the Appveyor error, just a connectivity issue

**Comment by rgommers** [comment]
@sturlamolden would you be able to review this?

**Comment by rainwoodman** [comment]
I threw in a few more clean-ups -- finally this PR is dropping the number of source code lines.

I do plan to make use of a few more recently established Cython features to eliminate the Python dependency in the C++ code. Either here or as a new PR.

**Comment by sturlamolden** [comment]
When the C++ code was written, we had to support Python 2.5. That is why it is written in such a peculiar way. Preferably all Python dependency should be in the Cython code, with no explicit use of Python and NumPy C API in C++. Regardless of how it is implemented, it is important that the GIL is released before doing any major lifting.

**Comment by sturlamolden** [comment]
That is, Python 2.5 and 2.6 severely limited the number of Cython features I could use.

As for avoiding Python dependency, we should even consider to avoid Python types, e.g. use ```double``` instead of ```npy_float64``` and ```std::intptr_t``` instead of ```npy_intp``` in the C++ code.

**Comment by rainwoodman** [comment]
I knew they were there for a reason.

My other concern was how reliable cython c++ exception translation is and
what version of cython are we targeting?

Yu

**Comment by sturlamolden** [comment]
The translation code is rather similar. Last time I checked, Cython also did not allow the GIL to be released, whilst cKDTree uses the simplified GIL API to temporarily reacquire the GIL during the translation process. GIL release is very important here. 

https://github.com/cython/cython/blob/084a25f55d0b4cf8b4c3cd496ec57bb3e2f57f71/Cython/Utility/CppSupport.cpp

https://github.com/scipy/scipy/blob/master/scipy/spatial/ckdtree/src/cpp_exc.cxx

**Comment by rainwoodman** [comment]
This thread seems to suggest we can declare a c++ extern function nogil,
and cython will do the right thing.

https://groups.google.com/forum/#!topic/cython-users/gz7UFvX9Rf0

**Comment by sturlamolden** [comment]
It seems Cython uses the simplified GIL API as well. 

https://github.com/cython/cython/commit/6795a2ba4761110c64c7a36401cb676614ba9f79

**Comment by sturlamolden** [comment]
Then I suppose we can get rid of a lot of crazy stuff. Cython can take care of all the Python dependencies. It probably makes it easier for others to contribute too :)

**Comment by rainwoodman** [comment]
To replace npy_intp with intptr_t we need stdint.h. 

I don't think older MSVC has the header, but we do target this compiler?

**Comment by sturlamolden** [comment]
template <class T>
auto __Pyx_pythran_to_python(T &&value) -> decltype(to_python(
      typename pythonic::returnable<typename std::remove_cv<typename std::remove_reference<T>::type>::type>::type{std::forward<T>(value)}))
{
  using returnable_type = typename pythonic::returnable<typename std::remove_cv<typename std::remove_reference<T>::type>::type>::type;
  return to_python(returnable_type{std::forward<T>(value)});
}


This is C++11, used by Cython

**Comment by rainwoodman** [comment]
Here is the travis error:
```
C compiler: g++ -pthread -Wno-unused-result -Wsign-compare -O0 -ggdb -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC
creating build/temp.linux-x86_64-3.7/scipy/spatial/ckdtree
creating build/temp.linux-x86_64-3.7/scipy/spatial/ckdtree/src
compile options: '-I/opt/python/3.7.1/include/python3.7m -I/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/numpy/core/include -Iscipy/_lib -Iscipy/spatial/ckdtree/src -I/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/numpy/core/include -I/opt/python/3.7.1/include/python3.7m -c'
g++: scipy/spatial/ckdtree.cxx
g++: scipy/spatial/ckdtree/src/query.cxx
In file included from /usr/include/c++/5/cstdint:35:0,
                 from scipy/spatial/ckdtree/src/ckdtree_decl.h:4,
                 from scipy/spatial/ckdtree/src/query.cxx:15:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
```

The default is -std=gnu++14; so I don't understand what's happening here. @rgommers What is the targeted C++ language standard of scipy?

**Comment by rgommers** [comment]
> The default is -std=gnu++14; so I don't understand what's happening here. @rgommers What is the targeted C++ language standard of scipy?

https://github.com/scipy/scipy/pull/9500/files has the most up-to-date overview of what compilers we need. There's no decision on C++ standard, we'd have to look at what the required compiler versions are. 

Looking at https://en.cppreference.com/w/cpp/compiler_support, anything beyond C++11 is going to be impossible for a very long time. For C++11, support for various features arrived in different MSVC versions, fom 14.0 to 19.0. Python 3.5 and 3.6 require MSVC 14.0, so you can only use C++ features that that version supports.

**Comment by sturlamolden** [comment]
This is odd. As ```auto``` keyword arrived in MSVC 16.0, does it mean that we cannot use Cython? Or that we cannot use Cython to translate C++ exceptions?

**Comment by rainwoodman** [comment]
The auto keyword is only used if one enables pythran, I think. But scipy doesn't use pythran -- at least we don't use it here. I checked my local generated source (Cython 0.29.x), and it doesn't have the auto keyword.

The final compilation issue is regarding the `isinf` function provided by the `_c99compat.h` header file.

Looks like it is not defined in clang on OSX. Shall this be considered as a bug in `_c99compat.h`?

**Comment by rainwoodman** [comment]
https://api.travis-ci.org/v3/job/509549669/log.txt

```

compile options: '-I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/Users/travis/build/scipy/scipy/venv/lib/python3.7/site-packages/numpy/core/include -Iscipy/_lib -Iscipy/spatial/ckdtree/src -I/Users/travis/build/scipy/scipy/venv/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c'

clang++: scipy/spatial/ckdtree.cxx

clang++: scipy/spatial/ckdtree/src/query.cxx

clang++: scipy/spatial/ckdtree/src/build.cxx

In file included from scipy/spatial/ckdtree.cxx:607:

In file included from /Users/travis/build/scipy/scipy/venv/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:

In file included from /Users/travis/build/scipy/scipy/venv/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:

In file included from /Users/travis/build/scipy/scipy/venv/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:

/Users/travis/build/scipy/scipy/venv/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]

#warning "Using deprecated NumPy API, disable it with " \

 ^

scipy/spatial/ckdtree.cxx:13563:19: error: use of undeclared identifier 'isinf'

  __pyx_t_4 = ((!(isinf(__pyx_v_p) != 0)) != 0);

                  ^

scipy/spatial/ckdtree.cxx:13587:23: error: use of undeclared identifier 'isinf'

      __pyx_t_4 = ((!(isinf((*((__pyx_t_5numpy_float64_t *) ( /* dim=0 */ ((char *) (((__pyx_t_5numpy_float64_t *) __pyx_v_real_r.data) + __pyx_t_16)) )))) != 0)) != 0);

                      ^

1 warning and 2 errors generated.
```

**Comment by rainwoodman** [comment]
I am done with the planned changes. I've checked valgrind was clean with latest suppression file from Python. The build error on circleci / pypy3 is a 404 we probably still want to rerun it.

**Comment by tylerjereddy** [comment]
I haven't had any luck using restarts to circumvent the recent pypy3 circleci issue, but probably safe to say it is unrelated.

**Comment by rainwoodman** [comment]
But pypy3 can talk to Cython extensions now?

**Comment by tylerjereddy** [comment]
cc @mattip for that

**Comment by rainwoodman** [comment]
It's documented in https://cython.readthedocs.io/en/latest/src/userguide/pypy.html

I am not experienced enough to tell the pypy3 friendliness of the new ckdtree.pyx; a pair of experienced eyes could be helpful. Making the situation easier is that we are certain that the C++ portion of the extension never does a single call to Python API.

**Comment by mattip** [comment]
The problem is long before `ckdtree.pyx`. the CI script is trying to download and install a specific libopenssl, but debian has changed the package name. That seems brittle. I will take a look tomorrow.

**Comment by tylerjereddy** [comment]
@rainwoodman Do you have a minute to rebase this on the latest master branch so we can see what happens on the pypy run?

I suspect we'll want to condense the 41 commits, but for now I just want to see the pypy3 run through.

**Comment by rainwoodman** [comment]
Looks like I can condense this into ~ 5 relatively orthogonal commits (one per item in the description) with relative ease.

**Comment by rgommers** [comment]
If it's not too much work, I think that would be useful @rainwoodman

**Comment by rainwoodman** [comment]
I simply squashed the later commits. I am afraid the earlier commits may be a bit too intertwined.

**Comment by sturlamolden** [comment]
It’s time to merge this.

**Comment by rgommers** [comment]
Thanks @rainwoodman! I did one more pass through the code, all looks good to me. Commit granularity and commit messages are very nice as well. In it goes.

**Comment by tylerjereddy** [comment]
Draft release note for this PR here: https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.3.0#scipyspatial-improvements

Please do fix up if you see a way to improve

**Pull request merged**
