### PR TITLE
DOC: Fixed incorrect default for mode in scipy.ndimage.spline_filter1d

### LINKED ISSUE #10610: ndimage.interpolation.spline_filter1d default value of mode
In ```ndimage.interpolation```, the function [```spline_filter1d```](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.spline_filter1d.html) has a misleading docstring about the default value of the parameter ```mode```. The docstring says default is ```'constant'```, however, in the implementation it is ```'mirror'```. One of them needs to be changed. Any idea on which one? This part of the docstring is set at the beginning of the file with copying a docdict, so I don't know what the best move is. (This might also affect ```spline_filter```)
cc @jaimefrio @rgommers

### PR DESCRIPTION
**Pull request by sethtroisi**
#### Reference issue

Fixes https://github.com/scipy/scipy/issues/10610

#### Additional information

I tested by running `doc$ make html-scipyorg` and tried to verify inspecting `scipy/doc/build/html-scipyorg/generated/scipy.ndimage.spline_filter1d.html` **but they don't show my changes** I spent 20 minutes and 3 builds but was unable to figure out how to get `make html` to reflect changes I made to docstrings. (maybe something is cached in some weird way)

### CODE REVIEW

**Comment by rgommers** [comment]
> I tested by running `doc$ make html-scipyorg` and tried to verify inspecting `scipy/doc/build/html-scipyorg/generated/scipy.ndimage.spline_filter1d.html` **but they don't show my changes** I spent 20 minutes and 3 builds but was unable to figure out how to get `make html` to reflect changes I made to docstrings. (maybe something is cached in some weird way)

or it's picking up your install SciPy rather than your in-place build?

**Review by rgommers — APPROVED** [review]
Nice comprehensive fix, thanks @sethtroisi

**Comment by larsoner** [comment]
>  was unable to figure out how to get make html to reflect changes I made to docstrings. (maybe something is cached in some weird way)

This is indeed something that should work. I made use of it just a few days ago when working on docs. So something must be awry with your setup. I can't think of anything that could be wrong beyond what @rgommers suggested, though.

**Comment by sethtroisi** [comment]
Yes, SciPy was based on my system's scipy (despite virtualenv having dev scipy installed).

I also seem to be running into https://github.com/scipy/scipy/issues/11179

**Pull request merged**
