### PR TITLE
ENH: Peaks declustering and signal up/down-crossing finding

### PR DESCRIPTION
**Pull request by ali-cetin-4ss**
This pull request adds peaks declustering and basic signal crossing detection similar to argrelmax, argrelmin (cf. @rgommers ).

The pull request is feature complete with unit-tests and doc.

### CODE REVIEW

**Comment by ilayn** [comment]
Pinging @lagru just in case wants to be involved

**Comment by lagru** [comment]
@ilayn Thanks. I'll have a look.

**Comment by ace-e4s** [comment]
>           May need a rebase for that dispatcher error in the CI?

Hmm... I tried to do a rebase, but now it got even worse? Help?

**Comment by tylerjereddy** [comment]
Yeah, the git history looks a little messy now with unrelated changes from others showing up in the PR itself.

You can maybe use `git log` to isolate a relevant commit hash where `git diff master` produces the diff you'd expect, but it will take some work now I think.

Usually I'd do something like:
`git checkout master`
`git fetch origin`
`git pull origin master`
`git checkout crossing_finding`
`git rebase master`
`git push -f ace-e4s crossing_finding`

I'm guessing you did something differently though. You should be able to use git to selectively pick changes from specific files in a new / clean branch off master if worst comes to worst.

**Comment by ace-e4s** [comment]
Ahh crap! I merged upstream/master in into master before rebase. hmmf… Lets see if I manage to untangle this :(

**Comment by ilayn** [comment]
If it turns out to be too difficult just get your changes out somewhere else close this and open a new one. It kinda doesn't pay off in the end. You can always cherrypick from here if need be but I don't see any reason to keep the history per se.

**Comment by ace-e4s** [comment]
Yes, this turned out to be a messy affair. As @ilayn suggests, I will close this pull request and open a new one with the changes. I will notify you when the new PR is ready.

**Comment by ilayn** [comment]
No problem, I'm still doing these mistakes and I'd like to stay as a noob in Git if I can :) Here is also my saved reply in Github in case needed similar to Tyler's workflow

<hr>

For future when you are updating the branch first get to the master branch, say you call the actual scipy repo as `upstream` and your own origin is, well, `origin`. 

    git fetch upstream  # this will grab the current status and changes of the upstream
    git rebase upstream/master  # this will implement the changes of the official to your own master
    git push origin  # this is optional but brings your origin uptodate

then suppose you want to bring the official changes to your dev branch `my_dev_branch`, start by switching to it

    git checkout my_dev_branch

then the tricky bit that actually does the rebase over your dev branch

    git rebase master

This temporarily removes your changes, grabs the changes of the master and inserts to your branch, then adds your changes at the end of it. At this point git is craving for a sync, but you just force push such that the commit your branch is not contaminated by other commits from others. 

    git push origin -f
    
By doing so compared to master, only your changes are pushed. (I'm pretty sure I'm not perfectly on point with my explanation but to be honest I'll never get the git syntax)

**Pull request closed without merging**
