### PR TITLE
DOC: stats: Add Examples for bartlett, fligner, levene.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
The examples aren't very exciting, but they're better than nothing.

### CODE REVIEW

**Comment by chrisb83** [comment]
Suggestion: print the variance of a, b and c in the examples?

**Comment by WarrenWeckesser** [comment]
@chrisb83, good idea, I'll add that.

**Comment by WarrenWeckesser** [comment]
@chrisb83, I added a note about the samples variances of the data.

**Comment by chrisb83** [comment]
Thanks for updating the example!

**Pull request merged**
