### PR TITLE
Add 'exponential' interpolation to `scipy.interpolate.interp1d`

### PR DESCRIPTION
**Pull request by APN-Pucky**
#### What does this implement/fix?
Add 1-dimensional exponential interpolation. 
This is similar to the linear interpolation `f(x) = a*x+b` between two data points, but with `g(x) = a*exp(b*x)`.
This is useful for interpolation of an exponential curve (straight lines on a logarithmic x axis).

#### Additional information
The blue plot is a linear interpolation on a logarithmic scale.
The orange plot is the new exponential interpolation.

2022-06-14 11_00_30-Interpolate

In the same way one could add a logarithmic interpolation.

### CODE REVIEW

**Comment by ev-br** [comment]
How is this different from taking a log manually and log(y) vs x?

**Comment by APN-Pucky** [comment]
I agree. It is basically the same as `f = lambda x_new : np.exp(interpolate.interp1d(x,np.log(y),kind="linear")(x_new))` which is a bit unwieldy.

**Comment by ev-br** [comment]
> I agree. It is basically the same as

Thanks.

> ip = interpolate.interp1d(x,np.log(y),kind="linear")
> f = lambda x_new : np.exp(ip(x_new))

Which is precisely why I'm -1 for adding it to the library. This firmly belongs to the userland. 
Maybe the recipe above can be added to the interpolate tutorial

**Comment by ev-br** [comment]
Thanks @APN-Pucky for wanting to help! This kind of functionality was actually present in scipy.interpolate a while ago. It was basically unused, so we removed it. The bottom line is it's even easier for a user to compute the logs then sort through and validate what a library does.

**Pull request closed without merging**
