### PR TITLE
MAINT: Don't use numpy's aliases of Python builtin objects.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Don't use `np.int`, `np.float`, etc.  These numpy names will
be deprecated; see https://github.com/numpy/numpy/pull/14882.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
I tested this branch locally against numpy version `'1.20.0.dev0+c22fab7'` from https://github.com/numpy/numpy/pull/14882, and all tests passed.

**Review by eric-wieser — APPROVED** [review]

**Comment by eric-wieser** [comment]
This is a follow up to #5076

**Review by larsoner — APPROVED** [review]

**Review by tylerjereddy — APPROVED** [review]
Changes look sensible from a quick scan and expert approvals from NumPy and SciPy core devs, so merging, thanks @WarrenWeckesser and reviewers.

**Comment by tylerjereddy** [comment]
This needs a backport based on the pre-wheels CI failures in https://github.com/scipy/scipy/pull/12397 so labeling accordingly

**Pull request merged**
