### PR TITLE
ENH:special:Re-rewrite cdflib in C

### PR DESCRIPTION
**Pull request by ilayn**
Following the translation of `cdflib` from F77 to Cython in #19560, due to our discussions about binary sizes and other details this is the translation from Cython to C.

For future readers, since Fortran subroutines all pass by reference and Cython wrappers were not very ergonomic we first translated the Fortran code to functions returning output arguments. Then we retranslated them here and to keep things compatible we used `structs` for returning multiple output args. Those are the `TupleDXXX` that are in the code.

### CODE REVIEW

**Comment by steppi** [comment]
Thanks @ilayn! This is a big help.

**Comment by izaid** [comment]
> Thanks @ilayn! This is a big help.

Indeed! Many thanks @ilayn!

**Comment by ilayn** [comment]
This is is code-wise finished but I've hit some 10ish test errors that I can't find out where I made a typo. Unfortunately, I ran out of steam trying to hunt down bugs with special code as it has been months looking at the same stuff. 

So if you have any bandwidth have a go at it, maybe I will come back later when I feel less blinded in a month or so.

**Review by tylerjereddy — COMMENTED** [review]
Do we have a reliable way to produce Cython-based code line coverage reports with `meson`/`dev.py`? This has always been a bit annoying I think, irrespective of build system (internet searches agree with various things needing to be just right/activated...).

When looking at one of the failures via `python dev.py test -j 1 -t "scipy/special/tests/test_data.py::test_boost[<Data for gdtrix_comp: gamma_inv_big_data_ipp-gamma_inv_big_data>]"`

I ended up using `printf` to track incantations of:

- `gaminv`
- `gratio`
- `erfc1` 
- `rcomp` 
- `rlog` 
- `cdfgam_which2`

But getting the Cython line coverage hits in a nice HTML file could be useful for quickly seeing what is flushed on a given test. It looks like the way the bindings work for `cdflib.c` C file, using `gcov` (which is easier) for the C version faces the problem of working with generated C code from Cython bindings it seems (?), so tracking the control flow that way seems messy too.

That's a bit unfortunate, both Cython and the way the translation units seem to work on the "pure C" side seems to make getting side-by-side control flow comparisons a bit tricky.

Perhaps that's some tooling we could think about improving over time, it is pretty useful to be able to see the line hits when debugging, and a major quality of life difference compared with pure Python of course.

**Comment by steppi** [comment]
> So if you have any bandwidth have a go at it, maybe I will come back later when I feel less blinded in a month or so.

I should have time to review it earlier than that. I’m going to give it the same line by line treatment I did for specfun, and will hopefully find everything that way.

**Comment by ilayn** [comment]
> This has always been a bit annoying I think, irrespective of build system

Indeed, I have a full `printf`'d versions of these files including fortran ones but the issue of finding the bugs is that these are iterative solutions. Hence you have to view the progression in a very long log file. On top of that, though code seems to be quite robust, the coding practices are substandard and needs serious refactoring. 

> C version faces the problem of working with generated C code from Cython bindings it seems

That's correct. I could not make `gcov` work with `cimport`ed cases somehow Cython blocks the hits from the mechanism.

> I should have time to review it earlier than that. I’m going to give it the same line by line treatment I did for specfun, and will hopefully find everything that way.

Thanks. I think bratio, bup, brcmp1 are the culprit for the beta bugs, and gaminv for the remaining ones. I already discovered some more bugs in cdflib which are fixed here. But introduced new ones apparently

**Comment by ilayn** [comment]
OK I accidentally found my printf'd copies of both Cython and C file. As usual the typos are just from my acquired blindness. 

There is a final test remaining failing locally about slight tolerance violation. If that's acceptable to bump, this is good to go.

**Comment by ilayn** [comment]
Nevermind it's another typo. All pass locally.

**Comment by ilayn** [comment]
@rgommers The last commit is making `cdflib` a static library and before that I added the c files directly. If you want you can check the binary sizes, it would be great to have 3 data points; Cython vs. raw compile vs. static linking.

I wanted to do it myself but I couldn't quite get the right compilation environment details from the meson system that builds the wheels.

And for all potential reviewers, this is ready for merge.

**Comment by lucascolley** [comment]
we are still green, CI failure is the flaky overflow (@tylerjereddy is there an issue for that??)

**Review by steppi — APPROVED** [review]
Looks good @ilayn. Thanks for doing this. I’m going to give @rgommers a chance to respond re static_library or not, but otherwise think it’s ready to merge.

**Comment by rgommers** [comment]
To look 

> @rgommers The last commit is making `cdflib` a static library and before that I added the c files directly. If you want you can check the binary sizes, it would be great to have 3 data points; Cython vs. raw compile vs. static linking.

To get release build sizes, you can remove the `build` directory and then do:
```
python dev.py build -C-Dbuildtype=release
```
after that first build, and rebuilds with `python dev.py build` will use the release setting, so you can switch branches and do a partial rebuild easily.

It looks like:
- Cython: `_cdflib.so` is 178 kb
- static lib: `_ufuncs.so` grows by 70 kb and `cython_special.so` by 78 kb -> 148 kb
- adding `cdflib.c` to sources: the exact same numbers as for the static library (that's expected)

So it's only a modest gain. Once `cython_special.so` disappears, it's a ~2.5x gain it looks like.

Build time goes from 5.7 sec with Cython to 1.2 sec with this PR (2.4 sec without the static lib). So static lib is the winner, about 4x-5x faster - nice work:)

**Comment by ilayn** [comment]
Hmm I would have expected a more dramatic drop but anyways data is data, thanks for the analysis 😃 

And thanks all for the review and the help.

**Comment by rgommers** [comment]
I think the difference in binary sizes in debug mode may have been significantly larger (but I didn't recheck this).

**Pull request merged**
