### PR TITLE
TST: fix test bug w/ convolve method

### LINKED ISSUE #7348: New complex192 not supported test error
Getting errors for the 32-bit builds of scipy:

```
======================================================================
ERROR: test_convolve_method (test_signaltools.TestConvolve)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 186, in test_convolve_method
    for key in ['fft', 'direct']}
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 186, in <dictcomp>
    for key in ['fft', 'direct']}
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/signaltools.py", line 789, in convolve
    out = fftconvolve(volume, kernel, mode=mode)
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/signaltools.py", line 403, in fftconvolve
    sp2 = fftpack.fftn(in2, fshape)
  File "/venv/local/lib/python2.7/site-packages/scipy/fftpack/basic.py", line 622, in fftn
    return _raw_fftn_dispatch(x, shape, axes, overwrite_x, 1)
  File "/venv/local/lib/python2.7/site-packages/scipy/fftpack/basic.py", line 631, in _raw_fftn_dispatch
    raise ValueError("type %s is not supported" % tmp.dtype)
ValueError: type complex192 is not supported
```

https://travis-ci.org/MacPython/scipy-wheels/jobs/226731274

I guess this is from 760a369 - @stsievert - any thoughts?

### PR DESCRIPTION
**Pull request by stsievert**
Fixes #7348

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
LGTM, I'll merge once CIs are happy unless someone else beats me to it.

**Comment by stsievert** [comment]
I'm running into a CI bug.

``` python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/ndimage/tests/test_c_api.py", line 8, in <module>
    from scipy.ndimage import _ctest_oldapi
ImportError: dynamic module does not define module export function (PyInit__ctest_oldapi)
```

All tests pass except the Python 3.5 test.

**Comment by Eric89GXL** [comment]
Failure is unrelated and is happening on all CIs. Thank @stsievert

**Comment by rgommers** [comment]
Just ran into this because I didn't backport it. After looking into it I'm pretty sure that this fix is not correct and that ``_fftconvolve_valid`` doesn't make sense. It returns False also for float64 input, because of the last check:

    if _numeric_arrays([volume, kernel]):
        return False

I'll open a new issues about checking ``_fftconvolve_valid``, and will open a new PR with what I think is the correct fix.

**Comment by rgommers** [comment]
PR to fix this up: gh-7517

**Pull request merged**
