### PR TITLE
ENH: Wrap all BLAS routines

### LINKED ISSUE #1915: Wrap BLAS function gbmv
_Original ticket http://projects.scipy.org/scipy/ticket/1390 on 2011-02-21 by trac user RhysU, assigned to unknown._

Please add a wrapper for the BLAS level 2 routine general band matrix-vector multiply (gbmv) within source:trunk/scipy/lib/blas/fblas_l2.pyf.src

This should just be wrapping the BLAS dgbmv routine (see http://www.netlib.org/blas/dgbmv.f) in the same way that dgemm has been wrapped.

Thank you,
Rhys

### PR DESCRIPTION
**Pull request by ilayn**
Remaining tasks are 

- [x] Add tests for the missing ones
- [x] Wrap `trsm`

Closes #1915

### CODE REVIEW

**Comment by ilayn** [comment]
There are two files for BLAS tests and it seems that I've chosen the wrong one. Should I move the new tests into `test_blas.py` or should I keep them under `test_fblas.py` ?

**Comment by rgommers** [comment]
I can't detect a clear logic in the split between ``test_blas.py`` and ``test_fblas.py``. They're about the same length and there's some overlap in functions they test. So not sure. 

If you see the logic and can maintain or improve it, go for the move though I'd say:)

**Comment by pv** [comment]
I think it's some leftover from the days we had both blas and cblas 
wrappers, most likely not relevant any more.

**Comment by ilayn** [comment]
I am really surprised that this test ```


    def test_scal(self):
        for p in 'sd':
            f = getattr(fblas, p+'scal', None)
            if f is None:
                continue
            assert_array_almost_equal(f(2, [3, -4, 5]), [6, -8, 10])
        for p in 'cz':
            f = getattr(fblas, p+'scal', None)
            if f is None:
                continue
            assert_array_almost_equal(f(3j, [3j, -4, 3-4j]), [-9, -12j, 12+9j])
        for p in ['cs', 'zd']:
            f = getattr(fblas, p+'scal', None)
            if f is None:
                continue
            assert_array_almost_equal(f(3j, [3j, -4, 3-4j]), [-9, -12j, 12+9j])
```

under `TestFBLAS1Simple` class has been passing. It should have been (and does on my build) failed in the 3rd assertion. Can anyone confirm this? 

`csscal` and `zdscal`, as their name imply meant for real,float scalars but here it is multiplied by a complex number.

**Comment by ilayn** [comment]
Here is my regular console output with SciPy 0.19.1
```
In[15]: sp.linalg.blas.zdscal(3j,[3j, -4+0j, 3-4j])
Out[15]: array([ 0.+0.j, -0.+0.j,  0.-0.j])

In[16]: sp.linalg.blas.csscal(3j,[3j, -4+0j, 3-4j])
Out[16]: array([ 0.+0.j, -0.+0.j,  0.-0.j], dtype=complex64)
```

**Comment by pv** [comment]
The code pasted above is not the same as in the repository:
https://github.com/scipy/scipy/blob/master/scipy/linalg/tests/test_blas.py#L180

**Comment by ilayn** [comment]
Tests seem to be stuck but this is ready for review from my side.

**Comment by zerothi** [comment]
@ilayn could you according to #7847 add `*sycon`, `*hecon` routines as well? Then I can apply our discussion in #7847.

**Comment by ilayn** [comment]
Yes, I'll add as soon as I have time with another PR.

**Comment by zerothi** [comment]
Great! Thanks!

**Comment by rgommers** [comment]
This would be really nice to get into the next release, so if someone has the bandwidth and expertise to review in the next 24 hours, please do!

**Comment by zerothi** [comment]
I won't be able to check and do #7847 before next week. :(

**Comment by larsoner** [comment]
I might have time -- @ilayn if this is Fortran wrapping plus tests for it I might be able to look. Do you think it's good enough if I look, given I've done two (one accepted one in progress) PR to add LAPACK functions, or would you be more comfortable if someone more experienced looked?

**Comment by rgommers** [comment]
@larsoner go for it I'd say! If you're not 100% about something maybe just flag it, and someone else can check post merging.

**Comment by ilayn** [comment]
Sure @larsoner the more the merrier. It's mostly repetitive wrappers anyways. Tests are there but let me know if more is needed.

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge

**Comment by rgommers** [comment]
All tests pass (also checked 32-bit Linux), and positive review. So in it goes. Thanks @ilayn, and @larsoner for the review!

**Comment by rgommers** [comment]
I'll do the release notes update.

**Pull request merged**
