### PR TITLE
BENCH: optimize: add timings to global optimizers benchmarks

### PR DESCRIPTION
**Pull request by tessavdheiden**
#### What does this implement/fix?

The global optimizers are now also benchmarked on time they take to execute.

**How to run?**
Please execute the following commands. 
The variables are set to limit the time it takes to run the benchmark. 
```
export SCIPY_GLOBAL_BENCH=AMGM
export SCIPY_XSLOW=1
export SCIPY_GLOBAL_BENCH_NUMTRIALS=10
python dev.py bench -t optimize.BenchGlobal
``` 

Observe the following: 
```
[100.00%] ··· =============== ============== ===================== ==================== ===================== ====================== =====================
              --                                                                                 solver                                                   
              ------------------------------ -------------------------------------------------------------------------------------------------------------
               test function   result type             DE                basinh.                  DA                  DIRECT                  SHGO        
              =============== ============== ===================== ==================== ===================== ====================== =====================
                    AMGM         success%            100.0                100.0                 100.0                 100.0                  100.0        
                    AMGM          <nfev>             1840.0               847.3                 4044.3                2008.0                  6.0         
                    AMGM       average time   0.04791226387023926   0.0276763916015625   0.07132751941680908   0.008054971694946289   0.15258502960205078 
                  Ackley01       success%             n/a                  n/a                   n/a                   n/a                    n/a         
                  Ackley01        <nfev>              n/a                  n/a                   n/a                   n/a                    n/a         
                  Ackley01     average time           n/a                  n/a                   n/a                   n/a                    n/a         
                 .
                 .
                 .
                 Zimmerman       success%             n/a                  n/a                   n/a                   n/a                    n/a         
                 Zimmerman        <nfev>              n/a                  n/a                   n/a                   n/a                    n/a         
                 Zimmerman     average time           n/a                  n/a                   n/a                   n/a                    n/a         
                  Zirilli        success%             n/a                  n/a                   n/a                   n/a                    n/a         
                  Zirilli         <nfev>              n/a                  n/a                   n/a                   n/a                    n/a         
                  Zirilli      average time           n/a                  n/a                   n/a                   n/a                    n/a         
              =============== ============== ===================== ==================== ===================== ====================== =====================


```
#### Additional information

Any future changes to the global optimizer algorithms, can now be compared on time :-).

### CODE REVIEW

**Comment by dschmitz89** [comment]
Thanks for the PR!

When I saw the title, I was sceptical at first because runtime is not a typical benchmark metric for global optimizers but the results are actually quite interesting. The optimizers implemented in Python apparently come with significant overhead for cheap objective functions like the ones benchmarked here. DIRECT is much faster than basinhopping although it performs more objective evaluations.

**Comment by Stefan-Endres** [comment]
To add to @dschmitz89's comments the runtime is important not only in scipy's benchmarks, but also in practical applications where the objective function is relatively cheap to evaluate, but global optimisation is still needed (phase equilibria computations is an explicit example). It is therefore also important for development to benchmark new branches with. I've discussed this before over e-mail with @tessavdheiden, as something I would personally also really like to see used in scipy.

I would be happy to help review and/or contribute to this PR if this is addition is wanted by everyone.

**Comment by lucascolley** [comment]
@tessavdheiden a message to the mailing list might help this gain some traction

**Comment by tupui** [comment]
Thank you @tessavdheiden 
I am +1 on the proposal too.

**Comment by tessavdheiden** [comment]
Hey @lucascolley,

Thanks for your comment! I've posted a [message](https://mail.python.org/archives/list/scipy-dev@python.org/thread/3VW5O7AYDIGAOMPGVEGWJ35GJZ27XLR5/), but I am not sure if it resulted in much traction. 

Any ideas how we can merge it in?

**Review by lucascolley — APPROVED** [review]
I've added a milestone - someone should get to it before the next release :) (no complaints on the mailing list is always a good sign)

**Review by lucascolley — APPROVED** [review]
okay, I gave this a go locally and observe the times as well - pulling this in now, thanks for your first contribution to SciPy @tessavdheiden !

**Pull request merged**
