### PR TITLE
MAINT: update scipy-sphinx-theme

### PR DESCRIPTION
**Pull request by rgommers**
For theme update, see https://github.com/scipy/scipy.org/pull/290

~~Updates numpydoc from 0.8.0 to 0.9.1~~

### CODE REVIEW

**Comment by rgommers** [comment]
@tylerjereddy I would like to apply the `scipy-sphinx-theme` commit also to 1.3.x before the 1.3.0 release. Okay to backport?

**Comment by rgommers** [comment]
Hmm, spotting two issues with the numpydoc update

1. The yellow highlighting of the See Also blocks is not the right vertical length (sometimes too long, something too short).
2. The function listing for `*args, **kwargs` functions look bad: https://13071-1460385-gh.circle-artifacts.com/0/html-scipyorg/stats.html

**Comment by rgommers** [comment]
The numpydoc update isn't urgent, so removing that from this PR for now.

**Comment by tylerjereddy** [comment]
Ok, so this will remove the old "sponsored by" headline in our docs?

**Comment by rgommers** [comment]
indeed

**Comment by tylerjereddy** [comment]
I'm getting ready for a backport PR and an rc2, so putting this in, thanks Ralf

**Comment by rgommers** [comment]
thanks Tyler

**Comment by tylerjereddy** [comment]
I've removed the backport label after merging #10155 -- if this also belongs in 1.2.x LTS maybe restore the label so I see it

**Pull request merged**
