### PR TITLE
Fix umfpack solver construction for win-amd64

### PR DESCRIPTION
**Pull request by rc**
See #7600. This should address the scipy side of https://github.com/scikit-umfpack/scikit-umfpack/issues/36.

### CODE REVIEW

**Comment by rgommers** [comment]
Commenting in the right place now: I tested this PR and scikit-umfpack master, both pass all tests on 32-bit Linux (which had issues with this before).

**Comment by rc** [comment]
OK, I guess that's it from me for now :)

**Comment by rgommers** [comment]
Tested also on 64-bit Windows (https://github.com/scikit-umfpack/scikit-umfpack/issues/36#issuecomment-332282857), all good so merging. Thanks @rc

**Comment by rgommers** [comment]
backported in commit 6cbb1f82

**Pull request merged**
