### PR TITLE
DOC: Add examples to spatial.distance

### PR DESCRIPTION
**Pull request by MartinThoma**
Additionally, make first like use imperative mood

### CODE REVIEW

**Comment by perimosocordiae** [comment]
I'm not sure I see the benefit of these new examples. The formulas for each distance metric are pretty clear and the function signatures are straightforward, so what are the examples adding?

**Comment by MartinThoma** [comment]
I simply like having examples. Everywhere. For me, it is much faster to just skip to the examples, copy & paste one and adjust it instead of going through the function signatures / the formula.

When there are examples, it is simpler to add new ones. I would like to see ones which show properties of the distance functions. For example, for cosine I added an example which shows that it is independant of the length of a vector.

**Comment by rgommers** [comment]
> I simply like having examples. Everywhere. For me, it is much faster to just skip to the examples, copy & paste one and adjust it instead of going through the function signatures / the formula.

I agree with this, ideally every function should have examples. ``%paste`` in IPython is my best friend:)

**Comment by apbard** [comment]
I agree that examples are generally useful but on this particular case (i.e. metric functions) I am not sure how much they can be useful. Anyway, I would either add examples to all metrics or to none.

p.s. To better show the properties of the metric couldn't be useful to add a link to the wiki page or to the paper where the metric is defined?

**Comment by MartinThoma** [comment]
> Anyway, I would either add examples to all metrics or to none.

I've just added the remaining examples to all metrics and dissimilarity measures.

**Comment by rgommers** [comment]
@MartinThoma we've just merged a couple of PRs that added weights to most metrics and changed the pdist/cdist signatures. So this now needs a rebase. Demonstrating what the weights do would add value to the examples.

**Comment by MartinThoma** [comment]
@rgommers I've rebased the pull request, but I don't think I'll find the time to demonstrate the influence of weights anytime soon.

**Comment by rgommers** [comment]
Thanks @MartinThoma, no worries. I think this is OK to merge in its current state (disclaimer: haven't double checked all examples in detail).

**Pull request merged**
