### PR TITLE
DOC: fix typos in doc

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by andyfaff** [comment]
The typo changes involved in tutorials and documentation are worth making. However, those involved with release notes (which seem to be most of the changes) are not. This is because the typos involved in the latter are from git commit messages, and we're not going to go making changes to those.

**Comment by kianmeng** [comment]
@andyfaff Done. Please check.

**Comment by andyfaff** [comment]
Thank you @kianmeng

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
