### PR TITLE
CI: re-enable Pythran in Azure Windows CI jobs

### PR DESCRIPTION
**Pull request by rgommers**
Building with Pythran should be fixed in gh-15531

[skip github]

### CODE REVIEW

**Comment by tupui** [comment]
> Building with Pythran should be fixed in [gh-15531](https://github.com/scipy/scipy/pull/15531)
> 
> [skip github]

It's `[skip actions]` 😉 And I am also wondering why the other is not working, maybe the same issue with azure. I noticed `[skip azp]` must be on the first line for it to work.

**Comment by rgommers** [comment]
> It's `[skip actions]`

Why? Was this just changed? I still see `[skip github]` in the magic strings in our `.yml` files.

**Comment by larsoner** [comment]
> Why? Was this just changed?

`[skip github]` was the original third-party/custom solution, `[skip actions]` is what the GH Actions people actually implemented at their end. So most projects I work on have transitioned to using `[skip actions]` and gotten rid of `[skip github]` in the YAML files.

> I still see [skip github] in the magic strings in our .yml files.

Maybe it's present in some but not others? I'm not sure... but it might be good to get rid of it in all files and have people transition to the more standard `[skip actions]`.

**Comment by tupui** [comment]
I don't know when the behaviour changed if it did (and I did not do anything on that myself). I just noticed that I can use `actions` (IIRC this is included in GH, also why we don't have this in our yml) anywhere in the message and `azp` must be on the first line because the filter explicitly ask for this line only.

**Comment by rgommers** [comment]
> `[skip actions]` is what the GH Actions people actually implemented at their end

ah finally!

now if only Azure could get their act together too ....

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge assuming it actually comes back green!

**Review by tylerjereddy — APPROVED** [review]
CI seems "ok" to me--I doubt the Azure timeouts are related, and a few Azure Windows jobs do pass here. Also unlikely that 1-line change in the Azure config causes CircleCI to timeout.

**Comment by tylerjereddy** [comment]
thanks; I guess we'll do something similar in the wheels repo as well for `1.8.1` perhaps

**Pull request merged**
