### PR TITLE
BUG: linalg.cossin: fix for nonsymmetric cases

### LINKED ISSUE #19365: BUG: scipy.linalg.cossin fails for specific values of (p, q) and separate=False
### Describe your issue.

I found a case where the scipy.linalg.cossin function returns an incorrect diagonal block matrix (D) when separate=False. Using terminology like https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cossin.html, if q > m - p then `assert np.allclose(U@D@Vt, X)` fails.

I developed a workaround in https://github.com/sfcaracciolo/cossin_wrapper. I use separate=True to build each matrix from theta.

### Reproducing Code Example

```python
import scipy  as sp 
import numpy as np 

# generate a random dimension m
rng = np.random.default_rng()
m = rng.integers(50, high=100)
p = np.random.randint(10, 40) # always p < m
q = np.random.randint(m-p+1, m-1) # always m-p < q < m 
# next line works
# q = np.random.randint(1, m-p-1) # always q < m-p
X = sp.stats.unitary_group.rvs(m) # random unitary matrix
U, D, Vt = sp.linalg.cossin(X, p=p, q=q, separate=False)
assert np.allclose(U@D@Vt, X)
```

### Error message

```shell
Traceback (most recent call last):
  File "E:\Repositorios\cossin_wrapper\tests\issue.py", line 13, in <module>
    assert np.allclose(U@D@Vt, X)
AssertionError
```

### SciPy/NumPy/Python version and system information

```shell
Python: 3.10.0
SciPy: 1.11.3
NumPy: 1.26.0
```

### PR DESCRIPTION
**Pull request by Ritvik1sharma**
…omposition correctly. If I run it for a 9x9 matrix with p, q as 3, 6 and 6,3 it causes errors.

### CODE REVIEW

**Comment by ilayn** [comment]
Hi @Ritvik1sharma thank you for taking the time to fix an issue. Could you please elaborate what the issue was and what the solution fixes? 

For instance, there is still #19365 open that I just realized I forgot to come back to. Is it possible to replicate the story for this issue too?

**Comment by mdhaber** [comment]
Actually, I think this just needs tests. It fixes gh-19365 and the following property-based test, which just confirms everything the documentation claims about the output. The test fails (many times over) in `main`, but passes with this patch.

<details>

```python3
import numpy as np
from scipy import linalg
from scipy.stats import unitary_group

def test_cossin(m, p, q):
    # Generate unitary input
    X = unitary_group.rvs(m)
    np.testing.assert_allclose(X @ X.conj().T, np.eye(m), atol=1e-15)

    # Perform the decomposition
    u, cs, vh = linalg.cossin(X, p=p, q=q, separate=True)
    u1, u2 = u
    v1, v2 = vh
    v1, v2 = v1.conj().T, v2.conj().T

    # "U1, U2, V1, V2 are square orthogonal/unitary matrices
    # of dimensions (p,p), (m-p,m-p), (q,q), and (m-q,m-q) respectively"
    np.testing.assert_allclose(u1 @ u1.conj().T, np.eye(p), atol=1e-13)
    np.testing.assert_allclose(u2 @ u2.conj().T, np.eye(m-p), atol=1e-13)
    np.testing.assert_allclose(v1 @ v1.conj().T, np.eye(q), atol=1e-13)
    np.testing.assert_allclose(v2 @ v2.conj().T, np.eye(m-q), atol=1e-13)

    # "and C and S are (r, r) nonnegative diagonal matrices..."
    C = np.diag(np.cos(cs))
    S = np.diag(np.sin(cs))
    # "...satisfying C^2 + S^2 = I where r = min(p, m-p, q, m-q)."
    r = min(p, m-p, q, m-q)
    np.testing.assert_allclose(C**2 + S**2, np.eye(r))

    # "Moreover, the rank of the identity matrices are
    # min(p, q) - r, min(p, m - q) - r, min(m - p, q) - r,
    # and min(m - p, m - q) - r respectively."
    I11 = np.eye(min(p, q) - r)
    I12 = np.eye(min(p, m - q) - r)
    I21 = np.eye(min(m - p, q) - r)
    I22 = np.eye(min(m - p, m - q) - r)

    # From:
    #                            ┌                   ┐
    #                            │ I  0  0 │ 0  0  0 │
    # ┌           ┐   ┌         ┐│ 0  C  0 │ 0 -S  0 │┌         ┐*
    # │ X11 │ X12 │   │ U1 │    ││ 0  0  0 │ 0  0 -I ││ V1 │    │
    # │ ────┼──── │ = │────┼────││─────────┼─────────││────┼────│
    # │ X21 │ X22 │   │    │ U2 ││ 0  0  0 │ I  0  0 ││    │ V2 │
    # └           ┘   └         ┘│ 0  S  0 │ 0  C  0 │└         ┘
    #                            │ 0  0  I │ 0  0  0 │
    #                            └                   ┘

    # We can see that U and V are block diagonal matrices like so:
    U = linalg.block_diag(u1, u2)
    V = linalg.block_diag(v1, v2)

    # And the center matrix, which we'll call Q here, must be:
    Q11 = np.zeros((u1.shape[1], v1.shape[0]))
    IC11 = linalg.block_diag(I11, C)
    Q11[:IC11.shape[0], :IC11.shape[1]] = IC11

    Q12 = np.zeros((u1.shape[1], v2.shape[0]))
    SI12 = linalg.block_diag(-S, -I12)
    Q12[-SI12.shape[0]:, -SI12.shape[1]:] = SI12

    Q21 = np.zeros((u2.shape[1], v1.shape[0]))
    SI21 = linalg.block_diag(S, I21)
    Q21[-SI21.shape[0]:, -SI21.shape[1]:] = SI21

    Q22 = np.zeros((u2.shape[1], v2.shape[0]))
    IC22 = linalg.block_diag(I22, C)
    Q22[:IC22.shape[0], :IC22.shape[1]] = IC22

    Q = np.block([[Q11, Q12], [Q21, Q22]])

    # Confirm that `cossin` decomposes `X` as shown
    np.testing.assert_allclose(X, U @ Q @ V.conj().T)

    # And check that `separate=False` agrees
    U0, CS0, Vh0 = linalg.cossin(X, p=p, q=q)
    np.testing.assert_allclose(U, U0)
    np.testing.assert_allclose(Q, CS0)
    np.testing.assert_allclose(V, Vh0.conj().T)

for m in range(1, 20):
    for p in range(1, m):
        for q in range(1, m):
            print(p, q)
            test_cossin(m, p, q)

```

</details>

Thanks @Ritvik1sharma!

**Comment by sfcaracciolo** [comment]
Hi everybody, 

I just want share with you that I tested the @Ritvik1sharma code too. This fragment https://github.com/sfcaracciolo/cossin_wrapper/blob/master/tests/issue.py works for every q < m now. Before it failed if m-p < q < m.

Thanks!

**Comment by ilayn** [comment]
I think it is obvious that there is a bug in the indexing but I did not look into it. So any fix is welcome.

**Comment by mdhaber** [comment]
OK, I'll go ahead and add something like my test above and merge.

**Comment by mdhaber** [comment]
@sfcaracciolo I think this is about ready, but I might add `compute_u` and `compute_vh` into the test for completeness. Otherwise, do the tests look like they are comprehensive and doing what they purport to do (i.e. check all the features about the decomposition claimed in the docs)?

**Comment by sfcaracciolo** [comment]
@mdhaber I think the tests looks fine, great job!

Just as suggestion, I think it's good to build Q11, Q12, Q21 and Q22 without u1, u2, v1, v2 information (shapes in this case) to keep Q separated of v, u errors. Following [this](https://github.com/scipy/scipy/issues/19365#issuecomment-1758655908), I would replace,
```python
Q11 = np.zeros((u1.shape[1], v1.shape[0]))
...
```
by
```python
r = min([p, q, m - p, m - q])
fmin = lambda a, b: min([a, b])-r
fmax = lambda a, b: max([a-b, 0])

Q11 = np.zeros((fmin(p,q) + r + fmax(p,q), fmin(p,q) + r + fmax(q,p)))
...
```
or something like (adapted of [this](https://github.com/sfcaracciolo/cossin_wrapper/blob/d62743ad3611dda609e868660d7e0c4bf8ac54ed/src/cossin_wrapper/core.py#L5)),
```python
Q11 = sp.sparse.block_diag((
    sp.sparse.identity(fmin(p,q), format='dia', dtype=np.float64),
    C,
    sp.sparse.csc_array((fmax(p,q), fmax(q,p)), dtype=np.float64)
))
```

**Comment by mdhaber** [comment]
> Just as suggestion, I think it's good to build Q11, Q12, Q21 and Q22 without u1, u2, v1, v2 information (shapes in this case) to keep Q separated of v, u errors.

I following the properties given in the documentation, and I don't see the shapes of these matrices given there. After this merges, would you be willing to add that information to the documentation and update the test accordingly?

**Comment by mdhaber** [comment]
@sfcaracciolo I'll go ahead and merge now so this fix makes it into the next release, but please let me know if you'd be willing to add that information to the documentation. I'd be happy to review and merge a PR about that.

**Pull request merged**
