### PR TITLE
Update description for nnz on csc.py

### PR DESCRIPTION
**Pull request by spaceman-codes**
This is to resolve issue #10132

### CODE REVIEW

**Review by perimosocordiae — APPROVED** [review]
Thanks for the quick fix!

**Comment by ev-br** [comment]
Does this need to be forward-ported to master? It seems unlikely that there will be a new 1.2.x release.
@spaceman-codes usually, all PRs should be towards the master branch. release manager then decides what to backport

**Comment by perimosocordiae** [comment]
Oops, sorry I merged without looking at the target branch. My git-fu is a little rusty, does someone else want to move the commit to master?

**Comment by rgommers** [comment]
is in master now, commit 2202f70921

**Comment by WarrenWeckesser** [comment]
The same change should be made in bsr.py, coo.py, csr.py, dia.py and lil.py.

**Comment by spaceman-codes** [comment]
@WarrenWeckesser done.

**Pull request merged**
