### PR TITLE
TST: use np not math for functions to avoid conversion of ndim>0 to scalar

### PR DESCRIPTION
**Pull request by andyfaff**
Should hopefully fix one of the test fails in #18331

### CODE REVIEW

**Comment by andyfaff** [comment]
@josef-pkt, this PR fixes one of the test fails in #18331 (test_newton_by_name), but is there an issue that needs to be fixed at a deeper level in the newton code?

**Comment by josef-pkt** [comment]
The warning in the statsmodels test suite is below. 
I did not look at it because we have a HUGE number of warnings with assignments like `arr[0] = np.array([1])`

```
statsmodels/emplike/tests/test_origin.py::TestOrigin::test_ci_beta
  /opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/scipy/optimize/_zeros_py.py:799: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
# this looks like scipy
```

**Comment by andyfaff** [comment]
With `optimize.newton` the underlying code uses `optimize._numdiff.approx_derivative` (which is private), whose docstring states:
```
    fun : callable
        Function of which to estimate the derivatives. The argument x
        passed to this function is ndarray of shape (n,) (never a scalar
        even if n=1). It must return 1-D array_like of shape (m,) or a scalar.
    x0 : array_like of shape (n,) or float
        Point at which to estimate the derivatives. Float will be converted
        to a 1-D array.
```
Thus user functions are always going to be sent arrays, even if there is only one entry in them.
I think the test fail was because code similar to the following triggers the DeprecationWarning.

```python
import math
import numpy as np

math.cos(np.array([0.5]))
```

**Review by mdhaber — APPROVED** [review]
I'm not too concerned about the overhead of using NumPy versions of these functions in tests, and it fixes the failure.

@andyfaff would you like this merged now or wait to collect other things?
@josef-pkt if this PR does not address your failures, please provide a minimal reproducible example involving only SciPy code.

**Comment by josef-pkt** [comment]
The folder does not use math. We almost never use `math`.

I'm just guessing because I don't have any dev versions of numpy nor scipy.

possibly 
The unit test has one bound as scalar and one bound as one-element 1d array
The function `f` returns a scalar for scalar input (and AFAICS raises if ndim is not zero)
`optimize.brentq(f, 3.8295722241620758, array([0.00351813]))`

**Comment by andyfaff** [comment]
This PR is only going to fix the scipy test, and won't address any downstream code. I'd prefer to merge now so that CI isn't continuously red. If there are downstream issues that it's best if new issues are raised.

**Pull request merged**
