### PR TITLE
MAINT: sparse.linalg: A minor improvement with zero initial guess

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

Residual norm should be calculated according to the specific value of the initial guess

### CODE REVIEW

**Comment by jarrodmillman** [comment]
This looks like it is mainly for performance. Is that correct?

(If `x0 is None`, then the `x` returned by `make_system` is a vector of zeroes.)

**Comment by xie-group** [comment]
> This looks like it is mainly for performance. Is that correct?
> 
> (If `x0 is None`, then the `x` returned by `make_system` is a vector of zeroes.)

Yes. `b - Ax` does not need to be calculated in the case of the zero initial guess.

**Comment by zhaog6** [comment]
> This looks like it is mainly for performance. Is that correct?
> 
> (If `x0 is None`, then the `x` returned by `make_system` is a vector of zeroes.)

Yes. `b - Ax` does not need to be calculated in the case of the zero initial guess.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @zhaog6

**Pull request merged**
