### PR TITLE
Adds CMH

### PR DESCRIPTION
**Pull request by Vassyli**
This PR adds the Cochran-Mantel-Haenszel test of independence for Nx2x2 contingency tables.

### CODE REVIEW

**Comment by josef-pkt** [comment]
FYI: I assume this is the same as http://www.statsmodels.org/dev/generated/statsmodels.stats.contingency_tables.StratifiedTable.test_null_odds.html  for 2x2xk stratified contingency tables.

**Comment by rgommers** [comment]
If this functionality is already available in ``statsmodels``, then we shouldn't add it to ``scipy``. @Vassyli maybe there's still something in your PR that is of value to the ``statsmodels`` implementation?

**Comment by Vassyli** [comment]
The Cochran-Mantel-Haenszel test is listed in morestats.py under "Tests to include (from R) -- some of these already in stats.", that (and since the statsmodels package was unknown to me) motivated me to add it myself. I admit it's not the generalized CMH test for NxJxK that is in R and I can understand that you think it's not necessary to add it to scipy.stats if it's already in statsmodels.

**Comment by rgommers** [comment]
Thanks for pointing that out @Vassyli. Those comments are from before the creation of statsmodels and haven't been kept up-to-date. I will remove them.

For major features/TODOs we have a [roadmap](https://github.com/scipy/scipy/blob/master/doc/ROADMAP.rst.txt), for anything else we don't really keep a list (although there are GitHub issues with feature requests) - that too easily goes out of date. Asking about or proposing a new feature on the scipy-dev mailing list is usually the best way to go.

Closing this PR, since we don't want to duplicate statsmodels here. Thanks for your contribution @Vassyli

**Pull request closed without merging**
