### PR TITLE
sparse.linalg.svds: ensure non-negative singular values for which='SM'

### PR DESCRIPTION
**Pull request by jedbrown**
When estimating the smallest magnitude singular values of a singular
matrix, it is common for ARPACK to return tiny negative values.  These
are handled carefully in which='LM', but not for which='SM'.  Simple
examples such as
    
      A = csr_matrix(([1.,1,1,1,1], ([0,1,1,2,3],[0,0,1,0,1])), shape=(4,3))
      svds(A, which='SM', k=2, return_singular_vectors=False)

 produce `FloatingPointError: invalid value encountered in sqrt`.  This
commit ensures that the estimated eigenvalues are non-negative.

### CODE REVIEW

**Review by tylerjereddy — CHANGES_REQUESTED** [review]
I'm not the right person to comment on the linear algebra, but since you've already included what seems to be a clean example of a failure scenario with the original code, I might suggest that adding a unit test of a similar nature would be most helpful (i.e., in preventing regression, etc.).

**Comment by lobpcg** [comment]
https://github.com/scipy/scipy/pull/10830 supersede this PR

**Comment by rgommers** [comment]
Apologies your PR didn't get reviewed @jedbrown. We're short on reviewers that understand sparse linalg.

After merging gh-10830, your example now gives:
```
>>> A = csr_matrix(([1.,1,1,1,1], ([0,1,1,2,3],[0,0,1,0,1])), shape=(4,3))                     
>>> svds(A, which='SM', k=2, return_singular_vectors=False)                                    
/Users/rgommers/Code/scipy/scipy/sparse/linalg/eigen/arpack/arpack.py:1871: RuntimeWarning: invalid value encountered in sqrt
  cutoff = cond * np.max(eigvals)
array([      nan, 1.1755705])
```

Just checking: I assume that's the expected behavior?

**Comment by jedbrown** [comment]
It is not expected/desirable behavior. Expected behavior is to return `[1.1755705, 0]` without errors. A singular matrix is not malformed input.

**Comment by lobpcg** [comment]
Sorry, I do not have a setup to run it myself and debug now. But there is something I do not understand in this error in https://github.com/scipy/scipy/pull/8169#issuecomment-552223536 
The corresponding code is line 1864-1871 of https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/arpack/arpack.py
```
    # Gramian matrices have real non-negative eigenvalues.
    eigvals = np.maximum(eigvals.real, 0)

    # Use the sophisticated detection of small eigenvalues from pinvh.
    t = eigvec.dtype.char.lower()
    factor = {'f': 1E3, 'd': 1E6}
    cond = factor[t] * np.finfo(t).eps
    cutoff = cond * np.max(eigvals)
```

1. First, notice the 1865 line `eigvals = np.maximum(eigvals.real, 0)` ,which is suggested in PR, appearing in the merged code. That is why I have proposed closing this PR.  
2. Second, there is no explicit `sqrt` call in the line 1871:
```
cutoff = cond * np.max(eigvals)
```
so I am unsure where the error comes from. 

If this error is re-confirmed, the proper course of action may be to close this PR, since the proposed fix is already merged, and instead open a new bug report with this error.

**Comment by rgommers** [comment]
Thanks @jedbrown, and thanks for the detailed feedback @lobpcg.

It looks like I was indeed testing with the wrong version. At least, I can't reproduce it anymore:
```
In [1]: from scipy.sparse import csr_matrix                                        

In [2]: from scipy.sparse.linalg import svds                                       

In [3]: %paste                                                                     
  A = csr_matrix(([1.,1,1,1,1], ([0,1,1,2,3],[0,0,1,0,1])), shape=(4,3))
  svds(A, which='SM', k=2, return_singular_vectors=False)

## -- End pasted text --
Out[3]: array([0.       , 1.1755705])

In [4]: import scipy; scipy.__version__                                            
Out[4]: '1.5.0.dev0+9e27e4c'
```

Sorry about the confusion. Seems fixed, closing.

**Pull request closed without merging**
