### PR TITLE
TST: reduce time of some DE tests

### PR DESCRIPTION
**Pull request by andyfaff**
The pypy circle build gives a list of slow tests at the end of a run. This [list](https://circleci.com/gh/scipy/scipy/11277?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) indicates 3 slow differential evolution tests. This PR significantly reduces the time for those tests to run.

### CODE REVIEW

**Comment by andyfaff** [comment]
@larsoner, this should reduce the runtime of the pypy run by approx 25 secs.

**Review by larsoner — APPROVED** [review]
Excellent, it's always good to cut on test time. This one looks pretty straightforward, feel free to ping me tomorrow or early next week for a merge if there are no other comments.

**Comment by andyfaff** [comment]
@larsoner ping

**Comment by larsoner** [comment]
Thanks @ andyfaff

**Pull request merged**
