### PR TITLE
MAINT: add issue template for bug reports

### PR DESCRIPTION
**Pull request by pv**
It may be worthwhile to add an issue template to guide people on what information is useful to include in bug reports, especially in trying to push them to include self-contained test cases.

### CODE REVIEW

**Comment by ev-br** [comment]
Non-blocking comment: maybe try crafting some friendlier language. These things tend to look like government forms, and thus might scare off less experienced first-time reporters.

+1 from me regardless.

**Comment by rgommers** [comment]
> especially in trying to push them to include self-contained test cases.

+1 

Other items are probably less necessary, e.g. OS and compilers are not often needed. So maybe leave those out or explicitly say they're optional?

**Comment by ilayn** [comment]
I particularly liked the spyder version just to give another example afbeelding

**Comment by pv** [comment]
The spyder is a bit different as it's interactive application. In the 
case of Scipy, the steps to reproduce are better substituted by the code 
example imho.
.
I agree it's important the template is short, because of tl;dr.
.
We can perhaps scrap the expected/actual behavior parts, as those are 
usually remembered. The OS can often be inferred, so maybe that can go too.
.
This would leave error code example, error message, and version. I think 
it's useful to emphasize the full error message, as sometimes people 
just paste the last line and you are left guessing.
.
If you know how you want to adjust the language, please go ahead and do 
it (to me it reads matter-of-fact but OTOH not native english speaker).

**Comment by perimosocordiae** [comment]
I think the language is fine as written, and I'm also +1 for removing expected/actual behavior sections.

It might be worthwhile to manually line-wrap the longer lines, as I'm not sure if the new issue UI does it automatically.

**Comment by pv** [comment]
I think the UI linewraps.

**Comment by pv** [comment]
Updated, maybe merge? If you want to adjust the language, please push changes directly to the branch (or merge and send a new PR).

**Comment by Eric89GXL** [comment]
+1 for merge from me

**Pull request merged**
