### PR TITLE
Fix or avoid various test failures that are showing up in CI

### PR DESCRIPTION
**Pull request by rgommers**
Relevant issues:
- gh-17004
- gh-16926
- gh-16949
- gh-17056

### CODE REVIEW

**Comment by rgommers** [comment]
Okay, this fixes all the known older problems that I wanted to fix. Just one new problem with `gfortran` on Azure Ubuntu (unrelated to changes in this PR). I'll add one more fix, hopefully that helps.

**Comment by ilayn** [comment]
> I agree that the OpenBLAS issues do need investigation, but that is a separate task from fixing CI so we can sensibly work on other PRs.

I am checking that these days, so far no smoking guns.

> The PROPACK issues may require a separate discussion for the next release. There are so many issues that at this point it would not be unreasonable to completely remove that functionality from SciPy.

I am slowly warming up to this idea as well.

**Comment by rgommers** [comment]
Ah, great to hear you are looking into the issues @ilayn. I will mark the linked issues for the `1.10.0` release, so that we at least revisit them before the next release and can assess if we should really disable some functionality as @WarrenWeckesser suggests. It's not so easy to do this based on detected `openblas` version reliably, but that would be one option.

**Review by tylerjereddy — APPROVED** [review]
Changes LGTM. The PR doesn't auto-close any of the matching issues so seems like pretty standard to get the CI green(er) again and continue addressing the bad tests on a case-by-case basis.

**Pull request merged**
