### PR TITLE
Fix fresnel documentation

### PR DESCRIPTION
**Pull request by lakshayg**
#### What does this implement/fix?
The documentation of fresnel function had the definitions of
S and C integrals mixed up. This PR fixes those definitions.

### CODE REVIEW

**Comment by person142** [comment]
Thanks for the fix @lakshayg.

**Comment by mdhaber** [comment]
Thanks @lakshayg! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Comment by lakshayg** [comment]
Hi @mdhaber, I've added an entry to the wiki page. Do you happen to know how often is scipy documentation at docs.scipy.org regenerated? I still see the incorrect fresnel definitions there.

**Comment by person142** [comment]
@lakshayg so the docs for each particular version are typically only updated at the time of release, but the devdocs already reflect the change:

https://scipy.github.io/devdocs/generated/scipy.special.fresnel.html#scipy.special.fresnel

**Pull request merged**
