### PR TITLE
STY: always `import numpy as np`

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
n/a

#### What does this implement/fix?
Always `import numpy as np`, rather than just `import numpy`. In one blame-ignored commit.

I've taken care to fix indentation where applicable.

#### Additional information
This was annoying me so I dealt with it package-wide. Took a lot longer than I was expecting, darn `ndimage` tests :upside_down_face:

### CODE REVIEW

**Comment by rgommers** [comment]
Seems like a useful thing to do, thanks Lucas.

This accumulated a merge conflict already, could you resolve that?

**Comment by lucascolley** [comment]
done. do you want a rebase to capture everything in the blame-ignore?

**Comment by rgommers** [comment]
> done. do you want a rebase to capture everything in the blame-ignore?

It's fine as is I think, the number of "escaping" lines here is small.

**Review by j-bowhay — APPROVED** [review]
Thanks @lucascolley, CI is green and changes are quite straightforward so let's get this in before we pick up any more merge conflicts

**Comment by tqa236** [comment]
I wonder if there's any interest in adding a lint rule to prevent regression? `ruff`'s [`unconventional-import-alias`](https://docs.astral.sh/ruff/rules/unconventional-import-alias/) can be used to enforce this. 

I can submit a PR if this is a welcome change.

**Comment by lucascolley** [comment]
> I wonder if there's any interest in adding a lint rule to prevent regression? ruff's unconventional-import-alias can be used to enforce this.

Yes, I am interested in this, as long as the amount of current violations is small enough to be dealt with in one PR (hopefully 0 after this! But not sure which other imports are included).

> I can submit a PR if this is a welcome change.

Happy to review!

**Pull request merged**
