### PR TITLE
BUG: minimize(f, [x], method="Powell").x.shape should return (1,)

### LINKED ISSUE #9715: scipy.optimize.minimize(f, [array_of_length_1], method="Powell").x.shape is ()
When minimize single parameter function like `lambda x: x*x` with `scipy.optimize.minimize`, 
Only Powell method returns zero-dimensions array. (Other methods return one-dimension array)

I wrote test code to check all methods which described in [SciPy v1.2.0 Reference Guide](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html).
Code is https://github.com/gyu-don/scipy/commit/e0d698d8e0bfd5862a2245174e462e8c3ed468c9
All methods except Powell are returns one-dimension array.

### Reproducing code example:

```
import numpy as np
import scipy.optimize

def fun(x):
    return x*x

res = scipy.optimize.minimize(fun, [0.1], method="Nelder-Mead")
print("Nelder-Mead:")
print("Optimized:", res.x, "Shape:", res.x.shape)
res = scipy.optimize.minimize(fun, [0.1], method="COBYLA")
print("COBYLA:")
print("Optimized:", res.x, "Shape:", res.x.shape)
res = scipy.optimize.minimize(fun, [0.1], method="Powell")
print("Powell:")
print("Optimized:", res.x, "Shape:", res.x.shape)
```

Above code uses only 3 methods.
pytest code is available here.
https://github.com/gyu-don/scipy/commit/e0d698d8e0bfd5862a2245174e462e8c3ed468c9

### Output:

```
Nelder-Mead:
Optimized: [1.94289029e-16] Shape: (1,)
COBYLA:
Optimized: [0.00010234] Shape: (1,)
Powell:
Optimized: 4.163336342344337e-17 Shape: ()
```

### Scipy/Numpy/Python version information:

```
1.3.0.dev0+e0d698d 1.16.0 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

### Solution?
Remove the line `x = np.squeeze(x)` in scipy/optimize/optimize.py, then, Powell returns one-dimention array. https://github.com/gyu-don/scipy/commit/763da791f6836c10186be278251735a41582b84a
If this solution is acceptable, I will submit pull request.

### PR DESCRIPTION
**Pull request by gyu-don**
#### Reference issue
Closes gh-9715.

#### What does this implement/fix?

Move `squeeze(x)` from `_minimize_powell` to `fmin_powell`.
Behaviour of `fmin_powell` is not changed and `minimize(f, [x], method="Powell").x` returns 1-dimensional array.

### CODE REVIEW

**Comment by gyu-don** [comment]
> gyu-don force-pushed the gyu-don:gh-9715 branch from be28a92 to d68b256 3 minutes ago

Sorry, it's because my master branch was old.

```
git remote add upstream https://github.com/scipy/scipy.git
git checkout master && git pull upstream master
git checkout gh-9715
git rebase master
git push --force
```

**Review by andyfaff — CHANGES_REQUESTED** [review]
The change to optimize.py is fine. Whilst the test is ok in itself, it's probably a lot longer than it needs to be. My preference would be for:

```
def test_resultXShapeWhenLenXIsOne():
     def fun(self, x):
        return x * x

     def jac(self, x):
        return 2. * x

     def hess(self, x):
        return np.array([[2.]])

     methods = ['Nelder-Mead', 'Powell', 'CG', 'BFGS',  'L-BFGS-B', 'TNC', 'COBYLA', 'SLSQP']
     for method in methods:
         res = optimize.minimize(self.fun, np.array([0.1]), method=method)
         assert res.x.shape == (1,)
     # use jac+hess
     methods = ['trust-constr', 'dogleg', 'trust-ncg', 'trust-exact', 'trust-krylov', 'Newton-CG']
     for method in methods:
         res = optimize.minimize(self.fun, np.array([0.1]), method=method, jac=jac, hess=hess)
         assert res.x.shape == (1,)
```

**Comment by andyfaff** [comment]
Or even put all the methods within a single string, do a single loop, and just filter the RuntimeWarning caused by sending hess/jac to Nelder-Mead, etc.

**Comment by gyu-don** [comment]
@andyfaff  Sorry for late reply. I modified the test.

**Review by andyfaff — APPROVED** [review]

**Comment by andyfaff** [comment]
Thank you for contributing to scipy @gyu-don. It's in a good state, so merging.

**Comment by mdhaber** [comment]
Thanks @gyu-don! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Pull request merged**
