### PR TITLE
Add citation of published paper

### PR DESCRIPTION
**Pull request by raoulbq**
I found that the paper "Fast computation of Gauss quadrature nodes and weights on the whole real line" was published in March. Here is the additional reference.

### CODE REVIEW

**Comment by ev-br** [comment]
http://imajna.oxfordjournals.org/content/early/2015/03/10/imanum.drv002.full.pdf+html (google search result for the DOI link) seems to be gated, I'd suggest keeping both published version and the arXiv link.

**Comment by raoulbq** [comment]
Yes, I we should keep both versions. I like citing freely accessible resources.
Another question is if and how one could deduplicate the citation. It should
definitely appear in all the relevant docstrings.

**Comment by ewmoore** [comment]
I wouldn't worry about the duplication.    

It would be good to add something like [this](https://gist.github.com/jonls/b910afc46473b02597c4) to our document generation routines. Possibly extended to also support arxiv links. It would probably also be good to go back through and add dois to all of the references.

**Comment by ewmoore** [comment]
Seems adding support for doi's to numpydoc is actually numpy/numpydoc#34.

**Pull request merged**
