### PR TITLE
BENCH: Add dual annealing to scipy benchmark (see #9415)

### PR DESCRIPTION
**Pull request by sgubianpm**
@rgommers, thanks for the merging. This PR is for adding `optimize.dual_annealing` into the scipy optimize benchmark. I ran:
```bash
python runtests.py --bench -s optimize
```
with ``SCIPY_XSLOW=5`` env var exported to test if what I added in benchmarks/benchmarks/optimize.py was ok.
This was to address #9415.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @sgubianpm, that works for me.

**Comment by sgubianpm** [comment]
Thanks @rgommers for merging this benchmark addition. What about running the test with [GOBench](https://github.com/sgubianpm/GOBench) for now including `shgo` as an intermediate evaluation overall performance (something outside the repos for now) and enhance the scipy benchmark for optimization later one?

**Comment by rgommers** [comment]
Thanks @sgubianpm , that makes sense for now. We'll want some viz capability at some point though. Perhaps there was something somewhere that I missed, because the original source of our benchmarks had some plots as well IIRC (@andyfaff do you remember?).

@Stefan-Endres said in https://github.com/scipy/scipy/pull/8098#issuecomment-436729990 that he's interested in adding performance profile plots as well.

**Comment by andyfaff** [comment]
When I added in the Global Optimisation benchmarks there was no plotting. Any plots would've been done by other code. The output could certainly be improved, both in terms of writing to a properly designed file (I think at the moment one has to parse stdout), and code that could plot the file.

**Comment by rgommers** [comment]
> both in terms of writing to a properly designed file (I think at the moment one has to parse stdout),

`asv` produces sane json files.

**Comment by sgubianpm** [comment]
I ran the benchmark with only 5 runs to check and `asv` produced a file called ``global-bench-results.json`` which seems to be usable (I changed the extension for attaching it).

[global-bench-results.txt](https://github.com/scipy/scipy/files/2565058/global-bench-results.txt)

**Pull request merged**
