### PR TITLE
MAINT: special: Remove deprecated `hyp2f0`, `hyp1f2`, and `hyp3f0`

### PR DESCRIPTION
**Pull request by person142**
They were deprecated in 1.2, so their time is up. Original deprecation PR was here: https://github.com/scipy/scipy/pull/8924

### CODE REVIEW

**Comment by ev-br** [comment]
Thanks Josh

**Comment by ev-br** [comment]
Needs a release note, too

**Comment by pv** [comment]
Great, good riddance!

**Comment by person142** [comment]
Release note added: https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.4.0#scipyspecial-changes

**Pull request merged**
