### PR TITLE
DEP: non-integers in `factorial(..., exact=True)`: deprecate for scalars and execute deprecation for arrays

### PR DESCRIPTION
**Pull request by h-vetinari**
Follow-up to #15841

### CODE REVIEW

**Comment by h-vetinari** [comment]
If desired, I can split the PR in two - one for executing the deprecation in the array case (first commit), and one for adding the deprecation in the the scalar case (second commit).

I hadn't done the latter in https://github.com/scipy/scipy/pull/15841 in an attempt to minimize the breakage that this PR already entailed by necessity).

**Comment by j-bowhay** [comment]
The new deprecation part probably needs an email to the mailing list

**Comment by h-vetinari** [comment]
> The new deprecation part probably needs an email to the mailing list

While I don't think that's needed in this case (`exact=True` with floats does nothing at best and is actively misleading at worst), I don't mind writing an email. 🤷

**Review by j-bowhay — APPROVED** [review]
Thanks @h-vetinari, LGTM. Will leave a couple of days incase something from the mailing list comes through

**Review by lucascolley — APPROVED** [review]
some non-blocking nits

**Comment by h-vetinari** [comment]
Got something yesterady, now fixed. Remaining failure is unrelated:
```
=========================== short test summary info ============================
FAILED scipy/io/tests/test_fortran.py::test_fortranfiles_mixed_record - DeprecationWarning: Passing in a parenthesized single number for repeats is deprecated; pass either a single number or indicate a tuple with a comma, like "(2,)".
= 1 failed, 45342 passed, 2356 skipped, 147 xfailed, 14 xpassed in 326.33s (0:05:26) =
```

PS. If someone else presses the button, please avoid squash merging this one.

**Pull request merged**
