### PR TITLE
MAINT: fix rdist methods in scipy.stats

### PR DESCRIPTION
**Pull request by chrisb83**
`rdist` does not have efficient _cdf, _ppf and _rvs method. Tests are therefore marked as slow.
This PR adds fast methods by using the methods of `stats.beta`.

Cross-ref #10106 and #1285

### CODE REVIEW

**Comment by chrisb83** [comment]
@WarrenWeckesser I implemented the methods for `rdist` as discussed. Feedback welcome.

I will look into the test failure, ppf-cdf-roundtrip fails in one case for the median value, that seems odd.

`x = array([0.001,   nan, 0.999]), y = array([0.001, 0.5  , 0.999])`

**Comment by chrisb83** [comment]
I cannot reproduce the error on Windows:
```
values = [0.001, 0.5, 0.999]
x = rdist.ppf(values, 0.9) # array([-9.99998722e-01,  8.88178420e-16,  9.99998722e-01])
rdist.cdf(x, 0.9) # array([0.001, 0.5  , 0.999])
```

**Comment by WarrenWeckesser** [comment]
I haven't had any luck getting the failed tests to re-run by clicking on the "re-run" links in https://github.com/scipy/scipy/pull/10118/checks, so I'm closing and reopening the pull request.

**Comment by WarrenWeckesser** [comment]
The test failures occur because `scipy.special.btdtri(0.45, 0.45, 0.5)` returns `nan` on those two platforms.  I just checked this in a pull request (https://github.com/scipy/scipy/pull/10174) that added a test of that result, and it caused the same two failures as this pull request. (There is a third failure in that test which is I assume is unrelated.  I don't see how simply adding a `special` test would cause problems in the qhull tests.)

Now the problem is to figure out why the result is `nan` on those platforms.

**Comment by ev-br** [comment]
Needs a rebase. Which, accidentally, might fix the CI falures?

**Comment by chrisb83** [comment]
> Needs a rebase. Which, accidentally, might fix the CI falures?

Unfortunately, there seems to be a bug in `scipy.special.btdtri`. I will create an issue, then one could mark the test as xfail / skip until the underlying issue is solved.

**Comment by chrisb83** [comment]
Related issue already exists: #7931

I noted that `scipy.stats.semicircular` is a special case of `rdist` (c=3). `semicircular` does not have a ppf method yet. Once one uses `btdtri`, the same issue will appear again

**Comment by chrisb83** [comment]
changing the Parameter of `rdist` from 0.9 to 1.6 avoids the failure...

**Comment by chrisb83** [comment]
@WarrenWeckesser Can you review this PR when you have time? Thanks!

**Comment by WarrenWeckesser** [comment]
@chrisb83, I'll get back to it this weekend.

**Comment by WarrenWeckesser** [comment]
@chrisb83, this looks good, thanks!  I made several minor formatting requests, actually all the same: put spaces around `+` in several places.

I'd also like to see a few changes related to the git commits. *Each* commit message should follow the commit style guidelines.  While you're fixing the commit messages, you can also squash any intermediate commits that were fixups of previous commits in the pull request.  Specifically, the commit "fix _logpdf" is just a correction to a previous commit, and we don't need to preserve that kind of churn in the commit history.  Whether or not you squash them all into a single commit, or leave a few independent commits, is your choice.  Whatever you do, be sure to explain any nontrival changes made in the commit in the commit message.  For example, at the start of this PR, you made the comment

    `rdist` does not have efficient _cdf, _ppf and _rvs method. Tests are therefore
    marked as slow.  This PR adds fast methods by using the methods of stats.beta.

A comment like that should also be in the *commit message* in which the relevant changes are made (but use the term "commit" instead of "PR" where necessary).

**Review by WarrenWeckesser — CHANGES_REQUESTED** [review]

**Comment by chrisb83** [comment]
@WarrenWeckesser Thanks, I added spaces around `+` and fixed the commit messages.

**Comment by chrisb83** [comment]
@WarrenWeckesser Hi Warren, do you think you can review the changes? Your comments should be addressed.

**Comment by WarrenWeckesser** [comment]
Thanks @chrisb83, merged.

**Pull request merged**
