### PR TITLE
CI: add a Windows CI job on GitHub Actions using Meson

### PR DESCRIPTION
**Pull request by rgommers**
[skip azp]

Co-authored-by: Matthew Brett <matthew.brett@gmail.com>

### CODE REVIEW

**Comment by rgommers** [comment]
Cc @matthew-brett FYI

After this PR is merged, we have all relevant CI jobs from my fork integrated. I'll still keep running against Meson master on my fork for a while, but we've not seen any regressions there. We use fairly standard features, aside from the Cython support which is pretty new, so I don't expect to catch many issues by doing those CI runs.

**Comment by rgommers** [comment]
Okay, this is happy now. We should merge it before upgrading HiGHS or other significant changes to vendored libraries.

**Review by tylerjereddy — APPROVED** [review]
Seems "ok" to me. A few parts seem a bit convoluted if I'm being honest, but I don't mind merging to protect the meson build on Windows.

Some longer-term questions I might have:
- do we really need a custom version of Python from `choco` instead of one provided by GHA by default?
- the `post-install` step is a bit gruesome maybe

**Comment by rgommers** [comment]
Thanks Tyler. Good questions, we can do some cleanup at some point, a few of the steps are too much broken up or may not be necessary.



> do we really need a custom version of Python from `choco` instead of one provided by GHA by default?

I don't think so. We do need Chocolatey anyway for `rtools` (compilers) here, so I didn't mind, but I don't think there's a reason we need it. @matthew-brett any thoughts on this?

> the `post-install` step is a bit gruesome maybe

That replicates what we do with wheels. Agreed it's not great and I'd like to get rid of it before 1.9.0

**Pull request merged**
