### PR TITLE
DOC: Update svds documentation

### PR DESCRIPTION
**Pull request by bartvm**
The docstring says that the order of the singular values is not guaranteed, but the code actually sorts the singular values in ascending order using `argsort`.

#### Reference issue
n/a 

#### What does this implement/fix?
Small inaccuracy in docstring. 

#### Additional information
n/a

### CODE REVIEW

**Comment by tupui** [comment]
Thanks @bartvm. It's correct that we sort, but not for PROPACK as we return earlier. Here is the relevant part. It's unclear reading this if it's guaranteed to be `largest first`. @mdhaber can you clarify here?
```python
        # PROPACK order appears to be largest first. `svds` output order is not
        # guaranteed, according to documentation, but for ARPACK and LOBPCG
        # they actually are ordered smallest to largest, so reverse for
        # consistency.
```

**Comment by mdhaber** [comment]
I don't know whether PROPACK guarantees the order. I just observed in testing that it appeared to be smallest to largest. Since we don't guarantee the output order, i didn't look into PROPACK documentation/code for an official answer. So reversing the order makes it consistent with the other solvers in every case I've seen, but i don't know whether it's guaranteed.

**Comment by mdhaber** [comment]
I defiantly noted this as something that should be guaranteed, but there were a lot of other fish to fry and i neglected to return to it. I would have either tracked the answer down in PROPACK or done a pass with a sorting algorithm that is O(N) when the order is already perfect.

**Comment by bartvm** [comment]
I had a quick look at PROPACK. The documentation for `_lansvd` and `_lansvd_irl` doesn't say anything about the order of the singular values but internally they call the subroutine `_bdsqr` (SVD of a bidiagonal matrix) whose documentation says `On exit, if INFO=0, the singular values of B in decreasing order.` AFAICT the order of the singular values is never changed after this call (the only other subroutine called on the workspace is `_refinebounds` which does not modify it). So I'm pretty sure the order is also guaranteed for PROPACK.

**Comment by mdhaber** [comment]
I looked a bit into the history here. 

- We decided [here](https://github.com/scipy/scipy/issues/9643#:~:text=commented-,on%20Jan%202%2C%202019,-I%27d%20much%20rather) to leave it alone.
- I think gh-10830 (2f8cd5e474cf22299d301c5c2708b4c1c7d74e37) added the explicit sorting.
- After that, gh-12627 also suggested that we should document the order, and actually suggested that we reverse the order before we do that. (It would not technically break compatibility against the documentation, but I'm guessing it would be disruptive.)

@perimosocordiae Do you still think we should not guarantee the order?

**Pull request closed without merging**
