### PR TITLE
FIX: Clean warnings

### PR DESCRIPTION
**Pull request by larsoner**
This fixes warnings for me on Py3k and Python2 @rgommers.

I do have 18 failures if I compile with MKL (even though `numpy` has no errors), are those to be expected?

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @Eric89GXL!

No failures are expected with MKL. Can you open a new issue for those?

**Comment by Eric89GXL** [comment]
Sure. I'm going to try updating my Parallel Studio / MKL libraries first (I think I'm using MKL from 2013), which means getting a new license from Intel. Hopefully that doesn't take too long.

**Comment by rgommers** [comment]
This looks good to me. A few very minor cleanups in https://github.com/rgommers/scipy/commit/4861385bd020c0222daa6ad499d688a976af406f, can you take those over?

The one warning that I'm not sure needs investigating or not is that in ``ellip_harm``. @pv what do you think?

**Comment by Eric89GXL** [comment]
@rgommers commit cherry-picked into my PR

**Comment by rgommers** [comment]
Okay, I'll put this in and open a new issue to not lose track of the potential issue with ``ellip_harm``. Thanks @Eric89GXL

**Comment by rgommers** [comment]
Pushed this PR to master in c1fa391

**Pull request merged**
