### PR TITLE
TST: speed up full test suite by less eval points in mpmath tests.

### PR DESCRIPTION
**Pull request by rgommers**
This will address the TravisCI timeouts we're experiencing.

Closes gh-6989.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, +1 for merge assuming Travis shows good improvement.

**Comment by pv** [comment]
Indentation error on line 146

**Comment by person142** [comment]
Probably too annoying to do, but in an ideal world we would have differing numbers of default points for functions of 1, 2, etc. variables. The issue being that 5000 points is probably overkill for a function of one real variable, but when you get to e.g. hypergeometric functions of 3 real variables and one complex variable it's not very many.

**Comment by rgommers** [comment]
Time of ``test('full')`` down to 40 min now. Just 2 failing tests, so have changed those to always use ``n=5000``:

    ======================================================================
    FAIL: test_mpmath.TestSystematic.test_hyp0f1
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/scipy/scipy/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/travis/build/scipy/scipy/venv/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
        return f(*args, **kwargs)
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/tests/test_mpmath.py", line 1341, in test_hyp0f1
        [Arg(-1e7, 1e7), Arg(0, 1e5)])
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 239, in assert_mpmath_equal
        d.check()
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 226, in check
        reraise(*sys.exc_info())
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 222, in check
        param_filter=self.param_filter)
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_testutils.py", line 119, in assert_func_equal
        fdata.check()
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_testutils.py", line 338, in check
        assert_(False, "\n".join(msg))
      File "/home/travis/build/scipy/scipy/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 92, in assert_
        raise AssertionError(smsg)
    AssertionError: 
    Max |adiff|: 1.34485e+292
    Max |rdiff|: 0.0440728
    Bad results (1 out of 378) for the following points (in output 0):
           -3.1622776601683793e-16                             1.0 =>            -4808347426889712.0 !=            -5030035390860123.0  (rdiff            0.04407284377625481)

    ======================================================================
    FAIL: test_mpmath.TestSystematic.test_rgamma
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/scipy/scipy/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/travis/build/scipy/scipy/venv/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
        return f(*args, **kwargs)
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/tests/test_mpmath.py", line 1739, in test_rgamma
        ignore_inf_sign=True)
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 239, in assert_mpmath_equal
        d.check()
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 226, in check
        reraise(*sys.exc_info())
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_mptestutils.py", line 222, in check
        param_filter=self.param_filter)
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_testutils.py", line 119, in assert_func_equal
        fdata.check()
      File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/special/_testutils.py", line 338, in check
        assert_(False, "\n".join(msg))
      File "/home/travis/build/scipy/scipy/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 92, in assert_
        raise AssertionError(smsg)
    AssertionError: 
    Max |adiff|: 2.28215e+289
    Max |rdiff|: 6.08258e-13
    Bad results (1 out of 502) for the following points (in output 0):
                           -1000.0 =>                            inf !=                            0.0  (rdiff                            0.0)

**Comment by rgommers** [comment]
This looked good, however still timed out (on build caching, tests were all finished). Restarting, will probably pass next time.

**Comment by rgommers** [comment]
TravisCI is having a bad day. https://travis-ci.org/scipy/scipy/jobs/244830974 is the only failure, and the tests have again completed but it's timed out on the final ``ccache`` step.

I suggest to just merge this PR. If it remains problematic we can try to speed up by tackling some other tests.

**Comment by Eric89GXL** [comment]
Good progress despite the timeout. Are you going to keep looking into speed gains?

**Comment by rgommers** [comment]
> Good progress despite the timeout. Are you going to keep looking into speed gains?

Depends on whether the timeouts go away soon. Otherwise we have little choice:(  Don't think that tweaking individual tests is the way to go then; best to split a test run in half in the build matrix.

**Pull request merged**
