### PR TITLE
ENH: sparse: avoid densifying on sparse/dense elementwise mult

### PR DESCRIPTION
**Pull request by perimosocordiae**
This is the long-awaited followup to #4133, which I lost track of and forgot about.

### CODE REVIEW

**Comment by argriffing** [comment]
Looks good to me.

**Comment by argriffing** [comment]
Should the unit tests check that the product is sparse? I checked this myself and it is true, but I'm not sure it is tested.

**Comment by perimosocordiae** [comment]
At least until numpy/numpy#6060 is merged, the tests will fail if the result is not sparse. Do you think a future-proof test of sparseness would help?

**Comment by argriffing** [comment]
> At least until numpy/numpy#6060 is merged, the tests will fail if the result is not sparse.

I guess it's good then.

> Do you think a future-proof test of sparseness would help?

My only worry was giving a +1 to a PR that lacks unit tests for its new features.

**Comment by larsmans** [comment]
Since this is a change of behavior in existing functionality, I think it should be listed in the release notes (`doc/release/0.17.0-notes.rst`).

**Comment by perimosocordiae** [comment]
@larsmans Done, though I forgot to add [ci skip] to the commit message, sorry!

**Comment by larsmans** [comment]
I just wanted to merge this, but it has a merge conflict. Would you rebase, please?

**Comment by perimosocordiae** [comment]
Rebased.

**Comment by larsmans** [comment]
Ok, tested this offline too. Sorry to have kept you waiting for so long.

**Comment by yoch** [comment]
This patch don't handle the (pretty common) case of multiplying sparse matrix by dense vector (or (1,N) and (N,1) dense matrices as well).

For instance, both `m.multiply(m.sum(0))` and `m.multiply(m.sum(0))` produce dense matrices.

I use this code snippet to do so : 

```python
# for sparse.matrix of (N,M) elements
m.data * v[m.indices]  # if v.shape == (M,) or v.shape == (1,M)
m.data * v[np.repeat(np.arange(0, len(m.indptr)-1), np.diff(m.indptr))] # if v.shape == (N,1)
```

**Comment by perimosocordiae** [comment]
@yoch Are you sure you're using a build with this PR included? On my machine, I get:

```
In [1]: m = scipy.sparse.rand(5, 4, density=0.5, format='csr')

In [2]: m.multiply(m.sum(axis=0))
Out[2]:
<5x4 sparse matrix of type '<type 'numpy.float64'>'
        with 10 stored elements in COOrdinate format>

In [3]: m.multiply(m.sum(axis=1))
Out[3]:
<5x4 sparse matrix of type '<type 'numpy.float64'>'
        with 10 stored elements in COOrdinate format>

In [4]: scipy.__version__
Out[4]: '0.19.0.dev0+549dead'
```

**Comment by yoch** [comment]
I use the 0.18.1 version, and got differents results.

```pycon
>>> import scipy.sparse
>>> m = scipy.sparse.rand(5, 4, density=0.5, format='csr')
>>> m.multiply(m.sum(axis=0))
matrix([[ 0.        ,  0.        ,  0.        ,  1.86535774],
        [ 1.81304656,  0.        ,  1.37334535,  0.        ],
        [ 1.20588342,  0.        ,  0.58686208,  1.61101565],
        [ 1.40392034,  0.09484932,  1.8872025 ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.7687906 ]])
>>> m.multiply(m.sum(axis=1))
matrix([[ 0.        ,  0.        ,  0.        ,  0.66338431],
        [ 1.34682281,  0.        ,  1.09382579,  0.        ],
        [ 0.90368124,  0.        ,  0.47153385,  1.10861637],
        [ 1.29351335,  0.59675584,  1.8642916 ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.5964771 ]])
>>> scipy.__version__
'0.18.1'
```

And in your case, I don't understand why COO format is returned ? In fact, we can keep CSR or CSC format  (and it's often very interesting).

**Comment by perimosocordiae** [comment]
Oops, I forgot that there was another PR that followed up on this one (gh-6750), which was only merged three days ago. That's the one that fixes this particular case.

COO format is returned because it was a convenient format for the internal operations required (see the above PR), and in general sparse matrix operations aren't guaranteed to preserve format. I agree that in this case it would be nice to preserve CSR/CSC format, but that'll have to be a separate change. For now, you can just call `.tocsr(copy=False)` on the result, which is usually a pretty cheap operation.

**Comment by yoch** [comment]
Okay, thank you for the explanation.

**Pull request merged**
