### PR TITLE
ENH/TST: Update Newton's method.

### PR DESCRIPTION
**Pull request by Chronum94**
Modified Newton's method by HHH Homeier. Converges cubically with two derivative evaluations per iteration. Useful for functions which are more or approximately as expensive to evaluate as their derivatives. https://www.sciencedirect.com/science/article/pii/S0377042703010215?via%3Dihub

### CODE REVIEW

**Comment by Chronum94** [comment]
A few zerodivision errors. I know what caused them, attempting a fix now.

**Comment by Chronum94** [comment]
Fixed the zerodiv errors. There's currently one failing test that looks for number of iterations to convergence.

FAIL scipy/optimize/tests/test_zeros.py::TestBasic::()::test_newton_full_output

This fails because the proposed method converges in 3 iterations instead of 5 (and in general faster, as expected). However, since the test looks very specifically for 5 iterations, fewer iterations causes it to fail.

**Comment by mikofski** [comment]
There is currently another PR (#8357) pending for newton method and another, #8803, which you mentioned, that was recently merged. I wonder how we can resolve all of the PR(s) so that there aren't too many conflicts?

**Comment by Chronum94** [comment]
The changes here (just an extra few lines if the second derivative is not provided) work with #8803, but #8357 appears to be much more nontrivial.], so I'm not sure how (in)convenient that would be.

**Comment by pvanmulbregt** [comment]
My reading of Homeier's paper suggests that it is a parametrizable family of algorithms, with iterations of
```
x  ->  x - f(x) / f'(x + a(x)*f(x))
```
the parametrization being the choice of `a(x))`.  
`a(x) == 0`  is the usual Newton-Raphson method, which provides locally quadratic convergence (per iteration).  If instead one uses `a(x)=-1/(2f'(x))`, then the convergence is locally cubic.
[I.e. the Mean Value Theorem => `f(b) = f(a) + (b-a)*f'(c)` for some `c` in the open interval `(a, b)`. Newton-Raphson approximates `f'(c)` with `f'(b)`, and Homier takes a half-size Newton step and uses  the derivative at that value.]

A few comments:
1. This PR is not backwards compatible, in that it will change results in existing code.  I'd suggest making it a separate function and then working to justify its inclusion based on its performance.
2. The method is locally cubically convergent when considering iteration count.  When considering function count, however the convergence rate is more like `3**(1/3) ~ 1.44`.  If the derivative evaluation is much less costly than a function evaluation, 1.44 is an underestimate of effective convergence rate. If derivatives cost as much as (or more than) a function, 1.44 may be an overestimate.
3. I tried it on 13 families of functions (see gh-8876) and didn't see any advantage to using this method over other methods.  On test cases where it did converge, it needed ~18.6 function evaluations per problem, about the same as Newton's method, and about 10% less than Halley's method. But this compared with 12-14 for the bracketing algorithms,`Brent`/`Ridder`/`toms748`. I suspect that the effectiveness of the Homeier method is not apparent until one is very close to the root and the higher order terms have little impact.

**Comment by Chronum94** [comment]
The examples in the paper (and the use cases I've found so far) for this method are in fact when the derivative is much easier to evaluate than the function itself. (such as when the 'function' is a numerically solved integral). I'll work on an implementation as a new method sometime soon. The feedback is really appreciated.

**Comment by pkofod** [comment]
> The examples in the paper (and the use cases I've found so far) for this method are in fact when the derivative is much easier to evaluate than the function itself. (such as when the function is a numerically solved definite integral and the derivative is just the integrand).

I think it'll be useful to simply show these examples and clearly document exactly what the use-case is.

**Pull request closed without merging**
