### PR TITLE
BUG: Fix root bracketing logic in Brent's method (issue #13737)

### LINKED ISSUE #13737: brentq can overflow / underflow
According to the source code:

https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brentq.c#L67

the brentq algorithm uses the product of two function values to see if the zero is in the bracketing interval.

In 

    Malcolm, Michael A., Cleve B. Moler, and George Elmer Forsythe. 
    Computer methods for mathematical computations. Prentice-Hall, 1977.

we see the following advice:

"Careful attention is paid to underflow and overflow problems. For example, the test to ensure that F(B) and F(C) have different signs is *not* the conventional:

F(B) * F(C) < 0.0

If F(B)=10^-40 and F(C)=10^-40, then they have opposite signs, but on many computers the product will underflow and be set to zero, and the test will fail."

### PR DESCRIPTION
**Pull request by rrsq**
The check, f(a)*f(b) < 0, to determine if the interval [a, b]
brackets a root, can fail when the product overflows/underflows.
The modified check is:
sgn(f(a))*sgn(f(b)) < 0, where sgn(x) denotes the sign of x.

Closes #13737

### CODE REVIEW

**Comment by charris** [comment]
Not the same if the search range is 0 to 0 . Note that float comparisons ignore the sign of zero.
```
In [1]: -0.0 * 0.0 < 0
Out[1]: False
```

**Comment by rrsq** [comment]
Thanks @charris 
Will fix the signed zero problem by adding a check like: fpre != 0 && fcur != 0 && (SIGN(fpre) != SIGN(fcur))

**Comment by rrsq** [comment]
Some full tests are succeeding (e.g. Main Linux_Python_37_32bit_full, while some others like (Main preprelease_deps_64bit_blas) are failing.  Any pointers as to the cause (i.e. is the code change breaking it) as I am not yet familiar with the various build pipelines here.

**Comment by rrsq** [comment]
> Some full tests are succeeding (e.g. Main Linux_Python_37_32bit_full, while some others like (Main preprelease_deps_64bit_blas) are failing. Any pointers as to the cause (i.e. is the code change breaking it) as I am not yet familiar with the various build pipelines here.

Seems to be related to this issue https://github.com/scipy/scipy/issues/14014

**Comment by tupui** [comment]
@charris Friendly reminder so we can proceed.

**Comment by tupui** [comment]
Merging as tests are passing and change is sensible. Thanks again @rrsq, feel free to go along with similar functions.

**Pull request merged**
