### PR TITLE
BLD: fix two `-Duse-g77-abi` regressions and a PROPACK bug

### LINKED ISSUE #18371: BUG: Missing symbol when used with reference LAPACK: cblas_cdotc_sub
I've been testing scipy against all the BLAS/LAPACK variants available in conda-forge for a [while](https://github.com/conda-forge/scipy-feedstock/pull/224), and though there are small issues here and there, generally things work everywhere.

Since scipy 1.10.1 (or some other change in the last 3 months), there's however now a kind of error I haven't seen before - a missing symbol (`cblas_cdotc_sub), but only for one BLAS/LAPACK flavour, namely the "netlib" one from https://github.com/Reference-LAPACK/lapack/.

#### This happens for linux on all arches (x64, aarch64, ppc64le), but not on osx/win.

Since this is causing an error directly upon import (rather than a small handful of failed tests), this has a much bigger blast radius.

```
import: 'scipy.cluster'
Traceback (most recent call last):
  [...]
    from . import _iterative
ImportError: $PREFIX/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/_iterative.cpython-310-x86_64-linux-gnu.so: undefined symbol: cblas_cdotc_sub
```

Apparently this is encountered in the wild already: https://github.com/python-control/Slycot/pull/194

### PR DESCRIPTION
**Pull request by rgommers**
The first was caused by gh-18264 and caused a build issue, the second was a missing CBLAS issue when building against Netlib BLAS with this combination of flags (two examples, both reproduce the problem):

    python -m build -nwx -C-Dblas=blas -C-Dlapack=lapack -C-Duse-g77-abi=true
    python dev.py build -C-Dblas=blas -C-Dlapack=lapack -C-Duse-g77-abi=true

Closes gh-18371

### CODE REVIEW

**Comment by h-vetinari** [comment]
Great news! So to fix this on 1.10 in conda-forge (current release broken with netlib), which commits/PRs should I backport? I tried to pick https://github.com/scipy/scipy/pull/18264 onto 1.10.1, but that failed; haven't investigated further

**Comment by ilayn** [comment]
Looks good to me. Hopefully we will not need any of this CBLAS/CLAPACK at some point.

**Review by ilayn — APPROVED** [review]

**Comment by h-vetinari** [comment]
> squash the one commit in this PR together with the commits from [gh-18264](https://github.com/scipy/scipy/pull/18264). If that turns out to be hairy for some reason, I think you can also take only the `meson.build` changes in this PR and leave all the rest alone.

The conflicts weren't _too_ bad. I hope I got everything correctly 🤞 

Pushed a for testing to https://github.com/conda-forge/scipy-feedstock/pull/224, if it passes, I'll open a PR to (feedstock-)main.

**Comment by h-vetinari** [comment]
This worked, great job!

**Comment by h-vetinari** [comment]
FYI, while this is a clear improvement, I found something surprising while looking a bit closer at the results of the CI run with distutils in https://github.com/conda-forge/scipy-feedstock/pull/224 after encountering some discrepancies in https://github.com/conda-forge/scipy-feedstock/pull/200.

Even with all the backports from https://github.com/conda-forge/scipy-feedstock/pull/233, we had the following failures with meson (for the first 1.10.1 [update](https://github.com/conda-forge/scipy-feedstock/pull/224#issuecomment-1521174029)), which are not there when using distutils, _but only on OSX+MKL_:
```
=========================== short test summary info ============================
FAILED sparse/linalg/tests/test_propack.py::test_examples[False-complex64]
FAILED sparse/linalg/tests/test_propack.py::test_examples[True-complex64]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex128-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex128-csc_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex128-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex64-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-False-complex64-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex128-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex128-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex64-array]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex64-csc_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[LM-True-complex64-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex128-csr_matrix]
FAILED sparse/linalg/tests/test_propack.py::test_svdp[SM-True-complex64-array]
= 14 failed, 50135 passed, 2304 skipped, 253 xfailed, 11 xpassed, 265 warnings in 1244.19s (0:20:44) =
```

To make things even more confusing, these errors are _not_ present on PyPy (whether using distutils _or_ meson), and there's a wildly diverging hodgepodge of error behaviours (possibly random per CI run) after having backported this patch. I'm still preparing that update.

**Comment by h-vetinari** [comment]
> there's a wildly diverging hodgepodge of error behaviours (possibly random per CI run) after having backported this patch. I'm still preparing that update.

Finished that now, and I cannot wrap my head around it. While the situation before backporting the patches was weird, it was at least stable along the lines of CPython/PyPy resp. meson/distutils. Now we get wildly varying failures (though out of a fixed set!) per Python version & implementation, though somehow, despite huge build differences, OSX+MKL has effectively the exact same failure surface as windows + all other BLAS implementations.

**Comment by h-vetinari** [comment]
> While the situation before backporting the patches was weird, it was at least stable along the lines of CPython/PyPy resp. meson/distutils.

While it doesn't elucidate the full situation, I have at least been able to rule out that this is unrelated to the patches; it's entirely due to switching back on PROPACK, which therefore somehow causes a _reduction_ of some of the failures seen on OSX+MKL+meson+CPython.

**Comment by h-vetinari** [comment]
As a final point, I'm now trying to enable these backported patches also on windows. While I _think_ the CI here should still ensure a working distutils build on windows, I wanted to make sure things remain buildable. It possible that this will need some further patches. Failure looks pretty straightforward:
```
%SRC_DIR%\scipy\_build_utils\src\npy_cblas.h(9): fatal error C1083: Cannot open include file: 'numpy/npy_common.h': No such file or directory
```

**Comment by h-vetinari** [comment]
> Failure looks pretty straightforward:

OK, this is obviously related to 8bb7733395a98528974de22fed3c6e770f545784, but it's weird because we do `#include <numpy/npy_common.h>` all over the place. The first assumption would then be that it's somehow related to `wrap_g77_abi_c`, however I cannot find recent (non-meson) changes related to that, so then perhaps the statement from that commit
> This is necessary, because it uses `npy_int64` & co. The implicit
assumption previously was that this was made available in the
file that included `npy_cblas.h`, but this wasn't guaranteed in
any way. This is why the build failed after removing a
`from numpy.math cimport` line in `_ellip_harm.pxd`.

ends up not being true on windows? 🤔

**Comment by rgommers** [comment]
I'm not interested in the PROPACK failures here, because PROPACK is still known to be broken in ways that cause exactly these random bugs. It's disabled for a reason - it needs more work, which is in the pipeline. Please don't burn too much time on PROPACK right now I'd say.

> `Cannot open include file: 'numpy/npy_common.h'` (on Windows/distutils)

This one I do want to fix, should be easy. ~It's puzzling though, because I am explicitly adding the numpy include directory the `g77_abi_wrappers` right in this PR. The `cl.exe` line doesn't show the full compile/link flags.~ Ah that is the problem, I am only updating the Meson build here, I simply need to make the corresponding change in `setup.py`.

**Comment by h-vetinari** [comment]
> Please don't burn too much time on PROPACK right now I'd say.

That's fair, though I was interested because CI with PROPACK passed in [January](https://github.com/conda-forge/scipy-feedstock/pull/200#issuecomment-1406488151) (before https://github.com/conda-forge/scipy-feedstock/pull/231) was merged, so I wanted to check the status now that we fixed a couple of issues in the meantime, if only to find out what's delta might still exist between distutils/meson.

**Comment by h-vetinari** [comment]
> so I wanted to check the status now that we fixed a couple of issues in the meantime, if only to find out what's delta might still exist between distutils/meson.

... and indeed, the propack tests on OSX+MKL pass when built with distutils (and no patches) on top of 1.10.1.

**Comment by h-vetinari** [comment]
I picked the two extra commits into https://github.com/conda-forge/scipy-feedstock/pull/234, and it's still not enough, because the old `bld.bat` does a [bare](https://github.com/conda-forge/scipy-feedstock/blame/main/recipe/bld.bat#L20-L21) compilation of `wrap_g77_abi_c.c `
```
cl.exe scipy\_build_utils\src\wrap_g77_abi_c.c -c /MD
```
which now requires the numpy include folder AFAICT. Not that this needs to be changed here, but just FYI. I'll try to add the numpy headers there and see how it goes.

Sidenote: there's a TODO comment from the original MSVC+gfortran integration just above:
```
TODO: rewrite wrap_g77_abi.f with iso_c_binding when the compiler supports it
```

Not sure what that's referring to, but I thought I mention it.

**Comment by h-vetinari** [comment]
> I'll try to add the numpy headers there and see how it goes.

Should be fixed in https://github.com/conda-forge/scipy-feedstock/pull/234 now, CI is still running, but past the previous failure.

**Comment by rgommers** [comment]
Okay, this was approved and confirmed to work in conda-forge. So I'll get this in, since the current state of `main` is broken with `-Duse-g77-abi`.

**Pull request merged**
