### PR TITLE
Explain where LIL comes from

### PR DESCRIPTION
**Pull request by stefanv**
Happy to move this to the notes section or elsewhere, if that seems better. But an explanation helps understand the LIL short form, now that the repr has been changed by @AnirudhDagar.

### CODE REVIEW

**Review by jarrodmillman — APPROVED** [review]

**Review by AnirudhDagar — COMMENTED** [review]
Thanks for adding the explanation here, should make the origin quite clear. LGTM!

**Comment by stefanv** [comment]
Thanks for taking a look, @AnirudhDagar!

**Review by tupui — APPROVED** [review]

**Comment by tupui** [comment]
Thanks Stéfan :)

**Comment by perimosocordiae** [comment]
I see this has already been merged, but unfortunately I think it's not correct. The LIL abbreviation stands for "LIst of Lists", not "LInked List".

Citations:
 1. https://scipy-lectures.org/advanced/scipy_sparse/lil_matrix.html
 2. https://phys.libretexts.org/Bookshelves/Mathematical_Physics_and_Pedagogy/Computational_Physics_(Chong)/08%3A_Sparse_Matrices/8.02%3A_Sparse_Matrix_Formats
 3. https://en.wikipedia.org/wiki/Sparse_matrix#List_of_lists_(LIL)

I did find one reference that uses "linked list" language (https://imada.sdu.dk/~marco/DM559/Resources/Ipython/Sparse.html) but it's not authoritative.

**Comment by stefanv** [comment]
@perimosocordiae No problem if that's wrong, I'll fix it up! The naming is weird. You'd think List Of List would be abbreviated `lol_matrix` (although perhaps it's clear why that wasn't chosen :smile:).

The earliest commit I could find is this one: https://github.com/scipy/scipy-svn/commit/b3827deddd0c1a25986c802b91a4f7d359830ebc

It contains the following:

```
# Linked list matrix, by Ed Schofield -- report bugs to him!
# This contains a list (self.rows) of rows, each of which is a sorted list of
# column indices of non-zero elements; and a list (self.vals) of lists of these
# elements.
class lil_matrix(spmatrix):
    def __init__(self, A=None, shape=None, dtype='d'):
        """ Create a new list-of-lists sparse matrix.  An optional
        argument A is accepted, which initializes the lil_matrix with it.
        This can be a tuple of dimensions (M, N) or a (dense)
        array/matrix to copy.
        """
```

So, looks like there was some confusion from the start.

**Comment by stefanv** [comment]
Next commit of relevance: https://github.com/scipy/scipy-svn/commit/39730dc5482dad6f92dc8751e2048c0f27b64580

**Comment by stefanv** [comment]
Anyway, it's clear that a linked list representation isn't what was intended here, otherwise how would you access, say, row 4 directly.  I'll make another PR to fix the description.

**Comment by stefanv** [comment]
Please see https://github.com/scipy/scipy/pull/17027

**Pull request merged**
