### PR TITLE
MAINT: fix circular import after moving functions out of misc

### PR DESCRIPTION
**Pull request by rgommers**
``import scipy.special`` will fail on master right now.

### CODE REVIEW

**Comment by ev-br** [comment]
Ouch!
Thanks Ralf, am merging it right away.

Going forward I wonder if we can somehow test these things. Just running `$ python runtests` did not catch it either locally or on CI (is nose importing things differently?).

**Comment by pv** [comment]
That it's not caught by `runtests` is surprising as it does 
`__import__('scipy.special')`

**Comment by ev-br** [comment]
https://travis-ci.org/scipy/scipy/builds/175999973 is all green

Trying to replicate it locally:

```
(scipy_py27)br@duneyrr:~/repos/scipy$ git co 29c715d4d53e4e45d86e5864c69d034c5bf3a5fb
Note: checking out '29c715d4d53e4e45d86e5864c69d034c5bf3a5fb'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 29c715d... Merge pull request #6759 from ev-br/move_logsumexp
(scipy_py27)br@duneyrr:~/repos/scipy$ git clean -xdf
(scipy_py27)br@duneyrr:~/repos/scipy$ python setup.py build
... <snip> ...
(scipy_py27)br@duneyrr:~/repos/scipy$ python runtests.py
... <snip> ...
======================================================================
FAIL: test_datetime_missing (test_arffread.DateAttributeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/br/repos/scipy/build/testenv/lib/python2.7/site-packages/scipy/io/arff/tests/test_arffread.py", line 243, in test_datetime_missing
    assert_array_equal(self.data["attr_datetime_missing"], expected)
  File "/home/br/virtualenvs/scipy_py27/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 787, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/br/virtualenvs/scipy_py27/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 33.3333333333%)
 x: array(['NaT', '2004-12-02T02:59+0300', 'NaT', 'NaT',
       '2013-11-30T08:55+0400', '1631-10-15T20:04Z'], dtype='datetime64[m]')
 y: array(['NaT', '2004-12-01T23:59+0300', 'NaT', 'NaT',
       '2013-11-30T04:55+0400', '1631-10-15T20:04Z'], dtype='datetime64[m]')

----------------------------------------------------------------------
Ran 23801 tests in 436.321s

FAILED (KNOWNFAIL=83, SKIP=1823, failures=1)
```

The failure is unrelated, and I'm seeing it for a while. Apart from it, tests seem to pass. However,
```
(scipy_py27)br@duneyrr:~/repos/scipy$ python runtests.py -s special
Building, see build.log...
Build OK
Cannot run tests for scipy.special ('module' object has no attribute 'special')
```

**Comment by rgommers** [comment]
Not sure it's worth the effort, but if we would want to catch this kind of thing then we'd need a CI matrix entry that imports all public submodules separately, in separate subprocesses.

**Comment by pv** [comment]
Then the explanation probably is that `scipy.test()` silently passes if 
submodules fail to import. So not related to runtests.py directly.

**Comment by rgommers** [comment]
> Then the explanation probably is that `scipy.test()` silently passes if submodules fail to import. 

I'm pretty sure that that is not the case - you will get test errors.

> So not related to runtests.py directly.

Indeed, it's not. It's just about import ordering. When you have a circle ``C -> B -> A -> C`` that gives an import error on ``import C``, you may not get that same import error for ``import A; import B; import C``.

**Comment by pv** [comment]
You don't get test errors from `import scipy; scipy.test()` because the 
import succeeds if scipy.misc comes first --- it depends on which order 
Nose imports the submodules.
.
Before this fix, I get:
.
`python -c 'import scipy; scipy.test()'` -> success!
`python -c 'import scipy.special'` -> ImportError
`python -c 'import scipy.misc, scipy.special'` -> success!
.
There's no difference between runtests.py and `import scipy; 
scipy.test("fast")` because the former just does the latter (after 
setting up sys.path correctly).

**Comment by pv** [comment]
Rather than adding a separate CI entry, it would probably be better to 
run the import commands in the same travis-ci entry --- to avoid the 
need for rebuild --- or maybe add a test that runs 'python -c 'import 
scipy.submodule' for all submodules.

**Comment by rgommers** [comment]
added test in gh-6796

**Pull request merged**
