### PR TITLE
MAINT: remove `NPY_INLINE`, use `inline` instead

### PR DESCRIPTION
**Pull request by rgommers**
xref https://github.com/numpy/numpy/issues/22100

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
LGTM and the NumPy folks seem in favor as well. The only thing that didn't seem obvious was the `M_PI64` substitutions, I guess that's our internal thing.

Unrelated CI failures from https://github.com/scipy/scipy/issues/14517 apparently

**Comment by rgommers** [comment]
> The only thing that didn't seem obvious was the `M_PI64` substitutions, I guess that's our internal thing.

Indeed, see commit 8250f96b8a0 for context of why that exists. It's higher-precision than `M_PI`, so this was the easiest solution, rather than add `_USE_MATH_DEFINES`.

**Comment by WarrenWeckesser** [comment]
>  It's higher-precision than M_PI...

Actually, it isn't higher precision.  `M_PI64` is precisely the  double precision (i.e. 64 bit floating point) approximation to π.  The lesson learned in https://github.com/scipy/scipy/commit/8250f96b8a09290bcaeeefa437d71451a5d7b6d0 was that if a literal such as `3.14159265358979323846264` (as `M_PI` might be defined) is used in an expression, the compiler might use extended precision (80 bits) in intermediate calculations before assigning the result of the expression to a `double` variable.  Normally, that would be fine--who doesn't want a little incidental extra precision?  But that broke the calculation in
https://github.com/scipy/scipy/blob/eee13eb0dca36c185b4335ac5834872b1f614ddb/scipy/special/_cosine.c#L101
which depends on the literal representation of π being exactly the 64 bit approximation.

I think it is fine to use `M_PI64` elsewhere, but that specific value is only *needed* in that one line.  The other uses of `M_PI64` could be replaced/reverted to `M_PI`, if the additional definitions or `#include`s are added that ensure that `M_PI` is defined, since it is not standard.

**Comment by WarrenWeckesser** [comment]
By the way: thanks, @rgommers, for fixing the bug that I introduced in https://github.com/scipy/scipy/commit/8250f96b8a09290bcaeeefa437d71451a5d7b6d0 when I left `M_PI` undefined.  I guess it continued to work because on all the CI jobs, with the various compilers that we use and the existing NumPy/SciPy `#include`s, we ended up with a definition of `M_PI`, even though nothing guaranteed that it would be defined.

**Comment by rgommers** [comment]
Thanks for the extra details @WarrenWeckesser.

> The other uses of `M_PI64` could be replaced/reverted to `M_PI`, if the additional definitions or `#include`s are added that ensure that `M_PI` is defined, since it is not standard.

As you point out in your second comment, this may have been broken before (or not, hard to tell when header order matters so much and we don't use MSVC in CI anymore). So I considered it, and chose to add `64` rather than add extra defines in `meson.build` and `setup.py` - just easier. So my preference would be to leave it as is.

**Pull request merged**
