### PR TITLE
MAINT: linalg: Don't use variables 'I' or 'l'.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Grumble... `pep8` doesn't like multiple spaces after a comma, but it is natural to align the columns of a multiline array like I did in `test_special_matrices.py`:

```
        assert_array_equal(y, [[1,  1,  1,  1],
                               [1, -1,  1, -1],
                               [1,  1, -1, -1],
                               [1, -1, -1,  1]])
```
I'll try adding `# noqa` after each of those lines.

**Comment by WarrenWeckesser** [comment]
Sigh.  `pep8` wins; readability loses. 😞

**Comment by larsoner** [comment]
You could do `[+1, ...]` but I'm not sure if it will make it more readable.

**Comment by WarrenWeckesser** [comment]
I looked into it a bit more.  By default, `pep8` (now `pycodestyle`) does not warn about extra spaces after commas, precisely because it is common to align columns like I wanted to.  We override the default, and we don't include E241 in the list of warnings to ignore.  Also, E241 is not one of warnings that can be marked inline with `# noqa`, so you can't disable it for specific lines in the code.

**Comment by larsoner** [comment]
I imagine there are a lot of places where use or would like to use this pattern, so +1 for adding E241 to the ignore list.

**Comment by WarrenWeckesser** [comment]
I removed the commit with the big PEP 8 clean up in `test_decomp.py`.  That can wait for another time.

**Pull request merged**
