### PR TITLE
MAINT: Backports / updates for 1.2.2 (LTS)

### PR DESCRIPTION
**Pull request by tylerjereddy**
These are updates in preparation for SciPy `1.2.2`, which is part of our long-term support (LTS) release that covers Python 2.7. Let me know if you see any issues/ omissions--much easier to fix now than later in the process.

* the updates to the release notes here should provide a summary of the new backported PRs / issues solved--remember that the resolution for #10132 was accidentally merged to the maintenance branch, so that's not included here, but is added to release notes here
* other updates to `1.2.x` maintenance branch CI are for usage of OpenBLAS `0.3.7.dev`, despite the [deceptive file names](https://github.com/MacPython/openblas-libs/issues/4); the justification is in the release notes and [confirmation of `1.2.1` OpenBLAS issue on SkylakeX AVX 512 kernel](https://github.com/numpy/numpy/issues/13401#issuecomment-486690487) was previously provided along with [demonstrated reproduction in master branch CI](https://github.com/scipy/scipy/pull/10145)

### CODE REVIEW

**Comment by tylerjereddy** [comment]
I don't know if we'll want to touch PyPy3 CI here...

I'll be pleasantly surprised if that's the only problem though!

**Comment by tylerjereddy** [comment]
I've succeeded in debugging some of the issues on my fork (to avoid CI noise here), but the Python 2.7 + Windows on Azure case looks like a real problem with distutils in NumPy 1.16.4, so I will report that over there to confirm.

**Comment by tylerjereddy** [comment]
Actually, scratch that--I think the problem is that we still have the code to replace NumPy distutils with a copy from NumPy master on this maintenance branch because of some other unrelated issue, which probably doesn't matter here since Azure is just using unpinned NumPy wheels that are easily new enough.

I think we have to get rid of that so we can use the backport Python 2.7 adjustment from @charris here: https://github.com/numpy/numpy/pull/13072#issuecomment-468930861 rather than overwriting it with non-2.7 compliant NumPy master distutils.

I suspect we can't expect NumPy master to remain 2.7 compatible at this stage. If 1.17 gets released before we're done making changes to this branch, we'd likely have to pin the NumPy version in pip installs here too, but I'm currently just suggesting we get rid of "Replace NumPy distutils" Azure stage.

**Comment by rgommers** [comment]
> but I'm currently just suggesting we get rid of "Replace NumPy distutils" Azure stage.

Pretty sure we can't do that, we need the `system_info` changes for NumPy < 1.15.

Also I don't see the relation yet. We only override `system_info` and the patch you're linking to is in `misc_util`. 

The issues on the one TravisCI failures are like:
```
E   ImportError: dlopen(/Users/travis/build/scipy/scipy/build/testenv/lib/python3.7/site-packages/scipy/spatial/qhull.cpython-37m-darwin.so, 2): Library not loaded: /Users/travis/build/scipy/scipy/openblas/usr/local/lib/libopenblasp-r0.3.0.dev.dylib
E     Referenced from: /Users/travis/build/scipy/scipy/build/testenv/lib/python3.7/site-packages/scipy/spatial/qhull.cpython-37m-darwin.so
E     Reason: image not found
_ ERROR collecting build/testenv/lib/python3.7/site-packages/scipy/cluster/tests/test_vq.py _
ImportError while importing test module '/Users/travis/build/scipy/scipy/build/testenv/lib/python3.7/site-packages/scipy/cluster/tests/test_vq.py'.
Hint: make sure your test modules/packages have valid Python names.
```

That does not look similar to the `numpy.distutils` issue you linked to. Can you explain in more detail what you think is going on?

**Comment by tylerjereddy** [comment]
That failure is because we need to adjust the mingw version to provide the requisite gcc toolchain libraries at runtime when bumping OpenBLAS version. This already happened in master in #9774, and you suggested not backporting, but we really have to now & and I've already confirmed that fix on my fork.

> Pretty sure we can't do that, we need the system_info changes for NumPy < 1.15.

NumPy 1.15 isn't used anywhere in Azure CI. Even if it were, we'd still have to pin the distutils version we pull in to the 1.16.x series. The traceback for Python 2.7 Windows on Azure here is clear:

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\vssadm~1\appdata\local\temp\pip-req-build-rp9lws\setup.py", line 492, in <module>
      setup_package()
    File "c:\users\vssadm~1\appdata\local\temp\pip-req-build-rp9lws\setup.py", line 468, in setup_package
      from numpy.distutils.core import setup
    File "c:\hostedtoolcache\windows\python\2.7.16\x64\lib\site-packages\numpy\distutils\__init__.py", line 6, in <module>
      from . import ccompiler
    File "c:\hostedtoolcache\windows\python\2.7.16\x64\lib\site-packages\numpy\distutils\ccompiler.py", line 18, in <module>
      from numpy.distutils import log
    File "c:\hostedtoolcache\windows\python\2.7.16\x64\lib\site-packages\numpy\distutils\log.py", line 10, in <module>
      from .misc_util import (red_text, default_text, cyan_text, green_text,
    File "c:\hostedtoolcache\windows\python\2.7.16\x64\lib\site-packages\numpy\distutils\misc_util.py", line 1840
      m = re.match(rb'(?P<revision>\d+)', output)
  SyntaxError: invalid syntax
  Building wheel for scipy (setup.py): finished with status 'error'
  ERROR: Failed building wheel for scipy
```

Chuck swapped `rb` to `br` in the backport for Python 2.7, but not on master.

**Comment by tylerjereddy** [comment]
@andyfaff 

`TestDifferentialEvolutionSolver.test_parallel` is [failing on Python 2.7 Windows in CI](https://github.com/tylerjereddy/scipy/pull/23), almost certainly because of #9749 backport included here.

```
________________ TestDifferentialEvolutionSolver.test_parallel ________________
[gw0] win32 -- Python 2.7.16 C:\hostedtoolcache\windows\Python\2.7.16\x64\python.exe

self = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0x000000000E3C1668>

    def test_parallel(self):
        # smoke test for parallelisation with deferred updating
        bounds = [(0., 2.), (0., 2.)]
>       with multiprocessing.Pool(2) as p, DifferentialEvolutionSolver(rosen, bounds,
             updating='deferred', workers=p.map) as solver:
E            AttributeError: __exit__

bounds     = [(0.0, 2.0), (0.0, 2.0)]
self       = <scipy.optimize.tests.test__differential_evolution.TestDifferentialEvolutionSolver object at 0x000000000E3C1668>

C:\hostedtoolcache\windows\Python\2.7.16\x64\lib\site-packages\scipy\optimize\tests\test__differential_evolution.py:532: AttributeError
```

Suggestions?

**Comment by andyfaff** [comment]
@tylerjereddy I know what the problem is. With 2.7 `multiprocessing.Pool` can't be used as a context manager, so it doesn't have an `__exit__` method. The fix for this would be to amend `test_parallel ` accordingly. I would say it would be sufficient to remove the test.

**Comment by andyfaff** [comment]
```
         try:
            p = multiprocessing.Pool(2)
            with DifferentialEvolutionSolver(rosen, bounds,
                                             updating='deferred',
                                             workers=p.map) as solver:
                assert_(solver._mapwrapper.pool is not None)
                assert_(solver._updating == 'deferred')
                solver.solve()
        finally:
            p.close()
```
should work.

**Comment by tylerjereddy** [comment]
@andyfaff Thanks, I've pushed that patch in after checking locally on 2.7 & 3.6.

**Comment by tylerjereddy** [comment]
CI is all green now -- I'll let this "simmer" overnight given the number of adjustments / interventions needed, though most were just CI infrastructure things because of OpenBLAS bump & NumPy master moving on from 2.7.

**Comment by tylerjereddy** [comment]
Alright, putting this in the maintenance branch given all green CI & no further objections.

Hopefully there won't be any more surprises when I start dealing with the updated LTS wheel builds.

**Pull request merged**
