### PR TITLE
Optimize loggers

### PR DESCRIPTION
**Pull request by ryanpeach**
This is a feature I have been needing for my minimization functions, given that they are so slow I want to capture all their data and receive real-time updates on it's step-by-step process. I have, to that effect, added the option to put logger objects instead of an int or bool as the optional 'disp' parameter in each function of this file which had one previously. I have created a message function that chooses the best way to present the message to the user, in a consistent and backwards-compatible way. I have added comments to the documentation of each function. Right now, _message calls just replace anything that would have previously been printed, including error raises. Also, in _minimize_neldermead I have added my own custom logs anytime a function call occurs to present the results and their effect on the regression in real-time, varying debug levels depending on the level of detail you want. All in all, I'm happy with it, and would appreciate it's testing by the community, some more messages to be added in other functions, and it's eventual adoption.

### CODE REVIEW

**Comment by josef-pkt** [comment]
What's the overhead and what are the consequences for multiprocessing?
No idea about the second but aren't loggers global?

Looks pretty invasive based on a quick look, given that we use those optimizers heavily, without logging.  There is also the callback option in some optimizers, AFAIK.

**Comment by ryanpeach** [comment]
I have used logger objects in multiprocessing before. Of course, if you don't pass it a logger, there is no issue, but if you do then I don't believe there is a problem.

**Comment by ryanpeach** [comment]
I doubt it will have a considerable overhead, again especially if you don't use it. _message handles it all, so if we optimize it a bit then it should be simple.

**Comment by ryanpeach** [comment]
I haven't had the opportunity to test it large scale on my optimizer, so give me the rest of the day to get it down pat. Idk if there are any tests we can run for time, if there aren't I can make some too.

**Comment by ryanpeach** [comment]
Can you explain the callback a bit? I was confused by that in the code.

**Comment by josef-pkt** [comment]
I'm just a user. I know we use a callback to check for a special case that doesn't have a solution with finite parameters during optimization in statsmodels. But I never looked at the details.
eg. a quick google search
http://stackoverflow.com/questions/16739065/how-to-display-progress-of-scipy-optimize-function

AFAIK the callback provides some basic information after each iteration.

**Comment by ryanpeach** [comment]
Hmm, I'll rethink it for a bit, mine was so slow it never gave me any info at all after hours, so I just made this to give me more step by step data.

**Comment by ryanpeach** [comment]
That is very helpful, I had no idea it existed. Thank you very much! Still, some need for this in the time between iterations for very slow objective functions though. But I will see if maybe I can start over and use a more minimalist approach now.

**Comment by tacaswell** [comment]
attn @newville

**Comment by josef-pkt** [comment]
scipy optimizers look slow, maybe
https://juliaeconomics.com/2014/06/19/revisited-julia-vs-python-speed-comparison-bootstrapping-the-ols-mle/
I played for some time with his example but none of the changes made it more than a little bit faster.
My general opinion or experience is that algorithmic differences are in most cases more important, there are seldom exactly identical algorithms implemented.

The main usecase I would worry about speed is for cheap optimization problems with good starting values that we need to run very often as in bootstrap, and we want to run them on multiple processors if possible.
statsmodels is also using `joblib` in some cases like this for mutliprocessing.

**Comment by newville** [comment]
I would think that the existing per-iteration callback mechanism is sufficient for this sort of logging.   If not, maybe changing them so that they are sufficient is preferred.

**Comment by ryanpeach** [comment]
I was dumb guys, you can just put the logger in your objective function... Now it's so obvious its embarrassing haha.

**Pull request closed without merging**
