### PR TITLE
BUG: correct the test loop in test_arpack.eval_evec

### PR DESCRIPTION
**Pull request by dimpase**
In scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py, eval_evec
one tests for correctness eigenpairs, in a loop,
which is meant to allow for an error (the
`k`-tuple of eigenpairs found differs from what's asked by `which`
argument) in Krylov subspaces method. Cf. comments there:

    # on rare occasions, ARPACK routines return results that are proper
    # eigenvalues and -vectors, but not necessarily the ones requested in
    # the parameter which. This is inherent to the Krylov methods, and
    # should not be treated as a failure. If such a rare situation
    # occurs, the calculation is tried again (but at most a few times).

One should 1st check whether one got correct eigenvalues, and try again
if they are not the wanted ones.
The current implementation does it backwards: it checks whether
the eigenpair works, without 1st checking for eigenvalues.

This commit corrects this programming error.

#### Reference issue
Requested by @rgommers  in review of gh-14786

#### Additional information
https://github.com/scipy/scipy/pull/14786#issuecomment-932793440

### CODE REVIEW

**Comment by dimpase** [comment]
ok, a test in GitHub Actions fails in the changed function on Linux Python 3.8:
```
_____________________________ test_hermitian_modes _____________________________
[gw1] linux -- Python 3.8.0 /usr/bin/python3.8-dbg
scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py:421: in test_hermitian_modes
    eval_evec(symmetric, D, typ, k, which,
        D          = <gen-hermitian-Mc>
        k          = 2
        mattype    = <built-in function asarray>
        params     = <scipy.sparse.linalg.eigen.arpack.tests.test_arpack.SymmetricParams object at 0x7fd8a0dcf500>
        sigma      = None
        symmetric  = True
        typ        = 'F'
        which      = 'LA'
scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py:271: in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
E   AssertionError: 
E   Not equal to tolerance rtol=0.000357628, atol=0.000357628
E   error for eigsh:general, typ=F, which=LA, sigma=None, mattype=asarray, OPpart=None, mode=normal
E   Mismatched elements: 1 / 12 (8.33%)
E   Max absolute difference: 0.00344393
E   Max relative difference: 0.00106749
...
```
and a  different failure on Nightly CPython
```
_____________________________ test_hermitian_modes _____________________________
scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py:421: in test_hermitian_modes
    eval_evec(symmetric, D, typ, k, which,
        D          = <gen-hermitian-Mc>
        k          = 2
        mattype    = <class 'scipy.sparse.csr.csr_matrix'>
        params     = <scipy.sparse.linalg.eigen.arpack.tests.test_arpack.SymmetricParams object at 0x7f0e211f24a0>
        sigma      = None
        symmetric  = True
        typ        = 'D'
        which      = 'LM'
scipy/sparse/linalg/eigen/arpack/tests/test_arpack.py:271: in eval_evec
    assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
E   AssertionError: 
E   Not equal to tolerance rtol=4.44089e-13, atol=4.44089e-13
E   error for eigsh:general, typ=D, which=LM, sigma=None, mattype=csr_matrix, OPpart=None, mode=normal
E   Mismatched elements: 1 / 12 (8.33%)
E   Max absolute difference: 3.6483776e-12
E   Max relative difference: 9.24609212e-13
...
```

**Comment by rgommers** [comment]
The new failures are not from reversing the checks right, but from this piece of code have the wrong indentation for `assert_allclose(...)` so it's not run at all for `general` is True?
```python
        LHS = np.dot(a, evec)
        if general:
            RHS = eigenvalues * np.dot(b, evec)
        else:
            RHS = eigenvalues * evec

            assert_allclose(LHS, RHS, rtol=rtol, atol=atol, err_msg=err)
```

**Comment by rgommers** [comment]
Reversing the checks makes sense to me, and the last two failures seem minor. The first one is a large change, increasing `atol` by an order of magnitude (`0.000357` to `0.00344`). Maybe that is what it is, but it would be good to bump the tolerance only for the subset of test parameters where that is really necessary.

**Comment by dimpase** [comment]
On Sun, Oct 3, 2021 at 4:31 PM Ralf Gommers ***@***.***>
wrote:

> The new failures are not from reversing the checks right, but from this
> piece of code have the wrong indentation for assert_allclose(...) so it's
> not run at all for general is True?
>

Good catch, thanks! I was puzzled by these tests passing at all. Needless
to say, I corrected the indentation, without
noticing it was wrong before.

**Comment by dimpase** [comment]
> Reversing the checks makes sense to me, and the last two failures seem minor. The first one is a large change, increasing `atol` by an order of magnitude (`0.000357` to `0.00344`). 

It's a bit suspect to me that it depends on the Python version. 3.8 is getting old, perhaps time to move on 3.9?
(or perhaps it's cause it's a "dbg" build, whatever it is)

**Comment by rgommers** [comment]
> It's a bit suspect to me that it depends on the Python version. 3.8 is getting old, perhaps time to move on 3.9?
> (or perhaps it's cause it's a "dbg" build, whatever it is)

We can't drop 3.8, we're only just dropping 3.7 now - 3.8 will be around for another ~1.5 years. This is also not likely to be dependent on Python version I'd say.

A dbg build is a debug build of Python, so debug symbols are included. Such builds are typically also shipped in Linux distros as separate packages (typically named `python-dbg`).

**Comment by dimpase** [comment]
Is there documentation on how to fix a particular test?
We have to fix 2 instances, which differ from one another in 3 places, marked by `*` below:
```
    eval_evec(symmetric, D, typ, k, which,
        D          = <gen-hermitian-Mc>
        k          = 2
*       mattype    = <built-in function asarray>
        params     = <scipy.sparse.linalg.eigen.arpack.tests.test_arpack.SymmetricParams object at 0x7fd8a0dcf500>
        sigma      = None
        symmetric  = True
 *      typ        = 'F'
 *      which      = 'LA'
```
and
```
    eval_evec(symmetric, D, typ, k, which,
        D          = <gen-hermitian-Mc>
        k          = 2
*       mattype    = <class 'scipy.sparse.csr.csr_matrix'>
        params     = <scipy.sparse.linalg.eigen.arpack.tests.test_arpack.SymmetricParams object at 0x131cf32e0>
        sigma      = None
        symmetric  = True
 *      typ        = 'D'
 *      which      = 'LM'
```

**Comment by rgommers** [comment]
There aren't any docs, this is too detailed to have docs. I'd say bump the test tolerance unconditionally to make the 2 tests with a small mismatch pass, and then special-case the last test based on the parameters you point out above.

**Comment by rgommers** [comment]
@dimpase the change to the PROPACK submodule was a mistake I assume?

**Comment by dimpase** [comment]
it's a pure evil - the submodule update got mixed into d6f6eecac4ec04c4f25ba3aca384ace55354bf2f - nothing and nobody told me this happened...

**Comment by dimpase** [comment]
macOS tests fail while building `quadpack` extension, something unrelated:
```
/usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.14-x86_64-3.9/scipy/integrate/_quadpackmodule.o -L/usr/local/lib -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.9.0 -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.9.0/../../.. -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin13/4.9.0/../../.. -L/Users/runner/hostedtoolcache/Python/3.9.7/x64/lib -Lbuild/temp.macosx-10.14-x86_64-3.9 -Wl,-rpath,/usr/local/lib -lquadpack -lmach -lopenblas -lopenblas -lgfortran -o build/lib.macosx-10.14-x86_64-3.9/scipy/integrate/_quadpack.cpython-39-darwin.so
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
```
The rest passes.

**Comment by dimpase** [comment]
the failing check is due to the rebase over the current master, unrelated to the ticket

**Review by rgommers — APPROVED** [review]
Okay, this should be good to go now - let's give it a try. Thanks @dimpase!

**Pull request merged**
