### PR TITLE
TST: linalg: skip failing tests due to Accelerate bug in macOS >=15,<15.2

### PR DESCRIPTION
**Pull request by andyfaff**
See #21862 
Skips those tests if on macOS Sequoia < 15.2.

Hopefully Accelerate is fixed for 15.2

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Looks good to me so far--I guess you've abstracted handling some of the remaining fails to gh-21946?

I'll add a milestone here so I don't forget, given the impending branching.

**Comment by andyfaff** [comment]
The trouble is that I'm not sure how much is ascribable to Accelerate, and how much is due to scipy. I'm trying to see if I can get a beta version of accelerate to see if the fix cures things.

**Comment by tylerjereddy** [comment]
That sounds like a good idea, I don't think I have easy access/permission to bump to 15.x at work yet.

**Comment by rgommers** [comment]
If you prefer to merge these tests skips after all, that seems fine to me @andyfaff - your call. If you drop the CI changes, I think it is mergeable.

**Comment by tylerjereddy** [comment]
Based on https://github.com/scipy/scipy/issues/21862#issuecomment-2503479151, and given the proximity to branching for `1.15.0`, I think my preference now is not to merge this at the last minute and probably to just wait on MacOS `15.2` as noted over there (it should be released before SciPy `1.15.0`).

If there is some scenario I'm not thinking of that causes a bunch of pushback on the intermittent test failures, we could consider a backport, but seems like a stretch and wouldn't really change the root problem of the linalg backend needing to be patched for user code anyway.

**Comment by tylerjereddy** [comment]
I'll bump the milestone, but won't be so aggressive as closing this in case we get some feedback or something.

**Pull request closed without merging**
