### PR TITLE
ENH: scipy.optimize.minimize with method=SLSQP returns KKT multipliers

### PR DESCRIPTION
**Pull request by msparapa**
See issue #9827.

I added a `KKT` dictionary, which behaves almost identical to `OptimizeResult`, whose role is to store the KKT multipliers in two separate fields, `equality` and `inequality`. This is consistent with how results are returned from scipy optimizers, but there may be a better way to do this. Since the user enters in constraints as a list of equality and inequality constraints, should we do the same for the output of kkts?

The only change to `_minimize_slsqp` was that we grab the kkt multipliers from the `w` variable output by the SLSQP FORTRAN code. I don't think any changes are necessary to the documentation or test cases.

### CODE REVIEW

**Comment by mdhaber** [comment]
Looks like the test failure is unrelated.

I know that `OptimizeResult` doesn't seem to document all solver-specific attributes, but that is a shortcoming and we should try to fix that. For now, I'd suggest documenting these additional attributes in the [SLSQP-specific documentation](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-slsqp.html#optimize-minimize-slsqp).

This also deserves at least one unit test. Can you pick an example problem that will have both equality and inequality multipliers and set up a test case to ensure that they are reported correctly in the OptimizeResult?

**Comment by msparapa** [comment]
Gotcha. Is this failing because of #9837? I can rebase once the fix is merged.

I'll also come up with a test case. This can get sort of tricky because often times the kkt multipliers are not unique. I'll see if I can make a problem that has unique multipliers.

**Comment by mdhaber** [comment]
@msparapa looks like it is #9837, yup

**Comment by msparapa** [comment]
Ok this is strange. See lines 468-473 in my optimize/slsqp.py. I had to add in 1 extra call to the FORTRAN slsqp to get the correct values of the kkt multipliers. I suspect the FORTRAN code is updating the multipliers prior to updating x and fx. Thus when it terminates, it doesn't do the final update step for the multipliers. I don't know FORTRAN so diving into the .f file is rough.

If you comment out the final slsqp call, you'll get incorrect values for the multipliers with the following code:

```
from scipy.optimize import minimize

x0 = 3.0 # Change this

opt = minimize(lambda z: z**2, x0, constraints=[{'fun':lambda z: z[0]-1, 'type':'eq'}])

print(opt['kkt']) # The correct result here is [array([2.0])]
```

Changing the initial guess affects the output of the multipliers. However, with the extra call I added in, changing x0 does not affect the multipliers and they are correct estimates.

**Comment by mdhaber** [comment]
You mean it is executing on 446 (are you sure? just checking) but it has to be called a second time on 470 or else you get incorrect multipliers?
Yes, that would seem strange. 
@pv thoughts?

**Comment by msparapa** [comment]
Yes, it's executing like normal on 446, which is what we want, but to do the final update for the multipliers I had to call it again on 470. Put the code from my comment above in a new file and run it with the branch in the pull request. When you comment out the 470 call, the multipliers change to incorrect values, but we do not want the 470 call when we merge back into scipy. I believe the 446 call is wrapped in a loop because it gets new estimates of the nonlinear system every iteration, then the slsqp call solves the subproblem. I've been looking through the FORTRAN file a bit to see if there's a convenient way of moving the multiplier update to the end instead of right at the beginning. But I'm not even 100% certain that is whats going on at the moment.

**Comment by mdhaber** [comment]
I suggest looking through the SLSQP history here on GitHub to see who has worked on it in the past. Perhaps someone else would know what to do.

**Comment by andyfaff** [comment]
I note that the ordering within the optimize loop in _minimize_slsqp.py has been changed now. It may be time to revisit this to check for correctness.

**Comment by mdhaber** [comment]
Closing because this is superseded by gh-15641.

**Pull request closed without merging**
