### PR TITLE
Fixes #6602 - Typo in docs

### LINKED ISSUE #6602: Typo in docs
https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html

An example in the docs for `scipy.integrate.quad` is 

image

However, the `integrand` function is written:

image

where `x` appears to be missing a square, i.e. we expect `return (a * x**2) + b` .  Either the latex should be written to reflect the code, or vice versa.

Many thanks.

### PR DESCRIPTION
**Pull request by bhavika**
I updated the code to reflect the Latex in an example from `scipy.integrate.quad`.

### CODE REVIEW

**Comment by person142** [comment]
Hey @bhavikat, note that you'll need to fix the result too--it currently says

```python
>>> I = (2.0, 2.220446049250313e-14)
```
(actually not sure why it's formatted like that, should be changed to) when it should be
```python
>>> from scipy.integrate import quad
>>> def integrand(x, a, b):
...     return a*x**2 + b
...
>>> a = 2
>>> b = 1
>>> I = quad(integrand, 0, 1, args=(a, b))
>>> I
(1.6666666666666667, 1.8503717077085944e-14)
```

**Comment by bhavikat** [comment]
@person142 Ofcourse! I'm sorry, I'll update that as well - in a little bit.

**Comment by person142** [comment]
Build failure looks unrelated; restarted it.

**Comment by person142** [comment]
Looks good now, thanks. Also, in the future don't forget your friendly neighbourhood commit message acronyms!

 http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message

**Comment by person142** [comment]
See also #6610 for a follow-up issue.

**Comment by bhavikat** [comment]
@person142 I hadn't see the list of acronyms. I'll be using them now in the future. Checking out #6610 too, thank you!

**Pull request merged**
