### PR TITLE
DOC/MAINT: doc: fix some typos

### PR DESCRIPTION
**Pull request by musvaage**
@lucascolley

mostly release note fixes
tutorial also affected and some other cleanup

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
thanks for your first contribution to SciPy!

**Comment by musvaage** [comment]
@lucascolley 

doc/source/building/index.rst (line 355)

.\venv\Scripts\activate

Doesn't Windows .\venv\Scripts\ have a .bat and a .ps1 file?

.\venv\Scripts\Activate.ps1

or, as `pwsh` is case-insensitive

.\venv\Scripts\activate.ps1

**Comment by lucascolley** [comment]
hmm, I'm not sure. Maybe open a new issue about that?

**Comment by musvaage** [comment]
@DimitriPapadopoulos 

if pertinent to the corpus of codespell

some fixes in this pull and it's sibling `#21573`

**Pull request merged**
