### PR TITLE
DOC: stylistic consistency, punctuation, etc.

### PR DESCRIPTION
**Pull request by mkg33**
This is the penultimate commit and the last pull request regarding the stylistic consistency, punctuation revision, etc., in the current documentation. The last part will follow tomorrow (at the latest).

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @mkg33! From a first browse this looks good. There are quite a few CI failures though, could you try and resolve those? 

One of the main reasons I see is that you changed the text of warnings in some places (e.g. `behaviour` -> `behavior`) and the corresponding test was using the old string to check if a warning got raised.

You should be able to look at the test failures, find the corresponding change to the docstring or code of the function being tested, and then adjust either the test or your change.

If there are some you can't figure out, let me know!

**Comment by mkg33** [comment]
Thanks for the quick review, @rgommers. And I was being really careful... Of course, I'll resolve the issues ASAP.

**Comment by rgommers** [comment]
> because I'm still unable to build the documentation - about that: I'll post the full error message after the GSoD deadline.

Sounds good, no hurry.

> Update: the Travis CI check is probably not my fault (?) because it refers to something in the `stats` module and I've never touched the `stats` module.

Yes indeed. That one is a known issue with a not completely reproducible example that needs fixing before the 1.4.0 release next week.

**Comment by rgommers** [comment]
Merged, thanks Maja!

**Comment by endolith** [comment]
I tried to make comments on some changes that are less clear than the original.  `1-D`, `2-D`, `N-D` have clear meanings, but `D-D`, `R-D` do not.

**Pull request merged**
