### PR TITLE
[MRG] BUG: Update lobpcg.py to validate the accuracy and issue warnings

### LINKED ISSUE #14784: BUG: wrong results in sparse.linalg.lobpcg
### Describe your issue.

As first discussed in #10974 , I obtained wrong results when trying to approximate the SVD of a matrix with LOBPCG. ARPACK is fine.

The matrix can be found as a txt file at https://gist.github.com/ogauthe/63b70fd32329eac90150fa91dfb1ac67. It is pretty small with shape (504, 504), square but not symmetric, with ~78 non-zero singular values, without any degeneracy.

For `k=1`, everything is fine. For `k=2`, the result is completely wrong. For `k>7`, the functions crashes, so I suppose the problem comes from an undetected Cholesky failure, as in  #10974.

ping @lobpcg 

### Reproducing Code Example

```python
import numpy as np
import scipy.linalg as lg
import scipy.sparse.linalg as slg

A = np.loadtxt("lobpcg_fail.txt")
x = lg.norm(A)
print(A.shape, A.dtype)

k = 2
u0, s0, v0 = lg.svd(A)
u1, s1, v1 = slg.svds(A, k=k, solver="lobpcg")
u2, s2, v2 = slg.svds(A, k=k, solver="arpack")

print("dense  truncation", lg.norm(u0[:,:k] * s0[:k] @ v0[:k] - A) / x) 
print("arpack truncation", lg.norm(u2 * s2 @ v2 - A) / x) 
print("lobpcg truncation", lg.norm(u1 * s1 @ v1 - A) / x)
```

### Error message

```shell
(504, 504) float64
dense  truncation 0.002749949291553053
arpack truncation 0.0027499492915530536
lobpcg truncation 1.2256989944723657
```

### SciPy/NumPy/Python version information

1.6.2 1.20.3 sys.version_info(major=3, minor=7, micro=11, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by lobpcg**
Update lobpcg.py to validate the accuracy and issue warnings

#### Reference issue
Closes https://github.com/scipy/scipy/issues/14784

#### What does this implement/fix?
Adding Postprocessing to LOBPCG output to validate the accuracy and issue a user warning  if the code exits without reaching the requested tolerance.

### CODE REVIEW

**Review by ilayn — COMMENTED** [review]
Some minor comments

**Review by tupui — COMMENTED** [review]
Thanks @lobpcg. Some non-blocking suggestions on my side.

**Review by tupui — COMMENTED** [review]
Thanks for the quick update! I made some suggestion (ready to be applied for your convenience: use the `Files changed` tab to batch them and do it all at once, if you agree) regarding old API use of np.random. `rand` and `randn` are both kept for backward compatibility so we should move away from them.

**Review by tupui — COMMENTED** [review]
Thanks for your patience @lobpcg. On my side we just need to adjust the `stacklevel`.

I tested the following suggestions with a test file (bellow). And get the following:

```python
/.../warnings.py:59: UserWarning: Failed at iteration 2 with accuracies [3.01627227 \
        9.23113038 9.61200487 7.92599915]
 not reaching the requested tolerance 3.162277660168379e-06.
  eigenvalues, _ = lobpcg(A, Q, maxiter=20)
/.../warnings.py:59: UserWarning: Exited at iteration 2 with accuracies 
[3.01627227 9.23113038 9.61200487 7.92599915]
not reaching the requested tolerance 3.162277660168379e-06.
  eigenvalues, _ = lobpcg(A, Q, maxiter=20)
/.../warnings.py:48: UserWarning: The problem size 10 minus the constraints size 0 is too
small relative to the block size 10. Using a dense eigensolver instead of LOBPCG.
  eigvals, _ = lobpcg(A, X, B=B, tol=1e-2, maxiter=50, largest=False)
```

If the `stacklevel` is 3 or above, we get to `sys:1:` which is not providing any information. Hence it should be 2 when in `lobpcg` and then it increments. So we get to 4 in `_report_nonhermitian`.

Can you confirm @ilayn (and thanks for the long exhaustive explanation).

<details><summary>warnings.py</summary>
<p>
```python
"""I copied all these straight from the tests"""
import numpy as np

from scipy.linalg import eig, orth
from scipy.sparse.linalg import lobpcg


def ElasticRod(n):
    """Build the matrices for the generalized eigenvalue problem of the
    fixed-free elastic rod vibration model.
    """
    L = 1.0
    le = L/n
    rho = 7.85e3
    S = 1.e-4
    E = 2.1e11
    mass = rho*S*le/6.
    k = E*S/le
    A = k*(np.diag(np.r_[2.*np.ones(n-1), 1])-np.diag(np.ones(n-1), 1)-np.diag(np.ones(
            n-1),
                                                                           -1))
    B = mass*(np.diag(np.r_[4.*np.ones(n-1), 2])+np.diag(np.ones(n-1), 1)+np.diag(np.ones(
            n-1),
                                                                            -1))
    return A, B


def MikotaPair(n):
    """Build a pair of full np.diagonal matrices for the generalized eigenvalue
    problem. The Mikota pair acts as a nice test since the eigenvalues are the
    squares of the integers n, n=1,2,...
    """
    x = np.arange(1, n+1)
    B = np.diag(1./x)
    y = np.arange(n-1, 0, -1)
    z = np.arange(2*n-1, 0, -2)
    A = np.diag(z)-np.diag(y, -1)-np.diag(y, 1)
    return A, B


def compare_solutions(A, B, m):
    """Check eig vs. lobpcg consistency.
    """
    n = A.shape[0]
    rnd = np.random.RandomState(0)
    V = rnd.random((n, m))
    X = orth(V)
    eigvals, _ = lobpcg(A, X, B=B, tol=1e-2, maxiter=50, largest=False)  # THIS IS LINE 48
    eigvals.sort()
    w, _ = eig(A, b=B)
    w.sort()


rnd = np.random.RandomState(0)
X = rnd.standard_normal((100, 10))
A = X @ X.T
Q = rnd.standard_normal((X.shape[0], 4))
# "Exited at iteration"
eigenvalues, _ = lobpcg(A, Q, maxiter=20)  # THIS IS LINE 59


A, B = ElasticRod(10)
# "The problem size"
compare_solutions(A, B, 10)
```
</p>
</details>

**Comment by lobpcg** [comment]
@tupui I have changed the stacklevel per your suggestions and added a new unit test that you had noted was missing, although unrelated to this PR. 

It appears like everything works in this PR, with all failures unrelated. Could you have the hopefully final look?

**Comment by ilayn** [comment]
I think we can put this in and since a couple of us have been looking at it lately, there is no showstoppers and if still minor issues left we can handle it before 1.8. Sorry for dropping out lately, I am having hard time sparing quality time. Nevertheless thanks @lobpcg @tupui !

**Comment by lobpcg** [comment]
Thanks for your reviews and suggestions @ilayn and @tupui !

**Comment by lobpcg** [comment]
There are 2  new warnings implemented: 
- problem too small for the actual LOBPCG to run, so it internally calls LAPACK. This needs to be silenced or even some tests removed.
- iterations stop before the requested tolerance is reached because max number of iterations is topped. This may require a review if the value of the requested tolerance is reasonable, i.e. not too small, or the maxit parameter needs to be increased. If the test passes otherwise, the warning can of course be silenced

**Pull request merged**
