### PR TITLE
ENH: stats.binned_statistic: allow structured/rec array input

### PR DESCRIPTION
**Pull request by yoachim**
#### Reference issue
I was too lazy to make an issue for this.

#### What does this implement/fix?
Adding a check so `binned_statistic` can take a numpy structured or rec array as input. 

#### Additional information
I think most people would probably just convert to a pandas DataFrame and do a groupby, but for my use case I think the overhead of creating dataframes would become an issue.

### CODE REVIEW

**Review by mdhaber — CHANGES_REQUESTED** [review]
It looks like this is the recommended way to test whether the array is structured - good. 

All feature PRs like this need a unit test. 

What happens if `values` has zero size with and without this PR?

Does this work if `statistic` is a string?

**Comment by yoachim** [comment]
> All feature PRs like this need a unit test.
Unit test added.
> What happens if `values` has zero size with and without this PR?
Looks like `binned_statistic` fails either way with a zero size `values` array.
> Does this work if `statistic` is a string?
Fails if `values` is a structured array and `statistic` is a string, which is good because it's ambiguous what the `mean` should be for an array with multiple columns. Could add an explicit ValueError if that seems helpful.

**Comment by mdhaber** [comment]
> Could add an explicit ValueError if that seems helpful.

It would be. And adding a test that the error is emitted as intended with `pytest.raises(ValueError, match=message)` context..

That said, I'd hold up on adding that. I'll talk with other statistics maintainers about this shortly, but I'm not sure adding support for structured arrays is a direction we want to start going down. We recently removed support for `object` arrays from `stats.mode`, for instance, and the main thrust right now is support for the Python array API, which does not have a specification for structured arrays.

What other SciPy functions "should" have support for structured arrays, in your opinion, and for those, is there not another option to do the same sort of tasks (e.g. `pandas`)?

**Comment by tupui** [comment]
Hi @yoachim,

I agree with Matt on not moving forward with this proposal. We are adding support for Array API so these input arrays should follow the standard. If down the line the standard would allow something like rec array, then by all mean.

**Comment by lucascolley** [comment]
> What other SciPy functions "should" have support for structured arrays, in your opinion, and for those, is there not another option to do the same sort of tasks (e.g. pandas)?

I'm going to close this PR, but feel free to continue discussing this point here!

**Pull request closed without merging**
