### PR TITLE
Add 'implicit none' to cfftb

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes a part of #3168

### CODE REVIEW

**Comment by ev-br** [comment]
Looks like fftpack relies on implicit typing. So you'd need to either add explicit types, it seems.

**Comment by souravsingh** [comment]
@ev-br So we have to change `N` to `INTEGER N`, correct? Are there any other changes that are needed?

**Comment by person142** [comment]
Every variable needs to be explicitly typed now. (`N`, `C`, `WSAVE`, `IW1`, `IW2`)

**Comment by person142** [comment]
(Implicit typing default rules: variables beginning with `I`, `J`, `K`, `L`, `M`, `N` are integers; everything else is `REAL`.)

**Comment by person142** [comment]
Build is failing--typing occurs inside the subroutine, as does the `IMPLICIT NONE` statement. Build it locally; you'll see the failures. Also might want to familiarize yourself with Fortran syntax; otherwise this is going to seem like a lot of black magic.

**Comment by pv** [comment]
Also, if this is the first contact to fortran, it is easy to make errors here, and it may be better and more fun to contribute by doing something else. This `implicit none` business is imho fairly low priority.

**Comment by ev-br** [comment]
I agree re: priority.

I added these to several files a while ago, thinking that there will be gazillions of errors. Nope, not that many, and none of them critical. So I guess we'd require it in new code but battle-tested libraries are fine (or their bugs are better hidden).

**Comment by souravsingh** [comment]
@person142 I will scrub through the syntax for Fortran. It has been a long time since I worked in Fortran and I have forgotten many things.

**Comment by souravsingh** [comment]
@ev-br So by your comment, do you mean we have to add the line to actively developed Fortran libraries like arpack?

**Comment by ev-br** [comment]
> do you mean we have to add the line to actively developed Fortran libraries like arpack?

Nonono. Meant new code written by us for scipy specifically in Fortran (not that there's much reason to).

**Comment by souravsingh** [comment]
@person142 Is the PR ready for merging?

**Comment by pv** [comment]
C is not integer

**Comment by souravsingh** [comment]
@pv I have updated the code. Is the PR ready for merging?

**Comment by souravsingh** [comment]
@pv Is the Patch ready for merging?

**Comment by souravsingh** [comment]
@pv Is the Patch ready for merging?

**Comment by souravsingh** [comment]
Closing PR due to no feedback

**Pull request closed without merging**
