### PR TITLE
ENH:integrate: Rewrite QUADPACK in C

### LINKED ISSUE #12662: Complex numpy exponentiation, nan, and/or inf causes segfault in indefinite weighted integrate.quad
#### Reproducing code example:
```python
from numpy import cos, inf, float64
from scipy.integrate import quad

a = float64(0.5)
quad(lambda t: t ** a, -inf, 0, weight="cos", wvar=1, limlst=10 ** 3)
```

#### Error message:
```python
test.py:5: RuntimeWarning: invalid value encountered in double_scalars
  quad(lambda t: t ** a, -inf, 0, weight="cos", wvar=1, limlst=10 ** 3)
Segmentation fault (core dumped)
```

#### Scipy/Numpy/Python version information:
Scipy version 1.5.2
Numpy version 1.19.1

I accidentally came across this when I erroneously allowed a function to become complex when integrating.

Note that 
```python
a = float64(0.5)
quad(lambda t: t ** a * cos(1 * t), -inf, 0)
```
returns `nan` and
```python
a = 0.5
quad(lambda t: t ** a, -inf, 0, weight="cos", wvar=1, limlst=10 ** 3)
```
raises a `TypeError:  can't convert complex to float`, so this should probably do something similar, but there's some scipy-numpy mismatch when using weighted integration.

### LINKED ISSUE #14945: BUG: Overflows/NaNs cause segfault in integrate.quad on certain domains
### Describe your issue.

I was working on something similar to this issue https://github.com/scipy/scipy/issues/12662 and am encountering similar segfaults, even without using weighted integration. Below is the simplest example that I can reproduce this on where I've essentially removed all mathematical calculations entirely.

Surprisingly, this is **very** sensitive to the domain of integration. It segfaults on [-1.5, 1.5], but does not on [-1.49, 1.5] or [-1.5, 1.49]. It does not appear particularly sensitive to the locations of the NaNs either.

No error message or warnings are printed before the segfault. The segfault is triggered by a general protection fault in `scipy/integrate/_quadpack.cpython-39-x86_64-linux-gnu.so`.

This consistently occurs after the 4557th query to `f(theta)` after this sequence of Gauss-Kronrod samples:
scipy_nan_quad_segfault
The final query (which segfaults) has `theta=1.7144581914055983e-17`, but I imagine the issue is in the scipy/QUADPACK bookkeeping of earlier samples.

### Reproducing Code Example

```python
import numpy as np
from scipy.integrate import quad


def f(theta):
    if theta < -1:
        return np.nan
    return 0.0

quad(f, -1.5, 1.5, limit=1000)
```

### Error message

```shell
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

### LINKED ISSUE #21057: BUG: loong64 architecture fails TestQuad.test_complex
### Describe your issue.

loong64 is a new Chinese CPU architecture, which debian includes in its suite of supported architectures.  It is related to MIPS64, but is failing the TestQuad.test_complex test from the integrate tests.

The failure only started recently, the test was passing before 14 June.  I'm not certain what changed. The gcc version is the same.

Build logs (building scipy 1.13.1) can be found at https://buildd.debian.org/status/logs.php?pkg=scipy&arch=loong64

e.g. https://buildd.debian.org/status/fetch.php?pkg=scipy&arch=loong64&ver=1.13.1-1exp7&stamp=1719404050&raw=0

Only this one test is failing on loong64, but the error looks serious enough to report rather than skip and ignore.

For comparison, the test is still passing on MIPS64 (mips64el), https://buildd.debian.org/status/fetch.php?pkg=scipy&arch=mips64el&ver=1.13.1-1exp6&stamp=1718428354&raw=0

### Reproducing Code Example

```python
# on a loong64 system
python3 -c "import scipy.integrate; scipy.integrate.test(extra_argv=['-k', 'quadpack and test_complex', '-v'])"
```

### Error message

```shell
____________________________ TestQuad.test_complex _____________________________

E   AssertionError: 
    Items are not equal:
     ACTUAL: 230.90706003885032
     DESIRED: 32.986722862692815
All traceback entries are hidden. Pass `--full-trace` to see hidden and internal frames.

During handling of the above exception, another exception occurred:

self = <scipy.integrate.tests.test_quadpack.TestQuad object at 0x7fffe9cb2540>

    def test_complex(self):
        def tfunc(x):
            return np.exp(1j*x)
    
        assert np.allclose(
                    quad(tfunc, 0, np.pi/2, complex_func=True)[0],
                    1+1j)
    
        # We consider a divergent case in order to force quadpack
        # to return an error message.  The output is compared
        # against what is returned by explicit integration
        # of the parts.
        kwargs = {'a': 0, 'b': np.inf, 'full_output': True,
                  'weight': 'cos', 'wvar': 1}
        res_c = quad(tfunc, complex_func=True, **kwargs)
        res_r = quad(lambda x: np.real(np.exp(1j*x)),
                     complex_func=False,
                     **kwargs)
        res_i = quad(lambda x: np.imag(np.exp(1j*x)),
                     complex_func=False,
                     **kwargs)
    
>       np.testing.assert_equal(res_c[0], res_r[0] + 1j*res_i[0])
E       AssertionError: 
E       Items are not equal:
E        ACTUAL: (230.90706003885032+1.1655968375567166e-15j)
E        DESIRED: (32.986722862692815+1.1655968375567166e-15j)

kwargs     = {'a': 0, 'b': inf, 'full_output': True, 'weight': 'cos', ...}
res_c      = ((230.90706003885032+1.1655968375567166e-15j), (292.1681167840555+5.585367613532157e-15j), {'imag': ({'erlst': array([...ure invoked on this cycle.  It is assumed that the result on this interval is the best which can be obtained.', ...})})
res_i      = (1.1655968375567166e-15, 5.585367613532157e-15, {'erlst': array([4.82013969e-18, 3.89507855e-16, 4.53618857e-17, 1.498...     1038530212, -1073741824,  1042556203, -2147483648,  1041689581],
      dtype=int32), 'lst': 6, 'neval': 150, ...})
res_r      = (32.986722862692815, 2.0517814695912247e-10, {'erlst': array([2.05135975e-11, 2.05139675e-11, 2.05132276e-11, 2.051267...     1049296283,  -778100732,  1048957913, -1583113503,  1049668002],
      dtype=int32), 'lst': 7, 'neval': 525, ...})
self       = <scipy.integrate.tests.test_quadpack.TestQuad object at 0x7fffe9cb2540>
tfunc      = <function TestQuad.test_complex.<locals>.tfunc at 0x7fffdb430040>

scipy/integrate/tests/test_quadpack.py:530: AssertionError
```

### SciPy/NumPy/Python version and system information

```shell
[this system info is taken from my amd64 system, to show indicative versions.  I have manually replaced the `x86_64` references to `loongarch64` to represent loong64]

$ python3 -c "import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()"
1.13.1 1.26.4 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/loongarch64-linux-gnu
    lib directory: /usr/lib/loongarch64-linux-gnu/openblas-pthread
    name: blas
    openblas configuration: unknown
    pc file directory: /usr/lib/loongarch64-linux-gnu/pkgconfig
    version: 0.3.27+ds
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/loongarch64-linux-gnu
    lib directory: /usr/lib/loongarch64-linux-gnu/openblas-pthread
    name: lapack
    openblas configuration: unknown
    pc file directory: /usr/lib/loongarch64-linux-gnu/pkgconfig
    version: 0.3.27+ds
  pybind11:
    detection method: pkgconfig
    include directory: /include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -g, -O2, -Werror=implicit-function-declaration, -ffile-prefix-map=/projects/python/build/scipy=.,
      -fstack-protector-strong, -fstack-clash-protection, -Wformat, -Werror=format-security,
      -fcf-protection, -Wdate-time, -D_FORTIFY_SOURCE=2
    commands: cc
    linker: ld.bfd
    linker args: -Wl,-z,relro, -g, -O2, -Werror=implicit-function-declaration, -ffile-prefix-map=/projects/python/build/scipy=.,
      -fstack-protector-strong, -fstack-clash-protection, -Wformat, -Werror=format-security,
      -fcf-protection, -Wdate-time, -D_FORTIFY_SOURCE=2
    name: gcc
    version: 13.2.0
  c++:
    args: -g, -O2, -ffile-prefix-map=/projects/python/build/scipy=., -fstack-protector-strong,
      -fstack-clash-protection, -Wformat, -Werror=format-security, -fcf-protection,
      -Wdate-time, -D_FORTIFY_SOURCE=2
    commands: c++
    linker: ld.bfd
    linker args: -Wl,-z,relro, -g, -O2, -ffile-prefix-map=/projects/python/build/scipy=.,
      -fstack-protector-strong, -fstack-clash-protection, -Wformat, -Werror=format-security,
      -fcf-protection, -Wdate-time, -D_FORTIFY_SOURCE=2
    name: gcc
    version: 13.2.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: -fPIC
    commands: gfortran
    linker: ld.bfd
    linker args: -Wl,-z,relro, -fPIC
    name: gcc
    version: 13.2.0
  pythran:
    include directory: ../../../../../../../usr/lib/python3/dist-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: loongarch64
    endian: little
    family: loongarch64
    system: linux
  cross-compiled: false
  host:
    cpu: loongarch64
    endian: little
    family: loongarch64
    system: linux
Python Information:
  path: /usr/bin/python3.11
  version: '3.11'
```

### PR DESCRIPTION
**Pull request by ilayn**
Part of #18566 

- I removed the dependency to LAPACK by adding the `dgtsv` solver manually (I tested the code separately offline). Hence we don't need for ILP adjustments. We can make the library run with 64-bit integers but I am not sure if that would make things any better. 
- The front-end functions (which are publicly exported functions) have a very tangled goto behavior that has no logic but a lot of code repetition if unrolled. Thus I didn't bother to unroll them. A domain expert should actually tidy these things up instead.
- QUADPACK also includes a frontend function DQAGE however it is not exposed in SciPy hence skipped. Also there are 31, 41 and 51 Gauss-Kronrod algorithms however none of the exposed routines use them (They are used by DQAGE). Because they were easy copy paste operations I translated them anyways. We can always come back to it if there is a need.

Closes #12662
Closes #14945
Closes #21057

### CODE REVIEW

**Comment by mdhaber** [comment]
I'd be willing to help review by test, but I could use some help getting full coverage. If I write Python tests, can you tell what lines in your code they exercise (i.e. code coverage of the C code)? Alternatively, can you tell  what sorts of arguments are needed to get QUADPACK to choose each routine? (e.g. integration limits need to be infinite to choose QAGI.)

**Comment by ilayn** [comment]
Thank you @mdhaber for the helping hand, much appreciated. Give me a few more days so that this code is compiling without issues (this is my first pass of the rewrite without paying any attention to indices and potential segfaults). I'm close to finishing the second pass and I'll ping again here when it is just making mistakes and not segfaults.

> If I write Python tests, can you tell what lines in your code they exercise (i.e. code coverage of the C code)?

I think I can figure that out. We did a similar exercise with AMOS code on special side so probably I can regurgitate that mechanism. @j-bowhay also helped with that so maybe he can chime in here. 

> Alternatively, can you tell what sorts of arguments are needed to get QUADPACK to choose each routine? (e.g. integration limits need to be infinite to choose QAGI.)

This is my biggest source of annoyance to hunt down the if then else trees. But I don't know any other way so, with regret, I don't want to say it but I must say yes 😃

**Comment by mdhaber** [comment]
Actually, I read the docstring more carefully, and if you can check the code coverage, I think I have a good idea of how to hit all the main routines. Let's see what's left over in the coverage after I try that.

**Comment by ilayn** [comment]
OK, great. On my side, actually going from bottom to top was faster for the second pass (as opposed to top to bottom) hence I will try to send something tomorrow or tonight after work.

**Comment by mdhaber** [comment]
I revived a benchmarking script I had used for `_tanhsinh`. If you don't mind using Dropbox, the folder is here:
https://www.dropbox.com/scl/fo/yv8lgxf3qbrb0cin9ba6e/AMJbgk8xfbxbTYOzvhOhJV4?rlkey=iqaze0cwpr8r8nc238srzqfur&dl=0

I found the Excel file with 818 problem definitions in an mpmath forum, and I've just been working with it rather than turning it into plain text or something. Since the script is already working with Excel, it writes the results in Excel too, so you need `pandas` and `openpyxl` to work with the script as-is. But I can run things when you think this is ready, so you don't really have to work with it.

 We really only need to compare the two versions of `quad` against one another, so don't really even need the analytical result that's in the file, just the function definition and limits of integration.
 
Looks like this will exercise the main routine, `qagse`. To exercise the rest of the routines, I think we can just modify these problems. Not all will converge, but behavior in those cases is a good thing to test, too.
- `qadie` - might as well just try making one or both limits of integration infinite. Some of them will converge, some won't. I think we can still get a good comparieson.
- `qadpe` - many of the problems have singularities at `x=0`, so I could just add that as the trouble spot and include that in the integration interval.
- `qawoe` - just add `weight='sin'` and `weight='cos'` with `wvar` as any arbitrary number. ISTM to that if the original interval converged, this should too.
- `qawfe` - same as `qawoe` but with infinite upper limit of integration

etc.

**Comment by ilayn** [comment]
Thanks @mdhaber this sounds great. Today I had two hours that I could spare and I'm down to 9 failures overall which only one is from `test_quadpack.py` and the rest is from the fallout from it in special and stats. There is some typo lurking somewhere that I'm hunting for right now once I find it, we will be good to go starting from fail-free test suite.

**Comment by ilayn** [comment]
I'll quickly see whether CI also agrees that there are 9 failures left. I fixed the typo but full mode revealed 9 more, one of which is a segfault. 

```
FAILED scipy\stats\tests\test_continuous_basic.py::test_methods_with_lists[levy_stable-args66-pdf] - AssertionError:
FAILED scipy\stats\tests\test_continuous_basic.py::test_moments[crystalball-arg13-True-True-True-False] - scipy.integrate._quadpack_py.IntegrationWarning: The occurrence of roundoff error is detected, which prevents
FAILED scipy\stats\tests\test_distributions.py::TestLevyStable::test_pdf_nolan_samples[pct_range0-alpha_range0-beta_range0]
FAILED scipy\stats\tests\test_survival.py::TestSurvival::test_plot_iv - DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetim...
FAILED scipy\stats\tests\test_distributions.py::TestLevyStable::test_cdf_nolan_samples[pct_range1-alpha_range1-beta_range1] - AssertionError:
FAILED scipy\stats\tests\test_distributions.py::TestLevyStable::test_location_scale[pdf-0] - AssertionError:
FAILED scipy\stats\tests\test_distributions.py::TestLevyStable::test_pdf_nolan_samples[pct_range1-alpha_range1-beta_range1] - AssertionError:
FAILED scipy\stats\tests\test_distributions.py::TestLevyStable::test_pdf_alpha_equals_one_beta_non_zero[piecewise-4]
FAILED scipy\stats\tests\test_distributions.py::TestLevyStable::test_location_scale[pdf-1] - AssertionError
```

**Comment by ilayn** [comment]
Should be down to a single failure now without any segfaults or other issues.

**Comment by ilayn** [comment]
Well, emphasis on "*should*" I guess.

**Comment by mdhaber** [comment]
Note that the complaint on the mypy job is different from the rest.

**Comment by ilayn** [comment]
Yes LevyStable failure is a tough one because the error builds up very slowly after calling lots of calls to `DQAWFE` and afterwards `DQAWPE`. I don't understand why one of the tests crashed on special test though. I tested those almost continuously throughout the week in both Win and Linux. Let me spend some more time on this.

**Comment by ilayn** [comment]
Found the error in Levy Stable, but it seems like this test does multiple calls in one invocation, and only two of those calls are problematic. I could not decipher what the inputs are yet. But hopefully tomorrow I'll take another shot by recording the inputs at the function entrance and see where it goes wrong.

image

**Comment by ilayn** [comment]
Not sure about why macOS runners did not pick up but seems like we are back to normal. I'll fix the clang error which is about C17. And then see if I have the chops to use your excel file.

**Comment by mdhaber** [comment]
> And then see if I have the chops to use your excel file.

Hah it really should just run if you have those dependencies. If not, LMK; you shouldn't have to debug that. 
Now there is still the benchmark failure though : /

**Comment by mdhaber** [comment]
I ran the script and the translation is working well! There is no performance regression, and most of the integrals and errors match up closely. Here are a few integrals where `main` is more accurate on my computer.

```python3
import numpy as np
from scipy import integrate
integrate.quad(lambda x: np.sin(100*np.pi*x)/(np.pi*x), 0.1, 1)  # analytical: 0.00909863753916684
integrate.quad(lambda x: np.exp(x)*np.sin(3*x)*np.tanh(5*np.cos(30*x)), -1, 1)  # analytical: -0.0177905930768788

# There were a few others with oscillatory integrands; this is the only one without
# Maybe an unfair comparison, since it reaches the maximum number of subdivisions
integrate.quad(lambda x: 1/np.log(1/x)**3/x, 0, 0.5)  # analytical: 1.0406844905028
```

**Comment by ilayn** [comment]
Thanks Matt, great to hear that verification runs OK except some corners. I will check them out. I did not manage to filter out what to call is to the benchmark suite but probably your explicit examples will also cover that issue too (if I have to speculate).

**Comment by ilayn** [comment]
OK I think I found the culprit. Let's see if it makes the benchmark happy first. Then I'll rebase and add the docstrings etc.

**Comment by ilayn** [comment]
Now all your examples agree with main except this one 

```python
integrate.quad(lambda x: np.sin(100*x)/x, -0.1, 0.1)  # analytical: 3.31669518843774
```
actually hit the analytical number. Not sure why but I'll take it :)

**Comment by mdhaber** [comment]
OK, I'll start trying to hit some of the other routines within QUADPACK!

**Comment by mdhaber** [comment]
Another one this hits almost on the nose that fails in main is:
```python3
integrate.quad(lambda x: x/np.sin(x), -1.5707963267949, 1.5707963267949)
```

For 2/3 of the problems, the difference between the two is zero. For only 20 problems is the difference between the two greater than `1e-13`. For those, the error (difference between numerical and analytical result) is usually smaller in the PR than in main, and if not, it is always within an order of magnitude. The number of function evaluations is almost always the same. So although not bit for bit identical, the PR QAGSE routine seems just as good as in main - if not better by a hair.

To look at QAGIE, I made the upper limit of integration infinite for all of these problems. One thing that jumped out at me is that the maximum number of function evaluations in main is 1485 vs 1515 in this PR, and there are *many* problems that hit these limits. One example is the infinite sine integral:

```python3
integrate.quad(lambda x: np.sin(x)/x, 0, np.inf)
```
They get the same answer, `2.2478679634689205`, which is different from the true value of $\pi/2$. (`1.5707963267948966`). Would it be good to track down these extra function evaluations before comparing in more detail?

**Comment by ilayn** [comment]
Thank you for the analysis. I also ran the script and saw similar results. 

> Would it be good to track down these extra function evaluations before comparing in more detail?

Not sure if I can get an answer, but definitely let me check why that might be happening.

**Comment by ilayn** [comment]
Found it :) I was counting the evals wrong. See the last commit. Great catch!

**Comment by josef-pkt** [comment]
I did not look at this PR, just one question

How good is the test or benchmark coverage for non-smooth functions, kinks and jumps?

I have been using it recently integrate.quad for brute force integration of functions that have kinks and jumps and it works reasonably well. Well enough that I didn't bother trying to improve the integration by providing function specific hints.
(main applications: expectation of nonlinear functions wrt. normal distribution using `stats.norm.expect` in statsmodels.robust.)

**Comment by ilayn** [comment]
I did the gcovr builds and checked the output. We are hitting pretty much all corners except the wrong input checking branches that return with error since they are very hard to compose a problem that will evolve into a state that will hit those parts. I don't know how to do coverage for Fortran code (another reason for this translation effort) but I am cautiously positive that we are hitting all the functional parts with the test suite and Matt's extra functions.

**Comment by ilayn** [comment]
Lastly, I've added the docstrings and the license info. That seems to conclude things from my side. Let me know if you have any other comments.

**Comment by mdhaber** [comment]
[Here](https://drive.google.com/drive/folders/1tVrTFJqc-DbY0SfzCR7vQA_NCcotEObr?usp=sharing) are a bunch of result files on Google Drive. I hope the column names are self-explanatory. The file names indicate the QUADPACK routine I was trying to hit.

`qagie1` has an infinite upper limit of integration like:
```python3
integrate.quad(lambda x: 4/(1+x**2), 0 , np.inf)
```
`qagie2` has an infinite lower and upper limits of integration like:
```python3
integrate.quad(lambda x: 4/(1+x**2), -np.inf , np.inf)
```
I confirmed that the reported number of function evaluations equals the actual number of function evaluations, so the discrepancies in function evaluations between main and PR are real. The PR almost always does more function evaluations, so that might be something to investigate further. For a lot of these test cases, though, the integral is not a finite number, so keep that in mind when looking at the results. I need to take a closer look myself to get much more out of these (e.g. pay closer attention only when the estimated error is small relative to the result).

`qagpe` specifies the point `x = 0` as a break point and includes it in the integration interval by making the left limit of integration `-1`. Because many of these integrands are not real-valued at negative abscissae, I did arithmetic in the complex domain and took the real part. A great example is:
```python3
integrate.quad(lambda x: np.cos(np.log(x + 0j)).real, -1, 1, points=(0,))
```
Agreement seems to be much better here - maybe because QUADPACK is just breaking the interval at `0` and doing QAGSE, which we've already nailed down.

There is a lot more here, but I can't write about it tonight. I'll complete this post later.

**Comment by ilayn** [comment]
Very nice! No rush, take your time. Troubleshooting is much easier than translations and we can investigate failing cases one by one.

**Comment by ilayn** [comment]
I've started to look into the qawce issues. This is basically due to how goto is converted to if then else in my code. Because the function `np.sin(3*x)*np.cos(2*x)/np.sin(x)` has singularities at 0.0, this in turn causes certain initialization of elements to be marked as NaN.

But in fortran code,

```fortran
   15   if(error2.gt.error1) go to 20
        print *,"ENTERED TOP BRANCH"
        alist(last) = a2
        blist(maxerr) = b1
        blist(last) = b2
        elist(maxerr) = error1
        elist(last) = error2
        go to 30
   20   alist(maxerr) = a2
        print *,"ENTERED BOT BRANCH"
        alist(last) = a1
        blist(last) = b1
        rlist(maxerr) = area2
        rlist(last) = area1
        elist(maxerr) = error2
        elist(last) = error1
```

is converted to 

```C
        if (error2 <= error1)
        {
            printf("ENTERED TOP BRANCH\n");
            alist[L] = a2;
            blist[maxerr] = b1;
            blist[L] = b2;
            elist[maxerr] = error1;
            elist[L] = error2;
        } else {
            // 20
            printf("ENTERED BOT BRANCH\n");
            alist[maxerr] = a2;
            alist[L] = a1;
            blist[L] = b1;
            rlist[maxerr] = area2;
            rlist[L] = area1;
            elist[maxerr] = error2;
            elist[L] = error1;
        }
```

There are many places that this is not considered since function is considered to be well behaving across quadpack. But not sure if we should correct this or not. 

To be honest, it is more or less an accident that we end up with `NaN` on the fortran side since the result is the sum of this array 

```
 rlist[           1 ]=  -1.3311941766899151E-007
 rlist[           2 ]= -0.69787281552267089
 rlist[           3 ]= -0.45357278015863728
 rlist[           4 ]=                       NaN
 rlist[           5 ]= -0.22385949400615590
 rlist[           6 ]= -0.13655845873144629
 rlist[           7 ]=  -9.0207778789895457E-002
 rlist[           8 ]=  -6.1730046356216615E-002
 rlist[           9 ]=  -4.2953031743864778E-002
 rlist[          10 ]=  -3.0131174723920615E-002
 rlist[          11 ]=  -2.1221562203731156E-002
 rlist[          12 ]=  -1.4976226425519518E-002
 rlist[          13 ]=  -1.0579323457890689E-002
 rlist[          14 ]=  -7.4770152091656137E-003
 rlist[          15 ]=  -5.2857422153277135E-003
 rlist[          16 ]=  -3.7371225928298588E-003
 rlist[          17 ]=  -2.6423815637763412E-003
 rlist[          18 ]=  -1.8683882397898433E-003
 rlist[          19 ]=  -1.3211296012454821E-003
 rlist[          20 ]=  -9.3417248999874344E-004
 rlist[          21 ]=  -6.6055715342796953E-004
 rlist[          22 ]=  -4.6708354133149187E-004
 rlist[          23 ]=  -3.3027762082785291E-004
 rlist[          24 ]=  -2.3354143270808503E-004
 rlist[          25 ]=  -1.6513869092947705E-004
 rlist[          26 ]=  -1.1677067410862238E-004
 rlist[          27 ]=  -8.2569330522467931E-005
 rlist[          28 ]=  -5.8385331781685910E-005
 rlist[          29 ]=  -4.1284663395253214E-005
 rlist[          30 ]=  -2.9192665222584565E-005
 rlist[          31 ]=  -2.0642331449698826E-005
 rlist[          32 ]=  -1.4596332524434493E-005
 rlist[          33 ]=  -1.0321165665898036E-005
 rlist[          34 ]=  -7.2981662714000249E-006
 rlist[          35 ]=  -5.1605828927640504E-006
 rlist[          36 ]=  -3.6490831543169335E-006
 rlist[          37 ]=  -2.5802912887053843E-006
 rlist[          38 ]=  -1.8245415387955102E-006
 rlist[          39 ]=  -1.2901457801660343E-006
 rlist[          40 ]=  -9.1227094842421771E-007
 rlist[          41 ]=  -6.4507281051527166E-007
 rlist[          42 ]=  -4.5613591384404065E-007
 rlist[          43 ]=  -3.2253646260047225E-007
 rlist[          44 ]=  -2.2806660895129083E-007
 rlist[          45 ]=  -1.6126728191453851E-007
 rlist[          46 ]=  -1.1403406034294896E-007
 rlist[          47 ]=  -8.0633635392623890E-008
 rlist[          48 ]=  -5.7014034070263435E-008
```

which gives `NaN` on main.

However, if I fix all the comparisons to double negatives, this PR exits this problem after a single spin since it encounters the NaN and no inequality is satisfied. 

From this I have the conclusion that this code is not meant for functions with singularities or just accidental that it handles them.

**Comment by ilayn** [comment]
So if I have to speculate freely, certain things are getting proper results instead of segfaults in this PR compared to the original code as NaN and Inf propogation is not handled in the old code and people just accepted over time.

**Comment by ilayn** [comment]
> Often we're getting many more function evaluations before it decides to give up, though:

            integrate.quad(lambda x: np.sqrt(1-x**2), 0, np.inf, weight='sin', wvar=1.0)

> That's 17250 in main and 75750 in this PR.

Same reason was causing this. I will need to convert the whole codebase use double negatives apparently.

**Comment by ilayn** [comment]
I've pushed a commit specifically for this so you can also test them. If we are not satisfied then we can roll it back.

**Comment by mdhaber** [comment]
Which tests should I run with it? `qawce`?

**Comment by ilayn** [comment]
Sorry for the recent failure, I converted one too many inequalities. Now should be fine.

**Comment by mdhaber** [comment]
The discrepancy you were referring to in https://github.com/scipy/scipy/pull/21201#issuecomment-2249742738 seems to be resolved, and several others seemed to be fixed at the same time. There are still about 90 others. The worst one that remains is probably:
```
import numpy as np
from scipy import integrate

def f(x):
    return (np.cos(x)-np.sin(x))/(np.cos(x)+np.sin(x))*x

integrate.quad(f, 0, np.inf, weight='sin', wvar=1, full_output=True)[2]['neval']
```
I get `39300` in main and `71820` with the latest commit.

It's probably not realistic to get everything lining up exactly. It might be helpful to have a third person to assess which discrepancies are important.

**Comment by mdhaber** [comment]
Actually there are several in which the latest commit has *fewer* iterations than in main and in some cases it's not a good thing. For instance:
```
import numpy as np
from scipy import integrate

def f(x):
    return 1/(1+np.tan(x)**3)

integrate.quad(f, 0, np.inf, weight='sin', wvar=1)
```
In the PR, I get no warnings and a result of `(0.2977844936463344, 4.908718431728687e-10)` after 18720 iterations, but in main, there is a warning about the maximum number of cycles, and the result is `(0.3051108641494791, 27.776497690706137)` after 64830 iterations.

**Comment by ilayn** [comment]
Hmm, this shows that there are still places that I did not fix. I thought I went through all of them but apparently missed a few. Let me check.

**Comment by ilayn** [comment]
With the last commit things lined up properly for both problems above for me;

> I get 39300 in main and 71820 with the latest commit.

the numbers I get from both main and this PR is 54015. 

There was a single algorithmic bug but the rest was mostly due to catastrophic cancellations and operation orders and hence took me quite some time to find them.

I left it as a separate commit for now but in case you are also seeing the same similar results then I'll fold it into the C file commit so that it stays sane. Otherwise please let me know if you find any other discrepancies. You really found some deep dark places indeed hence hats off.

**Comment by ilayn** [comment]
@rgommers With the last commit I carried over the GIL details here, is that sufficient or should I do something else in the meson side?

**Comment by rgommers** [comment]
> @rgommers With the last commit I carried over the GIL details here, is that sufficient or should I do something else in the meson side?

The changes in `meson.build` look fine to me. I looked through all the new C code, and that largely looks fine. The one thing that needs attention is the callback mechanism - `ccallback.h` uses thread-local storage and seems to be fairly carefully written, but still the code that uses it needs exercising in multi-threaded tests. I've made a note of that in gh-20669, let's not mix it into this PR.

**Comment by ilayn** [comment]
Thanks Ralf sounds good to me. I did not do anything specific regarding the multithreading hence it is indeed better to test it properly.

In the meantime I did some more tests with Matt's testing mechanism with infinite integrals and they seem to be in agreement with main with/out the warnings, hence I think we are good with this one. But we can always revisit in case the nightlies uncover something. 

Thanks a lot @mdhaber for the thorough testing and everyone for the help.

**Comment by mdhaber** [comment]
Here are a few remaining discrepancies that might be worth checking out:

QAWOE:
```python3
import numpy as np
from scipy import integrate

def f(x):
    return 1/np.log(1/x)**3/x

res = integrate.quad(f, 0, 0.5, weight='cos', wvar=1., full_output=True)
print(res[0], res[1], res[2]['neval']) 
# before: 0.9732677628602296 8.077384222593409e-07 1485
# after: 0.9732570039506375 5.453762165430476e-06 1275
```

```python3
import numpy as np
from scipy import integrate

def f(x):
    return (x**5-1)/x/np.log(x)**2-5/np.log(x)

res = integrate.quad(f, 0, 1, weight='cos', wvar=1., full_output=True)
print(res[0], res[1], res[2]['neval']) 
# before: 2.2288220193686836 7.971556617691888e-05 1485
# after: 2.2297787141057044 0.0001842835140855037 1305
```

QAGPE:
```python3
import numpy as np
from scipy import integrate

def f(x):
    return x/(np.sin(x)+np.cos(x))/np.sin(x)

res = integrate.quad(f, -1, 1.5707963267949, full_output=True, points=(0.,))
print(res[0], res[1], res[2]['neval']) 
# before: -0.9792966888282281 0.04570645829321163 2058
# after: -0.9695460842973103 0.30532522085639935 2058
# SciPy 1.13.1 on Colab: -0.9695461499435704 0.3053252645164952 2058
# so this one must be numerically sensitive
```

I can also provide some examples of QAWFE where the number of function evaluations doesn't match (but in these cases, the integral probably doesn't converge and the results are garbage both before and after).

You must have fixed a bug in QAWSE with `alg-loga` weights. There are hundreds of discrepancies, but I've checked several against mpmath, and the new version is always more accurate - even when the new version does fewer function evaluations.

There are also many discrepancies before and after for QAGIE. However, most of these problems are divergent and/or run into complex domain issues, so it's hard to tell whether there are important discrepancies. When I try to force the integrals to converge by manually adding a `np.exp(-x**2)` weight to the integrand (and for doubly-infinite limits of integration, doing the math in the complex domain and taking the real part), there are only a few discrepancies left. In these cases, I've only seen discrepancies when the integral still doesn't exist (I think) or when the discrepancy is smaller than the error estimate. In the latter case, I've checked a few of the integrals with `mpmath`, and the agreement between the two `mpmath` methods agreement is worse, so the integrals must be challenging, so perhaps these can be forgiven.

**Comment by ilayn** [comment]
Very nice! I think most of the discrepancies are started to go into the compiler differences. Not saying there are no bugs left but I started to see that same inputs starting to give different decimals on fortran side and C side. I'll definitely check these ones anyways. Please put any examples if you think they are suspicious. The more the better. 

> You must have fixed a bug in QAWSE with `alg-loga` weights

I wish I can say that I did it on purpose but probably it was some edge case that I subconsciously fixed while reading the code or it was f2py playing some tricks that we no longer have.

> When I try to force the integrals to converge by manually adding a np.exp(-x**2) weight to the integrand (and for doubly-infinite limits of integration, doing the math in the complex domain and taking the real part), there are only a few discrepancies left. 

If you have them ready please add to above. I'd be happy to take a look. In fact when I fix a slight issue, typically 10 - 15 examples resolve simultaneously.

>  I've only seen discrepancies when the integral still doesn't exist (I think) or when the discrepancy is smaller than the error estimate.

This is certainly possible. Fortran77 arithmetic is probably slightly different than math library of C which I see with `log` function (admittedly very small differences). However when things are diverging these might be playing some role.

**Comment by mdhaber** [comment]
It sounds like you were able to run the original script? For reproducibility, I branched it into a copy for each QA*** routine and `weights` option, and all that and the results are at the original link:
https://www.dropbox.com/scl/fo/yv8lgxf3qbrb0cin9ba6e/AMJbgk8xfbxbTYOzvhOhJV4?rlkey=iqaze0cwpr8r8nc238srzqfur&dl=0

To see the discrepancies, just open the Excel files for QAWFE and and QAGIE and look for red.

You are probably right about the arithmetic differences being the root cause. For instance, I tried out the first three discrepant cases in the QAWFE Excel file in Colab, e.g.:
```python3
import numpy as np
from scipy import integrate

def f(x):
    return np.exp(x**2*(1-x)**2)

res = integrate.quad(f, 0, np.inf, weight='sin', wvar=1., full_output=True)
print(res[0], res[1], res[2]['neval']) 
```
Colab with SciPy 1.13.1 gives the same result as main does *now*, after the PR; it's only my PC before the PR that gives a different number of function evaluations.

**Comment by mdhaber** [comment]
Ah, another interesting thing: on my mac, there are 203 discrepancies in QAGSE (vanilla, no weights, finite limits, etc.). There are 0 on my PC. Similar for many other routines. So I think a lot of what we might find now is indeed due to differences between the underlying math libraries.

**Comment by ilayn** [comment]
> There are 0 on my PC.

So that's why I have not been able replicate some of the discrepancies you mentioned previously. I'll do a round of red marks and check the ones I can reproduce. 

I think I know why the last one is slightly off. That's probably an off-by-1 error from the Fortran to C indexing.

**Pull request merged**
