### PR TITLE
MAINT: free-threading: declare HiGHS, `ndimage._rank_filter_1d` safe

### PR DESCRIPTION
**Pull request by rgommers**
- Pulls in https://github.com/scipy/HiGHS/pull/70
- The other two changes were missed previously in gh-21199

### CODE REVIEW

**Comment by rgommers** [comment]
Found two more, those really should be the last ones (🤞🏼). Added as a second commit; please feel free to squash them.

**Review by tylerjereddy — COMMENTED** [review]
I don't see any obvious issues in the diff.  I noticed the CI *does* seem to use `--parallel-threads` testing on Linux, but went ahead and did some local testing on this branch vs. `main` for those subpackages that get touched here (on a machine with probably more cores than the CI).

I had "moderate" issues on x86_64 Linux with two of the modules on this branch that I didn't see on main with `3.13t` and `PYTHON_GIL=0`:

- I had to cancel/restart this one because of perhaps-flaky hang/slow test: `python dev.py test -j 16 -t scipy/integrate/tests/ -- --parallel-threads=10` (the restart passed just fine)
- This one had a single flaky test that passed the second time: `python dev.py test -j 16 -t scipy/optimize/tests/ -- --parallel-threads=10`
  - `FAILED scipy/optimize/tests/test_nonlin.py::TestLinear::test_krylov - scipy.optimize._nonlin.NoConvergence: [  8.33817876  13.04954042 -13.34052329  -8.19259511   2.10018891`

It may be best for you to judge these observations--maybe higher levels of parallel stress will be dealt with later if they are concerns.

**Comment by rgommers** [comment]
> It may be best for you to judge these observations--maybe higher levels of parallel stress will be dealt with later if they are concerns.

Yeah that will be unrelated. The only thing this PR does is avoid these extension modules re-enabling the GIL on import and emitting a warning about doing so. It has the same effect as you using `export PYTHON_GIL=0`. It can't really cause the test issues you saw - this PR is essentially trivial plumbing.

There are certainly issues left to be fixed with `--parallel-threads`, some of which have open PRs and some of which are yet to be discovered or dealt with. We'll deal with those before enabling `pytest-run-parallel` in a CI job.

**Comment by tylerjereddy** [comment]
The testing was thorough enough here and conversation above explains the rest, squash merging based on request to do so.

**Pull request merged**
