### PR TITLE
MAINT: bump pybind11, mark C/C++/Cython extension modules as safe to run without the GIL

### PR DESCRIPTION
**Pull request by rgommers**
This bumps the lowest supported version of `pybind11` to 2.13.1, which is the minimum version needed to be able to use the support for free-threaded Python.

It also marks all extension modules written in C, C++ and Cython as safe to run without the GIL (EDIT: as documented at https://py-free-threading.github.io/porting/#declaring-free-threaded-support). There are probably some remaining problems waiting to be uncovered, but we've been running without the GIL (via `PYTHON_GIL=0`) in CI for a while now and at least the test suite is quite stable (partly due to limited testing with `threading` & co). So this should be fine to do now, making it easier for downstream users to start testing with a free-threaded interpreter.

The part that is still missing is extension modules generated by `f2py` and by `pythran`. That generated code must be modified in the future via CLI flags (similar to how it works for Cython), but support hasn't yet landed upstream. I'll add an item to gh-20669 to keep track of that.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Are we planning to backport free-threading support for the `1.14.1` release? I guess I'm looking at the commits here and extent of https://github.com/scipy/scipy/issues/20669 and wondering how messy it will be.

**Review by andfoy — APPROVED** [review]
Looks good to me, minus updating the issue tracker list for the reasons why the C modules were greenlit as free-threaded compliant. e.g., `integrate`, `special`. It seems this was done for other modules that do not have an specific PR like `fft`.

I'm assuming that all Cython modules will be tested at a later time. Maybe it would be good to update the tracking issue to mark which modules are missing threading tests?

**Comment by rgommers** [comment]
> minus updating the issue tracker list for the reasons why the C modules were greenlit as free-threaded compliant. e.g., `integrate`, `special`. It seems this was done for other modules that do not have an specific PR like `fft`.

The expectation is that all C/C++/Cython code marked as compatible here is either 100% compatible or largely compatible. We're confident that it's at least that because we have been testing with `PYTHON_GIL=0` for almost 2 months now. The goal of marking them as compatible is to make it easier to have downstream packages and end users use free-threaded Python, and if we get bug reports we'll fix them as soon as we can.

Re the tracking issue: I marked several modules that required no changes but which I fully audited as done (e.g., `fft`). For others (e.g., `special`) that wasn't done yet, so I don't have enough confidence to really mark them as compatible.

> Maybe it would be good to update the tracking issue to mark which modules are missing threading tests?

We cannot reasonably write manual multi-threaded tests for everything, and also that will blow up the regular runtime of the test suite. We should only add multi-threaded tests to places where we need to test for regressions or expect issues. And aside from that we should be getting a new pytest plugin to be able to test everything in a multi-threaded fashion automatically, without source-level changes to the test suite.

**Comment by rgommers** [comment]
Could I interest someone in hitting the green button here (maybe @tylerjereddy or @andyfaff)?

**Review by tylerjereddy — APPROVED** [review]
I resolved the merge conflict in `scipy/special/_special_ufuncs.cpp` because of the `xsf` renaming that just got merged in. I installed Python `3.13.0rc1` free-threaded interpreter locally on MacOS ARM and confirmed that on this branch i.e., `PYTHON_GIL=0 python dev.py -n test -j 16` after building with accelerate passes the full suite.

I did notice a few complaints about the Python header inclusion order in `python dev.py lint`, but if any of those are actually real they can be dealt with in a follow-up.

The changes look correct to me as well based on i.e., https://py-free-threading.github.io/porting/ (I guess we mostly use single-phase init). I'm not a free-threading CPython expert but sounds like we want to find some of the rough edges by adding tentative support and dealing with feedback from consumers.

**Comment by rgommers** [comment]
Thanks Tyler! And yes indeed, we only use single-phase initialization.

**Pull request merged**
