### PR TITLE
Fixed docstring for resample

### PR DESCRIPTION
**Pull request by cB-Abhinav-Gautam**
fixed documentation for resample 

#9273

### CODE REVIEW

**Comment by rgommers** [comment]
CI failures are odd, but indeed unrelated to this PR. Merging. Thanks @Gotham13121997

**Comment by rgommers** [comment]
damn, missed that this PR was against the wrong branch. will fix that up right now.

@Gotham13121997 please always send PRs against `master`.

**Comment by Gotham13121997** [comment]
wait, this pr fixes the documentation of scipy 1.6 which had wrong
documentation. the latest one has right.

**Comment by Gotham13121997** [comment]
as mentioned in #9273

**Comment by rgommers** [comment]
we never go back and edit old docs/releases, unless we plan on making a new release. if it was already correct on master, then there was nothing to do

**Comment by rgommers** [comment]
I have now removed the commit in this PR and the merge commit again. BTW, branch protection works, it makes it nontrivial to force-push, which is good

**Comment by Gotham13121997** [comment]
Well I am sorry for this issue then. I will keep this in mind in future

**Comment by rgommers** [comment]
No worries @Gotham13121997, thanks for helping to improve SciPy:)

**Pull request merged**
