### PR TITLE
DEP: Deprecation follow-ups

### PR DESCRIPTION
**Pull request by h-vetinari**
Some leftovers from:
* 7151e90e7d3480cd82e9e1f2c104d7e76507055f: #16067 / https://github.com/scipy/scipy/pull/15054  CC @j-bowhay 
* f264e9720a1bccb032f0bbc94ba5796240dd38b8: #15749 / https://github.com/scipy/scipy/pull/15083 CC @tirthasheshpatel
* f5cf643b22ffe032ac1cadb1438412120fe992f2: #15934

### CODE REVIEW

**Comment by h-vetinari** [comment]
@mdhaber

Where would you prefer the warning for the frozen gilbrat distribution? On the methods or just on initialisation?
```
g = gilbrat(1)   # <- warn here?
g.pdf(1)         # <- or warn here?
```

**Comment by h-vetinari** [comment]
> Where would you prefer the warning for the frozen gilbrat distribution? On the methods or just on initialisation?
> 
> ```
> g = gilbrat(1)   # <- warn here?
> g.pdf(1)         # <- or warn here?
> ```

I currently implemented the latter, but I think it could be quite noisy (basically every method on that frozen distribution would raise a separate warning), and also slightly misleading (in that the code that needs to change is the freezing and not the method call after), so now I'm tending towards switching to the former.

**Comment by h-vetinari** [comment]
Thanks for taking a look @mdhaber! :)

**Review by mdhaber — APPROVED** [review]
I approve the `gibrat` stuff.

**Review by tupui — APPROVED** [review]
And the rest LGTM. Thanks @h-vetinari.

Note: please continue to keep track of deprecations on the release note PR.

**Pull request merged**
