### PR TITLE
DEP: execute sparse array API deprecations

### PR DESCRIPTION
**Pull request by h-vetinari**
Follow-up to #18507

### CODE REVIEW

**Comment by h-vetinari** [comment]
Two seemingly unrelated warnings in the doc build:
```
Running Sphinx v7.3.2
WARNING: The config value `nb_execution_excludepatterns' has type `list'; expected `Any'.
SciPy (VERSION pull/20499)
[...]
reading sources... [ 97%] tutorial/interpolate/1D
<string>:19: DeprecationWarning: invalid escape sequence '\s'
reading sources... [ 97%] tutorial/interpolate/ND_regular_grid
```
and another unrelated test failure in `Linux Meson tests / Linux - 32 bit`:
```
scipy/sparse/linalg/_isolve/iterative.py:842: in gmres
    x += y @ v[:col+1, :]
E   RuntimeWarning: invalid value encountered in matmul
[...]
=========================== short test summary info ============================
FAILED scipy/sparse/linalg/_eigen/arpack/tests/test_arpack.py::test_hermitian_modes
= 1 failed, 48288 passed, 2230 skipped, 14574 deselected, 567 xfailed, 13 xpassed in 823.38s (0:13:43) =
```

The benchmark failures are real though...

**Review by j-bowhay — APPROVED** [review]
Thanks @h-vetinari

**Comment by h-vetinari** [comment]
CC @perimosocordiae, in case you want to double check that this has been done correctly.

**Review by perimosocordiae — APPROVED** [review]
Looks good, thanks for cleaning this up!

**Pull request merged**
