### PR TITLE
BUG: Allow odd-length windows to be periodic ("DFT-even") too

### PR DESCRIPTION
**Pull request by endolith**
Fixes https://github.com/scipy/scipy/issues/2190 and https://github.com/scipy/scipy/issues/4551 per the discussion on those pages.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Looks like this causes some failures

https://travis-ci.org/scipy/scipy/jobs/151387369

**Comment by endolith** [comment]
Yes, they're in `signal.spectral.welch` and `signal.spectral.csd`, tests created by @e-q and @ewmoore 

- `test_integer_onesided_odd`
- `test_real_onesided_odd`
- `test_real_onesided_odd_32`

I don't know welch/csd to know whether this is a real problem or not.  I'll try to look when I have time.

**Comment by e-q** [comment]
Those failing tests are tests against hardcoded values, so it doesn't surprise me that they would fail when changing the default behavior of odd length windows. I think it would be fine to either to update the hardcoded values or change these tests to explicitly use aperiodic odd length windows.

**Comment by e-q** [comment]
Failures look like PEP8 in `test_windows.py` and outdated values in a tutorial.

**Comment by Eric89GXL** [comment]
Yep, fixing those should make the CIs happy

**Comment by endolith** [comment]
Ok, fixed those.  I want to review all these PRs and finish all these things I started but I've been busy, sorry.  Feel free to fix my mistakes for me.  :D

**Comment by e-q** [comment]
Merging, thanks @endolith!

**Pull request merged**
