### PR TITLE
BUG: special: Fix a couple issues with the 'double-double' code in cephes/dd_*

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
This fixes two bugs in the double-double code in cephes/dd_real.c:

* dd_exp(0) was incorrectly returning inf; this has been fixed to return 1.
* dd_expm1(x) was not returning correct values--the code did not handle the
  low component of the double-double argument correctly.  The function has
  been reimplemented by porting an implementation from Boost Math.

Other changes:

* The predefined double-double constant DD_C_NEGONE, equal to -1, is
  added.
* The double-double functions polyeval() and polyroot() are renamed to
  dd_polyeval() and dd_polyroot() for consistency.
* In dd_real.c, don't include "mconf.h".  "mconf.h" redefines some math
  std library names and results in the dd_* code depending on more of
  cephes than necessary.
* Created the Cython module special/_test_dd.pyx which wraps the functions
  dd_exp, dd_log and dd_expm1 as Python functions so they can be tested
  with unit tests in Python.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
I've been looking into using the double-double functions in some new ufuncs, and failing tests of these ufuncs led to finding the bugs in the functions `dd_exp` and `dd_expm1`

None of the existing ufuncs in `special` use the affected double-double functions, so this PR doesn't fix any bugs in existing code.  However, I also discovered a bug in `dd_log1p`, and that function *is* used in `kolmogorov.c`.  I'll get back to that bug later.

**Comment by WarrenWeckesser** [comment]
@pvanmulbregt, this PR replaces the implementation provided for `dd_expm1` that you added in https://github.com/scipy/scipy/pull/8551.  The problem with the original implementation can be demonstrated with,  for example, any `double2` input of the form `a = {x0, 0.0}`.  The return value is `{expm1(x0), 0.0}`--it doesn't compute the full double-double result.  I couldn't see a simple fix, so in this PR I replaced it with Boost's quad precision implementation ported to use the `double2` code.

I'm poking the double-double code now because I am working on a PR that will use it as a fallback when it is detected that using the `double` type loses too much precision.  That PR depends on `dd_expm1`.

**Comment by WarrenWeckesser** [comment]
Rebased and updated to not use npymath.

**Comment by rgommers** [comment]
Thanks @WarrenWeckesser, this looks quite good to me. My main question is related to `_test_dd.pyx`. Cython is extremely slow (~1.6 sec to generate `_test_dd.c` for me) and generates bulky extension modules, so I'm not a big fan of these little test extensions. What do you think about combining it with `_test_round.pyx`?

**Comment by WarrenWeckesser** [comment]
> What do you think about combining it with _test_round.pyx?

Good idea.  I pushed an update, let me know what you think.

**Review by rgommers — APPROVED** [review]
LGTM, in it goes. Thanks Warren!

**Pull request merged**
