### PR TITLE
BUG: Add to ignore

### PR DESCRIPTION
**Pull request by larsoner**
After spending way too much time trying to fix the errors that now crop up with Pytest 3.8:
```
can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```
I found out they are caused by an upstream Cython bug (https://github.com/astropy/astropy/issues/6025). So for now we should probably ignore these.

### CODE REVIEW

**Comment by pv** [comment]
why is renaming qhull directory necessary?

**Comment by larsoner** [comment]
On Python2 you get:
```
E   ImportWarning: Not importing directory '/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/spatial/qhull': missing __init__.py
```

**Comment by pv** [comment]
I see. Not sure if it's good for Python to warn about that though ...

**Comment by pv** [comment]
Ok, travis is green so merging.

There are some leftover references to the renamed directories e.g. in gitignore, which should still be changed.

**Comment by larsoner** [comment]
> There are some leftover references to the renamed directories e.g. in gitignore, which should still be changed.

I can take care of this unless you are already on it

**Comment by pv** [comment]
Please go ahead. Thanks!

**Pull request merged**
