### PR TITLE
MAINT: Update vendored uarray, required for auto-dispatching

### PR DESCRIPTION
**Pull request by AnirudhDagar**
#### Reference issue
See #14266 

#### What does this implement/fix?

> 1. We need to update the vendored version of uarray used in SciPy. This is because the current uarray vendored version in SciPy doesn't support options like try_last=True which got added later in uarray #236.

The vendor uarray lib needed an update regardless of points 2 and 3 in the solution for #14266. It has now been almost two years since the last update was made. 

#### Additional information
This will also later enable us to help with automatically setting the global backend on import of the library if the discussion in #14266 is in favour of the proposal.

**Edit**: We also need to update the fft module [`fft._backend.py`](https://github.com/scipy/scipy/blob/master/scipy/fft/_backend.py) once this is good to go. I'll send a subsequent PR for that.

Looking forward to the feedback/review. Please let me know in case there is something I might have done wrong so that I can make the required changes.

### CODE REVIEW

**Comment by rgommers** [comment]
This looks good from a quick scan. Are you still exploring whether to turn this into a git submodule @AnirudhDagar, or is there a blocker for that?

**Comment by AnirudhDagar** [comment]
Yeah, I wanted do that but as discussed earlier I'm not sure if git submodule can be patched.
Here the patch fixes the version for vendor `uarray` code and if we go to the submodule route, we'll have to depend on `versioneer` (`uarray`'s version string is generated by `versioneer` so to not have SciPy depend on it, we need to edit the `__init__.py`) 

Ps. I'll take a look at the failed build. (It was building fine for me locally)

**Comment by rgommers** [comment]
Okay, thanks - good to know! Maybe not worth looking into more right now. Also, I really don't like `versioneer` so happy to not pick that up:)

**Comment by peterbell10** [comment]
@AnirudhDagar the build failures should be fixed by Quansight-Labs/uarray#257

**Comment by AnirudhDagar** [comment]
The tests on the python 3.7 debug build are failing. I tried to run the build and tests on a Linux machine in py3.7 env and everything worked fine.
But here the CI hints to an issue with fft tests:
```bash
Current thread 0x00007f826c65d740 (most recent call first):
  File "/home/runner/work/scipy/scipy/build/testenv/lib/python3.7/site-packages/scipy/_lib/_uarray/_backend.py", line 274 in set_backend
  File "/home/runner/work/scipy/scipy/build/testenv/lib/python3.7/site-packages/scipy/fft/_backend.py", line 148 in set_backend
  File "/home/runner/work/scipy/scipy/build/testenv/lib/python3.7/site-packages/scipy/fft/tests/test_backend.py", line 51 in test_backend_call
```
@peterbell10 any ideas? Thanks! :))

**Comment by peterbell10** [comment]
Test failures fixed in Quansight-Labs/uarray#258. Just a false-positive assert failure.

**Review by peterbell10 — APPROVED** [review]
LGTM. I'll let someone else merge as a lot of this is my code.

**Review by rgommers — APPROVED** [review]
This LGTM, it was already reviewed upstream, and CI is green - so in it goes.

Thanks @AnirudhDagar! And thanks for reviewing @peterbell10

**Comment by rgommers** [comment]
There a couple of `-Wterminate` build warnings that would be nice to get rid of as a follow-up:

<details>

```
[4/7] Compiling C++ object scipy/_lib/_uarray/_uarray.cpython-39-x86_64-linux-gnu.so.p/_uarray_dispatch.cxx.o
In file included from ../scipy/_lib/_uarray/_uarray_dispatch.cxx:1:
../scipy/_lib/_uarray/small_dynamic_array.h: In instantiation of 'void SmallDynamicArray<T, SmallCapacity>::default_construct_buffer(T*, T*) [with T = std::vector<{anonymous}::backend_options>*; long int SmallCapacity = 1]':
../scipy/_lib/_uarray/small_dynamic_array.h:86:7:   required from 'SmallDynamicArray<T, SmallCapacity>::SmallDynamicArray(size_t) [with T = std::vector<{anonymous}::backend_options>*; long int SmallCapacity = 1; size_t = long unsigned int]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:777:61:   required from here
../scipy/_lib/_uarray/small_dynamic_array.h:37:7: warning: throw will always call terminate() [-Wterminate]
   37 |       throw;
      |       ^~~~~
../scipy/_lib/_uarray/small_dynamic_array.h: In instantiation of 'SmallDynamicArray<T, SmallCapacity>& SmallDynamicArray<T, SmallCapacity>::operator=(SmallDynamicArray<T, SmallCapacity>&&) [with T = std::vector<{anonymous}::backend_options>*; long int SmallCapacity = 1]':
../scipy/_lib/_uarray/_uarray_dispatch.cxx:673:20:   required from 'bool {anonymous}::context_helper<T>::init({anonymous}::context_helper<T>::BackendLists&&, T) [with T = {anonymous}::backend_options; {anonymous}::context_helper<T>::BackendLists = SmallDynamicArray<std::vector<{anonymous}::backend_options>*, 1>]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:796:57:   required from here
../scipy/_lib/_uarray/small_dynamic_array.h:186:7: warning: throw will always call terminate() [-Wterminate]
  186 |       throw;
      |       ^~~~~
../scipy/_lib/_uarray/small_dynamic_array.h: In instantiation of 'void SmallDynamicArray<T, SmallCapacity>::default_construct_buffer(T*, T*) [with T = std::vector<{anonymous}::py_ref>*; long int SmallCapacity = 1]':
../scipy/_lib/_uarray/small_dynamic_array.h:86:7:   required from 'SmallDynamicArray<T, SmallCapacity>::SmallDynamicArray(size_t) [with T = std::vector<{anonymous}::py_ref>*; long int SmallCapacity = 1; size_t = long unsigned int]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:873:61:   required from here
../scipy/_lib/_uarray/small_dynamic_array.h:37:7: warning: throw will always call terminate() [-Wterminate]
   37 |       throw;
      |       ^~~~~
../scipy/_lib/_uarray/small_dynamic_array.h: In instantiation of 'SmallDynamicArray<T, SmallCapacity>& SmallDynamicArray<T, SmallCapacity>::operator=(SmallDynamicArray<T, SmallCapacity>&&) [with T = std::vector<{anonymous}::py_ref>*; long int SmallCapacity = 1]':
../scipy/_lib/_uarray/_uarray_dispatch.cxx:673:20:   required from 'bool {anonymous}::context_helper<T>::init({anonymous}::context_helper<T>::BackendLists&&, T) [with T = {anonymous}::py_ref; {anonymous}::context_helper<T>::BackendLists = SmallDynamicArray<std::vector<{anonymous}::py_ref>*, 1>]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:887:74:   required from here
../scipy/_lib/_uarray/small_dynamic_array.h:186:7: warning: throw will always call terminate() [-Wterminate]
  186 |       throw;
      |       ^~~~~
../scipy/_lib/_uarray/small_dynamic_array.h: In instantiation of 'void SmallDynamicArray<T, SmallCapacity>::move_construct_buffer(T*, T*, T*) [with T = std::vector<{anonymous}::backend_options>*; long int SmallCapacity = 1]':
../scipy/_lib/_uarray/small_dynamic_array.h:181:7:   required from 'SmallDynamicArray<T, SmallCapacity>& SmallDynamicArray<T, SmallCapacity>::operator=(SmallDynamicArray<T, SmallCapacity>&&) [with T = std::vector<{anonymous}::backend_options>*; long int SmallCapacity = 1]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:673:20:   required from 'bool {anonymous}::context_helper<T>::init({anonymous}::context_helper<T>::BackendLists&&, T) [with T = {anonymous}::backend_options; {anonymous}::context_helper<T>::BackendLists = SmallDynamicArray<std::vector<{anonymous}::backend_options>*, 1>]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:796:57:   required from here
../scipy/_lib/_uarray/small_dynamic_array.h:51:7: warning: throw will always call terminate() [-Wterminate]
   51 |       throw;
      |       ^~~~~
../scipy/_lib/_uarray/small_dynamic_array.h: In instantiation of 'void SmallDynamicArray<T, SmallCapacity>::move_construct_buffer(T*, T*, T*) [with T = std::vector<{anonymous}::py_ref>*; long int SmallCapacity = 1]':
../scipy/_lib/_uarray/small_dynamic_array.h:181:7:   required from 'SmallDynamicArray<T, SmallCapacity>& SmallDynamicArray<T, SmallCapacity>::operator=(SmallDynamicArray<T, SmallCapacity>&&) [with T = std::vector<{anonymous}::py_ref>*; long int SmallCapacity = 1]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:673:20:   required from 'bool {anonymous}::context_helper<T>::init({anonymous}::context_helper<T>::BackendLists&&, T) [with T = {anonymous}::py_ref; {anonymous}::context_helper<T>::BackendLists = SmallDynamicArray<std::vector<{anonymous}::py_ref>*, 1>]'
../scipy/_lib/_uarray/_uarray_dispatch.cxx:887:74:   required from here
../scipy/_lib/_uarray/small_dynamic_array.h:51:7: warning: throw will always call terminate() [-Wterminate]
../scipy/_lib/_uarray/_uarray_dispatch.cxx:86:12: warning: 'PyObject* {anonymous}::py_get(PyObject*)' defined but not used [-Wunused-function]
   86 | PyObject * py_get(PyObject * obj) { return obj; }
```

</details>

**Comment by peterbell10** [comment]
@rgommers how strongly do you feel about the warning? It's benign and the solutions either involve duplicated code or compiler-dependent pragmas to silence the warning.

**Comment by rgommers** [comment]
> @rgommers how strongly do you feel about the warning? It's benign and the solutions either involve duplicated code or compiler-dependent pragmas to silence the warning.

I'm trying to get to a completely silent Meson build, but we can also just add `-Wno-terminate` to if you'd be okay with that? For the distutils-based build I don't care - lost cause:)

**Comment by peterbell10** [comment]
`-Wno-terminate` seems fine to me. It's only a vendored library anyway, so the warning still shows up in development.

**Pull request merged**
