### PR TITLE
TST: fix missing seed in lobpcg test.

### PR DESCRIPTION
**Pull request by rgommers**
CI failure observed in gh-9447, this will fix that.

### CODE REVIEW

**Comment by ev-br** [comment]
Thanks Ralf, merged.

**Comment by tylerjereddy** [comment]
The random seed wasn't the problem -- you can see the same thing happening here: https://ci.appveyor.com/project/scipy/scipy/builds/20106920

That's from #7827 after I rebased on the fix / latest master.  cc @rc 

I keep seeing `array([4.+0.j, 5.+0.j])` compared with `array([5., 4.])`. Is it something related to complex numbers, and only happening on Windows / subset of Python versions? Are we even expecting complex numbers here? I know that complex math can sometimes happen slightly differently depending on platform and so on.

**Comment by tylerjereddy** [comment]
Maybe I spoke too soon -- I do see the seed added here in the failing test, but I'll keep the issue closed because Ralf's commit wasn't in my rebase after all. Not sure if appveyor is rebasing for those subset jobs or something. If the fresh rebase fails I guess I'll reopen the issue.

**Comment by tylerjereddy** [comment]
Alternative suggestions in the linked issue now.

**Pull request merged**
