### PR TITLE
BLD: Warning fix from ``scipy/special/special/gamma.h``

### LINKED ISSUE #20587: BLD: warning from `scipy/special/special/gamma.h`
There's a new warning when building main:

```
[32/247] Compiling C++ object scipy/specia...86_64-linux-gnu.so.p/_special_ufuncs.cpp.o
In file included from ../scipy/special/_special_ufuncs.cpp:15:
../scipy/special/special/gamma.h: In function 'std::complex<_Tp> special::gamma(std::complex<_Tp>) [with T = float]':
../scipy/special/special/gamma.h:19:44: warning: infinite recursion detected [-Winfinite-recursion]
   19 | SPECFUN_HOST_DEVICE inline std::complex<T> gamma(std::complex<T> z) {
      |                                            ^~~~~
../scipy/special/special/gamma.h:20:17: note: recursive call
   20 |     return gamma(z);
      |            ~~~~~^~~
```

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Reference issue

Fixes https://github.com/scipy/scipy/issues/20587

### CODE REVIEW

**Comment by czgdp1807** [comment]
This is ready for review.

**Comment by rgommers** [comment]
This is now all green, thanks @czgdp1807. It'd be nice to get this merged, since the warning is annoying (it's the only one for GCC on Linux). 

I'll leave the review to @steppi.

**Review by steppi — CHANGES_REQUESTED** [review]
Thanks @czgdp1807.

Let me give you an overview of what's going on and what should be done.

So in C++, we can safely overload on input type, so we should never need to add a suffix for the type like this.  @izaid and I just got a little aggressive with the templating and wrote something which can resolve ambiguously. All we actually want is `complex<double>` and `complex<float>` versions of the `gamma` function.

I think we should keep the `gamma` in `loggamma.h` exactly the same, but move it to `gamma.h` since it seems like that's where it logically belongs. Instead of adding a templated `gamma`, we should just have another one that works with `std::complex<float>` and casts to `double` and back, like we do for `digamma` here:

https://github.com/scipy/scipy/blob/d7bab751686788d82e2968f9aa163e015ee2b9d3/scipy/special/special/digamma.h#L200-L202

**Comment by czgdp1807** [comment]
https://github.com/scipy/scipy/actions/runs/9304146804/job/25608074162?pr=20820 fails. I think we should keep it templated. Its causing problems with 32 bit. But something similar should have happened for `digamma`, right?

**Comment by czgdp1807** [comment]
The docs are failing though I didn't touch anything related to that.

```zsh
/home/circleci/repo/build-install/lib/python3.11/site-packages/scipy/stats/_morestats.py:docstring of scipy.stats._morestats.false_discovery_control:44: WARNING: py:obj reference target not found: statsmodels.stats.multitest.multipletests

Exited with code exit status 1
```

**Review by steppi — APPROVED** [review]
Thanks @czgdp1807. Looks good. I'll merge after CI settles.

**Comment by czgdp1807** [comment]
> Basically, SciPy can be thought of as a large monorepo of separate modules, tests for everything run for every PR

Yes. 32-bit failure felt relevant to me, but regarding docs failure I was aware that it's not relevant to my PR.

Reverted the last change I made. Please see if it looks good now.

**Comment by czgdp1807** [comment]
This Windows tests is failing on multiple PRs with different limits.

**Pull request merged**
