### PR TITLE
TST: NumpyVersion dev -> dev0

### PR DESCRIPTION
**Pull request by argriffing**
Just a test that changing dev to dev0 doesn't bother NumpyVersion too much.  This is for https://github.com/scipy/scipy/pull/4512.

### CODE REVIEW

**Comment by rgommers** [comment]
Tests look good, except that they should now be using ``.dev0+`` instead of ``.dev0-``.

**Comment by rgommers** [comment]
And thanks for taking care of this loose end!

**Comment by argriffing** [comment]
> they should now be using `.dev0+` instead of `.dev0-`.

Fixed.

**Comment by rgommers** [comment]
Thanks, merged.

**Pull request merged**
