### PR TITLE
BUG: Ensure factorial is not too large in kendaltau

### LINKED ISSUE #9611: Overflow error with new way of p-value calculation in kendall tau correlation for perfectly monotonic vectors.
My issue is about overflow error caused by zero discordant pairs in scipy version 1.2.0, in the improved p-value calculation of the kendall's tau function. In the case of two perfectly monotonic vectors x, y, c becomes 0 and the if-else condition calculates a factorial. In version 1.1.0, this refined term calculation is not present and so this issue does not occur there. If others can reproduce this issue, it seems that the solution is simple: when c becomes 0 (when dis is 0), p-value converges to zero very rapidly for sizes > 15 etc., so an if-statement could take care of that. Another solution could be to flag large sample sizes with method='asymptotic' being used instead.

(The c = 1 case seems to be similar in my mind.)

```
elif c == 0:
    pvalue = 2.0/np.math.factorial(size)
elif c == 1:
    pvalue = 2.0/np.math.factorial(size-1)
```

### Reproducing code example:

Sample code to reproduce the problem
```
from scipy import stats
kendall, _ = stats.kendalltau(np.arange(200), np.arange(200))
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/stats.py", line 3632, in kendalltau
    pvalue = 2.0/np.math.factorial(size)
OverflowError: long int too large to convert to float
```
Note that in this example, size is equal to 200.

### Scipy/Numpy/Python version information:
```
>>> scipy.__version__
'1.2.0'
```

This error does not occur in 1.1.0.

### PR DESCRIPTION
**Pull request by bashtage**
Avoid excessively large factorial in kendall tau when sample size is large

closes #9611

### CODE REVIEW

**Comment by bashtage** [comment]
The alternative is to use exp(gammaln(size)) which works for size up to about 1e150, which will never be hit, but would theoretically produce a nan. exp(gammaln(size)) is simpler since no if needed.

**Comment by ev-br** [comment]
While you're at it, maybe import `factorial` straight from the builtin `math`?

```
In [10]: import math, numpy as np

In [11]: np.math.factorial is math.factorial
Out[11]: True
```

**Comment by rgommers** [comment]
Thanks @bashtage, merged.

**Comment by tylerjereddy** [comment]
@rgommers Do you want this backported to 1.2.x LTS? It is already in the 1.3.x maintenance branch used for 1.3.0rc1

**Comment by rgommers** [comment]
yes that's a good idea I think

**Comment by tylerjereddy** [comment]
Release scripts that scrape GitHub for milestones become somewhat less effective on the bugfix point releases where I'd basically want two milestone labels attached here -- 1.3.0 and 1.2.2. Anyway, I'll do it by hand.

**Pull request merged**
