### PR TITLE
ENH: stats: make distribution instances picklable

### LINKED ISSUE #4816: scipy.stats.distributions.rv_frozen not picklable
```python
from scipy.stats import randint
import pickle
pickle.dumps(randint(1, 20))
```

> TypeError: can't pickle instancemethod objects

### PR DESCRIPTION
**Pull request by ev-br**
Intends to close gh-4816.

(this likely has a milestone "after 0.16 is done")

<s>Note to self:</s> multivariate distributions are <s>likely</s> OK, <s>but it's worth checking.</s>

### CODE REVIEW

**Comment by rgommers** [comment]
It passes (except for pep8), but indeed I agree it would be better to merge this after the release split.

**Comment by ev-br** [comment]
rebased.

**Comment by rgommers** [comment]
Question: is it a problem that this loses changes to attributes that are made after instantiation (``_ctor_param`` is never updated)? Not sure if there's a good use-case for doing that, but it may be something worth checking for.

**Comment by ev-br** [comment]
Here's `_ctor_param`:
```
        self._ctor_param = dict(
            momtype=momtype, a=a, b=b, xtol=xtol,
            badvalue=badvalue, name=name, longname=longname,
            shapes=shapes, extradoc=extradoc, seed=seed)
```

`a` and `b` are either fixed or get regenerated at each call for some distributions, `seed` is related to the `random_state` which is taken care of separately here, the rest do not seem like something a user is very likely to change.

I also note that freezing distributions also relies on `_ctor_param`.

**Comment by rgommers** [comment]
I noticed indeed that freezing does the same. It's odd though that there are a bunch of attributes that we aren't preventing users from changing, but assuming that they don't. 

It would be easy to add a private method to update ``self._ctor_param`` and call that from ``freeze`` and from ``__getstate__``. That would solve the issue.

**Comment by ev-br** [comment]
> It would be easy to add a private method to update self._ctor_param and call that from freeze and from __getstate__. That would solve the issue

Done.

**Comment by rgommers** [comment]
Thanks Evgeni, merged.

**Pull request merged**
