### PR TITLE
MAINT: Remove `np.rollaxis` usage with `np.moveaxis` and `.T`

### LINKED ISSUE #14491: MAINT: Replace np.rollaxis with np.moveaxis
### Context
NumPy initially added [`np.rollaxis`](https://numpy.org/doc/stable/reference/generated/numpy.rollaxis.html), but later, several users reported confusing API/working of `rollaxis` (see [this](https://stackoverflow.com/questions/29891583/reason-why-numpy-rollaxis-is-so-confusing/39878857) SO discussion or numpy/numpy#15926 or numpy/numpy#9473). Thus, a more clear and crisp function to achieve the same goal was added i.e named [`np.moveaxis`](https://numpy.org/doc/stable/reference/generated/numpy.moveaxis.html#numpy.moveaxis).

Quoting @shoyer from the [StackOverflow discussion](https://stackoverflow.com/questions/29891583/reason-why-numpy-rollaxis-is-so-confusing/39878857).
> NumPy v1.11 and newer includes a new function, moveaxis, that I recommend using instead of rollaxis (disclaimer: I wrote it!). The source axis always ends up at the destination, without any funny off-by-one issues depending on whether start is greater or less than end.

NumPy has already removed any use of `rollaxis` internally in favour of `moveaxis` with numpy/numpy#9475.

In fact, array/tensor libraries like `torch` don't even have `rollaxis`, instead, they have the `moveaxis` method. (See [docs](https://pytorch.org/docs/stable/generated/torch.moveaxis.html)).

Having old functions which are not present in other libraries and are not very user friendly make it difficult to read/understand the source code.

### Pitch
I propose to replace the use of `rollaxis` with `moveaxis` in SciPy internally and refactor accordingly, making things a little more coherent. This was added in `numpy v1.11.0`, hence it is easy to move away since SciPy [claims](https://github.com/scipy/scipy/blob/master/INSTALL.rst.txt#prerequisites) support for only `numpy>=1.16.5`.

I can send a PR if there aren't any issues that I'm missing. 

cc @rgommers

### PR DESCRIPTION
**Pull request by AnirudhDagar**
#### Reference issue
Closes gh-14491

#### What does this implement/fix?
Refactor all the `np.rollaxis` instances in the codebase.
Also see [np.rollaxis documentation](https://numpy.org/doc/stable/reference/generated/numpy.rollaxis.html).

#### Additional information
Discussion about `np.moveaxis` not as performant as `np.rollaxis` is probably something practically negligible in the changes made here. These functions include operations that take at least an order of magnitude more in total to run making the performance effect of changing to `moveaxis` from `rollaxis` pointless.

### CODE REVIEW

**Comment by ilayn** [comment]
Indeed just encountered this on another PR seems like things have been moved around again https://stackoverflow.com/questions/56156520/gfortran-error-ld-library-not-found-for-lsystem-when-trying-to-compile

**Review by rgommers — APPROVED** [review]
Nice cleanup, thanks @AnirudhDagar

**Comment by rgommers** [comment]
Hmm, post-merge the nightly build failed with some errors that look related, even though that same job passed here: https://github.com/scipy/scipy/runs/3852437676?check_suite_focus=true

```
FAILED scipy/integrate/tests/test_bvp.py::test_compute_global_jac - Assertion...
FAILED scipy/signal/tests/test_filter_design.py::TestCheby1::test_bandstop - ...
FAILED scipy/special/tests/test_orthogonal.py::test_roots_chebyu - AssertionE...
FAILED scipy/special/tests/test_orthogonal.py::test_roots_chebys - AssertionE...
FAILED scipy/stats/tests/test_morestats.py::TestCircFuncs::test_circfuncs_close[circstd-std]
```

Would you be able to have a look at those @AnirudhDagar?

**Comment by AnirudhDagar** [comment]
Interesting, master is green again (See 2abc0bbc4758506056ed45e96ff7e5c9cdf08755). I'm curious now, why did it fail earlier. What if the tolerances are too tight?

**Comment by ilayn** [comment]
It was #14701 and after a rerun they also passed so probably it is coming and going.

**Comment by AnirudhDagar** [comment]
I'll send a small update to increase the tolerances a bit looking at the numbers from those fails.

Do you have any ideas on how we can reproduce this locally? Earlier I ran a script several times just on those tests to understand the probability of this failing (on py 3.8/3.9 environments) but all of them passed (maybe I need to do the same on python 3.10 which is still not readily available with conda). This will also give a good upper bound for the tolerances.

**Comment by ilayn** [comment]
The error margins are in the failing jobs so slight nudge would be sufficient for now to be on the safe side.

**Comment by AnirudhDagar** [comment]
Yeah, sending a PR for this.

**Pull request merged**
