### PR TITLE
MAINT: special: simplify the algorithm of cexpm1

### PR DESCRIPTION
**Pull request by person142**
As a side effect silences some of the noise in gh-6144.

### CODE REVIEW

**Comment by person142** [comment]
Hm, another one where the tests succeed on my machine and fail on Travis. Last night I thought I was making a stupid mistake somewhere (and maybe I still am...), but after staring a while longer I still didn't see it. Will have to figure it out.

**Comment by pv** [comment]
Needs to rerun `generate_ufuncs.py`?

**Comment by pv** [comment]
But I don't understand why it's failing either...

**Comment by person142** [comment]
Well I'm glad it's not just me. :-) Might as well give ``generate_ufuncs.py`` a try.

**Comment by pv** [comment]
I think `generate_ufuncs.py` loops over dict keys, which is nondeterministic. Could be fixed.
In principle it shouldn't generate any code changes here.

Maybe the problem is that the test is buggy? The failing points have pretty big imaginary parts, and you have sines and cosines of those. Reordering the code in principle might force the fp values in/out of registers, and change the results that way if the fpu works in higher internal precision...

**Comment by person142** [comment]
@pv: it does involve sines and cosines in regions where those functions are not necessarily very accurate, but does ``exp(z)`` inherit the same problems? If we just think about the imaginary axis where ``exp(iy) = cos(y) + i*sin(y)``, then intuitively when the conditioning of ``sin`` is very bad, then the conditioning of ``cos`` should not be too bad and vice versa. To try and make this more formal, the condition number of ``exp(z)`` is (if I didn't screw up the computation) ``|z|``: it doesn't have the poles that the condition numbers of ``sin`` and ``cos`` do. I'm revealing my own ignorance here...

**Comment by pv** [comment]
I think the explanation is that condition number assumes small 
perturbation, but the perturbation from fp truncation is of order 
`np.spacing(y)` ~ 1e-16*|y| which becomes comparable to the period of 
sin/cos already for not very large |y|.

**Comment by pv** [comment]
Of course, here it's not clear that that is the explanation, because the 
input arguments are directly real/imag parts of the input `z` rather 
than some values produced by intermediate fp computations.
.
Other explanations could involve that the compiler in one case optimized 
the sin/cos calls into a call to a single call to sincos(), but in the 
other case not, and the accuracy of sincos() is not the same as sin() 
cos() in cases when fp truncation error is larger than 2pi, on the old 
libc version used on Travis. Being sure of what happened would require 
having access to the optimized code produced by gcc (and managing to get 
this on Travis is a bit annoying).

**Comment by person142** [comment]
Closing; the code is correct as is and I'm only succeeding in making Travis unhappy.

**Pull request closed without merging**
