### PR TITLE
add an iterative version of stats._mannwhitneyu._MWU._f to fall back to when recursion limit is hit by 'exact' method

### PR DESCRIPTION
**Pull request by szkafander**
#### Reference issue
#14622 

#### What does this implement/fix?
mannwhitneyu hits recursion limits when _mwu_choose_method chooses 'exact' but one sample is large. This implements an iterative version of _f in _MWU that is used as a fallback when the recursion limit is hit.

#### Additional information
The iterative version is slower than the recursive; however, this only affects the rare edge cases that the issue pertains to. Nevertheless, in those cases, reverting to the 'asymptotic' method only to work around the recursion limit may cause a significant difference in the resulting p-value; therefore, it is proposed to fall back to iteration instead.

### CODE REVIEW

**Comment by szkafander** [comment]
> Thanks. It looks like you tied this in really cleanly. I hope someone can review in detail soon. (I would probably not be before December for me.) Could you add the test to `test_hypotests` instead? That where most of the MWU tests are; the ones in `test_stats` are just preserved because that's where they were before the overhaul. Also, please consider:
> 
>     * adding the iterative method to `test_exact_distribution`

Will do.

> 
>     * testing a call to `mannwhitneyu` with a case that triggers the iterative method and check for accuracy (e.g. you could hard-code the results from the recursive solution as ground truth),

Right, I did not add this because it would be slow.

> 
>     * testing a call with n-d array input that triggers the iterative method to check that it still does the right thing (maybe using the asymptotic method as a reference? We don't need to check for perfect accuracy; just that it's still applying the `axis` parameter appropriately.).

OK, I'll make a test for this.

> 
> 
> If some of these tests are really slow and we can be convinced they're not needed, let us know. These are just some things that come to mind.

FYI, _without caching_, iteration for cases that would hit the recursion limit run for slightly over a minute on an i5 laptop. Cases slightly smaller than these edge cases run for ~40 seconds with recursion. Thus, iteration is not super slow, but it is definitely slower than recursion. The cause of course is method calls and .append/.pop inside the loop. I tried to strip it down as much as possible but the slight performance increase did not seem to justify the loss of readability. 

On that note, do you know why an array is used for caching (_fmnks in _MWU)? I tested with a dict and it appeared faster. In some large cases, assigning the array for the cache can hit memory limits as well. A dict would suffer less from this.

**Comment by szkafander** [comment]
I 

> Thanks. It looks like you tied this in really cleanly. I hope someone can review in detail soon. (I would probably not be before December for me.) Could you add the test to `test_hypotests` instead? That where most of the MWU tests are; the ones in `test_stats` are just preserved because that's where they were before the overhaul. Also, please consider:
> 
> * adding the iterative method to `test_exact_distribution`

Added this. I just cloned your existing tests and forced iteration.

> * testing a call to `mannwhitneyu` with a case that triggers the iterative method and check for accuracy (e.g. you could hard-code the results from the recursive solution as ground truth),
> * testing a call with n-d array input that triggers the iterative method to check that it still does the right thing (maybe using the asymptotic method as a reference? We don't need to check for perfect accuracy; just that it's still applying the `axis` parameter appropriately.).

I added tests for this.

> 
> If some of these tests are really slow and we can be convinced they're not needed, let us know. These are just some things that come to mind.

The issue is, all edge cases that trigger iteration will be solved slowly. Both recursion (with increased recursion limit) and iteration will take minutes. Thus, I did not include these "real" tests. Instead, I included smaller problems and forced _mwu_state to use iteration. I suspect that if solutions of small problems are equivalent, solutions of large problems will be equivalent as well. I tested equivalence of large problems manually and everything looked OK.

TestMannWhitneyU::test_gh_11355 and TestMannWhitneyU::test_gh_4067 failed due to ValueError: `x` and `y` must not contain NaNs. My changes are apparently unrelated to this, but I am not sure.

**Comment by szkafander** [comment]
> For lint checks, consider looking for an IDE option that eliminates trailing or blank line whitespace.

Removed blanks.

**Comment by tirthasheshpatel** [comment]
> The issue is, all edge cases that trigger iteration will be solved slowly. Both recursion (with increased recursion limit) and iteration will take minutes. Thus, I did not include these "real" tests.

BTW you can decorate very slow tests (the ones that take minutes) with `pytest.xslow`. These don't run in the CI and one can run the tests locally with the `SCIPY_XSLOW` env variable set to 1. Although, as you already test with smaller problems and verified it works for larger problems, it'd be OK not to do this.

**Review by tirthasheshpatel — APPROVED** [review]
This is very well-written and the implementation looks correct. The tests are also quite comprehensive (with 100% coverage of the iterative implementation). @mdhaber Do you think the tests are strong enough? If yes, this looks good to go in!

**Comment by tirthasheshpatel** [comment]
@szkafander I subclassed `TestMannWhitneyU` to always use the iterative implementation and got some assertion errors.

Here's the implementation:

```python
class TestMannWhitneyUIterative(TestMannWhitneyU):
    class _MWU_Iterative(_MWU):
        def cdf(self, k, m, n):
            '''Cumulative distribution function'''
            # We could use the fact that the distribution is symmetric to avoid
            # summing more than m*n/2 terms, but it might not be worth the
            # overhead. Let's leave that to an improvement.
            pmfs = self.pmf(np.arange(0, np.max(k) + 1), m, n)
            cdfs = np.cumsum(pmfs)
            return cdfs[k]
    _mannwhitneyu._mwu_state = _MWU_Iterative()
    _mannwhitneyu._mwu_state._use_iter = True
```

Failures:

```none
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_auto - assert 0.41083916083916083 == 0.09597902097902099
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_basic[kwds3-expected3] - AssertionError: 
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_basic[kwds4-expected4] - AssertionError: 
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_basic[kwds5-expected5] - AssertionError: 
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_asymptotic_behavior - AssertionError: assert 0.047152776667529275 < 0.001
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_gh_9184[True-less-exact-0.8967698967699] - AssertionError: 
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_gh_9184[True-greater-exact-0.1272061272061] - AssertionError: 
FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_gh_9184[True-two-sided-exact-0.2544122544123] - AssertionError:
```

I haven't carefully investigated the failures but it looks like the iterative implementation genuinely fails for some test cases. Can you please confirm these failures and try to find what's wrong with the implementation?

**Comment by szkafander** [comment]
> @szkafander I subclassed `TestMannWhitneyU` to always use the iterative implementation and got some assertion errors.
> 
> Here's the implementation:
> 
> ```python
> class TestMannWhitneyUIterative(TestMannWhitneyU):
>     class _MWU_Iterative(_MWU):
>         def cdf(self, k, m, n):
>             '''Cumulative distribution function'''
>             # We could use the fact that the distribution is symmetric to avoid
>             # summing more than m*n/2 terms, but it might not be worth the
>             # overhead. Let's leave that to an improvement.
>             pmfs = self.pmf(np.arange(0, np.max(k) + 1), m, n)
>             cdfs = np.cumsum(pmfs)
>             return cdfs[k]
>     _mannwhitneyu._mwu_state = _MWU_Iterative()
>     _mannwhitneyu._mwu_state._use_iter = True
> ```
> 
> Failures:
> 
> ```
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_auto - assert 0.41083916083916083 == 0.09597902097902099
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_basic[kwds3-expected3] - AssertionError: 
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_basic[kwds4-expected4] - AssertionError: 
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_basic[kwds5-expected5] - AssertionError: 
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_asymptotic_behavior - AssertionError: assert 0.047152776667529275 < 0.001
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_gh_9184[True-less-exact-0.8967698967699] - AssertionError: 
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_gh_9184[True-greater-exact-0.1272061272061] - AssertionError: 
> FAILED scipy/stats/tests/test_hypotests.py::TestMannWhitneyUIterative::test_gh_9184[True-two-sided-exact-0.2544122544123] - AssertionError:
> ```
> 
> I haven't carefully investigated the failures but it looks like the iterative implementation genuinely fails for some test cases. Can you please confirm these failures and try to find what's wrong with the implementation?

Will do. I need a few days.

**Comment by mdhaber** [comment]
Looks like this fell off the radar - no problem! We went ahead and finished this up in gh-15920. Thanks!

**Pull request closed without merging**
