### PR TITLE
BENCH: Add benchmarks for special.factorial/factorial2/factorialk

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

part of gh-15600
#### What does this implement/fix?

gh-15600 highlight a number of inconsistencies in special.factorial/factorial2/factorialk. As a first step to resolving them in would be useful to benchmark the existing functionality to ensure we are not making it worse. This pull request adds benchmarks for all the options in the table bellow that dont raise an exception or return nan.
image
(table courtesy of @h-vetinari )
#### Additional information

cc. @h-vetinari , @tupui , @tirthasheshpatel ,

### CODE REVIEW

**Comment by tupui** [comment]
Thank you @j-bowhay for the PR. For reference, could you post in the description the results of the benchmarks?

**Comment by j-bowhay** [comment]
Benchmark results @tupui 
```
(scipydev) [jakeb@jake-pc scipy]$ python runtests.py --bench special.Factorial
Building, see build.log...
Build OK (0:00:15.023924 elapsed)
Running benchmarks for Scipy version 1.9.0.dev0+1605.684bfef at /home/jakeb/development/scipy/build/testenv/lib/python3.8/site-packages/scipy/__init__.py
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Discovering benchmarks
· Running 22 total benchmarks (1 commits * 1 environments * 22 benchmarks)
[  0.00%] ·· Benchmarking existing-py_home_jakeb_miniconda3_envs_scipydev_bin_python
[  2.27%] ··· Running (special.Factorial.time_factorial_exact_false_array_negative_float--)......................
[ 52.27%] ··· special.Factorial.time_factorial_exact_false_array_negative_float                                                                                                                                                                                                   1.81±0.2μs
[ 54.55%] ··· special.Factorial.time_factorial_exact_false_array_negative_int                                                                                                                                                                                                     3.18±0.4μs
[ 56.82%] ··· special.Factorial.time_factorial_exact_false_array_positive_float                                                                                                                                                                                                   2.12±0.2μs
[ 59.09%] ··· special.Factorial.time_factorial_exact_false_array_positive_int                                                                                                                                                                                                     4.65±0.5μs
[ 61.36%] ··· special.Factorial.time_factorial_exact_false_scalar_negative_float                                                                                                                                                                                                  2.30±0.9μs
[ 63.64%] ··· special.Factorial.time_factorial_exact_false_scalar_negative_int                                                                                                                                                                                                    2.89±0.1μs
[ 65.91%] ··· special.Factorial.time_factorial_exact_false_scalar_positive_float                                                                                                                                                                                                          ok
[ 65.91%] ··· ========= =============
                  n                  
              --------- -------------
                100.8     2.94±0.7μs 
                1000.3    2.75±0.4μs 
               10000.5   2.34±0.07μs 
              ========= =============

[ 68.18%] ··· special.Factorial.time_factorial_exact_false_scalar_positive_int                                                                                                                                                                                                            ok
[ 68.18%] ··· ======= =============
                 n                 
              ------- -------------
                100     3.64±0.5μs 
                1000   3.18±0.09μs 
               10000    3.08±0.2μs 
              ======= =============

[ 70.45%] ··· special.Factorial.time_factorial_exact_true_array_negative_float                                                                                                                                                                                                       109±9μs
[ 72.73%] ··· special.Factorial.time_factorial_exact_true_array_negative_int                                                                                                                                                                                                       98.6±20μs
[ 75.00%] ··· special.Factorial.time_factorial_exact_true_array_positive_int                                                                                                                                                                                                      1.08±0.1ms
[ 77.27%] ··· special.Factorial.time_factorial_exact_true_scalar_negative_float                                                                                                                                                                                                     6.81±2μs
[ 79.55%] ··· special.Factorial.time_factorial_exact_true_scalar_negative_int                                                                                                                                                                                                     6.19±0.5μs
[ 81.82%] ··· special.Factorial.time_factorial_exact_true_scalar_positive_int                                                                                                                                                                                                             ok
[ 81.82%] ··· ====== =============
                n                 
              ------ -------------
               100      10.1±3μs  
               1000     73.4±5μs  
               5000   1.23±0.07ms 
              ====== =============

[ 84.09%] ··· special.Factorial2.time_factorial2_exact_false_array_negative_int                                                                                                                                                                                                     126±20μs
[ 86.36%] ··· special.Factorial2.time_factorial2_exact_false_array_positive_int                                                                                                                                                                                                     183±30μs
[ 86.36%] ···· /home/jakeb/development/scipy/build/testenv/lib/python3.8/site-packages/scipy/special/_basic.py:2447: RuntimeWarning: overflow encountered in multiply
               place(vals, cond2, gamma(nd2e + 1) * pow(2.0, nd2e))

[ 88.64%] ··· special.Factorial2.time_factorial2_exact_false_scalar_negative_int                                                                                                                                                                                                     114±9μs
[ 90.91%] ··· special.Factorial2.time_factorial2_exact_false_scalar_positive_int                                                                                                                                                                                                          ok
[ 90.91%] ··· ====== ==========
                n              
              ------ ----------
               100    132±20μs 
               1000   108±2μs  
               2000   114±9μs  
              ====== ==========

[ 93.18%] ··· special.Factorial2.time_factorial2_exact_true_scalar_negative_int                                                                                                                                                                                                     364±40ns
[ 95.45%] ··· special.Factorial2.time_factorial2_exact_true_scalar_positive_int                                                                                                                                                                                                           ok
[ 95.45%] ··· ====== ============
                n                
              ------ ------------
               100    7.23±0.9μs 
               1000    128±10μs  
               2000    421±7μs   
              ====== ============

[ 97.73%] ··· special.FactorialK.time_factorialk_exact_false_scalar_negative_int                                                                                                                                                                                                     299±7ns
[100.00%] ··· special.FactorialK.time_factorialk_exact_true_scalar_positive_int                                                                                                                                                                                                           ok
[100.00%] ··· ====== ============ ============ ============ ============ ============ ============ ============ ============ ============
              --                                                              k                                                          
              ------ --------------------------------------------------------------------------------------------------------------------
                n         1            2            3            4            5            6            7            8            9      
              ====== ============ ============ ============ ============ ============ ============ ============ ============ ============
               100    13.0±0.9μs   6.74±0.7μs   4.91±0.3μs   3.58±0.4μs   4.79±0.3μs   3.71±0.6μs   2.72±0.3μs   2.63±0.5μs   2.26±0.3μs 
               1000    400±40μs     158±20μs    89.5±10μs     58.2±2μs     38.9±9μs     33.3±5μs     27.9±4μs     22.1±3μs     17.1±2μs  
              ====== ============ ============ ============ ============ ============ ============ ============ ============ ============
```

**Comment by h-vetinari** [comment]
Thanks a lot for tackling this @j-bowhay!

**Comment by h-vetinari** [comment]
@tylerjereddy
Any recommendations who should be (asked for) reviewing benchmark PRs?

**Comment by h-vetinari** [comment]
@rgommers 
Perhaps you could suggest who'd be the right person to ask to review a benchmark PR? This is currently the blocker for continuing with #15600 (which - in an ideal world - I'd like to sort out before 1.9).

**Review by rgommers — COMMENTED** [review]
Thanks @j-bowhay. This looks quite good. Two things I noticed:
- There is one RuntimeWarning that would be nice to silence (perhaps by use of `np.errstate`) or avoid
- The total runtime of the added tests is a bit slow. In particular `Factorial.time_factorial_exact_false_array_negative_float` it looks like. If you could make that faster, maybe by just cutting down on input array size, that'd be great.

```
$ time python dev.py --bench Factorial
...
[ 86.36%] ···· /home/rgommers/code/scipy/build-install/lib/python3.10/site-packages/scipy/special/_basic.py:2476: RuntimeWarning: overflow encountered in multiply
               place(vals, cond2, gamma(nd2e + 1) * pow(2.0, nd2e))
...
real    0m26.912s
user    0m22.170s
sys     0m1.550s
```

Full output:

<details>

```
$ time python dev.py --bench Factorial
ninja: Entering directory `build'
[2/2] Generating scipy/generate-config with a custom command
Build OK
Installing, see meson-install.log...
Installation OK
Running benchmarks for Scipy version 1.9.0.dev0+1671.94c4de8 at /home/rgommers/code/scipy/build-install/lib/python3.10/site-packages/scipy
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Discovering benchmarks
· Running 22 total benchmarks (1 commits * 1 environments * 22 benchmarks)
[  0.00%] ·· Benchmarking existing-py_home_rgommers_anaconda3_envs_scipy-dev_bin_python
[  2.27%] ··· Running (special.Factorial.time_factorial_exact_false_array_negative_float--)......................
[ 52.27%] ··· ...ctorial.time_factorial_exact_false_array_negative_float           577±10ns
[ 54.55%] ··· ...Factorial.time_factorial_exact_false_array_negative_int        1.00±0.01μs
[ 56.82%] ··· ...ctorial.time_factorial_exact_false_array_positive_float            749±7ns
[ 59.09%] ··· ...Factorial.time_factorial_exact_false_array_positive_int        1.50±0.01μs
[ 61.36%] ··· ...torial.time_factorial_exact_false_scalar_negative_float           728±10ns
[ 63.64%] ··· ...actorial.time_factorial_exact_false_scalar_negative_int           942±20ns
[ 65.91%] ··· ...torial.time_factorial_exact_false_scalar_positive_float                 ok
[ 65.91%] ··· ========= ==========
                  n               
              --------- ----------
                100.8    885±9ns  
                1000.3   853±20ns 
               10000.5   840±9ns  
              ========= ==========

[ 68.18%] ··· ...actorial.time_factorial_exact_false_scalar_positive_int                 ok
[ 68.18%] ··· ======= =============
                 n                 
              ------- -------------
                100    1.15±0.02μs 
                1000   1.10±0.01μs 
               10000   1.07±0.02μs 
              ======= =============

[ 70.45%] ··· ...actorial.time_factorial_exact_true_array_negative_float         27.3±0.3μs
[ 72.73%] ··· ....Factorial.time_factorial_exact_true_array_negative_int        25.1±0.05μs
[ 75.00%] ··· ....Factorial.time_factorial_exact_true_array_positive_int            351±4μs
[ 77.27%] ··· ...ctorial.time_factorial_exact_true_scalar_negative_float        1.76±0.02μs
[ 79.55%] ··· ...Factorial.time_factorial_exact_true_scalar_negative_int        1.74±0.01μs
[ 81.82%] ··· ...Factorial.time_factorial_exact_true_scalar_positive_int                 ok
[ 81.82%] ··· ====== =============
                n                 
              ------ -------------
               100    2.69±0.03μs 
               1000    28.8±0.2μs 
               5000     548±3μs   
              ====== =============

[ 84.09%] ··· ...ctorial2.time_factorial2_exact_false_array_negative_int        31.6±0.08μs
[ 86.36%] ··· ...ctorial2.time_factorial2_exact_false_array_positive_int         37.6±0.2μs
[ 86.36%] ···· /home/rgommers/code/scipy/build-install/lib/python3.10/site-packages/scipy/special/_basic.py:2476: RuntimeWarning: overflow encountered in multiply
               place(vals, cond2, gamma(nd2e + 1) * pow(2.0, nd2e))

[ 88.64%] ··· ...torial2.time_factorial2_exact_false_scalar_negative_int         31.9±0.2μs
[ 90.91%] ··· ...torial2.time_factorial2_exact_false_scalar_positive_int                 ok
[ 90.91%] ··· ====== ============
                n                
              ------ ------------
               100    32.3±0.6μs 
               1000   32.4±0.2μs 
               2000   33.2±0.6μs 
              ====== ============

[ 93.18%] ··· ...ctorial2.time_factorial2_exact_true_scalar_negative_int            100±1ns
[ 95.45%] ··· ...ctorial2.time_factorial2_exact_true_scalar_positive_int                 ok
[ 95.45%] ··· ====== =============
                n                 
              ------ -------------
               100    2.24±0.02μs 
               1000    47.9±0.4μs 
               2000     177±4μs   
              ====== =============

[ 97.73%] ··· ...torialK.time_factorialk_exact_false_scalar_negative_int            110±1ns
[100.00%] ··· ...ctorialK.time_factorialk_exact_true_scalar_positive_int                 ok
[100.00%] ··· ====== === =============
                n     k               
              ------ --- -------------
               100    1   4.42±0.05μs 
               100    2   2.22±0.03μs 
               100    3   1.59±0.03μs 
               100    4   1.23±0.03μs 
               100    5   1.01±0.03μs 
               100    6     913±10ns  
               100    7     824±10ns  
               100    8     765±10ns  
               100    9     704±6ns   
               1000   1     161±6μs   
               1000   2    47.8±0.7μs 
               1000   3    24.9±0.3μs 
               1000   4    15.8±0.1μs 
               1000   5    11.7±0.1μs 
               1000   6    9.30±0.1μs 
               1000   7   7.80±0.09μs 
               1000   8   6.63±0.09μs 
               1000   9   5.70±0.08μs 
              ====== === =============


real    0m26.912s
user    0m22.170s
sys     0m1.550s
```

</details>

**Comment by j-bowhay** [comment]
@rgommers thanks for the review. I have reduced the magnitude of some of the parameters / the size of some the arrays. This has hopefully sped things up and has fixed the overflow warning.

**Comment by rgommers** [comment]
Thanks for the update @j-bowhay. That didn't really make a difference. I think the cause is that if a calculation gets faster, `asv` just starts running more loops. Looking at just one example, it's running a million loops, times 7 iterations:
```
In [3]: %timeit factorial(10000)
753 ns ± 2.83 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
So it's just the number of benchmarks that are added.

If this takes half a minute on my machine, it's probably double that in CI. Do we really need all these? Or can a good amount of these be removed after gh-15600 is fixed?

**Comment by j-bowhay** [comment]
> If this takes half a minute on my machine, it's probably double that in CI. Do we really need all these? Or can a good amount of these be removed after [gh-15600](https://github.com/scipy/scipy/issues/15600) is fixed?

@h-vetinari any thoughts on this?

**Comment by rgommers** [comment]
> My understanding of a performance test suite is that it should cover most common functionality

Indeed. Which in this case would be a single invocation of each factorial function with floats I'd say - not scalars vs. arrays and negative/positive ints, and that for all 3 flavors again. We do need to care about running benchmarks in CI so they actually keep working, so half a minute is a lot.

> In this case, the key motivation is to dot our i's and cross our t's to make sure that the work on #15600 doesn't cause regressions. We could also do it with less (or no) benchmarks, and certainly we could remove/reduce them afterwards.

Makes sense. Okay, I'll merge this as is then. Once we have gh-15600 merged too, please remember to trim these benchmarks down.

**Comment by rgommers** [comment]
In it goes, thanks @j-bowhay!

**Pull request merged**
