### PR TITLE
FIX: generating random sparse matrix with size > max(int32)

### PR DESCRIPTION
**Pull request by haidark**
This fixes the following bug:
```
from scipy import sparse
N = 46952
x = sparse.random(N,N, density=100/N/N)
```
This occurs because the product of the matrix dimensions is larger than the maximum value of np.int32 and so the the `randint()` call fails. The fix passes the correct type to the `dtype` parameter. The documentation should be updated to mention that the `random_state.randint` function must accept a `dtype` argument.

### CODE REVIEW

**Comment by ilayn** [comment]
Thanks @haidark  Can you please also add some tests such that we can detect regressions in the future?

**Comment by haidark** [comment]
Added test to generate random matrix of size `10000000000`, which is greater than `np.iinfo(np.int32).max = 2147483647`.

**Comment by rgommers** [comment]
There is a real test failure here

**Comment by AtsushiSakai** [comment]
We can close this PR because this issue is already solved in main branch. 
```
In [1]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sy
   ...: s.version_info)
1.8.1 1.22.4 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

In [2]: from scipy import sparse

In [3]: N = 100

In [4]: %time x = sparse.random(N, N, density=100/N/N)
CPU times: user 1.03 ms, sys: 1.98 ms, total: 3.02 ms
Wall time: 7.85 ms

In [5]: N = 1000

In [6]: %time x = sparse.random(N, N, density=100/N/N)
CPU times: user 27.5 ms, sys: 2.77 ms, total: 30.3 ms
Wall time: 29.7 ms

In [7]: N = 10000

In [8]: %time x = sparse.random(N, N, density=100/N/N)
CPU times: user 6.68 s, sys: 244 ms, total: 6.92 s
Wall time: 7.2 s

In [9]: N = 46952

In [10]: %time x = sparse.random(N, N, density=100/N/N)
CPU times: user 15min 27s, sys: 54min 10s, total: 1h 9min 37s
Wall time: 1h 38min 31s
```

**Pull request closed without merging**
