### PR TITLE
ENH: add 'alternative' keyword to hypothesis tests in stats

### PR DESCRIPTION
**Pull request by aeklant**
See issue #4882

### CODE REVIEW

**Comment by rgommers** [comment]
Probably we shouldn't try to do all functions in this one PR - it'll be a pain to have correct and reviewed code hanging around, because after a while I will have forgotten what I did and didn't review. You can add some more functions here if you want (or leave this as is), but let's aim to merge this the coming week.

**Comment by aeklant** [comment]
I agree that we should merge this and keep the rest for a different PR later on. Maybe I should also remove the changes to `mannwhitneyu` since it will most likely be deprecated in gh-4933.

**Comment by aeklant** [comment]
@rgommers shall we merge this as is then? gh-4933 and this one as well seem to be on hold until we can decide the way to go with `mannwhitneyu` and `ranksums`. Is it deprecation? should `mannwhitneyu` be updated by merging this anyway?

**Comment by rgommers** [comment]
LGTM, merged. Thanks @aeklant

**Comment by rgommers** [comment]
Tests and changes are OK, so I didn't see a reason not to merge (more effort than merging).

**Pull request merged**
