### PR TITLE
MAINT: interpolate: move function definitions from __fitpack.h to _fitpackmodule.c

### LINKED ISSUE #1767: Function definitions in __fitpack.h should be moved. (Trac #1240)
_Original ticket http://projects.scipy.org/scipy/ticket/1240 on 2010-07-18 by @charris, assigned to @charris._

They aren't inlined, so should be in their own file or in _fitpackmodule.c. I don't know where scipy is on the multiple files thingie yet, so moving them into _fitpackmodule.c is probably the best short term solution.

### PR DESCRIPTION
**Pull request by ev-br**
closes gh-1767

The history is sort of preserved: github shows me as having written these C-to-Fortran wrappers (sigh), but `git blame -M -C -C` seems to detect the ground truth.

My secret agenda is to avoid a wall of warnings  about functions defined but not used I get in gh-3174 when trying to reuse a single routine from `__fitpack.h`.

In fact, I'm not sure what is the recommended layout of these C extension modules, would appreciate an advice.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
I say finish the job, and move *all* code and variables from `__fitpack.h` to `_fitpackmodule.c`.   For example, there is no reason for a declaration such as

    static char doc_bispev[] = " [z,ier] = _bispev(tx,ty,c,kx,ky,x,y,nux,nuy)";

or the definition of the function `_deBoor_D` to be in a header file.  In the end, you can probably remove `__fitpack.h`.  The only thing that includes it is `_fitpackmodule.c`, so nothing else will need the function prototypes.  `multipack.h` could use a review, too--the function definitions in there could be moved to a C file.

I'm looking into a similar clean up of some of the C code in scipy/integrate, but I'll wait for https://github.com/scipy/scipy/pull/4358 to be merged first.

**Comment by WarrenWeckesser** [comment]
I just reread this:
> My secret agenda is to avoid a wall of warnings about functions defined but not used I get in gh-3174 when trying to reuse a single routine from __fitpack.h.

and took a look at gh-3174, where you want to use `_deBoor_D()`.  Instead of completely removing `__fitpack.h` as I suggested above, it should have the prototype of the function `_deBoor_D()`, and `_deBoor_D()` shouldn't be declared as `static` in `_fitpackmodule.c`.  Alternatively, put `_deBoor_D()` in a C file by itself, with a corresponding header file containing the function prototype.  This function would then become a small self-contained library, to be used in `_fitpackmodule.c` and in the code in gh-3174.

**Comment by ev-br** [comment]
Addressed @WarrenWeckesser's comments in a force-pushed version, sort of --- made  `_deBoor_D` inline and left it in `__fitpack.h`. 

Also left the fortran wrapper prototypes in

**Comment by ev-br** [comment]
This does not apply cleanly after 8bbe97ac91ef109d864dc9f7b818b195db58d6ad and 3c8b54bb593e3e36f80228db82b5335dd625d15f which are actual bugfixes while this is just moving things around. It's easier to redo this from scratch than rebase, so I'll just close the PR for now.

**Pull request closed without merging**
