### PR TITLE
BUG: integrate: Make arrays passed to odeint user functions read-only.

### LINKED ISSUE #16170: BUG: scipy.integrate.odeint returns wrong values when derivative function overwrites y
### Describe your issue.

`odeint` supplies the original `y` vector to the derivative function so when the function writes the derivative directly into the vector it also overwrites the `y` vector in `odeint`. 

The function `derivative_1` from the code example overwrites `y` with the derivative. `odeint` doesnt seem to pass a copy of `y`, so its record is also overwritten. This only happens in the first time-step, after that `odeint` seems to properly pass copy's.

`derivative_2` produces the expected result since `y` is not overwritten,

### Reproducing Code Example

```python
from scipy.integrate import odeint

def derivative_1(y, t):
    y[0] = 1
    y[1] = 0
    return y

def derivative_2(y, t):
    return [1, 0]

y = [0, 1]
t = [0, 1, 2]

print(odeint(derivative_1, y, t)) # Produces wrong result.
print(odeint(derivative_2, y, t)) # Produces the expected result.
```

### Error message

```shell
There is no error message, but I cant submit this form without writing something into this field.
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Closes gh-16170.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The failed Windows job is not related to this PR.  It looks like some sort of CI infrastructure issue:

```
[...]
 Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
   ---------------------------------------- 87.5/87.5 kB 2.5 MB/s eta 0:00:00
Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 1.2/1.2 MB 37.4 MB/s eta 0:00:00
Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
   ---------------------------------------- 121.1/121.1 kB 3.6 MB/s eta 0:00:00
Downloading zipp-3.19.0-py3-none-any.whl (8.3 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 7a89180babf3b6af321f5d6970f8a90d687977565a48f05dc4ce75dfb94c777d
             Got        52c33cdda6efdc34dc995f43c7b0cd170e99b63331e9f2bc1d7a2aad6471df30

Error: Process completed with exit code 1.
```

**Review by rgommers — COMMENTED** [review]
Thanks Warren. This change makes sense in an ideal world. I suspect however that this is a breaking change when users supply a function written in Cython (xref gh-20196).

To get around that, it may be needed to call the function once with a read-only array, catch ValueError/TypeError, and avoid using read-only arrays from then on if an error got caught.

**Comment by WarrenWeckesser** [comment]
@rgommers, do you have an example of how this could cause a problem?  Clearing the WRITEABLE bit dynamically has nothing to do with `const`-ness of arguments in compiled code.

**Comment by rgommers** [comment]
> Clearing the WRITEABLE bit dynamically has nothing to do with `const`-ness of arguments in compiled code.

You'd think that yes, based on how things _should_ work - but tell that to Cython. The example in gh-17172 does what you say here, and it was failing for a very basic `linalg.expm` call. Cython chokes on read-only arrays unless arguments in the Cython function are declared as `const`.

**Comment by WarrenWeckesser** [comment]
Heh, I even commented in gh-17172 (a mind like a steel sieve).  OK, I'm not going to pursue this further.

If `odeint` was a new function, we could specify up front that the arrays passed to user functions will be read-only, so if a user implements their functions in Cython, they must use `const` appropriately.  But I guess we can't add this now without introducing a backwards compatibility break.  Maybe it could be considered for a SciPy 2.0 API change.

**Comment by rgommers** [comment]
>  Maybe it could be considered for a SciPy 2.0 API change.

Agreed, and even then it's a stretch perhaps. At a minimum we first need to fix all our own Cython code to work with read-only arrays, and properly test that.

**Pull request closed without merging**
