### PR TITLE
MAINT: SciPy 1.15.0rc2 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
These aren't all strictly bug fixes, but maybe "ok" given size of release. I've made a note where I had to manually resolve merge conflicts.

TODO:

- [x] ~some backport PRs are not merged yet: https://github.com/scipy/scipy/pulls?q=is%3Aopen+is%3Apr+label%3Abackport-candidate+is%3Aopen~
- [x] test wheel builds before merge most likely, so I can be confident we are ready for rel process
- [x] ~I have 4 doc build warnings locally related to `scipy.stats`--we'll see if the CI reproduces them~ (CI doesn't repro, so I'll ignore them)
- [x] ~consider performing the reversion that Evgeni describes here: https://github.com/scipy/scipy/issues/22143#issuecomment-2558181896~ (no longer needed, bug fix merged and labeled for backport)
- [x] update release notes/related lists after the additional backport activity

Backports included so far:

1. gh-22025 (cherry-pick ~15 commits)
2. gh-22081 (manual merge conflict resolution)
3. gh-22082
4. gh-22098
5. gh-22104 (manual merge conflict resolution)
6. gh-22106
7. gh-22107
8. gh-22124
9. gh-22129
10. gh-22135
11. gh-22139
12. gh-22162
13. gh-22156
14. gh-22113
15. gh-22099
16. gh-22149
17. gh-22085
18. gh-22158
19. gh-22168
20. gh-22177
21. gh-22175
22. gh-22167

### CODE REVIEW

**Comment by tylerjereddy** [comment]
@ev-br I thought I had a backport on your shims but maybe missing one

```
Expected:
    (array([0, 0, 1, 2, 2]), array([0, 1, 2, 0, 2]))
Got:
    (array([0, 0, 1, 2, 2], dtype=int32), array([0, 1, 2, 0, 2], dtype=int32))
```

**Comment by dschult** [comment]
@ev-br had a reasonable backport for those dtype shims in 22085.
I added the backport-candidate label just now.

**Review by mdhaber — APPROVED** [review]
I took a look at the stats and release notes stuff that's here now, and it LGTM. Thanks!

**Comment by jorenham** [comment]
https://github.com/scipy/scipy/pull/22156 also seems relevant

**Comment by jorenham** [comment]
As @steppi mentioned in https://github.com/scipy/scipy/pull/22156#issuecomment-2558462489, [`scipy.special.sph_harm`](https://scipy.github.io/devdocs/reference/generated/scipy.special.sph_harm.html) has been deprecated in favor of
[`scipy.special.sph_harm_y`](https://scipy.github.io/devdocs/reference/generated/scipy.special.sph_harm_y.html#scipy.special.sph_harm_y).
So that should probably also be included in the release notes.

**Comment by tylerjereddy** [comment]
- I've updated this PR to that we're at parity with the 17 merged backport PRs, and the `smoke-docs` check looks healthier locally at least now
- I added Joren's release note suggestion and the doc build/relnotes still looked good locally
- We'll see if the regular CI is finally happy here
- There are still some unmerged backport-labeleld PRs--I'll see where things stand in the morning tomorrow

**Comment by h-vetinari** [comment]
All other things being equal, I think we should not exclude backports which:
* have a merged PR
* solve one of:
  * execute or announce deprecations, especially if not in sync with our docs or the rest of scipy
  * the king of bugfix that we'd backport to a point release anyway (targeted fix, not 100s of lines of overhaul)
  * fix a consistency hole in APIs that were added or changed during this release cycle (better to delay than release a known-bad state)

Of course, it's reasonable to define a cut-off at some point, but the above kinds of PRs in particular can IMO be backported during all the rc phase, and even up to GA (subject to the RM's opinion of course, but speaking generally).

Also, there's a kind of natural response to the rc phase where people start double-checking things and finding issues. Obviously it would be better if that happened already before the branch, but it happens every release from what I can tell, and we shouldn't discard these issues just because they arrive late (though it makes sense to decide on a case-by-case basis whether a backport is justified).

**Comment by tylerjereddy** [comment]
Ok, I don't think I have any plans to *not* backport anything that was requested so far, let me know if I'm missing one. https://github.com/scipy/scipy/pull/22167#pullrequestreview-2521007835 was my comment re: the one in question I think.

**Comment by tylerjereddy** [comment]
We're back at parity with the 5 additional merged backport PRs, there are no remaining unmerged backport PRs, local testing/doc build/smoke-docs looks "ok," proceeding with (hopefully final) wheel build check. If the CI is all green (include wheels, but ignoring some known flakes), the release process can be started.

**Comment by tylerjereddy** [comment]
I don't think I'll let the on test crash in the fail slow job, `worker 'gw1' crashed while running 'build-install/Lib/site-packages/scipy/linalg/tests/test_extending.py::test_cython'` hold up the release. This test has quite a few skip markers and known issues on Windows already (https://github.com/scipy/scipy/issues/22039)

**Comment by tylerjereddy** [comment]
Wheel builds for RC2 were started this evening -- I'll resume the rel process on the morning of the 24th.

- GitHub Actions: https://github.com/scipy/scipy/actions/runs/12476043834
- Cirrus CI: https://cirrus-ci.com/build/5361784862801920

**Pull request merged**
