### PR TITLE
MAINT: 1.9.3 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
Backport 37 PRs after manually curating merges to `main` that seemed suitable for backporting. Only gh-17200 had a merge conflict to resolve, in the `meson` build system. List of backports is below; I didn't have the steam to fixup `.mailmap` but that's a lot of PRs so some names in author list probably could use a cleanup, though that's at least not critical I suppose.

- gh-5288
- gh-13322
- gh-13349
- gh-15363
- gh-15381
- gh-16212
- gh-16288
- gh-16318
- gh-16460
- gh-16506
- gh-16521
- gh-16525
- gh-16528
- gh-16562
- gh-16573
- gh-16588
- gh-16590
- gh-16630
- gh-16645
- gh-16649
- gh-16657
- gh-16669
- gh-16701
- gh-16752
- gh-16780
- gh-16836
- gh-16872
- gh-16965
- gh-17043
- gh-17090
- gh-17105
- gh-17166
- gh-17190
- gh-17193
- gh-17200
- gh-17204
- gh-17209
- gh-17210

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The 1 test failure I see looks like an easy fix--probably the result of cherry-picking a patch that depended on an import that didn't exist on the maintenance branch.

**Comment by tylerjereddy** [comment]
`DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.` I'm pretty sure Ralf and Sebastian were talking about a fix that already happened for that recently on `main`. I haven't check if that is appropriate for backporting but maybe.

**Comment by tylerjereddy** [comment]
thanks, I backported that as well, I'll probably merge in the next day or two if nobody has reason to object, and then turn my attention to `1.9.3` release process

**Review by rgommers — APPROVED** [review]
Wow, thanks for that very comprehensive checking and backporting @tylerjereddy

**Pull request merged**
