### PR TITLE
MAINT: update pydata-sphinx-theme

### PR DESCRIPTION
**Pull request by tupui**
The new version of the theme adds a theme switcher (light, dark, auto mode).

Also took the opportunity to add our twitter handle.

cc @tylerjereddy this would be good to get in.

### CODE REVIEW

**Comment by rgommers** [comment]
> I understand. It's unfortunate that our doc updates are too much linked to our releases. We should find a way to work on such UX improvement and not have to make a full release to see changes.

http://scipy.github.io/devdocs/ - not to different from code changes/features I'd say.

**Comment by tupui** [comment]
Note that this PR will fix the current issue in the doc CI
`preparing documents... WARNING: unsupported theme option 'logo_link' given
`

**Review by jarrodmillman — CHANGES_REQUESTED** [review]

**Review by rgommers — APPROVED** [review]
conda-forge package is available now, so the one CI error can be ignored.

LGTM, thanks @tupui

**Comment by rgommers** [comment]
> Yes status on main is not my concern, but there is no easy path to update 1.8.1 for instance.

If we do a 1.8.2, it will rebuild with the newer version of the theme I think, cause we don't pin with `==`. Other than that, I don't quite understand the problem. The release has been shipped, and we don't update code, package, docs, or anything else (except in case of really egregious problems, but it's very very rare).

**Comment by tupui** [comment]
It's an inconvenience when we want to update the theme without touching the content. Like adding the version switcher. I think it is a Sphinx issue more than anything else. I am not sure if there is a way to just rebuild the style/theme without having to rebuild from scratch.

**Comment by rgommers** [comment]
I don't think that there is. That'd be a nice feature also for development though

**Comment by tupui** [comment]
@tylerjereddy if this goes in 1.9, then #16379 should also get in to have a better experience with dark mode.

**Pull request merged**
