### PR TITLE
DEP: `stats.find_repeats`: deprecate function

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-21077

#### What does this implement/fix?
The docstring of `find_repeats` mentions:
> In numpy >= 1.9 `numpy.unique` provides similar functionality. The main difference is that `find_repeats` only returns repeated values.

NumPy 1.9 has been available for a while now, and we were not able to find many uses of `find_repeats` (gh-21077), so we discussed removing the function rather than adding array API support.

#### Additional information
Needs approval on [discuss](https://discuss.scientific-python.org/t/deprecate-stats-find-repeats/1286) before merge.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
I guess if you do this you need one more spot patched as below (or with a suppression of the warning, or with replacement by the NumPy equivalent). By the way, what happens for the `mstats` version of the function if you do this? Does that one get to stay since the mask-related functionality is still unique to SciPy?

```diff
--- a/scipy/stats/tests/test_mstats_basic.py
+++ b/scipy/stats/tests/test_mstats_basic.py
@@ -1865,7 +1865,9 @@ class TestCompareWithStats:
         xm = np.ma.array(tmp, mask=mask)
         x_orig, xm_orig = x.copy(), xm.copy()
 
-        r = stats.find_repeats(x)
+        message = "`scipy.stats.find_repeats` is deprecated..."
+        with pytest.deprecated_call(match=message):
+            r = stats.find_repeats(x)
```

**Comment by mdhaber** [comment]
Yes, I'll fix that. 
And yes, I think the `mstats` version can stay for that reason and others.

**Review by j-bowhay — COMMENTED** [review]
@mdhaber I would be happy to review and merge this, it has been a week no complaints from the dev forum

**Review by j-bowhay — APPROVED** [review]
Thanks @mdhaber

**Pull request merged**
