### PR TITLE
Added class ExactKrylovJacobian

### PR DESCRIPTION
**Pull request by gabrielfougeron**
Hi,

This PR addresses issue #15367 

I've been using this code for a while now in a personal project of mine.
I use it as a parametrized substitution of ```scipy.optimize.nonlin.KrylovJacobian```. It showed very good convergence behavior near a solution, where massive cancellation is avoided.
My usage case looks something like this:

```
if (Use_exact_Jacobian):

    FGrad = lambda x,dx : Compute_action_hess_mul(x,dx,callfun)
    jacobian = ExactKrylovJacobian(exactgrad=FGrad,**jac_options)

else: 
    jacobian = scipy.optimize.nonlin.KrylovJacobian(**jac_options)

x0 = np.copy(best_sol.x)
opt_result = scipy.optimize.nonlin.nonlin_solve(F=F,x0=x0,jacobian=jacobian,verbose=disp_scipy_opt,maxiter=maxiter,f_tol=gradtol,line_search=line_search,callback=best_sol.update,raise_exception=False)
                
```

I have little experience contribution to big open source project, so don't hesitate to tell me if more info is required etc...

In particular, I have little understanding of the inner workings of scipy.optimize, so I am not sure how to best propagate these changes at the user level.

Cheers,

### CODE REVIEW

**Comment by tupui** [comment]
Thank you @gabrielfougeron for the PR. Provided @andyfaff confirms this is wanted, it would need some tests.

On my side, it looks very simple and I feel it would be better suited in some doc. I will let specialists weight in.

**Comment by gabrielfougeron** [comment]
Indeed it's nothing extravagant in terms of code, but in order to achieve this, you really need to get deep into the inner workings of scipy.optimize. As a layman, it was actually quite hard to achieve, and the optimize series of calls really felt like a deep rabbithole. 

As mentioned in the issue though, the functionality is already present for scipy.optimize.minimize via the hessp argument. So I can't believe I would be the only one to need/want this kind of addition.

**Comment by andyfaff** [comment]
@tupui, I'm not familiar/expert with nonlin, going to need another expert here.

**Comment by rgommers** [comment]
@zhaog6 you've been improving Krylov methods, maybe you have an opinion on whether this is worth adding?

**Comment by zhaog6** [comment]
Thanks @gabrielfougeron for your contribution. What does the keyword `Exact` in `ExactKrylovJacobian` mean? (Generally, it means to use like automatic differentiation (AD-like) to exactly find Jacobian/gradient of function, but it's not common). 
The `matvec` in `KrylovJacobian` implemented Jacobian-Free Newton-Krylov, and the finite difference form for approximating Jacobian is popular, which is enough in most cases. With your issue, I guess you might need a better approximation of Jacobian.
Have you implemented `Compute_action_hess_mul` by high-order difference or other approximate methods in your personal project? Could you provide the specific form of `f` mentioned in the issue #15367?

**Comment by gabrielfougeron** [comment]
The keyword maybe could have been better chosen indeed. In this case, it is meant at giving the user the opportunity to provide their own hand coded jacobian matrix vector product. In my case, I compute it with no approximation. The soundness of such an approach of course depends on the problem at hand, but it made sense in my case.

**Comment by zhaog6** [comment]
> In this case, it is meant at giving the user the opportunity to provide their own hand coded jacobian matrix vector product.

I see, that's what I mean. Whether it is exact Jacobian or design high-order approximation for Jacobian (by evaluating matrix-vector products), a `matvec` interface that can be customized by users is needed. It would be nice to include related references and test cases for this interface.

**Pull request closed without merging**
