### PR TITLE
BUG: refix wrong shape from median_absolute_deviation for arrays with size 0 and an axis

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
Refix #11720

#### What does this implement/fix?
Refix wrong shape from median_absolute_deviation for arrays with size 0 and an axis based on the discussion in #11735

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Thanks @AtsushiSakai, but the logic is still not correct.  The array shape handling must be consistent, even when the input contains `nan`.  You still have this in your code:

    if contains_nan and nan_policy == 'propagate':
        return np.nan

which means the scalar `nan` is returned for any array that contains `nan`, even when the array is 2-d or higher-dimensional.

So, with this PR, we have
```
In [22]: x
Out[22]:
array([[ 1.,  2.,  3., nan],
       [nan, nan, nan, nan],
       [ 1.,  1.,  2.,  2.]])

In [23]: median_absolute_deviation(x, axis=1)
Out[23]: nan
```
That is not what we want.  The output in that case should be the three values `[nan, nan, 0.7413]`.

(I just took another look at https://github.com/scipy/scipy/issues/11720, and I realize some of what I wrote in the description of the problem might be confusing.  In the text, I described how it *should* behave, but the first two examples where I call `median_absolute_deviation(z, axis=0)` and `median_absolute_deviation(z, axis=1)`, demonstrate the incorrect behavior that exists in the master branch.  I just edited the issue to clarify that.)

I discovered a second problem that occurs if we use `nan_policy='omit'` with that input.  This problem exists in the master branch, so it is not in your code, but we might as well fix this, too.  With `x` shown above, the expected output of `median_absolute_deviation(x, axis=1, nan_policy='omit')`  is an array that contains `[1.4826, nan, 0.7413]`, but instead we get an error:

```
In [30]: median_absolute_deviation(x, axis=1, nan_policy='omit')
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
<ipython-input-30-b275f204adf0> in <module>
----> 1 median_absolute_deviation(x, axis=1, nan_policy='omit')

~/mc37scipy/lib/python3.7/site-packages/scipy-1.5.0.dev0+16f58e5-py3.7-macosx-10.7-x86_64.egg/scipy/stats/stats.py in median_absolute_deviation(x, axis, center, scale, nan_policy)
   2856         mad = np.median(np.abs(arr - med))
   2857     else:
-> 2858         med = np.apply_over_axes(center, arr, axis)
   2859         mad = np.median(np.abs(arr - med), axis=axis)
   2860 

<__array_function__ internals> in apply_over_axes(*args, **kwargs)

~/mc37scipy/lib/python3.7/site-packages/numpy/lib/shape_base.py in apply_over_axes(func, a, axes)
    493             axis = N + axis
    494         args = (val, axis)
--> 495         res = func(*args)
    496         if res.ndim == val.ndim:
    497             val = res

<__array_function__ internals> in median(*args, **kwargs)

~/mc37scipy/lib/python3.7/site-packages/numpy/lib/function_base.py in median(a, axis, out, overwrite_input, keepdims)
   3500     """
   3501     r, k = _ureduce(a, func=_median, axis=axis, out=out,
-> 3502                     overwrite_input=overwrite_input)
   3503     if keepdims:
   3504         return r.reshape(k)

~/mc37scipy/lib/python3.7/site-packages/numpy/lib/function_base.py in _ureduce(a, func, **kwargs)
   3388         keepdim = list(a.shape)
   3389         nd = a.ndim
-> 3390         axis = _nx.normalize_axis_tuple(axis, nd)
   3391 
   3392         for ax in axis:

~/mc37scipy/lib/python3.7/site-packages/numpy/core/numeric.py in normalize_axis_tuple(axis, ndim, argname, allow_duplicate)
   1321             pass
   1322     # Going via an iterator directly is slower than via list comprehension.
-> 1323     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1324     if not allow_duplicate and len(set(axis)) != len(axis):
   1325         if argname:

~/mc37scipy/lib/python3.7/site-packages/numpy/core/numeric.py in <listcomp>(.0)
   1321             pass
   1322     # Going via an iterator directly is slower than via list comprehension.
-> 1323     axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
   1324     if not allow_duplicate and len(set(axis)) != len(axis):
   1325         if argname:

AxisError: axis 1 is out of bounds for array of dimension 1
```

-----

For what it's worth, it turns out that I am working on a similar change to `scipy.stats.variation`.  The pull request is https://github.com/scipy/scipy/pull/11754.  There are differences between that function and `median_absolute_deviation`, so it probably doesn't make sense to copy that code exactly, but it does show some of the special handling that might be necessary to achieve the desired API.

**Comment by AtsushiSakai** [comment]
@WarrenWeckesser Hi. Thank you so much for your detailed comments. I fixed my code based on your comment to fix the two issues. PTAL.

**Comment by AtsushiSakai** [comment]
Some CI failed due to "UserWarning Invalid value encountered in median".
- https://travis-ci.org/github/scipy/scipy/jobs/669633172#L1473-L1475
- https://travis-ci.org/github/scipy/scipy/jobs/669633172#L1388-L1390

However, current numpy code removed these warnings by https://github.com/numpy/numpy/pull/12679

**Comment by AtsushiSakai** [comment]
The RuntimeWarning issue was avoided by adding warning filter.

**Comment by AtsushiSakai** [comment]
@WarrenWeckesser Could you help me to review this PR if you have time?

**Comment by rlucas7** [comment]
The travis build failure is unrelated to the changes here:
https://travis-ci.org/github/scipy/scipy/jobs/677212865#L983
and there is an open PR for it already:
https://github.com/scipy/scipy/pull/11902

**Comment by WarrenWeckesser** [comment]
@AtsushiSakai, I'll get back to this on Thursday--if no one else gets to it sooner.

**Comment by AtsushiSakai** [comment]
@WarrenWeckesser OK. Thank you!!

**Comment by WarrenWeckesser** [comment]
@AtsushiSakai, thanks for continuing to work on this.  There are still some issues with the logic when handling edge cases (e.g. `median_absolute_deviation([], aixs=999)` should raise `AxisError`), and I've discovered some new bugs in the `nan_policy` code that I think existed before your changes.  I'm afraid that to explain all the little issues and get this working correctly, I'll end up rewriting the code and then say "just do this".  That's not a good use of either of our's time.  I think it will be easier if I start a new pull request of my own to fix these issues.  I hate to do this, when you're doing such great work, but in this case, it turns out that some of the existing patterns in the code are bad and shouln't be emulated.

Instead, what I'll do is create a new pull request that handles the edges cases and `nan_policy` as cleanly as possible.  I'm also running into similar issues with `variation` over gh-11754; gh-11896 is another PR to fix edge-case handling.  I suspect that the work on these functions will lead to a set of utility functions that we can use elsewhere to help ensure that we maintain a consist API throughout `scipy.stats` and other SciPy modules.

**Comment by AtsushiSakai** [comment]
@WarrenWeckesser Thank you for your comment. I understand your concern. I’ll close this PR. If there’s something I can help you, please let me know.

**Pull request closed without merging**
