### PR TITLE
ENH: Make cython_special actual code, not autogenerated

### PR DESCRIPTION
**Pull request by izaid**
The intention is to update `cython_special` to go along with our general modernisation of `special`

Back in https://github.com/scipy/scipy/pull/20260, we updated the ufunc machinery so that there was no longer any need for autogenerated loop functions for ufuncs. This PR handles the complementary Cython generation. For `cython_special`, however, the process is *way* simpler. The functions in `cython_special` just provide Cython-level access to the scalar kernels. There is no need for any autogeneration really, hence we can just paste in the current autogenerated Cython file (`cython_special.pyx` and `cython_special.pxd`) and start modifying them.

This will allow us to start deleting ufuncs from `_generate_pyx.py`, meaning we will no longer be duplicating ufuncs. We will also not need to maintain all these C wrappers for each scalar kernel, which are being wrapped in Cython anyway. The goal is `cython_special` should be wrapping the functions directly, in a way that is easy to modify. It may be possible to ultimately turn `cython_special` into a `pxd` file, which would also take it out of the binary size.

### CODE REVIEW

**Comment by izaid** [comment]
This is, in fact, done. @steppi What do you think?

This PR makes `_generate_pyx.py` generate only the ufuncs, everything else has been removed from it.

**Comment by steppi** [comment]
As an interim measure, this sounds like a good idea. I haven't considered things carefully yet though and want to hear feedback from others too. We need to update the documentation here: https://docs.scipy.org/doc/scipy/dev/api-dev/special_ufuncs.html; It needs updating anyway. I can submit a PR to your branch with an update to that doc page tomorrow if you like.

**Review by rgommers — COMMENTED** [review]
This looks like a very nice simplification. Can you also get rid of `_cython_special.pxi` and `_cython_special_custom.pxi`? They're two short files that seem to be only included once, and can now be included verbatim at the top of `cython_special.pyx` instead.

Furthermore, now that `cython_special.pxd` is a regular file, you can also get rid of this in `special/meson.build`:
```meson
cython_special_pxd = custom_target('_dummy_cython_special.pxd', ...
```
and replace it with a much simpler:
```meson
cython_special_pxd = fs.copyfile('cython_special.pxd')
```
which is nice because that `custom_target` currently re-runs on every build invocation and the `copyfile` replacement won't.

**Comment by izaid** [comment]
> _cython_special_custom.pxi

Great ideas! Done. Your suggested update to `meson.build` also fixed a build issue with `scipy.special`, which now is as is before.

**Review by steppi — APPROVED** [review]
Looks good. The failure is unrelated. Let's get this in. I'll submit a follow-up updating the developer docs for `special`. Also, good idea too, just adding the `.pyi` type stubs file directly instead of auto-generating it.

**Comment by lucascolley** [comment]
Yep, that's https://github.com/scipy/scipy/pull/20422#issuecomment-2045980635, should be fixed soon.

**Comment by izaid** [comment]
> I believe this broke scikit-learn
> 
> ```
>       [199/249] Compiling Cython source /home/tcaswell/source/p/scikit-learn/scikit-learn/sklearn/tree/_criterion.pyx
>       FAILED: sklearn/tree/_criterion.cpython-312-x86_64-linux-gnu.so.p/sklearn/tree/_criterion.pyx.c
>       cython -M --fast-fail -3 '-X language_level=3' '-X boundscheck=False' '-X wraparound=False' '-X initializedcheck=False' '-X nonecheck=False' '-X cdivision=True' '-X profile=False' --include-dir /home/tcaswell/source/p/scikit-learn/scikit-learn/.mesonpy-tqmycukf /home/tcaswell/source/p/scikit-learn/scikit-learn/sklearn/tree/_criterion.pyx -o sklearn/tree/_criterion.cpython-312-x86_64-linux-gnu.so.p/sklearn/tree/_criterion.pyx.c
> 
>       Error compiling Cython file:
>       ------------------------------------------------------------
>       ...
> 
>       import numpy as np
>       cimport numpy as cnp
>       cnp.import_array()
> 
>       from scipy.special.cython_special cimport xlogy
>       ^
>       ------------------------------------------------------------
> 
>       /home/tcaswell/source/p/scikit-learn/scikit-learn/sklearn/tree/_criterion.pyx:23:0: 'scipy/special/cython_special.pxd' not found
> ```
> 
> Reverting to [ad0edb9](https://github.com/scipy/scipy/commit/ad0edb959d9a180b7a64be52cbe301f2722d471d) makes sckit-learn build again.

Right, thanks for flagging @tacaswell and thanks for answering @lucascolley. Looks like there is already a fix in the works! Not sure how that happened, but we've been discovering quite a lot of untested things in SciPy special.

**Pull request merged**
