### PR TITLE
Rephrase collection of libraries that use PyData-Sphinx

### PR DESCRIPTION
**Pull request by stefanv**
NumFOCUS is not the binding factor here, so replacing it with "ecosystem".

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
LGTM, thanks

I usually "bump the version" on the release branch before adding in the next batch of backports. Actually, not sure there's a strict need for that, maybe just habit. Anyway, will merge at that time.

**Comment by stefanv** [comment]
Thanks, Tyler!

**Review by rgommers — APPROVED** [review]
Agreed, this reads better. Thanks Stefan.

**Comment by tylerjereddy** [comment]
One mistake I've made is not stripping out the line that says `.. note:: Scipy 1.7.0 is not released yet!` in the `1.7.0` "final" release notes (the tag has been pushed/wheels built).

Sorry about that--in any case, I can at least purge it from the GitHub release notes that get pasted in GUI and same for the email when it goes out later.

**Comment by rgommers** [comment]
that happens, no worries:)

**Comment by tylerjereddy** [comment]
Alright, there's already a joke about it on twitter, what can you do... :)

**Pull request merged**
