### PR TITLE
MAINT: special: some more Cephes cleanup

### PR DESCRIPTION
**Pull request by larsmans**

### CODE REVIEW

**Comment by rgommers** [comment]
Makes sense to me to reuse ``np.exp2``. But I'll let @pv merge this.

**Comment by juliantaylor** [comment]
I'm not so sure about the removal, numpys exp2 fallback is just exp(log(2)*x), which already fauls to produce 16 for 4.
the fallback is only used without the C exp2, but we all now on which platform this is probably missing.

**Comment by larsmans** [comment]
Oh... `exp2` is not in C89. My mistake. Meh!

Is lifting the Cephes function to NumPy an option, so at least `exp2` can go in the long run?

**Comment by larsmans** [comment]
Anyway, I removed the commit that deleted `exp2`, leaving only the error handling bit.

**Comment by charris** [comment]
I wouldn't mind, although we usually borrow from BSD. There is also a slightly cleaned up GO version, also borrowed from BSD.

**Comment by larsmans** [comment]
Merging the rest of this PR (without the `exp2` stuff) as it should be uncontroversial.

**Comment by ewmoore** [comment]
What the [revert-5143-cleanup](https://github.com/scipy/scipy/compare/revert-5143-cleanup) branch in this repo?

**Comment by larsmans** [comment]
That's me clicking the wrong button. Sorry, deleted the branch. I'm surprised GitHub puts it in *this* repo.

**Pull request merged**
