### PR TITLE
DEP: Remove setup.py install.

### LINKED ISSUE #12727: setup_requires is vestigial
There's some old code in the install script which is supposed to make sure all the build requirements exist:

https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/setup.py#L508-L524

This was added to address https://github.com/scipy/scipy/issues/3379.

The same issue exists/existed for:

* https://github.com/nilearn/nistats/issues/154
* https://github.com/scikit-learn/scikit-learn/issues/4164 (they ended up adopting your code: https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-76982101)
* https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-71550942
* https://github.com/apple/turicreate/issues/642

However it doesn't seem to work anymore:

```
[kousu@laptop scipy]$ python -m virtualenv ../venv
created virtual environment CPython3.8.5.final.0-64 in 365ms
  creator CPython3Posix(dest=/home/kousu/src/neuropoly/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/kousu/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[kousu@laptop scipy]$ . ../venv/bin/activate
(venv) [kousu@laptop scipy]$ python setup.py install

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Traceback (most recent call last):
  File "setup.py", line 590, in <module>
    setup_package()
  File "setup.py", line 565, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
```

`pip` works

```
(venv) [kousu@laptop scipy]$ pip install .
Processing /home/kousu/src/neuropoly/scipy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ...
```

because you have https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/pyproject.toml.

It seems like you're maintaining the build dependencies in two places: setup.py, where they're not being maintained, and pyproject.toml. I want to remove them from setup.py.

---

I don't really understand what happened. Did setuptools used to work differently? It looks to me like

https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/setup.py#L564-L565

always runs before setup() has a chance to even see `setup_requires`. You have that `run_build` flag to prevent running that code if numpy isn't installed yet, but it's not doing its job. I want to get rid of that too.

---

https://github.com/scikit-image/scikit-image/issues/4919 is the same issue. And they have the same problem: their setup.py unconditionally imports `numpy.distutils` before setup() has a chance to run to install build deps. I guess that's why https://www.python.org/dev/peps/pep-0517/ exists, because specifying build deps inside of setup.py is fraught.

### PR DESCRIPTION
**Pull request by kousu**
scipy is now using pep517-based pyproject.toml to install. It *must* be run by pip (or the [pep517 project](https://pypi.org/project/pep517/)) to install reliably. This makes this code vestigial.

#### Reference issue

Closes gh-12727.

#### What does this implement/fix?

`python setup.py install` is unreliable because it needs `numpy.distutils` but can't declare that dependency without also running a bunch of code that tries to import that. It's probably been broken for a long time. scipy has already migrated to [PEP 517](https://www.python.org/dev/peps/pep-0517/) to deal with this, so this completes the transition by deprecating `setup.py install` completely:

```
(venv) [kousu@laptop scipy]$ python setup.py install

`setup.py install` is not supported, use one of the following instead:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Add `--force` to your command to use it anyway if you must (unsupported).
```

### CODE REVIEW

**Comment by charris** [comment]
Hmm, I don't use pip locally because it has problems dealing with installs of multiple versions in arbitrary order.

**Comment by ev-br** [comment]
-1

**Comment by peterbell10** [comment]
If the problem is that `numpy` isn't installed in the build environment then shouldn't the fix be to unconditionally include `numpy` in the `setup_requires` instead of dropping it?

**Comment by tylerjereddy** [comment]
I still use `python setup.py install` locally pretty frequently, so I think I'm with Evgeni

**Comment by rgommers** [comment]
Agreed, this does not seem like the right solution. The issue you opened has an actual problem statement, so let's discuss there what the correct solution is.

**Comment by kousu** [comment]
On August 15, 2020 2:59:23 PM EDT, peterbell10 <notifications@github.com> wrote:
>If the problem is that `numpy` isn't installed in the build environment
>then shouldn't the fix be to unconditionally include `numpy` in the
>`setup_requires` instead of dropping it?

I hoped that too but I tried and it doesn't work because setup.py needs to load numpy.distutils in order to call setup() in the first place.

PyPA is in the process of deprecating most of setuptools. They've mentioned this lots of times on their bug trackers, but I don't know of an obvious announcement on the tools themselves or on any of their websites. They want everyone to migrate to pep517. (I wish there was a better upgrade path planned)

**Comment by kousu** [comment]
On August 15, 2020 2:59:23 PM EDT, peterbell10 <notifications@github.com> wrote:
>If the problem is that `numpy` isn't installed in the build environment
>then shouldn't the fix be to unconditionally include `numpy` in the
>`setup_requires` instead of dropping it?

Maybe keep `install` but at the very least `setup_requires` needs to go away. Look at my bug report: `setup_requires` is not doing its job.

**Pull request closed without merging**
