### PR TITLE
TST: parametrize some test class methods in stats distributions

### PR DESCRIPTION
**Pull request by rlucas7**
#### Reference issue
N/A

#### What does this implement/fix?
Some refactoring of tests for `trapz` and `triang` to make them less verbose.

#### Additional information
Test cases are unchanged with this PR. 
For some reason the way the tests were written, with lots of repetitive characters/statements, was bothering me.

### CODE REVIEW

**Review by andyfaff — COMMENTED** [review]
50:50 either way. I personally find parameterised tests much harder to follow, but I can see how the other point of view is valid as well

**Comment by rlucas7** [comment]
> 50:50 either way. I personally find parameterised tests much harder to follow, but I can see how the other point of view is valid as well

Sure. The thing that I prefer about the approach is 2 things really:

(i) it allows you to add test cases without changing the "execution" code but this is both a strength and a limitation (e.g. if you want the flexibility) 
(ii) the separation (on different lines) of the input data from the code executed for output values makes it easier to focus on what calculation is being done versus the inputs. 

For example with these changes, I find it much easier to determine which set of inputs executes a specific function and input values as compared to the previous code. 

That being said if we don't think this is helpful, I can close.

**Review by mdhaber — APPROVED** [review]
I like `parametrize`. I'd prefer `scipy.stats.pdf` over `'pdf'`/`getattr`, but not blocking. 2.5 is better than many PRs, so I'd be happy to merge tomorrow if there are no objections.

**Comment by rlucas7** [comment]
realizing now the full green of CI is unlikely b/c of the failing `scipy/linalg/tests/test_lapack.py::test_heequb` test:
https://travis-ci.org/github/scipy/scipy/jobs/677958981#L1155
so I'll leave this alone for now, should be green besides the heequb issue.

**Comment by mdhaber** [comment]
I think we'll fix `test_heequb` soon. I've got it backed into a corner in gh-11902.

**Comment by rgommers** [comment]
Besides the readability, something to consider for `parametrize` is what happens if there's a bug in the object under test. In this case, it's generate 12 failures instead of a single failure. I'm not sure that's helpful - it has proven to be annoying sometimes in the past. The cases under test aren't really distinct. 

Also, it's probably slower since many more test cases are generated. So I'd lean towards not merging this.

**Comment by rlucas7** [comment]
@rgommers

Not sure why you say it’s slower, the number of tests are the same. The only slowdown would maybe be from the introspection which I’d guess is minimal. 

I hear your point on the multiple failures but that really depends on how the methods are failing. This might also tie in with Matt’s comment about the same test for both cdf and pdf methods. I could separate to two tests, one for pdf alone and another for cdf alone. 

Given we’ve got a +1, a -1, and a 50/50, I’m wondering if I should close out the PR or to separate out the two methods into two distinct tests?

Sincerely, 

-Lucas Roberts

**Comment by rgommers** [comment]
Try putting this in a file `parametrize.py` and running it as `pytest parametrize.py`:
```
import pytest
from numpy.testing import assert_almost_equal
from scipy import stats


class TestTrapz(object):
    @pytest.mark.parametrize('method, inputs, expected', [
        # edge cases
        ('pdf', (0, 0, 0), 2),
        ('pdf', (1, 1, 1), 2),
        ('pdf', (0.5, 0, 0.8), 1.11111111111111111),
        ('pdf', (0.5, 0.2, 1.0), 1.11111111111111111),
        # straightforward case
        ('pdf', (0.1, 0.2, 0.8), 0.625),
        ('pdf', (0.5, 0.2, 0.8), 1.25),
        ('pdf', (0.9, 0.2, 0.8), 0.625),
        ('cdf', (0.1, 0.2, 0.8), 0.03125),
        ('cdf', (0.2, 0.2, 0.8), 0.125),
        ('cdf', (0.5, 0.2, 0.8), 0.5),
        ('cdf', (0.9, 0.2, 0.8), 0.96875),
        ('cdf', (1.0, 0.2, 0.8), 1.0)
    ])
    def test_cases(self, method, inputs, expected):
        result = getattr(stats.trapz, method)(*inputs)
        assert_almost_equal(result, expected)
```

You'll see it will report running 12 tests, not 1 test. I'm not sure if the overhead is relevant, and that's less important than the multiplication in tests. 

> I hear your point on the multiple failures but that really depends on how the methods are failing.

Sure, but there's also not much to gain. If it's one corner case, it will still be clear in the way the test is currently written.

> Given we’ve got a +1, a -1, and a 50/50, I’m wondering if I should close out the PR or to separate out the two methods into two distinct tests?

I'd suggest closing, since there's at least no significant improvement here.

**Comment by rlucas7** [comment]
>I'd suggest closing, since there's at least no significant improvement here.

I was just trying to make the tests easier to read and follow. I guess my definition of easy to read is a bit off from others. Closing.

**Comment by rgommers** [comment]
> I was just trying to make the tests easier to read and follow. I guess my definition of easy to read is a bit off from others. Closing.

Thanks anyway @rlucas7

**Comment by tylerjereddy** [comment]
It may also be interesting to follow the [development of subtests in Python](https://blog.ganssle.io/articles/2020/04/subtests-in-python.html) as a lighter-weight alternative.

**Pull request closed without merging**
