### PR TITLE
MAINT: remove lsim2/impulse2/step2 docstring examples

### PR DESCRIPTION
**Pull request by h-vetinari**
Alternative to #18471 as one of the [suggestions](https://github.com/scipy/scipy/pull/15929#issuecomment-1549065305) how to unbreak the doc build.

Closes #18471

### CODE REVIEW

**Comment by h-vetinari** [comment]
@mdhaber @rgommers @tupui
This fixes the doc build failure on main, and should be less of a big hammer than #18471. There's also a third [alternative](https://github.com/scipy/scipy/pull/18471#issuecomment-1549108421) that doesn't have a PR yet, but it would probably take some more time because I'm not sure that it covers all current warnings.

I think the ~best~ least bad solution would be merging this PR, and then opening another PR without the pressure of a broken CI, that reinstates the examples & refixes the doc build. We could also just forget about the docstring examples of these functions, but fixing the other warnings would IMO be a good thing in itself, so uncovering those is not necessarily something to be shunned.

PS. The one failure here is due to a download error from the ubuntu repos.

**Review by rgommers — APPROVED** [review]
Thanks @h-vetinari, this works and is fine with me. Either this, or fixing the doc builds works. A partial revert as in gh-18471 is less ideal, partial reverts are usually messy and it'd require yet more follow ups to then reinstate the part that was reverted.

Unless someone disagrees, I plan to merge this later today to unbreak CI.

**Comment by h-vetinari** [comment]
> A partial revert as in [gh-18471](https://github.com/scipy/scipy/pull/18471) is less ideal, partial reverts are usually messy and it'd require yet more follow ups to then reinstate the part that was reverted.

FWIW, I did the partial revert to minimize the churn (i.e. keep test improvements), and it's functional (failures are likewise due to flaky Ubuntu repos today), but I prefer this PR. So +1 for your plan. Afterwards, I can open a follow-up to investigate the sphinx warnings.

**Review by j-bowhay — APPROVED** [review]
Thanks @h-vetinari

**Pull request merged**
