### PR TITLE
DOC/CI: do not allow sphinx 4.1.

### LINKED ISSUE #14396: BUG: Sphinx 4.1 breaks the banner's logo
Sphinx 4.1 was released on July 11th, 2021. Since then the logo file is not present anymore in the artifact which is uploaded. As we did not touch anything (I checked pipelines before and after to confirm this), I am confident this is linked to Sphinx release.

[EDIT: the path is indeed changed to `/_static/_static/scipyshiny_small.png` due to a Sphinx regression, see the linked Sphinx PR below.]

From the logs
```
# working
Running Sphinx v4.0.3
SciPy (VERSION 1.8.0.dev0+1419.1d97b81)

# failing
Running Sphinx v4.1.0
SciPy (VERSION 1.8.0.dev0+1420.0a95709)
```

### PR DESCRIPTION
**Pull request by tupui**
Closes #14396

This would mitigate the regression introduced by this new version by not allowing it...

[skip azp] [skip actions]

### CODE REVIEW

**Comment by rgommers** [comment]
Is the fix already merged? If not, Sphinx `4.1.1` will break things again if you use `!= 4.1.0`

**Comment by tupui** [comment]
> Is the fix already merged? If not, Sphinx `4.1.1` will break things again if you use `!= 4.1.0`

Not yet, it's indeed a wishful thinking. The PR to fix the issue is https://github.com/sphinx-doc/sphinx/pull/9440. Shall we instead just pin to 4.0.3 in the meantime?

**Comment by rgommers** [comment]
> Shall we instead just pin to 4.0.3 in the meantime?

I'd use `<4.1.0`

**Review by rgommers — APPROVED** [review]
Thanks @tupui!

**Pull request merged**
