### PR TITLE
BLD: update pyproject.toml - add macOS M1, drop py36

### PR DESCRIPTION
**Pull request by rgommers**
Changes taken over from gh-14145 and from https://github.com/scipy/oldest-supported-numpy/pull/20

### CODE REVIEW

**Comment by rgommers** [comment]
This should be good to go now. The only CI failures are the known pre-release ones.

**Review by tylerjereddy — APPROVED** [review]
Thanks Ralf I'll put it this in.

I'm guessing the maintenance branch has the changes it needs, but if the macOS M1 stuff needs to be backported for eventual support let me know I guess.

**Comment by rgommers** [comment]
> I'm guessing the maintenance branch has the changes it needs, but if the macOS M1 stuff needs to be backported for eventual support let me know I guess.

I'll keep an eye on it. We still have serious problems on M1, now that we'll get NumPy wheels with 1.21.0 we should prioritize looking into those. E.g., https://github.com/scipy/scipy/issues/13409, https://github.com/scipy/scipy/issues/13364. It looks like it's not too much work, some people had success building it. Just a pain to work on without the hardware.

**Comment by AngelikB** [comment]
Hello everyone!

I don't use this platform very often and I'm trying to find a solution for a few errors if someone has any ideas, that would be super nice.
It seems spicy can't be downloaded here, I tried pip instal spicy and brew install spicy but none of these work.
(I'm on a M1 2020)
Have a good one!


   [Collecting scipy==1.6.1
  Using cached scipy-1.6.1.tar.gz (27.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      setup.py:463: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/2s/9j3z_ls129b3cpsx824sc01r0000gp/T/pip-modern-metadata-354tp06i'), proceeding with generating Cython sources and expanding templates
        ' '.join(sys.argv[1:])))
      Error: 'None' must be installed before running the build.
      
     
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.]

**Comment by ilayn** [comment]
Hi @AngelikB Please open a fresh issue by clicking the New Issue button and follow the instructions to create the most informative explanation of the issue so that we can help you

**Comment by AngelikB** [comment]
Okay, thank you @ilayn !

**Pull request merged**
