### PR TITLE
MAINT: use f-strings

### PR DESCRIPTION
**Pull request by ikamensh**
#### What does this implement/fix?
As scipy no longer supports python 3.5, it's safe to migrate to f-strings. This should improve readability and be marginally faster.

#### Additional information

The change was derived by running `flynt scipy -ll 79 `. 

Stats:
```
Files modified:                            183
Character count reduction:                 4424 (0.04%)

Old style (`%`) expressions attempted:     636/1019 (62.4%)
`.format(...)` calls attempted:            401/412 (97.3%)
F-string expressions created:              678
```
It also reduces the line count by 33.

### CODE REVIEW

**Comment by ikamensh** [comment]
Failures:
Flake8:
- line limit for lines that were already over the limit and were made shorter with this  PR
- space after comma - same line, but not the change itself (fixed in new commit)

ARM - Test Group 2:
- is also failing for other PRs, seems unrelated

**Review by tylerjereddy — COMMENTED** [review]
There is sometimes a bit of a resistance to mass-reformatting in the codebase; I guess we'll see what other devs think. I'm kind of neutral on it--I can see both sides.

I believe sometimes the argument is made that changes like this are best included "when you happen to see them" while focused on another fix.

**Comment by andyfaff** [comment]
Personally I much prefer f-strings. However, I'd come down -1 for an en-masse change like this.

- there are hundreds of files changed, with 700 odd lines to be checked during the PR. This makes it more likely that something might be missed in code review.
- how reliable is the flynt tool? Are there edge cases for which it can miss?
- changing all these lines raises the probability that a lot of other PRs then have merge conflicts, which causes more work for the author to fix.

If there is a general move to f-strings it'd probably be best to tackle individual modules in  their own PR.

I wonder if the lint diff tool can look for instances where f-strings could be used in new PRs, and one can slowly ratchet up to full use of f-strings in the codebase over time.

**Comment by andyfaff** [comment]
Also, I don't think it's a good idea to make such changes to vendored code, as that makes it harder to pull in upstream changes.

**Comment by ilayn** [comment]
Same opinion here that I think f-strings are definitely needed but actually that we need to go one by one. Especially when there are typos etc. we can also fix them, and in the mean time get rid of `!r`s and `!s`s.

**Comment by ikamensh** [comment]
IMO the advantage is that developers concentrate in future work on their features, and don't mix the style changes into PR. It's also quite some work when taken in bulk.

What part of code is Vendored? does this mean it's copy-pasted from another source and this repo is not it's home?

Quite a few people use `flynt` but it's still not a reason to say it's error-free. But probably more reliable than a human before review, statistically.

**Comment by rlucas7** [comment]
>> On Oct 22, 2020, at 3:48 AM, Andrew Nelson <notifications@github.com> wrote:
> ﻿
> Personally I much prefer f-strings. However, I'd come down -1 for an en-masse change like this.
> 
> there are hundreds of files changed, with 700 odd lines to be checked during the PR. This makes it more likely that something might be missed in code review.
> how reliable is the flynt tool? Are there edge cases for which it can miss?
> changing all these lines raises the probability that a lot of other PRs then have merge conflicts, which causes more work for the author to fix.
This is a big one for me. Lots of new contributors have trouble with git rebase and this increases the likelihood they’d need to do exactly that b/c of upstream merge conflicts.
> If there is a general move to f-strings it'd probably be best to tackle individual modules in their own PR.
> 
> I wonder if the lint diff tool can look for instances where f-strings could be used in new PRs, and one can slowly ratchet up to full use of f-strings in the codebase over time.
> 
Does the flynt tool support this use case?

 I’d be +1 for adding that functionality into the lint diff tool unless there are downsides to that approach that I’m not seeing. 

For context for Ilya here is the one we use;

https://github.com/scipy/scipy/blob/master/tools/lint_diff.py

Could the flynt tool be stitched into there?

**Comment by rgommers** [comment]
From http://scipy.github.io/devdocs/hacking.html#maintaining-existing-code:

_Pull requests that only change code style, e.g. fixing some PEP8 issues in a file, are discouraged. Such PRs are often not worth cluttering the git annotate history, and take reviewer time that may be better spent in other ways. Code style cleanups of code that is touched as part of a functional change are fine however._

f-strings are, just like PEP8 changes, a purely cosmetic change for code that already works. Maybe we should add the above note to the PR template in bold letters.

**Comment by rgommers** [comment]
We keep on discussing this over and over, the outcome is always the same. We really do not want to receive PRs like this.

**Comment by ikamensh** [comment]
😰💔 feel free to close it

**Comment by rgommers** [comment]
@ikamensh thanks. Sorry if that sounded a bit harsh, wasn't meant to be. I appreciate the effort you took to open a PR.

**Pull request closed without merging**
