### PR TITLE
MAINT: approx_derivative with FP32 closes #12991

### LINKED ISSUE #12991: least_squares broken with float32
`optimize.least_squares` doesn't work reliably with float32. Changing the dtype to float64 (or removing it) yields the expected result.

#### Reproducing code example:
```
import matplotlib.pyplot as plt
import numpy as np
from scipy import optimize

x = np.linspace(0, 1, 100).astype("float32")
y = np.random.random(100).astype("float32")


def func(p, x):
    return p[0] + p[1] * x


def err(p, x, y):
    return func(p, x) - y


res = optimize.least_squares(err, [-1.0, -1.0], args=(x, y))
plt.plot(x, y, "x")
plt.plot(x, func(res.x, x))
plt.show()
```

#### Error message:
No error is raised, just the fit does not converge.

#### Scipy/Numpy/Python version information:

```
1.5.3 1.18.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by andyfaff**
#12991 reports that `optimize.least_squares` stops prematurely when the problem is specified with `np.float32`. This is because `approx_derivative` only chooses step sizes suitable for working with `np.float64`. This PR changes `approx_derivative` to choose a step size that is determined by `np.finfo(fun(x0).dtype).eps`.

I tried to add some tests, but they are basic, and might need more improving.

closes #12991

### CODE REVIEW

**Comment by ev-br** [comment]
Looks reasonable, so let's get this in to keep the ball rolling.

ISTM a big fat warning is warranted somewhere to warn against using finite differencing in float32 , but that cam wait for a separate PR.

**Comment by ev-br** [comment]
Thanks @andyfaff , merged. 

I took a liberty to squash-merge it since the resulting commit is small enough and self-contained.
Hope this unblocks some of the work you are doing.

**Comment by andyfaff** [comment]
@ev-br, squashing was fine.
The next PR's I'd like looked at at are:  #12889, #13009, #11263 (this is in the order of pain they're causing users)

**Comment by ev-br** [comment]
No ETA from me on these ones, sorry.

**Pull request merged**
