### PR TITLE
CI: MAINT: Skip a ckdtree test on pypy

### PR DESCRIPTION
**Pull request by ilayn**
As per discussion on #9455, one of the ckdtree tests are skipped. The PR became noisy after auto-removal of the spurious spaces. The change is around line no.1127

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
+1 for merge assuming the CIs are happy(ier)

**Comment by sturlamolden** [comment]
We need to know why ```test_arnoldi``` fails on PyPy. We cannot just remove it because it fails.

**Comment by ilayn** [comment]
It is failing on most PRs so that can still be investigated independently. Also I don't have access to PyPy environment.

**Comment by ilayn** [comment]
CIs are happy. Fingers crossed

**Pull request merged**
