### PR TITLE
BUG: Handling negative values in `scipy.special.spherical_jn`

### LINKED ISSUE #14582: Negative arguments for scipy.special.spherical_jn leads to nans
`scipy.special.spherical_jn` seems to generate `nan`s for negative input arguments, which does not seem to be prohibited and the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.spherical_jn.html) does not seem to warn against. For example, the following code

```
import numpy as np
from scipy.special import spherical_jn

n = 5
zs = np.linspace(-5, 5, 10)
print(spherical_jn(n, zs))
```
yields an output of 
`[           nan            nan            nan            nan      nan 5.03098996e-06 1.11092345e-03 1.17516973e-02 4.66525179e-02 1.06811161e-01]`

Based on the reflection formula from [DLMF](http://dlmf.nist.gov/10.47.E14), I used the following fix for my purposes

```
import numpy as np
from scipy.special import spherical_jn

def spherical_bessel(n, z):
  return np.where(not isinstance(z, complex) and z<0, (-1)**n*spherical_jn(n, -z), spherical_jn(n, z))

zs = np.linspace(-5, 5, 10)
print(spherical_bessel(n, zs))
```
which gave the result
`[-1.06811161e-01 -4.66525179e-02 -1.17516973e-02 -1.11092345e-03
 -5.03098996e-06  5.03098996e-06  1.11092345e-03  1.17516973e-02
  4.66525179e-02  1.06811161e-01]`

I suspect that a similar, but more general fix can be used for a PR if this is deemed a legitimate issue. 

(I'm using Python 3.7.7, numpy-1.21.1 and scipy-1.7.1)

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Reference issue

Closes https://github.com/scipy/scipy/issues/14582

#### What does this implement/fix?

The negative valued inputs to `scipy.special.spherical_in`, `spherical_jn`, `spherical_kn` are handled by using reflection formulae given [here](https://dlmf.nist.gov/10.47#E14).

#### Additional information

cc @cw-tan

### CODE REVIEW

**Comment by czgdp1807** [comment]
I suspect, the same problem might appear in `spherical_in`, `spherical_yn`, `spherical_hn`, etc.

**Comment by czgdp1807** [comment]
On my system, no test related to this PR fail. Only two fail but they are failing on `master` as well on my system.

**Comment by person142** [comment]
@czgdp1807 sorry for the lack of review here. I am out of time for review this weekend; ping me next weekend and I will try to get to this.

**Comment by czgdp1807** [comment]
Hi. Dropping in. I am a bit focussed on other project right now. I will get back to this issue in a couple of weeks.

**Comment by ptbrown1729** [comment]
@czgdp1807 
I came across this and [14582](https://github.com/scipy/scipy/issues/14582) because I was considering adding `spherical_jn` to CuPy, and I discovered my implementation disagreed with Scipy for all negative arguments and odd order spherical Bessel functions. Anything I can do to help resolve this?

**Comment by steppi** [comment]
Hey @ptbrown1729, good timing. @izaid and I are on a quest to clean up `scipy.special` and replace our implementations with NVCC compliant C++ reference implementations which could in principle be used by other array libraries like `CuPy` `Jax` and `PyTorch`, as part of a push to create a special function [array API extension](https://data-apis.org/array-api/latest/extensions/index.html). See the RFC gh-19404 and gh-19435 with an implementation of the `lambertw` function. Also feel free to chime in on gh-19404.

I think the first order of business for `spherical_jn` is for myself and/or @izaid to give this PR a proper review so @czgdp1807 can get credit for his work. If you'd like to submit a PR to SciPy rewriting `spherical_jn` in C++ along the lines of gh-19435, since you plan to write one for CuPy anyway, that would be awesome and we'd try to give it a prompt review.

**Comment by ptbrown1729** [comment]
@steppi thanks for the response --- that sounds like exciting work. I will take a look and see if I think there is something I can contribute

**Comment by mdhaber** [comment]
@czgdp1807 Can you allow edits from maintainers? I went ahead and merged main, re-implementing the reflection formalas (because the Cython file is gone) but keeping the tests, so I'd like to push that here for you so we can get this in.

**Comment by mdhaber** [comment]
Superseeded by gh-21629.

**Pull request closed without merging**
