### PR TITLE
FIX: Incorect boschloo pvalue

### LINKED ISSUE #15345: BUG: boschloo_exact gives pvalue > 1 (and sometimes nan)
### Describe your issue.

Found a bug in `boschloo_exact` (EXAMPLE 1): Sometimes, it yields pvalue > 1! The pvalue should obviously never be greater than 1.

In addition, I think `boschloo_exact` should never return `nan`, like `fisher_exact` (EXAMPLE 2). The documentation says that `statistic` is " the p-value from Fisher’s exact test", thus it should be 1. Imo, `pvalue` should also be 1 rather than nan.

Honestly, I don't understand what the `statistic` means, because it's not the same value as Fisher's test.

I'm tagging @V0lantis because he implemented the function (#13896).

### Reproducing Code Example

```python
from scipy.stats import fisher_exact, boschloo_exact



# EXAMPLE 1: pvalues > 0
boschloo_exact([[0,0],[7,4]])  # BoschlooExactResult(statistic=1.0, pvalue=2.0)

boschloo_exact([[1, 1], [13, 12]])  # BoschlooExactResult(statistic=0.7407407407407399, pvalue=1.2772982529540837)



# EXAMPLE 2: pvalues are nan
TABLE = [[0,5],[0,8]]

odds_ratio, pvalue = fisher_exact(TABLE)  # odds_ratio=nan pvalue=1.0

boschloo_exact(TABLE)  # BoschlooExactResult(statistic=nan, pvalue=nan)
```

### Error message

```shell
(no error message)
```

### SciPy/NumPy/Python version information

1.7.3 1.22.0 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by V0lantis**
#### Reference issue
should closes gh-15345

#### What does this implement/fix?

boschloo_exact had incorect pvalues (See #15345).
Clip the result of the two-sided case between 0 and 1.

It may happen in some edges cases that both pvalues
from `less` and `greater` alternatives have a value > .5 leading to a `two-sided` `pvalue` > 1

### CODE REVIEW

**Comment by mdhaber** [comment]
Thanks for submitting this. I worked on `fisher_exact` recently, so this is fresh in my mind: are there different conventions for calculating a two-sided p-value for this test? If so, what is done here should probably be documented. I can merge this as-is if you want that in a second PR, but it is pretty closely related. 

(For `fisher_exact`, the two-sided p-value is the probability of observing, under the null hypothesis, a table with probability mass less than or equal to the probability mass of the observed table. Since the null distribution of the test statistic is not symmetric, this is not the same as twice the smaller of the one-sided p-values.)

**Comment by mdhaber** [comment]
Please consider V0lantis/scipy#7 before this is merged.

**Comment by V0lantis** [comment]
> Please consider [V0lantis#7](https://github.com/V0lantis/scipy/pull/7) before this is merged.

My apologies @mdhaber for this late answer. I used the definition defined by @jb-leger in this [comment](https://github.com/scipy/scipy/pull/13899#issuecomment-829993123). Should I add more documentation to explain how we compute the two-sided test?

Please know that before, I was using the fisher way of computing the two-sided test and I had slight differences with the expected and computed result from the R algorithm

**Comment by mdhaber** [comment]
@V0lantis no need to add more documentation yourself. Please see the PR V0lantis/scipy#7 I submitted against your fork. If you merge it, it will show up here.

**Comment by V0lantis** [comment]
> @V0lantis no need to add more documentation yourself. Please see the PR [V0lantis#7](https://github.com/V0lantis/scipy/pull/7) I submitted against your fork. If you merge it, it will show up here.

Thank you so much @mdhaber, very nice help !

**Review by tupui — APPROVED** [review]
LGTM, thanks @V0lantis. I will let you merge @mdhaber

**Pull request merged**
