### PR TITLE
DOC, API: scipy.stats.reciprocal is "log-uniform"

### LINKED ISSUE #10745: Add loguniform distribution
**Is your feature request related to a problem? Please describe.**

When randomly sampling a variable over several orders of magnitude, it is often useful to sample uniformly on a log scale. This could be done with a `loguniform` distribution. 

For instance, 
 - this would be very useful when randomly sampling hyper-parameters in machine learning (https://github.com/scikit-learn/scikit-learn/issues/9919)
 - in science fields where variables can vary by several orders of magnitude (astrophysics, plasma physics to take a few), it is common to compute values on a `logspace` grid. `loguniform` would then be the equivalent in the randomized case.  

The [SO issue about it](https://stackoverflow.com/questions/43977717/how-do-i-generate-log-uniform-distribution-in-python) receives around 3k visits/ year.

**Describe the solution you'd like**

The solution is basically,
```
def loguniform(low=0, high=1, size=None):
    return np.exp(np.random.uniform(low, high, size))
```
but following the `scipy.stats` API. A partial implementation can be found in https://github.com/scikit-learn/scikit-learn/pull/11232 

**Describe alternatives you've considered**

Manually computing this distribution each time (or vendor it in  projects that need it) is also not ideal. 

There are already a number of distribution with an applied log function: `loggamma`, `loglaplace`, `lognorm`.

If an implementation for `scipy.stats.loguniform` was proposed, would it be accepted?

### PR DESCRIPTION
**Pull request by stsievert**
#### What does this implement/fix?
This PR improves the documentation on the reciprocal random variable. It makes it more clear that it's "log-uniform". It also adds the random variable `loguniform` as an alias to `reciprocal`.

#### Reference issues/PRs
* https://github.com/scikit-learn/scikit-learn/issues/9919, https://github.com/scikit-learn/scikit-learn/pull/11232: scikit-learn issue/PR (respectively) focused on implementing a log-uniform RV.
* this closes https://github.com/scipy/scipy/issues/10745, an issue asking about a loguniform RV (from the PR above)

[1]:https://stackoverflow.com/questions/43977717/how-do-i-generate-log-uniform-distribution-in-python

### CODE REVIEW

**Comment by rth** [comment]
Thanks for this PR @stsievert !

Doctests fail in Travis on Python 3.6 , do they pass for you locally?

**Comment by ev-br** [comment]
Doctest failure is real if annoying: you added a new distribution (only an alias, but still), need to bump the number of them in the tutorial:

```
../doc/source/tutorial/stats.rst
Failed example:
    print('number of continuous distributions: %d' % len(dist_continu))
Expected:
    number of continuous distributions: 98
Got:
    number of continuous distributions: 99
```

**Comment by rth** [comment]
Thanks @ev-br !

I also meant the syntax error in Travis CI,
```
File "build/testenv/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py", line ?, in loguniform
Failed example:
    a, b = 
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.6.7/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest loguniform[3]>", line 1
        a, b =
              ^
    SyntaxError: invalid syntax
```

**Comment by ev-br** [comment]
Uhm, yeah.
Try adding an entry for the new alias to this list: https://github.com/scipy/scipy/blob/master/scipy/stats/_distr_params.py

**Comment by rth** [comment]
I think the CI is green. The Circle CI report here shows an error with "There was an infrastructure problem while running yo..", but actually clicking on the link shows that the build passed.

**Comment by WarrenWeckesser** [comment]
+1 for improved documentation.

-1 for adding the new name to the namespace.  I'd rather we didn't expand the API that way.  Will the improved documentation be a good enough solution to the problem that is being solved by this PR?

**Comment by rth** [comment]
> -1 for adding the new name to the namespace. I'd rather we didn't expand the API that way. Will the improved documentation be a good enough solution to the problem that is being solved by this PR?

I understand that `reciprocal` is the name for this distribution, but IMO it's a really bad name. Most scipy users are scientists and engineers not statisticians. 

Reading code that samples from `reciprocal` distribution makes no sense to me and I presume to most readers. `loguniform` is much more explicit. The naming is so confusing that 4 reviewers were seriously considering accepting a re-implementation it in https://github.com/scikit-learn/scikit-learn/pull/11232 not realizing it existed in scipy. FWIW one scipy reviwer was initially also OK with adding a new implementation for it in the parent issue. Improving the docs would help some, but it will not help much with the confusing naming. 

@WarrenWeckesser Any chance code readability and usability could outweigh possible maintenance concerns here?

**Comment by person142** [comment]
I don't have any insights into the merits of this particular situation, but I will note that in the past in similar situations we've also completely removed the alias from the documentation. That way we maintain back compatibility while making it clear to users which function they should use going forward.

See e.g. https://github.com/scipy/scipy/pull/6645 for an example of this.

**Comment by rth** [comment]
Renaming with a deprecation warning `stats.reciprocal` to `stats.loguniform` is indeed another option, while keeping backward compatibility for some time.

Searching on Github there are,
 - [647 mentions of `stats.reciprocal`](https://github.com/search?l=Python&q=%22stats.reciprocal%22&type=Code)

and for comparison,
 - [19,067 mentions of `stats.uniform`](https://github.com/search?q=%22stats.uniform%22&type=Code) 
 - [20,364 mentions of `stats.gamma`](https://github.com/search?l=Python&q=%22stats.gamma%22&type=Code)
 - [8,476 mentions of `stats.lognorm`](https://github.com/search?l=Python&q=%22stats.lognorm%22&type=Code)

so it's little used. At the same time `loguniform` is a very useful distribution for sampling anything on a log grid. I certainly I wish I knew about its existence during my PhD.

**Comment by rgommers** [comment]
> **Edit**: to clarify, in this situation, the "alias" would be `reciprocal`.

This seems like a good way to go. @stsievert could you do this? Then we'll get this in for 1.4.0

**Comment by stsievert** [comment]
I had to issue a `DeprecationWarning` in `reciprocal.__init__`. I'd appreciate guidance: this is my first experience with the scipy.stats documentation stack.

I tried to remove `reciprocal` from the documentation AND keep `'reciprocal'` in `scipy.stats.__all__`. That failed; I wound up with an error that prompted me to include deprecate `reciprocal`:

```
Non-deprecated objects in __all__: 226
Objects in refguide: 227

Deprecated objects in refguide::

    frechet_l
    frechet_r
    itemfreq

ERROR: objects in scipy.stats.__all__ but not in refguide::

    reciprocal

This issue can be fixed by adding these objects to
the function listing in __init__.py for this module

The command "if [ "${REFGUIDE_CHECK}" == "1" ]; then python runtests.py -g --refguide-check; fi" exited with 1.
```

I believe deprecating this will clear this issue: https://github.com/scipy/scipy/blob/91f43942cfcfb63c4b2ca58a55562295a7b00cde/tools/refguide_check.py#L226

**Comment by stsievert** [comment]
I've resolved the issue now. I think I'll have a green check mark. Here's what I've implemented:

* `reciprocal` docstring: stripped from the documentation
* `reciprocal` implementation: untouched.
* `loguniform` docstring: included in the documentation
* `loguniform` implementation: mapped to the `reciprocal` implementation
* Better docstring for `loguniform` and `reciprocal` (includes a log-scaled histogram).

**Comment by stsievert** [comment]
Thanks for including the documentation build on the CI! That's been useful for debugging. I've been trying to make the documentation page appear as I expect.

I've been debugging the `loguniform` docstring. I can't get the matplotlib figure to show up, despite following other examples. Can I have some help with this?

Here's the doc build for 
aeaa300: https://15878-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.stats.loguniform.html

**Comment by rgommers** [comment]
There is one figure on that page. I assume you're talking about a second one, for the first `plt.show()`? It looks to me like your `Examples` heading is in the wrong place, perhaps moving it helps.

**Comment by stsievert** [comment]
This PR LGTM. It should have a green check mark for deb3219  (previous commits had unrelated errors; see details below).

Here's a link to the docs under 7fe328a  for loguniform: https://15895-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.stats.loguniform.html

Here's the message from pytest summary on the failed test on 7fe328a. All tests passed except a Travis CI test. The pytest summary from the failed test had to do with a worker crashing on `scipy/optimize/tests`:

<details>


```

=================================== FAILURES ===================================
_ build/testenv/lib/python3.6/site-packages/scipy/optimize/tests/test__shgo.py _

[gw2] linux -- Python 3.6.7 /home/travis/virtualenv/python3.6.7/bin/python

worker 'gw2' crashed while running 'build/testenv/lib/python3.6/site-packages/scipy/optimize/tests/test__shgo.py::TestShgoArguments::test_2_1_sobol_iter'
```

</details>

**Comment by rgommers** [comment]
LGTM now, merged. Thanks @stsievert!

**Comment by stsievert** [comment]
I've posted an answer to [the SO question][1] now that v1.4.0 has been released. Let me know what edits you have.

[1]:https://stackoverflow.com/a/59367252/1141256

**Comment by guillaume-chevalier** [comment]
To me, it doesn't look like a LogUniform distribution. I tried to debug this several months ago, and the reciprocal chart didn't align with the LogUniform function that I tried to code. Other people seems to share the same view as mine on the [SO loguniform thread](https://stackoverflow.com/questions/43977717/how-do-i-generate-log-uniform-distribution-in-python).

**Comment by WarrenWeckesser** [comment]
@guillaume-chevalier, in that SO thread, joaoFaria's answer is correct.  Could you be more specific about what you did and explain what you mean when you say "the reciprocal chart didn't align with the LogUniform function that I tried to code"?

Here's a simple demonstration that show pretty clearly that the distribution is log-uniform (`hist` is from matplotlib):

```
In [5]: from scipy.stats import reciprocal

In [6]: x = reciprocal.rvs(1, np.e, size=100000)

In [7]: y = np.log(x)

In [8]: hist(y, bins=25)
```
Figure_1

**Comment by guillaume-chevalier** [comment]
@WarrenWeckesser I still support that to me, it doesn't look like a LogUniform distribution (especially in the context of having learning rates for artificial neural networks). The tests I've performed a few months ago can be reproduced here: https://github.com/Neuraxio/Neuraxle/issues/429

This leads me to believe that there are two conflicting definitions of the LogUniform, and that the one used in machine learning is the definition I advance as described in my issue. Your proof seems mathematically right, and mine as well, but are different proofs to proove the different distribution are good. 

It feels that perhaps in one case the CDF is loguniform and as if in the other case the PDF is loguinform, or that the transformation is in the other direction, but I'm not sure. Well my code speaks more than I could try to speak. Or maybe it is that in your `In [7]` you'd need to do `y = np.exp(x)` instead of `y = np.log(x)` to find the flat distribution anew? Not sure again. But I'm looking for the LogUniform that is good for machine learning learning rates whereas this hyperparameter needs to be adjusted relatively multiplicatively (in a logspace or expspace) rather than in the regular uniform space. Same for LogNormal learning rates.

**Comment by rkern** [comment]
I'm looking at your links, but I don't see any tests of the scipy `reciprocal/loguniform` distribution. I just see you plot the results for `hyperopt`. FWIW, if I do something similar and draw `x = stats.reciprocal.rvs(a=low, b=1/low, size=1000)` and plot histograms of `x` and `1/x`, they look like they are drawing from the same distribution.

Please note that there is a difference in the _parameterization_ of the `reciprocal` implementation and `hyperopt`'s `LogUniform`, but they are both implementing the same distribution.

**Comment by WarrenWeckesser** [comment]
@guillaume-chevalier, the different parameterizations of the hyperopt and SciPy distrbributions is likely the cause of the confusion.

Take a look at the [definition of hyperopt's loguniform distribution](https://github.com/hyperopt/hyperopt/blob/0f383f842f27b6a494212ee7174ef7ee7fa54ae0/hyperopt/rdists.py#L13).  The class docstring says this is "Stats for Y = e^X where X ~ U(low, high)."  That is, for given `low` and `high`, the log of the hyperopt distribution is uniform on `[low, high]`.  The random samples drawn from this distribution will be between `exp(low)` and `exp(high)`.

For the shape parameters `a` and `b`, SciPy's distribution is "Y = e^X where X ~ U(log(a), log(b))."  Samples drawn from this distribution will be between `a` and `b`.

To translate between the two parameterizations, use

    a = exp(low)
    b = exp(high)

**Pull request merged**
