### PR TITLE
ENH: sparse.linalg: Normalize type descriptions

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

Use clearer and consistent type descriptions.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Just to confirm--all of the removed `matrix` entries are not actually referring to support for the separate `np.matrix` object?

I know usage of `np.matrix` is discouraged, but just wondering if the use of `matrix` was referring to that type even though it is not supported, or is the point that it is supported but you want to discourage the use here as well?

**Comment by zhaog6** [comment]
> Just to confirm--all of the removed `matrix` entries are not actually referring to support for the separate `np.matrix` object? 
>
> I know usage of `np.matrix` is discouraged, but just wondering if the use of `matrix` was referring to that type even though it is not supported, or is the point that it is supported but you want to discourage the use here as well?

`matrix` (`numpy.matrix`) is effectively deprecated and I don't want users to use it here. With dense matrix and vector, just use `ndarray` (`numpy.array`).

**Comment by zhaog6** [comment]
Dear Ralf @rgommers , Could you review this PR for me? the PR just clears some the fuzzy and deprecated type in the comments. The other PR https://github.com/scipy/scipy/pull/14160 submitted before has been modified and corrected, I would also like to you to review it again. Thank you.

**Comment by zhaog6** [comment]
@tylerjereddy I would like to ask how to remind appointed expert to review the PR, there seems to be no one to review it.

**Review by ilayn — APPROVED** [review]
In the `{array, matrix}` ones, what is meant is the np.matrix but I think we would be better off without it anyways. Hence looks good to me.

**Comment by zhaog6** [comment]
Thanks for your review.

**Comment by ilayn** [comment]
This is pretty safe to click the button and revert just in case so in it goes. Thanks @zhaog6 !

**Comment by rgommers** [comment]
Nice, thanks @zhaog6 & reviewers

**Pull request merged**
