### PR TITLE
This adds root finding to pchip as this is possible to do optimal because pchip is a monotonic interpolation.

### PR DESCRIPTION
**Pull request by bmcage**
Alternative would be fsolve and friends, but those would not use the known structure of pchip.

A typical use for pchip is an interpolation that can be inverted.  This adds a root finding to pchip that uses the pchip form to invert fast.

I am not sure this is the best way. It might be better to use phcip to obtain yi=f(xi) and yi' = f'(xi), then create the cubic monotonic interpolation through yi with derivatives yi' as self.pchipinv. This should be the correct f^-1. 
Then when asking roots, one can use this self.pchipinv. 

The algorithm proposed here works differently: search the cubic for the y value given, calculate the 3 cubic roots. As it is a monotonic function only 1 of the roots will be in the correct interval.

Some problems:
1. computing cubic roots gives imaginary parts which need to be discarded.
   See the np.allclose(ires, 0., atol=1e-10) to discard this. -10 is hard coded
2. return value can be numerically close to the bounding edges.
   See the np.allclose(x1-rres, 0., atol=1e-10) to recognize this. -10 is hard coded
3. Use of newaxis to dump the results: x[c] = ress[:, np.newaxis] 
    I believe this will be correct for the use cases possible

### CODE REVIEW

**Comment by ev-br** [comment]
OK, I looked at this PR again, in gh-16147. Implementation details have changed a bit since this was first submitted, so here's a brief summary.

Given a piecewise polynomial, `f(x)`, represented as  a `PPoly` object, `PPoly.solve(y)` returns solutions, `x`, of `f(x) = y`. Since `pchip` (a `PPoly` subclass) constructs a locally monotonic polynomial, the idea is that it can use a more efficient implementation which takes the monotonicity into account. 

The currently missing bit is that `PPoly.solve` only accepts a single float number, and does not accept arrays : The idea is that given the array of `y` values, `.solve(y)` produces an array of solutions, so that
`p = PPoly(...); p.solve(y)` should be equivalent to `[p.solve(yval) for yval in y]` etc.

The discussion in https://github.com/scipy/scipy/pull/4356#issuecomment-185340184 claims that vectorizing `.solve` is an easy-fix enhancement, but I now don't think it is.

Here's a problematic thing. Consider

```
In [2]: from scipy.interpolate import pchip

In [3]: xi = [1., 2., 3., 4.]
   ...: yi = [-1., 2, -1, 1]
   ...: p = pchip(xi, yi)

In [4]: p.solve(0)
Out[4]: array([1.18350342, 2.61303686, 3.73205081])

In [5]: p.solve(2)
Out[5]: array([2.        , 4.19582335])
```

Note that the number of solutions is different for different values of `y`. So, what would be the output of `p.solve([0, 2])`?
It cannot be a numpy array with `dtype=float` since numpy does not have ragged arrays. 

So, possible options are
1. one can pad the shorter arrays with nans:

```
array([[1.18350342, 2.61303686, 3.73205081],
       [2., 4.19582335, nan]])
```

2. always return an object array of arrays, 
```
array(array([1.18350342, 2.61303686, 3.73205081]),
      array([2., 4.19582335]),
      dtype=object)

3. return an array of floats when possible, an object array otherwise
```

Option 1 feels ugly. 
Option 3 is certainly a bad form to change the array dtype depending on input values.
Option 2 is at least consistent, but these sorts of arrays are not very useful I'd guess.

All in all, I fail to see an advantage over just manually looping over the input array in user code: `[p.solve(_) for _ in y]` --- then each element of the list is then a float numpy array and the rest is up to a user who is better equipped to handle it then a library.

@bmcage  would appreciate your thoughts  (I realize it's been a while)

I'll also ping @AtsushiSakai and @mdhaber, maybe y'all have better ideas?

**Comment by mdhaber** [comment]
Is there a way to vectorize it efficiently within the function, or would it just be a loop internally?

**Comment by ev-br** [comment]
> Output convention side, is there a way to vectorize the calculation efficiently within the solve method of PPoly, or would it just be a loop anyway?

It's a loop this way or another. In the solve method it's likely this one: https://github.com/scipy/scipy/blob/main/scipy/interpolate/_interpolate.py#L1268


> What does the solve method return currently when there is no solution?

Following up the example above,

```
In [3]: p.solve(8)
Out[3]: array([4.91391421])

In [4]: p.solve(8, extrapolate=False)
Out[4]: array([], dtype=float64)
```

> The comment ENH: add PPoly.solve(y) for solving p(x) == y #4356 (comment) suggests that solve for array y would be helpful to complete the present PR. Without digging, i can't see why that is needed, but if it is needed, does it need to be a feature of the public interface of solve, or can you just loop as needed in this PR?

The intended usage AFAIU is exemplified by the tests in this PR, which are somewhat cleaned up and expanded in gh-16147.

**Comment by AtsushiSakai** [comment]
Personally, I like option 1 style output, because dtype stability is more important than nan filtering. I have no better ideas for ragged array representation.

**Comment by ev-br** [comment]
OK, so per review comments object arrays are not wanted; on the table there are only option 1 --- pad shorter arrays with nans --- and the unnumbered option of not accepting arrays at all and asking a user to do `[p.solve(_) for _ in y]` themselves, which is the status quo. I actually prefer the status quo, as accepting arrays here
- does not seem to bring drastic benefits as opposed to user looping
- does complicate the user API considerably

On balance, I suggest we close this PR and gh-16147. I'm going to hit the red button in a couple of weeks, please comment if you prefer a different course of action.

**Comment by ev-br** [comment]
OK, no further comments, so let's close this and gh-16147, for now at least. To summarize, I don't see a way this is can be implemented so that it both useful in special cases and is general enough.  If there is a suggestion, we certainly can and will reconsider. 

Thanks @bmcage and all reviewers!

**Pull request closed without merging**
