### PR TITLE
Remove wrappers for LAPACK deprecated routines

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
Closes https://github.com/scipy/scipy/issues/5266. This should be included in the next release. Except for `*ggsvd` and `*ggsvp`, all the routines removed were deprecated in favor of a routine that is already present in our wrappers.

### CODE REVIEW

**Comment by pv** [comment]
LGTM. For future -- I'd prefer committing autogenerated files in a separate commit. They should also be listed as binary in `.gitattributes`.

**Comment by insertinterestingnamehere** [comment]
@pv thanks for looking at it. I've restructured the commits as you suggested, marked the autogenerated wrappers as such in `.gitattributes` and reworded the comment in the release notes slightly.

**Comment by insertinterestingnamehere** [comment]
Quick update on this. There are also longstanding f2py wrappers for the deprecated and now removed `*gegv` routines. Given that LAPACK 3.6.0 has already been released, we really need to work out a deprecation and removal plan for those wrappers as well, though it's less clear what to do in that case. The only idea I've had thus far is to add in the needed fortran files so that those routines will still have f2py wrappers in the immediate future, and then wrap the f2py bindings inside another Python function so that they raise a deprecation warning whenever they are called. In another one or two releases we could remove them entirely. Thoughts?

**Comment by insertinterestingnamehere** [comment]
I'm not going to be able to work on this for the next few days. Feel free to merge this as it stands since the changes to the Cython wrappers are finished. If someone hasn't taken care of the f2py wrapper issues by the beginning of next week, I'll take a look at it again then and put the changes either in this PR if it's still open or in a separate one if it isn't.

**Comment by ev-br** [comment]
OK, the comments seem to be addressed, there are no further comments, so merging this. Thanks @insertinterestingnamehere

**Comment by insertinterestingnamehere** [comment]
@ev-br Thanks! https://github.com/scipy/scipy/issues/5266 should be reopened until we get the f2py deprecations taken care of in another PR.

**Pull request merged**
