### PR TITLE
REL: fix doc upload path, remove "not yet released" line for 1.7.0

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-14267

`[ci skip]`

### CODE REVIEW

**Comment by rgommers** [comment]
@tylerjereddy this PR is against the `1.7.x` branch. Do you want to take this along when forward-porting release notes, or should I open a PR to master for it?

**Comment by tylerjereddy** [comment]
I can forward port it next time; is there anything you need me to do short-term or did you already overwrite the uploaded docs for `1.7.0`?

**Comment by rgommers** [comment]
I uploaded new docs already, should be all fixed.

**Comment by rgommers** [comment]
Since this is already uploaded, let's put it in.

**Comment by tylerjereddy** [comment]
Thanks Ralf

**Pull request merged**
