### PR TITLE
TST/DOC: smoke docs: strict checks

### PR DESCRIPTION
**Pull request by ev-br**
Match https://github.com/numpy/numpy/pull/27272, which is a fix for https://github.com/numpy/numpy/issues/27263

The NumPy issue is that the smoke-docs checker relies on equality which is rather loosely defined in NumPy:

```
>>> np.float63(3) == 3
True
```

which leads to the checker allowing mismatched dtypes: e.g. a function returns an int but the example shows floats.

Thus add a flag to `scipy-doctest` checker (https://github.com/scipy/scipy_doctest/issues/172) and switch it on in SciPy, too. 
This might open a can of worms with us supporting NumPy 1.x and 2.x : the default integer has changed on Wndows, so it is technically possible that there are examples which fail on either 1.x or 2.x. If that happens to be the case, I'd just target NumPy 2.x and accept that 1.x on Windows fails `smoke-docs`. 

Whether we actually want stricter checking, I'm ambivalent. I had to check that the fallout is not huge, and once checked, it's easier to just fix the issues and forget. So possible outcomes for this PR could be
- land as is
- flip the `strict-check` flag back to False in `conftest.py` and accept changes to the docstrings
- just do not merge and keep both docstrings as they were and checking relying on lax equality.

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
This LGTM if CI is green! (I edited the top post slightly to avoid auto-closing the NumPy issue.)

>  possible outcomes for this PR could be
> - land as is
> - flip the strict-check flag back to False in conftest.py and accept changes to the docstrings
> - just do not merge and keep both docstrings as they were and checking relying on lax equality.

I propose we land as is (modulo green CI), but flip the flag to False if anybody complains about the job failing for NumPy<2.

**Review by lucascolley — COMMENTED** [review]
Just one failure left in CI

**Comment by tylerjereddy** [comment]
Diff looks nice to me too; focusing on NumPy 2 output makes sense I think

**Comment by lucascolley** [comment]
7th time lucky :) thanks!

**Pull request merged**
