### PR TITLE
MAINT: stats.johnsonsu: override _stats

### LINKED ISSUE #18071: BUG: rv_continuous.stats fails to converge when trying to estimate moment parameters for particular distributions
### Describe your issue.

When trying to get moments estimation (mean, variance, skewness, kurtosis) for Johnson SU distributions parametrized with specific location, scale, a and b values, the function fails to converge.
Tried to increase the limit from 50 to 100 as suggested from the error message, with no result. 
From a quick look at _distn_infrastructure.py, the culprit should be the part where the ppf is integrated, especially when it contains high steepness near the boundaries (singularities). It can be mitigated by changing the integration boundaries in _distn_infrastructure.py:2041 from (0, 1) to (0.00000001, 0.9999999). This however changes the integration result. 

### Reproducing Code Example

```python
from scipy.stats import johnsonsu

l= 0.02; s= 0.0001; a = -0.01; b = 1.1
mean, var, skew, kurt = johnsonsu.stats(a, b, loc=l, scale=s, moments='mvsk')
```

### Error message

```shell
IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
If increasing the limit yields no improvement it is advised to analyze
the integrand in order to determine the difficulties.  If the position of a
local difficulty can be determined (singularity, discontinuity) one will
probably gain from splitting up the interval and calling the integrator
on the subranges.  Perhaps a special-purpose integrator should be used.
return integrate.quad(self._mom_integ1, 0, 1, args=(m,)+args)[0]
```

### SciPy/NumPy/Python version information

1.10.1 1.22.3 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Closes gh-18071

#### What does this implement/fix?
gh-18071 reported a warning produced by `johnsonsu.stats`. This overrides `johnsonsu`'s `_stats` method using straightforward implementations of formulas for the moments. No attempt is made to ensure numerical stability for extreme parameter values, so the test only checks what this PR is intended to resolve: the warning is no longer produced, and the implementation is not incorrect. 

*The failure in `test_moments` (which has been xfailed) is due to inaccuracy when the second noncentral moment is computed using the generic `_munp`. The code below shows close agreement between this PR's implementation and mpmath numerical integration.*

<details>

```python3
import numpy as np
from scipy import stats
from numpy.testing import assert_allclose
from mpmath import mp
mp.dps = 100
def pdf(x, a, b):
    x, a, b = mp.mpf(x), mp.mpf(a), mp.mpf(b)
    x2 = x * x
    trm = mp.npdf(a + b * mp.log(x + np.sqrt(x2 + mp.one)))
    return b * mp.one / mp.sqrt(x2 + mp.one) * trm
x = 1.5
a, b = 2.554395574161155, 2.2482281679651965

def moment(order=1):
    return mp.quad(lambda x: x**order * pdf(x, a, b), (-mp.inf, mp.inf))

pdf1 = pdf(x, a, b)
pdf2 = stats.johnsonsu.pdf(x, a, b)
assert_allclose(float(pdf1), pdf2, rtol=1e-14)

mean1 = moment(order=1)
mean2 = stats.johnsonsu.stats(a, b, moments='m')
assert_allclose(float(mean1), mean2, rtol=1e-15)

var1 = moment(order=2) - mean1**2
var2 = stats.johnsonsu.stats(a, b, moments='v')
assert_allclose(float(var1), var2, rtol=1e-15)

skew1 = (moment(order=3) - 3*mean1*var1 - mean1**3)/var1**1.5
skew2 = stats.johnsonsu.stats(a, b, moments='s')
assert_allclose(float(skew1), skew2, rtol=1e-15)

kurtosis1 = (moment(order=4) - 4*mean1*moment(order=3) + 6*mean1**2*moment(order=2) - 3*mean1**4)/var1**2 - 3
kurtosis2 = stats.johnsonsu.stats(a, b, moments='k')
assert_allclose(float(kurtosis1), kurtosis2, rtol=1e-15)
```

</details>

#### Additional information
~~I would prefer not to add an entry to the tutorial, but I could cite the source of the formulas. I used [this](https://variation.com/wp-content/distribution_analyzer_help/hs126.htm) instead of Wikipedia because I didn't get a correct result when I tried implementing Wikipedia's formula for skewness.~~ Done.

I would recommend that future reports similar to gh-18071 be tracked in gh-17832. The warning emitted by `johnsonsu.stats` is not really a "bug"; it is just the generic implementation doing its job and warning the user when it's not sure about the accuracy. By this logic, this PR is an enhancement rather than maintenance, and perhaps it would be considered incomplete because it does not attempt to be robust. If that is the case, I am happy to close this PR.

### CODE REVIEW

**Review by dschmitz89 — APPROVED** [review]
Looks good to me and the source of the formulas can be a great resource for other distributions too. :)

**Comment by steppi** [comment]
> I would recommend that future reports similar to [gh-18071](https://github.com/scipy/scipy/issues/18071) be tracked in [gh-17832](https://github.com/scipy/scipy/issues/17832). The warning emitted by `johnsonsu.stats` is not really a "bug"; it is just the generic implementation doing its job and warning the user when it's not sure about the accuracy. By this logic, this PR is an enhancement rather than maintenance, and perhaps it would be considered incomplete because it does not attempt to be robust. If that is the case, I am happy to close this PR.

I think I'd be OK merging this and just making an additional issue/issues if there end up being numerical problems. I'll take a closer look in the next few days.

**Comment by tupui** [comment]
@steppi trusting your judgement here. Feel free to merge when you think it's ready 😃

**Comment by mdhaber** [comment]
Thanks @steppi. Note that the test failures are unrelated. One has already been resolved in main, and the other is tracked by gh-18108.

**Pull request merged**
