### PR TITLE
ENH: Bounds for the Powell minimization method

### PR DESCRIPTION
**Pull request by andyfaff**
This PR replaces #10648. The original PR wasn't done on a feature branch it was done on the master branch of @jtiosue fork, and had tens of commits. The original PR needed changes, in order to get the PR into 1.5.0 (@tylerjereddy) I decided to make them myself.
I therefore checked out the original fork, rebased it onto the current tip of scipy/master (which took a lot of interactive work), squashed the original PR commits down, and made it into a feature branch. I don't know how to push those changes back into the original PR without difficult rebasing efforts, so it just seemed easier to create a new PR.
The work done by @jtiosue is still acknowledged in the git commit history.

I've gone over the PR and I'm happy for it to be merged.

### CODE REVIEW

**Comment by andyfaff** [comment]
See original PR for comment history

**Comment by jtiosue** [comment]
@andyfaff Thanks a lot for pushing this forward! Sorry I should have read the Contributing guide more carefully before starting the original PR. I hope I didn't cause too much unnecessary work. But I think this bounded Powell variant is pretty cool, so I'm really excited for it to be in scipy!

**Comment by andyfaff** [comment]
It'd be nice to have this merged for the upcoming release. I'm happy with it, but I probably touched too much to merge myself.

**Comment by tylerjereddy** [comment]
@andyfaff Can you rebase to get rid of the Azure drive path failures fixed in `master`?

**Comment by andyfaff** [comment]
rebased

**Review by tylerjereddy — APPROVED** [review]
Ok, CI is green, no old tests were modified, and Matt was also broadly in favor of this idea in the original PR. That PR also had about 200 comments from review, so seems pretty thorough--not sure we'd get much better than that even if we delayed.

I looked over quickly and might personally split some of the unit tests into smaller pieces, but maybe that's personal preference.

Anyway, merging before branching, thanks @andyfaff,  @jtiosue and reviewers of this & previous PR

**Comment by tylerjereddy** [comment]
I've tentatively labelled this an enhancement PR--if you want a release note, maybe just suggest it in #12221

**Comment by mdhaber** [comment]
I think it deserves a simple one. I added:
```
- ``minimize``'s ``method= 'powell'`` now supports simple bound constraints
```

**Pull request merged**
