### PR TITLE
BUG: misspelled __dealloc__ in cKDTree.

### PR DESCRIPTION
**Pull request by sturlamolden**
Fixes misspelling preventing destructor from being invoked.

### CODE REVIEW

**Comment by sturlamolden** [comment]
Fix for #5630 in master

Backport candidate for 0.17.x

**Comment by ev-br** [comment]
The fix looks good, how about a test. Is there a simple way to adapt the code from gh-5630 into a unit test?

**Comment by sturlamolden** [comment]
Yes, ```resource``` is in the standard libary so this should be possible. There might be other parts of the system causing small leaks (I get a few of them unrelated to ```cKDTree```), but at least the frequency should be much lower than one per ```cKDTree``` instance.

**Comment by sturlamolden** [comment]
Added unit test

**Comment by sturlamolden** [comment]
```resource``` is Unix only on Python 2.6 so the unit test needs a tiny update.

**Comment by sturlamolden** [comment]
Note that if we run the unit test against 0.16.0 this happens:

```Python
import numpy as np
from scipy.spatial import cKDTree
from numpy.testing import assert_


def test_ckdtree_memuse():
    # unit test adaptation of gh-5630
    try:
        import resource
    except ImportError:
        return
    # Make some data
    dx, dy = 0.05, 0.05
    y, x = np.mgrid[slice(1, 5 + dy, dy),
                    slice(1, 5 + dx, dx)]
    z = np.sin(x)**10 + np.cos(10 + y*x) * np.cos(x)
    z_copy = np.empty_like(z)
    z_copy[:] = z
    # Place FILLVAL in z_copy at random number of random locations
    FILLVAL = 99.
    mask = np.random.random_integers(0, z.size - 1, np.random.randint(50) + 5)
    z_copy.flat[mask] = FILLVAL
    igood = np.vstack(np.where(x != FILLVAL)).T
    ibad = np.vstack(np.where(x == FILLVAL)).T
    mem_use = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    # burn-in
    for i in range(10):
        tree = cKDTree(igood)
        tree = None
    # count memleaks while constructing and querying cKDTree
    num_leaks = 0
    for i in range(100):
        mem_use = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        tree = cKDTree(igood)
        dist, iquery = tree.query(ibad, k=4, p=2)
        tree = None
        new_mem_use = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if new_mem_use > mem_use:
            num_leaks += 1
    # ideally zero leaks, but errors might accidentally happen
    # outside cKDTree
    assert_(num_leaks < 10)

test_ckdtree_memuse()
```

```bash
sturla$ python test.py
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    test_ckdtree_memuse()
  File "test.py", line 40, in test_ckdtree_memuse
    assert_(num_leaks < 10)
  File "/Users/sturla/anaconda/lib/python3.4/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError
```

Which means it finds the problem if it is there.

**Comment by sturlamolden** [comment]
Travis is still happy. Nothing more to do here.

**Comment by rgommers** [comment]
Great, merged. Thanks Sturla!

**Comment by rgommers** [comment]
@ev-br you want to do the backport before the final release?

**Comment by ev-br** [comment]
@rgommers yes, will lump the backports together

**Comment by ev-br** [comment]
backported in gh-5682

**Pull request merged**
