### PR TITLE
CI: clean conda index upon cache invalidation

### PR DESCRIPTION
**Pull request by tupui**
As seen in recent logs, it seems like when cache is invalidated, the index could also be cached an cause resolve issues.

https://github.com/scipy/scipy/actions/runs/4075996433/jobs/7023135535

This is an attempt at fixing it.

### CODE REVIEW

**Comment by tupui** [comment]
So we see now that it's not using a cached index, but it's failing with the same resolution error. I don't know what is going on here.

@MarcoGorelli any idea? Maybe you looked into this for Pandas?

**Comment by MarcoGorelli** [comment]
hey - I don't know I'm afraid

**Comment by tupui** [comment]
ok thanks no worries :)

**Comment by tupui** [comment]
I tried to create an env from scratch and it did not help as well. I am confused now.

**Comment by tupui** [comment]
Ok found it! This was due to the option `use-only-tar-bz2: true`

**Comment by tupui** [comment]
Getting this in as it fixes the CI

**Pull request merged**
