### PR TITLE
MAINT: casting errstate for NumPy 1.24

### PR DESCRIPTION
**Pull request by tylerjereddy**
* Attempts to deal with the ARM-specific portion of gh-17630 -- these issues appear to be the result of NumPy 1.24.0 change:
https://numpy.org/devdocs/release/1.24.0-notes.html#numpy-now-gives-floating-point-errors-in-casts

* I was able to reproduce and fix the issues in `scipy/sparse/tests/test_base` on an ARM node

* however, for `test_decomp_update` I actually saw more severe problems when working on a Cavium ThunderX2 B0 node; for the latter cases, I'll paste what I saw below for some of the representative failures, but for now I just tried to patch the less severe casting errors I see in the CI for those tests to see if it helps (I'm hoping that my own flavor of ARM + gcc-something-different OpenBLAS is just throwing things off locally and I can at least delay looking into that for now...)

```
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::test_neg_strides_economic_rank_p - ValueError: array must not contain infs or NaNs
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::test_neg_strides_rank_p - ValueError: array must not contain infs or NaNs
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::test_non_itemsize_strides_rank_p - ValueError: array must not contain infs or NaNs
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::test_non_native_byte_order_economic_rank_1 - ValueError: array must not contain infs or NaNs
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::test_non_unit_strides_rank_p - ValueError: array must not contain infs or NaNs
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_D::test_economic_rank_p - AssertionError:
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_d::test_non_native_byte_order_rank_1 - ValueError: array must not contain infs or NaNs
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_D::test_Mx1_economic_rank_p - AssertionError:
FAILED scipy/linalg/tests/test_decomp_update.py::TestQRupdate_D::test_economic_rank_1 - AssertionError:
```

* we'll see if the various ARM runs in CI agree with me here, to fix up the CI failures we currently see there

### CODE REVIEW

**Comment by tylerjereddy** [comment]
cc @seberg FYI

**Comment by andyfaff** [comment]
If it's necessary to iterate locally then it may be possible to debug in a docker container on an M1 mac

**Comment by seberg** [comment]
LGTM, thanks.  CPUs/compilers handle these casts a bit different, so whether they flag invalid or not for an out-of-bounds value depends on the system.  I hope this looks fine to you.
This may help with having more SIMD in the future, since when this happens the result is undefined behavior and SIMD runs in into that more often.

**Comment by tylerjereddy** [comment]
Alright, I checked with an active NumPy developer, and I think we'd probably merge this even if we weren't on the cusp of another release candidate. It simply suppresses a few floating point warnings on `aarch64` and cleans up the CI a bit, and from release management perspective means we can pass tests with latest stable NumPy on ARM.

**Comment by tylerjereddy** [comment]
marked as backport candidate for `1.9.x` series as discussed in cross-linked issue above, in the event that we have a compelling reason to do another `1.9.x` release

**Pull request merged**
