### PR TITLE
CI: pin OpenBLAS to specific build in macOS job to avoid gges issue

### PR DESCRIPTION
**Pull request by rgommers**
xref gh-16949. This doesn't fix the root cause of the problem, but stops the CI job from failing.

[skip azp] [skip circle]

### CODE REVIEW

**Comment by rgommers** [comment]
This worked, the `macOS tests (meson)` build is green now.

**Review by tylerjereddy — APPROVED** [review]
LGTM

**Comment by rgommers** [comment]
Argh, this is not correct. It fixes CI, but breaks package resolution on platforms other than macOS x86-64:
```
nothing provides requested openblas ==0.3.21 openmp_h2bb6d6c_
```
I will revert this, and resubmit once I have the right incantation to make it cross-platform.

**Comment by rgommers** [comment]
I forgot, this can't actually work because conda/mamba don't support selectors, only `conda-build` does: https://github.com/conda/conda/issues/8089

**Pull request merged**
