### PR TITLE
Allow homogeneous coordinate transforms in affine_transform

### PR DESCRIPTION
**Pull request by jni**
There was some discussion in https://github.com/scipy/scipy/issues/2255#issuecomment-29190417 about including support for homogeneous coordinate transforms by detecting the shape of the transformation matrix as being 1 + the dimensionality of the image. This implements that change. Hopefully I haven't broken 50 things in the process. =P

### CODE REVIEW

**Comment by pv** [comment]
Test failures.

**Comment by jni** [comment]
@pv I think I've addressed your comments. I tested the functions manually for a translation -> rotation -> translation sequence to get a rotation about the center. Splitting the resulting homogeneous matrix as is done in the PR gave the correct result using affine_transform.

The scipy.special.orthogonal errors appear unrelated to this PR, am I right there?

**Comment by jni** [comment]
Here's the code I used to check that the offset is used correctly in the PR:

```python
import numpy as np
from scipy import ndimage as ndi
from skimage import data

camera = data.camera()
θ = np.deg2rad(30)
C = np.cos
S = np.sin

T0 = np.array([[1, 0, -256], [0, 1, -256], [0, 0, 1.]])
Rot = np.array([[C(θ), -S(θ), 0], [S(θ), C(θ), 0], [0, 0, 1]])
T1 = np.array([[1, 0, 256], [0, 1, 256], [0, 0, 1.]])

Forward = T1 @ Rot @ T0
Inverse = np.linalg.inv(Forward)

camera_rot = ndi.affine_transform(camera, Inverse[:2, :2], Inverse[:2, 2], order=1)

plt.imshow(camera_rot)
```

Result:

figure_1

**Comment by pv** [comment]
I think the change is fine, but there are some test failures on travis (test_affine_transform26, test_affine_transform27)

**Comment by pv** [comment]
Also, the text `The given matrix and offset are used ...` in docstring probably should be moved to `Notes`, and adding a paragraph there about the extended affine transform matrices could be useful, even if this is a standard convention.

**Comment by jni** [comment]
@pv Thanks for the review! Let's hope third time's the charm! =)

**Comment by jni** [comment]
Oooh Travis is happy. That's a first. =P

**Comment by matthew-brett** [comment]
Great - thanks for doing this - it's a very nice addition.

**Comment by stefanv** [comment]
Thank you, Juan; this will certainly lead to more elegant SciPy use downstream.

**Pull request merged**
