### PR TITLE
DOC: special: update docs of `mathieu_cem` and `mathieu_sem`

### PR DESCRIPTION
**Pull request by abhijeethreddy**
#### Reference issue

Documentation of mathieu_cem and mathieu_sem do not have a clear overview of parameters

#### What does this implement/fix?

Updates the documentation to make more sense of input parameters

#### Additional information

The values are taken in degrees and not in radians

### CODE REVIEW

**Comment by tupui** [comment]
Thank you for the PR @abhijeethreddy. @j-bowhay are you interested in doing the full review as well?

**Comment by j-bowhay** [comment]
> Thank you for the PR @abhijeethreddy. @j-bowhay are you interested in doing the full review as well?

Happy to have a look at this

@abhijeethreddy do you have a source for this change? It was my understanding that the period depends on whether m is even or odd. See https://en.wikipedia.org/wiki/Mathieu_function#Mathieu_functions

**Comment by abhijeethreddy** [comment]
> Thank you for the PR @abhijeethreddy. @j-bowhay are you interested in doing the full review as well?

Yes, very much interested in a full review

**Comment by abhijeethreddy** [comment]
> > Thank you for the PR @abhijeethreddy. @j-bowhay are you interested in doing the full review as well?
> 
> Happy to have a look at this
> 
> @abhijeethreddy do you have a source for this change? It was my understanding that the period depends on whether m is even or odd. See https://en.wikipedia.org/wiki/Mathieu_function#Mathieu_functions
    Even Mathieu function and its derivative

    Returns the even Mathieu function, ``ce_m(x,q)``, of order m and
    parameter q evaluated at x (given in degrees).  Also returns the
    derivative with respect to x of ce_m(x,q)

    Notes
    -----
    The Mathieu function obeys the following differential equation:

    .. math:: \mathrm{ce}_\mathrm{m}''(x) + [\alpha + 2 q \cos(2x)] \mathrm{ce}_\mathrm{m}(x) = 0

    For a given real parameter 'q' the characteristic value 'alpha' is chosen
    such that ce_m(x) is periodic with period 2 pi (see mathieu_a). The possible
    solutions for the characteristic value 'alpha' are indexed with 'm'. Further the even
    function fulfills the initial condition ce_m(x=0) != 0 and ce_m'(x=0) == 0 where as
    for the odd function ce_m(x=0) == 0 and ce_m'(x=0) != 0 holds true.

    Further reading see [1] page 475.

    References
    ----------
    .. [1] Shanjie Zhang and Jianming Jin, Computation of special functions, John Wiley, 1996

**Comment by j-bowhay** [comment]
Having looked at this a bit more I'm not confident to say whether this change is correct so I think someone else will have to review

**Comment by melissawm** [comment]
Hello @abhijeethreddy - I'm not too familiar with these functions but looking at [Wikipedia](https://en.wikipedia.org/wiki/Mathieu_function) it looks like the period is either `2*pi` or `pi` depending on the function - could you double check the values you are suggesting here? 

Also, while we're changing these docstrings, I'd advocate for adding a link to either wikipedia or any other reference for these functions so these parameters can be checked by users. Thanks!

**Pull request closed without merging**
