### PR TITLE
BUG: Fix signal.dlsim output length

### LINKED ISSUE #9342: Incorrect output length from scipy.signal.dlsim
I created a discrete transfer function with a dt of 0.025.  I provided an x-vector of length 38,733 and a time vector created externally from 0 to 968.3.  The output data and time vectors that I got back had 38,732 elements instead of 38,733.  The problem went away when I did not input the time vector.

I believe that the error was introduced via the else section of this block of code (lines 3302-3307 in ltisys.py):
```
    if t is None:
        out_samples = len(u)
        stoptime = (out_samples - 1) * system.dt
    else:
        stoptime = t[-1]
        out_samples = int(np.floor(stoptime / system.dt)) + 1
```

What seems to happen is that 968.3/0.025 = 38731.99999999999, which floors to 38731 instead of 38732.  I recommend changing np.floor() to a function that rounds to the nearest integer instead.

### PR DESCRIPTION
**Pull request by gcunhase**
Closes #9342

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
This appears to fix the issue described. One suggestion is to add a unit test to prevent regression in the future--something that fails now on master branch but won't after this fix.

I think the description of the problem provided in the linked issue might help form the basis of a suitable unit test.

We usually try to prefix commit messages that fix bugs with `BUG: `. Hopefully one of our signal processing gurus can confirm this is an actual bug.

**Review by akahard2dj — COMMENTED** [review]
The `np.floor()` function is used to discard digits below the decimal point.
The `np.round()` or `np.around()` function adds 1 for greater than 0.5 and gives the same value `np.floor()` for less than 0.5.
If there are 32.6 and 32.3, the number of samples is different. 
`np.round(32.6) = 33`, `np.round(32.3) = 32`
is there any problem in that case?

**Comment by tylerjereddy** [comment]
@gcunhase Any chance you'll take a look at the revisions here? I see the 1.2.0 milestone was added, which is coming up.

**Comment by rgommers** [comment]
No follow-up on either this PR or the original bug report, which seems invalid. So closing. Thanks for trying to address an issue @gcunhase.

If anyone comes up with a reproducer, please comment.

**Comment by arun-aks** [comment]
I can replicate this with the following code:

```python
import numpy as np
import scipy.signal as signal

FS = 128e8;
n = 49

system = ([1, 0], [1, 0], 1/FS)
tmp, resp = signal.dimpulse(system, n=n);
print(n, tmp.shape, resp[0].shape)


system1 = signal.dlti(*system[:-1], dt=system[-1])._as_ss()
t = np.linspace(0, n * system1.dt, n, endpoint=False)
u = np.zeros((n,))
one_output = signal.dlsim(system1, u, t=t, x0=None)

print(n, one_output[0].shape, one_output[1].shape)
```

The output I get with scipy version 1.4.1 is 
```
49 (48,) (48, 1)
49 (48,) (48, 1)
```

What is expected is
```
49 (49,) (49, 1)
49 (49,) (49, 1)
```

**Pull request closed without merging**
