### PR TITLE
WIP: Have scipy.spatial.qhull link to system qhull

### PR DESCRIPTION
**Pull request by cielavenir**
#### Reference issue

https://github.com/scipy/scipy/issues/9025

#### What does this implement/fix?

Below scipy 1.4.0, bundled qhull is to old. This MR make linking to system qhull.

### CODE REVIEW

**Comment by cielavenir** [comment]
By the way, do you know how to configure using system qhull by pip command line option?

**Comment by cielavenir** [comment]
this MR is for 1.1.x but I have another branch for 1.2.x: https://github.com/cielavenir/scipy/tree/1.2.3-gcc10-externalqhull

**Comment by lucascolley** [comment]
@tylerjereddy am I correct in saying that PRs to very old maintenance branches are not accepted?

**Comment by lucascolley** [comment]
Sure - leaving links to your patches on the linked issue is probably the most helpful place for them in that case.

**Comment by tylerjereddy** [comment]
> @tylerjereddy am I correct in saying that PRs to very old maintenance branches are not accepted?

Probably yeah, the amount of effort required to get wheels rebuilt would be pretty massive I think, given the ecosystem that advanced around/away from the release.

**Pull request closed without merging**
