### PR TITLE
fix merge conflicts in 'option to avoid computing possibly unused svd matrix'

### PR DESCRIPTION
**Pull request by argriffing**
The PR https://github.com/scipy/scipy/pull/4147 had merge conflicts with recent changes in the abstract linear operator interface, so I've manually resolved these in this PR.  The logic and tests should be the same as in the original PR.

### CODE REVIEW

**Comment by larsmans** [comment]
Can you change the commits so that @nicolamontecchio is listed as the author (of the first one at least)? I think `git commit --amend --author=X` will do that.

**Comment by argriffing** [comment]
@larsmans sorry I tried
`$ git commit --amend --author=nicolamontecchio  156d2ce`
but I got the output
`fatal: No existing author found with 'nicolamontecchio'`
I've searched this output on google and I'm not sure what is an acceptable way to deal with it.  Do you have any other suggestions, keeping in mind that I'm not a git pro?

**Comment by pv** [comment]
Git requires an email address in the author name. If you don't know it,
using --author="nicolamontecchio <nicolamontecchio@localhost>" is
probably ok.

**Comment by argriffing** [comment]
Looks like I screwed that up.

**Comment by argriffing** [comment]
fwiw I used
`$ git commit --amend --author="nicolamontecchio <nicolamontecchio@localhost>" -c 156d2ce`
Then when I tried to push to this branch, git complained, so I added the `-f` flag.

**Comment by ev-br** [comment]
@argriffing I tried my git-fu with https://github.com/ev-br/scipy/compare/pr/4147?expand=1
Does it look right? [I'm not sure in either my git-fu or my understanding of this code]

**Comment by argriffing** [comment]
@ev-br Yes that looks good.  I guess you've made the changes from `dot` to `matmat` to resolve the conflict, and haven't messed with the style.  The git-fu of that PR is much better so if you add it as a new PR I'll close this one.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/4504

FWIW, what I did was
```
$ git fetch upstream
$ git checkout pr/4147   # this relies on some git magic I got from @rgommers
$ git rebase upstream/master   # the fun is here
```

This keeps the commit author, but yeah, I wonder what's the recommended way of doing three-way merge with git (I typically do `git difftool`, but I'm sure there is some better incantation)

**Comment by argriffing** [comment]
> # this relies on some git magic I got from @rgommers

Thanks, I googled for 'git checkout pr` and found https://gist.github.com/piscisaureus/3342247 but I'm hesitant to use a non-vanilla git config until I'm more comfortable with git.

**Comment by ev-br** [comment]
I *think* something along the lines of `git remote add <their scipy fork> their_fork` and `git checkout their_fork/<their_branch>` could work

**Comment by pv** [comment]
```
git remote add argriffing https://github.com/argriffing/scipy.git
git fetch argriffing
git checkout argriffing/montecchio-partial-svd
```
is the "standard" way to grab someone else's stuff.

**Comment by argriffing** [comment]
What about a PR like https://github.com/scipy/scipy/pull/3303 which does not use a separate branch and which conflicts with the scipy master branch?  I'd like to try to merge that, after (possibly temporarily) removing the axis-specific stuff and after fixing its brokenness with respect to complex-valued matrices.

**Comment by pv** [comment]
`master` is not a special branch, the name is just a convention, so it works like the others.
You'd need to use `git rebase upstream/master` to resolve the merge conflict:
```
git remote add perryism https://github.com/perryism/scipy.git
git fetch perryism
git checkout -b pr-3303-fix perryism/master
git remote add upstream https://github.com/scipy/scipy.git
git fetch upstream
git rebase upstream/master
# 1.
# edit files with merge conflicts, see the message it prints and `git status`
# replace the parts between the <<< >>> markers with something sensible
git add scipy/sparse/data.py scipy/sparse/tests/test_base.py # mark conflicts resolved
git rebase --continue
# go to 1. until rebase is finished
```

**Comment by argriffing** [comment]
Thanks, I'll try this.  It won't throw away the original authorship information or other meta-data that reviewers might want?

**Comment by larsmans** [comment]
Rebase will leave the author as is, but will make you the "committer" because you last touched the commits.

**Pull request closed without merging**
