### PR TITLE
ENH: contingency: Added measures of association

### PR DESCRIPTION
**Pull request by dtemkin**
measures include Tschuprow's T and Cramer's V and phi. Functions are contained in 'association_test' function within the stats.contingency module.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Is this translated from another package/language? If yes, which and under what license?

**Comment by dtemkin** [comment]
@josef-pkt Nope. Not translated. Wrote the code all by my lonesome. Do I still need to license the addition?

**Comment by josef-pkt** [comment]
> Do I still need to license the addition?

No, if you open a PR, then it is assumed that it is licensed in the same way as scipy.

The names, like camel case, have to be changed to correspond to Python and scipy convention. The docstrings need to follow the numpy documentation standard https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

Those are the things that made me suspect that it is a translation from another language. If you wrote the code, then there is no problem with licensing.

(When I made my first comment, I thought it is a statsmodels PR, The same applies to scipy, statsmodels and other related packages.)

**Comment by dtemkin** [comment]
Cool, I will fix my conventions and look for opportunities to make it more pythonic. I did have one question regarding the scipy/benchmarks. should I be writing and submitting a PR for one of those as well? The ASV documentation links are all code 404, so if I do need to write and submit one some guidance would be appreciated. Thanks for your patience.

**Comment by pv** [comment]
asv was moved to https://github.com/airspeed-velocity/asv
The canonical documentation link is https://asv.readthedocs.io/
I see we are have some other link in some documents --- those should be 
fixed to point to the right place.

**Pull request closed without merging**
