### PR TITLE
[MRG] fix test_lobpcg test failure macOS #10718

### PR DESCRIPTION
**Pull request by lobpcg**
test_lobpcg test failure macOS scipy#10718 is OS specific, indicating possibly some differences in the compiled low-level libraries. I am thinking that this may actually be a bug in eigh. In the call
eigh(gramA, gramB)
both matrices are supposed to be real symmetric or Hermitian. In practice, they are not quite so.
The low-level functions called from eigh are supposed to take only the triangular parts of gramA and gramB, making them automatically symmetric. I get a suspicion that it might not be the case for some libraries/OS's. This may be why lobpcg computes a totally wrong eigenvalue after the message
matrix gramA of the type float32 is not sufficiently Hermitian.

I am fixing it in this PR by making the matrices symmetric explicitly in lobpcg, which removes the dependence on how eigh treats real symmetric or Hermitian matrices. This results in extra computations in some cases, but may also improve overall stability of lobpcg.

### CODE REVIEW

**Comment by lobpcg** [comment]
Funny that the updated test now introduces issues in other configurations, and it still system-specific... 

It still runs fine on my system, so I cannot do any debugging of the lobpcg itself. I'll try to find a similar looking example of failure on my system, to have something specific to look at.

**Comment by lobpcg** [comment]
May be in the mean time this specific test test_tolerance_float32 should be temporary excluded from scipy testing.

**Comment by rgommers** [comment]
> May be in the mean time this specific test test_tolerance_float32 should be temporary excluded from scipy testing.

Makes sense. There are multiple `float32` tests, so not running one if it's troublesome sounds fine. You can decorate the test in this PR with:
```
@pytest.mark.xfail(reason="This fails on some platforms, ...<etc>")
```

**Comment by lobpcg** [comment]
I have found a similar example that fails on my system, so I try to debug and find an actual fix

import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg.eigen.lobpcg import lobpcg

np.random.seed(1566777238)
n = 60
m = 4
vals = -np.arange(1, n + 1)
A = diags([vals], [0], (n, n))
A = A.astype(np.float32)
X = np.random.randn(n, m)
X=X.astype(np.float32)
eigvals, _ = lobpcg(A, X, tol=1e-8, maxiter=50, verbosityLevel=1)

Solving standard eigenvalue problem without preconditioning

matrix size 60
block size 4

No constraints


iteration 0
current block size: 4
eigenvalue: [-23.82003  -25.394815 -28.272272 -33.422115]
residual norms: [17.86237  16.818165 15.563285 15.41456 ]
iteration 1
current block size: 4
eigenvalue: [ -9.539008  -11.289349  -14.8041525 -17.867403 ]
residual norms: [ 9.287929  8.849451  8.460517 12.356036]    
iteration 2
current block size: 4
eigenvalue: [ -5.5675707  -7.0538855  -9.043852  -10.574869 ]
residual norms: [5.3667207 6.804403  8.23447   6.020886 ]
iteration 3
current block size: 4
eigenvalue: [-3.4613361 -4.5784235 -6.243501  -8.501392 ]
residual norms: [5.1134396 4.8072042 4.4674463 4.282956 ]
iteration 4
current block size: 4
eigenvalue: [-2.0328438 -3.1851683 -5.2839847 -7.2655554]
residual norms: [3.4501534 3.2814322 2.720375  4.636082 ]
iteration 5
current block size: 4
eigenvalue: [-1.4901878 -2.6502504 -4.810485  -4.9524   ]
residual norms: [2.1526556 2.0325382 5.274499  2.745181 ]
iteration 6
current block size: 4
eigenvalue: [-1.2479848 -2.3691878 -3.4560955 -4.6440525]
residual norms: [1.6429825 2.185988  3.0767286 1.9107376]
iteration 7
current block size: 4
eigenvalue: [-1.0898232 -2.1054451 -3.1566012 -4.339618 ]
residual norms: [1.1599809 1.3091618 1.3457662 1.7988803]
iteration 8
current block size: 4
eigenvalue: [-1.0226592 -2.028383  -3.0691385 -4.1283655]
residual norms: [0.65728    0.7152142  0.81444055 1.3397031 ]
iteration 9
current block size: 4
eigenvalue: [-1.0068636 -2.007465  -3.0311673 -4.050292 ]
residual norms: [0.31308296 0.311632   0.5721221  0.7859263 ]
iteration 10
current block size: 4
eigenvalue: [-1.0018156 -2.003277  -3.012018  -4.016252 ]
residual norms: [0.19928446 0.21450831 0.43116117 0.47894868]
iteration 11
current block size: 4
eigenvalue: [-1.0003539 -2.0008767 -3.0032818 -4.006688 ]
residual norms: [0.09127599 0.12196373 0.24135138 0.27747154]
iteration 12
current block size: 4
eigenvalue: [-1.0000674 -2.000196  -3.0008082 -4.003014 ]
residual norms: [0.03627297 0.0651545  0.11585114 0.15411644]
iteration 13
current block size: 4
eigenvalue: [-1.0000128 -2.0000534 -3.0003154 -4.001745 ]
residual norms: [0.01846664 0.02919248 0.05665667 0.12130237]
iteration 14
current block size: 4
eigenvalue: [-1.0000023 -2.000015  -3.0001466 -4.000925 ]
residual norms: [0.00620153 0.01384443 0.04059397 0.09352355]
iteration 15
current block size: 4
eigenvalue: [-1.0000007 -2.0000026 -3.00006   -4.0003705]
residual norms: [0.00361749 0.00952669 0.02895345 0.06722998]
iteration 16
current block size: 4
eigenvalue: [-1.0000001 -2.0000005 -3.000018  -4.000137 ]
residual norms: [0.00164955 0.00541906 0.01695555 0.04046936]
iteration 17
current block size: 4
eigenvalue: [-1.        -1.9999894 -3.0000048 -4.0000644]
residual norms: [0.00088737 0.00260692 0.00910376 0.02517417]
iteration 18
current block size: 4
eigenvalue: [-0.99999994 -1.9999949  -3.0000067  -4.0000405 ]
residual norms: [0.00043189 0.00142937 0.00479182 0.01704712]
iteration 19
current block size: 4
eigenvalue: [-1.        -2.0000014 -3.000004  -4.0000315]
residual norms: [0.00021487 0.0008333  0.00310983 0.010489  ]
iteration 20
current block size: 4
eigenvalue: [-1.        -2.0000079 -2.9999976 -4.0000095]
residual norms: [0.0001179  0.00053212 0.00197382 0.00965141]
iteration 21
current block size: 4
eigenvalue: [-1.        -2.000006  -3.0000036 -4.0000124]
residual norms: [7.1841358e-05 2.9756816e-04 1.4777052e-03 8.9202439e-03]
iteration 22
current block size: 4
eigenvalue: [-1.        -1.9999963 -3.        -4.000005 ]
residual norms: [4.5318615e-05 1.7441159e-04 9.8370283e-04 7.2212168e-03]
iteration 23
current block size: 4
eigenvalue: [-1.        -1.9999899 -2.999992  -4.0000067]
residual norms: [2.32534749e-05 1.01488135e-04 6.09903655e-04 4.65402426e-03]
iteration 24
current block size: 4
eigenvalue: [-1.        -2.0000048 -2.9999998 -4.000001 ]
residual norms: [1.0482983e-05 5.2714717e-05 3.2237312e-04 2.4414905e-03]
iteration 25
current block size: 4
eigenvalue: [-1.        -2.0000012 -2.999994  -4.0000014]
residual norms: [6.6231960e-06 3.6839170e-05 2.4182994e-04 1.5475648e-03]
iteration 26
current block size: 4
eigenvalue: [-1.        -1.9999989 -2.9999986 -3.9999907]
residual norms: [3.4432517e-06 2.5696767e-05 1.7096169e-04 1.2090916e-03]
iteration 27
current block size: 4
eigenvalue: [-1.        -1.9999968 -3.0000033 -4.0000033]
residual norms: [2.51051847e-06 1.65687834e-05 1.16021554e-04 9.61379614e-04]
iteration 28
current block size: 4
eigenvalue: [-1.        -2.000007  -3.000004  -3.9999924]
residual norms: [1.8607587e-06 1.2153918e-05 5.7312162e-05 5.1090989e-04]
iteration 29
current block size: 4
eigenvalue: [-1.        -2.        -3.0000007 -4.000001 ]
residual norms: [1.7648547e-06 1.0975477e-05 3.5225061e-05 2.6257292e-04]
iteration 30
current block size: 4
eigenvalue: [-1.        -1.9999981 -2.9999962 -3.9999967]
residual norms: [1.8350212e-06 5.9516306e-06 2.3264050e-05 1.8937267e-04]
iteration 31
current block size: 4
eigenvalue: [-1.        -2.000008  -3.000002  -4.0000014]
residual norms: [1.9175918e-06 9.6671474e-06 1.5774258e-05 1.5134600e-04]
iteration 32
current block size: 4
eigenvalue: [-1.        -2.0000062 -2.9999979 -3.9999995]
residual norms: [2.0081227e-06 8.9899213e-06 1.4424178e-05 1.4697736e-04]
iteration 33
current block size: 4
eigenvalue: [-1.        -2.0000038 -2.9999962 -3.9999995]
residual norms: [2.0977420e-06 7.1352028e-06 1.0013096e-05 1.3417588e-04]
iteration 34
current block size: 4
eigenvalue: [-1.        -2.0000052 -3.0000012 -4.000002 ]
residual norms: [2.0977420e-06 7.0746114e-06 6.8475351e-06 9.8549383e-05]
iteration 35
current block size: 4
eigenvalue: [-1.        -2.0000005 -2.9999936 -3.9999988]
residual norms: [2.0977420e-06 3.2920777e-06 1.0483093e-05 7.3061041e-05]
iteration 36
current block size: 4
eigenvalue: [-1.        -2.0000043 -3.        -3.9999986]
residual norms: [2.0977420e-06 7.1852201e-06 4.2926458e-06 5.2291318e-05]
iteration 37
current block size: 4
eigenvalue: [-1.        -2.0000002 -2.999996  -4.0000014]
residual norms: [2.1190021e-06 6.7725105e-06 1.0223392e-05 4.6127177e-05]
matrix gramA of the type float32 is not sufficiently Hermitian:
condition: 2e-04 < 1.674703e-04
iteration 38
current block size: 4
eigenvalue: [38.25031   -1.        -1.9999994 -2.9999976]
residual norms: [8.6147049e+01 2.1190021e-06 3.2544465e-06 5.6324225e-06]
iteration 39
current block size: 4
eigenvalue: [49.658165   -0.99999964 -1.9999969  -2.999998  ]
residual norms: [6.9545944e+01 6.8770987e-06 7.3898996e-06 6.7223164e-06]
iteration 40
current block size: 4
eigenvalue: [ 1.2888766e+03 -9.9993312e-01 -1.9999981e+00 -2.9999955e+00]
residual norms: [4.7831533e+03 1.2393303e-04 1.3471979e-05 9.5481955e-06]
iteration 41
current block size: 4
eigenvalue: [ 1.3033303e+03 -9.9993569e-01 -2.0000031e+00 -2.9999979e+00]
residual norms: [4.6710322e+03 7.7177952e-05 7.0989922e-06 5.1876550e-06]
iteration 42
current block size: 4
eigenvalue: [ 1.3169757e+03 -9.9993789e-01 -2.0000055e+00 -2.9999952e+00]
residual norms: [4.5612397e+03 7.3438277e-05 8.5749425e-06 9.3858407e-06]
iteration 43
current block size: 4
eigenvalue: [ 1.3294900e+03 -9.9993032e-01 -2.0000057e+00 -2.9999928e+00]
residual norms: [4.453318e+03 7.415292e-05 8.246502e-06 8.029652e-06]
iteration 44
current block size: 4
eigenvalue: [ 1.3410140e+03 -9.9992627e-01 -2.0000107e+00 -2.9999921e+00]
residual norms: [4.3473667e+03 7.4634707e-05 2.1115693e-05 9.5831929e-06]

**Comment by lobpcg** [comment]
> 
> 
> > May be in the mean time this specific test test_tolerance_float32 should be temporary excluded from scipy testing.
> 
> Makes sense. There are multiple `float32` tests, so not running one if it's troublesome sounds fine. You can decorate the test in this PR with:
> 
> ```
> @pytest.mark.xfail(reason="This fails on some platforms, ...<etc>")
> ```

Where does the decoration go? I have not used it before

**Comment by rgommers** [comment]
right above the `def test_tolerance_float32`

**Comment by andyfaff** [comment]
This PR passes on my computer.

**Comment by MichaelMarien** [comment]
a bit late, but I can confirm this also fixes #10718 for me

**Pull request merged**
