### PR TITLE
MAINT: spatial: upgrade to Qhull 2015.2

### PR DESCRIPTION
**Pull request by pv**
Upgrade bundled Qhull to most recent version.
Also, switch to using the reentrant interface, which simplifies the wrapper code.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
> Sorry, we could not display the entire diff because it was too big.

Would any reviews help here, or should it be good enough to trust Travis?

**Comment by pv** [comment]
You can look at the individual commits (apart from the first one which just upgrades the files).

**Comment by ev-br** [comment]
Barf, this now needs a rebase. Once it's mergeable again, I'll be inclined to trust the tests and merge it. This way, it'll have a better chance of being tested via travis-wheels. If someone want to review this in detail, needs more time, or otherwise has issues with this, please speak up.

**Comment by pv** [comment]
Rebased

**Comment by ev-br** [comment]
Merged, thanks Pauli.

(the CI test error is unrelated and is safe to ignore.)

**Pull request merged**
