### PR TITLE
MAINT: Fix typos in comments, docs and test name

### PR DESCRIPTION
**Pull request by minho42**
Fixed some typos.

### CODE REVIEW

**Review by peterbell10 — CHANGES_REQUESTED** [review]
ARPACK, SuperLU and qhull are vendored libraries so I don't think those changes are appropriate.

**Review by peterbell10 — APPROVED** [review]

**Comment by minho42** [comment]
Oh I'm sorry I made the same mistake.
Thanks @peterbell10

**Review by tylerjereddy — APPROVED** [review]
Thanks for the typo fixes, merging.

**Comment by minho42** [comment]
Thanks.

**Pull request merged**
