### PR TITLE
ENH: optimize: add method attribute to result object from root_scalar and root

### LINKED ISSUE #19098: ENH: add method in RootResults of root_scalar and root
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

Add an attribute `method` to the result object of `root_scalar` and `root`.

### Describe alternatives you've considered.

_No response_

### Additional context (e.g. screenshots, GIFs)

It is already hard to tell which method is chosen as default. It would be nice to have it at least in the return results object.

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

closes #19098
#### What does this implement/fix?

Adds a `method` attribute to the results object returned by `root_scalar` and `root`.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The ref. guide check failure is real.  The docstring of `toms748` in `_zeros_py.py` needs to be updated.

**Comment by mdhaber** [comment]
It looks like the goal was not just to add `method` to the results of `root_scalar` and `root` but also to the separate public functions for each of the `root_scalar` methods? For `root`, `minimize`, and `minimize_scalar`, the individual method functions (e.g. `fmin_...`) are listed in the "Legacy Functions" section, but that's not the case for `root_scalar`, so I suppose that's why they are modified here?

**Comment by j-bowhay** [comment]
> It looks like the goal was not just to add `method` to the results of `root_scalar` and `root` but also to the separate public functions for each of the `root_scalar` methods? For `root`, `minimize`, and `minimize_scalar`, the individual method functions (e.g. `fmin_...`) are listed in the "Legacy Functions" section, but that's not the case for `root_scalar`, so I suppose that's why they are modified here?

The separate public functions for each of the `root_scalar` methods return result objects whereas the "Legacy Functions" don't. To me a least, the code makes more sense if the method is added to the result object at instantiation rather than having to hunt around for where this attribute is added.

**Comment by mdhaber** [comment]
> To me a least, the code makes more sense if the method is added to the result object at instantiation rather than having to hunt around for where this attribute is added.

I agree with the sentiment but reach the opposite conclusion. If the attribute is only present in the objects returned from `root_scalar`, then if one wanted to find the source code where the attribute is added, a natural place to start would be `root_scalar`. I would have thought we could add the attribute there, in which case the search would end. Here, though, the interested developer needs to check in all of the separate solvers individually.

I'm OK with that; it's just not what I had in mind, and it takes a little more concentration to review. Perhaps @WarrenWeckesser would be willing to review and merge?

**Review by mdhaber — APPROVED** [review]
Looks like all `RootResult` returns are covered and that the `method` is consistent with the method used. Tests look good. (The existing `run_tests` code is harder to follow, but I don't think the test would pass if the modification were not correct.) Remaining CI failures look unrelated to the PR. Thanks @j-bowhay.

**Pull request merged**
