### PR TITLE
CI: pin Sphinx version to 1.8.5

### PR DESCRIPTION
**Pull request by rgommers**
Sphinx 2.0.0 (just released) breaks the doc build. So fix CI first, investigate later.

### CODE REVIEW

**Comment by rgommers** [comment]
will merge this straight away to prevent more CI failures

**Comment by larsoner** [comment]
Thanks for the quick fix

**Comment by larsoner** [comment]
I can try to use 2.0 locally tomorrow. Last I worked on docs I was probably on a 2.0+ dev branch so I'm optimistic that it shouldn't take too much work

**Comment by rgommers** [comment]
thanks, that would be nice!

**Pull request merged**
