### PR TITLE
[DOC] mention graph cuts in maximum flow docstring

### PR DESCRIPTION
**Pull request by emmanuelle**
I propose here to add a reference to graph cuts optimization which relies on maximum flow; I had been told that scipy had a new graph cuts algorithm (which was of course incorrect, but not far), and googling "scipy graph cuts" did not return anything meaningful. 

By the way, thank you for adding this algorithm to scipy, we'll probably try it for scikit-image features which have been stalled for a long time due to the difficulty of implementing correctly a maxflow-mincut algorithm. (scikit-image maintainer here :-))

### CODE REVIEW

**Comment by ilayn** [comment]
Pinging @fuglede for reviewing this addition.

**Comment by fuglede** [comment]
Thanks; this seems like a useful reference (I learned something from it!)

The built docs look as expected as well.

One minor nit I noticed: Wikipedia refers to the problem as "graph cut optimization" where the PR calls it "graph cut*s* optimization". Both seem to be in active use but the former is perhaps more standard?

For these applications, it looks like the main use is in having a minimum cut. Should we consider including that explicitly here as well, e.g. as part of `MaximumFlowResult` (where it could be calculated on demand)? We're already building the residual graph, so it should be straight-forward enough to find a minimum cut.

**Review by fuglede — APPROVED** [review]

**Comment by tylerjereddy** [comment]
Merging doc change based on expert review, thanks @emmanuelle & @fuglede

**Comment by mdhaber** [comment]
Thanks @emmanuelle! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Comment by emmanuelle** [comment]
Sorry for not following up on this @fuglede. Should I open a new issue in order to discuss the computation of the min cut, and the corresponding API?

**Comment by fuglede** [comment]
@emmanuelle That'd work for me. The [mailing list](https://mail.python.org/mailman/listinfo/scipy-dev) is also a natural home for more general discussion.

**Pull request merged**
