### PR TITLE
MAINT: work around a possible numpy ufunc loop selection bug

### PR DESCRIPTION
**Pull request by argriffing**
Suggested by @pv in https://github.com/scipy/scipy/issues/4895#issuecomment-103807494.

### CODE REVIEW

**Comment by argriffing** [comment]
TravisCI failure is due to the 50min timeout.

**Comment by argriffing** [comment]
If no one has an objection I might merge this in a few days.

**Comment by rgommers** [comment]
Not backporting this one to 0.16.0, because it doesn't look like it's necessary and it would probably require another RC.

**Comment by WarrenWeckesser** [comment]
Another example of this issue: http://stackoverflow.com/questions/33186777/evaluating-function-using-numpy-array-returns-inf-and-nan

**Comment by pv** [comment]
@rgommers: backport-candidate?

**Pull request merged**
