### PR TITLE
Added more testing of smirnov/smirnovi functions 

### PR DESCRIPTION
**Pull request by pvanmulbregt**
Added test_kolmogorov.py to test `smirnov(n,x)` and `smirnovi(n,p)`, especially near the endpoints of the `[0,1]` interval.
Note: many of these tests fail with the current implementation of `smirnovi()`.  E.g.
test_basic (test_kolmogorov.TestSmirnovi) ... FAIL
test_n_equals_1 (test_kolmogorov.TestSmirnovi) ... FAIL
test_n_equals_2 (test_kolmogorov.TestSmirnovi) ... FAIL
test_n_equals_3 (test_kolmogorov.TestSmirnovi) ... FAIL
test_round_trip (test_kolmogorov.TestSmirnovi) ... FAIL
test_x_equals_0 (test_kolmogorov.TestSmirnovi) ... FAIL

### CODE REVIEW

**Comment by pv** [comment]
If you want to add these tests now, before fixing the bugs in smirnov*, 
please add knownfailure markers to disable the failing tests:
```
from numpy.testing import (..., dec)


     @dec.knownfailureif(True, "test fails; smirnov() is not accurate")
     def test_n_equals_1(self):
         ...
```

**Comment by pvanmulbregt** [comment]
Thanks for the info.  Requested decorations made.

**Comment by pvanmulbregt** [comment]
Anything required here?  The py2.7 full test timed out.
[Is there a good time to submit PRs which would avoid this issue? Or is the time to run the testing independent of the date/time of submission?]

**Comment by rgommers** [comment]
> Anything required here?

looks good from a quick glance, but leaving this to someone else to merge.

> [Is there a good time to submit PRs which would avoid this issue? Or is the time to run the testing independent of the date/time of submission?]

It's independent of time of day as far as I can tell. TravisCI has gotten slower the last weeks/month. We've recently sped up the test suite so it avoids the timeouts the majority of the time, but further improvements may be needed.

**Comment by pv** [comment]
Rebased + pushed for merging.

**Pull request merged**
