### PR TITLE
DOC: update the author name mapping

### PR DESCRIPTION
**Pull request by ev-br**
@vanpact @Sebascn @mamrehn @cel4 @chemelnucfin  Do you want to tell me your full name so that we can properly attribute your contributions in the release notes?

@person142 @drpeteb your git/github handles only have your first names. If you want to be credited with a full name, please let me know

### CODE REVIEW

**Comment by Sebascn** [comment]
My full name is "Sebastian Skoupý". Thanks a lot! :)

**Comment by cel4** [comment]
At the moment I am not really interested in revealing my true identity. As there is not really a big contribution from my side, I think it makes sense to simply drop me from the contributors list.

**Comment by chemelnucfin** [comment]
Hi Evgeni,
  Ya, my contribution is not that significant.  Wait until I have more
significant ones.  :)

Thanks.

**Comment by vanpact** [comment]
My first name is "Yves-Rémi" and my family name is "Van Eycke". :)
Thanks!

**Comment by person142** [comment]
Josh Wilson; thanks.

**Comment by drpeteb** [comment]
Pete Bunch.

Thank you!

**Comment by rgommers** [comment]
TravisCI failure was an unrelated VM timeout.

**Comment by rgommers** [comment]
Merging, thanks Evgeni!

**Pull request merged**
