### PR TITLE
DOC: Fix indentation in new_stats_distribution.rst.inc

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
I noticed this while reviewing another PR.  The text for the first numbered item under "Before Implementation" wasn't indented enough.

### CODE REVIEW

**Comment by mdhaber** [comment]
I'll wait for CI to finish then merge.

**Review by mdhaber — APPROVED** [review]

**Comment by mdhaber** [comment]
Before:
image

After:
image

**Comment by WarrenWeckesser** [comment]
Thanks @mdhaber.  I don't know why Sphinx is not adding some space after the bulleted list.  If I do a similar bulleted list outside of an enumerated list, Sphinx puts a bit of space before and after the bulleted list, so it might be a Sphinx bug/wart/quirk.

**Comment by mdhaber** [comment]
Yeah I just forgot to merge.

**Pull request merged**
