### PR TITLE
implement two sample one sided ks test

### PR DESCRIPTION
**Pull request by MarvinT**
Updates ks_2samp to work with one sided alternative hypotheses

### CODE REVIEW

**Comment by josef-pkt** [comment]
looks good to me. The one-sided alternative needs to be better explained and show in which direction the one-sided test goes, i.e. one greater than two or two greater than one.

Is there a reference for the p-value approximation, e.g. Stephens, or is it taken from the two-sided case.
Adding a reference would be useful.

**Comment by josef-pkt** [comment]
This should be checked against the mstats version, which already has an alternative option.
https://github.com/MarvinT/scipy/blob/a5e46e9b0f84bd3016055055bbc1fca6b52f7c07/scipy/stats/mstats_basic.py#L1074
(I don't remember that I ever looked at the details of it.)

(especially confusing for this type of statistics: "larger" cdf means "smaller" values are observed.)

**Comment by MarvinT** [comment]
Hmm, I wasn't aware of the mstats version. Had I known about it I probably would have just used that... which would have been troubling since it doesn't agree with the sp.stats version (which does agree with the matlab version)

```
x1 = [1, 1, 2, 2, 1, 3, 2]
x2 = [4, 5, 7, 2, 5, 2, 4]
print sp.stats.mstats.ks_twosamp(x1, x2, alternative='two-sided')
print sp.stats.ks_2samp(x1, x2)
>>> (0.71428571428571419, 0.056230069748064229)
>>> Ks_2sampResult(statistic=0.7142857142857143, pvalue=0.027500341091743086)
```

and in Matlab
```
>> [H,P,KSSTAT] = kstest2(x1, x2)
H =
     1
P =
    0.0275
KSSTAT =
    0.7143
```

You're definitely right about the one sided needing better explanation on which side it compares to.  I actually seem to have it backwards from kstest and Matlab's kstest2 since I interpreted less and greater to refer to the values, not the CDF. I'll definitely fix that. I'm not sure what to do about the discrepancy with the mstats version?

**Comment by MarvinT** [comment]
I was looking for a reference and haven't been able to find anything.

I've looked at [this](http://www.jstatsoft.org/v39/i11/paper) and [this](http://www.jstatsoft.org/v08/i18/paper) but neither seem to be the method I used.

I just took the calculation done by the Matlab function kstest2 and translated it into python.

**Comment by rgommers** [comment]
> I just took the calculation done by the Matlab function kstest2 and translated it into python.

@MarvinT unfortunately that's a problem - you're saying that your implementation is based on Matlab code, and that Matlab code doesn't have a license that is compatible with the BSD license we ship Matlab with.

**Comment by pv** [comment]
Closing, we cannot take translations of license-incompatible codes.

**Pull request closed without merging**
