### PR TITLE
STY: c89 style issues

### PR DESCRIPTION
**Pull request by apbard**
fixes errors with c89 compilers #7628

@pv I fixed all warnings marked as "ISO C90 forbids mixed declarations and code". Please check to see if it is enough.

### CODE REVIEW

**Comment by xoviat** [comment]
https://ci.appveyor.com/project/scipy/scipy/build/1.0.16/job/2172a814fcamrah2

**Comment by xoviat** [comment]
msvc 2008 a horrible compiler so you know if it passes there, it will pass anywhere.

**Comment by xoviat** [comment]
Looks good

**Comment by pv** [comment]
Thanks. MSVC seems to be happy with it now.

**Pull request merged**
