### PR TITLE
FIX: Allow any dtype-specifier for ndimage output

### PR DESCRIPTION
**Pull request by effigies**
#### Reference issue
Fixes bug introduced in gh-18841.

#### What does this implement/fix?
As of #18841, calling `ndimage.map_coordinates(..., output='float32')` fails with:

```python
File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/sdcflows/transform.py", line 105, in _sdc_unwarp
	resampled = ndi.map_coordinates(
	            ^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/scipy/ndimage/_interpolation.py", line 455, in map_coordinates
	output = _ni_support._get_output(output, input, shape=output_shape,
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/scipy/ndimage/_ni_support.py", line 96, in _get_output
	output = f_dict[output]
	         ~~~~~~^^^^^^^^
KeyError: 'float32'
```

This replaced `output = np.sctypeDict[output]`, which would normalize scalar types to their numpy types. Looking at the codes in that `dict`, it is basically equivalent to:

```Python
def __getitem__(self, key)
    dtype = np.dtype(key)
    if len(dtype) != 0:
        raise KeyError(key)
    return dtype.type
```

Which will fail for record types, but not much else.

The proposed solution just uses `np.dtype()` directly and moves on. If desired, I could add more checks, such as that `len(output)` must be 0 or `output.type` must not be void or must be numeric, or whatever the actual intent of this section is.

#### Additional information
xref nipreps/sdcflows#433

### CODE REVIEW

**Comment by ev-br** [comment]
It seems reasonable to allow `output="float32"` etc indeed.
From poking around a bit with scipy 1.9, it seems that ndimage emits a reasonable error if asked a non-numeric dtype:

```
In [37]: from scipy import ndimage
    ...: >>> import numpy as np
    ...: >>> a = np.arange(12.).reshape((4, 3))
    ...: >>> a
    ...: >>> ndimage.map_coordinates(a, [[0.5, 2], [0.5, 1]], order=1, output=np.dtype([('a', int), ('b', 'float')]))
....
<snip>
...
--> 456     _nd_image.geometric_transform(filtered, None, coordinates, None, None,
    457                                   output, order, mode, cval, npad, None, None)
    458     return output
RuntimeError: data type not supported
```

I still think it'd be useful to filter out non-numeric types earlier, via something like
```
dt = np.dtype(output)
if not issubclass(dt.type, np.number): raise ...
```

`np.number` comes from https://numpy.org/doc/stable/reference/arrays.scalars.html, under an assumption that `map_coordinates` expects numeric inputs and can handle all of them.

**Comment by effigies** [comment]
Okay, I added a check. Do you want some tests fully exercising `_get_output()`? Or just that it handles sensible dtypes and errors on inappropriate ones?

**Comment by ev-br** [comment]
The closer you can move this Achilles to the turtle, the better :-)

**Comment by effigies** [comment]
Added tests. Having a bit of trouble getting an editable install up and running, so testing locally is very slow. Hopefully the linter caught all the bugs in the tests.

**Comment by ev-br** [comment]
Let's see what the CI says. 
Locally it's easiest to use `$ python dev.py`, does it not work for you?

**Comment by effigies** [comment]
Ah, thanks for the pointer. I tried `python dev.py` for something but possibly had a messed up virtual environment, so just switched to `pip install -e .[test]`, thinking that should work. Figured out `dev.py` and fixed up the tests. This should be good to go.

**Review by rgommers — COMMENTED** [review]
Thanks @effigies. The fix looks good to me - it makes the code easier to understand. The test is too heavily parametrized and really hard to read though. Could you please cut that down a lot, by:
- separating regular test from the `raises` assertion test,
- separating the pre-allocated array input, so there doesn't need to be `(2, 3)` everywhere (regular case is simply input shape == output shape)
- only testing a few cases. Say 4: `'float32'`, `'f4'`, `'complex64'`, `'complex128`. That's enough to guard for regressions, so no need to test every possible string specifier

**Comment by effigies** [comment]
Thanks for the reality check @rgommers. Hopefully this is a more reasonable number of tests, written more clearly.

**Review by rgommers — APPROVED** [review]
LGTM now, thanks @effigies. And thanks for the review @ev-br

**Comment by lucascolley** [comment]
thanks for your first contribution to SciPy @effigies !

**Pull request merged**
