### PR TITLE
ENH: sparse: enable 64-bit index arrays & nnz > 2**31

### PR DESCRIPTION
**Pull request by pv**
Currently Scipy's sparse matrices are limited to `nnz < 2**31`, and crashes and other unspecified behavior occurs if `nnz` becomes larger so that the `int32` indices start to wrap around.

This PR enables sparse matrices to use either int32 or int64 as the data type of
the indices. The data type is chosen automatically based on the `nnz` of the data
and requirements of the different sparse matrix types.

The threshold selection is written so that it can be monkeypatched to be lower
for testing purposes. The 64-bit specific test suite however currently only consists
of running the existing tests with lower thresholds and randomly assigned index
array data types (these tests pass).

The direct linear algebra (superlu, probably also umfpack) do not work with int64 indices, but implementing that is out of scope for this PR. For matrices with `nnz < 2**31`, things should be backwards compatible.

However, more tests would be needed, so this PR is still a bit in a WIP state.
Some help would be appreciated:

```
Write tests / audit the code checking that the data type selection
works appropriately when needed e.g. in assignment etc.
```

Closes [Trac #1307](http://projects.scipy.org/scipy/ticket/1307)

### CODE REVIEW

**Comment by benbowen** [comment]
Is there a plan to merge this?  I would like to run minimum_spanning_tree on a graph that has more edges than allowed. Seems like current minimum is 2.1 billion edges.

**Comment by pv** [comment]
It is already merged. Nobody has taken up enabling 64-bit for csgraph routines however.

**Comment by pv** [comment]
So if you need it, that could be a useful small project to contribute to Scipy.

**Comment by benbowen** [comment]
Thanks, I'll take a closer look, and see if I can setup a development branch on our large-memory nodes for Scipy.

**Comment by pv** [comment]
Note that large memory is not necessarily needed for development --- 
sparse matrices with int64 index data types can be created manually.

**Comment by perimosocordiae** [comment]
Unfortunately, many csgraph functions require square CSR input, so you do actually need lots of memory for the `indptr`, even if `nnz` is small.

**Comment by pv** [comment]
Yes, but note that you can consider small matrices with 64-bit indices.

**Pull request merged**
