### PR TITLE
Replace kl_div by rel_entr in entropy

### LINKED ISSUE #6521: scipy.stats.entropy does *not* calculate the KL divergence
As stated in the documentation for scipy.stats.entropy, the KL divergence is S = sum(pk * log(pk / qk), axis=0). However, by calling scipy.special.kl_div, there are extra linear terms in there (pk - qk) that should not be there. The fix is easy: replace the call to scipy.special.kl_div with scipy.special.rel_entr.

### PR DESCRIPTION
**Pull request by mirca**
Fix #6521

### CODE REVIEW

**Comment by pv** [comment]
Needs tests

27.8.2016 1.14 "Zè Vinícius" <notifications@github.com> kirjoitti:

**Comment by mirca** [comment]
@pv Could you point what kind of tests are needed? Doesn't  those in ``test_distributions.py`` suffice already?

**Comment by pv** [comment]
Sorry, this was a off-the-hip comment. If the line of code in question 
is already tested in a way that ensures it's correct, then it's fine. 
Did you check the current tests do this?

**Comment by mirca** [comment]
@pv Yes, there are tests in ``test_distributions.py`` that check the entropy of most (every?) scipy distributions.

**Comment by pv** [comment]
I see --- they are the same because sum p_k = sum q_k = 1 due to the normalization.

**Comment by mirca** [comment]
@pv Yep. Thanks!

**Pull request merged**
