### PR TITLE
ENH: add a new init method for k-means

### PR DESCRIPTION
**Pull request by jeanpauphilet**
ENH: add a new init method for k-means
- implement the kmeans++ initialization (_kpp) as proposed by D. Arthur and S. Vassilvitski (2007)
- remove references to unsupported init methods ('uniform')

### CODE REVIEW

**Comment by rgommers** [comment]
@jeanpauphilet if you feel like addressing the random number issue we discussed above in this PR that would be great, but if not that's also fine (since it's an existing issue).

**Comment by rgommers** [comment]
@jeanpauphilet are you still interested in finishing this? The PR looks useful, but there are a number of open comments.

**Comment by perimosocordiae** [comment]
Needs a rebase on master.

**Comment by rgommers** [comment]
updated in gh-9037, so closing this now to keep the open PR list manageable.

**Pull request closed without merging**
