### PR TITLE
Removes unused variable

### PR DESCRIPTION
**Pull request by Lv101Magikarp**
Removes unused variable 'i' in evaluate_spline()

### CODE REVIEW

**Comment by ilayn** [comment]
It seems like that `i` should be `ip, jp` for the loop variables below

**Comment by Lv101Magikarp** [comment]
> It seems like that `i` should be `ip, jp` for the loop variables below

Yes, which are already declared just above at line `118`

**Comment by ilayn** [comment]
My bad. Sorry for the noise

**Comment by Lv101Magikarp** [comment]
> My bad. Sorry for the noise

No problem!

**Comment by ev-br** [comment]
Look good, CI failures are not related. Thanks @Lv101Magikarp

**Pull request merged**
