### PR TITLE
MAINT: special: Move Faddeeva into xsf

### PR DESCRIPTION
**Pull request by izaid**
This PR migrates all Faddeeva functions to xsf, such as `erf`, `erfi`, `dawsn`, and others. It also removes unnecessary Faddeeva wrappers and turns Faddeeva into a single header file `Faddeeva.hh` in xsf.

### CODE REVIEW

**Comment by izaid** [comment]
@steppi This is done, ready for review.

**Comment by steppi** [comment]
Thanks @izaid, looks good. To minimize the diff with what's currently in the `xsf` repo, can you make it so we only have one new header in `xsf`, `faddeeva.h`, which combines what was in `_faddeeva.cxx` and `Faddeeva.hh`?  Ideally, there wouldn't be any commits which touch both `xsf` and something in SciPy outside of `xsf` here either, but don't worry about that if it would be too much trouble to rewrite history.

**Comment by lucascolley** [comment]
> Ideally, there wouldn't be any commits which touch both xsf and something in SciPy outside of xsf here either

I did this - merry xmas! 🎄

**Review by steppi — APPROVED** [review]
Everything looks to be in order. Thanks @izaid. And thanks for cleaning up history @lucascolley. I plan to do some unholy git surgery to cherry pick https://github.com/scipy/scipy/pull/22176/commits/7488fd23502db91a6514dd389ec70050eb64f553 into the `xsf` repo, but I think it will only work if there are no commits touching both SciPy and `xsf`.

**Pull request merged**
