### PR TITLE
CI: remove pin on Jinja2

### PR DESCRIPTION
**Pull request by tupui**
Pin was added in #15868 and since #15443 it can be removed.

### CODE REVIEW

**Comment by tupui** [comment]
@rossbar seems like the issue is still there with the new version of numpydoc (1.2):

```python-traceback
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/refguide_check.py", line 46, in <module>
    from numpydoc.docscrape_sphinx import get_doc_object
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/numpydoc/docscrape_sphinx.py", line 11, in <module>
    from sphinx.jinja2glue import BuiltinTemplateLoader
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/sphinx/jinja2glue.py", line 15, in <module>
    from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, contextfunction
ImportError: cannot import name 'contextfunction' from 'jinja2' (/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by rossbar** [comment]
Okay the root issue is reported here: sphinx-doc/sphinx#10291. Jinja 3.1.X (released ~5 days ago) is incompatible with sphinx 2.X and 3.X and the failing CI jobs look like they install sphinx 2.1.

`numpydoc` still supports all the way back to sphinx 1.8 (for now) so the jinja version will be pinned there, see numpy/numpydoc#369.

**Comment by tupui** [comment]
Nice and looks like you already have a release, let's try!

**Comment by tupui** [comment]
Looks like it's working 👍

**Pull request merged**
