### PR TITLE
MAINT: Remove suppress_warnings

### PR DESCRIPTION
**Pull request by sethtroisi**
#### Reference issue

Patched on Sympy side in https://github.com/sympy/sympy/pull/18784 which was part of sympy 1.6 (released last week). Happy to wait another week, month, release to push this.

### CODE REVIEW

**Comment by ilayn** [comment]
Added the milestone so we don't forget this should we decide to add it in.

**Review by tylerjereddy — COMMENTED** [review]
CI is green apart from the ARM timeout in Travis, and the comment says we can remove the guard when the issue is resolved.

The normal point of hesitation would be that we may require a fairly bleeding-edge version of `sympy` for users to use whatever depends on this, but then `sympy` is not a mandatory dependency.

In fact, it is not even mentioned in the devdocs deps page: https://scipy.github.io/devdocs/dev/core-dev/index.html#dependencies

OTOH, we don't gain too much from the change so if it does currently cause user inconvenience may be better to delay.

Maybe @person142 can take a quick look and advise since I have less experience with `special`.

**Comment by sethtroisi** [comment]
I'm also happy to close for 3/6 months and revisit at that time

**Comment by rgommers** [comment]
Agree that the Sympy fix is a bit too recent, let's merge this right after the 1.5.x release split - there's no real upside from having it in 1.5.0, and it may resurface the warnings for users.

**Comment by sethtroisi** [comment]
@rgommers, I don't understand exactly how releasing works, but I suspect we are past the 1.5.x release split (given that head is labelled as 1.6.0 now)

**Comment by rgommers** [comment]
This LGTM now, merging. Thanks @sethtroisi 

> I don't understand exactly how releasing works, but I suspect we are past the 1.5.x release split (given that head is labelled as 1.6.0 now)

Indeed. We now have a `maintenance/1.5.x` branch that the release(s) will be made from. If there's changes in `master` that need to still go into a `1.5.x` release at some point, we backport the commits; the two branch won't ever be merged together again.

**Pull request merged**
