### PR TITLE
DOC: integrate.cubature: fix doc formatting and references issues

### PR DESCRIPTION
**Pull request by ollybritton**
Addresses @ev-br's last comments in #20930.

#### What does this implement/fix?
- Add an extra line after `::` in `cubature`'s docstring so that code blocks render correctly.
- Add references for QUADPACK and Genz-Malik cubature to `cubature` rather than just in rules.

### CODE REVIEW

**Comment by ev-br** [comment]
Close/reopen to flush CircleCI

**Comment by ev-br** [comment]
Something's going on with CircleCI, it does not proceed from building scipy to building the docs. Can you actually build the docs locally @ollybritton ?

**Comment by ollybritton** [comment]
@ev-br Yes, the docs build locally and `python dev.py smoke-docs -s integrate` passes. There is one warning which has happened every time I've built the docs (including before this PR) which is related to `np.linalg` and so I think it's unrelated:

```
/Users/olly/code/python/scipy/build-install/lib/python3.12/site-packages/scipy/signal/_ltisys.py:docstring of scipy.signal._ltisys.place_poles:125: WARNING: Exception occurred in plotting scipy-signal-place_poles-1
 from /Users/olly/code/python/scipy/doc/source/reference/generated/scipy.signal.place_poles.rst:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/scipy-dev/lib/python3.12/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
    exec(code, ns)
  File "<string>", line 46, in <module>
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/scipy-dev/lib/python3.12/site-packages/numpy/linalg/_linalg.py", line 2371, in det
    r = _umath_linalg.det(a, signature=signature)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeWarning: divide by zero encountered in det
```

But the docs output looks fine locally:

Screenshot 2024-09-12 at 09 02 39

...

Screenshot 2024-09-12 at 09 02 59

**Comment by ev-br** [comment]
Okay, docs build fine locally for me, too. Let's assume it was a temporary CircleCI glitch and land this. If it causes problems in main, will revert.
Thanks @ollybritton !

**Pull request merged**
