### PR TITLE
Move lil_matrix storage to array.array for compatible data types.

### PR DESCRIPTION
**Pull request by maciejkula**
This PR changes the underlying storage of `lil_matrix` from Python `list` to `array.array` objects for compatible data types. For remaining data types, I continue to use plain lists.

This drastically reduces the amount of memory required for constructing a large `lil_matrix`.

With the current implementation:

```
Line #    Mem usage    Increment   Line Contents                
================================================                
     6     28.4 MiB      0.0 MiB   @profile                     
     7                             def example():               
     8                                                          
     9     28.4 MiB      0.0 MiB       shape = 1000, 1000       
    10                                                          
    11     36.0 MiB      7.6 MiB       arr = np.ones(shape)     
    12    104.0 MiB     67.9 MiB       mat = sp.lil_matrix(arr) 
```

Using arrays:

```
Line #    Mem usage    Increment   Line Contents               
================================================               
     6                             @profile                    
     7                             def example():              
     8    26.078 MB     0.000 MB                               
     9    26.078 MB     0.000 MB       shape = 1000, 1000      
    10                                                         
    11    33.723 MB     7.645 MB       arr = np.ones(shape)    
    12    57.246 MB    23.523 MB       mat = sp.lil_matrix(arr)
```

Since `list` and `array.array` support the same operations, this change should not break sensible user code that touches the `rows` and `data` attributes.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @maciejkula. Profiling results look good. 

Immediate question that your last sentence invites: what non/less-sensible user code might break?

**Comment by maciejkula** [comment]
The `+` operator between `list` and `array` is not supported, for instance (though `.extend` is). I can't see the reason for doing that, though.

**Comment by pv** [comment]
I'm fairly sure there's 3rd party code out there that inserts lists to the .data directly, and will be broken by this. I would prefer not to change the data format.
.
A better approach for performance would be to add a new matrix class with an appropriate opaque data format, and without python data structures.

**Comment by maciejkula** [comment]
If it does `matrix.data[i] = [1, 2, 3]`, it should continue to work (no code depends on the type of the `.data` elements). If it inserts into an existing row, you are correct in that it will fail. Do you have a particular 3rd party library in mind?

**Comment by pv** [comment]
the c_array.array declarations probably prevent it from working

**Comment by maciejkula** [comment]
That'd be correct for `.rows`. Do you have an example of the code that we want to keep from breaking?

If that's a priority I could have two code paths, one for lists and one for arrays, so that both are always handled (but arrays are preferentially used by the `lil_matrix` code).

**Comment by argriffing** [comment]
> I'm fairly sure there's 3rd party code out there that inserts lists to the .data directly, and will be broken by this.

Would it be worth adding a unit test for this?  Maybe even in a separate PR?

**Comment by maciejkula** [comment]
I'm working on a better PR, closing this in the meantime.

**Pull request closed without merging**
