### PR TITLE
DOC: Clarify documenation on atol/rtol

### PR DESCRIPTION
**Pull request by nbelakovski**
Contrasted atol to rtol and provided explicit instructions for how to
achieve desired atol or rtol.

#### Reference issue
N/A

#### What does this implement/fix?
Updates documentation for atol/rtol in the integrate package to hopefully bring some clarity. The existing documentation didn't clarify what atol was for and did not give usable guidance on how to use rtol/atol.

#### Additional information
There are surely lots of different ways to word this section and some will make more sense than others. Happy to receive feedback on the content and change as necessary.

Most things in the checklist are not relevant since this is documentation only. I have checked that documentation renders properly via the circleCI build_docs_artifact

### CODE REVIEW

**Comment by nbelakovski** [comment]
bump for visibility, should be a quick win

**Comment by nbelakovski** [comment]
bumping @tylerjereddy

**Comment by tylerjereddy** [comment]
For `integrate`, we can maybe ping @nmayorov

**Comment by nbelakovski** [comment]
Ping @tylerjereddy @nmayorov . Sorry for the pings, I hope I'm not being annoying, I just feel that the documentation as it stands isn't particularly clear and could use some improvement. Thanks.

**Review by Patol75 — APPROVED** [review]
This looks like a welcomed addition to me as it explains in simple words the interplay between `rtol` and `atol` values, and it replaces a sentence on `atol` which was, at best, obscure for the newcomer.

**Comment by nbelakovski** [comment]
@tylerjereddy @nmayorov @Patol75 monthly ping/bump

**Comment by nmayorov** [comment]
@nbelakovski, my bad that I haven't checked it for so long. I find your description precise and more useful.

**Comment by nbelakovski** [comment]
Thank you!

**Pull request merged**
