### PR TITLE
ENH: improves rankdata algorithm

### PR DESCRIPTION
**Pull request by behzadnouri**
- avoids type casting as in the current implementation
- adds supports for object & string arrays
- returns more natural integer ranks as opposed to floats (except for
  'average' method)

on master:

``` python
>>> sp.__version__
'0.17.0.dev0+bb3c6b1'
>>> a = np.array(['xyz', 'abc', 'efg'])
>>> a.dtype
dtype('<U3')
>>> rankdata(a)
ValueError: could not convert string to float: 'xyz'

>>> a = np.array(['test', 'with', 'objects'], dtype='O')
>>> rankdata(a)
ValueError: could not convert string to float: 'objects'
```

on branch:

``` python
>>> a = np.array(['xyz', 'abc', 'efg'])
>>> a.dtype
dtype('<U3')
>>> rankdata(a)
array([ 3.,  1.,  2.])

>>> a = np.array(['test', 'with', 'objects'], dtype='O')
>>> rankdata(a)
array([ 2.,  3.,  1.])
```

### CODE REVIEW

**Comment by jaimefrio** [comment]
Nice simplification!

Couldn't you do away with the couple of loops where Cython serves some purpose and turn everything into pure Python? I think if you keep the sorted array around (and perhaps sort with `kind='mergesort'` for `'ordinal'`) it would be possible. Something very similar to the `count` array generation can be found in [`np.unique`](https://github.com/numpy/numpy/blob/v1.9.1/numpy/lib/arraysetops.py#L96).

**Comment by behzadnouri** [comment]
the 2nd commit does a python only implementation. but one of the travis builds fails because it  is running numpy 1.6 but `return_counts` was added later to `np.unique`

**Comment by rgommers** [comment]
This is the second time in a short while that we could have used ``return_counts``. If it helps, you can put a copy of the numpy implementation of ``unique`` in ``scipy/_lib/_numpy_compat.py``

**Comment by behzadnouri** [comment]
@rgommers copied `np.unique` to `_numpy_compat.py`

**Comment by ev-br** [comment]
Can you comment on performance characteristics of this vs master please.

**Comment by behzadnouri** [comment]
@ev-br 

on master:
```python
In [5]: np.random.seed(2718281)

In [6]: n = 1 << 20

In [7]: a = np.random.choice(np.random.randn(n // 100), n)

In [8]: for method in 'average', 'min', 'max', 'dense', 'ordinal':
   ...:         print(method.ljust(7), end=': ')
   ...:         %timeit -n 3 rankdata(a)
   ...:     

average: 3 loops, best of 3: 217 ms per loop
min    : 3 loops, best of 3: 217 ms per loop
max    : 3 loops, best of 3: 217 ms per loop
dense  : 3 loops, best of 3: 217 ms per loop
ordinal: 3 loops, best of 3: 217 ms per loop
```

on branch:
```python
In [8]: for method in 'average', 'min', 'max', 'dense', 'ordinal':
   ...:         print(method.ljust(7), end=': ')
   ...:         %timeit -n 3 rankdata(a)
   ...:     

average: 3 loops, best of 3: 272 ms per loop
min    : 3 loops, best of 3: 273 ms per loop
max    : 3 loops, best of 3: 273 ms per loop
dense  : 3 loops, best of 3: 273 ms per loop
ordinal: 3 loops, best of 3: 273 ms per loop
```

**Comment by larsmans** [comment]
I'm inclined to merge this, but the promised changes to `_numpy_compat.py` are missing from the PR. @behzadnouri could you push them? They'll be relevant for #5307 as well, which is a third use case for `unique` with `return_counts`.

**Comment by behzadnouri** [comment]
@larsmans i changed the code so that it does not have a dependency on `np.unique` and then squashed the commits into one. 

commit which added `np.unique` to `_numpy_compay.py` was: https://github.com/behzadnouri/scipy/commit/01b6a12f2bd4809857526b8b923ed3f05e4bfb8a

commit which removed  `np.unique` dependency was:  https://github.com/behzadnouri/scipy/commit/1bbf3965f99ba70ba3f00de23b6304d02c887bc7

**Comment by larsmans** [comment]
Cool, thanks. As I said, +1 for merging this, even if `rankdata` gets a bit slower.

**Comment by larsmans** [comment]
(Where I said #5307 I meant #5303.)

**Comment by behzadnouri** [comment]
by mistake, all timings were from `average` method; this is the correct one:

on master:

```python
In [5]: n = 1 << 20

In [6]: np.random.seed(2718281)

In [7]: a = np.random.choice(np.random.randn(n // 10), n)

In [8]: for method in 'dense', 'min', 'max', 'ordinal', 'average':
   ...:         print('{:7}: '.format(method), end='')
   ...:         %timeit -n 5 rankdata(a, method)
   ...:
dense  : 5 loops, best of 3: 238 ms per loop
min    : 5 loops, best of 3: 238 ms per loop
max    : 5 loops, best of 3: 238 ms per loop
ordinal: 5 loops, best of 3: 273 ms per loop
average: 5 loops, best of 3: 238 ms per loop
```

on branch:

```python
dense  : 5 loops, best of 3: 264 ms per loop
min    : 5 loops, best of 3: 272 ms per loop
max    : 5 loops, best of 3: 260 ms per loop
ordinal: 5 loops, best of 3: 276 ms per loop
average: 5 loops, best of 3: 294 ms per loop
```

**Comment by ev-br** [comment]
Can you also add your examples with strings and objects as a test? (I know, it's late in the process, but still). Then I think this is good to go in, we can probably live with the timings as is.

**Comment by behzadnouri** [comment]
@ev-br added tests for object and strings

**Comment by ev-br** [comment]
LGTM now, merging. thank you @behzadnouri, all

**Pull request merged**
