### PR TITLE
The plt.show () command is not inserted

### PR DESCRIPTION
**Pull request by mohmmadd**

### CODE REVIEW

**Comment by larsoner** [comment]
Can you paste a link to the `CircleCI: build_docs` artifact for this function once it's complete? You might need to login to CircleCI (using GitHub credentials) to be able to see the "Artifacts" link, where the doc build for this PR will live once it finished.

**Comment by ilayn** [comment]
Currently none of the plotting examples have `plt.show()` but it is generated in the documentation http://scipy.github.io/devdocs/generated/scipy.signal.windows.general_cosine.html#scipy.signal.windows.general_cosine

**Comment by mohmmadd** [comment]
@larsoner https://circleci.com/gh/scipy/scipy/6904#artifacts/containers/0

**Comment by larsoner** [comment]
Thanks @mohmmadd

**Pull request merged**
