### PR TITLE
DOC: add a generative art example to the scipy.spatial tutorial.

### PR DESCRIPTION
**Pull request by rgommers**
Creates a Mandala diagram with a very interesting geometrical pattern:

image

A big thank you to @audreyr and @CarlosFocil for the original code on which this is based.

### CODE REVIEW

**Comment by ev-br** [comment]
Nice!

**Comment by ilayn** [comment]
Very nice indeed.

**Review by larsoner — APPROVED** [review]

**Review by tylerjereddy — APPROVED** [review]
Thanks Ralf

**Comment by WarrenWeckesser** [comment]
Cool.  Now let's bring it to life...

animandala

The code is in a [gist](https://gist.github.com/WarrenWeckesser/76fb975d9cbe9dd7373fb840ff96888e).

**Comment by rgommers** [comment]
Very nice @WarrenWeckesser!

**Pull request merged**
