### PR TITLE
CI: try running python 3.6-nightly

### PR DESCRIPTION
**Pull request by ev-br**
Let's peek into the future.

### CODE REVIEW

**Comment by rgommers** [comment]
the future is unhappy

**Comment by ev-br** [comment]
The future looks brighter than it could though:

Apart from an incredible amount of noise from importlib (which can be runtests or nose?), the failures are only in sparse and they all look reasonably similar:

```
======================================================================
ERROR: test_base.Test64Bit.test_no_64(<class 'test_base.TestLIL'>, 'test_fancy_assign_empty')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "<decorator-gen-24>", line 2, in check
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 146, in deco
    return func(*a, **kw)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 4379, in check
    getattr(instance, method_name)()
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2818, in test_fancy_assign_empty
    A[K] = 42
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.Test64Bit.test_resiliency_all_32(<class 'test_base.TestLIL'>, 'test_fancy_assign_empty')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "<decorator-gen-26>", line 2, in check
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 146, in deco
    return func(*a, **kw)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 4379, in check
    getattr(instance, method_name)()
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2818, in test_fancy_assign_empty
    A[K] = 42
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.Test64Bit.test_resiliency_all_64(<class 'test_base.TestLIL'>, 'test_fancy_assign_empty')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "<decorator-gen-28>", line 2, in check
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 146, in deco
    return func(*a, **kw)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 4379, in check
    getattr(instance, method_name)()
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2818, in test_fancy_assign_empty
    A[K] = 42
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.Test64Bit.test_resiliency_limit_10(<class 'test_base.TestLIL'>, 'test_fancy_assign_empty')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "<decorator-gen-30>", line 2, in check
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 146, in deco
    return func(*a, **kw)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 4379, in check
    getattr(instance, method_name)()
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2818, in test_fancy_assign_empty
    A[K] = 42
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.Test64Bit.test_resiliency_random(<class 'test_base.TestLIL'>, 'test_fancy_assign_empty')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "<decorator-gen-32>", line 2, in check
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 146, in deco
    return func(*a, **kw)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 4379, in check
    getattr(instance, method_name)()
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2818, in test_fancy_assign_empty
    A[K] = 42
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.TestLIL.test_fancy_assign_empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2818, in test_fancy_assign_empty
    A[K] = 42
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.TestLIL.test_fancy_assignment_dtypes(dtype('int64'),)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2755, in check
    A[[0,1],[0,1]] = dtype.type(1)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 592, in scipy.sparse._csparsetools._lil_fancy_set_int64_int64 (scipy/sparse/_csparsetools.c:9604)
ValueError: Unexpected format string character: 'q'
======================================================================
ERROR: test_base.TestLIL.test_fancy_assignment_dtypes(dtype('uint64'),)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_base.py", line 2755, in check
    A[[0,1],[0,1]] = dtype.type(1)
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.6/site-packages/scipy/sparse/lil.py", line 377, in __setitem__
    i, j, x)
  File "scipy/sparse/_csparsetools.pyx", line 231, in scipy.sparse._csparsetools.lil_fancy_set (scipy/sparse/_csparsetools.c:4513)
  File "scipy/sparse/_csparsetools.pyx", line 608, in scipy.sparse._csparsetools._lil_fancy_set_int64_uint64 (scipy/sparse/_csparsetools.c:9829)
ValueError: Unexpected format string character: 'Q'
----------------------------------------------------------------------
```

**Comment by ev-br** [comment]
OK, the traceback points to the last line in the definition of 

```
def _lil_fancy_set_int64_uint64(cnp.npy_intp M, cnp.npy_intp N,
                                         object[:] rows,
                                         object[:] data,
                                         cnp.npy_int64[:,:] i_idx,
                                         cnp.npy_int64[:,:] j_idx,
                                         cnp.npy_uint64[:,:] values):     # <<< line 592
```

And the character code `'q'` shows up somewhere in cython's numpy header
https://github.com/cython/cython/blob/master/Cython/Includes/numpy/__init__.pxd#L834

Whether it's a bug in python 3.6 alpha, or numpy or cython's typed memoryviews, I'm way out of my depth.

**Comment by person142** [comment]
The 3.5 failure is I think unrelated (https://github.com/scipy/scipy/issues/6696), so the future looks bright!

**Comment by person142** [comment]
All green now. :-)

**Comment by rgommers** [comment]
In it goes then. Thanks @ev-br.

**Pull request merged**
