### PR TITLE
ENH: Use double precision numbers in specfun.f

### PR DESCRIPTION
**Pull request by Pranavchiku**
#### What does this implement/fix?
With this PR, I am trying to use double-precision numbers in `specfun.f` file of `scipy/special/` package. This may help in achieving better precision.

### CODE REVIEW

**Comment by rkern** [comment]
We'd need a demonstration that it _does_ help in concrete scenarios. It ought to affect the unit tests in some way, at least in that you could tighten up the tolerances that are tested. Otherwise, I'd leave the code alone.

**Comment by steppi** [comment]
These functions are using Fortran's [Implicit](https://www.cita.utoronto.ca/~merz/intel_f10b/main_for/mergedProjects/lref_for/source_files/rfimpli.htm) construct, so I think the variables in question should already be using double precision.

For instance, in the snippet below

```F77
        IMPLICIT DOUBLE PRECISION (A-H,O-Z)
        DIMENSION ZO(NT),RT0(8)
        RT0(1)=2.84891
        RT0(2)=5.02622
        RT0(3)=1.71854
        RT0(4)=3.91467
        RT0(5)=6.03871
        RT0(6)=3.77268
        RT0(7)=2.66584
        RT0(8)=4.93181
```

All variable names that begin with a letter from A to H or from O to Z will implicitly be a double without having to add the `D0` at the end.

**Comment by Pranavchiku** [comment]
If I use the following code:
```fortran
subroutine klvnzo_()
implicit double precision (a-h,o-z)
rt=4.93181
print *, "rt = ", rt
return
end

program main
   call klvnzo_()
end program
```

> GFortran

```console
% gfortran a.f90 && ./a.out
 rt =    4.9318099021911621     
```


But if I add `D0` at end, I get more precision.

```fortran
subroutine klvnzo_()
implicit double precision (a-h,o-z)
rt=4.93181d0
print *, "rt = ", rt
return
end

program main
   call klvnzo_()
end program
```

> GFortran

```console
$ gfortran a.f90 && ./a.out
 rt =    4.9318099999999996     
```

**Comment by rkern** [comment]
Okay, I followed the link to the associated `lfortran` issue; that's sufficient to prove the case for me. There are also [other versions of this code](https://people.sc.fsu.edu/~jburkardt/f77_src/special_functions/special_functions.f) that more consistently use `double precision` literals in these places.

I'm curious if this only changes behavior on `lfortran`, though.

**Comment by Pranavchiku** [comment]
Thank you @rkern, you may wish to take a look at typical single/double precision corruption in Fortran: https://www.fortran90.org/src/gotchas.html#floating-point-numbers. 

> I'm curious if this only changes behavior on lfortran, though.

Indeed. If you see https://github.com/lfortran/lfortran/issues/2117#issuecomment-1684807249, here you may see that for the case 1 int the above comment, LFortran treats it as double precision implicitly and provides `4.93180999999999958e+00` unlike gfortran which gives `4.9318099021911621`.

**Comment by steppi** [comment]
I see, yeah. For some compilers

```F77
subroutine klvnzo_()
implicit double precision (a-h,o-z)
rt=4.93181
print *, "rt = ", rt
return
end

program main
   call klvnzo_()
end program
```

`rt=4.93181` is setting `rt` to the nearest `float` value to `4.93181` and then casting to double, but `rt=493181d0` will set `rt` directly to the nearest `double` value to `4.93181`. So you get two results which are equivalent in `float` precision but very different in `double` precision.

Since this is actually causing problems for you downstream, we should try to get the fix in asap. Thanks @Pranavchiku.

**Review by steppi — APPROVED** [review]
I think this looks good and can go in. At a glance I noticed each of `JDZO` and `CVQL` still doesn't have literals explicitly marked as float, but the former isn't wrapped by SciPy and in the latter case the values are integers and will be the same in both float and double precision, so I think it's fine to leave those as is.

Thanks @Pranavchiku

**Comment by Pranavchiku** [comment]
Thanks @steppi! There will be many more places I think, do let me know if you wish me to update or test anything related to same :)

**Comment by steppi** [comment]
> Thanks @steppi! There will be many more places I think, do let me know if you wish me to update or test anything related to same :)

Thanks. No need to look into anything else like this at the moment, but I'd be happy to help if you run into any more issues that impact your work.

**Comment by certik** [comment]
@steppi, @rkern thank you!

I have a suspicion that this is going to be coming up quite often. We should probably enable the GFortran behavior with a compiler option.

For code like this:
```
RT0(8)=4.93181
```
One can argue that since the constant is only known to single precision, then rounding it to the closest single precision number and only then casting to double is as accurate as just padding it with zeros.

However, for code like this one:
```diff
--- a/scipy/special/specfun/specfun.f
+++ b/scipy/special/specfun/specfun.f
@@ -9185,7 +9185,7 @@ C
 60            CONTINUE
 65         R=-0.25D0*X*X2
            GS=1.5D0
-           HER=1.5D0*R-BER/X-(DLOG(X/2.D0)+EL)*DER+0.25*PI*DEI
+           HER=1.5D0*R-BER/X-(DLOG(X/2.D0)+EL)*DER+0.25d0*PI*DEI
            DO 70 M=1,60
               R=-0.25D0*R/M/(M+1.0D0)/(2.0D0*M+1.0D0)**2*X4
               GS=GS+1.0D0/(2*M+1.0D0)+1.0D0/(2*M+2.0D0)
```
The 0.25 and 1.5 is clearly meant as 1/4 and 3/2. If they were incorrect after 1e-6, it seems that would not be good. Ironically, I believe 0.25 is represented exactly in floating point, so I guess it doesn't matter in this case.

In practice the issue becomes when you enable all optimizations and the compiler starts assuming that you really want single precision, and so it starts "optimizing" your code, reducing accuracy. 

The other issue is the classic:
```fortran
integer, parameter :: dp = kind(0.d0)
real(dp) :: pi = 3.1415926535897932384626
print *, pi
print *, "Accuracy:", abs(pi - 3.1415926535897932384626_dp)
end
```
Where you only get ~1e-7 accuracy with GFortran:
```
$ gfortran a.f90 && ./a.out 
   3.1415927410125732     
 Accuracy:   8.7422780126189537E-008
$ lfortran a.f90 
3.14159265358979312e+00
Accuracy: 0.00000000000000000e+00
```
It's a common gotcha that every new Fortran programmer hits and gets burned by.

One of our goal with LFortran is to eliminate all these bugs. I think the way to do it is to give a warning message for all the cases above, and in the warning message suggest to write the constant as double precision. That makes the code more "accurate" in all compilers.

We can add a compiler option to control the behavior.

Regarding what to do by default, I think LFortran should treat these constants as double precision by default. If you want single precision, you can always specify it in the code explicitly (typically with `3.1415926535897932384626_sp`), or you can ask for it with a compiler option (which we might later use for SciPy, to get bit to bit exact answers with GFortran).

Thanks again for being flexible here and working with us. We are very close to get `specfun.f` 100% working in SciPy with LFortran. That's 12.3K lines of Fortran, passing all the tests, unmodified. No small feat! Thank you @Pranavchiku, great progress. The rest of the SciPy packages will follow, the first one is always the hardest to get it to 100%.

**Pull request merged**
