### PR TITLE
MAINT: SciPy 1.11.3 backports/prep

### PR DESCRIPTION
**Pull request by tylerjereddy**
Prep for SciPy `1.11.3` now that NumPy `1.26.0` stable is out and Python `3.12` stable is imminent per gh-19274. `1.11.2` does support Python `3.12` already, but was built with a beta version of NumPy in that scenario.

Backports Included so far:

1. gh-17633
2. gh-18913
3. gh-18956
4. gh-19076
5. gh-19111
6. gh-19123
7. gh-19135
8. gh-19139
9. gh-19156
10. gh-19208
11. gh-18784
12. gh-19200
13. gh-19199
14. gh-19280
15. gh-19299
16. gh-19286
17. gh-19290
18. gh-18924

Possible TODOs:

- [x] typically need to patch a few things that show up in CI on the maintenance branch 
- [x] locally from `python dev.py lint` I noticed: `scipy/scipy/sparse/csgraph/_traversal.pyx:187:5: 'node_list' defined but unused (try prefixing with underscore?)`
- [x] locally from `python dev.py doc -j 32` I noticed a single warning: `scipy/stats/_mstats_basic.py:docstring of scipy.stats._mstats_basic.argstoarray:22: WARNING: py:obj reference target not found: numpy.ma.row_stack`
- [x] perhaps check `pip install -v .` on a Python `3.12` release candidate locally on this branch before probing wheel builds
- [x] any missing backports folks want/need?
- [x] probe the full set of wheel builds in CI on this PR before merging (likely more efficient than finding problems after starting release process proper)
- [x] do we want to backport gh-18924 so that `dev.py` works with `3.12` on this branch?
- [ ] do we want a Python 3.12 (temporarily RC) CI job on this maintenance branch?

### CODE REVIEW

**Comment by mdhaber** [comment]
> any missing backports folks want/need?

Can we get gh-18782 in here?
It would also be good to get gh-19199 in. @tirthasheshpatel (or anyone else) do you have a moment to review that (one line fix)?

**Comment by tylerjereddy** [comment]
Added a few more fixes based on CI failures, and a few more backport requests (only 1 from Matt was merged at the time of writing), and updated the original comment accordingly. My decision to pin `meson-python` and `pythran` in the `gcc-8` GHA job may be debatable, I just went with the conservative adjustment of minimizing changes to `pyproject.toml`/wheel builds, but if those bumps to latest stable release series are safe they could also be considered I suppose.

**Comment by mdhaber** [comment]
Oops. I just merged gh-19280. Would you like me to submit a PR against this branch adding that?

**Comment by tylerjereddy** [comment]
Nah, I can cherry-pick, I'm sure there will be more of that to do still.

**Comment by tylerjereddy** [comment]
I think I'm up-to-date with all requests so far, and I've updated the original PR comment above accordingly. I had to slightly modify Matt's test in `test_zeros.py` because the imported namespace status of that module has drafted from `main`, but it was a minor shim.

I've been keeping the release notes updated as I go, which has the drawback of polluting the commit history a bit, but anyway not a huge deal.

**Comment by tylerjereddy** [comment]
I checked that with `Python 3.12.0rc3` on x86_64 Linux we can pass all tests after `python -m pip install -v .`

I did note two things to consider, which I've added to the checklist above--`dev.py` doesn't work with `3.12.0` on this branch because we haven't backported the fix for that. On the other hand, the case for using that developer tool on the maintenance branch may be less clear I suppose.

I also added a checklist item for `3.12` CI on the maintenance branch--seems optional, perhaps potentially useful if we get a few bug reports when `3.12.0` final is out, which is probably when a larger user base will really start probing things. But not sure it is worth the work upfront.

I'll leave this PR open for a day or two more before starting to probe the wheel builds with i.e., the cirrus credits Ralf added, to give folks a change to review/suggest more backports, etc.

**Comment by rgommers** [comment]
> do we want to backport gh-18924 so that `dev.py` works with `3.12` on this branch?

Seems like a good idea to me, and can't really hurt.

> do we want a Python 3.12 (temporarily RC) CI job on this maintenance branch?

Wheel builds run the full test suite, so it isn't necessary - but if you prefer to add one, that's fine too I think.

**Comment by h-vetinari** [comment]
https://github.com/scipy/scipy/pull/19286 would be good to have for 1.11.3 as well. :)

**Comment by rgommers** [comment]
> #19286 would be good to have for 1.11.3 as well. :)

Agreed - and I marked gh-19290 for backport as well; it'll be useful to not have to carry patches for those things in conda-forge.

**Comment by rgommers** [comment]
@tylerjereddy here are my proposed updates to `pyproject.toml`: https://github.com/rgommers/scipy/commit/9ae4cc77936721368639f3597aa7ce4580f4875c. Would you like to take them over in this PR, or should I open a separate one?

**Comment by tylerjereddy** [comment]
I can just cherry-pick it over if you keep that branch alive, I've got a list of 3 other backports to include already in any case.

**Comment by tylerjereddy** [comment]
I've updated the PR/original comment above--there are 18 backports listed up there and that matches 18 merged backport-labelled PRs on GitHub at the time of writing. `python dev.py test -j 32` now works on Python `3.12.0rc3` locally on x86_64 Linux, doc build passed locally with Python 3.9.

If the regular CI remains green, and I don't see any more backport requests, ~20 is probably enough to think about releasing then, so I'd probably try wheel builds on this PR/branch, and if they succeed, then proceed with the release process in the next day or two.

**Comment by tylerjereddy** [comment]
The job `Windows tests / cp311 (build sdist + wheel), full, no pythran (pull_request) ` seems to be hanging on the test stage, but the regular CI had already passed before I pushed in the empty commit to test wheel builds.

The wheel build/test jobs all passed. One thing I don't like is that there still seem to be complaints about `least_squares` stuff in `optimize` per gh-19309, but for that particular issue we get a pretty slow trickle of different complains each time we try to patch it, so I'm not convinced it will be resolved decisively soon anyway.

I'll proceed with a merge here, and probably get the rel process started. I did one final read through the diff--it was mostly what I expected, perhaps my version pins in CI could be reverted with the latest `pyproject.toml` changes, but those were only in a few places with non-isolated builds anyway.

**Pull request merged**
