### PR TITLE
Travis CI: pip install scipy fails on Python 3.8 beta 4

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by rgommers** [comment]
You can install numpy and scipy from master (or maintenance/1.17.x for numpy, maintenance/1.13.x for scipy) for Python 3.8. Don't expect releases on PyPI to work for a Python version that is not yet released. We don't have a magic ball to anticipate future changes to CPython.....

I'll close this, since there's nothing to do at the moment. If you can't install from source please open a new issue.

**Comment by cclauss** [comment]
Understood.  This is the last beta so there is more pressure to test packages that depend on scipy.   Does this __.travis.yml__ file do something special to _force_ an install from source because on two other repos __pip install scipy__ fails on Python 3.8 but on this repo it succeeds.

**Comment by rgommers** [comment]
>  **pip install scipy** on Python 3.8 succeeds on this repo but on two other repos, it fails.

nothing special, it's just that if we do `pip install .` here (note the `.`) it builds from master (that's the point of CI right?), while if you do `pip install scipy` somewhere else it will grab the latest release from PyPI. In another repo you could do `pip install https://github.com/scipy/scipy/archive/master.zip` and that will work.

**Comment by rgommers** [comment]
It's anyway a good idea probably to test against the SciPy master branch if your package depends on SciPy. That way if we happen to break anything for you, you'll see it before we make a new release of SciPy and it can be addressed in time.

**Pull request closed without merging**
