### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### scipy/scipy now has a Chat Room on Gitter

@mdhaber has just created a chat room. You can visit it here: [https://gitter.im/scipy/scipy-sprint](https://gitter.im/scipy/scipy-sprint?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/scipy/scipy-sprint?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://gitlab.com/gitlab-org/gitter/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by rgommers** [comment]
This was for the sprint, which was very good but is now finishing. That leaves the discussion - do we want a Gitter channel (e.g. for more real-time scipy-dev or core team discussions)?

**Comment by andyfaff** [comment]
I think it's important to have a canonical location to get help/discuss issues.

For example, I subscribe to the scipy and scipy-dev mailing lists, but we regularly get GH issues being created that are help problems rather than real bugs, which would've been better directed towards one of the mailing lists. Sometimes the dialogue mentions that they tried to post the issues to stackoverflow (or was it stackexchange), but had no luck. At this point I think to myself, why didn't they try using the mailing list.

I wouldn't like to have to monitor for communications in more than one place.

**Comment by tylerjereddy** [comment]
> I wouldn't like to have to monitor for communications in more than one place.

I think I agree with that--I struggle as it is, and many of us have to monitor Slack & stuff too these days.

**Comment by perimosocordiae** [comment]
I find that mailing lists can be pretty daunting to new users (of scipy, or of mailing lists in general) and that chat-based systems are often more welcoming.

Maybe we can get a few core devs to volunteer to hang out in the gitter channel and field questions from time to time? (I think we do something similar with the #scipy IRC channel?)

**Comment by rgommers** [comment]
Two thoughts:

1. We really should redirect user help questions to Stackoverflow, that's way more effective (and searchable).
2. I do think that @perimosocordiae has a point, mailing lists can be intimidating. If we can dedicate the Gitter channel to SciPy project and development related discussions, that could be quite useful. It can be mirrored to Slack to avoid having to run both. I'd want to hang out on such a channel regularly.

**Comment by ilayn** [comment]
> I find that mailing lists can be pretty daunting to new users (of scipy, or of mailing lists in general) and that chat-based systems are often more welcoming.

+1 about the mailing lists. Outside the maintainer circles, mailing lists quite belong to the past regardless of what we think about them. Also it has a strange reply thread behavior. Personally I always think that everyone talks past each other when things get a bit convoluted, maybe that's because I read it from gmail directly and can't see the thread tree. 

Matplotlib folks are quite helpful on Gitter, @tacaswell can chime in about the extra effort.

**Comment by tacaswell** [comment]
For Matplotlib we are pretty happy with gitter for 'prompt'/transient communication.  It has a low barrier to entry and is open-by-default.

Contrary to @dashohoxha we see more user support conversion from "random" users than we see discussion between existing devs (as we tend to communicate in GH issues or the mailing list).

I am also told that there is an active matplotlib IRC channel but I do not hang out there...

I have some concerns about pushing people to SO explicitly as the conversation there can quickly become toxic and we have minimal control over what goes on there.

**Comment by rgommers** [comment]
> I have some concerns about pushing people to SO explicitly as the conversation there can quickly become toxic and we have minimal control over what goes on there.

interesting. I've never seen this. From my point of view SO has been a life saver; it takes a major load off the maintainers, because the SO system incentivizes other users to answer questions. If even 10% of those questions would be filed as issues, that would be a massive problem (there are over 62,000 questions tagged with numpy right now and over 14,000 tagged with scipy).

**Comment by tupui** [comment]
Closing this PR for now as we moved to Slack and Discord.

**Pull request closed without merging**
