### PR TITLE
DOC: add example for scipy.io.loadmat

### PR DESCRIPTION
**Pull request by matthew-brett**
Add example in loadmat docstring.

### CODE REVIEW

**Review by carrdelling — APPROVED** [review]
:+1: Looks good to me

**Comment by ilayn** [comment]
I also think this is good but the file name and folder is a bit too specific I think for quick lookup. Could we use something more common like something in the current user directory and with a file name `test.mat`?

**Comment by matthew-brett** [comment]
I was trying to write an example that would a) work when doctested and b) the user could run themselves to get the same result.  But you're right, that puts some extra complexity into the example.

**Comment by mikofski** [comment]
Thanks for adding this example! It looks good to me. The `scipy.io.loadmat` docs will benefit from this PR. But I wonder if there should be a few more complex examples? There are already good docs for flags `struct_as_record`, `squeeze_me`, etc. but maybe they would benefit from examples too? Like the example I posted [here on loading mat file into Python] (http://poquitopicante.blogspot.com/2014/05/loading-matlab-mat-file-into-pandas.html). I can send a patch for `scipy/io/Matlab/tests/data/teststruct_7.4_GLNX86.mat` that follows your example if you think that's helpful? Thanks again!

**Comment by matthew-brett** [comment]
More examples would be good - thanks - I will try my best to be prompt at review.

**Comment by mikofski** [comment]
OK, I sent a PR to your PR, hope that works.

**Comment by matthew-brett** [comment]
@mikofski kindly submitted a rewrite to this branch, which I have merged.  @ilayn - can you accept the inconvenience of loading the test files from the test directory?  Are you OK to merge this?

**Review by larsoner — APPROVED** [review]

**Comment by ilayn** [comment]
It reads good now in my opinion and Eric is also happy then in it goes. Thanks to all involved!

**Pull request merged**
