### PR TITLE
MAINT: filter out np.matrix PendingDeprecationWarning's in numpy >=1.15

### PR DESCRIPTION
**Pull request by rgommers**
Introduced in https://github.com/numpy/numpy/pull/10142. This chooses to simply silence all of them in `sparse/__init__.py`. Seems more straightforward than trying to do so around each use of `np.matrix` inside `sparse`.

### CODE REVIEW

**Comment by rgommers** [comment]
One test failure:
```
warning_calls = (['optimize/optimize.py:814', 'sparse/__init__.py:248'], ['__init__.py:113', 'cluster/hierarchy.py:2659', 'cluster/vq.py:138', 'cluster/vq.py:527', 'cluster/vq.py:634', 'constants/codata.py:1196', ...])

    @pytest.mark.slow
    @pytest.mark.skipif(sys.version_info < (3, 4), reason="needs Python >= 3.4")
    def test_warning_calls_filters(warning_calls):
        bad_filters, bad_stacklevels = warning_calls
    
        # There is still one missing occurrence in optimize.py,
        # this is one that should be fixed and this removed then.
        bad_filters = [item for item in bad_filters
                       if 'optimize.py' not in item]
    
        if bad_filters:
            raise AssertionError(
                "warning ignore filter should not be used, instead, use\n"
                "scipy._lib._numpy_compat.suppress_warnings (in tests only);\n"
                "found in:\n    {}".format(
>                   "\n    ".join(bad_filters)))
E           AssertionError: warning ignore filter should not be used, instead, use
E           scipy._lib._numpy_compat.suppress_warnings (in tests only);
E           found in:
E               sparse/__init__.py:248

bad_filters = ['sparse/__init__.py:248']
bad_stacklevels = ['__init__.py:113', 'cluster/hierarchy.py:2659', 'cluster/vq.py:138', 'cluster/vq.py:527', 'cluster/vq.py:634', 'constants/codata.py:1196', ...]
warning_calls = (['optimize/optimize.py:814', 'sparse/__init__.py:248'], ['__init__.py:113', 'cluster/hierarchy.py:2659', 'cluster/vq.py:138', 'cluster/vq.py:527', 'cluster/vq.py:634', 'constants/codata.py:1196', ...])

scipy/_lib/tests/test_warnings.py:101: AssertionError
```

Cannot use `suppress_warnings` here, so just change the failing test to allow this filter.

**Comment by rgommers** [comment]
green finally. since this fixes CI failures, would be good to get a quick review

**Review by larsoner — APPROVED** [review]

**Comment by larsoner** [comment]
LGTM, merging quickly to restore green to the repo.

**Comment by larsoner** [comment]
This does not actually filter out the warnings for me, changing it to `ignore:the matrix ...` does. I'll open a PR soon.

**Comment by PascalLesage** [comment]
Warning filter appreciated. Anyone planning for the day where it actually does become deprecated?

**Comment by rgommers** [comment]
> Warning filter appreciated.

Does this really still warm on master? It doesn't for me.

> Anyone planning for the day where it actually does become deprecated?

Yes, `np,matrix` will not be deprecated without a plan for how to deal with that in `scipy.sparse`.

**Pull request merged**
