### PR TITLE
DEP: Remove deprecated functions for 1.3.0

### PR DESCRIPTION
**Pull request by ilayn**
`scipy.misc` has quite a number of functions either deprecated or relocated. I have removed them and the related data, tests and cleaned up docstrings. Also removed the `scipy.ndimage.imread` function as it was an alias with PIL dependency and being the only function in `ndimage.io.py`, file is also removed. 

Let me know if there are other deprecations in the pipeline that I forgot.

### CODE REVIEW

**Comment by ev-br** [comment]
(There's also a bunch of deprecated stuff in `interpolate`.) 

I actually wonder if we should merge this just after branching 1.2.0, so that it lands in 1.3.0 instead. Maybe a year from 1.0.0 is a little too fast for some of these. Also run this through the mailing list to probe waters?

**Comment by ilayn** [comment]
> I actually wonder if we should merge this just after branching 1.2.0, so that it lands in 1.3.0 instead. Maybe a year from 1.0.0 is a little too fast for some of these. 

1.2.0 is actually what we promised in the [current documentation](http://scipy.github.io/devdocs/misc.html). But I don't mind waiting a bit more.

> Also run this through the mailing list to probe waters?

True, I'll do that.

**Comment by rgommers** [comment]
Yes I agree, waiting one more release is probably better as this is going to affect quite a few users. The 1.2.0 in the deprecation message was my doing I think; 1.3.0 would have been better. Bumping the milestone.

**Comment by rgommers** [comment]
this needs a rebase now

**Comment by ilayn** [comment]
No problem I'll do that.

**Comment by ilayn** [comment]
Great now another doctest failure seemingly out of the blue sky 😃

**Comment by rgommers** [comment]
All green now. In it goes. Thanks @ilayn.

I'll send a message to the list too - this one will hurt a little ....

**Comment by rgommers** [comment]
> In it goes.

In a minute - just double checking the `imread`/`imsave` stuff.

**Comment by rgommers** [comment]
Okay, we decided to remove `imread` et al rather than making new wrappers in gh-7869. Users who run into this removal, see that issue.

**Comment by rgommers** [comment]
@ilayn could you also add these removals to the backwards-incompatible changes section of the 1.3.0 release notes?

**Pull request merged**
