### PR TITLE
TST: special: better test for gammainc at large arguments

### PR DESCRIPTION
**Pull request by person142**
This changes the systematic test for gammainc at large arguments to be
based on data precomputed by mpmath. This allows the test to have a
much larger range and run faster. (Note that although the previous
test at large values nominally had an upper bound of 1e100, only about
183 points were actually tested because the others raised exceptions
in mpmath.)

Since the utilities in test_mpmath are also useful in precompute
tests, they have been moved to the new file _mptestutils.py.

### CODE REVIEW

**Comment by person142** [comment]
Nobody merge this until I add tests for ``gammaincc`` too.

**Comment by person142** [comment]
Ok, I think this is ready for review now. I had hoped to have one data file for both ``gammainc`` and ``gammaincc``, but it turns out that with mpmath

- ``gammainc`` takes prohibitively long to compute when ``x > a``
- ``gammaincc`` takes prohibitively long to compute when ``x < a``,

so that didn't work out. As a result there is just a test for ``gammainc`` when ``x < a``; the hope is that these can be combined with future tests for ``gammaincc`` (which is based on the same code) to get reasonable coverage. The tolerance had to be rather large (``5e-9``) to get the test to pass, so further improvements to the asymptotic regime would be good. (Working on it.)

Finally, the function ``mpf2float`` probably deserves extra skepticism and scrutiny.

**Comment by person142** [comment]
Rebased and force-pushed.

**Comment by pv** [comment]
Thanks, looks good to me

**Pull request merged**
