### PR TITLE
DOC: Fix code of conduct formatting

### PR DESCRIPTION
**Pull request by bashtage**
Code of conduct unordered list is over indented

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Interesting that our CI isn't showing up in PRs at all at the moment for some reason.

**Comment by WarrenWeckesser** [comment]
> Interesting that our CI isn't showing up in PRs at all at the moment for some reason.

It is probably because of is https://www.githubstatus.com/incidents/nf4gcjtcsqdb

**Comment by bashtage** [comment]
Not my fail?

**Comment by rgommers** [comment]
Indeed looks like an unrelated failure. Thanks @bashtage

**Pull request merged**
