### PR TITLE
DOC: Embed method signatures of `spatial.transform.Rotation`

### LINKED ISSUE #16713: BUG/DOC: spatial: docstrings of `Rotation` methods are missing the function signature.
### Describe your issue.

The docstrings of the methods of `scipy.spatial.transform.Rotation` are missing the function signature in their first line.  See, for example, https://scipy.github.io/devdocs/reference/generated/scipy.spatial.transform.Rotation.from_euler.html, where the page shows `Rotation.from_euler()` as the signature.

These methods are implemented in Cython, so either the signature must be manually added as the first line of the docstring, or the Cython decorator or compiler directive [`embedsignature`](https://cython.readthedocs.io/en/stable/src/userguide/source_files_and_compilation.html?highlight=embedsignature#compiler-directives) should be used.

### SciPy/NumPy/Python version information

1.10.0.dev0+1555.eecd600 1.24.0.dev0+568.g606fa1fb6 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by kianelbo**
#### Reference issue
Closes #16713 

#### What does this implement/fix?
Just used [embedsignature](https://cython.readthedocs.io/en/stable/src/userguide/source_files_and_compilation.html?highlight=embedsignature#compiler-directives) decorator before `spatial.transform.Rotation` methods to have their signatures in the docs.

#### Additional information
I did not test anything.
Also my first contribution :)

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Interesting thank you @kianelbo. @jjerphan should we add this decorator to all Cython `def`? Are there drawbacks doing so? In other places we were adding the signature as the first line of the docstring.

**Comment by jjerphan** [comment]
Thanks for the heads-up, @tupui.

Indeed, from [Cython's documentation section on Compiler directives](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives)):

> 
> embedsignature (True / False)
>
>    If set to True, Cython will embed a textual copy of the call signature in the docstring of all Python visible functions and classes. Tools like IPython and epydoc can thus display the signature, which cannot otherwise be retrieved after compilation. Default is False.


Hence:

> should we add this decorator to all Cython def?

Yes.

> Are there drawbacks doing so? In other places we were adding the signature as the first line of the docstring.

I do not think there are any drawbacks of this directive. [Functions and methods declared `def` and `cdef` and `property` have their signatures automatically handled by the `EmbedSignature` when this directive has been activated](https://github.com/cython/cython/blob/master/Cython/Compiler/AutoDocTransforms.py#L173-L254). Hence, to me it makes sense to update those doc-strings to remove the signature and add a description.

**Comment by tupui** [comment]
Great thanks for confirming. It sounds like we could set this as a general option.

I will wait for the CI to finish by precaution, but the doc rendering looks way nicer now.

**Review by tupui — APPROVED** [review]

**Comment by jjerphan** [comment]
My guess is that `embedsignature` is not activated by default for backward compability and consistency: in the past, doc-strings had no particular format and were probably not propagated to tools which could inspect them.

**Comment by tupui** [comment]
Thanks again @kianelbo. If you are interested, we might have more signatures in need of this change. But maybe we should take a global approach. I don't know.

**Pull request merged**
