### PR TITLE
Doxy Typos + trivial comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Most are non-user facing. They were found using
`codespell -d -q 3 --skip="*.po,*.ts" --ignore-words=../sc-whitelist.txt` 
Whitelist consisted of:
```
amin
ans
thru
adn
twon
dum
te
iff
ot
```

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by andyfaff** [comment]
Not that I've gone through those,  but iff has a meaning, if and only if. I
wouldn't necessarily replace those.

**Comment by luzpaz** [comment]
@andyfaff 
I don't think any `iff` strings were replaced. In fact they are on the whitelist.

**Comment by andyfaff** [comment]
Sorry, my mistake.

**Comment by rgommers** [comment]
There's only a single ``iff`` in a docstring so not that important, but imho using such a word is a very poor idea. The vast majority of people that aren't from a field where it's used (mathematics mostly) will consider it a spelling error.

**Comment by rgommers** [comment]
It's probably best to get rid of the changes to ``SuperLU`` and ``ARPACK``, because those are vendored libs that we update once in a while. The rest LGTM.

**Comment by luzpaz** [comment]
@rgommers good to know. I'll resubmit the PR then without those changes.

**Comment by luzpaz** [comment]
apologies, my git-fu is inferior. I have no idea how to remove those commits from the PR.

**Comment by luzpaz** [comment]
Closing PR in favor of #8091

**Pull request closed without merging**
