### PR TITLE
MAINT: restore lost tail accuracy in genpareto.logsf

### LINKED ISSUE #5048: BUG: Upper tail accurracy lost in genpareto.logsf.
In the maintanence dcc44e2428d4a046ce3ddce9466175373a52065b the genpareto._logsf method was removed. The effect of this removal is that the  upper tail accuracy of genpareto.logsf is completely lost. It is very important to keep this accurracy when doing extreme value analysis.

Therefore I would propose to undo the removal of the _logsf method:

    def _logsf(self, x, c):
            return _lazywhere((x == x) & (c != 0), (x, c),
                lambda x, c: -special.log1p(c*x) / c,
                -x)

### PR DESCRIPTION
**Pull request by argriffing**
fixes a regression introduced in https://github.com/scipy/scipy/pull/4211
closes https://github.com/scipy/scipy/issues/5048

### CODE REVIEW

**Comment by ev-br** [comment]
I nearly hit the green button on this, but then realized I'm not sure what's the policy on backporting, and I'd defer to the release manager (I'm +1 on it, FWIW).  @rgommers

**Comment by argriffing** [comment]
I'd only added that label because backporting was mentioned in the issue https://github.com/scipy/scipy/issues/5048. I've removed it.

**Comment by ev-br** [comment]
@argriffing my comment was only meaning to mean that I'm not sure what's the best way of tracking a PR proposed for backporting, and I did not merge it on the spot to keep it more visible. I fully support the original suggestion to backport it.

**Comment by ewmoore** [comment]
You could make a PR against the the 0.16.x branch, but I don't think a policy has been decided. That decision is tracked in #4817.

**Comment by argriffing** [comment]
To avoid stalling the PR would it be better to merge this and make a new issue for backporting it?

**Comment by ev-br** [comment]
OK, reading #4817 (thanks Eric!) it seems to me that the RM preference is to keep the tag for both open and closed PRs. So merging this to master and keeping the tag sounds like the right thing to do. Merging, thanks you @argriffing

**Comment by rgommers** [comment]
backported in 154baeb

**Comment by rgommers** [comment]
This way of labeling backports works for me by the way.

**Pull request merged**
