### PR TITLE
investigating CI problems

### PR DESCRIPTION
**Pull request by lucascolley**
An attempt to reproduce https://github.com/scipy/scipy/pull/20255#issuecomment-2000393462

### CODE REVIEW

**Comment by lucascolley** [comment]
@ev-br I can't seem to reproduce any problems. What happened for you? Did all of the workflows get skipped?

**Comment by lucascolley** [comment]
Hmm - what was the exact commit message that you used? If I can't reproduce with that then who knows

**Comment by ev-br** [comment]
it was `TST: linalg: reenable gges[float32] tests`, I think.

**Comment by lucascolley** [comment]
Okay, I still can't reproduce 🤷‍♂️ let's close this but give me a shout if you have any more issues!

**Comment by lucascolley** [comment]
image

I've just witnessed the same symptoms from a commit message that doesn't have any square brackets at all. Probably just a fluke that the two happened to coincide, maybe it's just something occasionally failing on GitHub's end.

**Pull request closed without merging**
