### PR TITLE
BUG: Fixes #8158

### LINKED ISSUE #8158: BUG: romb print output requires correction
The option `show=True` results into a wrongly formatted output

### Reproducing code example:
```
x9v, h9v = np.linspace(1, 2, 9, retstep=True)  # korak h9v = 0.125 (9 vozlišč)
y9v = x9v * np.sin(x9v)
romb(y9v, dx=h9v, show=True)
```
See figure:
image

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by Tokixix**
Hello!
I've created simple commit  repairing output formatting of "romb" method in Integrate module.
Fixes #8158

### CODE REVIEW

**Comment by Tokixix** [comment]
Can't understand the reason of this fail...

**Comment by andyfaff** [comment]
It looks like the test fail on Appveyor is unrelated.

**Comment by andyfaff** [comment]
I've verified that the correct formatting is produced.

**Comment by Tokixix** [comment]
@andyfaff Thank You for verifying and merging!

**Pull request merged**
