### PR TITLE
CI: numpy 1.9.1 -> 1.10.1

### PR DESCRIPTION
**Pull request by argriffing**
I just want to see what this does...

### CODE REVIEW

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/5374 :-)

**Comment by ev-br** [comment]
I wonder how does 1.10.2rc

**Comment by argriffing** [comment]
Ugh, sorry..

> I wonder how does 1.10.2rc

Would you like to check this on your PR?

**Comment by ev-br** [comment]
not from a <s>phone</s> portable computing device

**Comment by argriffing** [comment]
I think TravisCI decided that the docs generated from this build are the new scipy docs, and they are now being distributed or uploaded or something. How badly did I screw up?

**Comment by rgommers** [comment]
Docs for the latest dev version only get uploaded for merge commits.

**Comment by ev-br** [comment]
Now that 1.10.2 is out, this PR could use it :-)

**Comment by charris** [comment]
Lookee there, the tests pass 8-)

**Comment by ev-br** [comment]
Thanks Alex

**Pull request merged**
