### PR TITLE
BUG: dual annealing off by one with maxiter

### PR DESCRIPTION
**Pull request by sgubianpm**
@andyfaff, fix for the defect mentioned in #9419 
@js850, added suggested counting of nhev

Thanks a lot.

### CODE REVIEW

**Comment by rgommers** [comment]
This has too many commits, could you start a new branch based off of current master, and then cherry-pick only the new commits from your current branch into that, and then push that new branch back here?

**Comment by rgommers** [comment]
All changes look good to me. Missed the `sda` files, thanks for cleaning those up.

**Comment by andyfaff** [comment]
@sgubianpm, as Ralf says you'll need to bring your master branch up to date, create a feature branch, then only include the changes in the new commits. We can't merge as is as it would screw up the git history.

**Comment by ilayn** [comment]
I would create a new branch and simply copy paste the changes. It probably is much less of a hassle.

**Comment by sgubianpm** [comment]
@andyfaff, @ilayn . Thanks a lot. I close this PR, use a fresh master, create a branch with the changes in the _dual_annealing.py file and create a PR that as only 1 commit.

**Pull request closed without merging**
