### PR TITLE
Improved documentation of affine_transform (fixes #5702 and warns about #1547)

### LINKED ISSUE #5702: scipy.ndimage.interpolation.affine_transform lacks documentation about the exact transform applied
The documentation only says `matrix` and `offset` determine the mapping from input to output, but it is not clear how offset is used. I posted an attempt in #5692, but I later realised that it is actually wrong. Maybe someone who actually knows these functions could step in, as trying to guess from behaviour as I did obviously is error-prone.
Particularly, there should also be a note indicating if integer indices refer to the centre or the edges of the pixels.

### PR DESCRIPTION
**Pull request by burnpanck**

### CODE REVIEW

**Comment by rgommers** [comment]
this is almost a duplicate of gh-5794. I guess it makes sense to close this one?

**Comment by burnpanck** [comment]
Not exactly, this one does not change any behaviour, it only issues a warning. The idea was to get a warning into scipy as soon as possible, such that the users get at least a small heads-up of the upcoming backwards incompatible change. That is why it is filed against maintenance/0.17.x instead of master.

**Comment by burnpanck** [comment]
The travis failure in 2.6 (and possibly the ones in 3.4 and 3.5 as-well) are due to newly introduced tests for #1547, here still marked with `unittest.expectedFailure`, which does not yet exist in 2.6. Maybe I should just remove these tests?

**Comment by ev-br** [comment]
Typically we use a (cryptically named) `knowfailureif` from numpy.testing.decorators; you can grep the codebase for the uses. That being said, I'm not sure a PR against maintenance/0.17.x is that useful. I'm not aware of any plans for releasing 0.17.1.

**Comment by pv** [comment]
thanks, merged --- even if there won't be 0.17.1

**Pull request merged**
