### PR TITLE
ENH: interpolate: expose memort_budget optional kwarg of RBF.__call__

### PR DESCRIPTION
**Pull request by ev-br**
An alternative to the monkey-patching part of gh-16487.

cc @rgommers @larsoner -- feel free to cherry-pick or otherwise incorporate

### CODE REVIEW

**Comment by larsoner** [comment]
@ev-br is this actually something that we want in the public API, independent of the motivation to speed up a test? (I have no knowledge/opinion on if this is the case.) If so, +1 for merge and I'm happy to rebase #16487

**Comment by tupui** [comment]
We could also just have the value stored as a private attribute if we don't want to decide now.

**Comment by larsoner** [comment]
> We could also just have the value stored as a private attribute if we don't want to decide now.

Sure, this would work. But even this requires adding extra "stuff"/complications to the real code that people care about and maintain when we are really just trying to solve a testing issue. So to me the monkeypatching approach within the test of interest still has a better/more appropriate scope than adding a private attribute.

**Comment by ev-br** [comment]
> is this actually something that we want in the public API, independent of the motivation to speed up a test? (I have no knowledge/opinion on if this is the case.)

When this came in a couple of months ago, my thought knee-jerk reaction was to expose it, the second thought was it's YAGNI. So your experience seems to say that the default memory_budget is something a user _might_ want to adjust on some systems (low-memory cloud VMs? Not sure). It is still borderline YAGNI, and your PR shows working around the limitation is not impossible. But this is all handwaving anyway, this haven't seen much real-world usage yet. 
So all in all, I think it's best to add a parameter and be done with it. However, if you have a strong opinion, I won't object to just monkeypatch the test and forget. 

And either way I'd say a private attribute is worse then either of the two things IMO.

**Comment by treverhines** [comment]
I am not in favor of exposing the `memory_budget` parameter in the public API. It is an implementation detail, and we would be tied to a particular implementation once it is exposed. For example, if/when we are able to compile pythran with BLAS, we may want an implementation that avoids chunking entirely, as I suggested here https://github.com/scipy/scipy/issues/15150#issuecomment-986106487.

**Comment by ev-br** [comment]
Ok, let's declare this YAGNI and reject it

**Pull request closed without merging**
