### PR TITLE
ENH: signal: add cross cyclic spectral density

### PR DESCRIPTION
**Pull request by ggkogan**
#### Reference issue
#14783

#### What does this implement/fix?
Function cyclic_sd estimates the [cross-cyclic spectral density](https://en.wikipedia.org/wiki/Spectral_correlation_density#Definition), using [csd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.csd.html)

The signal + noise presented in the time domain (carrier frequency is 1234 Hz, modulation frequency is 28 Hz)
image

and the signal's cyclic spectral density
image

#### Additional information
Based on **ENH: signal: add cross cyclic spectral density #15519**. I have added leakage handling, example, and minor modifications to the naming - maintaining the standard convention.

### CODE REVIEW

**Comment by ggkogan** [comment]
@qbarthelemy , I consider integrating the loop in the example into the function. This will allow the user access the function with both float or vector modulation frequency input. What do you think of it?

**Comment by ggkogan** [comment]
ci/circleci: build_scipy seems to be failed due to some random slow-down. I do not have the credentials to rerun the test. @qbarthelemy, what I should do?

**Comment by qbarthelemy** [comment]
> @qbarthelemy, what I should do?

As mentionned here https://github.com/scipy/scipy/issues/14783#issuecomment-1029303310, you should avoid competing PRs, especially with same title. I am totally lost in the messages I receive: I don’t know which PR they refer to.

> Also, see my question there, about the integration of the loop into the function...

You should send an email about issue #14783 to the [scipy-dev mailing list](https://mail.python.org/mailman3/lists/scipy-dev.python.org/). In it, please explain why `cyclic_sd` is fundamental / should be added to `scipy.signal`, and please invite people to PR #15519 to discuss. 
Integration of alpha loop into function will be discussed with `signal` maintainers.

> @qbarthelemy any way we can unify this pull request with #18627?

I have merged your suggested example, giving credit to your contribution, because you will be marked as co-author then.
I you copy-paste code of others, you won’t give credit to their work.

**Comment by ggkogan** [comment]
> > @qbarthelemy, what I should do?
> 
> As mentionned here [#14783 (comment)](https://github.com/scipy/scipy/issues/14783#issuecomment-1029303310), you should avoid competing PRs, especially with same title. I am totally lost in the messages I receive: I don’t know which PR they refer to.
> 
> > Also, see my question there, about the integration of the loop into the function...
> 
> You should send an email about issue #14783 to the [scipy-dev mailing list](https://mail.python.org/mailman3/lists/scipy-dev.python.org/). In it, please explain why `cyclic_sd` is fundamental / should be added to `scipy.signal`, and please invite people to PR #15519 to discuss. Integration of alpha loop into function will be discussed with `signal` maintainers.
> 
> > @qbarthelemy any way we can unify this pull request with #18627?
> 
> I have merged your suggested example, giving credit to your contribution, because you will be marked as co-author then. I you copy-paste code of others, you won’t give credit to their work.

No competition or credit interest here. I am not familiar with the process and might have done it wrong. The previous branch was not promoted for a year and after failing to contact you I have opened a new pull request updating you and mentioning it in the description. 

Please see my new pull requests and consider integrating them. One improves the example. The other handles the leakage mentioned [here](https://github.com/scipy/scipy/pull/15519#issuecomment-1133750012)

PS: I do not know who and how to invite the people relevant for the discussion

**Comment by qbarthelemy** [comment]
Ok, fine.

I believe that the subject is not progressing, because the SciPy community has not been solicited, and the method is little known.
IMHO, I’m not sure they’re willing to add this contribution.

That said, to improve #15519, your suggestion of example with PR https://github.com/qbarthelemy/scipy/pull/1 was really a good move.

**Pull request closed without merging**
