### PR TITLE
DOC: add dev setup description for PRs to local repo

### PR DESCRIPTION
**Pull request by rlucas7**
This PR adds a few lines to the development setup to describe how to setup the configuration of git so that you grab the pull requests from github when you run:

`git fetch upstream`

and stores them in your local repository. This is helpful if you want to test out the code that someone has in a PR in an easy way. If the pull request is recent then you will need to re-fetch and then create a branch e.g. 

`git checkout pr/123`

### CODE REVIEW

**Comment by ilayn** [comment]
I think having this information is a good idea but modifying the config file is not since this would download a huge amount of redundant information. Probably you would only need a few of the PRs. 

Per pull request you can get the PR into local repo by various ways, see the [documentation](https://help.github.com/articles/checking-out-pull-requests-locally/) for creating a branch number with an ID or [this SO thread](https://stackoverflow.com/questions/6743514/how-can-i-fetch-an-unmerged-pull-request-for-a-branch-i-dont-own)

**Comment by rlucas7** [comment]
> I think having this information is a good idea but modifying the config file is not since this would download a huge amount of redundant information. Probably you would only need a few of the PRs.

True. For me it is more about being forgetful-my memory sucks. This means that whenever I update my master (which I do before starting any new dev/topic branch) I have all the PRs locally. This is also good if my internet connection goes out (often throttled in evening b/c of too many netflix watchers cloggin network bandwidth :).  

What about presenting both options (change config to get all) and pick out a single PR into a local branch? 

I can indicate in the doc the latter (single PR pick) is the preferred option. I'd put the preferred option first (reading top to bottom).

**Comment by ilayn** [comment]
I am not sure why you would want to have all the PRs locally. You probably don't want to do anything with others' PRs unless you really want to contribute to that particular PR which you can do it case by case.

Your own fork won't need any of the PRs. Am I missing something?

**Comment by rlucas7** [comment]
> Your own fork won't need any of the PRs. Am I missing something?

You might want some and not have them unless you explicitly bring them down to your local. This is more about making that automatic so you don't need to remember to bring them down, i.e. running 

`git fetch upstream` 

from local repo master branch syncs the master locally with the dev master branch and brings in all the PRs. 

The instructions in this PR refer to changes in the local repo, not the forked remote on github. 
I don't think changing the config this way will push the PRs to the forked remote, at least it didn't on my setup and I followed the instructions in this doc.

I agree with you that the forked remote (usually called `origin`) shouldn't need to carry around all the PRs. Unless someone has a custom configuration of the default push behavior in their git global config 
file this shouldn't happen.

**Comment by rlucas7** [comment]
@ilayn latest commit reverts to a description of how to manually add in a pr to a local branch (w/o any config changes). This should be in line with your previous recommendations for local dev env git repo setup.

**Comment by ilayn** [comment]
Reads quite nice and clear. Thanks @rlucas7

**Comment by rlucas7** [comment]
Thanks @ilayn, happy to see this in the DOC. Hopefully this will get more folks in the community involved in CRs of PRs.

**Pull request merged**
