### PR TITLE
DOC: Add math notation for examples of state space systems in ltisys.py

### PR DESCRIPTION
**Pull request by nosseb**
Following PR #13513, this is adding nice math notations for state space systems.

As the math representation is in two equations, I decided against using inline math.

There are a few more case of state space systems in ltisys.py but those have nice description in natural language, so I did not provide math notation for them.
e.g. : https://github.com/scipy/scipy/blob/b986aaaa3b9a2b2c2008db43db53ca5d2ab47e24/scipy/signal/ltisys.py#L1857-L1866

Also while I have some maintainer attention, I noticed that in #13513 I sometime placed the math notation after `>>> from scipy import signal` and in other places before it. Do you want me to homogenize that ? If so should I do it in this PR or open a new one ?

### CODE REVIEW

**Comment by ilayn** [comment]
That's nice @nosseb for your time. Consumers of Scipy are quite OK with reading 2x2 arrays. So I think this is pushing too much in the unreadableness. Maybe you want to write the underlying equations if you think it is still worthwhile?

**Comment by nosseb** [comment]
Thanks for your feedback @ilayn. I am fairly new to lti systems and what I though was a lack of documentation might very well be knowledge that is expected to be be learned outside scipy; and I can understand that over-documentation diminishes readability.

I not quite sure I understand what you mean by "write the underlying equations" . Do you mean something like this :
```
ẋ(t) = A · x(t) + B · u(t)
y(t) = C · x(t) + D · u(t)
```
without writing the values of the matrices ? Or are there still other ways of expressing lti that I am not aware of ?

**Comment by ilayn** [comment]
Ah no I mean the equations that are currently written as code; double integrator etc. From there it is not very difficult to arrive at the SS equations. Or at least doesn't require advance knowledge of the subject

**Comment by nosseb** [comment]
I haven't found the time to finish this in the past two years, and I doubt I will anytime soon.

**Pull request closed without merging**
