### PR TITLE
Mark FITPACK functions as thread safe.

### LINKED ISSUE #4673: scipy.interpolate.RectBivariateSpline construction locks PyQt event loop
Construction of a RectBivariateSpline is time-consuming, and I want to create it in a background PyQt thread and then pass to my GUI. Alas, its construction even in dedicated thread freezes PyQt event loop. Why does it happen? AFAIK, scipy calls do release GIL lock?

Here is my sample code

    # -*- coding: utf-8 -*-
    
    import numpy as np
    import scipy as sp
    import scipy.interpolate
    
    import os
    import sys
    import time
    import pickle
    from PyQt4 import QtCore, QtGui
    
    
    class LongRunningWorker(QtCore.QObject):
    
        result_ready = QtCore.pyqtSignal(tuple)
    
        @QtCore.pyqtSlot()
        def generate_uber_mega_data(self):
            print "Oy!"
            # time.sleep(5)
    
            r_ticks = np.linspace(0, 1000, 5000)
            phi_ticks = np.linspace(0, 2 * np.pi, 5000)
    
            r_grid, phi_grid = np.meshgrid(r_ticks, phi_ticks)
    
            print u"Starting interpolation"
            spline = sp.interpolate.RectBivariateSpline(r_ticks, phi_ticks, r_grid * phi_grid)
            print u"Интерполяция всё / Interpolation complete"
            time.sleep(5) # And here (while the sleep is running) GUI starts working
            print "Vey!"
            self.result_ready.emit((7, 40))
    
    @QtCore.pyqtSlot(tuple)
    def process_mega_data(mega_data):
        print mega_data
    
    if __name__ == "__main__":
        app = QtGui.QApplication(sys.argv)
        mega_button = QtGui.QPushButton("Press__________________________________________here")
        mega_button.show()
    
        background_thread = QtCore.QThread()
        worker = LongRunningWorker()
        worker.moveToThread(background_thread)
    
        background_thread.start()
    
        # Press here -- and interpolation will start and GUI events on SpinBox will freeze
        mega_button.clicked.connect(worker.generate_uber_mega_data)
        worker.result_ready.connect(process_mega_data)
    
        # This little scum doesn't change values, when interpolation is running!
        mega_spinbox = QtGui.QSpinBox()
        mega_spinbox.show()
    
        sys.exit(app.exec_())

### PR DESCRIPTION
**Pull request by erosennin**
Fixes #4673.

### CODE REVIEW

**Comment by pv** [comment]
For posterity, you should include a comment on the source code on the
rationale why these routines are threadsafe.

**Comment by erosennin** [comment]
Good point. Done.

**Comment by ev-br** [comment]
@erosennin (multithreading noob here) does it actually fix the problem in #4673? Is it possible to add a test case which does not depend on Qt being installed?

**Comment by erosennin** [comment]
It can be tested with something like this:

```python
import threading
import time

import numpy as np
import scipy.interpolate

r_ticks = np.linspace(0, 1000, 5000)
phi_ticks = np.linspace(0, 2 * np.pi, 5000)
r_grid, phi_grid = np.meshgrid(r_ticks, phi_ticks)

def long_running_calculation():
    print('interpolation started')
    scipy.interpolate.RectBivariateSpline(r_ticks, phi_ticks, r_grid * phi_grid)
    print('interpolation complete')

worker_thread = threading.Thread(target=long_running_calculation)

worker_thread.start()
for i in range(3):
    time.sleep(1)
    print('working')
```

The correct output should be like this:
```
interpolation started
working
working
working
interpolation complete
```

If `scipy.interpolate.RectBivariateSpline()` blocks, the output is something like:

```
interpolation started
interpolation complete
working
working
working
```

I'm not sure how to make this into a proper test case though, because it depends on timings and will fail if `scipy.interpolate.RectBivariateSpline()` completes too fast.

**Comment by ev-br** [comment]
Thanks. 
So is it correct that here you're relying on the assumption that the spline calculation takes longer than three seconds?
If this is the case, how about first running the calculation in the main thread, to gauge the runtime. 

It is likely still too brittle for a regular test suite. I think it still makes sense to add something like this as a test case, guarded with SCIPY_XSLOW env variable (grep the tests for the usage, eg somwehere in sparse, stats/tests/test_fit.py IIRC). This way, it's both not run by automated tests, and it's readily available for troubleshooting if needed.

**Comment by erosennin** [comment]
The problem here is that execution times depend on the system load, so the test can randomly fail even if the spline calculation takes longer than three seconds. There are many possible race conditions here.

Even worse, the test can give a false positive result under certain circumstances (pass where it should fail). I don't really like the idea of including such unreliable tests into the code base. Or, if we do so, perhaps we should consider adding a `SCIPY_XUNRELIABLE` env variable to clearly state that some tests are producing random results and should not be relied on. :)

And another point. If we add tests, we should add them for all `scipy.interpolate` functions and classes
affected by the patch, not only `scipy.interpolate.RectBivariateSpline`.

The question is, is it really worth it?

**Comment by ev-br** [comment]
Granted, it's fragile, indeterministic enough so that it's not a good test case for unit testing. 
And I agree, it's not worth adding tests for all the functions you marked as threadsafe in this PR. 
Adding a test which is flakey by design is IMO doing more harm than it's worth. Multiplying the number of special classes of tests and env variables is probably overboard as well.

The only thing I'm asking for is a bit of code one can run manually (50 times over if needed) if there's a need to debug a possible threading issue. --- Maybe it's just me, and everybody else is debugging race conditions every day before breakfast, or maybe even instead of it; in that case please feel free to disregard what I'm saying. Otherwise, adding just what you wrote above would be good.

I see three possibilities:

- cook up a "probabilistic" benchmark, a la https://github.com/scipy/scipy/blob/master/benchmarks/benchmarks/interpolate.py#L12
Likely too cool to be useful ;-)

- add a test but guard it with SCIPY_XFAIL, so that it does not run in a regular test suite (see https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_fit.py#L56; use `skipif` to skip the test instead of marking it as a knownfail).

- add a script to the testing directory, add comments, and mark it as a *not test* 
(e.g., https://github.com/scipy/scipy/blob/master/scipy/stats/morestats.py#L1671)
Likely the cleanest option.

**Comment by erosennin** [comment]
> add a script to the testing directory, add comments, and mark it as a not test 

I like this idea.

Added `scipy/interpolate/tests/check_gil.py`.

**Comment by pv** [comment]
In my experience, what typically happens with such scripts, is that nobody runs them, and they will bitrot.

**Comment by ev-br** [comment]
@pv what would you suggest?

**Comment by pv** [comment]
I'd follow your second suggestion, and piggypack it on the test framework as usual, but turned off by default.

**Comment by erosennin** [comment]
OK, I'll convert the script into a test case than, guarded by `SCIPY_XFAIL`.

By the way, is there a module for common test decorators like `xfail` and `xslow`? Copypasting just feels wrong. :)

**Comment by pv** [comment]
There's no module so far for them. They however could be added in
scipy._lib._testutil or something like that.

**Comment by erosennin** [comment]
Done. Converted the script into a test case.

**Comment by ev-br** [comment]
Merging, thanks @erosennin!

**Comment by Felix-neko** [comment]
Спасибо, братан!
^__^

**Pull request merged**
