### PR TITLE
scipy.signal.find_peaks documentation error

### PR DESCRIPTION
**Pull request by SyedSaifAliAlvi**
Line 763 has been changed.

### CODE REVIEW

**Comment by ilayn** [comment]
@lagru Do you mind checking this?

**Comment by lagru** [comment]
Not at all. 

@SyedSaifAliAlvi this is a typo and your fix is correct. Seeing that you closed this, do you want to go ahead and reopen this?

**Comment by SyedSaifAliAlvi** [comment]
> Not at all.
> 
> @SyedSaifAliAlvi this is a typo and your fix is correct. Seeing that you closed this, do you want to go ahead and reopen this?

I think i closed this request by mistake.

**Comment by ilayn** [comment]
OK in it goes then. Thanks @SyedSaifAliAlvi , @lagru !

**Comment by ilayn** [comment]
Just for the future reference, please make separate branches to work on new features and to send PRs such that your standard working repo does not interfere with the PRs you have submitted. Once a PR is merged you can safely delete that branch and keep working on other branches.

**Comment by SyedSaifAliAlvi** [comment]
> Just for the future reference, please make separate branches to work on new features and to send PRs such that your standard working repo does not interfere with the PRs you have submitted. Once a PR is merged you can safely delete that branch and keep working on other branches.

Sure,I will remember that, actually i am new that is why i made changes directly to master branch.

**Pull request merged**
