### PR TITLE
TST:special: bump tolerance levels for test_j_roots and test_js_roots

### PR DESCRIPTION
**Pull request by rohitjamuar**
See #5363 

@rgommers @pv

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @rohitjamuar, merged.

**Comment by rgommers** [comment]
Will also backport this to 0.16.1 - risk-free and I assume that that's helpful for icc users.

**Comment by rohitjamuar** [comment]
Thanks @rgommers.

**Comment by rgommers** [comment]
Interestingly I see that TravisCI is now busy building the merge commit. IIRC it didn't do that before. Did someone change settings on TravisCI by hand?

**Comment by ewmoore** [comment]
I think that is #5383.

**Comment by rgommers** [comment]
Ah makes sense that it was changed for that. gh-5383 itself shouldn't have changed when the tests run as far as I can tell though. It only adds ``after_success`` to ``.travis.yml``, which shouldn't affect that (http://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle).

**Pull request merged**
