### PR TITLE
DOC: clarify meaning of flags in ode.integrate

### PR DESCRIPTION
**Pull request by jakevdp**
This came up on StackOverflow. This PR adds a suitable description to the doc string. http://stackoverflow.com/questions/43500970/what-do-scipy-integrate-ode-integrate-optional-step-and-relax-arguments-do

### CODE REVIEW

**Comment by aryamccarthy** [comment]
Shouldn't it be` t_1 >= t` in the docstring?

**Comment by jakevdp** [comment]
Indeed, thanks!

**Comment by jakevdp** [comment]
I don't understand the source of the test failure, but I doubt it has anything to do with this PR.

**Comment by jakevdp** [comment]
Yep, it's the same failure as on master currently.

**Comment by WarrenWeckesser** [comment]
> Yep, it's the same failure as on master currently.

Reported in https://github.com/scipy/scipy/issues/7321

**Pull request merged**
