### PR TITLE
ENH: Improved speed of copy into L, U matrices

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
1. Split a single loop copying data from output of ?getrf to
   L and U matrices into three different loops to avoid conditional
   branching in the loop.

2. Swapped the order of iterators: iteration over the first index of
   matrix should be innermost to take better advantage of memory
   locality, since the first index moves contiguously in memory with
   Fortran data layout.

This change results in

  * 40% performance improvement on KNL for input
    of shape (23000, 27845) and in double precision.
  * 15% performance improvement on HSW for input
    of shape (17845, 13000) and in double precision

when building both the base and the improved sources using
Intel Compiler using MKL 2018.0.0 for BLAS/LAPACK.

The following script was used to measure timing:

```python
import numpy as np
from scipy.linalg import lu
import time
import copy
try:
   from numpy.random_intel import RandomState
   rs = RandomState(seed=124, brng='SFMT19937')
except ImportError:
   rs = np.random.RandomState(124)


for n,m in ((23000, 27845), (27845, 23000), (35000,35000)):
    rnd = copy.deepcopy(rs)
    mat = rnd.rand(n, m)
    print("LU-decomposition input shape: {}".format(mat.shape))
    for it in range(3):
        t0 = time.time()
        el, u = lu(mat, permute_l=True)
        t1 = time.time()
        print("\tIteration {it}, execution time = {time:.5g} seconds".format(it=it,time=t1-t0))

    print("  (L, U) shapes are {} and {}".format(el.shape, u.shape))
    print("  U[1,5] == {}".format(u[1, 5]))
    del el, u, mat
```

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@rgommers It would be great if this PR made it into SciPy 1.0. Is there anything I can do to help make this happen? Thank you

**Comment by rgommers** [comment]
@oleksandr-pavlyk it's too late, sorry. We're not backporting anything but important bug fixes to 1.0.x at this point. And in general that's the policy for any release after we branch.

This PR looks good, so I've added the 1.1.0 milestone. I'm not able to review it though, Fortran isn't really my thing....

**Comment by person142** [comment]
The Fortran changes look good. (How did I get to the point where Fortran 77 is my thing?)

It might be nice to add your benchmarks to the official benchmarks?

**Comment by rgommers** [comment]
> How did I get to the point where Fortran 77 is my thing?

I'm sure it was both interesting and painful:)

**Comment by rscohn2** [comment]
Oleksandr put the same patch into Intel Python, and I reviewed that one. The Fortran code is good.

**Comment by rgommers** [comment]
Thanks @rscohn2 and @person142 for reviewing. Merging then, benchmarks are not required for merge. 

@oleksandr-pavlyk a separate PR for turning your benchmarking code into a proper benchmark (easy to do, under ``benchmarks/benchmarks``) so we automatically get warned of speed regressions would still be welcome.

**Comment by pv** [comment]
Some stuff started failing on 32-bit win32 after merging this --- 
unclear if related:
.
https://ci.appveyor.com/project/scipy/scipy/build/1.0.689/job/2a4vgct77ob531mo

**Comment by oleksandr-pavlyk** [comment]
The failure is with Spearman Rank test, which is unrelated to LU decomposition AFAIK. The test should compute correlation coefficient between vector of ranks 

The change in Fortran code in this PR amounts to swapping the order of iterations in a double nested loop. Only data copying is done in those loops. No other computations are being done.

I am inclined to think that it is either a fluke, or caused by some other changes.

**Comment by pv** [comment]
I also do not see a way how this PR could cause these failures. The 
Numpy version used however appers to have changed from 1.13.1 to 1.13.2, 
which seems a more likely cause.

**Comment by rscohn2** [comment]
32 bit address spaces are more crowded and stray pointer problems are more likely to cause a problem. I did check the indexes in the review for that kind of problem.

I agree that the change in numpy seems more likely.

**Pull request merged**
