### PR TITLE
DOC: Update docs for connection='weak' in connected_components

### LINKED ISSUE #9861: Bug in connected_components with connection='weak'
The [documentation for connected_components](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.connected_components.html) states that, with `connected='weak'` and a directed graph (the default), nodes i and j are weakly connected if there is a path from i to j or a path from j to i. Note that [this is not the same as saying that the undirected graph formed by ignoring directions is connected](https://math.stackexchange.com/questions/1212815/weakly-connected-graph-test). The distinguishing example in that post does not work correctly in SciPy.

### Reproducing code example:

```
G = np.zeros((3,3))
G[0,1] = 1
G[0,2] = 1
connected_components(G)
```
This returns:
```
(1, array([0, 0, 0], dtype=int32))
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by bharatr21**
Resolve #9861 by updating the docs for `connection='weak'` in connected_components

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The refguide failure looks like something that I thought was fixed recently

**Comment by Bharat123rox** [comment]
Whoops, sorry @tylerjereddy tests were meant for another branch, I've already reverted the commit

**Comment by JeremyRubin** [comment]
Looks good to me

**Comment by rgommers** [comment]
Merged, thanks @Bharat123rox . And thanks for the review @JeremyRubin

**Pull request merged**
