### PR TITLE
DOC: stats: add reference for gstd

### PR DESCRIPTION
**Pull request by qbarthelemy**
This PR:
- adds the reference to Kirkwood1979 for the geometric standard deviation;
- adds "See also", with reference to geometric mean, and standard deviation.

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
The rendered docs artifact LGTM (see below). Perhaps a stats regular may want to take a quick glance: 

image

**Comment by tylerjereddy** [comment]
Perhaps one question might be--is that reference definitely what was used to write the code? Or is it just the likely standard reference, but not sure if used to write the code?

**Comment by qbarthelemy** [comment]
Yes, this reference is self-sufficient.

Citation from Kirkwood1979:
>Let X be a Lambda(mu, sigma^2) log-normal variate, so that Z=log X is N(mu, sigma^2).
The mean, mu, and standard deviation, sigma, of Z suffice to convey all necessary information
about its distribution to statistician and non-statistician, alike.
The geometric mean of X is exp(mu), and let us define the geometric standard deviation (GSD) to be exp(sigma).

By definition, `gsd = exp(sigma) = exp(std(Z)) = exp(std(log(X)))`.

**Review by rgommers — APPROVED** [review]
This looks right to me. Thanks @qbarthelemy, and thanks @tylerjereddy for the review.

**Pull request merged**
