### PR TITLE
ENH: FIX: update HiGHS submodule to resolve MIP infeasibility error

### LINKED ISSUE #16609: BUG: `scipy.optimize.linprog` reports optimal for trivially infeasible MILP
### Describe your issue.

In anticipation of the upcoming 1.9.0 release, I've been trying to update [cvxpy](https://github.com/cvxpy/cvxpy) to use SciPy's newly-introduced MILP functionality. I've been working with SciPy `1.9.0rc2`. You can find [my draft fork of cvxpy here](https://github.com/tasseff/cvxpy) and the associated issue [here](https://github.com/cvxpy/cvxpy/issues/1443). While performing cvxpy unit tests, I came across [a MILP problem](https://github.com/cvxpy/cvxpy/blob/8cc75a8616ac4643134e25147033054d92d89951/cvxpy/tests/test_mip_vars.py#L92-L97) of the form
```
Minimize
 obj: t
Subject To
 c1: y = 0.5
Bounds
 0 <= t
General
 y
End
```
The problem is clearly infeasible, as `y` cannot be both integer (indicated by the `General` entry) and equal to `0.5`. This would be solved using SciPy's new MILP functionality with the script I've added below. Curiously, the solution status is reported as optimal, although it should clearly be reported as infeasible. (It is even acknowledged as infeasible in the rest of the log.) Replacing the `options` flag with `options={'disp': True, 'presolve': False}` provides the expected result, i.e., infeasibility is proven. This suggests the issue may be with the version of HiGHS used by SciPy, and more specifically, its presolve routine.

Indeed, building from [the HiGHS master branch](https://github.com/ERGO-Code/HiGHS) and solving using the above `.lp` problem provides the correct logging output, i.e., the problem is identified as infeasible. A similar issue raised [here](https://github.com/ERGO-Code/HiGHS/issues/902) suggests that this issue may not have been corrected, but another issue [here](https://github.com/ERGO-Code/HiGHS/issues/907) has been closed. Suffice to say, I think this is a trivial enough example where the correct behavior needs to be ensured by both SciPy and HiGHS. You may want to consider updating the version of HiGHS used for the 1.9.0 release or, if that is not enough, (i) providing a fix within HiGHS or (ii) waiting for this fix before releasing SciPy 1.9.0.

### Reproducing Code Example

```python
import numpy as np
import scipy

res = scipy.optimize.linprog(
    c=[1.0, 0.0],
    A_eq=[[0.0, 1.0]],
    b_eq=[[0.5]],
    bounds=[(0.0, None), (None, None)],
    integrality=[0, 1],
    options={'disp': True})
```

### Error message

```shell
Presolving model
0 rows, 0 cols, 0 nonzeros
0 rows, 0 cols, 0 nonzeros
Presolve: Optimal
WARNING: Untransformed solution with objective 0 is violated by 0.5 for the original model

Solving report
  Status            Optimal
  Primal bound      0
  Dual bound        0
  Solution status   infeasible
                    0 (objective)
                    0 (bound viol.)
                    0.5 (int. viol.)
                    0 (row viol.)
  Timing            0.01 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
```

### SciPy/NumPy/Python version information

1.9.0rc2 1.22.3 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

Closes gh-16609

#### What does this implement/fix?

- update HiGHS fork to latest available bug fixes/enhancements 

#### Additional information

- referenced issue from cvxpy expressed desire to have these fixes in the 1.9.0 release, so marked as backport-candidate
- should not be merged until https://github.com/scipy/HiGHS/pull/58 and the submodule is updated to point at that commit

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Changes here looks nicely concise, much less painful than the last update it looks like.

Can you update the submodule?

**Comment by mckib2** [comment]
> Can you update the submodule?

Done

> Changes here looks nicely concise, much less painful than the last update it looks like.

Yes, the HiGHS C++ API seems to be stabilizing and the largest changes are from good refactors

**Comment by rgommers** [comment]
The CI failures are unrelated. I did notice slow tests related to HiGHS:
```
59.60s call     build/testenv/lib/python3.9/site-packages/scipy/optimize/tests/test_linprog.py::TestLinprogHiGHSMIP::test_mip6
59.53s call     build/testenv/lib/python3.9/site-packages/scipy/optimize/tests/test_milp.py::test_milp_6
36.33s call     build/testenv/lib/python3.9/site-packages/scipy/optimize/tests/test_linprog.py::TestLinprogHiGHSMIP::test_mip1
```
but I also see those on other PRs, and that is gh-16494

**Review by rgommers — APPROVED** [review]
This all looks good, builds without warnings. I tested locally on macOS arm64, all good there too. I think this should be okay to backport still, even though it's a very large code change (so some risk).

**Comment by rgommers** [comment]
Thanks @mckib2!

**Pull request merged**
