### PR TITLE
BLD: use the meson-python build backend

### PR DESCRIPTION
**Pull request by FFY00**
Signed-off-by: Filipe Laíns <lains@riseup.net>

#### Reference issue
 #13615

#### What does this implement/fix?
This moves the Python build system to Meson, by using the `meson-python` backend.

### CODE REVIEW

**Comment by FFY00** [comment]
Some of the ways the CI is failing are surprising to me. DO the dependencies, etc. need to be manually updated?

**Comment by rgommers** [comment]
> Some of the ways the CI is failing are surprising to me. DO the dependencies, etc. need to be manually updated?

Ah yes, indeed. We have too many CI configs, and many require different sets of dependencies or different versions of the same dependency, so there's no single place that it's collected. 

I think only some Azure jobs will fail though; the others still use `setup.py ...` instead of `pip install .`. I suspect searching through `azure-pipelines.yml` for `setuptools` and replacing that will fix it.

**Comment by rgommers** [comment]
Although .... we don't want to update the Windows jobs just yet. Let me think about this for a minute.

**Comment by rgommers** [comment]
Okay I pushed a fix. We want the `source_distribution` job to pick up the `meson-python` changes in `pyproject.toml`, but leave the other jobs unchanged for the time being.

**Comment by rgommers** [comment]
Argh, next issue:
```
Run-time dependency openblas found: NO (tried pkgconfig and cmake)
```
Adding that.

**Comment by rgommers** [comment]
So the extra things we need here are:

- `meson-python`
- `pkg-config`
- `build`

I may still be missing something. The changes to `pyproject.toml` look good to me.

**Comment by rgommers** [comment]
Ah, we were still testing ATLAS in `source_distribution`, not OpenBLAS. No wonder it can't find it.

**Comment by rgommers** [comment]
@FFY00 it may be useful to have a look at the Azure yaml files to get a sense for our non-PyPI dependencies. E.g. for the Linux jobs:
```
# Install dependencies
- ${{ if eq(parameters.use_64bit_blas, true) }}:
  - script: |
      target=$(python tools/openblas_support.py)
      echo "[openblas64_]" > site.cfg
      echo "library_dirs = $target/lib" >> site.cfg
      echo "include_dirs = $target/include" >> site.cfg
      echo "runtime_library_dirs = $target/lib" >> site.cfg
    displayName: 'Enable 64-bit OpenBlas'
- script: >-
    sudo apt-get update -y &&
    sudo apt-get install -y
    libatlas-base-dev
    liblapack-dev
    libopenblas-dev
    pkg-config
    gfortran
    libgmp-dev
    libmpfr-dev
    libsuitesparse-dev
    ccache
    libmpc-dev
```
Half are build deps, half runtime deps.

**Comment by FFY00** [comment]
> I may still be missing something. The changes to `pyproject.toml` look good to me.

We will need `pep621` (but see https://github.com/FFY00/mesonpy/issues/33, so it's probably best to just wait on that before thinking of merging the PR).

> @FFY00 any idea why this was implemented in `pip`? It doesn't make any sense to me. We are switching build systems, which means we are going to default to Meson in `1.9.0` but will leave `setup.py` in the release as a backup.

Looks like a reasonable decision to me, but unfortunately it comes to bite us while we are in the middle of the process of migrating to PEP 517. In most situations where a PEP 517 backend is specified in `pyproject.toml`, the developers did not intend for the project to be installed without PEP 517.

Lots of users when facing issues will search for it online, and most likely some will end up finding something about PEP 517 and people telling the "asker" to disable PEP 517 as a solution. I think a big number of those users will just try out the PEP 517 disabling flag blindly, which will not work. In fact, I think it will throw them off by making it seems like it did, this is due to the way pip works, as I will explain below.

AFAIK, pip does not run `setup.py` directly, instead, it invokes setuptools itself and asks for a build. I don't know the particular reason behind that, perhaps @pradyunsg or @uranusjr do? (please don't feel any pressure to reply if you don't know this from the top of your mind, it is not very relevant to us, just something that would be nice to know)
This is one of the things that led to pip mistakenly start supporting `setup.cfg`-only projects (this means, no `pyproject.toml` and no `setup.py`), which was fixed in https://github.com/pypa/pip/pull/10031.
Other thing that contributes negatively to this situation is `setuptools` working with no metadata, it will fallback the package name to `UNKNOWN` and the version to `0.0.0`. Meaning that it will successfully build a sdist or wheel for any random directory it is run on.

```
$ mkdir test
$ cd test
$ python -c 'import setuptools; setuptools.setup()' bdist_wheel
running bdist_wheel
running build
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
installing to build/bdist.linux-x86_64/wheel
running install
running install_egg_info
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
listing git files failed - pretending there aren't any
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
Copying UNKNOWN.egg-info to build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/UNKNOWN-0.0.0.dist-info/WHEEL
creating 'dist/UNKNOWN-0.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'UNKNOWN-0.0.0.dist-info/METADATA'
adding 'UNKNOWN-0.0.0.dist-info/WHEEL'
adding 'UNKNOWN-0.0.0.dist-info/top_level.txt'
adding 'UNKNOWN-0.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
```

So if the user was able to disable PEP 517 in pip, I believe, as it stands currently, the project will still pass the rest of pip's validation, and pip would gladly build and install some garbage when not run on an actual valid project. This, of course, could be fixed another way, but I think pip's decision is reasonable for the reason I highlighted above.

Sorry for the dive on this, but I don't think many people know about pip's behavior here, so I thought it would be worth to share it you, even if it's just tangentially related to the actual issue :sweat_smile:

**Comment by FFY00** [comment]
As for us, right now, I think I will just work on the missing platforms and try to make the backend ready to actually be adopted.

**Comment by rgommers** [comment]
> Sorry for the dive on this, but I don't think many people know about pip's behavior here, so I thought it would be worth to share it you, even if it's just tangentially related to the actual issue

No worries, this is actually interesting. As usual, what is at face value an unreasonable thing to do (erroring out because of `pyproject.toml` content when I explicitly say _"do not use `pyproject.toml`, do the legacy thing"_) has some other reasons that made that necessary.

This isn't a blocker, we just need to make more changes to CI files to not use `pip`, but rather use `python setup.py bdist_wheel` or similar.

> As for us, right now, I think I will just work on the missing platforms and try to make the backend ready to actually be adopted.

That sounds good.

**Comment by pradyunsg** [comment]
> AFAIK, pip does not run `setup.py` directly, instead

It does. It calls `setup.py bdist_wheel` with a bunch of fancy wrapping and options.

https://github.com/pypa/pip/blob/bf91a079791f2daf4339115fb39ce7d7e33a9312/src/pip/_internal/utils/setuptools_build.py#L47

**Comment by pradyunsg** [comment]
There's actually some shim logic (see https://github.com/pypa/pip/blob/723b2df7b40b0c9d6c38bac4f20c533ae141b6fc/src/pip/_internal/utils/setuptools_build.py for an elaborated version of the file). That logic has a fallback for supporting setup.cfg-only projects, IIRC.

**Comment by pradyunsg** [comment]
> In fact, I think it will throw them off by making it seems like it did, this is due to the way pip works, as I will explain below.

IIRC, it won't work. If you have a pyproject.toml file and the user passes `--no-use-pep517`, pip should refuse to work stating that PEP 517 projects can't be used with `--no-use-pep517`.

**Comment by pradyunsg** [comment]
OK, that's all from me. KTHXBAI

**Comment by rgommers** [comment]
> IIRC, it won't work. If you have a pyproject.toml file and the user passes `--no-use-pep517`, pip should refuse to work stating that PEP 517 projects can't be used with `--no-use-pep517`.

Almost - it refuses when a `pyproject.toml` file is present AND a `build-backend` is specified. `pip install . --no-use-pep517` works just fine on SciPy's `main` branch right now.

**Comment by rgommers** [comment]
I can't think of a good workaround for a gradual transition right now. If a user wants to build the `1.9.0` release with `distutils` (for whatever reason), then basically the `sdist` is useless to them, unless they unpack it, delete the `pyproject.toml` from it, and then run `cd unpacked_sdist && pip install .` (or alternatively, run `python setup.py bdist_wheel && pip install dist/scipy*`). 

Which is all fine, they can just either do the extra steps (we will have docs), or they can just use `1.8.x`.

**Comment by FFY00** [comment]
@pradyunsg, thank you for clearing that up.

**Comment by pradyunsg** [comment]
> Almost - it refuses when a `pyproject.toml` file is present AND a `build-backend` is specified.

Yup, I read the code wrong. 😅 

I missed that we had this failure mode behind another conditional. Anyway, if someone wants to take a closer "proper" look, here's the ~140 line function: https://github.com/pypa/pip/blob/1cda23bd6bd0066ad557e4f7ca7c670744357b2b/src/pip/_internal/pyproject.py#L28

**Comment by Smit-create** [comment]
I generated the meson `sdist` (using this PR) and setup.py `sdist`. I see the following files missing in meson generated `sdist` (All of them might not be necessary to have)

<details>
<summary> Missing Files </summary>
<p>

```
scipy/sparse/csgraph/_flow.c
scipy/sparse/csgraph/_traversal.c
scipy/sparse/csgraph/_matching.c
scipy/sparse/csgraph/_min_spanning_tree.c
scipy/sparse/csgraph/_shortest_path.c
scipy/sparse/csgraph/_tools.c
scipy/sparse/csgraph/_reordering.c
linalg/_propack/PROPACK/.git
scipy/scipy/sparse/_csparsetools.pyx
scipy/sparse/sparsetools/csr_impl.h
scipy/sparse/sparsetools/bsr_impl.h
scipy/sparse/sparsetools/csc_impl.h
scipy/sparse/sparsetools/other_impl.h
scipy/sparse/sparsetools/sparsetools_impl.h
scipy/scipy/sparse/_csparsetools.c
scipy/ndimage/src/_ni_label.c
scipy/ndimage/src/_cytest.c
scipy/scipy/cluster/_optimal_leaf_ordering.c
scipy/scipy/cluster/_hierarchy.c
scipy/scipy/cluster/_vq.c
scipy/scipy/stats/_qmc_cy.cxx
scipy/scipy/stats/_biasedurn.pyx
scipy/scipy/stats/_stats.c
scipy/scipy/stats/_hypotests_pythran.cpp
scipy/stats/_levy_stable/levyst.c
scipy/scipy/stats/_biasedurn.cxx
stats/_boost/src/nbinom_ufunc.cxx
stats/_boost/src/beta_ufunc.cxx
stats/_boost/src/hypergeom_ufunc.cxx
stats/_boost/src/ncf_ufunc.cxx
stats/_boost/src/beta_ufunc.pyx
stats/_boost/src/templated_pyufunc.pxd
stats/_boost/src/binom_ufunc.cxx
stats/_boost/src/ncf_ufunc.pyx
stats/_boost/src/hypergeom_ufunc.pyx
stats/_boost/src/func_defs.pxd
stats/_boost/src/binom_ufunc.pyx
stats/_boost/src/nbinom_ufunc.pyx
scipy/stats/_unuran/unuran_wrapper.pyx
scipy/stats/_unuran/unuran_wrapper.c
scipy/scipy/stats/_sobol.c
scipy/scipy/linalg/_cythonized_array_utils.c
scipy/scipy/linalg/_matfuncs_sqrtm_triu.cpp
scipy/scipy/linalg/cython_blas.c
scipy/scipy/linalg/cython_lapack.pxd
scipy/scipy/linalg/_solve_toeplitz.c
scipy/scipy/linalg/_blas_subroutine_wrappers.f
scipy/scipy/linalg/_decomp_update.c
scipy/scipy/linalg/_matfuncs_expm.c
scipy/scipy/linalg/_decomp_update.pyx
scipy/scipy/linalg/_blas_subroutines.h
scipy/scipy/linalg/_lapack_subroutine_wrappers.f
scipy/scipy/linalg/cython_lapack.c
scipy/scipy/linalg/cython_lapack.pyx
scipy/scipy/linalg/_lapack_subroutines.h
scipy/scipy/linalg/cython_blas.pxd
scipy/scipy/linalg/_matfuncs_expm.pyx
scipy/scipy/linalg/cython_blas.pyx
scipy/scipy/linalg/_matfuncs_sqrtm_triu.c
scipy/io/matlab/_streams.c
scipy/io/matlab/_mio5_utils.c
scipy/io/matlab/_mio_utils.c
setup_scipy/scipy/scipy/version.py
scipy/scipy/signal/_peak_finding_utils.c
scipy/scipy/signal/_lfilter.c
scipy/scipy/signal/_spectral.cpp
scipy/scipy/signal/_spectral.c
scipy/scipy/signal/_upfirdn_apply.c
scipy/scipy/signal/_max_len_seq_inner.cpp
scipy/scipy/signal/_bspline_util.c
scipy/scipy/signal/_sosfilt.c
scipy/scipy/signal/_correlate_nd.c
scipy/scipy/signal/_max_len_seq_inner.c
scipy/optimize/_lsq/givens_elimination.c
scipy/scipy/optimize/_group_columns.cpp
scipy/scipy/optimize/_group_columns.c
scipy/optimize/_trlib/_trlib.c
scipy/optimize/tnc/_moduleTNC.c
scipy/optimize/cython_optimize/_zeros.pyx
scipy/optimize/cython_optimize/_zeros.c
scipy/scipy/optimize/_bglu_dense.c
_highs/cython/src/_highs_wrapper.cxx
_highs/cython/src/_highs_constants.cxx
scipy/scipy/special/_ufuncs.pyi
scipy/scipy/special/cython_special.pyx
special/tests/data/local.npz
special/tests/data/boost.npz
special/tests/data/gsl.npz
scipy/scipy/special/_ellip_harm_2.h
scipy/scipy/special/_ufuncs_cxx.pyx
scipy/scipy/special/_ufuncs.h
scipy/scipy/special/cython_special.c
scipy/scipy/special/_test_round.c
scipy/scipy/special/_ellip_harm_2.c
scipy/scipy/special/_ufuncs.c
scipy/scipy/special/_ufuncs_cxx.pxd
scipy/scipy/special/_ufuncs_cxx.cxx
scipy/scipy/special/_ufuncs_cxx.h
scipy/scipy/special/_ufuncs_defs.h
scipy/scipy/special/cython_special.pxd
scipy/scipy/special/cython_special.h
scipy/scipy/special/_ufuncs_cxx_defs.h
scipy/scipy/special/_ufuncs.pyx
scipy/scipy/special/_comb.c
scipy/scipy/spatial/_voronoi.c
scipy/spatial/transform/_rotation.c
scipy/scipy/spatial/_ckdtree.cxx
scipy/scipy/spatial/_hausdorff.c
scipy/scipy/spatial/_qhull.c
scipy/scipy/_lib/_test_deprecation_def.h
scipy/_lib/highs/.git
scipy/_lib/unuran/.git
scipy/scipy/_lib/_test_deprecation_def.c
scipy/_lib/boost/.git
scipy/scipy/_lib/_test_deprecation_call.c
scipy/scipy/_lib/messagestream.c
scipy/_lib/src/messagestream_config.h
scipy/scipy/_lib/_ccallback_c.c
scipy/scipy/fftpack/convolve.c
scipy/scipy/interpolate/interpnd.c
scipy/scipy/interpolate/_rbfinterp_pythran.cpp
scipy/scipy/interpolate/_bspl.c
scipy/scipy/interpolate/_ppoly.c
source/_static/scipy-mathjax/.git
```

</p>
</details>

To reproduce these results, you can use the script: https://gist.github.com/Smit-create/3ab27ff723a93aae1fbc1c31c31f4b13

**Comment by rgommers** [comment]
`scipy/sparse/csgraph/_flow.c` etc. are Cython generated files. We shouldn't be shipping those anymore. Are we really doing that in the 1.8.0 sdist?

All of these look like generated files, so we don't want to include them.

**Comment by rgommers** [comment]
Thanks @Smit-create, this is quite useful. Can you extend the script also to the contents of a wheel, and then to the files that are actually installed from a wheel?

**Comment by Smit-create** [comment]
> Can you extend the script also to the contents of a wheel, and then to the files that are actually installed from a wheel?

Using the same script, and changing the paths after building wheel from meson and setup.py, I get this missing files in meson wheel:

<details>
<summary> Files </summary>
<p>

```
scipy/sparse/tests/meson.build
sparse/csgraph/tests/meson.build
sparse/linalg/tests/meson.build
linalg/_eigen/tests/meson.build
_eigen/lobpcg/tests/meson.build
linalg/_eigen/lobpcg/setup.py
_eigen/arpack/tests/meson.build
_eigen/arpack/ARPACK/COPYING
linalg/_eigen/arpack/setup.py
sparse/linalg/_eigen/setup.py
linalg/_dsolve/tests/meson.build
linalg/_dsolve/SuperLU/License.txt
sparse/linalg/_dsolve/setup.py
scipy/sparse/linalg/setup.py
linalg/_isolve/tests/meson.build
sparse/linalg/_isolve/setup.py
meson_whl_scipy/scipy/sparse/setup.py
meson_whl_scipy/scipy/sparse/_generate_sparsetools.py
scipy/fft/tests/meson.build
fft/_pocketfft/tests/meson.build
scipy/fft/_pocketfft/setup.py
scipy/fft/_pocketfft/LICENSE.md
meson_whl_scipy/scipy/fft/setup.py
ndimage/tests/data/README.txt
scipy/ndimage/tests/meson.build
meson_whl_scipy/scipy/ndimage/setup.py
meson_whl_scipy/scipy/_build_utils/system_info.py
meson_whl_scipy/scipy/_build_utils/copyfiles.py
meson_whl_scipy/scipy/_build_utils/tempita.py
scipy/_build_utils/tests/__init__.py
scipy/_build_utils/tests/test_scipy_version.py
meson_whl_scipy/scipy/_build_utils/gcc_build_bitness.py
meson_whl_scipy/scipy/_build_utils/compiler_helper.py
meson_whl_scipy/scipy/_build_utils/cythoner.py
meson_whl_scipy/scipy/_build_utils/__init__.py
meson_whl_scipy/scipy/_build_utils/_fortran.py
meson_whl_scipy/scipy/_build_utils/setup.py
scipy/cluster/tests/meson.build
meson_whl_scipy/scipy/cluster/setup.py
tests/data/nist_linregress/meson.build
tests/data/levy_stable/meson.build
stats/tests/data/meson.build
tests/data/nist_anova/meson.build
scipy/stats/tests/meson.build
scipy/stats/_levy_stable/setup.py
meson_whl_scipy/scipy/stats/_hypotests_pythran.py
scipy/stats/_boost/setup.py
meson_whl_scipy/scipy/stats/setup.py
scipy/stats/_unuran/setup.py
dist/meson_whl_scipy/scipy/INSTALL.rst.txt
scipy/integrate/tests/meson.build
scipy/integrate/tests/banded5x5.f
scipy/integrate/tests/banded5x5.pyf
scipy/integrate/tests/_test_multivariate.c
integrate/_ivp/tests/meson.build
scipy/integrate/_ivp/setup.py
linalg/tests/data/meson.build
scipy/linalg/tests/meson.build
meson_whl_scipy/scipy/linalg/_matfuncs_expm.pyi
meson_whl_scipy/scipy/linalg/_cython_signature_generator.py
meson_whl_scipy/scipy/linalg/_matfuncs_sqrtm_triu.py
meson_whl_scipy/scipy/linalg/setup.py
src/id_dist/doc/doc.tex
linalg/src/lapack_deprecations/LICENSE
meson_whl_scipy/scipy/linalg/_generate_pyx.py
dist/meson_whl_scipy/scipy/meson_options.txt
scipy/io/tests/meson.build
io/matlab/tests/gen_mat5files.m
io/matlab/tests/meson.build
io/matlab/tests/afunc.m
io/matlab/tests/gen_mat4files.m
io/matlab/tests/save_matfile.m
scipy/io/matlab/setup.py
io/_harwell_boeing/tests/meson.build
scipy/io/_harwell_boeing/setup.py
io/arff/tests/meson.build
scipy/io/arff/setup.py
meson_whl_scipy/scipy/io/setup.py
dist/meson_whl_scipy/scipy/LICENSES_bundled.txt
dist/meson_whl_scipy/scipy/optimize.pxd
scipy/signal/tests/meson.build
scipy/signal/windows/setup.py
meson_whl_scipy/scipy/signal/setup.py
scipy/odr/tests/meson.build
meson_whl_scipy/scipy/odr/setup.py
scipy/optimize/_lsq/setup.py
scipy/optimize/tests/meson.build
meson_whl_scipy/scipy/optimize/_group_columns.py
scipy/optimize/lbfgsb_src/README
optimize/_trustregion_constr/tests/meson.build
scipy/optimize/_trustregion_constr/setup.py
scipy/optimize/_trlib/setup.py
meson_whl_scipy/scipy/optimize/cython_optimize.pxd
scipy/optimize/_shgo_lib/meson.build
meson_whl_scipy/scipy/optimize/setup.py
scipy/optimize/cython_optimize/setup.py
scipy/optimize/_highs/setup.py
_highs/cython/src/HighsIO.pxd
_highs/cython/src/SimplexConst.pxd
_highs/cython/src/HighsLp.pxd
_highs/cython/src/HighsInfo.pxd
_highs/cython/src/Highs.pxd
_highs/cython/src/HighsRuntimeOptions.pxd
_highs/cython/src/HighsLpUtils.pxd
_highs/cython/src/HighsStatus.pxd
_highs/cython/src/HConst.pxd
_highs/cython/src/HighsOptions.pxd
_highs/cython/src/HighsSparseMatrix.pxd
_highs/cython/src/HighsModelUtils.pxd
_highs/cython/src/highs_c_api.pxd
meson_whl_scipy/scipy/special/_ufuncs.pyi
special/tests/data/README
meson_whl_scipy/scipy/special/_test_round.pyi
scipy/special/_precompute/setup.py
scipy/special/_precompute/hyp2f1_data.py
meson_whl_scipy/scipy/special/cython_special.pyi
meson_whl_scipy/scipy/special/setup.py
meson_whl_scipy/scipy/special/cython_special.pxd
meson_whl_scipy/scipy/special/_orthogonal.pyi
meson_whl_scipy/scipy/special/_generate_pyx.py
scipy/spatial/tests/meson.build
spatial/transform/tests/meson.build
scipy/spatial/transform/setup.py
meson_whl_scipy/scipy/spatial/setup.py
scipy/_lib/_uarray/setup.py
scipy/_lib/_uarray/LICENSE
meson_whl_scipy/scipy/_lib/_boost_utils.py
meson_whl_scipy/scipy/_lib/_highs_utils.py
meson_whl_scipy/scipy/_lib/setup.py
meson_whl_scipy/scipy/_lib/_unuran_utils.py
scipy/misc/tests/meson.build
meson_whl_scipy/scipy/misc/setup.py
dist/meson_whl_scipy/scipy/HACKING.rst.txt
scipy/fftpack/tests/gendata.m
scipy/fftpack/tests/gendata.py
scipy/fftpack/tests/Makefile
scipy/fftpack/tests/meson.build
scipy/fftpack/tests/gen_fftw_ref.py
scipy/fftpack/tests/fftw_dct.c
meson_whl_scipy/scipy/fftpack/setup.py
dist/meson_whl_scipy/scipy/setup.py
dist/meson_whl_scipy/scipy/LICENSE.txt
dist/meson_whl_scipy/scipy/linalg.pxd
scipy/constants/tests/meson.build
meson_whl_scipy/scipy/constants/setup.py
dist/meson_whl_scipy/scipy/mypy_requirements.txt
dist/meson_whl_scipy/scipy/special.pxd
scipy/interpolate/tests/meson.build
meson_whl_scipy/scipy/interpolate/setup.py
dist/meson_whl_scipy/scipy/doc_requirements.txt
```
</p>
</details>

**Comment by FFY00** [comment]
One thing to note here is that meson-python uses `meson dist` to generate the base for the sdist, which when run in a VCS repo will only include the files that are checked in, and will ignore local modifications. That is useful when making releases, and is why Meson does it that way.

Are the files you mention perhaps created at build time, or something that you only have locally?

**Comment by Smit-create** [comment]
> Are the files you mention perhaps created at build time, or something that you only have locally?

I didn't have anything locally, still, I'll try with `git clean -dfx` and try to compare the files again.

**Comment by rgommers** [comment]
As we (@Smit-create and I) just discussed:
- the reason for the different paths (some starting with `/meson_whl_scipy`, some with `scipy/` etc.) is just readability: the script prints only the last 3 path elements
- almost all differences are things that the Meson build gets right and the `distutils` one wrong: build files, generated files, license files, etc.
- the `.pyi` files are missing in the Meson build, @Smit-create will open a separate PR to include them _and_ add a test that iterates over all `.pyi` files in the repo and checks they're all installed in CI
- there's still a FIXME for `cython_special.pxd`, @Smit-create will investigate and open an issue

**Comment by rgommers** [comment]
> One thing to note here is that meson-python uses `meson dist` to generate the base for the sdist, which when run in a VCS repo will only include the files that are checked in, and will ignore local modifications.

This is the thing that needs dealing with in our CI setups. `pyproject.toml` pins to old numpy versions; we need two `pyproject.toml` files - one for release, one for development with unpinned dependencies. We can't just dynamically switch them though in some script, because local modifications aren't picked up by `meson dist`. I have to think about the best strategy for this.

**Comment by rgommers** [comment]
All the missing `.pyi` and `.pxd` files are now correctly installed, so we can get back to this PR.

**Comment by rgommers** [comment]
> This is the thing that needs dealing with in our CI setups. `pyproject.toml` pins to old numpy versions; we need two `pyproject.toml` files - one for release, one for development with unpinned dependencies. We can't just dynamically switch them though in some script, because local modifications aren't picked up by `meson dist`. I have to think about the best strategy for this.

xref https://github.com/FFY00/mesonpy/issues/29 for more details and a possible strategy.

**Comment by rgommers** [comment]
> > 
> 
> xref [FFY00/meson-python#29](https://github.com/FFY00/meson-python/issues/29) for more details and a possible strategy.

I decided that just adding the `numpy==` pins in maintenance branches wasn't going to work. That would break CI in many ways, and also make it quite annoying to work on maintenance branches locally. So I went with what I think is a better approach in gh-16187.

**Comment by rgommers** [comment]
Closing in favor of gh-16187.

**Pull request closed without merging**
