### PR TITLE
ENH: Add `max_events` parameter for flexible termination of scipy.solve_ivp

### LINKED ISSUE #14176: Add option for terminating solver after n events
The [IVP solver in scipy](https://github.com/scipy/scipy/blob/2c72ae27e59e64f47d64bf65800a291ff972df86/scipy/integrate/_ivp/ivp.py#L156) is a flexible and useful initial value solver. One feature that I greatly appreciate is the ability for the solver to locate "events", and allow those events to be "terminal" (i.e., the integrator will stop when an event is found).

It would be really useful if the event handler in this solver could be extended so that the integration will stop after some number of "events" occurs. So instead of only having two options (_not terminal_ and _terminal at the first event_), the user would then be able to specify something like _terminal after n events_.

### PR DESCRIPTION
**Pull request by arichar6**
#### Reference issue
Closes gh-14176

#### What does this implement/fix?
This PR adds a parameter to the solve_ivp function which allows a user to specify that integration should terminate after an event has occurred `max_events` times.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @arichar6! I assume this is marked as draft because it still needs a unit test?

@drhagen @nmayorov it'd be great if one of you could have a look at this.

**Comment by arichar6** [comment]
Yes, it needs a test, and also some documentation. It's also still a draft because I'm not really sure what the best API would be for this. 

I really like how the current API allows multiple different events, each with their own `terminal` parameter. The most natural extension to this would be to allow each event type to have it's own `max_events`, but I'm not quite sure how to implement that, and track it. 

So right now I have just a single `max_events` parameter, and am checking all events against this max. Maybe instead each event should have a `max_events` attribute? Then this code would have to separately compare each max to the number of events (of that type) that have been found.

**Comment by drhagen** [comment]
I proposed an API over [at the original issue](https://github.com/scipy/scipy/issues/14176#issuecomment-883280721). We can discuss it here if you like.

> This sounds like a good feature to me. One thing to note is that the current `terminal` behavior is equivalent to terminating after 1 event, so the most appropriate API would be deprecating `terminal` as an attribute on the event and replacing it with `max_events` or some similar name with a default of `inf`.
>
> This would be a somewhat disruptive deprecation, but the deprecation period could be very long because it is not particularly bad to have these features side-by-side. In the interim, I would propose that setting both `terminal` and `max_events` would be an error. Setting `terminal=True` would be equivalent to `max_events=1`.

**Comment by arichar6** [comment]
Thanks for reposting here... I missed your proposal somehow. 

I like your idea of using a `max_events` attribute. It seems like allowing _either_ `max_events` _or_ `terminal` could be a good way to go. If it's possible to raise an error when both attributes are set, then I don't see the need to deprecate the `terminal` attribute option. Under the hood it could just set `max_events = 1`.

I will try to find some time to implement this API to see how it would work. If someone else gets to it before me, I won't be upset 😉

**Comment by drhagen** [comment]
> I don't see the need to deprecate the `terminal` attribute option.

As the Zen of Python says: "There should be one-- and preferably only one --obvious way to do it."

**Comment by arichar6** [comment]
Good point. And it would help keep the code clean if the `terminal` attribute/API is deprecated and eventually removed. I'm in favor of clean code, even though I don't always manage to keep my code as clean as I would like it to be.

**Comment by Patol75** [comment]
I have put together this [commit](https://github.com/Patol75/scipy/commit/831df2f01d36b0e76f53c4c80db88f30e81d1cbb) which allows for a maximum number of event occurrences without deprecating `terminal` or breaking backwards compatibility.

The commit can be tested using a simple snippet such as

```
from scipy.integrate import solve_ivp


def fun(t, y):
    return y / t


def event1(t, y):
    return 2 - t if t < 4 else t - 4


def event2(t, y):
    return 3 - t


event1.terminal = 2
event2.terminal = True
res = solve_ivp(fun, (1, 5), [0], events=(event1, event2), max_step=0.5)
print(res.t)
```

Happy to have your thoughts about it.

**Comment by drhagen** [comment]
I don't think there is any question that this should be added. The only question is should this feature be called `terminal`, `max_events`, or `terminate_after`. Attributes of type `int` are typically nouns, which is why I prefer `max_events`. But I would support merging either of @Patol75's commits if a core member made a decision on the attribute name.

**Comment by Patol75** [comment]
@rgommers @nmayorov @tylerjereddy @tupui Could any of you provide some advice about which attribute name to move on with? I am happy to amend either commit, though I think the second one makes more sense. Additionally, I will modify relevant existing tests to account for the new functionality.

**Comment by rgommers** [comment]
I'm happy with `max_events`, the rationale for it makes sense.

**Comment by Patol75** [comment]
Thanks @rgommers. I have pushed a third commit to my [branch](https://github.com/Patol75/scipy/tree/Max_Events_Solve_IVP).

@drhagen If you are happy with the proposed changes, how should I go about including the changed files in this PR? I have not done it before, and I am unsure about how to proceed.

**Comment by drhagen** [comment]
> If you are happy with the proposed changes, how should I go about including the changed files in this PR?

@Patol75 Thank you for taking the lead on this. Your best best is probably to make a new PR, reference this PR in the description, and summarize the decisions so far.

**Comment by mdhaber** [comment]
Looks like this has been superseded by gh-14771. Thanks @arichar6!

**Pull request closed without merging**
