### PR TITLE
MAINT: scipy.sparse cleanup

### PR DESCRIPTION
**Pull request by larsmans**
Small changes to the C++ code: mostly removing dead code, one micro-optimization. I was trying to get the module to compile faster and produce smaller binaries, but the effect is quite marginal. I thought I'd still offer my changes for review.

### CODE REVIEW

**Comment by argriffing** [comment]
If the `#if 0` blocks are unused should they be deleted?

**Comment by pv** [comment]
sizeof(bool) is unspecified, so it cannot be used in npy_bool_wrapper.
This structure is supposed to wrap numpy bool, which is same as char.

**Comment by pv** [comment]
Also, Numpy normalizes bool values on assign to 0 and 1, so I believe
the original code here was correct in doing that also.

**Comment by larsmans** [comment]
Changed back to `char`. @pv the `npy_bool_wrapper` constructors still normalize:

```c++
npy_bool_wrapper() {
    value = 0;
}
template <class T>
npy_bool_wrapper(T x) {
    value = (x != 0);
}
```

The other operations don't need to do explicit normalization since they use `||` etc.

**Comment by larsmans** [comment]
@argriffing The code might be useful in the future, so I've left it in there.

**Comment by pv** [comment]
I think the policy is to remove it: if it's useful in the future, it can
be found in the version history. The routines also look simple enough to
write from scratch in any case.

**Comment by larsmans** [comment]
Removed the dead code.

**Comment by larsmans** [comment]
Ping?

**Comment by larsmans** [comment]
@pv Can I merge all but the last commit?

**Comment by larsmans** [comment]
Ping?

**Comment by pv** [comment]
lgtm

**Comment by larsmans** [comment]
Thanks!

**Pull request merged**
