### PR TITLE
MAINT: special: refactor `ufunc.h` and move to `xsf`

### PR DESCRIPTION
**Pull request by izaid**
Putting things in `ufunc.h` in a namespace, also pulling useful definitions out of .cpp files

### CODE REVIEW

**Comment by izaid** [comment]
This is done, cc @steppi

**Review by steppi — APPROVED** [review]
Thanks @izaid. This looks good. I think it's a good idea to split the ufunc generation code off into `xsf` rather than having it in SciPy and for specifying ufunc loops, I think patterns like `xsf::numpy::dd_D2D3D4` look cleaner than `func_dd_D2D3D4`.

The linter failure seems to be a false positive. `_special_ufuncs.cpp` and `_gufuncs.cpp` each have `xsf/numpy.h` as their first include and `xsf/numpy.h` has `Python.h` as its first include. @DWesl, any idea what's going on here?

```
Run python tools/check_python_h_first.py 
Python.h not included before python-including header in file scipy/special/_special_ufuncs.cpp
xsf/numpy.h on line 1
Header before Python.h in file scipy/special/_special_ufuncs.cpp
Python.h on line 34, other header(s) on line(s) [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33]
Python.h not included before python-including header in file scipy/special/_gufuncs.cpp
xsf/numpy.h on line 1
```

I'll hold off on merging until this is sorted out.

**Comment by steppi** [comment]
We can fix the linter false positive by adding `"xsf/numpy"` to the list of Python including headers here, https://github.com/scipy/scipy/blob/f35d9dc6f75665ba125b49980dc3af1d54623554/tools/check_python_h_first.py#L17-L39

It seems that when `xsf` is split into it's own library, this will be the correct course of action anyway, so I see no harm in doing this.

**Comment by DWesl** [comment]
> The linter failure seems to be a false positive. `_special_ufuncs.cpp` and `_gufuncs.cpp` each have `xsf/numpy.h` as their first include and `xsf/numpy.h` has `Python.h` as its first include. @DWesl, any idea what's going on here?
> 
> ```
> Run python tools/check_python_h_first.py 
> Python.h not included before python-including header in file scipy/special/_special_ufuncs.cpp
> xsf/numpy.h on line 1
> Header before Python.h in file scipy/special/_special_ufuncs.cpp
> Python.h on line 34, other header(s) on line(s) [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33]
> Python.h not included before python-including header in file scipy/special/_gufuncs.cpp
> xsf/numpy.h on line 1
> ```

The first error looks like it doesn't know `xsf/numpy.h` is careful about including Python.h yet, which you can fix by adding that header to the list here:
https://github.com/scipy/scipy/blob/149f9fd32a1bdf1010944706b840c06816ea6a2f/tools/check_python_h_first.py#L38
The second error looks like it doesn't set `included_python = True` around line 122 of that script, so it notes those errors as well.  Fixing the first error will make the second go away.
The third error is the same as the first.

**Comment by steppi** [comment]
Thanks @DWesl, the latest CI results confirm that adding "xsf/numpy.h" to the list of python including headers worked.

**Pull request merged**
