### PR TITLE
ENH symmetrise in-place in scipy.spatial.distance.squareform to avoid MemoryError

### PR DESCRIPTION
**Pull request by jnothman**
The current copying approach in `squareform` is slower and prone to using all available memory for large distance matrices.

### CODE REVIEW

**Comment by pv** [comment]
This doesn't work since the order of operations is not guaranteed

**Comment by ewmoore** [comment]
The way to reduce the memory requirements here is to fill out the full square form array instead of just half of it in the C code.

**Comment by jnothman** [comment]
Ah of course. Thanks, @pv. For some reason I just assumed numpy would work it out.

**Comment by perimosocordiae** [comment]
I was somewhat surprised to see @pv's issue; I had thought the `X += X.T` was standard shorthand for symmetrizing. In fact, it's present in both scipy and scikit-learn (albeit in testing code):

 * https://github.com/scipy/scipy/blob/e758c482efb8829685dcf494bdf71eeca3dd77f0/scipy/sparse/linalg/dsolve/tests/test_linsolve.py#L349

* https://github.com/scikit-learn/scikit-learn/blob/8dab222cfe894126dfb67832da2f4e871b87bce7/sklearn/utils/tests/test_shortest_path.py#L37

Should these be reported as bugs?

**Comment by jaimefrio** [comment]
If the arrays are small it works, because the sum is done with buffering:

```
>>> np.getbufsize()
8192

>>> x = np.random.rand(90, 90)
>>>x.size  # smaller than buffer
8100
>>> y = x.copy()
>>> x += x.T
>>> np.allclose(x, y+y.T)
True

>>> x = np.random.rand(91, 91)
>>> x.size  # larger than buffer
8281
>>> y = x.copy()
>>> x += x.T
>>> np.allclose(x, y+y.T)
False
```

This is nevertheless an implementation detail subject to change without notice, and is therefore an accident waiting to happen. Yes, they should be reported as bugs!

**Comment by ewmoore** [comment]
To get this to send an email, I've made a pr with my proposed fix in #4404.

**Comment by pv** [comment]
@perimosocordiae: yes, that's a bug... ditto for the scikit-learn

**Comment by jnothman** [comment]
For reference, @pv, is there a fast, non-copying way to perform this in high-level numpy?

**Comment by pv** [comment]
Not that I know of.

The reason why Numpy doesn't automatically figure out the correct in-place order is that the general problem is NP-hard (IIRC). There have been some proposals to heuristically detect when a copy is really needed (won't help with the memory usage), but nobody has come up with a satisfactory implementation as far as I remember.

**Comment by jnothman** [comment]
> The reason why Numpy doesn't automatically figure out the correct in-place order is that the general problem is NP-hard (IIRC).

But determining that what the user requested is probably not what they mean is likely not NP hard, such that a warning could be issued?

**Comment by pv** [comment]
@jnothman: IIRC already checking whether two strided arrays overlap in memory is [apparently NP-complete](http://permalink.gmane.org/gmane.comp.python.numeric.general/22273). Simpler heuristics are possible if you are happy with false positives.

**Comment by jnothman** [comment]
Right, interesting. Thanks!

**Pull request closed without merging**
