### PR TITLE
Included blank line before list - Fixes #8658

### LINKED ISSUE #8658: DOC: bad reST in scipy.optimize/_root.py
The docstring of ``_root_broyden1_doc`` or ``_root_broyden2_doc`` have wrong mark-up

https://github.com/scipy/scipy/blob/master/scipy/optimize/_root.py#L347-L357

According to [Docutils documentation](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#bullet-lists), lists must be separated by a blank line from contents before. As a result this is mis-interpreted as a [definition list](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#definition-lists) as seen here https://docs.scipy.org/doc/scipy/reference/optimize.root-broyden1.html.

### PR DESCRIPTION
**Pull request by FranzForstmayr**
Fixes gh-8658

### CODE REVIEW

**Comment by ilayn** [comment]
Thanks @FranzForstmayr Just for the future reference, please make separate branches to work on new features and to send PRs such that your standard working repo does not interfere with the PRs you have submitted. Once a PR is merged you can safely delete that branch and keep working on other branches.

**Comment by ilayn** [comment]
Doesn't seem to fix the issue though https://10294-1460385-gh.circle-artifacts.com/0/html-scipyorg/optimize.root-broyden1.html Maybe the `-`s confusing it.

**Comment by FranzForstmayr** [comment]
This should work now, i removed the `:` character

**Comment by rgommers** [comment]
@FranzForstmayr why all those extra line breaks? that should not be necessary.

also, have you tried building the docs locally? that's usually a lot easier than trying on our CI.

**Comment by FranzForstmayr** [comment]
I throught it should be a list, with an additional description for each element in the following line. 
Do you have a reference, how it should be done? 
The first commit was without local build, because i had troubles first. The second one was built in my local machine and I thought this is correct.

**Pull request merged**
