### PR TITLE
ENH: Wrapped RFP format and RZ decomposition routines

### LINKED ISSUE #8212: LAPACK Rectangular Full Packed routines
`scipy.linalg.lapack` does not expose the LAPACK routines using the [Rectangular Full Packed storage (RFP)](https://software.intel.com/en-us/mkl-developer-reference-c-matrix-storage-schemes-for-lapack-routines#RFP_STORAGE) for upper triangular, lower triangular, symmetric, or Hermitian matrices. This includes 

- rank-k operations ([xfrk](https://software.intel.com/en-us/mkl-developer-reference-c-sfrk))
- triangular system ([xtfsm](https://software.intel.com/en-us/mkl-developer-reference-c-tfsm))
- Cholesky:  factorise ([xpftrf](https://software.intel.com/en-us/mkl-developer-reference-c-pftrf)), solve ([xpftrs](https://software.intel.com/en-us/mkl-developer-reference-c-pftrs)), and inverse ([xpftri](https://software.intel.com/en-us/mkl-developer-reference-c-pftri))
- copy from RFP to standard packed format ([xtfttp](https://software.intel.com/en-us/node/521386)), and the reverse conversion ([tpttf](https://software.intel.com/en-us/mkl-developer-reference-c-tpttf))

### PR DESCRIPTION
**Pull request by ilayn**
Closes #8212 

As discussed in the linked issue, RFP related routines are wrapped. Additionally, the so-called upper trapezoidal fat matrix RZ decomposition (`M = [R 0] * Z`)routines are added. I've seen that this has been [brought up in the mailing list ](https://mail.python.org/pipermail/scipy-user/2014-September/thread.html)a few years ago; later is better than never I guess.

The remaining task is adding tests. Pinging @luc-j-bourhis for a helping hand about the RFP examples.

### CODE REVIEW

**Comment by ilayn** [comment]
In one of the arguments in the wrappers the default value relies on a character value in the form of `*uplo`. But documentation treats this as an inline emphasis and looks for a matching `*` and then trips. 

How can we exclude these routines from the refcheck?

**Comment by rgommers** [comment]
test failures here are real

**Comment by rgommers** [comment]
ah, hence your question.

**Comment by rgommers** [comment]
probably just escaping it: `\*side`

**Comment by ilayn** [comment]
The error is generated through `validate_rst_syntax()` in `refguide_check.py`. Since the docs are autogenerated by f2py I don't have a way to alter the documentation. I'll try to look for another way to wrap this routine.

**Comment by ilayn** [comment]
Exactly what I had in mind :)

**Comment by ilayn** [comment]
OK, things are green again. This can be reviewed.

**Comment by ilayn** [comment]
I am inclined to merge this in a few days. Feedback is always welcome.

**Comment by rgommers** [comment]
All green and tests look good, so sounds fine to me.

**Pull request merged**
