### PR TITLE
Optional reflection padding in medfilt and medfilt2d

### PR DESCRIPTION
**Pull request by bmcfee**
By default, `signal.medfilt` and `signal.medfilt2d` zero-pad the input data prior to filtering.  This causes a winnowing toward 0 in the output near the boundaries.

This PR adds support for reflection padding, so that the filter is only computed on data derived from the input.

The previous behavior (zero-padding) is retained as the default.

Example:

``` python
In [19]: X = np.random.randint(100, 200, (8, 8)).astype(float)

In [20]: X
Out[20]: 
array([[ 185.,  158.,  165.,  108.,  163.,  106.,  165.,  166.],
       [ 148.,  138.,  135.,  143.,  111.,  161.,  154.,  118.],
       [ 151.,  104.,  187.,  141.,  143.,  193.,  195.,  195.],
       [ 175.,  193.,  118.,  115.,  190.,  187.,  152.,  114.],
       [ 154.,  182.,  142.,  193.,  116.,  169.,  152.,  114.],
       [ 107.,  120.,  153.,  193.,  104.,  128.,  120.,  145.],
       [ 193.,  155.,  113.,  110.,  151.,  123.,  143.,  195.],
       [ 140.,  134.,  170.,  102.,  197.,  149.,  163.,  149.]])

In [21]: scipy.signal.medfilt2d(X, 3, reflect=False)
Out[21]: 
array([[   0.,  138.,  135.,  111.,  108.,  111.,  118.,    0.],
       [ 138.,  151.,  141.,  143.,  143.,  161.,  165.,  154.],
       [ 138.,  148.,  138.,  141.,  143.,  161.,  161.,  118.],
       [ 151.,  154.,  142.,  142.,  169.,  169.,  169.,  114.],
       [ 120.,  153.,  153.,  142.,  169.,  152.,  145.,  114.],
       [ 120.,  153.,  153.,  142.,  128.,  128.,  143.,  120.],
       [ 120.,  140.,  134.,  151.,  128.,  143.,  145.,  143.],
       [   0.,  134.,  110.,  110.,  110.,  143.,  143.,    0.]])

In [22]: scipy.signal.medfilt2d(X, 3, reflect=True)
Out[22]: 
array([[ 148.,  148.,  138.,  135.,  143.,  154.,  154.,  154.],
       [ 148.,  151.,  141.,  143.,  143.,  161.,  165.,  165.],
       [ 148.,  148.,  138.,  141.,  143.,  161.,  161.,  154.],
       [ 175.,  154.,  142.,  142.,  169.,  169.,  169.,  152.],
       [ 175.,  153.,  153.,  142.,  169.,  152.,  145.,  145.],
       [ 155.,  153.,  153.,  142.,  128.,  128.,  143.,  143.],
       [ 134.,  140.,  134.,  151.,  128.,  143.,  145.,  145.],
       [ 155.,  155.,  113.,  113.,  123.,  149.,  149.,  149.]])
```

### CODE REVIEW

**Comment by rgommers** [comment]
This fails on numpy 1.6.2 because that doesn't have ``pad``. Is there an easy way around that (guess not)? Otherwise ``pad`` could be added to ``scipy._lib._numpy_compat``.

**Comment by rgommers** [comment]
About the API: it's possible that more padding methods are desired later right? Then it would be more extensible to have a keyword ``pad='zeros'`` than a boolean.

**Comment by bmcfee** [comment]
> This fails on numpy 1.6.2 because that doesn't have pad. Is there an easy way around that (guess not)? Otherwise pad could be added to scipy._lib._numpy_compat.

I'd personally vote for the latter, since it would make my job easier. :)

> About the API: it's possible that more padding methods are desired later right? Then it would be more extensible to have a keyword pad='zeros' than a boolean.

In general, yeah, there's no technical reason to limit it to zeros/reflection. However, reflection padding is pretty standard for median filters.  Edge, ramp, or wrap padding wouldn't make much sense here, IMO, but it's easy enough to support.

It's entirely possible that this same pattern (pad-filter-trim) would crop up in other multidimensional filtering problems where several padding options would make sense.  Given that nearly identical code already shows up twice (medfilt and medfilt2d), maybe it would make sense to abstract this functionality out so that it can be applied in general?  I'm not sure how best to structure something like that, but I'm open to suggestions.

**Comment by WarrenWeckesser** [comment]
For reference, here are a few other places where padding an input is an option.

`scipy.ndimage.convolve`, the filters in `scipy.ndimage.filters` (e.g. `gaussian_filter`), and other `ndimage` functions have `mode` and `cval` arguments to control the padding:

    convolve(input, weights, output=None, mode='reflect', cval=0.0, origin=0)
        mode : {'reflect','constant','nearest','mirror', 'wrap'}, optional
            the `mode` parameter determines how the array borders are
            handled. For 'constant' mode, values beyond borders are set to be
            `cval`. Default is 'reflect'.
        cval : scalar, optional
            Value to fill past edges of input if `mode` is 'constant'. Default
            is 0.0

`scipy.signal.savgol_filter` is similar:

    savgol_filter(x, window_length, polyorder, deriv=0, delta=1.0, axis=-1, mode='interp', cval=0.0)
        mode : str, optional
            Must be 'mirror', 'constant', 'nearest', 'wrap' or 'interp'.  This
            determines the type of extension to use for the padded signal to
            which the filter is applied.  When `mode` is 'constant', the padding
            value is given by `cval`.  See the Notes for more details on 'mirror',
            'constant', 'wrap', and 'nearest'.
            When the 'interp' mode is selected (the default), no extension
            is used.  Instead, a degree `polyorder` polynomial is fit to the
            last `window_length` values of the edges, and this polynomial is
            used to evaluate the last `window_length // 2` output values.
        cval : scalar, optional
            Value to fill past the edges of the input if `mode` is 'constant'.
            Default is 0.0.


`scipy.signal.filtfilt` has different arguments for padding:

    filtfilt(b, a, x, axis=-1, padtype='odd', padlen=None)
        padtype : str or None, optional
            Must be 'odd', 'even', 'constant', or None.  This determines the
            type of extension to use for the padded signal to which the filter
            is applied.  If `padtype` is None, no padding is used.  The default
            is 'odd'.
        padlen : int or None, optional
            The number of elements by which to extend `x` at both ends of
            `axis` before applying the filter. This value must be less than
            `x.shape[axis]-1`.  `padlen=0` implies no padding.
            The default value is 3*max(len(a),len(b)).

**Comment by WarrenWeckesser** [comment]
I guess the redundancy between `scipy.signal` and `scipy.ndimage` is because of "historical reasons".  It turns out we already have a median filter that does padding: `scipy.ndimage.median_filter`.  For example:
```
In [30]: from scipy.ndimage import median_filter

In [31]: from scipy import signal

In [32]: x = 1.0*np.random.randint(0, 9, size=(5,5))

In [33]: x
Out[33]: 
array([[ 2.,  1.,  4.,  5.,  6.],
       [ 5.,  0.,  6.,  2.,  2.],
       [ 1.,  6.,  6.,  1.,  5.],
       [ 3.,  0.,  7.,  6.,  1.],
       [ 6.,  3.,  3.,  2.,  6.]]) 

In [34]: signal.medfilt2d(x, 3)
Out[34]: 
array([[ 0.,  1.,  1.,  2.,  0.],
       [ 1.,  4.,  4.,  5.,  2.],
       [ 0.,  5.,  6.,  5.,  1.],
       [ 1.,  3.,  3.,  5.,  1.],
       [ 0.,  3.,  2.,  2.,  0.]])

In [35]: median_filter(x, 3, mode='constant', cval=0)
Out[35]: 
array([[ 0.,  1.,  1.,  2.,  0.],
       [ 1.,  4.,  4.,  5.,  2.],
       [ 0.,  5.,  6.,  5.,  1.],
       [ 1.,  3.,  3.,  5.,  1.],
       [ 0.,  3.,  2.,  2.,  0.]])
```

Should we simply deprecate `scipy.signal.medfilt2d`?  (We could keep `scipy.signal.medfilt`, and in future give it an `axis` argument so it can be used to filter 1-d slices of an n-d array.)

**Comment by rgommers** [comment]
I agree that there's no reason for ``medfilt2d`` to exist - the specialized C code could simply be called from ``medfilt`` for 2-D inputs of the handled types. This is kind of orthogonal to this PR however, unless you want to also deprecate ``medfilt``. ``medfilt`` is duplicate with ``ndimage``, but it fits in ``signal`` as well (there's many other filter functions). Keeping that and adding an ``axis`` argument makes sense to me.

I suggest to seperate that deprecation from this PR.

**Comment by rgommers** [comment]
So then this PR should use a signature with ``mode='constant', cval=0`` I guess.

**Comment by rgommers** [comment]
Adding ``pad`` to ``_lib._numpy_compat`` would be OK with me.

**Comment by rgommers** [comment]
This also needs a rebase.

**Comment by WarrenWeckesser** [comment]
You're right, `medfilt` could also be replaced with `median_filter`.  We could reimplement `medfilt` and `medfilt2d` as:

```
import scipy.ndimage as ndi

# scipy.signal.medfilt could be replaced with:

def medfilt(volume, kernel_size=None):
    if volume is None:
        # Weird special case for scipy.signal.medfilt.  There is
        # a unit test that scipy.signal.medfilt(None) doesn't raise
        # an exception.  In fact, it returns array([0], dtype=object),
        # but I don't know why that should be considered correct.
        volume = [0]
    volume = atleast_1d(volume)
    if kernel_size is None:
        kernel_size = [3] * len(volume.shape)
    kernel_size = np.asarray(kernel_size)
    if kernel_size.shape == ():
        kernel_size = np.repeat(kernel_size.item(), volume.ndim)

    result = 1.0*ndi.median_filter(volume, size=kernel_size, mode='constant', cval=0)

    return result


# scipy.signal.medfilt2d could be replaced with:

def medfilt2d(input, kernel_size=3):
    image = asarray(input)
    if kernel_size is None:
        kernel_size = [3] * 2
    kernel_size = np.asarray(kernel_size)
    if kernel_size.shape == ():
        kernel_size = np.repeat(kernel_size.item(), 2)

    for size in kernel_size:
        if (size % 2) != 1:
            raise ValueError("Each element of kernel_size should be odd.")

    result = 1.0*ndi.median_filter(image, size=kernel_size, mode='constant', cval=0)

    return result
```

I'm not proposing that we actually do this, but it means we don't lose much if, instead of improving `medfilt` and `medfilt2d`, we deprecate them and point users to `scipy.ndimage.median_filter`.  Also note that `median_filter` is much faster than `medfilt`, and is comparable to `medfilt2d` in the 2-d case.


Here's what I propose:

* Close this PR, because the desired capability is already available in `scipy.ndimage.median_filter`, and we shouldn't add code that increases the duplication.
* Make changes to `medfilt` and `medfilt2d`:
  * Add a note to the docstrings about the increased capabilities of `scipy.ndimage.median_filter`.  In particular, point out the increased padding options.
  * Optionally, deprecate `medfilt` and `medfilt2d`.

The `axis` argument is an option that could be added to the `ndimage` function.

**Comment by bmcfee** [comment]
> Close this PR, because the desired capability is already available in scipy.ndimage.median_filter, and we shouldn't add code that increases the duplication.
> Make changes to medfilt and medfilt2d:
> Add a note to the docstrings about the increased capabilities of scipy.ndimage.median_filter. In particular, point out the increased padding options.
> Optionally, deprecate medfilt and medfilt2d.

Fair enough, I agree with all of those points.  (My bad for not realizing that the ndimage version already did this, sorry!)

**Comment by WarrenWeckesser** [comment]
> My bad for not realizing that the ndimage version already did this, sorry!

No need to apologize!  Once you found `medfilt`, why would you expect there to be another implementation of the same function somewhere else in the library?

**Pull request closed without merging**
