### PR TITLE
TST: special: simplify `Arg`

### PR DESCRIPTION
**Pull request by person142**
This fixes a couple of things:

- Before the `TestSystematic` tests in `test_mpmath` could severely
   overestimate the desired number of points.
- Before the spread of points returned from `Arg` could be fairly
   different than what was requested.

Note, however, that this changes the test points for a lot of tests. (And requires tweaking tolerances accordingly.) On the one hand, the points we thought we were testing at weren't necessarily the points we were testing at. On the other hand, there's a lot of potential for this to break things and make us have to track down a new crop of failures.

Examples
----------

```
>>> import scipy
>>> scipy.__version__
'0.19.0'
>>> from scipy.special._mptestutils import Arg, ComplexArg, get_args
>>> args = get_args([Arg(), ComplexArg()], 500)
>>> args.shape
(9261, 2)
>>> Arg(-200, 200).values(20)
array([ -1.00000000e+01,  -9.00000000e+00,  -5.50000000e+00,
        -1.00000000e+00,  -6.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -3.16227766e-16,  -1.00000000e-30,
         0.00000000e+00,   1.00000000e-30,   3.16227766e-16,
         1.00000000e-01,   2.00000000e-01,   6.00000000e-01,
         1.00000000e+00,   5.50000000e+00,   9.00000000e+00,
         1.00000000e+01])
```

```
>>> import scipy
>>> scipy.__version__
'1.1.0.dev0+59d4448'
>>> from scipy.special._mptestutils import Arg, ComplexArg, get_args
>>> args = get_args([Arg(), ComplexArg()], 500)
>>> args.shape
(546, 2)
>>> Arg(-200, 200).values(20)
array([ -2.00000000e+02,  -5.15260277e-02,  -1.32746577e-05,
        -3.41995189e-09,  -8.81082680e-13,  -2.26993453e-16,
        -5.84803548e-20,  -1.50663019e-23,  -3.88153345e-27,
        -1.00000000e-30,   0.00000000e+00,   1.00000000e-30,
         1.09050773e-26,   1.18920712e-22,   1.29683955e-18,
         1.41421356e-14,   1.54221083e-10,   1.68179283e-06,
         1.83400809e-02,   2.00000000e+02])
```

### CODE REVIEW

**Comment by person142** [comment]
This will probably also continue to improve on the test speedups in https://github.com/scipy/scipy/pull/7507.

**Comment by pv** [comment]
The question now is: do you really want a logspace distribution, or is it more important to test numbers of order 1?

**Comment by person142** [comment]
> The question now is: do you really want a logspace distribution, or is it more important to test numbers of order 1?

Some thoughts: what I'd like to see is the mpmath tests restricting the range of `Arg`/`ComplexArg` more often and then removing the use of `exception_to_nan` and `nan_ok=True`. I think the latter two features often make you think functions work in ranges where they don't. (For a recent example, in https://github.com/scipy/scipy/pull/8028 I realized that only about 30 points were actually getting checked for `lambertw`.)

If the range of `Arg`/`ComplexArg` is restricted, then I think a logspace distribution is appropriate. (Perhaps the default small value around 0 should be larger than `1e-30` though.) So in my mind:

- With the ideal versions of the tests this selection of points would be ok
- We don't have the ideal versions of the tests
- We don't want to change test points very frequently
- Given all that, is it ok to change them now?

**Comment by person142** [comment]
And the right restriction for `Arg`/`ComplexArg` would be something like "go a couple of orders of magnitude beyond the boundary of the final transition between methods".

**Comment by pv** [comment]
On the other hand, we are not necessarily limited to a single version of the `Arg` class.
Changing the distribution to log-space in most existing tests would probably make them mostly test points far out in the tails of the functions.

**Comment by person142** [comment]
Ok, I'll change this to stick closer to the original points while (1) returning exactly `n` points and (2) always including the endpoints (unless `inclusive_a` or `inclusive_b` are `False`.)

**Comment by person142** [comment]
Closing in favor of https://github.com/scipy/scipy/pull/8096.

**Pull request closed without merging**
