### PR TITLE
Issue5047

### PR DESCRIPTION
**Pull request by pizzathief**

### CODE REVIEW

**Comment by charris** [comment]
Did you hit the `details` button and click on the failing test? Doesn't look like anything basic.
```
===============

scipy.constants

===============

scipy.constants.precision

-------------------------

File "build/testenv/lib/python2.7/site-packages/scipy/constants/codata.py", line 1281, in precision

Failed example:

    codata.precision(u'proton mass')

Expected:

    4.96226989798e-08

Got:

    1.2555138746605121e-08

ERROR: refguide or doctests have errors
```

**Comment by pizzathief** [comment]
I can only see a single test for the values of CODATA 2014, and that was the precision of "proton mass", Which I had to change anyway.  Is it worth writing tests that will pull constants from the CODATA web site, and compare them to whats in codata.py ?

**Comment by pv** [comment]
cf gh-5140

**Comment by rgommers** [comment]
Because gh-5140 was merged this PR is not needed anymore (it's basically identical), hence closing. 

@pizzathief thank you for your contribution, and sorry that no one noticed the duplication immediately after you opened this PR.

**Comment by rgommers** [comment]
@pizzathief for future reference: Github is very good at cross-linking, the open PR adding CODATA 2014 was already linked from gh-5047 when you opened this PR. It is usually a good idea to check cross-links on issues.

**Pull request closed without merging**
