### PR TITLE
DOC: Fixed build instructions in index.rst (#19568)

### LINKED ISSUE #19568: DOC/DX: `cd scipy` missing from 'Building from source'
### Issue with current documentation:

As reported by @tensionhead in https://github.com/scipy/scipy/issues/19563#issuecomment-1819311666:

```
git clone https://github.com/scipy/scipy.git
cd scipy # this one is missing in the doc, but Ok :)
git submodule update --init
```

### Idea or request for content:

Include `cd scipy` in the instructions on https://scipy.github.io/devdocs/building/index.html.

### Additional context (e.g. screenshots, GIFs)

image

### PR DESCRIPTION
**Pull request by abastola0**
#### Reference issue
Closes #19568 19568

#### What does this implement/fix?
Fix the documentation on building scipy

### CODE REVIEW

**Review by lucascolley — CHANGES_REQUESTED** [review]
Hi @abastola0, your change looks good, please could you also add this line in the other two places in this file where `git submodule ...` is used after `git clone ...`?

**Comment by abastola0** [comment]
i think these three commits are redundant. do you want me to squash all them to one?

**Review by lucascolley — APPROVED** [review]
LGTM!

**Comment by j-bowhay** [comment]
> i think these three commits are redundant. do you want me to squash all them to one?

for a simple pr like this we will just squash merge

**Review by j-bowhay — APPROVED** [review]

**Comment by lucascolley** [comment]
thanks for your first contribution to SciPy @abastola0 !

**Comment by abastola0** [comment]
> thanks for your first contribution to SciPy @abastola0 !

Thanks Lucas.

**Pull request merged**
