### PR TITLE
WIP: add support for nan_policy to stats.median_test

### PR DESCRIPTION
**Pull request by inoryy**
PR for #5114.

I've made use of private method `stats._contains_nan` - my reasoning is that it didn't make sense to copy/paste same method into `morestats.py`, but it's not generally useful enough to make it public either.

### CODE REVIEW

**Comment by Inoryy** [comment]
There's 2 build errors now:

* An exception raised by `nbelow = count_nonzero(sample < grand_median)`, which obviously fails if we have `grand_median = nan` value. How should we proceed in such scenario?

* Not sure how or why this happens:
```
Items are not equal:
 ACTUAL: 4.5
 DESIRED: nan
```

It works for me locally. Doesn't even make sense for it to be `4.5` from `[1,2,nan,4,5,6]` test set?

**Comment by rgommers** [comment]
Thanks for picking this up @Inoryy.

The answer 4.5 is correct, because it's an array of length 6 with the median being the average between the third and fourth element (4 and 5). Note that ``propagate`` doesn't mean "return nan" but "keep nan in the input array and do the computation".

**Comment by Inoryy** [comment]
Hello @rgommers!

But since arrays are 0-indexed, shouldn't it be the median between second and third (`nan` and `4`), which results in `nan`? I think that's the behavior for numpy:

```python
>>> x = np.asarray([1,2,np.nan,4,5,6])
>>> np.median(x)
nan
```

**Comment by WarrenWeckesser** [comment]
I agree with @Inoryy, the grand median should be `nan` in that test.

If the meaning of `'propagate'` is "just run the existing code and let the chips fall where they may", a `nan` in the data will result in a `ValueError` in a later calculation.  If, as the docstring suggests, `'propagate'` means "return `nan`", then all four return values should be equal to (or filled with) `nan`.

**Comment by WarrenWeckesser** [comment]
> If, as the docstring suggests, 'propagate' means "return nan", then all four return values should be equal to (or filled with) nan.

By the way, I think that is the correct thing to do when `nan_policy` is `"propagate"` and there is a `nan` in the data.

**Comment by WarrenWeckesser** [comment]
For the `"omit"` case, the PR needs more work.  I expect the following to return the same values:

```
In [29]: median_test([1, 2, np.nan], [4, 5, 6], nan_policy='omit')
Out[29]: 
(0.75, 0.3864762307712325, 4.0, array([[0, 2],
        [3, 1]]))

In [30]: median_test([1, 2], [4, 5, 6])
Out[30]: 
(0.31250000000000006, 0.57615012203057869, 4.0, array([[0, 2],
        [2, 1]]))
```

**Comment by WarrenWeckesser** [comment]
> Doesn't even make sense for it to be 4.5 from [1,2,nan,4,5,6] test set?

It is a detail of numpy's implementation of `median` that has changed.  In older versions of numpy, `np.median([1, 2, np.nan, 4, 5, 6])` returns 4.5.  (Presumably it sorts the array, which puts `nan` at the right end, and then takes the mean of the middle two values.)  In the latest numpy version, it returns `nan`.  I don't know when the behavior changed (maybe when the `partition` function and its relatives were added, as those could be used to implement `median` with an algorithm that is more efficient than sorting).

**Comment by Inoryy** [comment]
@WarrenWeckesser that makes sense, thanks for the explanation. The numpy version I've used locally is `1.10.2`. How should I proceed - assume `scipy` deps will be updated in the near future or downgrade local installation for the duration of this PR implementation?

**Comment by WarrenWeckesser** [comment]
This only matters when `nan_policy` is `"propagate"`, and as I wrote earlier, in that case I think the code should simply return all `nan`s when there is a `nan` in the data.  I don't see a reasonable alternative.  Running the current code with `nan` in the data using the latest numpy will generate errors, and adding code to avoid those errors might result in the behavior of the `propagate` case being implementation-dependent (or might result in code that always returns `nan`s anyway).

Before writing any more code, though, wait for some feedback from @rgommers.  Based on his earlier comment, he might have a different opinion.

**Comment by rgommers** [comment]
> It is a detail of numpy's implementation of ``median`` that has changed.

Hmm, I didn't realize that. I wonder if that was done on purpose. Anyway, then I agree that returning ``nan`` is the best/only option. This should then be done "by hand" inside ``median_test`` instead of via ``np.median`` in order to avoid the changed behavior on older numpy versions.

**Comment by WarrenWeckesser** [comment]
I rebased this PR and added a couple changes here: https://github.com/scipy/scipy/pull/6317

**Comment by ev-br** [comment]
Merged as a part of https://github.com/scipy/scipy/pull/6317, so closing this. Thanks @Inoryy and congratulations with what I believe is your first scipy commit!

**Pull request closed without merging**
