### PR TITLE
BLD: Support OpenBLAS meson build

### PR DESCRIPTION
**Pull request by mtsokol**
Hi @rgommers @HaoZeke,

This PR will add support for meson based OpenBLAS build, with:
```bash
python dev.py build --with-meson-openblas
```
where OpenBLAS is a git submodule.

### CODE REVIEW

**Comment by andyfaff** [comment]
Was there a discussion on adding OpenBLAS as a submodule? How big a repository is it? Is the option going to work across most OSes? Unfortunately the flag doesn't make it clear that OpenBLAS will be being built. People trying to use an already built openblas might find it confusing.

**Comment by ilayn** [comment]
The flag should clone OpenBLAS instead. It's a massive lib to carry it around if the flag is not used in my opinion. But I don't know how it would work then either.

**Comment by rgommers** [comment]
> Was there a discussion on adding OpenBLAS as a submodule?

There wasn't a dedicated issue, although we did touch on this several times before I believe (e.g., https://github.com/scipy/scipy/issues/12633#issuecomment-1078681133). @mtsokol can you please open an issue first to discuss the feature and integration approach? I agree with @andyfaff and @ilayn's concerns here - the OpenBLAS source repo is very large, so I think we want to avoid including that. This is a case where a Meson subproject may make sense. That can then download the source as a last resort, instead of failing with the dreaded "can't find a BLAS library" error (this is the main goal - it may make a few other things easier too, but those are not large enough benefits by themselves to motivate adding this feature).

Other points to cover given the questions above:
- the desired behavior of the feature itself (I think this is a last fallback, after we've failed to locate not only another OpenBLAS but any other library like MKL etc. - meaning I have some homework to finish the auto-BLAS detection)
- the name of a `dev.py` flag
- what the CI job should look like (I think it has to use `pip install .`, not `dev.py`)

Also, since this isn't ready yet, it'd be better to iterate on this CI job on your own fork. Discussing now is a good idea, but iterating in CI here triggers a lot of jobs. Instead, it's good practice to iterate by pushing to your own fork only when developing a new CI job.

**Comment by mtsokol** [comment]
Sure! I opened an issue: https://github.com/scipy/scipy/issues/21396

**Comment by rgommers** [comment]
@mtsokol I propose we close this, since gh-22047 should supersede this PR.

**Comment by mtsokol** [comment]
> @mtsokol I propose we close this, since [gh-22047](https://github.com/scipy/scipy/pull/22047) should supersede this PR.

Sure, closing!

**Pull request closed without merging**
