### PR TITLE
ENH: Adds Carlson's elliptic integrals in `scipy.special`

### PR DESCRIPTION
**Pull request by arokem**
#### Reference issue
Addresses https://github.com/scipy/scipy/issues/4452

#### What does this implement/fix?
This implements Carlson's elliptical integral functions 

This was implemented by @RafaelNH as part of the DIPY, which is BSD licensed. I am wondering how t give him and the project credit and signify that is used in accordance with the original license.

### CODE REVIEW

**Comment by pv** [comment]
I'd recommend:

- Create a new file `_carson_elliptic.py`, and add the appropriate copyright header in that file.
- Mention in the commit message who is the original author. If you use the phrase "Implementation courtesy of XXXXX.", the author list script will pick "XXXXX" up as an author.
- Might make sense to write these in Cython instead. It should be relatively straightforward, along these lines: 8ae90e379abd66399d5512ea59afa652bf74cd88

The Carson elliptic integrals were added also in gh-10504 --- which I still did not find time to review.

**Comment by arokem** [comment]
Thanks!

I was not aware of gh-10504 -- sorry about that!

Should we close this one? It looks like the other PR is pretty far along
already.

**Comment by rgommers** [comment]
> Should we close this one? It looks like the other PR is pretty far along already.

That makes sense I think, assuming gh-10504 is about right. Would you be able to help review that one @arokem?

**Comment by arokem** [comment]
Yes. Give me a couple of days.

**Comment by arokem** [comment]
Closing in favor of gh-10504

**Pull request closed without merging**
