### PR TITLE
DOC: `special.itairy` example

### PR DESCRIPTION
**Pull request by dschmitz89**
#### Reference issue
#7168 

#### What does this implement/fix?
Example for `special.itairy`

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Thanks @dschmitz89.

In the code to generate the plot, you create a new array `x` with length 500, but you don't call `itairy` with it to generate the data for the plot, so the code is trying to plot with the new `x` and the old values of `apt`, etc.

**Comment by WarrenWeckesser** [comment]
Also, in the plot labels, you have the character sequences `\i` and `\,`.  In some versions of Python, these unrecognized escape sequences generate a warning or error, and so the test job fails.  You should be able to fix that by changing the opening triple-quote of the docstring to `r"""` (i.e. make the docstring a raw string).

**Comment by WarrenWeckesser** [comment]
FYI: The lint failure is because of this:
```
add_newdoc("itairy",
    r"""
    itairy(x, out=None)
```
We can either ignore it (because most of the other calls of `add_newdoc()` in this file follow the same pattern, and this change is not actually changing the existing style), or make another small adjustment to make `flake8` happy:

```
add_newdoc(
    "itairy",
    r"""
    itairy(x, out=None)
```
The relevant guideline from PEP 8 that `flake8` is complaining about is the rule about "hanging indents" discussed in the section on [Code Lay-out](https://peps.python.org/pep-0008/#code-lay-out).

**Comment by ev-br** [comment]
FWIW, I'd suggest ignoring the lint complaint here to keep the style uniform.

**Review by tupui — APPROVED** [review]
LGTM and CI is happy. Thanks @dschmitz89 et al for having a look.

**Pull request merged**
