### PR TITLE
Fix undefined behavior within scipy.fft

### LINKED ISSUE #17644: BUG: 1.10.0rc2 Windows wheel tests runs all segfault
The wheel build jobs are here: https://github.com/scipy/scipy/actions/runs/3753070381

The non-informative failures were originally discussed here, and Ralf and I kind of went for trying to build the wheels anyway, because it wasn't clear there was a genuine SciPy issue: https://github.com/scipy/scipy/pull/17640#issuecomment-1362081751

We have just slightly more information from the `cibuildwheel` testing now, but not too much more--we now know it is a segfault:

```
 D:\a\scipy\scipy/tools/wheels/cibw_test_command.sh: line 11:  1391 Segmentation fault      python -c "import sys; import scipy; sys.exit(not scipy.test())"
```

For now, I'm tentatively labeling this is an upstream bug since it started with NumPy `1.24.0`.

Two solutions I can think of:
- try to identify the problematic test and skip it with NumPy >= 1.24.0 pending further investigation, on Windows only
- (easier, I think?): pin the runtime testing for Windows wheel builds on GitHub actions to NumPy < 1.24.0 temporarily

### PR DESCRIPTION
**Pull request by EthanSteinberg**
#### Reference issue
Closes #17644

#### What does this implement/fix?
scipy.fft currently triggers undefined behavior by calling Python functions before Python is initialized. 

This fixes that by moving the function call of py::none() into the module init function.

This also reverts https://github.com/scipy/scipy/pull/17653

CC @tylerjereddy

### CODE REVIEW

**Comment by andyfaff** [comment]
A question from the sidelines: I would've thought Python would have to be initialised before you could import any kind of module?

**Comment by Lalaland** [comment]
> A question from the sidelines: I would've thought Python would have to be initialised before you could import any kind of module?

There is additional per-DLL state (both for pybind11 and for Python as a whole) that needs to get initialized properly.

**Comment by tylerjereddy** [comment]
I added a tentative backport label for the upcoming release. I guess the windows meson CI job will tell us if we need to worry about https://github.com/mesonbuild/meson/pull/11220? I didn't quite catch how much that affects SciPy or not.

**Comment by Lalaland** [comment]
> musllinux_amd64_test

Is this a known flake or do I need to debug this?

**Comment by Lalaland** [comment]
@tylerjereddy 

>  I guess the windows meson CI job will tell us if we need to worry about mesonbuild/meson#11220? I didn't quite catch how much that affects SciPy or not.

That PR is only for Windows machines using BitLocker. Shouldn't affect SciPy in particular much.

**Comment by tylerjereddy** [comment]
> Is this a known flake or do I need to debug this?

Not sure, I don't see it failing in the other PRs opened today, but we did recently add a test skip for a segfault on alpine/musl recently, and I couldn't even reproduce it in an alpine docker container so..

**Comment by Lalaland** [comment]
> Not sure, I don't see it failing in the other PRs opened today, but we did recently add a test skip for a segfault on alpine/musl recently, and I couldn't even reproduce it in an alpine docker container so..

Let me trigger a CI run with the older pybind11 version to make sure.

**Review by Skylion007 — APPROVED** [review]

**Comment by Lalaland** [comment]
Hmm. Looks like the musllinux_amd64_test is failing due to the new pybind11. We fixed the windows test, but there is something else that is broken.

That is not good. I'll need to debug that before we can merge this.

**Comment by Lalaland** [comment]
What, musllinux_amd64_test is passing now? I have no clue what is going on here?

What would you recommend @tylerjereddy ?

**Comment by andyfaff** [comment]
What  test file was the test run failing on? It may be an infrequent failer that we've not seen before.
First step is to figure out what module it's coming from, to identify possible libraries.

**Comment by tylerjereddy** [comment]
Maybe I will see if I can reproduce in an alpine container or see if the flakiness shows up in other PRs in next few days.

We could still decide to pin pybind11 if we're too nervous, but if it is just down to the alpine issue now, that's probably a big improvement anyway.

**Review by tylerjereddy — APPROVED** [review]
I think unpinning `pybind11` definitely makes sense on `main` now that there has been substantial upstream discussion, including yanking of `2.10.2` from PyPI.

As for backporting, I may be a bit more conservative for `pyproject.toml`, just to be extra safe.

The upstream discussion in https://github.com/pybind/pybind11/issues/4420 suggests that although this may not quite be a bug in SciPy:

> Calling inc_ref on a none object is unlikely to break anything. Still worth fixing though.

**Comment by tylerjereddy** [comment]
refguide failure look unrelated, I'll squash merge to facilitate backporting

**Pull request merged**
