### PR TITLE
MAINT: Fix meson build warnings on windows

### PR DESCRIPTION
**Pull request by Smit-create**
For more details see: https://github.com/rgommers/scipy/issues/120

cc @rgommers

### CODE REVIEW

**Comment by Smit-create** [comment]
Test failures are unrelated:
```
=========================== short test summary info ============================
FAILED ../../stats/tests/test_distributions.py::TestStudentizedRange::test_moment_against_mp[case_result1]
FAILED ../../stats/tests/test_distributions.py::TestStudentizedRange::test_moment_vectorization
```

**Comment by ilayn** [comment]
Are Propack changes related?

**Comment by Smit-create** [comment]
> Are Propack changes related?

Sorry, pushed by mistake.

**Review by rgommers — APPROVED** [review]
This looks good now, thanks @Smit-create!

Can you also submit the SuperLU fix upstream (https://github.com/xiaoyeli/superlu)?

**Pull request merged**
