### PR TITLE
WIP: Add Dormand-Prince 8(5,3) method

### PR DESCRIPTION
**Pull request by astrojuanlu**
This comes from discussion on the mailing list:

https://mail.python.org/pipermail/scipy-dev/2018-September/023066.html

There are some failing tests that I could not fix in a quick way, since the structure of the method is a bit different. I am copy-pasting the code that @nikita-astronaut wrote for poliastro, adding some documentation, and including the method in the tests. Any guidance or advice is appreciated.

cc @nmayorov and @drhagen.

### CODE REVIEW

**Comment by drhagen** [comment]
This is a great addition. Thank you for putting this PR together.

I think the purpose of the test for  `assert_(res.nfev < 40)` is to ensure that the method is operating efficiently. If `DOP853` is the only method that evaluates the function more than 40 times for this simple integral, does that mean it is the least efficient method, or are the other methods just good at that polynomial problem and DOP853 is better for other kinds of problems? Usually, taking lots of steps but still getting the correct answer means there is a small bug in the integrator, but I am not familiar with this method at all.

You probably already recognized this, but I think the test failures are due to `get_coeffs` not accepting an array of times.

**Comment by Juanlu001** [comment]
Thanks for your prompt comments @drhaguen! I didn't know how to read the `get_coeffs` failure, now you gave me some hints to fix it.

Regarding the number of function evaluations, it surprised me because I understood that this higher order method was more efficient, but I will do more research before jumping to any conclusion.

**Comment by Juanlu001** [comment]
According to Hairer et al. "Solving Ordinary Differential Equations I", DOP853 should have the lowest number of function evaluations for a given error, especially when higher precision is requested:

screenshot from 2018-09-20 14-41-04

Still working on it.

**Comment by Juanlu001** [comment]
On the other hand, there's the possibility that, for very simple problems (when the number of function evaluations is on the order of 1e2, way below what the previous figure shows) DOP853 is just less efficient. I cannot dedicate much time to this during the following days, but I will try to:

* Double check that the coefficients are correct from https://www.unige.ch/~hairer/prog/nonstiff/dop853.f and add a comment, although I think @nikita-astronaut made no mistake here.
* Fix the dense output support, which seems to be "just" a code problem.
* Add a new test case for a more complicated problem, for example a celestial mechanics one.

So if anyone with more knowledge wants to:

* give their blessing, based on experience, that ~100 function evaluations is OK for this problem,
* compare with other implementations in Fortran ([1](https://github.com/helgee/LLEA/blob/master/src/dopri.f90), [2](https://github.com/jacobwilliams/dop853/blob/master/src/dop853_module.f90)) or Julia ([1](https://github.com/helgee/Dopri.jl/blob/master/src/Dopri.jl))

That would be great. If nobody does, I will try to do it myself but I will need some time.

**Comment by ev-br** [comment]
Not a blocker, just a suggestion to consider: 
Looking at https://github.com/poliastro/poliastro/commits/v0.11b1/src/poliastro/integrators.py it seems to me that the main part of the code was written by @nikita-astronaut , is this correct?
If that's the case, I suggest to consider `git commit --amend author="..."` to change the author of the first commit in this PR, and keep the subsequent commits under your name.

**Comment by Juanlu001** [comment]
@ev-br That's totally fair, thanks for the reminder! I will do some history rewriting when I get back to this.

**Comment by nmayorov** [comment]
Fixing dense output errors ("just a code problem") is not difficult. I can do it.

But I would like to check/understand the method logic (without comparing it to the Fortran code which is also very difficult and won't convince me anyway), but it seems not easy at all. I need to reread and better understand the whole part devoting to Runge-Kutta methods in the book.

If someone could prepare a short, concise and exact mathematical description of the algorithm --- it would be great: which coefficients go where and why, how error control and dense output are implemented exaclty. This piece of information is missing in my opinion, i.e. we have the Fortran code and good, but vague and rather difficult theoretical explanation in the book.

**Comment by Juanlu001** [comment]
I properly credited @nikita-astronaut in the commit, removed the exception from the test, and rebased to use the current CI infrastructure.

After some informal investigation ([and some struggle](https://github.com/ContinuumIO/anaconda-issues/issues/10495)), I think there is something wrong in the implementation, because the number of function evaluations and the intermediate results don't match the ones from `ode().set_integrator('dop853')`.

## Old method

```python
from scipy.integrate.tests.test_ivp import fun_rational
from scipy.integrate import ode

nfev = 0
def fun_rational2(t, y):
    global nfev
    nfev += 1
    return fun_rational(t, y)

rtol = 1e-3
atol = 1e-6
y0 = [1/3, 2/9]

def callback(t, y):
    print(t, y)

rr = ode(fun_rational2).set_integrator('dop853', rtol=rtol, atol=atol)
rr.set_initial_value(y0, 5).set_solout(callback)
```

Returns:

```
>>> rr.integrate(9)
5.0 [0.33333333 0.22222222]
5.300957107731379 [0.34644611 0.2264212 ]
7.106699754119652 [0.41543371 0.24284854]
9.0 [0.47368421 0.24930748]
>>> nfev
38
```

## Proposed method

```
from scipy.integrate.tests.test_ivp import fun_rational
from scipy.integrate import ode

rtol = 1e-3
atol = 1e-6
y0 = [1/3, 2/9]

res = solve_ivp(fun_rational, t_span, y0, rtol=rtol, atol=atol, method="DOP853", dense_output=True, jac=None, vectorized=False)
```

Returns:

```
>>> res.t                                                                                                                          
array([5.        , 5.35741471, 7.50190299, 9.        ])
>>> res.y
array([[0.33333333, 0.34884874, 0.42863356, 0.47368421],
       [0.22222222, 0.2271533 , 0.24490683, 0.24930748]])
>>> res.nfev                                                                                                                       
94
```

I will keep on investigating.

**Comment by Juanlu001** [comment]
* By comparing step by step the output of `dop853.f` and our implementation, I realized the first discrepancy was in the code that computes the initial step. The implementation is now identical to the original, but I broke other tests.
* The extra function evaluations came from the dense output computation. The quick and dirty solution was to add a new `**option` to our solver to control whether the interpolant should be computed or not. I wanted to use the `dense_output` function of `solve_ivp`, but surprisingly is not passed to the solvers and I preferred to keep the changes at a minimum before going forward. Because of this temporary solution, one extra test is broken (where `dense_output` is requested but the extra parameter defaults to `False`).

The former issue worries me the most, because it affects the other solvers. For the latter, we should agree on a way forward.

I'm sorry I didn't devote time to providing explanations about the algorithm and the implementation, but I wanted to focus on making it work first. Now I am closer, but there is still work to do.

**Comment by drhagen** [comment]
Can you eliminate the need for the `compute_dense_output` by moving the corresponding calculations from `_step_impl` to `_dense_output_impl`? Then the extra function evaluations would only be done when the dense input was requested rather than every step.

**Comment by Juanlu001** [comment]
Thanks @drhagen, I just did. The number of function evaluations in `test_integration` is back to 47 because `dense_output=True`, however I already checked with the `ode` class and they behave in the same way. I can only guess that the method works better for longer time spans.

I'm still concerned about the existing tests that broke. I modified `select_initial_step` to behave exactly like

https://github.com/scipy/scipy/blob/c4629af076351788a80d5e3d94dc8a61015da910/scipy/integrate/dop/dop853.f#L791-L795

But apparently the other solvers didn't like it. Not sure how to proceed here.

**Comment by Juanlu001** [comment]
> I would not expect the optimal step size to be the same for all methods.

That being the case, I used the Fortran-like implementation only for `DOP853` and left the rest without changes.

I still have three failing tests:

* `test_integration:assert_(res.nfev < 40)`. I would propose relaxing this condition to `<50` in this particular method, as I did at the beginning.
* `test_events:assert_(7.3 < res.t_events[1][0] < 7.7)`. Still not sure what's happening.
* `test_max_step:assert_(np.all(np.abs(np.diff(res.t)) <= 0.5))`. The `max_step` parameter is not being used in the code (that's a failure in @nikita-astronaut original implementation), so I will amend that when I figure out where to correct the `h`.

**Comment by Juanlu001** [comment]
(Oh, and the `get_coeffs` that I had forgotten about)

**Comment by Juanlu001** [comment]
I parametrized the tests using `pytest.mark.parametrize` to prevent failures from interrupting the rest of the iteration, and now the output is nicer because it tells you more clearly which method failed. Still I have numerical errors though...

**Comment by Juanlu001** [comment]
I parametrized the tests using `pytest.mark.parametrize` to prevent failures from interrupting the rest of the iteration, and now the output is nicer because it tells you more clearly which method failed. Still I have numerical errors though...

**Comment by Juanlu001** [comment]
I made some experiments focusing on the case `t_span = [5, 1]` and discovered that our implementation still matches the old interface... which does a too high error as well.

https://gist.github.com/Juanlu001/fb4f6b84754e24ff668f0a4490088137

```
In [1]: %run /tmp/ivp_dop853.py                                                                                 

In [2]: res.t                                                                                                   
Out[2]: array([5. , 4.9, 4.4, 3.9, 3.4, 2.9, 2.4, 1.9, 1.4, 1. ])

In [3]: res_old.t                                                                                               
Out[3]: array([5. , 4.9, 4.4, 3.9, 3.4, 2.9, 2.4, 1.9, 1.4, 1. ])

In [4]: res.y                                                                                                   
Out[4]: 
array([[0.33333333, 0.32885906, 0.30555556, 0.28057554, 0.25373134,
        0.2248062 , 0.19354839, 0.15966387, 0.12280702, 0.09090909],
       [0.22222222, 0.22071078, 0.21219136, 0.20185291, 0.18935175,
        0.17426837, 0.15608741, 0.13417132, 0.10772545, 0.08264463]])

In [5]: res_old.y                                                                                               
Out[5]: 
array([[0.33333333, 0.32885906, 0.30555556, 0.28057554, 0.25373134,
        0.2248062 , 0.19354839, 0.15966387, 0.12280702, 0.09090909],
       [0.22222222, 0.22071078, 0.21219136, 0.20185291, 0.18935175,
        0.17426837, 0.15608741, 0.13417132, 0.10772545, 0.08264463]])

In [6]: err                                                                                                     
Out[6]: 
array([0.00000000e+00, 8.85214325e-14, 1.33232875e-12, 4.56825364e-12,
       1.28876525e-11, 3.76602429e-11, 1.27711661e-10, 5.61741896e-10,
       3.68558335e-09, 7.36505916e-09])

In [7]: err_old                                                                                                 
Out[7]: 
array([0.00000000e+00, 1.18997221e-13, 1.54889154e-12, 4.69257995e-12,
       1.29087210e-11, 3.77030765e-11, 1.27694566e-10, 5.61734395e-10,
       3.68528341e-09, 7.36482279e-09])
```

I cannot compare the dense output because the old interface does not support it, but in any case the error is too high. The forward integration yields a much accurate result:

```
In [11]: err                                                                                                    
Out[11]: 
array([0.00000000e+00, 1.45112343e-13, 3.37968732e-13, 7.42118369e-13,
       8.04549340e-13, 9.43101159e-13, 9.06900706e-13, 8.75163939e-13,
       9.35136630e-13, 8.59719542e-13])

In [12]: err_old                                                                                                
Out[12]: 
array([0.00000000e+00, 8.73537693e-14, 4.36167860e-13, 7.28045367e-13,
       8.04549340e-13, 9.43101159e-13, 9.06900706e-13, 8.75163939e-13,
       9.35136630e-13, 8.59719542e-13])
```

Unfortunately my holidays are over and at the current pace it's unlikely that I will finish this soon :frowning_face: so leaving this here in case someone else wants to give it a try.

Or perhaps we should implement a Verner method, that [some authors claim is even more efficient](https://docs.juliadiffeq.org/latest/solvers/ode_solve.html#Translations-from-MATLAB/Python/R-1) and is probably better documented...

**Comment by Juanlu001** [comment]
After losing a bit of the motivation for pursuing this further, I thought that perhaps an alternative for this particular method would be to write some dedicated unit tests to at least verify that _it gives the same results with the same number of function evaluations than `dop853.f`_. Would that be acceptable?

**Comment by Juanlu001** [comment]
@nmayorov kindly took this over at #10173, so I am closing this PR. Thanks a lot!

**Pull request closed without merging**
