### PR TITLE
TST: add scikit-umfpack to Linux TravisCI builds

### PR DESCRIPTION
**Pull request by rgommers**
Wasn't tested at all so far. Related to gh-7600.

### CODE REVIEW

**Comment by rgommers** [comment]
Grr, ``ImportError: No module named 'numpy' .... The command "pip install scikit-umfpack" failed.``. I knew that, due to no ``setup_requires`` and pip building in an isolated virtualenv.

**Comment by rgommers** [comment]
Should be addressed by https://github.com/scikit-umfpack/scikit-umfpack/pull/38

**Comment by pv** [comment]
Does this need the "install oldest supported numpy version" hackery?

**Comment by rgommers** [comment]
It does in principle, but it's broken with latest pip master so this is better than nothing for now. I still have to debug, figure out why scipy does appear to work.

**Pull request closed without merging**
