### PR TITLE
Doc: Added tutorial documentation for stats distributions ksone and kstwobign

### PR DESCRIPTION
**Pull request by pvanmulbregt**
The stats tutorial pages in the doc for these two distributions existed but were empty.  This adds a body for each of them.

### CODE REVIEW

**Comment by rgommers** [comment]
Links to rendered pages:
https://2830-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/tutorial/stats/continuous_ksone.html
https://2830-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/tutorial/stats/continuous_kstwobign.html

**Comment by pvanmulbregt** [comment]
Withdrawing as rendering preview exposed an error.

**Comment by rgommers** [comment]
@pvanmulbregt for next time: it's better to just update an open PR (by pushing changes to the branch you sent the PR from) rather than closing it and opening a new one.

**Comment by pvanmulbregt** [comment]
@rgommers Thanks, I'll do that.  How exactly do I ensure the update gets picked up?  What is the last step in this process:
1. git checkout kolmogorovsmirnov_doc; <EDIT_&_TEST>; git commit
2. git push --set-upstream origin kolmogorovsmirnov_doc
3. <WHAT_HAPPENS_HERE?>

**Comment by rgommers** [comment]
1. git checkout kolmogorovsmirnov_doc; <EDIT_&_TEST>; git commit
2. git push origin kolmogorovsmirnov_doc

is enough, it will automatically show up in the open PR that you sent from that branch. Note that the PR still needs to be open, so if you just tried it for this one then that wouldn't have worked.

**Pull request closed without merging**
