### PR TITLE
MAINT: Module and example cleanups for doc build

### PR DESCRIPTION
**Pull request by larsoner**
When building SciPy doc I ran into a few problems because I'm using latest Sphinx `master` and `matplotlib`:

1. Latest matplotlib is unhappy about our use of `pcolormesh` because it wants to be passed the mesh edges rather than centers when `shading='flat'`. I fixed this by either passing `shading='gouraud'` when possible, or by defining the edges when `shading='flat'` was required pedagogically.
2. `matplotlib` deprecated `fig.add_subplot('111')` fixed by `add_subplot(1, 1, 1)`
3. Fixes a tiny docstring bug with `itemfreq` deprecation.
4. Bumps `numpydoc` / `doc/sphinxext` to be on ~~the latest `master` commit~~ v1.0.0 -- it fixes some issues like `\*\*kwargs` showing up in docs, and a nasty rebuild bug (caused by me!) that is present even in 0.9.2. It would be nice to push out NumpyDoc 1.0.0 and use that instead, which I could work on next week if it seems worthwhile.
5. Module names colliding with function names made `autodoc` fail. It's possible that this is some Sphinx bug, but it's not great in principle to have both `scipy.optimize.nnls` as a function and `scipy/optimize/nnls.py` as a file because of issues like this (and import problems). So this moves to a `_`-prefixed file:
    * `scipy.optimize.nnls` (and thus the `_nnls` extension to `__nnls`)
    * `scipy.integrate.quadrature`
    * `scipy.special.lambertw`
6. `scipy/stats/vonmises.py` appears to be used nowhere in the codebase. The last substantive change was back in 2014, and removing it did not break any tests. The functions in it like `von_mises_cdf_series` are also in [scipy/stats/_stats.pyx](https://github.com/scipy/scipy/blame/master/scipy/stats/_stats.pyx#L16), which appears to come from [12 years ago](https://github.com/scipy/scipy/commit/fc764b8f4af3c0a1d703d11c0503e2f6e3454d12). So assuming all tests pass (and `scipy.test('full')` does locally), I don't see a reason to keep this `.py` file around. It will live on in the git history if we ever need it.
7. EDIT: Removes `jet` from a couple of examples

Happy to split some or all of these points into separate PRs if we want only some of them for 1.5.0 branching (or at all, for that matter). At least (1), (2), and (3) are fairly safe, so my vote would be for at least those two to go in to 1.5.0.

### CODE REVIEW

**Comment by rgommers** [comment]
All those changes sound good to me, and I don't see a reason not to put any into 1.5.0.

CI is unhappy, one single warning left in doc build.



> 4. It would be nice to push out NumpyDoc 1.0.0 and use that instead, which I could work on next week if it seems worthwhile.

Thank you, that would be great!

**Comment by larsoner** [comment]
Pushing a commit to fix that, plus remove `cm.jet` from two examples in favor of `RdBu_r`, which is nicer when using divergent data (here, ones with a meaningful zero point).

**Comment by larsoner** [comment]
Okay, switched to numpydoc 1.0.0 and CIs are happy, ready for review/merge from my end

**Review by rgommers — APPROVED** [review]
LGTM, thanks @larsoner

**Pull request merged**
