### PR TITLE
 LICENSE: split license file in standard BSD 3-clause and bundled.

### PR DESCRIPTION
**Pull request by rgommers**
Reason: the GitHub license detection method relies on the LICENSE file matching for at least 95% with a standard license. Adding even one more sentence changes the license displayed in the
GitHub UI and also in the GitHub API that can be queried from BSD to "other".

See https://github.com/numpy/numpy/issues/13447 for more details.

Note that:
- this split license is what GitHub recommends to do, and is also what we do for wheels, where we append to the license file at build time.
- this was detected as an inconsistency between libraries.io and the GitHub API by Tidelift.
- this approach is taken over from NumPy, it worked fine there.
- I will update the scipy-wheels repo after this is merged.

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
Looks like a straightforward improvement. +1 for merge from me

I restarted a Travis build that looked like a spurious failure.

**Comment by larsoner** [comment]
Looks like the failure is persistent and unrelated, it's a bunch of these across tests on the build (presumably the one against `master` numpy):
```
mtrand.pyx:97: TypeError
```

**Comment by rgommers** [comment]
Oh yes, that's due to the merge of the new random number generators. I believe a fix for that is in the making. Let's ignore that failure.

**Comment by rgommers** [comment]
Given that this solves a licensing inconsistency, I'd like to merge it tomorrow evening to get it resolved before the end of this month.

If anyone sees an issue with that, please comment.

**Comment by tylerjereddy** [comment]
The proposed random fix was [merged upstream](https://github.com/numpy/numpy/pull/13670) though we'd likely have to wait for the nightly NumPy wheel build for that to propagate through to this particular CI entry

**Comment by tylerjereddy** [comment]
Ok, two core devs +1 and CI fail unrelated so let's put it in, thanks Ralf

**Comment by rgommers** [comment]
that change helped but wasn't enough. follow-up in gh-10247

**Comment by rgommers** [comment]
> I will update the scipy-wheels repo after this is merged.

**Pull request merged**
