### PR TITLE
Complex number support in log1p, expm1, and xlog1py

### PR DESCRIPTION
**Pull request by ewmoore**
I can't find an example where `log1p

### CODE REVIEW

**Comment by ev-br** [comment]
This looks very cool! Needs a rebase. And something went very wrong with expm1,  it seems.

**Comment by ewmoore** [comment]
This is green now largely because I'm excluded the values that were failing from the tests.  The tests pass locally without limiting the range to +/-1e8.  I don't understand why the tests were failing.  Don't merge this yet as I want to do some more checking.

Additionally, are we sure that the complex step derivative tests are doing what we really want? Are we really numerically calculating the derivative of CDF instead of just using PDF?  If so why?

**Comment by ewmoore** [comment]
Alright.  Nothing is excluded anymore, should be good to go.

**Comment by pv** [comment]
Where does the file name `_cunitity.pxd` come from?
Otherwise, LGTM.

**Comment by ewmoore** [comment]
Ha!  The name _cunitity.pyx comes from me misspelling _cunity.pyx a month ago and never paying any attention.  Fixed.  (_cunity.pyx is based on unity.c in cephes, where `expm1`, `log1p` and `cosm1` are implemented.)

**Comment by pv** [comment]
Thanks, merged.

**Pull request merged**
