### PR TITLE
CI: split travis arm64 run into two

### PR DESCRIPTION
**Pull request by pv**
The arm64 run is too slow for the test suite to complete, so split it into two batches.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Cool idea, I'd never heard of `pytest-test-groups`.

One of the Travis CI matrix entries seems problematic, and it isn't the usual linalg one we've been seeing lately: https://travis-ci.org/github/scipy/scipy/jobs/693175648

Looks like `pydata/sparse` issue?

**Comment by andyfaff** [comment]
I'm wondering if travis-ci. [build stages](https://docs.travis-ci.com/user/build-stages/) would be a cleaner solution. We could build and install in the first stage and test in the second. The question that would need to be answered is if the different build stages reset the clock.

**Comment by tylerjereddy** [comment]
I thought about that too, but I bet it would be a bit more disruptive since then the rest of our Travis config also has to respect the stages I think.

**Comment by pv** [comment]
I think refactoring to stages can be done in separate PR, if someone
wants to do it. Right now, I think the priority should be to get the CI
running reliably.

**Comment by pv** [comment]
I suspect the pydata/sparse failure has to do with running with Numpy prerelease (the py3.8+nump-pre job doesn't install pydata/sparse because it's skipped for py3.8, so the failure correlates fully with --pre). Added a commit to skip installing it in that case.

**Comment by rgommers** [comment]
> Added a commit to skip installing it in that case.

That seems like a good workaround, but would be nice to revert after it's fixed upstream.

**Comment by rgommers** [comment]
> I think refactoring to stages can be done in separate PR, if someone wants to do it. Right now, I think the priority should be to get the CI running reliably, in some way that works.

agreed. this is all green, so let's get it in. thanks Pauli!

**Comment by rgommers** [comment]
FYI @odidev cc, this may help with scipy-wheels ARM64 as well

**Pull request merged**
