### PR TITLE
BUG: Rewrite of stats.truncnorm distribution.

### LINKED ISSUE #2477: stats.truncnorm.rvs() does not give symmetric results for  negative & positive regions (and fails entirely away from the mean)
Sampling `[-11, -10]` from the negative tail of the truncated normal seems to work:

``` python
>>> x = scipy.stats.truncnorm.rvs(-11, -10, 0, 1, size=1000000)
>>> x.min(), x.max()
Out[6]: (-10.998337763352668, -10.000000033737539)
```

But sampling from the equivalent but positive region (i.e.`[10, 11]`) gives:

``` python
>>> y = scipy.stats.truncnorm.rvs(10, 11, 0, 1, size=1000000)
>>> y.min(), y.max()
Out[8]: (inf, inf)
```

This shouldn't fail in one case but not the other.

(Tested with SciPy 0.12 on win32)

---

Additionally sampling fails entirely when you're far from the mean:

``` python
>>> z = scipy.stats.truncnorm.rvs(100, 101, 0, 1, size=1000000)
>>> z.min(), z.max()
Out[24]: (inf, inf)
```

I believe this is because SciPy is using an inverse transform sampler which fails for precision reasons. Either way, it seems better to raise an exception than continue returning nonsense.

Perhaps there should be a different sampler (e.g. [rejection](http://arxiv.org/pdf/0907.4010.pdf), [B-M](http://www.tsc.uc3m.es/~luca/LetterTruncatedGaussianFinal.pdf) or [this](http://arxiv.org/pdf/1201.6140.pdf)) to handle the case when you're more than a couple standard deviations from the mean?

(Possibly related [this](https://github.com/scipy/scipy/issues/1489) issue)

### PR DESCRIPTION
**Pull request by pvanmulbregt**
Extend to support much wider tails (previously had overflow issues with abs(x) >= ~40, now can handle x at least as large as 10000.)
Fixes gh-2477, gh-9403, gh-9902, gh-10092.
Added regression tests.

### CODE REVIEW

**Comment by pvanmulbregt** [comment]
I'm seeing quite big numerical differences in the scipy.scipy Linux_Python_36_32bit_full Job Ubuntu Docker build.  I'm expecting a computed kurtosis to be about 6.7 or 6.71, but seeing 6.66 returned on that build. To make the tests pass, I can relax the constraint, as in
```
 assert_almost_equal(k, 6.70255909, decimal=1)
```
but that doesn't seem desirable. 
What is special about this Ubuntu 32-bit platform?
Is the `integrate.quad` implementation substantially different?  Or the underlying math libraries?

**Comment by rgommers** [comment]
You could use `_is_32bit_platform = np.intp(0).itemsize < 8` as we do in some other test files, and relax test precision only for 32-bit.

> What is special about this Ubuntu 32-bit platform?

not sure, nothing special in the test platform probably, just some 32-bit issue. The Cephes code is the first place I'd suspect.

**Comment by rgommers** [comment]
Merged master into this branch to resolve merge conflicts:
- updated test xfail to use the new `xfail_on_32bit`
- replaced `reciprocal` with the now preferred `loguniform`

**Comment by rgommers** [comment]
Hmm, `test_cont_basic[reciprocal-arg86]` failed on Appveyor with
```
    def deriv(f, x, *arg):
        x = np.asarray(x)
        h = 1e-10
>       return (f(x + h*1j, *arg)/h).imag
E       RuntimeWarning: invalid value encountered in true_divide
arg        = (0.01, 1)
f          = <bound method rv_continuous.logcdf of <scipy.stats._continuous_distns.reciprocal_gen object at 0x0000001231FE5848>>
h          = 1e-10
x          = array([0, 0, 0])
C:\Python37-x64\lib\site-packages\scipy\stats\tests\common_tests.py:246: RuntimeWarning
----------- generated xml file: C:\projects\scipy\junit-results.xml -----------
=========================== short test summary info ===========================
```

**Comment by rgommers** [comment]
Okay, found the issue - both `loguniform` and `reciprocal` were in `distcont`, and since they're aliases they shouldn't both be. removing `reciprocal` and keeping `loguniform` in `fails_cmplx`.

**Comment by rgommers** [comment]
That all passes now, the one failure is a CI timeout.

This PR is awesome, thanks @pvanmulbregt!

**Pull request merged**
