### PR TITLE
DOC: add Sphinx roles for DOI and arXiv links

### PR DESCRIPTION
**Pull request by ev-br**
This way, correct hyperlinks are generated automagically in the docstrings.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Could this be put in `numpydoc` instead so that other projects can more easily make use of it?

**Comment by pv** [comment]
I think inclusion in numpydoc can be considered as a separate issue.

**Comment by ev-br** [comment]
My reading of https://github.com/numpy/numpydoc/issues/34 is that it's not wanted in numpydoc. I'm happy to redirect it otherwise.

**Comment by Eric89GXL** [comment]
Yeah I agree after reading that issue

**Comment by rgommers** [comment]
Looks fine to me to add this, quite small and makes the docs more uniform. 

Can you add a link to where you found this code? A search for ``doi_role`` or ``doilinks`` doesn't lead me to the right place.

**Comment by ev-br** [comment]
It's from https://gist.github.com/jonls/b910afc46473b02597c4 
The link was hiding  in the commit message, and https://github.com/numpy/numpydoc/issues/34#issuecomment-91217470

One  search line which finds it is "DOI role Sphinx". 

For completeness, I'll note that networks has something similar, https://github.com/networkx/networkx/blob/master/doc/sphinxext/customroles.py

**Comment by rgommers** [comment]
Thanks, LGTM.

**Comment by Eric89GXL** [comment]
LGTM +1 for merge

**Pull request merged**
