### PR TITLE
CI: fix the failing job on linux.

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### Reference issue

N/A

#### What does this implement/fix?

I think the job on Linux failed as `cython` was not able to find the `setuptools` package. So, I changed the script to first upgrade `setuptools` and then upgrade `cython` and other packages. Works on my master: https://github.com/tirthasheshpatel/scipy/runs/2350445370

#### Additional information

N/A

### CODE REVIEW

**Comment by ilayn** [comment]
Hmm that's weird. I specifically remember splitting these up like you did but maybe I was dreaming. Do we need argparse since it is a built-in?

**Comment by tirthasheshpatel** [comment]
> Do we need argparse since it is a built-in?

Yes, it's built-in. So, I don't think we need that.

**Comment by ilayn** [comment]
Then we shouldn't need argparse since it's a built in. 😃 

Let's remove it...

**Review by tupui — APPROVED** [review]

**Comment by ilayn** [comment]
Thanks @tirthasheshpatel @tupui

**Pull request merged**
