### PR TITLE
BUG: type changes in rv_generic

### LINKED ISSUE #9313: geometric distribution stats.geom returns negative values if p is very small
For very small success probability `p`, `stats.geom` returns negative numbers.

### Reproducing code example:
```
from scipy import stats
import numpy as np

np.random.seed(1234)
stats.geom(np.exp(-20)).rvs(size=5) # ok, large positive numbers
stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648
stats.geom(np.exp(-30)).rvs(size=5) # all equal to -2147483648

np.random.seed(1367)
stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648, except the last 1670264715
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
1.0.0 1.14.1 sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by akahard2dj**
gh-9313

https://github.com/scipy/scipy/blob/ad00a9e8dccc6c075e724d0ff4f05bc5c0147a8b/scipy/stats/_distn_infrastructure.py#L963

In this section, type casting takes place in this point.
BUT `int` function is depends on the bit of os.
so I change forcibly `int` to `numpy.int64`.

### CODE REVIEW

**Comment by ev-br** [comment]
TBH I'm not sure about backcompat here. Maybe it's better to keep delegating to numpy here. If some specific distributions are broken in numpy, the fixes should go there, too. However, if others think it's OK, I won't block it.

**Comment by akahard2dj** [comment]
Should I close this PR?

**Comment by ilayn** [comment]
An ideal solution would be to cast to int64 only if overflows from 32bit max which retains backward compatibility.

**Comment by akahard2dj** [comment]
@ilayn 
Only when the value of `vals` overflows from 32bit max, I did `numpy.int64` instead of `int`.

**Comment by ilayn** [comment]
Nice, thanks. We need to modify it a bit though. The bit shift is not sufficient to check the overflow. Instead you can use `numpy.iinfo` function. 

```python
>>> np.iinfo(np.int32).max
2147483647
```
Hence it won't catch the overflow: 

```python
>>> if 2147483647 + 1 > (1 << 32) - 1:
...     print('yes')
... else:
...     print('no')
no
```

One option to go about it is 

```python
        if discrete:
            dtype = np.int64 if np.abs(vals) => np.iinfo(np.int32) else int
            if size == ():
                vals = dtype(vals)
            else:
                vals = vals.astype(dtype)
```

But I haven't checked the logic thoroughly so someone else should also check it. `size==()` seems a bit awkward.

**Comment by ilayn** [comment]
Ah the condition is not complete. It will not check all elements in the array case. But I hope it is clear enough.

**Comment by akahard2dj** [comment]
I did mistake for checking for maximum of 32bit integer.
the maximum of 32bit integer is not `(1<<32) -1` but `(1 << 32-1) -1`.

I will use the maximum of 32bit integer for `numpy.iinfo(numpy.int32)`.
 
fixed
```python
>>> if 2147483647 + 1 > (1 << 31) - 1:
...     print('yes')
... else:
...     print('no')
yes
```

**Comment by ev-br** [comment]
Closing based on @peterbell10 's review of gh-10415. Thanks anyway @akahard2dj

**Pull request closed without merging**
