### PR TITLE
ENH: spatial: reimplement cdist_cosine using np.dot

### PR DESCRIPTION
**Pull request by larsmans**
This uses `np.dot` instead of a custom dot product routine for computing `cdist(A, B, 'cosine')`. It also uses `np.einsum`, if available, to get the space complexity to a strict O(_mn_) when the dtypes are both `double`, instead of O(_mn_ + _mk_ + _nl_) for _m_, _k_ = `A.shape`, _n_, _l_ = `B.shape`.

I also tried doing the whole thing with `einsum` only:

```
1 - np.einsum('ij,jk,i,k->ik', XA, XB.T, 1/normsA, 1/normsB)
```

... but that was much slower.

Tackling the corresponding `pdist` is much harder and out of scope for this PR.

### CODE REVIEW

**Comment by larsmans** [comment]
@rgommers Wrote a new test that compares the results of `cdist` with a straightforward implementation of 1 - cosine similarity. Also rebased on master.

**Comment by larsmans** [comment]
Ok, should work on Py3 now too. Got rid of the "get ddot from NumPy hack".

**Comment by juliantaylor** [comment]
I don't really like the 2 times slowdown for low dim which I see with all three free blas libraries.
can one add a dimension threshold to use dot?

**Comment by larsmans** [comment]
? I tested this with ATLAS 3.10.1 as shipped with Ubuntu...

**Comment by juliantaylor** [comment]
and saw a factor 2 slowdown just as I did. Same if not worse with openblas.
I guess it may be acceptable for cosine dist as its probably more a sklearn area which is more often high-d?

**Comment by larsmans** [comment]
... eh, yes. Sorry, brain fart. Anyway, that's a tradeoff I'm willing to make, unless there's a need for fast low-d cosine distance. The only application of it that I know is clustering of categorical data represented as one-hot vectors; those are typically high-d.

**Pull request merged**
