### PR TITLE
BUG FIX: pearson3.stats returning moments as arrays rather than scalars. 

### LINKED ISSUE #11746: BUG: stats: pearson3 returns size 1 arrays where other distributions return scalars
Example:
```
from scipy.stats import alpha, halfcauchy, invgamma, invweibull, kappa3, levy, levy_l, loglaplace, pareto, pearson3
for dist in [alpha, halfcauchy, invgamma, invweibull, kappa3, levy, levy_l, loglaplace, pareto, pearson3]:
    print(dist.moment(1, 2))
```
prints:
```
inf
inf
1.0
1.7724538509055159
1.4142135623743761
inf
inf
1.3333333333333333
2.0
[0.]
```
The last one, from `pearson3`,  is a size 1 array; it should be a scalar like the rest.

_Update: Another problem is that the `pearson3.moment` function returns an empty array when `skew` is too small._
```
from scipy.stats import pearson
pearson3.moment(1, skew=0.000001)
```
 _When these issues are fixed, please try to remove the override of the `pearson3.fit` method and allow `check_fit_args` and `check_fit_args_fix`  to run in `test_continuous_basic.py` by removing `pearson3` from `fail_fit_test_mm`/`fail_fit_fix__test_mm`._

### PR DESCRIPTION
**Pull request by WillTirone**
#### Reference issue
Closes gh-11746

#### What does this implement/fix?
pearson3.moment was returning an array and now returns a scalar. Fixed by converting pearson._stats output variables to scalars.

#### Additional information
This is my first contribution so please review carefully. I followed the contribution guide fairly carefully. Changes pass testing and I added a regression test in _continous_distns.py. 

There is a comment that I would like reviewed from the distribution: 

        # The _argcheck function in rv_continuous only allows positive
        # arguments.  The skew argument for pearson3 can be zero (which I want
        # to handle inside pearson3._pdf) or negative.  So just return True
        # for all skew args.

I'm honestly not sure what the original intent here was as far as handling a skew of zero, so I just  defaulted to returning zeros in _stats, but please let me know if this is incorrect. I think that portion may be outside of my understanding of statistics / the standard approach for scipy devs in cases like this.

### CODE REVIEW

**Comment by mdhaber** [comment]
I started working on this but I got into a rabbit-hole, then got sidetracked without being able to document my thoughts. If I remember correctly, I uncovered a deeper issue - the [`rv_continuous.moment`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.moment.html#scipy.stats.rv_continuous.moment) function is supposed to accept array arguments for `loc`, `scale`, etc., but it doesn't. Can you confirm?

>I'm honestly not sure what the original intent here was as far as handling a skew of zero, so I just defaulted to returning zeros in _stats, but please let me know if this is incorrect

No, we can't just return zero unless that is the correct answer. I think the point was that for skews below a certain threshold, the calculation was to be performed by `norm` instead of the usual code.

**Comment by WillTirone** [comment]
Let me rework the norm section of that - I think that makes more sense now. I was assuming because it was returning an empty array it was supposed to be zero but that wouldn't make sense.

It looks like the following few examples work as expected: 
``` python 

expon.moment(n=np.array(1), loc=np.array(1), scale=np.array(1))
Out[16]: 2.0

pearson3.moment(n=np.array(1), skew=np.array(1), loc=np.array(1))
Out[13]: 1.0

**Comment by WillTirone** [comment]
I added `_norm_stats` as a method to `pearson3` because, while methods like `norm._pdf` and `norm._cdf` are defined outside of the class, `norm._stats` is not; to replicate using those moments, this seemed like the easiest approach. 

The rest of the `pearson3` dist uses the methods defined outside of the normal class.

**Comment by mdhaber** [comment]
@WillTirone thanks for your patience, but it's going to take me a bit to get to this. But can you confirm that  `moment` is supposed to accept array arguments for `loc` and `scale` but doesn't? Accepting arrays is the root of the problem -because that's why `moment` might be to return an array, and if that's not working properly, we might need to hold off on this.

**Comment by WillTirone** [comment]
@mdhaber no worries at all! If you take a look at my comment above yours, I think that's what you're mentioning? Unless I'm misunderstanding. But it seems like it's accepting arrays just fine and returning a scalar. Do you have maybe a code snippet of something that's not working properly?

**Comment by mdhaber** [comment]
I meant arrays with more than one element.

**Comment by WillTirone** [comment]
I'm not positive if I'm using arrays in the args as intended, but from reading the docs https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.moment.html it looks like these arguments should accept array-like and are returning a ValueError. Let me know if these args aren't what you were thinking as far as them accepting arrays.

```python 
expon.moment(n=np.array([1,2]), loc=np.array([1,2]), scale=np.array([1,2]))
Traceback (most recent call last):

  File "<ipython-input-3-dc42edd1473f>", line 1, in <module>
    expon.moment(n=np.array([1,2]), loc=np.array([1,2]), scale=np.array([1,2]))

  File "/home/will/Desktop/code/scipy/scipy/stats/_distn_infrastructure.py", line 1164, in moment
    if not (self._argcheck(*args) and (scale > 0)):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()




pearson3.moment(n=np.array([1,2]), skew=np.array([1,2]))
Traceback (most recent call last):

  File "<ipython-input-5-e4467db2ee48>", line 1, in <module>
    pearson3.moment(n=np.array([1,2]), skew=np.array([1,2]))

  File "/home/will/Desktop/code/scipy/scipy/stats/_distn_infrastructure.py", line 1164, in moment
    if not (self._argcheck(*args) and (scale > 0)):

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by WillTirone** [comment]
Is this issue stalled due to another issue? If so, should I close it below and start on another issue? 

Thanks :)

**Comment by WillTirone** [comment]
hi @mdhaber just wanted to check on this! Thanks

**Comment by mdhaber** [comment]
Thanks for the reminder. I'll take a look this week.

**Comment by mdhaber** [comment]
@WillTirone I dug into this today. When I marked gh-11746 as a good first issue, I hadn't really looked at `pearson3` carefully. It turns out that there are a few other issues (gh-9168, gh-11186, gh-12192) that made this more challenging than it would have been otherwise. It was really not a good first issue! Can I take this one over and help you find a better first issue?

**Comment by WillTirone** [comment]
@mdhaber sure, that sounds good to me! Appreciate the help. Let me know if I need to close this one or what. I'll also keep an eye out on the new issues that come up.

**Comment by mdhaber** [comment]
Yes, let's close this. Would you take a look at gh-7168? That is a much better place to start.

**Pull request closed without merging**
