### PR TITLE
GEN: Add comments to the tests for clarification

### PR DESCRIPTION
**Pull request by ilayn**
Additional comments for the test loops

### CODE REVIEW

**Comment by ilayn** [comment]
@rgommers FYI

**Comment by rgommers** [comment]
Thanks @ilayn, merged.

**Comment by rgommers** [comment]
``GEN`` is for generated code, it doesn't mean "general". You wanted ``MAINT``

**Comment by ilayn** [comment]
Oh, I didn't know that. Thanks!

**Pull request merged**
