### PR TITLE
BUG: white/black_tophat behavior fixes

### LINKED ISSUE #9553: ndimage routines behave badly when output has memory overlap with inputs
Maybe the problem is following
...
_tmp = grey_erosion(tmp, size, footprint, structure, output, mode, cval, origin)_ 
tmp and input is the same now
so
_numpy.subtract(tmp, input, out=tmp)_
gives zero

Thank you

### PR DESCRIPTION
**Pull request by akahard2dj**
closes #9553 

When the name of input parameter and output parameter is same in `ndimage.white_tophat()`/`ndimage.black_tophat()`, they gives zero.

I have designed the solution by comparing input and output.

### CODE REVIEW

**Comment by rgommers** [comment]
This fix is wrong in several ways. `array_equal` compares *values*, while what you care about here is whether `input` and `output` are the same *object*. Then, you can't just ignore `output` by setting it to None. Finally, the tests are wrong - the output isn't changed by the application of the filter.

**Comment by akahard2dj** [comment]
@rgommers 
I was mistake for a moment. I am so imprudent.
I will re-work this feature.

**Comment by akahard2dj** [comment]
> `array_equal` compares _values_, while what you care about here is whether `input` and `output` are the same object.

Yes, it is right. This feature is target to resolve the case of `a=ndi.balck_tophat(a, size=3, output=3)`.
That case is all of variables(`output`, return value, `input`) are same. In this situation, results is always zero.
Because of below part
```python
    tmp = grey_erosion(tmp, size, footprint, structure, output, mode,
                                   cval, origin)
...
...
    if input.dtype == numpy.bool_ and tmp.dtype == numpy.bool_:
        numpy.bitwise_xor(tmp, input, out=tmp)
    else:
        numpy.subtract(tmp, input, out=tmp)

    return tmp
```
After `grey_erosion` calculation, `tmp` value is alway same for `intput`. so result is zero value.
but in this case, when I remove `output` variable from `grey_erosion`, `tmp` is not `input`.
so result is normally processed.

My mistake was final value(output=tmp) is ignored.

**Comment by pv** [comment]
Thanks, but this seems to be the wrong approach. I left a comment in https://github.com/scipy/scipy/issues/9553#issuecomment-519231669 on how the issue should be fixed.

**Pull request closed without merging**
