### PR TITLE
MAINT: stats: fix and thoroughly test `rv_sample` at non-integer xk

### LINKED ISSUE #3758: discrete distribution defined by `values` with non-integer xk
I'm just checking an example that uses a noninteger xk. I'm surprised that it actually seems to be working for pmf, cdf and ppf. I thought this is not allowed, and I don't remember any unit tests for this. I'm puzzled and think that it's not supposed to work correctly.

http://stackoverflow.com/questions/24401723/given-a-frozen-scipy-discrete-random-variable-how-can-i-know-its-support/24407565

```
>>> scipy.__version__
'0.13.3'
```

```
>>> xk = [0, 1, 4, 9.1, 9.5, 9.6, 11]
>>> pk = np.ones(len(xk)) / float(len(xk))
>>> di = stats.rv_discrete(values=(xk, pk))
>>> di.ppf(np.linspace(0, 1, len(xk) + 1))
array([ -1. ,   0. ,   1. ,   4. ,   9.1,   9.5,  11. ,  11. ])
>>> di.ppf(np.linspace(0, 1, len(xk) + 1) + 0.01)
array([  0. ,   1. ,   4. ,   9.1,   9.5,   9.6,  11. ,   nan])
>>> di.ppf(np.linspace(0, 1, len(xk) + 1) - 0.01)
array([  nan,   0. ,   1. ,   4. ,   9.1,   9.5,   9.6,  11. ])

>>> xk = np.linspace(0, 1, 6)
>>> pk = np.ones(len(xk)) / float(len(xk))
>>> di = stats.rv_discrete(values=(xk, pk))
>>> di.ppf(np.linspace(0, 1, len(xk) + 1))
array([-1. ,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])
>>> di.ppf(np.linspace(0, 1, len(xk) + 1) - 0.01)
array([ nan,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])
>>> di.ppf(np.linspace(0, 1, len(xk) + 1) + 0.01)
array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  nan])
>>> di.inc
1
```

check if it really works, or raise Error ?

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Closes gh-3758

#### What does this implement/fix?
gh-3758 noted that some methods of `rv_discrete` distributions defined by `values` (`xk`/`pk` pairs, not formulas) work for non-integral `xk`, but not all do. The situation was improved by gh-5672, but more work was needed. This PR aims to fix the methods that were not working as expected and test all methods thoroughly.

There are two main problems:
* in `rv_discrete`, the `pmf` was defined to be zero for non-integral `xk`. The solution is simply to add this condition only for `rv_discrete` that are not instances of `rv_sample` (that is, defined by `values`)
* `rvs` seems to have problems, too, but I haven't looked into it closely yet. Should be easy enough to fix, because passing uniformly distributed random variates into the `ppf` works just fine.

### CODE REVIEW

**Comment by mdhaber** [comment]
@ev-br I thought you might be interested in reviewing this because the changes needed after you wrote gh-5672 are so minor. This is mostly tests.

One problem that remains with float `xk` is that `pmf` is zero unless the argument is _strictly_ equal to one of the provided `xk`, and `cdf` jumps exactly at the `xk`. There are many cases in which this could cause problems; one example is when the distribution is frozen with nonzero `loc`. I'd prefer to resolve this by adding a note about it in the docstring, but we could also try to add some wiggle room to the `pmf` function, transition `cdf` slightly below the `xk`s, etc.

**Comment by mdhaber** [comment]
Failure is:
```
=================================== FAILURES ===================================
___________________________ TestRvDiscrete.test_rvs ____________________________
[gw1] linux -- Python 3.9.12 /opt/hostedtoolcache/Python/3.9.12/x64/bin/python
../../build-install/lib/python3.9/site-packages/scipy/stats/tests/test_distributions.py:2505: in test_rvs
    assert_(isinstance(x, int))
E   AssertionError
        p          = 0.0
        probability = [0.0, 0.3, 0.4, 0.0, 0.3, 0.0]
        r          = <scipy.stats._distn_infrastructure.rv_sample object at 0x7f5f34f60430>
        s          = 4
        samples    = 1000
        self       = <scipy.stats.tests.test_distributions.TestRvDiscrete object at 0x7f5f65291a60>
        states     = [-1, 0, 1, 2, 3, 4]
        x          = 1
=========================== short test summary info ============================
```
This is because for `rv_sample` I eliminated the problematic cast to `int`. I suppose I could cast based on the data type of `xk`.

**Comment by tupui** [comment]
Agreed with not trying to do any custom casting. Let's keep things simple and return the same kind of objects in all cases.

**Review by ev-br — APPROVED** [review]
Wow, tests are impressive!

Overall, I'm about +0.5 on this.
I'm definitely not a fan of isinstance calls in generic `pmf` code---this feels like a scotch tape fix over a bigger design issue frozen in by backcompat --- but it's OK. There are many contortions in the distributions code and this is not a show-stopper.

<here was a long rant but I removed it and went on to test the PR instead>

What bothers me more is exact equality in the floating point.

This is a *huge* improvement over the status quo:

```
In [5]: rv = rv_discrete(values=(np.arange(1, 4) / 3, [1 / 3] * 3))

In [6]: data = rv.rvs(size=24); data
Out[6]: 
array([0.66666667, 1.        , 1.        , 0.33333333, 0.33333333,
       0.33333333, 0.66666667, 1.        , 0.33333333, 0.66666667,
       0.33333333, 0.33333333, 1.        , 0.66666667, 0.33333333,
       0.66666667, 0.66666667, 0.66666667, 0.33333333, 0.66666667,
       0.66666667, 1.        , 0.33333333, 0.33333333])
```

and so is this:

```
In [8]: rv.pmf(data)
Out[8]: 
array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333])
```

However, this is not so nice:

```
In [12]: rv.pmf(data + 1e-16)
Out[12]: 
array([0.        , 0.33333333, 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.33333333, 0.        , 0.        ])
```

OTOH, the example *is* contorted, and some form of this is inevitable if we ditch the integrality requirement and maybe it's OK. I started this review by saying I'm neutral but changed my mind -- I'm about +0.5 since it's maybe not perfect, but it's a clear improvement. 
So my suggestion is to merge it as is and think about improvements is subsequent PRs (half-formed ideas to follow)

**Comment by mdhaber** [comment]
No, I don't think the example is contorted. I wrote about that sort of thing [just above](https://github.com/scipy/scipy/pull/15932#issuecomment-1086949899).

**Comment by ev-br** [comment]
Speaking of half-formed ideas, triggered by looking at this PR (been a while since I looked at stats.distributions). A couple of random recollections, feel free to ignore if that's not something you'd want on you plate Matt:

- a while ago Josef was suggesting to make rv_sample public, and deprecate/remove the hacky dispatch in `rv_discrete.__new__`. This would make it easier to reason about the behavior w.r.t. exact equality in the floating point.
- one thought is to to the opposite to this PR : error out on non-integer `xk` right in the constructor and add something like a recipe to the docstring: enumerate the `xk` values, create a `rv_sample` with `values=(np.arange(len(xk)), pk)` and manage the mapping between indices and `xk` values in the user code. Probably not worth it, so just throwing it out there.
- a completely unrelated thing: `self.inc != 1` in `rv_discrete` subclasses, still buggy.

W.r.t. your aside on python types vs numpy dtypes --- I strongly suspect it's from the mists of time when mammoths roamed the Earth, the Scipy Core was a thing, and Numpy was not yet. So likely OK to change, preferably early enough in the release cycle, just in case :-).

**Comment by ev-br** [comment]
Comments crossed. Twice. So it sounds like we agree to merging this as is, and then disentangling `rv_sample` to a first-class citizen in a sequel?

**Comment by mdhaber** [comment]
> then disentangling rv_sample to a first-class citizen in a sequel?

Yes, sounds good to me. I'd be happy to review that.

**Comment by mdhaber** [comment]
Just a note @ev-br that exposing `rv_sample` would resolve gh-8057, too.

**Comment by ev-br** [comment]
Agreed, let's get this in and iterate. Thank @mdhaber !

**Comment by tadamcz** [comment]
Hi there, thanks for this work! 

My understanding that `rv_sample` either was never public or was made non-public by this reversion: https://github.com/scipy/scipy/pull/17471.

However, it is called by `rv_discrete` when `values` is provided. So perhaps the docs for `rv_discrete` need to be updated? It still [says](https://github.com/scipy/scipy/blob/v1.11.1/scipy/stats/_distn_infrastructure.py#L3042-L3045) `xk` must be integers.

```python
class rv_discrete(rv_generic):
    """
    ...

    values : tuple of two array_like, optional
        ``(xk, pk)`` where ``xk`` are integers and ``pk`` are the non-zero
        probabilities between 0 and 1 with ``sum(pk) = 1``. ``xk``
        and ``pk`` must have the same shape.

    ...
    """
```

If the docs are all that needs to change, I'm happy to make a PR for that. Personally I'd maybe also change the [example](https://github.com/scipy/scipy/blob/v1.11.1/scipy/stats/_distn_infrastructure.py#L3143-L3155) to make things as clear as possible:

```python
>>> np.linspace(0, 21, num=7)  # instead of xk = np.arange(7)
```

-------

btw, as a side note. As far as I can tell, `rv_sample` only supports "frozen" distributions, unlike all other discrete distributions in SciPy. Instantiating a frozen distribution first, and then calling its methods (e.g. `.pmf` etc.), is the usage I find most intuitive anyway for a discrete distribution with custom values, so this is not a big deal. It only confused me initially because the rest of `_distn_infrastructure.py` goes to great lengths to allow frozen and non-frozen usage, but normal users probably never look in `_distn_infrastructure.py` or wonder about this stuff.

**Comment by tadamcz** [comment]
> Another alternative is to deprecate values and make an rv_sample class public.

This might be fine as well. It would bring things closer in line with `rv_continuous` which is only used for subclassing. It's a bigger change though.

**Comment by mdhaber** [comment]
@tadamcz thanks for your interest. https://github.com/scipy/scipy/pull/17236#issuecomment-1288420090 showed many issues with `rv_sample` that are not easy to fix, so we removed it before releasing it. Instead, I will be replacing it as part of https://github.com/scipy/scipy/issues/15928. I can review your recent PR (gh-18803) if you like because it is simple enough, so I wouldn't recommend additional work on `rv_sample`.

**Comment by tadamcz** [comment]
I am aware of https://github.com/scipy/scipy/issues/15928, which is wonderful to see; that change would eliminate issues that confused me for multiple _years_ (especially when I was a less experienced Python programmer; nowadays I believe finally understand the current distribution infrastructure pretty well, but it still makes my life harder [e.g.](http://tadamcz.com/rvtools/index.html)). I just noticed you got money for it from CZI, nice. 

Depending on how close that is to completion (it's clearly a huge overhaul), changing the docs re integer `xk` might still be good in the meantime. Your call, just let me know and I will / won't make the PR.

Just to be clear, https://github.com/scipy/scipy/pull/18803 is a separate issue from the question of integers vs floats that I'm discussing here, and is not purely a docs change. https://github.com/scipy/scipy/pull/18803 seemed more obvious to me so I just made the PR without waiting to get your thoughts.

**Comment by mdhaber** [comment]
> Your call, just let me know and I will / won't make the PR.

Thanks.

**Pull request merged**
