### PR TITLE
MAINT: Pin pybind11==2.13.1

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
pybind11 released 2.13.3 yesterday. That might be related to the failures on Windows that just started.

### CODE REVIEW

**Review by lucascolley — COMMENTED** [review]
pins will be needed in CI also. Do we not want to try 2.13.2 first?

**Comment by WarrenWeckesser** [comment]
We have this nice system for generating requirements files in `requirements/`. Shouldn't the CI tools use those files?

**Comment by lucascolley** [comment]
> We have this nice system for generating requirements files in requirements/. Shouldn't the CI tools use those files?

There's probably room for improvement there, yeah, although various CI jobs deliberately test certain versions of dependencies.

**Comment by WarrenWeckesser** [comment]
> Do we not want to try 2.13.2 first?

2.13.2 and 2.13.3 were released on the same day, so 2.13.3 is probably a quick fix for a problem in 2.13.2. I wanted to go back to a version that we know should work.

**Comment by WarrenWeckesser** [comment]
The two Windows jobs that were failing with a compiler error pass here, so that confirms that the problem is pybind11, particularly https://github.com/pybind/pybind11/issues/5300.

Pinning isn't necessarily the right solution at the moment--pybind11 might get a fix out quickly--so I'm closing this PR.  Our CI gurus can decide if we should actually implement the pin.

**Pull request closed without merging**
