### PR TITLE
DOC/MAINT: stats: fix some typos

### PR DESCRIPTION
**Pull request by musvaage**
_cf_: https://github.com/scipy/scipy/pull/19295#issuecomment-1732672660

per request will revert changes to the C code

WONT' FIX

```
$ grep -nr awailable scipy
scipy/scipy/stats/biasedurn/stoc3.cpp:802:   For further documentation see nchyp.pdf, awailable from www.agner.org/random
$ grep -nr consequtive scipy/scipy/stats
scipy/scipy/stats/biasedurn/wnchyppr.cpp:832:   int converg = 0;              // number of consequtive terms below accuracy
scipy/scipy/stats/biasedurn/wnchyppr.cpp:1607:   int converg = 0;                    // number of consequtive terms below accuracy
$ grep -nr obtimized scipy/scipy/stats
scipy/scipy/stats/biasedurn/stoc3.cpp:329:   // and one for up search, because they are obtimized for consecutive x values.
$
```

### CODE REVIEW

**Review by rkern — APPROVED** [review]
LGTM! Thanks!

For future PRs, please take a look at [our documentation concerning git commit messages](http://scipy.github.io/devdocs/dev/contributor/development_workflow.html#writing-the-commit-message). Thanks!

**Comment by musvaage** [comment]
> git commit messages

e.g.

**MAINT: doc: typos**

Time permitting can your reply as to whether any of the following files should be left untouched?

```
$ cat doc.sh
#!/bin/sh

sed -i "s/alongsize/alongside/g" scipy/doc/source/release/1.3.0-notes.rst
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_fligner.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_bartlett.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_normaltest.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_skewtest.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_jarque_bera.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_spearmanr.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_kurtosistest.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_kendalltau.md
sed -i "s/aymptotic/asymptotic/g" scipy/doc/source/tutorial/stats/hypothesis_levene.md
sed -i "s/definifing/defining/g" scipy/doc/source/tutorial/interpolate/smoothing_splines.rst
sed -i "s/guassian/gaussian/g" scipy/doc/source/release/1.5.0-notes.rst
sed -i "s/intepreter/interpreter/g" scipy/doc/source/release/1.4.0-notes.rst
sed -i "s/iterpolation/optimization/g" scipy/doc/source/release/0.18.0-notes.rst
sed -i "s/optizimation/Ridge/g" scipy/doc/source/release/1.2.0-notes.rst
sed -i "s/pre-emptive/preemptive/g" scipy/doc/source/building/redistributable_binaries.rst
sed -i "s/prety-printed/pretty-printed/g" scipy/doc/source/building/introspecting_a_build.rst
sed -i "s/sparce/sparse/g" scipy/doc/source/release/1.9.0-notes.rst
sed -i "s/statisics/statistics/g" scipy/doc/source/dev/contributor/adding_new/new_stats_distribution.rst
sed -i "s/superceded/superseded/g" scipy/doc/source/release/0.18.0-notes.rst
sed -i "s/surpport/support/g" scipy/doc/source/dev/api-dev/array_api.rst
sed -i "s/thesame/the same/g" scipy/doc/source/release/1.4.0-notes.rst
$ 
```

**Comment by lucascolley** [comment]
for the release notes files, you shouldn't make a change to a title of a PR or issue. But you can fix typos in descriptions of what had changed in that release.

The other files look fine to change I think.

**Comment by musvaage** [comment]
> shouldn't make a change to a title of a PR or issue

that was rather obvious

WON'T FIX

```
$ sed -n '1032p' scipy/doc/source/release/1.9.0-notes.rst
* `#15835 <https://github.com/scipy/scipy/pull/15835>`__: FIX: Incorect boschloo pvalue
$ 

```

**Review by lucascolley — APPROVED** [review]
thanks!

**Pull request merged**
