### PR TITLE
DOC: more explicit example usage of scipy.linalg.lu_factor

### PR DESCRIPTION
**Pull request by ogrisel**
I think it can be helpful to be more explicit about how to recover the permutation matrix from the LAPACK pivots.

### CODE REVIEW

**Comment by lezcano** [comment]
Posting here not to deviate the discussion in the other issue even more. LAPACK pivots are 1-indexed:
https://netlib.org/lapack/explore-html/dd/d9a/group__double_g_ecomputational_ga0019443faea08275ca60a734d0593e60.html

>The pivot indices; for 1 <= i <= min(M,N), row i of the [...]

If SciPy deviates from this (and it looks like it does), then it should probably document it.

**Comment by ogrisel** [comment]
Thanks @lezcano this was probably the cause of my confusion in the previous discussion. Let me update the docstring accordingly.

**Comment by ilayn** [comment]
They are mostly coming from the strange wrappers we have, and it is a hot mess. The 0-indexing is done at the f2py wrapping. 


https://github.com/scipy/scipy/blob/maintenance/1.11.x/scipy/linalg/flapack_gen.pyf.src#L191

Don't know how but at some point we need to handle these discrepancies. Currently we are prefering the Cython interface to make naked calls without any additional wrappers in between

**Comment by ogrisel** [comment]
Thanks. I updated the PR accordingly.

**Comment by ogrisel** [comment]
The segfault in `musllinux_amd64_test` is probably unrelated.

**Comment by ilayn** [comment]
Even worse, not all pivs and ipivs are 0-indexed, it is really almost case-by-case basis.

**Pull request merged**
