### PR TITLE
CI: update encrypted tokens for CirrusCI wheel uploads

### LINKED ISSUE #17192: BUG: cirrus-ci nightly upload token is no longer valid - nightly builds are not being uploaded from cirrus
### Describe your issue.

I was browsing the nightly wheels on https://anaconda.org/scipy-wheels-nightly/scipy/files and noticed that the `macosx_arm64` and `manylinux2014_aarch64` wheels were out of date - they should've been built last weekend.
When I look at the CI build log for the cron job the upload process failed.

The settings for the cron job can be found at https://cirrus-ci.com/settings/repository/4894635377033216. The build log for the last cron job can also be found there, https://cirrus-ci.com/build/5940032849575936. The tail end of the log is below. 

The token is specified in `ci\cirrus_wheels.yml` using an encrypted variable, SCIPY_NIGHTLY_UPLOAD_TOKEN (originally created by @rgommers as SCIPY_NIGHTLY_UPLOAD_TOKEN_CIRRUS). I am not sure why the "Authorization token is no longer valid".

Assigning Ralf because he can create the tokens, and possibly try out a local upload. I wonder if the staging token is also broken.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
Uploading file "scipy-wheels-nightly/scipy/1.10.0.dev0/scipy-1.10.0.dev0-cp310-cp310-macosx_12_0_arm64.whl"
[WARNING] Distribution "scipy-1.10.0.dev0-cp310-cp310-macosx_12_0_arm64.whl" already exists. Removing.
[ERROR] ('Authorization token is no longer valid', 401)
```

### SciPy/NumPy/Python version information

N/A

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-17192

[ci skip]

### CODE REVIEW

**Comment by larsoner** [comment]
I tried looking to see if I could view the variables on CirrusCI to see if they hashes are correct at least, but I couldn't see anything. I'll just have to trust you got the copy-paste right, and if not, that you'll fix it post-haste :)

Thanks @rgommers

**Comment by larsoner** [comment]
Well that seems somewhere between buggy and dangerous in their UI! Good to know I'm not the only one at least.

**Comment by rgommers** [comment]
I think it may not be too bad actually; because it's tied to the repo, you should be able to search the repo for `ENCRYPTED[` and figure it out from there. It's just unusual, so it takes some time to get used to.

**Comment by andyfaff** [comment]
For future reference the documentation is at https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables.

The next run is supposed to be on Saturday, but we could make it happen sooner.

**Comment by andyfaff** [comment]
I changed the nightly run on cirrus to be every night. Let's see if it works today.

**Comment by andyfaff** [comment]
From the looks of it it looks like nightly is working again. https://cirrus-ci.com/task/5038087638614016?logs=upload#L12431

**Comment by rgommers** [comment]
Great, thanks for confirming @andyfaff

**Pull request merged**
