### PR TITLE
DOC: add sections to mstats overview in scipy.stats

### PR DESCRIPTION
**Pull request by chrisb83**
similar to #9062, this time for `mstats`

### CODE REVIEW

**Comment by rgommers** [comment]
Good idea.

https://travis-ci.org/scipy/scipy/jobs/410055295 claims that 4 items went missing from the function listing.

**Comment by chrisb83** [comment]
@rgommers i added the missing functions and it now passes except for 3.6. The abort seems unrelated but restarting the job did not help. any idea?

**Comment by rgommers** [comment]
> The abort seems unrelated but restarting the job did not help.

That seems to be a structural issue. No new `mpmath` or `gmpy2` releases on PyPI, but given that the failure is macOS specific, maybe some change in one of the packages in Homebrew. Either way, unrelated to this PR, I'll open a new issue for that.

**Comment by rgommers** [comment]
Merged, thanks @chrisb83

**Pull request merged**
