### PR TITLE
DOC: special: Expanded docs for special functions.

### PR DESCRIPTION
**Pull request by tpudlik**
Expands the documentation of faster versions of the common Bessel functions, derivatives of Bessel functions, Riccatti-Bessel functions, Struve functions and certain raw statistical functions.

This is a followup to #5632.  The emphasis is on noting the provenance of the underlying implementation and incorporating all information from the relevant Fortran docstrings into the Python ones.

### CODE REVIEW

**Comment by pv** [comment]
In the new examples that use plots, you need to add the `import matplotlib.pyplot as plt` import.
cf. https://travis-ci.org/scipy/scipy/jobs/106878537#L3358

**Comment by tpudlik** [comment]
There's something funny about this error, because the examples missing `matplotlib.pyplot` imports are not new---they were already in `master` and appear in functions I haven't edited.  But the errors don't come up in `master`, either in Travis or on my own machine, only in my branch.  Huh.

Anyway, I added the import statements, and this fixed the error.

**Comment by ev-br** [comment]
It's probably just that we forgot to run `generate_ufuncs.py` previously, so that `add_newdocs` and actual docstrings got out of sync, until *you* regenerated them. (cf http://scipy.github.io/devdocs/generated/scipy.special.wofz.html which seems to be missing the plot et al).

**Comment by tpudlik** [comment]
@ev-br I think that must be it: the plots were introduced in https://github.com/scipy/scipy/commit/222f7bf5711c73b086e9c2ed0e486be64a8976bb, but `_ufuncs.pyx` has not been regenerated since until this PR.

**Comment by pv** [comment]
In the discussion of the struve function --- """Rounding errors are estimated based on the largest terms in the sums, and the result associated with the smallest error is returned.""" --- the Python function does not return error estimates. Instead, it will return nan if the error is too large, iirc sqrt(eps).

**Comment by pv** [comment]
Another thing to note is that some of the Cephes routines have been modified (don't remember which, `git log -- scipy/special/cephes` should reveal), so "based on ..." probably should be added in those descriptions.

**Comment by pv** [comment]
Ok, I read wrong --- the struve description is fine.
Thanks, merged!

**Comment by ewmoore** [comment]
There appear to be some issues.  Looking at http://scipy.github.io/devdocs/generated/scipy.special.j0.html#scipy.special.j0  there are a number of `[Math Processing Error]` across this page and others.

**Comment by pv** [comment]
The errors vanished on reload --- maybe something intermittent?

**Comment by tpudlik** [comment]
I wasn't able to reproduce the error in either Chrome, Firefox, or IE11---everything looks fine to me.

Sounds like it might be a MathJax issue?  (Based on, say, the discussion here: http://meta.math.stackexchange.com/a/3630/60522)

**Pull request merged**
