### PR TITLE
DOC: changed documentation of brent to be consistent with bracket

### PR DESCRIPTION
**Pull request by person142**
Closes gh-5408.

### CODE REVIEW

**Comment by rgommers** [comment]
I think this formulation is clearer. I verified that the last sentence about not meeting ``

        elif len(brack) == 3:
            xa, xb, xc = brack
            if (xa > xc):  # swap so xa < xc can be assumed
I think this formulation is clearer. I verified that  ``... satisfy xa<=x<=xb`` indeed only refers to the case where ``brack`` is of length 2.

**Comment by rgommers** [comment]
Merged, thanks @person142

**Comment by rgommers** [comment]
Just saw this snippet in ``Brent``:

        elif len(brack) == 3:
            xa, xb, xc = brack
            if (xa > xc):  # swap so xa < xc can be assumed
                xc, xa = xa, xc

Why not just raise an exception.....

**Comment by josef-pkt** [comment]
I think before adding an exception, someone has to figure out what brent is actually doing in the different cases. I haven't tried the 3 value brackets again, but the 2 value brackets (a,b) seem to work fine whether a< b or a>b.

(In my example, brent destroyed the sorting I had in a double loop because it found an optimum outside (a,b), but it kept successfully working in spite of unsorted (a,b) values.
Now, I force the sorting of the brackets inside the loop https://github.com/statsmodels/statsmodels/pull/2677 )

**Comment by person142** [comment]
@rgommers: shoot, should have changed the ```xa<xb<xc``` part in the documentation too. My apologies.

I was trying to make the minimal changes necessary for correctness, but more generally what's your opinion on beefing up the documentation for ```bracket``` (and perhaps as a consequence ```Brent```) some? (i.e. describing what it's doing to get the bracket, which based on the presence of the golden ratio I imagine is golden section search, but I haven't checked the code.) I'd be willing to do it. (Am trying to find small things to work on to get familiar with the project.)

**Pull request merged**
