### PR TITLE
MAINT: special: Make sine and cosine integrals work in CUDA

### PR DESCRIPTION
**Pull request by steppi**
This PR makes it so the functions `sici` and `shichi` will work in CUDA.  These functions compute *sine and cosine integrals* and *hyperbolic sine and cosine integrals* respectively. These are examples of ufuncs which return multiple values, e.g. `sici(x)` returns a tuple containing the both the sine integral and the cosine integral evaluated at `x`. I thought it would be good to work on these because I had yet to attempt getting a function with multiple output values to work in CuPy.

Getting this working required translating the complex valued `shichi` and `sici` implementations from Cython to C++. The real valued implementations from Cephes were already translated into C++ and needed only small adjustments to work on CUDA. I also needed to make `expi` and hence `exp1` which it depends on work in CUDA, since the complex valued `sici` and `shichi` depend on `expi`. I've made it so the entire file `scipy/special/special/expint.h` will work in CUDA, which required moving some code out of `scipy/special/special/specfun/specfun.h` and into `scipy/special/special/expint.h` and making the changes to it needed to get it working on CUDA.

I've added relevant tests to `test_xsf_cuda.py`, which tests that these implementations will compile when used in a CuPy `ElementwiseKernel`. These are the first tests I've added here for functions with multiple return values; only a minor adjustment was needed there to make this work.

cc @rlucas7. I know you don't have much bandwidth at the moment, but am just putting this on your radar.

### CODE REVIEW

**Comment by steppi** [comment]
@rlucas7, I've cleaned up the merge conflicts. This is ready to review again.

**Comment by steppi** [comment]
Ah, more merge conflicts after merging #21401. I’ll have time to fix in a few hours.

**Comment by steppi** [comment]
This PR also fixes `test_xsf_cuda.py` in general, which is broken on main because the include path for the headers used in this file was not changed from `special` to `xsf` in #21297 .

**Comment by rlucas7** [comment]
> @rlucas7, I've cleaned up the merge conflicts. This is ready to review again.

Ok, Taking a look today-apologies for delay and thanks for the reminder.

**Comment by rlucas7** [comment]
This looks good to me as is but there are 3 files with merge conflicts to main/master. Can you resolve those so I can merge this? 

Screenshot 2024-08-30 at 6 07 44 PM
After manual removal of the xslow skip, these run-and pass-as part of
```bash 
python dev.py test -s special
``` 
and individually via:
```bash
python dev.py test -t scipy.special.tests.test_xsf_cuda
```
They take about 8 minutes to run on a `g4dn.xlarge` for only the `test_xsf_cuda.py` module.

**Comment by steppi** [comment]
Thanks @rlucas7. No worries about the delay. I've cleaned up the merge conflicts.

**Review by rlucas7 — APPROVED** [review]
This LGTM I'll merge Monday (September 2nd) if no other concerns.

**Comment by steppi** [comment]
I removed the tests for `iv_ratio.c` from `test_xsf_cuda.py`. They were broken by https://github.com/scipy/scipy/pull/20760; the failure is unrelated to this PR.

**Comment by rlucas7** [comment]
> I removed the tests for `iv_ratio.c` from `test_xsf_cuda.py`. They were broken by #20760; the failure is unrelated to this PR.

Ok these latest changes seem aligned with what you wrote on #20760 except for one thing which perhaps I'm mistaken in my understanding on; for these xsf tests I understood that the tests are testing that the kernels compile on cuda architectures using nvrtc mechanism-and they passed for me, see above comments in my review. However, @steppi you wrote in #20760 [here](https://github.com/scipy/scipy/pull/20760#issuecomment-2323919363) 

> I've found that the `double_double` arithmetic currently doesn't compile in NVRTC ...

So are these tests passing because we're not testing for that particular type (`double_double`) in the compilation here for xsf or am I missing something? 

I'll hold off to merge until I grok this point but o/w I think this pr and these changes are fine to merge.

**Comment by steppi** [comment]
> So are these tests passing because we're not testing for that particular type (`double_double`) in the compilation here for xsf or am I missing something?

Basically, it’s just that not everything we’ve done works with NVRTC yet. This PR for instance takes some things we’ve translated to C++ already and makes them work with NVRTC. I had added tests for `iv_ratio.h` earlier even though it’s only used in private functions in SciPy, because I wanted to test if the kahan summation and continued fraction evaluation tools @fancidev wrote for that PR work with NVRTC. @fancidev added `double_double` arithmetic to `iv_ratio.h` in a recent PR, which isn’t working with NVRTC due to dynamic allocations. Since `iv_ratio` is currently private, and the scope of things we plan to add to CuPy are ufuncs in SciPy special’s public API, there’s no harm in taking those tests out; and failing `iv_ratio` tests have no bearing on the correctness of the current PR. If we want to get `iv_ratio` or other functions using `double_double` arithmetic to work with NVRTC, I think best solution will be to use conditional compilation to do those computations with regular doubles when running with CUDA, accepting that we’ll get worse accuracy. Rather than making double_double arithmetic work with NVRTC, since the latter will be slow on GPU anyway.

**Comment by rlucas7** [comment]
> Since `iv_ratio` is currently private, and the scope of things we plan to add to CuPy are ufuncs in SciPy special’s public API, there’s no harm in taking those tests out; and failing `iv_ratio` tests have no bearing on the correctness of the current PR.

I see, this is the thing I was missing I think, `iv_ratio` is private. To be clear I'm *not* suggesting that we should work to include double double, I am only trying to confirm and clarify any misunderstandings, e.g why I didn't notice any compilation breakage for double double. 

I'll merge to master/main now-thanks for clarifying @steppi

**Comment by rlucas7** [comment]
Also probably worth noting the `iv_ratio` pr was only merged a couple days ago so the rebase made the change get included.

**Comment by steppi** [comment]
Thanks @rlucas7! Sorry, I should have explained better when I took the iv_ratio test out. Can you take a look at #21454 next? There’s kind of a lot going on in that one, but it already got a close look from @fancidev on the math side, so hopefully isn’t too bad to review.

**Pull request merged**
