### PR TITLE
Fix the behavior of discrete distributions at the right-hand edge of the support

### PR DESCRIPTION
**Pull request by ev-br**
Previously, the behavior of  discrete distributions at positive infinity depended on whether the corresponding special functions were or were not able to handle infinities. For instance,

```
In [3]: poisson.sf(np.inf, 0.5)
/home/br/scipy/build/testenv/lib/python2.7/site-packages/scipy/stats/_discrete_distns.py:463: RuntimeWarning: floating point number truncated to an integer
  return special.pdtrc(k, mu)
Out[3]: nan
```

(I was sure there was a ticket about this, but I cannot find it.)

### CODE REVIEW

**Comment by argriffing** [comment]
Looks good to me!

**Comment by argriffing** [comment]
Thanks @ev-br!

**Comment by WarrenWeckesser** [comment]
I get two errors now in the `stats` test suite. This is with numpy 1.10.1, python 2.7.10, Mac OS X 10.9.5:

```
$ python -c "import scipy.stats as m; m.test('full')"
Running unit tests for scipy.stats
NumPy version 1.10.1
NumPy relaxed strides checking option: True
NumPy is installed in /Users/warren/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.17.0.dev0+bdea80d
SciPy is installed in /Users/warren/local_scipy/lib/python2.7/site-packages/scipy
Python version 2.7.10 |Anaconda 1.8.0 (x86_64)| (default, Sep 15 2015, 14:29:08) [GCC 4.2.1 (Apple Inc. build 5577)]
nose version 1.3.7
...<snip>...
======================================================================
ERROR: test_discrete_basic.test_discrete_basic(<scipy.stats._discrete_distns.dlaplace_gen object at 0x10407e050>, (0.8,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/warren/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/tests/common_tests.py", line 113, in check_edge_support
    npt.assert_equal(distfn.logcdf(x, *args), [-np.inf, 0.0])
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2964, in logcdf
    place(output, cond, self._logcdf(*goodargs))
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 845, in _logcdf
    return log(self._cdf(x, *args))
RuntimeWarning: divide by zero encountered in log

======================================================================
ERROR: test_discrete_basic.test_discrete_basic(<scipy.stats._discrete_distns.skellam_gen object at 0x10407e110>, (15, 8))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/warren/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/tests/common_tests.py", line 113, in check_edge_support
    npt.assert_equal(distfn.logcdf(x, *args), [-np.inf, 0.0])
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 2964, in logcdf
    place(output, cond, self._logcdf(*goodargs))
  File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py", line 845, in _logcdf
    return log(self._cdf(x, *args))
RuntimeWarning: divide by zero encountered in log
```

**Comment by argriffing** [comment]
@WarrenWeckesser Yes, now I see that those warnings are present in the passing Travis test https://travis-ci.org/scipy/scipy/jobs/87121115.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/5412 fliters out these warnings.

**Pull request merged**
