### PR TITLE
ENH: stats: Add freezability to `unitary_group`

### PR DESCRIPTION
**Pull request by NamamiShanker**
#### Reference issue

#15617 

#### What does this implement/fix?

Implement `unitary_group` freezability

### CODE REVIEW

**Comment by NamamiShanker** [comment]
Hey @mdhaber, I cannot understand why the doc build is failing. The error message also doesn't specify anything. Can you help me out here?

**Comment by mdhaber** [comment]
Not your fault. It's in main. Just take a look at the artifacts - do they look right?

**Comment by NamamiShanker** [comment]
Yes, the artifact of `unitary_group` looks correct. Also, this other error in `refguide_asv_check` shows errors in functions that were not a part of my commit. Should I do anything regarding those functions?

**Comment by mdhaber** [comment]
Great! This looks perfect to me. (We'll improve the documentation regarding freezing for all the multivariate distributions later.)

**Pull request merged**
