### PR TITLE
MAINT: stats.rankdata: change default to nan_policy='propagate'

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-16140

#### What does this implement/fix?
gh-16140 added `nan_policy` to `stats.rankdata`, but the default value is `'omit'` instead of the usual `'propagate'`. I merged it, but I'm reconsidering this choice of default. I thought I'd open this for further discussion (and to set a precedent for other `nan_policy` implementations where `'propagate'` doesn't just mean "run the code without considering NaNs").

On one hand, `'omit'` is a good default because it more closely matches the behavior before the introduction of the `nan_policy`.

Before `nan_policy`:
```python3
from scipy.stats import rankdata
rankdata([0, 2, 3, 2, np.nan, np.nan])  # array([1.  2.5 4.  2.5 5.  6. ])
```

After gh-16140:
```python3
rankdata([0, 2, 3, 2, np.nan, np.nan])  # array([1.  2.5 4.  2.5 np.nan np.nan ])
rankdata([0, 2, 3, 2, np.nan, np.nan], nan_policy='omit')  # same as above
rankdata([0, 2, 3, 2, np.nan, np.nan], nan_policy='propagate')  # array([nan, nan, nan, nan, nan, nan])
```

But the behavior of the original code wasn't intentional; it was an artifact of the implementation. So this PR suggests making the default `nan_policy='propagate'` like pretty much every other stats function.

One other thought is that `rankdata` might be easier to use if `nan_policy='omit'` were the default - but the same could be said of any other stats function. The counter-argument is that it is also easier to make mistakes you don't catch if `nan_policy='omit'` is the default. For better or for worse, `nan_policy='propagate'` is the default in other functions, so I think that `stats` as a whole would be easier to use if the user doesn't need to remember (or look up) a different default for each function.

#### Additional information
gh-13572 added `nan_policy` with default `'propagate'` to `stats.percentileofscore`. It's worth mentioning because, like `rankdata`, `nan_policy='propagate'` changes the behavior compared to "just run the code without considering NaNs" (as the code did before the PR; see gh-2868).

### CODE REVIEW

**Review by AtsushiSakai — COMMENTED** [review]
IMO, “omit” is useful for more use cases than “propagate”, so I feel “omit” should be default personally. I understand “propagate” is more correct theoretically, because comparing numbers to nan is undefined. However, in typical cases, if a list has some nans, I would like to get rank data excepts nans in default, this is “omit behavior. But I would like to hear other opinions.

**Comment by tupui** [comment]
I also like the omit better. I think it corresponds more to what users might want. This is also what pandas does. https://pandas.pydata.org/docs/user_guide/missing_data.html#calculations-with-missing-data

They propagate for arithmetic operations, but for the rest they use omit.

**Comment by mdhaber** [comment]
@tirthasheshpatel I'd appreciate your opinion here. I understand the arguments above for using `'omit'` - it is more useful. But I see that as an argument for why 'omit' should be the default across the board, not why `'omit'` should be the default for this function _only_. We are working hard to offer a consistent `nan_policy` experience throughout `stats` functions, so I don't really like the idea of creating a new special case like this.

**Comment by tirthasheshpatel** [comment]
I agree that `'omit'` is a better option for all the stats functions. If we are enforcing consistency across the stats module, then `'propagate'` makes more sense. Although it would be great to have a warning or note in the docs highlighting the behavior of `rankdata` with `nan_policy='propagate'` if we don't have it already.

**Review by tirthasheshpatel — APPROVED** [review]
I didn't think of consistency when suggesting to use `'omit'` as default. Since we have been enforcing it at other places in stats, it would be better to be consistent here too. @tupui Do you have an opinion here?

**Comment by tupui** [comment]
As I said I prefer omit, but I am fine with propagate as well for consistency reasons. If at some point we want to revisit everything we could do it in one go with a deprecation période for the whole policy.

**Comment by mdhaber** [comment]
> As I said I prefer omit, but I am fine with propagate as well for consistency reasons. If at some point we want to revisit everything we could do it in one go with a deprecation période for the whole policy.

Yes. I will not lead the charge to charge it before a SciPy 2.0 is discussed, but I would probably not oppose it. I can see much stronger cases for the default being `nan_policy=None` (no checks for NaNs at all, which is better for speed) or `nan_policy='omit'` than I can for `nan_policy='propagate'`.

But in the meantime, I think there is the strongest case to be made for consistency. 
LMK if there's anything to do here.

**Review by tupui — APPROVED** [review]
Ok I think we are all on the same page. Let's get this in. Thanks all 😃

**Pull request merged**
