### PR TITLE
MAINT: Adds implicit none to fftpack fortran sources

### PR DESCRIPTION
**Pull request by richardjgowers**
Should start #3168

I'm not entirely sure that `REAL*8` is identical to `DOUBLE PRECISION` across all compilers/platforms.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @richardjgowers. Looks like a good idea. I don't speak much Fortran, so will leave review to others. @ev-br is that issue/idea still important you think?

Just a note on fftpack: after many years it looks like we now have a good alternative with pocketfft (https://github.com/numpy/numpy/pull/11888); if that works fine for `numpy.fft` I imagine we'll drop it into SciPy as well. So more than essential maintenance for `scipy.fftpack` is probably unneeded effort at this point.

**Comment by richardjgowers** [comment]
I ended up writing a script that does this, so if there’s another module
that needs this more I can do that instead

**Comment by ev-br** [comment]
I worked on this for a bit a while ago. It turned out to be much better than I originally thought, the errors were mostly trivial, so all in all I now think that issue as mostly maintenance, not very high prio.

Re `real*8` vs `double precision`: these were equivalent on all systems I met, but the language-lawyer does say these are not necessarily equivalent. So better revert to `double precision`, especially for these venerable libraries. And then the PR can be merged since the work has already been done.

**Comment by richardjgowers** [comment]
@ev-br ok I switched over to `DOUBLE PRECISION`, should be good to go

**Comment by ev-br** [comment]
Yup, let's get this in. Thanks @richardjgowers

**Pull request merged**
