### PR TITLE
DOC: minor issues in install commands

### PR DESCRIPTION
**Pull request by RobPasMue**
#### Reference issue
None related.

#### What does this implement/fix?
Trying to install the project in dev mode, I realized there were two install statements missing.

#### Additional information
None.

[skip ci]

### CODE REVIEW

**Comment by RobPasMue** [comment]
Related to SciPy Conference '23

**Comment by RobPasMue** [comment]
@melissawm

**Comment by melissawm** [comment]
Thanks - seems pretty straightforward and the right fix. Congrats on your first PR to SciPy 🎉

**Comment by RobPasMue** [comment]
Thanks, really appreciated! Even though it was simple =)

**Pull request merged**
