### PR TITLE
ENH, TST: Use explicit imports in docstring examples

### PR DESCRIPTION
**Pull request by Sheila-nk**
#### Reference issue

N/A

#### What does this implement/fix?

- Fixes missing imports and ensures functions and classes are explicitly imported when used in the docstrings.
- This PR also includes unmerged docstring fixes from @ev-br 's draft PR: [WIP: verify doctesting refactor #16391](https://github.com/scipy/scipy/pull/16391)

#### Additional information

N/A

### CODE REVIEW

**Comment by ev-br** [comment]
So the bulk of changes here are in docstrings of non-public functions, which the refguide-checks ignores (it only looks at the public functions).

While we don't have a way of checking these on CI just yet, eyeballing the changes LGTM.

To those reading the patch: this is a part of @Sheila-nk 's internship work on building a reusable pytest plugin our of refguide-check docstring checking utility.

Sheila, one quick note for your future PRs: it'd be nice to skip non-needed CI runs. Here you are only touching the docs, thus everything apart from CircleCI can be skipped (https://docs.scipy.org/doc/scipy/dev/contributor/continuous_integration.html#skipping).

**Comment by Sheila-nk** [comment]
Thanks for the review @ev-br and for providing extra context where I failed to.

> Sheila, one quick note for your future PRs: it'd be nice to skip non-needed CI runs.

Yes, I will keep this in mind for next time, thank you.

**Review by melissawm — APPROVED** [review]
These all look pretty straightforward to me, thanks @Sheila-nk !

**Comment by Sheila-nk** [comment]
Thanks for the review, @melissawm

**Review by tylerjereddy — APPROVED** [review]
Ok, two core developer approvals, and the changes seem sensible enough to me as well. Thanks for your first contribution to SciPy.

**Comment by Sheila-nk** [comment]
Great! Thanks for the review @tylerjereddy

**Pull request merged**
