### PR TITLE
DOC: optimize: add tutorial for milp

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue

N/A

#### What does this implement/fix?

From v1.9.0, the mixed integer linear programing solver [`optimize.milp`](http://scipy.github.io/devdocs/reference/generated/scipy.optimize.milp.html?highlight=milp#scipy.optimize.milp) is added.
This solver can be used for many kinds of applications, so I think it would be great to add a tutorial for `milp`.

In this PR, I added a tutorial section "Mixed integer linear programming" and added a simple tutorial to solve the Knapsack problem.
And I added a tutorial link in the `milp` Examples doc.

### CODE REVIEW

**Comment by mdhaber** [comment]
Oops, @mckib2 has been working on one. Perhaps this can be added as another example.

**Comment by mckib2** [comment]
> Oops, @mckib2 has been working on one. Perhaps this can be added as another example.

Yes, I am working on one.  No reason this one can't go in first if it's ready?  It would be nicer to have each tutorial split into its own file, but fine to kick that down the road until there are multiple tutorials here

**Comment by AtsushiSakai** [comment]
@mckib2 I'm sorry I didn't know you were already working on it. Either is fine for me, merging this PR first or waiting for your PR to be merged if your tutorial does not have a knapsack problem example.

**Review by rgommers — COMMENTED** [review]
This seems polished and ready to go, I think it should be merged. @mdhaber or @mckib2 want to review the optimization problem content?

**Comment by mdhaber** [comment]
Merging main + re-building docs so I can review.

**Comment by mdhaber** [comment]
@AtsushiSakai this is great! I made suggestions in https://github.com/AtsushiSakai/scipy/pull/3. Please consider merging that (with commit comment `[skip azp] [skip actions]`, perhaps), and then I think this is ready to merge!

**Comment by mdhaber** [comment]
Thanks @AtsushiSakai!

**Pull request merged**
