### PR TITLE
MAINT: add rvs for semicircular in scipy.stats

### PR DESCRIPTION
**Pull request by chrisb83**
add _rvs method and reference

```
timeit(stats.semicircular.rvs(size=1000))
# scipy 1.2.0
3.03 s ± 9.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
# new
2.38 ms ± 74.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

cross-ref #10106

### CODE REVIEW

**Comment by chrisb83** [comment]
"If shape_only is True, it means the _rvs method of the distribution uses more than one random number to generate a random" => this is the case for semicircular since one needs two uniform rvs for the rejection method

**Comment by WarrenWeckesser** [comment]
It occurred to me that we don't need to use the rejection method here. Just take the x coordinate of samples generated uniformly in the upper half of the unit circle:

    r = np.sqrt(np.random.rand(N))
    theta = np.pi*np.random.rand(N)
    # x is the sample from the semicircular distribution.
    x = r * np.cos(theta)

**Comment by chrisb83** [comment]
you are right, that is the idea behind the rejection method, somehow i did not see this :) thanks

**Comment by WarrenWeckesser** [comment]
Thanks, Chris, this is great.

**Pull request merged**
