### PR TITLE
ENH: extend special.spence to complex arguments.

### PR DESCRIPTION
**Pull request by person142**
Spence's function was only implemented for real arguments; this
extends it to the entire complex plane. It also adds tests for both
the real and complex versions. (Tests for the real version were
previously lacking.)

### CODE REVIEW

**Comment by person142** [comment]
The changes to ``_complexstuff.pxd`` are probably especially deserving of scrutiny and skepticism.

**Comment by pv** [comment]
Thanks, merged. Didn't read [3] though, but willing to bet on mpmath.

Some of the workarounds required in basic complex arithmetic could be pushed into numpy in principle. E.g. numpy has complex division in npy_math, but it's not exported for use. We might also want to switch to C99 complex numbers at some point, to avoid relying on Cython's implementation of complex arithmetic. Of course, C compilers / math libraries also have bugs...

**Comment by pv** [comment]
Note also that it could be good to cite the references used in the docstring of the function, not only in the source code. cf https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections

**Comment by person142** [comment]
Yes, I spent some time looking for where numpy exported complex division so that I could use it as a workaround before I read ``npy_math_complex.c.src`` and realized it wasn't exported.

IIUC, numpy doesn't use C99 complex arithmetic to deal with systems which don't support it. Is that not a concern for scipy?

**Comment by pv** [comment]
Yes, the C99 question is about whether there still are important enough platforms that don't support it (well enough). I don't recall the exact situation, but msvc may have been one.

**Pull request merged**
