### PR TITLE
BUG: fix array_like input defects and add tests for all functions in fitpack2.py

### LINKED ISSUE #12469: SciPy 1.9 exception in LSQSphereBivariateSpline
The issue is an exception in `SciPy` 1.9.0 which did not occur in earlier versions of `SciPy` ...

```
File "~/PyGeodesy/pygeodesy/heights.py", line ...
    self._ev = scipy.interpolate.LSQSphereBivariateSpline(..., eps=EPS, w=w).ev
 File "~/Library/Python/3.8/lib/python/site-packages/scipy/interpolate/fitpack2.py", line 1549, in __init__
    if w is not None and not (w >= 0.0).all():
TypeError: '>=' not supported between instances of 'list' and 'float'
```
Variable `w` is a list of `float`s ...
 ```
w = [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
```
The exception is due to ...
```
(w >= 0.0).all()
```

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
fix #12469 

#### What does this implement/fix?
I fixed array_like input defects in fitpack2.py
In #11736, all functions in fitpack2.py has input validations, but some input validations assumed input is only np.array.
But these should accept list, not only np.array, so I fixed these defects.

Also, I added tests to check all functions in fitpack2.py can accept both list and np.array.
#12469 just reports `LSQSphereBivariateSpline` has the issue, but the tests show `SmoothSphereBivariateSpline` and `RectSphereBivariateSpline` have the same issue. I fixed these also.

### CODE REVIEW

**Review by sethtroisi — COMMENTED** [review]
(not a core member) but PR looks good.

**Comment by ev-br** [comment]
Looks good to me too, CI is green modulo `test_lgmres` on ARM which is hardly related. Merging. Thanks @AtsushiSakai @sethtroisi

**Comment by ev-br** [comment]
P.S. You seemed to merge master into the branch, did you? Typically the history is cleaner and easier to bisect if you rebase on master. Did squash-merge because of that. Not a big deal.

Not sure about the backport-candidate label, is it worth the backport? This seems to be a nice improvement, but we typically limit backports to critical fixes. Or maybe the RM stance changed on this, so I'll keep the label and leave the decision to the RM.

**Comment by AtsushiSakai** [comment]
@ev-br Thank you for your review and comments.
> if you rebase on master. 

Thanks. I will do that from the next PR.

> I see it's a fix for a recent regression

Unfortunately, it is.

**Pull request merged**
