### PR TITLE
MAINT: set `NPY_NO_DEPRECATED_API` also for Cython code

### PR DESCRIPTION
**Pull request by rgommers**
This is a follow-up to gh-10840.

The one minor issue is a few "redefinition of macro" warnings because Pythran defines `NPY_NO_DEPRECATED_API` as well (and to a different value). That should be solved by https://github.com/serge-sans-paille/pythran/pull/2168.

The removal of `_build_utils/__init__.py` could have been done earlier, I only noticed because it contained the same macro - the file was already unused.

### CODE REVIEW

**Comment by rgommers** [comment]
The one CI failure is for `-Werror`, which should be solved by the linked Pythran PR. So this isn't quite mergeable yet.

**Comment by h-vetinari** [comment]
With this PR we get to also remove the following:
https://github.com/scipy/scipy/blob/7ff74ee275de307d6a17bebff4ea10cf58d35dff/doc/source/dev/roadmap-detailed.rst#L62-L67

**Comment by h-vetinari** [comment]
As a completely unrelated aside: wanting to fix `NPY_NO_DEPRECATED_API` warnings is how I nerd-sniped myself into closely following Cython 3 development for almost 5 years, so I'm very excited to see this finally happening! Crazy how long it's taken from the introduction of the deprecation in [numpy 1.7](https://github.com/numpy/numpy/releases/tag/v1.7.0) to close the loop (11 years...)

**Comment by rgommers** [comment]
> With this PR we get to also remove the following:

Note that there are two unrelated points in there. The second part can go, but the memoryviews part should stay.

**Review by h-vetinari — APPROVED** [review]
🥳

**Comment by ilayn** [comment]
This is a milestone that only maintainers can appreciate I think 🥲 In it goes. Thanks Ralf, Axel!

**Comment by rgommers** [comment]
> This is a milestone that only maintainers can appreciate I think 🥲 In it goes.

Yeah, on reflection, it is. Hat tip to @cournape for, I believe, implementing these deprecations in NumPy ~15 years ago. Took us a while to squash the last usages:)

**Pull request merged**
