### PR TITLE
BUG: fix logic error in cKDTree.sparse_distance_matrix

### PR DESCRIPTION
**Pull request by sturlamolden**
Fixes the logic error reported in #5077

### CODE REVIEW

**Comment by sturlamolden** [comment]
@rgommers Sorry that this did not make it to the 0.16 release. It should also be pushed to the 0.16.x maintenance branch.

**Comment by rgommers** [comment]
@sturlamolden no need at all to apologize - things get fixed when they get fixed, I'm already very happy that you're acting as the ``cKDTree`` maintainer.

**Comment by rgommers** [comment]
Okay, preparing for 0.16.1 so time to get this in. Thanks Sturla!

**Comment by rgommers** [comment]
will backport in a couple of days.

**Pull request merged**
