### PR TITLE
DOC: scipy.fft.fht - documentation issue 

### LINKED ISSUE #19573: scipy.fft.fht - documentation issue
### Describe your issue.

In your published documentation for scipy.fft.fht (https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fht.html) and scipy.fft.ifht, the formulas you report for the forward and inverse Hankel transforms appear incorrect. For the forward transform, I believe the integral kernel should be written as "a(r) J_u(kr) r dr". For the inverse transform, I believe the integral kernel should be written as "A(k) J_u(kr) k dk". See, for example, the link here:
https://mathworld.wolfram.com/HankelTransform.html
I believe this is just a typo in the documentation but wanted to alert you of it. I also wanted to confirm that the algorithm you developed was based around the correct formula.

### Reproducing Code Example

```python
issue does not concern code
```

### Error message

```shell
issue does not concern code
```

### SciPy/NumPy/Python version and system information

```shell
issue does not concern code
```

### PR DESCRIPTION
**Pull request by willtryagain**
#### Reference issue
Closes #19573

#### What does this implement/fix?
add clarification note

### CODE REVIEW

**Review by willtryagain — COMMENTED** [review]
fix linting

**Comment by ilayn** [comment]
which linter is this? I don't see the point of these changes.

**Comment by lucascolley** [comment]
@willtryagain hmm, your commit to fix the lint errors seems to have touched loads of lines - did you use an autoformatter? Please only change the lines which you added which caused the linter to fail - the rest are file.

```
scipy/fft/_fftlog.py:59:89: E501 Line too long (101 > 88)
scipy/fft/_fftlog.py:60:89: E501 Line too long (145 > 88)
scipy/fft/_fftlog.py:72:89: E501 Line too long (262 > 88)
```

**Comment by lucascolley** [comment]
There are still a lot of erroneous changes here - perhaps you reverted an older commit (they look like changes I made a few months ago). If things have become messy, feel free to close this PR and start again with the new branch off main.

Also, while you are pushing more commits to an open PR, please keep [our guidance on CI skips](https://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#skipping) in mind to help us save some CI time.

**Comment by willtryagain** [comment]
> There are still a lot of erroneous changes here - perhaps you reverted an older commit (they look like changes I made a few months ago). If things have become messy, feel free to close this PR and start again with a new branch off `main` (or you can reset your branch to `main` and force push).
> 
> Also, while you are pushing more commits to an open PR, please keep [our guidance on CI skips](https://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#skipping) in mind to help us save some CI time.

yeah, new pr makes sense

**Pull request closed without merging**
