### PR TITLE
DOC: expand RegularGridInterpolator docstring

### LINKED ISSUE #14926: RegularGridInterpolator should be called RectilinearGridInterpolator
https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/interpolate/interpolate.py#L2345-L2572

This function is somewhat misnamed and mis-documented. 

image

1) Points e.g. on a hexagonal/triangular grid form a **perfectly regular** grid, the resulting tessellation cells are all identical parallelepipeds, yet these points **cannot be used** with this interpolator class (even with a basis transformation, as the distance metrics are not compatible).

2) Points defined on a general rectilinear grid are **not regular**, since the cells are not all congurent parallelepipeds, yet they **can be used** with this interpolator class

image

This class should be named RectilinearGridInterpolator for accuracy.

Please see also: https://en.wikipedia.org/wiki/Regular_grid

This also applies for the documentation of interpn: https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/interpolate/interpolate.py#L2577-L2583

### PR DESCRIPTION
**Pull request by ev-br**
#### What does this implement/fix?

Expand the docstring examples of RegularGridInterpolator, stress the `fill_value = None` being the extrapolation mode, add a docstring example to the `__call__` method docstring.

#### Additional information

Also mention the Rectilinear / Rectangular grid naming issue, so that this PR hopefully closes https://github.com/scipy/scipy/issues/14926.

While technically, what this class assumes is, uhm, recilinear grids (did not know the word before gh-14926), and that not all regular grids are supported (bcc / fcc lattices etc), I believe that
- it's way too late to rename the class
- adding an alias is also not desired (API surface)
- the issue is best addressed as a doc issue, which this PR tries to do. If someone has suggestions for a better wording, that would be most welcome. 

[ci skip] [skip ci]

### CODE REVIEW

**Review by AtsushiSakai — COMMENTED** [review]
Should we also imporve `interpn` docstring to fix #14926 too?
For example, "Multidimensional interpolation on regular grids or rectilinear grids" or something like that. 
https://github.com/scipy/scipy/blob/5811dfcc5339aaaca4ab29b6155993dec7144756/scipy/interpolate/_interpolate.py#L2666

**Comment by ev-br** [comment]
OK, I added a sentence to the `interpn` docstring.

There are several further tweaks for the docstrings of `RGI` and `interpn` (e.g., Matt suggested to add an example from gh-7560 etc), let's track them in https://github.com/orgs/scipy/projects/1#card-81397314

At some point we might need to move some examples to the tutorial maybe. This needs  decision. I suggest we do things piecemeal and iterate.

**Review by AtsushiSakai — APPROVED** [review]
Thank you. LGTM.

**Review by rgommers — APPROVED** [review]
Agreed with the rationale about addressing the issue as a docs clarification.

LGTM too, in it goes. Thanks @ev-br. And thanks for the review @AtsushiSakai

**Pull request merged**
