### PR TITLE
Lapack deprecations

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This should finish off https://github.com/scipy/scipy/issues/5266. I'm posting what I have for review, but this still needs some more testing.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
I've removed the "WIP" marker. This should be done now. Thoughts?

**Comment by rgommers** [comment]
The approach of adding the functions themselves and unconditionally compiling them seems fine to me. I haven't played with this yet, but it makes sense at first sight.

**Comment by rgommers** [comment]
(@ev-br: I know that I should stop adding things to the 0.17.0 milestone, but did it anyway here - seems important to take along)

**Comment by insertinterestingnamehere** [comment]
Thanks for adding the 0.17.0 tag, it'd be really good to have support for LAPACK 3.6.0 before it becomes very common.

**Comment by ev-br** [comment]
I'm going to merge this soon unless there are further comments.

**Comment by philipdeboer** [comment]
It solved the problem I was having. I'd like to see it merged.

**Comment by rgommers** [comment]
I've tested this as well, all looks good to me. So in it goes. Thanks @insertinterestingnamehere!

**Comment by rgommers** [comment]
and pushed the fix for the Bento build in 03cd4dc.

**Comment by insertinterestingnamehere** [comment]
Awesome! Thanks @rgommers and @ev-br!

**Pull request merged**
