### PR TITLE
BUG/TST: linalg: Check the results of 'schur' more carefully.

### LINKED ISSUE #14517: scipy/linalg/tests/test_decomp.py::TestSchur::test_sort test failure
`scipy/linalg/tests/test_decomp.py::TestSchur::test_sort` test fails in 1.7.1 (IIRC 1.7.0 too).

#### Error message:
```pytb
_________________________________________________________ TestSchur.test_sort _________________________________________________________
scipy/linalg/tests/test_decomp.py:1918: in test_sort
    assert_array_almost_equal([[0.1134, 0.5436, 0.8316, 0.],
E   AssertionError: 
E   Arrays are not almost equal to 3 decimals
E   
E   Mismatched elements: 8 / 16 (50%)
E   Max absolute difference: 1.64897635
E   Max relative difference: 2.00019569
E    x: array([[ 0.113,  0.544,  0.832,  0.   ],
E          [-0.113, -0.825,  0.554,  0.   ],
E          [-0.821,  0.131,  0.026, -0.555],
E          [-0.547,  0.087,  0.018,  0.832]])
E    y: array([[-1.134e-01, -5.436e-01,  8.316e-01, -5.470e-15],
E          [ 1.134e-01,  8.245e-01,  5.544e-01, -4.318e-15],
E          [ 8.213e-01, -1.308e-01,  2.650e-02, -5.547e-01],
E          [ 5.475e-01, -8.718e-02,  1.767e-02,  8.321e-01]])
        a          = [[4.0, 3.0, 1.0, -1.0], [-4.5, -3.5, -1.0, 1.0], [9.0, 6.0, -4.0, 4.5], [6.0, 4.0, -3.0, 3.5]]
        s          = array([[-1.41421356,  0.14557215, 11.58158585,  7.71743518],
       [ 0.        , -0.5       , -9.44719662,  0.7184405...    [ 0.        ,  0.        ,  1.41421356, -0.14557215],
       [ 0.        ,  0.        ,  0.        ,  0.5       ]])
        sdim       = 2
        self       = <scipy.linalg.tests.test_decomp.TestSchur object at 0x7f88fcebe9d0>
        u          = array([[-1.13395338e-01, -5.43632173e-01,  8.31628257e-01,
        -5.47030881e-15],
       [ 1.13395338e-01,  8.24476...33e-02,
        -5.54700196e-01],
       [ 5.47521126e-01, -8.71829392e-02,  1.76652155e-02,
         8.32050294e-01]])
```

#### Scipy/Numpy/Python version information:
```
$  python3.8 -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'
1.7.1 1.21.1 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
The Schur decomposition is not unique, so testing the result
of linalg.schur against hard-coded matrices is not reliable.
The updated tests check that the desired properties of the
result are satisfied, and that the order of the diagonal
elements of the triangular matrix agrees with the given
'sort' parameter.

Closes gh-14517

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The one test failure is not related to these changes.

**Review by rgommers — APPROVED** [review]
Looks great, and makes the tests much more readable and shorter as a bonus. Thanks @WarrenWeckesser!

**Comment by rgommers** [comment]
Added the `backport-candidate` label because this is going to be failing on the 1.9.x branch as well now that it's triggered by the newest openblas version.

**Comment by ilayn** [comment]
Indeed it is nice but we need those sorting options still tested  I am afraid. Any chance we can incorporate them again ?

**Comment by WarrenWeckesser** [comment]
@ilayn, the `sort` parameter is still tested.  The order of the elements on the diagonal of the triangular matrix will be different for each `sort` parameter, and this is checked in the updated tests.

**Comment by ilayn** [comment]
Ah they are now in the pytest parametrization sorry for the noise. Thanks

**Pull request merged**
