### PR TITLE
MAINT: avoid `func_data`, it conflicts with system header on IBM i system

### PR DESCRIPTION
**Pull request by zheddie**
"func_data" was predefined in sys/timer.h as others. So, trying to avoid some compiler failures on AIX and IBM i operating system. Please kindly help to review and merge it. thanks.

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
@zheddie could you please try rebasing your branch onto main? This is related to the failing circle ci docs, I suspect this might just fix the issue.

Reference #16838

cc @dschmitz89

**Comment by zheddie** [comment]
thanks @AnirudhDagar . Is it possible I can reuse this PR or need create a new for main branch?

**Comment by AnirudhDagar** [comment]
You can reuse this PR. In your branch `supportos400`, you can just do `git rebase main` or `git merge main` after making sure your local `main` is in sync with the remote upstream main. Finally, push (--force, needed if you rebase) your commits after the rebase/merge is complete.

Essentially you need to make sure that commit https://github.com/scipy/scipy/commit/d58e74655e1129d5d18f034b5a0219dba90368d3 is present in your branch.

**Comment by zheddie** [comment]
@AnirudhDagar , I have done according to your suggestions. Please review again. thanks.

**Comment by zheddie** [comment]
@rgommers Following is the error message for it: I would guess they may using some workaround to bypass it. The issue is caused by AIX sys/timer.h header defining func_data as t_union.data.  A known workaround of it is to define a macro as _LINUX_SOURCE_COMPAT, which would also affect other part of code, as _LINUX_SOURCE_COMPAT is defined in lots of places in AIX. So, the best way to fix is to change the variable name in scipy. Luckily, it's not wide used in scipy. thanks.

```
scipy/optimize/Zeros/zeros.h:28:51: error: expected ';', ',' or ')' before '.' token
                      double rtol, int iter, void *func_data,
                                                                ^
scipy/optimize/Zeros/zeros.h:31:51: error: expected ';', ',' or ')' before '.' token
                      double rtol, int iter, void *func_data,
                                                                ^
scipy/optimize/Zeros/zeros.h:34:51: error: expected ';', ',' or ')' before '.' token
                      double rtol, int iter, void *func_data,
                                                                ^
scipy/optimize/Zeros/zeros.h:37:51: error: expected ';', ',' or ')' before '.' token
                      double rtol, int iter, void *func_data,
                                                                ^
```

The definition in timer.h is as below:
```
#ifndef  _LINUX_SOURCE_COMPAT
#define func_data       t_union.data
#endif
```

**Review by rgommers — APPROVED** [review]
Thanks @zheddie. This looks good to me, in it goes.

It's a little questionable how some `optimize` files use timer info, which contributed to the build issue here. We'll leave that for another day.

**Comment by zheddie** [comment]
@rgommers Hi, I noticed that we just released 1.9.2 of scipy, while from this tag's code, I can not find the update from this PR. Is it  as design or a mistake ? If as design, how can we expect that this PR could be finally merged into next release of scipy. thanks.

**Comment by rgommers** [comment]
Ah, this PR was merged into `main` which means it will be in the next feature release (1.10.0). It was not marked for backport to the 1.9.x maintenance branch. That could have been done - I've marked it now, so that in case we do a 1.9.3, it will get into that release.

**Comment by zheddie** [comment]
that sounds good. thanks Ralf.

**Pull request merged**
