### PR TITLE
TST: scipy.signal.order_filter: add test coverage

### PR DESCRIPTION
**Pull request by DWesl**
Move tests from #16468 to their own PR.  Those tests were based on the examples in the documentation of `scipy.signal.order_filter`

#### What does this implement/fix?

This provides a few more tests for `scipy.signal.order_filter` and `scipy.signal.medfilt`.

#### Additional information

No extensive tests or corner cases, just a few examples built out of the documentation examples.

I can try building tests of invariants using hypothesis if someone wants me to add that.

### CODE REVIEW

**Comment by DWesl** [comment]
The failure looks like a disagreement about the best format for the expected results.  What is the preferred resolution?  Remove the spaces, ask the linter to ignore that bit, or something else?

**Comment by j-bowhay** [comment]
> Remove the spaces, ask the linter to ignore that bit, or something else?

I think removing the space so the linter passes would be preferable

**Comment by DWesl** [comment]
> > Remove the spaces, ask the linter to ignore that bit, or something else?
> 
> I think removing the space so the linter passes would be preferable

Done.

The Cirrus CI failures seem to be in clone, while the Linux 3.11 failures seem to be mostly in special and stats with a few in spatial

**Comment by DWesl** [comment]
Down to the Cirrus CI repository clone failures, which I think are unrelated.

**Comment by andyfaff** [comment]
Could you try rebasing on main, that might fix the clone issues.

**Comment by DWesl** [comment]
> Could you try rebasing on main, that might fix the clone issues.

Thank you, they're gone now.

**Comment by DWesl** [comment]
It looks like the current failures are in `scipy.linalg` and `scipy.spatial`, which should be unrelated.

**Review by j-bowhay — APPROVED** [review]
Thanks @DWesl

**Pull request merged**
