### PR TITLE
MAINT: special: deprecate `orthopoly1d`

### LINKED ISSUE #1777: Refactor scipy.special ortho polynomials to use new numpy.polynomial sub-package (Trac #1250)
_Original ticket http://projects.scipy.org/scipy/ticket/1250 on 2010-07-29 by trac user dgoldsmith, assigned to @pv._

Presently, the orthogonal polynomial objects and related functions in scipy.special are derived from/depend on numpy.poly1d (via orthopoly1d, which is located in scipy/special/orthogonal.py).  However, numpy.poly1d has poor numerical properties/performance (the conversion to a polynomial using roots is slow and inaccurate for high degree and the polynomials themselves are numerically ill-conditioned [Charles Harris]) and is slated to be replaced--eventually--by appropriate objects/functions in numpy.polynomial.  So the scipy dependencies on poly1d need to changed accordingly.

### LINKED ISSUE #6586: improve the documentation of orthogonal polynomials
gh-6540 improved the documentation of orthogonal polynomials. As a follow-up, we should
- [ ] update `eval_*` docstrings
- [ ] cross-link functions returning `orthopoly1d` objects, and their corresponding `eval_*` and `*_roots`.
- [ ] document the `orthopoly1d` object itself and add clear usage guidelines (e.g. which operations
    convert to power basis)
- [ ] clarify the relation to newer `numpy.polynomial`s

Alternatively, maybe we want to even deprecate `np.poly1d`-based polynomials in favor of `np.polynomial`s.

### PR DESCRIPTION
**Pull request by person142**
The `orthopoly1d` class does three main things:
- Lets you evaluate orthogonal polynomials
- Lets you get roots and weights for Gaussian quadrature
- Gives you coefficients of orthogonal polynomials in the power basis

The first two things can be done directly with the `eval_*` and `*_roots` functions. The third thing is unstable since the coefficients are constructed from the roots of the polynomial. One could fix the situation by making a new class that subclasses numpy's `polynomial` and constructs the polynomial directly from its coefficients, but IMO this is not worth it: when does one actually need the power-basis coefficients of an orthogonal polynomial? (Note that for arithmetic with series of orthogonal polynomials there's already `numpy.polynomial.chebyshev` et. al.)

Instead this deprecates `orthopoly1d` and requests that users call the `eval_*` and `*_roots` functions directly.

Closes gh-1777; related to gh-6586.

**Edit**: at this point closes gh-6586 too.

### CODE REVIEW

**Comment by pv** [comment]
The quadrature etc. tests may be worth "porting over" from the deprecated framework.

**Comment by person142** [comment]
The quadrature tests are all in--the only aspect of `orthopoly1d` they were using was the weight function, which has been switched out. What's getting thrown out is the tests that compare coefficients constructed from roots to data, which don't seem worth keeping around?

**Comment by ev-br** [comment]
I actually like `weight_function` being somewhere together with `_roots`, `weights` and `eval_`. Saves a bit of fuzzing around to figure out factors of two or `q` vs`q-1`s in definitions. 

Maybe we should add some replacement sugar. Something along the lines of

```
class AbstractOrthoPoly(object):
    def roots_and_weights(self):
        raise NotImplementedError

    def weight_func(self, x):
        raise NotImplementedError

   def __call__(self, x, out=None):
      """This does *not* convert to the power basis."""
       raise NotImplementedError

    def to_poly_basis(self):
        """Exposition only. Return a `np.polynomial`.  Do NOT use for evaluation.  """
       raise NotImplementedError


class HermiteOrthoPoly(AbstractOrthoPoly):
       def __init__(self, n):
           self.n = n

       def roots_and_weights(self):
           return h_roots(self.n)

       def __call__(self, x, out=None)
           return eval_hermite(self.n, x, out)

      def weight_function(self, x):
          return np.exp(-x**2)

      def to_power_basis(self):
        ....
```

**Comment by pv** [comment]
Or, we could add the weight functions as public functions in scipy.special.
They're very simple but may be useful to have so that you don't have to re-type them.

**Comment by person142** [comment]
Unrelated to above discussion, but how inconceivable would it be back-compatibility wise to deprecate the current `*_roots` functions and rename them to be more consistent with the `eval_*` functions?

e.g. changes like

`p_roots` -> `legendre_roots`

which would match with `eval_legendre`.

**Comment by pv** [comment]
Having matching names would IMO be better. Not sure whether `roots_legendre` or `legendre_roots`, though.

The `*roots` functions were added to the documentation only recently in 142277e8fae. However, they have been public since b618415241c2f and I think also used in the wild. I think deprecation is possible if we want to rename them for consistency --- but maybe with a comment in the source that we will keep these aliases around for a long time (ie. not scheduled for removal currently).

**Comment by person142** [comment]
New changes:

- Added weight functions as ufuncs
- Renamed the `*_roots` functions (but kept the old ones around and deprecated them with a note in the code to not remove them)
- Added a section to the tutorial about orthogonal polynomials

An example of the new naming scheme:

`eval_legendre` - evaluate Legendre polynomials
`roots_legendre` - roots and quadrature weights for Legendre polynomials
`weight_legendre` - weight function for Legendre polynomials

If there's a strong push for also wrapping everything in an object then I'll do that too. (But will wait to gauge public opinion. We're currently at +1 from @ev-br)

**Comment by ev-br** [comment]
I won't press for the wrapper classes, triplets of _roots, _eval and weight_funcs are fine for me, as long as the usage is documented and the functions are cross-linked in the docs.

**Comment by person142** [comment]
I'm putting off the release notes because there's yet one more deprecation I'd like to broach.

Currently there's a public submodule `special.orthogonal` which mirrors the orthogonal-polynomial functions in `special`, e.g. there's `special.eval_legendre` as well as `special.orthogonal.eval_legendre`. AFAICT `orthogonal` is undocumented (though it looks like it used to be the default way of accessing these functions?), can we deprecate the entire submodule?

**Comment by pv** [comment]
Our policy of prefixing private modules with `_` wasn't always in place, and it's not a very widely adopted Python convention for modules. There are a number of modules in Scipy which are intended to be private but are without underscore. The actual API surface is defined in https://github.com/scipy/scipy/blob/master/doc/API.rst.txt. Of course, there is some code in the wild that imports stuff from private modules, despite them having never been documented.

There's an example of deprecating modules here:
https://github.com/scipy/scipy/blob/master/scipy/linalg/calc_lwork.py
So it's OK in principle to do, but in this case it may not be that urgent to do, since we are not removing `orthogonal.py`.

**Comment by person142** [comment]
Now:

- The "See Also" sections for the `*_eval`, `*_roots`, and `*_weights` functions link to each other.
- The tutorial has an example
- The release notes have been updated

Won't try to do anything about deprecating `orthogonal`, so we'll just leave the `eval_*` imports at the end lurking around.

The documentation could still be improved (most notably adding "Parameters" and "Returns" sections in the `*_eval` functions), but this is already massive so I'm removing the "needs-work" label. (Which I might regret since Travis isn't finished yet.)

**Comment by josef-pkt** [comment]
mainly a question (I'm not sure I understand correctly in skimming this PR):

Will `hermite` and similar `from scipy.special import hermite, chebyt` still return some polynomial objects or not? i.e. are those deprecated without direct alternative in scipy?

(I have some sandbox code that was written a long time ago, before numpy.polynomial. My code was never updated but still seems to runs fine. It uses only low order polynomials.)

**Comment by person142** [comment]
> Will `hermite` and similar from `scipy.special import hermite, chebyt` still return some polynomial objects or not? i.e. are those deprecated without direct alternative in scipy?

They will be removed, and there will be no replacement function that returns a polynomial object. The replacement is using the `eval_*`, `roots_*` and `weight_*` functions directly.

> (I have some sandbox code that was written a long time ago, before numpy.polynomial. My code was never updated but still seems to runs fine. It uses only low order polynomials.)

Even high order polynomials would work fine as long as they we just being used for evaluation and getting roots/weights since the `__call__` method was overridden by the `eval_*` functions. Problems would pop up when doing polynomial arithmetic with high degree polynomials.

To try and summarize: `orthopoly1d` was good for three things: evaluation, getting roots/weights, and weight functions. Those will be separate functions. If was not good for polynomial arithmetic, so this removes the temptation to try and do that.

**Comment by josef-pkt** [comment]
> It was not good for polynomial arithmetic, so this removes the temptation to try and do that.

But that was my main usage, after estimating the coefficient for the linear combination of orthogonal polynomial basis functions, it's easy to evaluate at new points and have available the other methods that polynomials provide.
I don't want to write a wrapper for the different methods myself, so that might mean switching to numpy.polynomial.

(maybe it's a bit like taking away numpy.linalg.inv because you should never use the matrix inverse. We just replaced numpy.linalg.inv by an svd in statsmodels for one of the central calculations, but inv worked happily for 7 years.)

**Comment by josef-pkt** [comment]
I'm -0 because for new users numpy.polynomial should work well enough (I don't have enough experience with it to tell.)

as background: When I worked with the orthogonal polynomials, I had very little background, and the applied literature used mainly the standard polynomial representation. It was relatively easy for me to figure out how to work with the scipy.special polynomials, while doing everything from scratch would have been above my knowledge. (The only problem I had was with figuring out the orthonormal version of the polynomials.)

The question is what's the easy usage when we don't know or don't want to worry about numerical precision details.

**Comment by person142** [comment]
> But that was my main usage, after estimating the coefficient for the linear combination of orthogonal polynomial basis functions, it's easy to evaluate at new points and have available the other methods that polynomials provide.
I don't want to write a wrapper for the different methods myself, so that might mean switching to numpy.polynomial.

A good idea: `numpy.polynomial.chebychev.Chebychev`, `numpy.polynomial.legendre.Legendre`, `numpy.polynomial.laguerre.Laguerre`, `numpy.polynomial.hermite.Hermite`, and `numpy.polynomial.hermite_e.HermiteE` do a much better job of this. They do fitting and provide accurate evaluation of series of orthogonal polynomials.

> The question is what's the easy usage when we don't know or don't want to worry about numerical precision details.

Use the numpy versions. I added a note to the tutorial about using them, but I should probably add it to the main documentation too so that it's very visible.

**Comment by person142** [comment]
As a silly example of how pleasant it is to use the numpy stuff:
```python
>>> import numpy as np
>>> from numpy.polynomial.chebyshev import Chebyshev
>>> x = np.linspace(-1, 1, 200)
>>> y = np.exp(x)
>>> series = Chebyshev.fit(x, y, 100) # least squares fit of a 100 degree Chebychev series
>>> np.max(np.abs(y - series(x)))
1.3100631690576847e-14
```

**Comment by person142** [comment]
The documentation for the `eval_*` functions is now complete. (Full definitions of functions and proper "Parameters"/"Returns" sections.)

**Comment by person142** [comment]
Does anyone have opinions on renaming the `weight_*` functions to `weightfun_*`? e.g.

`weight_jacobi` -> `weightfun_jacobi`.

If a function were called `weights_jacobi` then I would expect it to compute the quadrature weights for Gauss-Jacobi quadrature, and I'm worried that `weight_jacobi` is too similar.

**Comment by aarchiba** [comment]
There are a number of pieces of information one could want about each family of orthogonal polynomials: 
* the weights
* the roots
* the evaluation method
* the interval
* the recurrence relation

It would be nice if these were all associated in some way, perhaps in a factory function that took n as input and provided an object wrapping up the above information for that n. That's what orthopoly1d currently is, with a side order of making the power-basis coefficients available. I certainly don't mind dropping the power basis representation, but in your proposed interface, where is the interval information? Is there any way to specify a family of orthogonal polynomials, say to a quadrature routine?

The recurrence relation is currently not available, and it's not really clear how to make it so in a manageable way, but it would be useful for someone who had (say) a polynomial expressed in an orthogonal-polynomial basis who wanted to evaluate it using Clenshaw's algorithm.

**Comment by person142** [comment]
Ok, let's see if we can reach a consensus. What if we:

- Introduce a new orthogonal polynomial object that doesn't inherit from `poly1d` or `polynomial` which wraps the appropriate `eval_*`, `root_*`, and `weightfun_*` functions and also has a `domain` attribute to describe the interval. (Use the name `domain` for compatibility with numpy's `Polynomial`.)
- When possible, allow the user to do arithmetic with orthogonal polynomials by casting them to the appropriate numpy orthogonal polynomial series first (the resulting object would also be a numpy orthogonal polynomial series). This would work for Legendre polynomials, Chebyshev polynomials of the first kind, Legendre polynomials, Laguerre polynomials, and Hermite polynomials and raise a `NonImplementedError` for the others.

Thoughts?

**Comment by person142** [comment]
> The recurrence relation is currently not available, and it's not really clear how to make it so in a manageable way, but it would be useful for someone who had (say) a polynomial expressed in an orthogonal-polynomial basis who wanted to evaluate it using Clenshaw's algorithm.

This seems like it would fit better as an enhancement to the numpy stuff since it already provides several orthogonal polynomial series and evaluates them with Clenshaw recursion.

**Comment by charris** [comment]
NumPy `Polynomial` uses `domain` for the fitted data and  `window` for the natural domain of the polynomial that the data is mapped to. Hmm, I don't know if there is a generally accepted name for what we want here. If the weight function is zero outside the interval of integration, it could be called the `support`.

**Comment by person142** [comment]
The `numpy.polynomial.chebyshev.Chebyshev` doc says that `domain` is

> Domain to use. The interval [domain[0], domain[1]] is mapped to the interval [window[0], window[1]] by shifting and scaling. The default value is [-1, 1].

so isn't domain the natural domain? We should probably make shifting and scaling to arbitrary intervals work, so we should be able to piggyback on the numpy notation.

**Comment by charris** [comment]
Nope. For Chebyshev polynomials the domain is mapped to [-1, 1] by affine tranformation and evaluated there. In this case the window is [-1, 1], and domain is where the unmapped data sits.

**Comment by charris** [comment]
The default value of the domains is also set to [-1, 1] so that the result is an ordinary unscaled and unshifted Chebyshev polynomial, useful for pedagogical purposes, but when used to represent data the domain will generally be where the data unless specifically chosen otherwise.

**Comment by person142** [comment]
After starting to write the object-oriented interface I'm feeling more bearish about the idea, so maybe I'll push back a little.

About quadrature, in particular

> Is there any way to specify a family of orthogonal polynomials, say to a quadrature routine?

A quadrature routine needs roots, weights, and possibly the interval on which the polynomials are orthogonal. Two of those things are provided already by the `roots_*` functions, what if we add an option to also return the interval and let a quadrature routine accept a callable? If we go for an object-oriented design then a user would need to provide an evaluation function and a weight function too. (Unless they were optional, but then we're essentially asking them to provide a `roots_*` function and calling it something else.)

**Comment by aarchiba** [comment]
I'm not hung up on an object-oriented framework; for one thing, it's not clear whether the objects should be for families or individual polynomials. It's just that the possibility of doing other things with scipy's orthogonal polynomials came up in discussions of quadrature and ODE solving. And this is python, scipy.special doesn't necessarily need to be a giant bag of functions.

**Comment by person142** [comment]
Can we leave the question of an object-oriented framework open for now? If there's consensus that `orthopoly1d` should be deprecated, then we don't have to replace it with something right away. Perhaps as things advance on the quadrature/ODE solving fronts it will become more clear what kind of object we want. Let me just say that I'm not opposed to an object-oriented framework in principle; I'm just not sure yet what it should look like to be useful and not a lot of boilerplate. I also don't see the changes here as precluding an object-oriented interface since I think there should be a ufunc interface regardless.

**Comment by person142** [comment]
@aarchiba: what if the `roots_*` functions returned a lightweight object (named tuple or similar) called maybe `GaussQuadInfo` which bundled together the roots, weights, sum of the weights, and quadrature interval? Then something like `fixed_quad` could be extended to something like `fixed_quad(..., method=None, ...)` where `method` could be a string parameter or an instance of `GaussQuadInfo`.

What were the ideas about using orthogonal polynomials in ODE solving?

**Comment by person142** [comment]
After thinking about this a little longer:

- This PR is way too bloated; reviewing it is going to be a pain.
- I'm going to close this and break it into chunks, starting with the small uncontroversial parts like improving the documentation.
- Maybe by the time all the current bits are cleaned up the correct object-oriented API will be more clear.

**Comment by aarchiba** [comment]
A lightweight return object seems sensible - though keep in mind that an adaptive or Romberg quadrature will need to be able to extract it for many ns, so you'd want to pass a factory function of some kind.

The use in ODE solving is that some methods are "collocation methods", that is, to extend the solution forward, they search for a polynomial whose derivative matches the ODE's vector field at specified times - and those times are the zeros of an orthogonal polynomial. This polynomial can also be used to interpolate the solution between stopping points (though it can be of lower order than you want). The descriptions I have read all seem to use the power basis and don't worry about numerical instability; to be fair, they're using order 8 or 12 at most. So really, all they need are the roots, and often they'll just type in values from a table (or mpmath).

**Comment by charris** [comment]
Passing thought, it should be possible to make a class factory that produces numpy polynomial classes given the recursion relationship, the support of the weight function, and perhaps the integration/differentiation formulas.

**Pull request closed without merging**
