### PR TITLE
ENH: stats: improve kendall_tau cache usage

### PR DESCRIPTION
**Pull request by vigna**
This pull request improves the cache efficiency of the subroutine used to compute the number of transposition in Kendall's τ computation. The timings in seconds on an Intel Core i7-7770 CPU @3.60GHz (Kaby Lake) are

    k        new                                       old
    18      0.05589556694030762     0.05243515968322754
    19      0.11377596855163574       0.10748624801635742
    20      0.2333989143371582       0.2219550609588623
    21      0.45459985733032227     0.4673912525177002
    22      0.9821414947509766       0.98244309425354
    23      2.0328445434570312      2.0543222427368164
    24      4.117265701293945         4.26338005065918
    25      8.355305671691895       8.964257001876831
    26      17.25917959213257         18.699312925338745
    27      35.32108664512634       38.955217361450195
    28      72.20554256439209       80.67914152145386
    29      144.18521857261658      162.25554394721985

The timings are for computing τ between a list of 2^k - 1 distinct elements and the the same list, reversed. The bigger the lists, the greater the improvement. The difference will vary depending on the cache architecture.

### CODE REVIEW

**Comment by rgommers** [comment]
Hi @vigna, thanks this is interesting. Performance improvement looks good. Can you add a detailed comment to the first change to explain what is going on there? 

Also, adding a benchmark at https://github.com/scipy/scipy/blob/master/benchmarks/benchmarks/stats.py may be useful.

**Comment by vigna** [comment]
Section 5.2 of https://arxiv.org/abs/1904.12370 explains it in some detail.

But, long story short: the code uses a Fenwick tree to count the number of transpositions which generate a permutation. A Fenwick tree is given by the overlay of three implicit trees, of which the code uses two (the "update" tree and the "prefix" tree). In all trees, the high nodes, which are the most frequently accessed, are positioned at indices that have a large number of trailing zeros. You can easily see it because the "parent" operation through the loop is deleting the lowest bit set, in one case, and adding the lowest bit set, in the other case.

Thus, the positions (pointers) in memory or such high (and frequently accessed) nodes all have the same lower bits. As a result, they are all mapped to the same way of multi-way caches: in essence, you're using just a fraction of your cache because caches have been designed with the idea that important cache lines in the same region of memory are laid out consecutively, or at random (in both cases, the lower bits are a good way to address the multiple ways available for the memory region). 

The code inserts very rare holes in the data structure (1 ever 4096 elements). Space increase is undetectable (less than 0.1%) but now the lower bits of relevant nodes are perturbed (e.g., the node that had index 4096 has now index 4097): as a result, you are gonna use all of your cache.

**Comment by vigna** [comment]
BTW, the failed test appears to be a problem with the CircleCI installation.

**Comment by vigna** [comment]
Note that for very small lists (e.g., a few thousand elements) the slowdown due to the additional code is barely measurable—in the order of 1%. It is possible to have conditional code for the small and large case if you think it's worth it.

**Comment by rgommers** [comment]
Thanks for the explanation. Can you put a comment like this in the code?
```
# Improve cache performance of Fenwick tree (see gh-10108)
```

>  It is possible to have conditional code for the small and large case if you think it's worth it.

This isn't worth it, let's leave as is.

> BTW, the failed test appears to be a problem with the CircleCI installation.

Yes, please ignore `pypy3` failures, we've already removed that test run from our config but CircleCI is persistent.

**Comment by rgommers** [comment]
In it goes. Thanks @vigna

**Pull request merged**
