### PR TITLE
BUG: fix LowLevelCallable issue on 32-bit Python.

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-6926.

### CODE REVIEW

**Comment by rgommers** [comment]
Tests pass, but I suspect this is not right. Should be something like https://github.com/rgommers/scipy/commit/078384b8d0bf4d, but I can't figure out the right Cython syntax right now.

**Comment by pv** [comment]
I think this is not correct fix, notjing guarantees int and long are same.
The correct fix is to add the #ifdef sizeofint=sizeoflong stanzas to the
test c code, thevsame ones that are in the quadpack/ndimage codes.

6.1.2017 11.56 "Ralf Gommers" <notifications@github.com> kirjoitti:

**Comment by pv** [comment]
https://github.com/rgommers/scipy/commit/078384b8d0bf4d looks ok

6.1.2017 13.53 "Pauli Virtanen" <pvirtn@gmail.com> kirjoitti:

**Comment by pv** [comment]
maybe this: gh-6934

**Comment by rgommers** [comment]
Okay this is happy now, thanks for the help Pauli.

**Pull request merged**
