### PR TITLE
DOC: Expand odd_ext even_ext const_ext docstrings

### PR DESCRIPTION
**Pull request by endolith**
Add "A one-line summary that does not use variable names or the
function name"

Add graphical examples

Simplify text examples

From https://github.com/scipy/scipy/pull/6058#issuecomment-254061700

### CODE REVIEW

**Comment by Eric89GXL** [comment]
These don't show up in the docs currently, [right] (https://1242-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/signal.html)? Maybe we should add them.

**Comment by WarrenWeckesser** [comment]
> These don't show up in the docs currently, right? Maybe we should add them.

`signal._array_tools` is a private module, and the functions it contains are private functions.  I recommend being very conservative about making functions public.  Has there been any demand for these functions from users?  If so, could those demands be met by `numpy.pad` instead?

**Comment by Eric89GXL** [comment]
Ahh right. Fine by me

**Comment by endolith** [comment]
numpy.pad examples show it adding a duplicate sample at the boundary though

**Comment by rgommers** [comment]
Expanded docstrings look good, so merged.

**Comment by rgommers** [comment]
Thanks @endolith

**Comment by rgommers** [comment]
I'd indeed hesitate to make these functions public - too many little utilities and won't be used heavily. Rather improve ``pad`` if needed, or look for another single function that does what all of these functions do if there really is a need that ``np.pad`` can't cater for.

**Pull request merged**
