### PR TITLE
MAINT: stats.ContinuousDistribution.llf: remove method

### LINKED ISSUE #22146: BUG:`stats.ContinuousDistribution.llf`: should not be public
### Describe your issue.

I'm currently trying to annotating `ContinuousDistribution.llf` in `scipy.stats`, whose output depends on the shape of the input, but also on the shape of the parameters.
To see how it works, I started with a vectorized normal RV, and generated some samples with it:

```pycon
>>> X = Normal(mu=[0, 1])
>>> xs = X.sample(10)
```

At this point, I expected `X.llf(xs)` to return an array of shape `(2,)`, so that it matches the shape of `X.mu`. But because of the `axis=-1` default, this wasn't what happened:

```pycon
>>> X.llf(xs)
array([-2.50518611, -4.06898409, -2.06169297, -1.88010484, -2.71600634,
       -2.52051706, -2.66203451, -1.89359128, -2.35288552, -3.36842927])
```

It's not a big problem, but it's just a bit of an awkward `axis` default, which is easy to work around:

```pycon
>>> X.llf(xs, axis=0)
array([-14.39796723, -11.63146478])
```

OK all good. But since `axis` is also allowed to be `None`, I wanted to check whether it behaved as I expected it to behave. Usually `axis=None` just ravels your input, but in this case, there are 2 parameters, so I expected it to "ravel" the columns of `xs` individually, which is effectively a no-op. If it would ravel everything into a 1-d array, an error would be raised, saying it's not broadcastable.

But apparently, I missed a secret option no. 3:

```pycon
>>> X.llf(xs, axis=None)
np.float64(-26.029432010837176)
```

... it summed the individual outputs 😅

### Reproducing Code Example

```pycon
>>> from scipy.stats import Normal
>>> X = Normal(mu=[0, 1])
>>> xs = X.sample(10)
>>> X.llf(xs)
array([-2.50518611, -4.06898409, -2.06169297, -1.88010484, -2.71600634,
       -2.52051706, -2.66203451, -1.89359128, -2.35288552, -3.36842927])
>>> X.llf(xs, axis=0)
array([-14.39796723, -11.63146478])
>>> X.llf(xs, axis=None)
np.float64(-26.029432010837176)
```

### Error message

```shell
# I'm afraid my brain doesn't output stacktraces
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0rc1 2.2.0 sys.version_info(major=3, minor=13, micro=1, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-fa6gfmf0/overlay/lib/python3.13/site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp313-cp313/bin/python
  version: '3.13'
```

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Closes gh-22146

#### What does this implement/fix?
Code for an `llf` method has been hiding in the `ContinuousDistribution` class, but the documentation didn't render and it's not tested because it wasn't supposed to be public at this time. This PR removes the method for now.

#### Additional information
The idea of providing a LLF is fine, but it would need interface discussion (should it be a class method? separate function?) and more work.

### CODE REVIEW

**Comment by jorenham** [comment]
Do you know whether this will directly go into `1.15.0` final, or if there'll be a an `rc2` first?

**Comment by mdhaber** [comment]
That's up to @tylerjereddy, but I think there will be an RC2.

**Comment by jorenham** [comment]
> That's up to @tylerjereddy, but I think there will be an RC2.

The reason I'm asking, is because withoout an `rc2`, I'll have to remove the `llf` annotations while still using `1.15.0rc1`, and add an allowlist entry to ignore the `stubtest` errors about the missing annotations.

**Comment by tylerjereddy** [comment]
There will be an RC2 yes, the draft backport PR will be up shortly. A few things are still in flight, so RC2 definitely will not happy today, though if it could happen this weekend that may be nice.

**Comment by jorenham** [comment]
> There will be an RC2 yes, the draft backport PR will be up shortly. A few things are still in flight, so RC2 definitely will not happen today, though if it could happen this weekend that may be nice.

That helps, thanks!

**Review by j-bowhay — APPROVED** [review]

**Pull request merged**
