### PR TITLE
DOC: add next_fast_len to list of functions

### PR DESCRIPTION
**Pull request by endolith**
Missed this in https://github.com/scipy/scipy/pull/6153

### CODE REVIEW

**Comment by endolith** [comment]
Is there a way for this to be more automatic?

**Comment by ev-br** [comment]
You can run `$ python runtests.py --refguide-check -s signal` locally to catch these sorts of inconsistencies if that's what you mean

**Comment by Eric89GXL** [comment]
Looking at this:

https://804-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.fftpack.next_fast_len.html#scipy.fftpack.next_fast_len

I realized we missed the `.. versionadded::`, too, can you add it?

**Comment by endolith** [comment]
@ev-br  I meant the documentation being generated automatically from the function docstrings, like (I think) it is for scipy.signal

**Comment by Eric89GXL** [comment]
I don't think it's automatic there either

**Comment by endolith** [comment]
Ok added versionadded

**Comment by Eric89GXL** [comment]
Great, happy to merge but could you squash first?

**Comment by endolith** [comment]
squashed

**Comment by Eric89GXL** [comment]
Thanks @endolith

**Pull request merged**
