### PR TITLE
MAINT: stats: Remove an unused list from test_continuous_basic.py.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Also remove an unused import (pickle), and make a few whitespace
fixes.

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]
I suppose if all tests (including slow) pass with this change, it's safe. If the list was considered important for some other reason, it should have had a comment about why. 

Have you checked distributions with these parameters? Are they useful to remember for debugging purposes? (They don't belong here, of course.)

**Comment by WarrenWeckesser** [comment]
> Have you checked distributions with these parameters?

No, but I suspect the comments are either obsolete or redundant.

If we encounter actual problems with these distribution, appropriate github issues should be created.

**Comment by josef-pkt** [comment]
you could append it to distcont and  test run the unit tests to see what or if anything still fails with those parameters

**Comment by WarrenWeckesser** [comment]
Someone could do that 😃 ; I have enough other issues to work on that I don't think I'll get to that any time soon.  If y'all would be more comfortable with someone investigating the potential issues before removing the list from `test_continuous_basic.py`, I don't mind just closing the PR for now.

**Comment by mdhaber** [comment]
I don't think it's doing anyone much good sitting in the file, and it must have been important if you wanted to take it out, so let's take it out.

I added these parameters to the tests as @josef-pkt suggested and I only get a failure with genextreme. 

```
_____________________________________ test_cont_basic[500-200-genextreme-arg109] ______________________________________
..\..\scipy\stats\tests\test_continuous_basic.py:143: in test_cont_basic
    check_sample_meanvar_(distfn, arg, m, v, sm, sv, sn, distname + 'sample mean test')
        arg        = (3.3184017469423535,)
        distfn     = <scipy.stats._continuous_distns.genextreme_gen object at 0x000001E402D67B48>
        distname   = 'genextreme'
        m          = array(-2.43383995)
        n_fit_samples = 200
        rng        = RandomState(MT19937) at 0x1E402FB6D08
        rvs        = array([-1.01303356e+01, -1.12833375e+00, -1.96932527e+00,  3.01316409e-01,
       -5.99979548e-01,  2.79509250e-01,  2...5365e-01,  1.01277938e-01, -7.36864115e-01,
        2.88324861e-01,  3.01197620e-01, -1.35957088e-01,  3.00850885e-01])
        sm         = -1.2902787656253494
        sn         = 500
        sv         = 27.925289588585446
        v          = array(214.60078302)
..\..\scipy\stats\tests\test_continuous_basic.py:448: in check_sample_meanvar_
    check_sample_mean(sm, sv, sn, m)
        arg        = (3.3184017469423535,)
        distfn     = <scipy.stats._continuous_distns.genextreme_gen object at 0x000001E402D67B48>
        m          = array(-2.43383995)
        msg        = 'genextremesample mean test'
        sm         = -1.2902787656253494
        sn         = 500
        sv         = 27.925289588585446
        v          = array(214.60078302)
..\..\scipy\stats\tests\test_continuous_basic.py:466: in check_sample_mean
    (t, prob, popmean, sm))
E   AssertionError: mean fail, t,prob = 4.838888, 0.000002, m, sm=-2.433840,-1.290279
        df         = 499
        n          = 500
        popmean    = array(-2.43383995)
        prob       = 1.7430784120857393e-06
        sm         = -1.2902787656253494
        svar       = 27.925289588585443
        t          = 4.838887931439731
        v          = 27.925289588585446
=============================================== short test summary info ===============================================
```

The PDF has a surprisingly long left tail but basically becomes a spike approaching 0 from the left. Running the example code with that value of `c`:
image

Let me know if you think it's worth opening an issue, but I don't think it's a very valuable test case. There is no shortage of numerical issues like this.

**Pull request merged**
