### PR TITLE
BUG: tighten condition for bsr eliminate_zeros fast path

### LINKED ISSUE #9687: 'eliminate_zeros' does not do anything on a 'bsr_matrix' entirely of zeros
### Summary

If the dense representation of a `bsr_matrix` is all zeros, `eliminate_zeros` becomes a no-op rather than removing the explicit zeros.

### Reproduction

```py3
import numpy as np
import scipy.sparse as sp
np.random.seed(0xcafebabe)

m = sp.bsr_matrix(np.random.random((27, 27)), blocksize=(3,3))
print(m.nnz, len(m.data))

# eliminate some blocks
m.data[np.absolute(m.data) < 0.8] = 0
m.eliminate_zeros()
print(m.nnz, len(m.data))

# eliminate all blocks
m.data[...] = 0
m.eliminate_zeros()
print(m.nnz, len(m.data))
```

**Output:**
```
729 81
603 67
603 67
```

**Expected output:**

I expect that everything should be truncated from the last matrix, like it is with `csr_matrix`.
```
729 81
603 67
0 0
```

### Scipy/Numpy/Python version information:

```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

### Other notes

This looks suspicious:

https://github.com/scipy/scipy/blob/95029ad1452495bf3acfc7daa973cfd12e298064/scipy/sparse/bsr.py#L552-L553

### PR DESCRIPTION
**Pull request by ExpHP**
Fixes #9687, wherein `eliminate_zeros()` fails to remove any data from a `bsr_matrix` that contains nothing but explicit zeros.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Thanks! Could you move the test case you added to here? https://github.com/scipy/scipy/blob/95029ad1452495bf3acfc7daa973cfd12e298064/scipy/sparse/tests/test_base.py#L4231

(as a separate case, maybe `test_eliminate_zeros_all_zero` or something descriptive like that.)

**Comment by ExpHP** [comment]
Looks like Appveyor timed out for some reason while running tests?

**Review by perimosocordiae — APPROVED** [review]
Change looks good, thanks! I'll look into the CI issues.

**Comment by perimosocordiae** [comment]
CI problems are unrelated. I'll wait a day or so to see if anyone else has comments, then merge.

**Comment by perimosocordiae** [comment]
No other comments, merged. Thanks for your first scipy PR, @ExpHP!

**Pull request merged**
