### PR TITLE
MAINT: raise runtime error for newton with zeroder if disp true, add tests

### LINKED ISSUE #9551: BUG: scipy.optimize.newton says the root of x^2+1 is zero.
Scipy version 1.1.0, Python 3.6.3

```python
>>> def f(x):
...     return x*x+1
...
>>> def f_p(x):
...     return 2*x
>>> newton(f, 1, f_p)
../../scipy/optimize/zeros.py:169: RuntimeWarning: derivative was zero.
  warnings.warn(msg, RuntimeWarning)
0.0
```

See related discussion on [scicomp.stackexchange](https://scicomp.stackexchange.com/questions/30597/defining-a-condition-number-and-termination-criteria-for-newtons-method).

### PR DESCRIPTION
**Pull request by mikofski**
closes #9551

### CODE REVIEW

**Comment by mikofski** [comment]
FYI: @WarrenWeckesser @NAThompson @pvanmulbregt

**Comment by NAThompson** [comment]
My opinion is that zero derivatives are far to common to simply raise an exception. Can you instead use bisection when a zero derivative is encountered?

**Comment by josef-pkt** [comment]
I think we had this discussion before.

IMO, scipy optimize should never raise when running into convergence problems or problems finding an optimum or root. Failure to find a solution should be signaled with a return flag, so the caller can look at the results and continue with another optimizer or rootfinder.

(I'm not in this neighborhood right now, for univariate rootfinders (not newton) I am trying several methods in sequence if they fail to find a root. (although IIRC I still have to try... except catch input errors, like bad bounds in brentq))

**Comment by WarrenWeckesser** [comment]
@josef-pkt wrote
> scipy optimize should never raise when running into convergence problems or problems finding an optimum or root. Failure to find a solution should be signaled with a return flag,

That is the behavior of `newton` when `full_output` is True.  When `full_output` is False (which is the default), the only thing returned by `newton` is the root.  There is no way to pass a return flag.  So raising an exception when the algorithm fails to converge is the appropriate behavior.  And that is what it currently does when, for example, `maxiter` is reached before convergence.  I think failing to raise an exception in the derivative 0 case was just an oversight.

For the behavior that you are recommending, the user must use the argument `full_output=True`.  Then an exception is not raised, and, for a call such as

    root, result = newton(f, 1, f_p, full_output=True)

the user is expected to check `result.converged` to verify that the algorithm converged.

(Yeah, the way `full_output` and `disp` control the return value and how nonconvergence is handled is ugly, but these are the typical contortions we go through to maintain backwards compatbility.)

**Comment by josef-pkt** [comment]
@WarrenWeckesser  Thanks for the clarification. I didn't notice that. 
I usually have full_output=True (and that is hardcoded in statsmodels)

**Comment by pvanmulbregt** [comment]
The arguments `disp` and `full_output` are recent additions (gh-8803), attempting to backfit functionality already available in `bisect`, `brentq`... 
The behavior in `newton` dating back at least 8 years was for a derivative being 0 to trigger a warning.
`full_output=False, disp=True` are the default values and matched the defaults in `brentq`.  
To  maintain backwards-compatibility the behavior had to match the pre-PR behavior, which meant that `disp=True` only caused the warning to be raised. Otherwise it would have broken existing code.
It's not an exact fit.  
Using `full_output=True, disp=False` is the best way to get the return status signalled in a "flag" and to not have to worry about warnings/exceptions.

**Comment by WarrenWeckesser** [comment]
So the original code *did* raise an exception on failure to converge (i.e. `maxiter` is reached), but it didn't raise an exception on hitting a zero derivative (which is just an extreme way for the algorithm to not converge)?  I would call that a bug that should be fixed, not an API that should be preserved.

**Comment by mikofski** [comment]
@WarrenWeckesser any more thoughts on this? @rgommers and @pvanmulbregt any thoughts? For more information you can check the comments in #9551.

In a nutshell, if `disp=True` then a zero derivative should raise an error, not a warning. I think this is worth fixing. I think this is just a maintenance issue to clean up the api and make it consistent. Thanks!

**Comment by mikofski** [comment]
@tylerjereddy, @rgommers, and @pvanmulbregt do you think this can be resolved in the 1.3.0 milestone?

**Comment by rgommers** [comment]
It seems easy enough, so probably yes, No time right now though. I'll just mark it for 1.3.0 so we'll get another nudge next week.

**Review by tylerjereddy — COMMENTED** [review]
The discussion is a little confusing because of the API, but I think this makes sense.

I was also slightly confused not to find the exact example used in the issue report, but I'll assume the test cases are close enough to reproduce. Probably just because I'm not used to looking at the root finder stuff.

I confirmed that the issue still persists on latest master branch.

I suggest:
- rebasing on latest master because the commit is > 4 months old
- double-checking there are no formatting-related issues with the following output that I get when running the "problem case" in the linked issue:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    result = newton(f, 1, f_p)
  File "/Users/treddy/.local/lib/python3.6/site-packages/scipy-1.3.0.dev0+a0804d2-py3.6-macosx-10.9-x86_64.egg/scipy/optimize/zeros.py", line 286, in newton
    ", value is %s", itr + 1, p0)
RuntimeError: ('Failed to converge after %d iterations, derivative was zero., value is %s', 2, 0.0)
```

Apart from that, we can probably just merge if the CI is all green after the rebase since the argument seems to be that we're fixing a defect rather than changing behavior for convenience.

**Comment by mikofski** [comment]
@tylerjereddy I rebased from master, fixed the string formatting, and added a test for the exact example from the original issue report. The test also checks the error message using a strict regex pattern match. Let me know if there's anything else :)

**Comment by NAThompson** [comment]
I do not believe that a zero derivative should raise an exception. In boost we revert to Muller's method on zero derivatives:

https://github.com/boostorg/math/blob/develop/include/boost/math/tools/roots.hpp

See line 594.

**Comment by tylerjereddy** [comment]
@WarrenWeckesser Would we prefer to fall back to Muller's method when Newton hits a zero derivative, instead of raising an exception? The contention around the appropriate solution here is making me apprehensive about making a final decision by Thursday.

**Comment by WarrenWeckesser** [comment]
@tylerjereddy wrote

> Would we prefer to fall back to Muller's method when Newton hits a zero derivative, instead of raising an exception?

That sounds like an interesting enhancement, but not something that should be rushed in for 1.3.0.

When we're only returning the root (i.e. with the defaults `full_output=False, disp=True`), raising an exception on hitting a zero derivative is consistent with raising an exception when the maximum number of iterations is reached.  In fact, that's what the docstring *says* should happen:

    disp : bool, optional
        If True, raise a RuntimeError if the algorithm didn't converge

Encountering a zero derivative is just an another way the algorithm can fail to converge,
so I'm still in favor of raising an exception. (Note that I haven't actually reviewed the implementation of that behavior in this pull request--sorry!)

**Comment by mikofski** [comment]
I guess I would expect Muller's method to be a separate implementation, and that [`scipy.optimize.root_scalar`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.root_scalar.html#scipy.optimize.root_scalar) would choose which method to use or fall back on.

**Review by tylerjereddy — APPROVED** [review]
Ok, this seems like a useful bug fix after more careful thought. I don't think raising the exception as documented precludes us from providing similar functionality to that available in other prominent libraries (i.e., boost) in the future.

Whether that future behavior should be a fallback within `newton` itself, or perhaps only isolated to the more general `root_scalar`, is a decision for the resident `optimize` experts.

One final note--try to prefix commit messages with `BUG` or `TST` or whatever appropriate tag is [documented](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html); same goes for the titles of PRs

Thanks @mikofski

**Comment by tylerjereddy** [comment]
I added a short release note at bottom of "other changes": https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.3.0#other-changes

Feel free to modify / improve / remove as appropriate

**Pull request merged**
