### PR TITLE
ENH: dual_annealing vectorise visit_fn

### PR DESCRIPTION
**Pull request by andyfaff**
There is a simple optimisation to be made in `dual_annealing` with a simple vectorisation of a function.
For the `test_high_dim_no_ls` test on my computer I see a factor of 2.3 speedup (from ~2s to 0.85).

The vectorisation will result in slightly different output because the random numbers are generated in slightly different order. If that's a significant issue it should be possible to recreate the same order.

### CODE REVIEW

**Comment by andyfaff** [comment]
@sgubianpm

**Comment by andyfaff** [comment]
- The speedup will aid the pypy CI because a few of the high hitters on the slowest CI tests are from dual_anneal (knocking > 30s off total test time).
- the changes are less consequential as the objective function gets more expensive to calculate.

**Comment by andyfaff** [comment]
ping @rgommers, this should be an easy win.

**Review by rgommers — CHANGES_REQUESTED** [review]
Thanks @andyfaff, sounds like a nice speedup.  I do see a few things that need addressing though:

- the added attributes should be private, so add underscores
- your comment *these are invariant numbers unless visiting_param changes* should be expanded a bit: this implies that `visiting_param` cannot be changed anymore (note in docstring also would make sense). It's not changed in the code now, but better to guard against future changes here
- random numbers for a fixed seed should preferably be kept the same, would be a minor backwards compat break otherwise.

**Comment by sgubianpm** [comment]
@andyaff vectorization looks great to me.
Do you want me to make the changes suggested in @rgommers comments?

**Comment by andyfaff** [comment]
@sgubianpm point 3 is already done, and I can address point 1. W.r.t `visiting_param` is it ever likely to be changed?

**Comment by andyfaff** [comment]
@rgommers, comments addressed.

**Comment by rgommers** [comment]
@andyfaff the refguide check failure is real

**Comment by andyfaff** [comment]
I git screwed up somehow.

**Comment by andyfaff** [comment]
I fixed the screw up, and decided to squash them into a single commit. Let's hope this turns green now.

**Comment by andyfaff** [comment]
All pass, apart from unrelated tests failing on pypy3.

**Comment by andyfaff** [comment]
@rgommers, the reason the refguide test failed was because when I addressed your review comments I was on a different computer, and spliced in some changes that caused the random numbers to be generated in a different order. Since force-pushing the refguide tests work again, because the stream of random numbers used is the same as before.

**Comment by rgommers** [comment]
LGTM now, merged. Thanks @andyfaff

**Comment by sgubianpm** [comment]
@rgommers, @andyfaff, does this mean that issue #9732 can be closed (I think it was related to the random numbers generation).

**Comment by andyfaff** [comment]
Whilst the refguide tests pass on travis, I don't think it necessarily closes #9732. All this PR did was vectorise things, the behaviour should be unchamged. I'd like to get confirmation from the contributors to that issue before closing it.

**Comment by rgommers** [comment]
agreed, that issue wasn't fixed - it's still a bit of a mystery what is going on there

**Pull request merged**
