### PR TITLE
DOC: Define BEFORE/AFTER in runtests.py -h for bench-compare

### PR DESCRIPTION
**Pull request by rainwoodman**
Such that we do not need to look keep cross referencing the logs!

### CODE REVIEW

**Comment by rgommers** [comment]
+1 this makes sense to me, easier to use this way.

Leaving open for a while to give people a chance to comment.

**Comment by ev-br** [comment]
+1

**Comment by ev-br** [comment]
I've merged this. Thanks @rainwoodman

**Comment by rainwoodman** [comment]
Thanks!

**Pull request merged**
