### PR TITLE
CI: fix wheel upload to anaconda [wheel build]

### LINKED ISSUE #18597: CI, BUG: Cirrus wheel upload fails on maintenance branch
See: https://cirrus-ci.com/build/4827956036501504

`failing at upload stage: [miniconda.sh](http://miniconda.sh/): line 29: HOME: unbound variable`

### PR DESCRIPTION
**Pull request by andyfaff**
Should hopefully fix #18597 
@tylerjereddy

### CODE REVIEW

**Comment by andyfaff** [comment]
Don't know why the page says I removed the labels, perhaps because I was adding labels at the same time?

**Comment by tupui** [comment]
@andyfaff what is the upload logic with the maintenance branch? I could not find the information in our doc https://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#wheel-builds

**Comment by andyfaff** [comment]
The logic for GHA and cirrusci is pretty much congruent.

**Comment by tupui** [comment]
I see that but that's not very clear at first glance. Could you add some documentation itself? Right where we currently describe CirrusCI?

**Review by rgommers — APPROVED** [review]
LGTM, let's give this a go and see if it resolves the problem.

**Comment by tupui** [comment]
Yes but then did you update the secret on CirrusCI? The hash in our config should be updated too no?

**Pull request merged**
