### PR TITLE
TST: fix incorrect signal.sosfilt tests

### PR DESCRIPTION
**Pull request by rgommers**
This caused failures on macOS arm64 with NumPy main, because `clongdouble` arrays started to be passed to `np.linalg.eigvals`.

This code, as the deleted comment in `cast_sos2tf` said, does not actually work with long double dtypes, nor with object. So trying to cast to complex128, call the functionality, then cast back, doesn't really make sense as a test. Hence simply delete the unsupported dtypes from the tests.

This fixes the macOS failures in the wheel build (xref gh-19605).

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
I did check that it fixes the failures alongside NumPy `main` for me on Mac ARM locally as well.

I'm still a bit confused, because we're also purging `g` (`float64`), and because of the way NumPy propagates the error messages back up, but I guess NumPy can decide if there's something reasonable to be done at https://github.com/numpy/numpy/pull/25285. 

I guess I can even confuse myself pretty easily though:

```python
>>> np.dtype("D")
dtype('complex128')
>>> np.dtype("G")
dtype('complex128')
>>> np.dtype("G") == np.dtype("D")
True
```

If there's a meaningful difference between those typecodes (the test fails with one, passes with the other), the repr is not doing it justice. Chaos, I need to take a NumPy class!

**Comment by ilayn** [comment]
On windows they are the same, on *nix they are not unfortunately.

**Comment by rgommers** [comment]
They're not the same - they have the same memory layout, but they are still distinct dtypes. Behavior is going to still differ, that was the initial problem with these tests - `numpy.linalg` simply does not support long doubles, but we tried to sneak them in; now NumPy's validation seems to have improved a bit and things fail.

**Comment by ilayn** [comment]
Ah I was replying to Tyler but didn't see your comment coming in, sorry about that.

**Comment by rgommers** [comment]
No worries! I'm sharing your pain by the way @ilayn, working on the Windows wheel builds by trying to build everything from source against NumPy main ... not enjoying it much so far:)

**Comment by tylerjereddy** [comment]
I'll carry my views on reprs being the same but the data underneath not being the same over to the NumPy PR then. `g` prints as `float64` on the problem platform.

**Comment by rgommers** [comment]
Sounds good. We should also clean up use of these one-character typecodes throughout SciPy at some point, they're too annoying (as this issue shows).

**Pull request merged**
