### PR TITLE
DEP: deprecate `scipy.stats.ss` and `scipy.stats.square_of_sums`.

### LINKED ISSUE #663: Statistics Review: ss (Trac #136)
_Original ticket http://projects.scipy.org/scipy/ticket/136 on 2006-04-02 by @rkern, assigned to @rkern._

The function `ss` in file source:trunk/Lib/stats/stats.py needs review.

Please look over the StatisticsReview guidelines and add your comments below.

### LINKED ISSUE #665: Statistics Review: square_of_sums (Trac #138)
_Original ticket http://projects.scipy.org/scipy/ticket/138 on 2006-04-02 by @rkern, assigned to @rkern._

The function `square_of_sums` in file source:trunk/Lib/stats/stats.py needs review.

Please look over the StatisticsReview guidelines and add your comments below.

### PR DESCRIPTION
**Pull request by aeklant**
closes gh-663; closes gh-665

### CODE REVIEW

**Comment by aeklant** [comment]
There is no test coverage for these supporting functions so there are no warnings to be silenced.

**Comment by rgommers** [comment]
Let's leave this open for at least 4 more days before merging, just in case someone objects on the mailing list.

**Comment by rgommers** [comment]
``ss`` and ``square_of_sums`` are used in ``f_oneway`` and ``kruskal`` at least, so they will be giving warnings. Instead of silencing, how about making the current functions private (prepend underscore) and then re-add like so

    @np.deprecate(...)
    def ss(a, axis=0):
        return _ss(a, axis=0)

**Comment by aeklant** [comment]
Alright, I made that change. I also made sure to change the name of `ss` to `_sum_of_squares` and removed the examples from the docstring because they are not meant to be used outside the module. 

Let me know if that's alright.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @aeklant

**Comment by rgommers** [comment]
For completeness the mailing list message (5 days ago, no responses): http://article.gmane.org/gmane.comp.python.scientific.devel/19714

**Pull request merged**
