### PR TITLE
WIP: DOC: Document how to set up meson with CLion nova

### PR DESCRIPTION
**Pull request by Kai-Striega**
#### Reference issue

na

#### What does this implement/fix?

This PR documents how to configure CLion Nova to allow syntax highlighting / code analysis / refactoring tools for SciPy. I spent several hours configuring this and wanted to document it somewhere.

#### Additional information

This is still a WIP. It is working locally for me, but is not tested thoroughly enough to be published (yet). I'd prefer some review and, if there is any interest, add it later.

cc @ev-br you expressed some interest in this.

### CODE REVIEW

**Comment by Kai-Striega** [comment]
@melissawm the build is failing because ``document isn't included in any toctree``. I know this means that I need to include it in a toctree (somewhere?) but I'm not really sure where to put it. Do you have any suggestions?

**Review by rgommers — COMMENTED** [review]
Thanks for sharing @Kai-Striega 

> CLion Nova executes the meson command in the global environment. This

That should not work reliably I think. Without environment activation, `LDFLAGS` & co aren't set. I suspect you're using the system linker rather than the conda env's linker, which may or may not work depending on which versions both are at.

Isn't it possible to instead define a build command like:
```
conda activate scipy-dev && python dev.py build
```
? 

Logistical comment: using `[docs only]` in the commit messages would be useful.

**Comment by Kai-Striega** [comment]
Sorry Ralf, I don't think I was very clear in how I phrased it, what we're doing here isn't building SciPy. It's only allowing CLion Nova to find the project structure. What is actually being executed is:

```
home/kai/miniconda3/envs/scipy-dev/bin/meson setup --native-file local-config.ini
```

> I suspect you're using the system linker rather than the conda env's linker, which may or may not work depending on which versions both are at.

Noted. Looking at the logs, this seems to work for me on Linux, however I'm not sure if that guaranteed to be the case.

```
 C compiler for the host machine: /home/kai/miniconda3/envs/scipy-dev/bin/gcc (gcc 12.3.0 "gcc (conda-forge gcc 12.3.0-5) 12.3.0")
C linker for the host machine: /home/kai/miniconda3/envs/scipy-dev/bin/gcc ld.bfd 2.40
C++ compiler for the host machine: /home/kai/miniconda3/envs/scipy-dev/bin/g++ (gcc 12.3.0 "g++ (conda-forge gcc 12.3.0-5) 12.3.0")
C++ linker for the host machine: /home/kai/miniconda3/envs/scipy-dev/bin/g++ ld.bfd 2.40
```

This isn't ready for release yet, but I wanted somewhere to document what has worked for me. And to gauge interest in having support.

**Comment by rgommers** [comment]
> Sorry Ralf, I don't think I was very clear in how I phrased it, what we're doing here isn't building SciPy. It's only allowing CLion Nova to find the project structure.

I'm not sure I understand. If CLion Nova has support for Meson-based projects, I can understand that you'd need to give it a hint somewhere about Meson or project structure. But if it's not about building, then why does it need to know about compilers? Looks like there are two things mixed here?

> This isn't ready for release yet, but I wanted somewhere to document what has worked for me. And to gauge interest in having support.

I suspect that this isn't specific to SciPy, but more to using Meson projects in general. And other IDEs/editors like VSCode may need something similar when they have functionality for project navigation, or something like a "build it" or debug/set-breakpoint type things. So it'd be useful to have that somewhere - but as concise as possible I think. Things like `git clone` commands shouldn't be repeated, you can just refer to the general doc page on that.

**Comment by Kai-Striega** [comment]
I'm going to close this for now. CLion has changed again and I want to wait until the method becomes more stable.

**Pull request closed without merging**
