### PR TITLE
BUG: test_falker not robust against numerical fuss in eigenvalues

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
The generalized eigenvalue-problem with two matrices `A` and `B`
as given in the `scipy.linalg.tests.test_decom:test_falker` is such that one 
of the generalized eigenvalue is infinite, one is a negative real, two are exact zeros, 
and the remaining two are complex conjugates of each other with a negative
real part.

To compare whether eigenvalues obtained from `eig` and from `eigvals` are
the same, the code checks `assert_all_close` on `np.sort`-ed finite eigenvalues.

The sorted vector of eigenvalues is sensitive to numerical fuss in real parts
of the complex conjugate eigenvalues pair.

It may happen, with a change from one solving library to another, or even with
the version upgrade of the same library, that the ordering of the result of `eig`
be `(-real + 1j*imag, -real -1j*imag)`, while the ordering of the result of
`eigvals` be `(-real - 1j*imag, -real + 1j*imag)`, which causes the test to fail,
even though the result is correct within the numerical precision.

To fix this issue, this PR introduces routine `clear_fuss` which zeros out
certain number of trailing binary digits (default is arbitrarily chosen as 7) in a real
number's mantissa. For complex numbers fuss is independently cleared for real and
imaginary parts.

Ordering permutation is computed for the vector where the fuss has been cleared,
and the permutation is applied to the actual vector of eigenvalues.  These permuted
vectors are then compared with `assert_all_close`.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
See https://github.com/scipy/scipy/pull/7084 and https://github.com/scipy/scipy/pull/7095 for examples of previously reported failures.

**Comment by ilayn** [comment]
That seems more like the sorting function needs to pair complex numbers first with negative or positive first.

**Comment by person142** [comment]
@ilayn I wonder if you could elaborate on your point more? As it stands the changes seem reasonable to me.

**Comment by ilayn** [comment]
Ah I didn't mean that this is not a valid change. I meant as in `esort`, or `dsort`  behavior in matlab. Always place the eig with positive imag part before its conjugate in the array kind. That would not let these order problems happen.

**Comment by person142** [comment]
Right, and that should be what NumPy is doing:

```
>>> np.sort([1 + 1j, 1, 1 - 1j])
array([ 1.-1.j,  1.+0.j,  1.+1.j])
```

(Well that's negative real part first, but no matter.) IIUC the issue here is that the real parts aren't coming out exactly equal, so the sort never falls back to the imaginary part check, and the fix is to round the real parts so that they are equal and the fallback happens.

**Comment by ilayn** [comment]
Yes indeed. I wrote an overkill for pairing complex numbers some time ago. If you think it is salvagable for SciPy I might try to make a PR out of it. 

You can find it [here](https://github.com/ilayn/harold/blob/master/harold/_aux_linalg.py#L148)

**Comment by pv** [comment]
You can use the linear assignment solver from scipy.optimize for finding the optimal permutation for pairing complex numbers. But that's also overkill.

**Comment by pv** [comment]
fixed pep8 issue, merge once ci finishes

**Pull request merged**
