### PR TITLE
DOC: badge with version of the doc in the navbar

### PR DESCRIPTION
**Pull request by tupui**
Add a badge with the version information to the navbar between the logo and the sections. The badge is an hyperlink to the list of versions (https://docs.scipy.org/doc/).

The badge is responsive.

As discussed in #14128

Screenshot 2021-05-25 at 15 27 44

Screenshot 2021-05-25 at 15 19 06
119655356-c7cd7700-be29-11eb-96b2-6f9a4e254583
Screenshot 2021-05-29 at 09 33 00

### CODE REVIEW

**Comment by mdhaber** [comment]
Looks great to me! 
Re: colors - Maybe green for most recent release, red for old releases, and yellow (/amber) for dev? I guess it doesn't work exactly like a traffic light, but could be reasonable choices nonetheless. Do you know of other libraries that color code?

**Comment by tupui** [comment]
> Looks great to me!

🥳

> Re: colors - Maybe green for most recent release, red for old releases, and yellow (/amber) for dev? I guess it doesn't work exactly like a traffic light, but could be reasonable choices nonetheless. Do you know of other libraries that color code?

Colors choices are tricky and I am not sure about best practices here for color deficient people. I will search other examples, but I have nothing in mind right now.

**Comment by tupui** [comment]
I found this nice website which gives nice color-blind palettes https://davidmathlogic.com/colorblind

I will see to make the logic for changing the colors and then select some colors from there.

So *latest* is on the same foot as *recents*, correct? Also what is *recents*? According to NEP29? If yes, do we want to have a manual list, or rely on some internal/external tools like `pip install nep29`?

**Comment by tupui** [comment]
I am just seeing https://github.com/scipy/docs.scipy.org/blob/master/_static/versionwarning.js_t. I am not sure how this will play along here. This would be something separate I would say...

So for now I propose to have green for latest stable and orange/amber for dev. @rgommers what do you think?

**Comment by tupui** [comment]
If the `version` from `conf.py` does not have `dev` here is the result:

Screenshot 2021-05-26 at 13 52 53

**Comment by mdhaber** [comment]
> So for now I propose to have green for latest stable and orange/amber for dev

Would there be a color for old versions?

**Comment by tupui** [comment]
> Would there be a color for old versions?

I just don't know how to get this information. Would you have some way in mind? I could remove the javascript which currently add the banner and use the logic in `conf.py` to define a variable that I can use for that.

**Comment by tupui** [comment]
For reference here is the color palette https://davidmathlogic.com/colorblind/#%23E69F00-%23009E73-%23980F0F

Screenshot 2021-05-29 at 08 29 08

**Comment by tupui** [comment]
@mdhaber I think now it should work. Locally I added `tags.add('versionwarning')` in `conf.py` and it's red as expected.

One tweak that could be done would be to change `RELEASE` as well depending on the status. Not sure here. But otherwise I think it looks good and it's ready.

What do you think @rgommers?

**Comment by tupui** [comment]
Unrelated note. Locally (macOS) I am always getting these warnings for `odr`. But this does not happen on CI. Is this known? Does not seem to be dramatic hence I did not open an issue yet.
```bash
.../scipy/scipy/odr/__init__.py:docstring of scipy.odr.rst:10: WARNING: autosummary: stub file not found 'scipy.odr.odr'. Check your autosummary_generate setting.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorial/stats/discrete_zipfian                                                                                                                                                                
docstring of _odrpack.odr:16: WARNING: py:obj reference target not found: ODR
docstring of _odrpack.odr:28: WARNING: py:obj reference target not found: ODR
.../scipy/scipy/odr/__init__.py:docstring of scipy.odr:29:<autosummary>:1: WARNING: py:obj reference target not found: scipy.odr.ODR
release/1.6.0-notes.rst:47: WARNING: py:obj reference target not found: scipy.odr.ODR
```

**Comment by rgommers** [comment]
Re `odr` warning: I've seen that happen before, probably Sphinx-version-dependent. I suggest ignoring it for now - `scipy.odr.ODR` is definitely a thing, and the formatting in the release notes is correct.

**Comment by tupui** [comment]
This should be actually part of the joint proposal to improve PyData Sphinx theme. So maybe not needed now. @jorisvandenbossche you might be interested.

**Comment by tupui** [comment]
Do we want to go with this or wait for a possible integration in the theme?

**Comment by mdhaber** [comment]
Fine with me to wait.

**Comment by rgommers** [comment]
The preview has disappeared, regenerating. 

> Do we want to go with this or wait for a possible integration in the theme?

What's your preference @tupui?

**Comment by rgommers** [comment]
The preview has disappeared, regenerating. 

> Do we want to go with this or wait for a possible integration in the theme?

What's your preference @tupui?

**Comment by tupui** [comment]
Before a few days I would have said we merge. But since I went over the theme's issue tracker, I revived the topic and there is a new active PR. So this might Lead somewhere this time. It would be easy as well to come remove later should we merge it so I am neutral here.

xref https://github.com/pydata/pydata-sphinx-theme/pull/433

**Review by rgommers — APPROVED** [review]
Nice! It'll be a while till a version switcher is in a release of the theme though. This PR is small and LGTM, so let's give it a try.

**Comment by rgommers** [comment]
Squash-merged so it's easier to revert when upgrading to the theme version with the switcher.

**Comment by tupui** [comment]
> Squash-merged so it's easier to revert when upgrading to the theme version with the switcher.

Great, thanks Ralf!

**Pull request merged**
