### PR TITLE
ENH: linalg.nullspace: expose SVD options

### LINKED ISSUE #21166: ENH: `linalg.null_space`: expose `lapack_driver` and `check_finite`
### Is your feature request related to a problem? Please describe.

As discussed in https://github.com/scipy/scipy/issues/10032 `gesdd` sometimes gives inaccurate results. `scipy.linalg.svd` also provides the option to skip finite check of `A`.

### Describe the solution you'd like.

Expose these two keyword arguments.

### Describe alternatives you've considered.

_No response_

### Additional context (e.g. screenshots, GIFs)

_No response_

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

closes #21166
#### What does this implement/fix?

Exposes `overwrite_a`, `check_finite=True`, and `lapack_driver` in `nullspace` as these are useful to be able to set.

### CODE REVIEW

**Comment by ilayn** [comment]
Looks good to me. Probably it also needs an additional "if the driver is unknown, error out" line

**Comment by j-bowhay** [comment]
Thanks for taking a look @ilayn 

> Looks good to me. Probably it also needs an additional "if the driver is unknown, error out" line

Can we not rely on the check in `svd`?
```
In [1]: import numpy as np

In [2]: from scipy.linalg import null_space

In [3]: null_space(np.eye(2), lapack_driver="magic")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 null_space(np.eye(2), lapack_driver="magic")

File ~/development/scipy/build-install/lib/python3.11/site-packages/scipy/linalg/_decomp_svd.py:415, in null_space(A, rcond, overwrite_a, check_finite, lapack_driver)
    348 def null_space(A, rcond=None, *, overwrite_a=False, check_finite=True,
    349                lapack_driver='gesdd'):
    350     """
    351     Construct an orthonormal basis for the null space of A using SVD
    352 
   (...)
    413 
    414     """
--> 415     u, s, vh = svd(A, full_matrices=True, overwrite_a=overwrite_a,
    416                    check_finite=check_finite, lapack_driver=lapack_driver)
    417     M, N = u.shape[0], vh.shape[1]
    418     if rcond is None:

File ~/development/scipy/build-install/lib/python3.11/site-packages/scipy/linalg/_decomp_svd.py:135, in svd(a, full_matrices, compute_uv, overwrite_a, check_finite, lapack_driver)
    133 if lapack_driver not in ('gesdd', 'gesvd'):
    134     message = f'lapack_driver must be "gesdd" or "gesvd", not "{lapack_driver}"'
--> 135     raise ValueError(message)
    137 if lapack_driver == 'gesdd' and compute_uv:
    138     # XXX: revisit int32 when ILP64 lapack becomes a thing
    139     max_mn, min_mn = (m, n) if m > n else (n, m)

ValueError: lapack_driver must be "gesdd" or "gesvd", not "magic"
```

**Comment by ilayn** [comment]
Yes also fine indeed

**Comment by j-bowhay** [comment]
@ilayn is there any left to do here?

**Review by ilayn — APPROVED** [review]
All good from my side.

**Comment by lucascolley** [comment]
thanks both!

**Pull request merged**
