### PR TITLE
BUG: Fix regression in dblquad: #6458

### PR DESCRIPTION
**Pull request by woodscn**

### CODE REVIEW

**Comment by ev-br** [comment]
@jobovy could you test this PR on your problems which led to #6458

**Comment by jobovy** [comment]
Would be happy to do this, but I can't get scipy to install from source on my machine (an issue I've been having for many years, luckily now solved by conda). I think this is a simple enough fix that the automated test can be trusted as much as me!

**Comment by ev-br** [comment]
OK, let's merge this. Thanks @woodscn @jobovy

**Comment by ev-br** [comment]
backported in gh-6557

**Pull request merged**
