### PR TITLE
DEP: deprecate scipy.signal wavelets

### PR DESCRIPTION
**Pull request by ev-br**
#### What does this implement/fix?

Act on the roadmap item (https://docs.scipy.org/doc/scipy/dev/roadmap-detailed.html),

> Wavelets: what’s there now doesn’t make much sense. Continuous wavelets only at the moment - decide whether to completely rewrite or remove them. Discrete wavelet transforms are out of scope (PyWavelets does a good job for those).

Do the simplest thing: deprecate all public symbols under `scipy/signal/_wavelets.py`, point to PyWavelets instead.

### CODE REVIEW

**Comment by j-bowhay** [comment]
Please could you propose on the mailing list just to make sure everybody is happy :)

**Comment by j-bowhay** [comment]
Also I think these functions will need adding here to fix the doc build https://github.com/scipy/scipy/blob/4c45942cc5dfbf6d5fa82b44ae595d11a7e5d08b/doc/source/conf.py#L324-L332

**Comment by endolith** [comment]
https://github.com/scipy/scipy/issues/1449#issuecomment-518476757

https://pywavelets.readthedocs.io/en/latest/ref/cwt.html

https://github.com/OverLordGoldDragon/ssqueezepy/releases claims to be better solution for CWT

(I haven't tried or compared them)

**Review by ilayn — APPROVED** [review]

**Comment by ev-br** [comment]
for completeness, the ML thread (silent for last ten days): https://mail.python.org/archives/list/scipy-dev@python.org/thread/E5JAKFP2AQS2OLBABU6YNVK55QGTFUFF/

**Comment by j-bowhay** [comment]
Time allowing, hope to review/merge this in the coming week

**Review by j-bowhay — APPROVED** [review]
Thanks @ev-br

**Comment by endolith** [comment]
> (silent for last ten days)

(Mailing lists are a pretty dead form of communication, though.  Maybe posting such RFCs on social media would reach more people?  Or somewhere where people who actually use things would be more likely to see them?  [There are various uses of these functions out there](https://github.com/search?q=%22from+scipy.signal+import+cwt%22&type=code).)

**Comment by ev-br** [comment]
Does my preferring a dead form of communication mean I'm a zombie? :-).

Seriously though, the policy is that RFCs / API changes go through the mailing list; do you have a preference for a specific  other medium @endolith? I think we can discuss that, the first thing the discussion would need is a champion though.

For the usage --- thanks! --- I still believe users are better off either moving to PyWavelets or copy-pasting small code snippets that are `cwt`, `morlet` etc.
If large problems appear before the release or during the rc phase, we can of course revert the removal. WDYT?

**Pull request merged**
