### PR TITLE
Fix: Negative zero handling with ifort

### LINKED ISSUE #11339: TestExp1.test_branch_cut test failure with Intel Fortran
Running Windows Scipy 1.4.1 (compiled with MKL taken from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy) standard test suite with Python 3.7.6 x64 results in failure for TestExp1.test_branch_cut test:
 
```
_________________________________________________________________________________________________________ TestExp1.test_branch_cut _________________________________________________________________________________________________________

self = <scipy.special.tests.test_exponential_integrals.TestExp1 object at 0x00000296E7953EC8>

    def test_branch_cut(self):
        assert np.isnan(sc.exp1(-1))
>       assert sc.exp1(complex(-1, 0)).imag == (
            -sc.exp1(complex(-1, -0.0)).imag
        )
E       AssertionError: assert -3.141592653589793 == --3.141592653589793
E        +  where -3.141592653589793 = (-1.8951178163559368-3.141592653589793j).imag
E        +    where (-1.8951178163559368-3.141592653589793j) = <ufunc 'exp1'>((-1+0j))
E        +      where <ufunc 'exp1'> = sc.exp1
E        +      and   (-1+0j) = complex(-1, 0)
E        +  and   -3.141592653589793 = (-1.8951178163559368-3.141592653589793j).imag
E        +    where (-1.8951178163559368-3.141592653589793j) = <ufunc 'exp1'>((-1-0j))
E        +      where <ufunc 'exp1'> = sc.exp1
E        +      and   (-1-0j) = complex(-1, -0.0)

self       = <scipy.special.tests.test_exponential_integrals.TestExp1 object at 0x00000296E7953EC8>

C:\Program Files\Python\3.7.6\lib\site-packages\scipy\special\tests\test_exponential_integrals.py:12: AssertionError
```

On the same PC package manually compiled with MKL on Ubuntu 18.04 (Python 3.6.5) successfully passes all tests.

### PR DESCRIPTION
**Pull request by h6197627**
#### Reference issue
Fixes #11339

#### What does this implement/fix?
SciPy compiled with Intel Fortran compiler fails scipy.special.tests.test_exponential_integrals.TestExp1 test because with default flags it treats both -0.0 and +0.0 as 0.0.

### CODE REVIEW

**Comment by h6197627** [comment]
cc @person142 for visibility

**Comment by h6197627** [comment]
cc @pv for visibility

**Comment by h6197627** [comment]
@person142, @pv, @rgommers kind reminder :)

**Comment by rgommers** [comment]
Thanks for the ping @h6197627. I commented on gh-11339

**Comment by h6197627** [comment]
Closed in favor https://github.com/numpy/numpy/pull/18753

**Pull request closed without merging**
