### PR TITLE
ENH: option to reuse binnumbers in scipy.stats.binned_statistic_dd

### PR DESCRIPTION
**Pull request by egouden**
Dear scipy developers,

This is my first pull request to the scipy project !
It adds the functionality of reusing the bin numbers in scipy.stats.binned_statistic_dd.
This is useful when new values are available for the same dataset.
A quick benchmark shows a decrease in computation time by a factor 3.

Best regards,

Edouard

### CODE REVIEW

**Comment by ev-br** [comment]
You don't need to close PRs, you can just push (or force-push if needed) additional commits to the branch you're sending the PR from

**Comment by egouden** [comment]
What if the CI fails for reasons apparently unrelated to the PR?

**Comment by rgommers** [comment]
If it's unrelated then you can just add a comment that that's the case and ignore it (likely it'll then either be a flake and we can re-trigger, or it's something we're busy fixing somewhere else).

**Comment by egouden** [comment]
But I cannot re-trigger (without new commits) as a contributor right?

**Comment by rgommers** [comment]
If you want that, you can close and immediately re-open a PR, that will re-trigger everything. But yes, only people with commit rights can re-run one job or one CI system. So usually just ignoring it is fine.

**Comment by ev-br** [comment]
One way would be to first rebase on current master and force-push, in case it's something already fixed. If that does not help, do what Ralf said: leave a comment and ignore.


You can close/reopen. Or just leave a comment (what Ralf said) and leave it at that.

**Pull request closed without merging**
