### PR TITLE
Pytestifying

### PR DESCRIPTION
**Pull request by pv**
Work in progress in replacing nose with pytest. (On top of some previous unmerged PR.)
Putting this up early in case there is some comment.

Todo

- [x] Add basic `test()` function in top-level scipy package.
- [x] Fix up things in `runtest.py`.
- [x] Convert `tests` dir to subpackages and fix imports.
- [x] Fix up minor things so that test collection passes and it runs.
- [x] dec.knownfailureif
- [x] dec.skipif
- [x] dec.slow (custom marker)
- [x] SCIPY_XSLOW (custom marker)
- [x] Fix `sparse:test_base.py:_TestCommon` (a bit ugly; but the yield tests that necessitate this would be on way out anyway)
- [x] Replace `test()` in all subpackages.
- [x] Make travis pass
- [x] Make circleci pass

Fixing up all the yield tests, which is a bit of more work, can be done later. 
We can stick with Pytest 3.x for that.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Now that the first two test janitoring PRs have been merged, could you rebase?

**Comment by pv** [comment]
Everything seems to pass on Travis now.

The big remaining thing would be conversion of all yield tests to pytest.mark.parametrize, plain for loops (pytest can print local variables), or some other approach --- the refactoring in some cases may need some thought on how to do it. This in principle can be done later piecewise, as they're still supported in current pytest. (Although, if you forget to say `--disable-warnings` or pipe the output to `uniq`, pytest will print the "yield tests are deprecated" message 15652 times to make sure you got it :)

There are also some more minor cleanups that could be done.

**Comment by rgommers** [comment]
> The big remaining thing would be conversion of all yield tests to pytest.mark.parametrize, plain for loops (pytest can print local variables), or some other approach --- the refactoring in some cases may need some thought on how to do it.

I'd be happy to see the ``yield``-based tests go in some cases. For example the ARPACK or 64-bit sparse tests; when something is wrong you often get 20-100 test errors instead of one or two, which gives the impression that something is horribly broken (bad for users) or you just have to scroll forever in a terminal (bad for devs).

So if a for-loop approach can be made to work, that sounds good to me.

**Comment by pv** [comment]
Note that I was thinking of leaving fixing the yield tests to be done 
later in separate PRs. They are still supported in pytest, and 
refactoring them is a bit more complicated as it's not just a 
search-and-replace operation.

**Comment by rgommers** [comment]
> Note that I was thinking of leaving fixing the yield tests to be done later in separate PRs.

So this is good to merge as is (after a rebase)? Still has ``WIP`` in the PR title

**Comment by pv** [comment]
Yes, I think this is no longer WIP, as I think I won't be adding more 
stuff here.

**Comment by rgommers** [comment]
Looks like `` pytest.ini`` needs to be added to ``MANIFEST.in``.

This looks good from a browse. Would like to test in a bit of detail

**Comment by rgommers** [comment]
Question: with the removal of ``run_module_suite``, is there still a way to run one file?

**Comment by pv** [comment]
The same way you would do it with nose:
.
python -c "scipy.test(tests=['scipy.fftpack.tests.test_basic'])"
python runtests.py -t scipy/fftpack/tests/test_basic.py
cd scipy/fftpack/tests; python -mpytest test_something.py  (not sure if 
making the tests packages breaks this)
.
We may also want to add --disable-warnings to pytest.ini to avoid 
getting the tens of thousands of "yield tests are deprecated" messages.

**Comment by rgommers** [comment]
Hmm, first test drive: 

    $ python -c "import scipy as s; s.test()"
    ========================================= test session starts ==========================================
    platform linux2 -- Python 2.7.6, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
    rootdir: /home/rgommers/Code/tmp, inifile: 
    plugins: xdist-1.13.1, timeout-0.5, capturelog-0.7
    collected 23164 items / 3 errors 
     .....................EEEEEEEEEEx..EEE
     <etc>
    INTERNALERROR> Traceback (most recent call last):
    INTERNALERROR>   File "/home/rgommers/.local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
    INTERNALERROR>     session.exitstatus = doit(config, session) or 0
    INTERNALERROR>   File "/home/rgommers/.local/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
    INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
    INTERNALERROR>   File "/home/rgommers/.local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    <etc>
    =============================== 460 tests deselected by "-m 'not slow'" ================================
     1 failed, 17263 passed, 1798 skipped, 460 deselected, 74 xfailed, 1 xpassed, 3 pytest-warnings, 1863 error in 448.68 seconds 

After upgrading to latest ``pytest`` (3.1.3) it looks much better. Guess needs a check for minimum supported version somewhere.

**Comment by rgommers** [comment]
One test failure with latest pytest:


    _________________________________________ TestExpect.test_zipf _________________________________________

    self = <scipy.stats.tests.test_distributions.TestExpect object at 0x851b55ac>

        def test_zipf(self):
            # Test that there is no infinite loop even if the sum diverges
            assert_warns(RuntimeWarning, stats.zipf.expect,
    >           lambda x: x**2, (2,))

    self       = <scipy.stats.tests.test_distributions.TestExpect object at 0x851b55ac>

    ../scipy/scipy/stats/tests/test_distributions.py:1964: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    ../../.local/lib/python2.7/site-packages/numpy/testing/utils.py:1730: in assert_warns
        return func(*args, **kwargs)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = <contextlib.GeneratorContextManager object at 0x851b584c>, type = None, value = None
    traceback = None

        def __exit__(self, type, value, traceback):
            if type is None:
                try:
    >               self.gen.next()
    E               AssertionError: No warning raised when calling expect

    self       = <contextlib.GeneratorContextManager object at 0x851b584c>
    traceback  = None
    type       = None
    value      = None

    /usr/lib/python2.7/contextlib.py:24: AssertionError
    =========================================== warnings summary ===========================================
    :68
      'pytest_runtest_protocol' hook uses deprecated __multicall__ argument

    :171
      'pytest_runtest_makereport' hook uses deprecated __multicall__ argument

    None
      pytest_funcarg__caplog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
      pytest_funcarg__capturelog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.

    /home/rgommers/Code/scipy/scipy/_lib/tests/test_ccallback.py
      yield tests are deprecated, and scheduled to be removed in pytest 4.0
      <infinite amounts of warnings to follow>

**Comment by charris** [comment]
> Question: with the removal of run_module_suite, is there still a way to run one file?

Fixing run_module_suite was the easy part in numpy. Fixing runtests and friends, as here, looks more difficult (to me.  I'll probably steal some of this ...

**Comment by pv** [comment]
@charris: how did you fix run_module_suite? Transforming test/ to 
packages + adding conftest.py seems to throw cranks in the gears?

**Comment by pv** [comment]
@rgommers: looks a bit like another warning suppression 
indeterminancy... not sure if the test order is fully deterministic. 
Maybe this is fixed by gh-7583 (needs to be merged before this).
.
The semi-infinite "yield tests are deprecated" spam will hopefully be 
fixed in the next pytest version.

**Comment by charris** [comment]
@pv Like so. The plugin isn't needed, I've just been fooling around with them to see how they work.
```
    import pytest
    from .noseclasses import NpyPlugin

    if file_to_run is None:
        f = sys._getframe(1)
        file_to_run = f.f_locals.get('__file__', None)
        if file_to_run is None:
            raise AssertionError

    if argv is None:
        argv = sys.argv[1:] + [file_to_run]
    else:
        argv = argv + [file_to_run]

    pytest.main(argv, plugins=[NpyPlugin()])
```

**Comment by pv** [comment]
That fails because of conftest.py and __init__.py under tests/.
Either of those is enough to make it not to work, although the former 
can be avoided by --noconftests, but that makes tests behave in a 
different way which not desirable.

**Comment by charris** [comment]
Works fine for me on NumPy, I've been using it for several days. There must be something different about SciPy.
```
charris@fc [numpy.git (add-pytest-support)]$ NPY_PYTEST=1 python numpy/core/tests/test_umath_complex.py --disable-pytest-warnings -q
...................s.........................................s...............
75 passed, 2 skipped, 67 warnings in 0.06 seconds
```

**Comment by pv** [comment]
The difference is having a conftest.py, and __init__.py in test directories.

**Comment by charris** [comment]
The conftest.py files could probably be gotten rid of by using a class plugin instead. The `__init__.py` are something else, what problem do they cause ?

**Comment by pv** [comment]
I would not want to go with custom test runners and plugins, to keep 
things simple and to retain similarity between `pytest --pyargs scipy` 
and `scipy.test`.
.
I think dropping run_module_suite and sticking close to the pytest 
recommended setup is a simpler alternative.

**Comment by rgommers** [comment]
> I think dropping run_module_suite and sticking close to the pytest recommended setup is a simpler alternative.

Sounds OK to me

**Comment by andyfaff** [comment]
OSX10.12.5 
platform darwin -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0

Getting weird errors thinking I'm on Linux for some reason. Test run using `python runtests.py` after `rm -r build; git clean -xdf`

```
======================================================================== ERRORS =========================================================================
___________________________ ERROR collecting build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_sparsetools.py ___________________________

self = <scipy.sparse.tests.test_sparsetools.TestInt32Overflow object at 0x121296ba8>

    def setup_method(self):
        assert self.n**2 > np.iinfo(np.int32).max
    
>       check_free_memory(9000)

self       = <scipy.sparse.tests.test_sparsetools.TestInt32Overflow object at 0x121296ba8>

scipy/sparse/tests/test_sparsetools.py:81: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
scipy/sparse/tests/test_sparsetools.py:310: in check_free_memory
    meminfo = get_mem_info_linux()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_mem_info_linux():
        """
        Get information about available memory.
    
        Returns a dict of items in /proc/meminfo
        """
        info = {}
>       with open('/proc/meminfo', 'r') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/proc/meminfo'

info       = {}

scipy/sparse/tests/test_sparsetools.py:323: FileNotFoundError
___________________________ ERROR collecting build/testenv/lib/python3.6/site-packages/scipy/sparse/tests/test_sparsetools.py ___________________________

self = <scipy.sparse.tests.test_sparsetools.TestInt32Overflow object at 0x12135bac8>

    def setup_method(self):
        assert self.n**2 > np.iinfo(np.int32).max
    
>       check_free_memory(9000)

self       = <scipy.sparse.tests.test_sparsetools.TestInt32Overflow object at 0x12135bac8>

scipy/sparse/tests/test_sparsetools.py:81: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
scipy/sparse/tests/test_sparsetools.py:310: in check_free_memory
    meminfo = get_mem_info_linux()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def get_mem_info_linux():
        """
        Get information about available memory.
    
        Returns a dict of items in /proc/meminfo
        """
        info = {}
>       with open('/proc/meminfo', 'r') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/proc/meminfo'

info       = {}

scipy/sparse/tests/test_sparsetools.py:323: FileNotFoundError
```

**Comment by andyfaff** [comment]
Further information, the errors I reported are seen using `import scipy;scipy.test()` as well. None of the test suite runs because those errors are seen during test collection.

**Comment by pv** [comment]
@andyfaff: thanks, those tests were supposed to skipped on non-linux. Should be fixed now (another yield test + mark issue).

**Comment by andyfaff** [comment]
The tests run this time. There is still a test failure, #7590, log at this [gist](https://gist.github.com/andyfaff/7ea166f38921536022c8bf0b00a9651f). Is there anyway we can get a CI working on a true OSX install?

**Comment by rgommers** [comment]
> The tests run this time. There is still a test failure, #7590, log at this gist. Reinforces the need to OSX CI

That test failure is already present in master, not introduced by this PR. So nothing stopping this PR from getting merged I think.

**Comment by rgommers** [comment]
Okay went through this again, LGTM. Needs another rebase, when it's green it can be merged I think.

**Comment by pv** [comment]
Finally, is there a way to get ccache enabled also on the osx side for clang.
If it's enabled, it will greatly speed up the build due to the various c++ modules...

**Comment by pv** [comment]
Rebased.

**Comment by rgommers** [comment]
Merged, thanks a lot @pv !

**Comment by charris** [comment]
@rgommers @v You can do
```
charris@fc [scipy.git (master)]$ pytest --pyarg scipy/stats/tests/test_multivariate
================================= test session starts ==================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/charris/Workspace/scipy.git, inifile: pytest.ini
collected 69 items 

. .....................................................................

============================== 69 passed in 0.74 seconds ===============================
```
I suspect that can be made into a `run_module_suite` pytest fixup.

**Comment by pv** [comment]
@charris: note that it seems to run the installed version of the file, not the file under `$PWD/scipy/stats/tests/test_multivariate` which may be confusing --- it seems to be the same as `pytest --pyargs scipy.stats.tests.test_multivariate`.

**Comment by charris** [comment]
Ah, indeed, that seems to be the case. I was looking for a substitute for `nose.runmodule`, but apparently this isn't it.

**Pull request merged**
