### PR TITLE
Use miniforge for uploading wheel builds

### PR DESCRIPTION
**Pull request by andyfaff**
Use miniforge instead of miniconda for uploading wheels.

Whilst I don't think it's ultimately essential for the project I was prompted to make the changes by https://discuss.scientific-python.org/t/response-to-anaconda-switch-to-paid-plans/1395.

### CODE REVIEW

**Comment by andyfaff** [comment]
Also, it's not fully clear if this PR will work until the nightly builds run.

**Comment by lucascolley** [comment]
shall we merge and then revert if the nightlies have problems?

**Comment by andyfaff** [comment]
I think merge and iterate until it works

**Comment by lucascolley** [comment]
thanks Andrew!

**Pull request merged**
