### PR TITLE
MAINT: backports for SciPy 1.3.2

### PR DESCRIPTION
**Pull request by tylerjereddy**
Backports included (so far):

- #10930 
- #10906 
- #10891 
- #10882 
- #10833 
- #10756 
- #10709
- #10700 
- #10693 
- #10671 
- #10498 
- #10536 
- #10943 
- #10938
- #10917
- #10977 
- #10961
- #10971

TODO:

- [x] address #10967 if it shows up again in this backport PR (most likely will)
- [x] address other failures that show up (some of the 3.8-related backports were fraught with merge conflicts & I spent quite some time deleting fixes for code that doesn't even exist on the maintenance branch)
- [x] bump Travis 3.8-dev CI check to 3.8 "release" (backport from from a master-branch PR if possible)
- [ ] when the above backport list is complete/CI is green, go through and adjust PR milestones to 1.3.2 (same for cognate issues, where they exist), to give traction to the issue/PR/author list scripts
- [ ] update release notes, with help from those scripts & final curation

### CODE REVIEW

**Comment by tylerjereddy** [comment]
I've pushed an attempted fix for the `test__differential_evolution.py` import issues causing errors on Azure and Appveyor jobs. Seems to work locally, but @larsoner may want to confirm those fixes.

I think it was probably a matter of some changes that snuck in to empower 3.8 compatibility for features that don't exist on this branch.

The Travis failures are another matter.

**Comment by tylerjereddy** [comment]
Azure builds not showing up in the matrix--will keep an eye on that..

**Comment by tylerjereddy** [comment]
Ok, now down to just the MacOS build failure reported in #10967, so that's progress.

I'm a bit surprised the `TestDualAnnealing.test_slsqp_ls_minimizer` failure in other Travis matrix entries just disappeared after I fixed the error in `scipy/optimize/tests/test__differential_evolution.py `, but I'll take it.

**Comment by tylerjereddy** [comment]
I've cherry-picked Pauli's fix--hopefully CI becomes all green now. Of course, a list of more things to backport has grown.

**Comment by tylerjereddy** [comment]
I'm still planning to backport: #10977, #10961, #10971. Hopefully not much more beyond that. Also, the wheels repo is complaining/failing on Travis & Appveyor so will chip away at that & will have to look into 3.8 there as well (can hopefully build on some of the stuff Chuck & Matti did for 3.8 NumPy wheels, I think).

**Comment by rgommers** [comment]
List of backports looks good, and this is all green now. List of todos in PR description LGMT as well.

**Comment by tylerjereddy** [comment]
Added the final 3 backports I was planning to put in--fingers crossed CI remains green. Then I can focus on the wheels repo/release notes.

**Comment by rgommers** [comment]
All green, in it goes. Thanks Tyler!

**Comment by rgommers** [comment]
the release notes can be separate

**Pull request merged**
