### PR TITLE
DOC: Clean up README

### PR DESCRIPTION
**Pull request by jarrodmillman**
I added some badges, simplified some text, and made it more compact so that it is easier to view and find information.

### CODE REVIEW

**Comment by ilayn** [comment]
Regarding the badges while they are useful for other projects, I think they don't serve any purpose for SciPy, because code is thoroughly tested before merges and the badges have some refresh delay, probably any failure would be fixed before they get updated.

**Comment by jarrodmillman** [comment]
I am not sure what you mean by "code is thoroughly tested before merges".  Isn't that standard practice for projects using automated testing of PRs?  Does SciPy do some extra level of testing that other projects (like NumPy, matplotlib, scikit-learn, scikit-image, networkx, etc.) don't?

I like badges in the READMEs of projects because it is an easy and compact way of letting visitors see what integration services you are using for the passing bits also the coverage report is nice.  They don't take up much space and provide a quick sense of new visitors of the extent to which the project is tested without having to dig into the documentation or look at configuration files.  For developers, it provides a convenient location for finding links to the various integration systems used for projects. 

I am not sure what you like about the Pandas README.  Are you pointing to it as a example of inserting a logo in a README?  Or is there something else about their README you like?  Personally, I find their README a bit too long and uses too much vertical space making it difficult to get a quick visual overview.

If you want me to insert the logo, I can do the same thing I did for NumPy:
  https://github.com/numpy/numpy/blob/master/README.md
I found this logo:
  https://github.com/scipy/scipy/blob/master/doc/source/_static/scipyshiny_small.png
However, it would be better if there was a banner style logo like the one I used for NumPy.  (Personally, I prefer just having a plain text "logo", but I don't have a strong opinion.)

**Comment by ilayn** [comment]
I mean, seeing a `build:passing` badge wouldn't say much, I am not sure about its purpose. I don't think anybody would leave it in a `build:failing` state especially SciPy scaled projects so having another badge seems redundant to me but I also don't have any strong opinion about them. 

For the integration services yes indeed that might be a message. We can still have those as you said they don't take up any space. There are more examples here : http://shields.io/

Pandas example was for the logo example and the badge table layout. Instead of leaving them inline without any frames, maybe we can also confine them into proper layout

**Comment by jarrodmillman** [comment]
I used the badges from http://shields.io/ already so that the badge don't just say ``build:passing``, but ``Travis CI: passing``, ``AppVeyor: passing``, and ``CircleCI: passing``.

I don't see any advantage to using a table layout like pandas did.

**Review by ghost — CHANGES_REQUESTED** [review]
[retracted]

**Comment by matthew-brett** [comment]
I have no opinion on the badges, but it does look simpler and less verbose to me.

**Comment by perimosocordiae** [comment]
I'm also +1 for this change. Less text, same content, gets the job done.

**Comment by ilayn** [comment]
If nobody else shares my opinion about the badges, then let's get it in 😃

**Comment by rgommers** [comment]
https://github.com/jarrodmillman/scipy/tree/readme-cleanup looks like a significant improvement over the current README, and I'm fine with the badges.

**Comment by rgommers** [comment]
Oh and welcome back @jarrodmillman !

**Comment by person142** [comment]
In it goes then.

**Pull request merged**
