### PR TITLE
DOC and BUG: Bessel function docstring improvements, fix array_like, general formatting (repush)

### PR DESCRIPTION
**Pull request by endolith**
Same as https://github.com/scipy/scipy/pull/5214

### CODE REVIEW

**Comment by endolith** [comment]
Still not working:

```
Line 46, in kn

Failed example:

kn([4, 5, 6], 1)

Expected:

array([ 44.2324, 360.9606, 3653.8384], dtype=float32)

Got:

array([ 44.23241585, 360.9605896 , 3653.83831186])
```

**Comment by WarrenWeckesser** [comment]
Slightly off-topic for this PR, but I think it is a bug that `yn([1, 2, 3], 1)` and `kn([1, 2, 3], 1)` return arrays with dtype `np.float32`.  The default type should be `np.float64`.  If you change any argument to a float, or if you make the second argument a sequence, or if you make the first argument a scalar, `np.float64` values are returned.  I'll create a separate issue for this.

**Comment by WarrenWeckesser** [comment]
It turns out my previous comment is not off-topic.  With scipy 0.16.0, the return value of `kn([4, 5, 6], 1)` has dtype `np.float32`.  In master, it has dtype `np.float64`.

This is scipy version `'0.17.0.dev0+ea8d2d1'`:
```
In [1]: from scipy.special import kn

In [2]: kn([4, 5, 6], 1)
Out[2]: array([   44.23241585,   360.9605896 ,  3653.83831186])

In [3]: import scipy

In [4]: scipy.__version__
Out[4]: '0.17.0.dev0+ea8d2d1'
```

In 0.16.0, we have:
```
In [1]: from scipy.special import kn, yn, jn

In [2]: kn([4, 5, 6], 1)
Out[2]: array([   44.23241425,   360.96060181,  3653.83837891], dtype=float32)

In [3]: import scipy

In [4]: scipy.__version__
Out[4]: '0.16.0'
```

(In both cases above, I used numpy 1.9.2.)

The docstrings of `yn` and `kn` should reflect the behavior in master.

**Comment by endolith** [comment]
Well, setting up the development version requires me to compile all the C and fortran etc?  Can you just run these in yours and I'll paste the output?

```
    >>> kvp(5, (1, 2, 3+5j))
    >>> kvp((4, 4.5, 5), 1)
    >>> kn([4, 5, 6], 1)
    >>> kv([4, 4.5, 5], 1+2j)
```

or any other values that you think would make better examples

Also note:

```
kv(3.5, -0.43062885+0j)
(-2.1565794684087855e-14+352.19489087271933j)

kv(3.5, -0.43062885)
nan
```

is this expected behavior?

**Comment by pv** [comment]
@endolith: the travis report says what the code actually output, so you
can probably copypaste from there. Returning `nan` instead of complex
result is expected, as the domain only depends on the type on the input
values, and not on the input values.

**Comment by endolith** [comment]
Ok I fixed those things.  I was also going to include the description from https://github.com/endolith/scipy/blob/master/scipy/special/cephes/kn.c#L21 in the Notes section, but is that definitely the source code for `kn()`?  It's hard for me to follow which C or F code goes with which Python function.

**Comment by rgommers** [comment]
This looks OK to me now. Note that the changes to ``add_newdocs.py`` aren't shown by Github under "Files changed" but actually do need review. See d887d8133f34d28f8. It looks reasonable to me but I don't know those functions well, so leaving that and the merge to @pv.

**Comment by pv** [comment]
Rebased and pushed in bcd0705e031

**Pull request closed without merging**
