### PR TITLE
Revert "ENH: add `order` parameter to specify quaternion format"

### PR DESCRIPTION
**Pull request by pmla**
Reverts scipy/scipy#15410

### CODE REVIEW

**Comment by tylerjereddy** [comment]
@pmla still working on it or did someone discover a bug?

**Comment by pmla** [comment]
No, I just wanted to give Nikolay the opportunity to take a look before merging. I created the PR on a Friday and it's only Monday now. [My comment](https://github.com/scipy/scipy/pull/15410#issuecomment-1013494119) must have been overlooked.

**Comment by tylerjereddy** [comment]
yeah sounds good

**Comment by tupui** [comment]
Yes I did not see this comment, apologies 🙇

**Pull request merged**
