### PR TITLE
BUG: stats.ttest_1samp: fix use of `keepdims`

### PR DESCRIPTION
**Pull request by sdiebolt**
#### Reference issue

Partially addresses gh-20725.

#### What does this implement/fix?

This PR fixes an error raised when using the `keepdims` argument of `scipy.stats.ttest_1samp`. The error comes from the `_axis_nan_policy_factory` decorator that tries to expand the dimensions of all returns from decorator functions. Some of the decorated functions return simple integers that cannot be expanded, thus the error:

https://github.com/scipy/scipy/blob/626bbd18e1cb45afa9648aa8e1eddbc68fa69d0d/scipy/stats/_axis_nan_policy.py#L240-L246

#### Additional information

`test_keepdims` originally raised an error when adding `stats.ttest_1samp` due to a division-by-zero warning. The error is due to some test cases where omitting NaNs leads to samples of size 1, thus the division-by-zero when computing the SEM. To fix this, I set the `too_small` argument to a callable that checks if the sample to test has at least size 2. I could not simply use `too_small=1` however, since it seems `popmean` is considered a sample (ie., `n_samples` is set to 2 in the decorator of `ttest_1samp`).

Adding all other functions from `axis_nan_policy_cases` raises many more errors that I'll try to check now.

### CODE REVIEW

**Comment by sdiebolt** [comment]
@mdhaber Ok so it seems most errors that occur when running `test_keepdims` on all `axis_nan_policy_cases` are due to small sample sizes (occurring for a number of reasons, from samples becoming too small after omitting NaNs, to samples being simply too small or having a degenerate dimension, e.g. with the case `sample_shape=(20, 0)`). What would you recommend? Should I try to modify `test_keepdims` parameters in this PR to fit `axis_nan_policy_cases`?

**Comment by mdhaber** [comment]
Maybe leave the existing test alone if it's that strict. Instead, add a new test like it that doesn't generate the problematic cases that are unrelated to the issue of non-expandable scalars. The inconsistent behavior w.r.t. small samples is being fixed separately; when that's resolved, we can probably combine the tests more easily.

**Comment by mdhaber** [comment]
This fixes a bug as-is, so I'd like this to make it into 1.14.0. 
We just did a major cleanup of warnings/errors for functions with sample sizes <= `too_small`. We need to do a follow-up of functions that need a different `too_small` than they have, so I don't want that to hold up or be touched in this issue. 
I'll leave gh-20725 open after this so we remember to add other functions to `test_keepdims` after fixing `too_small`.

**Review by mdhaber — APPROVED** [review]
If tests pass, I'll merge.
@tylerjereddy can we backport this fix into the next release candidate?

**Pull request merged**
