### PR TITLE
DOC: Example for integrate.romb

### PR DESCRIPTION
**Pull request by rafalalgo**
Reference to: https://github.com/scipy/scipy/issues/7168

### CODE REVIEW

**Comment by rafalalgo** [comment]
@person142  probably it can be merge

**Comment by ilayn** [comment]
Just for the future reference, please make separate branches to work on new features and to send PRs such that your standard working repo does not interfere with the PRs you have submitted. Once a PR is merged you can safely delete that branch and keep working on other branches.

**Comment by rafalalgo** [comment]
Ok @ilayn, thanks for advice!

**Comment by ilayn** [comment]
Rendered version https://5717-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.integrate.romb.html#scipy.integrate.romb

**Pull request merged**
