### PR TITLE
BUG: Correct handling of scalar 'b' in lsmr and lsqr

### PR DESCRIPTION
**Pull request by nmayorov**

### CODE REVIEW

**Comment by ev-br** [comment]
It seems to me that this PR tries to fix a corner case which did not work previously. 

On master:
```
In [31]: scipy.__version__
Out[31]: '0.17.0.dev0+9cb5bd2'

In [32]: A = np.array([[1.0, 2.0]])

In [33]: b = 3.0

In [34]: lsmr(A, b)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-576c216bc3e4> in <module>()
----> 1 lsmr(A, b)

/home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/lsmr.pyc in lsmr(A, b, damp, atol, btol, conlim, maxiter, show)
    137 
    138     A = aslinearoperator(A)
--> 139     b = b.squeeze()
    140 
    141     msg = ('The exact solution is  x = 0                              ',

AttributeError: 'float' object has no attribute 'squeeze'
```

with this PR:

```
In [3]: import numpy as np

In [4]: A = np.array([[1.0, 2.0]])

In [5]: b = 3.0

In [6]: from scipy.sparse.linalg import lsmr

In [7]: lsmr(A, b)
Out[7]: 
(array([ 0.6,  1.2]),
 1,
 1,
 0.0,
 0.0,
 2.23606797749979,
 1.0,
 1.3416407864998734)

In [8]: import scipy

In [9]: scipy.__version__
Out[9]: '0.17.0.dev0+622db1e'
```

@nmayorov some context would be helpful. My understanding is that this arised in gh-5044. While it seems easy to work around it in there, it seems to make sense to fix the problem at the source, and the change looks reasonable to me. 
OTOH, I'm not familiar with this code, so I'll defer merging this PR to someone who is. (or at the very least, I'd like to have a second set of eyes on this.)

**Comment by nmayorov** [comment]
To improve test coverage in gh-5044 I added a degenerate problem, where the matrix (Jacobian) had the shape (1, 2) and the dimension mismatch occurred after `b` was squeezed to 0-d array . Obviously the use case is very thin, but for correctness it should work with any dimensions.

**Comment by ewmoore** [comment]
I think that `lsqr` has a similar, but slightly different issue. 
```
In [1]: from scipy.sparse import linalg as sl

In [2]: A = np.array([[1.0, 2.0]])

In [3]: b = 3.0 

In [4]: sl.lsmr(A, b)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-cf1937e4be8a> in <module>()
----> 1 sl.lsmr(A, b)

C:\Anaconda\lib\site-packages\scipy\sparse\linalg\isolve\lsmr.pyc in lsmr(A, b, damp, atol, btol, conlim, maxiter, show)
    137 
    138     A = aslinearoperator(A)
--> 139     b = b.squeeze()
    140 
    141     msg = ('The exact solution is  x = 0                              ',

AttributeError: 'float' object has no attribute 'squeeze'

In [5]: sl.lsqr(A, b)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-18946f688504> in <module>()
----> 1 sl.lsqr(A, b)

C:\Anaconda\lib\site-packages\scipy\sparse\linalg\isolve\lsqr.pyc in lsqr(A, b, damp, atol, btol, conlim, iter_lim, show, calc_var)
    251     """
    252     A = aslinearoperator(A)
--> 253     if len(b.shape) > 1:
    254         b = b.squeeze()
    255 

AttributeError: 'float' object has no attribute 'shape'

```

But I've never used this part of scipy, and I'm not really sure about the differences between `lsqr` and `lsmr`.

Generally this `at_least_1d` dance is the right way to solve this problem.  Solutions using `np.isscalar` are too fragile.

**Comment by nmayorov** [comment]
I will fix it too.

**Comment by nmayorov** [comment]
I updated the commit. Now it addresses `lsqr` too.

**Comment by ev-br** [comment]
OK, no further comments for a week, two votes in favor --- merging. Thanks Nikolay, Eric.

**Pull request merged**
