### PR TITLE
MAINT: integrate: Avoid using variable `l` in quadrature, integrate._…

### LINKED ISSUE #8389: fix pep8/pycodestyle E741 do not use variables named ‘l’, ‘O’, or ‘I’
See discussion on #8384 - Running pycodestyle v2.3.1 currently reports 81 cases of ``E741`` which is one of a set of three style checks to avoid ambiguous single letter names which look like numbers:

* E741 do not use variables named ‘l’, ‘O’, or ‘I’
* E742 do not define classes named ‘l’, ‘O’, or ‘I’
* E743 do not define functions named ‘l’, ‘O’, or ‘I’

See https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes

The reasoning being in many fonts:

* Upper case eye looks like the digit one (``I`` vs ``1``)
* Upper case oh looks like the digit zero (``O`` vs ``0``)
* Upper case el looks like the digit one (``L`` vs ``1``)

Assuming #8384 or similar is merged, then as part of fixing this whitespace, the style checker settings in tox.ini should be updated to stop ignoring E741.

### PR DESCRIPTION
**Pull request by samyak0210**
…ivp: Avoid using variable `I` in bdf,io.matlab: Avoid using variable `O` in mio4

fixed https://github.com/scipy/scipy/issues/8389

### CODE REVIEW

**Comment by peterjc** [comment]
If you're going to the trouble of replacing the problematic single letters (which can look like numbers in some fonts), why not replace them with longer variables names rather than a different single letter?

**Comment by peterjc** [comment]
It is only Python 3.5 which failed on TravisCI, and it looks like white space and rounding issues only - my hunch would be NumPy 1.14 related. The logs are a little odd here:

```
$ travis_retry pip install $NUMPYSPEC
You must give at least one requirement to install (see "pip help install")
```

Later on we see:

```
Successfully uninstalled numpy-1.14.0
```

This would seem to be a wider issue and not specific to your changes.

**Comment by peterjc** [comment]
See #8279 for the NumPy 1.14 failure

**Comment by ilayn** [comment]
the integer is represented as MOPT where M is the thousands digit, O is the hundreds digit, P is the tens digit, and T is the ones digit. Here you are changing O to different chars but the error message shouldn't change. It's still the O of MOPT. 

I thought we were going to ignore this this PEP8 rule in one of those issues.

**Comment by person142** [comment]
Similarly the change from `I` to `K` for an identity matrix is a bad idea. Something like `id` should be ok.

**Comment by samyak0210** [comment]
@person142 can I give it a name then like identity or anything else??

**Comment by ev-br** [comment]
TBH, I don't believe that benefits here justify the code churn, and I think this PR should not be accepted.

**Comment by pv** [comment]
-0 from me on PRs fixing variable names etc. minor style issues

**Comment by peterjc** [comment]
If the SciPy team are on balance against these changes, should we close #8389 as a won't fix (and perhaps say so explicitly in the style checking configuration comments?)

**Comment by rgommers** [comment]
I agree with @ev-br and @pv, so I'm going to close this. Thank you nevertheless @samyak0210 for attempting to address an open issue.

> If the SciPy team are on balance against these changes, should we close #8389 as a won't fix (and perhaps say so explicitly in the style checking configuration comments?)

@peterjc good point. I'll comment on that issue.

**Pull request closed without merging**
