### PR TITLE
Attribute kurtosistest() to Anscombe & Glynn (1983)

### PR DESCRIPTION
**Pull request by mspacek**
It would be nice to be able to refer to this test by name when using it (such as when referring to it in a paper). From looking at the code, it seems to use the method of Anscombe & Glynn (1983):

http://biomet.oxfordjournals.org/content/70/1/227

See equations 2 through 5 in that paper.

Does anyone have any further insight? I tracked that reference down via the Wikipedia article on Agostino's K-squared test:

https://en.wikipedia.org/wiki/D%27Agostino%27s_K-squared_test

### CODE REVIEW

**Comment by argriffing** [comment]
@mspacek Thanks for adding this reference! Could you put it in a `References` section in the docstring like https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt? Also maybe add source code comments indicating which Python code corresponds to which equations 2 through 5.

**Comment by mspacek** [comment]
Sorry for the delay. OK, how's this? I did this all with the online GH editor. I haven't tested how the docstring actually renders.

**Comment by josef-pkt** [comment]
Sounds good to my.

I was a bit surprised about the reference. The distribution of the kurtosis seems to go back to the 1930s (E.S. Pearson and Fisher) but the approximation to the distribution looks like Anscombe and Glynn by comparing the formulas that @mspacek pointed out.
D'Agostino and Jarque-Bera use different approximations.

a bit more precise might be: "The pvalue is based on the approximation to the distribution of the kurtosis by Anscombe and Glynn ..."

**Comment by josef-pkt** [comment]
slightly confusing references:
normal test uses the test statistic from kurtosis test and skew test, but references are in the 1970's for the combination of the two tests not for the kurtosis transformation of the later Anscombe and Glynn,

AFAICS

**Comment by ev-br** [comment]
How about adding an *exempli gratia*,

`.. [1] see, e.g., F. J. Anscombe, W. J. Glynn, "Distribution...`

@mspacek would you also correct the pep8 violations (which is a trivial matter of adding some spaces before the inline comments)

**Pull request merged**
