### PR TITLE
sparse: enhancements for DIA format

### PR DESCRIPTION
**Pull request by perimosocordiae**
This is still a WIP, due to slower speeds on `tocsr()`:
_Updated timings as of 50dbbfa_

```
In [2]: A = scipy.sparse.rand(200,300,density=0.8,format='dia')

In [3]: %timeit A.tocoo().tocsc()
100 loops, best of 3: 5.78 ms per loop

In [4]: %timeit A.tocsc()
100 loops, best of 3: 3.33 ms per loop

In [5]: %timeit A.tocoo().tocsr()
100 loops, best of 3: 4.42 ms per loop

In [6]: %timeit A.tocsr()
100 loops, best of 3: 8.06 ms per loop
```

Both `tocsc()` and `tocsr()` look like they can be optimized further.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Bump? I rebased to collapse everything into two commits (one for `tocoo()`, one for `transpose()`).

**Comment by rgommers** [comment]
This PR looks quite clean. I marked it for 0.16.0 so it won't miss the next release; will leave it to someone else to merge though.

**Comment by rgommers** [comment]
@jakevdp @pv will one of you be able to merge this before the planned release split (Sunday)?

**Comment by jakevdp** [comment]
I just did a local build and checked that tests still passed (along with purposely breaking the code to see how many tests would catch it – I got 43 failures in this case)

Clean code, tests passing – I think this looks good. Thanks @perimosocordiae!

**Comment by rgommers** [comment]
Great, thanks @perimosocordiae @jakevdp.

**Pull request merged**
