### PR TITLE
BENCH: fix `cython_special` benchmarks

### PR DESCRIPTION
**Pull request by person142**
Now they won't crash if `cython_special` does not exist. Closes
gh-6478.

### CODE REVIEW

**Comment by pv** [comment]
The whole metaclass mess I added probably can also be thrown out:
```
class CythonSpecial(object):
     params = [sorted(FUNC_ARGS.items()),
               (10, 100, 1000),
               ('python', 'numpy', 'cython')]
     param_names = ['name_args', 'N', 'api']

     def setup(self, name_args, N, api):
         name, args = name_args
         ...

     def time_func(self, name_args, N, api):
         if api == 'python':
             self.py_func(N, *args)
         elif api == 'numpy':
             self.np_func(*self.obj)
         else:
             self.cy_func(N, *args)
```

**Comment by pv** [comment]
Or even simpler,
```
     params = [sorted(FUNC_ARGS.keys()),
               (10, 100, 1000),
               ('python', 'numpy', 'cython')]
     param_names = ['name', 'N', 'api']

     def setup(self, name, N, api):
         args = FUNC_ARGS[name]
         ...
```

**Comment by person142** [comment]
Removing the metaclass has the disadvantage of not being able to test one function at a time, no? It also makes the tables asv outputs less pretty.

**Comment by pv** [comment]
merged, I'll avoid the bikeshed

**Pull request merged**
