### PR TITLE
Update decomp_cholesky.py

### PR DESCRIPTION
**Pull request by tuxcell**
#### Fixing the get_lapack_funcs bottleneck when calling cholesky()

Calling the cholesky method in a loop is slow because of multiple calls to get_lapack_funcs. By passing the lapack function as a parameter, we fix that problem, while keeping the method backwards-compatible and even allowing the use of custom lapack calls, such as Cython or GPU based, etc.

### CODE REVIEW

**Comment by pv** [comment]
The right solution is probably that, instead of adding this keyword argument, you call potrf directly in your own code.

**Comment by tuxcell** [comment]
> The right solution is probably that, instead of adding this keyword argument, you call potrf directly in your own code --- or find a way to speed up the `get_lapack_funcs` call for potrf.

The advantage of using this argument is that it is optional, therefore it does not break existing code that uses 'cholesky', no need to reinvent the wheel. By using this argument one can call 'get_lapack_funcs' once and then pass it as an argument to 'cholesky'. What is the sense of speeding up 'get_lapack_funcs' and then call it a million times inside a loop? When this idea is that 'get_lapack_funcs' is called once and then its reference is used a million times inside a loop. Look at the example, it does this.

**Comment by pv** [comment]
It's a marginally useful complication in the API, and inconsistent since none of the other functions have it. Moreover, for several functions this type of stuff becomes complicated. So -1 from me.

You can get even more speed by using potrf directly, so why not use it directly if that's a bottleneck for you?

**Comment by tuxcell** [comment]
> It's a marginally useful complication in the API, and inconsistent since none of the other functions have it. Moreover, for several functions this type of stuff becomes complicated. So -1 from me. There's room to speed up `get_lapack_funcs` significantly.
> 
> You can get even more speed by using potrf directly, so why not use it directly if that's a bottleneck for you?



> It's a marginally useful complication in the API, and inconsistent since none of the other functions have it. Moreover, for several functions this type of stuff becomes complicated. So -1 from me. There's room to speed up `get_lapack_funcs` significantly.
> 
> You can get even more speed by using potrf directly, so why not use it directly if that's a bottleneck for you?

IMHO, 'cholesky' is a special method that could be more flexible than most others and be a bit different in any ways that make it more useful. I see no inconsistency in having an optional parameter that can be ignored with no side effects.
Sure, we can call lapack and use our own code but then we're avoiding the API. An API is about reusing instead of redoing.
This idea seems good to me because I use 'cholesky' inside big loops but maybe other people use other methods and might find this to be useful to those methods. The API should follow people's needs and evolve accordingly.

**Comment by ewmoore** [comment]
This is also -1 from me.  

I suspect that you are calling `cholesky` on rather small arrays.  In this case, nothing you can do will get the overhead down as much as just calling `potrf` directly.  For instance, here are some timings: 
Figure_1

For matices less than 500 x 500, calling `potrf` handily wins.  At that size and up it is a bit of wash.

**Comment by rgommers** [comment]
agreed, this isn't an API change we can accept. so closing. thanks for your contribution though @tuxcell!

**Pull request closed without merging**
