### PR TITLE
ENH: improve docstring of weibull_min_gen and weibull_max_gen to fix #10014

### LINKED ISSUE #10014: Distribution names `weibull_min`and `weibull_max` should be explained
No error, I just noted that `weibull_min` is usually called Weibull distribution and it arises as the limiting distribution of the rescaled minimum of iid random variables (https://en.wikipedia.org/wiki/Fisher–Tippett–Gnedenko_theorem)

`weibull_max` is just the distribution of -X if X is `weibull_min`, and therefore, the limiting distribution of the rescaled maximum of iid random variables. (so if negative scale parameters  were possible, one could go from one distribution to the other with `scale = -1`)

I think it would be nice to explain this in the docstring since the distribution names are not standard.

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
To fix #10014

#### What does this implement/fix?
improve docstring of weibull_min_gen and weibull_max_gen based on discussion in #10014 and #10053

#### Additional information
PR #10053 is no longer active, so I create this PR based on the discussion in #10053.

### CODE REVIEW

**Comment by chrisb83** [comment]
Hi,

thanks for submitting this PR. Could you also add a reference to the Fisher-Gnedenko theorem for both distributions? 

For weibull_min, could you change :math:`x >= 0` to :math:`x > 0` (this is unrelated to your changes). 

Overall, I think one could write a bit more about this topic but a short update is already an improvement.

**Comment by AtsushiSakai** [comment]
Hi. Thank you reviewing. I fixed it based on you review. Please take a look.

**Comment by AtsushiSakai** [comment]
I fixed docstring based on your comment.

**Comment by chrisb83** [comment]
Thanks, I will merge it.

**Pull request merged**
