### PR TITLE
CI: update `SCIPY_NIGHTLY_UPLOAD_TOKEN` on CirrusCI.

### LINKED ISSUE #18656: CI: cirrus wheels not being uploaded
### Describe your issue.

@rgommers, the cirrus ci wheels still aren't being uploaded to nightly. See https://cirrus-ci.com/task/4508001206272000. The upload step got a little bit further but errored out.

### Reproducing Code Example

```python
Na
```

### Error message

```shell
IS_SCHEDULE_DISPATCH is true
scheduled or dispatched event
/tmp/cirrus-ci-build
./wheelhouse/scipy-1.12.0.dev0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
./wheelhouse/scipy-1.12.0.dev0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
./wheelhouse/scipy-1.12.0.dev0-cp311-cp311-macosx_12_0_arm64.whl
./wheelhouse/scipy-1.12.0.dev0-cp39-cp39-macosx_12_0_arm64.whl
./wheelhouse/scipy-1.12.0.dev0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
./wheelhouse/scipy-1.12.0.dev0-cp310-cp310-macosx_12_0_arm64.whl
Found wheel
Using Anaconda API: https://api.anaconda.org
Using "scientific-python-nightly-wheels" as upload username
Processing './wheelhouse/scipy-1.12.0.dev0-cp310-cp310-macosx_12_0_arm64.whl'
Detecting file type...
File type is "Standard Python"
Extracting standard python attributes for upload
Creating package "scipy"
Creating release "1.12.0.dev0"
Uploading file "scientific-python-nightly-wheels/scipy/1.12.0.dev0/scipy-1.12.0.dev0-cp310-cp310-macosx_12_0_arm64.whl"
[ERROR] ('"scipy" could not be found',
```

### SciPy/NumPy/Python version and system information

```shell
Na
```

### PR DESCRIPTION
**Pull request by tupui**
Closes #18656

Update the token using my personal token as per the new requirements of SPEC4.

I went into the settings section of SciPy on CirrusCI and under `Secured Variables` I put the token and got back the encrypted string.

--- 
@rgommers @andyfaff as you set this up, could you check the security settings of CirrusCI? To me it seems that we should enable `Require approval for builds from users without write permissions`.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks for taking care of this @tupui.

Re _Require approval for builds from users without write permissions_: I haven't seen that before, I suspect it did not exist yet when we started using Cirrus CI - and I still don't see it mentioned in the docs. It doesn't sound quite right to me - I think we'd like the exact same thing as GitHub Actions does, where it runs for contributors who have at least one PR merged. If it never runs for any non-maintainers, that will be too annoying.

**Comment by tupui** [comment]
ah ok, I will do that to check then. I thought there was a manual trigger possible, like for GitHub actions with the manual dispatching.

**Comment by andyfaff** [comment]
ATM the upload script wouldn't run with a manual trigger.

**Comment by charris** [comment]
ISTR that you need to allow manual triggers in the yml file. I can't manually run numpy builds on cirrus, but can rerun existing builds.

**Comment by tupui** [comment]
Well nothing happened 😅 https://cirrus-ci.com/build/5939126856318976

**Comment by andyfaff** [comment]
The cron job needs to be called nightly

**Comment by tupui** [comment]
I am also seeing that apparently we do a full git clone instead of fetching only the last commit? Is there a reason for that or can we change this? It's taking like 40s to do the clone.

**Comment by andyfaff** [comment]
We don't clone in the wheel build script. The clone occurs in general ci. The reason there's git ops is because default cirrus runs against the PR branch, not against the PR merged into main/maintenance.
I believe that a non shallow clone is required for PRs because the merge can be made to main or maintenance branches.

**Comment by tupui** [comment]
Yay, the token is working and we got new wheels up there. (And also the readme did not get messed up again with the update, so my manual edit stayed.)

**Pull request merged**
