### PR TITLE
DOC: optimize: make `lsq_linear` example smaller

### PR DESCRIPTION
**Pull request by ev-br**
Before the change, CircleCI periodically times out (in https://github.com/scipy/scipy/pull/21437), and

```
$ python smoke-docs -s optimize --durations 10
...
10.23s call     build-install/lib/python3.12/site-packages/scipy/optimize/__init__.py::scipy.optimize.lsq_linear
4.46s call     build-install/lib/python3.12/site-packages/scipy/optimize/__init__.py::scipy.optimize.differential_evolution
1.35s call     build-install/lib/python3.12/site-packages/scipy/optimize/__init__.py::scipy.optimize.least_squares
0.87s call     build-install/lib/python3.12/site-packages/scipy/optimize/__init__.py::scipy.optimize.dual_annealing
```

### CODE REVIEW

**Comment by ev-br** [comment]
One other outlier is `stats.multiscale_graphcorr`:

```
$ python dev.py smoke-docs -s stats --durations 10

....

===================================================================== slowest 10 durations =====================================================================
23.01s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.multiscale_graphcorr
3.04s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.recipinvgauss
2.28s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.studentized_range
2.06s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.gausshyper
1.86s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.rel_breitwigner
1.84s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.foldcauchy
1.80s call     build-install/lib/python3.12/site-packages/scipy/stats/sampling.py::scipy.stats.sampling.NumericalInverseHermite
1.70s call     build-install/lib/python3.12/site-packages/scipy/stats/sampling.py::scipy.stats.sampling.NumericalInversePolynomial
1.47s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.kappa4
1.40s call     build-install/lib/python3.12/site-packages/scipy/stats/__init__.py::scipy.stats.goodness_of_fit
```

**Review by lucascolley — APPROVED** [review]
ready to go in or would you like to change the stats one here too?

**Comment by ev-br** [comment]
Not really. The stats one deserves a look from a subject matter expert IMO, I'm not comfortable assessing if the sample sizes can just change or a more invasive change is needed to keep the example sensible.

**Comment by ev-br** [comment]
Uhm, sorry, to clarify: I think the `multiscale_graphcorr` could/should be looked at by a subject matter expert, so there's no need to lump it together with `lsq_linear` of this PR. So this PR is ready to go in, IMO.

**Comment by WarrenWeckesser** [comment]
Thanks, the change makes sense.

The example output should be updated to reflect the change in size.  It looks like this causes the typical number of iterations to be lower, and the typical costs differ by an order of magnitude compared to the larger case.  The numbers will vary, but they should probably continue to reflect a "typical" result from the input sizes used in the example.

**Comment by ev-br** [comment]
Thanks for the catch Warren. Updated to match the return message locally.

**Comment by WarrenWeckesser** [comment]
I don't recall the scope of `# may vary`.  It looks like the occurrence of `# may vary` in an output section applies to all lines in that output, and not just the one line where is occurs.  Is that correct?

**Comment by ev-br** [comment]
Yes, `# may vary` should apply to the whole output, multiline or not. Dropping a breakpoint at https://github.com/scipy/scipy_doctest/blob/main/scipy_doctest/impl.py#L285 gives:


```
(Pdb) p want
'# may vary\nThe relative change of the cost function is less than `tol`.\nNumber of iterations 16, initial cost 1.5039e+04, final cost 1.1112e+04,\nfirst-order optimality 4.66e-08.\n'
(Pdb) p got
'The relative change of the cost function is less than `tol`.\nNumber of iterations 16, initial cost 1.4910e+04, final cost 1.1015e+04, first-order optimality 6.95e-08.\n'
```

(this is on main not this PR for a random reason)

**Comment by lucascolley** [comment]
thanks both!

**Pull request merged**
