### PR TITLE
MAINT: integrate: Clean the C code behind odeint.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Argh... I just noticed a mistake in the last commit message.  It should be `_odepackmodule.c`, not `_quadpackmodeul.c`.  I'll fix that before this gets merged.

**Comment by rgommers** [comment]
You mean you just want to fix the commit message?

**Comment by WarrenWeckesser** [comment]
>  You mean you just want to fix the commit message?

Yes, just the commit message.

**Comment by WarrenWeckesser** [comment]
In fact, I'll do that right now...

**Comment by WarrenWeckesser** [comment]
The commit message is fixed.

**Comment by rgommers** [comment]
You tested with numpy 1.10 master I assume, to check the no-deprecations is OK? that's not added in Travis config yet.

**Comment by WarrenWeckesser** [comment]
Yes, and I just rebuilt and tested it again with numpy 1.10.0.dev0+a866fdd, and all is well.  I didn't get any numpy API warnings for the odepack module, and the `integrate` tests all pass.

**Comment by rgommers** [comment]
LGTM, in it goes. Thanks Warren.

**Pull request merged**
