### PR TITLE
DOC: differential_evolution, improve docstring for mutation and recom…

### PR DESCRIPTION
**Pull request by andyfaff**
This PR improves the docstring for the `mutation` and `recombination` constants, in response to comments in #5101.

@Hvass-Labs, @dlax

### CODE REVIEW

**Comment by pavelponomarev** [comment]
Hello,

Why is there a separate class for the solver? Does anybody use this separate solver functionality? Would it be better to unwrap the solver functionality out from that class? It will remove necessity to maintain practically the same documentation in two different places.

**Comment by andyfaff** [comment]
It's probably better to start an unrelated (to this PR) change on the scipy-dev mailing list. It'll reach more people.
To answer your question, yes there are places where I use the class directly, and there are places I call the function. A few of the reasons for having the class are as follows:
* one can call the solve method repeatedly.  For example, you can set `maxiter` to 1, and evolve the population once (a single generation). After inspecting the result you can call `solve` again, *without* the population being reinitialised.
* the differential_evolution function only returns an `OptimizeResult`, but what if you want to access the the population energies, or the population itself? Or perhaps you would like to evolve for a certain number of generations then change the mutation strategy, without reinitialising the population? You can do those with a class based solver.
* All the class the class methods need access to instance attributes (encapsulation). For example all the methods that mutate (e.g. `_best1`, etc) need access to the population of candidates and the mutation constant (F).  If they weren't methods, but static functions, then all the functions would have to have more parameters.

It might be possible to change the code to have a dynamically created docstring for the `DifferentialEvolutionSolver` and the `differential_evolution` function.  This docstring could use a similar text origin, meaning that only one source has to be maintained.

**Comment by pavelponomarev** [comment]
OK, I see now. But this functionality you mentioned is not documented. This requires some internal knowledge how everything works.
How about to make this class private (with docstring mentioning that the parameters are all the same as of the module) and provide public methods to access the population and energies of every step (e.g. within the callback function). Additionally, the seeding can be made possible from a saved population.
This way, it seems for me, it will be more natural to perform all those operations (which now require internal knowledge of the module) using only public documented methods. And maintenance of the documentation will be eased.

**Comment by rgommers** [comment]
This looks clear to me.

**Comment by rgommers** [comment]
The discussion on code structure is unrelated to this PR, which is a clear improvement, so merging. Thanks @andyfaff

**Pull request merged**
