### PR TITLE
MAINT: spatial: use cython_lapack in spatial/_qhull.pyx

### PR DESCRIPTION
**Pull request by ev-br**
Use `linalg.cython_lapack` in `_qhull.pyx` instead of manual LAPACK wrappers (the qhull usage likely predates cython_lapack).

Just a small drive-by cleanup while looking at https://github.com/scipy/scipy/issues/20271

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
The diff seems sensible and passed full suite locally with my setup as well.

I did notice I could make this cleanup on this branch now, with full suite still passing locally, any reason not do do that:

```diff
--- a/scipy/spatial/meson.build
+++ b/scipy/spatial/meson.build
@@ -40,7 +40,7 @@ py3.extension_module('_qhull',
     'qhull_src/src'
   ],
   link_args: version_link_args,
-  dependencies: [lapack, np_dep],
+  dependencies: [np_dep],
   install: true,
   subdir: 'scipy/spatial'
 )
```

**Comment by ev-br** [comment]
Indeed. Added your patch to the PR.

**Comment by h-vetinari** [comment]
Do you think this would help with https://github.com/scipy/scipy/issues/20271, even if it's just about easier debugging? If so, should we still backport this to 1.13?

**Comment by ev-br** [comment]
That's clutching at straws basically: if we're in luck, the issue was in the manual lapack wrappers, as unlikely as it is. The alternative is rather bleak, it'd likely mean the issue is in vendored qhull code. A stack trace would be really helpful.

**Comment by h-vetinari** [comment]
> A stack trace would be really helpful.

Yeah, I know. I'll try to look into it when I'm back at my laptop in about a week.

**Pull request merged**
