### PR TITLE
DEV,BLD: Use Meson in Gitpod builds

### LINKED ISSUE #16065: BUG: Gitpod build with `python runtests.py` fails; move to meson on gitpod
### Describe your issue.

The current configuration of gitpod for the SciPy repo involves creating the `scipy-dev` environment and building through `python setup.py build_ext --inplace`. However, running `python runtests.py` with this setup results in test errors. 

On the other hand, creating the `scipy-meson` environment and running `python dev.py` works well. My suggestion is to move to meson on gitpod. This would also help with consistency, since our developer quickstart now recommends meson.

### Reproducing Code Example

```python
Open gitpod on scipy repo, and do `python runtests.py` in the terminal.
```

### Error message

```shell
Building, see build.log...
    ... build in progress (0:01:00.073483 elapsed)
Build OK (0:01:51.134909 elapsed)
Running tests for scipy version:1.9.0.dev0+1937.7043404, installed at:/workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.1, pluggy-1.0.0
rootdir: /workspace/scipy, configfile: pytest.ini
plugins: cov-3.0.0, forked-1.4.0, xdist-2.5.0
collected 122 items / 263 errors / 2 deselected / 120 selected

==================================== ERRORS ====================================
_ ERROR collecting build/testenv/lib/python3.10/site-packages/scipy/cluster/tests/test_disjoint_set.py _
ImportError while importing test module '/workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/cluster/tests/test_disjoint_set.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/envs/scipy-dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:25: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:105: in <module>
    from ._kdtree import *
scipy/spatial/_kdtree.py:5: in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
E   ImportError: /workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/spatial/_ckdtree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNSt11logic_errorC1EPKc
_ ERROR collecting build/testenv/lib/python3.10/site-packages/scipy/cluster/tests/test_hierarchy.py _
ImportError while importing test module '/workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/cluster/tests/test_hierarchy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/envs/scipy-dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:25: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:105: in <module>
    from ._kdtree import *
scipy/spatial/_kdtree.py:5: in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
E   ImportError: /workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/spatial/_ckdtree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNSt11logic_errorC1EPKc
_ ERROR collecting build/testenv/lib/python3.10/site-packages/scipy/cluster/tests/test_vq.py _
ImportError while importing test module '/workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/cluster/tests/test_vq.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/envs/scipy-dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/cluster/__init__.py:25: in <module>
    from . import vq, hierarchy
scipy/cluster/vq.py:72: in <module>
    from scipy.spatial.distance import cdist
scipy/spatial/__init__.py:105: in <module>
    from ._kdtree import *
scipy/spatial/_kdtree.py:5: in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
E   ImportError: /workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/spatial/_ckdtree.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNSt11logic_errorC1EPKc
_ ERROR collecting build/testenv/lib/python3.10/site-packages/scipy/fft/_pocketfft/tests/test_basic.py _
ImportError while importing test module '/workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/fft/_pocketfft/tests/test_basic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/conda/envs/scipy-dev/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/fft/__init__.py:85: in <module>
    from ._basic import (
scipy/fft/_basic.py:1: in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
scipy/_lib/uarray.py:28: in <module>
    from ._uarray import *
scipy/_lib/_uarray/__init__.py:115: in <module>
    from ._backend import *
scipy/_lib/_uarray/_backend.py:5: in <module>
    from . import _uarray
E   ImportError: /workspace/scipy/build/testenv/lib/python3.10/site-packages/scipy/_lib/_uarray/_uarray.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNSt16invalid_argumentD1Ev

<snip>
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1937.7043404 1.22.3 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by trallard**
- DEV: Remove multiple images
- BUG: Fix bashrc
- BUG: Fix bashrc
- DOC: Update gitpod docs
- DEV: Update conda dev in gitpod settings
- DEV: Remove multiple images
- BUG: Fix bashrc
- BUG: Fix bashrc
- DOC: Update gitpod docs
- DEV: Add Meson Dockerfile again
- ENH: Do not split run commands
- Final edits

#### Reference issue

Replaces #16066
Closes https://github.com/scipy/scipy/issues/16065

#### What does this implement/fix?

- Uses Meson to build SciPy and docs in Gitpod
- Fixes issued with rst rendering from recent updates to the extensions
- Updates to the Gitpod dev docs (link to Meson)

#### Additional information

- Docker images have been built and tested locally then pushed to DockerHub (so even if the action workflow fails Gitpod will pull the right image for now) 🩹 
- Prebuilt works (ran on my GitHub project and inspected the logs)
- Will need some cleanup later on 🧹  

Also it all seems to work as expected as I did most of this in Gitpod instead of my local env

### CODE REVIEW

**Comment by trallard** [comment]
cc/ @melissawm  since the previous one was reverted - this should be merged before the Sprints 😶‍🌫️

**Review by melissawm — APPROVED** [review]
Thanks you @trallard -this looks good to me! Let's wait for a maintainer to merge 😊

**Comment by melissawm** [comment]
@tupui @tylerjereddy can either of you take a look and merge if you think this is OK? Ideally we would like to get this in for today's mentored sprint at PyCon. Thanks!

**Review by tylerjereddy — COMMENTED** [review]
I took a quick lock and made sure the CI failures were not related.

If it helps us during the sprint later it probably makes sense to merge and follow-up with adjustments later, since it seems primarily confined to the Docker/Gitpod stuff.

**Comment by tylerjereddy** [comment]
I see the separate commits are well-written, but perhaps in this case I'll make the call to squash merge since I'm not quite sure we need all 15 commits to be separate in this particular case (mostly thematically-related changes to the Docker/Gitpod stuff).

**Comment by tylerjereddy** [comment]
thanks

**Comment by trallard** [comment]
Thanks @melissawm and @tylerjereddy - I made sure that even if the CI fails the Gitpod instances will work. 

There are some cleaning bits that Ralf and I discussed but those can be done later with more time. Lmk if there is anything I can help with in the meantime

**Pull request merged**
