### PR TITLE
BUG: linalg: Fix the XSLOW test test_sgesdd_lwork_bug_workaround()

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Edit: see the discussion below for the summary of the change.

<strike>The test would call `p.terminate()` on the subprocess, but apparently
the subprocess wouldn't actually be terminated by the time the test
function exited, and pytest didn't like this.  By calling `p.wait(10)`,
we give Python up to 10 seconds to actually terminate the subprocess.

Also, close `p.stdout` before leaving the test function.  Without this
change, pytest reports the error:

    E   ResourceWarning: unclosed file <_io.BufferedReader name=11>
</strike>

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
I confirmed locally that this fails on `main` and passes with this branch:

`SCIPY_XSLOW=1 python dev.py test -j 10 -m full -t scipy/linalg/tests/test_lapack.py`

Maybe I'll let a `linalg` resident double check, but changes seem reasonable to a non-expert, or at least as reasonable as you can be given a test that kind of "waits" for something to happen.

**Comment by WarrenWeckesser** [comment]
@tylerjereddy, what platform did you use?  Locally I've checked that it works on a Linux workstation and an old (Intel) Macbook.

Can anyone run this XSLOW test on a Windows machine and an M1/M2 Apple machine?

**Comment by tylerjereddy** [comment]
Linux x86_64

**Comment by andyfaff** [comment]
On main I get the error:
```
 ignored in: <_io.FileIO name=13 mode='rb' closefd=True>
Traceback (most recent call last):
  File "/Users/andrew/miniconda3/envs/dev3/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 59, in __exit__
    del self.unraisable
ResourceWarning: unclosed file <_io.BufferedReader name=13>
```

on the `fix-lapack-xslow-test` branch the test line passes.

Mac M1, macOS 12.5.1

**Comment by ilayn** [comment]
The problem this test was addressing is no more because we updated our LAPACK version way past 3.2.2. And thus we can remove the whole test to shave off some time and future headache (#5401).

**Comment by WarrenWeckesser** [comment]
Thanks @ilayn.  I see a bug fix reported for reference LAPACK 3.6.0:

* https://netlib.org/lapack/errata_from_350_to_360.html#_strong_span_class_green_bug120_span_strong_workspace_query_return_too_small_value_for_xgesdd

And another fix in 3.6.1 that might be related:

* https://netlib.org/lapack/errata_from_360_to_361.html#_strong_span_class_green_bug_157_span_strong_gesdd_gesvd_and_bdsdc_workspace_computation

But it looks like the general problem in LAPACK of using single precision floats for workspace computations (as [explained by @pv in 2015](https://github.com/scipy/scipy/issues/5401#issuecomment-149982319) in the case of sgesdd)  is still an open issue:

* https://github.com/Reference-LAPACK/lapack/issues/600

**Comment by ilayn** [comment]
Yes that's basically the case for quite a while now hence compute_lwork is working as intended. I don't think anything grants a 10 second waiting test for it.

**Comment by WarrenWeckesser** [comment]
I experimented a bit with code related to this issue.  I started with a plain Fortran program to call `sgesdd` directly:

*sgesdd_example.f03*

```
!
! This is not a complete example of sgesdd.
! It only executes a call with lwork = -1 and prints
! the value returned in work(1).
!

program sgesdd_example

    implicit none
    external sgesdd

    integer, parameter :: n = 9537
    real, dimension(n, n) :: a
    real, dimension(n) :: s
    real, dimension(n, n) :: u
    real, dimension(n, n) :: vt
    real, dimension(1) :: work
    integer lwork
    integer, dimension(8*n) :: iwork
    integer info

    lwork = -1
    call sgesdd('A', n, n, a, n, s, u, n, vt, n, work, lwork, iwork, info)

    print *, info
    print *, work(1)

end program sgesdd_example

```
As discussed over in https://github.com/scipy/scipy/issues/5401#issuecomment-149982319, the return value 272929856 is incorrect (too small).  The corrected LAPACK code returns 272929888, and this is also the value returned by our work-around in `_compute_lwork`.  I ran this program with recent versions of Netlib reference LAPACK.  It turns out this was not fixed until LAPACK 3.10.1 (see https://github.com/Reference-LAPACK/lapack/pull/605).  So previous comments that *LAPACK* was fixed in much earlier versions are not correct.  OpenBLAS did not update to LAPACK 3.10.1 until version 0.3.21, so older version of OpenBLAS will also return the incorrect result.

This just means we can't completely remove the `_compute_lwork` work-around until LAPACK 3.10.1 is the minimum required LAPACK version.  That is not a problem--the work-around appears to be working fine.

That's just background information.  This pull request is about fixing a test of the work-around.  The test is somewhat awkward and indirect.  The test passes if a subprocess that runs `svd` for a big array doesn't crash Python within 5 seconds of being run.  Currently, this pull request doesn't make any major changes to what the test does; it just tweaks the test to make `pytest` happy that the subprocess has been cleaned up by the time the test function exits.

Instead of this slow and indirect test, I think we should use a more direct test of the issue: call `sgesdd_lwork` and `_compute_lwork` with inputs that correspond to the array with shape (9537, 9537), and verify that the result is 272929888.  I realize that the exact value is an implementation detail, and it is possible that a future version of LAPACK might change how `sgesdd` is implemented and therefore return a different `lwork` size.  If that happens, it will be easy enough to make the expected value depend on the LAPACK version.

Because the new test will only call the `sgesdd_lwork` and `_compute_lwork`, it won't need to actually allocate the large array that is used in the current test, so it will not need to be marked `xslow`. 

@ilayn, what do you think?  Specifically, I propose to remove the test `test_sgesdd_lwork_bug_workaround()` and add a new test as described above.

**Comment by ilayn** [comment]
Sounds like the sensible thing to do indeed. +1 from me.

**Comment by WarrenWeckesser** [comment]
@ilayn, I pushed a new version of the pull request with a simplified test.

As the comment in the test explains, the test accepts two values for the corrected `lwork`.  Currently, `_compute_lwork()` always applies the correction to the value returned by the underlying Fortran function, even if we are using a version of LAPACK that doesn't have the bug.  I didn't see an obvious method for determining which version of LAPACK is in use, so the test accepts either value.

**Comment by ilayn** [comment]
>  I didn't see an obvious method for determining which version of LAPACK is in use, so the test accepts either value.

That's always tricky anyways but `linalg.lapack.ilaver` typically used for version information. However OpenBLAS includes heterogeneous fixes from different versions thus we better don't trust that value. I don't think it is a big deal. Hence up to you as you see fit. But this can go in already in this state.

**Comment by WarrenWeckesser** [comment]
Thanks @ilayn.  In that case, I think this can be merged as it is.

**Comment by ilayn** [comment]
Thanks for the fix @WarrenWeckesser !

**Comment by tylerjereddy** [comment]
I checked that the commit can be cleanly backported so I'll add the label given this was considered a bug. Hopefully there are no linear algebra backend version mismatches between the branches that would cause issues.

**Pull request merged**
