### PR TITLE
DEP: signal: remove `cmplx_sort`

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

follow up to https://github.com/scipy/scipy/pull/18587
#### What does this implement/fix?

scheduled to be removed in this release

### CODE REVIEW

**Comment by h-vetinari** [comment]
Doc error looks relevant:
```
/home/circleci/repo/build-install/lib/python3.11/site-packages/scipy/signal/__init__.py:docstring of scipy.signal:118: WARNING: autosummary: failed to import cmplx_sort.
```

**Comment by j-bowhay** [comment]
Oops forgot to stage one of the files, hopefully this comes back green

**Review by h-vetinari — APPROVED** [review]
👍

**Comment by lucascolley** [comment]
thanks both!

**Pull request merged**
