### PR TITLE
MAINT: 1.8.0rc2 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
- backport every merged PR with a backport candidate label and update the release notes accordingly
- remaining issues:
  - two open PRs in main repo with backport labels:
    - https://github.com/scipy/scipy/pull/15235
    - https://github.com/scipy/scipy/pull/15215
  - we need to pick one of two proposed fixes for: https://github.com/MacPython/scipy-wheels/issues/155
    - https://github.com/MacPython/scipy-wheels/pull/156
    - https://github.com/MacPython/scipy-wheels/pull/157
  - do we need to delay rc2 for conda-forge/linalg backend segfaults, or proceed and likely do rc3 as well?:
    - https://github.com/conda-forge/scipy-feedstock/pull/198#issuecomment-997298099

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
The one CI failure in the pre-release job on this:
```
TypeError: __init__() got multiple values for argument 'reason' - maybe you meant pytest.mark.skipif?
```
looks relevant. For the rest it LGTM.

**Comment by WarrenWeckesser** [comment]
It looks like https://github.com/scipy/scipy/pull/15181 should be backported, too.

**Comment by tylerjereddy** [comment]
Ok, I cherry-picked from Warren's PR---if the CI passes this time, apart from timeouts, I will likely merge and consider doing rc2 pretty soon.

An rc3 looks unfortunately rather likely at the moment because of the segfault stuff on conda-forge, but we already have quite a few fixes for rc2.

**Comment by andyfaff** [comment]
On holiday, so won't be able to review this.

**Comment by tylerjereddy** [comment]
> On holiday, so won't be able to review this.

ah yeah, it is just github automatically pinging you for code review as a code owner, not me being inpolite during Holiday time, to be clear :)

**Comment by tylerjereddy** [comment]
The only remaining CI issues are the usual timeouts, so in it goes.

**Comment by tylerjereddy** [comment]
backport labels for PRs included here have been removed so we have a cleaner slate for additional backports

**Pull request merged**
