### PR TITLE
fixed a bug in kde logpdf

### PR DESCRIPTION
**Pull request by h3jia**
There shouldn't be index i in line 612 of `kde.py`.

### CODE REVIEW

**Comment by rgommers** [comment]
@HerculesJack can you please give an explanation of what the issue is exactly, and a self-contained example that demonstrates that there is a bug?

**Comment by HerculesJack** [comment]
> @HerculesJack can you please give an explanation of what the issue is exactly, and a self-contained example that demonstrates that there is a bug?

Sure, I just fixed a bug in my previous commit. Here's an example to demonstrate the bug:
```
import numpy as np
from scipy.stats.kde import gaussian_kde as kde
kk = kde(np.array([[0.,1.,1.],[0.,1.,-1.]]), bw_method=1., weights=np.array([2,1,1]))
print(kk.logpdf(np.array([[-2.,-1.,0.,1.,2.],[-2.,-1.,0.,1.,2.]])))
print(np.log(kk.pdf(np.array([[-2.,-1.,0.,1.,2.],[-2.,-1.,0.,1.,2.]]))))
```
And the output is:
```
[-10.14186096  -4.48300639  -2.38694181  -2.44302713  -4.51916291]
[-9.45499062 -3.81281351 -1.81863205 -2.32601787 -4.51559963]
```
But they should be same. The problem is lines 604-613 of `kde.py`:
```
if m >= self.n:
    # there are more points than data, so loop over data
    energy = zeros((self.n, m), dtype=float)
    for i in range(self.n):
        diff = self.dataset[:, i, newaxis] - points
        tdiff = dot(self.inv_cov, diff)
        energy[i] = sum(diff*tdiff, axis=0) / 2.0
    result = logsumexp(-energy,
                       b=self.weights[i]*self.n/self._norm_factor,
                       axis=0)
```
Notice that in the second to last line, it uses the index `i` in the previous for-loop, which should be a bug. Here `energy` has shape (n, m), `self.weights` has shape (n,), so it's actually using `self.weights[-1]` for all the mixture components.

**Comment by HerculesJack** [comment]
Also I modified the definition of `self._norm_factor`. Currently it's defined to be multiplied by `self.n`, but then is always divided by it again.

**Comment by rgommers** [comment]
Ah yes, that's clear, thanks. Could you add your example as a test to `scipy/stats/tests/test_kdeoth.py`?

**Comment by rgommers** [comment]
> Also I modified the definition of self._norm_factor. Currently it's defined to be multiplied by self.n, but then is always divided by it again.

I seem to remember some previous discussion about that, need to dig that up. IIRC it had to do with `n` being a public attribute, and changes to it by the user after initialization becoming inconsistent.

**Comment by HerculesJack** [comment]
> Ah yes, that's clear, thanks. Could you add your example as a test to scipy/stats/tests/test_kdeoth.py?

Sure, I will do it later.

> I seem to remember some previous discussion about that, need to dig that up. IIRC it had to do with n being a public attribute, and changes to it by the user after initialization becoming inconsistent.

I think it comes from here #8991, but sorry I failed to get the point. Can you please explain it in a bit more detail? The current version seems to pass all the checks.

Btw I have another proposal. In my application, sometimes I'll need the marginal pdf to make a [triangle plot](https://corner.readthedocs.io/en/latest/pages/quickstart.html), which is useful to visualize high dimensional distributions. This should be easy for kde, since each component is Gaussian so it's trivial to marginalize. 

If you like this idea, I can open another PR to add e.g. `pdf_marginal` and `logpdf_marginal`. Alternatively I think we can just add an `axis` argument to `pdf` and `logpdf`. If it's None (by default), then it returns the full pdf. If it's an 1-d array, then it returns the marginal pdf along the given axis (axes).

**Comment by rgommers** [comment]
> Btw I have another proposal. In my application, sometimes I'll need the marginal pdf to make a triangle plot, which is useful to visualize high dimensional distributions. This should be easy for kde, since each component is Gaussian so it's trivial to marginalize.

makes sense to me. would be good to keep that in a separate PR

> If you like this idea, I can open another PR to add e.g. pdf_marginal and logpdf_marginal. Alternatively I think we can just add an axis argument to pdf and logpdf

My first thought was that an `axis` argument was cleaner, but I'm not sure - it's not obvious what the meaning of `axis` is without reading the docs, and `pdf` is an alias of `evaluate` and `__call__` so they'd all need changing. Plus all the shape checks there become more complicated. So I now think `pdf_marginal` may be better.

Let's see if there are more opinions.

**Comment by rgommers** [comment]
> I think it comes from here #8991, but sorry I failed to get the point. Can you please explain it in a bit more detail? The current version seems to pass all the checks.

Okay I looked into it. gh-8991 was indeed what I remembered, but it's not relevant here. Your change seems fine, I can't think of a sensible subclass that would break due to the changes in this PR. 

If you can add the test case then I'll merge this.

**Comment by rgommers** [comment]
that last commit didn't work; CI failed with `ValueError: `weights` input should be of length n`

**Comment by HerculesJack** [comment]
> that last commit didn't work; CI failed with `ValueError: `weights` input should be of length n`

I just realized that. I think this one will work.  : )

**Comment by rgommers** [comment]
LGTM now, merged. Thanks @HerculesJack!

**Pull request merged**
