### PR TITLE
ENH: add distance gufuncs to `scipy.spatial`

### PR DESCRIPTION
**Pull request by jaimefrio**
This provides a new submodule `umath_distance` to `scipy.spatial`, that provides gufuncs for distance calculations. The Python wrapper to the C coded gufuncs allows `pdist` and `cdist` style calculations with a simpler, common interface.

Only functions of two inputs with no additional parameters are included in this version, i.e. everything provided in `scipy.spatial.distance` except `mahalanobis`, `minkowski`, `seuclidean` and `wminkowski`.

### CODE REVIEW

**Comment by rgommers** [comment]
gh-2009 has more details and references on (5), and gh-2011 on (1, 2).

**Comment by rgommers** [comment]
@jaimefrio can you comment on your plans for this PR? It seems to be close to completion....

Found this again after looking at the other issues I just linked to.

**Comment by rgommers** [comment]
This PR has been superceded by gh-13907, which rewrites the pdist/cdist infrastructure in C++. So I'll close this. Thanks for all the effort you put into this @jaimefrio. 

@peterbell10 it may still be worth checking https://github.com/scipy/scipy/pull/3163#issuecomment-34224341, which points some bugs (or definition issues) that may still not be all fixed or captured elsewhere.

**Comment by sturlamolden** [comment]
> 4. `minkowski` has a check for `p >= 1`. That condition is usually enforced for the Minkowski distance to be a metric, i.e. for the triangle inequality to hold. This is a very restrictive condition, because many of the other distances are not proper metrics. Furthermore, the condition is not enforced either in `pdist` or `cdist`, which will happily take `p`s smaller than 1. I would like to drop this as well.

Both the distance functions and kd-tree have this limitation. It is actually nonsence, as the minkowski distance is symmetric around the Mahattan distance at ```p==1```. And in the same way the limit to ```p==inf``` is the Chebychev distance ```max(abs(x-y))```, the limit to ```p==0```is ```min(abs(x-y))```. We should special case minkowski ```for p in [0, 1, 2, inf]``` and allow ```p>=0``` instead of ```p>=1```.

**Comment by h-vetinari** [comment]
> @rgommers: @peterbell10 it may still be worth checking [#3163 (comment)](https://github.com/scipy/scipy/pull/3163#issuecomment-34224341), which points some bugs (or definition issues) that may still not be all fixed or captured elsewhere.

I think all points are now being tracked (AFAICT):
1./2. Tracked in #2011
3./5. Tracked in #2009, implemented in #14588
4. Tracked in #14710

**Comment by rgommers** [comment]
thanks @h-vetinari

**Comment by h-vetinari** [comment]
> 
> 
> thanks @h-vetinari

Happy to. 🙃 
I couldn't remember anymore why I had put 3./5. together, so I ended up digging up the references to double-check, and in passing also found a better-fitting issue for 1. as well! :)

**Comment by fabianegli** [comment]
The linked issues for the normalized hamming distance do not really apply because they are about the handling of string arguments and not the normalization. There it might be worth to ad a boolean argument `normalize` to the function to select the desired behavior.

**Pull request closed without merging**
