### PR TITLE
Added functionality to the stats.sigmaclip function

### PR DESCRIPTION
**Pull request by Kitchi**
Added the `iters` keyword to sigmaclip as well as the ability to use custom functions to calculate the average value and the standard deviation value - This functionality has been adapted from the `astropy/stats/sigma_clip` function.

### CODE REVIEW

**Comment by Kitchi** [comment]
Looks like this PR has some issues, but I'm unable to see what they are from my end. I'll submit another PR - And if that one works I'll close this one.

**Comment by ev-br** [comment]
One issue is that you seem to have been working off a somewhat old master branch --- it's a good idea to do `git fetch upstream; git rebase upstream/master` once in a while (make a backup branch if you do it for the first time). Here's a rebased branch: https://github.com/ev-br/scipy/tree/pr/5559.
(I did not look at the code)

**Comment by Kitchi** [comment]
Looks like I've pulled in some other stuff while rebasing - What is the best course of action here? Submit another pull request with a "clean" commit of the changes made?

**Comment by ev-br** [comment]
Try `git rebase -i deadbeef^` where deadbeef is the hash of your first commit. Note the trailing caret, ^. It means, basically, "the parent of". 
Back up the current branch first :-).

**Comment by Kitchi** [comment]
Oh whoops, damn. Git really confuses me, sorry! I accidentally deleted the branch in my repo, but then re-pushed the branch again. So looks like the branch is now clean, but the PR has been closed.

Sorry for all this confusion!

**Pull request closed without merging**
