### PR TITLE
add as_inexact option to _lib._util._asarray_validated

### PR DESCRIPTION
**Pull request by argriffing**
In general, SciPy linear algebra functions prefer input arrays that don't contain NaNs, that are not object arrays or masked arrays, and that are dense (not sparse).  Currently `_asarray_validated` checks all of those properties.  This PR adds the additional option to convert the input array to a dtype that is more palatable to BLAS/LAPACK functions, and it should address one of the complaints in https://github.com/scipy/scipy/issues/4866.

### CODE REVIEW

**Comment by ev-br** [comment]
Maybe add a bit more flexibility by adding a `dtype` kwarg instead:  `_asarray_validated(..., dtype=None)`. Then `dtype=None` would mean to keep the input dtype (just like `as_inexact=False` is doing here), otherwise use `toarray(.., dtype=dtype)`?

**Comment by argriffing** [comment]
@ev-br There is some discussion about that kind of thing at https://github.com/numpy/numpy/pull/5634, especially regarding extensions for flexibility.

> `dtype=None` would mean to keep the input dtype (just like `as_inexact=False` is doing here), otherwise use `toarray(.., dtype=dtype)`

As I understand it, this suggestion would need at least some modification.  For example the code in this PR is intended to convert `int` but not `complex` to `float` when `as_inexact=True`.

The TravisCI tests are failing because of test timeouts and also because the code is incompatible with supported numpy 1.6.
`asarray_chkfinite() got an unexpected keyword argument 'dtype'`

**Comment by ev-br** [comment]
Ah, OK. Indeed, it might be better to keep it simple for now and delegate additional sophistication to numpy. The numpy 1.6 limitation is I guess easy to work around with a `try... except TypeError: (..).astype(np.float_)` --- unless we want to bump the minimum numpy version again for scipy 0.17 :-).

**Comment by ev-br** [comment]
OK, this should not fall through the cracks. I've tested it locally and it seems to do what it says on the box:

```
>>> a
array([1, 1, 1])
>>> a.dtype
dtype('int64')
>>> from scipy._lib._util import _asarray_validated as av
>>> av(a, as_inexact=True).dtype
dtype('float64')
>>> 
>>> b = np.ones(3, dtype=np.complex128) * 2j
>>> b.dtype
dtype('complex128')
>>> av(b, as_inexact=True).dtype
dtype('complex128')
>>>
>>> c = np.ones(3)
>>> cc = av(c, as_inexact=True)
>>> np.may_share_memory(c, cc)
True
```
Until numpy grows the relevant functionality, this should do the it (and we'll see how much usage this actually gets). 
Merging, thanks @argriffing.

**Pull request merged**
