### PR TITLE
MAINT:linalg: Remove redundant det and lu Fortran files

### PR DESCRIPTION
**Pull request by ilayn**
#18358 finalized replicating the work that these old Fortran files were used for. This PR removes the files themselves.

### CODE REVIEW

**Comment by j-bowhay** [comment]
Opinions on also getting rid of `flinalg.py` and `_flinalg.py` too? Last time around there was some concerns about the 2.0.0 deprecation warning. Since then, the only two functions left now have a warning saying they will be removed in this release as they are not part of the `linalg` namespace which would leave an empty module
```
In [2]: scipy.linalg.flinalg.__all__
Out[2]: ['get_flinalg_funcs', 'has_column_major_storage']

In [3]: scipy.linalg.flinalg.get_flinalg_funcs
<ipython-input-3-2f187ec6e743>:1: DeprecationWarning: `scipy.linalg.flinalg.get_flinalg_funcs` is deprecated along with the `scipy.linalg.flinalg` namespace. `scipy.linalg.flinalg.get_flinalg_funcs` will be removed in SciPy 1.13.0, and the `scipy.linalg.flinalg` namespace will be removed in SciPy 2.0.0.
  scipy.linalg.flinalg.get_flinalg_funcs
Out[3]: <function scipy.linalg._flinalg_py.get_flinalg_funcs(names, arrays=(), debug=0)>

In [4]: scipy.linalg.flinalg.has_column_major_storage
<ipython-input-4-e9709a88fd27>:1: DeprecationWarning: `scipy.linalg.flinalg.has_column_major_storage` is deprecated along with the `scipy.linalg.flinalg` namespace. `scipy.linalg.flinalg.has_column_major_storage` will be removed in SciPy 1.13.0, and the `scipy.linalg.flinalg` namespace will be removed in SciPy 2.0.0.
  scipy.linalg.flinalg.has_column_major_storage
Out[4]: <function scipy.linalg._flinalg_py.has_column_major_storage(arr)>
```

**Comment by ilayn** [comment]
Oh I completely forgot those. Let me check what they do.

**Comment by ilayn** [comment]
>  so seems a little pointless to leave around

I agree, removed them now.

**Comment by lucascolley** [comment]
`flinalg` also has references in `mypy.ini`, `scipy\_lib\tests\test_public_api.py`, `scipy\linalg\__init__.py`, `scipy\linalg\_basic.py`, `scipy\linalg\basic.py`, and `scipy\linalg\decomp_lu.py`.

**Comment by ilayn** [comment]
Oh my if it is not a hassle please go ahead, I don't know how I missed them. Thanks for the drill down though.

**Comment by lucascolley** [comment]
CI happy, just need to decide whether https://github.com/scipy/scipy/blob/e00a5948a9dddd81954d2039d71e7b0ffe8a36bc/scipy/linalg/_basic.py#L947-L955 should stay/be reworded/be deleted.

**Comment by ilayn** [comment]
That comment has no relevance anymore hence I removed it. It was when we tried to use F or C linalg based on the array flag but that's long gone.

**Review by j-bowhay — APPROVED** [review]
Thanks both! Nice to see ~600 lines go

**Comment by ilayn** [comment]
Thanks @lucascolley for the emergency save, @j-bowhay

**Pull request merged**
