### PR TITLE
MAINT: optimize: remove circular reference in `ScalarFunction`

### LINKED ISSUE #20768: BUG: optimize.minimize: garbage collection in `lbfgs`
### Describe your issue.

Iterated calls to LBFGS increase memory consumption if garbage collection is not explicitly called.

This pipped up in https://github.com/scikit-learn/scikit-learn/issues/28993.

### Reproducing Code Example

```python
import tracemalloc

from scipy.optimize import minimize
import numpy as np


def do_something(*args, **kwargs):
    return np.random.rand()


def do_train():
    minimize(
        do_something,
        np.random.rand(300),
        args=(np.random.rand(2000, 3000)),
        method="L-BFGS-B"
    )


def run(reps):
    tracemalloc.start()
    for _ in range(reps):
        do_train()

    base, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    print(f"| {reps:^6} | {base/ 1024**2:^9.2f} | {peak/ 1024**2:^9.2f} | {(peak-base)/ 1024**2:^9.2f} |")


if __name__ == "__main__":
    print("| # runs | base (MB) | peak (MB) | diff (MB) |")
    print("| ------ | --------- | --------- | --------- |")

    run(1)
    run(2)
    run(3)
    run(4)
    run(5)
    run(6)
    run(7)
    run(8)
    run(9)
    run(14)
    run(16)
    run(8)
```

### Error message

```shell
| # runs | base (MB) | peak (MB) | diff (MB) |
| ------ | --------- | --------- | --------- |
|   1    |   45.79   |   46.59   |   0.80    |
|   2    |   91.57   |   92.37   |   0.80    |
|   3    |  137.36   |  138.16   |   0.80    |
|   4    |  183.15   |  183.94   |   0.80    |
|   5    |  228.93   |  229.73   |   0.80    |
|   6    |  274.72   |  275.52   |   0.80    |
|   7    |   45.79   |  321.21   |  275.42   |
|   8    |  366.29   |  367.08   |   0.80    |
|   9    |  412.07   |  412.87   |   0.80    |
|   14   |  641.00   |  641.80   |   0.80    |
|   16   |  366.29   |  412.07   |   45.78   |
|   8    |  366.29   |  367.08   |   0.80    |
```

### SciPy/NumPy/Python version and system information

```shell
python: 3.10.11
scipy: 1.11.1
```

### PR DESCRIPTION
**Pull request by andyfaff**
This PR would close #20768.

In that issue it was determined that circular references in `optimize._differentiable_functions.ScalarFunction` prevent it from being immediately garbage collected when functions that use the class go out of scope. 

> functions defined inside `ScalarFunction.__init__()` have a closure that allows them to access local variables, such as `self`. Then those functions get assigned as instance variables of `ScalarFunction`, which creates the reference cycle.

This PR removes those circular references by lifting references to `self` out of closures used for wrapping. I have checked that the issue is fixed using the example given by @nickodell:

```
| # runs | base (MB) | peak (MB) | diff (MB) | SF objs |
| ------ | --------- | --------- | --------- | ------- |
|   10   |   0.01    |   45.92   |   45.90   |    0    |
```

Performance should be unchanged, although there are a few more `if` checks.

### CODE REVIEW

**Comment by dschmitz89** [comment]
This is quite dense, will have a closer look in the coming days. Can we test this somehow using refcounting? This is a rather serious issue that affects most local optimizers.

**Comment by andyfaff** [comment]
We can certainly add the test from the original issue, that's straightforward.
Eventually those objects do get collected, just not for a while. That, coupled with the code having existed for several years reduces the urgency somewhat, but we should get a fix for the issue in the next release.

**Comment by andyfaff** [comment]
Last commit adds a test to check that the ScalarFunction object is collected properly. This test fails on main, but not on this PR.

**Comment by nickodell** [comment]
I found a cleaner way to assert that no ScalarFunction objects are left over. I also added a test for VectorFunction and LinearVectorFunction. VectorFunction is marked as a TODO, and LinearVectorFunction seems to have no reference cycles.

The PR can be found here: https://github.com/andyfaff/scipy/pull/67

Apologies if I did anything incorrectly - I didn't see Andy's branch in the SciPy branch list.

**Comment by andyfaff** [comment]
@nickodell I merged your PR and skipped the tests on PyPy (a RuntimeError is raised otherwise). I had to force push a couple of times because I wanted to squash commits and remove the test I added. You're still listed as author on your commit.

**Comment by dschmitz89** [comment]
The mypy complaint is related, besides that this looks good to go in 1.14: https://github.com/scipy/scipy/actions/runs/9217036884/job/25358377982?pr=20770

**Review by dschmitz89 — CHANGES_REQUESTED** [review]
The mypy complaint is related, besides that this looks good to go in 1.14: https://github.com/scipy/scipy/actions/runs/9217036884/job/25358377982?pr=20770

**Comment by dschmitz89** [comment]
Thanks @andyfaff and @nickodell !

**Comment by andyfaff** [comment]
@nickodell contribution was crucial here, the initial diagnosis was spot on.

**Pull request merged**
