### PR TITLE
ENH: Add renormalization optional for expm_multiply

### PR DESCRIPTION
**Pull request by MarcDrudis**
#### Reference issue
Implements issue #16945

#### What does this implement/fix?
Now expm_multiply has an boolean flag `renormalize` that allows for the output vector to ve of norm 1. This is specially useful for applications in which we would run into overflow errors and we only care about the direction of the vector. For example evolving a state for a long time in quantum physics.

### CODE REVIEW

**Comment by ilayn** [comment]
I have basically two comments one is do we really want to add this. Because typically blowups are related to the stability of matrix and not the norm bounds


and the second is that the keyword shoud read `normalize` or `return_unit_vector` or something since we are not renormalizing.

**Comment by MarcDrudis** [comment]
> I have basically two comments one is do we really want to add this. Because typically blowups are related to the stability of matrix and not the norm bounds
> 
> and the second is that the keyword shoud read `normalize` or `return_unit_vector` or something since we are not renormalizing.

Hello, there are some cases when even if the algorithm is working properly we get overflows that we can't avoid. Take for example the identity matrix with a given vector. If we let it evolve for a time T, it grows as `exp(t)` which can typically overflow quite fast.
I am working with the evolution of quantum states in quantum computers, and typically the exponential of a matrix is computed to find it's maximal eigenvalue. Using expm_multiply to benchmark against a classical algorithm feels quite natural.

How would you deal with such a problem? Specially when you don't know the maximum eigenvalue in advance. I kept running into overflow errors until I added a couple of lines of code in order to renormalize the states at each timestep.

I am open for suggestions since you are probably more familiar with the library.

**Comment by ilayn** [comment]
Typically for evolution in time you might want to use a state space approach that is what simulink does; that is pick a timestep and do `dot(x) = Ax` and so on. This is practically more robust to strange tiny overflows that blow up quickly. Most of this is due to the precision problems in `expm`. 

Do you have a code snippet that shows the blowup? Could you also if possible try with the dense `scipy.linalg.expm` manually in a regular loop?

**Comment by MarcDrudis** [comment]
Here could be an example of a case where we encounter overflow.
```
np.random.seed(1234)
start = 0.1
stop=10
num=5
n = 40
A = 1e3*scipy.sparse.rand(n, n, density=0.05)
B = np.random.randn(n)
endpoint = True
X = expm_multiply(
    A, B, start=start, stop=stop, num=num,
    endpoint=endpoint)
assert np.inf not in X and -np.inf not in X, "Overflow encountered"
```
I don't exactly understand what do you mean by "strange tiny overflows". Here the result is overflowing because it needs to. The expected result is such a big number that we can not store it within a numpy array. What I would like is that whenever I can not store such a result at the very least I can get the direction of the vector.

**Comment by ilayn** [comment]
Yes because your array is not Hurwitz meaning you have eigenvalues with positive real parts. So this is not something a code can fix but as you said this is expected. Hence I don't understand why this has to be solved at the expm side. If only the direction of the vector is needed then expm_multiply is not the right tool for that. Either an external for loop or a numerical stepping with `dot(x)=Ax` is needed here.

**Comment by MarcDrudis** [comment]
Okay, and about this method that you are refering to, what do you mean by `dot(x) = Ax` ? One can use Euler forward method or any other integration method and renormalize at each step, but the result is not nearly as fast.

**Pull request closed without merging**
