### PR TITLE
MAINT: prepend underscore to mask_to_limits; delete masked_var.

### PR DESCRIPTION
**Pull request by aeklant**
See issue #585

### CODE REVIEW

**Comment by rgommers** [comment]
Looks good to me. I verified the ``ddof=1``, is correct. Will merge in a day or so if no one comments.

**Comment by aeklant** [comment]
Great! I'll continue working on gh-2914 once this is merged. In the meantime, I will try to get the ball rolling with the other issues that have already been indirectly addressed to some extent.

**Comment by rgommers** [comment]
@aeklant tip for future commits: if you add "closes gh-xxxx" in the commit message, then the corresponding issue gets closed automatically.

**Comment by rgommers** [comment]
Merged, thanks Abraham.

**Comment by aeklant** [comment]
@rgommers noted. Thanks for the tip.

**Pull request merged**
