### PR TITLE
MAINT/STY: fftpack: remove E501 (line length) lint ignore

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
Towards gh-19479.

#### What does this implement/fix?
Follow-up to gh-19489 for `fftpack`.

#### Additional information
cc @mdhaber @j-bowhay. Feel free to wait for gh-19497 if you don't want to test locally.

### CODE REVIEW

**Review by j-bowhay — CHANGES_REQUESTED** [review]
Can you add the blame ignore for this one? Whilst the change is small and trivial it would be nice to keep a reference to what pr / why the skip was added

**Comment by mdhaber** [comment]
Could also do all the blame ignores at the end in one commit, right?

**Comment by lucascolley** [comment]
> Could also do all the blame ignores at the end in one commit, right?

I would suggest doing them as we go along to ensure that none are missed, and also so that these PRs set an example if others end up submitting PRs for other subpackages. Your choice!

**Review by j-bowhay — APPROVED** [review]
Thanks @lucascolley

**Pull request merged**
