### PR TITLE
CI: Add GCC 4.8 entry to travis build matrix

### PR DESCRIPTION
**Pull request by peterbell10**
#### Reference issue
Ref gh-12579

#### What does this implement/fix?
This makes one of the CI entries use the same compilers as the `manylinux1` image.

I expect the first build to fail as I based this off of a commit from before gh-12586

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
I think Travis CI does merge first before build/test, so not sure we'd expect a fail given the fix was merged to master first, though that would have been nice to observe.

That said, this seems like a decent idea. NumPy uses an actual manylinux base image in one of their CI entries last time I checked. I was planning to do that at some point, but this may be good enough for now.

I may also want to backport this as it can be painful to get all the way to wheel preparation to discover issues during release process.

**Comment by peterbell10** [comment]
Okay, lets try the other way. Rebased on master and pushed a commit disabling the flag. I would like to make sure the `CC` and `CXX` flags are working correctly.

**Comment by peterbell10** [comment]
It looks like either `distutils` or `numpy.distutils` is not happy with calling `ccache` directly. More worryingly, the CI passed even though the build failed. I'm hoping `set -e` will get it to fail.

**Comment by peterbell10** [comment]
Okay, after a bit of work the failure is being reproduced here:
https://travis-ci.org/github/scipy/scipy/jobs/710118562#L10818

**Comment by tylerjereddy** [comment]
I've tried restarting the single travis CI matrix entry that failed with `mv: cannot stat '*.gcov': No such file or directory`

**Comment by tylerjereddy** [comment]
Normally I'd just ignore something like that, but given the modification of Travis CI code let's be sure first.

**Comment by peterbell10** [comment]
It looks like that `mv` command has always been failing, for example I found this in gh-12516:
https://travis-ci.org/github/scipy/scipy/jobs/710121153#L1461

It is just only now causing the build to fail because I added `set -e` to check for failed commands.

**Comment by peterbell10** [comment]
Alright, as a bonus feature `runtests.py --gcov` now works with `CC` and `CXX`. Coverage reports for native code should also be fixed now.

**Comment by tylerjereddy** [comment]
Great, CI is all green now. I will squash-merge to facilitate backporting and hopefully be in a position to retry `1.5.2` in the next week or so.

**Pull request merged**
