### PR TITLE
generate AR covariance matrix of an Autoregressive model. 

### PR DESCRIPTION
**Pull request by nitaifingerhut**

### CODE REVIEW

**Comment by rkern** [comment]
Can you fill out the information requested in the PR template? What is this function for? How does it fit in with the rest of `scipy`, which has nothing else for autoregressive models? This would probably fit better in [`statsmodels`](https://pypi.org/project/statsmodels/), which does, in case it doesn't already have an equivalent.

**Comment by josef-pkt** [comment]
isn't this just linalg toeplitz

**Comment by rkern** [comment]
Yes, the most efficient and idiomatic way to implement this would be to use `scipy.linalg.toeplitz()`. But my first question is "why should we add this in the absence of any other tools for autoregressive models?" It seems like `statsmodels` already handles this capably (keeping the efficient vector form until the last moment before using `toeplitz()` to expand it when needed).

**Comment by nitaifingerhut** [comment]
Wasn’t familiar with statsmodel
Will take a look
Thanks!

**Pull request closed without merging**
