### PR TITLE
 Address concerns in gh-12999 for ks_2samp in exact mode.

### LINKED ISSUE #12999: Bug in scipy.stats.ks_2samp for two-sided auto and exact modes on a few thousand samples (when n1!=n2)
When you run have a few thousand samples for each group, and different a number of samples than auto goes to exact.
One sided - gets an exception and shifts to 'asymp'
Two sided - doesn't get an exception but may well finish with prob = 0 or 1, which is not the real probability.
                   the "finally" statement whould change to 'asymp' mode, if it was prob < 0 or >1, but not at 0 and 1.
                   I think this should change to prob <=0 or >=1.

This causes the code snippet below to work well for 1000, 1010 samples worse for 2000,2010 and fail completely for 3000,3010 and above, until 10,000 when the 'asymp' mode kicks in no matter what. 

#### Reproducing code example:

print("look at the p_values going to 1, for 3000 and above when in 'auto' mode. This is clearly not the right probability.")
for x in range(1000, 12000,1000):
    print("For %d vs %d auto" % (x, x))
    print(scipy.stats.ks_2samp([random.normalvariate(100,10) for i in range(x)], [random.normalvariate(95,10) for i in range(x)]))
    print("For %d vs %d asymptotic (not exact)" % (x, x))
    print(scipy.stats.ks_2samp([random.normalvariate(100, 10) for i in range(x)],
                               [random.normalvariate(95, 10) for i in range(x)], mode='asymp'))
    print()

#### Scipy/Numpy/Python version information:

1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by pvanmulbregt**
Return an estimate of the relative error of the probability computed by
stats._compute_prob_inside_method(). As the desired probability is the
complement of the one computed, subtractive cancellation can occur.
Check if it may have, and declare the attempt a failure.  This prevents
a probability ~ 1e-16 being reported when the actual probability is many orders
of magnitude lower.

#### Reference issue
Closes gh-12999

#### What does this implement/fix?
Checks if the computation of a probability in stats._compute_prob_inside_method(), using exact algorithm, may have lost too much precision to be used as a complementary probability.  If so, back off to the asymptotic computation.
In stats. _compute_prob_outside_square(), do a pre-check to determine if the computation will definitely overflow.  If so, return immediately.

### CODE REVIEW

**Comment by pvanmulbregt** [comment]
Actually this cure is starting to look worse than the problem it is addressing...

**Comment by mdhaber** [comment]
> Actually this cure is starting to look worse than the problem it is addressing...

Shall I hold off on review, then?

**Comment by pvanmulbregt** [comment]
yes, hold off on any review, the "fix" affects too many probability calculations. 
A better approach may be to compute an outside probability, scaling with every iteration to avoid underflow/ overflow.

**Comment by t-vi** [comment]
@pvanmulbregt I wrote up a more stable recursion for the inner method / 2-sided 2-sample in 
https://arxiv.org/abs/2102.08037

The basic trick that you can do instead of doing `1-A(m,n)/Binom(m+n,n)` at the end, you can do the entire recursion on values of this form `1-A(i,j)/Binom(i+j,j)`.  It seems to be about 4x slower than the current implementation, which I think it is due to the extra compute, but then both the current implementation and the stable recursion can be moved to numba / other ways to compile to speed them up.

**Comment by rgommers** [comment]
This was superceded by gh-14432, closing. Thanks @pvanmulbregt, all

**Pull request closed without merging**
