### PR TITLE
MAINT: prevent divide by zero warnings in scipy.optimize BFGS algorithm

### PR DESCRIPTION
**Pull request by segasai**
#### Reference issue
N/A

#### What does this implement/fix?
When running scipy.optimize.minimize on some functions, a warning like this 

```
..../pyenv36/lib/python3.6/site-packages/scipy/optimize/optimize.py:1058: RuntimeWarning: divide by zero encountered in double_scalars
  rhok = 1.0 / (numpy.dot(yk, sk))
```
is produced. Since the code already checks for the result being infinity, the warning can be completely avoided.

### CODE REVIEW

**Comment by EverLookNeverSee** [comment]
@segasai Please provide a code sample that produces warning above.

**Comment by segasai** [comment]
I am afraid I wasn't been able to make a small isolated illustration of the warning, when I tried.The warning is regularly produced for me, but the optimization problem is of a nontrivial function with a gigabytes of external data required. Maybe somebody with better understanding of BFGS can come up with a function that triggers the rhok=infty condition...

**Comment by ev-br** [comment]
Can you do `pdb.pm()` or some such and inspect the state after the error is triggered?

**Comment by segasai** [comment]
Okay, I was able to catch it in the act and here are are all the locals() when the warning is raised (just after the rhok = 1/numpy.dot(...) expression)
```
yk': array([      0.        ,       0.        , -327013.32421875,
             0.        ,       0.        ,       0.        ]), 'sk': array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -2.71050543e-20,  0.00000000e+00]), 'xkp1': array([ 7.01291961e+01, -4.67426942e+00,  5.83103638e+03,  4.70006334e+00,
        1.27410791e-04,  3.36565948e-04]), 'gfkp1': array([ 532291.17578125,       0.        ,  839626.97265625,
        145667.109375  , 1022626.875     ,  653863.07421875]), 'gc': 27, 'fc': 27, 'alpha_k': 2.8060923112169665e-26, 'pk': array([ -532291.17578125,       -0.        , -1166640.296875  ,
        -145667.109375  , -1022626.875     ,  -653863.07421875]), 'gnorm': 1022626.875, 'warnflag': 0, 'xk': array([ 7.01291961e+01, -4.67426942e+00,  5.83103638e+03,  4.70006334e+00,
        1.27410791e-04,  3.36565948e-04]), 'old_old_fval': -416970.36162666255, 'Hk': array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]]), 'I': array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]]), 'N': 6, 'k': 1, 'gfk': array([ 532291.17578125,       0.        ,  839626.97265625,
        145667.109375  , 1022626.875     ,  653863.07421875]), 'myfprime': <function wrap_function.<locals>.function_wrapper at 0x7f87a834ec80>, 'grad_calls': [28], 'old_fval': -416970.36162666255, 'func_calls': [224], 'retall': False, 'epsilon': 1.4901161193847656e-08, 'fprime': None, 'f': <function wrap_function.<locals>.function_wrapper at 0x7f87a834e0d0>, 'unknown_options': {}, 'return_all': False, 'disp': False, 'maxiter': 1200, 'eps': 1.4901161193847656e-08, 'norm': inf, 'gtol': 1e-05, 'callback': None, 'jac': None, 'args': (), 'x0': array([ 7.01291961e+01, -4.67426942e+00,  5.83103638e+03,  4.70006334e+00,
        1.27410791e-04,  3.36565948e-04]), 'fun': <function process.<locals>.func at 0x7f87a834e730>}
```

**Comment by ev-br** [comment]
Now that I actually looked at the patch, the patch LGTM

**Review by miladsade96 — APPROVED** [review]
LGTM, Feel free to merge it if @andyfaff or @ev-br are also satisfied.
Thank you @segasai for this PR.

**Comment by ev-br** [comment]
Thanks @segasai @EverLookNeverSee

**Pull request merged**
