### PR TITLE
[WIP] BUG: special: Fix special function errstate

### PR DESCRIPTION
**Pull request by izaid**
The `special` module in `scipy` has functions for error handling, namely `geterr`, `seterr`, and `errstate`. They are analogous to the ones in NumPy. I've personally never used them, but in the process of doing [other work](https://github.com/scipy/scipy/pull/20260) for `special` it became clear these do not appear to be working correctly.

What's the problem? Well, they rely on static variables in `sf_error.c` to be set. For that to behave properly, there must be only one copy of these variables. From what I see in the `meson.build` of `special`, `sf_error.c` is getting compiled in all over the place. That means there would be many copies of these state variables.

I've never used this functionality from `special`, but I don't want it to hold up other efforts. So I'm proposing a fix in this PR. The way forward is to turn `sf_error.c` into a single shared library that everything else links to. This was not as easy as it sounds because `sf_error.c` currently has all kinds of Python C API calls. That's not really workable. So I adapted it to take in a generic callback, which we can set from Cython to replicate the same behaviour as before.

At the end of the day, this is not a feature that I use. So I'd greatly appreciate if someone that **does** use this feature can check this out.

cc @steppi

### CODE REVIEW

**Comment by steppi** [comment]
Nice. I spent 30 minutes on this today and also discovered the Python C api calls blocking making it a shared library. If I understand correctly, I think you’ve taken the right approach, but I haven’t looked at the code yet.

**Comment by izaid** [comment]
Getting the following error on CI.

```
~/work/scipy/scipy/tools ~/work/scipy/scipy
----------- All the test files were installed --------------
----------- All the .pyi files were installed --------------
../build/scipy/special/libspecial_error.so: too many public symbols!
00000000000014f0 T set_error
0000000000001370 T sf_error
0000000000001420 T sf_error_check_fpe
00000000000011e0 T sf_error_get_action
0000000000004080 D sf_error_messages
00000000000011c0 T sf_error_set_action
0000000000001200 T sf_error_set_callback
0000000000001210 T sf_error_set_callback_fpe
0000000000001220 T sf_error_v
```

This seems to be part of SciPy's build process. Not sure what the deal is, but @rgommers I see you've run into it [before](https://github.com/scipy/scipy/issues/15996).

**Comment by steppi** [comment]
@izaid, could we have a shared library just for the shared state, and then sprinkle in the Python API stuff separately?

**Comment by izaid** [comment]
> @izaid, could we have a shared library just for the shared state, and then sprinkle in the Python API stuff separately?

@steppi I think that's what I've done here? There are no Python API calls in the shared library I've pushed. They come in through a function pointer. Let me know if you see differently.

**Comment by rgommers** [comment]
That error is a check for symbol visibility. We've had issues with symbol clashes when multiple copies of SciPy were floating around (IIRC in an embedding scenario, can't remember exactly). So we introduced a linker script to hide everything except `PyInit_xxx` in extension modules (on top of Meson using `-fvisibility=hidden|inlineshidden` for extension modules by default): https://github.com/scipy/scipy/blob/e4655a65036585d2c91ff8fb336b0cbce01a3b3f/meson.build#L119-L131

We are shipping exactly zero shared libraries right now; they can be problematic. If it's only used from multiple extension modules in a single directory it may work; if not then it's going to be a problem (especially on Windows, because of the lack of RPATH support). 

I'll have a closer look later. Once things work in regular CI we should run a full set of wheel builds on this PR (pushing a commit with `[wheel build]` in the first line of the commit message will do that).

**Comment by izaid** [comment]
> That error is a check for symbol visibility. We've had issues with symbol clashes when multiple copies of SciPy were floating around (IIRC in an embedding scenario, can't remember exactly). So we introduced a linker script to hide everything except `PyInit_xxx` in extension modules (on top of Meson using `-fvisibility=hidden|inlineshidden` for extension modules by default):
> 
> https://github.com/scipy/scipy/blob/e4655a65036585d2c91ff8fb336b0cbce01a3b3f/meson.build#L119-L131
> 
> We are shipping exactly zero shared libraries right now; they can be problematic. If it's only used from multiple extension modules in a single directory it may work; if not then it's going to be a problem (especially on Windows, because of the lack of RPATH support).
> 
> I'll have a closer look later. Once things work in regular CI we should run a full set of wheel builds on this PR (pushing a commit with `[wheel build]` in the first line of the commit message will do that).

Thanks @rgommers! Yes, that's what I thought, that the error was checking if there was exactly one visible symbol (i.e. is this a Python extension).

Again, my goal here is to fix what appears to be an existing issue. I wouldn't have proposed the shared library solution if I saw another easy way. And, if there is one, happy to discuss it.

**Comment by rgommers** [comment]
If it works in our CI and wheel builds, then it should be fine - all other methods to build/distribute binaries are more sane and won't have issues with shared libraries.

It would be useful to make the symbol names more specific if possible. Something like `sf_error` (and definitely `set_error`) is so generic that it's likely to result in conflicts. Is it possible to prepend `scipy_` to the symbol names?

**Comment by izaid** [comment]
> If it works in our CI and wheel builds, then it should be fine - all other methods to build/distribute binaries are more sane and won't have issues with shared libraries.
> 
> It would be useful to make the symbol names more specific if possible. Something like `sf_error` (and definitely `set_error`) is so generic that it's likely to result in conflicts. Is it possible to prepend `scipy_` to the symbol names?

Sure, happy to do that. I'll do that once you let me know what needs to happen with the linking issues above.

**Comment by rgommers** [comment]
You can skip all checking for this extension in the test script (`tools/check_pyext_symbol_hiding.sh`).

**Comment by steppi** [comment]
> > @izaid, could we have a shared library just for the shared state, and then sprinkle in the Python API stuff separately?
> 
> @steppi I think that's what I've done here? There are no Python API calls in the shared library I've pushed. They come in through a function pointer. Let me know if you see differently.

Sorry, the **just** was doing a lot of work there. I know you're doing that already. I meant, why not make a more minimal set of changes like here, https://github.com/scipy/scipy/compare/main...steppi:scipy:sf_error_state?expand=1?

I still get linking errors though.

**Comment by steppi** [comment]
> Sorry, the **just** was doing a lot of work there. I know you're doing that already. I meant, why not make a more minimal set of changes like here, https://github.com/scipy/scipy/compare/main...steppi:scipy:sf_error_state?expand=1?

Nevermind, that doesn't even work to make the error handling work. I'm out of my element here. At some point I'd like to understand what's going on though.

**Comment by izaid** [comment]
> > Sorry, the **just** was doing a lot of work there. I know you're doing that already. I meant, why not make a more minimal set of changes like here, https://github.com/scipy/scipy/compare/main...steppi:scipy:sf_error_state?expand=1?
> 
> Nevermind, that doesn't even work to make the error handling work. I'm out of my element here. At some point I'd like to understand what's going on though.

I think a working version of that is just the same thing ultimately? Shared library that needs to be linked to multiple locations.

**Comment by steppi** [comment]
fwiw, If I build with  `python dev.py build` on this branch and then `import scipy.special as special` I get

```
In [1]: import scipy.special as special
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import scipy.special as special

File ~/scipy/build-install/lib/python3.11/site-packages/scipy/special/__init__.py:777
    773 import warnings
    775 from ._sf_error import SpecialFunctionWarning, SpecialFunctionError
--> 777 from . import _ufuncs
    778 from ._ufuncs import *
    780 # Replace some function definitions from _ufuncs to add Array API support

ImportError: libspecial_error.so: cannot open shared object file: No such file or directory
```

**Comment by izaid** [comment]
> fwiw, If I build with `python dev.py build` on this branch and then `import scipy.special as special` I get
> 
> ```
> In [1]: import scipy.special as special
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Cell In[1], line 1
> ----> 1 import scipy.special as special
> 
> File ~/scipy/build-install/lib/python3.11/site-packages/scipy/special/__init__.py:777
>     773 import warnings
>     775 from ._sf_error import SpecialFunctionWarning, SpecialFunctionError
> --> 777 from . import _ufuncs
>     778 from ._ufuncs import *
>     780 # Replace some function definitions from _ufuncs to add Array API support
> 
> ImportError: libspecial_error.so: cannot open shared object file: No such file or directory
> ```

That might have something to do with how it gets installed in `meson.build`, but I don't know. I don't normally use meson, I'm just getting used to it now with SciPy.

**Comment by steppi** [comment]
> I think a working version of that is just the same thing ultimately? Shared library that needs to be linked to multiple locations.

Sorry, I just don't understand why some of the changes you've made are needed due to my own ignorance of these things, and I don't understand why the naive thing I tried doesn't work. You're work shouldn't be blocked by me not being an expert in these matters though, but I should try to catch up.

**Comment by steppi** [comment]
Huh, 

```
In [2]: with special.errstate(all="raise"):
   ...:     special.gammaln(-1)
   ...:
```

doesn't raise for me locally on your branch either.

**Comment by izaid** [comment]
> Huh,
> 
> ```
> In [2]: with special.errstate(all="raise"):
>    ...:     special.gammaln(-1)
>    ...:
> ```
> 
> doesn't raise for me locally on your branch either. This is installing with `pip install .` for each.

@steppi You should now, I just tested. Forgot to put `-DSP_SPECFUN_ERROR` back in the `cpp_args` for `_special_ufuncs`.

**Comment by izaid** [comment]
> fwiw, If I build with `python dev.py build` on this branch and then `import scipy.special as special` I get
> 
> ```
> In [1]: import scipy.special as special
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> Cell In[1], line 1
> ----> 1 import scipy.special as special
> 
> File ~/scipy/build-install/lib/python3.11/site-packages/scipy/special/__init__.py:777
>     773 import warnings
>     775 from ._sf_error import SpecialFunctionWarning, SpecialFunctionError
> --> 777 from . import _ufuncs
>     778 from ._ufuncs import *
>     780 # Replace some function definitions from _ufuncs to add Array API support
> 
> ImportError: libspecial_error.so: cannot open shared object file: No such file or directory
> ```

I don't see this on my Mac, what OS are you on?

**Comment by steppi** [comment]
> > Huh,
> > ```
> > In [2]: with special.errstate(all="raise"):
> >    ...:     special.gammaln(-1)
> >    ...:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > doesn't raise for me locally on your branch either. This is installing with `pip install .` for each.
> 
> @steppi You should now, I just tested. Forgot to put `-DSP_SPECFUN_ERROR` back in the `cpp_args` for `_special_ufuncs`.

Nice! My version of this also works now; I'd also left that out. I'm far in the weeds of trying to get this to work on meson now.

**Comment by izaid** [comment]
> > > Huh,
> > > ```
> > > In [2]: with special.errstate(all="raise"):
> > >    ...:     special.gammaln(-1)
> > >    ...:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > doesn't raise for me locally on your branch either. This is installing with `pip install .` for each.
> > 
> > 
> > @steppi You should now, I just tested. Forgot to put `-DSP_SPECFUN_ERROR` back in the `cpp_args` for `_special_ufuncs`.
> 
> Nice! My version of this also works now; I'd also left that out. I'm far in the weeds of trying to get this to work on meson now. I'm on Linux.

I suspect the issue is to do with the relative path for shared libraries, perhaps meson defaults to absolute path or something.  I'm looking at the meson docs.

**Comment by izaid** [comment]
@steppi I think this is relevant, see https://github.com/mesonbuild/meson/issues/3038

Is there a SciPy meson expert?

**Comment by steppi** [comment]
> @steppi I think this is relevant, see [mesonbuild/meson#3038](https://github.com/mesonbuild/meson/issues/3038)
> 
> Is there a SciPy meson expert?

I’ve been reading about rpath too. It’s Ralf, but let’s not bug him too much, he’s busy enough as it is.

**Comment by izaid** [comment]
@steppi and I have been looking into this, we're not sure, but we think the rpath isn't being set correctly on the shared_library. I see:

```
readelf -d ~/git/scipy/build-install/lib/python3/dist-packages/scipy/special/_special_ufuncs.cpython-310-x86_64-linux-gnu.so 

Dynamic section at offset 0x25db0 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libspecial_error.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x2000
 0x000000000000000d (FINI)               0x19174
 0x0000000000000019 (INIT_ARRAY)         0x26da0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x26da8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x2f0
 0x0000000000000005 (STRTAB)             0x948
 0x0000000000000006 (SYMTAB)             0x318
 0x000000000000000a (STRSZ)              991 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x27000
 0x0000000000000002 (PLTRELSZ)           1320 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x1300
 0x0000000000000007 (RELA)               0xeb0
 0x0000000000000008 (RELASZ)             1104 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0xdb0
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0xd28
 0x000000006ffffff9 (RELACOUNT)          37
 0x0000000000000000 (NULL)               0x0
```

I wonder if we just need to inject `./` before `libspecial_error.so` somehow.

**Comment by steppi** [comment]
That should fix it. I needed to add the `install_dir` for the shared library.

**Comment by steppi** [comment]
@izaid, my preference for the short term would be to go with #20321 instead. It attempts to reduce the shared library to the minimum set of things needed to manage the shared state, with `sf_error.c` being otherwise unchanged. The shared library exports only the two symbols `scipy_sf_error_set_action` and `scipy_sf_error_get_action`. I've prepended `scipy` following @rgommers suggestion. I think it's better to make the minimum necessary fix to leave our options more open for the future, and then revisit special function error handling later on.

 I've managed to get it working for all but one CI job, `Windows tests / cp311 (build sdist + wheel), full, no pythran (pull_request)`

**Comment by izaid** [comment]
> @izaid, my preference for the short term would be to go with #20321 instead. It attempts to reduce the shared library to the minimum set of things needed to manage the shared state, with `sf_error.c` being otherwise unchanged. The shared library exports only the two symbols `scipy_sf_error_set_action` and `scipy_sf_error_get_action`. I've prepended `scipy` following @rgommers suggestion. I think it's better to make the minimum necessary fix to leave our options more open for the future, and then revisit special function error handling later on.
> 
> I've managed to get it working for all but one CI job, `Windows tests / cp311 (build sdist + wheel), full, no pythran (pull_request)`

Happy with that, especially if it is working on CI! Closing.

**Pull request closed without merging**
