### PR TITLE
MAINT: stats: restrict gausshyper z > -1

### LINKED ISSUE #10134: gausshyper distribution accepts invalid parameters
gausshyper distribution accepts invalid parameters:

```
import numpy as np
from scipy Import stats

x = np.linspace(0, 0.5, 10)
stats.gausshyper(1, 1, -1, -5).pdf(x)
array([-0.66666667, -0.48148148, -0.2962963 , -0.11111111,  0.07407407,
        0.25925926,  0.44444444,  0.62962963,  0.81481481,  1.        ])
```

Current `_argcheck` method is:
```
def _argcheck(self, a, b, c, z):
        return (a > 0) & (b > 0) & (c == c) & (z == z)
```
Look like the last parameter z needs to be in (-1, 1) as it enters `special.hyp2f1`. Not sure about `c`

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gausshyper.html

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by mdhaber**
`scipy.stats.gausshyper` parameter `z` should be restricted to `z > -1` per discussion in gh-10134. 

Closes gh-10134

### CODE REVIEW

**Comment by chrisb83** [comment]
Would you mind adding the reference that introduces the distribution?

Armero, C., and M. J. Bayarri. "Prior Assessments for Prediction in Queues." Journal of the Royal Statistical Society. Series D (The Statistician) 43, no. 1 (1994): 139-53. doi:10.2307/2348939

I am also ok to merge the PR as it is.

**Comment by mdhaber** [comment]
Good idea. And I'll add the reference that specifies z > -1 as a comment here.

**Comment by mdhaber** [comment]
Also needed to update the tutorial. The notation is inconsistent between the two, but I think that is a job for a more general cleanup.

**Review by chrisb83 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
