### PR TITLE
Fix up boxcox for underflow / loss of precision

### LINKED ISSUE #4862: the scipy.special.boxcox function is inaccurate for denormal floating point values
see https://github.com/scipy/scipy/pull/4839#issuecomment-101250837

### PR DESCRIPTION
**Pull request by ewmoore**
closes gh-4862

### CODE REVIEW

**Comment by argriffing** [comment]
The `print` functions should be removed eventually.

**Comment by ewmoore** [comment]
Yes, my bad.  They're gone now.

**Comment by argriffing** [comment]
There was a failing commit `1575faa`, it was bugfixed and banished from existence?

**Comment by ev-br** [comment]
The genpareto test fails across all python versions. It is probably a bit unreasonably stringent, and can be changed. On the same machine which started  https://github.com/scipy/scipy/issues/4862 via https://github.com/scipy/scipy/pull/4839#issuecomment-101250837, the test passes with

```
$ git diff
diff --git a/scipy/stats/tests/test_distributions.py b/scipy/stats/tests/test_distributions.py
index 62ed9cb..592301d 100644
--- a/scipy/stats/tests/test_distributions.py
+++ b/scipy/stats/tests/test_distributions.py
@@ -620,7 +620,7 @@ class TestGenpareto(TestCase):
         q = np.r_[np.logspace(1e-12, 0.01, base=0.1),
                   np.linspace(0.01, 1, 30, endpoint=False),
                   1. - np.logspace(1e-12, 0.01, base=0.1)]
-        for c in [1e-8, -1e-18, 1e-15, -1e-15]:
+        for c in [1e-8, 1e-12, -1e-12]:
             assert_allclose(stats.genpareto.cdf(stats.genpareto.ppf(q, c), c),
                     q, atol=1e-15)
```

(PR which brought this test is https://github.com/scipy/scipy/pull/3225)

**Comment by ewmoore** [comment]
The test is a good test.  I've made my changes less aggressive, since in principle `log1p(x)` can return something not equal to `x` anywhere that `x**2` doesn't underflow.

**Comment by ewmoore** [comment]
Green now.

**Comment by ev-br** [comment]
Thanks @ewmoore, merging

**Pull request merged**
