### PR TITLE
TST: backport gh-9493 to 1.2.x branch

### PR DESCRIPTION
**Pull request by tylerjereddy**
Backport gh-9493

With both [Travis](https://travis-ci.org/MacPython/scipy-wheels/builds/458994594) and [Appveyor](https://ci.appveyor.com/project/scipy/scipy-wheels/builds/20519928) wheel build CI runs now finally green (for the first time in 2+ months) on the master branch after a set of PRs, this is the first of a few backport PRs to enable the same wheel building fixes in the `1.2.x` maintenance branch, so that I may eventually proceed with the somewhat-delayed release candidate process.

### CODE REVIEW

**Comment by charris** [comment]
You don't need to wait on reviews for backports, just put them in after the tests run.

**Comment by tylerjereddy** [comment]
I'm probably just a little slow because of long weekend stuff. I think the pypy3 failures are known / skipped in master, but Appveyor will take about 2 hours to run typically.

**Comment by charris** [comment]
Just wanted to make sure you didn't wait on review.

**Comment by rgommers** [comment]
Merged. For next backports I'd suggest to do multiple in a single PR, rather than all separate - easier on CI, and keeps the history cleaner.

PyPy CI failures are known. The crashes can be ignored, but the content of gh-9507 would be useful to backport as a single commit as part of the next backport PR.

**Pull request merged**
