### PR TITLE
ENH: Minor user-friendliness cleanup in LowLevelCallable

### PR DESCRIPTION
**Pull request by pv**
Fix some issues in docstring + provide a more friendly error message on failure.

### CODE REVIEW

**Comment by rgommers** [comment]
TravisCI is unhappy

**Comment by pv** [comment]
The test failures do look unrelated, it's stuff like
```
FAIL: test_base.Test64Bit.test_no_64(<class 'test_base.TestBSR'>, 
'test_elementwise_divide')
FAIL: test_base.TestLIL.test_elementwise_divide
```
Maybe they go away on restart?

**Comment by pv** [comment]
Maybe the failures are due to using Numpy prerelease?

**Comment by pv** [comment]
Indeed, gh-6950 has the same failures.

**Comment by pv** [comment]
I think the problem is https://github.com/numpy/numpy/pull/8452

**Comment by rgommers** [comment]
Ah, good we ran into that before 1.12.0 final....

There are also some compiler warnings that may be useful to clean up?


    In file included from ../scipy/_lib/src/_test_ccallback.c:40:0:
    ../scipy/_lib/src/ccallback.h: In function ‘ccallback_prepare’:
    ../scipy/_lib/src/ccallback.h:370:13: warning: passing argument 2 of ‘ccallback__err_invalid_signature’ discards ‘const’ qualifier from pointer target type [enabled by default]
                 ccallback__err_invalid_signature(signatures, name);
                 ^
    ../scipy/_lib/src/ccallback.h:201:13: note: expected ‘char *’ but argument is of type ‘const char *’
     static void ccallback__err_invalid_signature(ccallback_signature_t *signatures,
                 ^
    In file included from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                     from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/noprefix.h:9,
                     from ../scipy/ndimage/src/nd_image.h:41,
                     from ../scipy/ndimage/src/nd_image.c:32:
    /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from ../scipy/ndimage/src/nd_image.c:41:0:
    /home/rgommers/Code/scipy/scipy/_lib/src/ccallback.h: In function ‘ccallback_prepare’:
    /home/rgommers/Code/scipy/scipy/_lib/src/ccallback.h:370:13: warning: passing argument 2 of ‘ccallback__err_invalid_signature’ discards ‘const’ qualifier from pointer target type [enabled by default]
                 ccallback__err_invalid_signature(signatures, name);
                 ^
    /home/rgommers/Code/scipy/scipy/_lib/src/ccallback.h:201:13: note: expected ‘char *’ but argument is of type ‘const char *’
     static void ccallback__err_invalid_signature(ccallback_signature_t *signatures,


    In file included from ../scipy/integrate/__quadpack.h:26:0,
                     from ../scipy/integrate/_quadpackmodule.c:4:
    /home/rgommers/Code/scipy/scipy/_lib/src/ccallback.h: In function ‘ccallback_prepare’:
    /home/rgommers/Code/scipy/scipy/_lib/src/ccallback.h:370:13: warning: passing argument 2 of ‘ccallback__err_invalid_signature’ discards ‘const’ qualifier from pointer target type [enabled by default]
                 ccallback__err_invalid_signature(signatures, name);
                 ^
    /home/rgommers/Code/scipy/scipy/_lib/src/ccallback.h:201:13: note: expected ‘char *’ but argument is of type ‘const char *’
     static void ccallback__err_invalid_signature(ccallback_signature_t *signatures,
                 ^
    In file included from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                     from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/rgommers/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from ../scipy/integrate/__quadpack.h:28,
                     from ../scipy/integrate/_quadpackmodule.c:4:

**Comment by rgommers** [comment]
Tested on 32-bit to be sure - all is well there.

**Comment by jotasi** [comment]
@rgommers Was this comment meant for this PR or #6950 ?

**Comment by rgommers** [comment]
This PR. But no worries, I'll test yours on 32-bit as well:)

**Comment by pv** [comment]
Travis rebuild passes now that the numpy package was updated.

**Comment by rgommers** [comment]
In it goes then, thanks!

**Pull request merged**
