### PR TITLE
BLD: make scipy build warning-free with LTO enabled

### PR DESCRIPTION
**Pull request by eli-schwartz**
Much fortran code is not LTO-safe, and would require modernizing that fortran code, probably. We cannot actually solve this trivially. What we *can* do, is mark each of these targets as LTO-unsafe so that meson with -Db_lto=true refrains from compiling these specific targets with LTO.

Reproduce by compiling SciPy with:

- compile/link flags (CFLAGS, CXXFLAGS, FFLAGS, LDFLAGS): -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing

- meson setup -Db_lto=true

and keep adding override_options to various targets until the build succeeds.

Bug: #16098

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I noticed this when I tried reinstalling SciPy on Gentoo with -flto in /etc/portage/make.conf.

@rgommers commented in the linked ticket:

> It's mostly old Fortran code. Example:
> 
> ```
> scipy/stats/statlib/spearman.f:75:72: warning: type of ‘alnorm’ does not match original declaration [-Wlto-type-mismatch]
>    75 |       prho = u / exp(y / two) + alnorm(x, .true.)
>       |                                                                        ^
> scipy/stats/statlib/swilk.f:217:38: note: return value type mismatch
>   217 |       DOUBLE PRECISION FUNCTION ALNORM(X, UPPER)
> ```
> 
> It's pretty tedious (but not hard) to fix.

Since it's been a while and it doesn't appear to be getting fixed? I think the pragmatic approach is to carefully disable LTO for those targets. Also, this makes it easier to grep for "known trouble spots" without doing a full build. If a target is suppressing LTO, that can be analyzed as a red flag.

**Review by rgommers — COMMENTED** [review]
Nice idea, I like it, thanks!

It looks like I need to retest on Linux; on macOS the linker gets unhappy very quickly: 
```
ninja: Entering directory `build'
[4/1298] Linking target scipy/special/_ufuncs_cxx.cpython-310-darwin.so
FAILED: scipy/special/_ufuncs_cxx.cpython-310-darwin.so
c++  -o scipy/special/_ufuncs_cxx.cpython-310-darwin.so scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/meson-generated__ufuncs_cxx.cpp.o scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/_faddeeva.cxx.o scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/_wright.cxx.o scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/ellint_carlson_wrap.cxx.o scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/Faddeeva.cc.o scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/sf_error.cc.o scipy/special/_ufuncs_cxx.cpython-310-darwin.so.p/wright.cc.o -L/Users/rgommers/mambaforge/envs/scipy-dev/lib -flto -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,dynamic_lookup -bundle -Wl,-undefined,dynamic_lookup -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/rgommers/mambaforge/envs/scipy-dev/lib -D_FORTIFY_SOURCE=2 -isystem /Users/rgommers/mambaforge/envs/scipy-dev/include scipy/special/libcephes.a
ld: multiple errors: could not parse bitcode object file scipy/special/libcephes.a[66](cephes_zetac.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[66](cephes_zetac.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[65](cephes_zeta.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[65](cephes_zeta.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[64](cephes_yv.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[64](cephes_yv.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[63](cephes_yn.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[63](cephes_yn.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[62](cephes_unity.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[62](cephes_unity.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[61](cephes_tukey.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[61](cephes_tukey.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[60](cephes_tandg.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[60](cephes_tandg.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[59](cephes_struve.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[59](cephes_struve.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[58](cephes_stdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[58](cephes_stdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[57](cephes_spence.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[57](cephes_spence.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[56](cephes_sinpi.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[56](cephes_sinpi.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[55](cephes_sindg.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[55](cephes_sindg.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[54](cephes_sici.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[54](cephes_sici.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[53](cephes_shichi.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[53](cephes_shichi.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[52](cephes_scipy_iv.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[52](cephes_scipy_iv.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[51](cephes_round.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[51](cephes_round.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[50](cephes_rgamma.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[50](cephes_rgamma.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[49](cephes_psi.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[49](cephes_psi.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[48](cephes_poch.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[48](cephes_poch.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[47](cephes_pdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[47](cephes_pdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[46](cephes_owens_t.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[46](cephes_owens_t.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[45](cephes_ndtri.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[45](cephes_ndtri.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[44](cephes_ndtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[44](cephes_ndtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[43](cephes_nbdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[43](cephes_nbdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[42](cephes_lanczos.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[42](cephes_lanczos.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[41](cephes_kolmogorov.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[41](cephes_kolmogorov.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[40](cephes_kn.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[40](cephes_kn.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[39](cephes_k1.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[39](cephes_k1.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[38](cephes_k0.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[38](cephes_k0.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[37](cephes_jv.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[37](cephes_jv.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[36](cephes_j1.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[36](cephes_j1.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[35](cephes_j0.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[35](cephes_j0.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[34](cephes_incbi.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[34](cephes_incbi.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[33](cephes_incbet.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[33](cephes_incbet.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[32](cephes_igami.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[32](cephes_igami.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[31](cephes_igam.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[31](cephes_igam.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[30](cephes_i1.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[30](cephes_i1.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[29](cephes_i0.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[29](cephes_i0.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[28](cephes_hyperg.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[28](cephes_hyperg.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[27](cephes_hyp2f1.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[27](cephes_hyp2f1.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[26](cephes_gdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[26](cephes_gdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[25](cephes_gammasgn.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[25](cephes_gammasgn.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[24](cephes_gamma.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[24](cephes_gamma.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[23](cephes_fresnl.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[23](cephes_fresnl.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[22](cephes_fdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[22](cephes_fdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[21](cephes_expn.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[21](cephes_expn.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[20](cephes_exp2.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[20](cephes_exp2.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[19](cephes_exp10.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[19](cephes_exp10.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[18](cephes_erfinv.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[18](cephes_erfinv.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[17](cephes_ellpk.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[17](cephes_ellpk.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[16](cephes_ellpj.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[16](cephes_ellpj.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[15](cephes_ellpe.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[15](cephes_ellpe.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[14](cephes_ellik.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[14](cephes_ellik.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[13](cephes_ellie.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[13](cephes_ellie.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[12](cephes_dd_real.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[12](cephes_dd_real.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[11](cephes_dawsn.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[11](cephes_dawsn.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[9](cephes_chdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[9](cephes_chdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[8](cephes_chbevl.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[8](cephes_chbevl.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[7](cephes_cbrt.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[7](cephes_cbrt.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[6](cephes_btdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[6](cephes_btdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[5](cephes_beta.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[5](cephes_beta.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[4](cephes_besselpoly.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[4](cephes_besselpoly.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[3](cephes_bdtr.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[3](cephes_bdtr.c.o)'; could not parse bitcode object file scipy/special/libcephes.a[2](cephes_airy.c.o): 'Unknown attribute kind (86) (Producer: 'LLVM16.0.6' Reader: 'LLVM APPLE_1_1500.0.40.1_0')', using libLTO version 'LLVM version 15.0.0' in 'scipy/special/libcephes.a[2](cephes_airy.c.o)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

That may be expected though when mixing `clang` and `gfortran`.

**Comment by eli-schwartz** [comment]
That looks more like somehow it is mixing AppleClang together with generic Clang compilers.

**Comment by rgommers** [comment]
> That looks more like somehow it is mixing AppleClang together with generic Clang compilers.

Yes indeed, that is happening with conda-forge compilers; the compilers are built within conda-forge, but the system linker may be used (sometimes with a shim, platform-dependent). I have LLVM 16.0.6 from conda-forge, and LLVM 15.0.0 from macOS.

On Linux I get similar issues with conda-forge compilers:
```
[1361/1537] Linking static target scipy/optimize/_highs/libbasiclu.a
/home/rgommers/mambaforge/envs/scipy-dev/bin/x86_64-conda-linux-gnu-ar: scipy/optimize/_highs/libbasiclu.a.p/.._..__lib_highs_src_ipm_basiclu_src_basiclu_factorize.c.o: plugin needed to handle lto object
```

xref https://github.com/conda-forge/clangdev-feedstock/issues/155; conda-forge can't enable LTO. However, Linux distros can - and they do ensure to build all their packages with the same compilers.

Since this is an improvement and will help Linux distros, let's get this in. A lot of the problematic Fortran code is in the process of being rewritten in another language, so the problem will gradually shrink / go away.

**Review by rgommers — APPROVED** [review]
In it goes. Thanks again @eli-schwartz 

The 1.13.0 release isn't too far off anymore (~1 month or so I hope), and 1.12.0 is already at RC2, so I'll not mark this for backporting.

**Comment by eli-schwartz** [comment]
> The 1.13.0 release isn't too far off anymore (~1 month or so I hope), and 1.12.0 is already at RC2, so I'll not mark this for backporting.

Sure, no problem. For now I can add `filter-lto` to the SciPy ebuilds, which will delete -flto completely from the user's `*FLAGS`. That way other users won't hit this footgun.

**Pull request merged**
