### PR TITLE
BUGS: Fixes #4746 and #4594: linprog returns solution violating equality constraint and IndexError when a callback is provided

### LINKED ISSUE #4746: linprog returns solution violating equality constraint
From https://stackoverflow.com/questions/29629618/scipy-optimize-linprog-equality-constraint-does-not-appear-satisfied

This program returns a solution not satisfying the equality constraint
```
import numpy as np
from scipy.optimize import linprog

c=[-0.098782540360068297, -0.072316526358138802, 0.004, 0.004, 0.004, 0.004]
A_ub=[[1.0, 0, 0, 0, 0, 0], [-1.0, 0, 0, 0, 0, 0], [0, -1.0, 0, 0, 0, 0], [0, 1.0, 0, 0, 0, 0], [1.0, 1.0, 0, 0, 0, 0]]
b_ub=[3.0, 3.0, 3.0, 3.0, 20.0]
A_eq=[[1.0, 0, -1, 1, -1, 1], [0, -1.0, -1, 1, -1, 1]]
b_eq=[0,0]
res=linprog(c, A_ub, b_ub, A_eq, b_eq)

print("A_eq x", np.dot(A_eq, res.x), "b_eq", b_eq)
# -> ('A_eq x', array([ 0., -6.]), 'b_eq', [0, 0])

assert res.success
assert np.all(np.dot(A_ub, res.x) <= np.asarray(b_ub) + 1e-4)
assert np.allclose(np.dot(A_eq, res.x), b_eq, atol=1e-4)
```

cc @robfalck

### PR DESCRIPTION
**Pull request by Andreea-G**
Solves the case when artificial variables remain in the basis at the end of Phase 1.

### CODE REVIEW

**Comment by Andreea-G** [comment]
Used "An Introduction to Linear Programming and Game Theory" by Paul R. Thie, Gerard E. Keough, pag 102, available on Google Books.

**Comment by pv** [comment]
Please add that reference as a comment in the code, so that it's possible for other people to find it later on.

**Comment by Andreea-G** [comment]
Oh, ok.

**Comment by argriffing** [comment]
Thanks @Andreea-G this looks plausible.

The test failure appears to be unrelated.
```
======================================================================
FAIL: test_random_complex (test_basic.TestDet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.7/site-packages/scipy/linalg/tests/test_basic.py", line 693, in test_random_complex
    assert_allclose(d1, d2, rtol=1e-13)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-13, atol=0
(mismatch 100.0%)
 x: array((11943.878531342612-5984.856954081124j))
 y: array((11943.878531342718-5984.856954083003j))
```

A minor docs typo is that the page number in the PR is `pag 201` instead of `page 102`...

**Comment by Andreea-G** [comment]
Ah, good catch. Fixed it.

**Comment by dlax** [comment]
@Andreea-G could you clean the commit history from the merge? it comes from another of yours own branches apparently.

@argriffing I'm not very familiar with this linprog algorithm (and you apparently dug into this more than I would be able to do), so once you think this is fine, go ahead and merge.

**Comment by argriffing** [comment]
> I'm not very familiar with this linprog algorithm (and you apparently dug into this more than I would be able to do), so once you think this is fine, go ahead and merge.

I'm OK with this being merged.  I haven't merged it myself, because of the comment about cleaning the commit history.

**Comment by Andreea-G** [comment]
Like this?

**Comment by argriffing** [comment]
> Like this?

Yes I think that's what @dlax had in mind. I've merged it! Thanks for your contribution, @Andreea-G.

**Comment by Andreea-G** [comment]
@argriffing Thanks! :)

**Pull request merged**
