### PR TITLE
Update constants.py

### PR DESCRIPTION
**Pull request by mefuller**
#### What does this implement/fix?

Add missing SI prefix for yocto (1e-24, https://physics.nist.gov/cuu/Units/prefixes.html)

### CODE REVIEW

**Review by tupui — CHANGES_REQUESTED** [review]
Thanks @mefuller. It would make it consistent with having the counterpart `yotta`. There is still a failure in the CI which is related.

```
===============
scipy.constants
===============

Non-deprecated objects in __all__: 160
Objects in refguide: 159

ERROR: objects in scipy.constants.__all__ but not in refguide::

    yocto

This issue can be fixed by adding these objects to
the function listing in __init__.py for this module
```

So here

https://github.com/scipy/scipy/blob/e4029e66af17383697c34a519f8a46e52b08eb23/scipy/constants/__init__.py#L111

**Review by mefuller — COMMENTED** [review]
Requested addition to `refguide` made

**Review by tupui — CHANGES_REQUESTED** [review]
Actually doing a search and we can see it needs also to be added here `scipy/_lib/boost/boost/units/scale.hpp` and `scipy/_lib/boost/boost/units/systems/si/prefixes.hpp`. Sorry I don't know this module so just seeing these now. **EDIT** my bad, already there.

**Review by tupui — APPROVED** [review]

**Comment by tupui** [comment]
CI failure is unrelated. I will merge. Thanks @mefuller 😃

**Comment by mefuller** [comment]
Thank you @tupui

**Pull request merged**
