### PR TITLE
BUG: _qmc.py::_random_oa_lhs produces correlated samples

### PR DESCRIPTION
**Pull request by pwcnorthrop**
The variable `oa_sample_` scambles the orthogonal array but is not being used. As a result the sample outputs are highly correlated in higher dimensions and with large samples.

Calling `lhs_engine.reset()` causes identical LHS sampling to be applied in each orthogonal subsection. This creates patterns to arise when observing at larger scales and may result in an aliasing affect. Removing it should improve the random properties of the LHS sampling.

#### What does this implement/fix?

The orthogonal arrays were highly correlated across higher dimensions and not creating samples as expected.

#### Additional information

Minimum code example. Three dimensional sampling, colored by the 3rd dimension:

```
from scipy.stats import qmc
import matplotlib.pyplot as plt

sampler = qmc.LatinHypercube(d=3, strength=2, scramble=True, seed=1)
sample = sampler.random(n=529)

plt.scatter(sample[:,0], sample[:,1], c=sample[:,2])
plt.show()

```
Result before change:
LHS_OA_Test_before_fix

Result after change:
LHS_OA_Test_after_fix

### CODE REVIEW

**Review by tupui — CHANGES_REQUESTED** [review]
Thank you @pwcnorthrop for the detailed report and the PR!

Indeed that felt through the cracks. In the original code I even had the substitution. See the issue https://github.com/scipy/scipy/issues/13659#issuecomment-890511835 and the gist https://gist.github.com/tupui/3b79ecea1631e8925f3d47069d435b0f 

I might have removed that because of MyPy. I don't recall and don't find any info either on my original PR #14546. For the reset part, I am not sure why I did that (https://github.com/scipy/scipy/pull/14546/commits/e8144408286feac554bc5a7c3e8fc4a040379e56).

FYI @kstoneriv3

I think we also might only want to do the `oa_sample_` block if we have `scramble=True`.

Could you also fix the linter? It's not related to your changes but would be nice 🙇

**Comment by pwcnorthrop** [comment]
Yes, there clearly had been thought put into developing and scrambling the OA, but easy enough to slip through the cracks. It isn't obvious in any two dimensions, only when you look at it in 3 dimensions does the pattern emerge. I just appreciate you did the hard thought-work already. 

My opinion is that we would want the `oa_sample_` block regardless of `scamble`. I think avoiding the `oa_sample_` would be like just populating LHS along the diagonal: sure, it technically satisfies the requirement, but it is not what I would expect (though I am not a statistician by any means). Since the inner LHS loop uses the `scamble` parameter, `scamble=False` still ensures the points are centered in the LHS grid. 

I took a stab at the linter error, I think. Changing `.format()` to f-strings if I understood correctly, though I may not actually know what I'm doing.

**Comment by pwcnorthrop** [comment]
@tupui Maybe the `lhs_engine.reset()` should exist but be subject to `scramble=False`?  I could see how the reset forces greater separation in the larger p*p grid by effectively forcing a 1/p distance between points in a given row and in a given column.

**Comment by tupui** [comment]
I mean reset means that the next time we call the engine, it will produce exact the same sample as we it also resets the internal seed.

**Comment by tupui** [comment]
I will give a few more days to @kstoneriv3 to chime in.

@alegresor do you have an opinion?

I will message Art next week if we did not converge by then 😄

**Comment by kstoneriv3** [comment]
I haven't worked on Latin hypercube sampling in a while so I may be very wrong, but I have some comments:

- I think we forgot to permute the columns as pointed out. Thank you for a good catch!!
```python
oa_sample = oa_sample_
```
- It is expected that you see some patterns if you visualize the 3-dimensional marginal of the sample as we use `strength=2`, not `strength=3`. The point of the orthogonal LHS with strength=2 is that the 2-d marginal distribution of the sample looks very evenly distributed. 
- Even though it looks as if properly permuting the columns randomly solves the problem of the correlation in the 3-d space in the above plots, I kind of expect we will still be able to make a similar plot with correlated points, by plotting it with different permutations of the columns by one of 
```python
plt.scatter(sample[:,0], sample[:,1], c=sample[:,2])
plt.scatter(sample[:,0], sample[:,2], c=sample[:,1])
plt.scatter(sample[:,1], sample[:,2], c=sample[:,0])
```
- As for resetting the lhs_engine for the additional (1/p) scale noise, I am indifferent. It looks like I even suggested using standard random numbers there in the past (https://github.com/scipy/scipy/pull/14546/files#r686340327) but keep using the LHS and not resetting the engine sounds more right to me.

So overall I am happy with the PR but not very sure about the correlation in the 3-d space discussed above.

**Review by tupui — APPROVED** [review]
I think it's safe to get this in as it is. Of course we can keep discussing and can always change something. The next release is in a few months so there is no pressure there too.

Thanks again both for your help and nice first contribution @pwcnorthrop 👏 

I am always looking for people to comment on the API, know how people are using these, etc. If you are interested to share or have any feedback, I have this tracking issue #14510 Feel free to post anything there 😃

**Comment by pwcnorthrop** [comment]
Awesome! Thanks, @tupui!

@kstoneriv3 , my understanding is that `strength=2` ensures a close-to-uniform sampling for each 2D projection of the N-D parameter space, sudoku-style,  but that doesn't extend to higher dimensions. I would expect sampling in 3D to be less uniform (random volumes of high or low density due to clustering), but I wouldn't expect a strong correlation. (See figure below with the three permutations of the 3D sampling data). I'd expect similar behavior in higher dimensions. Full acknowledgement that I'm going more on gut-feeling than rigorous statistical analysis, however. 

LHS_OA_Testing_Perm

@tupui, I'll keep that tracking issue in mind if I think of anything. For context, I've been using this to develop an initial population of parameters to develop surrogate models of moderately computationally expensive physics-based models. Roughly 10-15 dimensions, and this has been working quite well for me for that initialization. After the initial generation, I select additional points to perform the full-order simulation based on some criteria, regenerate the surrogate model, and repeat.

**Comment by kstoneriv3** [comment]
@pwcnorthrop Thanks for the visualization! Then, most likely, you are right that some fix in your PR was necessary to make it work properly. Thank you for fixing this🚀

**Comment by tupui** [comment]
> For context, I've been using this to develop an initial population of parameters to develop surrogate models of moderately computationally expensive physics-based models. Roughly 10-15 dimensions, and this has been working quite well for me for that initialization. After the initial generation,

I see, I am also coming from there 😉

Why LHS if I can ask? With 15 dimensions I would have go for Halton or Sobol' if you can get away with a power of 2.

> I select additional points to perform the full-order simulation based on some criteria, regenerate the surrogate model, and repeat.

Sounds like EGO (scikit-optimize has a good implementation). I also did a bit of research there, and resample based on sensitivity indices values estimated by the current surrogate. It worked well for me.

**Comment by pwcnorthrop** [comment]
> Sounds like EGO

It's very similar approach to EGO, for sure. EGO-inspired,  😉. Really, one reason I didn't use EGO directly was that the 3 of the parameters are operational and defined by the experiment and we ran something 50+ distinct operating conditions that I'm trying to fit to. Figured it was easier to build an `Np+3` dimensional surrogate model, rather than `Np` dimensions but needing to run a half-week of simulations for each point. 

> Why LHS if I can ask? With 15 dimensions I would have go for Halton or Sobol' if you can get away with a power of 2.

Honestly, I probably don't have a great justification of LHS. You are probably right that Sobol' or Halton would be the better choice (and you certainly know more than I do about sampling selection). My first time getting into surrogate modeling and I was already familiar with and understood LHS so that was my default. Eventually ran across Sobol' and played with it some. Looking at some of the 2D projections, there were clear patterns (even though, logically I know "looking random" isn't really the goal 😆). And the discrepancy scores didn't seem that different between Sobol' and OA-LHS, though I don't know how much I should worry about that. But ultimately just stuck with the original LHS approach. 

I may end up revisiting that choice if I get a chance. The ability to resample and continue the Sobol' sequence seems like something worth exploring.

**Comment by tupui** [comment]
Very interesting, thanks for sharing 😃 

By the way if it's for academia, we do have a paper for the QMC in SciPy in the Journal of Open Source Software 😅

Just a note on continuing the sampling. Sobol' is tricky as continuing means doubling the number of samples. This is if you want to do things by the book of course and need to ensure a proper sampling to have the right properties. Art Owen even wrote a paper showing that the sequence of Sobol' loses its properties if you remove a single point. Otherwise Halton does not have such limitation.

**Pull request merged**
