### PR TITLE
DEP: remove all deprecated `scipy.<numpy-func>` objects

### PR DESCRIPTION
**Pull request by rgommers**
As evidenced by gh-19065, changes to the contents of numpy's main namespace or `__all__` dict have a direct impact on scipy's main namespace. It may cause warnings, import errors in test suites where warnings get converted to errors directly, and it changes the actual contents of the `scipy` namespace.

The above was always the case, however in the run-up to NumPy 2.0, we can expect a very large amount of changes in NumPy's main namespace. We don't want to expose newly added NumPy functions in the `scipy` namespace, nor have new breakage each time something in numpy gets deprecated or removed. Hence, let's remove these long-deprecated items now. Our deprecation message said "scipy 2.0" as a way of saying "this is not urgent, these things will be removed eventually". However, it has become urgent now (I'll note that the issue in gh-19065 also affected two of our own CI jobs with obscure errors, e.g. see [this CI log](https://github.com/scipy/scipy/actions/runs/5863421186/job/15896853062)). Changing this in SciPy 1.12.0, which will roughly coincide with the NumPy 2.0 release date, should be fine and healthy.

### CODE REVIEW

**Comment by h-vetinari** [comment]
> Our deprecation message said "scipy 2.0" as a way of saying "this is not urgent, these things will be removed eventually". However, it has become urgent now

I don't think that's so self-explanatory; at least it's not ideal messaging:
* we want people to react to deprecation warnings, of course without overwhelming them; some deprecations are also more impactful than others, but 2.0 seems so mythically far off that it probably encourages laziness rather than action
* however it does make an explicit promise, which we then either have to keep (e.g. carry around privatized modules around for a long time[^1]), or break (like in this case), neither of which is ideal IMO.

I think it would be less friction all around to extend the warning period to e.g.  4 releases (rather than 2) for a particularly impactful deprecation, but still provide an explicit date and then execute it. I think that would give a clearer guidance to users (not breaking promises or giving indefinite timelines), and cause less maintenance to keep certain deprecated-in-2.0 bits around for a really long time.

That's less about this PR though, just a comment about the 2.0-situation. If you think it's worth it, we can move this to an issue.

[^1]: this was done in 1.8; how many users do we think have not yet seen this, but will react to it in 1.12+? If that number is low, is it still worth the maintenance effort to keep them?

**Comment by rgommers** [comment]
> I think it would be less friction all around to extend the warning period to e.g. 4 releases (rather than 2) for a particularly impactful deprecation, but still provide an explicit date and then execute it

That's fine with me. That would also match the 2 year window given in https://scientific-python.org/specs/spec-0000/.

**Review by tylerjereddy — APPROVED** [review]
Ok, this stuff was deprecated in [`1.4.0`](https://github.com/scipy/scipy/releases/tag/v1.4.0) almost four full years ago, and so while not ideal that we differ from the messaging on deletion release number, that's a long time for consumers to make straightforward changes. Compounding with the fact that we don't want to continuously maintain a NumPy-namespace-ban-list over the next few months of heavy changes in NumPy, the case to merge seems pretty strong indeed.

The diff looks sensible to me, CI was passing apart from the benchmark fixup that was applied, and branch is passing full suite for me locally as well. Sounds like `conda-forge` release manager is also "ok" with this particular change because of the urgency, with a 4-release wait period for some bigger deprecations like this moving forward.

Some of the testing deleted here is pretty ugly too (running in subprocesses to avoid namespace collisions, etc.), so that's a win as well.

One follow-up is we may want to delete this line in `scipy/__init__.py`:

> SciPy imports all the functions from the NumPy namespace, and in
addition provides:

but that can be snuck into another cleanup PR

**Comment by pllim** [comment]
I would be happy to see if this address the warnings I am ignoring downstream when it is in a nightly wheel. I just need to know when. Thank you, all!

**Comment by rgommers** [comment]
@pllim this may have been enough, but I'll follow up in NumPy, I think these warnings being emitted is turning out to be a bit too disruptive, so I'll fix them there. I'll follow up on gh-19067.

**Pull request merged**
