### PR TITLE
BLD: PEP 440

### PR DESCRIPTION
**Pull request by argriffing**
closes https://github.com/scipy/scipy/issues/4301

### CODE REVIEW

**Comment by ahjulstad** [comment]
To me it appears that PEP 440 requires that development versions start use the suffix `-devN`

Quote from PEP440: 

"The developmental release segment consists of the string .dev , followed by a non-negative integer value. "

The current code also complains: 

```
>c:\appl\Python34\python.exe setup.py config --help

c:\appl\Python34\lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning
: 'numpy (1.10.0.dev-a4cdc5b)' is being parsed as a legacy, non PEP 440, version. 
You may find odd behavior and sort order. In particular it will be sorted as less 
than 0.0. It is recommend to migrate to PEP 440 compatible versions.
```

(Both numpy and scipy use the same approach, it seems).

**Comment by argriffing** [comment]
> PEP440Warning: 'numpy (1.10.0.dev-a4cdc5b)' is being parsed as a legacy, non PEP 440, version.

Yes, the point of this PR was intended to change formats like `1.10.0.dev-a4cdc5b` to formats like `1.10.0.dev+a4cdc5b` to avoid that version comparison error.  I don't know why it's not working in your case, maybe it needs to be changed in more places?

**Comment by pv** [comment]
I think pip wants `1.10.dev0+a4cdc5b`. If you try to `pip install .` Scipy with newest pip+setuptools, you get the complaint
```
    /home/pauli/prj/scipy/scipy/asd/local/lib/python2.7/site-packages/setuptools/dist.py:283: UserWarning: The version specified requires normalization, consider using '0.16.0.dev0+ae24f24' instead of '0.16.0.dev+ae24f24'.
      self.metadata.version,
```

**Comment by ahjulstad** [comment]
I missed the `+` vs `-` issue the first time around. (I had old versions from distutil installs lying around, that was confusing me...)

The message is now:
```
    C:\appl\Python34\lib\site-packages\setuptools\dist.py:283: UserWarning: The
version specified requires normalization, 
consider using '1.10.0.dev0+a4cdc5b' instead of '1.10.0.dev+a4cdc5b'.
```

The PEP requires a number, it seems.

**Comment by josef-pkt** [comment]
(I'm going to free ride in whatever you figure out.)

Thanks

**Pull request merged**
