### PR TITLE
DOC: sparse: 1.14.0 release notes additions

### PR DESCRIPTION
**Pull request by dschult**
I didn't get release notes into the wiki, so I'm suggesting we add some via a PR to the maintenance 1.14.x branch.

These three bullets will help explain the status of the work toward sparse arrays.

### CODE REVIEW

**Comment by lucascolley** [comment]
(for future reference, good to add `[docs only]` or `[skip ci]` into the commit message for PRs like this)

**Comment by tylerjereddy** [comment]
I merged the version bump to RC2 in gh-20839, so once this has been reviewed/approved it is "safe" to merge to the release branch.

**Review by lucascolley — APPROVED** [review]
LGTM, do you want to add a mention of gh-20722?

**Comment by tylerjereddy** [comment]
I think I already got that part, no? 

> Addition between DIA-format sparse arrays and matrices is now faster.

**Comment by lucascolley** [comment]
> I think I already got that part, no?

Indeed, thanks both!

**Pull request merged**
