### PR TITLE
MAINT: DRY up generic computations for discrete distributions 

### PR DESCRIPTION
**Pull request by ev-br**
Reuse a common way of iterating over the support in moment and entropy methods.

### CODE REVIEW

**Comment by rgommers** [comment]
@ev-br this looks reasonable and test coverage for ``moment`` and ``ppf`` seems OK, but it's a bit hard to review in detail. I'm tempted to just hit the green button, but first I have to ask if there's a reason you chose the ``_drv2_ppfsingle`` way for a reason?

**Comment by ev-br** [comment]
@rgommers not sure what you mean, would you elaborate?
I don't think I touched `_drv2_ppfsingle` at all.

**Comment by rgommers** [comment]
> I don't think I touched _drv2_ppfsingle at all.

right, I can't read diffs. I meant the ``expect`` implementation. Basically there were 3 pieces of code doing similar things, and you selected 1 of those over the other 2. So I was wondering if there was a reason for the choice.

**Comment by ev-br** [comment]
Re: ease of review. Maybe it's easier to review individual commits. Generally speaking:

* I separated iterating over the support from the `expect` method into `_expect`, which is easier to put as a free-standing function at the module level.

* then notice that this computation of `sum(f(x) for x in support)` is the same for  `expect`, `moment` and `entropy`, the only difference is the exact form of `f(x)`.

* Then there are two commits, replacing the custom summation with `_expect`, one in `entropy`, one in `moment`.

**Comment by ev-br** [comment]
Why this specific way out of the three, huh. <s>I just like this better because I wrote it.</s>
It iterates in chunks. Basically, you're doing a python sum (which is awkward to fully vectorize) by summing in chunks of N, and for each chunk you use `np.sum`.

**Comment by ev-br** [comment]
and the summation itself was added in https://github.com/scipy/scipy/pull/5153

**Comment by rgommers** [comment]
Clear, thanks! In it goes then.

**Pull request merged**
