### PR TITLE
scipy.stats: numerical stability improvement

### PR DESCRIPTION
**Pull request by jonaballe**
make use of the complementary incomplete gamma functions to improve numerical stability. additionally:
- harmonized np. namespace usage
- np.where can do broadcasting as of now (tested this), so explicit broadcasting shouldn't be necessary.

### CODE REVIEW

**Comment by ev-br** [comment]
While you're at it, it would make sense to add explicit sf and isf methods. A test with broadcasting might also be nice.

**Comment by argriffing** [comment]
After two hours, TravisCI hasn't even started a build.

**Comment by ev-br** [comment]
And when it did start, it timed out on submission to coveralls.

**Comment by argriffing** [comment]
This might seem superficial, but the slowness of the CI pipeline means that the feedback loop for contributors is extending from hours to days. In my opinion this is really bad and could be silently filtering out the most valuable contributions.

**Comment by pv** [comment]
I guess we get what we pay for.

Travis probably schedules things based on how long the runs previously took.
If so, we could just drop most of the Python versions (maybe keep 2.6 and 3.2),
the relaxed strides run etc.

The `tox.ini` could be updated too, so that it's easier to run the same test suite locally.

**Comment by argriffing** [comment]
I'm naive about the business aspects of the scipy stack, but maybe this could be a consideration for the upcoming discussions associated with the scipy conference in Austin?

**Comment by rgommers** [comment]
@jonycgn in https://github.com/scipy/scipy/pull/5005#issuecomment-117354426 @ev-br made a couple of suggestions for further improvement. Those would be nice to have but aren't really necessary to merge this PR. Are you planning on looking at those, or should we merge this as is?

**Comment by jonycgn** [comment]
sorry, i didn't have enough time for following up. last week, i had to come up with a similar fix for the chi distribution, which i think i'll include here. then i think we should merge, because i don't really have the time to look into the other suggestions right now. agreed?

**Comment by rgommers** [comment]
@jonycgn that sounds good to me

**Comment by ev-br** [comment]
Ok, agreed, _sf and _isf can be added later as an easy-fix followup PR

**Comment by ev-br** [comment]
OK, merging. Thank you @jonycgn

**Pull request merged**
