### PR TITLE
ENH: Add functionality to accept descending input for scipy.interpolate.interpn and RegularGridInterpolator

### LINKED ISSUE #11447: scipy.interpolate.interpn: Handle ValueError('The points in dimension %d must be strictly ascending')
**Is your feature request related to a problem? Please describe.**

`scipy.interpolate.interpn` and `RegularGridInterpolator` raises a `ValueError` when the grid (arg `points`) is not strictly ascending in a dimension.

**Describe the solution you'd like**

That points in descending order raise no error but be handled internally.

**Describe alternatives you've considered**

For now, I manage it with code like:
    
    # Assume all points dimension are sorted and have no duplicate values
    slicer = tuple(slice(None, None, None if x[0] <= x[-1] else -1) for x in points) # '<=' is in case len(x) == 1
    points_asc = [x[s] for x, s in zip(points, slicer)]
    values_asc = values[slicer]
    interp = RegularGridInterpolator(points_asc, values_asc)

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
Fix #11447 

#### What does this implement/fix?
Add functionality to accept descending input for scipy.interpolate.interpn and RegularGridInterpolator

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
I close and reopen this PR to rerun CI.

**Comment by rgommers** [comment]
I'm not sure if this is desired behavior. Issue gh-11447 asks to accept descending input, the code in this PR seems to try to handle any input. If inputs points aren't either ascending or descending, it's not unlikely there's a bug in the user's code I'd think.

Let's see what others think.

**Comment by AtsushiSakai** [comment]
Thank you for reviewing. I thought accepting all input was the simplest way, but I might be wrong.
Is there any use-case to input not ascending or descending? If there is not, it is ok for me to close this PR, and I will try to create a new PR.

**Comment by rgommers** [comment]
> Is there any use-case to input not ascending or descending data? 

I tend to say not really - let's leave it open for a little in case someone else does have a valid use case.

**Comment by AtsushiSakai** [comment]
I think there is no use-case to input not ascending or descending data. So, I changed the code just accepting descending data as requested in original issue. PTAL.

**Comment by ev-br** [comment]
Any interest in reviving this @AtsushiSakai ? A quick glance over the code looks good and it seems to fix the OP issue, so why not

**Comment by AtsushiSakai** [comment]
@ev-br Thank you for revisiting this PR. Yes. I can try this again in a new PR.

**Pull request closed without merging**
