### PR TITLE
ENH: cache square of sums for f_oneway

### PR DESCRIPTION
**Pull request by bantmen**
#### Reference issue
n/a

#### What does this implement/fix?
The change is trivial: cache the `_square_of_sums(alldata) / bign` in `f_oneway` to avoid computing it for a second time.

#### Additional information
I could profile the speed impact of the change if there is interest.

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
LGTM pending CI tests. Not sure how much faster it would be, but avoiding a duplicate operation may be more maintainable in any case.

**Comment by tylerjereddy** [comment]
Thanks @bantmen

**Comment by bantmen** [comment]
Thanks for the quick process :)

**Comment by mdhaber** [comment]
Thanks @bantmen! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Pull request merged**
