### PR TITLE
MAINT: sparse: Support tuple input parameters for the shape in `spdiags`

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

For the convenience of users, the sparse diagonal matrix function `spdiags` support tuple input of matrix shape, which is consistent with the input parameter (tuple form) of `diags` (The purpose is to make users no longer need to distinguish whether the shape input parameter is a tuple or just two integers). Because backward compatibility is also considered, shape input parameters of integer type in `spdiags` are still reserved.

### CODE REVIEW

**Review by perimosocordiae — APPROVED** [review]
This maintains backwards compatibility and is a clear usability win. I added a commit with some minor style tweaks, but otherwise I'm happy with this.

I should note that the `diags` function is now recommended in cases where more customization is desired, but improving `spdiags` doesn't detract from that.

**Comment by zhaog6** [comment]
@perimosocordiae Thanks for your review, this code looks better : )

**Comment by zhaog6** [comment]
Dear @perimosocordiae , Could you merge this PR for me? Thank you.

**Comment by perimosocordiae** [comment]
Merged. Thanks, @zhaog6 !

**Pull request merged**
