### PR TITLE
DOC: interpolate: deduplicate docstrings in _fitpack_py and _fitpack_impl

### PR DESCRIPTION
**Pull request by ev-br**
#### What does this implement/fix?

Functions in _fitpack_py are nothing but thin wrappers which dispatch to either BSpline methods or _fitpack_impl FITPACK Fortran wrappers.  Previously, the docstrings were duplicated, and were slightly diverging over time.

So merge the docstrings and deduplicate: move all docstrings to _fitpack_impl/* and attach to _fitpack_py/*.

### CODE REVIEW

**Comment by ev-br** [comment]
Close/reopen to rerun tests

**Review by tupui — COMMENTED** [review]
Thanks @ev-br.

In general I am not sure though about dynamic docs. It does not play well with IDEs usually at it would just present an empty box and not follow the redefinition of `__doc__`.

e.g.
Screenshot 2023-05-01 at 20 02 58

vs
Screenshot 2023-05-01 at 20 03 46

**Comment by ev-br** [comment]
Hmmmm. This is baffling, I've to admit. The manipulation basically happens on import, so should be safe. Anyway.
Do you know how work make it easier for these IDEs? This certainly is not the only place in scipy we construct docstrings at import time, e.g. in stats.distributions. Does your IDE follow what's done over there?

**Comment by ilayn** [comment]
IDEs do the analysis on the source code. If you import something then they go and fetch the imported func docstring. So this is an annoyance only if you are directly working on the SciPy codebase itself with bare functions. Otherwise users will see the full docstring.

**Comment by tupui** [comment]
I am not sure about that. E.g. with stats distributions, it does not render more than what's in the actual docstrings:

Screenshot 2023-05-02 at 11 45 48

This is with PyCharm, maybe some other IDEs behave differently.

**Review by rgommers — APPROVED** [review]
This LGTM once CI is green(er). The IDE issue is an unrelated generic problem and shouldn't block merging this - best to move that to a separate follow-up issue. Probably not much that can be done about that within SciPy though, so it's probably a _wontfix_.

**Comment by tupui** [comment]
> This LGTM once CI is green(er). The IDE issue is an unrelated generic problem and shouldn't block merging this - best to move that to a separate follow-up issue.

I am not blocking the PR. Just pointing out that this has consequences for IDE users.

> Probably not much that can be done about that within SciPy though, so it's probably a _wontfix_.

I don't think we have made a public decision about going one route or the other. Not using any overwrite for `__doc__` would solve the issue (and other issues we have with our own machinery to do so.)

**Comment by ev-br** [comment]
> Just pointing out that this has consequences for IDE users.

This is unfortunate indeed. I guess I wouldn't be surprised if it's a wontfix for pycharm as well, importing stuff online is a big can of worms.

So, to proceed here there are three options:

- keep the status quo. Some 400 lines of duplicated docstrings. Duplicating them was a bad decision (quite a while ago).
- keep this PR as is
- move the docstrings to the functions which end up in the public namespace, i.e. `_fitpack_py.py` + add code comments to point to where the docstrings are. This is IMO slightly worse than the current state of the PR but is likely OK.

**Comment by tupui** [comment]
My preference would be option 3 (moving the doc to the public facing API) as to me private functions can then have more maintainers' oriented docs.

**Review by tupui — APPROVED** [review]
Thank you Evgeni 😃 Diff is also simpler to parse, I don't see anything we should wait for in CI before we merge, I will go ahead.

**Pull request merged**
