### PR TITLE
Fix test fails caused by pytest 7.1.3

### PR DESCRIPTION
**Pull request by andyfaff**
The new pytest release broke some of our test suite. This PR fixes the test suite and will return the CI suite to green-ish.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
I compared this branch with `main` locally (with latest `pytest`/`pytest-xdist`) and did indeed see some nice improvement:

- `main`: `4 failed, 37614 passed, 2237 skipped, 140 xfailed, 8 xpassed, 134 errors in 266.74s (0:04:26)`
- here: `37752 passed, 2237 skipped, 140 xfailed, 8 xpassed in 261.01s (0:04:21)`

I didn't check the changes too closely, but on `main` there were tons of errors related to `nose` support--is that related to your `setup` -> `setup_method` style changes?

I'm not sure there's much we can do about that linter complaint:
`E711 comparison to None should be 'if cond is None:'`

Unless I'm really forgetting something major, I think three are various technical reasons that `is` "ufuncs" don't exist.

**Comment by andyfaff** [comment]
I think the four minpack tests are more smoke tests to check that concurrency can work. There's probably no need to check the return value, but I can rearrange those four tests to eliminate the lint fail.

Setup and teardown had to be changed to setup_method and teardown_method with this version of pytest. This was the majority of the test fails.

**Comment by WarrenWeckesser** [comment]
> I'm not sure there's much we can do about that linter complaint:

The check with the "nonpythonic" use of `== None`,

    assert np.all(np.array(v) == None)

could be written

    np.testing.assert_array_equal(y, None)

or, without NumPy,

    assert all([result is None for result in v])

**Comment by andyfaff** [comment]
@WarrenWeckesser I was going to use the second version in another commit.

**Comment by andyfaff** [comment]
Done

**Comment by andyfaff** [comment]
Ok. Got most of the test breakages fixed now, so am merging. THere's one remaining that is pytest-xdist related.

**Pull request merged**
