### PR TITLE
ENH: sparse.linalg: Add the feature of spectral norm of sparse matrices

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

In this PR, the spectral norm (2-norm and -2-norm) of the matrices are added, the singular values are computed by efficient LOBPCG indirectly.

### CODE REVIEW

**Comment by zhaog6** [comment]
@lobpcg In addition to the above reasons, there is another reason. For `scipy.sparse.linalg.norm`, I just want to obtain the smallest and largest sing. value without introducing additional operations. So I didn't choose `scipy.sparse.linalg.eigen.svds`, although it's easy to call.

**Comment by zhaog6** [comment]
> `svds` should pretty much do exactly the same thing (I wrote the part that adds `lobpcg` to it) as you do in this PR, so I am unsure why there might be a difference in the results, especially for simply computing the single largest singular value.
> 
> The case you provide above is for the smallest singular value, so I am also unsure how it relates to the spectral norm.

Dear Andrew,
In fact, on my server and laptop, `svds` is no problem for the alegbraic accuracy (it is zero exactly), But it reports the accuracy problem (it became 5.3e-8) on the SciPy Github Azure platform.

**Comment by zhaog6** [comment]
> Possible, look at the end of svds code.

@lobpcg I modified the file `_svds.py` and implementation of 2/-2 norm of sparse matrices, Please let me know if it is not a popular implementation way.

**Review by lobpcg — COMMENTED** [review]
You need to make sure that everything works in single precision as well. So you cannot use fixed constants like 1e-14
You also need unit tests in both precisions.

**Comment by zhaog6** [comment]
> You need to make sure that everything works in single precision as well. So you cannot use fixed constants like 1e-14 You also need unit tests in both precisions.

Okay, I try it.

**Comment by lobpcg** [comment]
My suggestion is to try obtaining both values  ~20*np.finfo(np.float64).eps and ~50*np.finfo(np.float32).eps by a single formula f(x) with x=np.finfo(dtype).eps with dtype=np.float64 or np.float32. Try to find experimentally such a fixed function f(x) to handle both cases, if possible.

**Comment by zhaog6** [comment]
> My suggestion is to try obtaining both values ~`20*np.finfo(np.float64).eps` and ~`50*np.finfo(np.float32).eps` by a single formula `f(x)` with `x=np.finfo(dtype).eps` with `dtype=np.float64` or `np.float32`. Try to find experimentally such a fixed function `f(x)` to handle both cases, if possible.

Okay, I'll try to find it, thanks.

**Comment by zhaog6** [comment]
Dear Andrew @lobpcg I make some tests varous platform in Docker, there is no rule for the fluctuation range of the result. However, I find a bug from NumPy when I check the call process in NumPy and SciPy (Notice: the `scipy/sparse/linalg/tests/test_norm.py` file compare the "SciPy norm" and "Numpy norm"). The bug occurs in the `svd` function in `numpy/linalg/linalg.py`
https://github.com/numpy/numpy/blob/ba3664766d1f8c6b2521b82edd717a2f2be974f2/numpy/linalg/linalg.py#L1659-L1661

For a `np.float32` matrix, `s` in line 1660 is `np.float64`, and `s` in line 1661 is converted to `np.float32`, in other words, `_umath_linalg_svd_n` (`gufunc`) computed singular values with `np.float64`, then the type conversion (`np.float64`->`np.float32`) is performed. It is different from `svds` in SciPy (svds->lobpcg->eigh->drv). So SciPy truely implemented it with `np.float32` when given matrix is `np.float32`, but NumPy doesn't seem to be. The above are only the clues I found when debugging, for reference only.

**Comment by zhaog6** [comment]
> Please submit a bug report and the fix, since you have already found it!

Okay, I'll submit the bug report and fix it later. Thanks.

**Comment by lobpcg** [comment]
For the smallest SVD, have a look at https://github.com/scipy/scipy/pull/11829

**Pull request closed without merging**
