### PR TITLE
ENH: vectorize some distance functions

### PR DESCRIPTION
**Pull request by juliantaylor**
as these are reductions they can't be autovectorized by gcc without
adding unsafe-math optimization flags, so vectorize them manually for
SSE2 which is available on all amd64 machines.
This changes the numerical result as the summation ordering is different,
but the change should be only in the order of a few machine precisions.

Also release the GIL during the computations.

### CODE REVIEW

**Comment by juliantaylor** [comment]
most of the other functions could also be vectorized with relatively little effort, though I don't know which ones are most worthwhile to tackle, so I only did those I know about for now, if you know of one which is important I'll be glad to look at it too.

**Comment by juliantaylor** [comment]
as for tests, the existing suite looks good, I intentionally broke lots of parts of the code and the existing tests always failed.

**Comment by larsmans** [comment]
I can't read any of this. Isn't it better to use `#pragma omp simd` or `#pragma simd` (Cilk Plus) for this kind of thing? GCC 4.9 has an option `-fopenmp-simd` (or something like that) to get the former without dragging in `libgomp` and all the rest of OpenMP.

**Comment by larsmans** [comment]
Or in fact: what happens when we do add `-funsafe-math` in the build system, just for this module?

**Comment by juliantaylor** [comment]
with the option (+ -O3/-ftree-vectorize) gcc can vectorize it, but the options are gcc specific while this code works on pretty much all compilers.
Unfortunately it is not recommended to use these semantic changing flags on a per function basis (optimize attribute) so its only whole file or nothing.

**Comment by larsmans** [comment]
I just don't like the idea of multiple code paths, one of which contains thinly disguised inline assembler for a particular platform (even if it's the most popular one). Of course, I'm perfectly ok with releasing the GIL around a big batch computation.

Why is it "not recommended" to do this per function?

And I forgot to ask the main question: what does this buy us? Any profiling results?

**Comment by juliantaylor** [comment]
its not recommended because its full of bugs, mostly it just does nothing. The attribute only really works as intended for non semantic changing flags like optimization levels, unrolling control etc.

performance improves by a factor of 1.5x-2x for appropriate inputs.

e.g.

```
d = np.random.uniform(size=((1000,1000)))
%timeit scipy.spatial.distance.pdist(d)
d = np.random.uniform(size=((3,10000)))
%timeit scipy.spatial.distance.cdist(d,d)
d = np.random.uniform(size=((10000,3)))
%timeit scipy.spatial.distance.cdist(d,d)
```

1 loops, best of 3: 613 ms per loop
10000 loops, best of 3: 115 µs per loop
1 loops, best of 3: 1.15 s per loop

to

1 loops, best of 3: 356 ms per loop
10000 loops, best of 3: 65.3 µs per loop
1 loops, best of 3: 972 ms per loop

**Comment by larsmans** [comment]
Those timings looks nice, especially for high-d. Ping @WarrenWeckesser.

**Comment by jaimefrio** [comment]
How does vectorization compare to using the dot function?

**Comment by juliantaylor** [comment]
the dot is only used for the cosine distance, and it is a vector dot so there is not much more optimization potenzial available, possibly you can squeeze some percent by unrolling and AVX is an option, though its likely memory bandwidth bound too quickly.
Additionally blas libraries typically have very large overheads for small sizes.

So I don't think its that worthwhile to investigate.

**Comment by jaimefrio** [comment]
You are of course absolutely right, sorry for the noise. I think I have seen enough code for today...

**Comment by larsmans** [comment]
Does unrolling this loop give any benefits? I tried it to see if GCC would start vectorizing (nope), but didn't profile the resulting code.

**Comment by juliantaylor** [comment]
it should provide benefit as it breaks a dependency chain allowing the processor to do stuff in parallel, though the cpu might also be able to do that on its own until it reaches the sum so it likely only saves a few cycles. But its probably an interesting experiment.

**Comment by larsmans** [comment]
#4256 replaces the dot product function with a call to NumPy's. I was already having second thoughts because of the hacky implementation.

**Comment by juliantaylor** [comment]
added double hamming vectorization and unrolled the loops once, it gives a relevant 10% performance increase on my i5 haswell. I didn't unroll seuclidean as it has a division in it which to my knowledge can't be efficiently pipelined even in new cpus.

**Comment by juliantaylor** [comment]
I noticed all boolean optimizations of the distance functions are disabled by https://github.com/scipy/scipy/blob/master/scipy/spatial/distance.py#L2005

is this accidental? the git blame does not indicate intention. Assuming distance on booleans are relevant in practice this misses out on significant performance improvements in some areas.

**Comment by rgommers** [comment]
Like @larsmans I'm worried by this. I can't read the code at all, and I think the maintainability hit is not worth it for a factor 1.5x-2x speedup.

Note that we don't really have an official "policy" on this kind of thing, but IIRC we discussed the maintainability/speed tradeoff of ``np.add.reduce`` vs. ``np.sum``, and had a preference for ``np.sum`` - readability over performance.

**Comment by ev-br** [comment]
While I cannot read it either, I'm wondering if there's a way of providing both optimized *and* original versions as fallbacks. Sort of similar to pickle/cpickle, kdtree/ckdtree etc.

**Comment by argriffing** [comment]
I also can't read the code, but if there is a trade-off between readability and performance then isn't scipy a relatively good place to hide this unreadable code from user applications?  Or should it go into a layer like BLAS/LAPACK?

**Comment by larsmans** [comment]
... or still the compiler.

**Comment by juliantaylor** [comment]
its not so bad once you get used to it, its just +-*/ replaced with well documented functions doing the same thing on two doubles at once.
one can write the same vectorized but without the function calls using gccs vector extensions, the only drawback is that its less portable to other compilers. Would you prefer that?

Also note that the non-vectorized fallback is right below the vectorized part, so you can quickly see what the code is doing in case you can't read it.

using unsafe-math-optimziations is also an option, though that requires checking every function in the file if that flag is safe (also it won't work for hamming, that kind of transformation is not available in current gcc)

**Comment by juliantaylor** [comment]
concerning if its worthwhile to speed up, sklearn reimplements some of the functions apparently because they are too slow, so I think its worthwhile to have the generic variants in scipy more optimal even if it goes a bit against readability.

**Comment by larsmans** [comment]
scikit-learn reimplements Euclidean distance also because the one in SciPy doesn't support sparse matrices. It uses a different algorithm that is less numerically stable.

In benchmarks, I've found scikit-learn to be faster for high-d, but SciPy for low-d (think 4× for 3-d space, or something like that).

**Comment by juliantaylor** [comment]
note that these optimizations are only really noticeable for high-d while not slowing down low-d

**Comment by rgommers** [comment]
@juliantaylor if there's a clean way to add this flag (not sure how to best check for gcc in setup.py) that would be preferable I'd think. Or otherwise do nothing. Adding code that cuts the people that are able to maintain it by an order of magnitude is unhealthy imho.

@ev-br that pickle/cPickle style thing is outdated and Python itself doesn't do that anymore.

**Comment by rgommers** [comment]
@juliantaylor and I know it looks easy for you, but for us simple Python programmers who happen to know some C it's a different story.... It's not just about reading the fallback to know what it's doing; if a change to the code is needed both code paths need the same change. So I simply wouldn't be able to touch this code anymore without a lot of effort.

**Comment by rgommers** [comment]
Should we merge the GIL releases and setup.py fix in a separate PR already?

**Comment by jaimefrio** [comment]
I have never jumped down the vectorization intrinsics rabbit hole, but have looked down it a couple of times.

And I think Julian is mostly right: with a template to follow (which his code is providing), and the abundant documentation that can be found googling the function names (e.g. [this](https://software.intel.com/sites/products/documentation/doclib/iss/2013/compiler/cpp-lin/GUID-A41D4DCE-6725-447A-94EB-EA063631762E.htm) and [this](https://software.intel.com/sites/products/documentation/doclib/iss/2013/compiler/cpp-lin/GUID-1CBDFCFA-15BE-4423-8CAA-99C5C425EC7C.htm) for the code in this PR), it is relatively easy to figure out what is being done, and modify it if needed, even if not understanding very well what exactly is going on.

**Comment by rgommers** [comment]
The decision we take here should also be valid for the next times this comes up, so I'd like to hear a few more opinions. @pv @WarrenWeckesser?

**Comment by juliantaylor** [comment]
I'd argue that even the gcc specific feature detection would be more complicated than this. I haven't found any any infrastructure for this in scipy.
The advantage would be that gcc could use AVX automatically if users configure it so, but I doubt many really do this.
Should I just copy numpy configure infrastructure into scipy?

Regardless of helping the compiler or not, I'd like to keep the hamming code as the compiler is unable to do this by itself.
The whole code is really the most basic C code evne if unfamiliar with the basics you should be able to grasp it in detail in a very reasonable time. It is even similar to how numpy itself works, instead of scalar loops you work on vectors, this shouldn't be unfamiliar to python coders.
You also accept new cython code, which is also just C again if you want it fast. I'm not adding any tricky CPython api usage here.

I could add some comments but I consider them very redundant the functions have very clear names:

```c
    /* unroll 4 loop elements */
    for (; i < n - (n & 3); i+=4) {
        __m128d uv1 = _mm_loadu_pd(&u[i]); /* load uv1 = u[i], u[i+1] */
        __m128d vv1 = _mm_loadu_pd(&v[i]); /* load vv1 = v[i], v[i+1] */
        __m128d uv2 = _mm_loadu_pd(&u[i + 2]); /* load uv2 = u[i+2], u[i+3] */
        __m128d vv2 = _mm_loadu_pd(&v[i + 2]); /* load vv2 = v[i+2], v[i+3] */
        __m128d dv1 = _mm_sub_pd(uv1, vv1); /* dv1 = uv1 - vv1 */
        __m128d dv2 = _mm_sub_pd(uv2, vv2); /* dv2 = uv2 - vv2 */
        dv1 = _mm_mul_pd(dv1, dv1);  /* dv1 = dv1 * dv1 */
        dv2 = _mm_mul_pd(dv2, dv2);  /* dv2 = dv2 * dv2 */
        sv1 = _mm_add_pd(sv1, dv1);  /* sv1 += dv2 */
        sv2 = _mm_add_pd(sv2, dv2);  /* sv1 += dv2 */
    }
    sv1 = _mm_add_pd(sv1, sv2); /* sv1 + sv2 */
    s = horizontal_add(sv1);    /* sv1[0] + sv1[1] */
```

**Comment by argriffing** [comment]
```c
sv1 = _mm_add_pd(sv1, dv1);  /* sv1 += dv2 */
sv2 = _mm_add_pd(sv2, dv2);  /* sv1 += dv2 */
```
I assume these comments are typo'd.

**Comment by larsmans** [comment]
I don't think comments add a lot. I take my comment about "thinly disguised assembler" back, because I read up intrinsics and at least register allocation is done by the compiler, so it's less tricky than I thought.

I also looked at how this stuff is implemented by GCC and Clang, and they both support the same [vector extension syntax](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html), so an SSE register is

```c
typedef double __m128d __attribute__((__vector_size__(16)));
```

and multiplication is actually defined as

```c
static __inline__ __m128d __attribute__((__always_inline__, __nodebug__))
_mm_mul_pd(__m128d __a, __m128d __b)
{
  return __a * __b;
}
```

in both compilers. I.e., it looks to me like they're implementing intrinsics by mapping them onto a cleaner API. Would it be feasible to program using these vector extensions directly instead of using the intrinsics? A dot product can be written

```c
typedef double Double2 __attribute__((vector_size(16)));

double dot(const double *a, const double *b, npy_intp n)
{
    Double2 acc = {0, 0};
    double s;
    npy_intp i;

    for (i = 0; i < n - (n & 1); i += 2) {
        acc += (Double2){a[i], a[i + 1]} * (Double2){b[i], b[i + 1]};
    }
    s = acc[0] + acc[1];
    for (; i < n; i++) {
        s += a[i] * b[i];
    }
    return s;
}
```

**Comment by larsmans** [comment]
The inner loop of the above compiles to

```gas
.L3:
	movsd	(%rdi,%rax,8), %xmm0
	movsd	(%rsi,%rax,8), %xmm2
	movhpd	8(%rdi,%rax,8), %xmm0
	movhpd	8(%rsi,%rax,8), %xmm2
	addq	$2, %rax
	cmpq	%rdx, %rax
	mulpd	%xmm2, %xmm0
	addpd	%xmm0, %xmm1
	jb	.L3
```

while the non-unrolled loop by @juliantaylor becomes

```gas
.L3:
	movupd	(%rdi), %xmm1
	addq	$2, %rax
	addq	$16, %rdi
	addq	$16, %rsi
	movupd	-16(%rsi), %xmm2
	cmpq	%rdx, %rax
	mulpd	%xmm2, %xmm1
	addpd	%xmm1, %xmm0
	jb	.L3
```

so it's just the loads that are not optimized by GCC. Clang is smarter and compiles both to

```
.LBB0_2:
	movupd	(%rdi,%rax,8), %xmm0
	movupd	(%rsi,%rax,8), %xmm2
	mulpd	%xmm0, %xmm2
	addpd	%xmm2, %xmm1
	addq	$2, %rax
	cmpq	%rdx, %rax
	jb	.LBB0_2
```

so this seems to be a reasonable option (but I still have to do timings).

**Comment by larsmans** [comment]
The nice thing about this is that we can also set the vector size to a larger value and unroll the loops twice; Clang at least is smart enough to turn unrolled SSE2 loops into AVX instructions when given `-mavx`.

**Comment by juliantaylor** [comment]
yes vector extensions are a bit cleaner, and as you already noticed, the intrinsics in gcc and clang are actually implemented in terms of vector extensions.
While the code is a bit cleaner, the drawback is possibly worse portability.
clang and gcc work, but I do not know if ICC or MSVC support them. But I know for sure that those two do support intrinsics (actually msdn has the best available docs for this stuff).

are you sure clang changes SSE to AVX for you? that is a feature I'd like but never saw in any compiler (including clang), usually what it does is just change the encoding to VEX but still works on the 128 bit xmm registers instead of the larger ymm ones.

**Comment by juliantaylor** [comment]
I'd prefer keeping it as intrinsics as it gives you better control and better googleability about what it does.
E.g. figuring out what a vector extension comparison does it not so easily found and may even depend on the compiler and hardware, while _mm_cmpeq_pd is easy to google and gives a well defined result.

**Comment by larsmans** [comment]
Clang output uses the `ymm` registers, though not in all instructions.

ICC apparently has broken support for these extensions (but is good at vectorizing anyway). MSVC probably doesn't have any of this, so it should be wrapped in some ifdefs (and maybe split out to a common header file; I've seen custom vector operations in `spatial`, `sparse` and `optimize`, and there might be more of them).

**Comment by juliantaylor** [comment]
intrinsics work just fine in MSVC.

let me know when you have made up your mind, my recommendation stays that the method here is the most reliable and simplest option, it works well in numpy and hundreds of other non-gcc specific projects.
Using gcc/clang specific -funsafe-math-optimizations is my second place recommendation as it allows simple reliable transformation to AVX or other hardware but is less reliable (e.g. hamming won't work) and needs distutils hackery.
A third option would be adding a vector class library like agner fog's one. But at this time that seems overkill for this one use.

**Comment by WarrenWeckesser** [comment]
Sorry for being late to the party.  (And be warned that future responses may be similarly non-prompt.)

I'm not against using SSE2 intrinsics in scipy code, but I suspect I'm not the only one with some tutorial-level questions.  (Eventually I might be able to answer the following myself--I'll be experimenting with the code over the next few days.)

Are there potential problems with passing in arrays that are less than ideally aligned?

If this PR is merged, and I build scipy on a machine with SSE2 capability, how do I disable the use of this SSE2 code?  Packagers of binary distributions (e.g. Enthought's Canopy, Continuum's Anaconda) might want to build non-sse versions for general use.

If we merge this, we'll need to modify the Travis CI configuration to run the tests with and without SSE2 enabled.

**Comment by juliantaylor** [comment]
unaligned memory does not matter as the code uses alignment safe instructions which are on machines newer than the core2 have pretty much the same speed.

the sse2 code is only enabled on amd64. sse2 is mandatory for all x86 64 bit cpus so no generic configuration is required. 32 bit builds will not use the code unless explicitly requested via compiler flags (-msse2).

if you want to test the scalar loops beyond the peeling parts required also with sse2 you do need a second configuration explicitly disabling sse2 (or a 32 bit build). I think the loops are so trivial this is not necessary, the scalar loops are still covered and should one wants to change them it is easy to disable the vector loop temporarily (rename the ifdef macro).

**Comment by WarrenWeckesser** [comment]
> if you want to test the scalar loops beyond the peeling parts 

"peeling parts"?  Remember, tutorial level... :)

Trivial code still needs tests.  We have two cases: SSE2 and non-SSE2.  We should be able to run the tests on Travis for these two cases.  I don't have a proposal for *how* to do that at the moment.

**Comment by juliantaylor** [comment]
vectorized loops work on multiple elements in per iteration, the remainder is handled in a scalar peeled loop. Here the peeling loop, the last iteration for odd number of elements, is the same as loop that would be used for disabled SSE2.
If one has to deal with alignment one sometimes also peels the first few iterations of the loop to archive alignment for the main loop.

**Comment by larsmans** [comment]
#4437 is an alternative with GCC vector extension syntax.

**Comment by juliantaylor** [comment]
if you prefer that, I'll update this pr to use them, though then I'll add alignment peeling to not penalize gcc which seems to have trouble with the (Double2){a, b} syntax

**Comment by ewmoore** [comment]
I'm somewhat opposed to requiring this kind of optimization leave MSVC out
in the cold. We have something that is the standard, cross platform
hardware vendor recomended method and we want to move to something that
doesn't work with the default compiler on the worlds most popular
platform?  I think this needs a little more justification.

**Comment by jaimefrio** [comment]
I am +1 on @ewmoore's comment: we Windows users may not be the coolest kids on the block, but it wouldn't be nice to not invite us to the party!

**Comment by rgommers** [comment]
Given the current state of CI (no Windows tests) and limited amount of testing by MSVC users I'd be very worried about breaking MSVC when enabling advanced features like this for it. Half the time master has failures for MSVC even for plainer C changes.

**Comment by juliantaylor** [comment]
these aren't exactly new features, MSVC has them since at the very least 2005

**Comment by matthew-brett** [comment]
Maybe now is a good time to try setting up testing with buildbots e.g at http://nipy.bic.berkeley.edu/builders ?   You can now add extra build status entries to commits on Github: https://github.com/blog/1935-see-results-from-all-pull-request-status-checks

**Comment by larsmans** [comment]
I thought MinGW was the recommended compiler on Windows? Also, can someone check if MSVC doesn't vectorize these loops? The reason for targeting GCC is not only that it's the default on Linux, but also that it's rather bad at autovectorization.

**Comment by juliantaylor** [comment]
fwiw its not bad it just decides to implement the C standard and making performance optimizations configurable. A decision commercial compilers usually don't make so they can win benchmarks (but to be fair the C standard is probably too strict in many cases).

**Comment by sturlamolden** [comment]
I did something similar to cKDTree in #4374, based on @larsmans PR #4437 

ICC could accelerate the loop if it were manually unrolled, but the resulting code was not as fast as using GNU SIMD syntax with clang 3.5.

```C++
// XXX earlier versions of GCC and Clang might work
#ifndef __INTEL_COMPILER
#if ((defined(__GNUC__) && (__GNUC__ > 4))\
    || (defined(__clang__) && ((__clang_major__ >= 3) && (__clang_minor >= 4)))\
    || defined(__APPLE__)) // FIXME: clang defines don't work for clang 3.5 in Xcode
#define SCIPY_SIMD
#endif
#endif // __INTEL_COMPILER
 
inline npy_float64
sqeuclidean_distance_double(const npy_float64 *u, const npy_float64 *v, npy_intp n)
{
    npy_float64 s;
    npy_intp i;
#ifdef SCIPY_SIMD
    // GCC SIMD extension, will be vectorized
    typedef npy_float64 Double4 __attribute__((vector_size(4 * sizeof(npy_float64))));
    Double4 acc = {0, 0, 0, 0};
    for (i = 0; i < n/4; i += 4) {
        Double4 d = (Double4){u[i], u[i + 1], u[i + 2], u[i + 3]} - 
            (Double4){v[i], v[i + 1], v[i + 2], v[i + 3]};
        acc += d * d;
    }
    s = acc[0] + acc[1] + acc[2] + acc[3];
    if (i < n) {
        for(; i<n; ++i) {
            npy_float64 d = u[i] - v[i];
            s += d * d;
        }
    }
#else
    // manually unrolled loop, might be vectorized
    npy_float64 acc[4] = {0, 0, 0, 0};
    for (i = 0; i < n/4; i += 4) {
        npy_float64 _u[4] = {u[i], u[i + 1], u[i + 2], u[i + 3]};
        npy_float64 _v[4] = {v[i], v[i + 1], v[i + 2], v[i + 3]};
        npy_float64 diff[4] = {_u[0] - _v[0], 
                               _u[1] - _v[1], 
                               _u[2] - _v[2],
                               _u[3] - _v[3]};
        acc[0] += diff[0] * diff[0];
        acc[1] += diff[1] * diff[1];
        acc[2] += diff[2] * diff[2];
        acc[3] += diff[3] * diff[3];
    }
    s = acc[0] + acc[1] + acc[2] + acc[3];
    if (i < n) {
        for(; i<n; ++i) {
            npy_float64 d = u[i] - v[i];
            s += d * d;
        }
    }
#endif
    return s;
} 
```

**Comment by sturlamolden** [comment]
I could not make the code with GNU vector extensions compile with ICC 14.0.2, so at least with this compiler it is not supported. ICC is however so good at autovectorization that manually unrolling worked surprisingly well.

I am not sure we should worry too much about MSVC. It cannot build SciPy anyway. But if someone insists on using it anyway there should be plain ANSI C fallback code.

**Comment by rgommers** [comment]
@larsmans we build our official binaries with MinGW (32-bit only until now, 64-bit still in progress), but MSVC is more commonly used. It's what Python itself is compiled with and what is used for Canopy & Anaconda.

**Comment by sturlamolden** [comment]
I believe Anacoda and Canopy are built with ICC.

**Comment by rgommers** [comment]
More in general: we care about performance for common compilers on Windows, OS X and Linux, and care about not breaking any exotic platforms. Just got a numpy build error report for AIX for example....

**Comment by rgommers** [comment]
@sturlamolden MSVC + ifort can definitely build Scipy. I'm not 100% sure about Canopy & Anaconda, but the popular binaries from Christoph Gohlke are definitely built with MSVC. We should care.

**Comment by sturlamolden** [comment]
Ok, that is good to know.

**Comment by sturlamolden** [comment]
How well does autovectorization work with MSVC?

**Comment by sturlamolden** [comment]
Another option is to use Fortran and just let the Fortran compiler take care of the SIMD vectorization. The Fortran subroutine can then be exposed to C through an inline function.

**Comment by sturlamolden** [comment]
For example, if I write the obvious Fortran 2003 code

```Fortran
subroutine sqeuclidean_distance_double(u, v, n, r)
    use iso_c_binding
    implicit none
    integer(c_intptr_t) :: n
    real(c_double) :: u(n), v(n), r
    real(c_double) :: tmp, acc
    integer(c_intptr_t) :: i
    acc = 0
    do i = 1,n
        tmp = u(i) - v(i)
        acc = acc + tmp*tmp
    end do
    r = acc
end subroutine
```

then gfortran 4.8.2 produces this loop:

```
L3:
	vmovsd	-8(%rdi,%rax,8), %xmm0
	vsubsd	-8(%rsi,%rax,8), %xmm0, %xmm0
	addq	$1, %rax
	cmpq	%rdx, %rax
	vmulsd	%xmm0, %xmm0, %xmm0
	vaddsd	%xmm0, %xmm1, %xmm1
	jne	L3
```

:smile:

**Comment by sturlamolden** [comment]
Oh yes, and with Fortran 2003 we can also produce a C callable function directly:

```
function sqeuclidean_distance_double(u, v, n) &
    bind(C, name="sqeuclidean_distance_double")
    use iso_c_binding
    implicit none
    real(c_double) :: sqeuclidean_distance_double
    integer(c_intptr_t), value, intent(in) :: n
    real(c_double), intent(in) :: u(n), v(n)
    real(c_double) :: tmp, acc
    integer(c_intptr_t) :: i
    acc = 0
    do i = 1,n
        tmp = u(i) - v(i)
        acc = acc + tmp*tmp
    end do
    sqeuclidean_distance_double = acc
end function
```

This one has the C signature:

```C
extern double
sqeuclidean_distance_double(const double *u, const double *v, npy_intp n);
```

**Comment by sturlamolden** [comment]
Fortran is still the king of number crunching :smile:

**Comment by juliantaylor** [comment]
how is all this crap more readable than the code that is here right now?

**Comment by juliantaylor** [comment]
as this does not look there is going to be a consensus, its probably best I change it to my option 2, keep code unchanged and use gcc's -funsafe-math-optimizations.
I'd still like to keep the intrinsics for hamming but that should be less contentious as there is only one available option.

But one last note on portability, numpy uses intrinsics since a while and there have been no issues (besides a minor mingw3 issue that was actually caused by being too careful). And numpy is probably built on more obscure platforms than scipy.

**Comment by sturlamolden** [comment]
I guess *readability* is a matter of taste :-)

Personally I think it is wonderful that this loop is compiled to the most optimized AVX code:

```Fortran
    do i = 1, n
        tmp = u(i) - v(i)
        acc = acc + tmp*tmp
    end do
```

To me Fortran is more readable than the SIMD intrinsics because I have used it a lot. SIMD intrinsics are not very readable to me, because I am unfamiliar with them. But that is just my personal perspective.

But regardless of perspective this shows that we sometimes have to beat C with a stick to get the best numerical performance. Fortran compiles to the fastest SIMD-code without any abuse. It is easier to just focus on the code, rather than also worry about the binary code produced by the compiler. There is a reason many scientists love Fortran [even though is is loathed by CS folks].

**Comment by juliantaylor** [comment]
the assembly code you posted shows no sign of vectorization or using AVX besides VEX encoding, all scalar instructions (sd vs pd)

**Comment by sturlamolden** [comment]
As for releasing the GIL, it might not be an advantage as these functions are potentially execute in a very short time. So it might be that some sort of conditional GIL-release depending on ```n``` should be used.

**Comment by larsmans** [comment]
The GIL release has already been merged.

**Comment by sturlamolden** [comment]
Sure, but that doesn't mean its static, and it does not mean it cannot be discussed. I am not against it, I just think there is a valid objection for small values of n.

**Comment by larsmans** [comment]
Of course. NumPy actually has a macro for this, `NPY_BEGIN_THREADS_THRESHOLDED(loop_size)`.

**Comment by sturlamolden** [comment]
Using BLAS might alo be an option. Something like this (not tested):

```C
double
sqeuclidean_distance_double(const double *u, const double *v, npy_intp n)
{
    const int c = 4096; /* magic number */
    double tmp[c];
    double r = 0.0;
    npy_intp i = 0;    
    for (i=0; i<n/c; i++) {
        cblas_dcopy(c, &u[i*c], 1, tmp, 1);
        cblas_daxpy(c, -1.0, &v[i*c], 1, tmp, 1);
        r += cblas_ddot(c, tmp, 1, tmp, 1);
    }
    for (i = (n/c)*c; i<n; i++) {
        double d = u[i] - v[i];
        r += d*d;
    }
    return r;    
}
```

**Comment by sturlamolden** [comment]
The BLAS code works, but at least with Accelerate it is not faster than a simple C loop.

**Comment by sturlamolden** [comment]
And with MKL I only got half the performance I got with Accelerate. So no, BLAS is no good here.

**Pull request closed without merging**
