### PR TITLE
BUG: piecewise polynomial antiderivative

### LINKED ISSUE #4355: PPoly.antiderivative() produces incorrect output
I think this was introduced by #4216--the fix described below may make #4225 unnecessary (or wrong).

    >>> p = PPoly([[1, 0.5]], [0, 1, 2])
    >>> p.integrate(0, 2)
    array(1.5)
    >>> q = p.antiderivative()
    >>> q(2) - q(0)
    2.0

I believe the error is at https://github.com/scipy/scipy/blob/v0.14.0/scipy/interpolate/interpolate.py#L820-L821 which enforces that antiderivative(nu) be continuously differentiable of order nu. It should be nu - 1 instead. (For example, an indefinite integral is in C0.)

### PR DESCRIPTION
**Pull request by argriffing**
closes https://github.com/scipy/scipy/issues/4355

### CODE REVIEW

**Comment by argriffing** [comment]
Is it just me or has TravisCI seemed slower recently?

**Comment by rgommers** [comment]
@argriffing maybe we're getting more impatient:)   I didn't really notice - I'm just happy it's not timing out anymore.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/4336 ;-)

**Comment by rgommers** [comment]
Yeah, but that's on a different server farm.

**Comment by argriffing** [comment]
I may merge this in a few days if there are no more comments.

**Comment by pv** [comment]
I'll check this tonight...

**Comment by argriffing** [comment]
@pv OK I'll plan to not merge this until you've looked at it.

**Comment by pv** [comment]
Yea, I think it's correct now. Third time's the charm...

**Pull request merged**
