### PR TITLE
DOC: Examples for linalg/decomp eigvals function

### PR DESCRIPTION
**Pull request by Tokixix**
Hello!
I've just created some simple examples for eigvals function from linalg module. Can somebody review it? It is my first PR to scipy. If that is correct I will produce more examples and maybe get into some more interesting issues :)

### CODE REVIEW

**Comment by ilayn** [comment]
Hi @Tokixix Thank you for the PR. There is also another PR (#8200) that has examples in the docstrings waiting in the pipeline for all missing funcs in linalg.

If you have other ones waiting from other modules (the list is in #7168) then please add those ones and remove this particular one.  Or we can just push this in and I'll remove it from the other PR.

**Comment by Tokixix** [comment]
@ilayn It is fine. I will just make tests for other modules ;)

**Comment by rgommers** [comment]
@ilayn I kind of like this example, slightly more instructive than yours which produces random eigenvalues rather than 0+1j etc. Merge this and rebase yours?

**Comment by ilayn** [comment]
@rgommers Done :) . Thanks @Tokixix !

**Comment by ilayn** [comment]
Oh and just for the future reference, please make a separate branches to work and send PRs such that your working repo does not interfere with the PRs you have submitted. Once the PR are merged you can safely delete that branch and keep working on other branches.

**Comment by Tokixix** [comment]
@ilayn, @rgommers Thank You very much! I will keep in mind this remark about branch, thanks ;)

**Pull request merged**
