### PR TITLE
CI: temporary gast pin to fix CI (workaround)

### PR DESCRIPTION
**Pull request by andyfaff**
Speculative. I may need to make afew commits to get everything working. Once I've done so I'll squash it to a single commit, which will make it easier to `git revert`. I'm not sure what reverting will do to the git history.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Thanks, this looks like a clear improvement already!

> Once I've done so I'll squash it to a single commit, which will make it easier to `git revert`. I'm not sure what reverting will do to the git history.

it'll just add one more commit that does the revert of the squashed one? perfectly normal for such a situation IMO

**Comment by andyfaff** [comment]
@tylerjereddy this will get CI back up and running 'as normal' for `main`. The remaining fails are from tests that are failing anyway. I didn't touch the last Azure job because it'll be removed soon.

The main thing we don't want to see propagated to any release material is pyproject.toml which has had a temporary gast build dependency added.

Once gast has been fixed it should be simple as `git revert`ing the commit that added the changes. From reading up on the subject it's painless and doesn't affect git history.

**Review by tylerjereddy — APPROVED** [review]
Sounds good to me, feel free to self-merge the temporary workaround until we have a clear decision on the long-term path forward. It actually affects my release branch bug fix work too, but I'm hesitant to take action there just yet until the dust settles.

**Comment by h-vetinari** [comment]
> From reading up on the subject it's painless and doesn't affect git history.

Just to be 100%: pushing and then later reverting a commit will show up in the git history; the revert is just a regular commit that gets added whenever we're ready to do so.

In an ideal world, this wouldn't show up in the development history of scipy, but in the real world, this is a normal occurrence (for projects with less CI coverage like LLVM or the Linux kernel, reverting is a very common occurrence)

**Comment by andyfaff** [comment]
I can build and test locally with https://github.com/serge-sans-paille/pythran/pull/2100, with no gast pins. I would think if that PR gets merged and a pythran release published we should be ok.

**Comment by andyfaff** [comment]
If a pythran release doesn't occur in the next day I'll merge this PR.

**Comment by h-vetinari** [comment]
> If a pythran release doesn't occur in the next day I'll merge this PR.

pythran 0.13 has been released an has arrived on PyPI (not yet in conda-forge, but that's much less urgent for our CI)

**Comment by h-vetinari** [comment]
Seems we might have to (temporarily) pin both pythran and gast, as pythran 0.13.0 still leads to [breakage](https://github.com/scipy/scipy/issues/18390#issuecomment-1530957256).

**Comment by rgommers** [comment]
The `gast` pin should not be needed anymore with the about to be release pythran 0.12.2. And pythran 0.13.1 with the xsimd update is already up on PyPI. So let's verify once 0.12.2 is also out (looks like that's minutes to hours away), but I think we don't need to merge this PR anymore.

**Comment by rgommers** [comment]
I'm re-running the relevant failing jobs (musllinux on Cirrus, the 32-bit Linux job on Azure). And will also have a look at the pre-release job failing 4 tests in `signal.windows`.

**Comment by rgommers** [comment]
The `musllinux` job is okay now - still failing, but only due to the `signal.windows` failures as a result of some change in numpy `main`. The 32-bit Linux build also completed (tests still running). We should be good here after the two `pythran` bug fix releases. Hence I will close this PR. Thanks for investigating @andyfaff!

In the future, I think it'd also be fine to merge a PR like this as soon as it fixes the jobs that it's supposed to be fixing, in case you judge that unbreaking CI is important. Review can happen post-merge.

**Pull request closed without merging**
