### PR TITLE
ENH: interpolate: add rational interpolation

### PR DESCRIPTION
**Pull request by pv**
Implement rational function interpolation in barycentric basis.
These may be useful when interpolating analytic functions.

One remaining question:
- [ ] Should the barycentric formula be written including the node polynomial `l(x) = [\sum u_j/(x-x_j)]^-1`? This is important for barycentric polynomial interpolation, but I'm not sure whether it matters for rational interpolants, cf. http://www.damtp.cam.ac.uk/user/mdw42/webb2012stability.pdf   The denominator in a rational interpolant in general does not sum to `1/l(x)`, so it seems to me there's no way to fix things as suggested in that paper here.
- [ ] add a way to fit low-order rational functions

### CODE REVIEW

**Comment by ev-br** [comment]
What is the relation of this with `misc.pade`, if any?

**Comment by pv** [comment]
`misc.pade` computes rational approximation from known Taylor
coefficients around some point, and represents it in power basis (=
unstable for high orders) rather than in barycentric form. So it's
somewhat different.

**Comment by pv** [comment]
One should here note that there also exist "traditional" rational
interpolant algorithms (Bulirsch-Stoer) --- these are in functionality
equivalent to `lsq_rational` here, and share the same caveats vs.
spurious poles etc.
.
The barycentric form is however numerically more stable, and derivatives
can be more easily calculated (could also be implemented here).

**Comment by mdhaber** [comment]
Superseded by gh-21167.

**Pull request closed without merging**
