### PR TITLE
MAINT: stats: Add the "correct" Frechet distribution

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Fix for https://github.com/scipy/scipy/issues/3258.  This PR is an alternative to https://github.com/scipy/scipy/pull/3275.  The text of the `frechet` distribution docstring was taken from that PR, with only a little editing.  Many thanks to @ligon for getting the work started.

The functions added to `scipy.special._ufuncs` are  `_frechet_pdf`, `_frechet_logpdf`, `_frechet_cdf`, `_frechet_ppf`, `_frechet_sf` and `_frechet_isf`.

The new `frechet` distribution is the distribution that most folks consider *the* Frechet distribution, e.g.:

* [the Fréchet distribution on wikipedia](https://en.wikipedia.org/wiki/Fr%C3%A9chet_distribution)
* [Wolfram's implementation](http://reference.wolfram.com/language/ref/FrechetDistribution.html.en)
* Stuart Coles, *An Introduction to Statistical Modeling of Extreme Values*, Springer (2001)
* P. Embrechts, C. Klüppelberg, T. Mikosch, *Modelling Extremal Events*, Springer (1997)

The old names `frechet_l` and `frechet_r`, which were actually what are conventionally called the Weibull distribution, are deprecated.   To deprecate these, the deprecation decorator is applied to each public  method.  The old implementations of `frechet_l` and `frechet_r` are still available as `weibull_max` and `weibull_min`, respectively.

### CODE REVIEW

**Comment by rgommers** [comment]
The change to ufuncs looks good (clearer than monkeying with ``lazywhere``), and I think this should stay private. Will reply in more detail on the list.

**Comment by WarrenWeckesser** [comment]
This test failure occurs with the master branch of numpy:

```
======================================================================
FAIL: test_wrightomega.test_wrightomega_inf_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 368, in assert_equal
    assert_equal(actuali, desiredi)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 393, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0.0
 DESIRED: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/special/tests/test_wrightomega.py", line 26, in test_wrightomega_inf_branch
    assert_equal(res, 0)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 370, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0j
 DESIRED: 0

----------------------------------------------------------------------
Ran 24231 tests in 475.875s

FAILED (KNOWNFAIL=91, SKIP=1882, failures=1)
```

That test does not seem related to the changes in this pull request.

**Comment by person142** [comment]
I'm becoming more pro "put the stats ufuncs in stats". Not that I think it should be done for this PR; if anything it makes more sense to put them in special for now so that there's something to test on if the switch is made. Maybe worth taking a look at after this is merged.

**Comment by WarrenWeckesser** [comment]
@person142 wrote
>I'm becoming more pro "put the stats ufuncs in stats". 

That's fine with me.  Once this pull request is finished (one more detail to clean up before I remove the WIP prefix), I want to reimplement the `genextreme` functions using ufuncs.  It should clean up a spurious warning that sometimes occurs, and I'm curious to see if it makes a significant difference in the performance of the `fit()` method.

**Comment by WarrenWeckesser** [comment]
I pushed my latest changes.  This is ready for review.

**Comment by WarrenWeckesser** [comment]
I pushed up updated version of the pull request.  Let's see how Travis likes it.

**Comment by WarrenWeckesser** [comment]
I updated the description of the pull request to give a cleaner summary of the changes.

**Comment by rgommers** [comment]
By accident discovered recently that your new ``frechet`` is the same as ``stats.invweibull``: https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.stats.invweibull.html. I don't see that discussed here or in the other PR and issue.

**Comment by WarrenWeckesser** [comment]
> ... your new `frechet` is the same as `stats.invweibull`

Ha!  And I've even read the first sentence on the [Fréchet wikipedia page](https://en.wikipedia.org/wiki/Fr%C3%A9chet_distribution) multiple times!

I'll work on resolving this in a day or so.

**Comment by ligon** [comment]
Careful with the names!  That's what  started this problem to  begin with.
Here's part of the  docstring I wrote for my first effort on this (for
weibull_min):

    Notes
    -----
    The probability density function for `weibull_min` is::

        weibull_min.pdf(x, c) = c * x**(c-1) * exp(-x**c)

    for ``x >= 0``, ``c > 0``.

    Under certain conditions [1], the Weibull distribution is the limiting
    distribution of the minima of a collection of random variables; hence
the
    name `weibull_min` used here.

    More usually called simply the "Weibull" distribution [1]_, [2]_,
    [3]_.  Though [1]_ reports that historically this was also
    referred to as the Frechet distribution, this usage is no longer
    current, and poses a name conflict with the (related) Frechet
    distribution as implemented in scipy.stats (`frechet`).

    The distribution `weibull_min` is mean to be functionally
    equivalent to Mathematica's WeibullDistribution [4]_.

    References
    ----------
    .. [1] Johnson, N.; Kotz, S.; and Balakrishnan, N. Continuous
Univariate Distributions,
           Vol. 2, 2nd ed. New York: Wiley, 1995.

    .. [2] Weisstein, Eric W. "Weibull Distribution." From MathWorld--A
Wolfram Web Resource.
           http://mathworld.wolfram.com/WeibullDistribution.html

    .. [3] http://en.wikipedia.org/wiki/Weibull_distribution

    .. [4]
http://reference.wolfram.com/mathematica/ref/WeibullDistribution.html

**Comment by rgommers** [comment]
@ligon I know we have to be careful, but I'm not sure what your exact point is? In none of the PRs and issue about this has it been pointed out before that ``stats.invweibull`` is identical to what we want for a new Frechet distribution.

**Comment by WarrenWeckesser** [comment]
I'm going to split this into at least two pull requests.  The first will include only the deprecation of `frechet_l` and `frechet_r`.  This is the most important API change, and it should be in 1.0.0.  Adding ufuncs for the Frechet distribution functions (to be used in `invweibull`) will be in a separate pull request.  Later we can discuss whether `frechet` should be added as an alias to `invweibull`.

**Comment by WarrenWeckesser** [comment]
The pull request to deprecate `frechet_l` and `frechet_r` is https://github.com/scipy/scipy/pull/7838

**Comment by rgommers** [comment]
Good idea @WarrenWeckesser

**Pull request closed without merging**
