### PR TITLE
ENH: Add scipy.special.exprel relative error exponential ufunc

### PR DESCRIPTION
**Pull request by rmcgibbo**
Add the relative error exponential, `(exp(x)-1)/x` to scipy.special, as discussed in #4838.

I'm not sure that I did everything correctly with the ufunc machinery, but `$ python runtests.py -v -m full -t scipy/special/tests/test_mpmath.py:TestSystematic.test_exprel` seems to work on my machine.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
I based the implementation on http://www.netlib.no/netlib/slatec/fnlib/dexprl.f. Currently there's only a cython implementation for double precision -- I guess the ufunc machinery creates a single precision wrapper. I could also implement a separate version of the kernel for single precision, but I'm not sure if that's necessary.

**Comment by ev-br** [comment]
Can you comment on the relation of his implementation to `special.boxcox(np.e, x)`?

**Comment by rmcgibbo** [comment]
From the boxcox implementation at https://github.com/scipy/scipy/blob/master/scipy/special/_boxcox.pxd#L5-L9, it looks like that is equivalent to `expm1(x)/x`, which @argriffing pointed out would probably also achieve pretty good precision, similar to this method.

**Comment by argriffing** [comment]
Is this implementation better than `x ? expm1(x)/x : 1`?

**Comment by WarrenWeckesser** [comment]
I think it would be OK to add the `exprel` function.  Several numerical libraries have it (e.g. octave, GSL, SLATEC; google for `exprel function` to see more).

I'd like to see some examples where the implementation in this pull request is more accurate than `expm1(x)/x` or `boxcox(np.e, x)`.  If it isn't more accurate, then we should keep the code simple by implementing `exprel` using one of those expressions.

**Comment by argriffing** [comment]
> I'd like to see some examples where the implementation in this pull request is more accurate

I compared with `mpmath` using a [hypergeometric identity](http://functions.wolfram.com/HypergeometricFunctions/Hypergeometric1F1/03/02/08/0018/) and it looks like `expm1(x) / x` is accurate.

```python
from __future__ import print_function

from functools import partial
import numpy as np
import mpmath

def _f(x):
    if x:
        return np.expm1(x) / x
    else:
        return 1
exprel = np.vectorize(_f)

mpmath_exprel = np.vectorize(partial(mpmath.hyp1f1, 1, 2))

def main():
    for m in np.logspace(-20, 0, num=21):
        x = m * np.linspace(-1, 1, num=21)
        resid = np.max(np.absolute(exprel(x) - mpmath_exprel(x)))
        print(resid)

main()
```

```
0.0
0.0
0.0
0.0
0.0
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
1.11022302462516e-16
1.11022302462516e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
2.22044604925031e-16
```

**Comment by rmcgibbo** [comment]
Both `expm1(x)/x` and the version I implemented pass the test against mpmath.

**Comment by argriffing** [comment]
Is `expm1` not in `libc.math` alongside `log` and `exp`?  If so, it would be slicker to use `expm1`, right?  Or maybe it's not always there... numpy has a backup implementation:
https://github.com/numpy/numpy/blob/maintenance/1.9.x/numpy/core/src/npymath/npy_math.c.src
According to http://en.cppreference.com/w/c/numeric/math/expm1 it is available in C99, so maybe that's too restricted.

**Comment by rmcgibbo** [comment]
Okay, I've updated the PR and rebased to use expm1 instead of the slatec code.

**Comment by argriffing** [comment]
Sorry, I didn't realize that `expm1` was not as portable as `exp`.

**Comment by WarrenWeckesser** [comment]
See `_boxcox.pxd` for an example of the use of `expm1` in a ufunc: https://github.com/scipy/scipy/blob/master/scipy/special/_boxcox.pxd

**Comment by argriffing** [comment]
TravisCI is currently down.

**Comment by ev-br** [comment]
Looks like `x=0` needs special care:

```
>>> from scipy.special import exprel
>>> exprel(0.)
nan
```

**Comment by ev-br** [comment]
Not only `x=0`:

```
>>> boxcox(e, 1e-400)
1.0
>>> exprel(1e-400)
nan
```

(I know, this is borderline pathological, but still)

**Comment by WarrenWeckesser** [comment]
> Looks like x=0 needs special care:

Yes, otherwise `expm1(x)/x` is `0/0` which gives nan.

> Not only x=0:

`1e-400` *is* 0.  The smallest double precision floating point value is `5e-324`, and `expm1(x)/x` gives 1 (correctly) for that value:

```
In [35]: x = 5e-324

In [36]: x
Out[36]: 5e-324

In [37]: expm1(x)/x
Out[37]: 1.0
```

**Comment by ev-br** [comment]
> and expm1(x)/x gives 1 (correctly) for that value:

not universally, it seems: 

```
>>> from scipy.special import exprel, expm1, boxcox
>>> x = 5e-324
>>> x
5e-324
>>> exprel(x)
0.0
>>> expm1(x)/x
0.0
>>> import numpy as np
>>> boxcox(np.e, x)
0.0
```

**Comment by WarrenWeckesser** [comment]
Instead of adding a C function to `cephes/unity.c`, I'd rather see this implemented using cython in a .pxd file, following the relatively recent examples of `_xlogy.pxd` and `_boxcox.pxd`.

**Comment by WarrenWeckesser** [comment]
@ev-br Interesting.  Looks like handling of very small values needs some more investigation.  If you double `x` once or twice, do you get 1?  Do you get one with something close to the smallest normal (i.e. not subnormal [http://en.wikipedia.org/wiki/Denormal_number]) value, `x = 2.2250738585072014e-308`?

**Comment by ev-br** [comment]
Denormals seem to be problematic:

```
>>> x = 2.2250738585072014e-308
>>> for _ in range(10):
...    x = np.nextafter(x, 1.)
...    print x, exprel(x), boxcox(np.e, x), expm1(x) / x
... 
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
2.22507385851e-308 1.0 1.0 1.0
>>> 
>>> x = 5e-324
>>> for _ in range(10):
...    x = np.nextafter(x, 1.)
...    print x, exprel(x), boxcox(np.e, x), expm1(x) / x
... 
9.88131291682e-324 1.0 1.0 1.0
1.48219693752e-323 1.33333333333 1.33333333333 1.33333333333
1.97626258336e-323 1.0 1.0 1.0
2.47032822921e-323 0.8 0.8 0.8
2.96439387505e-323 1.0 1.0 1.0
3.45845952089e-323 1.14285714286 1.14285714286 1.14285714286
3.95252516673e-323 1.0 1.0 1.0
4.44659081257e-323 0.888888888889 0.888888888889 0.888888888889
4.94065645841e-323 1.0 1.0 1.0
5.43472210425e-323 1.09090909091 1.09090909091 1.09090909091
```

This is on a fairly standard 64-bit ubuntu precise machine.

```
>>> np.MachAr(np.float).xmin
2.2250738585072014e-308
```

**Comment by argriffing** [comment]
Added a separate issue for boxcox denormal https://github.com/scipy/scipy/issues/4862.

**Comment by argriffing** [comment]
As @ev-br has mentioned, the implementation is missing the special case `x=0`. Also the formula in the comment is typo'd.

```c
/* exprel(x) = (exp(x) - 1) - 1 */

double exprel(double x)
{
    return expm1(x)/x;
}
```

I don't know all of the pros/cons of making a C function alongside the cephes functions vs. making a Cython function in a .pxd file, but I assume @WarrenWeckesser's suggestion is good.

More test coverage should be added at least for `x=0`.

I can't reproduce @ev-br's problems with denormals either, but I assume it's an actual problem although I'm not sure if it is completely in the scope of this PR.  If http://www.netlib.no/netlib/slatec/fnlib/exprel.f avoids the problems with denormals then that could be a reason to use the slatec code instead of `expm1`.

**Comment by argriffing** [comment]
@ev-br Honestly, to me it looks like `expm1` is just broken for denormals on your system?  Is there a reason `expm1(x)` should not return `x` for such small values of `x`?

On my system I have
```python
>>> x = float.fromhex('0x1.6a09e667f3bccp-53')
>>> y = float.fromhex('0x1.6a09e667f3bcdp-53')
>>> math.expm1(x) == x
True
>>> math.expm1(y) == y
False
>>> np.expm1(x) == x
True
>>> np.expm1(y) == y
False
```
so `expm1(x)` should equal `x` for anything closer to zero than about 1.57e-16.

**Comment by pv** [comment]
Maybe avoid all this problem, and get continuity for x=0 (cf sinc), by
returning 1 for |x|<1e-16?

**Comment by argriffing** [comment]
> Maybe avoid all this problem, and get continuity for x=0 (cf sinc), by returning 1 for |x|<1e-16?

I think this sounds like a good solution.

BTW here are some `expm1`-related glibc bugs, maybe @ev-br is running into something like this?
https://sourceware.org/bugzilla/show_bug.cgi?id=13885
https://sourceware.org/bugzilla/show_bug.cgi?id=16293
https://sourceware.org/bugzilla/show_bug.cgi?id=17678

**Comment by ev-br** [comment]
It's full well possible that this particular system runs into one or more of these glibc bugs.  There are reasons why this system is frozen and I'm sure that's not the only one frozen system out there :-). That being said, I don't have a strong opinion on whether these denormals on semi-broken systems are worth worrying about. In my own code I'd use basically what Pauli said just to be done with it.

Long-term I'd guess it's worth test for and guard against denormals in the whole enchilada, but this can I guess wait until a subsequent PR as long as `x=0` is taken care of.

**Comment by rmcgibbo** [comment]
All of these corner cases are consistent, I think, with the original decision to use the SLATEC code.

**Comment by argriffing** [comment]
I think there's only one corner case (x=0) plus some `expm1` denormal libc bugs, and that something like the following function except in Cython would work.
```c
double exprel(double x)
{
  if (fabs(x) < 1e-16) {
    return 1.0;
  } else {
    return expm1(x) / x;
  }
}
```
I think the SLATEC implementation would be OK too.

**Comment by rmcgibbo** [comment]
I moved the definition into cython using the expm1 implementation, with guard at 10^-16 to return 1.0.

**Comment by rmcgibbo** [comment]
If this implementation makes sense to people, I'll squash the commits.

**Comment by argriffing** [comment]
I can't tell if the test covers `x=0` or the denormals that were failing on some systems.

I was wondering about complex numbers, but this wouldn't have to go into this PR.  Apparently [`cexprl`](http://www.netlib.no/netlib/slatec/fnlib/cexprl.f) is a thing.  If this is added to scipy it should probably not use an extra function.

**Comment by ev-br** [comment]
> I can't tell if the test covers x=0 or the denormals that were failing on some systems.

On the same system: 

```
>>> x = 5e-324
>>> for _ in range(10):
...    x = np.nextafter(x, 1.)
...    print x, exprel(x), boxcox(np.e, x), expm1(x) / x
... 
9.88131291682e-324 1.0 1.0 1.0
1.48219693752e-323 1.0 1.33333333333 1.33333333333
1.97626258336e-323 1.0 1.0 1.0
2.47032822921e-323 1.0 0.8 0.8
2.96439387505e-323 1.0 1.0 1.0
3.45845952089e-323 1.0 1.14285714286 1.14285714286
3.95252516673e-323 1.0 1.0 1.0
4.44659081257e-323 1.0 0.888888888889 0.888888888889
4.94065645841e-323 1.0 1.0 1.0
5.43472210425e-323 1.0 1.09090909091 1.09090909091
>>> 
>>> exprel(0)
1.0
```

So `exprel` seems to be fine at `x\to\infty` now. Still I'd say a simple test would be good. Just `assert_allclose(exprel(0), 1.0, rtol=1e-14)`  or equivalent.

One other corner case is 
```
>>> exprel(1e300)
inf
>>> exprel(np.inf)
nan
```

I guess it's just because `expm1(inf)` is `inf`, and inf/inf is nan even though the limit of `x\to\infty` is surely an inf. Since `boxcox` suffers from exactly the same issue, I'd not hold it against this PR, and these two might be better taken care of at the same time, in this PR or a separate one.

**Comment by argriffing** [comment]
> If this implementation makes sense to people, I'll squash the commits.

Sure, the other stuff (limits towards infinity, complex numbers, more unit tests, analogous fixes for other special functions) could be deferred to a later PR.

**Comment by caos21** [comment]
The implementation of this (Bernoulli) function and the limits could be useful, I found this function often in transport simulations.

**Comment by argriffing** [comment]
@caos21 If this PR starts to look abandoned, it will be commandeered :)  But I expect @rmcgibbo will revisit it soon.

**Comment by rmcgibbo** [comment]
I'm on vacation currently. I'll be back soon and fix it up :)

**Comment by rmcgibbo** [comment]
I updated the PR to rebase onto the current master, get the behavior right with infinity, and add a couple explicit tests at and around zero.

**Comment by ev-br** [comment]
LGTM. Squashed and merged in https://github.com/scipy/scipy/commit/89d32a866bc5a66862fab30be886e5becb98dda9. Thanks @rmcgibbo, all

**Comment by WarrenWeckesser** [comment]
@rmcgibbo Thanks (and thanks also to the reviews and mergers).

**Comment by rmcgibbo** [comment]
No problem. Really fantastic code review from everyone!

**Pull request closed without merging**
