### PR TITLE
CI: Pin ninja==1.10.2.4 to avoid bug in 1.11.1 that breaks meson.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
See github issue gh-17350

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @WarrenWeckesser.

The conda-forge macOS build is not happy with the pin:
```
Encountered problems while solving:
  - nothing provides requested ninja 1.10.2.4
```

And there are other failing jobs that are unhappy that the pin is missing.

**Comment by rgommers** [comment]
We can merge this when it's green; the breakage is bad enough that I assume the Ninja release will be yanked as soon as the maintainer wakes up.

**Comment by WarrenWeckesser** [comment]
With the last change that I pushed, we're back to just the known failure of `macos_arm64_test` on Cirrus.  This might not be the smallest change that would avoid the issue with ninja 1.11.1, but it is harmless to use it where we don't stricly have to.  We'll revert this change as soon as a fixed version of ninja is released, so it is probably fine to go with this for now.

**Review by tylerjereddy — APPROVED** [review]
The discussion in the matching issue suggests the problem may now be gone with a newer manylinux version binary now available on PyPI, but I'll go ahead and merge until we test that for sure.

**Pull request merged**
