### PR TITLE
ENH: Use fromfile where possible

### LINKED ISSUE #12176: cannot modify the slice of an array returned by `wavfile.read`
Trying to modify the slice of an array returned by `wavfile.read` results in a `ValueError: assignment destination is read-only`:

#### Reproducing code example:

```
from scipy.io import wavfile

fs, snd = wavfile.read("snd.wav");
snd[:,0] = snd[:,0] * 0.5
```

#### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/media/ntfsShared/otherNoSynch/tmp/pychoacoustics_wav_bug/test.py in <module>()
      2 
      3 fs, snd = wavfile.read("snd.wav");
----> 4 snd[:,0] = snd[:,0] * 0.5
      5 

ValueError: assignment destination is read-only

```

#### Scipy/Numpy/Python version information:

```
In [4]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

```

### Comments
The issue disappears if before performing operations on a slice the whole array is multiplied or divided by 1 as in the example code below:

```
from scipy.io import wavfile

fs, snd = wavfile.read("snd.wav");
snd = snd*1
snd[:,0] = snd[:,0] * 0.5 #now works fine
```
The issue is occurring on Debian Buster with Python 3.7.3 (default, Dec 20 2019, 18:57:59) and scipy version '1.1.0'. The issues does not occur on Debian Stretch with Python 3.5.3 (default, Sep 27 2018, 17:25:39) and scipy version '0.18.1'.

### LINKED ISSUE #12483: reading .wav fails when the file is too big on python 3.6.0
Running this on python 3.6.0:

```python
from scipy.io import wavfile
sampleRate, audioData = wavfile.read("output.wav")
```

gives this error:

```
Traceback (most recent call last):
  File "/Users/wyattblue/test.py", line 34
    sampleRate, audioData = wavfile.read("output.wav")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/io/wavfile.py", line 592, in read
    is_big_endian, mmap)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/io/wavfile.py", line 408, in _read_data_chunk
    data = numpy.frombuffer(fid.read(size), dtype=dtype)
OSError: [Errno 22] Invalid argument
```

output.wav is a 4 hour wavfile. This error doesn't occur when the file is only about 40 minutes long.
This error did not happen when I ran the same code with the same file but on python 3.8.3. I didn't test any other python version.

With some experimentation, I found out that `fid.read(size)` is causing the error but I don't know why.

To get the same file that I have, get ffmpeg and youtube-dl and run this code:

```python
import subprocess

cmd = ["youtube-dl", "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4",
       "https://www.youtube.com/watch?v=od-6uhIMRDQ", "--output", "video.mp4"]
subprocess.call(cmd)

cmd = ['ffmpeg', '-i', myInput, '-ab', '160k', '-ac', '2', '-ar', 
       '48000', '-vn', f'output.wav', '-nostats', '-loglevel', '0']
subprocess.call(cmd)
```

#### Notes
Both python versions are 64-bit
I am using the latest scipy version.

### PR DESCRIPTION
**Pull request by larsoner**
Try to use `np.fromfile` if possible to load the data so that the result is writeable. Add a note mentioning when it won't be.

Closes #12176
Closes #12483

@endolith WDYT? If we can get this in within the next couple of days it could maybe make 1.5.0.

### CODE REVIEW

**Comment by endolith** [comment]
I don't have an opinion on this, I have always just made copies while modifying things

**Comment by endolith** [comment]
Note that https://github.com/X-Raym/wavfile.py/commit/7742bb0d1f49ace84b49ef8379f78efbe0a3f15d#diff-ff5dc7839160fb901e1df7a103f80ba5R77 does this too

**Comment by endolith** [comment]
I guess the benefit of frombuffer is that it doesn't use any extra memory if the file is already open and you're not modifying it?  And if you want to modify it you can make a copy explicitly?  But most of the time you'll be loading from disk in which case they use the same amount of memory?

**Comment by larsoner** [comment]
> I guess the benefit of frombuffer is that it doesn't use any extra memory if the file is already open and you're not modifying it?

Do you envision cases where the current code using `frombuffer` will use less memory than this version (which tries `fromfile` first then resorts to `frombuffer)? In the case of fully loaded BytesIO for example, `fromfile` won't work and the code will end up using `frombuffer` anyway. So it should be the same memory requirement there. And for actually reading from a `fid` which actually points to a file on disk, it should be the same amount of memory use either way.

> And if you want to modify it you can make a copy explicitly? But most of the time you'll be loading from disk in which case they use the same amount of memory?

In the common use case of wanting to read a file from disk them modify, you are currently required to do `read_wav(...).copy()`, which will have double the memory requirement (two copies in memory until the first gets garbage collected) compared to this PR, where a single writable one is made by `fromfile`.

**Comment by endolith** [comment]
> Do you envision cases where the current code using frombuffer will use less memory than this version (which tries fromfile first then resorts to frombuffer)? In the case of fully loaded BytesIO for example, fromfile won't work and the code will end up using frombuffer anyway.

Oh, no, I was just trying to figure out why it would use `frombuffer` in the first place.  I guess that wouldn't be a benefit, then.

> compared to this PR, where a single writable one is made by fromfile.

Ok.  For 24-bit (or other non-{8, 16, 32} bit depths output as right-justified ints or float), it's going to need to make a copy anyway to convert it.

**Comment by larsoner** [comment]
@endolith happy with this one ?

**Comment by endolith** [comment]
It looks ok to me?

**Review by rgommers — APPROVED** [review]
LGTM, thanks @larsoner

**Pull request merged**
