### PR TITLE
ENH: Change COO reshape to not overflow

### PR DESCRIPTION
**Pull request by drhagen**
PR for #8912.

### CODE REVIEW

**Comment by pv** [comment]
Test?

**Comment by drhagen** [comment]
I discovered that the approach laid out here is fundamentally flawed. It only protects from overflow in some instances, but not others. In the main thread, I proposed simply elevating the intermediate indexes to int64 when needed. I'll update this PR when I get the time to implement that.

**Comment by pv** [comment]
Let's go with a new PR when you find time to update it (so that we get less inactive PRs in the list).

**Comment by drhagen** [comment]
Can this PR be reopened? I have committed a new solution and would like to see how it looks on CI.

**Comment by ilayn** [comment]
It says *this branch is force-pushed or recreated* and doesn't allow for reopening.

**Pull request closed without merging**
