### PR TITLE
MAINT: 1.7.0 backports before rc1

### PR DESCRIPTION
**Pull request by tylerjereddy**
I'll update the release notes/re-milestone things when this is otherwise ready to merge. Because of the long weekend here in the US I may try to bump `rc1` forward slightly from Saturday to early-mid next week instead of trying to rush it tonight.

Currently included:

- gh-14146
- gh-14164
- gh-14166 (not yet merged to `master`)
- gh-13925

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Ok, I've updated this backport PR based on the updates over the weekend, along with corresponding updates to the `1.7.0` release notes (pretty minor changes).

So, if CI is green and I don't see any objections I'll go ahead and self-merge this later this evening so that release candidate process can move forward.

**Comment by tylerjereddy** [comment]
@rgommers The nightly CPython `3.10` CI job is failing at least 1 test with a core dump--should we simply ignore that for the release branch here or should we go one step farther and adjust this down in` setup.py`:  `python_maxversion = '3.10'` (it looks like `pyproject.toml` is already `<3.10` from gh-14145).

The rbf test failure is once again causing problems--I've asked for either a resolution or permission to selectively disable it on Windows in a new issue here: https://github.com/scipy/scipy/issues/14158

The pre-release dependencies Azure CI failure has been described in a new issue here: https://github.com/scipy/scipy/issues/14159

Perhaps some of these things are safe to ignore on the release branch, but let's see if I get a bit more guidance on some of these failures tomorrow.

**Comment by rgommers** [comment]
> @rgommers The nightly CPython `3.10` CI job is failing at least 1 test with a core dump--should we simply ignore that for the release branch here or should we go one step farther and adjust this down in` setup.py`: `python_maxversion = '3.10'` (it looks like `pyproject.toml` is already `<3.10` from [gh-14145](https://github.com/scipy/scipy/pull/14145)).

We don't need to even run py3.10 CI for the `maintenance/1.7.x` branch, since Python 3.10 is not supported. Let's just change it to `3.9`.

> The pre-release dependencies Azure CI failure has been described in a new issue here: #14159

I'll comment there.

**Comment by tylerjereddy** [comment]
Ok, well I've added more backports (the list of backports in the original comment has been updated).

Somewhat unusually, I've backported one PR that hasn't yet been merged to `master`, but it is just for CI-related matters (I'm looking for the two pre-release CI entries to SKIP when targeting a maintenace branch).

So, when CI finally finishes looking for:
- no Windows failures from the new RBF test stuff b/c of a new backport
- a skip for the GitHub actions pre-release run (I can see this has happened already, so that's good) from backport config change
- a skip for the Azure pipelines pre-release run from backport config change

**Comment by tylerjereddy** [comment]
Ok, CI is finally green & I did another pass over the diff and I don't see anything unexpected sneaking in so I'm going to merge and see if I can move forward to try rc1 wheel builds today or tomorrow.

**Pull request merged**
