### PR TITLE
DOC: optimize: typo/import fix in linear_sum_assignment

### PR DESCRIPTION
**Pull request by ev-br**
Just a typo and a missing import in the docstring of `linear_sum_assignment`.

### CODE REVIEW

**Comment by ewmoore** [comment]
I guess the PR I merged this morning predates that check then?  Thanks for
fixing this.

**Comment by ev-br** [comment]
[shrug] apparently it does.
I  just happened to be looking at doctests.

**Comment by larsmans** [comment]
Oops! Thanks for the fix.

**Comment by Punit200320** [comment]
Hello, I am interested in contributing to SciPy.

I have started exploring the code related to this issue and I am currently setting up 
the development environment to reproduce the problem.

If the issue is still open, I would like to work on it and submit a fix.
Any guidance on the relevant files or modules would be helpful.

**Pull request merged**
