### PR TITLE
ENH: Add maskandscale support to netcdf; based on pupynere and netCDF4

### PR DESCRIPTION
**Pull request by efiring**
The changes are mostly from pupynere, but modified slightly to fix a bug and to match the rounding behavior of netCDF4-python.  I added a test.

### CODE REVIEW

**Comment by pv** [comment]
Thanks, looks good to me.

**Comment by efiring** [comment]
Thanks, @pv.  And thanks to @rgommers for the suggestion that led to the PR.

**Comment by rgommers** [comment]
Thanks for fixing this Eric. FWIW, I agree with your [suggestion](https://bitbucket.org/robertodealmeida/pupynere/issues/8/python-3-port) to develop in Scipy instead of in Pupynere. Pupynere doesn't have any new commits in the last 2.5 years, so in practice I guess the risk of Scipy falling behind again is small.

**Comment by efiring** [comment]
@rgommers There are still some differences that might be improvements in pupynere, but that I didn't understand, so I didn't try to port them.  There are also two modified versions in the MITgcm ocean/atmosphere numerical model codebase (http://mitgcm.org/viewvc/MITgcm/MITgcm/utils/python/MITgcmutils/MITgcmutils/ yes, it's CVS...).  I don't know whether any of the larger changes made there are things that should be ported, but there is one small change that probably makes sense for us right away: the use of OrderedDict when available.

**Comment by rgommers** [comment]
Change to OrderedDict makes sense. I'll open an easy-fix issue for it, many of those get picked up quickly lately.

**Comment by billsacks** [comment]
@efiring : I was happy to see mask support added - thank you! However, I'm wondering if np.ma.masked_values is really the right function to use in __getitem__. I think masked_equal would be more appropriate here, since masked_values masks any value that is "close" to the given _FillValue. Most (all?) netcdf utilities I have worked with only apply the _FillValue to array values that are identical to the given _FillValue (down to the last bit).

For example:

```
x = [0, 1e-10, 1e-5]

xm = ma.masked_values(x, 0)

xm
Out[390]: 
masked_array(data = [-- -- 1e-05],
             mask = [ True  True False],
       fill_value = 0.0)
```

I would expect the second array element to NOT be masked here.

**Comment by pv** [comment]
@billsacks: please open a new issue, comments added to closed ones are easily forgotten

**Comment by billsacks** [comment]
@pv : thanks - opened as issue #5626

**Pull request merged**
