### PR TITLE
MAINT: signal: replace `np.r_["-1", arrays]` by a more sane incantation

### PR DESCRIPTION
**Pull request by ev-br**
TIL that `np.r_[]` accepts string arguments. Moreover, if the first argument is a string like `"-1"` it is interpreted as the axis along which to stack the other arguments. Ugh. 

Quoting https://numpy.org/doc/stable/reference/generated/numpy.r_.html : 

> A string integer specifies which axis to stack multiple comma separated arrays along. A string of two comma-
> separated integers allows indication of the minimum number of dimensions to force each entry into as the second 
> integer (the axis to concatenate along is still the first integer).

So this PR removes this usage from `signal.findfreqs`. Furthermore, use the fact that the inputs to `findfreqs` are documented to be 1D, so use that to simplify manipulations a bit.

And while I'm looking at this function, replace explicit `numpy.` with a more standard `np.`

### CODE REVIEW

**Comment by ilayn** [comment]
Apart from the lint error, this looks good to me. It's a rather naive way of computing things anyways, typically you have to jump much more hoops ala https://github.com/ilayn/harold/blob/main/harold/_frequency_domain.py#L162-L341

**Comment by ev-br** [comment]
Lint error is hopefully fixed now. 

> typically you have to jump much more hoops ala https://github.com/ilayn/harold/blob/main/harold/_frequency_domain.py#L162-L341

Ouch. 

The goal here (and my several other signal MAINT pull requests) is to keep strict backwards compat and only clean up most egregious things.

**Comment by ilayn** [comment]
Fully agree, I raised this issue on mailing list some years ago, but scipy.signal.lti is what it is :) There is not much interest or residents for it.

**Comment by ilayn** [comment]
I'd say let's click the button once the CI is done

**Comment by ilayn** [comment]
debug atlas failure is typical we can ignore that but the other one I don't know if it is relevant or not. If not please feel free to put this in

**Review by tylerjereddy — APPROVED** [review]
This has a core dev approval if the MacOS ARM64 failures are unrelated, which I've confirmed they are (I see them elsewhere).

This looks like a modest simplification, and also slightly improves conformance with array API standard re: `round` vs. `around` I think.

**Pull request merged**
