### PR TITLE
MAINT: Fix two spots that depend on ravel always being 1-D.

### PR DESCRIPTION
**Pull request by charris**
These problems were revealed by tests against the numpy changes to ravel
to preserve subtypes.  That change will now be special cased for
matrices to avoid backward incompatibilities, but it might be good to
have these fixes in scipy as a guard against the future.

There may be other trouble spots, this only covers those revealed by the scipy tests.

### CODE REVIEW

**Comment by rgommers** [comment]
A quick search shows several uses of ``np.ravel`` in ``sparse/bsr.py``.

I'm not sure this change is well justified. ``np.matrix`` behavior shouldn't change, so is it right for other ``ndarray``-like inputs (and are those even supported by ``sparse``...)? If there's no good reason for this change, then it's just extra clutter/overhead.

**Comment by charris** [comment]
There are a ton of uses of ravel in sparse, but those two spots specifically deal with matrices and caused errors. That said, it wouldn't bother me at all if this PR is closed, I just wanted it out there.

**Comment by rgommers** [comment]
I meant specifically ``np.ravel``, there aren't tons:

    $ grin "np.ravel"
    ./base.py:
      335 :             result = self._mul_vector(np.ravel(other))
    ./bsr.py:
      288 :                                   np.ravel(self.data), y)
      382 :                          np.ravel(self.data),
      385 :                          np.ravel(other.data),
      564 :            np.ravel(self.data),
      567 :            np.ravel(other.data),
    ./tests/test_base.py:
     2430 :         desired_cols = np.ravel(mat.sum(0)) > 0

The ``ravel`` method is used more, but is not under discussion at the moment. 

I wouldn't mind if this got merged anyway, so let's see what others think.

**Comment by charris** [comment]
@rgommers so the suggestion is to fix the other uses of `np.ravel`? I can do that.

**Comment by rgommers** [comment]
@charris the suggestion is to at least check those ``np.ravel`` calls. I haven't looked at this in too much detail yet.

**Comment by charris** [comment]
I've checked all of scipy, and replaced `np.ravel` by the method. That may seem counter-intuitive, but everthing should be safe and there will be no changes to the method. I'm a bit unsure of the `bsr` changes, so might be worth having @pv take a quick look at it.

A check for `np.diagonal` turned up nothing of interest, but `np.diag` is pretty widely used, mostly for constructing diagonal arrays, but not always. It hasn't caused any problems yet, but I could make a similar PR for it.

**Comment by charris** [comment]
Oh, and Cython looks good also.

**Comment by charris** [comment]
Closing this, as numpy is going to keep ravel and diagonal backcompatible for matrices

**Pull request closed without merging**
