### PR TITLE
MAINT: stats: consistently return NumPy numbers

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Part of gh-14651
As noted in https://github.com/scipy/scipy/pull/17971#issuecomment-1430516925

#### What does this implement/fix?
_Note: this is a pretty obscure issue, but fortunately it's also very safe and simple to address. Might as well._

Most `stats` functions naturally return NumPy numbers (e.g. `np.float64`), which are drop-in replacements for the Python versions (e.g. `float`) but with desirable attributes. This should be consistent in functions that are wrapped by the `_axis_nan_policy` decorator, since its job is to ensure consistency. This PR adds a test for this condition. 

There is not perfect consistency yet because for various reasons, the decorator doesn't interfere with what the function wants to do in certain cases (e.g. 1D input with no NaNs), and some functions return Python floats. There are two common causes:
- use of `.item()` with 0D arrays, (fixed here). 
- returning `np.nan`, which (surprisingly) is a Python float (not yet fixed here). 

I wanted to wait for feedback before handling the latter case. Until we're ready for the decorator to get involved in all cases, the easiest fix is to change the individual functions. Another possibility is to ignore the inconsistency. If you're willing to review, let me know what you'd like to see.

<details>
I skipped running CI here because we still have several failures.

```
=================================================================== short test summary info ====================================================================
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-kruskal-args0-kwds0-3-2-False-None] - AttributeError: ...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-wilcoxon-args3-kwds3-2-2-True-<lambda>] - AttributeErr...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-wilcoxon-args4-kwds4-1-2-True-<lambda>] - AttributeErr...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-wilcoxon-args5-kwds5-1-3-True-<lambda>] - AttributeErr...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-iqr-args10-kwds10-1-1-False-<lambda>] - AttributeError...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-ttest_rel-args19-kwds19-2-7-True-unpack_ttest_result]
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[all_nans-omit-mode-args20-kwds20-1-2-True-<lambda>] - AttributeError...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-kruskal-args0-kwds0-3-2-False-None] - AttributeError...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-wilcoxon-args3-kwds3-2-2-True-<lambda>] - AttributeE...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-wilcoxon-args4-kwds4-1-2-True-<lambda>] - AttributeE...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-wilcoxon-args5-kwds5-1-3-True-<lambda>] - AttributeE...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-iqr-args10-kwds10-1-1-False-<lambda>] - AttributeErr...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-ttest_rel-args19-kwds19-2-7-True-unpack_ttest_result]
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-propagate-mode-args20-kwds20-1-2-True-<lambda>] - AttributeErr...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-kruskal-args0-kwds0-3-2-False-None] - AttributeError: 'fl...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-wilcoxon-args3-kwds3-2-2-True-<lambda>] - AttributeError:...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-wilcoxon-args4-kwds4-1-2-True-<lambda>] - AttributeError:...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-wilcoxon-args5-kwds5-1-3-True-<lambda>] - AttributeError:...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-iqr-args10-kwds10-1-1-False-<lambda>] - AttributeError: '...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-ttest_rel-args19-kwds19-2-7-True-unpack_ttest_result] - A...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-omit-mode-args20-kwds20-1-2-True-<lambda>] - AttributeError: '...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-kruskal-args0-kwds0-3-2-False-None] - AttributeError: 'f...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-wilcoxon-args3-kwds3-2-2-True-<lambda>] - AttributeError...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-wilcoxon-args4-kwds4-1-2-True-<lambda>] - AttributeError...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-wilcoxon-args5-kwds5-1-3-True-<lambda>] - AttributeError...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-iqr-args10-kwds10-1-1-False-<lambda>] - AttributeError: ...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-ttest_rel-args19-kwds19-2-7-True-unpack_ttest_result] - ...
FAILED ..\..\scipy\stats\tests\test_axis_nan_policy.py::test_axis_nan_policy_axis_is_None[empty-raise-mode-args20-kwds20-1-2-True-<lambda>] - AttributeError: ...
================================================================ 28 failed, 224 passed in 2.56s ================================================================
```

</details>

Note to self: followup in https://github.com/mdhaber/scipy/tree/gh17971b

### CODE REVIEW

**Comment by tirthasheshpatel** [comment]
> I wanted to wait for feedback before handling the latter case. Until we're ready for the decorator to get involved in all cases, the easiest fix is to change the individual functions. Another possibility is to ignore the inconsistency. If you're willing to review, let me know what you'd like to see.

I am OK with both, really. But I prefer the approach in [your follow-up](https://github.com/mdhaber/scipy/commit/2975006c758c9122876b817de320824d2b7ee8de) i.e. handling dtype in the decorator itself. The diff looks simple enough. Are you planning to add that commit here?

**Comment by mdhaber** [comment]
Thanks @tirthasheshpatel. Unfortunately, that commit doesn't resolve this issue, which is about the dtype of NaNs currently returned *by the functions* for 1D inputs. That commit fixes the dtype of NaNs returned *by the decorator*, but the decorator does not currently get involved with the output dtype for 1D inputs without NaNs.

At some point, yes, we will want the decorator to get involved in this case, but I don't want to do that yet. I think we need a more careful study of dtypes returned by these functions before we start altering them. For instance, if they are upcasting dtype for real (non-NaN) outputs unnecessarily, I want to know about it and fix it rather than hide it with the decorator. Some more careful study of the functions themselves is still needed; this is just doing some relatively safe things on the periphery of that topic.

Let me see how bad the diff is if I manually correct all these.

**Comment by tirthasheshpatel** [comment]
Oh, I see. Then I think it would be best to fix each function individually. Diff should not be too bad since I guess only the return statement would need to be changed.

**Comment by mdhaber** [comment]
OK, it's not too bad. But it makes me realize that getting all of stats to respect dtype will be tricky.  Any arithmetic with Python numbers (even integers) makes the result `float64`!
```python3
x = np.half(1)
(1 + x).dtype  # float64
```

**Comment by tirthasheshpatel** [comment]
> But it makes me realize that getting all of stats to respect dtype will be a lot of work. Any arithmetic with Python numbers (even integers) makes the result `float64`!

I think that's intuitive for NumPy. `float16` is not very common and usually something that the user doesn't expect. So, defaulting to `float64` even in SciPy won't be too bad. What do you think?

**Comment by tirthasheshpatel** [comment]
> In NumPy, though, the mean of a `float32` array is a `float32`. Ideally, we would respect that with our statistic functions, right? And preferably operations within the function actually work with that dtype rather than just converting at the end.

I agree. But if simple operations like adding a Python float to a NumPy dtype give a `float64` result, it would be very difficult to ensure we are operating with the same input dtype throughout a statistical test/function. For basic numpy functions like `add` and `mean`, it is much easier to operate with and output the same dtype.

> I just saying that if we wanted to respect dtype rules across the board, it would take a fair amount of work!

Agreed. I am just not sure if it's worth it.

**Review by tirthasheshpatel — APPROVED** [review]
Looks good now. Thanks Matt!

**Comment by mdhaber** [comment]
> I am just not sure if it's worth it.

There are many higher priority items for sure. But in the future, it would be good to make most stats functions compatible with other objects that satisfy NumPy's interface - e.g. GPU-based arrays for which float32 is more common.

**Pull request merged**
