### PR TITLE
BUG: Fix CLI Help in light themes

### PR DESCRIPTION
**Pull request by mariprudencio**
#### Reference issue
Closes #16334 

#### What does this implement/fix?
Fixed the problem observed on terminals that use light themes, when called dev CLI. 

#### Additional information
Used the second approach pointed out in issue. Fixed the problem when using "--help" argument and not showing the examples when it is not used.

### CODE REVIEW

**Comment by mariprudencio** [comment]
Hi @sayantikabanik, tks for reviewing my PR.

I sent another commit to fix the wrong behavior pointed out by you. I'm not sure about my understand of the markdown structure. If my commit is incorrect, once again, could you please explain to me what the Markdown structure should look like?

**Comment by sayantikabanik** [comment]
Thanks @mariprudencio 
I tested the changes on my system, LGTM 

@tupui: could you please verify the changes on your system too?

**Review by tupui — COMMENTED** [review]
LGTM as well. @mariprudencio could you update the PR since there is now an example for `build` which also needs this fix.

**Comment by mariprudencio** [comment]
Hi @sayantikabanik @tupui ! Once again, tks to reviewing my PR. 

As suggested, I fixed the example in `build`. If something else still wrong, let me know!

**Comment by sayantikabanik** [comment]
LGTM ✨

**Review by tupui — APPROVED** [review]
LGTM, thanks @mariprudencio and thanks @sayantikabanik for checking.

I just updated the indentation issues and verified locally that it does work.

**Pull request merged**
