### PR TITLE
MAINT: fix some build warnings from `special/ellip_harm.pxd`

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
Rebased to fix a merge conflict. CI failures are unrelated. Anyone want to have a look?

**Comment by ev-br** [comment]
Have a vague memory of Josh checking that ellipharm-related cython noise being noise. The patch itself looks good, and there is no need for it to linger. Thanks Ralf, merging.

**Comment by rgommers** [comment]
Thanks Evgeni! Almost down to no warnings on macOS now:)

**Comment by ev-br** [comment]
Recently, there are some build warnings on linux again, from propack. Apparently, I got used to warning-free builds :-). But that's separate anyway.

**Comment by rgommers** [comment]
Probably because you upgraded from GCC 9 to 10? That's what happened to me. We have one CI job which uses `-Werror` to keep things clean. I can upgrade that to a newer GCC, that should squash them. Ubuntu 22.04 LTS has GCC 11.2 by default.

**Comment by ev-br** [comment]
Not intentionally, no. `$ gcc --version` reports 9.04 for me, as I'm on 22.04.0 still. But if these go away on an upgrade, great, sorry for the noise.

**Pull request merged**
