### PR TITLE
add the options 'nearest-right' and 'nearest-left' to interp1d

### PR DESCRIPTION
**Pull request by mherkazandjian**
with these two kinds of interpolation one can choose which neighbor
to use in performing the nearest neighbor interpolation.

e.g.
    >>> interp1d(x, y, kind='nearest-left')
    >>> interp1d(x, y, kind='nearest-right')

all tests passing, and updated documentation builds correctly.

### CODE REVIEW

**Comment by ev-br** [comment]
Tests, we needs them.

**Comment by mherkazandjian** [comment]
ok, will work on it. i though to have the review/descision to accept this enhancement before proceeding with the tests.

**Comment by ev-br** [comment]
For decision to accept or not please send an email to the scipy-dev mailing list. A description of a use case might help. (I myself am neutral on the feature.)

**Comment by mherkazandjian** [comment]
yes, i can do that. I'll think of a better way to represent the nearest left/right interpolations. Moreover, i think i will add a bunch of examples on the other kinds of interpolation (maybe a separate pull request for that). Before that I will write the test cases.

**Comment by ev-br** [comment]
Yup, hacking on interp1d is a bit messy and fraught with backwards compatibility concerns :-). New features need to be tested on multidimensional inputs, also with non-default axes. 

I think we should articulate better the recommendation for users to prefer using specific interpolators unless constrained by backwards compat or porting code from matlab. For new features like this PR the guiding principle I think is how easy it is to construct an equivalent in the user code (compare to https://github.com/scipy/scipy/pull/6725#issuecomment-256432197). If it's just `np.searchsorted`, then I'd say it's not really worth it, but then there are edge cases which might be annoying to deal with in an ad hoc code.

**Comment by rdturnermtl** [comment]
Maybe the arguments ``'next'`` and ``'previous'`` should be used instead of ``'nearest-right'`` and ``'nearest-left'``.  It is shorter and it is compatible with convention from matlab:
[https://www.mathworks.com/help/matlab/ref/interp1.html](url)

**Comment by ev-br** [comment]
Superseded by gh-8572, so closing. Thanks @mherkazandjian

**Pull request closed without merging**
