### PR TITLE
BUG: fix potential division by zero for dataset of length 2 in stats pearsonr

### PR DESCRIPTION
**Pull request by rafalalgo**
Reference to: https://github.com/scipy/scipy/issues/7730

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @rafalalgo. The fix looks good, but can you please add the example from gh-7730 as a regression test?

**Comment by josef-pkt** [comment]
I'm not sure whether this shouldn't return nan instead

extreme case is when r=0, or r=nan e.g. when we have two constant, two point lines (1, 1), (0, 0)
(essentially a p-value doesn't make much sense if we only have two points)

**Comment by rgommers** [comment]
> I'm not sure whether this shouldn't return nan instead

Hmm, good point. I think I agree. looking at the formula for `pearsonr`, you'd need at least 3 points.

**Comment by WarrenWeckesser** [comment]
@rafalalgo, thanks for working on this.  The title of this pull request is "BUG: fix potential division by zero for dataset of length 2 in stats pearsonr", and the first comment mentions fixing gh-7730.  In https://github.com/scipy/scipy/pull/9562, `pearsonr` was given a complete overhaul, which fixed gh-7730.  So I'm closing this pull request as redundant.

There are other changes here that are not related to `pearsonr`.  If there are changes that you still want to contribute, can you update the pull request (or start another one) to focus on those changes?  If there are multiple changes that are not related, I recommend a separate pull request for each one.

**Pull request closed without merging**
