### PR TITLE
DOC: indent see also.

### PR DESCRIPTION
**Pull request by Carreau**
If second line is not properly indented, this is not properly parsed.

### CODE REVIEW

**Comment by mdhaber** [comment]
This is a private function, so I don't think it's rendered anywhere. 
It is still worth making the change if this is correct - but I'm having trouble checking because it isn't rendered anywhere.
Sphinx is so particular about these things - can you point me to a reference or example that shows this is the right fix?

**Comment by Carreau** [comment]
> This is a private function, so I don't think it's rendered anywhere.
> It is still worth making the change if this is correct - but I'm having trouble checking because it isn't rendered anywhere.

It's just that NumpyDoc can't parse it:

```
In [16]: NumpyDocString(scipy.stats.stats._sum_of_squares.__doc__)
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-16-19e19ff55939> in <module>
----> 1 NumpyDocString(scipy.stats.stats._sum_of_squares.__doc__)

~/dev/numpydoc/numpydoc/docscrape.py in NumpyDocString.__init__(self, docstring, config)
    144 self._parsed_data = copy.deepcopy(self.sections)
    146 try:
--> 147     self._parse()
    148 except ParseError as e:
    149     e.docstring = orig_docstring

~/dev/numpydoc/numpydoc/docscrape.py in NumpyDocString._parse(self)
    408     self['index'] = self._parse_index(section, content)
    409 elif section == 'See Also':
--> 410     self['See Also'] = self._parse_see_also(content)
    411 else:
    412     self[section] = content

~/dev/numpydoc/numpydoc/docscrape.py in NumpyDocString._parse_see_also(self, content)
    330         items.append((funcs, rest))
    331     else:
--> 332         raise ParseError("%s is not a item name" % line)
    333 return items

ParseError: `_sum_of_squares`). is not a item name in '\n    Square each element of the input array, and return the sum(s) of that.\n\n    Parameters\n    ----------\n    a : array_like\n        Input array.\n    axis : int or None, optional\n        Axis along which to calculate. Default is 0. If None, compute over\n        the whole array `a`.\n\n    Returns\n    -------\n    sum_of_squares : ndarray\n        The sum along the given axis for (a**2).\n\n    See Also\n    --------\n    _square_of_sums : The square(s) of the sum(s) (the opposite of\n    `_sum_of_squares`).\n\n    '
```

with the change it can:

```
In [2]: NumpyDocString(scipy.stats.stats._sum_of_squares.__doc__)
Out[2]: <numpydoc.docscrape.NumpyDocString at 0x10d7897f0>
```

Currently I'm just blindly trying to parse all docstrings for various documentation related side projects.

**Comment by Carreau** [comment]
Side note, it's because I'm working on a [docstring autoformatter](https://github.com/Carreau/velin) and a terminal rendered (here _square_of_sum, not sum_of_square), and both failed on this function.

So even if not rendered in the html docs there will hopefully be some way to access it via IPython's `?` at some point in the future.

Screen Shot 2021-01-29 at 14 30 54

**Review by mdhaber — APPROVED** [review]
OK! LGTM!
```python3
import scipy.stats
from numpydoc.docscrape import NumpyDocString

# (correct output for comparison)
doc = NumpyDocString(scipy.stats.linregress.__doc__)
print(doc['See Also'])

doc = NumpyDocString(scipy.stats.stats._sum_of_squares.__doc__)
print(doc['See Also'])
```

**Pull request merged**
