### PR TITLE
DOC: signal: Add examples for chirp() and sweep_poly().

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Review by larsoner — COMMENTED** [review]
Updated `chirp`:

https://2587-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.signal.chirp.html#scipy.signal.chirp

Updated `sweep_poly`:

https://2587-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.signal.sweep_poly.html#scipy.signal.sweep_poly

WDYT about using `spectrogram` instead or in addition to time plots? It might be more informative, at least for the `chirp` case where the differences are a bit more subtle.

Otherwise changes LGTM

**Comment by WarrenWeckesser** [comment]
> WDYT about using spectrogram instead or in addition to time plots? 

Good idea.  I'll experiment a bit.

The examples are based on http://scipy-cookbook.readthedocs.io/items/FrequencySweptDemo.html, but I tweaked the values a bit to look better in the smaller plots generated by sphinx, and I didn't include the plots of f(t) for the chirp examples.  Adding code to generate those seemed to clutter up the example.  But now, as you say, the differences between the plots of the waveforms are subtle.

**Comment by WarrenWeckesser** [comment]
Updated to use `spectrogram` in the `chirp()` examples.

**Comment by Eric89GXL** [comment]
LGTM:

https://2600-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.signal.chirp.html#scipy.signal.chirp

Anyone else want to have a look? If not, I'll go ahead and merge in a couple of days.

**Comment by Eric89GXL** [comment]
Thanks for cleaning these up @WarrenWeckesser

**Pull request merged**
