### PR TITLE
MAINT: additional 1.8.1 backports/adjustments

### PR DESCRIPTION
**Pull request by tylerjereddy**
* backport all three merged PRs with the appropriate label:
  * gh-15798
  * gh-16035
  * gh-16041
 * add Henry Schreiner to the release notes for providing [critical assitance](https://github.com/pypa/manylinux/issues/1309#issuecomment-1120330468) in handling the new [`git` security measure](https://github.blog/2022-04-12-git-security-vulnerability-announced/)
 * I do anticipate that we'll see a few CI failures that we also saw in gh-16139, though I believe we can probably safely ignore them (wheels repo CI is passing, etc.); we should check for anything new beyond those though, since there were some non-trivial merge conflicts/submodule changes

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
The backported PRs all look reasonable. There are a lot of failures though. The ones due to a `distutils` deprecation warning can be ignored. These ones may be due to the UNU.RAN update (not sure, @tirthasheshpatel do you remember?)
```
RuntimeWarning: invalid value encountered in multiply
```

**Comment by tirthasheshpatel** [comment]
> These ones may be due to the UNU.RAN update

No, I don't think the failures are related to UNU.RAN. The runtime warnings might be because of a change in NumPy. The prerelease_deps_coverage_64bit_blas uses the latest NumPy (1.23.0dev0).

**Comment by tylerjereddy** [comment]
For the failures @rgommers is worried about, isn't that just the thing that @seberg was shimming for bleeding-edge NumPy in gh-16152? It looks like he is even working on the same file over there `scipy/stats/tests/test_distributions.py`.

I also see a comment that the exact nature of the warnings is still subject to change, but I don't mind if we want to try backporting that when it is ready before we proceed here?

**Comment by tylerjereddy** [comment]
Ok, I dealt with the merge conflicts to pull in the new-NumPy shims from Sebastian and updated the relnotes.

Still, there are more failures to scan over I think, hopefully this reduces the count a bit more though.

**Comment by tylerjereddy** [comment]
The prerelease job is timing out now, making it harder to assess remaining failures--I'll try a restart or two.

**Comment by tylerjereddy** [comment]
For the NumPy prerelease failures, ignoring the distutils deprecation errors, we still have failures in:
- `TestSOSFreqz.test_sosfreqz_design_ellip`
  - `Mismatched elements: 1 / 103 (0.971%)`  @WarrenWeckesser looks like I should pull in fbfc0d1ee00 that touches this exact code--the PR shows fixing the same error I think: gh-15870
- `TestCorrelateComplex.test_rank0[complex256]`
  - I think @seberg is aware of this one--is it safe to ignore `TypeError: unsupported operand type(s) for *: 'complex' and 'numpy.float128'`?
- `TestSparseFunctions.test_scale_rows_and_cols `
  -  `PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.` safe to ignore for backporting since it is just a pending deprecation?
    - @rossbar thoughts? you've touched code around here lately I think? 
- `TestTruncnorm.test_moments`
  - small floating point delta: `5.8718046` vs. `5.871785` @mdhaber I think a 32-bit xfail was added recently, should we worry about this one?

@rkern @tupui @tirthasheshpatel looks like there may be some disagreement on the licensing backports (gh-16155, gh-16158)--suggestions?

**Comment by rkern** [comment]
I believe that [this commit](https://github.com/scipy/unuran/pull/5/commits/657516810ece1bd7bd30193318b9c734fa970251) should be reverted, yes. The rest of the PR is fine.

**Comment by tupui** [comment]
I will make the fix for the licensing. But fine with me to not block the release for that.

**Comment by WarrenWeckesser** [comment]
> * TestSOSFreqz.test_sosfreqz_design_ellip
>
>    Mismatched elements: 1 / 103 (0.971%) @WarrenWeckesser looks like I should pull in https://github.com/scipy/scipy/commit/fbfc0d1ee001e53aa28e744487faf322bddb5e0e that touches this exact code--the PR shows fixing the same error I think: https://github.com/scipy/scipy/pull/15870

If you need it to fix test failures in the 1.8.1 release, then sure, backporting is fine.  It is just a one-line fix of a test (three if you include the comments), so it should be straightforward to include it.

**Comment by tupui** [comment]
@tylerjereddy gh-16163 is in. I believe this is good now.

**Comment by tylerjereddy** [comment]
> @tylerjereddy https://github.com/scipy/scipy/pull/16163 is in. I believe this is good now.

Thanks! Yeah, main delay is just that I'm still recovering from some kind of virus, hopefully I can resume here soon.

**Comment by tupui** [comment]
oh no worries, take care of yourself first!

**Comment by tylerjereddy** [comment]
I've updated to backport everything I think I need here, along with another release notes update.

I'll wait for CI because we had so many failures before. My current plan is to allow for the following types of test suite failures with pre-release NumPy:
- `PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices` (this was primarily in `TestSparseFunctions.test_scale_rows_and_cols`) -- I do not see objections above to proposal of allowing these warnings to continue on this release branch
- `TestTruncnorm.test_moments` differs at the 4th decimal position with pre-release NumPy, and the test already has a 32-bit xfail for causing trouble

So, if I just see those failures I'll be tempted to self-merge. If I see additional failures with pre-release NumPy I may have to check those again.

**Comment by tylerjereddy** [comment]
There are only two failing CI jobs left:
  1. the circleci asv benchmark timeout, which we already agreed to ignore when the first thing we tried to fix that had no effect
  2. the prerelease deps jobs has 3 test failures and 2 errors left--they all involve either:
    - distutils deprecations
    - matrix subclass pending deprecations
    - or other cases I mentioned in my comment above

**Pull request merged**
