### PR TITLE
BLD: avoid setting an environment variable in a meson.build file

### PR DESCRIPTION
**Pull request by rgommers**
This was introduced last month in gh-20232; I commented on it there (https://github.com/scipy/scipy/pull/20232/files#r1524677014) about it maybe being able to cause an issue later. And it just did, see gh-20433. Upgrading Meson in an existing build environment is technically unsupported by Meson, but has always "just worked". Now we hit a corner case on Windows, because when we set an environment variable in a `meson.build` file, a pickled version of Meson is called and this is less robust to upgrading Meson in the build env.

The fix is a bit more verbose, but should be reliable - the `importlib` importing is directly copied from how it's done in NumPy's code generation scripts.

### CODE REVIEW

**Comment by ilayn** [comment]
Interesting indeed. No idea how I end up hitting these corners on Windows but thank you for the surgery anyways.

**Comment by thalassemia** [comment]
I should’ve known better haha. Thanks for the fix @rgommers!

**Comment by lucascolley** [comment]
Feel free to use the green button @thalassemia ;)

**Review by thalassemia — APPROVED** [review]

**Comment by rgommers** [comment]
> No idea how I end up hitting these corners on Windows

It's not you, it's Windows :)

**Pull request merged**
