### PR TITLE
STY: clang-format repo

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
https://github.com/scipy/scipy/pull/20539#discussion_r1649710379

#### What does this implement/fix?
Just using the same config as `scipy/special/special` initially.

#### Additional information
cc @izaid @steppi

### CODE REVIEW

**Comment by lucascolley** [comment]
we'll have to adjust the config for imports given that there are multiple `Header before Python.h in file` violations

**Comment by lucascolley** [comment]
@steppi here is how I have arrived at this diff:

1. add a copy of `scipy/special/special/.clang-format` at `scipy/.clang-format` in the first commit. This has the additional config line `IncludeBlocks: Preserve` so that includes can remain in order where they matter by splitting blocks up, such as for `<Python.h>`.
2. Separate `<Python.h>` includes into their own block in the second commit.
3. Separate `"sparsetools.h"` includes into their own block in the third commit (there are some overrides going on somewhere that seem to require that things from `"sparsetools.h"` are defined).
4. `cd scipy`
5. `find -E . -regex '.*\.(cpp|hpp|cc|cxx)' -exec clang-format --style=file -i --verbose {} \;`
6. Drop any changes that seem to be to vendored code. Commit the rest.

**Comment by lucascolley** [comment]
The diff is only so large because `special/Faddeeva.cc` has tab characters everywhere, btw.

**Comment by lucascolley** [comment]
I assume we probably want to include C files too. We may also want to make this a CI check, with something like https://github.com/marketplace/actions/clang-format-check.

**Comment by izaid** [comment]
So I'm basically okay with whatever you guys want to do. But one thought I have is that we probably shouldn't be autoformatting everything automatically when CI runs. That's because there is a lot of legacy code in C / C++ hidden throughout SciPy, and we actually probably don't want to format it. Best if it is left as the original formatting.

What I do think is good is having a global .clang-format that sets the SciPy style, so people can just it for the files they want.

**Pull request closed without merging**
