### PR TITLE
BUG: fixed _raw_fftnd sorting of mixed negative and non-negative axis indices

### PR DESCRIPTION
**Pull request by sjpeterson**
See issue #5403

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM. While we're at it, we could use `id_` instead of `id` to avoid shadowing a builtin.

Also, @ewmoore mentioned adding a check for axis validity. Do you think it's worth adding it here?

**Comment by sjpet** [comment]
Yeah, I could do both of those if that's desired.

**Comment by sjpet** [comment]
I changed 'id' to 'id_', but the only way I see early validation of axis indices giving a better error message is if it's done in directly in the user-called functions. The error message itself is clear enough in my opinion.

**Comment by Eric89GXL** [comment]
Thanks @sjpet

**Pull request merged**
