### PR TITLE
BUG: Add rmul for sparse arrays

### LINKED ISSUE #15210: BUG: A sparse matrix raises a ValueError when `__rmul__` with a value as `None`
### Describe your issue.

A sparse matrix multiplied with a value of an unsupported operand type raises TypeError. However, in SciPy 1.8.0rc1, a sparse matrix raises ValueError when it is called `__rmul__` with a value that is not interpretable as an array,  e.g. `None`. It should raise TypeError instead as `__mul__` does.

### Reproducing Code Example

```python
import numpy as np
import scipy.sparse as sp
m = np.eye(3)
m = sp.coo_matrix(m)
None * m
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ext-mtakagi/.pyenv/versions/nvidia/lib/python3.9/site-packages/scipy/sparse/_base.py", line 610, in __rmul__
    return self._rmul_dispatch(other)
  File "/home/ext-mtakagi/.pyenv/versions/nvidia/lib/python3.9/site-packages/scipy/sparse/_base.py", line 607, in _rmul_dispatch
    return (self.transpose() @ tr).transpose()
  File "/home/ext-mtakagi/.pyenv/versions/nvidia/lib/python3.9/site-packages/scipy/sparse/_base.py", line 618, in __matmul__
    raise ValueError("Scalar operands are not allowed, "
ValueError: Scalar operands are not allowed, use '*' instead
```

### SciPy/NumPy/Python version information

1.8.0rc1 1.22.0rc1 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by stefanv**
Closes #15210

### CODE REVIEW

**Comment by stefanv** [comment]
@tylerjereddy Not sure what the right milestone is, but this should go into the next point release; thanks!

**Comment by WarrenWeckesser** [comment]
Actually, I think this should be in 1.8.0 final.

**Comment by tylerjereddy** [comment]
backport-candidate label helps too, so I'll put that

**Review by perimosocordiae — APPROVED** [review]

**Review by tylerjereddy — COMMENTED** [review]
Looks like CJ is happy, and the fix makes sense to me as non-expert.

The stricter diff linter can probably be ignored re: adding an extra blank line, seems like not worth flushing CI again for that.

**Comment by tylerjereddy** [comment]
thanks Stefan

**Pull request merged**
