### PR TITLE
BUG: stats: mannwhitneyu hits max recursion limit with imbalanced inp…

### LINKED ISSUE #14622: BUG: (sort of) mannwhitneyu hits max recursion limit with imbalanced input sizes due to selection of 'exact' method; could method selection depend on max(n1,n2)?
### Reproducing Code Example

```python
from scipy.stats import mannwhitneyu
import numpy as np
a = np.random.randn(5)
b = np.random.randn(5000)
mannwhitneyu(a,b)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 414, in mannwhitneyu
    p = _mwu_state.sf(U.astype(int), n1, n2)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 53, in sf
    return self.cdf(k, m, n)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 41, in cdf
    pmfs = self.pmf(np.arange(0, np.max(k) + 1), m, n)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 33, in pmf
    self._f(m, n, i)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 81, in _f
    fmnk = self._f(m-1, n, k-n) + self._f(m, n-1, k)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 81, in _f
    fmnk = self._f(m-1, n, k-n) + self._f(m, n-1, k)
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 81, in _f
    fmnk = self._f(m-1, n, k-n) + self._f(m, n-1, k)
  [Previous line repeated 991 more times]
  File "/Users/pbradley/opt/anaconda3/envs/scanpy_piptest5/lib/python3.8/site-packages/scipy/stats/_mannwhitneyu.py", line 71, in _f
    if k < 0 or m < 0 or n < 0 or k > m*n:
RecursionError: maximum recursion depth exceeded in comparison
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by alexandschaefer**
#### Reference issue
Fixes #14622

#### What does this implement/fix?
Currently, the mannwhitneyu test hits maximum recursion limit when **one** (but not both) of the input dimensions is large. As it will try to perform `exact` method. Currently, `asymptotic` method is only performed when **both** input dimensions are larger than or equal 9. Here, we also handle when one of the dimensions is large. Large was set to 81. Which is based on the earlier definition with 81 = 9*9. In addition a test for execution with one large input dimension is added.

### CODE REVIEW

**Comment by mdhaber** [comment]
It sounds like the default recursion limit is 1000. Is this the recursion limit on the machine you're testing with? 
If so, this looks reasonable as a quick improvement. Other ideas include calculating whether the recursion is safe given the user's actual recursion limit, or trying exact and resorting to asymptotic if the recursion limit is reached.
Maybe someday I'll rewrite this part without explicit recursion.

**Comment by alexandschaefer** [comment]
Thank you for your comment. Yes. I tested with the standard recursion limit of 1000.

To your suggestion. Do you think the following can be sufficient?

```    
    if method == "auto":
        try:  # exact
            p = _mwu_state.sf(U.astype(int), n1, n2)
        except RecursionError:  # asymptotic
            z = _get_mwu_z(U, n1, n2, ranks, continuity=use_continuity)
            p = stats.norm.sf(z)
    elif method == "exact":
        p = _mwu_state.sf(U.astype(int), n1, n2)
    elif method == "asymptotic":
        z = _get_mwu_z(U, n1, n2, ranks, continuity=use_continuity)
        p = stats.norm.sf(z)
    p *= f
```

**Comment by mdhaber** [comment]
I had written the following:

> Close, but for now, I would keep the idea that `auto` should use `asymptotic` if `m` and `n` are both sufficiently large (as the asymptotic approximation tends to be "good" - or good enough by the original author's standards, if I remember correctly).

> So yes, get rid of `_mwu_choose_method` and add `auto` to the branching, but in there:
```
if n1 <= 8 or n2 <= 8:
   try:
      # try exact method
   except RecursionError:
      # Maybe produce a warning? 
      # use asymptotic
else:
   # use asymptotic
```

But as I think about it now, I don't really like the idea of the warning,. I do think there should be an error if the exact method fails. How about just putting the call to the exact method in a `try`-`except` and upon exception, [re-raise](https://stackoverflow.com/questions/9157210/how-do-i-raise-the-same-exception-with-a-custom-message-in-python) the exception with a more helpful error message (e.g. suggest raising the recursion limit with `sys.setrecursionlimit` or choosing `method='asmptotic'`)?

**Comment by alexandschaefer** [comment]
Hi @mdhaber ,

I implemented your suggestion. Is this still helpful or obsolete with #14854 ? Please let me know what you think.

Best,
Alex

**Comment by mdhaber** [comment]
Hmm after gh-14854, we won't really need an error when the recursion limit is reached. So I can't think of another way to use this : / can you? Sorry about that!

**Comment by alexandschaefer** [comment]
Hi @mdhaber. After switching to an iterative approach I see no reason of keeping this. No worries and thank you for the feedback.

**Comment by mdhaber** [comment]
Thanks for doing this! I didn't expect we'd have the iterative version so soon!

**Pull request closed without merging**
