### PR TITLE
Improved documentation on bartlett window on scipy.org

### PR DESCRIPTION
**Pull request by ChristinaCzaikowski**
Improved documentation on bartlett window 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.bartlett.html#scipy.signal.windows.bartlett
was missing 'import numpy as np'

### CODE REVIEW

**Comment by ChristinaCzaikowski** [comment]
Please do not be mad with me, if I did something wrong in the Git Workflow, it is my first time I contribute sth.

**Review by tylerjereddy — COMMENTED** [review]
Documentation improvements are almost always welcome.

In this case, there is already a tricky discussion happening about implicit vs. explicit imports in gh-13049, as I mentioned in your other similar PR, gh-15320.

For now, I'd suggest adding a comment in that issue and waiting for a resolution there before suggesting more changes like this, since if we did make the switch to explicit imports, it would be an enormous number of changes, and until the decision is made we wouldn't be able to act on the PRs anyway.

In the meanwhile, other kinds of documentation improvements are likely to be most welcome.

**Comment by tylerjereddy** [comment]
(also, note that the docstrings are actually in another source file, so you don't have to rewrite the entire examples--see my comment in gh-15320; I often find `git grep` useful for searching for the right source file based on a code snippet I want to change)

**Comment by rgommers** [comment]
> Please do not be mad with me, if I did something wrong in the Git Workflow, it is my first time I contribute sth.

@ChristinaCzaikowski no worries at all, thank you for contributing.

This adds a new file without extension, which can't be the right thing to do. The example you are trying to edit is at https://github.com/scipy/scipy/blob/3e77550/scipy/signal/windows/_windows.py#L671, so that is the place to make any changes. In this case the change is only a single line (`import numpy as np`) which is not quite desired, as @tylerjereddy. Given that this change is in the wrong place, I will close the PR. I'll have a look at gh-13049 now.

**Pull request closed without merging**
