### PR TITLE
DOC: signal.hilbert: update to reflect implementation

### LINKED ISSUE #21357: Terminology issue
https://github.com/scipy/scipy/blob/87c46641a8b3b5b47b81de44c07b840468f7ebe7/scipy/signal/_signaltools.py#L2289

The function is called "hilbert"  -- one thinks this function only computes the Hilbert transform.
For example, the function "sum" -- one thinks the function output is the sum of its inputs.

But the "hilbert" does the Hilbert Transform and more. It computes the analytic signal. 

So I propose two options:
1. This function should be rename "analytic". 
2. The function needs further documentation to say, "hilbert" computes the analytic signal, in which the Hilbert transform is an intermediary step.

The wikipedia reference, which the function cites, clearly dictates the Hilbert transform being a part of the process in calculating the analytic signal.

image

### PR DESCRIPTION
**Pull request by a-drenaline**
closes https://github.com/scipy/scipy/issues/21357

### CODE REVIEW

**Comment by melissawm** [comment]
Thanks @a-drenaline. For future reference, you can use [docs only] in your commit message to [not run the full CI tests](https://docs.scipy.org/doc/scipy/dev/contributor/continuous_integration.html#skipping) on a docs PR. I would also suggest having a look at our [commit message conventions](https://docs.scipy.org/doc/scipy/dev/contributor/development_workflow.html#writing-the-commit-message) which help keep our git history clean.

**Review by DietBru — CHANGES_REQUESTED** [review]
Sorry for being picky:
* Not only are negative frequencies filtered out, but the positive frequencies are also doubled.
* I think it makes sense to mention that a FFT is utilized, because it has a few caveats like being slow for signal length being prime or the assumption that the signal is periodic.
* Noting that more information can be found in the notes goes without saying for short docstrings, IMO.

What do you think about changing the text to something along the lines of

```text
    FFT-based computation of the analytic signal.

    The analytic signal is calculated by filtering out the negative frequencies and 
    doubling the amplitudes of the positive frequencies in the FFT domain.
    The imaginary part of the result is the hilbert transform of the real-valued input
    signal.
    
    ...
```

**Comment by a-drenaline** [comment]
- The original PR was meant to highlight what I think is the most important step of the calculation, and then refer the reader to the Notes section for explanation of all steps . The suggested PR is to explain all steps. Observe that the Notes section is already doing that, and so it seems a little redundant to have the suggested PR and the Notes section co-exist.
- That works.
- In the documentation URL for the "hilbert", I did not observe a Table of Contents section. Thus, I'd argue it does necessitate to explicitly tell the reader where to look for additional information for the calculation.

**Comment by lucascolley** [comment]
> Noting that more information can be found in the notes goes without saying for short docstrings, IMO.

I agree that this looks a little unusual - we don't typically direct to the Notes.

> In the documentation URL for the "hilbert", I did not observe a Table of Contents section.

Could you elaborate on what you would have liked to see here? For me, on loading https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.hilbert.html the Notes section is immediately visible.

**Comment by a-drenaline** [comment]
@lucascolley,
Why is it unusual? If the reader wants to know more about the sentence they are reading, then let's tell them where to go next. 

With no ToC, there is no obvious structure of where to look for information & how the information is organized.
Just because it is visible to you in your display, does not mean it will be visible in someone's laptop, smartphone, tablet, etc.

**Comment by a-drenaline** [comment]
@lucascolley,
I see, it seems your feedback was considering the codebase as a whole and not just this PR.
While the documentation structure should apply to the codebase, I prefer to focus on this PR.

I propose these changes remain. The reader does not know where to look. "Scrolling down" defeats the essence of documentation, which is to tell the reader what to look for and where to look for it. 

Said a different way, "scrolling down" would be the suitable option with older documentation structure (e.g., plain text file), which clearly this platform isn't.

**Comment by melissawm** [comment]
I don't think adding an internal link to a docstring section is possible.

**Comment by a-drenaline** [comment]
It's been nearly a week. 

If there's no new feedback, then let's check in this PR.

**Comment by lucascolley** [comment]
(to clarify, I have seen this, but I would like to see @DietBru's comments addressed before merging myself - another maintainer may merge as is, though)

**Comment by a-drenaline** [comment]
I have responded to @DietBru's comments, and have not been provided one direction or another. 

So in light of that, the original direction is admissible.

**Comment by DietBru** [comment]
Sorry for the delayed reply, @a-drenaline.  What @lucascolley is referring to that you didn't comment on my proposal of alternative wording [here]. So, would you like to update the wording? 


[here]: https://github.com/scipy/scipy/pull/21378#pullrequestreview-2237699006

**Comment by DietBru** [comment]
Gentle ping to @a-drenaline: Do you still have interest in finishing this PR? If not, that is fine as well. I would be happy to take up the remaining work.

**Comment by DietBru** [comment]
I took the liberty of reworking the docstr a bit and also beautifying the example. The rendered result can be found [here]. 

[here]: https://output.circle-artifacts.com/output/job/734bf73b-b5dc-4f8a-b31c-6797008dea03/artifacts/0/html/reference/generated/scipy.signal.hilbert.html

**Review by DietBru — APPROVED** [review]

**Review by j-bowhay — APPROVED** [review]
Thanks for your first contribution @a-drenaline, keep them coming! Thanks for pushing this over the finish line @DietBru

**Pull request merged**
