### PR TITLE
remove 1 - cosine similarity.

### PR DESCRIPTION
**Pull request by chenb67**
by wikipedia definiton: 
https://en.wikipedia.org/wiki/Cosine_similarity

a.dot(b) / (norm(a) \* norm(b))

this gives normalized results in the range -1 to 1

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Sorry, but this isn't the sort of change we can (or would like to) accept. `scipy.spatial.distance` defines distances, whereas the Wikipedia definition you cite is for cosine similarity.

**Comment by ewmoore** [comment]
-1.  We can't just change this because it will likely break other peoples code.  Beyond that, the page you linked even points out that cosine distance, which is what is being calculated here, uses  the 1-.

**Comment by ewmoore** [comment]
Too slow!

**Comment by chenb67** [comment]
@ewmoore You are right, it does say that :)
I got confused when the function returned values larger than 1.
Sorry

**Pull request closed without merging**
