### PR TITLE
MAINT: change type declaration in cluster.linkage, prevent overflow

### LINKED ISSUE #2089: Integer overflows cause segfault in linkage function with large input (Trac #1564)
_Original ticket http://projects.scipy.org/scipy/ticket/1564 on 2011-11-20 by trac user laserson, assigned to unknown._

Hi all,

I have been looking for the source of some segfaults I have been getting when trying to use the linkage function in scipy.cluster.hierarchy, and I finally found the reason (with the help of our cluster's IT person, Chris Walker).

In the 'linkage' function in hierarchy.c, the three variables `n`, `np`, and `npc2`, are declared as int types.  However, if `n=50000`, which is the case with my input files, then the value of NCHOOSE2(n) overflows, leading `malloc` to return a null pointer because the requested number of bytes is negative.

If you uncomment the debug message at l. 461, you will find this to be true.

These three variables should be changed to be long ints, or something similar, to accomodate larger input matrices.

Thanks!
Uri

### LINKED ISSUE #6107: scipy.cluster.hierarchy.single segmentation fault with 2**16 datapoints
Hi, 

Running the following code in the interactive prompt executes successfully:

```
>>> import scipy.cluster, numpy.random
>>> scipy.cluster.hierarchy.single(numpy.random.random_sample((2**15, 10)))
```

The following code results in a segmentation fault:

```
>>> import scipy.cluster, numpy.random
>>> scipy.cluster.hierarchy.single(numpy.random.random_sample((2**16, 10)))
```

Thanks, 
Tim

gdb output:

```
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /srv/sw/python/2.7.4/bin/python...done.
(gdb) run -c "import scipy.cluster, numpy.random; scipy.cluster.hierarchy.single(num
py.random.random_sample((2**16,10)))"
Starting program: /srv/sw/python/2.7.4/bin/python -c "import scipy.cluster, numpy.ra
ndom; scipy.cluster.hierarchy.single(numpy.random.random_sample((2**16,10)))"
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7f
fff7ffa000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__pyx_pf_5scipy_7cluster_10_hierarchy_26slink (__pyx_v_n=65536, __pyx_v_Z=...,
    __pyx_v_dists=..., __pyx_self=<optimised out>)
    at scipy/cluster/_hierarchy.c:10392
10392   scipy/cluster/_hierarchy.c: No such file or directory.
```

gdb backtrace:

```
(gdb) bt
#0  __pyx_pf_5scipy_7cluster_10_hierarchy_26slink (__pyx_v_n=65536, __pyx_v_Z=...,
    __pyx_v_dists=..., __pyx_self=<optimised out>)
    at scipy/cluster/_hierarchy.c:10392
#1  __pyx_pw_5scipy_7cluster_10_hierarchy_27slink (__pyx_self=<optimised out>,
    __pyx_args=<optimised out>, __pyx_kwds=<optimised out>)
    at scipy/cluster/_hierarchy.c:10160
#2  0x000000000049ec5d in call_function (oparg=<optimised out>,
    pp_stack=0x7fffffffd530) at Python/ceval.c:4021
#3  PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>)
    at Python/ceval.c:2666
#4  0x00000000004a0806 in PyEval_EvalCodeEx (co=<optimised out>,
    globals=<optimised out>, locals=<optimised out>, args=<optimised out>,
    argcount=1, kws=0xd1dc40, kwcount=2, defs=0xf525c0, defcount=2, closure=0x0)
    at Python/ceval.c:3253
#5  0x000000000049e6e5 in fast_function (nk=<optimised out>, na=1,
    n=<optimised out>, pp_stack=0x7fffffffd720, func=0xfc2cf8)
    at Python/ceval.c:4117
#6  call_function (oparg=<optimised out>, pp_stack=0x7fffffffd720)
    at Python/ceval.c:4042
#7  PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>)
    at Python/ceval.c:2666
#8  0x00000000004a0806 in PyEval_EvalCodeEx (co=<optimised out>,
    globals=<optimised out>, locals=<optimised out>, args=<optimised out>,
    argcount=1, kws=0x85c568, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3253
#9  0x000000000049e6e5 in fast_function (nk=<optimised out>, na=1,
    n=<optimised out>, pp_stack=0x7fffffffd910, func=0xfc29b0)
    at Python/ceval.c:4117
#10 call_function (oparg=<optimised out>, pp_stack=0x7fffffffd910)
    at Python/ceval.c:4042
#11 PyEval_EvalFrameEx (f=<optimised out>, throwflag=<optimised out>)
    at Python/ceval.c:2666
#12 0x00000000004a0806 in PyEval_EvalCodeEx (co=<optimised out>,
    globals=<optimised out>, locals=<optimised out>, args=<optimised out>,
    argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3253
#13 0x00000000004a0932 in PyEval_EvalCode (co=<optimised out>,
    globals=<optimised out>, locals=<optimised out>) at Python/ceval.c:667
#14 0x00000000004c5b2a in run_mod (arena=0x85ddb0, flags=<optimised out>,
    locals=0x7f65f0, globals=0x7f65f0, filename=0x51e326 "<string>",
    mod=<optimised out>) at Python/pythonrun.c:1365
#15 PyRun_StringFlags (flags=<optimised out>, locals=0x7f65f0, globals=0x7f65f0,
    start=257, str=<optimised out>) at Python/pythonrun.c:1328
#16 PyRun_SimpleStringFlags (command=<optimised out>, flags=<optimised out>)
    at Python/pythonrun.c:969
#17 0x00000000004152d5 in Py_Main (argc=3, argv=<optimised out>)
    at Modules/main.c:584
#18 0x00007ffff711d76d in __libc_start_main (main=0x4149e0 <main>, argc=3,
    ubp_av=0x7fffffffdc98, init=<optimised out>, fini=<optimised out>,
    rtld_fini=<optimised out>, stack_end=0x7fffffffdc88) at libc-start.c:226
#19 0x0000000000414a11 in _start ()
```

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-6107, closes gh-2089.

### CODE REVIEW

**Comment by person142** [comment]
Tested the examples in gh-6107; got this:

```
$ free -g
             total       used       free     shared    buffers     cached
Mem:            31          4         27          0          0          2
-/+ buffers/cache:          1         29
Swap:           63          0         63
$ python
Python 3.5.1 (default, Apr  7 2016, 13:07:27)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'0.19.0.dev0+c98f013'
>>> from scipy import cluster
>>> from numpy import random
>>> cluster.hierarchy.single(random.random_sample((2**16, 10)))
Segmentation fault (core dumped)
$ python
Python 3.5.1 (default, Apr  7 2016, 13:07:27)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import cluster
>>> from numpy import random
>>> cluster.hierarchy.average(random.random_sample((2**16, 10)))
Segmentation fault (core dumped)
```

**Comment by rgommers** [comment]
Hmm. And with ``2**15`` it works fine for you?

**Comment by person142** [comment]
Yes:

```
>>> import scipy
>>> scipy.__version__
'0.19.0.dev0+c98f013'
>>> from scipy import cluster
>>> from numpy import random
>>> cluster.hierarchy.single(random.random_sample((2**15, 10)))
array([[  2.51290000e+04,   2.88160000e+04,   9.80715880e-02,
          2.00000000e+00],
       [  7.36600000e+03,   2.03180000e+04,   1.22082847e-01,
          2.00000000e+00],
       [  2.79000000e+04,   3.01570000e+04,   1.36947331e-01,
          2.00000000e+00],
       ...,
       [  2.30610000e+04,   6.55310000e+04,   5.42795465e-01,
          3.27660000e+04],
       [  3.50100000e+03,   6.55320000e+04,   5.45920360e-01,
          3.27670000e+04],
       [  3.08590000e+04,   6.55330000e+04,   5.49410597e-01,
          3.27680000e+04]])
>>> cluster.hierarchy.average(random.random_sample((2**15, 10)))
array([[  1.70240000e+04,   2.91200000e+04,   1.47038692e-01,
          2.00000000e+00],
       [  1.31290000e+04,   2.07530000e+04,   1.52611363e-01,
          2.00000000e+00],
       [  6.18500000e+03,   3.12110000e+04,   1.54310641e-01,
          2.00000000e+00],
       ...,
       [  6.55240000e+04,   6.55290000e+04,   1.28342708e+00,
          1.63680000e+04],
       [  6.55310000e+04,   6.55320000e+04,   1.28852229e+00,
          3.27670000e+04],
       [  2.26460000e+04,   6.55330000e+04,   1.59988079e+00,
          3.27680000e+04]])
```

**Comment by rgommers** [comment]
I'd doubting whether to add ``cluster.hierarchy.single(np.random.random_sample((2**16, 10)))`` as a test or not. We'd have to run it only if this is true:

    is_64bit and psutil.virtual_memory().available > 17e9

and therefore add ``psutil`` as an optional test dependency.

**Comment by person142** [comment]
Seems reasonable to not add it. It would have to be `SCIPY_XSLOW` too, so it would almost never get run anyway.

I also ran the examples again and they worked, so since it's been fine for a few people I'm +1 for merging.

**Comment by rgommers** [comment]
>  so it would almost never get run anyway.

true, ``XSLOW`` plus needing >16GB RAM means it's not a very useful test. So I propose to hit the green button.

**Comment by ev-br** [comment]
Two +1s, so green button it is. Thanks all.

**Pull request merged**
