### PR TITLE
BLD: Update to Cython 0.29.33

### PR DESCRIPTION
**Pull request by jjerphan**
#### Reference issue

Pre-requisite for https://github.com/scipy/scipy/pull/18153.

#### What does this implement/fix?

Reason: Cython 0.29.33 brings support for const-qualified memoryviews (see https://github.com/cython/cython/issues/1772).

#### Additional information

Downstream projects (like scikit-learn) already have adopted Cython 0.29.33 for the support of this fix since it allows enhanced safety.

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
This should be fine, we bump Cython minor versions pretty liberally.

Our CI has quite a few known issues at the moment, so you may see a bunch of unrelated fails. Maybe I'll let things flush through just to confirm I mostly see what I expect to see failing...

**Comment by tylerjereddy** [comment]
Nah that's just the Cython beta for 3.0, which is a bigger can of worms. We have an issue open for it.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @jjerphan

**Comment by tylerjereddy** [comment]
There are no new CI failures, I just checked.

I squash-merged b/c of the empty CI re-retrigger commit

**Comment by tylerjereddy** [comment]
Also, can you let us know if the downstream issues merit backporting in your opinion? We can label this and the read-only view PR appropriately then

**Comment by jjerphan** [comment]
Backporting both would be useful for scikit-learn.

**Comment by jjerphan** [comment]
Thank you for asking.

Backporting both PRs would be useful for scikit-learn. 🙂

**Pull request merged**
