### PR TITLE
BUG: fix newline

### PR DESCRIPTION
**Pull request by flxai**
#### Reference issue
No issue exists.

#### What does this implement/fix?
Adds a missing newline in `scipy/optimize/_differentialevolution.py` so the examples' code blocks render correctly.

### CODE REVIEW

**Review by ilayn — APPROVED** [review]
@flxai Thanks for this PR. While we are at it, do you mind touching also line 198 to use straight quotes instead of backticks to render best and best1bin as normal text (as in line 208-209). Single backticks are used for internal referencing so that's why it is not rendering correctly.

**Comment by flxai** [comment]
@ilayn Thanks for the suggestion.

**Comment by hameerabbasi** [comment]
The issue here is a Numba error: Numba version 0.49 requires NumPy 1.15 minimum.

**Comment by flxai** [comment]
@hameerabbasi Does that mean it can be safely ignored?

**Comment by hameerabbasi** [comment]
Yes, it's unrelated to this PR. I will try to make a PR to fix it.

**Comment by ilayn** [comment]
Thanks @flxai, @hameerabbasi

**Pull request merged**
