### PR TITLE
DOC: improve description of 'output' keyword for convolve

### LINKED ISSUE #3694: scipy.ndimage.convolve doesn't work when output parameter is set to input
In place convolution fails

```
import numpy as np
from scipy.ndimage import convolve
ker = [1., 2., 1.]
x = np.random.random_sample(100)
out1 = convolve(x, ker)
out2 = convolve(x, ker)
convolve(x, ker, output=x)
print np.allclose(out1, out2)
>>> True
print np.allclose(out1, x)
>>> False
```

### PR DESCRIPTION
**Pull request by adivijaykumar**
Made changes, kindly review.

### CODE REVIEW

**Comment by adivijaykumar** [comment]
#3694

**Comment by rgommers** [comment]
You made the change just in one place, but all other filters also have ``output``. Looks like you need to change ``output_doc`` at line 56.

Also, please have a look at http://docs.scipy.org/doc/numpy-dev/dev/gitwash/development_workflow.html#writing-the-commit-message for your next commits. Plus note I changed the PR title to be more descriptive.

**Comment by adivijaykumar** [comment]
> You made the change just in one place, but all other filters also have output. Looks like you need to change output_doc at line 56.

Made changes to a couple more places.

> Also, please have a look at http://docs.scipy.org/doc/numpy-dev/dev/gitwash/development_workflow.html#writing-the-commit-message for your next commits. Plus note I changed the PR title to be more descriptive.
Thanks, will keep that in mind from now on. This is my first ever PR, I appreciate the help.

**Comment by adivijaykumar** [comment]
@rgommers does this look fine?

**Comment by rgommers** [comment]
Looks good to me now, merged. Thanks @adivijaykumar !

> This is my first ever PR.

Awesome, keep them coming:)

**Pull request merged**
