### PR TITLE
BUG: Fix signal.dfreqresp for StateSpace systems

### PR DESCRIPTION
**Pull request by e-q**
Unfortunately, this function currently uses the easily confused names
`system` and `sys` to refer to the unmodified input system and
potentially converted to ZPK system respectively. A typo then led to the
ability to fall out of an if block without actually computing the output
(see gh-7335).

This should fix the bug, but the issue exposes a lack of testing of
discrete time state space systems in `test_dlti.py`, so this is WIP for
now (hence the `ci skip`).

### CODE REVIEW

**Comment by e-q** [comment]
This should do the trick. I think this should be back ported, it is an unfortunate regression.

**Comment by Eric89GXL** [comment]
Looks like this Travis failure is probably related:

https://travis-ci.org/scipy/scipy/jobs/226583074#L1439

**Comment by rgommers** [comment]
> Looks like this Travis failure is probably related:

Restarted it to be sure, same test failure. ``BadCoefficients not raised`` is something that could be a test issue rather than something this PR broke.

**Comment by rgommers** [comment]
TravisCI failure on the last commit is a timeout only.

**Comment by Eric89GXL** [comment]
LGTM, feel free to merge if you're happy @rgommers

**Comment by rgommers** [comment]
Merged. Thanks @e-q, @Eric89GXL

**Pull request merged**
