### PR TITLE
BUG: fix typo causing memleak

### PR DESCRIPTION
**Pull request by sturlamolden**
tree_buffer misspelled as tree_vector in destructor

### CODE REVIEW

**Comment by sturlamolden** [comment]
This is the penalty for ducktyping...

**Comment by rgommers** [comment]
@sturlamolden you opened the exact same PR twice, so I'm closing this one.

**Comment by sturlamolden** [comment]
This is for master, the other was or 0.16.x.

**Comment by rgommers** [comment]
Ah, I missed that. Not used to that (usually we push backports directly), but it's a good habit actually. I'll reopen.

**Comment by sturlamolden** [comment]
Looking at the code I cannot fathom why Cython allowed it to pass silently instead of raising ```AttributeError```, but it did. Cython can be dangerous sometimes.

**Comment by rgommers** [comment]
Merged, thanks Sturla.

**Pull request merged**
