### PR TITLE
DOC: Remove link to alpha in scipy.stats.dirichlet

### LINKED ISSUE #14190: Links in documentation of Dirichlet distribution are a mess
Looking at page for `scipy.stats.dirichlet`: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.dirichlet.html, the following issues cropped up:

- Link to `alpha` in the second sentence is to the wrong alpha (not the parameter).
- Methods in the last section have a bunch of double backticks but no meaningful links.
- Self-link in the notes section seems spurious, but at least it's not outright wrong.

See https://stackoverflow.com/q/67855329/2988730 for an example of how this makes the documentation confusing.

### PR DESCRIPTION
**Pull request by NamamiShanker**
#### Reference issue
Closes: #14190 

#### What does this implement/fix?
Removes link to alpha and add math styling to an equation.

### CODE REVIEW

**Comment by madphysicist** [comment]
Is there a way to meaningfully fix the links to the methods at the bottom?

**Comment by NamamiShanker** [comment]
@madphysicist I don't think Sphinx renders the documentation of methods of dirichlet_gen class. I don't think we can link them. What do you suggest @ilayn?

**Comment by ilayn** [comment]
Since our stats residents are making substantial changes lately, I'd better shut up to avoid misleading you. I've requested some reviews and I'm sure one of them will stop by.

**Comment by mdhaber** [comment]
I don't think I can help much here, either, for a number of reasons.

I'll just mention that numpydoc standards for ["parameters"](https://numpydoc.readthedocs.io/en/latest/format.html#parameters) states that "variables" are supposed to be in single-backticks. 

I'm not sure how to link to method documentation.  There are a number of related issues; see e.g. gh-12848.

**Comment by madphysicist** [comment]
This is turning into more of a can of worms than I had initially expected.

**Comment by mdhaber** [comment]
I'd suggest making these `dirichlet`-specific fixes here and wait for a more complete response to gh-12848 to handle the rest.

**Comment by NamamiShanker** [comment]
> I'm not sure how to link to method documentation.
@mdhaber are method documentation generated by Sphinx?

**Comment by mdhaber** [comment]
@NamamiShanker Maybe the problem is that there is an explicit "Methods" section; perhaps if it's not there Sphinx will automatically generate it. gh-14207 tests this idea based on the fact that [`NumericalInverseHermite`](http://scipy.github.io/devdocs/reference/generated/scipy.stats.NumericalInverseHermite.html) does not have an explicit Methods section and Sphinx seems to generate it.

**Comment by NamamiShanker** [comment]
@mdhaber @madphysicist I will look into generating method documentation for objects from [this observation](https://github.com/scipy/scipy/pull/14207#issuecomment-857077944). Meanwhile, should we merge this PR?

**Review by WarrenWeckesser — APPROVED** [review]
I agree with @mdhaber: using double backticks for `alpha` makes sense here.  The numpy docstring standard says to use single backticks, but in this case, that creates an unwanted and potentially confusing link to an irrelevant web page.  Practicality beats purity, so let's avoid the bad link and go with double backticks.

I can go either way with the additional `:math:` markup.  I tend to prefer minimizing the use of LaTeX, but we don't have an objective set of guidelines to determine how much LaTeX is too much, and (for better or worse) decisions like this often come down to reviewers' personal preference, so I won't block this small use here.

**Review by mdhaber — APPROVED** [review]
LGTM, too. Thanks @NamamiShanker @madphysicist @WarrenWeckesser @ilayn!

**Pull request merged**
