### PR TITLE
STY: PEP8 amendments to io_matlab.py

### PR DESCRIPTION
**Pull request by jremes-foss**
Amended the block comments on lines 34 and 35 to be PEP8 compliant.

Thank you.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @Newman101, merged.

**Comment by rgommers** [comment]
@Newman101 if you're planning on making many more PEP8 fixes, would it be possible for you to bunch them together a bit?

**Comment by Newman101** [comment]
Sure, I bunch some of them together from now on.

**Comment by rgommers** [comment]
Thanks!

**Pull request merged**
