### PR TITLE
DOC: Remove the "Basic functions" section from the SciPy tutorial.

### LINKED ISSUE #12413: DOC: Remove the "Basic functions" section from the SciPy tutorial.
The ["Basic Functions"](http://scipy.github.io/devdocs/tutorial/basic.html) section of the SciPy tutorial is actually a small NumPy tutorial.  NumPy has great documentation, including tutorials, so I think we can simply remove this entire section.

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
To fix #12413 

#### What does this implement/fix?
Removed the "Basic functions" section from the SciPy tutorial.
The "Basic Functions" section of the SciPy tutorial is actually a small NumPy tutorial. NumPy has great documentation, including tutorials, so I think we can simply remove this entire section.

### CODE REVIEW

**Comment by peterbell10** [comment]
Perhaps instead of completely removing this section, it should be demoted to a short paragraph in the introduction stating a basic understanding of NumPy is required and links to their tutorials?

**Comment by AtsushiSakai** [comment]
> Perhaps instead of completely removing this section, it should be demoted to a short paragraph in the introduction stating a > basic understanding of NumPy is required and links to their tutorials?
I think that is good idea. 
What do you think? @WarrenWeckesser

**Comment by AtsushiSakai** [comment]
I updated code using @peterbell10 's idea.

**Comment by rgommers** [comment]
I'd say that linking to NumPy and how to find docs is already covered in the `Introduction` section: http://scipy.github.io/devdocs/tutorial/general.html. I don't quite see why we would want to keep a `Basic functions` section in the top-level overview of tutorials for a redundant couple of lines? Removing this entry would be good:

image

**Comment by AtsushiSakai** [comment]
Thank you for reviewing. I didn't know there is a doc link in the introduction. I agree. I deleted it again. PTAL.

**Comment by rgommers** [comment]
I think removing these files and tweaking `doc/source/tutorial/general.rst` was what @peterbell10 meant. That file could use a more extensive makeover, so let's not block merging this PR on it.

In it goes, thanks @AtsushiSakai.

**Pull request merged**
