### PR TITLE
MAINT: Use helper functions in ?tbtrs tests

### PR DESCRIPTION
**Pull request by Kai-Striega**
#### What does this implement/fix?

This PR tidies `TestTbtrs.test_random_matrices` by allowing it to use helper functions where possible. 

* ``generate_random_dtype_array`` is used to generate the bands rather than explicitly constructing random vectors
* ``_to_symmetric_banded`` is used to convert the full matrix ``A`` to banded storage ``ab``, further, this adds ``_to_banded``  a more generic version of ``_to_symmetric_banded``

The test constructs the banded matrix as a [dia_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.dia_matrix.html#scipy-sparse-dia-matrix) then massages the underlying data into `ab`. While this works, it is messy and could lead to some obscure bugs if the way the data is stored changes. Now the test is no longer dependent on the data's structure as it indexes the data directly.

#### Additional information

While ``_to_banded``  is not used here I've used a similar "trick" in #11890 / #11985. Adding it here will allow me to rebase those branches and have these functions without messing up my commit history too much.

Banded storage stores the diagonal bands of ``A`` in ``ab`` such that: ``ab[u + i - j, j] == a[i,j]`` for example, a (6, 6) matrix with 2 lower bands and 1 upper band is stored as:

```
*    a01  a12  a23  a34  a45
a00  a11  a22  a33  a44  a55
a10  a21  a32  a43  a54   *
a20  a31  a42  a53   *    *
```

where `*` elements are not referenced. sy/he banded storage uses a similar pattern except only the lower or upper bands are stored. Therefore, to store a sy/he banded matrix, only the number of unique diagonals and whether it is to be in lower or upper storage is required.

### CODE REVIEW

**Comment by ilayn** [comment]
I think this is slightly an overkill because you can always store the sub- super- diagonals and form each form easily by summing over `np.diag(..., k=n)` for the full and array slicing. 

In other words if you look at the banded storage scheme; say we have an 5x5 array `a` of 1 upper and 2 lower bands then 

```python
a = np.array([[ 1,  2,  0,  0,  0],
              [ 3,  4,  5,  0,  0],
              [ 6,  7,  8,  9,  0],
              [ 0, 10, 11, 12, 13],
              [ 0,  0, 14, 15, 16]])
```
so then conversion can be done going over the rows of the banded storage
```python
sub = 2; sup = 1; n = 5
ab = np.zeros([sub+sup+1, n])

for row, k in enumerate(range(sup, sub-1, -1)):
    ab[row, max(k, 0):min(n+k, n)] = np.diag(a, k=k)
```
which is almost a one-liner and in my opinion doesn't even grant a full blown functions. I don't mind repeating this in `?.b....` wrappers because I don't think we would need this function that often except some tests.

Note that we are only testing the wrappers not testing the correctness of the LAPACK functions. It's nice if we can squeeze in some verifications but I fear that this `test_lapack.py` file is getting a bit bloated and becoming almost as if a separate SciPy module.

**Comment by Kai-Striega** [comment]
OK. I'll add that version in. Let's do it in this PR as I don't like how I've done it originally. 

>  I fear that this test_lapack.py file is getting a bit bloated and becoming almost as if a separate SciPy module.

I think this should be better, or at least not getting much bigger, now that the grant is done. If you want I can go through our tests and see if we can strip any of the larger tests back a bit.

**Comment by mdhaber** [comment]
I don't think we went overboard, but we were definitely thorough. I agree that the file is getting really long. I wouldn't argue with it being broken up.
Sorry I can't review these right now.

**Comment by ilayn** [comment]
Let's get also this one in. Thanks all!

**Pull request merged**
