### PR TITLE
TST/MAINT: special: test with CuPy, make some CUDA fixes

### PR DESCRIPTION
**Pull request by steppi**
#### What does this implement/fix?

This PR makes a handful of fixes that are needed for some C++ special functions in `scipy/special/special/` to work in CuPy. I've also added a framework for testing that special functions work in CuPy; it autogenerates CuPy `ElementwiseKernel`s. It is incomplete in that it cannot handle ufuncs with signatures like `dd*dd->*i` for those which return multiple arguments, and it cannot handle gufuncs. I have only added tests for a handful of functions, but plan to follow up with more tests for more functions (and likely more CUDA fixes).

#### Additional information

@rlucas7, I whipped this up because you had mentioned you have some bandwidth to work on `special` this weekend, and I currently have no outstanding PRs. @izaid, you may be interested in this as well, but I know you are very busy at the moment.

### CODE REVIEW

**Comment by izaid** [comment]
This is great! Very useful, glad you went ahead and did it.

At some point, we may want to hook this into the normal tests. Perhaps there is a way to create a mock array API or something. In any case, great.

**Comment by steppi** [comment]
> At some point, we may want to hook this into the normal tests. Perhaps there is a way to create a mock array API special extension or something. In any case, great.

Unfortunately, the test is truly deserving of the `xslow` mark. Even just for the handful of functions here it takes over 2 minutes for these tests to complete.

I also want to point out to everyone other than @izaid, that the name `test_xsf_cuda.py` is because `xsf` is the name @izaid and I have settled on for the C++ special function library we are working on which we intend to split off from SciPy. We plan to change the namespace and folder for this library to `xsf` shortly. At the moment it is called `special`, which is a bit confusing.

**Comment by steppi** [comment]
@fancidev, I've made `iv_ratio` work on CUDA here, following up on https://github.com/scipy/scipy/pull/20457#pullrequestreview-2051490549.

**Comment by fancidev** [comment]
> @fancidev, I've made `iv_ratio` work on CUDA here, following up on [#20457 (review)](https://github.com/scipy/scipy/pull/20457#pullrequestreview-2051490549).

Thank you very much @steppi !

Are the CUDA tests added by this PR going to be included in the CI workflow? If included, it could be helpful for people without CUDA (like me) to fix the code errors by checking the error messages in the CI logs.

Btw, if you split the code into a separate C++ library for the wider audience, I expect some C++ folks will frown upon changing things in the `std` namespace (when using CUDA), because it is supposed to lead to _undefined behavior_. For better cooperation with other potential user code, it may be better to make an `xsf` specific namespace (such as `xsf::std`) to do what you now do with `std`. In addition, if someone wants to call CUDA version and CPU version of a special function in the same binary, is it possible for them to do so?

**Comment by steppi** [comment]
> Are the CUDA tests added by this PR going to be included in the CI workflow? If included, it could be helpful for people without CUDA (like me) to fix the code errors by checking the error messages in the CI logs.

Not at the moment, the tests are 1) very slow, 2) require a machine with an NVIDIA GPU, and 3) SciPy's test suites already take very long to finish. We've discussed adding GPU CI after splitting the library off though.

> Btw, if you split the code into a separate C++ library for the wider audience, I expect some C++ folks will frown upon changing things in the `std` namespace (when using CUDA), because that [leads to undefined behavior](https://stackoverflow.com/questions/37541022/what-are-the-reasons-that-extending-the-std-namespace-is-considered-undefined-be). For better cooperation with other potential user code, it may be better to make an `xsf` specific namespace (such as `xsf::std`) to do what you now do with `std`. In addition, if someone wants to call CUDA version and CPU version of a special function in the same binary, is it possible for them to do so?

You're preaching to the choir about injecting things into `std` and this has already been discussed extensively; it's just a temporary expedient. @izaid proposed doing things this way for now as a temporary shortcut as we get things off the ground. Right now we are just trying to ensure things can be used in both SciPy and CuPy and are focusing on the functions themselves.

> In addition, if someone wants to call CUDA version and CPU version of a special function in the same binary, is it possible for them to do so?

When compiling for CUDA, everything is marked as `__host__ __device__` and `libcudacxx` is cross platform, so I think this should work. No one has tested it yet though.

**Comment by izaid** [comment]
> > Btw, if you split the code into a separate C++ library for the wider audience, I expect some C++ folks will frown upon changing things in the `std` namespace (when using CUDA), because that [leads to undefined behavior](https://stackoverflow.com/questions/37541022/what-are-the-reasons-that-extending-the-std-namespace-is-considered-undefined-be). For better cooperation with other potential user code, it may be better to make an `xsf` specific namespace (such as `xsf::std`) to do what you now do with `std`. In addition, if someone wants to call CUDA version and CPU version of a special function in the same binary, is it possible for them to do so?

Yeah, I'm not really bothered by this. Yes, theoretically, it's undefined behaviour. In practice, I've not seen it be an issue. I think we should try to make things be as easy for people developing the library as possible, and if that means injecting things into `std` because CUDA is missing (say) `std::complex` then so be it. We can reevaluate this as we go, but for now the effort should be expended on the numerical algorithms.

To be clear, we are simply putting things into `std` which are missing on other platforms. Of course no one should just put random custom things into `std`.

> > In addition, if someone wants to call CUDA version and CPU version of a special function in the same binary, is it possible for them to do so?

Yes, that is what `__host__ __device__` means generally in CUDA. Also the library is header-only, so there's no binary.

**Comment by steppi** [comment]
> To be clear, we are simply putting things into `std` which are missing on other platforms. Of course no one should just put random custom things into `std`.

Yeah, that's an important point I should have mentioned. When compiling for CUDA, there is no `std`; we're injecting things there so we can use the same namespace in both CUDA and regular C++ while making the C++ code look "normal". I think the only potential issue here is not playing nice with other code which also injects things into `std`, like [cuda_workaround.h](https://github.com/cupy/cupy/blob/main/cupy/_core/include/cupy/cuda_workaround.h) in CuPy. This for instance means that our C++ special functions cannot currently be used in most other CUDA code in CuPy code outside of `special`.

**Comment by rlucas7** [comment]
I took a look today. I was able to run the tests which all pass but the tests for cupy are skipped unless run on a gpu device (as described already in the thread). I was going to try to setup a gpu device to run the tests but I'm not able to access the account with gpu devices @steppi and I've been sharing) Albert are you able to access? 

If so that means it is something  on my end I can work to resolve.

**Comment by steppi** [comment]
> I took a look today. I was able to run the tests which all pass but the tests for cupy are skipped unless run on a gpu device (as described already in the thread). I was going to try to setup a gpu device to run the tests but I'm not able to access the account with gpu devices @steppi and I've been sharing) Albert are you able to access?
> 
> If so that means it is something on my end I can work to resolve.

I'm able to access the account without issue. I can dm you on the scipy community slack so we can troubleshoot.

**Comment by rlucas7** [comment]
> > I took a look today. I was able to run the tests which all pass but the tests for cupy are skipped unless run on a gpu device (as described already in the thread). I was going to try to setup a gpu device to run the tests but I'm not able to access the account with gpu devices @steppi and I've been sharing) Albert are you able to access?
> > If so that means it is something on my end I can work to resolve.
> 
> I'm able to access the account without issue. I can dm you on the scipy community slack so we can troubleshoot.

I think I figured it out this morning, sent the details in response to dm. Thanks! When I get some time this week I'll try to test it in the cuda.

**Comment by rlucas7** [comment]
>When I get some time this week I'll try to test it in the cuda.

I setup a clean env using the DL ami in aws and i'm not able to get the test module here `test_xsf_cuda.py` to be executed by the test harness, there must be something I'm missing @steppi ? 

What I've done: 

1. clean install of this PR with cupy  and cuda 12.1 on aws dl ami 
2. reran clean build after `git clean -xdf`

Is there an env var that maybe need to be set for the  `test_xsf_cuda.py` module to execute? 

I'm also not sure how to confirm that the cuda kernel's are getting properly compiled with the `python dev.py test` harness here.

**Comment by rlucas7** [comment]
> > When I get some time this week I'll try to test it in the cuda.
> 
> I setup a clean env using the DL ami in aws and i'm not able to get the test module here `test_xsf_cuda.py` to be executed by the test harness, there must be something I'm missing @steppi ?
> 
> What I've done:
> 
> 1. clean install of this PR with cupy  and cuda 12.1 on aws dl ami
> 2. reran clean build after `git clean -xdf`
> 
> Is there an env var that maybe need to be set for the `test_xsf_cuda.py` module to execute?
> 
> I'm also not sure how to confirm that the cuda kernel's are getting properly compiled with the `python dev.py test` harness here.

Ah spoke/wrote too soon, I think I figured it out, @steppi I sent you a dm with the particulars, lmk if that looks correct to you and if so I can post the specifics.

**Comment by rlucas7** [comment]
> Ah spoke/wrote too soon, I think I figured it out, @steppi I sent you a dm with the particulars, lmk if that looks correct to you and if so I can post the specifics.

I'm able to run the tests on the gpu device via removing the 

```
@pytest.mark.xslow
```
and modifying the cupy version that I had installed on that machine to `13.1.0`

Here is a screenshot of the `test_xsf_cuda.py` module getting executed. 

Screen Shot 2024-05-27 at 9 15 15 PM

We'll probably want to circle back to this after the refactor to figure out a more repeatable way for the tests to be executed. 

For now it's good we can confirm they execute ok on an independent device in a somewhat repeatable way.  

I think setting the env var 

```
export SCIPY_XSLOW=1
```
should also work in case someone prefers that way. 

Marking approved in favor of forward progress.

**Review by rlucas7 — APPROVED** [review]
left a comment about particulars to confirm the cupy cuda test module executes.

**Comment by rlucas7** [comment]
also just noting here the failed tests/actions appear unrelated e.g. 

https://github.com/scipy/scipy/actions/runs/9101123182/job/25017550168?pr=20701#step:7:1116 

is about basin hopping which isn't touched here

**Comment by rgommers** [comment]
Thanks @steppi. I think this is a good idea. And I see a GPU CI job materializing at some point (maybe first on `xsf`, or on this repo).

I gave this a quick try, didn't quite work yet in a conda env with CuPy 13.1 and CUDA 12:
```
/home/rgommers/mambaforge/envs/scipy-dev-jax-cu12/lib/python3.12/site-packages/cupy/cuda/compiler.py:696: in compile
    raise CompileException(log, self.src, self.name, options,
E   cupy.cuda.compiler.CompileException: /home/rgommers/code/bldscipy/build-install/lib/python3.12/site-packages/scipy/special/special/config.h(68): catastrophic error: cannot open source file "cuda_runtime.h"
E     #include <cuda_runtime.h>
E                              ^
E   
E   1 catastrophic error detected in the compilation of "/tmp/tmpkq9ejm7t/c11e0bb1a19a07c2caeb92e970aee089008dadc1.cubin.cu".
E   Compilation terminated.
```

The header does exist, but apparently isn't on the header search path:
```
$ locate cuda_runtime.h
...
/home/rgommers/mambaforge/envs/scipy-dev-jax-cu12/targets/x86_64-linux/include/cuda_runtime.h 
```
I don't have time to dig in right now, but if you know what the problem is then please let me know.

**Comment by steppi** [comment]
> Thanks @steppi. I think this is a good idea. And I see a GPU CI job materializing at some point (maybe first on `xsf`, or on this repo).
> 
> I gave this a quick try, didn't quite work yet in a conda env with CuPy 13.1 and CUDA 12:
> 
> ```
> /home/rgommers/mambaforge/envs/scipy-dev-jax-cu12/lib/python3.12/site-packages/cupy/cuda/compiler.py:696: in compile
>     raise CompileException(log, self.src, self.name, options,
> E   cupy.cuda.compiler.CompileException: /home/rgommers/code/bldscipy/build-install/lib/python3.12/site-packages/scipy/special/special/config.h(68): catastrophic error: cannot open source file "cuda_runtime.h"
> E     #include <cuda_runtime.h>
> E                              ^
> E   
> E   1 catastrophic error detected in the compilation of "/tmp/tmpkq9ejm7t/c11e0bb1a19a07c2caeb92e970aee089008dadc1.cubin.cu".
> E   Compilation terminated.
> ```
> 
> The header does exist, but apparently isn't on the header search path:
> 
> ```
> $ locate cuda_runtime.h
> ...
> /home/rgommers/mambaforge/envs/scipy-dev-jax-cu12/targets/x86_64-linux/include/cuda_runtime.h 
> ```
> 
> I don't have time to dig in right now, but if you know what the problem is then please let me know.

That’s interesting. I wonder if the problem exists for the ufuncs I’ve added to CuPy already. I’ll look into it. Can you post some system info and how you installed CuPy so I can try to reproduce?

**Comment by rgommers** [comment]
> That’s interesting. I wonder if the problem exists for the ufuncs I’ve added to CuPy already. I’ll look into it. Can you post some system info and how you installed CuPy so I can try to reproduce?

It's Linux x86-64, and I created the env by editing `environment.yml`, adding `cupy` and `cudatoolkit` and changing the env name, then running `mamba env create -f environment.yml`.

**Comment by rlucas7** [comment]
> I gave this a quick try, didn't quite work yet in a conda env with CuPy 13.1 and CUDA 12:

FWIW I did not use a conda env, I used a venv. 

My notes indicate I did this: 

```
# after git clone scipy into ec2 (ubuntu 22.04 with nvidia ami on aws)
cd scipy 
git fetch origin pull/20701/head:MASTER
git checkout MASTER
git submodule update --init
sudo apt update --fix-missing
sudo apt install python3.10-venv -y 
sudo apt install python3-pip -y 
python3 -m venv $HOME/.venvs/scipy-dev
source $HOME/.venvs/scipy-dev/bin/activate
# install necessary dependencies 
python3 -m pip install numpy pytest cython pythran pybind11 meson ninja pydevtool rich-click hypothesis meson-python
python3 -m pip install pooch 

# these may be already present on system ...
sudo apt install pkg-config
sudo apt install gfortran
sudo apt install cmake
sudo apt install g++ 
sudo apt install libopenblas-dev -y

# now run the full build this does cpu only though 
python dev.py test

# tests took awhile to complete about 26 minutes for full suite (excluding the marked slow)
# the xsf cuda tests were skipped on the full run 

# now install cupy on the host
pip install cupy-cuda12x

# running to confirm the nvrtc is found
ldconfig -p | grep libnvrtc.so

# to run the test itself use:
python dev.py test -t scipy.special.tests.test_xsf_cuda.py

# and in a separate ssh session login to the same machine
# and run nvidia-smi while the tests execute as a quick n easy 
# way to confirm that the gpu is being used 
```

I'd probably say use `nvtop` for a more interactive workflow 
but the above  seemed to indicate this worked

@steppi and @rgommers if it helps I can rerun the above on an ami 
in the aws account to double check things

**Comment by steppi** [comment]
@rgommers, I tried using `conda` instead of `pip + virtual environment` to manage dependencies for the development build and didn't experience the issue you saw. This is with Ubuntu 22.04 on x64. I did however run into #19085 and had to make the same modifications to `environment.yml` that were suggested there: comment out compilers, python, and pythran, and add the lines

```yml
- pip
- pip:
   - pythran
```

**Comment by rgommers** [comment]
Okay, feel free to ignore the issue then - I'll figure it out when I have more time. The Ubuntu 22.04 issue should be a bug in the glibc/multiarch support on Ubuntu 22.04, or conda-forge's interaction with it somehow. Let's ignore that too.

**Comment by steppi** [comment]
> Okay, feel free to ignore the issue then - I'll figure it out when I have more time. The Ubuntu 22.04 issue should be a bug in the glibc/multiarch support on Ubuntu 22.04, or conda-forge's interaction with it somehow. Let's ignore that too.

OK, sounds good. I would guess conda-forge's interaction with it. @rlucas7, see above.

**Comment by steppi** [comment]
We have one approval and @rgommers said we could feel free to ignore the issue he observed when using `conda` for now. If no objections, I plan to merge this on Monday.

**Comment by rlucas7** [comment]
> We have one approval and @rgommers said we could feel free to ignore the issue he observed when using `conda` for now. If no objections, I plan to merge this on Monday.

That's fine by me @steppi, the only failure here on the PR is [this one](https://github.com/scipy/scipy/actions/runs/9571225741/job/26387800916#step:11:333) which looks like a array api compatibility issue that seems unrelated.

**Comment by mdhaber** [comment]
> the only failure here on the PR is this one which looks like a array api compatibility issue that seems unrelated.

And was fixed three weeks ago : )

**Comment by jakirkham** [comment]
> > That’s interesting. I wonder if the problem exists for the ufuncs I’ve added to CuPy already. I’ll look into it. Can you post some system info and how you installed CuPy so I can try to reproduce?
> 
> It's Linux x86-64, and I created the env by editing `environment.yml`, adding `cupy` and `cudatoolkit` and changing the env name, then running `mamba env create -f environment.yml`.

Pretty late to the party here unfortunately

That said, `cudatoolkit` is a legacy thing at this point. Just CUDA 11 and earlier

With CUDA 12+ onwards the CUDA Toolkit has been split up into a number of granular packages

General advice would be just use the `cuda-version` package (same way as the `cudatoolkit` package was before) and should get the right behavior for both old CUDA versions (back to CUDA 9.2) and new ones (currently up to CUDA 12.5)

More info in...

* The 2023 SciPy talk on this work:
  * [Abstract]( https://cfp.scipy.org/2023/talk/DQR9NU/ )
  * [Video]( https://youtu.be/WgKwlGgVzYE )
  * [Slides]( https://github.com/scipy-conference/scipy_proceedings/blob/2023/presentations/slides/cuda_toolkit_conda/SciPy_2023--New_CUDA_Toolkit_packages_for_Conda.pdf )
* conda-forge CUDA 12 effort
  * CUDA SDK Build order: https://github.com/conda-forge/staged-recipes/issues/21382
  * Bringup issue: https://github.com/conda-forge/conda-forge.github.io/issues/1963
* New CUDA Toolkit package documentation
  * [README]( https://github.com/conda-forge/cuda-feedstock/blob/main/recipe/README.md )

Happy to discuss and answer more questions as needed 🙂

**Pull request merged**
