### PR TITLE
ENH: wrap gtsv and ptsv for solve_banded and solveh_banded.

### PR DESCRIPTION
**Pull request by ewmoore**
For a (1000, 1000) tridiagonal system I find about a 2x speed up.

### CODE REVIEW

**Comment by ewmoore** [comment]
Closes #4206.

**Comment by argriffing** [comment]
I think it is weird that `solveh_banded` and its tridiagonal variant require the matrix to be positive definite.  The `h` as a suffix of a function name doesn't generally have this meaning in scipy -- the functions `pinvh` and `eigh` don't require positive definiteness; they just require the matrix be hermitian or real symmetric.  Also it's not like there aren't LAPACK functions for hermitian or real symmetric banded or tridiagonal solvers that do not require positive definiteness.

**Comment by argriffing** [comment]
Looks good to me; my nitpick about hermitian vs. positive definite is not in the scope of this PR.  I haven't worked with f2py so I'm too squeamish to merge this myself.

**Comment by ewmoore** [comment]
@ev-br, any thoughts? This addresses #4206 which you submitted.

**Comment by ev-br** [comment]
@argriffing IMO it would be good to figure out how to relax the positive definiteness restriction, but I agree it's best done separately

LGTM, merging. Thanks @ewmoore!

**Comment by pv** [comment]
TODO: also add *ptsv *gbsv to scipy.linalg.lapack.__doc__

**Comment by ev-br** [comment]
a follow-up doc-only PR: gh-4448

**Pull request merged**
