### PR TITLE
TST: fix test failures from Matplotlib 2.1 update

### PR DESCRIPTION
**Pull request by person142**
Closes gh-7997.

### CODE REVIEW

**Comment by person142** [comment]
Ugh forgot that there are also a bunch of refguide check errors that need to be fixed too.

**Comment by pv** [comment]
Thanks, merging. Added some stopwords to make refguide check pass.

OSX still fails, but apparently due to some different reason (pip or homebrew failure) :/

**Comment by person142** [comment]
I wonder if @matthew-brett would understand the failure better?

**Comment by pv** [comment]
Not sure. the osx failure is probably sporadic, seems to have appeared by itself and maybe goes away in the same way

**Comment by pv** [comment]
Or, maybe there was some recent change in multibuild we should adapt to?

**Comment by xoviat** [comment]
You know what, hombrew no longer works on Travis OSX. That might be it.

**Comment by pv** [comment]
Any more info about that? E.g. is it gone for good or just temporary?

**Comment by xoviat** [comment]
travis-ci/travis-ci#8552

**Comment by pv** [comment]
added HOMEBREW_NO_AUTO_UPDATE=1 to travis settings, which seems to have fixed it

**Comment by rgommers** [comment]
backported to 1.0.x in gh-8041

**Pull request merged**
