### PR TITLE
ENH: special: add long double implentations of `expi`, `exp1`

### LINKED ISSUE #1853: Provide float96 / float128 versions of exponential integral scipy.special.expi(x) (Trac #1327)
_Original ticket http://projects.scipy.org/scipy/ticket/1327 on 2010-11-12 by @zyv, assigned to @pv._

Hi!

Exponential integral saturates very quickly and already for values > 800 provokes an overflow. 

I could have used float96 / float128 as supported by numpy, however, when I try it, I get the following exception:

TypeError: function not supported for these types, and can't coerce safely to supported types

which implies, that it is not implemented (yet?). Therefore, I would like to request an extension of this function to the extended precision doubles.

Thanks!

### PR DESCRIPTION
**Pull request by person142**
This ports the current Fortran implementation to Cython and uses fused
types so that the new dispatches share a common implementation.

Closes gh-1853.

Note that some of the testing machinery is not set up to handle long doubles. If we want to do more of this in the future (I think we should) then we'll have to improve it.

### CODE REVIEW

**Comment by person142** [comment]
This also adds a specific float dispatch. Is it worth it?

**Comment by xoviat** [comment]
Why are the Fortran routines not removed?

**Comment by person142** [comment]
> Why are the Fortran routines not removed?

It looks like only `EIX` and `EXNA` call `E1XB` and we don't use `EXNA`, so it could be removed.

**Comment by person142** [comment]
Ok, think I got the issues on Linux sorted out, though of course we'll see what Travis has to say.

**Comment by ewmoore** [comment]
Another thing to think about is that long double isn't the same everywhere.  Generally long double is double on windows and on x86 linux it's 80 bits.  There are also other systems where long double might map to a double-double or to a true quad precision type.  So constants might need to change depending on platform or the number of terms might need to change, etc. and it becomes hard to test all of these things because we don't have CI on all of these platforms.

**Comment by person142** [comment]
Yes, all of this is a concern. I've done my best to mitigate:

- Floating point constants in the code are cast to the correct type (or use a small helper function that returns the correct type, as in the case of Euler's constant)
- Halting conditions for series are specified in multiples of machine epsilon for each type
- Test tolerances are specified in multiples of machine epsilon

But I imagine that there will still be bugs to fix on some platforms. I guess at a certain point we may decide that all the fuss isn't worth it. (Opinions?)

**Comment by person142** [comment]
Huh, one of the new failures is due to NumPy doing long double conversions incorrectly in older versions:

```
>>> np.finfo(np.longdouble).tiny
3.3621031431120935063e-4932
>>> np.longdouble('1.510844151217505622921e-4836')
0.0
>>> np.__version__
'1.8.2'
```

```
>>> np.finfo(np.longdouble).tiny
3.3621031431120935063e-4932
>>> np.longdouble('1.510844151217505622921e-4836')
1.5108441512175056229e-4836
>>> np.__version__
```

This is a pain to work around, does anyone object to just skipping on too-old NumPy?

**Comment by person142** [comment]
Ok, finally got all the CIs happy. Added the "needs-decision" label to indicate that we should think about whether it's worth adding extended precision functions given the risks pointed out by @ewmoore.

**Comment by person142** [comment]
Closing-we've decided we aren't interested in longdouble implementations.

**Pull request closed without merging**
