### PR TITLE
DOC: forward port 0.15.x release notes and update author name mapping

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
@bewithaman and @aman-thakral, do you also want your name included in the release notes? If so, please let me know your full name.

**Comment by bewithaman** [comment]
@rgommers Yes, that would be great. My name is Aman Singh. Thanks.

**Comment by rgommers** [comment]
thanks @bewithaman

**Comment by rgommers** [comment]
This is good to go now.

**Comment by aman-thakral** [comment]
@rgommers sorry just saw this.  The emails were in my spam folder.  My name is Aman Thakral.

**Comment by rgommers** [comment]
@aman-thakral thanks, I figured it out already - your committer name was set correctly, only your author name wasn't

**Pull request merged**
