### PR TITLE
Backports for 1.0.1

### PR DESCRIPTION
**Pull request by rgommers**
Backports for:
- gh-8082 `linalgsolve_lyapunov` not importable
- gh-8144 `optimize.cobyla` fix
- gh-8248 `optimize.ncg` issue
- gh-8530 `linalg.flapack` issue (fix build issue with numpy master)
- gh-8237 `optimize.linprog` issue
- gh-8187 `stats.ortho_group_gen` issue
- gh-8215 `ndimage.gaussian_filter` float16 segfault
- gh-8322 `optimize.root` segfault
- gh-8280 `sparse.csgraph`
- gh-8150 resolve UPDATEIFCOPY deprecation errors 
- gh-8566 pin Cython version in CI to 0.27.3
- gh-8068 fix NumPy 1.14.0 deprecation failures
- gh-8477 fix segfault in `signaltools`
- gh-8197 fix CI issue on macOS
- gh-8334 fix issue with `stats.mstats.hdmedian` test
- gh-8156 fix regression in `spatial.minkowski`

### CODE REVIEW

**Comment by rgommers** [comment]
Wow that's a lot of failures:(

**Comment by pv** [comment]
Do you want to cherrypick gh-8477 also, that's one segfault bug less? This is especially visible on Pypy, which is less forgiving for bad refcounting and on which this makes the test suite segfault.

**Comment by rgommers** [comment]
Thanks Pauli, done. Also fixed the refguide check CI config to numpy 1.13.3 (1.14.x printing behavior keeps changing still), and silenced one stats runtime warning. Should be down to a single CI issue now, some Fortran related build failure on macOS.

**Comment by rgommers** [comment]
That last issue looks like gh-8197, installing `oclint` on macOS and using `cd` instead of `pushd`.

**Comment by rgommers** [comment]
All green finally - I think this is the complete list of backports.

**Comment by rgommers** [comment]
In it goes. Release notes are next

**Pull request merged**
