### PR TITLE
ENH: Add a numerically stable logpdf function for the skewnorm distribution

### PR DESCRIPTION
**Pull request by maresb**
#### Reference issue

None

#### What does this implement/fix?

Improves the numerical stability of the `scipy.stats.skewnorm.logpdf` function

#### Additional information

I add a test to check large `x`-values where the logpdf previously evaluated to `-inf`. The test also includes the case `a=0` where `skewnorm` becomes `norm`.

### CODE REVIEW

**Review by mdhaber — COMMENTED** [review]
This looks easier to check than most. I'm not seeing any gotchas here. For example, all three terms in the sum have the same sign, so it looks like there's no chance of catastrophic cancellation. I'll check against Mathematica tomorrow and probably merge.

**Comment by maresb** [comment]
Thanks a lot @mdhaber, I really appreciate it!

I just realized that I missed the most important test case for my purposes: large `a` values since these result from `skewnorm.fit` when the true answer is `inf`. I added in this test case with both signs; I hope it's okay that I rebased to keep my commits clean (should be easy to verify using the "Compare" button).

**Comment by mdhaber** [comment]
Whoa is the "compare" button new? I've not noticed it before, and nobody has mentioned it when I've lamented about force-push.

**Review by mdhaber — APPROVED** [review]
This is a clear improvement to `skewnorm.logpdf`. I appreciate the careful separation of commits, starting with tests that would fail in main, and useful commit messages. The tests look reasonable. We could quibble about the test name (it's not just for large `x` now) and style (I'd prefer to use `scipy.stats.tests.test_generation.reference_distributions.SkewNormal.logpdf` rather than Wolfram Alpha, since it simplifies computation and verification of reference values) but this is fine in the short time before a better option is available (gh-15928).

**Pull request merged**
