### PR TITLE
MAINT: Replace some Unicode dash-like chars with an ASCII hyphen.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
A trivial change, but let's minimize the use of non-ASCII characters.

Also modernize a string used as a warning message.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The test failure is the recurring "Windows Python36-32bit-full" 60 minute time out.

**Review by larsoner — APPROVED** [review]

**Review by rlucas7 — APPROVED** [review]
These changes are all unicode/string related and very minor, not sure why the didn't get merged before with the previous approval though so I'm holding off. If they're still here this coming weekend I'll merge. 

Marking as approved for now.

**Comment by WarrenWeckesser** [comment]
Thanks @rlucas7.  I assume that it wasn't merged earlier to allow for more time for review from other devs.  But now that there are *two* approvals...

**Comment by tylerjereddy** [comment]
Thanks Warren et al.

**Comment by WarrenWeckesser** [comment]
If anyone has a moment, another PR with a tiny change is https://github.com/scipy/scipy/pull/12404.  Once that PR is merged, we can move ahead with https://github.com/scipy/scipy/pull/12393, which will make the message about unwanted unicode characters much nicer.

**Pull request merged**
