### PR TITLE
DEP: remove `right` from interpolate.PPoly.extend

### LINKED ISSUE #15752: DEP: remove right keyword from interpolate.extend
Deprecated since #6315

### PR DESCRIPTION
**Pull request by ML-Nielsen**
#### Reference issue
Closes gh-15752.

#### What does this implement/fix?
The `right` keyword was deprecated  #6315. This PR removes it.

### CODE REVIEW

**Review by h-vetinari — APPROVED** [review]
Thanks! :)

**Comment by h-vetinari** [comment]
However, your commit history is a bit off. We can solve this by squash-merging, but in general (and for the future) I'd suggest to do something like:
```
git fetch upstream  # or however you called this repo, as opposed to your fork
git rebase -i upstream/main
# edit lines so that only relevant (=the last in this case) commit remains
git push -f ML-Nielsen deprecation/right_interpolate_extend
```

Not having extraneous commits in the history makes reviewing easier (though rebasing should be used sparingly otherwise, as it loses the "changes since you last reviewed" baseline for anyone looking at the PR).

**Review by tupui — APPROVED** [review]
Thanks @ML-Nielsen and @h-vetinari. LGTM, the warning has been long enough there so we can remove the parameter.

**Comment by ML-Nielsen** [comment]
Thank you for the review @tupui.

I thought the commit history looked off, but I didn't know why. Thanks a lot for telling me @h-vetinari, I'll remember to rebase in the future.

**Pull request merged**
