### PR TITLE
ENH: Add gesvd method for svd

### LINKED ISSUE #4994: Wrap LAPACK.dgesvd for singular value decomposition
Currently, scipy only wraps dgesdd, which does essentially the same thing, but makes very mild assumptions about floating point arithmetic. At least in some cases, this approach fails and dgesvd works more robustly.
Also, it seems that other platforms (e.g. Matlab and Octave) use the dgesvd implementation.

http://www.netlib.org/lapack/explore-html/db/db4/dgesdd_8f.html

http://www.netlib.org/lapack/explore-html/d8/d2d/dgesvd_8f.html

### PR DESCRIPTION
**Pull request by larsoner**
First pass at adding `gesvd` to complement `gesdd` method for `svd`.

Closes #4994.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@pv feel free to comment on if you think this approach makes sense. I hope to find time to get it working fully in the next couple of weeks.

**Comment by ewmoore** [comment]
When adding something similar to `lstsq` we called the argument `lapack_driver` and just directly used the the names of the lapack functions as the option names.  It would be good to be consistent.

**Comment by Eric89GXL** [comment]
Sounds good, will change to `lapack_driver='gesdd' | 'gesvd'`

**Comment by Eric89GXL** [comment]
Okay @pv @ewmoore this one should be good to go now.

**Pull request merged**
