### PR TITLE
BUG: special: `cython_special` missing dep

### LINKED ISSUE #21217: BUG: SciPy won't pick the correct BLAS when running the test suite in a debug configuration
### Describe your issue.

SciPy tests cannot be run due to a missing symbol provided by LAPACK/BLAS (according to @ev-br), which doesn't have the `scipy_` prefix when using `scipy-openblas`. This is occurring when SciPy is compiled in a debug configuration, either via `dev.py build --debug` or `--config-settings=setup-args="-Dbuildtype=debug"` using pip. 

This issue is occurring both in CPython 3.12 and 3.13t. An important note is that when a release configuration is set, this error is not occurring, thus something is going wrong when setting the debug compilation flags and their interaction with the `BLAS_SYMBOL_PREFIX` macro flag.

### Reproducing Code Example

```python
docker pull quay.io/pypa/manylinux2014_x86_64
docker run -it quay.io/pypa/manylinux2014_x86_64 /bin/bash

cd home
export PATH=/opt/python/cp312-cp312/bin/:$PATH
git clone https://github.com/scipy/scipy.git --recursive

python -m pip install -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy cython
python -m pip install ninja meson-python pybind11 pythran
python -m pip install pytest hypothesis pooch

cd scipy
python -m pip install -r requirements/openblas.txt
python -c "import scipy_openblas32; print(scipy_openblas32.get_pkg_config())" > scipy-openblas.pc

PKG_CONFIG_PATH=$PWD pip install -e . -vvv --no-build-isolation  --config-settings=setup-args="-Dbuildtype=debug"
pytest -x -v scipy
```

### Error message

```shell
ImportError while importing test module '/home/scipy/scipy/differentiate/tests/test_differentiate.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/python/cp312-cp312/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/differentiate/tests/test_differentiate.py:11: in <module>
    from scipy import stats, optimize, special
scipy/__init__.py:136: in __getattr__
    return _importlib.import_module(f'scipy.{name}')
/opt/python/cp312-cp312/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:602: in <module>
    from ._stats_py import *
scipy/stats/_stats_py.py:51: in <module>
    from . import distributions
scipy/stats/distributions.py:10: in <module>
    from . import _continuous_distns
scipy/stats/_continuous_distns.py:24: in <module>
    from . import _stats
_stats.pyx:1: in init scipy.stats._stats
    ???
E   ImportError: /home/scipy/build/cp312/scipy/special/cython_special.cpython-312-x86_64-linux-gnu.so: undefined symbol: dstevr_
```

### SciPy/NumPy/Python version and system information

```shell
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.0",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../../opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27.dev",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include",
      "lib directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64",
      "pc file directory": "/home/scipy"
    },
    "lapack": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27.dev",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include",
      "lib directory": "/opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64",
      "pc file directory": "/home/scipy"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.13.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/_internal/cpython-3.12.4/bin/python",
    "version": "3.12"
  }
}
```

### PR DESCRIPTION
**Pull request by tylerjereddy**
* Fixes #21217

* Patch up a missing dependency for `cython_special` extension, introduced accidentally in a large PR as described in the bisection in above ticket. I didn't check why it only affects debug builds.

[skip circle] [skip cirrus]

### CODE REVIEW

**Review by ev-br — APPROVED** [review]
The fix looks obviously correct: Special functions either need lapack or they do not; since they do, it's a mystery why the missing dependency declaration did not cause failures across the board and why it only fails in the debug build. There is some spooky action on a distance in the build system apparently.

**Comment by lucascolley** [comment]
I merged, but indeed it would be good to figure out how this was working previously. Maybe you have an idea @thalassemia ?

**Comment by ilayn** [comment]
I don't remember any dependence to LAPACK from the parts I touched. Maybe other parts had.

**Comment by ev-br** [comment]
Yes, elliptic harmonics:

```
$ grep dstevr scipy/special -rn
scipy/special/lapack_defs.h:7:extern void BLAS_FUNC(dstevr)(char *jobz, char *range, CBLAS_INT *n, double *d, double *e,
scipy/special/lapack_defs.h:13:static void c_dstevr(char *jobz, char *range, CBLAS_INT *n, double *d, double *e,
scipy/special/lapack_defs.h:17:    BLAS_FUNC(dstevr)(jobz, range, n, d, e, vl, vu, il, iu, abstol, m,
scipy/special/_ellip_harm.pxd:40:    void c_dstevr(char *jobz, char *range, CBLAS_INT *n, double *d, double *e,
scipy/special/_ellip_harm.pxd:165:    c_dstevr("V", "I", &size, d, dd, &vl, &vu, &tp, &tp, &tol, &c, w, eigv,

```

**Comment by ilayn** [comment]
Then let me join the club of  spooky action at a distance.

**Comment by rgommers** [comment]
Thanks for the fix Tyler!

I still can't tell exactly what the problem was. It's very indirect - `_ellip_harm` uses a LAPACK function, and via the `functions.json` machinery that does end up in `_ufuncs.so`. But it doesn't get exposed in `cython_special.pxd`. So it may be something that is optimized out by the linker with `-O2` but hangs around in `cython_special.so` only with `-O0`.

**Comment by andfoy** [comment]
I confirm that this PR fixes the issue at hand! Thanks @tylerjereddy

**Pull request merged**
