### PR TITLE
FIX error, when reading 32-bit float wav files

### PR DESCRIPTION
**Pull request by raphaelw**
The FMT chunk of 32-bit float wave files has an additional "cbSize" field by convention. That means that their FMT chunk size is larger than 16 bytes by default. The current buggy version of _read_fmt_chunk(fid) overwrites the "wFormatTag" (called comp in the code) field of ALL files with a larger FMT chunk. Therefore wavfile.read() reads every 32-bit float wave file as 32-bit integer.

see Spec:
http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html

### CODE REVIEW

**Comment by pv** [comment]
This looks wrong --- `comp not in KNOWN_WAVE_FORMATS` does not imply `comp = WAVE_FORMAT_PCM`

**Comment by pv** [comment]
Of course, the original code has the same issue :-)

**Comment by raphaelw** [comment]
yes, i tried to make as few changes as possible. so i don't know why the original code assumed unknown formats as PCM (integer)

**Comment by raphaelw** [comment]
in commit `83af762` an exception is raised on unknown formats

**Comment by raphaelw** [comment]
i fixed the buggy implications of the original code.
in order to pass the file (test-44100-le-1ch-4bytes.wav) in the unit tests again, i had to implement the WAVE_FORMAT_EXTENSIBLE header (fmt chunk)

**Comment by raphaelw** [comment]
i now added corresponding unit tests to assure floating point wav file support. (32 and 64 bit)

**Comment by pv** [comment]
Thanks! 
Minor comment: the code probably should `raise ValueError` instead of `raise Exception`.

**Comment by raphaelw** [comment]
@pv i changed that exception
i just saw that there is a small error in the wavfile.write() function. it has to write an additional FACT chunk, if the output format is float. do i have to open a new pull request for this issue?

**Comment by pv** [comment]
You can do it in a new PR or here, this PR is not too large.

**Comment by raphaelw** [comment]
wavfile.write() now adds compliant header for non-PCM format (usually float):
- cbSize field in fmt chunk
- fact chunk

other fixes:
- original code falsely read every chunk size field as signed integer
- fixed endian independence (RIFX) of my pull request

other thoughts:
the global variable `_big_endian` is used to determine the endiannes of the current file. this is not thread safe. i'm not familiar with how strict the scipy project handles this topic. should it be mentioned in the doc string?

**Comment by raphaelw** [comment]
wavfile.write() now adds compliant header for non-PCM format (usually float):
- cbSize field in fmt chunk
- fact chunk

other fixes:
- original code falsely reads every chunk size field as signed integer
- fixed endian independence (RIFX) of my over all pull request

other thoughts:
the global variable `_big_endian` is used to determine the endiannes of the current file. this is not thread safe. i'm not familiar with how strict the scipy project handles this topic. should it be mentioned in the doc string?

**Comment by pv** [comment]
On the last point: this code is obviously written as a quick hack long ago, and was not revised.
Note that the `_big_endian` variable is never set to `False` except on the top of the file, so if you read one big endian file, *all* files after it will be considered big endian. Rather than a global variable, it should really be returned from `_read_riff_chunk` and passed in as an argument to the rest of the routines.

**Comment by raphaelw** [comment]
i implemented your suggestion. endianness is now determined correctly and passed to each chunk handler.

other changes:
- wavfile.write() now checks if the given data array exceeds the size limit of wave files

**Comment by raphaelw** [comment]
i implemented your suggestion. endianness is now determined correctly and passed to each chunk handler.

other changes:
- wavfile.write() now checks if the given data array exceeds the size limit of wave files

**Comment by pv** [comment]
Thanks, merged!

There are also some other low-hanging improvements that could be made (eg. reading 24-bit files) in the future.

**Pull request merged**
