### PR TITLE
BLD: update NumPy to >=1.19.5

### PR DESCRIPTION
**Pull request by tupui**
Regular bump after 1.9.x was branched (still slightly on the conservative side w.r.t. NEP 29).

We have some refs to 1.19.3. Not sure if I should bump these or not as well to 1.19.5 instead. And maybe there are other bumps related to NumPy to do.

### CODE REVIEW

**Review by jarrodmillman — APPROVED** [review]

**Comment by rgommers** [comment]
> We have some refs to 1.19.3. Not sure if I should bump these or not as well to 1.19.5 instead. And maybe there are other bumps related to NumPy to do.

Yes, it doesn't make sense to build against a version lower than the minimum supported one I think. I pushed a couple more tweaks.

**Comment by tupui** [comment]
ok thanks. Is there anything else to adjust?

**Review by rgommers — APPROVED** [review]
Should be good now, in it goes. Thanks @tupui

**Comment by tylerjereddy** [comment]
I wonder if this may cause a bit of annoyance in the wheels repo until I've branched there as well, since there could be some bounds flip-flop if I iterate while pointing to `main`, then branch in wheels repo to point back to the maintenance branch hashes again.

**Comment by rgommers** [comment]
I wouldn't expect that. Anything concrete you saw?

**Pull request merged**
