### PR TITLE
MAINT: update HiGHS submodule to include fix for Windows segfault

### LINKED ISSUE #15456: Segfault in HiGHS code when building with Mingw-w64 on Windows
Observing this consistently in the Meson Windows CI:

```
......                                                                   [ 40%]
Windows fatal exception: access violation

Current thread 0x000009d8 (most recent call first):
  File "D:\a\scipy\scipy\build\Lib\site-packages\scipy\optimize\_linprog_highs.py", line 405 in _linprog_highs
  File "D:\a\scipy\scipy\build\Lib\site-packages\scipy\optimize\_linprog.py", line 640 in linprog
  File "D:\a\scipy\scipy\build\Lib\site-packages\scipy\optimize\tests\test_linprog.py", line 288 in test_choose_solver
  File "C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\_pytest\python.py", line 183 in pytest_pyfunc_call
...
  File "<string>", line 1 in <module>
..\build\Lib\site-packages\scipy\optimize\tests\test_linprog.py .
Error: Process completed with exit code 1.
```

Before the update to a newer version of HiGHS in gh-15217 all tests were passing with the same build config. It looks like there are more issues with Mingw in HiGHS and it's not tested/supported yet upstream: https://github.com/ERGO-Code/HiGHS/issues/625.

Cc @mckib2.

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-15456

### CODE REVIEW

**Comment by rgommers** [comment]
All good here (`run_benchmarks` seems to be timing out consistently, that's not too interesting here). This fix was reviewed and tested upstream as well, so I'll go ahead and merge it.

**Comment by mdhaber** [comment]
Can this be included in 1.8.1 to fix gh-15730?

**Comment by tylerjereddy** [comment]
@mdhaber How do you propose I backport this given that HiGHS is vendored on the maintenance branch (at `scipy/optimize/_highs/src` it looks like) and a submodule at the backport proposal point here?

**Comment by tylerjereddy** [comment]
(I can obviously imagine brute force ways of doing this by carefully copying source around, but less clear on super-convenient ways to do it)

**Comment by mdhaber** [comment]
: / I haven't done a release so I really don't know what it entails. If it can't easily be backported, then "no" is ok : )

**Comment by rgommers** [comment]
@tylerjereddy it's a 2 line long patch that fixes a segfault, so I think backporting is a good idea. I suggest just applying the diff from https://github.com/scipy/HiGHS/pull/56/files manually.

**Comment by tylerjereddy** [comment]
@rgommers Hmm, none of these pick anything up on the backport branch, where HiGHS is vendored and not yet a submodule:

- `find . -name "HighsTaskExecutor.cpp"`
- `find . -name "HighsTaskExecutor.h"`
- `git grep -E -i "threadLocalWorkerDeque"`

Perhaps the conclusion here is that this parallel machinery is not present in the `1.8.x` series anyway, so perhaps no reason to worry?

**Comment by tylerjereddy** [comment]
To further solidify my observation, the PR to make HiGHS a submodule ( https://github.com/scipy/scipy/pull/15217 ) is obviously not present in the maintenance branch for the `1.8.x` series, and Ralf indicates that the segfault was not observed before that bump here: https://github.com/scipy/scipy/issues/15456#issue-1111572030

So, I'm stripping the backport label--there's nothing actionable here for release manager AFAICT.

**Comment by rgommers** [comment]
Thanks for investigating @tylerjereddy!

**Pull request merged**
