### PR TITLE
CI/BLD: update macos version [wheel build][skip cirrus]

### LINKED ISSUE #20523: CI/BLD: Nightly wheel builds failing for macOS x86_64
The nightly x86_64 macOS wheel build failed for the past few days because the deprecated macOS 11 runner does not have Clang 14 (gh-20478). This is fixed by gh-20510, but I could also create a separate PR to bump the requested OS version.

Also, I noticed that [the newest aarch64 Linux wheels](https://anaconda.org/scientific-python-nightly-wheels/scipy/files) are from 5 days ago. The Cirrus jobs responsible for building them failed on gh-20510, so the nightlies might also be failing.

### PR DESCRIPTION
**Pull request by andyfaff**
closes #20523

### CODE REVIEW

**Comment by rgommers** [comment]
I just noticed this as well. The easier fix is to just undo the too-aggressive bump on the lower bound, which is a good idea anyway because Homebrew or users on older macOS releases may run into the same thing.

You may want to make this change of runner image also, but it's not necessary.

**Comment by h-vetinari** [comment]
> The easier fix is to just undo the too-aggressive bump on the lower bound, which is a good idea anyway because Homebrew or users on older macOS releases may run into the same thing.

I don't mind undoing the bump, but I'm not really excited about pretending to support something lower than the lowest version we run in CI. That's the _effective_ lower bound (anything else will bitrot and break eventually), though I guess we could just show a warning of "you're on your own" if the version is below that.

**Comment by andyfaff** [comment]
I think @thalassemia PR is going to work better.

**Comment by rgommers** [comment]
> That's the _effective_ lower bound (anything else will bitrot and break eventually)

We don't have any evidence of that AFAIK, I can't remember a single bug report. We really don't require that much from compilers. Clang 12 is less than 3 years old, and should support C++17 well enough.

**Comment by lucascolley** [comment]
superseded by gh-20526

**Pull request closed without merging**
