### PR TITLE
ENH:stats: Add _isf method to pareto

### PR DESCRIPTION
**Pull request by OmarManzoor**
#### Reference issue

Towards: gh-17832

#### What does this implement/fix?

- Adds the _isf method to the Pareto distribution in order to improve its precision
- Adds a reference distribution
- Adds tests to verify the _isf method

### CODE REVIEW

**Comment by OmarManzoor** [comment]
Figure_1

<Details>

```python
from scipy.stats import pareto
import numpy as np
import matplotlib.pyplot as plt

def _isf(q, b):
    return np.power(q, -1.0/b)


def plot_isf():
    b = 2.62
    q = np.logspace(-40, -1, 200)
    plt.semilogx(q, pareto.isf(q, b), label="main", ls="dashed")
    plt.semilogx(q, _isf(q, b), label="pr", ls="dashdot")
    plt.legend()
    plt.title("pareto inverse survival function")
    plt.show()
```

</Details>

**Comment by mdhaber** [comment]
@OmarManzoor let's old off on adding `ReferenceDistribution`s and tests on these `isf` PRs that extend the useable domain to small values of the argument. I'll add a generic test that checks `isf`/`sf` roundtrip for extreme arguments so that there is not all this to write and review. Then you can just add the methods itself and produce the nice plot. I'll check the formation and merge if it looks good.

**Comment by OmarManzoor** [comment]
> @OmarManzoor let's old off on adding `ReferenceDistribution`s and tests on these `isf` PRs that extend the useable domain to small values of the argument. We don't really need `mpmath` to verify these. I'll add a generic test that checks `isf`/`sf` roundtrip for extreme arguments so that there is not all this to write and review. Then you can just add the methods itself and produce the nice plot. I'll check the formation and merge if it looks good.

Could you kindly provide an example of the kind of arguments to verify? Also we would still need some kind of reference to verify the value. Where would we get that from?

**Comment by mdhaber** [comment]
Shape parameters will be from `distr_params.py`. Probability masses (the primary argument to `isf`) will be logarithmically distributed like `np.logspace(-300, 0)` or so. I'll just test that `isf` is the inverse of `sf` even at the extremely small probabilities.

**Comment by dschmitz89** [comment]
One note about tests: we should also test the right tails of `_isf`. In #18002 , we observed that better accuracy close to zero does not necessarily mean that the accuracy close to 1 is preserved.

**Comment by mdhaber** [comment]
Yeah I thought about adding that. Will do.

**Comment by OmarManzoor** [comment]
> Shape parameters will be from `distr_params.py`. Probability masses (the primary argument to `isf`) will be logarithmically distributed like `np.logspace(-300, 0)` or so. I'll just test that `isf` is the inverse of `sf` even at the extremely small probabilities. There is almost certainly a generic test for this already; if so, I'll just extend the range for the distributions that have overriden `isf` and `sf`.
> 
> _Update: there is:_
> 
> https://github.com/scipy/scipy/blob/cfe80116aaa145061246b8aec0e98248fbefb835/scipy/stats/tests/test_continuous_basic.py#L585
> 
> I encourage you to continue doing whatever tests locally that convince you that the formulation is good. It's just that this is a lot to review, so I need to come up with even more efficient methods to keep up with it. If I only have to review one line for each instead of 10, that will be very helpful.

Thank you for the clarification.

**Comment by OmarManzoor** [comment]
@mdhaber I merged your PR related to the refined tests and remove the reference distribution.

**Review by mdhaber — APPROVED** [review]

**Pull request merged**
