### PR TITLE
larsmans refactor linearoperator

### PR DESCRIPTION
**Pull request by argriffing**
forked from @larsmans's https://github.com/scipy/scipy/pull/4087 then rebased and modified to pass unit tests, then benchmarked in an ad-hoc way.

### CODE REVIEW

**Comment by argriffing** [comment]
In the most recent PR I've tried to implement my interpretation of @pv's suggestion in https://github.com/scipy/scipy/pull/4087/files#r22310915 but it is causing errors and failures on TravisCI.  I do not have a solid understanding of the issues involved in this PR.

**Comment by argriffing** [comment]
@larsmans if you have any suggestions to address @pv's concerns in your original PR thread, this would be welcome!  I basically have no idea about the issues involved and I'm blindly transcribing the suggestions into this PR, and I'm almost tempted to close this PR and re-open your original PR.

**Comment by argriffing** [comment]
OK I think I've fixed the remaining two failing tests after having incorporated the suggested changes.

One test had failed because it was explicitly looking for an 'unspecified dtype'.  After having made the suggested changes, more effort is taken to precalculate the dtypes, so the dtype is no longer unspecified; I've changed this test to no longer expect 'unspecified type'.

The other had failed because I believe it was being passed a `matvec` function which was buggy, and because it had not been executed before the having implemented the suggested changes, its bugginess had not caused the tests to fail.  The buggy function was `matvec = partial(np.ones, 4)` which attempts to return something like `np.ones(4, x)` when `matvec(x)` is called.  I am guessing that the intention was to return a vector of ones regardless of the input, so I replaced `partial(np.ones, 4)` with a function that does this, and now this test passes.

**Comment by argriffing** [comment]
I might merge this in a few days if there are no comments -- I'm admittedly impatient to merge the open PRs related to abstract linear operators.

**Comment by larsmans** [comment]
W00t!

**Comment by argriffing** [comment]
> W00t!

Do you have any ideas about https://github.com/scipy/scipy/pull/4294?  I'd made that PR with the idea that it could be merged after only trivial modifications vs. the original PR (rebasing it and adding a unit test), but it has grown out of hand.

**Comment by argriffing** [comment]
The linear operator interface seems to be adding some overhead.  Here's an amusing cpu usage treemap with `dot` surrounded by its layers of management.
linear-operator-treemap

**Comment by larsmans** [comment]
How big are the arrays? We can specialize the relevant methods in the array wrapper.

**Comment by argriffing** [comment]
> How big are the arrays? We can specialize the relevant methods in the array wrapper.

In this example I think I used the matrix-power operator with dense square matrices of order 3, 10, and 30.  So the linear operators are relatively small.  Presumably for larger matrices this overhead would not be so important, although I guess it uses BLAS level 2 instead of level 3.

@larsmans This is not a big problem, but it's a slight performance regression from the earlier implementation.  The underlying issue is that the paper I used as reference for the one-norm estimation had less-comprehensive tests for complex matrices than for real matrices, so this was (and is) under-tested.  Your work on the linear operator framework changed a transpose to a conjugate transpose, probably correctly, but the conjugate transpose matrix multiplication function is not provided explicitly for the relevant operators whereas the transpose matrix multiplication function had been provided.  I guess this is what you mean by specializing the relevant methods in the array wrapper -- I think that adding the property `.H` for the matrix-power-matrix-product operator could be enough.

To address the underlying issue of norm estimation of complex matrices, I'm playing around with pseudospectrum applications which have been used as tests in the literature.  Testing is a little bit complicated because this norm estimation is probabilistic (it uses random number generation), although of course this generation can be specified using a random number seed, but it makes comparisons across implementations less straightforward.  Also for this algorithm it feels like it's easy to make errors in the implementation that would only be revealed for matrices with certain less-obvious properties, although this is just my intuition.

**Pull request merged**
