### PR TITLE
DOC/MAINT: clean doctests namespace

### LINKED ISSUE #16759: DOC: Add 'import numpy as np' to the 'Examples' section of docstrings.
It was recently decided that we would add the explicit import of numpy in the 'Examples' section of our docstrings. (See the discussion in https://github.com/scipy/scipy/issues/13049.)  Some progress has been made towards doing this consistently throughout SciPy, but there are still many functions and methods that need to be updated.

I created a script called `find_missing_import_np.py` that finds functions and methods that are missing the import.  Previously stored in a gist, the script is now in my github repo [`analyze-scipy-code`](https://github.com/WarrenWeckesser/analyze-scipy-code).

Here is the output when I run it with the SciPy main development branch (6-November-2022):
```
scipy version 1.10.0.dev0+2152.55452d1


Found 0 objects missing 'import numpy as np'
```
:tada:

### PR DESCRIPTION
**Pull request by tupui**
Closes #16759

Since #17349, all examples should be exempts of implicit NumPy imports. I tested this locally and if there are leftover example without explicit import, the ref guide check will fail.

This PR removes the import in the doctests logic and do some other cleanup I noticed while on this.

### CODE REVIEW

**Comment by ev-br** [comment]
Doctest namespace change LGTM, the rest looks reasonable for a non-expert reviewer.

**Comment by tupui** [comment]
I will fix the missing imports here.

**Comment by tupui** [comment]
Youhou CI is green. @ev-br @WarrenWeckesser this is ready.

**Review by WarrenWeckesser — APPROVED** [review]
Looks good, thanks @tupui.  I expected the script to find the missing imports wasn't checking all the docstrings, but I didn't think it missed so many!

**Pull request merged**
