### PR TITLE
DOC: Change `nb` and `na` to conventional m and n

### PR DESCRIPTION
**Pull request by endolith**
Also point out that zero-based indexing means that the last coefficient is m-1, not m.

or could be changed to TeX?

$$
H(\omega) = \frac
{b_0 (j\omega)^{(m-1)} + b_1 (j\omega)^{(m-2)} + \cdots + b_{(m-1)}}
{a_0 (j\omega)^{(n-1)} + a_1 (j\omega)^{(n-2)} + \cdots + a_{(n-1)}}
$$

### CODE REVIEW

**Comment by endolith** [comment]
Ok I rebased this and I found problems and am making more changes to it, so I'm going to take notes here as I go along so it's easier for others to check it.  Summary:

- zero-based indexing
- `b` is the TF numerator / feedforward coefficients
- `a` is the TF denominator / feedback coefficients
- `M` is the number of zeros, or the order of the numerator
- `N` is the number of poles, or the order of the denominator
- there are `M+1` `b` coefficients, the last of which is `a[M]`
- there are `N+1` `a` coefficients, the last of which is `b[N]`
- in SciPy's implementation, difference equations have minus signs before the `a` coefficients, and therefore transfer function has plus signs before them

So first formula is in 

`lfilter`:

       a[0]*y[n] = b[0]*x[n] + b[1]*x[n-1] + ... + b[nb]*x[n-nb]
                               - a[1]*y[n-1] - ... - a[na]*y[n-na]

This is copied from Matlab's [filter](http://www.mathworks.com/help/matlab/ref/filter.html#moreabout), except for 0-indexing, and the implementation is the same.  Instead of n_b and n_a, I'm changing to N and M:

       a[0]*y[n] = b[0]*x[n] + b[1]*x[n-1] + ... + b[M]*x[n-M]
                             - a[1]*y[n-1] - ... - a[N]*y[n-N]

http://www.cs.man.ac.uk/~barry/mydocs/COMP30291/Notes/DMP09-5.doc is the same except they swap a and b.

eq 8.2 in http://www.eas.uccs.edu/wickert/ece2610/lecture_notes/ece2610_chap8.pdf is equivalent except the `a` terms are negated.

same as section 4.3.2 in [google books](https://books.google.com/books?id=LyZyzdiJS9sC&lpg=PA70&ots=q9ldo-BwP2&dq=digital%20filter%20transfer%20function%20M%20N%20z&pg=PA70#v=onepage&q=digital%20filter%20transfer%20function%20M%20N%20z&f=false) except they swap M and N.


Then it has the transfer function:

                             -1               -nb
                 b[0] + b[1]z  + ... + b[nb] z
         Y(z) = ---------------------------------- X(z)
                             -1               -na
                 a[0] + a[1]z  + ... + a[na] z

Also the same as Matlab except 0-indexing.  I'm changing nb and na to M and N:

                             -1              -M
                 b[0] + b[1]z  + ... + b[M] z
         Y(z) = -------------------------------- X(z)
                             -1              -N
                 a[0] + a[1]z  + ... + a[N] z

same notation as eq 8.8 in http://www.eas.uccs.edu/wickert/ece2610/lecture_notes/ece2610_chap8.pdf except the `a` terms are negated.

same as section 4.3.2 in [google books](https://books.google.com/books?id=LyZyzdiJS9sC&lpg=PA70&ots=q9ldo-BwP2&dq=digital%20filter%20transfer%20function%20M%20N%20z&pg=PA70#v=onepage&q=digital%20filter%20transfer%20function%20M%20N%20z&f=false) except they swap M and N.

**Comment by endolith** [comment]
`residue` and `invres`:
Originally used M = len(b) and N = len(a):

              b(s)     b[0] s**(M-1) + b[1] s**(M-2) + ... + b[M-1]
      H(s) = ------ = ----------------------------------------------
              a(s)     a[0] s**(N-1) + a[1] s**(N-2) + ... + a[N-1]

Changed to M, N = order of polynomials:

              b(s)     b[0] s**(M) + b[1] s**(M-1) + ... + b[M]
      H(s) = ------ = ------------------------------------------
              a(s)     a[0] s**(N) + a[1] s**(N-1) + ... + a[N]

Simplifies formula and is now consistent with other docstrings and also Matlab's [residue](http://www.mathworks.com/help/matlab/ref/residue.html) (other than 1-indexing)

`invres` had x instead of s, made them consistent with each other.



`residuez` and `invresz`:

Originally:

                b(z)     b[0] + b[1] z**(-1) + ... + b[M-1] z**(-M+1)
        H(z) = ------ = ----------------------------------------------
                a(z)     a[0] + a[1] z**(-1) + ... + a[N-1] z**(-N+1)

Changed to:

                b(z)     b[0] + b[1] z**(-1) + ... + b[M] z**(-M)
        H(z) = ------ = ------------------------------------------
                a(z)     a[0] + a[1] z**(-1) + ... + a[N] z**(-N)

Changed to order of num,den instead of number of coefficients

**Comment by endolith** [comment]
Also was going to add some examples for the residue functions, but now I see there are no unit tests for them...  So I think that should be another PR.

**Comment by endolith** [comment]
Should I change the word "order" to "degree"?  http://mathworld.wolfram.com/PolynomialOrder.html  http://en.wikipedia.org/wiki/Order_of_a_polynomial

**Comment by rgommers** [comment]
not sure - for polynomials "degree" is better, but "order" seems to be used specifically for filter design. I don't work with these filters enough to have a clear expectation.

**Comment by endolith** [comment]
I changed them to "degree".

I'm confused by lfilter's use of `n` for both sample number and model order, and use of `m` for sample number, too.

**Comment by endolith** [comment]
I updated the state variable version of the difference equations, which was originally just copied from matlab.  

- changed to sample number `n` for consistency with other difference equation
- I moved state variables last, same as http://cnx.org/contents/ef583915-43cb-4189-be10-f0d776088304@1/Filter_Selection_and_Construct
- a0 is allowed to be not 1, but the difference equation (and matlab's diagram) assume it is 1, so I added it back in.
- changed state variable names to d to keep from confusion with z⁻¹ .  There's no consistent name for these elsewhere: d, s, w, x, etc.
- Matlab's isn't really correct when N>M, either, so I just made the assumption they are equal, which is common, for simplicity.
- total number of coefficients was wrong, if N is the degree of the numerator, then there are N+1 coefficients, numbered from b0 to bN.

**Comment by rgommers** [comment]
I'm leaving this on the 0.16.0 milestone, so I'll make sure to have a look at it before that release - this has been open for too long already.

**Comment by endolith** [comment]
Can this be reviewed please?  :)  It's almost 2 years old now

**Comment by e-q** [comment]
From my first read through of the discussion and changes, this all looks good with one minor language quibble of mine: I think "degree of the denominator" sounds a little weird, I would prefer something like "Degree of the denominator polynomial."

Caveat: I haven't looked for other docstrings that may also need adjustment, which may have cropped up given the time since the last commit...

**Comment by endolith** [comment]
>  I think "degree of the denominator" sounds a little weird

looks like this is the normal way to say it:

https://www.google.com/search?q=%22degree+of+the+denominator%22

**Comment by e-q** [comment]
Squashed and merged in 4ffc02a and a71ab83, thanks @endolith!

**Pull request closed without merging**
