### PR TITLE
MAINT: (more) backports for SciPy 1.7.0

### PR DESCRIPTION
**Pull request by tylerjereddy**
Backport gh-14171, gh-14175, and update the release notes accordingly.

These backports are aimed at fixing issues that cropped up in the wheels repo CI, and went undetected in the main repo CI.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
@WarrenWeckesser @mdhaber hmm, another surprise from `stats` in the doc build?

```python
/home/circleci/repo/build/testenv/lib/python3.7/site-packages/scipy/stats/morestats.py:docstring of scipy.stats.morestats.ppcc_plot:71: WARNING: Exception occurred in plotting scipy-stats-ppcc_plot-1
 from /home/circleci/repo/doc/source/reference/generated/scipy.stats.ppcc_plot.rst:
Traceback (most recent call last):
  File "/home/circleci/repo/venv/lib/python3.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 483, in run_code
    exec(code, ns)
  File "<string>", line 20, in <module>
  File "/home/circleci/repo/build/testenv/lib/python3.7/site-packages/scipy/stats/morestats.py", line 1349, in boxcox_normplot
    return _normplot('boxcox', x, la, lb, plot, N)
  File "/home/circleci/repo/build/testenv/lib/python3.7/site-packages/scipy/stats/morestats.py", line 1271, in _normplot
    z = transform_func(x, lmbda=val)
  File "/home/circleci/repo/build/testenv/lib/python3.7/site-packages/scipy/stats/morestats.py", line 1061, in boxcox
    raise ValueError("Data must be positive.")
ValueError: Data must be positive.
```

**Comment by WarrenWeckesser** [comment]
@tylerjereddy, I see what is happening.  In the [`stats.ppcc_plot`](http://scipy.github.io/devdocs/reference/generated/scipy.stats.ppcc_plot.html#scipy.stats.ppcc_plot) example, an array `x` is a random sample from the `tukeylambda` distribution, with parameter `lam = -0.7`.  When `lam` is negative, the support of the distribution is the entire real line, but in this example, it appears that it was not expected that `x` would have any negative values.  It turns out that `x` *can*  end up with negative values, e.g.:

```
In [295]: rng = np.random.default_rng(12)                                                                                                      

In [296]: x = stats.tukeylambda.rvs(-0.7, loc=2, scale=0.5, 
     ...:                           size=10000, random_state=rng) + 1e4                                                                        

In [297]: x.min()                                                                                                                              
Out[297]: -757.1319779987971
```
That will cause an error in the call to `boxcox_normplot()`, because that function requires that all the values in the input array be positive.

A simple fix is to add a seed to `default_rng()` that results in `x` containing only positive values.  I'll create a PR.

**Comment by tylerjereddy** [comment]
Updated with backport of gh-14182, and release notes updated accordingly, fingers crossed.

**Comment by tylerjereddy** [comment]
I had to restart github actions because of a timeout, but finally we have CI all green here.

**Pull request merged**
