### PR TITLE
ENH: producing warning , issue #7332

### PR DESCRIPTION
**Pull request by ashwinpathak20**
This is in reference to issue #7332

### CODE REVIEW

**Comment by pv** [comment]
This is the wrong place to fix it --- it should be fixed in the "hybr"
method, with no code additions in "def root".

**Comment by pv** [comment]
You are also hardcoding some tolerances --- instead, such checks should use tolerances passed to the method.

It is also not clear that emitting a warning is the right fix. Rather, the error must be somewhere in the original algorithm, which you can find under `scipy/optimize/minpack/hybrd.f`. Either it should be fixed, or if that is not possible, the algorithm should be made to terminate with error if it detects this condition.

**Comment by ashwinpathak20** [comment]
Ok, I will change it in 'hybr'

but what about the tolerance? I mean numerical differentiation will not give an exact 0 and would produce 0 (+/- some tolerence) what should I take this tolerence to be? Should I take it as an input?

And for termination, should I raise an error or emit warning?

**Comment by pv** [comment]
I think the proper fix requires understanding why the hybr algorithm
terminates apparently at the first step.
.
The question about tolerances in root finding are not necessarily
simple, because you want to make the algorithm be able to find roots to
functions `f(x)`, `1e-16*f(x)`, and `1e16*f(x)` without having to adjust
the tolerance precisely.

**Comment by ashwinpathak20** [comment]
While I am trying to understand completely the functioning of hybr.f , this seems to be a alternative as I have included the check : whether initial guess is the root of the derivative, if yes, an exception is raised.

**Comment by rgommers** [comment]
@ashwinpathak20 I suggest we close this PR, because as @pv says this is not the desired fix. And I suspect you don't want to dig into the Fortran code in ``hybr.f``.

**Pull request closed without merging**
