### PR TITLE
MAINT:TST:linalg modernize the test assertions

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
#14188 

#### What does this implement/fix?
Converted `assert_(np.allclose(...))` type assertions to the `assert_allclose(...)` with proper tol replacements. 

#### Additional information

@tylerjereddy do you mind running this PR locally? With 0.3.15 I don't get any errors on my machine.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Changes certainly look sensible to me. I've cherry-picked the changes here into the [PR on my fork](https://github.com/tylerjereddy/scipy/pull/57) where I saw the 32-bit Windows Azure linalg test issue with OpenBLAS `0.3.13`.

Even if this doesn't fix that though, it is almost certainly an improvement & would tell us how far off the precision is there.

**Comment by tylerjereddy** [comment]
32-bit Windows with OpenBLAS `0.3.13` still has a problem, but at least we can see how bad it is now: https://dev.azure.com/tylerjereddy/b7b8353e-eff5-4f0d-b725-2dbd0728d298/_apis/build/builds/1185/logs/195

So, we may just want to merge this and deal with that issue separately.

**Comment by ilayn** [comment]
Ah ok, I thought we would adjust the tolerances in this PR if it was a tiny bit of nudge. But yes, it seems like we have a different problem. I'm fine with any decision here. So please feel free to choose.

**Comment by tylerjereddy** [comment]
Ok, I did one more pass through and the changes all look like helpful modernizations that will give better tracebacks on precision issues.

Indeed, let's delay the rather large precision issue with OpenBLAS version bumping--that has been blocking us for a while, but could get messy to try to resolve in this PR.

**Comment by tylerjereddy** [comment]
thanks @ilayn

**Pull request merged**
