### PR TITLE
MAINT: Fix doc build bugs

### LINKED ISSUE #10384: CircleCI doc build failing on new warnings
89 warnings visible in gh-10378, perhaps due to a change in one of our doc build dependencies.

```
WARNING: duplicate object description of scipy.io.wavfile, other instance in io, use :noindex: for one of them
WARNING: duplicate object description of scipy.io.arff, other instance in io, use :noindex: for one of them
WARNING: duplicate object description of scipy.io, other instance in io, use :noindex: for one of them
checking consistency... /home/circleci/repo/doc/source/generated/scipy.LowLevelCallable.function.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.LowLevelCallable.signature.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.LowLevelCallable.user_data.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.BDF.step_size.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.LSODA.step_size.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.OdeSolver.step_size.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.RK23.step_size.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.RK45.step_size.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.Radau.step_size.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.complex_ode.y.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.integrate.ode.y.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.interpolate.BSpline.tck.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.interpolate.Rbf.A.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.interpolate.interp1d.fill_value.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.io.netcdf_variable.isrec.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.io.netcdf_variable.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.optimize.LbfgsInvHessProduct.H.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.optimize.LbfgsInvHessProduct.T.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.A.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.B.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.C.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.D.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.dt.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.poles.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.StateSpace.zeros.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.TransferFunction.den.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.TransferFunction.dt.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.TransferFunction.num.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.TransferFunction.poles.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.TransferFunction.zeros.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.ZerosPolesGain.dt.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.ZerosPolesGain.gain.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.ZerosPolesGain.poles.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.ZerosPolesGain.zeros.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.dlti.dt.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.dlti.poles.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.dlti.zeros.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.lti.dt.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.lti.poles.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.signal.lti.zeros.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.bsr_matrix.blocksize.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.bsr_matrix.dtype.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.bsr_matrix.has_canonical_format.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.bsr_matrix.has_sorted_indices.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.bsr_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.bsr_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.coo_matrix.dtype.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.coo_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.coo_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csc_matrix.dtype.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csc_matrix.has_canonical_format.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csc_matrix.has_sorted_indices.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csc_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csc_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csr_matrix.dtype.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csr_matrix.has_canonical_format.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csr_matrix.has_sorted_indices.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csr_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.csr_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.dia_matrix.dtype.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.dia_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.dia_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.dok_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.dok_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.lil_matrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.lil_matrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.linalg.LinearOperator.H.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.linalg.LinearOperator.T.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.spmatrix.nnz.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.sparse.spmatrix.shape.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.ConvexHull.points.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.ConvexHull.vertices.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Delaunay.convex_hull.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Delaunay.points.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Delaunay.transform.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Delaunay.vertex_neighbor_vertices.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Delaunay.vertex_to_simplex.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.HalfspaceIntersection.dual_vertices.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.HalfspaceIntersection.halfspaces.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Voronoi.points.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.spatial.Voronoi.ridge_dict.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.stats.gaussian_kde.neff.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.stats.gaussian_kde.weights.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.stats.rv_continuous.random_state.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.stats.rv_discrete.random_state.rst: WARNING: document isn't included in any toctree
/home/circleci/repo/doc/source/generated/scipy.stats.rv_histogram.random_state.rst: WARNING: document isn't included in any toctree
done
```

### PR DESCRIPTION
**Pull request by larsoner**
Todo:

- [x] Fix build warnings
- [x] Unpin Sphinx on CircleCI (works locally with `mastner` at least, let's see if CircleCI agrees)
- [x] Update `numpydoc` to 0.9.1

Closes #10384

### CODE REVIEW

**Comment by larsoner** [comment]
CircleCI appears to be happy, ready for review/merge from my end.

**Review by rgommers — APPROVED** [review]

**Comment by rgommers** [comment]
Merged, thanks @larsoner!

**Comment by tylerjereddy** [comment]
Pretty sure this needs a backport candidate label--I dug through commit history to find doc-related fixes for issues I'm seeing in #10496, and the number of warnings described in the cognate issue here (89) exactly matches the number observed in the circle CI fail in the backport PR.

**Comment by larsoner** [comment]
@tylerjereddy yes that's likely

**Pull request merged**
