### PR TITLE
DOC/BLD: macOS Homebrew OpenBlas detection advice

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
https://github.com/scipy/scipy/issues/19784#issuecomment-1873343063

#### What does this implement/fix?
Advises on a potential fix for OpenBlas detection on macOS with Homebrew.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, thanks @lucascolley

**Comment by rgommers** [comment]
For next time: consider adding `[skip actions]` in the commit message of a docs-only PR. The only relevant CI jobs are on CircleCI.

**Comment by lucascolley** [comment]
> For next time: consider adding [skip actions] in the commit message of a docs-only PR.

I added `[docs only]` which only ran the CircleCI jobs and the linter - the only GHAs that ran were the jobs to check the commit message :)

**Comment by rgommers** [comment]
Ah wait, that changed - there are more green checkmarks, but they're very short jobs indeed. Sorry for the noise!

**Pull request merged**
