### PR TITLE
BUG: prevent error accumulation in `Rotation` multiplication

### LINKED ISSUE #12314: scipy.spatial.transform.Rotation multiplication does not normalize quaternion
Not sure if this is considered a "bug" or not, but when rotations are multiplied in scipy.spatial.transform.Rotation, the resulting quaternion is not normalized.  This can eventually lead to numerical precision errors (e.g. a quaternion that is all NaNs or all zeros), in relatively few rotation iterations (in this example fewer than 100).

#### Reproducing code example:

```import numpy as np
from scipy.spatial.transform import Rotation

trialEulerAngles = np.array(
    [
        np.linspace(0,np.pi/6,100),
        np.linspace(0,np.pi/5,100),
        np.linspace(0,-np.pi/8,100)
    ]
).T
r1 = Rotation.from_euler('xyz',[0,0,0])

for eulerAngle in trialEulerAngles:
    r2 = Rotation.from_euler('xyz',eulerAngle)
    dr = r2 * r1.inv()
    r1=dr*r1

print(r1.as_quat()) # Results in [nan nan nan nan]
```

#### Error message:

```
Traceback (most recent call last):
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\spatial\transform\rotation.py:154: RuntimeWarning: overflow encountered in multiply
  product[:, 3] = p[:, 3] * q[:, 3] - np.sum(p[:, :3] * q[:, :3], axis=1)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\spatial\transform\rotation.py:154: RuntimeWarning: invalid value encountered in subtract
  product[:, 3] = p[:, 3] * q[:, 3] - np.sum(p[:, :3] * q[:, :3], axis=1)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\spatial\transform\rotation.py:155: RuntimeWarning: overflow encountered in multiply
  product[:, :3] = (p[:, None, 3] * q[:, :3] + q[:, None, 3] * p[:, :3] +
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1876: RuntimeWarning: overflow encountered in multiply
  multiply(a1, b2, out=cp0)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1877: RuntimeWarning: overflow encountered in multiply
  tmp = array(a2 * b1)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1878: RuntimeWarning: invalid value encountered in subtract
  cp0 -= tmp
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1879: RuntimeWarning: overflow encountered in multiply
  multiply(a2, b0, out=cp1)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1880: RuntimeWarning: overflow encountered in multiply
  multiply(a0, b2, out=tmp)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1881: RuntimeWarning: invalid value encountered in subtract
  cp1 -= tmp
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1882: RuntimeWarning: overflow encountered in multiply
  multiply(a0, b1, out=cp2)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1883: RuntimeWarning: overflow encountered in multiply
  multiply(a1, b0, out=tmp)
C:\Users\jrunnels\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\core\numeric.py:1884: RuntimeWarning: invalid value encountered in subtract
  cp2 -= tmp
```

#### Scipy/Numpy/Python version information:
1.3.1 1.16.5 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by pmla**
#### Reference issue

Closes #12314

#### What does this implement/fix?

After multiplication, the quaternions used in the internal representation of the `Rotation` class are normalized. This prevents error accumulation in the quaternion norms.

#### Additional information

Normalization incurs a small performance penalty, but I think this is a good trade-off considering that the `Rotation` class can otherwise mysteriously turn into NaNs.

Perhaps a backport candidate?

### CODE REVIEW

**Comment by pmla** [comment]
This PR is straightforward but I would like someone to sign off on it
@nmayorov @tylerjereddy

**Review by tylerjereddy — APPROVED** [review]
Ok, I checked locally that the test case in the issue no longer raises an exception with this feature branch as well, and that the unit test added in this PR fails in latest master branch.

Thanks @pmla.

**Comment by pmla** [comment]
Thanks Tyler.

**Comment by nmayorov** [comment]
@pmla 

> Normalization incurs a small performance penalty, but I think this is a good trade-off considering that the Rotation class can otherwise mysteriously turn into NaNs.

Have you encounter large accumulated errors of quaternions norms in practice? I've often heard that it's theoretically possible, but never saw it myself in practice even when there are millions of multiplications.

Could you prepare a small example where consecutive multiplications without normalization cause the norm to deviate from 1 significantly?

**Comment by pmla** [comment]
@nmayorov the test I added here blows up without normalization:
https://github.com/scipy/scipy/blob/master/scipy/spatial/transform/tests/test_rotation.py#L1129

**Comment by nmayorov** [comment]
I see, great change then! 

I also tested multiplication matrices - determinant property is violated after some time in a similar manner.

I guess I had a misconception about stability of quaternion/rotation matrix multiplications.

**Comment by nmayorov** [comment]
I noticed one thing - the problem is pronounced when you multiply rotation with itself.

In your loop if we remove `* rs` then the computations are stable. I'm sure you knew that too.

So if we don't do such "rotation powers", we won't see strong instability (that's why I haven't seen them). But as performance penalty is small (I've estimated it as <5%) I think normalization is a good straightforward strategy.

**Pull request merged**
