### PR TITLE
use int, float, bool instead of np.int, np.float, np.bool

### PR DESCRIPTION
**Pull request by argriffing**
This is just some ~~wiki~~ github gnome activity. See https://github.com/numpy/numpy/pull/6103.

``` shell
$ find . -name "*.py" -print0 | xargs -0 sed -i "s/\bnp.int\b/int/g"
$ find . -name "*.py" -print0 | xargs -0 sed -i "s/\bnp.float\b/float/g"
$ find . -name "*.py" -print0 | xargs -0 sed -i "s/\bnp.bool\b/bool/g"
```

### CODE REVIEW

**Comment by rgommers** [comment]
LGTM

**Comment by argriffing** [comment]
This now includes all of the types in the numpy PR: bool, int, float, complex, object, str, unicode.

**Comment by ev-br** [comment]
Good to know that dtype=int does the right thing on python 3 too.

**Comment by larsmans** [comment]
Merged. Added a rationale to the merge commit message since there wasn't any in the patches' messages.

**Pull request merged**
