### PR TITLE
ENH: rewrite of stats.ppcc_plot

### PR DESCRIPTION
**Pull request by rgommers**
Closes Statistics Review issue gh-679. 

Also some minor fixes to `stats.probplot` and `stats.tukeylambda` are included.

### CODE REVIEW

**Comment by rgommers** [comment]
This PR should be pretty straightforward, any takers for a review?

**Comment by WarrenWeckesser** [comment]
I haven't reviewed the `ppcc_plot` changes, but I noticed that the tukeylambda PPF function could be simplified to `boxcox(q, lam) - boxcox1p(-q, lam)`, where `boxcox` and `boxcox1p` are from `scipy.special`.  If you'd like, you can remove your change to `tukeylambda._ppf`, and I'll create a PR to make this change.

**Comment by josef-pkt** [comment]
Reading through the code: The changes look good to me, I don't see any problems and it improves the code.

I haven't paid any attention to what the empty array behavior is now in various functions.
I guess if there is only one point, or maybe a few, the plot and fit will break down. Is probplot defined for very small arrays?

**Comment by rgommers** [comment]
``probplot`` seems to work for any length input:

- length 0 is special cased
- length 1 gives a ``RuntimeWarning`` and returns ``((array([ 0.]), array([1])), (nan, nan, 0.0))``.
- length 2 and up return values and don't give any warning. There's not much point of course for a length-2 input, but it seems overkill to add warnings for specific input sized there (also not clear where you'd put the cutoff then).

Plots are all sensible as well, except a plot for length-1 which of course is just a single point in a figure.

For empty input ``ppcc_plot`` simple inherits the ``probplot`` behavior. At some point we may want to go through and review empty input handling for consistency between all stats functions, but that's not something I want to do now or in the near future.

**Comment by rgommers** [comment]
@WarrenWeckesser that sounds good. Although easier, why not merge this PR now (since Josef just reviewed it) and then you make your proposed change on top of it?

**Comment by WarrenWeckesser** [comment]
@rgommers: That's fine, too--less work for you, which is good. :)

**Comment by rgommers** [comment]
Great, thanks. Merging.

**Comment by WarrenWeckesser** [comment]
tukeylambda ppf change is here: https://github.com/scipy/scipy/pull/4692

**Pull request merged**
