### PR TITLE
MAINT: Allow F401 and F403 in module init files

### PR DESCRIPTION
**Pull request by ilayn**
The linter is complaining about [star imports](https://www.flake8rules.com/rules/F403.html) and [unused module imports](https://www.flake8rules.com/rules/F401.html) which we use in all init files. It didn't touch the existing ones but in #14701 it became visible. Since we use star imports very sparingly and track imports closely, we don't need this check.

### CODE REVIEW

**Comment by peterbell10** [comment]
>Since we use star imports very sparingly and track imports closely, we don't need this check.

Isn't that entirely consistent with enabling the linter check? They should only be used sparingly, so having to add a noqa comment isn't that big of a deal. Unused imports in particular is something that's hard to pick up on in review, so the linter is really helpful there.

**Comment by ilayn** [comment]
I don't see how. We are reviewing the PRs anyways so it is very unlikely that we can miss such imports. Here it is checking only new additions which has almost no use

**Comment by ilayn** [comment]
alternatively 

- we can go all the otherway and not use star imports at all. But even then we still need F401
- we exclude `__init__`s from pycodestyle

**Comment by ev-br** [comment]
+1 from me FWIW

**Comment by WarrenWeckesser** [comment]
> We are reviewing the PRs anyways so it is very unlikely that we can miss such imports.

Human reviewers miss these things.  A very common case is when some code is cleaned up resulting in an unused import. I agree with @peterbell10: leave the checks enabled, and use `noqa` explicitly in the `__init__` files.

**Comment by ilayn** [comment]
Reiterating the point, `#noqa` and other QA removals should be spared for edge cases. I can't see how tiling `#noqa`s applies here. I would prefer having the tool cooperate with us instead of we are hacking files to cooperate with it.

**Comment by ilayn** [comment]
Here is the said problematic area 

https://github.com/scipy/scipy/blob/master/scipy/linalg/__init__.py#L195-L217

**Comment by WarrenWeckesser** [comment]
But finding unused imports is *exactly* the kind of thing we want an automated checker for!  In general, we know that using `from module import *` is a bad practice, except in cases like `__init__.py`.  In other words, `__init__.py` *is* an edge case.

**Comment by ilayn** [comment]
OK would it be a viable option if we exclude init file then? Because the problem here is that linter is leaving the legacy code alone but only complaining about new code which is already forking the codebase into two maintenance regions. And 5 years from now 

```python
from Z import * #noqa
from X import * #noqa
from C  import *
from B  import *
from A import *  
```
would make very little sense to future maintainers. This is what I mean by hacking to comply with the tool

**Comment by larsoner** [comment]
+1 for @peterbell10 's solution of noqa. It allows us to incrementally make our code better going forward. I'm not too worried about the inconsistency.

**Comment by peterbell10** [comment]
If I'm reading the flake8 documentation right, I think we can disable these check for only `__init__.py`
https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores

(untested)
```
[flake8]
per-file-ignores=
  */__init__.py:F401,F403
```

**Comment by ilayn** [comment]
You beat me to it. Came here to propose the same

**Comment by ilayn** [comment]
Reading this again, looks like I was typing a bit too agitated which wasn't the intention. Any objections for exclusion of init files ?

**Review by larsoner — APPROVED** [review]

**Review by peterbell10 — APPROVED** [review]

**Comment by ilayn** [comment]
Fingers crossed let's see if this is going to work. Thanks all!

**Pull request merged**
