### PR TITLE
DOC: Fix signal docstrings; finish adding 'import numpy as np'

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
* Add the import of numpy in the 'Examples' where needed.
* Add missing 'Returns' section for some functions.
* Fix the section order in a few docstrings to comply with
  the NumPy docstring standard.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
The failure of CirleCI is not related; see https://github.com/scipy/scipy/issues/17350.

The lint failure is expected.  Some of the sections that were moved include lines that are unavoidably longer than 79 characters.

**Review by tupui — COMMENTED** [review]
LGTM, thanks @WarrenWeckesser.

Could you then remove the automatic import of NumPy in docstrings? This way we ensure it won't be allowed again and see if we missed anything.
We should also remove the mention at the beginning of the doc saying this import is implied.

**Comment by WarrenWeckesser** [comment]
> Could you then remove the automatic import of NumPy in docstrings? This way we ensure it won't be allowed again and see if we missed anything.

That's a great idea.  That can be done in a follow-up PR.

**Review by tupui — APPROVED** [review]
Alright then 👍 I can have a look on Monday if you did not do it by then.

**Pull request merged**
