### PR TITLE
WIP: fix an expm typo.

### PR DESCRIPTION
**Pull request by argriffing**
While looking into https://github.com/scipy/scipy/issues/4897 I found a typo where `2*m + 1` was used in place of `m`.  This is obscure for a couple reasons.  First, it appears in a formula that was less than completely derived in the original publication.  Second, it doesn't seem to have much of an effect on the expm calculation.  But I was able to add a regression test.

### CODE REVIEW

**Comment by argriffing** [comment]
This PR is entering 'work in progress' (WIP) mode as I try speeding up the expm calculation.

**Comment by ewmoore** [comment]
@argriffing, is it worth taking this fix?

**Comment by argriffing** [comment]
>  is it worth taking this fix?

Maybe. I see this PR has a unit test with tight tolerances that will probably fail on some systems. It was somewhat disturbing to me that this bug was not caught by existing tests, and I wasn't able to find a looser-tolerance example that exhibited the bug which was also a little disconcerting.

I think that expm in particular and the scipy 'abstract linear operator' code in general could benefit from focused effort that I can't justify spending in my current position, and IIRC there are related languishing open PRs by drive-by contributors. As Stephen Diehl says [here](http://www.stephendiehl.com/posts/haskell_2016.html) in his year-end reflection on Haskell, "progress in the numerical Python space was hard-won and usually built on the graves of academic careers of people who become community organizers around projects like NumPy and SciPy" so we probably need a new batch of naive grad students or post-docs for this linear operator overhaul.

By the way, here's a recent blog post on matrix-exponential-vector-product https://manchestersiam.wordpress.com/2016/01/15/on-the-leja-method/.

**Comment by rgommers** [comment]
> As Stephen Diehl says here in his year-end reflection on Haskell, "progress in the numerical Python space was hard-won and usually built on the graves of academic careers of people who become community organizers around projects like NumPy and SciPy"

or they become CEO's or go work for the Google's of this world next :)

**Comment by argriffing** [comment]
closing https://mail.scipy.org/pipermail/numpy-discussion/2016-January/074810.html

**Pull request closed without merging**
