### PR TITLE
DOC: Add examples to `scipy.interpolate.spalde`

### PR DESCRIPTION
**Pull request by mabatalla**
#### Reference issue
DOC: Add "Examples" to docstrings https://github.com/scipy/scipy/issues/7168 (partial)

#### What does this implement/fix?
Adds example for interpolate.spalde and unifies descriptions along the docstrings in the file.
Fixes previous attemps (#19434) to pass doc build and refgude-check.

[skip actions] [skip cirrus]

### CODE REVIEW

**Comment by mabatalla** [comment]
Friendly ping on this very little contribution, update of #19434

**Comment by ev-br** [comment]
OK, CI is green, the docs look good. Thank you @mabatalla !

**Comment by lucascolley** [comment]
thanks for your first contribution to SciPy!

**Comment by mabatalla** [comment]
Thank you all @ev-br @lucascolley @j-bowhay @astrojuanlu for your patience and advice. It's been a good learning, hope to be contributing more.

**Pull request merged**
