### PR TITLE
MAINT: Fix uninitialized warnings in `sparse/linalg/dsolve`

### PR DESCRIPTION
**Pull request by Smit-create**
#### Reference issue

* References: https://github.com/rgommers/scipy/issues/42

Fixing uninitialized warnings.

cc @rgommers

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Thanks @Smit-create! As we discussed, there's a file `scipychanges.patch` that would be good to update with the functional changes in this PR (not the whitespace changes). So that if SuperLU gets updated from its upstream version (which is at https://github.com/xiaoyeli/superlu), we can re-apply our changes.

Or the alternative is to submit another PR to upstream after review is done here.

Also, there is one warning in the Meson build that would be nice to take along:
```
[219/1311] Compiling C object scipy/sparse...9-x86_64-linux-gnu.so.p/_superluobject.c.o
../scipy/sparse/linalg/dsolve/_superluobject.c:209:32: warning: missing braces around initializer [-Wmissing-braces]
  209 | PyGetSetDef SuperLU_getset[] = {
      |                                ^
```
The fix is to change the last line of the initializer to:
```
    {NULL},
```

**Comment by Smit-create** [comment]
Does this look good now? @rgommers

**Review by ilayn — APPROVED** [review]

**Review by rgommers — APPROVED** [review]
LGTM now, thanks Smit!

**Comment by rgommers** [comment]
@Smit-create there are quite a few more issues with Clang in SuperLU:
```
[500/1308] Compiling C object scipy/sparse/linalg/dsolve/libsuperlu_lib.a.p/SuperLU_SRC_sreadhb.c.o
../scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c: In function ‘sReadValues’:
../scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c:167:2: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  167 |  fgets(buf, 100, fp);    /* read a line at a time */
      |  ^~~~~~~~~~~~~~~~~~~
../scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c: In function ‘sreadhb’:
../scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c:295:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
  295 |     fgets(buf, 100, fp);
      |     ^~~~~~~~~~~~~~~~~~~
../scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c:307:2: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  307 |  fscanf(fp, "%14c", buf); buf[14] = 0;
      |  ^~~~~~~~~~~~~~~~~~~~~~~
../scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c:315:5: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  315 |     fscanf(fp, "%3c", type);
```

See https://github.com/rgommers/scipy/runs/3209261122 for a full log. The warnings are valid, see https://stackoverflow.com/questions/34191613/warning-ignoring-return-value-of-fscanf-in-c. It would be nice to take care of those as well as a follow up.

**Comment by Smit-create** [comment]
Sure.

**Comment by czgdp1807** [comment]
@Smit-create There is no warning related to `fscanf` on my system. Please see the full logs [here](https://gist.github.com/czgdp1807/ca44a73c5663ff0247b2954d88432172).

cc @rgommers

**Comment by rgommers** [comment]
Looks like it's compiler-dependent. The CI log is for the Meson build with GCC 9.3.0 on Linux, yours is for Clang on macOS.

**Pull request merged**
