### PR TITLE
ENH: sparse: canonicalize on initialization

### PR DESCRIPTION
**Pull request by perimosocordiae**
Duplicates entries are still allowed in COO/CSR/CSC/BSR constructors, but are not handled anywhere else. See gh-5807 for the initial discussion.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
The Travis tests are all failing with `NameError: global name 'special' is not defined`. Seems unrelated to this PR, but I have no idea why it's happening.

**Comment by perimosocordiae** [comment]
Running the benchmark suite (`./run.py --current-repo continuous master sparse-no-duplicates`) results in no significant changes to performance.

That said, this PR does have the potential to slow down some user code quite substantially in cases where direct construction of CSR/CSC/COO/BSR sparse matrices is used (i.e., supplying data/index arrays directly). The performance will return to normal if `canonicalize=False` is passed, but I wouldn't rely on users to update their code pre-emptively.

This slowdown could be mitigated somewhat by adding a fast check for canonical form before sorting/summing duplicates in the constructor.

**Comment by person142** [comment]
Re

> The Travis tests are all failing with `NameError: global name 'special' is not defined`

I think the error is coming from https://github.com/scipy/scipy/pull/6294; hopefully this is fixed in https://github.com/scipy/scipy/pull/6632.

**Comment by perimosocordiae** [comment]
Yep, that fixed it. Thanks, @person142!

**Comment by tylerjereddy** [comment]
More than two years without a comment or flush through the CI & > 2 years with no discussion since the "needs-decision" label was added.

I'm bumping the milestone.

**Comment by tylerjereddy** [comment]
I'm bumping the milestone again on this one for the same reason as last time--roughly 2.5 years now without follow-up on the "needs decision" label & the the code diff is non-trivial.

**Comment by perimosocordiae** [comment]
Even ~3 years later, there's still no clear decision about how to deal with the problem of when to canonicalize sparse matrices. I'm pretty sure this PR isn't the right solution, though, so I'll close it now.

**Pull request closed without merging**
