### PR TITLE
CircleCI: Share data between jobs

### PR DESCRIPTION
**Pull request by stefanv**
See end of https://github.com/scipy/scipy/pull/8502 for discussion.  (Docker containers are used for jobs, so need special steps to share data between jobs.)

### CODE REVIEW

**Comment by stefanv** [comment]
@pv If you get a chance, can you take a look and see if you like this approach?

**Comment by pv** [comment]
Looks like it's trying to auth with the wrong key (ssh login succeeds both with checkout and deploy keys, and it uses the first one...). Previously, this was possible to fix by setting the hostname for the key in the circleci config panel, but apparently that doesn't work any more.

Probably something the following needs to be used, instead of modifying `.ssh/config`:
```
echo -e '#!/bin/sh\nunset SSH_AUTH_SOCK\nexec ssh -i ~/.ssh/id_rsa_eb75f0c2bf9fba96801e6b986f0b6063 -o StrictHostKeyChecking=no "$@"' > ~/git-ssh
chmod +x ~/git-ssh
export GIT_SSH=$HOME/git-ssh
```
(I also unchecked the "pass secrets to PRs" checkbox --- you may want to enable it temporarily again when you test.)

**Comment by stefanv** [comment]
@pv I regenerated the deploy key and removed the checkout key and all seems well now.

**Comment by pv** [comment]
ok, thanks, let's get this in, maybe it now works

**Comment by pv** [comment]
thanks, it indeed works now.

**Pull request merged**
