### PR TITLE
DOC: revert gh10540, removing mtrand

### PR DESCRIPTION
**Pull request by andyfaff**
#10540 converted `numpy.random.RandomState` in several docstrings to `numpy.random.mtrand.RandomState`. This was because the intersphinx mappings were incorrect (https://github.com/numpy/numpy/issues/14359). This PR reverts those changes, given that the intersphinx mappings are now correct.

### CODE REVIEW

**Comment by andyfaff** [comment]
It turns out that the numpy that we build the docs with still doesn't have the right intersphinx mapping.

**Comment by andyfaff** [comment]
I won't close, as it'll be useful when they eventually are available.

**Comment by rgommers** [comment]
Please update `intersphinx_mapping` to https://numpy.org/devdocs, then this should work

**Comment by andyfaff** [comment]
Looks as if it's passing, bar the ppc64

**Comment by andyfaff** [comment]
Self merging, I've checked all the links and they work.

**Pull request merged**
