### PR TITLE
MAINT: basinhopping remove instance test closes #5440

### LINKED ISSUE #5440: scipy.optimize.basinhopping: accept_test returning numpy.bool_ raises an error
Dear Scipy team

When using scipy.optimize.basinhopping, if the accept_test function returns an object of type numpy.bool_, an error occurs. Is this an intentional feature? If not, I think it can be removed allowing accept_test to return numpy.bool_ object.

Thanks
Ajay

### PR DESCRIPTION
**Pull request by andyfaff**
@dlax, this removes some of the instance tests discussed in #5440, but it seems more like messing round the edges rather than any concrete change. The accept tests still have to return `True`, `False` or `force accept`. The return values are well documented and I don't think we should really change it.

### CODE REVIEW

**Comment by dlax** [comment]
AFAICT, this will not fix #5440 as you still test for identity on Boolean and `np.bool_` type would not pass this. Using Numpy's Boolean types is a valid use case IMHO.

**Comment by andyfaff** [comment]
If np.bool_ is required (not a problem) then I can easily change it. I'll
change the documentation as well.

**Comment by dlax** [comment]
Andrew Nelson wrote:
> If np.bool_ is required (not a problem) then I can easily change it. I'll
> change the documentation as well.

It's not numpy.bool_ in particular, any object that support truth value 
testing should be applicable (duck typing).

**Comment by andyfaff** [comment]
Ok, so anything that equates to True is accepted, anything that equates to
False is rejected?

**Comment by dlax** [comment]
Andrew Nelson wrote:
> Ok, so anything that equates to True is accepted, anything that equates to
> False is rejected?
>

Not sure what you mean by "equates". Just rely on "truth value testing" 
https://docs.python.org/3.5/library/stdtypes.html#truth-value-testing

In your change, some like this would work I guess:

```
if testres == 'force accept':
    [...]
elif not testres:
    accept = False
```

**Comment by andyfaff** [comment]
That's what I meant.

**Comment by andyfaff** [comment]
@js850, do you have any comments on `_monte_carlo_step` using Truth value testing on whether to accept a step or not? The relevant code:

    accept = True
    for test in self.accept_tests:
        testres = test(f_new=energy_after_quench, x_new=x_after_quench,
                       f_old=self.energy, x_old=self.x)
        if testres == 'force accept':
            accept = True
            break
        elif not testres:
            accept = False

**Comment by js850** [comment]
Everything looks good to me :+1:

**Pull request merged**
