### PR TITLE
CI: run tests with pypy3 on circleci

### PR DESCRIPTION
**Pull request by pv**
Supporting also pypy3 as a platform probably does not take much extra effort (all tests pass for newest pypy release, with numpy master), and we can add it to CI to keep it working.

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
All tests in the CI matrix are passing, including the full pypy3 test suite added in here. The new pypy CI job takes about 26 minutes, which seems ok.

+1 to merge; since it is a change to our CI I'll leave it open for a bit longer.

**Comment by larsoner** [comment]
Just curious what is the reason to use CircleCI instead of Travis here? Because there is a CircleCI pypy image? To keep Travis times from increasing further?

26 minutes seems fine. +1 for merge from me

**Comment by pv** [comment]
The reason is that I initially expected it to be too close to Travis
time limits, and I happened to have an example circleci pypy config at
hand from which to copypaste. However, using "standard" docker image 
(https://hub.docker.com/r/library/pypy/) indeed is probably easier on
circleci, and it's probably faster like this since it runs in parallel
with travis.

**Review by larsoner — APPROVED** [review]

**Comment by ev-br** [comment]
Having all tests pass on pypy is great!
 +1 for having it in the CI.

**Comment by tylerjereddy** [comment]
Ok, looks like solid core dev support and no objections so in it goes.

**Pull request merged**
