### PR TITLE
ENH: LDLt decomposition for indefinite symmetric/hermitian matrices.

### PR DESCRIPTION
**Pull request by ilayn**
As discussed in #6202 on SciPy and https://github.com/numpy/numpy/pull/4078, https://github.com/numpy/numpy/pull/4079, https://github.com/numpy/numpy/issues/3960 on NumPy, this PR provides a wrapper around the solvers

```
?sytrf
?hetrf
?sytrf_rook
?hetrf_rook
```
and corresponding `lwork` computation routines. Compared to other implementations, some features are support of the rook pivoting algorithms, sanitized permutation information, symmetric (but not hermitian) complex-valued matrices. 

As one can see, the LAPACK output is so densely packed, getting the necessary information out with all exceptions requires quite some branching. Hence the length helper functions. This possibly explains why there are no open source implementations of the unpacking of these routines. We can also argue that these are rarely needed however since we have enough PRs and issues open for it, it seemed a valid contribution (not to mention I needed them).

I've also included the docstrings for the internal functions in case someone else wants to step in to optimize it further. The total cost of the unpacking is roughly about 10% of the actual time spent in the LAPACK call thus looks acceptable. 

I haven't spent too much time on the benchmarks since I kind of ran out of steam but from the few experiments, it looks like after 2k x 2k matrices the residual error of matlab in the frobenius norm sense gets unstable whereas this function though slower stays within the bounds. It might be due to a preconditioning step within matlab that I did not implement. 

The API requires essentially two keyword setting to choose between the correct solver with correct side of the triangular parts, `only_sym` as in *It is only symmetric but not hermitian*, and the switch for bounded BK algorithm `rook_pivoting`.

### CODE REVIEW

**Comment by ilayn** [comment]
Is there any way to check the LAPACK version on the TravisCI environment? The fails are about some LAPACK routines I've included for completeness (they are not essential to this PR, ?sytf2 and ?sytf2_rook) not being found though locally I can use them.

**Comment by ilayn** [comment]
Argh, I should have known. Many of these goodies came with LAPACK 3.5.0. What is the minimum required LAPACK for SciPy? 

Here is the [change log for v.3.5.0](http://www.netlib.org/lapack/lapack-3.5.0.html)

**Comment by person142** [comment]
See https://github.com/scipy/scipy/pull/6051.

**Comment by ilayn** [comment]
@person142 Ouch. So 3.5.0 is not even on the table. I should disable the rook parts then...

**Comment by ilayn** [comment]
Hmm, if I disable it, then later if we reintroduce it, the keyword would have to go to the bottom of the signature right?

**Comment by person142** [comment]
> the keyword would have to go to the bottom of the signature

Yup. Unless the world shifts to Python 3 overnight. ;-)

**Comment by rgommers** [comment]
something went wrong in the rebase here

**Comment by ilayn** [comment]
Ooops. I was doing a generic cleanup yesterday, sorry about that. I'll fix it tonight.

**Comment by twiecki** [comment]
What's the status of this? It would be quite useful to PyMC3.

**Comment by ilayn** [comment]
@twiecki This is done but unfortunately, minimum LAPACK version is too old and we are waiting for #6051 to be concluded.

**Comment by ilayn** [comment]
If I'm understanding @langou correctly on [his post here](http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=5&t=5087) the ?SYTRF_ROOK routines are deprecated before we can even push them in :) 

So this is just a reminder for myself to update the unpacking of the rook parts and asking for validation in case he can find time to read this...

**Comment by langou** [comment]
Hello. 

Yes, please use SYTRF_RK. And do not use SYTRF_ROOK. 

The interface of SYTRF_RK is cleaner and enables Level 3 BLAS inversion, Level 3 BLAS solve, etc. without any processing. The interface of SYTRF_ROOK needs some processing in between SYTRF_ROOK and any Level 3 BLAS follow up. 

As written in the post, we would like to deprecate SYTRF_ROOK from LAPACK in the near future. There is a plan for changing the interface of SYTRF itself similarly. (And probably change the name.) This is in the wish list. @scr2016 might want to give you more information. 

Best wishes, 
Julien.

**Comment by ilayn** [comment]
@langou Great, thank you for the confirmation. I'll update accordingly asap.

**Pull request closed without merging**
