### PR TITLE
DOC: signal.firls: fix broken link

### PR DESCRIPTION
**Pull request by doshi-kevin**
#### Reference issue

#21452 

#### What does this implement/fix?

Changed the dead reference link to a newer one.

#### Additional information

According to the current available sources on the internet, no other link is available for the mentioned reference publication. 
Please check the pull request, I would really love to be a contributor to this open source project.

### CODE REVIEW

**Comment by ilayn** [comment]
This link also smells like it won't survive another decade but it is what it is, unless we contact the author. 

Thank you @doshi-kevin we are also very happy that you spared your time to contribute. Please keep them coming.

**Comment by lucascolley** [comment]
@ilayn feel free to ignore my suggestion, but if you would like to entertain my pedantry, I would have suggested a squash merge here as the title of the PR conformed to our commit message guidelines, while the commit message itself didn't (partially motivated by an IRL conversation I just had about scikit-learn only squash-merging). Maybe just something to keep in mind for the future (or not, if you have better things to worry about!)

**Comment by ilayn** [comment]
I see, it had a single commit so there was nothing to squash but I think you mean the commit messages right?

**Comment by lucascolley** [comment]
Yeah, squash allows you to edit the commit message. For me, this defaults to the PR title, which is often suitable.

**Comment by ilayn** [comment]
OK let me pay attention to it from now on, please warn me again if I forget.

**Comment by doshi-kevin** [comment]
Hey @lucascolley , sorry it's 4 am in India so can't work on squashing right now, also so since you merged the pull request, does that mean that I am now a contributor of scipy.
Is there anything else needed or to be done. Happy to help 😊.

**Comment by lucascolley** [comment]
all done from your side @doshi-kevin , yes, you have now made your first contribution to SciPy. Thanks!

**Pull request merged**
