### PR TITLE
WIP: several x ckdtree query_pairs speedup

### PR DESCRIPTION
**Pull request by argriffing**
Instead of making a set of pairs and converting it to an ndarray, make the array directly.

But this is a horrible hack so comments or suggestions are appreciated!

``` python
from __future__ import print_function
from time import time as perf_counter
import sys
import numpy as np
import scipy
from scipy.spatial import cKDTree

print(sys.version)
print('numpy version:', np.__version__)
print('scipy version:', scipy.__version__)

npoints = 1000000
print('npoints:', npoints)

print('making some points and building the tree...')
t0 = perf_counter()
np.random.seed(0)
data = np.random.random((npoints, 2))
tree = cKDTree(data)
t1 = perf_counter()
print(t1 - t0)

pairs = tree.query_pairs(.002)
print(len(pairs))
t2 = perf_counter()
print(t2 - t1)

pairs_b = np.array(list(pairs))
t3 = perf_counter()
print(t3 - t2)

pairs_c = np.fromiter(pairs, dtype=np.dtype([("a", int), ("b", int)]))
t4 = perf_counter()
print(t4 - t3)

pairs_d = tree.query_pairs_array(.002)
print(pairs_d.shape)
t5 = perf_counter()
print(t5 - t4)

print('checking that the sets are the same...')
other_pairs = set(tuple(row) for row in pairs_d)
diff_a = pairs - other_pairs
diff_b = other_pairs - pairs
if pairs == other_pairs:
    print('they are the same!')
else:
    print('they are different :( :( :(')

print('garbage collecting...')
```

```
2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
numpy version: 1.10.0.dev-2ad5388
scipy version: 0.15.0.dev-c2375ee
npoints: 1000000
making some points and building the tree...
0.232572078705
6271234
2.88389992714
5.57017302513
2.22471213341
(6271234, 2)
1.0884988308
checking that the sets are the same...
they are the same!
garbage collecting...
```

### CODE REVIEW

**Comment by sturlamolden** [comment]
I suggest we rather add a keyword argument to ```query_pair``` to control the output type rather than adding almost identical query methods. It just pollutes the API and the docs to have a bunch of almost identical query methods that only differ in the collection or sequence type they return.

**Comment by anntzer** [comment]
Something like
```
query_pairs(self, r, p, eps, output_type="set") # one of "set", "array", "count"?
```

**Comment by sturlamolden** [comment]
Or just ```output```?

**Comment by sturlamolden** [comment]
In the long run I think we should try to move all query methods of cKDTree into C++. At least that was my plan. It can give fantastic speedups, see #4374 

Note that after #4374 ```leafnode``` and ```innernode``` structs are now both called ```ckdtreenode```. They are merged to allow the kd-tree to be stored in a contiguous buffer.

**Comment by anntzer** [comment]
I thought that `output` could be confused with the `out` arg of ufuncs, but tbh. I don't care much about the exact API.

**Comment by jaimefrio** [comment]
In `pair_array_accumulator`, rather than keeping both an `i` and a `j` array, you could keep a single `idx` array of twice the size. Assignments would then look something like:

```
self.idx_data[2*k] = i
self.idx_data[2*k+1] = j
```

The main advantage is you would spare yourself an extra copy in the call to `toarray`, since you would simply need to reshape the `idx` array, no need to do the `vstack`.

**Comment by sturlamolden** [comment]
The set is used to prevent the same pair from being counted twice. With an array you need to check that the pair is not already in the array. An open-adress hash table is the best data structure for this. That is why we do not create the array directly. But we can presumably get a good speedup by using a C++ class rather than a Python set.

**Comment by sturlamolden** [comment]
I looked at your code and it does not ensure that pairs are only counted once. If you start to do this you will find that an array is not the fastest data structure here.

**Comment by anntzer** [comment]
Seems like the easiest way out is to use a 2D array and `lexsort` at the end, keeping every other entry (which amounts to dropping the duplicates).  Sure this is still `O(n log n)` but this should be competitive.

**Comment by sturlamolden** [comment]
Using ```std::set``` instead of Python set would also be ```O(n log n)```. Sorting might be faster, but a set would use less memory by a factor of 50 %. Using a hash table would be ```O(n)```. It does not mean that hashing is always the faster option, but it has better scalability. A hash table requires more memory though, as more than 2/3 fill rate is sub-optimal. Anyway, I think the major gain we see here is from avoiding Python overhead. The easiest fix for that is to use ```std::set``` in the Cython code.

**Comment by sturlamolden** [comment]
I have started the tedious work of porting the rest of cKDTree to C++. The setup is the same as for query. This will make ```query_pairs```a lot faster (e.g. no Python set). We can also multithread and release the GIL. The setup is the same as for ```query``` which is in C++ in the 0.16 branch. 

Right now I have just copied the code and made placeholders for the C++. But the main structure is already there.

https://github.com/sturlamolden/scipy/tree/cpp_ckdtree/scipy/spatial/ckdtree

**Comment by anntzer** [comment]
I guess that lexsort always uses quicksort (the default for np.sort), which is certainly pretty bad here.  Still,
1. I don't see why std::set should have a 50% lower memory usage (in fact, I'd expect it to use more memory), and
2. in practice, at least the GCC sort implementation [is O(n log n)](https://en.wikipedia.org/wiki/Introsort) even with partially sorted data.  It seems quite probable(?) that even if std::set is able to reach the same complexity it'll be slower in practice.

**Comment by sturlamolden** [comment]
Yes, duh... To my defence, I did not write this part of cKDTree, Anne and Pat did. ;)

We still have to return ```set```by default, though, to maintain backwards compatibility.

**Comment by sturlamolden** [comment]
In the C++ version I now do this, which should address the issue here.

```
struct Pair {
    npy_intp i;
    npy_intp j;
};

inline void 
set_add_ordered_pair(std::vector<Pair>& results,
                       const npy_intp i, const npy_intp j)
{
    if (i < j) {
        Pair p;
        p.i = i;
        p.j = j;
        results.push_back(p); 
    }
}
```

**Comment by anntzer** [comment]
You can write `Pair p = {i, j};`.  Hardly a big deal.

**Comment by sturlamolden** [comment]
```query_pair``` is ported over to C++. I get a rougly 6x speedup on my Mac. The Python ```set``` has no impact on the performance.

**Comment by ev-br** [comment]
@sturlamolden @rainwoodman What about this PR --- this has been superseded by what is now available in master, correct?

**Comment by sturlamolden** [comment]
I think so.

**Comment by sturlamolden** [comment]
The PR that @rgommers pulled basically implements this PR, except the code is in C++.

**Comment by argriffing** [comment]
OK I will close this then, thanks!

**Pull request closed without merging**
