### PR TITLE
update lpmv docstring

### PR DESCRIPTION
**Pull request by argriffing**
See https://github.com/scipy/scipy/issues/4615.
Running `generate_ufuncs.py` also happened to finish applying a typo correction https://github.com/scipy/scipy/pull/5096 to `_ufuncs.pyx`.

### CODE REVIEW

**Comment by argriffing** [comment]
Should ufunc parameters be documented as array_like, or is that redundant?

**Comment by rgommers** [comment]
> Should ufunc parameters be documented as array_like, or is that too redundant?

You mean all of these: http://docs.scipy.org/doc/numpy/reference/ufuncs.html#optional-keyword-arguments? That's too much I think.

**Comment by argriffing** [comment]
Yes I was wondering how much 'ufunc stuff' should be documented in specific ufuncs, but I wasn't suggesting adding function-specific documentation of all of those keyword arguments.

Here's a ufunc parameter documentation example from `arctan2` in numpy:
```
    Parameters
    ----------
    x1 : array_like, real-valued
        `y`-coordinates.
    x2 : array_like, real-valued
        `x`-coordinates. `x2` must be broadcastable to match the shape of
        `x1` or vice versa.
```
Here the `array_like` types and the broadcastability caveats are inherited ufunc properties, but they are still given explicitly.  This is different from the `lpmv` docstring which doesn't explicitly document that the parameters can be array_like.  Also the docstring notation varies within scipy.special; some of the docstrings use notation more like `arctan2` and some use notation more like `lpmv`.

This is not a big deal, but a guideline could be helpful especially because many of the scipy.special functions still have only stubbed docstrings that do not even have a `Parameters` section.

**Comment by pv** [comment]
I think it may be best to assume the reader is familiar with ufunc
broadcasting. The ufunc-or-not status for each function is briefly
mentioned on the scipy.special module documentation page. I don't see
problem in documenting parameters as `array_like`, but the complex vs.
real-valuedness is probably more relevant information.

**Comment by ewmoore** [comment]
@argriffing, is this ready to go?  Kinda looks like it is.

**Comment by pv** [comment]
lgtm

**Pull request merged**
