### PR TITLE
CI: azure: Fix handling of 'skip azp'.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Print the git log with format `%B` instead of `%s`
to get the full commit message (subject and body).

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Strange.  If I run the `git log` command from `azure-pipelines.yml` locally, with `skip` changed to 0 because I don't have the merge commit, I get:

```
$ git_log=`git log --max-count=1 --skip=0 --pretty=format:"%B"`
$ echo $git_log
CI: azure: Fix handling of 'skip azp'. Print the git log with format `%B` instead of `%s` to get the full commit message (subject and body). [skip actions] [skip azp]
```
So it seems to work as expected: `git_log` is assigned the full message, including the subject and body of the commit message. But the Azure log for the "Check Skip" job shows:

```
Evaluating: or(contains(variables['log'], '[skip azp]'), contains(variables['log'], '[azp skip]'), contains(variables['log'], '[skip ci]'), contains(variables['log'], '[ci skip]'))
Expanded: or(contains('CI: azure: Fix handling of ''skip azp''.', '[skip azp]'), contains('CI: azure: Fix handling of ''skip azp''.', '[azp skip]'), contains('CI: azure: Fix handling of ''skip azp''.', '[skip ci]'), contains('CI: azure: Fix handling of ''skip azp''.', '[ci skip]'))
Result: False
```
So it looks like `variables.log` (apparently translated to `variables['log']` in the Azure log file) is still getting just the subject line and not the body of the commit message.

Ping @larsoner: got any clues?

**Comment by WarrenWeckesser** [comment]
In the last commit, I piped the output of `git log` to [`tr`](https://linux.die.net/man/1/tr) to convert the newlines in the output to spaces.  Now the "Skip" job successfully finds the `[skip azp]` markup in the last commit and prevents the rest of the Azure tests from running.

**Comment by tupui** [comment]
If this works now, could you add a line break in the CI documentation for the commit message? I had to omit it for this reason.

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge after updating the docs as suggested by @tupui

**Comment by WarrenWeckesser** [comment]
@tupui, do you mean the example at end of https://github.com/scipy/scipy/blob/master/doc/source/dev/contributor/continuous_integration.rst?  Are you suggesting changing

    DOC: improve QMCEngine examples.
    [skip azp] [skip actions]

to something like

    DOC: improve QMCEngine examples.
    [skip azp]
    [skip actions]

?

**Comment by tupui** [comment]
Yes here, but with a blank line in between. As in the example to format properly commit message (in the workflow doc). This was suggested by Ralf when I added this doc but I couldn't due to this bug.

**Comment by WarrenWeckesser** [comment]
@tupui, got it, thanks.

**Comment by WarrenWeckesser** [comment]
The example commit message in the continuous integration docs has been updated.

**Review by tupui — APPROVED** [review]
Thanks @WarrenWeckesser and @larsoner for the review. Merging

**Pull request merged**
