### PR TITLE
MAINT: Cleanup uses of PY_VERSION_HEX, NPY_PY3K in sparse

### PR DESCRIPTION
**Pull request by sethtroisi**
Cleans up Python2 constants in scipy/sparse

See: PR #11621 and issue #11584

### CODE REVIEW

**Review by peterbell10 — APPROVED** [review]

**Comment by perimosocordiae** [comment]
Looks like the Windows CI checks all timed out. I'll try re-running them, as this PR's changes seem safe to me.

**Comment by perimosocordiae** [comment]
Checks are green now, merging.

**Comment by perimosocordiae** [comment]
Thanks, @sethtroisi

**Comment by tylerjereddy** [comment]
> Looks like the Windows CI checks all timed out

This has been happening more often lately :/

**Pull request merged**
