### PR TITLE
TST:sparse.linalg: Use the more convenient "assert_normclose" in "test_minres.py"

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

A bug fix: the convergence condition should be `||b - Ax|| < tol * ||b||`, where `tol` is the tolerance of relative residual in MINRES algorithm.

### CODE REVIEW

**Comment by zhaog6** [comment]
Dear Ralf @rgommers ,Stefan @stefanv , ilhan @ilayn ,The PR has not been reviewed for a long time. Could you review this PR? Thank you all.

**Comment by ilayn** [comment]
My sincere apologies, I am having difficulty keeping up with the influx of issues lately so probably in my lazy mind I'm choosing the easy tasks first. I'll take a look asap.

**Comment by ilayn** [comment]
This looks good but can you also touch the error message of `assert_normclose()` in `test_iterative.py` if you don't mind;

- it can use an f-string instead of the printf stuff
- it really doesn't say how much the bound is violated which is what we want to see if it fails. 

By the way, this is not incorrect but a choice (admittedly looks better) we make since both bounds are related by the norm of b which we can adjust.

**Comment by zhaog6** [comment]
Dear @ilayn ,
Never mind, thanks for your review.
> it can use an f-string instead of the printf stuff

Yes, it's a good idea. Thanks.

> this is not incorrect but a choice (admittedly looks better)

I don't think so. we can take a look at the following description in docstring in `sparse/linalg/isolve/minres.py`:
https://github.com/scipy/scipy/blob/ce9621b4e394f2e547a5268985604da38dc2be55/scipy/sparse/linalg/isolve/minres.py#L46-L48
The MINRES algorithm terminates when `||b - Ax|| < ||b|| * tol`, where `tol` is the parameter option `minres(...)`. Let's see what the test is in the original `test_minres.py`:
https://github.com/scipy/scipy/blob/ce9621b4e394f2e547a5268985604da38dc2be55/scipy/sparse/linalg/isolve/tests/test_minres.py#L65-L73
The test code tests `||b - Ax|| < tol` instead of `||b - Ax|| < ||b|| * tol` mentioned in `minres.py`, where `tol` is also the parameter option in `minres(...)`. It will be confusing, and then someone will ask why you don't test the relative residual criterion `||b - Ax|| < tol * ||b||` (assert_normclose(a.dot(x), b, tol=tol)) but only test the absolute residual criterion `||b - Ax|| < tol` (norm(a.dot(x) - b) < tol). It is not a reasonable test if using the original `norm(a.dot - b) < tol` because the convergence of the MINRES algorithm doesn't mean that `||b - Ax|| < tol` (As mentioned in 'minres.py': "The algorithm terminates when the **relative** residual is below `tol`"). The above is just my opinion.

**Comment by ilayn** [comment]
No, I get your point. What I meant is that we can always do the `tol = ||b||*new_tol` offline and hard code it. Hence we have option to adjust so depending on who writes the test, the choice differs. But anyways, it's a minor nitpick so thank you for this PR @zhaog6

**Comment by zhaog6** [comment]
Okay, thanks for your kind explaination and suggestions @ilayn

**Pull request merged**
