### PR TITLE
BUG: stats: Fix boxcox_llf to avoid loss of precision.

### LINKED ISSUE #6873: 'stats.boxcox' return all same values
I applyed `stats.boxbox` to my data and the returned values are all the same, which seems really unreasonable!  it returned this same result in `scipy=0.18.1` and `scipy=0.17.1`. the  optimal `lambda` in my case is  -5.501196436791543.
your can download my data([data.txt](https://github.com/scipy/scipy/files/662791/data.txt)).
I also tried the `boxcox` function in `R` and it returned reasonable result. So  i think  the `boxcox_normmax`  function should do more test and should be used carefully.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
This change reformulates the expression for the log-likelihood
function computed by boxcox_llf in a way that is mathematically
equivalent to the old version but avoids the loss of precision
that can occur in the subtraction y**λ - 1.

For conciseness, let T(y; λ) be the Box-Cox transformation

    T(y; λ) = { (y**λ - 1)/λ  if λ ≠ 0
              { ln(y)         if λ = 0

As explained in a comment in gh-6873, a problem arises if y
is sufficiently large and λ is sufficiently negative (e.g.
5000**-5 is 3.2e-19).  When y**λ approaches the floating point
epsilon, the subtraction y**λ - 1 suffers catastrophic loss of
precision.  When this occurs in the log-likelihood function,
it results in the optimizer returning garbage.

The log-likelihood function (for a vector Y) is

    L(Y; λ) = -n*ln(var(T(Y; λ)))/2 + (λ - 1)*sum(ln(Y))

where n is the length of Y.  The Box-Cox transformation T only
appears as the argument to var; we only use the transform to
compute the variance of the transformed data.  The variance is
invariant with respect to a constant shift, so, assuming λ ≠ 0,

    var(T(y; λ)) = var(Y**λ/λ - 1/λ) = var(Y**λ/λ)

That is, we can compute var(T(y; λ)) without the subtraction
in the Box-Cox transformation.

Closes gh-6873.
Closes #9271.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
I added this to the 1.3 milestone.

**Review by larsoner — APPROVED** [review]
Looks like a reasonable solution to me, with appropriate tests (and rationale).

@omtinez can you take a look and see if you agree?

**Comment by omtinez** [comment]
Looks good to me. Pretty clever trick to avoid the subtraction altogether. The code is very well documented and significantly easier to understand than the replaced lines (or my bandaid fix).

**Review by omtinez — APPROVED** [review]

**Comment by WarrenWeckesser** [comment]
Thanks @omtinez!

**Comment by rgommers** [comment]
LGTM too, merged. Thanks @WarrenWeckesser, and thanks @omtinez for your PR and for the review!

**Pull request merged**
