### PR TITLE
CI/DEV: add some new auto-labels

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
n/a

#### What does this implement/fix?
A few more auto-labels since what we have seems to be working well.

#### Additional information
Feel free to add any more suggestions but I think this pretty much covers everything now.

### CODE REVIEW

**Comment by ev-br** [comment]
(A drive-by comment) While at it, may want to add `*.c.in` for C/C++ label, there are some in scipy.signal: https://github.com/scipy/scipy/blob/main/scipy/signal/_lfilter.c.in etc.

**Comment by lucascolley** [comment]
> may want to add *.c.in for C/C++ label

That's already here on line 123/125, no?

**Comment by ev-br** [comment]
> That's already here on line 123/125, no?

Indeed. Sorry for the noise @lucascolley !

**Review by j-bowhay — APPROVED** [review]
LGTM thanks!

**Pull request merged**
