### PR TITLE
CI: bdist_wheel windows job Azure --> GHA

### PR DESCRIPTION
**Pull request by andyfaff**
Moves the Azure `setup.py bdist_wheel` job from Azure to GHA. Also remove excess CI configuration from Azure pipelines because it's no longer needed.

### CODE REVIEW

**Comment by rgommers** [comment]
@andyfaff thanks! Nice to see most of the Azure config being removed.

The question I have at the moment is why you are trying to force static linking of `libopenblas`. I don't think the old CI config or wheel builds did that? It also seems to not be so happy:

```
 INFO:   libraries libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0 not found in ['c:\\opt\\64\\lib']
INFO: Library libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0 was not found. Ignoring
INFO:   FOUND:
INFO:     library_dirs = ['D:\\a\\scipy\\scipy\\build\\openblas_info']
INFO:     libraries = ['openblas_info']
INFO:     language = f77
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
INFO:   FOUND:
INFO:     library_dirs = ['D:\\a\\scipy\\scipy\\build\\openblas_info']
INFO:     libraries = ['openblas_info']
INFO:     language = f77
INFO:     define_macros = [('HAVE_CBLAS', None)]

WARN: could not find library 'quadpack' in directories ['D:\\a\\scipy\\scipy\\build\\openblas_lapack_info']
WARN: could not find library 'mach' in directories ['D:\\a\\scipy\\scipy\\build\\openblas_lapack_info']
WARN: could not find library 'openblas_lapack_info' in directories ['D:\\a\\scipy\\scipy\\build\\openblas_lapack_info']

INFO: c:\rtools40\ucrt64\bin\gfortran.exe -Wall -g -Wall -g -shared -Wl,--whole-archive c:\opt\64\lib\libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0.a -Wl,--no-whole-archive -Lc:\rtools40\ucrt64\lib\gcc\x86_64-w64-mingw32\10.3.0 -LC:\hostedtoolcache\windows\Python\3.10.11\x64\libs -LC:\hostedtoolcache\windows\Python\3.10.11\x64\PCbuild\amd64 -Lbuild\temp.win-amd64-3.10

INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\a\scipy\scipy\build\openblas_lapack_info /LIBPATH:c:\rtools40\ucrt64\lib\gcc\x86_64-w64-mingw32\10.3.0 
```

There are also a ton of logging errors towards the end that don't look familiar:

<details>

```
--- Logging error ---
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
ValueError: underlying buffer has been detached
Call stack:
  File "D:\a\scipy\scipy\setup.py", line 532, in <module>
    setup_package()
  File "D:\a\scipy\scipy\setup.py", line 528, in setup_package
    setup(**metadata)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\numpy\distutils\core.py", line 169, in setup
    return old_setup(**new_attr)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\wheel\bdist_wheel.py", line 405, in run
    wf.write_files(archive_root)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\wheel\wheelfile.py", line 137, in write_files
    self.write(path, arcname)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\wheel\wheelfile.py", line 153, in write
    self.writestr(zinfo, data, compress_type)
  File "C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\wheel\wheelfile.py", line 172, in writestr
    log.info(f"adding '{fname}'")
Message: "adding 'scipy/stats/_crosstab.py'"
Arguments: ()
```

</details>

**Comment by andyfaff** [comment]
<The Azure logs I refer to are from [this run](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=24523&view=logs&jobId=5798bea6-6f0e-53d8-f5d0-dee01455df3d&j=14043b7d-2651-5a54-9cc3-70f3679a5d14&t=ee6d32fb-4dd5-5051-d9ea-cfb3b2dcae02), from #18361>

> The question I have at the moment is why you are trying to force static linking of libopenblas. I don't think the old CI config or wheel builds did that?

From what I can tell the old CI didn't use the OpenBLAS dll. The OpenBLAS [download script](https://github.com/scipy/scipy/pull/18369/files#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5L139) uses `openblas_support.py`. On a Windows machine [unpack_windows_zip](https://github.com/scipy/scipy/blob/main/tools/openblas_support.py#L175) only extracts the `openblas.a` file, but not `openblas.dll.a` nor `openblas.dev.a`, and not the dll.
From this [build log](https://dev.azure.com/scipy-org/df8ffb44-7275-43bc-90f9-aa5c93ef5c51/_apis/build/builds/24523/logs/50) it looks like the build process turns the `openblas.a` file into a dll:

```
2023-04-24T21:31:03.5652957Z INFO: C:\rtools40\ucrt64\bin\gfortran.exe -Wall -g -Wall -g -shared -Wl,--whole-archive C:\agents\3.218.0\openblaslib\openblas.a -Wl,--no-whole-archive -LC:\rtools40\ucrt64\lib\gcc\x86_64-w64-mingw32\10.3.0 -LC:\hostedtoolcache\windows\Python\3.10.11\x64\libs -LC:\hostedtoolcache\windows\Python\3.10.11\x64\PCbuild\amd64 -Lbuild\temp.win-amd64-3.10 -o build\temp.win-amd64-3.10\Release\.libs\libopenblas.X2JZKBUGJG3HZYXZVWGSF2TAVVSA5SLB.gfortran-win_amd64.dll -Wl,--allow-multiple-definition -Wl,--output-def,build\temp.win-amd64-3.10\Release\libopenblas.X2JZKBUGJG3HZYXZVWGSF2TAVVSA5SLB.gfortran-win_amd64.def -Wl,--export-all-symbols -Wl,--enable-auto-import -static -mlong-double-64
2023-04-24T21:31:11.7640634Z INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\lib.exe /def:build\temp.win-amd64-3.10\Release\libopenblas.X2JZKBUGJG3HZYXZVWGSF2TAVVSA5SLB.gfortran-win_amd64.def /OUT:build\temp.win-amd64-3.10\Release\libopenblas.X2JZKBUGJG3HZYXZVWGSF2TAVVSA5SLB.gfortran-win_amd64.lib /MACHINE:X64
```

Something similar occurs in this PR if I only retain `openblas.a`. I have no idea of how the build process makes the dll.

The Azure CI runs did not create a `site.cfg` either. Neither [this run](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=24523&view=logs&jobId=5798bea6-6f0e-53d8-f5d0-dee01455df3d&j=14043b7d-2651-5a54-9cc3-70f3679a5d14&t=ee6d32fb-4dd5-5051-d9ea-cfb3b2dcae02) or [this run](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=24523&view=logs&jobId=5798bea6-6f0e-53d8-f5d0-dee01455df3d&j=5e97be52-375c-52a0-7702-83e7914a0a83&t=82ef957c-b597-5025-985c-a68e21314567) uses a `site.cfg`. Moreover, neither of them finds openblas either ([see here](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=24523&view=logs&j=14043b7d-2651-5a54-9cc3-70f3679a5d14&t=ee6d32fb-4dd5-5051-d9ea-cfb3b2dcae02&l=130)). All the warnings and logging errors from your comment are in those Azure build logs.

So in effect, the old setup.py Azure entries are quite broken, and all I'm doing is replicate the broken behaviour.

When I try an alternate approach, and retain all the files from the OpenBLAS archive, including the DLL, then the BLAS discovery at the start of the build is successful. However, the build fails halfway through with some LAPACK symbols not being resolved. I'll make a commit now to demonstrate this.

**Comment by andyfaff** [comment]
In the last commit I made some modifications so the OpenBLAS install is found. The build log is [here](https://github.com/scipy/scipy/actions/runs/4808257873/jobs/8558014986?pr=18369). THe build log shows that OpenBLAS is found:
```
INFO: openblas_lapack_info:
creating C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users
creating C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1
creating C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1\AppData
creating C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1\AppData\Local
creating C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1\AppData\Local\Temp
creating C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt /TcC:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\source.c /FoC:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\source.obj
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\opt\64\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\um\x64 libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0.lib C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\source.obj /OUT:C:\Users\RUNNER~1\AppData\Local\Temp\tmpmgonplm1\a.out.exe
C:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\numpy\distutils\system_info.py:931: UserWarning: Specified path c:\opt\bin is invalid.
  path = self.get_paths(self.section, key)
INFO:   FOUND:
INFO:     libraries = ['libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0', 'libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0']
INFO:     library_dirs = ['c:\\opt\\64\\lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
INFO: 
INFO:   FOUND:
INFO:     libraries = ['libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0', 'libopenblas_v0.3.20-571-g3dec11c6-gcc_10_3_0']
INFO:     library_dirs = ['c:\\opt\\64\\lib']
INFO:     language = c
INFO:     define_macros = [('HAVE_CBLAS', None)]
```

However, the build fails later on when trying to build `integrate._quadpack`

```
INFO: building 'scipy.integrate._quadpack' extension
INFO: compiling C sources
creating build\temp.win-amd64-3.10\Release\scipy\integrate
INFO: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_CBLAS -ID:\a\scipy\scipy\scipy\_lib\src -IC:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.10\numpy\distutils\include -IC:\hostedtoolcache\windows\Python\3.10.11\x64\include -IC:\hostedtoolcache\windows\Python\3.10.11\x64\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt /Tcscipy\integrate\_quadpackmodule.c /Fobuild\temp.win-amd64-3.10\Release\scipy\integrate\_quadpackmodule.obj
WARN: could not find library 'quadpack' in directories ['c:\\opt\\64\\lib']
WARN: could not find library 'mach' in directories ['c:\\opt\\64\\lib']
INFO: c:\rtools40\ucrt64\bin\gfortran.exe -Wall -g -Wall -g -shared D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqag.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqage.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagi.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagie.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagp.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagpe.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqags.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagse.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawc.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawce.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawf.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawfe.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawo.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawoe.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqaws.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawse.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25c.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25f.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25s.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqcheb.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqelg.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk15.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk15i.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk15w.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk21.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk31.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk41.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk51.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk61.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqmomo.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqng.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqpsrt.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqwgtc.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqwgtf.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqwgts.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\mach\d1mach.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\mach\xerror.o -Lc:\rtools40\ucrt64\lib\gcc\x86_64-w64-mingw32\10.3.0 -LC:\hostedtoolcache\windows\Python\3.10.11\x64\libs -LC:\hostedtoolcache\windows\Python\3.10.11\x64\PCbuild\amd64 -Lbuild\temp.win-amd64-3.10 -o build\temp.win-amd64-3.10\Release\.libs\libdqag.CH4MKSQ4SKWQSAVBXAXBJJZV5QXSBTUP.gfortran-win_amd64.dll -Wl,--allow-multiple-definition -Wl,--output-def,build\temp.win-amd64-3.10\Release\libdqag.CH4MKSQ4SKWQSAVBXAXBJJZV5QXSBTUP.gfortran-win_amd64.def -Wl,--export-all-symbols -Wl,--enable-auto-import -static -mlong-double-64
c:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25f.o: in function `dqc25f_':
D:\a\scipy\scipy/scipy/integrate/quadpack/dqc25f.f:293: undefined reference to `dgtsv_'
c:/rtools40/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\a\scipy\scipy/scipy/integrate/quadpack/dqc25f.f:235: undefined reference to `dgtsv_'
collect2.exe: error: ld returned 1 exit status
error: Command "c:\rtools40\ucrt64\bin\gfortran.exe -Wall -g -Wall -g -shared D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqag.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqage.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagi.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagie.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagp.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagpe.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqags.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqagse.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawc.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawce.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawf.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawfe.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawo.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawoe.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqaws.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqawse.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25c.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25f.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqc25s.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqcheb.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqelg.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk15.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk15i.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk15w.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk21.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk31.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk41.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk51.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqk61.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqmomo.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqng.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqpsrt.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqwgtc.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqwgtf.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\quadpack\dqwgts.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\mach\d1mach.o D:\a\scipy\scipy\build\temp.win-amd64-3.10\scipy\integrate\mach\xerror.o -Lc:\rtools40\ucrt64\lib\gcc\x86_64-w64-mingw32\10.3.0 -LC:\hostedtoolcache\windows\Python\3.10.11\x64\libs -LC:\hostedtoolcache\windows\Python\3.10.11\x64\PCbuild\amd64 -Lbuild\temp.win-amd64-3.10 -o build\temp.win-amd64-3.10\Release\.libs\libdqag.CH4MKSQ4SKWQSAVBXAXBJJZV5QXSBTUP.gfortran-win_amd64.dll -Wl,--allow-multiple-definition -Wl,--output-def,build\temp.win-amd64-3.10\Release\libdqag.CH4MKSQ4SKWQSAVBXAXBJJZV5QXSBTUP.gfortran-win_amd64.def -Wl,--export-all-symbols -Wl,--enable-auto-import -static -mlong-double-64" failed with exit status 1
```

It can't find a symbol called `dgtsv`. I presume that's provided by OpenBLAS? I can't see any OpenBLAS related items in the gfortran call. Shouldn't there be something like `-LC:\opt\64\lib -lopenblas<something>`?

**Comment by rgommers** [comment]
Thanks for the context, that is very helpful. It seems like our Azure setup did something quite different from our old wheel build machinery then. Since we don't need wheels anymore, I guess that does not matter much. All we're testing here is that we don't break `setup.py` builds just yet for conda-forge on Windows, e.g. by forgetting to include changes in `setup.py` when we make them in `meson.build`. 

> It can't find a symbol called `dgtsv`. I presume that's provided by OpenBLAS? I can't see any OpenBLAS related items in the gfortran call. Shouldn't there be something like `-LC:\opt\64\lib -lopenblas<something>`?

Yes indeed, that's what I would expect. That is a LAPACK symbol, so should indeed come from OpenBLAS.

**Comment by andyfaff** [comment]
`setup.py` seems to be using cl.exe instead of gcc provided by mingw. Is there a way of mandating the use of gcc instead of Visual Studio?

**Comment by rgommers** [comment]
> `setup.py` seems to be using cl.exe instead of gcc provided by mingw. Is there a way of mandating the use of gcc instead of Visual Studio?

Compiler selection is usually best done via environment variables (may need `shell: bash` in the relevant job):
```
export CC = gcc
export CXX = g++
export FC = gfortran  # probably not needed, only one compiler installed
```

**Comment by andyfaff** [comment]
Apparently the scipy-wheels build had to jump through numpy distutils hoops to get things to work, https://github.com/MacPython/scipy-wheels/blob/master/appveyor.yml#L131. I might close this PR, work on it some more in my fork, then reopen.

**Comment by rgommers** [comment]
Are you sure you want to dig into that? The job was passing before my first comment. I'm fine with not improving over what it did in Azure.

**Comment by andyfaff** [comment]
I don't want to disappear into the rabbit hole, no. However it irks me that I couldnt get it to work easily.

**Comment by andyfaff** [comment]
I might just drop the last few commits and merge.

**Comment by andyfaff** [comment]
Tests passed for setup.py job, and review was +ve, merging.

**Pull request merged**
