### PR TITLE
BUG/ENH: Added possible _transpose into LinearOperator. Fixes #8486

### LINKED ISSUE #8486: [Bug] '_<...> LinearOperator' object has no attribute '_transpose'
As far as I understand, `sparse.LinearOperator` creates some instance of `CustomLinearOperator` when it is called by `aslinearoperator()` or when passed `matvec=`.
But neither `CustomLinearOperator`, nor, e.g., `SumLinearOperator` have `transpose()`.

And the [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html) do not say much about how `transpose()` should be used or implemented.

### Reproducing code example:
```
import numpy as np
import scipy as sp
import scipy.sparse.linalg as sla


dim = 8
shp = (dim, dim)

I = np.eye(*shp)

x0 = -sp.pi
xf = sp.pi
x = np.linspace(x0, xf, dim, endpoint=False)
# this is a vector representation of an operator with diagonal matrix
ref = (1-np.exp(-x))**2


def mv(y):
    # multiply this diag matrix by vector
    vv = ref
    return vv*y


LO = sla.LinearOperator(shp, matvec=mv)
(LO+LO).T

# not ever if a matrix was passed
M = sla.aslinearoperator(I)
M.transpose()
```

### Error message:
```
'_CustomLinearOperator' object has no attribute '_transpose'
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by Tokixix**
I've submited possible solution to #8486 by adding _transpose funtion into LinearOperator code. It actualy returns MatrixLinearOperator, but it can be easily transformed. Please review this PR and also the idea. Thanks :)

### CODE REVIEW

**Comment by ewmoore** [comment]
The converts the linear operator to a dense array. A good part of the point
of this interface is that it allows you to work with linear operators
without realizing them as full dense matrices so I think this is probably
not the right way to go.

**Comment by Tokixix** [comment]
Or is there any possible idea how to implement "transpose" functionality without explicit matrix transposition?

**Comment by pv** [comment]
I think implicit cast to dense matrices should not be done here.

However, I think you can add a `_transpose` method to the `*MatrixLinearOperator` so that it works if the matrix is already sparse.

**Comment by pv** [comment]
Thinking a bit more, you can implement transposed linear operator by swapping rmatvec/matvec and complex conjugating the results of matvec/rmatvec/matmat.

For this, you need to add a new _TransposedLinearOperator subclass.

**Comment by pv** [comment]
Continued in gh-9064 (which I just discovered again...)

**Pull request closed without merging**
