### PR TITLE
Deprecate scipy.signal.{bspline, quadratic, cubic}

### LINKED ISSUE #14525: scipy.signal.bspline does not work for integer types
`scipy.signal.bspline` gives zero output for integer types. This also affects quadratic and cubic.

#### Reproducing code example:
An example of an incorrect result
```
>>> from scipy.signal import bspline, quadratic, cubic
>>> bspline(np.array([-3,-2,-1,0,1,2,3]), 6)
array([0, 0, 0, 0, 0, 0, 0])
```
What was expected
```
>>> bspline(np.array([-3,-2,-1,0,1,2,3]).astype(float), 6)
array([2.17013889e-05, 1.56684028e-02, 2.28797743e-01, 5.11024306e-01,
       2.28797743e-01, 1.56684028e-02, 2.17013889e-05])
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.7.0 1.21.1 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by ev-br**
#### Reference issue

supersedes and closes gh-14530, closes gh-14525

#### What does this implement/fix?

Start acting on the roadmap item (https://docs.scipy.org/doc/scipy/dev/roadmap-detailed.html#scipy-roadmap-detailed)

> B-splines: (Relevant functions are bspline, cubic, quadratic, gauss_spline, cspline1d, qspline1d, cspline2d, qspline2d, 
> cspline1d_eval, and spline_filter.) Move the good stuff to interpolate (with appropriate API changes to match how 
> things are done in interpolate), and eliminate any duplication.

There are two sorts of functions above: several do some sort of filtering, and others simply duplicate BSpline.basis_element from scipy.interpolate. This PR does not touch the former, and acts on the latter,  specifically, on the *remove duplication*  part.

Therefore, this PR deprecates `bspline`, `quadratic` and `cubic` functions from scipy.signal, and lists their direct analogs from scipy.interpolate.
The deprecation itself was discussed in https://github.com/scipy/scipy/issues/6730#issuecomment-290368820

None of this is essential for the approaching 1.10 release, so the deprecation messages mention the 1.11 release. If this comes in before the release, will adjust the deprecation message.

#### Additional information

While at it, cherry-pick parts of https://github.com/scipy/scipy/pull/14530 which stalled at fixing a bug with integer arguments, where floats <1 were rounded down to zero.

### CODE REVIEW

**Comment by j-bowhay** [comment]
It would be nice to remove the references to the deprecated functions in the signal processing tutorial https://docs.scipy.org/doc/scipy/tutorial/signal.html

**Comment by ev-br** [comment]
Thanks for the suggestion, done in the last commit. This whole section of the tutorial (or maybe even the whole scipy.signal tutorial, in fact) might be looking for an update, but this is definitely a separate PR material.

**Comment by j-bowhay** [comment]
I have tested this locally and happy with with the warnings etc. The doc build seems to have disappeared, @ev-br can you rerun the ci so that I can check the deprecation stuff is showing up in the docs as expected

**Comment by ev-br** [comment]
Restarted CircleCI

**Review by j-bowhay — APPROVED** [review]
To my eyes this looks good to go

**Comment by rgommers** [comment]
@j-bowhay since you've got commit right now, do you want to do the honors here?

**Comment by j-bowhay** [comment]
Thanks @ev-br and for the reminder @rgommers!

**Pull request merged**
