### PR TITLE
DOC: css adjustment in dark mode and hidden toctree in dev section

### PR DESCRIPTION
**Pull request by tupui**
Related to #18300

Adjust the colour of the card header to use the default text colour:

Screenshot 2023-04-14 at 17 56 09

And while I was building the doc I noticed that we were polluting the toctree when outside of the ref section. So I changed the toctree hiding. I did not notice bad behaviours with this change so I think it's ok.

Screenshot 2023-04-14 at 17 56 43

### CODE REVIEW

**Review by melissawm — APPROVED** [review]
Looks good to me! Maybe @ilayn wants to take a look at the contrast?

**Comment by ilayn** [comment]
Screenshots here are very clear. It was the blue(purple?!) over black with thin narrow characters that are often difficult. But these look quite OK. 

Another difficulty is the bold characters (not from color but from accessibility point of view). Don't know if we can do anything about it. I don't have any near/far sight impairment (still colorblind though 😃) but I do know some people mentioning that in the dark mode. At work we are using these as guidelines and tweaking further for the fontspacings https://www.w3.org/TR/WCAG21/#text-spacing

image

**Comment by tupui** [comment]
Thanks @ilayn for having a look!

I had a look at the bold. This one is from the theme directly. It's set in CSS to be `bolder` instead of `bold`. Apparently they had an issue about that https://github.com/pydata/pydata-sphinx-theme/issues/527

Still, there is a new grant from CZI which is supposed to have a look at the theme and its accessibility. Hopefully they will address such questions 😃

In the meantime, I am happy to make adjustments if you notice anything. (In this case I can make the change if you want.)

**Comment by ilayn** [comment]
The rest is all good from my side.

**Comment by melissawm** [comment]
Should we open a tracking issue with an accessibility wish list?

**Comment by tupui** [comment]
I am hesitant with that as we would ideally not do anything and rely on the theme. But the reality seems to point out that we need solutions for current issues 😅 so sure feel free to open a wish list and we can think about a plan.

**Comment by melissawm** [comment]
Ok - we'll figure that out separately then. Thanks @tupui and @ilayn for reviewing!

**Pull request merged**
