### PR TITLE
Add matrix manipulation functions in _matfuncs.py

### PR DESCRIPTION
**Pull request by muzakkirhussain011**
This commit introduces a comprehensive set of matrix manipulation functions to the codebase, expanding its capabilities significantly. These functions cover a wide range of operations, including

Matrix Transposition (transpose_matrix):

Allows for the transposition of a matrix.
Useful for changing the rows into columns and vice versa.

Matrix Projection (proj_matrix):

Projects one matrix onto another matrix or subspace. Useful for extracting relevant information or components from a matrix.

Matrix Concatenation (concatenate_matrices):

Concatenates matrices along specified axes.
Enables combining matrices to form larger ones.

Matrix Differentiation (matdiff_matrix):

Computes the derivative of a matrix with respect to a scalar variable. Facilitates the analysis of how a matrix changes with respect to a scalar parameter.

Matrix Scaling (scale_matrix):

Scales a matrix by a specified scaling factor.
Allows for resizing and altering the magnitude of matrix elements.

Matrix Trace (trace_matrix):

Calculates the trace of a matrix, which is the sum of its diagonal elements.
Useful for quantifying the cumulative effect of values along the diagonal of a square matrix.
Provides insight into the sum of self-interactions or self-contributions within the matrix, often used in various mathematical and scientific analyses.

Matrix Rotation (rotate_matrix):

Rotates a 2D matrix by a specified angle.
Useful for transforming and reorienting data in a matrix. Each of these functions extends the codebase's functionality, making it more versatile and suitable for a wide range of matrix-related tasks in mathematical and scientific applications.

### CODE REVIEW

**Comment by rkern** [comment]
I invite you to compare this list of functionality with what is already in `scipy.linalg`. Please go through the list and delete the functions that already exist in `scipy.linalg`. Hint: if your implementation is mostly just calling a function in `numpy.linalg`, that function almost certainly exists in `scipy.linalg`.

Once you delete the duplicative functions, then you can make a proposal for the new functionality on the mailing list, which is where discussions that affect the public API need to start.

**Comment by muzakkirhussain011** [comment]
> I invite you to compare this list of functionality with what is already in `scipy.linalg`. Please go through the list and delete the functions that already exist in `scipy.linalg`. Hint: if your implementation is mostly just calling a function in `numpy.linalg`, that function almost certainly exists in `scipy.linalg`.
> 
> Once you delete the duplicative functions, then you can make a proposal for the new functionality on the mailing list, which is where discussions that affect the public API need to start.

Hi @rkern 

Thank you for your feedback and suggestion. I have removed the functions (svd, eigen, norm, solve, kron) that were found to be redundant and readily available in scipy.linalg. Your hint was quite helpful in identifying these duplicative functions.

Best Regards

**Comment by rkern** [comment]
Generally, if your implementation is a simple one-liner using an existing `numpy` and `scipy` function after doing the `asarray()` conversions on the inputs, we're not likely to want to add them as new functions in `scipy`. Delete `scale_matrix`, `concatenate_matrices`, `matrix_rank`, `transpose_matrix`, `trace_matrix`, accordingly.

`matdiff_matrix` has two problems:

1. It's currently buggy and fails to execute.
2. It doesn't compute anything anyone wants to compute. AFAICT, it will return the original matrix, just with accumulated floating point error from doing unnecessary operations. The derivative of the function `f(x) = A*x` is just `A`.

`rotate_matrix` is unlikely to be accepted. At most, we might add a function to represent a 2D rotation from an angle (probably in `scipy.spatial`, see #14711). But we expect people to be able to do the matrix multiplication themselves.

That leaves `matrix_similarity_transform` and `proj_matrix` as a little more than trivial applications of single existing functions, but they are still just one-linears (after the `asarray()` conversions). We have a saying: not every one-liner needs to be in the library. If you want to make a case for each of these, please make your proposal to the mailing list. We're not going to act further on this PR until that discussion happens there. [Please read our documentation on the general criteria on which we decide on new features](http://scipy.github.io/devdocs/dev/core-dev/index.html#deciding-on-new-features) to give an idea of the case that you will need to make for each of these.

I recommend that you edit down this PR description to just include the functions you are proposing, so as not to confuse the new people that might come to this PR from the mailing list discussion.

**Comment by muzakkirhussain011** [comment]
> Generally, if your implementation is a simple one-liner using an existing `numpy` and `scipy` function after doing the `asarray()` conversions on the inputs, we're not likely to want to add them as new functions in `scipy`. Delete `scale_matrix`, `concatenate_matrices`, `matrix_rank`, `transpose_matrix`, `trace_matrix`, accordingly.
> 
> `matdiff_matrix` has two problems:
> 
> 1. It's currently buggy and fails to execute.
> 2. It doesn't compute anything anyone wants to compute. AFAICT, it will return the original matrix, just with accumulated floating point error from doing unnecessary operations. The derivative of the function `f(x) = A*x` is just `A`.
> 
> `rotate_matrix` is unlikely to be accepted. At most, we might add a function to represent a 2D rotation from an angle (probably in `scipy.spatial`, see #14711). But we expect people to be able to do the matrix multiplication themselves.
> 
> That leaves `matrix_similarity_transform` and `proj_matrix` as a little more than trivial applications of single existing functions, but they are still just one-liners (after the `asarray()` conversions). We have a saying: not every one-liner needs to be in the library. If you want to make a case for each of these, please make your proposal to the mailing list. We're not going to act further on this PR until that discussion happens there. [Please read our documentation on the general criteria on which we decide on new features](http://scipy.github.io/devdocs/dev/core-dev/index.html#deciding-on-new-features) to give an idea of the case that you will need to make for each of these.
> 
> I recommend that you edit down this PR description to just include the functions you are proposing, so as not to confuse the new people that might come to this PR from the mailing list discussion.

Hi @rkern ,

Thank you for your feedback and detailed evaluation of the functions in the PR. Your insights are valuable, and I'll proceed to remove the functions that are not suitable for inclusion in scipy as suggested.

I'll also edit the PR description to focus on the functions that I propose for consideration.

Could you please provide more information or a link regarding the mailing list discussion you mentioned? I want to make sure I follow the correct process and guidelines for proposing these functions.

Thanks for your guidance, and I look forward to your response.

Best regards,

**Comment by lucascolley** [comment]
Hi @muzakkirhussain011 , here is the link to the mailing lists https://projects.scipy.org/scipylib/mailing-lists.html. It is 'scipy-dev' that you are looking for.

Also see the 'contributing new code' section of this page http://scipy.github.io/devdocs/dev/hacking.html for more information.

**Pull request closed without merging**
