### PR TITLE
BUG: linalg: use zero scratch arrays in `expm`

### LINKED ISSUE #18086: BUG: `scipy.linalg.expm` generates inconsistent results between runs
### Describe your issue.

For a custom `(400, 400)` matrix , `scipy.linalg.expm` generates inconsistent results between runs. I understand that the documentation mentions for `n>=400`, some approximation will be applied. However, there are just too much differences between runs, potentially causing backward incompatibility. Is there a way to make it deterministic like `scipy.sparse.linalg.expm` and matlab?

The matrix I used is uploaded here: *removed for security reasons*. 

### Reproducing Code Example

```python
import numpy as np
import scipy
data = np.load("laplacian.npy")
scipy.linalg.expm(data)
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
1.10.0 1.23.4 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

### PR DESCRIPTION
**Pull request by ev-br**
#### Reference issue

supersedes and closes gh-19020, closes gh-18086 

#### What does this implement/fix?

The first commit it gh-19020; the second commit zeros out a work array on top of it.

### CODE REVIEW

**Comment by thalassemia** [comment]
I think I've figured out the underlying issue. [The test matrix](https://github.com/scipy/scipy/issues/18086#issuecomment-1453621049) from the bug report causes `pick_pade_structure` to return an `m` of 9. The corresponding `pade_9_UV_calc_*` function is the only one that actually uses `Am[4, :, :]`. This slice normally holds $A^8$ at that point, but we skip this calculation for $n \geq 400$, leaving the random noise from `np.empty`.

Applying the following diff fixed the inconsistency for me even after reverting back to `np.empty`:
```diff
diff --git a/scipy/linalg/_matfuncs_expm.pyx.in b/scipy/linalg/_matfuncs_expm.pyx.in
index 429a180fa..0dfded12d 100644
--- a/scipy/linalg/_matfuncs_expm.pyx.in
+++ b/scipy/linalg/_matfuncs_expm.pyx.in
@@ -342,6 +342,7 @@ cdef void pade_9_UV_calc_{{ pfx }}({{ tname }}[:, :, ::]Am, int n) noexcept nogi
     cdef int i, info, n2 = n*n, int_one = 1
     cdef {{ tname }} one = 1.0, zero = 0.0, neg_one = -1.0
     cdef {{if pfx in ['s', 'c']}}float{{else}}double{{endif}} two = 2.0
+    cdef char* cN = 'N'
 
     if not (work and ipiv):
         raise MemoryError('Internal function "pade_9_UV_calc" failed to allocate memory.')
@@ -357,6 +358,11 @@ cdef void pade_9_UV_calc_{{ pfx }}({{ tname }}[:, :, ::]Am, int n) noexcept nogi
         b[7] = 3960.
         b[8] = 90.
 
+        # Compute this in case we skipped it before (n >= 400)
+        if n >= 400:
+            {{ pfx }}gemm(cN, cN, &n, &n, &n, &one, &Am[2, 0, 0], &n,
+                &Am[2, 0, 0], &n, &zero, &Am[4, 0, 0], &n)
```

As an aside, I did not find any tests for `expm` when $n \geq 400$ in our current suite. Maybe we could turn the bug report into a test case?

**Comment by ev-br** [comment]
Wow. 
Is your patch above on top of main, or on top of this PR @thalassemia ?

**Comment by thalassemia** [comment]
It was on top of this PR.

**Comment by ev-br** [comment]
Great! 
Want to send a PR with your fix on top? I'll happily close this PR in favor of yours.

**Comment by thalassemia** [comment]
Just put up a separate PR. Took me a while to figure out how to set up a test matrix for CI.

**Comment by ev-br** [comment]
closing in favor of gh-20259

**Pull request closed without merging**
