### PR TITLE
improve doc of ode.get_return_code

### PR DESCRIPTION
**Pull request by anubhavp28**
Resolving #8526, add what different return codes mean for different integrators. Improving the documentation of ode.get_return_code.

### CODE REVIEW

**Comment by anubhavp28** [comment]
Hey @nmayorov,
I have added positive codes for vode & zvode, but I am little clueless regarding why the formatting is poor - the different html tables generated by Sphinx have different width for the first column.

**Comment by nmayorov** [comment]
Never mind "bad formatting", it's good.

Please do the following:

1. Use "Computation successful" or "Integration successful" uniformly.
2. Move ending triple quote to a new line.
3. Rebase it to a single commit in the format "DOC: integrate: improve doc of ode.get_return_code"

**Comment by anubhavp28** [comment]
@nmayorov If I am not wrong, the checks are failing because of AssertionError in scipy/sparse/linalg/isolve/tests/test_iterative.py, I guess the problem resides in the master branch. Can you guide me, how should I proceed?

**Comment by nmayorov** [comment]
Looks like it. Your changes are definitely unrelated to that. I think it's good to be merged.

**Pull request merged**
