### PR TITLE
DOC: optimize.root_scalar: improve parametrization of methods

### LINKED ISSUE #16796: DOC: Method "bisect" for root_scalar lacks correct argument list
### Describe your issue.

In the [documentation](https://docs.scipy.org/doc/scipy/reference/optimize.root_scalar-bisect.html#optimize-root-scalar-bisect) for `root_scalar` with `method='bisect'`, there is no mention of having to use the `bracket` argument. This is also the case for other methods, such as `brentq`, which take a `bracket` argument not shown by the documentation sub-page. 

### Reproducing Code Example

```python
NA
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

SciPy 1.9.0

### PR DESCRIPTION
**Pull request by asberk**
Add correct argument list and Returns information for method="brentq" and method="bisect"

#### Reference issue

Closes #16796 

#### What does this implement/fix?

Add correct argument list and Return information in docstring for `scipy.optimize.root_scalar(method="brentq")` and `scipy.optimize.root_scalar(method="bisect")`

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Thank you for the PR @asberk!

I am not sure about adding the full doc as it duplicates what we have for the optimizers themselves. Instead I would add a link.

For adding `bracket` I agree, and I think we also need to update `doc/source/scipyoptdoc.py` to have the proper signature (`maxiter` is missing too and I there is also a rendering bug with the underlying of `Options`). @mdhaber seems like you edited this file recently. Is this the correct approach?

Also I would update the main docstring of `root_scalar` to note which function needs what. Maybe a table would be simpler.

**Comment by asberk** [comment]
Thanks @tupui — good ideas, I will make the updates. 
I see that the Main Lint is failing, but I'm not sure how to get the workflow to reveal a descriptive error message to me (I think Build Log 19 is not displayed when I click the relevant hyperlinked text). Help/input fixing this is appreciated — and probably necessary.

**Comment by tupui** [comment]
For the linter, here is the link https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=19824&view=logs&j=fdd89725-f657-5341-7d77-3c5c44c4f5b6&t=325fc03e-e0b9-5339-adaf-099a49a14600

```
scipy/optimize/_root_scalar.py:303:80: E501 line too long (80 > 79 characters)
scipy/optimize/_root_scalar.py:319:80: E501 line too long (80 > 79 characters)
scipy/optimize/_root_scalar.py:323:80: E501 line too long (80 > 79 characters)
scipy/optimize/_root_scalar.py:501:80: E501 line too long (80 > 79 characters)
scipy/optimize/_root_scalar.py:513:80: E501 line too long (80 > 79 characters)
scipy/optimize/_root_scalar.py:517:80: E501 line too long (80 > 79 characters)
```

E.g. for the first line, it's telling you that L303 you have 80 chars on the line which is above 79. You can check this locally if you run: `python dev.py lint`

**Comment by asberk** [comment]
Thanks @tupui I now understand that `scipyoptdoc.py` might need some work - indeed, the options aren't formatting correctly. This one might take me a little longer but I'll try to make (slow) progress. In the meantime, I've added a candidate table that looks nice in HTML format, but not in plaintext. Was this roughly what you had in mind?

**Comment by tupui** [comment]
Thanks for the update. I am not sure about the format you used though as it's not very readable in plain text, which is important for maintenance. Instead please have a look for instance at how we did it in `_minimize.py`

**Comment by tupui** [comment]
Nice table (linter will fail but it's fine as we cannot do without it.). I will let it render in the doc and check the output there.

**Comment by tupui** [comment]
FYI I am playing with this locally to see why it's failing. I suppose it has to do with the way we add the custom doc. I will push some changes on the branch soon to fix this.

**Comment by tupui** [comment]
I think I got it. We cannot have anything else in these doc functions basically as they will not render (and other links will fail).

TBH I think this whole thing is a not ideal design. Complicated and very much prone to errors like we had here. And we still have issues with signatures being wrong. IMHO we should just refer to the underlying function instead of trying to do that. We have the same issue with the `minimize` function.

Anyway this is for another time and I will merge this once CI is happy.

@andyfaff are we open to changing this logic around the doc?

**Comment by asberk** [comment]
I cast my vote for linking to `zeros.brentq`, `zeros.bisect` etc. in `root_scalar`. Only while working on this (through jumping around source code) did I realize that (a) `zeros` exists and (b) these are the underlying functions. 😅

**Review by tupui — APPROVED** [review]
Alright LGTM now, thanks again @asberk. This is a great improvement of the doc!

**Pull request merged**
