### PR TITLE
ENH: added the spectral 2-norm to _norm.py

### LINKED ISSUE #7268: scipy.sparse.linalg.norm does not implement spectral norm
It seems that this would be very easy to implement with a call to `svds` since the spectral norm is just the largest singular value. Are there any issues with this approach?

### PR DESCRIPTION
**Pull request by lobpcg**
Added the spectral norm

#### Reference issue
Closes gh-7268

#### What does this implement/fix?
Rejuvenates https://github.com/scipy/scipy/pull/8472

### CODE REVIEW

**Comment by lobpcg** [comment]
The failure appears in many PRs and is unrelated to this PR:
2022-08-08T01:25:28.4346259Z scipy.sparse.linalg.svds
2022-08-08T01:25:28.4346816Z ------------------------
2022-08-08T01:25:28.4347071Z 
2022-08-08T01:25:28.4347787Z File "build/testenv/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 239, in svds
2022-08-08T01:25:28.4348368Z Failed example:
2022-08-08T01:25:28.4348770Z     (np.allclose(s3, s) and
2022-08-08T01:25:28.4349216Z      np.allclose(np.abs(u3), np.abs(u.toarray())) and
2022-08-08T01:25:28.4349730Z      np.allclose(np.abs(vT3), np.abs(vT.toarray())))
2022-08-08T01:25:28.4350148Z Expected:
2022-08-08T01:25:28.4350501Z     True
2022-08-08T01:25:28.4350824Z Got:
2022-08-08T01:25:28.4351252Z     False

**Comment by lobpcg** [comment]
This PR is ready for review & merge

**Comment by lobpcg** [comment]
This PR is ready for review & merge, please. The new failures after merge main are unrelated to this PR

**Comment by lobpcg** [comment]
This PR is ready for review & merge, please.

**Review by tylerjereddy — APPROVED** [review]
This LGTM, admittedly outside my expertise.

I tested against a rust crate with similar functionality, after compensating for vector vs. matrix offerings, and seems to match up well (I did a few other permutations):

```python
from scipy.sparse import *
import numpy as np
from scipy.sparse.linalg import norm

a = np.array([[1.0, 0, 2.0, 0, 3.0],
              [0.0, 0, 0.0, 0, 0.0]])
b = csr_matrix(a, dtype=np.float64)
print("norm(b, 2):", norm(b, 2))
```

```rust
fn main() {
    use sprs::{CsVec};
    let x = CsVec::new(5, vec![0, 2, 4], vec![1., 2., 3.]);
    println!("{:?}", x);
    let result = x.norm(2.0);
    println!("{:?}", result);
}

```

```
norm(b, 2): 3.7416573867739413
```

```
CsVecBase { dim: 5, indices: [0, 2, 4], data: [1.0, 2.0, 3.0] }
3.7416573867739413
```

**Pull request merged**
