### PR TITLE
Test multibuild modifications

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by andyfaff** [comment]
What does the different branch do?

**Comment by xoviat** [comment]
Nothing. Last time I merged something the builds broke, so I wanted to test it with this PR fist.

**Comment by andyfaff** [comment]
It's possible to enable travis builds for your fork. Thus, when you push to a branch on your fork it runs just that. It's not necessary to open a scipy PR to see if modifications break things.

**Comment by xoviat** [comment]
Good point.

**Pull request closed without merging**
