### PR TITLE
ENH: special: add ufuncs for amos

### LINKED ISSUE #20385: MAINT: special version hex cleanup
Just poking around after gh-20373, I think this can be removed now from `scipy/special/ufunc.h`:

```
#if (PY_VERSION_HEX < 0x030a00f0)
// This function is standard in Python >=3.10, we just add it here for convenience.
inline int PyModule_AddObjectRef(PyObject *module, const char *name, PyObject *value) {
    Py_INCREF(value);
    return PyModule_AddObject(module, name, value);
}
#endif
```

Not sure if the C++ stuff just makes it all obsolete anyway. That's the last remaining usage of `PY_VERSION_HEX` we have.

### PR DESCRIPTION
**Pull request by izaid**
This PR adds ufuncs for the amos functions, using the new-style machinery. Also closes gh-20385.

cc @steppi

### CODE REVIEW

**Comment by steppi** [comment]
Thanks @izaid! If it's not too tough, can you incorporate the changes I made to `amos.h`  and `amos/amos.h` in the cephes PR:  https://github.com/scipy/scipy/pull/20390/files#diff-856882a37611b3aee9222818d9827a1c3f7b8a34cd0ec8aac40b61f3a7acd3f7).

Key points are
1. Using `set_error` instead of `sf_error` in `amos.h`
2. Adding #pragma once to `amos/amos.h`
3. Making all of the functions in these two headers inline
4. Using an `amos` namespace in `amos/amos.h` instead of prefixing all functions with `amos_`.
(I also made all of the `static const` arrays `constexpr` but I'm not sure how useful that actually is, so it's a judgement call if that's actually a good idea).

This way I won't have to worry about having tricky merge conflicts to resolve, and can just base things on your version of these files directly in the cephes PR.

**Comment by izaid** [comment]
I have also dealt with https://github.com/scipy/scipy/issues/20385 in this PR.

**Comment by izaid** [comment]
> Thanks @izaid! If it's not too tough, can you incorporate the changes I made to `amos.h` and `amos/amos.h` in the cephes PR: https://github.com/scipy/scipy/pull/20390/files#diff-856882a37611b3aee9222818d9827a1c3f7b8a34cd0ec8aac40b61f3a7acd3f7).
> 
> Key points are
> 
>     1. Using `set_error` instead of `sf_error` in `amos.h`
> 
>     2. Adding #pragma once to `amos/amos.h`
> 
>     3. Making all of the functions in these two headers inline
> 
>     4. Using an `amos` namespace in `amos/amos.h` instead of prefixing all functions with `amos_`.
> 
>     5. (I also made all of the `static const` arrays `constexpr` but I'm not sure how useful that actually is, so it's a judgement call if that's actually a good idea).
> 
> 
> This way I won't have to worry about having tricky merge conflicts to resolve, and can just base things on your version of these files directly in the cephes PR.

@steppi Done! Let me know if there's something else that would help, otherwise ready for review.

**Review by steppi — APPROVED** [review]
Thanks @izaid. Looks good to me and tests are passing. Let's get this in.

**Pull request merged**
