### PR TITLE
MAINT: 1.15.0rc1 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
With the concurrent release of NumPy `2.2.0` and the unusually large volume of changes in this release, some of the backports added here are a bit debatable since we don't normally backport improvements, but I think some of the cases are probably "ok" since they cover substantial gaps in new features that were still burning hot near the branch point. We should probably draw the line on those at RC1 though--I think I'd almost certainly deny an `ENH` backport at RC2.

TODO:

- [x] confirm regular CI is passing
- [x] confirm full wheel build CI is passing
- [x] there are two doc build warnings/issue with `scipy.stats` locally, so I'm expecting those to show up here, and indeed `stats` is the subpackage that is seeing the most "debatable" backport activity here because of the flurry of activity around the branch point with the new dist infra
- [x] Some backport PRs have not been merged yet, including some potentially important `stats` documentation?
  - gh-22025
  - ~gh-22043~
- [x] update release notes/lists again after all the backports

Misc. changes (so far):
1. Increase cirrus CI timeout for wheel builds, was a problem in the last backport PR I did on the release branch

Backports included (so far -- see bold text where I had to resolve merge conflicts manually):

1. gh-22059
2. gh-22058
3. gh-22050
4. gh-22048
5. gh-22040
6. gh-22037 -- **caution: merge conflicts resolved manually**
7. gh-22036
8. gh-22033
9. gh-22030
10. gh-22027 -- **caution: merge conflicts resolved manually**
11. gh-22026
12. gh-20908
13. gh-22043

### CODE REVIEW

**Comment by mdhaber** [comment]
Yes, gh-22025 is just documentation (transition guide), but it would be very helpful for it to accompany all the new features. I think it will be exclusively documentation, so not much risk.

**Comment by tylerjereddy** [comment]
The regular CI was all passing, so I've pushed in an empty commit to probe the wheel builds.

**Comment by rgommers** [comment]
Looks like a new segfault in the `cp311-macosx x86_64 accelerate 14.0` job ([log](https://github.com/scipy/scipy/actions/runs/12309368863/job/34356278535?pr=22067)):
```
optimize/tests/test_minpack.py ....................................Fatal Python error: Segmentation fault
  
  Current thread 0x00007ff8584d4940 (most recent call first):
    File "/private/var/folders/x4/dc0wnrqs60v8cfdj3vx06s1h0000gn/T/cibw-run-r3jk0biw/cp311-macosx_x86_64/venv-test-x86_64/lib/python3.11/site-packages/scipy/optimize/_minpack_py.py", line 438 in leastsq
    File "/private/var/folders/x4/dc0wnrqs60v8cfdj3vx06s1h0000gn/T/cibw-run-r3jk0biw/cp311-macosx_x86_64/venv-test-x86_64/lib/python3.11/site-packages/scipy/optimize/tests/test_minpack.py", line 378 in test_float32
    File "/private/var/folders/x4/dc0wnrqs60v8cfdj3vx06s1h0000gn/T/cibw-run-r3jk0biw/cp311-macosx_x86_64/venv-test-x86_64/lib/python3.11/site-packages/_pytest/python.py", line 159 in pytest_pyfunc_call
```
That's in the regression test for gh-1447, which has been fixed for a decade so that doesn't look related. Unclear if it's a very rare problem or something broke recently - re-running the wheel build.

**Comment by rgommers** [comment]
I just lightly browsed the PR list and the diff - and LGTM.

**Comment by tylerjereddy** [comment]
The full CI, including wheels, is now passing. I'm inclined to go for an RC1 today and I've put aside the time to do it, and it is well past due.

I merged the one minor/outstanding `sparse` PR and for Matt's `stats` docs improvements that is safe between RC1 and RC2.

I'll probably push in one more commit with regular CI only just for the last backport from `sparse` and to update the relnotes/lists following all the backports.

**Comment by tylerjereddy** [comment]
Alright, let's get the release process going, in it goes.

**Pull request merged**
