### PR TITLE
FIX: correctly compute group_delay for complex-coefficient TFs

### LINKED ISSUE #19586: BUG: scipy.signal.group_delay not correct for complex coefficients
### Describe your issue.

The group delay is not computed correctly for complex coefficients. For example, a first order all-pass filter with complex coefficients given as $$H(z) = \frac{1 - r e^{j \omega_n}z^{-1}}{-r + e^{-j\omega_n}z^{-1}}$$ should show a group delay as a single peak at $\omega = \omega_n$, but instead shows two peaks at $\omega = \pm \omega_n$, (as if it were forced to be real coefficients with a complex conjugate pole zero pair).

With $r=0.7$ and $\omega_n = 1.5$, we should get the following group delay:

  
image

However, instead I am getting the following incorrect result:

image

 

### Reproducing Code Example

```python
import numpy as np
import scipy.signal as sig
import matplotlib.pyplot as plt

r = 0.7
angle = 1.5
a = [1, -r * np.exp(1j*angle)]
b = [-r * np.exp(-1j*angle), 1]
w, gd = sig.group_delay((b, a), whole=True)
plt.figure()
plt.plot(w, gd)


# The following creates the Group Delay plot correctly:

import scipy.fft as fft
#impulse response
nsamps= 512
impulse = np.zeros(nsamps)
impulse[0]=1
imp_response = sig.lfilter(b, a, impulse)
num = fft.fft(np.arange(nsamps)*imp_response)
den = fft.fft(imp_response)
gd = fft.fftshift(np.real(num/den)))

# alternatively the following gives a similar correct result
w, H = sig.freqz(b, a, 512, whole=True)
wd = w[1:] - np.pi  + (w[1]-w[0])/2
gd = -np.diff(np.angle(H))/np.diff(w)
plt.figure()
plt.plot(wd, fft.fftshift(gd))
```

### Error message

```shell
There is no error message.
```

### SciPy/NumPy/Python version and system information

```shell
In [9]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.10.1 1.23.4 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\lib']
    include_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\lib']
    include_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\include']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/bosch/miniconda3/envs/test\\Library\\include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX
    not found = AVX512_CNL,AVX512_ICL
```

### PR DESCRIPTION
**Pull request by roryyorke**
Added unit test for complex-coefficient TF case.

Added second reference for algorithm.

#### Reference issue

Closes gh-19586.

#### What does this implement/fix?

Correctly calculate group-delay; see https://ccrma.stanford.edu/~jos/filters/filters-citation.html

Notation in implementation and reference above is similar enough that there is likely  common ancestry.

#### Additional information

I didn't know what nulp to set for the unit test, so it's arbitrarily "passing-value-on-my-computer-plus-one".  Perhaps `assert_array_almost_equal` would be better?

### CODE REVIEW

**Comment by lucascolley** [comment]
@roryyorke yep, that CI failure was unrelated and fixed recently, merge main and it should go away

**Comment by tylerjereddy** [comment]
Honestly, with just a new test added and no old tests changed this looks relatively safe, but a `signal` dev review would be sensible first.

I'll bump the milsetone given that I'm about to branch for `1.13.0`, apologies.

**Comment by j-bowhay** [comment]
@DietBru maybe you would be able to have a quick look here?

**Comment by DietBru** [comment]
Looks good for me to go (I checked the URL and verified the fix by checking the group delay of the transfer function in `test_complex_coef`  with `freqz`).

**Review by j-bowhay — APPROVED** [review]
Thanks for the review @DietBru, let's get this in and thanks for the fix @roryyorke

**Comment by j-bowhay** [comment]
Agh sorry picked up submodule changes while resolving merge conflicts, I will resolve

**Comment by rgommers** [comment]
@roryyorke FYI: the test tolerance is bumped in gh-20355

**Pull request merged**
