### PR TITLE
DOC: Show probability density functions as math

### PR DESCRIPTION
**Pull request by MartinThoma**
Follow-up for pull request #7756 /
commit c8f91ae303af8487f702c3a3266d5eb59b82eefa

For LaTeX, the following rules were decided:

* No \left ( ... \right )
* \le, \ge, \ne and not \leq, \geq, \neq
* No \cdot for multiplication (just ommit it)
* No grouping {...}^x
* exp vs e: https://tex.stackexchange.com/a/254786/5645

All of this aims at making the source code easy to read
while still having a nice rendered formula

The pseudocode was kept in the comments for easier
maintainability.

### CODE REVIEW

**Comment by rgommers** [comment]
Some issues:

    SyntaxError: invalid escape sequence \e

and 

    Docstring contains a non-printable character '\x0c'! Maybe forgot r"""?

Using ``r"""`` for all docstrings should fix that.

**Comment by rgommers** [comment]
Thanks for implementing this so quickly!

**Comment by MartinThoma** [comment]
> Using `r"""` for all docstrings should fix that.

argh, I always forget that. I wonder why the Sublime Plugin "Python Fake8 lint" does not mention it ... I think it did a while ago.

> Thanks for implementing this so quickly!

Sure, no problem :-)

**Comment by rgommers** [comment]
LGTM, merged. Thanks @MartinThoma

**Pull request merged**
