### PR TITLE
ENH: linalg: Adding wrapper for potentially useful LAPACK function *lasd4.

### PR DESCRIPTION
**Pull request by AlexGrig**
ENH: linalg: Adding wrapper for potentially useful LAPACK function *d…
…lasd4.

This function computes the singular values of the diagonal matrix
augmented by one extra column (see LAPACK documentation).
This functionality is used in SVD computation, but may be useful
for other purposes as well.

### CODE REVIEW

**Comment by argriffing** [comment]
@AlexGrig Thanks for working on this.  Did you mean to include the commits related to least squares in this PR?

**Comment by argriffing** [comment]
The tests are failing on python 3 because of `xrange`.  If you want to use it instead of `range` then you will need to use the compatibility function
`from scipy._lib.six import xrange`

**Comment by ev-br** [comment]
Can you comment on the relation between your three PRs? gh-4478 and gh-4489 seem to contain same or very similar commits

**Comment by AlexGrig** [comment]
Hi, Evgeni

The PR  gh-4478 includes new wrappers of the LAPACK functions. The PR gh-4489 includes the modification of `linalg.lstsq` function to use theses extra LAPACK functions. So, basically, they both are parts of the same functionality. I did two PRs because it was suggested in scipy-dev mailing list.
Also, the gh-4489 includes everything from gh-4478, because I thought that if they are merged in order, then it is easier

**Comment by ev-br** [comment]
Thanks for the explanation.

It's best to keep PRs focused, I'd say. If thus one does not depend on #4478 and #4489, those commits better not be here --- unless there is bad merge conflict between them.

What is your plan regarding *lasd4, is it a part of bigger picture?

**Comment by AlexGrig** [comment]
I have implemented the "SVD Update" algorithm which updates the SVD of the matrix if one new row (or column) is attached to it. The algorithm works good, and faster than computing SVD from scratch, however I am not sure that it is worth adding this into SciPy. It might be too specific for SciPy.

Anyway, there I used this function "*lasd4", so I thought it might be useful for others as well. So, there are no special plans for "*lasd4" - just useful wrapper and that is it.

**Comment by argriffing** [comment]
> I did two PRs because it was suggested in scipy-dev mailing list.

If you are referring to the suggestion by @rgommers

> I actually suggest to split it into 2 PRs: one that
wraps the LAPACK functions (which is quick to review), and one for the
change to lstsq which requires more careful review and testing.

then I think the idea is to first submit a single PR that wraps the LAPACK functions, maybe with some tests.  Ideally this could be reviewed and merged quickly by someone who understands f2py, because it would not be controversial.  Then after this has been reviewed and merged, you could submit a second PR which changes the behavior and possibly the interface of the scipy least squares solver.  This second PR could require more discussion depending on how much it changes the interface.  These two PRs would not share any commits between them.

**Comment by ev-br** [comment]
Regarding whether rank-one update of an SVD is or is not within scope of scipy --- I personally think it very well might be. It could parallel/complement low-rank updates of a QR decomposition, https://github.com/scipy/scipy/pull/4249
Maybe @ewmoore could weigh in?

**Comment by ewmoore** [comment]
I think it would probably be in scope and a nice addition.  It seems to me
to be the kind of lower-level, general functionality that we should be
providing.

**Comment by AlexGrig** [comment]
To @argriffing: If they do not share any commits how then tests for `linalg.lstsq` work in the second PR?
Tests require LAPACK wrappers that is why the second PR #4489 includes the first PR #4478. Am I correct here?

And I will make this PR independent of the other two.
Regarding the SVD-update I can try to submit it also. I can look as an example to QR-update which was mentioned before.

**Comment by argriffing** [comment]
@AlexGrig PRs generally do not share commits between each other.  When I talk about the 'commits in a PR' I'm referring to the listing of new commits.  For example, this PR currently has 14 commits.  I don't know the best way to contribute a bunch of dependent PRs; here are a couple ways I've seen, and maybe people more experienced with collaborative development would have other suggestions:

1) Contribute one PR, wait for it to be reviewed and merged into the scipy development branch, then contribute a new PR based on the updated scipy development branch.  The listing of the new commits within the second PR will not include the commits listed in the first PR, even though the new PR uses the code that these earlier commits have introduced into the scipy development branch.

2) Bundle all of the work into a single huge PR.

These both have drawbacks.  For the first method, if the review cycle takes months then it could easily take a year for a few dependent PRs to be merged.  The second method could cause delay if the huge PR is too intimidating to reviewers, or if one part is questioned then the entire PR could stall.

**Comment by pv** [comment]
I think sometimes we have done just similarly as here (?), where a PR
depending on another includes the commits of the other. You'd just need
to indicate in the text which of the commits are new here.
.
When the first PR is merged, the second one may need a rebase, but this
usually does not require significant work.

**Comment by argriffing** [comment]
@pv Thanks, that is helpful.  Sorry for giving misleading advice to the contributors.  If the original PR by @AlexGrig is merged and then he rebases this PR on scipy master, will some of the 14 commits be removed from the list that github shows on this PR if they duplicate the work that will have been merged?

**Comment by pv** [comment]
Yes, they will "disappear" here, assuming they have not been modified (= have the same commit ids).

**Comment by AlexGrig** [comment]
@argriffing Since this PR is actually independent from the other two, I am going to completely renew this PR. I am going to include only the modifications which are unique for this `*lasd4` function and get rid of all the commits from the PRs #4478 and #4489. Sorry for this confusion )

**Comment by argriffing** [comment]
This has a test failure in only the Python 3.4 TravisCI configuration.

```
======================================================================
ERROR: test_sing_val_update (test_lapack.TestDlasd4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python3.4/site-packages/scipy/linalg/tests/test_lapack.py", line 161, in test_sing_val_update
    res = lasd4(i, sgm, mvc)
_flapack.error: (i>=0 && i<=(shape(d,0)-1)) failed for 1st argument i: dlasd4:i=0
```

**Comment by ev-br** [comment]
> This has a test failure in only the Python 3.4 TravisCI configuration.

Which might be indicative of a missing depend attribute. I think I needs a `depend(d)` qualifier.

**Comment by ev-br** [comment]
Am adding the needs-work label because of the py3.4 failure.

**Comment by AlexGrig** [comment]
Hi,
I have added this missing dependency Evgeni has pointed out. No errors in Travis. Seems that is was the reason.

**Comment by ev-br** [comment]
LGTM.

**Comment by ewmoore** [comment]
LGTM, merging.

**Pull request merged**
