### PR TITLE
DOC: remove deprecated functions from refguide

### PR DESCRIPTION
**Pull request by tupui**
This should fix an oversight from #16265

Not 100% sure this is what should be done here (locally it fixes the ref guide check). But makes sense to not advertise this in the doc.

### CODE REVIEW

**Comment by ev-br** [comment]
I think there are some more like this (refguide-check CI job will tell if what I saw in some other PR was a fluke or not):

```
===========
scipy.stats
===========

Non-deprecated objects in __all__: 264
Objects in refguide: 259

Deprecated objects in refguide::

    NumericalInverseHermite
    dirichlet
```

**Comment by tupui** [comment]
Yes we can combine these here 👍

**Comment by tupui** [comment]
What I did is correct right? I shall just do the same for other functions? (I have the commit ready)

**Comment by ev-br** [comment]
> What I did is correct right? I shall just do the same for other functions? (I have the commit ready)

I think so, yes. Refguide-check (the original part of it) checks consistency of, well, refguide (module doc string listings) and `__all__` dicts, and that deprecated items are not listed in the refguide.

**Comment by tupui** [comment]
mmm CircleCI seems to have some downtime.

**Comment by tupui** [comment]
Ok an hopefully this new commit will fix the remaining issues with doc. It's "dangerous" to have links to things we might remove in the release notes.

Also I am seeing another ref guide check but unrelated.

```
File "build/testenv/lib/python3.9/site-packages/scipy/sparse/linalg/_isolve/iterative.py", line 62, in bicgstab
Failed example:
    np.allclose(A.dot(x), b)
Expected:
    True
Got:
    False
```

Do you know something about this one @ev-br?

**Comment by ev-br** [comment]
bicgstab is an intermittent one, cf https://github.com/scipy/scipy/pull/16082#issuecomment-1114052991

**Comment by h-vetinari** [comment]
> bicgstab is an intermittent one, cf [#16082 (comment)](https://github.com/scipy/scipy/pull/16082#issuecomment-1114052991)

I commented [here](https://github.com/scipy/scipy/pull/16257#issuecomment-1135992805) that:
> The [bicgstab] doctest failure is unrelated; I have a suspicion it might be a variant of [this](https://github.com/scipy/scipy/issues/15533#issuecomment-1135990584).

**Comment by tupui** [comment]
@ev-br CI is green.

**Comment by ev-br** [comment]
Thanks Pamphile!

**Pull request merged**
