### PR TITLE
MAINT: linalg: add `const` to Cython function signatures

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Reference issue
Towards gh-20196

### CODE REVIEW

**Comment by czgdp1807** [comment]
```
_________________ Test64Bit.test_no_64[TestDIA-test_add_sub] __________________
[gw1] win32 -- Python 3.12.3 C:\hostedtoolcache\windows\Python\3.12.3\x64\python.exe
Test passed but took too long to run: Duration 1.0013048000000708s > 1.0s
```

The time difference is not too much I think. A re-run can make the tests pass but I think we can increase the time limit to say `1.1`s. Might be because of some noise that it took slightly larger.

**Comment by rgommers** [comment]
> The time difference is not too much I think. A re-run can make the tests pass but I think we can increase the time limit to say `1.1`s. Might be because of some noise that it took slightly larger.

If you see these, don't worry about making them pass. Please add them to gh-20806 instead.

**Review by rgommers — APPROVED** [review]
Thanks @czgdp1807. These all look correct to me. 

I'm not going to check if they all actually fix bugs (the change is an improvement either way); the correctness is clear from reading the code. That said, let me record that I did do a spot check for this first PR with:
```diff
diff --git a/scipy/linalg/tests/test_solve_toeplitz.py b/scipy/linalg/tests/test_solve_toeplitz.py
index c078235e92..31b288bb13 100644
--- a/scipy/linalg/tests/test_solve_toeplitz.py
+++ b/scipy/linalg/tests/test_solve_toeplitz.py
@@ -93,6 +93,7 @@ def test_reflection_coeffs():
 
     y_d_concat = np.concatenate((y_d[-2:0:-1], y_d[:-1]))
     y_z_concat = np.concatenate((y_z[-2:0:-1].conj(), y_z[:-1]))
+    y_z_concat.flags.writeable = False
     _, ref_d = levinson(y_d_concat, b=y_d[1:])
     _, ref_z = levinson(y_z_concat, b=y_z[1:])
```
and I confirmed that that indeed yields a test failure on `main` and is fixed by this PR:
```
_solve_toeplitz.pyx:14: in scipy.linalg._solve_toeplitz.levinson
    ???
<stringsource>:663: in View.MemoryView.memoryview_cwrapper
    ???
<stringsource>:353: in View.MemoryView.memoryview.__cinit__
    ???
E   ValueError: buffer source array is read-only
```
So that's at least one potential bug report avoided. These are easy wins.

**Comment by mdhaber** [comment]
> If you see these, don't worry about making them pass. Please add them to gh-20806 instead.

That test is already on [my list](https://github.com/scipy/scipy/issues/20806#issuecomment-2135842449).

**Pull request merged**
