### PR TITLE
ENH: special: add a real dispatch for `wrightomega`

### LINKED ISSUE #10596: Adding Wrightomega real dispatch
This issue relates to #2851 #6653 for adding the Wright omega function into scipy.special. 

The original implementation described in ACM TOMS Algorithm 917: Complex Double-Precision Evaluation of the Wright ω Function [http://dx.doi.org/10.1145/2168773.2168779](http://dx.doi.org/10.1145/2168773.2168779) with code available here: [http://calgo.acm.org/917.zip](http://calgo.acm.org/917.zip).

At the time we wrote this paper, we were more interested in evaluation over the complex plane, and not necessarily the behavior on the real axis. However, since then it seems clear that there really should be a real dispatch of the Wright ω function.

To that end, I made some improvements for this purpose, and propose the attached algorithm for evaluation over the reals.

As mentioned in the first post of  #6653, we really do need to avoid the overflow introduced by the z*z*z term in the series about infinity. As it turns out, we actually only need the first two terms (x-log(x)+log(x)/x) in the series about infinity on the real axis, and we can avoid the overflow problem. The same could probably be done for the complex code, but it would need testing for the accuracy.

Similarly, we need only the first term (exp(x)) of the series about negative infinity, and this is good enough on (-inf,-2] with two iterations of the Fritsch, Schafer, Crowley (FSC) iteration.

For the remaining region (-2,1] we only need a low accuracy approximation, and I suggest exp(2/3*(x-1)) which is continuous with respect to the other two series (not the derivatives, obviously) and is good enough to obtain double precision accuracy in two iterations of FSC.

I attach my implementation of the real Wright omega function, if someone with more knowledge of integrating into scipy can work this in, I would appreciate it (especially since the complex implementation seemed to have many issues with the build system).

Regards,
[wright_real_dispatch.txt](https://github.com/scipy/scipy/files/3468516/wright_real_dispatch.txt)

Piers Lawrence

### PR DESCRIPTION
**Pull request by person142**
#### Reference issue

Closes gh-10596.

#### What does this implement/fix?

A real dispatch is added to `special.wrightomega`.

#### Additional information

This is the algorithm provided by @pierslawrence in gh-10596 with one modification.

For very large `x` the FSC iteration can overflow causing NaN to be returned. For those large values, however, the initial guess of `x - log(x) + log(x) / x` is already sufficiently accurate, so we can just return the initial guess. A bit of experimenting (see `_precompute/wrightomega.py`) shows that a crossover of `x = 1e20` works fine. @pierslawrence what do you think?

### CODE REVIEW

**Comment by pierslawrence** [comment]
Thanks Josh @person142 I think that sounds ideal for the crossover point. The series about infinity should be accurate out there.

There should actually be a point where you only need the `x` term, and it seems 1e20 is beyond that point (i.e. `x-log(x)=x` in floating point) so these two other terms are not necessary. But it is neither here not there.

I didn't check the underflow behavior as x goes to negative infinity. I suspect there might not be any problems, but wanted to be sure.

**Comment by person142** [comment]
> There should actually be a point where you only need the x term, and it seems 1e20 is beyond that point (i.e. x-log(x)=x in floating point) so these two other terms are not necessary.

Ah thanks for pointing that out, I will update.

> I didn't check the underflow behavior as x goes to negative infinity. I suspect there might not be any problems, but wanted to be sure.

At first glance it seems fine (large negative `x` return the expected `0` in the tests), but I didn't test the exact region where underflow first occurs very carefully. I should probably add a test for that.

**Comment by pierslawrence** [comment]
> At first glance it seems fine (large negative `x` return the expected `0` in the tests), but I didn't test the exact region where underflow first occurs very carefully. I should probably add a test for that.

The asymptotic behavior is much like exp(x) as x goes to negative infinity so I expect any problem would occur in the FSC iteration.

**Comment by person142** [comment]
An update:

- For the asymptotic series when `x > 1e20`: switched to just returning `x`.
- For `x` just before underflow: it looks like the FSC iteration wasn't causing any problems. On the other hand, it looks like the `exp(x)` approximation is accurate to double precision for `x < -50` anyway, so I switched to using that for performance.

Thoughts?

**Comment by pierslawrence** [comment]
Both of those approximations sound like they should do the trick. Thanks!

**Comment by person142** [comment]
AFAICT, the test failure is a problem with old gcc/glibc. I can't repro it on Ubuntu using e.g. gcc 8.3.

I don't really want to track the problem down any more than that (I feel we spend enough time appeasing old compiler versions around here), so I just skipped the test. If there are strong objections to doing that then I can revisit that decision.

**Comment by rgommers** [comment]
```
E       Max |adiff|: 1.01307e-06
E       Max |rdiff|: 3.70151e-06
```
on the last TravisCI run, seems still acceptable (but still needs a fix to test tolerance here).

Test you `xfail`-ed had 
```
E       Max |adiff|: 9.74619e-07
E       Max |rdiff|: 4.17627e-06
```
Probably better to bump test tolerance than `xfail`, to ensure it doesn't get worse (especially since it also failed on Azure). But yes, fine with me to not investigate root cause and leave implementation as is. This PR is still an improvement it looks like.

**Comment by person142** [comment]
Ach, I finally tracked down the issue-there were some instances of `abs` that needed to be `fabs`. Only newer C++ versions have the right overloads IIRC.

Anyway, everything passes now; no skips needed.

**Comment by rgommers** [comment]
Merged, thanks @person142 and @pierslawrence

**Comment by peterbell10** [comment]
>Ach, I finally tracked down the issue-there were some instances of `abs` that needed to be `fabs`. Only newer C++ versions have the right overloads IIRC.

`abs` is a function from the C standard so in theory there aren't any overloads at all. `std::abs` on the other hand has (AFAIK) always had overloads for `float` input. Unfortunately, many standard libraries muddy the waters by not distinguishing between the two.

In general, I would suggest _always_ qualifying `<cmath>` functions with `std::`.

**Comment by person142** [comment]
> In general, I would suggest always qualifying <cmath> functions with std::.

Fair suggestion, not doing so definitely caused me a headache here. I'll go clean up the other Wright omega uses in a follow up...

**Pull request merged**
