### PR TITLE
ENH: linalg: add the function 'solve_circulant' for solving a circulant system

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
I updated the pull request.  The proposed signature of `solve_circulant` is now

```
def solve_circulant(c, b, singular='raise', tol=None, caxis=-1, baxis=0, outaxis=0):
```

When `c` is a 1-d array, @argriffing's suggested behavior is followed: `solve_circulant(c, b)` is a specialized implementation of `solve(circulant(c), b)`, where `solve` is `scipy.linalg.solve`.

Note that `scipy.linalg.solve` and `numpy.linalg.solve` do not handle high dimensional `b` arrays the same way.  If, for example, `a` has shape `(3, 3)` and `b` has shape `(3, 2, 5)`, `scipy.linalg.solve(a, b)` returns an array with shape `(3, 2, 5)`;  `numpy.linalg.solve(a, b)` raises a ValueError. `solve_circulant` follows the convention of `scipy.linalg.solve`.

**Comment by rgommers** [comment]
This looks ready. Besides a rebase, is there anything left to do here?

**Comment by WarrenWeckesser** [comment]
Rebased.  I don't have any more changes in mind.

**Comment by rgommers** [comment]
@pv @argriffing maybe time for a final review and then green button it?

**Comment by argriffing** [comment]
Yes, it has tests asserting that `solve_circular(c, b)` is almost equal to `solve(circular(c), b)`, including tests for the 2d rhs mentioned by @pv, so I think it is safe to merge.

**Comment by argriffing** [comment]
Thanks @WarrenWeckesser sorry it took a year to merge :/

**Pull request merged**
