### PR TITLE
MAINT: Remove Python2 cStringStream

### PR DESCRIPTION
**Pull request by sethtroisi**
Continued work to remove all Python2 Code #11584 
---

I don't have a good understanding of the lifecycle of py3k.h, please excuse me if I'm being haste.
From Numpy commits I came away with the idea that you could delete the compatibility functions once they were cleaned up entirely in the code base. If this is not true then I'm acting in haste and I can close this PR

### CODE REVIEW

**Comment by sethtroisi** [comment]
Travis errors are the same as in some of my other recent PRs

________________________________ test_lsmr[COO] ________________________________
and
____________________ TestCurveFit.test_curvefit_covariance _____________________
both appear related to relative error being slightly higher than the threshold

**Comment by rgommers** [comment]
yes, please ignore `TestCurveFit` failures, there's a separate issue open for those

**Comment by sethtroisi** [comment]
Ping, this is waiting on an answer about if `py3k.h` code lifecycle (e.g. can be deleted).

**Comment by rgommers** [comment]
> Ping, this is waiting on an answer about if `py3k.h` code lifecycle (e.g. can be deleted).

Yes, `py3k.h` headers can all be cleaned up at this point.

**Comment by sethtroisi** [comment]
Given `py3k.h` can be cleaned up IMO this just deletes dead code and is a safe change

**Comment by rgommers** [comment]
LGTM, merged. Thanks @sethtroisi

**Pull request merged**
