### PR TITLE
RFC: ENH: stats: Extend `wasserstein_distance` to different `p` values. See ticket #19727.

### PR DESCRIPTION
**Pull request by yagizolmez**
Closes #19727

This is still a draft and I am seeking opinions.

There has been a request to add a function to calculate the Wasserstein distance with $p=\infty$, see #19727. I have figured two things:

i) The implementation for the multidimensional case easy to generalize to an arbitrary $p \geq 1$.

ii) Following the [reference](https://arxiv.org/pdf/1509.02237.pdf) in the docs, I have figured that there is an analytical result for $p = \infty$ in the 1-D case. On page 10, it is stated that  

$$W_\infty(P,Q) = ||F^{-1}-G^{-1}||_\infty$$ 

in the 1-D case, where $F^{-1}$ and $G^{-1}$ are the [quantile functions](https://en.wikipedia.org/wiki/Quantile_function) of $P$ and $Q$ respectively. Here, $|\cdot|_\infty$ is the [infinity norm](https://en.wikipedia.org/wiki/Norm_(mathematics)#Maximum_norm_(special_case_of:_infinity_norm,_uniform_norm,_or_supremum_norm)).

I have extended the `wasserstein_distance` function to take a new input `p`. In the one dimensional case, if $p=1$ then the analytical result from `_cdf_distance` is used. If $p=\infty$, then the analytical result from the newly added function `_wasserstein_infty` is used. For any other `p` value the 1-D array is turned into 2-D and the corresponding Wasserstein distance is calculated numerically.

I have written some tests. It seems that as long as the distributions are 'nice enough', $W_p \to W_\infty$ as $p \to \infty$ as expected. Please see the tests.

However there are some caveats:

1. If `p` is too large ($p>50$) the algorithm blows up. 
2. The distributions in my tests are a little too nice.

As a result, while I am mostly confident that `_wasserstein_infty` works as intended (more tests are needed though), I am not confident with extending $p=\infty$ to the 2-D case or supporting all `p` values. Small `p` values (such as `p=2`) are probably fine.

My questions are:
1. What are your opinions on extending this metric?
2. What other tests would you recommend me to do?

Please let me know what you think.

### CODE REVIEW

**Comment by lutefiskhotdish** [comment]
On stability with large p, would it help if you scale the distances `D` before `cost = np.power(D.ravel(), p)` (line 10408), by dividing by the largest `D`?  Then de-scale the result before returning it.  See [Handling Overflow condition in calculating p-Norm](https://rehanguha.github.io/articles/overflow-p-norm).

**Comment by yagizolmez** [comment]
@lutefiskhotdish Thanks for the recommendation. I also figured that there is an analytical result for general `p` in the 1-D case. I will also implement that and compared the results with the numerical method.

**Comment by rlucas7** [comment]
It might be worthwhile to check/compare the numerics against [`pot`](https://pythonot.github.io/index.html) for the `p=oo` scenario to confirm that the values agree. The pot package specializes in optimal transport so they should have numerically stable solution if one exists here.

**Comment by B0Gec** [comment]
@yagizolmez I am pleased to be heard from my issue. :raised_hands: 
1.) From my current point of view, metrics where p=1, 2 and $\infty$ in 1-D are enough for me. So I have no further need for generalization.
2.) I am currently busy with other stuff so I will have to check and test in a while, so I did not go deep inside the code to check the scope of the tests. So for me, they are fine.

Thank you and keep up the good work! :rocket:

**Comment by yagizolmez** [comment]
I know that `wasserstein_distance` has been reverted, but I am keeping the 2-D version for now for this draft PR. I still use the 2-D method for tests.

For the 1-D case with `p=1` and `p=2`, I have implemented the Proposition 1 [in the reference](https://arxiv.org/pdf/1509.02237.pdf):

$$
W_p^p (P,Q) = \int_0^1 |F^{-1} (t) - G^{-1} (t) |^p \text{d} t
$$

On the same page, there is also a formula for $p=\infty$ case:

$$
W_\infty(P,Q) = ||F^{-1} - G^{-1}||_\infty
$$

which is also implemented. I have written tests to compare the `p=1` case with `_cdf_distance` and `p=2` case with the optimization method. I have not written any tests for the $p=\infty$ case yet. 

@mdhaber, @com3dian. Any recommendations would be appreciated. Especially on writing tests for the $p=\infty$ case and on including the `axis` argument.

**Comment by mdhaber** [comment]
Please merge main here. If you need to use the linear programming backend that was removed from `wasserstein_distance`, just copy-paste it from the code that was removed. You can make it a private function in `_stats_py.py`, e.g. `_wasserstein_distance_nd`, for now; we'll make it public in a separate PR.

**Comment by yagizolmez** [comment]
@mdhaber Done!

**Comment by mdhaber** [comment]
@yagizolmez Let's keep this one open, too, since it is conceptually distinct from adding the separate `wasserstein_distance_nd` function. Once that merges, we can consider making these changes there.

**Comment by yagizolmez** [comment]
Looking at this, based on how I implemented the $p=2$ in the multivariate case, I conjecture that for the $p = \infty$ case we should simply return `D_largest_abs`. I will implement this and compare with the analytical results from the 1D case. If that works, I will look for an analytical proof somewhere to make sure.

**Comment by mdhaber** [comment]
@yagizolmez Thought i'd check in to see if you were still interested?

**Comment by yagizolmez** [comment]
@mdhaber Thanks for asking. I have gotten very busy lately. I am trying to finish off my PhD and find a job. I will come back to this if I can find the time. In the mean time, please feel free to work on it, or assign it to someone else. I truly regret not having the time right now.

**Comment by mdhaber** [comment]
No problem. I'll go ahead and close it for now but leave the issue open. I think before we return to this, we should check the box for `wasserstein_distance` in gh-20544.

**Pull request closed without merging**
