### PR TITLE
DOC: examples for derivatives of Bessel functions

### PR DESCRIPTION
**Pull request by dschmitz89**
#### Reference issue
part of #7168 

#### What does this implement/fix?
Adds examples for all functions listed under derivatives of Bessel functions.

#### Additional information
I am not familiar with plotting in the complex plane, thats why I did not add plots for Hankel function derivatives. Could still be added if deemed necessary.

### CODE REVIEW

**Review by tupui — APPROVED** [review]
All good to me, thanks @dschmitz89.

Some potential improvements, use different linestyles and have a custom legend positioning. But this can be done later.

**Comment by WarrenWeckesser** [comment]
A couple reminders:

* Examples should now include the line `import numpy as np` if `np` is used.
* No blank line immediately after the `Examples` heading.

**Comment by tupui** [comment]
@WarrenWeckesser The first point is addressed no? Do you see any missing import? (Note they are not at the beginning of the examples).

**Comment by WarrenWeckesser** [comment]
@tupui, yeah, I noticed that after my comment (comment has been edited).  I thought we had a preference for importing numpy at the beginning.

**Comment by tupui** [comment]
I am neutral on the import location for examples. But sure if we want that, let's make it the policy to have all imports at the top.

**Comment by WarrenWeckesser** [comment]
In https://github.com/scipy/scipy/issues/13049#issuecomment-1199457608, @mdhaber suggested adding the imports "to the top of the code block where they are first needed", which I guess is consistent with this pull request.   I have a slight preference for putting the imports of `np` and `plt` at the beginning, but I'll let those with stronger preferences run the debate.

**Pull request merged**
