### PR TITLE
WIP: ENH: allow generating ufuncs in multiple modules

### PR DESCRIPTION
**Pull request by person142**
@WarrenWeckesser's PR https://github.com/scipy/scipy/pull/10170 got me thinking about the discussion we had a while ago in https://github.com/scipy/scipy/pull/7190 (and on the mailing list https://mail.python.org/pipermail/scipy-dev/2017-March/021847.html) about having a way to generate ufuncs for multiple modules. This is a rough sketch of what we would need to do to support that. It's incomplete (a few things are still hard-coded), mostly due to not having a simple example to test on (once https://github.com/scipy/scipy/pull/10170 is merged it would provide that example).

The general idea is:

- Move `_generate_pyx.py` to tools, remove hard-coded special bits
- Add a config file to modules that will need ufuncs that has
  - the signatures file
  - the docstrings file
  - the optional name of the Cython API (e.g. `cython_special`)
- Update `cythonize.py` search for the config files and call `generate_pyx.py` on them

The question is: are we interested in doing this? I'm interested because:

- If we're just going to use functions in stats, I'd rather see them defined there
- Long term we could think about making a Cython interface for the the pdfs, cdfs etc. like we did with special, which also allows them to e.g. be called from Numba fairly easily (which is what happens for special now: https://github.com/numba/numba/issues/3086)

### CODE REVIEW

**Comment by rgommers** [comment]
Yes I think this would be a useful improvement.

> If we're just going to use functions in stats, I'd rather see them defined there

this would indeed make that a lot easier

> Long term we could think about making a Cython interface for the the pdfs, cdfs etc. like we did with special

it would be quite a bit of work, because I think we'd want to do it for all distributions if we decide to go for this, but yes those pdf/cdf functions can be performance pain points so could be nice.

**Comment by person142** [comment]
Closing this-the code is getting stale. Will resume work when more stats-only ufuncs begin to get created.

**Comment by WarrenWeckesser** [comment]
@person142, interested in reviving this, or something like it?  I think the need for ufuncs in `stats` just keeps growing.  I grumble every time I have to resort to `_lazywhere`.  I'd like to revive https://github.com/scipy/scipy/pull/10170, and some of the current issues with very slow behavior in `stats` could be fixed if we converted certain functions to ufuncs, implemented in C or Cython.

**Comment by person142** [comment]
Yup, I’m still down to spread the ufuncs.

**Comment by WarrenWeckesser** [comment]
Will you be able to revive this PR any time soon?  Or should someone else pick up from here?

> Will resume work when more stats-only ufuncs begin to get created.

Chicken-and-egg problem?  Let's put in the infrastructure.  I'm sure there are several enhancements to `stats` that will follow pretty quickly.  "If you build it, they will come."

**Pull request closed without merging**
