### PR TITLE
DOC: replace `sphinx_panels` and `sphinx_tabs` with `sphinx_design`

### PR DESCRIPTION
**Pull request by tupui**
Sphinx-Panels is deprecated in favour of Sphinx-Design. It also allows to remove the the extra dependency to Sphinx-Tabs

See https://sphinx-design.readthedocs.io/en/pydata-theme/index.html

### CODE REVIEW

**Comment by tupui** [comment]
@rossbar maybe you could have a look?

**Review by rossbar — APPROVED** [review]
LGTM @tupui , thanks for taking this up!

I'm pleased to see that the rendered output (at least for the cards - I didn't check the tabs closely) is more or less the same. The only difference I can detect on the landing page of the [scipy devdocs](https://scipy.github.io/devdocs/index.html) is that the "shadow" below the cards seems deeper. That's purely an aesthetic difference and I have no opinion about it, but just thought I'd point it out.

IMO this PR is a blueprint for updates that should be made to numpy's documentation as well, though that case will be even easier because I don't think the numpy docs use tabs (yet :) ). Thanks again @tupui !

**Comment by tupui** [comment]
Cool thanks for having a look! I can make a PR to NumPy if wanted.

**Comment by rossbar** [comment]
> Cool thanks for having a look! I can make a PR to NumPy if wanted.

That'd be great!

**Comment by rossbar** [comment]
The pandas devs might appreciate the update as well, though I'm less familiar with the pandas docs and can't say off hand whether the changes might be more involved (I'm not sure how extensively cards are used, for example).

**Comment by tupui** [comment]
I will have a look at these tmr 😃

**Review by rgommers — APPROVED** [review]
LGTM too, and it looks like you found all the config files to update. Merging, thanks @tupui

**Pull request merged**
