### PR TITLE
WIP: Porting the remaining cKDTree query methods to C++

### PR DESCRIPTION
**Pull request by sturlamolden**
Moving query methods to C++ allows for a significant speed improvement and ability to release the GIL during queries.

### CODE REVIEW

**Comment by sturlamolden** [comment]
```query_pair``` is ported over to C++ and works fine on my computer. I get a rougly 6x speedup on my Mac. 

New ```output_type``` keyword argument selects between a ```set``` and ```ndarray``` as return container, as there has been complaint about the return type.

**Comment by rgommers** [comment]
Looks like this needs a rebase. TravisCI didn't have a heart attack though:)

**Comment by sturlamolden** [comment]
Yes, it likely needs a rebase. That does not matter right now because ```cKDTree``` is quite orthogonal to the rest of SciPy.

I still have to port ```count_neighbors```, ```query_ball_point```, ```query_ball_tree```, and ```sparse_distances``` before this is ready to merge. Most of the porting is already done. They share a lot of code with ```query_pair``` so it should be doable to have this ready for 0.17.

**Comment by sturlamolden** [comment]
Git is trying to make me go insane by claiming my remote branch is up-to-date, which it clearly is not. Pushing to a new remote branch works fine.

**Comment by sturlamolden** [comment]
test

**Comment by sturlamolden** [comment]
I need a new WIP PR it seems, this one is fubar.
https://github.com/scipy/scipy/pull/4890

**Pull request closed without merging**
