### PR TITLE
Update _fftconv_faster

### LINKED ISSUE #10427: ENH: convolve numbers should be updated
Now that `scipy.fft` exists, the `oneD_bigO` and `big_O_constant` should be updated in `signal/signaltools.py`, e.g. from this commit:

https://github.com/scipy/scipy/commit/dea7712e31f1b57e6abc21cdbd33c4dfcd62e71f

See previous discussions here:

https://github.com/scipy/scipy/pull/5608

I couldn't find one of the linked gists that I think was used for the benchmark, hopefully @endolith can find his copy!

### LINKED ISSUE #10887: scipy.signal.signaltools._fftconv_faster has incorrect estimates
My issue is about the function `scipy.signal.signaltools._fftconv_faster`. The function has a logical error, causing most convolutions to use fft when the direct method would save a large factor.

Code example, showing that `_fftconv_faster` returns that fft is faster even when multiplying by a scalar kernel, when the signal is large enough.
```
>>> from scipy.signal.signaltools import _fftconv_faster
>>> _fftconv_faster(np.empty(1), np.empty(1000000), "full")
True
```

Here is the impact in timing on a lenovo yoga 920, intel core i7 8th gen, 16gb ram, running Ubuntu 18.04:
```
>>> import numpy as np
>>> from scipy.signal import convolve
>>> h = np.random.randn(1)
>>> x = np.random.randn(1000000)
>>> %timeit convolve(x, h, method="direct")
714 µs ± 14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit convolve(x, h)
70.2 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

The automatic run, which chooses fft, is slower by a x100 factor.

The root cause for this is the incorrect estimate for the number of multiplications in the direct convolution algorithm. This is line 506 in v1.3.1, and 497 of the latest commit [8a3e9fa] as of writing this issue:
```
direct_time = (x.size * h.size * _prod(out_shape))
```

The correct direct computation time is actually:
```
direct_time = min(x.size, h.size) * _prod(out_shape)
```

The big oh constants, in the tens of thousands, were probably calculated as a ratio to the incorrect estimate. So a fix to the direct estimate will need to be accompanied by a recalculation to the constants.

### PR DESCRIPTION
**Pull request by peterbell10**
#### Reference issue
Fixes gh-10887, closes gh-10427

#### What does this implement/fix?
Uses a more correct expression for the complexity and updated big O constants in `signal._fftconv_faster`. I have also included a new `threshold` parameter where the  FFT convolution is only used if its predicted speedup is above. This accounts for the higher overhead involved in `fftconvolve` of a small array.

#### Additional information
To find the constants I just used the notebook in gh-10427 with the updated complexity expressions. According to the test there this is ~85-95% accurate.

Note this doesn't have specific constants for 1D as I was just using the output from @stsievert's notebook.

### CODE REVIEW

**Comment by stsievert** [comment]
I'd also like to see the 1D numbers updated too.

> I was just using the output from @stsievert's notebook.

The implementation at https://github.com/stsievert/scipy-convolve-timings/?

> I have also included a new `threshold` parameter ... [that] accounts for the higher overhead involved in fftconvolve of a small array.

I'd like to see validation of this choice. I can't see how well this performs, or verify the implementation; my notebooks don't include it. Could you push the notebooks you used or publish your fork?

**Comment by peterbell10** [comment]
Apologies for the delayed response @stsievert. I've noticed a bug in the modifications I made to your testing code and these numbers actually perform very badly in `mode="same"` and `mode="valid"` (<70% accuracy). 

I'm fairly certain that the formula for `fftconvolve` is correct as I've looked at that code fairly recently but am less sure about `method="direct"`. I think that `min(x.size, h.size)` is theoretically correct but it's possible that doesn't match the actual implementation.

> Could you push the notebooks you used or publish your fork?

I've pushed the notebooks [here](https://github.com/peterbell10/scipy-convolve-timings)

**Comment by peterbell10** [comment]
>>I have also included a new threshold parameter ... [that] accounts for the higher overhead involved in fftconvolve of a small array.

>I'd like to see validation of this choice.

I agree that a proper validation would be good. My motivation was that fftconvolve has ~10x more overhead for small sizes but this overhead is just a constant time and doesn't scale with size:
```python
In [4]: x = np.random.rand(2,2)

In [7]: %timeit convolve(x, x, method='direct')
7.57 µs ± 199 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [8]: %timeit convolve(x, x, method='fft')
64.4 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by stsievert** [comment]
> I think that min(x.size, h.size) is theoretically correct but it's possible that doesn't match the actual implementation.

I see your point. I didn't consider that case a ton in development (and implemented the `method` option to allow users to circumvent it).

When is this an issue? In your example, `choose_conv_method` makes the right choice on `direct` vs `fft`:

``` python
In [13]: from scipy.signal import convolve, choose_conv_method
In [14]: import numpy as np

In [15]: x = np.random.randn(2, 2)

In [16]: choose_conv_method(x, x)
Out[16]: 'direct'

In [17]: %timeit convolve(x, x)
20.7 µs ± 509 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [18]: %timeit convolve(x, x, method="direct")
9.85 µs ± 49.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [19]: %timeit convolve(x, x, method="fft")
507 µs ± 57.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by peterbell10** [comment]
>When is this an issue? In your example, `choose_conv_method` makes the right choice on `direct` vs `fft`

This PR uses a completely different performance model so what was true before doesn't carry over. Without it, `choose_conv_method` would almost always underestimate the size where fftconvolve was faster than direct. Presumably because it is fitting to the asymptotic trend and was not accurate for small sizes.

Now that I think about it again though, a better approach would be to focus on fitting the curve near to the cross-over point as that's the only place where precision is actually important.

**Comment by stsievert** [comment]
> a better approach would be to focus on fitting the curve near to the cross-over point as that's the only place where precision is actually important.

Let me know if you want help with that, or any tips.

**Comment by larsoner** [comment]
It would be good to get this in for 1.4.0 if possible, given that our FFT backend has changed.

I would say the bar for that should be that it does better than what we have now, even if it's not perfect (e.g., could be fit near the transition point). @stsievert does it meet this criteria to you? Or is something missing (e.g., 1D updates)?

**Comment by stsievert** [comment]
> It would be good to get this in for 1.4.0 if possible, given that our FFT backend has changed.

It looks like the FFT backend will change in 1.4.0. Is that accurate? When do you expect 1.4.0 to be released?

**Comment by larsoner** [comment]
Yes the FFT backend has switched from fftpack to pocketfft in 1.4.0.

We branch 1.4.0 in just under two weeks.

**Comment by stsievert** [comment]
> Yes the FFT backend has switched from fftpack to pocketfft in 1.4.0. We branch 1.4.0 in just under two weeks.

Copy. I didn't realize. That puts a new urgency on updating the constants.

I'll try to put in a PR by Monday after completing some work on https://github.com/stsievert/scipy-convolve-timings over the weekend. My goal will be to update the numbers for the new FFT backend (possibly focusing on implementation details https://github.com/scipy/scipy/pull/10904#issuecomment-539701304 but not sampling near the decision boundary https://github.com/scipy/scipy/pull/10904#issuecomment-539886619).

**Comment by larsoner** [comment]
@stsievert that would be great!

**Comment by peterbell10** [comment]
Superceded by gh-11031

**Pull request closed without merging**
