### PR TITLE
MAINT: Use lanczos approximation for gamma ratios in hyp2f1 for complex numbers

### PR DESCRIPTION
**Pull request by steppi**
#### Reference issue

This PR closes no issues. A bug has been fixed which has no open issue.

#### What does this implement/fix?

This PR updates the cases z = 1, c - a - b > 0 [[DLMF 15.4.20]](https://dlmf.nist.gov/15.4#E20) and z near -1, c = 1 + a - b,
[[DLMF 15.4.26]](https://dlmf.nist.gov/15.4#E26) to use the [Lanczos approximation](https://www.boost.org/doc/libs/1_78_0/libs/math/doc/html/math_toolkit/lanczos.html) to the gamma function for values that overflow or underflow with the direct computation of the gamma ratios, as suggested by @person142 in [this comment](https://github.com/scipy/scipy/pull/14692#pullrequestreview-746682504) on an earlier pull request in this series. This approach gives more accurate results than the naive approach of taking logs and then exponentiating at the end. This update has been made now because a function to compute these kinds of Gamma ratios using the Lanczos approximation will be helpful in the next two PR's which will implement the `1 - z` [[DLMF 15.8.4]](https://dlmf.nist.gov/15.8#E4) and `1/z` [[DLMF 15.8.2]](https://dlmf.nist.gov/15.8#E2) transforms respectively. These transforms are used to extend hyp2f1 outside the domain of its Maclaurin series.

In addition a bug has been fixed which has caused the cases where `z` is very near 1, `c` is a negative integer and one of `a` or `b` is a negative integer greater than or equal to `c` to be handled incorrectly. We seek to follow `mpmath` in returning finite values for these cases, using the result that in these cases the series becomes a terminating polynomial. These cases were being caught in earlier conditions before the terminating polynomial case was reached.

#### Additional information

I haven’t taken to much care to combine the Lanczos factors analytically in the best way for each case. At one point, the code checks for underflow or overflow and then retries with another combination. There are two other possible combinations that are untried. It can be observed in the new test cases that  `hyp2f1(a, b, c, 1 + 0j)` and `hyp2f1(b, a, c, 1 + 0j)` can disagree due to a difference in combining terms, despite the fact that they should be equal. Surprisingly, it can also be observed that `mpmath`s implementation itself disagrees for some of these cases, at least when using the default internal precision. It would perhaps not be too difficult to come up with a good rule of thumb to determine which way to combine the parameters based on the values of `a`, `b`, and `c`, but I haven't attempted it due to scarcity of time and seeking to avoid complicating the code further.

### CODE REVIEW

**Comment by steppi** [comment]
@person142, basically what happened is that while I was implementing the `1 - z` transform, I noticed it would be really helpful to have the lanczos approximation for these gamma ratios since they are used in both the `1 - z` and `1/z` transforms. This seemed involved enough that it should get its own pull request. When you have time to review this, let me know if there's a better way to decide how to combine the lanczos approximation factors that you know offhand.

**Comment by steppi** [comment]
@person142 I have an idea for a heuristic to decide how to combine the terms. Marking this work in progress and will implement next weekend.

**Comment by steppi** [comment]
@person142, instead of trying to find the best way to combine the factors from the lanczos approximation, this now computes things in four different ways, and takes the average among results that are nonzero, non-infinite, and not NaN. There's some special logic to handle cases where all of the ways to combine the terms result in one of zero, +- infinity, or NaN. This way of doing things seems to work well, but the code is a little tortured. Sorry if it's a little painful to review.

**Comment by person142** [comment]
Ah yeah, combining a bunch of Lanczos terms is always a pain... I used to think about rewriting the beta function w/ Lanczos but then the number of cases made me give up every time.

**Comment by steppi** [comment]
> Ah yeah, combining a bunch of Lanczos terms is always a pain... I used to think about rewriting the beta function w/ Lanczos but then the number of cases made me give up every time.

Yeah, this was definitely tedious. There's one thing I wasn't sure about: this just uses Lanczos if directly taking the ratio of Gamma products leads to overflow or underflow. Is this what you would have done with the beta function? It's seems possible that the Lanczos approximation could be more accurate than the direct approach in some cases even when the direct approach doesn't underflow or overflow, but I haven't had time to investigate.

**Comment by person142** [comment]
In general yes it should be more accurate in other cases too - catastrophic cancellation still being possible in the subtraction when there's a quotient of Gammas involved.

**Comment by person142** [comment]
We need to write like a Sympy "simplify these Lanczos calculations" package.

**Comment by steppi** [comment]
> In general yes it should be more accurate in other cases too - catastrophic cancellation still being possible in the subtraction when there's a quotient of Gammas involved.

I see. So far I've seen better results when directly computing the quotient of Gamma functions and I think it may be because I'm using `lanczos_sum_expg_scaled`. The Boost documentation on the [Lanczos approximation](https://www.boost.org/doc/libs/1_38_0/libs/math/doc/sf_and_dist/html/math_toolkit/backgrounders/lanczos.html) has the following to say about exp(g) scaling:

_Finally note that the Lanczos approximation can be written as follows by removing a factor of exp(g) from the denominator, and then dividing all the coefficients by exp(g):_

_This form is more convenient for calculating lgamma, but for the gamma function the division by e turns a possibly exact quality into an inexact value: this reduces accuracy in the common case that the input is exact, and so isn't used for the gamma function._

I'm going to change it to first try with the regular lanczos approximation and then try again with the expg scaled version if the first attempt leads to underflow or overflow.

**Comment by steppi** [comment]
> We need to write like a Sympy "simplify these Lanczos calculations" package.

Heh. That sounds like it would be a fun project.

**Comment by steppi** [comment]
Marking this as draft again. It still needs some work.

**Comment by steppi** [comment]
@person142 OK, I think this is ready. I've abandoned the horrible complexity of what I had before and now have something much simpler that is only a little less accurate. 

Rather than putting more thought into how to combine the factors, this just chooses the factor with highest exponent to absorb into the others. I've stared at the improved formula described in the Boost documentation for the [Beta function](https://www.boost.org/doc/libs/1_38_0/libs/math/doc/sf_and_dist/html/math_toolkit/special/sf_beta/beta_function.html), and may look into something like that in the future, but for now I think it's better to start simple.

Rather than directly computing the ratio in terms of Gamma functions, and then only trying lanczos if there is underflow or overflow, this only uses lanczos. The direct ratio seems to be slightly more accurate in many cases, and I had to loosen the tolerance on one test because of this. I plan to revisit this in the future.

You may notice that I've also loosened the tolerance for one test for the regions around exp(±iπ/3). This is because I added a missing `cdivision` decorator to `hyp2f1_lopez_temme_series`, which caused a very slight reduction in accuracy on 32 bit linux.

A reminder:  a bug has been fixed which caused the cases for `z` very near 1, `c` a negative integer and one of `a` or `b` a negative integer greater than or equal to `c` to be handled incorrectly.

After this PR, we just have the `1 - z` and `1/z` transformations and then we can banish the Fortran implementation from the codebase forever. Using the lanczos approximation for these gamma ratios will help with these transformations for the cases where `c - a - b` or `b - a` is close to an integer.

**Comment by steppi** [comment]
Shelving this again. I ran some benchmarks last night that show this offers no discernible improvement over the naive exp log implementation for cases where the direct gamma ratio overflows, and hurts performance considerably when the direct gamma ratio doesn't overflow.

**Comment by steppi** [comment]
@person142, I checked [Boost's beta function implementation](https://github.com/boostorg/math/blob/2b9927871fd86312f753e4bcbdb82236022c5856/include/boost/math/special_functions/beta.hpp#L96-L105), and saw that they have special handling for cases where the base of a power is close to one. 

```c++
   if((fabs(b * ambh) < (cgh * 100)) && (a > 100))
   {
      // Special case where the base of the power term is close to 1
      // compute (1+x)^y instead:
      result *= exp(ambh * boost::math::log1p(-b / cgh, pol));
   }
   else
   {
      result *= pow(agh / cgh, a - T(0.5) - b);
   }
```

I added this to our implementation and now things seem to work well enough that we can just always use the lanczos implementation and not worry about having to still do the direct gamma ratio in some cases.  I added many relevant examples to the `special/_precompute/hyp2f1_data.py` script that can be used to demonstrate this. When I have more time, I'll make some more plots and tables like I did in previous PRs.

**Comment by person142** [comment]
Nice, this is excellent stuff!

**Comment by steppi** [comment]
I added some more cases to the _precompute script. We're making good progress but this still needs a little more work. Sometimes lanczos still overflows when exp-log doesn't so we need another fallback. I'll try exp-log of the direct ratio, and also exp-log of lanczos.

|    | method   |   min |         25% |         50% |         75% |           max |
|----|----------|-------|-------------|-------------|-------------|---------------|
|  0 | lanczos  |     0 | 1.23508e-15 | 1.48275e-14 | 1.60318e-13 | inf           |
|  1 | old      |     0 | 2.25212e-16 | 1.05305e-13 | 4.58413e-13 |   7.23766e-12 |

**Comment by steppi** [comment]
Trying to mix the different approaches. Getting closer. This uses the direct ratio when computing 
Gamma(u) * Gamma(v) / (Gamma(w) * Gamma(x)) when |u|, |v|, |w|, |x| <= 100, otherwise lanczos, and falls back to the exp-log if lanczos overflows or underflows.

| method   |   min |         25% |         50% |         75% |         max |
|----------|-------|-------------|-------------|-------------|-------------|
| lanczos  |     0 | 2.2068e-16  | 8.91584e-15 | 1.6663e-13  | 0.00331349  |
| old      |     0 | 2.25212e-16 | 1.05305e-13 | 4.58413e-13 | 7.23766e-12 |

I went deep into the weeds on [another branch](https://github.com/steppi/scipy/tree/hyp2f1-of-theseus-4-a) trying to find an optimal way to combine the terms following what [boost does for the beta function](https://www.boost.org/doc/libs/1_38_0/libs/math/doc/sf_and_dist/html/math_toolkit/special/sf_beta/beta_function.html). Things get grotesquely complicated there, but performance actual suffers a little bit. Giving up on that and just trying to find different regimes where we should use different methods. Now I just have to expand where exp-log is used. Was hoping to wrap this up this weekend, but it will take a little longer.

**Comment by steppi** [comment]
@person142 nevermind, there were 313 examples where the old implementation returns `nan` that were inadvertently being excluded in my benchmark. This PR's implementation doesn't return `nan` for any examples in the relevant benchmark set from `scipy/special/_precompute/hyp2f1_data.py`. I've made the relative error for these examples `inf` in the table of relative quantiles below. I think it's finally ready to ship.

|    | method   |   min |         25% |         50% |         75% |          max |
|----|----------|-------|-------------|-------------|-------------|--------------|
|  0 | lanczos  |     0 | 2.2068e-16  | 8.91584e-15 | 1.66557e-13 |   0.00331349 |
|  1 | old      |     0 | 2.39105e-16 | 1.13334e-13 | 5.04077e-13 | inf          |

**Review by person142 — APPROVED** [review]

**Comment by person142** [comment]
Woo nice stuff @steppi!

**Comment by steppi** [comment]
> @steppi thanks for the improvement! It looks like there are still some issues open about `hyp2f1`. Are any of those closed by this? Are there cases in which we should use the Boost implementation directly? (We call Boost's implementation of several stats distributions now.)

No issues fixed here. Just an improvement in relative error for the `z = 1`, `c - a - b > 0` case, and another small bug fix. After this PR, there will be two that will fully replace the previous Fortran implementationd. Then one more with some small tweaks. A final PR after that will implement a recurrence that allows for accurate results when |a|, |b|, |c| are large. After that I'll move onto other hypergeometric functions.

There's no Boost implementation of the Gaussian hypergeometric function unfortunately. Oddly enough, it looks like the [boost.org](https://www.boost.org/) domain has expired, so I can't link the documentation that shows which hypergeometric functions are available.

**Comment by steppi** [comment]
Boost's site is back. https://www.boost.org/doc/libs/1_74_0/libs/math/doc/html/math_toolkit/hypergeometric.html
We should compare their [hyp1f1 implementation](https://www.boost.org/doc/libs/1_74_0/libs/math/doc/html/math_toolkit/hypergeometric/hypergeometric_1f1.html) with ours. Although it looks like they don't handle the case of complex `z`.

**Comment by mdhaber** [comment]
Oops, of course. I knew there was a reason I didn't ask before : P

**Pull request merged**
