### PR TITLE
MAINT: update `stats.iqr` for deprecated `np.percentile` keyword

### LINKED ISSUE #15064: MAINT:  `interpolation` keyword is renamed to `method` in `np.percentile`
### Describe your issue.

Starting from NumPy 1.22, `np.percentile` keyword `interpolation`  is deprecated and renamed to `method` .

Seen https://github.com/scipy/scipy/runs/4247004117?check_suite_focus=true

### Reproducing Code Example

```python
# on NumPy 1.22
np.percentile(a, q, interpolation="linear")
```

### Error message

```shell
E   DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
1606
E   Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they. (Deprecated NumPy 1.22)
```

### SciPy/NumPy/Python version information

NumPy 1.22

### PR DESCRIPTION
**Pull request by rgommers**
Also clean up the docstring, and enable the new options added for the `method` keyword in numpy 1.22.0

### CODE REVIEW

**Review by tupui — APPROVED** [review]
LGTM, thanks @rgommers.

Luckily it was the only occurrence. In general, how would you proceed if there would be more API changes like these? Should we have some dedicated file for all affected NumPy functions?

**Comment by tupui** [comment]
(Seems like GH is now deleting branches on merge even if they are not ours)

**Comment by rgommers** [comment]
> Luckily it was the only occurrence. In general, how would you proceed if there would be more API changes like these? Should we have some dedicated file for all affected NumPy functions?

It depends, probably just fix them up. If there were really a lot, go back and reconsider the deprecation in NumPy.

I'm not sure it would help to have a separate file for this, that would just be more complex in cases like these, and there's no real need for it as far as I can tell.

**Comment by tylerjereddy** [comment]
Hmm, not sure on backporting this one.. the file doesn't even exist on the maintenance branch and remapping it to the original file, before namespace privacy adjustments, produces a larger diff.

**Comment by rgommers** [comment]
Okay, I'll have a look. Maybe reapplying just the 5 line diff to fix the deprecation warnings that will show up with numpy 1.22.0 will be useful.

**Pull request merged**
