### PR TITLE
Splrep _curfit_cache global variable bugfix

### PR DESCRIPTION
**Pull request by clementkng**
#### Reference issue

Supersedes and closes gh-2884
#### What does this implement/fix?

Replaced _`curfit_cache` global variable with optional user-passed `cache` variable.

### CODE REVIEW

**Comment by ev-br** [comment]
Looks good. Thanks @clementkng 
Might want to add a short note to https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.4.0

**Comment by larsoner** [comment]
It looks like this probably is causing new failures on AppVeyor on other PRs, e.g.:

https://ci.appveyor.com/project/scipy/scipy/builds/26302160
https://ci.appveyor.com/project/scipy/scipy/builds/26307892

Maybe an error that only occurs some of the time?

**Comment by ev-br** [comment]
Hmm... I restarted the Appveryor build of https://github.com/scipy/scipy/pull/10546
Do you know how to get more details from Appveyor? I cannot reproduce the failure locally, and did not manage to find e.g. a traceback from a failed test.

**Comment by pv** [comment]
There's a Python-level traceback in https://ci.appveyor.com/project/scipy/scipy/builds/26307892:
```
Current thread 0x00000044 (most recent call first):
  File "C:\Python37-x64\lib\site-packages\scipy\interpolate\_fitpack_impl.py", line 970 in bisplrep
  File "C:\Python37-x64\lib\site-packages\scipy\interpolate\tests\test_fitpack.py", line 430 in test_cache_argument
  File "C:\Python37-x64\lib\site-packages\_pytest\python.py", line 165 in pytest_pyfunc_call
...
```

**Comment by pv** [comment]
Among other things, there seems to be also `_surfit_cache` global variable in bisplrep, and those were not properly changed in this PR.

Since these features never worked before, they would need more extensive tests than what's there now, to verify this stuff even works as promised. E.g. compare the results "computed for new s" to those computed from scratch for that s. They probably don't agree exactly, but some criterion probably can be used to check the results make sense.

**Comment by clementkng** [comment]
@pv I wasn't sure if I should remove the `_surfit_cache` global variable, but I will. I'm not sure if I can do that in the original PR (since it's merged), or do I need a new PR? Also, is the comparison between the new tests for `s` mean that we want the results using the `cache` and not using the `cache` argument to be comparable, or is this testing a different thing?

@ev-br Do I edit the Release note entries page directly?

**Comment by pv** [comment]
@clementkng: you'll need a new PR (and new branch). For the tests, what I mean it would be necessary to find out how the "task=0" and "task=1" stuff is properly used, and then add tests that check they produce the expected output. One way to do that could be to check against the result produced without `cache=`, but it will not necessarily be exactly the same, in which case it's necessary to find some other way to check whether the result is as expected.

**Comment by larsoner** [comment]
Maybe we should revert for now so that the CIs can be reliable again?

**Comment by ev-br** [comment]
OK, here's a revert PR: https://github.com/scipy/scipy/pull/10560

@clementkng if gh-10560 is merged, you can just send a new PR with all changes, including the ones from gh-10500. Or work on top of your `p3trus-splrep-bugfix` branch, and send a PR from it, whichever is easier for you.

**Pull request merged**
