### PR TITLE
DEP: stats: switch kendalltau to kwarg-only, remove initial_lexsort kwarg

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

#15765
follow up to https://github.com/scipy/scipy/issues/16388 https://github.com/scipy/scipy/pull/18936
#### What does this implement/fix?

These changes are scheduled for this release

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
LGTM! Do we want to start adding expired deprecations to the wiki release notes after merge just in case we forget again?

**Comment by j-bowhay** [comment]
> LGTM! Do we want to start adding expired deprecations to the wiki release notes after merge just in case we forget again?

Yes, that's what I have been doing so far

**Comment by lucascolley** [comment]
I checked the diff of the previous PRs and CI is happy, thanks Jake!

**Comment by mdhaber** [comment]
Thanks @j-bowhay @lucascolley !

**Pull request merged**
