### PR TITLE
CI: uninstall oclint

### LINKED ISSUE #8192: OSX builds failing
xref travis-ci/travis-ci#8826

### PR DESCRIPTION
**Pull request by ghost**
Closes #8192

### CODE REVIEW

**Comment by andyfaff** [comment]
Do you have any info for why it needs to be removed?

**Comment by xoviat** [comment]
xref travis-ci/travis-ci#8826

**Comment by xoviat** [comment]
It looks like this fix worked. Do you know why pushd builds is returning -1?

**Comment by andyfaff** [comment]
> It looks like this fix worked. Do you know why pushd builds is returning -1?

See travis-ci/travis-ci#8703

**Pull request merged**
