### PR TITLE
MAINT: linalg: make handling of infinite eigenvalues in `ordqz` explicit

### PR DESCRIPTION
**Pull request by person142**
When there are infinite eigenvalues the sorting functions in `ordqz`
end up dividing by zero. This PR modifies the sort functions to handle
the infinite eigenvalue case explicitly, adopting the convention that
infinite eigenvalues do not lie in the left-hand plane or the
right-hand plane, but they do lie outside the unit circle.

This silences some zero division warnings and resolves an ambiguity
for left-hand and right-hand plane sorting: before the eigenvalue
-1.0/0 was considered to lie in the left-hand plane and the
eigenvalue 1.0/0 was considered to lie in the right-hand plane despite
the fact that both correspond to the complex point at infinity.

### CODE REVIEW

**Comment by ilayn** [comment]
I'm just passing by but shouldn't this information be shown to user since an infinite value means the deflation was not succesful? In a perfect world those should be deflated out anyways. 

Does it classify a huge number or actual `Inf` when it complains ?

**Comment by person142** [comment]
The decomposition is succeeding; an infinite eigenvalue just amounts to a solution of `beta*A*x = alpha*B*x` in which `beta = 0` (i.e. `(alpha, beta)` is complex projective infinity). The problem comes from the sort functions considering the quantity `alpha/beta` when `beta = 0`: it made unnecessary noise and didn't necessarily get correctly interpreted as the point at infinity. Nothing is hidden from the user though since they get `alpha` and `beta` back.

**Comment by ilayn** [comment]
No I mean, the algorithm if decides so, explicitly places a zero to get a proper infinity and separates from the finite subblock (GUPTRI and so on). 

I was wondering if it is complaining about small noise giving 1e16-18s or spot on zero. I understand that when it is perfectly zero you want to silence them, I was just curious about the motivation.

**Comment by person142** [comment]
@ilayn apologies, I misunderstood your question. It is complaining about spot-on zero.

**Pull request merged**
