### PR TITLE
CI: bump gcc from 4.8 to 6

### PR DESCRIPTION
**Pull request by h-vetinari**
Rebased @mckib2's #13347 (without the openblas commit); now that manylinux1 is gone from the wheel builder repo (cf. https://github.com/MacPython/scipy-wheels/pull/141)

Closes #13347

### CODE REVIEW

**Comment by h-vetinari** [comment]
Bumped to GCC 6 (which ends up installing 6.5), as this is the most reasonable next lower bound (mainly due to manylinux), see discussion leading up to [this](https://github.com/scipy/scipy/pull/13347#issuecomment-974098145).

**Comment by h-vetinari** [comment]
Adding this to the 1.8 milestone so it will at least be discussed. :)

**Review by tylerjereddy — APPROVED** [review]
Ralf was already "ok" with trying this in that linked discussion and `1.8.x` will probably have at least two release candidates, so let's try it. The CI is passing.

I guess this means people can also use even crazier C++ stuff..

**Comment by tylerjereddy** [comment]
thanks

**Comment by h-vetinari** [comment]
> I guess this means people can also use even crazier C++ stuff..

If C++14 is your idea of a wild ride, then that is now possible! ;-)
See #15045

**Comment by mckib2** [comment]
Glad to see this go through, thanks @h-vetinari!  Indeed, I find C++17 has lots of nice quality of life improvements

**Comment by h-vetinari** [comment]
> Glad to see this go through, thanks @h-vetinari! Indeed, I find C++17 has lots of nice quality of life improvements

Glad to hear it! Careful though, C++17 is not yet supported - people were not yet comfortable with bumping the GCC minimum version high enough to do that. Details in [toolchain](https://github.com/scipy/scipy/blob/master/doc/source/dev/toolchain.rst) resp. https://github.com/scipy/scipy/pull/15045

**Pull request merged**
