### PR TITLE
CI: remove Azure sdist job

### PR DESCRIPTION
**Pull request by andyfaff**
The GHA `linux_meson` workflow already does a couple of tests from an sdist, `test_venv_install` and ` python_debug`. We can therefore remove it from the Azure setup.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
If we remove `sdist` stuff from Azure, shouldn't we also remove stuff like:

 `ci/azure-travis-template.yaml:- ${{ if eq(parameters.use_sdist, true) }}:`

> The GHA linux_meson workflow already does a couple of tests from an sdist, test_venv_install and  python_debug

Sorry, maybe I'm just missing it from a quick check, but I don't see them doing that? I see `python3-dbg -m build --wheel` and `python -m pip install .`.  I don't think I actually see `python -m build --sdist ...` anywhere on the GHA side just yet?

**Comment by andyfaff** [comment]
You're correct @tylerjereddy, I'll make amends.

The [`pypa-build` docs](https://pypa-build.readthedocs.io/en/latest/#python--m-build) say

> **python -m build**
A simple, correct Python build frontend. By default, a source distribution (sdist) is built from {srcdir} and a binary distribution (wheel) is built from the sdist. This is recommended as it will ensure the sdist can be used to build wheels.

The `python_debug` job uses build, but I think I need to remove the --wheel flag. That will build the wheel from the sdist.

The windows.yml [`full_build_sdist_wheel`](https://github.com/scipy/scipy/blob/main/.github/workflows/windows.yml#L118) is definitely building the wheel from an sdist.

**Comment by rgommers** [comment]
Two different jobs going the vcs->sdist->wheel route seems reasonable to me. There is very little chance that the sdist creation is platform-dependent, but also not 100% impossible (e.g., a generated file containing the git hash of the commit being built somehow working differently on Windows).

**Comment by andyfaff** [comment]
@tylerjereddy the most recent commit should have it following the vcs->sdist->whl route for the `linux_meson::python_debug` job. I'd prefer not to remove sdist related cruft from the ci/azure-pipelines.yml template. It makes more sense to me to wait for when the files are removed completely, which shouldn't be too much longer.

**Comment by andyfaff** [comment]
Also, the Windows 64 bit/no pythran job is already in `windows.yml:: full_build_sdist_wheel`, so remove that as well. The windows.yml jobs examine 3.9/3.10/3.11 whilst all doing different types of build.

**Comment by andyfaff** [comment]
https://github.com/scipy/scipy/actions/runs/4791999712/jobs/8523033610?pr=18351#step:4:26 shows that the `python_debug` job is building from sdist.

**Comment by rgommers** [comment]
> I'd prefer not to remove sdist related cruft from the ci/azure-pipelines.yml template. It makes more sense to me to wait for when the files are removed completely, which shouldn't be too much longer.

Seems fine, and that'd be the way I would have gone as well.

**Review by rgommers — APPROVED** [review]
LGTM, thanks @andyfaff. And thanks for the review @tylerjereddy

**Pull request merged**
