### PR TITLE
CI: simplify Pythran configuration setup for Azure

### PR DESCRIPTION
**Pull request by serge-sans-paille**
According to distutils documentation, the CFLAGS environment variable is
honored.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Depends on https://github.com/serge-sans-paille/pythran/pull/1741 and https://github.com/serge-sans-paille/pythran/pull/1742

**Comment by rgommers** [comment]
`CFLAGS` should be honored indeed. You are dropping `/std:c++14` here, is that on purpose?

**Comment by serge-sans-paille** [comment]
Well it's not dropped, it no longer needs to be replicated from the default `pythran-win32.cfg`

**Comment by serge-sans-paille** [comment]
PR updated, but it requires a release on Pythran side

**Comment by rgommers** [comment]
> PR updated, but it requires a release on Pythran side

Thanks, this looks helpful. Can you change this PR to "draft"status to signal it cannot be merged yet?

**Comment by mdhaber** [comment]
Are the Windows CI failures related to this PR, or is there something in master? 

We're seeing the same ""No module named 'scipy'" in gh-13732, too, but it's for all four Windows CI checks there. Are you able to tell whether it's something wrong in that PR?

**Comment by rgommers** [comment]
> We're seeing the same `ModuleNotFoundError: No module named 'scipy'` in [gh-13732](https://github.com/scipy/scipy/pull/13732), too

answered in https://github.com/scipy/scipy/issues/13464#issuecomment-808007208

**Comment by serge-sans-paille** [comment]
@rgommers Pythran release done, all tests are now green. I'm very happy of this patch, it should make everything work « out of the box »

**Review by rgommers — APPROVED** [review]
This is very helpful, thanks @serge-sans-paille!

**Pull request merged**
