### PR TITLE
Travis CI: Add Python 3.7 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
Python 3.7 must run with sudo on xenial travis-ci/travis-ci#9069

### CODE REVIEW

**Comment by andyfaff** [comment]
I'm addressing this in #8988

**Comment by cclauss** [comment]
OK.  Should I close this one?

**Comment by andyfaff** [comment]
I guess I was just trying to say that someone was on it.

**Comment by cclauss** [comment]
Closing in favor of #8988

**Comment by ilayn** [comment]
Thanks @cclauss marking as duplicate just in case

**Pull request closed without merging**
