### PR TITLE
MAINT: update contributor name mapping

### LINKED ISSUE #4774: Update contributor list for v0.16
I'm in the process of updating the contributor name mapping in `tools/authors.py`.

@ldamewood, @levelfour,  @plafl, @RoyalTS, @terrycojones: I found your full name in your Github profile. Do you agree to have your full name included in the upcoming v0.16 release notes?

@argriffing Are you the person behind the committer "Perry" (e.g., ca35e25)?

@Andreea-G, @axiru, @kshramt, @I--P, @newman101, @perimosocordiae: I could not find your full names in your Github profiles.  Please let me know with which name you want to be listed in the release notes.

### PR DESCRIPTION
**Pull request by andreas-h**
fixes #4774

### CODE REVIEW

**Comment by rgommers** [comment]
I cancelled the TravisCI run, no code in this PR.

**Comment by rgommers** [comment]
@andreas-h I have a few minor tweaks in https://github.com/rgommers/scipy/commit/70254f8d72c467978bb256c3e24ad9ab0e3519ba - consistently start Github handles with ``@``, capitalization and removing affiliation (which is already in THANKS.txt). If that looks OK I'll squash and merge it.

**Comment by andreas-h** [comment]
In #4774, Irvin Probst @I--R has explicitly asked for his  affiliation to be named along his name. Apart from that, I'm fine with your corrections.

**Comment by rgommers** [comment]
I know, but I'd much rather keep the affiliation in THANKS.txt, that's where we have that for multiple people and institutions. In a release announcement it looks a bit odd.

**Comment by andreas-h** [comment]
Okay, sure, understood.  Go ahead!

**Comment by rgommers** [comment]
Merged in 02f1eb6, thanks Andreas.

**Pull request closed without merging**
