### PR TITLE
BUG: io: Fix savemat compression OverflowError

### PR DESCRIPTION
**Pull request by eternia478**
1. Pre-compute byte counting to write data sequentially.
2. Fix savemat OverflowError issue from compressing large matrices.
3. Optimization to decrease memory usage for Fortran-contiguous arrays.

### CODE REVIEW

**Comment by eternia478** [comment]
Stupid bug, forgot to commit. Trying again.

**Comment by pv** [comment]
Note that you can `git push -f` to update the previous PR --- you can use the same one rather than reopening new for each change.

**Comment by ewmoore** [comment]
Not just can you use the same one, please do use the same one unless there
is a good reason not to do so.

**Comment by eternia478** [comment]
Given that I've already submitted a new PR, let's just use the new one for now unless I can merge/delete them all. I'll just reuse the PR next time.

**Pull request closed without merging**
