### PR TITLE
ENH: optimize: add HiGHS methods to linprog

### PR DESCRIPTION
**Pull request by mdhaber**
I accidentally merged gh-11759 prematurely then reverted in gh-12032.

We tried to create a new PR to replace gh-11759, but the diffs were wonky (see gh-12033, gh-12034).

Apparently [a solution is to revert the revert](https://stackoverflow.com/questions/41516743/github-does-not-recognize-changes-from-a-reverted-pull-request), so this reverts scipy/scipy#12032.

gh-11759 was a huge improvement to `linprog` and all tests were passing. We were just putting on some finishing touches and waiting for additional reviews. Should we merge this and work from there?

### CODE REVIEW

**Comment by mdhaber** [comment]
@rgommers @pv We're in a bit of a pickle. Can you advise?

**Comment by mckib2** [comment]
Travis CI is still failing since it doesn't have [latest](https://github.com/mckib2/scipy/tree/fix-PR)

**Comment by pv** [comment]
This adds the code back to master, so unless you think it's ready, we do not merge this.

You should start the new pull request by reverting the revert, and working from there. For example, you can continue working on it in this PR.

**Comment by mdhaber** [comment]
Thanks very much @pv. I eventually came to that conclusion but it took me a while to get past the shock of unexpected diffs and the weirdness of reverting a revert.

**Comment by pv** [comment]
We could have force-pushed the commit away from master, but now there are more commits added so it's probably better to just leave the revert in there.

**Comment by mdhaber** [comment]
Yeah, hopefully there is not a next time, but in the future I'll wait on corrective action until I can discuss with someone. (For obvious reasons, I wouldn't be comfortable force-pushing to master.) Revert was a knee-jerk reaction.

I'm closing this one so we can develop on my fork.

**Pull request closed without merging**
