### PR TITLE
ENH: stats.bartlett: add axis / nan_policy / keepdims support

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Toward gh-14651

#### What does this implement/fix?
Adds axis / nan_policy / keepdims support to `scipy.stats.bartlett`.

#### Additional information
Similar to `ansari` (gh-19371), for Nd input, `bartlett` returns a scalar result. However, the result seems to be garbage - it's different from `axis=None` / raveling the arrays before passing them to the function. So I think it's safe to let `axis=0` be the default since there's no useful behavior to maintain.

### CODE REVIEW

**Comment by mdhaber** [comment]
@tirthasheshpatel if this looks good other than the merge conflict, I think it will be safe to resolve it and commit with `[skip ci]`.

**Review by tirthasheshpatel — APPROVED** [review]
LGTM! Feel free to just merge main and skip ci.

**Comment by mdhaber** [comment]
Oops, when resolving merge conflicts using the web interface, it doesn't allow you to change the commit message : /

**Comment by tirthasheshpatel** [comment]
No worries, I just merged so the runs should be cancelled.

**Pull request merged**
