### PR TITLE
ENH: Improve MLE for von Mises distribution (`vonmises.fit`) 

### PR DESCRIPTION
**Pull request by jjerphan**
#### Reference issue
Treats #11782, see this [comment](https://github.com/scipy/scipy/issues/11782#issuecomment-633188975).

#### What does this implement/fix?

Improve stability maximum likelihood estimation of the von Mises distribution.

#### Additional information

Currently deriving an analytical expressions of ML estimators with scipy's generic parametrization.

### CODE REVIEW

**Comment by jjerphan** [comment]
I started some notes for the MLE derivation here:
https://hackmd.io/@jjerphan/scipy-13435

**Comment by jjerphan** [comment]
I am currently trying to find a way to solve the optimisation problem, taking into account the supports of `scale` and `kappa`.

**Comment by mdhaber** [comment]
@jjerphan Are you interested in continuing this?

**Comment by jjerphan** [comment]
I do not have time, at least yet to pursue it.

Hence closing it for now.

**Comment by mdhaber** [comment]
Hope things calm down! Thanks for your help!

**Pull request closed without merging**
