### PR TITLE
MAINT: Minor changes in solve_bvp

### PR DESCRIPTION
**Pull request by nmayorov**
1. Renamed 'res' to 'rms_res' in the return bunch. The name 'res' bothered me because of its ambiguity. Very minor, but still.
2. Several fixes in the docstring.

Another thing to consider: whether to allow `*args, **kwargs` parameters to pass into `fun`, `bc`, `fun_jac`, `bc_jac`. Four different callables and the optional parameter `p` make it somewhat clumsy to introduce. So I'm neutral about this addition. @pv @ev-br can you help to decide?

### CODE REVIEW

**Comment by pv** [comment]
In general related to naming: avoiding abbreviations can be useful --- `sol.rms_residual` can be clearer to read than `sol.rms_res`.

Several Scipy routines take in the `args`, but the user can always use `lambda` to do the same.

**Comment by nmayorov** [comment]
> In general related to naming: avoiding abbreviations can be useful --- sol.rms_residual can be clearer to read than sol.rms_res. 

It doesn't look consistent with other short names though, why not to use `solution` instead of `sol` then (etc.)? Also `residuals` is a rather special term, it doesn't tell a user whole lot about what these values are. I don't mind renaming them as `rms_residuals`, just not sure. And it doesn't really matter... probably I shouldn't think about such things at all.

OK, @ev-br maybe you can decide?

> Several Scipy routines take in the args, but the user can always use lambda to do the same.

In this particular case I think it's better to ask users to use lambas whether they need extra arguments.

**Comment by ev-br** [comment]
FWIW, I like `rms_residual` better than `rms_res`.

**Comment by nmayorov** [comment]
I thought that `rms_residuals` would be more correct. So I think it can be merged, as the changes are cosmetic.

**Pull request merged**
