### PR TITLE
addition of rankine conversions in constants

### PR DESCRIPTION
**Pull request by Gillu13**
Hello,

I did small additions to the `scipy.constants` module: I added converting functions from Rankine scale to other temperature scales and vice versa.

This might be useful since many people keep using this scale.

### CODE REVIEW

**Comment by rgommers** [comment]
@Gillu13 in principle I'm fine with adding this scale, but I think adding 6 functions is too much. It also makes it even more expensive (in terms of # of funcs) to add more scales - what if someone else needs the Romer scale tomorrow? Therefore I think if this is added, a single function ``convert_temperature(degrees, scale, newscale)`` or some such name would be better.

Can you bring this up on the scipy-dev mailing list? That's where we decide on adding new features.

**Comment by Gillu13** [comment]
@rgommers sorry I was out of town for a little while. I see your point. OK I'll bring this up on the scipy-dev mailing list.

**Comment by FRidh** [comment]
*I just attempted to reply to this issue on the mailing list but unfortunately my reply was again rejected by the mail server.*

I agree with Ralf. These are a lot of extra, trivial, functions. Furthermore, functions like C2F don't tell me anything as to what it does. Therefore I would suggest a function name that actually describes what it does, e.g. `convert_temperature(value, old_scale, new_scale)` as Ralf suggested or perhaps `convert_temperature(old_scale, new_scale)(temperature)`. I like the latter since often you only do one type of conversion and this way you just reuse the converter. Of course you can always achieve this using partial or lambda.

**Comment by rgommers** [comment]
@FRidh did you send your email from a Gmail account? There was just another report of rejected mail here: https://github.com/numpy/numpy/issues/7238

**Pull request closed without merging**
