### PR TITLE
DOC: interp2d class description

### PR DESCRIPTION
**Pull request by ionelberdin**
Returns section seems not only unnecessary, but also misleading.

### CODE REVIEW

**Comment by rgommers** [comment]
Makes sense, what ``Returns`` says now is confusing. It would be good to add to the first paragraph a clearer link to ``interp2d.__call__`` though - because that docstring does clearly explain the return values obtained from using the callable.

**Comment by rgommers** [comment]
@ionelberdin you have two merge commits in this PR that need removing (by rebasing on master), and you have inserted tabs in the code instead of spaces which causes the test failure.

**Comment by ionelberdin** [comment]
@rgommers sorry for the accidental tab I inserted, I've just corrected that.
Regarding the two merge commits, I was trying to update my local branch before making any change in order to push a clean commit in the end. What do I need to do make that right?
Thank you for your patience.
Cheers.

**Comment by pv** [comment]
```
git fetch origin
git rebase origin/master
git push -f
```

**Comment by ionelberdin** [comment]
@rgommers values_x doesn't seem a correct descriptive name for the return value. In any case it would make more sense a variable named values_z, or simply z, with shape: (len(yi), len(xi)), like in the description of the __call__ method, which is quite well explained.

**Comment by pv** [comment]
See also
https://docs.scipy.org/doc/numpy-dev/dev/gitwash/development_workflow.html

**Comment by ionelberdin** [comment]
Thank you @pv, I'll read those guidelines carefully and follow them from now on!

**Comment by ionelberdin** [comment]
HI @pv and @rgommers 
Is there anything else I need to do?
I already did what you told me.
Cheers!

**Comment by pv** [comment]
@ionelberdin: please see the comment(s) above on rebasing https://github.com/scipy/scipy/pull/5875#issuecomment-186828083

**Comment by pv** [comment]
anyway, pushed in 0fbef6d, thanks for the correction

**Pull request closed without merging**
