### PR TITLE
MAINT: remove scipy.weave submodule

### PR DESCRIPTION
**Pull request by rgommers**
`scipy.weave` has been deprecated since 0.15.0. It has been available as a standalone package (https://github.com/scipy/weave) for 2.5 years now. So I think it's time to remove it.

I will mention this on the mailing list as well.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
LGTM, +1 for merge but you somehow already need a rebase

**Comment by rgommers** [comment]
yeah, release notes are annoying for merging.

will rebase once the mailing list message has gone through, so that we can merge quickly after it

**Comment by rgommers** [comment]
Three +1's in total and no complaints. Here is the mailing list thread for reference: https://mail.scipy.org/pipermail/scipy-dev/2016-September/021534.html

**Comment by person142** [comment]
Merging before it needs another rebase then.

**Pull request merged**
