### PR TITLE
BUG: various errors in weight calculations in orthogonal.py

### LINKED ISSUE #4683: special.orthogonal.he_roots() gives halved weights in 0.15 compared to 0.14
Is this expected behaviour? I could not find anything in the changelog, my excuses if I missed it.

```
In [15]: import scipy

In [16]: scipy.__version__
Out[16]: '0.14.0'

In [17]: n, w = scipy.special.orthogonal.he_roots(3)

In [18]: w
Out[18]: array([ 0.41777138,  1.67108552,  0.41777138])

In [19]: w.sum()
Out[19]: 2.5066282746310002
```

```
In [7]: import scipy

In [8]: scipy.__version__
Out[8]: '0.15.1'

In [9]: n, w = scipy.special.orthogonal.he_roots(3)

In [10]: w
Out[10]: array([ 0.20888569,  0.83554276,  0.20888569])

In [11]: w.sum()
Out[11]: 1.2533141373155003

In [12]: w.sum() * 2
Out[12]: 2.5066282746310007
```

### PR DESCRIPTION
**Pull request by ewmoore**
Some of these bugs came with gh-3941, some (c_roots, s_roots at least) predate that work.

Fixes gh-4683.

### CODE REVIEW

**Comment by pv** [comment]
Can you modify `verify_gauss_quad` so that it calculates integral for some test function using the roots and weights, and compares the result to integrate.quad.

This probably catches the normalization error in the `he_root` weights, which does not seem to be currently detected because the result is normalized...

**Comment by josef-pkt** [comment]
can you mark this as a possible backport candidate to fix 0.15.x ?

I have gaussian quadrature code using `he_roots`  and `h_roots` that never made it into statsmodels. We might have a GSOC project that needs gaussian quadrature weights, and it would be nicer to have correct he_roots across scipy versions.
(We can use h_roots instead of he_roots in statsmodels, now that we know.)

**Comment by ewmoore** [comment]
@pv, requested test added.

**Comment by ewmoore** [comment]
This needs rebased since #4587 was merged.  @pv, do you have any thoughts on what to do here? The two commits here ought to back port cleanly, but if I rebase them on the current master branch they won't.

**Comment by pv** [comment]
Probably easiest to open a separate pull request against the 0.15.x branch.

**Comment by ewmoore** [comment]
Rebased.

**Comment by ewmoore** [comment]
PR against maintenance/0.15.x here: #4700

**Comment by ewmoore** [comment]
This has had a month to cook.  I'm going to merge it now.  This is a gotta-have for 0.16.

**Comment by rgommers** [comment]
Thanks @ewmoore.

Anyone have an objection to hitting the green button on the 0.15.x backport of this PR now?

**Pull request merged**
