### PR TITLE
DOC: Release notes to reflect the new covariance feature in optimize.curve_fit

### PR DESCRIPTION
**Pull request by surhudm**
This pull request changes the release notes from 0.19.0 to reflect the new covariance feature added in optimize.curve_fit by #6493

### CODE REVIEW

**Comment by nmayorov** [comment]
I suggest to add your name to "Authors" in the release notes. Also to THANKS.TXT if you want to.

**Comment by ev-br** [comment]
Authors section in the release notes is autogenerated, see tools/authors.py.

**Comment by nmayorov** [comment]
Wow, I didn't know about that)

**Comment by surhudm** [comment]
@nmayorov Added to THANKS.txt now. Please merge once you are ok.

**Pull request merged**
