### PR TITLE
BUG: special: some fixes for `lambertw`

### PR DESCRIPTION
**Pull request by person142**
This:

- Cleans up the code for `lambertw` to make it more readable. In particular, special cases are moved to the beginning of the function and the branch cut logic for the initial guess is simplified
- Fixes the `lambertw` mpmath tests, which were not actually checking the majority of the test points (`nan_ok = True` strikes again).
- Prevents overflow in the Halley iterations by being careful about exponentials

### CODE REVIEW

**Comment by pv** [comment]
one failing doc example

**Comment by person142** [comment]
Ok, went ahead and did the initial guess for `W(z, 0)` correctly (implemented Pade approximation, series expansion around branch point). There's `_precompute/lambertw.py` for exploring the decision boundaries between the methods. Also here's a gist exploring one of the old high-error areas:

https://gist.github.com/person142/7d585322ec919689b2be439e955b48e7

`W(z, -1)` and `W(z, 1)` TBD.

**Comment by person142** [comment]
And just to be clear, by "TBD" I mean not in this PR (which seems large enough already).

**Comment by pv** [comment]
Thanks, read it through and looked ok (indeed I thought this was in WIP stage).

**Pull request merged**
