### PR TITLE
BUG: fix overflow bug in stats.tiecorrect

### LINKED ISSUE #5553: stats.tiecorrect overflows
```python
>>> import numpy as np
>>> from scipy import stats
>>> ntie, k = 2000, 2
>>> a = np.repeat(np.arange(k), ntie)
>>> n = a.size  # ntie * k
>>> ranks = stats.rankdata(a)
>>> 1.0 - k * (ntie**3 - ntie) / float(n**3 - n)
0.750000046875003
>>> stats.tiecorrect(ranks)
0.9513266514579157
```

However, if u apply this patch:

```diff
diff --git a/scipy/stats/_rank.pyx b/scipy/stats/_rank.pyx
index 2851baa..a309663 100644
--- a/scipy/stats/_rank.pyx
+++ b/scipy/stats/_rank.pyx
@@ -57,7 +57,7 @@ def tiecorrect(rankvals):

     """
     cdef np.ndarray[np.float64_t, ndim=1] ranks
-    cdef unsigned int i, inext, n, nties, T
+    cdef long long i, inext, n, nties, T
     cdef np.ndarray[np.intp_t, ndim=1] order
     cdef np.ndarray[np.float64_t, ndim=1] sorted_
     cdef double factor
```

result would be correct:

```python
>>> stats.tiecorrect(ranks)
0.750000046875003
```

### PR DESCRIPTION
**Pull request by larsmans**
This is #5554 with a simplification suggested in the review by @ev-br. Closes #5553. It's about equally fast on @behzadnouri's benchmark and produces the same numbers.

### CODE REVIEW

**Comment by behzadnouri** [comment]
why don't you add your comments/commits on original pr instead of opening a new one?

**Comment by larsmans** [comment]
This seemed to be the easiest and quickest option.

**Comment by behzadnouri** [comment]
no, it is not.

aside from being appropriate or not, one has to go to two different pr's to track back the change history.

plus, your code is adding a bug in a corner case. check my comment in the other pr to see when that happens.

**Comment by larsmans** [comment]
Ok, calm down, I'll send you a patch with a fixed version.

**Comment by ev-br** [comment]
For the record, it's perfectly fine to rebase somebody else's PR, add your commits, and submit it as a separate PR, as long as the commit authorship is preserved. The elementary unit of attribution is a commit, and pull requests are just a nice syntactic sugar Github provides for us. Whichever PR is finally merged, the commit history is going to be essentially the same, and commit authorship will be exactly the same.

In future we might or might not use github (or git itself), but we will keep the commit history, just like we do for commits from before github and even before git.

**Comment by larsmans** [comment]
I didn't actually rebase, but I did notice that I used an outdated version of @behzadnouri's commit and I only noticed that when setting up the PR behzadnouri/scipy#1.

**Pull request closed without merging**
