### PR TITLE
ENH: modernise some Fortran code, needed for nagfor compiler

### LINKED ISSUE #13222: porting scipy's Fortran code to NAG's nagfor compiler
After the recently merged numpy's https://github.com/numpy/numpy/pull/17950 `nagfor` still cannot compile all of `scipy`'s Fortran code.

Using numpy's master with the PR just mentioned in, one still gets:
```
$ python3 setup.py build -j 1 config_fc --fcompiler=nagfor install --prefix $HOME/.local
...
nagfor:f77: scipy/integrate/odepack/srcma.f
Option warning: -c option specified twice, continuing
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Evaluation trial version of NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Obsolescent: scipy/integrate/odepack/srcma.f, line 1: Fixed source form
Obsolescent: scipy/integrate/odepack/srcma.f, line 27: DO 10 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 29: DO 15 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 32: DO 20 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 34: DO 25 ends neither with CONTINUE nor ENDDO
Error: scipy/integrate/odepack/srcma.f, line 36: First subscript (49) is greater than upper bound (1) for array ISAV
Error: scipy/integrate/odepack/srcma.f, line 37: First subscript (50) is greater than upper bound (1) for array ISAV
Obsolescent: scipy/integrate/odepack/srcma.f, line 42: DO 110 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 44: DO 115 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 47: DO 120 ends neither with CONTINUE nor ENDDO
Obsolescent: scipy/integrate/odepack/srcma.f, line 49: DO 125 ends neither with CONTINUE nor ENDDO
Error: scipy/integrate/odepack/srcma.f, line 51: First subscript (49) is greater than upper bound (1) for array ISAV
Error: scipy/integrate/odepack/srcma.f, line 52: First subscript (50) is greater than upper bound (1) for array ISAV
[NAG Fortran Compiler error termination, 4 errors, 9 warnings]
```

This one is easy to fix (apparently natfor does not grok `dimension`?):
```diff
diff --git a/scipy/integrate/odepack/srcma.f b/scipy/integrate/odepack/srcma.f
index 62c07a571..aa3ba1e22 100644
--- a/scipy/integrate/odepack/srcma.f
+++ b/scipy/integrate/odepack/srcma.f
@@ -11,12 +11,11 @@ c        job  = 1 if common is to be saved (written to rsav/isav)
 c        job  = 2 if common is to be restored (read from rsav/isav)
 c        a call with job = 2 presumes a prior call with job = 1.
 c-----------------------------------------------------------------------
-      integer isav, job
+      integer isav(*), job
       integer ieh, ils, ilsa
       integer i, lenrls, lenils, lenrla, lenila
-      double precision rsav
+      double precision rsav(*)
       double precision rls, rlsa
-      dimension rsav(1), isav(1)
       common /ls0001/ rls(218), ils(39)
       common /lsa001/ rlsa(22), ilsa(9)
       common /eh0001/ ieh(2)
```
After this fix, the next error, not very clear either:
```
nagfor:f77: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f
Option warning: -c option specified twice, continuing
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Evaluation trial version of NAG Fortran Compiler Release 7.0(Yurakucho) Build 7036
Warning: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 850: Unused dummy variable NB
Obsolescent: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 208: Fixed source form
Error: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 666: Inconsistent structure for arg 3 in call to SVOUT
Error: scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f, line 737: Inconsistent structure for arg 3 in call to SVOUT
[NAG Fortran Compiler error termination, 2 errors, 2 warnings]
error: Command "/usr/local/bin/nagfor -fixed -O4 -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/home/dimpase/.local/lib/python3.7/site-packages/numpy-1.21.0.dev0+137.g91d9bbebc-py3.7-linux-x86_64.egg/numpy/core/include -c -c scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.f -o build/temp.linux-x86_64-3.7/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.o" failed with exit status 2
```

Any ideas for this latter?

### PR DESCRIPTION
**Pull request by dimpase**
#### Reference issue

This is the Fortran lang part, necessary to handle #13222.

#### What does this implement/fix?

We remove various non-standard/obsolete extensions and clean up few
things such as incorrect specification of formal arg array dimensions
and goto into if-then block. 

This is needed to support the use of NAG's nagfor Fortran compiler with scipy.

#### Additional information

In order to fully handle #13222  another PR will be needed.

### CODE REVIEW

**Comment by dimpase** [comment]
codecov alerts are bogus here - these Fortran lines I've changed are not "covered" by tests directly, anyway.

**Comment by rgommers** [comment]
Just a few changes in `odepack` and a bunch in `specfun` looks fine to me. I'm not much of a Fortran person so I hope someone else will give this a detailed review, but it looks okay to merge soon.

> codecov/patch alerts are bogus here

they usually are:(

**Comment by dimpase** [comment]
@certik - you suggested to create an updated fork of `odepack` to serve the community as the default upstream, right?

**Comment by dimpase** [comment]
[It seems odepack is not actively developed anymore. Like most such Fortran libraries. We want to change that in the long run (thus our `fpm` and other efforts). The best way is for somebody (you?) to create a github repository for odepack, and then put the patches there.](https://twitter.com/OndrejCertik/status/1337428755615105027)

**Comment by rgommers** [comment]
Would there be a point for `odepack`? For `arpack-ng` it makes sense, because it's still actively used in multiple places and there's lots of bugs left to squash. `fftpack` (mentioned in tweet) won't make sense anymore, because it's simply obsolete. Who uses `odepack` other than SciPy, and would there be enough to fix that just synching fixes directly between users isn't enough?

**Comment by dimpase** [comment]
Everyone who codes in Fortran and solves ODEs numerically uses it, I presume. A definitive upstream with modernisations (maybe, under scipy github org ?) is good, and I can maintain it. 

I have extensive training in Fortran (IV), you know. :-)

**Comment by dimpase** [comment]
I also see @khinsen advocate odepack. Maybe he can comment.

**Comment by rgommers** [comment]
> Everyone who codes in Fortran and solves ODEs numerically uses it, I presume. A definitive upstream with modernisations (maybe, under scipy github org ?) is good, and I can maintain it.

That sounds good, except it shouldn't live in the SciPy org - we unfortunately don't have many people who speak Fortran. How about https://fortran-lang.org/community/, that seems to have some good momentum and seems like a much better fit?

**Comment by khinsen** [comment]
@dimpase As far as I can tell from exchanges with computational scientists, odepack is still widely used. Mostly by people who write their own special-purpose Fortran code for some problem. Much of that probably never gets published, or at least never gets public attention. As Ondrej and @rgommers say, reviving maintenance of odepack as a Fortran community project is probably the best way to go.

**Comment by rgommers** [comment]
@ev-br or @ilayn can one of you have a quick glance at this? It all looks good to me, but I'm not a Fortran person. 

A license for a NAG compiler won't be forthcoming, but I think that doesn't matter - if CI is green, we can just merge this.

**Comment by ev-br** [comment]
@rgommers From a quick glance, this looks mostly harmless. Changing cdexp` to `exp` etc is similar to C++ overloaded functions from cmath, e.g. `std::exp`, so this should be OK. Assumed-array specifications look good. So if this all helps to this particular compiler, then OK. (I'm mildly surprised given the general backcompat level in the fortran land, but that's beside the point)

We should mention this in the release notes --- just in case there are issues for other exotic compilers.

**Comment by certik** [comment]
I created an issue at https://github.com/fortran-lang/fpm-registry/issues/44 to maintain ODEPACK under @fortran-lang. This all takes time, but I think we can do a good job at that, and if we do, then later on (perhaps in a year or two) we can revisit this topic how SciPy might depend on such (newly) maintained packages. The easiest way would be to simply copy the Fortran sources from the new "upstream" into the SciPy git repository (so nothing would change for the SciPy's build system and end users), and keep submitting such patches to "upstream" first.

**Comment by ilayn** [comment]
+1 for @ev-br , a heart emoji for @certik

**Comment by dimpase** [comment]
assuming we agree that this should be merged, I would need to be told what to do with codecov report.

**Comment by ev-br** [comment]
Ok, let's get this in. Thanks @dimpase , all.

**Comment by rgommers** [comment]
> We should mention this in the release notes --- just in case there are issues for other exotic compilers.

Sure. It'll go into 1.18.0, so it has 5-6 months in master. 

> assuming we agree that this should be merged, I would need to be told what to do with codecov report.

Nothing, that can just be ignored. Codecov is basically always wrong, it's a nice interface to browse coverage but failures shouldn't happen (and we haven't had any more recently).

**Comment by rgommers** [comment]
Comments crossed. Thanks for merging @ev-br. And thanks for working on this @dimpase!

**Pull request merged**
