### PR TITLE
DOC: remove broken link to scipy.stats.distributions

### PR DESCRIPTION
**Pull request by partev**
remove broken link to scipy.stats.distributions

### CODE REVIEW

**Comment by mdhaber** [comment]
Thanks @partev. Next time for a doc-only change, please include `[skip actions] [skip cirrus]` in the commit message so that only the doc-build job runs. (Nobody would have expected you to know that before, though!)

**Comment by mdhaber** [comment]
I see now that `scipy.stats.distributions` was supposed to appear on that page because it is still a public subsubpackage. The preferable fix would be to ensure it goes to a page (which may not exist yet). Would you like to make that happen?

**Review by tupui — COMMENTED** [review]
Thanks @partev but this is the expected rendering/behavior. I closing this one now as we have further plans for refactoring of the whole stats section.

**Comment by tupui** [comment]
Oh seeing your comment now Matt (again this phone caching sorry.) I will let you decide then

**Comment by mdhaber** [comment]
@tupui I know we have plans for the tutorials, but did we have plans for the API section? What did you have in mind?

**Comment by tupui** [comment]
Work for me 👍 The ball in on your side @partev 😃

**Comment by partev** [comment]
thanks for all the comments. I am going to close this since you are going to refactor this soon.

**Pull request closed without merging**
