### PR TITLE
TST: Add Boost ellipr[cdfgj]_data test data

### PR DESCRIPTION
**Pull request by sethtroisi**
Follows after https://github.com/scipy/scipy/pull/12357 adding data needed for https://github.com/scipy/scipy/pull/10504

```
git clone --depth=1 https://github.com/boostorg/math.git boostmath

rm -rf scipy/special/tests/data/boost/*

# Changed the regex
vim scipy/special/utils/convert.py

python scipy/special/utils/convert.py

# Verify all the new files are used in test_data.py
git diff --stat HEAD~ | grep "Bin 0"
git diff upstream/master -- scipy/special/tests/test_data.py
```

To keep the diff smaller I revert any whitespace-only change via this hack
```
git diff -a -w HEAD~ > test.patch
git reset --hard HEAD~
git apply test.patch
git add scipy/special/tests/data/boost
git commit -m 'MAINT,TST: Run scipy/special/utils/convert.py'
```

### CODE REVIEW

**Comment by rgommers** [comment]
LGTM. @sethtroisi it's probably useful to have those detailed instructions in `special/tests/data/README`, would that make sense to add?

**Comment by sethtroisi** [comment]
@rgommers 

> LGTM. @sethtroisi it's probably useful to have those detailed instructions in `special/tests/data/README`, would that make sense to add?

Yes, I'm working on it in a separate PR. Wording is one of my weaker strengths and it may take a couple of iterations.

Follow up question, given another core member LGTM and the simple nature of this, can I (the author) merge this assuming all checks are green? or should the author never merge their own PR?

**Comment by rgommers** [comment]
> Follow up question, given another core member LGTM and the simple nature of this, can I (the author) merge this assuming all checks are green? or should the author never merge their own PR?

For really straightforward things it's okay for people to self-merge, but I'd say the usual etiquette is to first wait for someone else to do it (say 48 hrs) and then comment that you intend to self-merge within 1-2 days. Unless there's a reason to merge immediately, like fixing broken CI.

It's a bit fuzzy, if it's a typo fix then straight away with a comment is fine. This is more a "wait a day or two" kind of thing I'd say.

Also note that on other repos, like the `scipy.org` or `scipy-cookbook` ones, self-merging PRs is fine - those repos are much less critical and less well maintained.

**Comment by sethtroisi** [comment]
Thanks for the explanation; Follow up question as a reviewer can I LGTM and immediately merge for small PRs with passing checks (e.g. a PR that fixes an issue in an obvious way)? Or should I always wait 2 hrs? 2 days? When I LGTM but wait should I add a comment to the effect of "this looks good and should be merged in 2/24/48 hrs unless anyone objects"?

I'm trying to calibrate as I'm new to remote volunteer coordination.

**Comment by rgommers** [comment]
Yes, if you're a reviewer and it's clear the PR you're reviewing is the correct fix, go ahead and merge it straight away. When it's something that could be done multiple ways or you have reason to think someone else may object or see changes, then wait some days.

**Comment by sethtroisi** [comment]
@rgommers I think this can go in (along with #12648)

**Comment by rgommers** [comment]
Indeed, thanks @sethtroisi

**Pull request merged**
