### PR TITLE
ENH: stats: absolute value of a random variable

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Toward gh-15928

#### What does this implement/fix?
SciPy's `foldnorm` and `foldcauchy` are examples of folded distributions, which "fold" the PDF from the left of the origin to the right. In terms of random variables, this corresponds with taking the absolute value. `halfnorm`, `halfgennorm`, `halflogistic`, and `halfcauchy` are are all special cases of folded distributions.

This PR adds a class that represents folded distributions and a function `abs` that takes the absolute value of a random variable. For example, if `X = stats.Normal()`, `Y = abs(X)` is distributed according to the folded normal. While I was at it, I went ahead and implemented the `__abs__` operator. We should probably still have our own `abs` function for the same reasons that NumPy includes `abs` in addition to overriding `__abs__` (probably documentation and discoverability). 

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

X = abs(stats.Normal() + 1.2)
X0 = stats.foldnorm(1.2)

x = np.linspace(-1, 5, 300)
pdf = X.pdf(x)
pdf0 = X0.pdf(x)
plt.plot(x, pdf, label='PDF underlying `X`')
plt.plot(x, pdf0, '--', label='PDF underlying `X0`')
plt.legend()
plt.title("PDF of a folded normal distribution")
plt.show()
```

{AD726DA4-D326-4FA3-883F-CB6C885F70F5}

#### Additional information
~~Together with gh-21746, this will allow us to implement `__pow__` for even values of `other`. I think gh-21746 alone is enough to implement `__rpow__`. These methods can be added in a follow-up PR.~~ Added `__rpow__` to gh-21746; with these PRs, `__pow__` is quite simple: https://github.com/mdhaber/scipy/compare/imf_transform...mdhaber:scipy:pow?expand=1

### CODE REVIEW

**Comment by rkern** [comment]
FWIW, the `np.abs` alias for `np.absolute` primarily exists for historical reasons, more or less. I probably wouldn't consider it a precedent to emulate. `__abs__` and good examples would be fine, I think.

**Review by steppi — APPROVED** [review]
This looks good @mdhaber, modulo cleaning up existing merge conflicts and those which will arise if #21746 is merged. I agree that optimizations for the symmetric case can wait. If possible, I think it would be nice to add  `__pow__` to this PR and get it in before we branch.

**Comment by mdhaber** [comment]
The merge conflicts are resolved and the code for `__pow__` is [here](https://github.com/mdhaber/scipy/compare/imf_transform...mdhaber:scipy:pow?expand=1).

**Comment by mdhaber** [comment]
Demonstration of `__pow__`.
<details>

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

X = stats.Normal()**2
X0 = stats.chi2(1)

x = np.linspace(0, 5, 300)
pdf = X.pdf(x)
pdf0 = X0.pdf(x)
plt.plot(x, pdf, label='PDF underlying `X`')
plt.plot(x, pdf0, '--', label='PDF underlying `X0`')
plt.legend()
plt.title("PDF of a Chi-squared distribution with 1 DoF")
plt.show()

</details>

I'll push a commit that fixes this for odd powers.
image

**Comment by mdhaber** [comment]
Cube of shifted normal:

<details>

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats, integrate
X = (stats.Normal()+1)**3
x = np.linspace(-1, 10, 300)
sample = X.sample(100000)
plt.plot(x, X.pdf(x), label='pdf')
plt.hist(sample, density=True, bins=x[::5], label='normalized histogram')
plt.legend()
plt.show()

ecdf = stats.ecdf(sample)
plt.plot(x, ecdf.cdf.evaluate(x), label='ecdf')
plt.plot(x, X.cdf(x), label='cdf')
plt.legend()
plt.show()

rng = np.random.default_rng(787435872347234)

p = rng.uniform(size=10)
np.testing.assert_allclose(X.cdf(X.icdf(p)), 1 - X.ccdf(X.icdf(p)))
np.testing.assert_allclose(X.cdf(X.icdf(p)), p)
np.testing.assert_allclose(X.ccdf(X.iccdf(p)), p)
```

</details>
image

image

**Pull request merged**
