### PR TITLE
TST: ensure negative weights are not allowed in distance metrics

### LINKED ISSUE #7953: Using cdist with wminkowski disagrees with wminkowski
It appears that running `cdist` using the `wminkowski` metric reports inaccurate results that disagree with running `wminkowski` on each vector combination individually. The issue goes away if the absolute value of `w` is taken before giving it to `cdist`. However this is done for the user in `wminkowski` matching the equation in the docs. Hence the disagreement. Below is an example of this behavior with details about how to install a `conda` environment that will reproduce the issue.

Example:

<details>

```python
In [1]: import numpy as np

In [2]: import scipy.spatial.distance as spdist

In [3]: np.random.seed(0)

In [4]: a_u = 2 * np.random.random((7, 6)) - 1

In [5]: a_v = 2 * np.random.random((3, 6)) - 1

In [6]: p = 1.6

In [7]: w = 2 * np.random.random(a_u.shape[-1:]) - 1

In [8]: spdist.cdist(a_u, a_v, metric="wminkowski", p=p, w=w)
Out[8]: 
array([[ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan]])

In [9]: d = np.empty((len(a_u), len(a_v)), dtype=float)
   ...: for i in range(len(a_u)):
   ...:     for j in range(len(a_v)):
   ...:         d[i, j] = spdist.wminkowski(a_u[i], a_v[j], p=p, w=w)
   ...:         

In [10]: d
Out[10]: 
array([[ 1.24606122,  1.16395049,  1.25037412],
       [ 1.84842639,  1.06442873,  1.44461084],
       [ 1.96393331,  1.98499393,  1.75982539],
       [ 1.51823304,  1.68759411,  1.87569175],
       [ 1.63240776,  1.32480509,  1.47219684],
       [ 1.50025279,  1.54607896,  1.40125501],
       [ 1.0061864 ,  1.26567631,  1.31885044]])

In [11]: spdist.cdist(a_u, a_v, metric="wminkowski", p=p, w=abs(w))
Out[11]: 
array([[ 1.24606122,  1.16395049,  1.25037412],
       [ 1.84842639,  1.06442873,  1.44461084],
       [ 1.96393331,  1.98499393,  1.75982539],
       [ 1.51823304,  1.68759411,  1.87569175],
       [ 1.63240776,  1.32480509,  1.47219684],
       [ 1.50025279,  1.54607896,  1.40125501],
       [ 1.0061864 ,  1.26567631,  1.31885044]])
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: test
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- blas=1.1=openblas
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- decorator=4.1.2=py36_0
- ipython=6.2.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_0
- libgfortran=3.0.0=0
- ncurses=5.9=10
- numpy=1.13.1=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- python=3.6.2=0
- readline=6.2=0
- scipy=0.19.1=py36_blas_openblas_202
- setuptools=36.3.0=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zlib=1.2.11=0
```

<details>

### PR DESCRIPTION
**Pull request by apbard**
Fixes #7953 by raising an exception if some weights are negative

Also:
- added missing tests for chebyshev, kulsinski, cityblock
- add weights to chebyshev

### CODE REVIEW

**Comment by rgommers** [comment]
LGTM, merged. Thanks @apbard

**Comment by rgommers** [comment]
I think that's low risk so probably a good idea. I'll look at it again when I do all the backports, but I think I'll backport it.

**Comment by pv** [comment]
What about weights that become negative only due to rounding error?

**Comment by apbard** [comment]
@pv without the check you would still get NaNs or an error in subroutines calls at the same time and I can't think of a reliable way to "correct" the weights. Do you have any suggestions?

**Comment by rgommers** [comment]
There were several questions about this implementation still and it's not super critical for 1.0.0, so I took this commit out of the backport PR again.

**Pull request merged**
