### PR TITLE
MAINT: make hann() the function and hanning the alias

### PR DESCRIPTION
**Pull request by endolith**
pedantic, but the window is named "Hann".  "Hanning" is erroneous, from being confused with Hamming.  Also, scipy.signal documentation lists "hann", not "hanning".  https://github.com/scipy/scipy/blob/4e4c8c98802698556d0b02aebab662f72f7cf19b/scipy/signal/info.py

### CODE REVIEW

**Comment by endolith** [comment]
Can we clarify somehow that `hanning` is just an alias?  There are identical pages for both that might confuse people:

https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.signal.hanning.html
https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.signal.hann.html

**Comment by rgommers** [comment]
Sure. A change like this should do it:
```
def hanning(...):
    """
    Note: `hanning` is an alias of `hann`.  See `hann` for more details
    """
    return hann(...)
```

**Comment by endolith** [comment]
@rgommers 

That doesn't work because every docstring needs to contain a Parameters line, apparently:

https://github.com/scipy/scipy/blob/master/scipy/signal/__init__.py#L342

https://github.com/scipy/scipy/pull/8148#issuecomment-343753139

(Also that error message should be clearer)

**Comment by person142** [comment]
Since we have a number of aliases floating around, it might make sense to add some sort of `alias` decorator to lib which injects the notice into the docstring.

**Comment by endolith** [comment]
@person142 Do you want to make that decorator?  https://github.com/scipy/scipy/pull/8148 and https://github.com/scipy/scipy/pull/8213 would use it

**Pull request closed without merging**
