### PR TITLE
DOC: Describe signal.find_peaks and related functions behavior for NaNs

### PR DESCRIPTION
**Pull request by lagru**
as well as a typo I noticed in THANKS.txt.

### CODE REVIEW

**Comment by lagru** [comment]
@larsoner These are only small changes to the docstring and I it would be nice to have this merged included in 1.1.0.

**Comment by lagru** [comment]
The second commit addresses the behavior of the functions if NaNs are present in the signal. This came up in #8708. It might be worth discussing whether this needs to be addressed further. It might be worth it to raise a warning message if any NaNs are encountered (a candidate for 1.2?).

**Comment by larsoner** [comment]
I don't think we need to warn so long as it's documented clearly in the
docstring. Maybe put it first in the notes, and somewhere in an example?

>

**Comment by larsoner** [comment]
+1 for `.. note` (or if you want, `.. warning` even).

I don't know of any rule of thumb. You don't want to warn too much or too little. To me this would fall into the "too much" category but this is just my subjective judgment based on expected use cases.

**Comment by lagru** [comment]
I decided not to use the `note`-directive here... it doesn't seem to be a standard in SciPy and this felt more natural.

I'll have a look and try to come up with an elegant way to deal with NaNs. Otherwise I'll add warning messages if NaNs are found in the input. In the meantime I'm hesitant to introduce any in-code changes here as I don't want to block this from being potentially merged before 1.1 branches. So that would be another PR.

**Comment by larsoner** [comment]
> I'll have a look and try to come up with an elegant way to deal with NaNs. Otherwise I'll add warning messages if NaNs are found in the input.

I am arguing against such a warning so long as the behavior of NaN is properly documented. Are you saying we should have a warning if NaN is in the input?

**Comment by larsoner** [comment]
... and actually the tests should probably be updated to test that `NaN` is handled how we say it will be handled.

**Comment by lagru** [comment]
> Are you saying we should have a warning if NaN is in the input? -- @larsoner 

Yes, unless I think of another way to deal with NaNs without completely rewriting the algorithms.

> ... and actually the tests should probably be updated to test that NaN is handled how we say it will be handled. -- @larsoner 

I agree although I don't see it as a priority because in most cases the documentation states to "expect the unexpected" if NaNs are contained in the input. I hope nobody tries to use that as a feature. :wink:  
If its okay I'll think of meaningful tests in another PR in the next few days.

**Comment by larsoner** [comment]
Since the comparisons always evaluate to False, isn't `nan` behavior then the same as (assuming all other points are finite) setting the `nan` points to `inf` but never giving those indices as peak locations?

**Comment by lagru** [comment]
Not really. If we compare a finite number to nan it is both "not smaller", "not larger" and "not equal" at the same time. That means depending on the comparator chosen at different points in the algorithm nan is treated as +inf or -inf. Replacing with either one of those values would change the behavior.

In some cases this might actually be useful but your proposed case we don't gain anything. If we replace with +inf, we find new peaks at those positions. If never return those inf-peaks we don't gain anything compared to just leaving them nan because the neighbouring samples still can't be peaks.

(Or did I misunderstand your suggested solution?)

**Comment by larsoner** [comment]
I'm not proposing a solution -- I'm trying to describe the behavior of the current algorithm for the user when their input has NaNs. If it can be distilled to something equivalent that is simple to explain to the user then we can just clearly document this behavior rather than emitting a warning. So something like "Locations with the value NaN will be treated like `np.inf` when evaluating whether immediate neighbors are peaks, but will never be returned as peak locations themselves" would work, assuming it's correct.

It might not be possible to distill the other functions like `prominence` the same way, though.

**Comment by lagru** [comment]
> It might not be possible to distill the other functions like prominence the same way, though.

Correct, those are more complicated to judge. That's why my warning in those cases was a bit more general.

**Comment by larsoner** [comment]
Ahh okay. In that case, can you make a PR to add warnings for those other functions? I agree it makes sense to have them. It would be good to have for 1.1.0 if possible. Adding them, then using `pytest.warns` context manager in the tests should be enough for now. This should still be forward-compatible with a future `nan_policy`-type argument that could try to do something smart(er).

**Comment by lagru** [comment]
> Ahh okay. In that case, can you make a PR to add warnings for those other functions?

I'll try. But if today is the deadline I have a feeling there won't be enough time left to properly review & iterate...

**Comment by lagru** [comment]
@larsoner On another note... do you consider this ready to be merged today?

**Comment by larsoner** [comment]
I can rapidly iterate today if you can :)

But more seriously 1) I don't think it should be too difficult or require too much iteration since it's warning emission, and 2) I'd also consider it a form bug fix which means that tomorrow isn't a hard deadline (can backport).

**Comment by WarrenWeckesser** [comment]
The updated docstring says

    The algorithm treats NaNs the same way as a window border and stops
    searching for an intersection possibly leading to unwanted results.

Is this the API that you *designed*, or it this an accident of the implementation (i.e. the code was not written with NaNs in mind, but if there are NaNs in the data, that is how it happens to be treated)?  If the latter, it might be safer to simply state in the docstring that "the behavior of the function with data containing NaNs is undefined".  That way there is no commitment to an API.  Then if explicit handling of NaN is added later, there is no need to worry about backwards compatbility.

**Comment by larsoner** [comment]
> If the latter, it might be safer to simply state in the docstring that "the behavior of the function with data containing NaNs is undefined". That way there is no commitment to an API. Then if explicit handling of NaN is added later, there is no need to worry about backwards compatbility.

This makes sense to me. I was probably over-engineering a bit before. I think we can just say this in all the functions for now.

@WarrenWeckesser any opinion on `.. note::` vs `.. warning::` vs no-directive for these statements?

**Comment by lagru** [comment]
> If the latter, [...]

Yes, I didn't have NaNs in mind when writing those functions so its just behavior resulting from the documentation.

> [...] it might be safer to simply state in the docstring that "the behavior of the function with data containing NaNs is undefined".

I agree, here.

**Comment by WarrenWeckesser** [comment]
No directive is probably fine, but that's not a string opinion.

**Comment by lagru** [comment]
To avoid having to wait for CI to build the doc, here the images with `.. warning::` 
[find_peaks](https://user-images.githubusercontent.com/20140352/38642682-0f683c08-3ddb-11e8-9ba2-7a247f1dc829.png),  [peak_prominences](https://user-images.githubusercontent.com/20140352/38642683-0f867ee8-3ddb-11e8-9fdf-3613712e12b8.png),   [peak_widths](https://user-images.githubusercontent.com/20140352/38642684-0fa0b178-3ddb-11e8-8b12-c2adfa6714c1.png).

**Comment by larsoner** [comment]
Looks good to me

**Pull request merged**
