### PR TITLE
MAINT: io: move `_test_fortran` under `tests`

### PR DESCRIPTION
**Pull request by lucascolley**
[skip cirrus]

An experiment towards gh-18566. I don't see why this private testing module would have to sit in the top level of `io` rather than `io/tests`, but maybe I am unaware of a reason.

### CODE REVIEW

**Comment by lucascolley** [comment]
There is a build hiccup here, but I can't tell whether that is because this idea is incorrect, or whether there's just something small missing.

**Review by tylerjereddy — COMMENTED** [review]
The diff below the fold fixed the problem for me locally. It may be that the generator process doesn't allow you to do what you want with underscore prefixes; perhaps not something you'd want to mess with in this PR.

<details>

```diff
--- a/scipy/io/tests/meson.build
+++ b/scipy/io/tests/meson.build
@@ -1,6 +1,6 @@
 py3.extension_module('_test_fortran',
   [
-    f2py_gen.process('_test_fortran.pyf'),
+    f2py_gen.process('test_fortran.pyf'),
     '_test_fortran.f'
   ],
   c_args: [Wno_unused_variable],
diff --git a/scipy/io/tests/_test_fortran.pyf b/scipy/io/tests/test_fortran.pyf
similarity index 100%
rename from scipy/io/tests/_test_fortran.pyf
rename to scipy/io/tests/test_fortran.pyf
```


</details>

**Comment by lucascolley** [comment]
that did the trick, thanks Tyler!

**Comment by ilayn** [comment]
Today another one popped up inside the tests of `scipy.integrate`. https://github.com/scipy/scipy/blob/main/scipy/integrate/tests/banded5x5.f

It's like mold growing inside the repo.

**Comment by tylerjereddy** [comment]
No further comments. Since this is more consistent with test organization in general in our project, I merged.

**Comment by WarrenWeckesser** [comment]
> Today another one popped up inside the tests of scipy.integrate. https://github.com/scipy/scipy/blob/main/scipy/integrate/tests/banded5x5.f
>
> It's like mold growing inside the repo.

Heh, I planted that mold years ago.  The comments in `banded5x5.f` explain why.

**Comment by ilayn** [comment]
> Heh, I planted that mold years ago. The comments in `banded5x5.f` explain why.

Yes, I saw that :) No worries, I was surprised that there is still `.f` files that I missed after a year looking into it.

**Comment by rgommers** [comment]
Belated comment: this PR seems fine to me (test files should ideally live under `tests/` indeed), but it doesn't really help with gh-18566. We'd want to get rid of this Fortran code completely to do that.

**Comment by lucascolley** [comment]
> it doesn't really help with https://github.com/scipy/scipy/issues/18566. We'd want to get rid of this Fortran code completely to do that.

Indeed, although I was actually thinking along the lines of gh-20712 - if somebody chooses not to install tests, this module shouldn't be installed.

**Comment by lucascolley** [comment]
By the way, would it be more idiomatic to have these lines in `integrate/tests/meson.build`?

https://github.com/scipy/scipy/blob/61f2a11cfdc07a7d167bd715aae6fe76d04c354e/scipy/integrate/meson.build#L164-L182

**Comment by ilayn** [comment]
I'd say your time is more valuable than this. If we translate that `banded5x5` file then we can do the plumbing. It is also calling LSODA so probably would waste your time to do the connection.

**Comment by lucascolley** [comment]
> It is also calling LSODA so probably would waste your time to do the connection.

Right, makes sense, better to leave it in the same directory then 👍

**Comment by h-vetinari** [comment]
This PR causes windows builds in conda-forge (using MSVC+flang) to fail: #21561

It makes no sense to me why, but the bisection is clear, and a revert of https://github.com/scipy/scipy/commit/cf664690e47bb0fed5ee1552353de42797a30b12 on top of main passes.

**Pull request merged**
