### PR TITLE
MAINT: Remove `openblas_support.py`

### PR DESCRIPTION
**Pull request by mattip**
Builds on numpy/numpy#25505 to refactor wheel building
- remove `tools/openblas_support`, use wheels instead
- refactor to use a single cibw_before_build.sh script
- move many of the CIBW env variables set in CI into pyproject.toml, which makes it easier to run cibuildwheel outside of CI and reduces some duplication
- upgrade OpenBLAS from `v0.3.20-571` (in the openblas_support script) and `v0.3.23.293` (in the ci test runs) to v0.3.26, and add a single source of truth in a `requirements/openblas_requirements.txt` file

cc@ [matthewfeickert](https://github.com/matthewfeickert)

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks Matti. Some non-existing `pip` and undefined symbols - probably worth working on a fork to get one wheel build job per OS to pass?

**Comment by mattip** [comment]
Right, it is a shame to burn so much CI. I can reproduce the failures locally. 

After the build starts to work, I am seeing
```
ImportError: <path>_fblas.cpython-311-x86_64-linux-gnu.so: undefined symbol: dznrm2_
```

This should be `scipy_dznrm2_`. I think there is some missing handling of `BLAS_SYMBOL_PREFIX` around `scipy.linalg.get_blas_funcs`

**Comment by rgommers** [comment]
> This should be `scipy_dznrm2_`. I think there is some missing handling of `BLAS_SYMBOL_PREFIX` around `scipy.linalg.get_blas_funcs`

That wouldn't be surprising, since we've never used a prefix for anything. I'm fairly sure that it'll be missing in more places. I think this is going to intersect substantially with the re-introduction of ILP64 support, which is ongoing in other branches. So we should probably pause this until ILP64 support is back.

**Comment by mattip** [comment]
OK

**Comment by mattip** [comment]
> which is ongoing in other branches

I am not sure which branches/PRs are relevant. Certainly #20510, are there others?

**Comment by rgommers** [comment]
The key one was gh-19816 (and other PRs split off from that. They're all merged now, so this PR is unblocked I believe.

There are a lot of conflicts here, and I think it's a little tricky to figure out what is relevant and what is not. It may be better to open a new PR, using an `scipy-openblas32` for a single wheel build first. Problems with the `scipy_` prefix should be common to all builds I believe, so getting it to work for a single one (x86-64 manylinux should do) with the smallest diff possible would be a great start. I suspect then the rest will not be too difficult.

**Pull request closed without merging**
