### PR TITLE
BUG: Changed zip() to list(zip()) so that it could work in Python 3 also...

### LINKED ISSUE #4527: KDTree example doesn't work in Python 3
The example in the docstring of `KDTree` doesn't work with Python 3:

```
In [47]: x, y = np.mgrid[0:5, 2:8]

In [48]: tree = spatial.KDTree(zip(x.ravel(), y.ravel()))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-48-62da5c6cfbd2> in <module>()
----> 1 tree = spatial.KDTree(zip(x.ravel(), y.ravel()))

/Users/warren/local_py34/lib/python3.4/site-packages/scipy/spatial/kdtree.py in __init__(self, data, leafsize)
    227     def __init__(self, data, leafsize=10):
    228         self.data = np.asarray(data)
--> 229         self.n, self.m = np.shape(self.data)
    230         self.leafsize = int(leafsize)
    231         if self.leafsize < 1:

ValueError: need more than 0 values to unpack
```

The problem is that in Python 3, `zip` returns an iterator, and when the `KDTree` code calls `np.asarray()` with its argument, an 'object' array with a single element is created:

```
In [49]: np.asarray(zip(x.ravel(), y.ravel()))
Out[49]: array(<zip object at 0x1082b9408>, dtype=object)
```
(In Python 2, `zip` returns a list, and `np.asarray()` creates the expected array of points.)

This was reported on stackoverlow (http://stackoverflow.com/questions/28551279/error-running-scipy-kdtree-example), where I suggested some possible changes to the docstring.

### PR DESCRIPTION
**Pull request by aman1k4**
.... Fixes gh-4527

### CODE REVIEW

**Comment by bewithaman** [comment]
@WarrenWeckesser If zip function is modified, all the functions using zip in scipy would be effected?

**Comment by pv** [comment]
Yes. However, in the actual code this was taken into account when Scipy
was ported to Python 3.

**Comment by rgommers** [comment]
Merged, thanks @bewithaman

**Comment by argriffing** [comment]
There's also a `zip` in here https://github.com/scipy/scipy/blob/master/scipy/_lib/six.py.

**Comment by rgommers** [comment]
indeed. I don't think that that's what we want here though. And I'd rather not use ``six`` in any user-visible place.

**Pull request merged**
