### PR TITLE
FIX:linalg.lu:Guard against permute_l out of bound behavior

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Related to #18751

#### What does this implement/fix?
Strangely sporadic crashes are reported with linalg.lu added for 1.11. This is to make sure that it is indeed the problem we are suspicious of. 

#### Additional information
Pinging @ogrisel @h-vetinari if you could test this version, that would be a great help for the triage.

### CODE REVIEW

**Comment by ogrisel** [comment]
I will build it an give it a try on the machine where I can reproduce the segfault.

**Comment by ogrisel** [comment]
Unfortunately I cannot reproduce the original problem when building scipy from the `v1.11.0` tag (using `python dev.py build` / `python dev.py shell` from the `scipy-dev` freshly created with the `environment.yml` file from the scipy repo. My `repro_lu.py` script can only trigger the problem when scipy 1.11.0 is installed from official pypi wheels or conda-forge package.

So I cannot really tel if the proposed fix in this PR will actually fix the originally reported segfault or not.

Is there a way to make the scipy CI build the wheels for this PR and upload the artifacts

**Comment by andyfaff** [comment]
If you're on Linux, it should be possible to emulate the cibuildwheel process locally using a docker container. 

Alternatively you can get a wheel build by including [wheel build] in a commit message. The wheels are uploaded as artefacts available from the CI run. The commit has to be against a PR on a maintenance branch, or against main.

If you edit the `.github/wheels/wheels.yml` you could make a wheel run occur on your own fork.

**Comment by ilayn** [comment]
So the plot thickens then. I can't find any detail that would effect the wheels and not the self-built versions. 

I don't know enough about building the wheels here since it became a separate discipline almost hence let me summon @andyfaff @tylerjereddy is it possible for me to turn on the wheel build on a PR?

**Comment by ogrisel** [comment]
Actually: I tried to install scipy from conda-forge in the `scipy-dev` env from `environment.yml` and I cannot reproduce either. So it might be the influence of a runtime dependency rather than being caused a build time variation. Let me investigate further.

**Comment by h-vetinari** [comment]
> I tried to install scipy from conda-forge in the `scipy-dev` env generated from the `environment.yml` of the scipy repo and I cannot reproduce either.

FWIW, I could [reproduce](https://github.com/scipy/scipy/issues/18751#issuecomment-1608378236) it yesterday with builds from conda-forge (but larger parameters).

**Comment by ilayn** [comment]
I am also, since this morning, trying different sources to reproduce, conda, self-built, pip and so on. but so far no avail. I'll try the docker container version if I can manage to set it up

**Comment by h-vetinari** [comment]
For context, some failures we see (in our testing across blas variants, e.g. https://github.com/conda-forge/scipy-feedstock/pull/242) are dependent on the presence/absence of AVX512[^1], especially for openblas/MKL.

[^1]: I'm aware that this is a large family, and realistically it's just a proxy for the processor generation, especially as azure CI seems to have only 2 types of processors, or at least 2 observable errors modes.

The failure for me locally happens on a machine without it (only AVX2).

**Comment by ilayn** [comment]
Ouch, do you have a quick way to bisect numpy versions?

**Comment by h-vetinari** [comment]
> Ouch, do you have a quick way to bisect numpy versions?

Sorry, what I meant to say with that is: if you cannot reproduce it (especially with the conda-forge builds, of which there's only one), then it could be related to your processor type.

**Comment by ogrisel** [comment]
I managed to build this branch (`scipy.__version__ == "1.12.0.dev0+1237.019d82e"`) and I can reproduce it with the pytest / scikit-learn test.

**Comment by ogrisel** [comment]
I can also reproduce it with the repro script with larger dimensions but more rarely than via the scikit-learn test case.

**Comment by ilayn** [comment]
I removed all instances of `memcpy` that *might* affect different architectures. The rest is plain numpy and cython. @ogrisel  Could you rerun the build?

**Comment by ilayn** [comment]
Oh, another possibility is the difference between `NPY_FLOAT64` and C-type `double` because now for the first time I'm seeing the warning 

```bash
[6/7] Compiling C object scipy/linalg/_decomp_lu_cython.cp310-win_amd64.pyd.p/meson-generated__decomp_lu_cython.c.obj
In file included from ..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:1929,
                 from ..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:12,
                 from ..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\include/numpy/arrayobject.h:5,
                 from scipy/linalg/_decomp_lu_cython.cp310-win_amd64.pyd.p/_decomp_lu_cython.c:750:
..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h:14:9: note: '#pragma message: ..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\include/numpy/npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION'
   14 | #pragma message(_WARN___LOC__"Using deprecated NumPy API, disable it with " \
      |         ^~~~~~~
[7/7] Linking target scipy/linalg/_decomp_lu_cython.cp310-win_amd64.pyd
Build OK
```

This wasn't there until very recently for Cython. So probably I should also try that next.

**Comment by ogrisel** [comment]
I believe the new version of the code of this PR fixed the problem @ilayn!

I will continue re-running a few more times to be sure. But I already ran the scikit-learn tests 10x in a row and they were all green. This never happened before.

**Comment by ogrisel** [comment]
It seems stable, I reswitched to the previous commit and and it failed again on the first try so I am pretty confident this is a fix.

Also I wanted to run `gdb` post mortem on the previous commit but I don't know how to build scipy with debug symbols using the new `meson` based setup. Any suggestion? I had never used meson before.

**Comment by ilayn** [comment]
Glad that at least we know a way out. I don't know how much performance we lost but always better than mysterious segfaults. Every time I promise myself "never ever use C internals" then I lower my guard and this happens 🥲. 

For the gdb, I really wouldn't know. That stuff never worked on windows properly.

**Comment by ogrisel** [comment]
> In the meantime, what should we do about it, v1.11 or backporting ?

I would be in favor of backporting to the next bugfix release.

**Comment by ogrisel** [comment]
I found `python dev.py build --debug` in the output of `python dev.py build --help`. I will try that. Will do a full rebuild.

**Comment by ogrisel** [comment]
BTW, I did not review the correctness of the code in this PR (nor understand how it was broken in v1.11.0 because the pointer/indexer is quite complex).

I think this kind of code my deserve being checked with [valgrind memcheck]( https://stackoverflow.com/questions/3982036/how-can-i-use-valgrind-with-python-c-extensions).

**Comment by ilayn** [comment]
The tests are passing so at least that part is working. And they are relatively large to be of coincidence.

**Comment by ilayn** [comment]
Removed all architecture related types and only used NumPy types. Let's see if things will work out. I checked the correctness and size up to 5300. Did not have any problems locally (which means not much given the nature of this issue)

**Review by tylerjereddy — COMMENTED** [review]
I added a backport label, though I note that I can't reproduce on x86_64 MacOS per https://github.com/scipy/scipy/issues/18751#issuecomment-1610159356.

The two CI failures I see here have been observed elsewhere, so shouldn't be related. The code changes don't seem too scary to me, though I'm not an expert on this module. Obviously, finding a good regression test seems a bit problematic, at least for my experience on x86_64 macos.

**Comment by ilayn** [comment]
It is indeed very mysterious to me why we need this. Probably not breaking a lot of code out in the open but clearly affecting some.

**Comment by tylerjereddy** [comment]
Ok, I put it in, I did keep the 3 individual commits instead of squashing since they had unique descriptions and I'm still not sure what is going on if we ever need to revisit this, but since downstream seems happier with this patch makes sense to go in with our CI otherwise happy.

**Pull request merged**
