### PR TITLE
ENH:MAINT:optimize: Re-rewrite nnls in Cython

### LINKED ISSUE #20813: BUG: ``optimize.nnls`` sometimes fails when input ``A`` is a Fortran order array
### Describe your issue.

Lastest stable version of ``scipy.optimize.nnls`` (1.13.1) is sometimes sensitive to input array memory layout. For certain input arrays, ``nnls`` works fine with c-contiguous arrays, but raises ``RuntimeError`` for Fortran order arrays. 

Interestingly, the reproducibility of this error is very sensitive to the values of the array (see example below).

Older version of nnls (scipy 1.11.4, written in Fortran) always work fine. As far as I know, This error appears on multiple platforms (MacOS, Ubuntu) and multiple python versions (3.8, 3.9, 3.10, 3.12)

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import nnls


A1 = np.array(
    [
        [
            5.6804456109393231e-01,
            7.7293613312687126e-01,
            5.3596749047874905e-02,
            6.6478181730523378e-01,
        ],
        [
            9.2559663829266103e-01,
            8.7034572210281691e-01,
            3.6157431133730261e-01,
            4.8690183372106080e-02,
        ],
        [
            7.1036058197886942e-02,
            9.7838908691940440e-01,
            3.3106681832243329e-01,
            7.0049535992329526e-01,
        ],
        [
            2.0000000000000000e02,
            2.0000000000000000e02,
            2.0000000000000000e02,
            2.0000000000000000e02,
        ],
    ]
)

b1 = np.array(
    [5.680445610939323e-01, 9.255966382926610e-01, 7.103605819788694e-02, 2.000000000000000e02]
)

A2 = np.asfortranarray(A1)
b2 = b1  # or b2 = np.asfortranarray(b1), both will raise Error

print(nnls(A1, b1))  # This works
print(nnls(A2, b2))  # This raises RuntimeError("Maximum number of iterations reached.") 
# Won't be fixed even if ``maxiter`` is set to 1000

"""
Interestingly, when using lower precision but almost same values, There will not be any error:
A1 = np.array(
    [
        [5.68044561e-01, 7.72936133e-01, 5.35967490e-02, 6.64781817e-01],
        [9.25596638e-01, 8.70345722e-01, 3.61574311e-01, 4.86901834e-02],
        [7.10360582e-02, 9.78389087e-01, 3.31066818e-01, 7.00495360e-01],
        [2.00000000e02, 2.00000000e02, 2.00000000e02, 2.00000000e02],
    ]
)

b1 = np.array(
    [5.68044561e-01, 9.25596638e-01, 7.10360582e-02, 2.00000000e02],
)

A2 = np.asfortranarray(A1)
b2 = b1

print(nnls(A1, b1))  # This works
print(nnls(A2, b2))  # This works

"""
```

### Error message

```shell
Traceback (most recent call last):
  File "/Users/zwang505/Code/archetypes/examples/test_nnls.py", line 41, in <module>
    print(nnls(A2, b2))  # This raises RuntimeError("Maximum number of iterations reached.")
  File "/Users/zwang505/Code/archetypes/.venv/lib/python3.9/site-packages/scipy/optimize/_nnls.py", line 93, in nnls
    raise RuntimeError("Maximum number of iterations reached.")
RuntimeError: Maximum number of iterations reached.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=9, micro=18, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../../../../../private/var/folders/2f/8t5k6yr535sdw0s4glnpxrzm0000gn/T/pip-build-env-ddcl7dz8/overlay/lib/python3.9/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/2f/8t5k6yr535sdw0s4glnpxrzm0000gn/T/cibw-run-_36keccq/cp39-macosx_arm64/build/venv/bin/python
  version: '3.9'
```

### LINKED ISSUE #20984: BUG: scipy.optimize.nnls 1.11.4 version has better performance than the rewritten version with same results
### Describe your issue.

I updated my code to latest version and recognize that the new nnls version does take much more ressources and time for the same results. Is there maybe a way to access the old version also in the latest version?
my test is using the same data for both cases.
old: duration 2s
image
new: duration 2min
image

### Reproducing Code Example

```python
i use latest scikit-learn LinearRegression which calls scipy.optimize.nnls
LinearRegression(positive=True, fit_intercept=True, copy_X=False)
```

### Error message

```shell
Matrix is singular
```

### SciPy/NumPy/Python version and system information

```shell
all latest except scipy==1.11.4 for getting the performant version
```

### LINKED ISSUE #21140: BUG: optimize.nnls: re-implementation not robust
### Describe your issue.

The new re-implementation of `nnls` in [SciPy 1.12](https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html), which replaced the solid-rock classic implementation by [Lawson & Hanson 1995 (L&H)](http://dx.doi.org/10.1137/1.9781611971217), is a major step back and not robust enough for real-works applications.

The previous L&H `nnls` implementation was designed to deal with degenerate Jacobians and rounding errors. It solved the linear sub-problem using a least-squares method which allowed for degenerated Jacobians. 

The current one simply ignores ill-conditioned matrices and solves the linear sub-problem assuming no degeneracy.

The previous L&H implementation was designed to avoid explicitly forming the `J.T @ J` square matrix, where `J` is the problem Jacobian, to avoid increasing the ill-conditioning of the problem. Instead, the current re-implementation forms the `J.T @ J` matrix and uses that in the linear solution.

Overall, the current implementation is a major step back and not robust enough for real-world applications. It breaks (fails to converge) a number of my large applications that worked well with the L&H Scipy version.

A much more robust implementation of this same problem is provided by the SciPy [bvls](https://github.com/scipy/scipy/blob/v1.14.0/scipy/optimize/_lsq/bvls.py) procedure, which is a more general version of `nnls`. The Scipy `bvls` already implemented (without credit) the equivalent for `bvls` problems of the so-called `fast nnls` modification. It could be stripped down to solve `nnls` problems. Or the L&H procedure could be retained.

### Reproducing Code Example

```python
NA
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version and system information

```shell
Scipy 1.14.0
```

### PR DESCRIPTION
**Pull request by ilayn**
Recently, in #18570, we have swapped the old F77 nnls solver with a Python version of the so-called Fast NNLS based on Bro & de Jong paper. As we have received a few reports, the FNNLS description of the paper, as it turns out, leaves a lot of details out and there is no obvious way to fix it without switching to "research" mode.

I went back to the original F77 code and converted to Cython. The current tests are now passing without any issues. I can feel how to generalize to Bro & De Jong results but frankly I will have no appetite for a while. The F77 code is unbearable and can't find any examples to make it fail so far (In English, lack of edge problems). Also there is nothing in common with the text version and the actual implementation as can be seen as L&H description of this PR (hence absolute madness)

image

#### Reference issue
Closes #20813
Closes #20984 
Closes #21140

Reverted the changes we did in #20961 (@h-vetinari it would be great if you can test it if you have any capacity)

For @jonasgitabap 's case in #20984, here are the results;

```
THIS PR : 0.9998772286451303 1.15.0.dev0+960.95f8d01 8640ms
RELEASE: <did not finish after 10 minutes...>
```

Unfortunately, this old code does not use any tolerances, but I have introduced the `atol` keyword for the FNNLS and that needs an agreement. Apologies for introducing it prematurely in this fashion. I should not have relied to the paper this much.

### CODE REVIEW

**Comment by ilayn** [comment]
I also dare to ping (and possibly annoy) @jvendrow and @lucasbotang in case they are interested in improving this solver using Bro & De Jong algorithm. 

In the current release of scipy we (meaning I) have translated the FNNLS (possibly in erroneous form) here; 

https://github.com/scipy/scipy/blob/628a6b3bf3e1a3149b8a6390322ae976bba930fa/scipy/optimize/_nnls.py#L98-L164

This caused some accuracy issues and at certain cases it spins too many times signaling a chattering behavior in the active passive set swaps (#20168). I know there are issues with it but I don't have any time to dig deep into the literature. Hence this PR; a cythonized version of original NNLS. It is quite fast up until n=100 and keeps up then quickly deteriorates performance as expected. 

This is the fnnls performance result for the this current PR

image

and the scipy implementation that is currently released (using the aforementioned implementation)

image



The original `fnnls.m` is here but I'm not sure if it is fit for production code https://web.archive.org/web/20010708150016/http://www.models.kvl.dk/source/nnls/fnnls.m

If you have a robust implementation of FNNLS, it would be great if you can help us with it. I can happily help you converting it to Cython and with other details. Please let us know.

**Comment by mdhaber** [comment]
Just trying to help by testing. On my machine, the assertion fails:
```python3
import numpy as np
from scipy import optimize

A = [[0.004734199143798789, -0.09661916455815653, -0.04308779048103441, 0.4039475561867938,
      -0.27742598780954364, -0.20816924034369574, -0.17264070902176, 0.05251808558963846],
     [-0.030263548855047975, -0.30356483926431466, 0.18080406600591398, -0.06892233941254086,
      -0.41837298885432317, 0.30245352819647003, -0.19008975278116397, -0.00990809825429995],
     [-0.2561747595787612, -0.04376282125249583, 0.4422181991706678, -0.13720906318924858,
      -0.0069523811763796475, -0.059238287107464795, 0.028663214369642594, 0.5415531284893763],
     [0.2949336072968401, 0.33997647534935094, 0.38441519339815755, -0.306001783010386,
      0.18120773805949028, -0.36669767490747895, -0.021539960590992304, -0.2784251712424615],
     [0.5009075736232653, -0.20161970347571165, 0.08404512586550646, 0.2520496489348788,
      0.14812015101612894, -0.25823455803981266, -0.1596872058396596, 0.5960141613922691]]
b = [18.036779281222124, -18.126530733870887, 13.535652034584029, -2.6654275476795966,
     9.166315328199575]

A = np.asarray(A)
b = np.asarray(b)

x, res = optimize.nnls(A, b)
np.testing.assert_allclose(np.linalg.norm(A@x - b), res, rtol=1e-15)

# Mismatched elements: 1 / 1 (100%)
# Max absolute difference: 8.49127064
# Max relative difference: inf
# x: array(8.491271)
#  y: array(0.)
```
It was a bit puzzling at first, but I realized that the function is mutating `A`.

In case you're interested in silly edge cases:
```python3
optimize.nnls(np.empty((1, 0)), np.empty(1))
# (array([], dtype=float64), 29.732883325343384)
```

**Comment by ilayn** [comment]
Thank you @mdhaber much appreciated. You are right about the mutation. I thought asarray copies but apparently not, I'll fix.Good catch. 

The residual is strange indeed I'll check.

**Comment by ilayn** [comment]
> Even after passing copies into the function, I'm finding that the assertion still fails (meaningfully - i.e. with O(1) relative error) sometimes. I'd suggest comparing the residuals returned by the function against A@x - b for the problems you're generating.

Thanks for catching this @mdhaber. The residual norm is actually tracked by the algorithm as it moves along by the remaining entries of the working copy of `b`. But I wasn't slicing the right number of "remaining" values. Now corrected. 

I've added your examples and an extra problem with an interesting zero pattern optimal solution to the existing tests and residuals are compared.

**Comment by ilayn** [comment]
@mdhaber I know you are quite busy with other PRs. Do you think you can have a final look?

**Comment by h-vetinari** [comment]
> (@h-vetinari it would be great if you can test it if you have any capacity)

I backported this PR to 1.14 and threw it at the BLAS flavour testing gauntlet in https://github.com/conda-forge/scipy-feedstock/pull/280.

**Comment by h-vetinari** [comment]
No failures of `test_nnls_inner_loop_case1` reappeared 👍

**Comment by ilayn** [comment]
Ah great! Then I'll wait for a few days and click in case someone else does not. Thank you @h-vetinari !

**Comment by ilayn** [comment]
As an external verification from #21140, which seems to hit all parts of the inner loop, I think this is correct for cases we tried out. I'll click it in and brace for impact :)

**Comment by divenex** [comment]
> and the scipy implementation that is currently released (using the aforementioned implementation)
> 
> image

How does the current Cython version compare with the following `nnls` based on [SciPy bvls](https://github.com/scipy/scipy/blob/main/scipy/optimize/_lsq/bvls.py)?

    def nnls(A, b):
        return bvls(A, b, bounds=(0, np.inf)).x

**Comment by ilayn** [comment]
Hi @jd-edp. It is going to show up in version 1.15 that will be out in about a month.

**Comment by h-vetinari** [comment]
> For now i have to stick on version 1.11.4 which doesn't let me upgrade to py3.13

What keeps you from moving to 1.14 (which supports py3.13)?

**Pull request merged**
