### PR TITLE
DOC/MAINT: special: Several updates for tklmbda

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
See the individual commit messages for details.

### CODE REVIEW

**Review by melissawm — COMMENTED** [review]
This looks good to me - out of curiosity, was the missing bounds check creating a bug somewhere?

Also, I noticed both in the [tutorial](https://scipy.github.io/devdocs/tutorial/stats/continuous_tukeylambda.html) and in the docstring for the [Tukey lambda distribution](https://scipy.github.io/devdocs/reference/generated/scipy.stats.tukeylambda.html#scipy.stats.tukeylambda) the formatting is still "wrong" (Tukey-Lambda instead of Tukey lambda). I am guessing those fixes can be done in a follow-up - they also look like good first issues :)

**Comment by WarrenWeckesser** [comment]
Thanks @melissawm.

> [...] was the missing bounds check creating a bug somewhere?

If we call it a bug, it is not a very serious bug.  The differences would only be noticed at the ends of the support of the distribution, and they are tiny.

Here are some cases where the change makes a noticeable difference.  The values at the ends of the support should be 0 and 1.  With the main development branch:

```
In [2]: tklmbda([-1, 1], 1).tolist()
Out[2]: [7.105427357601002e-15, 0.9999999999999929]

In [3]: tklmbda([-4, 4], 0.25).tolist()
Out[3]: [7.105427357601002e-15, 0.9999999999999929]

In [4]: tklmbda([-0.125, 0.125], 8).tolist()
Out[4]: [7.105427357601002e-15, 0.9999999999999929]

```

With this pull request:

```
In [2]: tklmbda([-1, 1], 1).tolist()
Out[2]: [0.0, 1.0]

In [3]: tklmbda([-4, 4], 0.25).tolist()
Out[3]: [0.0, 1.0]

In [4]: tklmbda([-0.125, 0.125], 8).tolist()
Out[4]: [0.0, 1.0]

```

**Review by dschmitz89 — APPROVED** [review]
Very illustrative examples. Nitpick: it could be helpful to add a comparison of calling the Tukey lambda CDF via `special.tklmbda` or `scipy.stats.tukeylambda` but that is not a must for me.

**Comment by WarrenWeckesser** [comment]
@dschmitz89, good idea.  I added a note at the end of the docstring.  You can see the updated docstring at [`tklmbda`](https://output.circle-artifacts.com/output/job/1a19613d-9043-4483-9ed9-5fc644e89c48/artifacts/0/html/reference/generated/scipy.special.tklmbda.html)

**Comment by melissawm** [comment]
This looks like a clear improvement so I'll put it in - thanks @WarrenWeckesser !

**Pull request merged**
