### PR TITLE
DEP: integrate: remove simps,trapz,cumtrapz

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

follow up to #18699
#### What does this implement/fix?

Deprecated for two releases so ready for the chopping block.

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]
LGTM if tests pass - unless we decided that these need to wait for 1.15 since 1.13 was not in the normal cadence? I looks like these weren't deprecated until 1.12, so this would only give 6 months. Some other features deprecated in 1.12 said they would be removed in 1.15 ([Release Notes](https://docs.scipy.org/doc/scipy-1.12.0/release/1.12.0-notes.html#deprecated-features)).

 I am not finding any other appearances of these terms except for `trapz`, which is still allowed as an alias for the trapezoidal distribution and as a `method` option of `quad_vec`. (Those uses don't appear to have been deprecated.)

Aside - looks like we can now remove all those attributes from private namespaces that weren't marked with an underscore!

**Comment by h-vetinari** [comment]
When 1.13 was announced to be out-of-band, I did an [analysis](https://github.com/scipy/scipy/issues/15765#issuecomment-1892941618) of the deprecations in 1.11/1.12 and whether to postpone them. In this case I don't think it's necessary to wait any longer, 1.14 should be fine IMO. The non-slur aliases have also existed for a long time already.

**Comment by h-vetinari** [comment]
> I am not finding any other appearances of these terms except for `trapz`, which is still allowed as an alias for the trapezoidal distribution and as a `method` option of `quad_vec`. (Those uses don't appear to have been deprecated.)

Hm yeah, we should deprecate those and remove them as well.

**Comment by mdhaber** [comment]
Thanks @h-vetinari. 
@j-bowhay, with that in mind, shall I merge this?

**Comment by j-bowhay** [comment]
Thanks for confirming @h-vetinari , happy to merge

**Comment by mdhaber** [comment]
Thanks @j-bowhay @h-vetinari!

**Pull request merged**
