### PR TITLE
BUG: fix amax constraint not enforced in scalar_search_wolfe2

### PR DESCRIPTION
**Pull request by vegatheil**
Fixing the error indicated by [this question](https://stackoverflow.com/questions/47698022/interpreting-the-amax-parameter-in-scipys-line-search).

### CODE REVIEW

**Comment by rgommers** [comment]
I'm not sure that this is a good example, because for default `amax` the answer is not as expected:
```
In [17]: ls.scalar_search_wolfe2(phi, derphi, amax=0.001)
Out[17]: (1.0, 16.0, 25.0, -8.0)

In [18]: ls.scalar_search_wolfe2(phi, derphi, amax=None)
Out[18]: (1.0, 16.0, 25.0, -8.0)
```

**Comment by rgommers** [comment]
Okay, verified now - all looks good. Merged, thanks @vegatheil

**Comment by rgommers** [comment]
For future reference: the test verifies a private function; the corresponding public one is `optimize.line_search`:
```
>>> def phi(alpha):
...           return (alpha - 5) ** 2
>>> def derphi(alpha):
...            return 2 * (alpha - 5)
>>> x_current = 0
>>> search_direction = 1
>>> optimize.line_search(phi, derphi, x_current, search_direction)
(1.0, 2, 1, 16.0, 25.0, -8.0)
```

**Comment by DonatoMeoli** [comment]
@rgommers could you help me with #11360 ?

**Pull request merged**
