### PR TITLE
MAINT: sparse: Stop supporting multi-Ellipsis indexing

### PR DESCRIPTION
**Pull request by perimosocordiae**
#### Reference issue
This is the cleanup that we started warning about in gh-18540.

NOTE: We should not merge this until at least v1.13.0! I'll leave this in draft mode until then.

### CODE REVIEW

**Comment by rgommers** [comment]
> NOTE: We should not merge this until at least v1.13.0! I'll leave this in draft mode until then.

Can you close this and reference it in the deprecation meta tracker issue (gh-15765) instead? Having a PR in the queue that's not mergeable for another year at least is a little annoying; it can be reopened when it's mergeable. We have folks that are good about going through the outstanding deprecations for every release.

**Comment by j-bowhay** [comment]
I already have this in the tracker so will reopen it when we start development on 1.13

**Comment by perimosocordiae** [comment]
Sounds good, thanks!

**Comment by h-vetinari** [comment]
1.12 has branched, so this is now fair game. :)

**Comment by j-bowhay** [comment]
@perimosocordiae diff seems reasonable but just wanted to check in before merging that you were happy with everything  since it has been 6+ months since opening

**Comment by perimosocordiae** [comment]
Thanks, I just took another look and I'm happy with it.

**Review by j-bowhay — APPROVED** [review]
Not an expert in this part of the codebase but diff looks reasonable and CI is happy, thanks @perimosocordiae

**Pull request merged**
