### PR TITLE
MAINT,CI: signal: fix failing refguide check

### LINKED ISSUE #15692: CI: scipy.scipy (Main refguide_asv_check) failure in main
CI Failure in main (e.g. gh-15652).

```python3
Checking tutorial files at doc/source/tutorial/*.rst:

============
scipy.signal
============

scipy.signal.bohman
-------------------

File "build/testenv/lib/python3.9/site-packages/scipy/signal/__init__.py", line 412, in bohman
Failed example:
    np.seterr(divide='ignore')
Expected nothing
Got:
    {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

scipy.signal.cosine
-------------------

File "build/testenv/lib/python3.9/site-packages/scipy/signal/__init__.py", line 417, in cosine
Failed example:
    np.seterr(divide='ignore')
Expected nothing
Got:
    {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


====================
scipy.signal.windows
====================

scipy.signal.windows.bohman
---------------------------

File "build/testenv/lib/python3.9/site-packages/scipy/signal/windows/_windows.py", line 339, in bohman
Failed example:
    np.seterr(divide='ignore')
Expected nothing
Got:
    {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

scipy.signal.windows.cosine
---------------------------

File "build/testenv/lib/python3.9/site-packages/scipy/signal/windows/_windows.py", line 1603, in cosine
Failed example:
    np.seterr(divide='ignore')
Expected nothing
Got:
    {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

ERROR: refguide or doctests have errors

```

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### Reference issue

fixes #15692 

#### What does this implement/fix?

`np.seterr` prints a status in new releases which caused the refguide check to fail. This PR fixes those failures.

### CODE REVIEW

**Comment by ev-br** [comment]
Minor, optional, non-blocking: While you're at it, maybe use a context manager instead
```
with np.errstate(divide='ignore'):
   ...
```

**Review by tupui — COMMENTED** [review]
Thanks @tirthasheshpatel. I agree with @ev-br.

As discussed in the other issue, if you have a better exemple in mind that would not require this that would be better. I proposed something but did not get a feedback so I am not sure (never used this).

**Comment by tirthasheshpatel** [comment]
> As discussed in the other issue, if you have a better exemple in mind that would not require this that would be better. I proposed something but did not get a feedback so I am not sure (never used this).

I think it could be done in a follow-up. For now, it would be nice to have CI green again.

**Comment by ev-br** [comment]
LGTM now

**Review by tupui — APPROVED** [review]

**Comment by ilayn** [comment]
Can you folks reproduce this locally? I couldn't with NumPy 1.21.5 which refguide is using I think

**Comment by rgommers** [comment]
> Not to block this PR but can you folks reproduce this locally? I couldn't with NumPy 1.21.5 which refguide is using I think

These kind of floating point errors are unfortunately not always portable, so it doesn't just depend on numpy version.

**Comment by ilayn** [comment]
True but FFT result shouldn't be that far off to get away  from zero

**Comment by tirthasheshpatel** [comment]
I too am not able to reproduce it locally. I have removed np.errstate. Let's see if the CI is happy with it.

**Comment by tirthasheshpatel** [comment]
One timeout notwithstanding, the CI is happy with this! Feel free to merge if this looks good to you @tupui!

**Comment by tupui** [comment]
> One timeout notwithstanding, the CI is happy with this! Feel free to merge if this looks good to you @tupui!

I am not sure, if we do then we should leave an issue open to track it because we added this in the first place after noticing some instabilities there.

I would instead do this `window = signal.windows.cosine(51)[1:-1]` as a bandaid, as I proposed in the previous issue, but better confirm this with @ilayn

**Comment by tirthasheshpatel** [comment]
> I am not sure, if we do then we should leave an issue open to track it because we added this in the first place after noticing some instabilities there.

Oh OK, I wasn't aware about that. Looking at the blame, I see you submitted [#15649](https://github.com/scipy/scipy/pull/15649) (can't find the issue where this was discussed). I can revert the last commit in that case.

**Comment by ilayn** [comment]
My apologies @tupui for missing out the previous pings in that issue. So as far as I understand it started with #15327 then we fixed bunch of stuff and then things kind of disappeared. If none of us is able to repro then this is probably a fluke otherwise I don't see why this should pop up because hitting exact 0. is very unlikely.

**Comment by tupui** [comment]
No worries :)

As you wish, as I said it's really not my area so would rely on your judgment. Feel free to merge if you think this is fine as it is.

**Comment by ilayn** [comment]
Let's get this in and if the problem comes back, I'll fix the examples quickly. Thanks all!

**Pull request merged**
