### PR TITLE
MAINT: stats: Post-"lint everything" clean up in stats.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
In this commit, I fix all the occurrences of the following flake8 issues in scipy.stats:

* E127 continuation line over-indented for visual indent
* E128 continuation line under-indented for visual indent
* E202 whitespace before ')'
* E302 expected 2 blank lines, found 1
* E306 expected 1 blank line before a nested definition, found 0
* W391 blank line at end of file

The "lint everything" changes introduced some of these issues, but I didn't limit the clean up to just the issues introduced in that pull request.

### CODE REVIEW

**Comment by tupui** [comment]
If we do things like that, can you also update the git revision file? (also I guess the current commit needs fixing due to squash).

cc @stefanv

**Comment by tupui** [comment]
Ok thanks for updating the sha. Once this is in, we will add it as well to the list.

**Review by tupui — APPROVED** [review]
LGTM if the linter is back green

**Comment by tupui** [comment]
Linter is green, merging. Thanks again Warren

**Comment by stefanv** [comment]
Thanks, Warren!

**Comment by stefanv** [comment]
Out of curiosity, where did these errors crop up? They are flake styling errors, and not structural errors as checked by ruff, looks like?

**Comment by stefanv** [comment]
Which reminds me @charliemarsh, do we have a tracking issue for adding some of those rules back for projects that don't use black?

**Comment by charliermarsh** [comment]
@stefanv - I just created a new one to track the work here with proper tabulation: #2402

**Pull request merged**
