### PR TITLE
MAINT: Cleanup uses of PY_VERSION_HEX, NPY_PY3K in ndimage

### PR DESCRIPTION
**Pull request by sethtroisi**
Continued work on Python2 code cleanups #11584

These are the easy cases for these three consts.
The hard cases involve tracking down if functions are used anywhere, updating names...

This is the uses in ndimage, I'll open two other PRs for uses in sparse and elsewhere

### CODE REVIEW

**Comment by EverLookNeverSee** [comment]
@sethtroisi Too many files changed in one PR!

**Comment by sethtroisi** [comment]
@EverLookNeverSee Okay, I'll break out into a couple of PRs

**Review by peterbell10 — APPROVED** [review]

**Review by miladsade96 — APPROVED** [review]
Thanks @sethtroisi 
LGTM, feel free to merge it if @rgommers is also satisfied.

**Comment by tylerjereddy** [comment]
Several approving reviews & I checked it as well, merging--thanks @sethtroisi

**Pull request merged**
