### PR TITLE
MAINT: list of minimize methods

### PR DESCRIPTION
**Pull request by andyfaff**
It struck me that it might be useful to have a list of all the minimize methods listed somewhere. This PR adds this list.
 
- is it worth having the list (e.g. would be useable in #10756, #10640)?
- is the naming right?
- all caps?
- is it worth adding lists for methods requiring grad/{hess, hessp}?

### CODE REVIEW

**Comment by mdhaber** [comment]
This sounds like a good idea. 
The spellings look right.
I don't think caps matter internally. If we care, maybe stick with what's in the [documentation](http://scipy.github.io/devdocs/optimize.html#local-multivariate-optimization)?
Not a bad idea to add these separate lists for different requirements. In any case, take a look at the lists already in [`benchmarks/benchmarks/optimize.py`](https://github.com/scipy/scipy/blob/master/benchmarks/benchmarks/optimize.py); these should probably refer to your lists instead of being defined separately.

**Comment by andyfaff** [comment]
> I'm happy with all lower case,

Internally they're all converted to lower case.

**Comment by mdhaber** [comment]
> Internally they're all converted to lower case.

Yup, I looked. For instance, in [`_minimize.py`](https://github.com/scipy/scipy/blob/master/scipy/optimize/_minimize.py)

```
    if callable(method):
        meth = "_custom"
    else:
        meth = method.lower()
```
But since I suggested something like:
```
if meth not in MINIMIZE_METHODS:
   raise ValueError('Unknown solver %s' % method)
```
that check is a tiny bit simpler if `MINIMIZE_METHODS` is already lower.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @andyfaff and @mdhaber

**Pull request merged**
