### PR TITLE
BUG: spatial: Fix a couple edge cases for the Mahalanobis metric in pdist and cdist.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by rgommers** [comment]
LGTM, merged. Thanks Warren.

**Comment by argriffing** [comment]
The original implementation of `scipy.spatial` mahalanobis distance looks a bit off to me, when the `VI` argument is `None`. There is no mean subtraction, the numpy `cov` function assumes 1 degree of freedom but maybe 0 should be used instead, it is transposing matrices that are symmetric by construction, explicit matrix inversion is used instead of cholesky or singular value decomposition or at least `pinvh`, it seems to unnecessarily disallow high dimensions when the observations are in a subspace, and it doesn't take the square root at the end or it is inconsistently documented (e.g. https://github.com/scipy/scipy/issues/2189). But it could be a clone of http://www.mathworks.com/help/stats/mahal.html, I don't know.

**Comment by WarrenWeckesser** [comment]
@argriffing  I asked myself some of those questions, too.  But these days I don't have time to dive deep, so I fixed the obvious problem.  Now at least it won't return garbage or nan in the singular case.  How about creating a new issue for the concerns you mentioned?

**Comment by argriffing** [comment]
@WarrenWeckesser OK I've created a new issue. I agree that this PR is an improvement!

**Pull request merged**
