### PR TITLE
CI build log: try harder to detect test failures

### LINKED ISSUE #4847: travisCI status is unreliable
Output redirection we do on Travis CI since https://github.com/scipy/scipy/pull/4792 seems to fool the CI service and we get false positive success results again. For instance,
https://travis-ci.org/scipy/scipy/jobs/61926464

The issue seems to be that the exit code from a series of shell commands connected by pipes is the exit code from the last one. Which is a `tee` and it succeeds even if `runtests.py` fails.

One option is to revert gh-4792 (which means we do not see lapack xerbla failures), or to make output validation smarter (eg, grep for SUCCESS or FAILED in the log) around https://github.com/scipy/scipy/blob/master/tools/validate_runtests_log.py#L39

### PR DESCRIPTION
**Pull request by ev-br**
Do it two ways: use shell settings to try propagating error codes _and_ try being a little smarter with parsing the test log. 

closes gh-4847

### CODE REVIEW

**Comment by pv** [comment]
@ev-br: LGTM. Please go ahead and merge it when travis passes.

**Comment by ev-br** [comment]
Ok, merged.

**Comment by ev-br** [comment]
NB: Looks like both log parsing and set pipefail work: https://travis-ci.org/scipy/scipy/jobs/62205299
Which is nicely redundant: if/when TravisCI config changes, we are less likely to get false positives.

**Comment by argriffing** [comment]
I think this PR causes the regression observed in https://github.com/scipy/scipy/pull/4968#issuecomment-112607763.

**Comment by ev-br** [comment]
It looked like the build failed earlier, while building scipy. Thus runtests.py terminated with error code 1, and validate_run tests_log.py happily reported that something's amiss. I've restarted that build, let's see how it fares this time.

**Comment by argriffing** [comment]
I think it failed in an unintended way, where it tries to check the value of an uninitialized `found_it` at https://github.com/scipy/scipy/blob/master/tools/validate_runtests_log.py#L59. Should the code be change to initialize `found_it` to `False` near https://github.com/scipy/scipy/blob/master/tools/validate_runtests_log.py#L45?

**Comment by ev-br** [comment]
Yes, I agree. The error message is unhelpful when there's no match.

**Pull request merged**
