### PR TITLE
CI: work around the 50 minute test timeout

### PR DESCRIPTION
**Pull request by argriffing**
see also https://github.com/scipy/scipy/issues/3913

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I think that coveralls combines coverage reports from all the runs where coveralls is called in order to generate overall coverage report. If the problem is that each run locally overwrites the `.coverage` files from doing multiple sub-runs itself (which I suspect is going on here), then you can instead 1) do each sub-run, 2) rename the output after each sub-run finishes to e.g. `.coverage.sparse`, and then when all are done 3) use `coverage combine` or so to combine all the coverage files. I have done this in a different repository successfully.

But if coveralls really isn't worth keeping, then ignore this :) It seems like this limitation should also go away if the combined instead of isolated sub-module running mentioned by @argriffing works out.

**Comment by rgommers** [comment]
Coveralls was working so badly - only intermittent runs, not showing coverage per line for large files - that I disabled it a couple of weeks ago. No one seems to have missed it:)

**Comment by pv** [comment]
Coveralls is working badly, but coverage checking itself is useful when run locally.
There's some way to merge coverage files, don't recall how, however.
You can maybe just do `if args.coverage and len(submodules) > 1: parser.error("--coverage does not work with multiple submodules")`.

I don't know a way to get the test suites collected using Numpy's runner framework, there are many elephants stacked on top of each other in the way, and runtests.py is a hack in the first place already...

**Comment by ev-br** [comment]
For the record, the following method for combining coverage files work:
```
$ python runtests.py -s linalg --coverage
$ mkdir cov_temp_dir
$ cp build/test/.coverage cov_temp_dir/.coverage.linalg   # it gets overwitten otherwise
$ python runtests.py -s interpolate --coverage
$ cp build/test/.coverage cov_temp_dir/.coverage.interpolate
$ cd cov_tmp
$ coverage combine
```

**Comment by ev-br** [comment]
Strangely enough, we might want to use this for the relaxed strides checking CI run. Esp if we do it by submodule and split off the linalg run...

**Comment by ev-br** [comment]
Apparently, the move to container-based infrastructure brought the run time to well below the CI timeout.

**Comment by argriffing** [comment]
Yes, after https://github.com/scipy/scipy/pull/5036 the CI process looks like it is taking 30 minutes instead of hitting the limit at 50+ minutes. I'll close this.

**Pull request closed without merging**
