### PR TITLE
ENH: Add test on random inpu to volume computations

### PR DESCRIPTION
**Pull request by haudren**
As a follow-up from pull request #5014 , I propose to add a test to the spatial module in order to check that the volume computed is correct.

I generated a set of random points, and computed the volume from qconvex to compare it with scipy's output.

Hervé Audren

### CODE REVIEW

**Comment by rgommers** [comment]
@haudren the TravisCI tests actually never ran on this PR because it had a merge conflict when you submitted it. Can you please rebase on latest master?

**Comment by rgommers** [comment]
You may also want to squash the commits into a single one and start the commit message with ``TST: ``. (see http://docs.scipy.org/doc/numpy-dev/dev/gitwash/development_workflow.html#writing-the-commit-message)

**Comment by haudren** [comment]
@rgommers : Just rebased and squashed, and used a more proper commit message. I guess we now just have to wait for Travis to complete :)

**Comment by rgommers** [comment]
Thanks @haudren, merged.

**Comment by haudren** [comment]
Thank you @rgommers , always a pleasure to contribute :)

**Pull request merged**
