### PR TITLE
ENH: Add wrappers for ?syconv routines

### PR DESCRIPTION
**Pull request by ilayn**
I think this is small of a change to add to 1.3.0. Basic tests are added.

### CODE REVIEW

**Comment by ev-br** [comment]
Looks good, CI is happy, let's get this in. Thanks Ilhan

**Comment by tylerjereddy** [comment]
I added a brief note to the linalg release note section here: https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.3.0#scipylinalg-improvements

Feel free to improve/ correct

**Comment by dhomeier** [comment]
When testing this in 1.3.0rc1 and linked to OpenBLAS 0.3.6, `test_syconv` fails with apparently an invalid `LWORK` input to `SSYTRF`:
```
    def test_syconv():
        """
        Test for going back and forth between the returned format of he/sytrf to
        L and D factors/permutations.
        """
        seed(1234)
        for ind, dtype in enumerate(DTYPES):
            n = 10
    
            if ind > 1:
                A = (randint(-30, 30, (n, n)) +
                     randint(-30, 30, (n, n))*1j).astype(dtype)
    
                A = A + A.conj().T
            else:
                A = randint(-30, 30, (n, n)).astype(dtype)
                A = A + A.T + n*eye(n)
    
            tol = 100*np.spacing(dtype(1.0).real)
            syconv, trf = get_lapack_funcs(('syconv', 'sytrf'), dtype=dtype)
    
            L, D, perm = ldl(A, lower=1, hermitian=False)
            ldu, ipiv, info = trf(A, lower=1)
            a, e, info = syconv(ldu, ipiv, lower=1)
>           assert_allclose(tril(a, -1,), tril(L[perm, :], -1), atol=tol, rtol=0.)
E           AssertionError: 
E           Not equal to tolerance rtol=0, atol=1.19209e-05
E           
E           Mismatch: 45%
E           Max absolute difference: 51.22727273
E           Max relative difference: nan
E            x: array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
E                  [-18.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
E                  [ 34.,  14.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],...
E            y: array([[ 0.      ,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,
E                    0.      ,  0.      ,  0.      ,  0.      ],
E                  [-0.409091,  0.      ,  0.      ,  0.      ,  0.      ,  0.      ,...

A          = array([[ 44., -18.,  34.,  52.,  -7.,  35., -19.,  28., -39.,  35.],
       [-18.,  32.,  14., -18.,  -6.,  28.,   7.,...  12.,  -5., -23.,   5.,  18.,  45., -14., -34.],
       [ 35.,  32.,  25., -15.,  29., -25.,  13., -13., -34.,  42.]])
D          = array([[  44.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.       ...0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        , -177.6434372 ]])
L          = array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ...738 ,  0.96975676,  0.81860519, -1.02883434,
         0.72890491,  1.06115079,  2.38677107, -1.28621472,  1.        ]])
a          = array([[ 44., -18.,  34.,  52.,  -7.,  35., -19.,  28., -39.,  35.],
       [-18.,  32.,  14., -18.,  -6.,  28.,   7.,...5.,  18.,  45., -14., -34.],
       [ 12.,  -1., -14.,  -1., -25.,  13., -13.,  28., -34.,  42.]],
      dtype=float32)
dtype      = <class 'numpy.float32'>
e          = array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)
ind        = 0
info       = 0
ipiv       = array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)
ldu        = array([[ 44., -18.,  34.,  52.,  -7.,  35., -19.,  28., -39.,  35.],
       [-18.,  32.,  14., -18.,  -6.,  28.,   7.,...5.,  18.,  45., -14., -34.],
       [ 35.,  32.,  25., -15.,  29., -25.,  13., -13., -34.,  42.]],
      dtype=float32)
n          = 10
perm       = array([0, 1, 5, 3, 4, 2, 6, 7, 8, 9])
syconv     = <fortran object>
tol        = 1.1920928955078125e-05
trf        = <fortran object>

/sw/lib/python3.7/site-packages/scipy/linalg/tests/test_lapack.py:1272: AssertionError
---------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------
 ** On entry to SSYTRF parameter number  7 had an illegal value
```
more precisely,
```
>>> ldu, ipiv, info = trf(A, lower=1)
 ** On entry to SSYTRF parameter number  7 had an illegal value
```
Strangely, the same call and the test succeed with OpenBLAS 0.3.5, although AFAICS both are using the same [sources](https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/SRC/ssytrf.f) from LAPACK 3.7.0.

**Comment by dhomeier** [comment]
> ```
> >>> ldu, ipiv, info = trf(A, lower=1)
>  ** On entry to SSYTRF parameter number  7 had an illegal value
> ```
> 
> 
> Strangely, the same call and the test succeed with OpenBLAS 0.3.5, although AFAICS both are using the same [sources](https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/SRC/ssytrf.f) from LAPACK 3.7.0.

Might be rather an OpenBLAS issue then, but I am at a complete loss what could have changed there. Some further experimenting showed that in 0.3.6 apparently `SSYRTF` requires `LWORK` to be at least the matrix size below the diagonal (i.e., N**2/2 for even, and N*(N-1)/2 for uneven N):
```
>>> ldu, ipiv, info = trf(A, lower=1, lwork=49)
 ** On entry to SSYTRF parameter number  7 had an illegal value
>>> ldu, ipiv, info = trf(A, lower=1, lwork=50)

```
But `ssyrtf.f` does not even test for `LWORK.LT.N`, merely `LWORK.LT.1` (which would always be caught by the `_flapack` interface)...

**Comment by ilayn** [comment]
The only lwork test in place, is here 

https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack_sym_herm.pyf.src#L185

And that assumes `nb=1` is the worst case hence "at least use `n`" is used on SciPy side. Could you please check, in the risk of being obvious what `scipy.linalg.lapack.ilaver()` gives in different OpenBLAS versions?

**Comment by dhomeier** [comment]
Can never be too obvious, I am still trying to find my way through the interface and calling logics...
It's `(3, 8, 0)`, although `ilaver.f` says `LAPACK computational routine (version 3.7.1)`.
The one change I could identify (just before the 0.3.6 release) was, of all things, in [relapack/config.h](https://github.com/xianyi/OpenBLAS/commit/2cd463eabdcecce01a379c7aaebbb0c48e21c27d) -
disabling this indeed set the minimum required lWork in relapack's `ssytrf.c` from `1` to `n*(n/2)`.

I've just tested that after building openblas with that change reverted `_flapack.*sytrf` works with the default parameters again (internally `ssyrtf()` also accepts any `lwork>0`).
I am a bit puzzled if this means that actually always the `relapack` C implementation is called, and never the Fortran one from `lapack-netlib`.

Concerning the test failure, I could patch the openblas build I am packaging for Scipy accordingly, but if there was a good reason to disable `XSYTRF_ALLOW_MALLOC`, maybe the minimum lwork in Scipy should be set to `n*(n//2)` instead.

**Comment by dhomeier** [comment]
Can never be too obvious, I am still trying to find my way through the interface and calling logics...
It's `(3, 8, 0)`, although `ilaver.f` says `LAPACK computational routine (version 3.7.1)`.
The one change I could identify (just before the 0.3.6 release) was, of all things, in [relapack/config.h](https://github.com/xianyi/OpenBLAS/commit/2cd463eabdcecce01a379c7aaebbb0c48e21c27d) -
disabling this indeed set the minimum required lWork in relapack's `ssytrf.c` from `1` to `n*(n/2)`.

I've just tested that after building openblas with that change reverted `_flapack.*sytrf` works with the default parameters again (internally `ssyrtf()` also accepts `lwork>0`).
I am a bit puzzled if this means that actually always the `relapack` C implementation is called, and never the Fortran one from `lapack-netlib`.

**Comment by ilayn** [comment]
Maybe again as a reminder, netlib fortran code implementations are called the reference implementations and almost never being used by MKL or OpenBLAS at the BLAS level and few of the LAPACK routines. Hence there might be some specific optimization differences when things are compiled. 

From the details you have provided it seems like this is an OpenBLAS issue but I am not sure what exactly. I think they might give you a better answer because from the SciPy side I don't see how things might change. 

Also note that Scipy functions always use the accompanying functions `?sytrf_lwork` to get the optimal lwork value hence that won't (well at least shouldn't)  cause any problems.

**Comment by dhomeier** [comment]
Yes, I was perhaps left astray by the very Fortran-like diagnostic message. Looking at [lapack_wrappers.c](https://github.com/xianyi/OpenBLAS/blob/develop/relapack/src/lapack_wrappers.c) (and from the experiments with `config.h`) these seem indeed to be the versions exposed as the default.

I was just preparing a comment on the OpenBLAS commit to ask if this change is going to be permanent (but as it just made it into the release, it's probably going to be).

> Also note that Scipy functions always use the accompanying functions `?sytrf_lwork` to get the optimal lwork value hence that won't (well at least shouldn't) cause any problems.

So adding accordingly an `lwork = _compute_lwork(func_lwork, n)` to `test_syconv()` would be the proper fix? 
If the `cleanlWork = *n * (*n / 2)` in [ssytrf.c](https://github.com/xianyi/OpenBLAS/blob/develop/relapack/src/ssytrf.c#L22) is going to stay, it might still make sense to adapt the checks in `flapack_sym_herm.pyf.src`, or would that conflict with other BLAS implementations?

**Comment by dhomeier** [comment]
OK, as turned out from the discussion with the OpenBLAS developers, the problem was due to accidentally enabling the ReLAPACK set of functions in my build. Solved with actually a slight performance improvement, and passing all tests in 1.3.0rc1.

I think all that remains to consider is whether to use `_compute_lwork()` in `test_syconv()`.

**Comment by ilayn** [comment]
That's indeed a good suggestion that I failed to follow my own advice. Some facepalming and a PR in order but it is probably be for SciPy 1.4.0

**Pull request merged**
