### PR TITLE
Fix permissions

### PR DESCRIPTION
**Pull request by opoplawski**
Fixup some permissions.  Arguably some of these do not need shebang lines, but if they have them they should be executable.

### CODE REVIEW

**Comment by opoplawski** [comment]
Looks like a transient networking issue for the ci test failure.

However, looks like the .py files get installed with 0644 permissions so changing in the source doesn't really have an effect.  I'm trying to deal with rpmlint errors:

python34-scipy.x86_64: E: non-executable-script /usr/lib64/python3.4/site-packages/scipy/special/setup.py 0644L /usr/bin/env

**Comment by pv** [comment]
I would instead remove the shebang lines --- these are not really meant to be run directly.

**Comment by ev-br** [comment]
Where does this stand after https://github.com/scipy/scipy/pull/6962 removed shebang lines?

**Comment by ev-br** [comment]
Superseded by gh-7686

**Pull request closed without merging**
