### PR TITLE
Returning NotImplemented in comparisons with sparse arrays

### PR DESCRIPTION
**Pull request by emilfrost**
#### Reference issue

Closes issue [#4819](https://github.com/scipy/scipy/issues/4819).

#### What does this implement/fix?

For the comparison operators: `__eq__, __ne__, __ge__, __gt__, __le__, and __lt__`, the sparse arrays (and matrices) will now return `NotImplemented` at the end of the function call when they don't recognize the other object in the comparison and hand over control.

As an example (used as unit test), in the present version of SciPy, the comparison methods of an instance of `A` are never called when comparing with a sparse array if the array is on the left hand side.

```py
class A:
    def __eq__(self, other): return 'eq'
    def __ne__(self, other): return 'ne'
    def __lt__(self, other): return 'lt'
    def __le__(self, other): return 'le'
    def __gt__(self, other): return 'gt'
    def __ge__(self, other): return 'ge'
x = sp.coo_array((1, 1))
a = A()
assert (x == a) == 'eq'
assert (x != a) == 'ne'
assert (x > a) == 'lt'
assert (x >= a) == 'le'
assert (x < a) == 'gt'
assert (x <= a) == 'ge'
```

Currently, all these assertions fail: `x == a` returns `False`, `x != a` returns `True`, and the rest raise a `ValueError`. This PR changes all these to return `NotImplemented` from the SciPy side such that custom classes may define their own behavior.

### CODE REVIEW

**Comment by lucascolley** [comment]
ping @rileyjmurray @viech who had some useful discussion of this in gh-4819 and @stevediamond in case you are still interested in this after all these years 😅

**Review by dschult — APPROVED** [review]
This looks good to me.

**Comment by perimosocordiae** [comment]
This seems reasonable to me, though I need to do some thinking (and perhaps some archaeology) to understand why we didn't have this behavior in the first place.

**Review by perimosocordiae — APPROVED** [review]
Looks like the original behavior comes from gh-2561, which was likely before we had other arraylike types to consider.

**Comment by perimosocordiae** [comment]
The CI failure is for `test_intermediate_overlow` in scipy.special, so I'll merge this now.

**Comment by lucascolley** [comment]
Thanks for your first contribution to SciPy @emilfrost !

**Pull request merged**
