### PR TITLE
MAINT: stats: fix editable install issue in `qmc` and MPL-related issue in test

### PR DESCRIPTION
**Pull request by rgommers**
This makes the full test suite pass with editable installs and numpy 2.0-dev installed (without a matching `matplotlib` build, which is a pain to do).

### CODE REVIEW

**Comment by rgommers** [comment]
All green except for the following linter nit, so I'll push a fix for that without re-running the full batter of CI:
```
scipy/stats/_sobol.pyx:8:8: 'os' imported but unused
```

**Comment by rgommers** [comment]
Ready to merge. There's no CI job for editable installs yet, but the `qmc` failures at least should be reproducible locally I'd think.

**Review by tylerjereddy — APPROVED** [review]
I checked locally with editable installs and NumPy `main` + `matplotlib` stable and confirmed fail before/fix after.

I had to double take the test shims, but the commit messages are pretty detailed. The problem is obviously that `maplotlib` fails to import in the first place even though it is actually present, but that can be easy to miss if you just read the diff quickly.

**Comment by tylerjereddy** [comment]
thanks

**Pull request merged**
