### PR TITLE
BLD: fix missing build dependency on cython signature .txt files

### PR DESCRIPTION
**Pull request by rgommers**
Noticed this when looking at gh-18247.

### CODE REVIEW

**Review by lysnikolaou — COMMENTED** [review]
One question: Are these files used for something else as well? If not, would it be a good idea (or even possible) to remove them from the source tree, regenerate them as part of the build process and add `_cython_signature_generator.py` as a dependency instead?

**Comment by rgommers** [comment]
> Are these files used for something else as well? If not, would it be a good idea (or even possible) to remove them from the source tree, regenerate them as part of the build process and add `_cython_signature_generator.py` as a dependency instead?

They're only used during the build process, for the `linalg.cython_blas/cython_lapack` modules as well as in `scipy/_build_utils/_fortran.py` for the ILP64 build.

I'd not want to remove them, because to regenerate them requires BLAS/LAPACK sources that aren't available at build time. And vendoring those would be a lot more code than simply committing these two `.txt` files.

**Comment by lysnikolaou** [comment]
Oh yes, that right. Thanks!

**Review by lysnikolaou — APPROVED** [review]

**Review by tylerjereddy — APPROVED** [review]
LGTM as well and CI is green

**Pull request merged**
