### PR TITLE
DOC: `signal.unit_impulse`: add explanation about delta

### PR DESCRIPTION
**Pull request by MarDiehl**
The unit impulse is known as _Dirac delta_, (or _Dirac delta function_), not _Kronecker delta_.
https://en.wikipedia.org/wiki/Kronecker_delta
https://en.wikipedia.org/wiki/Dirac_delta_function

### CODE REVIEW

**Comment by ilayn** [comment]
This is a bit of a preference or purism thing as dirac delta is the continuous kronecker delta so this function generates sequential values thus should be the kronecker delta. 

In any case neither are correct here as delta functions are not pointwise defined but engineering usage is well established. We can instead remove the delta mention to avoid all that.

Either way I don't have any strong opinion.

**Comment by DietBru** [comment]
A  _Notes_ section with one sentence is not too helpful, IMO. What about something along the lines of ( essentially citing Wikipedia):

```ReSt
Notes
-----
In digital signal processing literature the unit impulse is often represented by
the Kronecker delta. [1] E.g., a signal :math:`u[n]` which is zero everywhere except
being one at the :math:`k`-th sample can be expressed as

.. math::

    u[n] = \delta[n-k] \equiv \delta[k-n] \equiv \delta_{n,k} \equiv \delta_{k,n}\ .

Furthermore, it is frequently interpreted as the discrete-time version of the
continuous-time Dirac distribution. [2]

References
----------
.. [1] "Kronecker delta", *Wikipedia*,
       https://en.wikipedia.org/wiki/Kronecker_delta#Digital_signal_processing
.. [2] "Dirac delta function" *Wikipedia*,
       https://en.wikipedia.org/wiki/Dirac_delta_function#Relationship_to_the_Kronecker_delta

```
What do you think, @MarDiehl?

**Comment by MarDiehl** [comment]
Having a longer explanation is IMHO a nice idea and the current text looks good.

**Comment by j-bowhay** [comment]
@MarDiehl would you be interested in committing the suggested text?

**Comment by DietBru** [comment]
I pushed the documentation change. The result can be viewed [here]—any improvements are very welcome!

PS: The test failures seem unrelated.

[here]: https://output.circle-artifacts.com/output/job/5705c8e3-6726-418a-8037-2a76243da662/artifacts/0/html/reference/generated/scipy.signal.unit_impulse.html

**Review by lucascolley — APPROVED** [review]
thanks all!

**Comment by MarDiehl** [comment]
thanks!

**Pull request merged**
