### PR TITLE
ENH: Benchmarking global optimizers

### PR DESCRIPTION
**Pull request by andyfaff**
This PR adds over 100 classes that can be used to benchmark global optimizers.  Global optimizers are methods for finding minima in functions that may have multiple local minima but few global minima, may not be differentiable, etc.  Global optimizers need to be used because normal minimizers typically can't cope with starting points that are far away from the global minimum.
These global benchmarking functions are based on a suite written by Andrea Gavana, https://code.google.com/p/ampgo/.

### CODE REVIEW

**Comment by argriffing** [comment]
I was thinking of making a PR into this branch to address some of the tiny issues in the comments above like `scipy.misc` -> `scipy.special` but I see that the `Merge pull request` button is disabled for me so I think that means it needs a rebase...  I'm not sure how this benchmarking PR interacts with the new `asv` benchmarking system.

**Comment by pv** [comment]
The files need to be moved under `benchmarks/benchmarks/`, and the ~100 lines changed in `benchmarks/benchmark_global_optimizers.py` need to be adapted so that it works with asv.

**Comment by andyfaff** [comment]
The reason that the PR hasn't progressed any further is that:

1) checks need to be done on whether the documentation/comments match what
the function returns
2) for some functions the literature differs on equations/global minima,
etc.
3) it would be nice to get a standard form for the documentation.

The above 3 points aren't difficult in themselves, it's just that there are
> 120 functions to do this for.  I don't want to do it more than once.
Alternatively, it would be nice if there was a few other contributors to
split the work.
If it did comply w.r.t. the asv benchmarking could it go in as it is, or
would it have to be polished up to the standard that is expected for the
main scipy.* codebase?

With respect to the asv benchmarking, it's important to note that we're not
really interested in runtime or memory usage.  Rather, we're only
interested in how many times a particular solver reaches a minimum.

**Comment by pv** [comment]
I apparently deleted the global optimizer benchmarks when porting to asv. Anyway, here's rebased and asv-ported branch of this one: https://github.com/pv/scipy-work/tree/pr-4191

**Comment by andyfaff** [comment]
@pv, @argriffing what's the best way for workflow on this PR?
Should I pull the changes from https://github.com/pv/scipy-work/tree/pr-4191 back onto andyfaff/go_benchmark?  Or would it be better for me to close this PR and for the PR to be re-submitted from pv's branch?

**Comment by pv** [comment]
Re asv: it is possible to track arbitrary performance numbers, for example nfev with it -- here's the smooth optimizer one: https://pv.github.io/scipy-bench/#optimize.BenchSmoothUnbounded.track_all
Currently, it's however not possible to return multiple values from a benchmark, so it runs it twice to get mean_nfev and success%. This is maybe not a problem, and will probably be fixed in the future.

@andyfaff: you can do
```
git remote add pv https://github.com/pv/scipy-work.git
git fetch pv pr-4191
git branch go_benchmark-old go_benchmark
git checkout go_benchmark
git reset --hard pv/pr-4191
git push -f
```
to get my rebased branch up here, which may be the simplest option in case you want to make some changes still.

**Comment by pv** [comment]
As to your other questions: potential errors in the benchmark functions or their docstrings probably don't block merging this. Another thing: I removed the anneal benchmark, as it is not present in current scipy --- it could be added back, in case we want to compare its performance in previous scipy versions.

The current benchmark set also runs with numtrials=1, so the success% information is not super-useful. Could perhaps be increased, although already with numtrials=1 it takes around 10 min to run.

**Comment by andyfaff** [comment]
Anneal definitely not needed.

The main aim of the GO benchmark suite was to compare success% _and_ how
many nfev it took to achieve that success across all the global optimizers.

For example, if you have a solver that achieves success 50% of the time,
but with nfev=10000, you might want to swap it for a solver that achieves
success 40% of the time, but with nfev=2000. In order for the stats to be
worthwhile I would say one would need numtrials >= 100.  This would take
the best part of a day to run.  If that's the case it's essential that nfev
and %success are recorded.

This kind of benchmark is not one that you would want to run automatically.

On 23 February 2015 at 12:10, Pauli Virtanen <notifications@github.com>
wrote:

> As to your other questions: potential errors in the benchmark functions or
> their docstrings probably don't block merging this. Another thing: I
> removed the anneal benchmark, as it is not present in current scipy --- it
> could be added back, in case we want to compare its performance in previous
> scipy versions.
>
> The current benchmark set also runs with numtrials=1, so the success%
> information is not super-useful. Could perhaps be increased, although
> already with numtrials=1 it takes around 10 min to run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/pull/4191#issuecomment-75477155>.
>



-- 
_____________________________________
Dr. Andrew Nelson


_____________________________________

**Comment by rgommers** [comment]
Regarding point 3 (docstring formatting), it should/can only be changed after hooking these functions up with the html docs. Because they're not importable that's not completely trivial. I planned to figure that one out but got side-tracked. I'd still like to do it, but as @pv says it's not a pre-requisite for merging. So for now let's only check that the contents are correct.

**Comment by rgommers** [comment]
@andyfaff you can assign me a bunch of functions to split the work. If you have a particular workflow on how to check these functions, that would be useful to know.

**Comment by andyfaff** [comment]
@rgommers, I have a whole heap of references.  Mostly the references concur, but there are some were they don't.  In some cases the equations are different from reference to reference. In some cases the global minima aren't even correct for the equation :-(.  This is why it's necessary to have a reference for each function.

    1. If the references don't concur I go with the one that feels 'right'. If it's in the majority, for example.
    2. I check that the quoted f(x) for the global minimum is correct for a given vector x. (This is one of the tests I added).
    3. During the benchmarking if I find a global minimum that is less than the quoted global minimum then I check that the function is correct.  If it is, then I assume that the reference hadn't found the global minimum, and that I've found a lower value.  I then replace the values for f(x) and x in the class.

**Comment by pv** [comment]
In case `numtrials` needs to be large, you can probably increase the
default numtrials and skip the benchmark by default unless a special
environment variable is set, ie.,
```
    def __init__(self):
        def skip(name, ret_value, solver):
            slow = False
            try:
                slow = int(os.environ.get('SCIPY_XSLOW', 0))
            except ValueError:
                pass
            if not slow:
                print("Benchmark skipped -- export SCIPY_XSLOW=1 to enable")
                raise NotImplementedError()
        self.track_all.__func__.setup = skip
```
Or, add separate test function with larger numtrials, in addition to the
one with the small one. It could also make sense to control which test
functions to run for and what numtrials to use via other environment
variables.

**Comment by andyfaff** [comment]
Currently working through all functions, giving each one a literature reference.  Then checking that the minimum is correct.  I'm currently halfway through D. Once that's done the code should be in a reasonable state, but the docstrings (esp the equations) would then need overhauling to check the equations match the code.

**Comment by andyfaff** [comment]
Completed A-M, checked in.

**Comment by andyfaff** [comment]
@pv, @rgommers I've gone through all the benchmark functions giving them a reference as to where they came from in the docstring.  Also, I've checked the function code, that it's (hopefully) correct and that it matches the reference.  There were several instances where the literature disagreed and those all had to be resolved.
The next step would be to overhaul the docstrings. There will be several instances where the docstring doesn't match the equation, and where the global minimum/solution doesn't match the code.

Also, when I run the asv benchmark, `python runtests.py --bench optimize.Global` I get `failed` for several of them.  I don't know what that failed means.  Can either of you shed any light on that?

**Comment by pv** [comment]
`failed` can mean exception raised, or, timeout (if no specific error message was printed). The default timeout is 2 min, can be adjusted by adding a `timeout` attribute to the benchmark class, cf. https://spacetelescope.github.io/asv/writing_benchmarks.html#benchmark-attributes

**Comment by ev-br** [comment]
@andyfaff needs a rebase

**Comment by andyfaff** [comment]
@ev-br, rebased. The current status of this PR is as follows:

1. I am fairly sure that all the benchmark functions are correct (there's over 130, it's a lot to audit).
2. The docstrings for all the benchmark functions have a literature reference from where the problem has been taken, for future reference (see 3).
3. However, the overall state of the docstrings are not in a good state. For example, a lot of the literature may not be consistent for a given function. The original docstring may therefore have the wrong equation, or the wrong minimum, etc. I simply don't have the time to go through all the docstrings to correct them. It's an enormous task
4. Benchmarking of the global optimizers takes a _long time_. Benchmarking is done on the number of function iterations, and the percentage of successful minimisations, not time. Typically each function is run through each minimizer 100 times. Doing all this takes > 1 day. This is not something anyone would want to run automatically, it should be an intentional ask. I don't know enough about the asv setup to do this at this stage.

I think the benchmark functions are a good enhancement to scipy. I don't know how to progress further though. Personally, I would add the benchmark functions as is, after altering the running code to ensure that the go_benchmarks are only run if asked for specifically.

**Comment by pv** [comment]
Thanks, merged in b0ca818, with some modifications to the test runner, so that they are only run when asked. Better ways to run these benchmarks (performance profile plots etc) can be probably worked on later.

**Comment by Hvass-Labs** [comment]
@andyfaff Nice work.

**Pull request merged**
