### PR TITLE
BLD: bump cibuildwheel closes #21275

### LINKED ISSUE #21275: CI: wheel builds for Python 3.13 are failing
[Example log](https://github.com/scipy/scipy/actions/runs/10122442825/job/27994599772)

Summary:
- all the `cp313` and `cp313t` wheel builds are failing (Linux/macOS/Windows)
- they were working two days ago
- 3.13 builds in regular CI are all working fine
- nothing seems to have changed:
    - no new `cibuildwheel`,
    - I verified it's not the new `meson` 1.5.1 (and the first wheel build failures were hours before 1.5.1 was released)
    - no new `pip`, `build`, `manylinux` images
    - the jobs appear to still be using CPython 3.13.0b2, and anyway 3.13.0b4 is already 10 days old
- the failure mode seems related to `numpy` (see traceback below), _however_ if there was an actual problem with `numpy` then regular CI would be failing as well.
- PyWavelets wheel builds are failing with the same problem, and also can't find `numpy-config`. That indicates an issue with install paths (both `bin/` and `lib/python3.13[t]/site-packages` go missing apparently)

```
     ..\scipy\meson.build:48:17: ERROR: Command `C:\Users\runneradmin\AppData\Local\Temp\cibw-run-vyehvmvp\cp313-win_amd64\build\venv\Scripts\python.exe -c "import os
    os.chdir(os.path.join(\"..\", \"tools\"))
    import numpy as np
    try:
      incdir = os.path.relpath(np.get_include())
    except Exception:
      incdir = np.get_include()
    print(incdir)
      "` failed with status 1.
    
    A full log can be found at D:\a\scipy\scipy\.mesonpy-zfcnoua5\meson-logs\meson-log.txt
    [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
```

`build/meson-logs/meson-log.txt` is hard to access when `cibuildwheel` is used, because `cibuildwheel` doesn't give you any way to run another command after a failure, or modify the install command. I don't expect it to be particularly informative though.

The best way to debug this is probably to reproduce this locally with `cibuildwheel`, and then use [`CIBW_DEBUG_KEEP_CONTAINER`](https://cibuildwheel.pypa.io/en/stable/options/#cibw_debug_keep_container) and try to figure out what is happening.

### PR DESCRIPTION
**Pull request by andyfaff**
Seems to unstick 3.13. Closes gh-21275

### CODE REVIEW

**Comment by andyfaff** [comment]
WOndering if we should just use cibuildwheel@2, i.e. always the latest, instead of pinning to a certain version.

**Comment by andyfaff** [comment]
All wheels built. Don't know precisely if this PR fixed things, nothing in the cibuildwheel docs seemed relevant.
Anyway, merging coz all green.

**Comment by ilayn** [comment]
If you put the "closes" clauses in the description instead of the title, it auto-closes the issue otherwise it won't fire up.

**Comment by lucascolley** [comment]
> If you put the "closes" clauses in the description instead of the title, it auto-closes the issue otherwise it won't fire up.

This actually did fire up as the merge commit message included the "closes ...". (but yeah, I prefer it in the description)

**Comment by EwoutH** [comment]
> WOndering if we should just use cibuildwheel@2, i.e. always the latest, instead of pinning to a certain version.

Either that, or use something like dependabot to automatically update it periodically.

**Comment by rgommers** [comment]
Thanks @andyfaff! 

> Don't know precisely if this PR fixed things, nothing in the cibuildwheel docs seemed relevant.

I don't see it either after looking through the changelog. It's possible that it's the interaction 

> Wondering if we should just use cibuildwheel@2, i.e. always the latest, instead of pinning to a certain version.

I'm not sure, that will have the opposite problem, so it's a toss-up.

The desirable long-term solution is to make the builds _fully_ reproducible (including GitHub runner images etc.) and have controlled upgrades, however that's a lot of work (we included it in the new NASA ROSES grant proposal though).

**Pull request merged**
