### PR TITLE
BUG: misc: Ensure fromimage converts mode 'P' to 'RGB' or 'RGBA'.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Convert images with mode 'P' to mode 'RGB' or 'RGBA', otherwise the array of palette indices is returned by `imread()` instead of the array of actual colors.

### CODE REVIEW

**Comment by pv** [comment]
Maybe we'd like to keep 100% backward compat?
Then, adding a kwarg `to_rgb=False` and document it as converting palette images to RGB.

**Comment by WarrenWeckesser** [comment]
> Maybe we'd like to keep 100% backward compat?

I wondered a bit about that, but decided the problem is really just a bug.  `imread` should "just work":  I shouldn't have to know or care that the image is indexed, it should just give me the array of colors.  As it is now, I need some other software (possibly PIL) to know that I read an index rather than the actual image colors.  While it is possible that there are users who learned to expect the index values rather than the actual colors, there could be other users who are currently being misled--they think the image is grayscale because that's what imread() returned, when in fact the image is RGB.  And I wonder what anyone who is relying on getting the index values *does* with that data?  Using `scipy.misc.imread`, they had no way to get the actual colors.  (I guess, if they happened to also be aware of `scipy.ndimage.imread` with its `mode` argument, they could read the file again with `mode='RGB'` or `mode='RGBA'`.)

So, IMHO, the current behavior is bug that should be fixed.  If this breaks someone's code, it seems likely that it happens because their code was already broken (mistaking an RGB image for grayscale).

Now that `scipy.misc.imread` has the `mode` argument (recently unified with `scipy.ndimage.imread`), if you really want the index values, you can explicitly request `mode='P'`:

    In [3]: im = imread('foo3x5x4indexed.png', mode='P')

    In [4]: im
    Out[4]: 
    array([[2, 2, 2, 2, 2],
           [3, 3, 0, 0, 0],
           [1, 1, 1, 1, 1]], dtype=uint8)

(My last commit fixes a warning that this call generated in PIL.)

**Comment by rgommers** [comment]
Treating the current behavior as a bug and just changing it sounds reasonable to me.

**Comment by rgommers** [comment]
@pv are you OK with merging this?

**Comment by pv** [comment]
ok with me

**Comment by rgommers** [comment]
thanks. in it goes then.

**Comment by rgommers** [comment]
Thanks Warren.

**Pull request merged**
