### PR TITLE
DEP: Remove `vertices` in qhull.

### LINKED ISSUE #16270: DEP: remove `vertices` kwarg in qhull
Follow-up to #16255 / #16258

### PR DESCRIPTION
**Pull request by stefmolin**
#### Reference issue

Closes https://github.com/scipy/scipy/issues/16270

#### What does this implement/fix?

Deprecate `vertices` for qhull.

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
This looks good to me. Since the removal is not scheduled until SciPy `1.11.0`, let's hold off on merging until I branch `maintenance/1.10.x` around December 6th or so, and then development of SciPy `1.11.0` can begin.

**Review by j-bowhay — APPROVED** [review]
LGTM (I originally deprecated this) but as stated this is due for 1.11.0 so need to hold fire on merging

**Comment by tylerjereddy** [comment]
I just branched, so this can go in now with two approvals/CI passing.

**Comment by h-vetinari** [comment]
I renamed this PR because it's removing an expired deprecation, rather than deprecating (=promising to remove) something.

I also added a note in the [release notes](https://github.com/scipy/scipy/wiki/*Release-Note-Entries-for-SciPy-1.11.0-(asterisk-makes-this-appear-at-the-top)#expired-deprecations), please double-check. :)

**Pull request merged**
