### PR TITLE
MAINT: cluster: cleaning up VQ/k-means code

### PR DESCRIPTION
**Pull request by perimosocordiae**
Much of the code in scipy.cluster.vq is almost 10 years old, so I figured it was time for an overhaul.

### Backwards compatibility
 - The method for selecting random elements from an array changed, so code relying on a random seed to produce the same codebook initialization will break (e.g., the test I removed).
 - The `py_vq` fallback function now computes all `n * k` distances at once, instead of `k` at a time. This is much faster (see the benchmarks), but does incur a potentially large memory cost if `n` and `k` are large. If this is a problem, we can change it to use a chunking strategy similar to scikit-learn's `pairwise_distances_argmin_min` function.
 - The unused `py_vq2` function is now just an alias for `py_vq`. I'm happy to deprecate it, though.
 - Passing a non-numeric scalar `k` to `kmeans` now throws a `TypeError` rather than a `ValueError`.
 - Some warning/error messages were re-written for clarity.

If you think any of the above changes (or any I missed) are problematic, let me know.

### Benchmarks

I added new benchmarks to make sure k-means and VQ don't regress in terms of speed, and here are the relevant changes for this PR:
```
BENCHMARK                                    BEFORE      AFTER     FACTOR
cluster.KMeans.time_kmeans(10)              61.52ms    53.16ms   0.86403187x
cluster.KMeans.time_kmeans(2)               23.07ms    19.77ms   0.85714533x
cluster.VQ.time_vq(50, 'float128')          96.44ms     3.33ms   0.03448292x
cluster.VQ.time_vq(10, 'float128')          81.17ms     1.02ms   0.01251954x
cluster.VQ.time_vq(2, 'float128')           76.28ms   473.52μs   0.00620748x
```
Note that last 3 lines are the branches which end up in `py_vq`. I think the use of a length-limited `deque` is responsible for the speedup in `kmeans`, but I haven't confirmed that by profiling.

@pv: I'm not sure that my method for generating a consistent random matrix for the benchmarks is the correct approach. The idea is to test each run using the same random values, though the variation in cluster initialization probably makes that irrelevant anyway...

### CODE REVIEW

**Comment by rgommers** [comment]
That looks like a much-needed cleanup!

- selecting random elements changed: I think that's fine, just needs to be documented in the release notes as a backwards incompatible change. 
- ``py_vq2``: go ahead and deprecate that I'd say
- chunking strategy, not so sure. float16/float128 is probably not interesting, but there may be users with large integer arrays.
- the last two points you mention seem perfectly fine

**Comment by perimosocordiae** [comment]
I added a mention in the release notes and deprecated `py_vq2`.

**Comment by rgommers** [comment]
Test failures for kmeans are real.

**Comment by perimosocordiae** [comment]
Old code crept back in during my rebase. Fixed now.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @perimosocordiae!

**Pull request merged**
