### PR TITLE
DEP: remove sym_pos argument from linalg.solve

### LINKED ISSUE #15829: DEP: remove sym_pos-keyword of scipy.linalg.solve
Deprecated in documentation since https://github.com/scipy/scipy/pull/6775, sharpened to actual warning in  #15735 / https://github.com/scipy/scipy/pull/15821.

### PR DESCRIPTION
**Pull request by jyuv**
#### Reference issue

Closes #15829 

#### What does this implement/fix?

Remove sym_pos argument from linalg.solve. Deleted also the test_sym_pos_dep test which checked if using a sym_pos argument will raise a DeprecationWarning

### CODE REVIEW

**Comment by ilayn** [comment]
Thanks @jyuv . This deprecation has been recently added to main and will start emitting warnings until version 1.11.

**Comment by rgommers** [comment]
Thanks @jyuv for the PRs. I will close the ones that aren't mergeable for until next year; if we leave them open until `1.11.0` development starts then maintainers see this in their review queue and spend too much time on it. It can be reopened in the future.

**Comment by j-bowhay** [comment]
Ditto, reopening now development has started for 1.11.0

**Review by tupui — APPROVED** [review]
LGTM and failures in CI are unrelated (Cirrus seems to fail when PRs are old for some reason. Although here I merged main when resolving a conflict.). Thanks again @jyuv

**Comment by h-vetinari** [comment]
I added a [release note](https://github.com/scipy/scipy/wiki/*Release-Note-Entries-for-SciPy-1.11.0-(asterisk-makes-this-appear-at-the-top)#expired-deprecations) for this (and your other PRs, @jyuv), please double-check :)

**Pull request merged**
