### PR TITLE
MAINT: update Boost submodule to include Cygwin fix

### LINKED ISSUE #15296: BUG: SciPy 1.7.x build failure on Cygwin
### Describe your issue.

SciPy 1.7.2 and 1.7.3 fail to build from source on Cygwin - https://trac.sagemath.org/ticket/33080

The failures come in through the vendored boost math library. as reported in https://github.com/boostorg/math/pull/727 and https://github.com/boostorg/math/pull/728

### Reproducing Code Example

```python
pip install scipy
```

### Error message

```shell
scipy/stats/_boost/src/beta_ufunc.cxx:3903:46:   required from here
  /opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/var/tmp/sage/build/scipy-1.7.3/src/scipy/_lib/boost/boost/math/tools/promotion.hpp:148:37: error: static assertion failed: Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.
    148 |          BOOST_STATIC_ASSERT_MSG((0 == ::boost::is_same<type, long double>::value), "Sorry, but this platform does not have sufficient long double support for the special functions to be reliably implemented.");
error: Command "g++ -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -DOPENSSL_NO_SSL3=1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/build=/usr/src/debug/python38-3.8.12-1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/src/Python-3.8.12=/usr/src/debug/python38-3.8.12-1 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -DOPENSSL_NO_SSL3=1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/build=/usr/src/debug/python38-3.8.12-1 -fdebug-prefix-map=/pub/devel/python/python38/python38-3.8.12-1.x86_64/src/Python-3.8.12=/usr/src/debug/python38-3.8.12-1 -D_GNU_SOURCE -DBOOST_MATH_DOMAIN_ERROR_POLICY=ignore_error -DBOOST_MATH_EVALUATION_ERROR_POLICY=user_error -DBOOST_MATH_PROMOTE_DOUBLE_POLICY=false -Iscipy/stats/_boost/include/ -Iscipy/stats/_boost/src/ -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/lib/python3.8/site-packages/numpy/core/include -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/var/tmp/sage/build/scipy-1.7.3/src/scipy/_lib/boost -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/lib/python3.8/site-packages/numpy/core/include -Ibuild/src.cygwin-3.3.3-x86_64-3.8/numpy/distutils/include -I/opt/sage-4525b51c9c556e7d1bf7a4d90ee129c6b7f1d9a7/include -I/usr/include/python3.8 -c scipy/stats/_boost/src/beta_ufunc.cxx -o build/temp.cygwin-3.3.3-x86_64-3.8/scipy/stats/_boost/src/beta_ufunc.o -MMD -MF build/temp.cygwin-3.3.3-x86_64-3.8/scipy/stats/_boost/src/beta_ufunc.o.d -std=c++14 -msse -msse2 -msse3" failed with exit status 1
```

### SciPy/NumPy/Python version information

1.7.x

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-15296 (now really)

### CODE REVIEW

**Comment by mckib2** [comment]
I was just creating a branch for this -- beat me to it :)  LGTM, no reason not to go in as soon as CI comes back green

**Review by mckib2 — APPROVED** [review]

**Comment by rgommers** [comment]
> I was just creating a branch for this -- beat me to it :)

Ah, I figured you'd be asleep by now, since it's my European morning:)

**Comment by DWesl** [comment]
[Build succeeds for me](https://github.com/DWesl/scipy/runs/6791704263?check_suite_focus=true)

**Comment by rgommers** [comment]
Great, thanks for confirming @DWesl!

That build (without tests) took `1h 22m`; there's no log, just `... build in progress`'s. I'm curious why it's that slow though, do you know?

**Comment by DWesl** [comment]
As a guess, there's a lot of C extension modules to be linked, and a lot of files to compile before that, each one requiring two `fork()` calls (one to `gcc.exe` and one to `cc1.exe`), and [Cygwin `fork()` is a lot of work](https://www.cygwin.com/faq.html#faq.api.fork).  

The lack of detailed log is probably from using `pip install -e .` instead of `python setup.py build_ext`.  I can change that to provide better logs, but it won't really speed things up.

**Comment by rgommers** [comment]
Ah makes sense. No need to change, I was just curious since it's unusually slow.

**Comment by DWesl** [comment]
Given jumps in runtime for those tests between 1.6 (pre-Boost) and 1.9 (post-Boost), I suspect how Cygwin interacts with Windows APIs to read files is also slow.

**Pull request merged**
