### PR TITLE
CI/BLD: create cp312 wheels

### PR DESCRIPTION
**Pull request by andyfaff**
This PR adds the machinery to build cp312 wheels for the as-yet unreleased Python 3.12

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @andyfaff!

The macOS failure looks like a connection error in `download_openblas`, I started a re-run to see if it passes. The Windows failure is:
```
sf_error.obj : error LNK2001: unresolved external symbol wrap_PyUFunc_getfperr
```
It seems to correctly install `numpy-1.22.4` in the `pip-packages` stage, so it's not immediately clear to me what is going wrong there.

**Comment by andyfaff** [comment]
I think the windows fail is unrelated. I've touched nothing that would cause issues there

**Comment by andyfaff** [comment]
macOS entry passes now. Feel free to squash merge.

**Review by rgommers — APPROVED** [review]
Great, in it goes!

> I think the windows fail is unrelated. I've touched nothing that would cause issues there

Agreed, it's not even in a wheel build but in the one CI job that still uses `setup.py`.

**Comment by rgommers** [comment]
I triggered wheel builds on main, so we should see nightly wheels for 3.12 appear in the next hour or so.

**Comment by lesteve** [comment]
Very nice :tada:, thanks!

**Pull request merged**
