### PR TITLE
MAINT: special: add tests for cdflib

### PR DESCRIPTION
**Pull request by person142**
Add roundtrip tests for cdflib functions. Use mpmath for one direction
to ensure that the functions are correct and not just consistent.

### CODE REVIEW

**Comment by person142** [comment]
So far all the tests fail; there appear to be a lot of bad corner cases. But I'm less familiar with these functions, so commentary from stats people as to whether I'm feeding them bad/unreasonable arguments is welcome.

**Comment by person142** [comment]
Added tests for more functions and changed it from WIP--about half the functions have tests and I'll leave it at that for now.

**Comment by rgommers** [comment]
@person142 would it be possible to split the tests marked as knownfail in two: one parameter range that passes, and one that fails? Otherwise the test never gets run and so doesn't improve on regression risk.

**Comment by person142** [comment]
A lot of the issues were at large/small values of parameters, so I added tolerances which can mask points close to the endpoints of ``*Arg`` et. al. As improvements are made the tolerances can converge to zero.

Some tests are still marked as known failures because there isn't a clear domain on which they succeed. These mostly involve inverting "discrete" parameters (in quotes because under the hood cdflib is interpolating between the discrete values), and would benefit from a skeptical eye.

**Comment by pv** [comment]
Thanks, lgtm.

**Pull request merged**
