### PR TITLE
BUG: sparse: pass assumeSortedIndices option to scikit.umfpack

### LINKED ISSUE #7387: scipy.sparse.linalg.use_solver(assumeSortedIndices=True) doesn't actually do anything
The documentation for `scipy.sparse.linalg.use_solver` [says](https://github.com/scipy/scipy/blob/28e2ee4d62ac07112c79f68818c435c197c7bd0e/scipy/sparse/linalg/dsolve/linsolve.py#L46):

> Umfpack requires a CSR/CSC matrix to have sorted column/row indices. If
    sure that the matrix fulfills this, pass ``assumeSortedIndices=True``
    to gain some speed.

But the flag is [not used](https://github.com/scipy/scipy/blob/28e2ee4d62ac07112c79f68818c435c197c7bd0e/scipy/sparse/linalg/dsolve/linsolve.py#L53) anywhere in the function. It seems it was removed by [this commit](https://github.com/scipy/scipy/commit/a5d38fc4d0268c32cdc56853d0ef1c4f557dc20c).

### PR DESCRIPTION
**Pull request by cdouglass**
Resolves #7387.

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @cdouglass. This seems straightforward enough; it would be nice to add tests though that are conditional on scikit-umfpack being installed (with ``@dec.skipif(not have_umfpack)``, similar to for example ``have_matplotlib`` in the ``scipy.cluster`` tests.

**Comment by rgommers** [comment]
We can then also add installing ``scikit-umfpack`` in the TravisCI tests.

**Comment by cdouglass** [comment]
@rgommers Thanks for the example to work from. I'll add those tests soon.

**Comment by cdouglass** [comment]
@rgommers Added tests, including documenting some differences in behavior with and without umfpack. Do I need to do anything further for Travis? And should I go ahead and eliminate the differences I've documented?

Regarding the test timeouts, I saw in the discussion of #6989 that there's a goal of moving from nose to pytest. Is anyone currently working on that? Could I help out there?

**Comment by rgommers** [comment]
> Regarding the test timeouts, I saw in the discussion of #6989 that there's a goal of moving from nose to pytest. Is anyone currently working on that? Could I help out there?

No one is currently working on that. Would be awesome if you could tackle that one!

**Comment by rgommers** [comment]
The test error here is real: ``NameError: global name 'umfpack' is not defined``

**Comment by cdouglass** [comment]
Amended, will see if it works now.

**Comment by cdouglass** [comment]
Just the timeout now, so I think this is ready.

**Comment by rgommers** [comment]
Tests are failing on 32-bit Python due to https://github.com/scikit-umfpack/scikit-umfpack/issues/34. Hopefully that can be resolved soon. Otherwise I think it's fine for now to change this to enabling the feature on 64-bit platforms only, or enable everywhere with a disclaimer in the docs and only skip the tests on 32-bit. 

@rc what do you think?

**Comment by rgommers** [comment]
LGTM. ``use_solver`` manipulates global state in an ugly way, but changing that is outside the scope of this PR I think.

**Comment by rgommers** [comment]
> And should I go ahead and eliminate the differences I've documented?

You mean the tests that pass or only warn with ``scikit-umfpack`` but raise exceptions without it? Maybe useful, but not high prio I think.

**Comment by cdouglass** [comment]
Yes, that's what I meant. I'll leave them as-is, then.

**Comment by perimosocordiae** [comment]
Needs rebase due to testing changes. Also needs some workaround for the 32-bit Python issue, perhaps checking the version of umfpack for 32-bit environments and emitting a warning?

**Comment by rc** [comment]
FYI: I can make a new release of `scikit-umfpack` with https://github.com/scikit-umfpack/scikit-umfpack/issues/34 fix, if that would help things.

**Comment by rgommers** [comment]
> FYI: I can make a new release of scikit-umfpack with scikit-umfpack/scikit-umfpack#34 fix, if that would help things.

@rc thanks, that would be helpful. If there's a new scikit-umfpack release then we don't have to ship a new keyword that is documented not to work on 32-bit platforms.

**Comment by rc** [comment]
@rgommers I have just released 0.3.0 on PyPi.

**Comment by rgommers** [comment]
Great, thanks @rc!

@cdouglass can you rebase this PR?

**Comment by cdouglass** [comment]
@rgommers Rebased!

**Comment by cdouglass** [comment]
Test failure seems unrelated: #7598

**Comment by rgommers** [comment]
Okay, in it goes. Thanks Cathy!

**Comment by asmeurer** [comment]
Thanks @cdouglass

**Pull request merged**
