### PR TITLE
BUG: Use raw strings for paths in `__config__.py.in`

### LINKED ISSUE #17934: BUG: meson `__config__` generation - truncated unicode characters
### Describe your issue.

The wheel builder CI entry has started failing for all the `win_amd64` entries. See https://github.com/scipy/scipy/actions/runs/4090921150
The issue comes when the wheel is tested. The issue is probably related to #17862. @ganesh-k13. When the fix is made remember to include `[wheel build]` in the commit message. This will ensure that the failure is exercised.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
+ python -c 'import sys; import scipy; sys.exit(not scipy.test())'
  0
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p68m4u3y\cp38-win_amd64\venv-test\lib\site-packages\scipy\__init__.py", line 141, in <module>
      from scipy.__config__ import show as show_config
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p68m4u3y\cp38-win_amd64\venv-test\lib\site-packages\scipy\__config__.py", line 54
      "include directory": "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-zh9c8rzi\overlay\Lib\site-packages\pythran"
                           ^
  SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
                                                             ✕ 56.74s
Error: Command bash D:\a\scipy\scipy/tools/wheels/cibw_test_command.sh D:\a\scipy\scipy failed with code 1. None
```

### SciPy/NumPy/Python version information

N/A

### PR DESCRIPTION
**Pull request by ganesh-k13**
#### Reference issue
resolves #17934

#### What does this implement/fix?

* `\U` leads to strings being treated as unicode, hence we escape it with raw strings
* Changed bool parameters to real bools instead of string `"True"` and `"False"`

#### Additional information
- Regression caused in https://github.com/scipy/scipy/pull/17862
- I see the above issue marked as `[backport-candidate]`, please mark this for backport as well (I cannot add labels)

### CODE REVIEW

**Comment by mattip** [comment]
It seems these are the build time python and include file paths. Is that going to be relevant for end users?

**Comment by andyfaff** [comment]
Thank you @ganesh-k13.

**Comment by andyfaff** [comment]
@tylerjereddy I think this has to be backported to allow the Windows wheels to be built, otherwise the wheel tests fail.

**Comment by tylerjereddy** [comment]
@andyfaff Indeed, thanks, the Windows wheel failures were observed in the backport PR cross-linked above.

**Pull request merged**
