### PR TITLE
BUG: rv_discrete.ppf() to handle loc

### PR DESCRIPTION
**Pull request by reidarkind**
#### Reference issue

Issue #11132

#### What does this implement/fix?

Updated  rv_discrete to support shifting loc of distribution. Before this change ppf(0) and ppf(1) returns the same result (respectively _a = min(xk) - 1 and _b = max(xk)), even though the optional parameter `loc` is given. 
After the change ppf(0) = _a + loc and ppf(1) = _b + loc

#### Additional information

Thanks to @josef-pkt for his comments!

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @reidarkind! Would you mind adding a regression test in `stats/tests/test_discrete_basic.py`?

**Comment by reidarkind** [comment]
@rgommers I will. I’ll try to submitting a PR tomorrow. Spent a lot of time today trying to set up a dev environ to building locally on my computer (win10) using mingw. Ended up using docker..

**Comment by mdhaber** [comment]
@reidarkind did you follow the instructions [here](http://scipy.github.io/devdocs/building/windows.html)? Where did you run into trouble? Did you build OpenBLAS yourself? Did you happen to use Anaconda?

**Comment by reidarkind** [comment]
Committed a test to my forked repo now, @rgommers. ok?

@mdhaber: I didn't follow those instructions. I found [this](http://scipy.github.io/devdocs/dev/contributor/contributor_toc.html) and then finally used [this approach](http://scipy.github.io/devdocs/dev/contributor/quickstart_docker.html#quickstart-docker)

My main approach was trying to build with
`python setup.py build -c <mingw32|mingw64|cygwin>`

Before trying with docker I tried several things; 
* compiling with [MinGW Installation Manager](https://osdn.net/projects/mingw/releases/)
* compiling with [MinGW64](https://sourceforge.net/projects/mingw-w64/)
* compiling with [cygwin](https://www.cygwin.com/)
* compiling with anaconda; after something like `conda install -c anaconda mingw` and `conda install -c msys2 m2w64-toolchain libpython`

For all of those; no openBLAS, and yes I used Anaconda.
Can't remember the exact error messages, but with mingw32 I got an error message saying that version 14 was not yet supported. With cygwin I got an error message saying that a file (can't recall exactely the file name, but something like: )python36a.dll

Don't think we should be spending time on my dev environ - I'll first to a try on the instructions you linked. :)

**Comment by rgommers** [comment]
Thanks @reidarkind. Almost there, there's a couple of trivial changes you introduced, one of which is failing a PEP8 check. Also, a random seed is missing from the test. Could you take over the most recent commit of https://github.com/rgommers/scipy/tree/reidarkind-master?

**Comment by reidarkind** [comment]
Thanks @rgommers. Cherry-picked your commit just now. Hopefully all cheks will succeed. 
Sorry for the whitespaces. I set up a new dev envirion on my home computer and forgot to install the [Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces) VS Code extension I usually have :)

For the random seed; I agree. Good to set for reproducability. Thanks!

**Comment by rgommers** [comment]
LGTM now, merged. Thanks @reidarkind!

**Pull request merged**
