### PR TITLE
Change to fully PEP440 compliant dev version numbers (always .dev0)

### PR DESCRIPTION
**Pull request by ahjulstad**
A small improvement to the issue in https://github.com/scipy/scipy/issues/4301, first fix in https://github.com/scipy/scipy/pull/4307

### CODE REVIEW

**Comment by argriffing** [comment]
@rgommers does `NumpyVersion` interact reasonably with this?

**Comment by pv** [comment]
NumpyVersion should  be ok. Adding new tests to `scipy/_lib/tests/test__version.py` could be nice though

**Comment by rgommers** [comment]
a test for this would indeed be useful

**Comment by rgommers** [comment]
Merged, thanks @ahjulstad. Test will be added in gh-4542.

**Pull request merged**
