### PR TITLE
ENH: add optional argument for scaled covariance matrix of ODR

### LINKED ISSUE #6842: Covariance matrix returned by ODR needs to be scaled by the residual variance
Originally reported on SO [here][1].

```python
import numpy as np
from scipy.odr import ODR, Model, RealData

def f(B, x):
    return B[0] + B[1]*x + B[2]*x**3

n = 100
sx = 0.3
sy = 2.0
B_real = [-2.3, 7.0, -4.0]
gen = np.random.RandomState(0)
x = np.linspace(-5, 5, n)
y = f(B_real, x)
x +=  gen.randn(n) * sx
y += gen.randn(n) * sy

model = Model(f)
data = RealData(x, y, sx=sx, sy=sy)
odr = ODR(data, model, beta0=[1., 0., 0.])
odr.set_job(fit_type=0)
output = odr.run()

output.pprint()
# Beta: [-2.56437069  6.97055557 -4.11430261]
# Beta Std Error: [ 0.48929313  0.66751299  0.14785663]
# Beta Covariance: [[ 0.2321291  -0.02974486  0.00394905]
#  [-0.02974486  0.43202691 -0.05337819]
#  [ 0.00394905 -0.05337819  0.02119693]]
# Residual Variance: 1.03135611652
# Inverse Condition #: 0.0768799779673
# Reason(s) for Halting:
#   Sum of squares convergence

print("           sd_beta: {}".format(output.sd_beta))
print("sqrt(diag(sd_cov)): {}".format(np.sqrt(np.diag(output.cov_beta))))
#            sd_beta: [ 0.48929313  0.66751299  0.14785663]
# sqrt(diag(sd_cov)): [ 0.48179778  0.65728754  0.14559166]
```

The discrepancy arises because `__odrpack.c` extracts `cov_beta` directly from the FORTRAN routine's `work` vector using the  [ `vcv` index][2]. However, according to the [ODRPACK documentation][3] (p85):

> **`WORK(VCVI)`** is the first element of a p × p array `VCV` containing the values of the covariance matrix of the parameters β *prior to scaling by the residual variance*, where  `WORK(VCVI-1+I+(J-1)*(NP)) = VCV(I,J)` = ̂σ⁻²V β(I, J) for I = 1,... ,p and J = 1,... ,p.

If we multiply the covariance matrix by the residual variance then we get the expected result:

```python
print("                sd_beta: {}".format(output.sd_beta))
print("sqrt(diag(sd_cov * rv)): {}".format(
      np.sqrt(np.diag(output.cov_beta * output.res_var))))
#                 sd_beta: [ 0.48929313  0.66751299  0.14785663]
# sqrt(diag(sd_cov * rv)): [ 0.48929313  0.66751299  0.14785663]
```

[1]: http://stackoverflow.com/q/41028846/1461210
[2]: https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/odr/__odrpack.c#L363
[3]: https://docs.scipy.org/doc/external/odrpack_guide.pdf

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
fix #6842

#### What does this implement/fix?
~~fix covariance matrix of ODR to be scaled by the residual variance and added its tests.~~
I added optional argument for scaled covariance matrix of ODR.
I updated sd_beta docstring to clarify the value is scaled.

### CODE REVIEW

**Comment by pv** [comment]
See discussion in https://github.com/scipy/scipy/pull/448 on probably similar resolved issue in `curve_fit` --- there it appears people have conflicting expectations on what's the right thing to do. If this issue is the same as there, the solution probably should be the same.

**Comment by AtsushiSakai** [comment]
Thank you so much for your comment. I didn’t realize that there are some different expectations for covariance matrix. I agree we should not break backward compatibility, there should be an optional argument to scale it or not. I will try to fix it.

**Comment by kurisutsukato** [comment]
I made a comment related to this issue here:
https://github.com/scipy/scipy/issues/6842#issuecomment-652583761

Basically there seems to be an inconsitency between curve_fit and odr in mode 2 (=least squares) in terms of the calculation of the error of the parameters. The unweightes covariance matrix returned by odr is almost equal to that returned by curve_fit.

**Comment by AtsushiSakai** [comment]
@kurisutsukato Hi. Thank you for your comment. I commented in #6842. PTAL.

**Comment by red-isso** [comment]
💡  @AtsushiSakai 
I suggest to make the additional options and the related output comparable, or better: identical to `scipy.optimize.curve_fit()` . I  followed the discussion here https://github.com/scipy/scipy/issues/6842 as well.  There is, however, a possible issue with `scipy.optimize.curve_fit()` as well, since omitting the error data set `sigma` **and** putting `absolute_sigma=True` still gives an output, but does not make sense since because in `curve_fit(func, x_data, y_data, absolute_sigma=True)` the weighting, i.e., 1/&sigma; is defaulted to unity and the option  `absolute_sigma=True` makes `scipy.optimize.curve_fit()` *think* the real errors are all ones. The correct output would be only given by `curve_fit(func, x_data, y_data)` - where `absolute_sigma` is defaulted to `False`, i.e. the scaling of the covariance matrix matrix in this case, as it discussed here makes sense and one has to be careful what is scaled in which *scenario*.

**Pull request closed without merging**
