### PR TITLE
WIP: CI: add a job with Intel Fortran + MSVC in Azure CI

### PR DESCRIPTION
**Pull request by rgommers**
Taken over from Meson (see [Meson issue gh-10775](https://github.com/mesonbuild/meson/issues/10775#issuecomment-1236366301)), who in turn took it over from MODFLOW, and they from https://github.com/oneapi-src/oneapi-ci (MIT license).
    
[skip actions][skip circle]

First time downloading and installing `ifort` took 4m 35s in total. Of that, 1m 24s was for the download (~1.2 GB), the rest for running the installer. After a first successful run, that download and install was cached; restoring the cache took 1m 48s (it's a hefty 1.86 GB download - 3.98 GB uncompressed). Compiler info after that:
```powershell
"Visual Studio Version: vs2019"
"OneAPI version: 2022.1.0"
"C:\Program Files (x86)\Intel\oneAPI\compiler\2022.1.0\env\vars.bat"
"OneAPI root directory: "
C:\Program Files (x86)\Intel\oneAPI\compiler\2022.1.0\windows\bin\intel64\ifort.exe
```

Configure info:
```
  C compiler for the host machine: cl (msvc 19.29.30146 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64")
  C linker for the host machine: link link 14.29.30146.0
  C++ compiler for the host machine: cl (msvc 19.29.30146 "Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64")
  C++ linker for the host machine: link link 14.29.30146.0
...
  Fortran compiler for the host machine: ifort (intel-cl 2021.6.0)
  Fortran linker for the host machine: xilink.exe xilink 2021.6.0
...
  Found pkg-config: C:\ProgramData\Chocolatey\bin\pkg-config.EXE (0.28)
  Run-time dependency openblas found: YES 0.3.18
  Dependency openblas found: YES 0.3.18 (cached)
```

### CODE REVIEW

**Comment by rgommers** [comment]
Now we're getting somewhere:
```
  [62/1556] Compiling Fortran object scipy/sparse/linalg/_propack/liblib__spropack.a.p/PROPACK_single_sblasext.F.obj
  FAILED: scipy/sparse/linalg/_propack/liblib__spropack.a.p/PROPACK_single_sblasext.F.obj
  "ifort" "-Iscipy\sparse\linalg\_propack\liblib__spropack.a.p" "-Iscipy\sparse\linalg\_propack" "-I..\..\scipy\sparse\linalg\_propack" "/MD" "/nologo" "/warn:general" "/warn:truncated_source" "/stand:none" "/Zi" "/traceback" "/O2" "/Fdscipy\sparse\linalg\_propack\liblib__spropack.a.p\PROPACK_single_sblasext.F.pdb" "/module:scipy\sparse\linalg\_propack\liblib__spropack.a.p" /Foscipy/sparse/linalg/_propack/liblib__spropack.a.p/PROPACK_single_sblasext.F.obj "/c" ../../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F
  ../../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F(5): warning #5117: Bad # preprocessor line
  #ifdef _OPENMP
  -^
  ../../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F(152): warning #5117: Bad # preprocessor line
  #else
  -^
  ../../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F(154): error #5508: Declaration of routine 'PSNRM2' conflicts with a previous declaration
        real function psnrm2(n, x, incx)
  --------------------^
  compilation aborted for ../../scipy/sparse/linalg/_propack/PROPACK/single/sblasext.F (code 1)
```

This has probably been broken since PROPACK support was merged. The issue is that `ifort` doesn't run the preprocessor by default for F77 files, and PROPACK code includes
```C
#ifdef _OPENMP
```
Adding `-fpp` (or `/fpp` on Windows) is the solution apparently, see [the docs on `fpp`](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/preprocessor-options/fpp.html)

**Comment by rgommers** [comment]
The excluding parts for caching probably isn't working well, the file sizes are too large. There's a standalone download for the Fortran compiler at https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#fortran, it's 530 MB rather than several times more.

**Comment by rgommers** [comment]
Next one is:
```
D:\a\1\s\scipy\fft\_pocketfft\pocketfft_hdronly.h(76): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
```

The dependency is found (second one is for pocketfft):
```
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
```
The issue is that what's being found is native Windows threading support, but the code assumes it's `pthreads`. We need to distinguish between the two - there's a Meson issue and PR for making this easier:
- https://github.com/mesonbuild/meson/issues/553
- https://github.com/mesonbuild/meson/pull/7174

It is possible to install `pthreads` on Windows and use it with MSVC, but by default we're going to get Win32 threading.

**Comment by rgommers** [comment]
Next issue:
```
[291/1556] Linking target scipy/special/_specfun.cp39-win_amd64.pyd
  FAILED: scipy/special/_specfun.cp39-win_amd64.pyd
  "xilink.exe"  /MACHINE:x64 /OUT:scipy/special/_specfun.cp39-win_amd64.pyd scipy/special/_specfun.cp39-win_amd64.pyd.p/meson-generated_..__specfunmodule.c.obj "/nologo" "/DLL" "/IMPLIB:scipy\special\_specfun.cp39-win_amd64.lib" "scipy\special\libspecfun.a" "scipy\lib_fortranobject.a" "C:\hostedtoolcache\windows\Python\3.9.13\x64\libs\python39.lib"
     Creating library scipy\special\_specfun.cp39-win_amd64.lib and object scipy\special\_specfun.cp39-win_amd64.exp
  meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol clqmn_
  meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol lqmn_
  meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol clpmn_
  meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol jdzo_
  meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol bernob_
<etc>
```

This seems fun, Fortran name mangling. From https://en.wikipedia.org/wiki/Name_mangling#Fortran:

_"The [GNU](https://en.wikipedia.org/wiki/GNU) [g77](https://en.wikipedia.org/wiki/GNU_Compiler_Collection) compiler converts identifiers to lower case plus an underscore `foo_`, except that identifiers already containing an underscore FOO_BAR have two underscores appended `foo_bar__`, following a convention established by [f2c](https://en.wikipedia.org/wiki/F2c). Many other compilers, including [SGI](https://en.wikipedia.org/wiki/Silicon_Graphics)'s [IRIX](https://en.wikipedia.org/wiki/IRIX) compilers, [GNU Fortran](https://en.wikipedia.org/wiki/GNU_Fortran), and [Intel](https://en.wikipedia.org/wiki/Intel)'s Fortran compiler (except on Microsoft Windows), convert all identifiers to lower case plus an underscore (`foo_` and `foo_bar_`, respectively). On Microsoft Windows, the Intel Fortran compiler defaults to uppercase without an underscore"_

Info on this seems to have disappeared from the Intel Fortran docs, but content from the link referenced from Wikipedia can still be found (and confirms the above): http://web.archive.org/web/20160817173106/https://software.intel.com/en-us/node/525345

**Comment by rgommers** [comment]
Okay, this one was kinda expected:
```
  [306/1556] Linking target scipy/linalg/_fblas.cp39-win_amd64.pyd
  FAILED: scipy/linalg/_fblas.cp39-win_amd64.pyd
  "xilink.exe"  /MACHINE:x64 /OUT:scipy/linalg/_fblas.cp39-win_amd64.pyd scipy/linalg/_fblas.cp39-win_amd64.pyd.p/meson-generated_..__fblasmodule.c.obj scipy/linalg/_fblas.cp39-win_amd64.pyd.p/meson-generated_..__fblas-f2pywrappers.f.obj scipy/linalg/_fblas.cp39-win_amd64.pyd.p/..__build_utils_src_wrap_dummy_g77_abi.f.obj "/nologo" "/DLL" "/IMPLIB:scipy\linalg\_fblas.cp39-win_amd64.lib" "scipy\lib_fortranobject.a" "c:/opt/openblas/if_32/64/lib/libopenblas.a" "C:\hostedtoolcache\windows\Python\3.9.13\x64\libs\python39.lib"
     Creating library scipy\linalg\_fblas.cp39-win_amd64.lib and object scipy\linalg\_fblas.cp39-win_amd64.exp
  libopenblas.a(zherk_kernel_LC.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
...
  libopenblas.a(openblas_error_handle.obj) : error LNK2001: unresolved external symbol __mingw_vfprintf
  libopenblas.a(zgemv_thread_o.obj) : error LNK2019: unresolved external symbol __emutls_get_address referenced in function zgemv_thread_o
...
  scipy\linalg\_fblas.cp39-win_amd64.pyd : fatal error LNK1120: 5 unresolved externals
```

`___chkstk_ms` and other such symbols are provided by `libgcc`. We can't expect our own mingw-built `libopenblas.a` to work here. Dynamic linking _may_ work, but preferably should use MKL in this setup.

**Comment by greenrongreen** [comment]
> Next issue:
> 
> ```
> [291/1556] Linking target scipy/special/_specfun.cp39-win_amd64.pyd
>   FAILED: scipy/special/_specfun.cp39-win_amd64.pyd
>   "xilink.exe"  /MACHINE:x64 /OUT:scipy/special/_specfun.cp39-win_amd64.pyd scipy/special/_specfun.cp39-win_amd64.pyd.p/meson-generated_..__specfunmodule.c.obj "/nologo" "/DLL" "/IMPLIB:scipy\special\_specfun.cp39-win_amd64.lib" "scipy\special\libspecfun.a" "scipy\lib_fortranobject.a" "C:\hostedtoolcache\windows\Python\3.9.13\x64\libs\python39.lib"
>      Creating library scipy\special\_specfun.cp39-win_amd64.lib and object scipy\special\_specfun.cp39-win_amd64.exp
>   meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol clqmn_
>   meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol lqmn_
>   meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol clpmn_
>   meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol jdzo_
>   meson-generated_..__specfunmodule.c.obj : error LNK2001: unresolved external symbol bernob_
> <etc>
> ```
> 
> This seems fun, Fortran name mangling. From https://en.wikipedia.org/wiki/Name_mangling#Fortran:
> 
> _"The [GNU](https://en.wikipedia.org/wiki/GNU) [g77](https://en.wikipedia.org/wiki/GNU_Compiler_Collection) compiler converts identifiers to lower case plus an underscore `foo_`, except that identifiers already containing an underscore FOO_BAR have two underscores appended `foo_bar__`, following a convention established by [f2c](https://en.wikipedia.org/wiki/F2c). Many other compilers, including [SGI](https://en.wikipedia.org/wiki/Silicon_Graphics)'s [IRIX](https://en.wikipedia.org/wiki/IRIX) compilers, [GNU Fortran](https://en.wikipedia.org/wiki/GNU_Fortran), and [Intel](https://en.wikipedia.org/wiki/Intel)'s Fortran compiler (except on Microsoft Windows), convert all identifiers to lower case plus an underscore (`foo_` and `foo_bar_`, respectively). On Microsoft Windows, the Intel Fortran compiler defaults to uppercase without an underscore"_
> 
> Info on this seems to have disappeared from the Intel Fortran docs, but content from the link referenced from Wikipedia can still be found (and confirms the above): http://web.archive.org/web/20160817173106/https://software.intel.com/en-us/node/525345
> 
> EDIT: `numpy.distutils` has the following hardcoded flags, which makes things work with `f2py`:
> 
> ```
>         opt = ['/nologo', '/MD', '/nbs', '/names:lowercase',
>                '/assume:underscore', '/fpp']
> ```
> 
> xref [numpy/numpy#21484](https://github.com/numpy/numpy/issues/21484)
> 
> * `/MD` is for dynamic linking (`/MT` would be static): [docs on `MD`](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/linking-or-linker-options/md.html)
> * `/names:lowercase` should resolve the name mangling issue we see here: [docs on `names`](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/language-options/names.html)
> * `/assume:underscore`: from [the docs on `assume`](https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/compiler-reference/compiler-options/language-options/assume.html): _On Windows systems, the compiler does not append an underscore character to external user-defined names. On Linux* and macOS systems, the compiler appends an underscore character to external user-defined names._

The abiility to decorate symbols with one or 2 underscores is still in the compiler and [documented here](https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2023-1/assume-002.html).  Scroll and look for 2underscore near the bottom of this page.
We did remove the reference to the origins of this decoration since: 1) most people don't care where it came from and 2) g77 is so old and unused that very few people even remember it.  It might be a good historical challenge question at a bar trivia night for programming wonks.

**Comment by ev-br** [comment]
I wonder to what extent the this PR is affected by the upcoming transition from `ifort` to `ifx`
https://fortran-lang.discourse.group/t/deprecation-notice-for-intel-fortran-compiler-classic-ifort/6841

**Comment by andyfaff** [comment]
We've stopped using Azure as a CI provider for the time being, having consolidated various CI runs on other providers. I'm going to close the PR, but if people want to resurrect on e.g. GHA, they are welcome to create an entry.

**Comment by h-vetinari** [comment]
I've spoken with Ralf about this, and a next reasonable step will be to introduce a flang-based CI on windows (there's builds in conda-forge now; still needs a patched meson, but we can limit the impact of that).

**Pull request closed without merging**
