### PR TITLE
Install Pythran from sources for python 3.10

### PR DESCRIPTION
**Pull request by serge-sans-paille**
This should fix the CI error in https://github.com/scipy/scipy/pull/13595

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
(note: pythran doesn't test with cpython3.10)

**Comment by serge-sans-paille** [comment]
@rgommers : is this the fix you were looking for?

**Comment by tupui** [comment]
Thanks @serge-sans-paille! I guess the change makes sense.

Side note: I would suggest that we change the name `Nightly CPython` as now it encompasses NumPy and Pythran. It would be clearer to either just call it `Nightly` or `Nightly CPython/NumPy/Pythran` 🤷‍♂️   What do you think?

**Comment by ilayn** [comment]
Indeed we probably need some separate job for non-CPython stuff. This was meant to be a canary-in-the-mine for the upcoming Python versions. Because often they are the hardest bugs to figure out.

**Comment by tupui** [comment]
> Indeed we probably need some separate job for non-CPython stuff. This was meant to be a canary-in-the-mine for the upcoming Python versions. Because often they are the hardest bugs to figure out.

Ah but you mean having yet another job? Is this really necessary, can we not keep these 3 in here? The only reason to separate would be to make sure that the bug is cause by one or the others. But I think it would be clear enough even now no?
IMO if we have CI ressources I would prefer to use them for another plateforme or something else.

**Review by rgommers — APPROVED** [review]
Yes, this makes sense. We should merge it as is, no separate job is needed. Pythran-related breakage is going to be build-time, and it'll be obvious what the problem is in most cases.

Thanks @serge-sans-paille

**Comment by rgommers** [comment]
>  It would be clearer to either just call it `Nightly` or `Nightly CPython/NumPy/Pythran`. What do you think?

Happy with anything there. Cleanups in CI or added docs are always useful.

**Pull request merged**
