### PR TITLE
TST: special: test ufuncs in special at `nan` inputs

### PR DESCRIPTION
**Pull request by person142**

### CODE REVIEW

**Comment by pv** [comment]
Maybe nicer to tell pytest in a more declarative way:
```
def _ufuncs():
     for item in sc.__dict__:
         if not isinstance(item, np.ufunc):
             continue

         msg = KNOWNFAILURES.get(item)
         if msg is None:
             yield item
         else:
             yield pytest.param(item, marks=pytest.mark.xfail(run=False, 
reason=msg))

@pytest.mark.parametrize("func", _ufuncs()):
...
```

**Comment by person142** [comment]
Made the changes--very cool, did not know about `pytest.mark`.

Also sorted the dictionary keys which will hopefully take care of the Travis failures.

**Comment by pv** [comment]
appveyor looks like this hangs somewhere. in theory, there should be 15min timeout after which pytest bails out, but maybe it doesn't work in tight compiled-code loop. you may want to add -v to the appveyor test to find which one fails

**Comment by person142** [comment]
Yup went through a couple of cycles of this on my own machine; hopefully there won't be too many more.

**Comment by xoviat** [comment]
> appveyor looks like this hangs somewhere. 

Happened to me while testing hyp2f1. The CI locks up hard on some `1e30` test.

**Comment by pv** [comment]
Also pbvv crashes.

**Comment by person142** [comment]
Ok, `pbvv` added to known failures, AppVeyor verbose output turned off, and commits squashed.

We'll see what the CIs say.

**Pull request merged**
