### PR TITLE
DOC: special: Updates for smirnov and smirnovi

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
* Copy-edit the docstrings: fix section order, fix long lines (PEP8), use f-strings, etc.
* Add Examples to smirnovi

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Marked as draft for now.  Even before this change, the plots generated by the run on CircleCI do not match the plots generated locally.  There is something wrong with the plots on CircleCI.

**Comment by WarrenWeckesser** [comment]
If you compare the plot in the `smirnov` docstring in the [released docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.smirnov.html), the [development docs](https://scipy.github.io/devdocs/reference/generated/scipy.special.smirnov.html), and in the rendered docs of any recent pull request (such as [this one](https://output.circle-artifacts.com/output/job/9230d260-983d-4436-b2dd-8231b95fe8ee/artifacts/0/html/reference/generated/scipy.special.smirnov.html), while it lasts), you'll see that, while all display the same `x` array, these values don't match the locations of the jumps in the plot of the empirical CDF.  Each rendering of the plot has a different empirical CDF.  I didn't figure out why the plot was not reproducible even though the `x` values are.  Since there are just 5 points in `x`, there is actually no need to generate `x` randomly.  In the latest update of the pull request, I changed `x` to be a literal array.  That seems to have avoided the problem with the plot, as can be seen in the new [docstring](https://output.circle-artifacts.com/output/job/62453169-8c1a-4125-b86c-44e3a7ac2213/artifacts/0/html/reference/generated/scipy.special.smirnov.html), where the plot of the empirical CDF matches the `x` values.

**Review by person142 — APPROVED** [review]

**Comment by WarrenWeckesser** [comment]
Merged main.  Updated doc links:
* [`smirnov`](https://output.circle-artifacts.com/output/job/51ebd09a-6669-49ae-9ebf-a6167526d584/artifacts/0/html/reference/generated/scipy.special.smirnov.html)
* [`smirnovi`](https://output.circle-artifacts.com/output/job/51ebd09a-6669-49ae-9ebf-a6167526d584/artifacts/0/html/reference/generated/scipy.special.smirnovi.html)

**Review by tylerjereddy — APPROVED** [review]
I took a quick look, but I'm mostly leaning on Josh's approval as a `special` regular + CI is passing, it is a doc-only change, and I need to start merging in `1.10` stuff that looks ready.

**Pull request merged**
