### PR TITLE
MAINT: scipy.io.wavfile: No infinite loop when trying to read a malformed file

### PR DESCRIPTION
**Pull request by mp4096**
If the RIFF chunk contains false information about the file size,
`scipy.io.wavfile.read()` gets stuck in an infinite loop as it tries
to read beyond the EOF.

Notice that the `mmap=True` call is still broken if the `data` chunk
has wrong size specification as well.

See #6700

### CODE REVIEW

**Comment by pv** [comment]
The `while` loop probably should not be using fid.tell() at all.
Instead, it should be `while True: chunk_id = fid.read(4); if not
chunk_id: break; else if len(chunk_id) < 4: warnings.warn("incomplete
wav chunk", WavFileWarning)`

**Comment by pv** [comment]
Or possibly, `while fid.tell() < file_size: (... the same as above ...)`  in case the wav file is embedded in a bigger file, or contains some garbage at the end.

**Comment by mp4096** [comment]
@pv Thank you, that's a much better solution. I've updated the PR, this should also fix the CI builds.

**Comment by pv** [comment]
A test checking the behavior here should be added to `scipy/io/tests/test_wavfile.py`.
Data files (preferably as small as possible) can be under  `scipy/io/tests/data/`.

**Comment by mp4096** [comment]
Yep, added unit tests.

---

When working on the test examples I realised that an unexpected EOF or an incomplete chunk may come before the `fmt ` chunk, when return variable `fs` is not defined. The same goes for the `data` chunk and `data` return variable.

So I think it is much better to be more cautious and raise an exception if an excepted EOF or an incomplete chunk has been consumed.

**Comment by pv** [comment]
Thanks, merged!

**Comment by pv** [comment]
The `while` loop probably should not be using fid.tell() at all.
Instead, it should be `while True: chunk_id = fid.read(4); if not
chunk_id: break; else if len(chunk_id) < 4: warnings.warn("incomplete
wav chunk", WavFileWarning)`

**Comment by FabricioS** [comment]
Is there a possibility to still retrieve the data (issuing a warning instead of the ValueError) ?
In my case, I have a wav file that only has a three additional meaningless bytes that invalidates the whole reading...

**Comment by mp4096** [comment]
If you need it just once, you can create a throwaway `virtualenv` exactly for this and modify the `scipy/io/wavfile.py` file as follows.
In line 241, change
```python
while fid.tell() < file_size
```
to
```python
from os.path import getsize
...
while fid.tell() < min(file_size, getsize(filename))
```

In general, though, I am against throwing a warning instead of an error. I thought about making the code as forgiving as possible, but failing late is not a good idea, see [this comment](https://github.com/scipy/scipy/pull/6716#issuecomment-255614303).

**Comment by FabricioS** [comment]
in fact, in the file I mentioned, the file_size is correct, and wavfile.read loops trying to read 4 bytes while only 3 are available (the chunk_id is then empty) The solution given b yPauli (comment just above mine) would succeed in getting out of the while loop.

**Comment by mp4096** [comment]
Oh, sorry, I see.

The problem is still the same, what do we do if the file is corrupted earlier and `data` or `fs` is not set? When I implement Pauli's solution, I get the following:

```
Traceback (most recent call last):
...
in read
    return fs, data
UnboundLocalError: local variable 'fs' referenced before assignment
```

One could surely track whether `fs` or `data` exists and then either raise an exception or a warning. However, this would lead a lot of unit tests etc.

On the other hand we could always emit a warning (+ `break`) and hope the user will understand the error message about `fs` / `data` being not set.

@pv what do you think?

**Pull request merged**
