### PR TITLE
MAINT: re-introduce multiprocessing tests on Python3.8

### LINKED ISSUE #11835: tests with `multiprocessing` hang on Python 3.8 on macOS
I'm running the whole test suite on macOS on Python 3.8 (via Github Actions on my local machine (Catalina)). I'm seeing several issues with multiprocessing, such as #11827.

They're related to https://bugs.python.org/issue38501. The tests that hang are:

- [`integrate.tests.test__quad_vec.test_quad_vec_pool`](https://github.com/scipy/scipy/blob/master/scipy/integrate/tests/test__quad_vec.py#L94)

I think the best thing to do at the moment is to use the skipif decorator (possibly also coupled to Darwin):

```
    @pytest.mark.skipif(multiprocessing.get_start_method() != 'fork',
                        reason=('multiprocessing with spawn method is not'
                                ' compatible with pytest.'))
```

### PR DESCRIPTION
**Pull request by andyfaff**
closes #11835

### CODE REVIEW

**Comment by andyfaff** [comment]
(hold off on merging until #11835 gets discussed in more detail)

**Comment by andyfaff** [comment]
I've taken out all the skips on Python3.8 for multiprocessing, and added `freeze_support` to `runtests.py`.  The whole test suite passes on macOS with Python 3.8 (with no hangs). If it passes on the other CI's, then I think I should clean up the modifications (at the moment they're just commented out) a little bit before merge.
I also removed the `gc.collect()` from the differential_evolution solver tests...

**Comment by larsoner** [comment]
Thanks for figuring it out, and sorry about trying to lead you down the wrong path!

It looks like there is a timeout (?):

https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=5610&view=logs&j=bffd5c03-492a-553d-5bbe-cf7a5bbf4943&t=259dec7b-a5ee-5fee-f3e0-1c0a04e08da9

**Comment by WarrenWeckesser** [comment]
> It looks like there is a timeout...

FWIW, I've found that if I follow the "Details" link of the failing Azure test suite, and click on "Re-run checks" and select "Re-run failed checks", more often than not the test does not timeout in the rerun.  Go figure.

**Comment by andyfaff** [comment]
I'll clean this up before a merge

**Comment by andyfaff** [comment]
Cleaned up.

**Review by larsoner — APPROVED** [review]
Changes look good to me, +1 for merge

@peterbell10 feel free to merge if you're happy

**Pull request merged**
