### PR TITLE
BUG: sparse: fix diags for nonsquare matrices

### PR DESCRIPTION
**Pull request by pv**
sparse.diags had incorrect array length check for nonsquare matrices, affecting sub/superdiagonals corresponding to the longer dimension.

Not sure what backward compat issues this makes, but it's a bugfix.

### CODE REVIEW

**Comment by larsmans** [comment]
Should this be in the release notes? (Or a waning against previous versions in the docstring?)

**Comment by rgommers** [comment]
Hit green button, add to 0.17.0 release notes, and maybe point out on the scipy-user mailing list as well?

**Comment by pv** [comment]
Updated: allow too long diagonal arrays (discard unnecessary trailing elements).
This should preserve backward compat, in case someone worked around the bug, and it may also be useful as one can then pass in the diagonals in a numpy array.

**Comment by rgommers** [comment]
Allright, in it goes. Don't think that it's essential to mention separately in the release notes now that backwards compat is preserved; it's just a regular bugfix now.

**Comment by rgommers** [comment]
Thanks @pv

**Pull request merged**
