### PR TITLE
STY: special: use indent width of 4 in clang-format

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
https://github.com/scipy/scipy/pull/19613#issuecomment-1836503053
https://github.com/scipy/scipy/pull/19613#issuecomment-1837120479

#### What does this implement/fix?
- Changes from indent width 2 to 4 in the clang-format of `scipy/special/special`
- Adds `git blame` ignores for the style only changes

### CODE REVIEW

**Comment by steppi** [comment]
Thanks @lucascolley. While were at it, @izaid, is it cool if we set the ColumnLimit to something smaller like 90? I like to code with two windows open side by side.

**Comment by izaid** [comment]
Thanks @lucascolley! That's actually really helpful!

I'm less keen on changing the columnwidth.

**Comment by steppi** [comment]
> I'm less keen on changing the columnwidth

Yeah. I’m working on porting cephes stuff now and saw the shorter column width isn’t working out.

**Review by steppi — APPROVED** [review]
Looks good to me.

**Pull request merged**
