### PR TITLE
BUG: redundant fft in signal.resample

### PR DESCRIPTION
**Pull request by wenhui-prudencemed**
```
     
    x = np.asarray(x)
    X = sp_fft.fft(x, axis=axis)
    Nx = x.shape[axis]

    # Check if we can use faster real FFT
    real_input = np.isrealobj(x)

    # Forward transform
    if real_input:
        X = sp_fft.rfft(x, axis=axis)
    else:  # Full complex FFT
        X = sp_fft.fft(x, axis=axis)

```

the second line: **X = sp_fft.fft(x, axis=axis)** is redundant and the X variable will be override by rfft or fft based on if it's real input.

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
Looks like a simple oversight to me, +1 for merge

**Comment by larsoner** [comment]
Labeling as backport candidate as it would be nice to backport this if possible

**Comment by larsoner** [comment]
Actually this is a bug introduced in 1.4, so I'll just set the milestone (hopefully it can make it into the release)

**Comment by tylerjereddy** [comment]
Why is this a bug/defect? Isn't this just a maintenance commit to remove a pointless (but largely harmless) line of code? Otherwise, we'd need a regression test for an issue of some sort, right?

Anyway, should be simple to backport so I suppose I will.

Thanks

**Comment by larsoner** [comment]
Defect from a performance standpoint (it's a potentially slow operation and useless here) not in terms of the output, so it's difficult/annoying to write a unit test for it. You could mock the calls and ensure fft is only called once but it seems like overkill.

**Comment by wenhui-prudencemed** [comment]
> Why is this a bug/defect? Isn't this just a maintenance commit to remove a pointless (but largely harmless) line of code? Otherwise, we'd need a regression test for an issue of some sort, right?
> 
> Anyway, should be simple to backport so I suppose I will.
> 
> Thanks

is it possible to generate the benchmark report for each release on specific aws instance so we can compare the performance more easily between the releases and figure out the potential performance issues.

**Comment by mdhaber** [comment]
Thanks @wenhui-prudencemed! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Pull request merged**
