### PR TITLE
DOC: update doctests to satisfy scipy-doctests==1.2.0

### LINKED ISSUE #20921: DOC: stats: wrong docstrings of `*Result` classes
Quite a few docstring examples in scipy.stats show an incorrect repr of `*Result` classes. Consider the docstring of `ttest_ind` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html#scipy.stats.ttest_ind):

```
In [15]: import numpy as np
    ...: from scipy import stats
    ...: rng = np.random.default_rng()

In [16]: rvs1 = stats.norm.rvs(loc=5, scale=10, size=500, random_state=rng)
    ...: rvs2 = stats.norm.rvs(loc=5, scale=10, size=500, random_state=rng)
    ...: stats.ttest_ind(rvs1, rvs2)
Out[16]: TtestResult(statistic=0.40375493221427916, pvalue=0.6864794357079085, df=998.0)
```

Note that `TtestResult` has three keys (`statistic`, `pvalue` and `df`) while the docstring example only shows two, `statistics` and `pvalue`.

Yes, `TtestResult` unpacks into these two values for backwards compatibility. 

So we need to either adjust the repr or fix the docstrings.

This was not caught by the smoke-docs machinery because of a bug which just got fixed in https://github.com/scipy/scipy_doctest/pull/162 by @luxedo. The fix will be available in the upcoming scipy-doctest==1.2.0 release relatively soon.

Meanwhile to see the failures locally, do 

```
$ # clone scipy-doctest & cd 
$ pip install -e .
$ cd path/to/scipy
$ python dev.py smoke-docs -s stats
```

### PR DESCRIPTION
**Pull request by luxedo**
#### Reference issue

Closes https://github.com/scipy/scipy/issues/20921

#### What does this implement/fix?

Updates doctests to satisfy the upcoming scipy-doctests==1.2.0

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
happy if `scipy-doctests` is!

**Comment by ev-br** [comment]
NB: scipy-doctest 1.2 is still imaginary at this point, the svipy CI is on 1.1 which does not include the fix. Will test it manually though.

**Comment by ev-br** [comment]
Tested it locally to confirm it works. And it does. Fixes follow the suggestion of https://github.com/scipy/scipy/issues/20921#issuecomment-2155312955 and are LGTM. Merged. Thanks @luxedo , Lucas.

**Comment by ev-br** [comment]
scipy-doctest==1.2.0 is on PyPI.

**Pull request merged**
