### PR TITLE
#6318 avoid overflow when x is an integer array

### PR DESCRIPTION
**Pull request by karischoonbee**

### CODE REVIEW

**Comment by person142** [comment]
You want to be merging those commits into master--that will take care of the CircleCI failure and the Python 3.5 Travis failure (and likely the pep8 failure).

**Comment by ev-br** [comment]
Thanks for the pull request!

It needs some more work though,

- Llike Josh said, all PRs start against the master branch. We might backport it to 0.18.x (which is currently in the rc phase), but there's no plan for a 0.17.2 release.

- It needs a regression test: something which fails in master and does not fail with your changes. There is a quick draft in gh-6318, using np.int8. 

- A bit more care is needed with division-by-two in integer arithmetic: notice that `3/2 + 5/2 != (3+5)/2`, on python2 at least. Tests need to cover both even and odd cases.

- (minor quibble) please edit the commit message to start with `BUG` (see http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html for prefixes)

**Comment by karischoonbee** [comment]
Thanks, I'll make those changes. I am converting the input to float by dividing by 2.0 so no integer division should be taking place.

In which class do you want me to put the test? TestRegression or TestInterp1D?

**Comment by ev-br** [comment]
Either's fine. 
I would add it to TestInterp1D, bur I did not know the other one existed :-)

**Pull request closed without merging**
