### PR TITLE
REL: set version to 1.8.0.dev0

### PR DESCRIPTION
**Pull request by tylerjereddy**
Don't merge until `1.7.0` release notes update has been finalized/merged & we have branched `maintenance/1.7.x.`

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Ok, release notes merged and I've pushed the maintenance branch.

The Windows-specific CI failures are strange, but I'm going to merge this regardless since this shouldn't really have platform-specific deleterious effects...

```
2021-05-27T05:14:06.5886344Z   Building wheel for scipy (PEP 517): finished with status 'done'
2021-05-27T05:14:06.7072155Z   Created wheel for scipy: filename=scipy-1.8.0.dev0_.1833e8e-cp37-cp37m-win_amd64.whl size=33611782 sha256=bbba0c4d4a641099d939f5e63c93204a0057b4025b6da4b30725286551f55e43
2021-05-27T05:14:06.7073711Z   Stored in directory: C:\Users\VSSADM~1\AppData\Local\Temp\pip-ephem-wheel-cache-emd5u_2j\wheels\ab\d6\d3\43d300a6071326ace16aad002d166549bd5ba4bd8647fcad25
2021-05-27T05:14:06.7196184Z   WARNING: Built wheel for scipy is invalid: Metadata 1.2 mandates PEP 440 version, but '1.8.0.dev0-.1833e8e' is not
2021-05-27T05:14:06.7197962Z Failed to build scipy
2021-05-27T05:14:06.7201492Z ERROR: Failed to build one or more wheels
2021-05-27T05:14:06.7349162Z Exception information:
```

**Comment by tylerjereddy** [comment]
cc @rgommers for that issue maybe

**Comment by rgommers** [comment]
I'll look into it, `'1.8.0.dev0-.1833e8e'` is indeed not a valid version string. I have an idea about what caused it.

**Comment by tupui** [comment]
Isn't it because there is no other commit on the branch, so the increment number is empty?

**Comment by tupui** [comment]
Actually caused because there is no tag for `v1.7.0`:

```python
out = _minimal_ext_cmd(['git', 'rev-list', 'HEAD', prev_version_tag,
                        '--count'])
# fatal: bad revision '^v1.7.0'
```

**Comment by tupui** [comment]
> Actually caused because there is no tag for `v1.7.0`:
> 
> ```python
> out = _minimal_ext_cmd(['git', 'rev-list', 'HEAD', prev_version_tag,
>                         '--count'])
> # fatal: bad revision '^v1.7.0'
> ```

So `out=b''` in this case.

**Pull request merged**
