### PR TITLE
DEP: Deprecate private namespaces in `scipy.odr`

### PR DESCRIPTION
**Pull request by Smit-create**
#### Reference issue

* See: #14360
* References: https://github.com/scipy/scipy/pull/14419, https://github.com/scipy/scipy/pull/14447/

cc @rgommers

### CODE REVIEW

**Review by AnirudhDagar — CHANGES_REQUESTED** [review]
Hi @Smit-create, thanks for the PR.

Just reviewing this cursorily. I've a few comments:
* You'll probably (not tested) need to update the [mypy.ini](https://github.com/scipy/scipy/blob/3fa75b9114982b332265ece2e2eeef482baa2f02/mypy.ini#L602) config while deprecating these modules. This will fix the Lint failures.
* We need to preserve the git blame and git history functionality when making these deprecations. This is very important and with the current way, we'll lose it as seen from the diff. Instead of a single commit, please break this PR down into two separate commits. The first commit can just have `git mv ...` and in the second commit you may add the deprecation warnings etc. This way on merging, we can do a merge commit (instead of a squash commit) which will help us save the history.

For reference, you can look at @rgommers' [#14360 comment](https://github.com/scipy/scipy/issues/14360#issuecomment-874978101) and  PR #14447.

**Comment by AnirudhDagar** [comment]
Lint checks are still failing, you need to add `# noqa: F822` comments at the relevant places to avoid those. This is due to the recent changes in #14456. Feel free to start with `linalg` in parallel. :)

**Review by rgommers — APPROVED** [review]
Thanks @Smit-create, this looks good now! I fixed the last lint failure and squashed things back to 2 commits (useful in these PRs to keep history always to 2 commits, one for rename, one for re-adding the non-underscored files).

@AnirudhDagar thanks for the review!

**Comment by rgommers** [comment]
> If this looks good should I start working on `linalg` next?

Yep, and it's fine to work on other modules in parallel too if you're waiting for review. Now that the first PR is merged the rest should be smooth sailing - and we can always rewrite history later.

**Pull request merged**
