### PR TITLE
MAINT: stats: separate UNU.RAN functionality to its own submodule

### LINKED ISSUE #14830: do CDF inversion methods have to be public?
@chrisb83, @mdhaber, @tirthasheshpatel I had completely missed the API changes to add `NumericalInverseHermite` and other public classes listed in http://scipy.github.io/devdocs/reference/stats.html#random-variate-generation-cdf-inversion. Was that discussed on the mailing list, and do these things have to be public?

My impression is that it's a complex API that is quite unlike other APIs in `scipy.stats`. They take distribution objects that are not the regular `stats` distributions:

_An instance of a class with `pdf` and `dpdf` methods._

It looks to me at first glance that this should be private infrastructure which supports improved RVS generation in the regular distribution classes?

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### Reference issue

closes #14830 

#### What does this implement/fix?

Moved all the UNU.RAN random number generators to their own submodule `scipy.stats.sampling`. Added the submodule entries to API docs and user manual. Previously, `NumericalInverseHermite` was present in `scipy.stats` but it has now been moved to `scipy.stats.sampling` with only an alias to it in `scipy.stats`. When `scipy.stats.NumericalInverseHermite` is called, it emits a DeprecationWarning asking the user to use `NumericalInverseHermite` from `scipy.stats.sampling`.

### CODE REVIEW

**Comment by chrisb83** [comment]
Hi Tirth,

thanks, all changes look good and the name 'sampling' was discussed on the mailing list. There is just one point left to fix. In the refguide check, I saw the following message:

```
Checking tutorial files at doc/source/tutorial/*.rst:

====================
scipy.stats.sampling
====================

Non-deprecated objects in __all__: 7
Objects in refguide: 6

ERROR: objects in scipy.stats.sampling.__all__ but not in refguide::

    UNURANError

This issue can be fixed by adding these objects to
the function listing in __init__.py for this module
```

**Review by chrisb83 — APPROVED** [review]
All tests pass and the rendered doc/tutorials look good.

**Comment by chrisb83** [comment]
Remaining test failures are not related:
FAILED scipy/stats/tests/test_distributions.py::TestStudentizedRange::test_moment_against_mp[case_result1]
FAILED scipy/stats/tests/test_distributions.py::TestStudentizedRange::test_moment_vectorization

**Comment by mdhaber** [comment]
@DominicChm @swallan Do these failures ring a bell?

<details>

```

        mu2        = None
        n          = 1
scipy/stats/_continuous_distns.py:9495: in _munp
    return np.float64(ufunc(K, k, df))
E   RuntimeWarning: invalid value encountered in ? (vectorized)
        K          = 1
        _a         = 0
        _b         = inf
        _single_moment = <function studentized_range_gen._munp.<locals>._single_moment at 0xd22ec658>
        cython_symbol = '_studentized_range_moment'
        df         = array([10])
        k          = array([3])
        self       = <scipy.stats._continuous_distns.studentized_range_gen object at 0xebf8eaf0>
        ufunc      = <ufunc '? (vectorized)'>
________________ TestStudentizedRange.test_moment_vectorization ________________
[gw0] linux -- Python 3.8.0 /usr/bin/python3.8
scipy/stats/tests/test_distributions.py:4636: in test_moment_vectorization
    m = stats.studentized_range._munp([1, 2], [4, 5], [10, 11])
        self       = <scipy.stats.tests.test_distributions.TestStudentizedRange object at 0xd1bb2430>
scipy/stats/_continuous_distns.py:9495: in _munp
    return np.float64(ufunc(K, k, df))
E   RuntimeWarning: invalid value encountered in ? (vectorized)
        K          = [1, 2]
        _a         = 0
        _b         = inf
        _single_moment = <function studentized_range_gen._munp.<locals>._single_moment at 0xd1da72f8>
        cython_symbol = '_studentized_range_moment'
        df         = [10, 11]
        k          = [4, 5]
        self       = <scipy.stats._continuous_distns.studentized_range_gen object at 0xebf8eaf0>
        ufunc      = <ufunc '? (vectorized)'>
- generated xml file: /scipy/build/testenv/lib/python3.8/site-packages/junit/test-results.xml -
=========================== short test summary info ============================
FAILED scipy/stats/tests/test_distributions.py::TestStudentizedRange::test_moment_against_mp[case_result1]
FAILED scipy/stats/tests/test_distributions.py::TestStudentizedRange::test_moment_vectorization
= 2 failed, 44389 passed, 2398 skipped, 918 xfailed, 11 xpassed in 948.10s (0:15:48) =
```

</details>

**Comment by swallan** [comment]
I do not recall seeing these previously.

**Comment by DominicChm** [comment]
Not sure what's causing these to suddenly fail now, but I suspect the integration is going too far causing the PDF integrand to become unstable. Were there any recent PRs related to anything in the integrate module?

**Pull request merged**
