### PR TITLE
DEP: Deprecate private namespaces in `scipy.special`

### PR DESCRIPTION
**Pull request by Smit-create**
* Reference issue: #14360 

cc @rgommers

### CODE REVIEW

**Review by rgommers — COMMENTED** [review]
Looks good, except Mypy is a bit unhappy. Functions like `roots_jacobi` are actually public and present, and checking `'roots_jacobi' in special.__all__` yields `True`. So it's not immediately clear to me what is happening there - could you look into that @Smit-create?

**Comment by rgommers** [comment]
> > Functions like `roots_jacobi` are actually public and present
> 
> Yes, exactly, tests are also running fine so imports are working fine imo, can't able to get the exact reasons for failures

The problem is that Mypy is hopelessly buggy with star imports, so just slightly tweaking imports as in this PR results in a world of pain - (details at https://github.com/python/mypy/issues/4930). The solution is to get rid of star imports completely. I'm halfway there, so let me try to finish cleaning all this up.

**Comment by rgommers** [comment]
Ugh, there was a much easier way - the `orthogonal.pyi` stub file needed renaming to `_orthogonal.pyi`. That's an easier fix, then we can keep the star imports.

The renaming of `specfun` is still useful.

**Comment by Smit-create** [comment]
Failures seems unrelated? as all the tests were passing locally(on Linux) and here Linux job tests too. 
macOS failures:

```
=========================== short test summary info ============================
FAILED scipy/stats/tests/test_distributions.py::TestBeta::test_issue_12635 - ...
FAILED scipy/stats/tests/test_distributions.py::TestBeta::test_issue_12794 - ...
FAILED scipy/stats/tests/test_distributions.py::TestBeta::test_issue_12796 - ...
```

**Comment by rgommers** [comment]
> Failures seems unrelated? as all the tests were passing locally(on Linux) and here Linux job tests too.
> macOS failures:

Indeed, I see them on another PR as well.

**Review by rgommers — APPROVED** [review]
This looks good now, thanks @Smit-create!

**Pull request merged**
