### PR TITLE
MAINT: interpolate: remove several fused type uses from `_bspl.pyx`

### PR DESCRIPTION
**Pull request by ev-br**
#### What does this implement/fix?

Slim down the `_bspl` extension. Two changes:

- move the `insert_knot` routine to python: it's basically pure numpy anyway, there's no reason to keep it in Cython
- remove a fused dtype `double_or_complex`

Locally this shaves off 150kb in a release build with no functional changes apart from a small enhancement that `BSpline.insert_knot` now handles complex-valued spline coefficients.

<details>

Several cython routines in scipy.interpolate templated on real and complex dtypes:

```
ctypedef fused double_or_complex:
    double
    double complex
```

In many cases, templated routines do not actually use complex math, and only use operations linear in data---thus each complex value is nothing but a pair of floats. We can thus simplify the cython routines to only accept float arrays, and convert complex to float on the python side with some minor numpy voodoo:

```
>>> np.arange(3, dtype=complex).view(float)
array([0., 0., 1., 0., 2., 0.]
```
</details>

#### Additional information

This started as an experiment on plumbing complex values to from python to C++ which gets annoying when wrapped via cython. As is, this PR unblocks further experiments to slim down and streamline this and other C extensions:

- some more routines from `_bspl.pyx` can be moved to C/C++ from Cython. 
- a similar removal of fused dtypes can shave off a non-trivial amount of fat from other extensions.

Both of these are best done in separate follow-up PRs.

Specific patterns of moving things from Cython to C++ require some more experimenting. For one, it's not yet clear to me what is the size/maintainability tradeoff between moving things to C++ wholesale (and interface between C++ and python manually) vs keeping the interface in Cython. There are some preliminary experiments in https://github.com/ev-br/scipy/pull/14

### CODE REVIEW

**Comment by ev-br** [comment]
`double_or_complex` fused type is also used in `_ppoly.pyx` and `interpnd.pyx`. Let's roughly estimate the total budget for the binary size reduction. With #19970, 

```
$ cd build-install/lib/python3.12/site-packages/scipy/interpolate
$ ll *so
-rwxr-xr-x 1 br br 3274208 июл 20 16:23 _bspl.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br  914192 июл 20 16:20 _dfitpack.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br  232248 июл 20 16:20 _fitpack.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 2060392 июл 20 16:23 interpnd.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 2178760 июл 20 16:23 _ppoly.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 6885472 июл 20 16:20 _rbfinterp_pythran.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 1060352 июл 20 16:20 _rgi_cython.cpython-312-x86_64-linux-gnu.so*
```

Moving to the tip of this PR (so that the fused type is gone from `_bspl.pyx`), and changing the declaration to `ctypedef double double_or_complex`:

```
-rwxr-xr-x 1 br br 2517200 июл 20 16:20 _bspl.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br  914192 июл 20 16:20 _dfitpack.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br  232248 июл 20 16:20 _fitpack.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 1729392 июл 20 16:20 interpnd.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 1302248 июл 20 16:20 _ppoly.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 6885472 июл 20 16:20 _rbfinterp_pythran.cpython-312-x86_64-linux-gnu.so*
-rwxr-xr-x 1 br br 1060352 июл 20 16:20 _rgi_cython.cpython-312-x86_64-linux-gnu.so*
```

So the  `_ppoly` size changes from 2178760 to 1302248  (minus 855kb, 40%) and `interpnd` size goes from 2060392 to 
1729392 (-323kb, 15%). Meaning we can shave off up to 1.9Mb in total. There is maybe some more room in `_rgi_cython` and an additional `int32/int64` fused type in `_bspl.pyx::make_design_matrix`, but this is unlikely to change the calculus significantly.

**Comment by rgommers** [comment]
Interesting, thanks for looking into it @ev-br. Minor comment: when looking at file size reductions, you normally want to look at a release build for realistic results (`dev.py build --release`). Sizes in release builds are (on arm64; x86-64 will be larger):
```
% ls -lhS build-install/lib/python3.10/site-packages/scipy/interpolate/
-rwxr-xr-x   1 rgommers  staff   442K Jul 20 16:37 _bspl.cpython-310-darwin.so
-rwxr-xr-x   1 rgommers  staff   340K Jul 20 16:37 _ppoly.cpython-310-darwin.so
-rwxr-xr-x   1 rgommers  staff   328K Jul 20 16:37 interpnd.cpython-310-darwin.so
-rwxr-xr-x   1 rgommers  staff   298K Jul 20 16:37 _rbfinterp_pythran.cpython-310-darwin.so
-rwxr-xr-x   1 rgommers  staff   272K Jul 20 16:37 _dfitpack.cpython-310-darwin.so
-rwxr-xr-x   1 rgommers  staff   224K Jul 20 16:37 _rgi_cython.cpython-310-darwin.so
-rwxr-xr-x   1 rgommers  staff   102K Jul 20 16:37 _fitpack.cpython-310-darwin.so
```

**Comment by ev-br** [comment]
Thanks, I did not realize the difference between debugoptimized and release builds is this large!

Under `python dev.py build --release` the numbers are

```
-rwxr-xr-x 1 br br 612K июл 20 19:07 _bspl.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 425K июл 20 18:59 _ppoly.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 406K июл 20 18:59 interpnd.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 339K июл 20 18:59 _dfitpack.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 259K июл 20 18:59 _rgi_cython.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 225K июл 20 18:59 _rbfinterp_pythran.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br  87K июл 20 18:59 _fitpack.cpython-312-x86_64-linux-gnu.so
```
vs

```
-rwxr-xr-x 1 br br 472K июл 20 22:21 _bspl.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 347K июл 20 22:21 interpnd.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 339K июл 20 22:21 _dfitpack.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 263K июл 20 22:21 _ppoly.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 225K июл 20 22:21 _rbfinterp_pythran.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br 219K июл 20 22:21 _rgi_cython.cpython-312-x86_64-linux-gnu.so
-rwxr-xr-x 1 br br  87K июл 20 22:21 _fitpack.cpython-312-x86_64-linux-gnu.so
```

so all in all removing fused types can give up to 400k in binary size, which is about 17% of the whole scipy.interpolate. Wow.

**Comment by ev-br** [comment]
Rebased on main to remove the dependency on #19970. This PR is now mergeable and is ready from my side. To summarize (I also edited the OP description): removing fused types and moving a numpy-heavy routine from Cython to Python shaves off 150kb from the release binary size (546k -> 393k). Further tweaks are best done in follow-up PRs, so this one is ready from my side.

**Comment by ev-br** [comment]
I'd rather have this land sooner than later, as it's now blocking further tweaks which are in the pipeline. If someone feels like reviewing this, it'd be great. Otherwise I plan to push the green button next week.

**Review by j-bowhay — APPROVED** [review]
Thanks @ev-br this looks like a nice improvement on a number of fronts

**Pull request merged**
