### PR TITLE
ENH: Make next_fast_len public and faster

### PR DESCRIPTION
**Pull request by endolith**
Continuation of https://github.com/scipy/scipy/pull/6124

Change name to public `next_fast_len`

Speed up for small n since FFT itself can take a similar amount of time:

figure_2

Expanded docstring with example

### CODE REVIEW

**Comment by endolith** [comment]
tag @hgomersall again because name will affect pyfftw

**Comment by Eric89GXL** [comment]
Maybe we should write this function in Cython so it's faster, looks like it would be pretty simple. SciPy requires 2.7+ now, too, so the try/except can be removed.

**Comment by endolith** [comment]
Cython is fine but I don't know how to do it.  It would use C ints instead of Python long ints?  Does anyone do FFTs that are longer than 2147483647 points?

**Comment by Eric89GXL** [comment]
You can use 64 bit integers in Cython. It shouldn't be too bad to do it. Do
you prefer a PR into your branch or should I make a follow up PR? And can
you share the code to make the relative timing plot?

**Comment by endolith** [comment]
I don't have a preference about PRs.

posted code here https://gist.github.com/endolith/2d35f3ea8f64cd2d02d1b49b43f25a21

**Comment by Eric89GXL** [comment]
Let's get this one in first. The Cython can come later if someone finds time. I have a WIP version if you're ever interested.

I assume this is ready to go from your end? Should we wait to hear form @hgomersall?

**Comment by hgomersall** [comment]
I'm happy :) When is a release on this due?

**Comment by Eric89GXL** [comment]
It looks like [0.18 is due in June] (https://github.com/scipy/scipy/milestones) and this could easily make it in there.

**Comment by Eric89GXL** [comment]
@hgomersall are there other things that you want/need to facilitate PyFFTW integration?

**Comment by hgomersall** [comment]
£10k :) No, I think for the time being that is all that is needed - at least, it haven't come across anything else.

That said, there is a consideration as to whether some use on the scipy end could be made of lower level pyFFTW objects. The interface code is rather slow in comparison, so in some cases the maximum benefit occurs when operating directly on FFTW objects - the overhead is generally in required copies to obey the `scipy.fftpack` contracts, and these aren't always necessary. I don't know how this can be realised however...

**Comment by endolith** [comment]
Yes I have no more changes.  You're ok with the length of the `hams` list?  Will take up a kB of memory whenever this is imported?

**Comment by Eric89GXL** [comment]
> Will take up a kB of memory whenever this is imported?

I hadn't actually thought about this, but now that you mention it, how about nesting `hams`? It takes 1uS on my system to create it, and then it only sits in memory when necessary.

> That said, there is a consideration as to whether some use on the scipy end could be made of lower level pyFFTW objects. The interface code is rather slow in comparison, so in some cases the maximum benefit occurs when operating directly on FFTW objects - the overhead is generally in required copies to obey the scipy.fftpack contracts, and these aren't always necessary. I don't know how this can be realised however...

Hmm... if you're interested in actually trying this, let's break it out into a new topic. I'd be interested to know what common use cases you have in mind that would suffer from the fftpack contracts. It might be worth seeing if there is some way to alleviate those burdens given the potential speed increases people can see with FFTW.

**Comment by hgomersall** [comment]
@Eric89GXL I started thinking about this, but I can't see what is needed without some pretty deep changes to the basic algorithmic implementation (along with caching infrastructure and so on). It would be quite a bit of work I think.

**Comment by endolith** [comment]
> how about nesting hams? 

You mean inside the function?  Strangely, that doesn't seem to make the function any slower, so I'll do it.

**Comment by Eric89GXL** [comment]
Yeah -- it takes 1uS to construct the tuple on my system so it should be negligible.

**Comment by endolith** [comment]
I mean calling the function `next_fast_len(1021)` takes 1 μs for me whether it's inside the function or not, so creating the tuple doesn't take any time?

**Comment by Eric89GXL** [comment]
Yeah the 1uS I'm quoting was from doing `timeit` on the tuple creation alone.

**Comment by Eric89GXL** [comment]
(plus or minus say a factor of two, not exactly 1uS)

**Comment by endolith** [comment]
Anything else to do on this?

**Comment by Eric89GXL** [comment]
No, thanks @endolith

**Pull request merged**
