### PR TITLE
MAINT: update the author name mapping

### PR DESCRIPTION
**Pull request by ev-br**
@bdvd @gfyoung @jona-sassenhagen @kleskjr @mseri @MYheavyGo @solarjoe @yanxun827 @ionelberdin @emptymalei
Do you guys want to be credited in the release notes? The result will look similar to https://github.com/scipy/scipy/blob/master/doc/release/0.17.0-notes.rst#authors

If you do, would you mind letting me know your name, as a comment to this PR? (I might have some ideas in some cases, but in the face of ambiguity I refuse the temptation to guess)

<s>There are a few more mysteries in the output of `$ ./authors.py v0.17.0..HEAD` :</s>
There's only one left:
- GitHub +

<s> If you recognize a name you might have been using in a git record, or you can otherwise link one of these to a github handle, please comment. </s>

### CODE REVIEW

**Comment by gfyoung** [comment]
@ev-br: G Young is fine for me.

**Comment by mseri** [comment]
Oh, that would be nice. Thanks!! My name is Marcello Seri

**Comment by emptymalei** [comment]
Name is Lei Ma. Appreciate it.

```
emptymalei -> Lei Ma
```

**Comment by ionelberdin** [comment]
Thanks a million! My name's Ion Elberdin. Cheers!

**Comment by rgommers** [comment]
LGTM. I don't see where ``GitHub`` is coming from, but we can simply delete it from the list when copying that into the release notes.

**Comment by jona-sassenhagen** [comment]
My handle is my actual name so you can keep it at that. Thanks!

**Comment by bdvd** [comment]
My name is: Dávid Bodnár. Thanks.

**Comment by ev-br** [comment]
Thanks to all of you, I've now merged the mapping.
For those who did not reply: we'll be using your GH handles for now. Feel free to reply to this issue  though, release notes are in the works during the rc phase.

**Pull request merged**
