### PR TITLE
DEP: Deprecate private namespaces in ``scipy.sparse``

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Reference issue

gh-14360

### CODE REVIEW

**Comment by thisisamardeep** [comment]
@czgdp1807  Can you pls share what setup in vscode do you use to debug scipy.Do you use some other ide.?
I am having tough time trying to debug scipy.If you upload on a sample github repo it will be very helpful

**Comment by czgdp1807** [comment]
@thisisamardeep It usually depends on the type of the bug. My debugging methods are IDE/Editor agnostic. In general, adding debug print statements to code, or using lldb/gdb for C/C++ after analysing the stacktrace works. For verifying whether a new feature is producing wrong outputs you can use binary search to pin point the part of code which is generating wrong data and then fix it. I hope that helps.

**Review by perimosocordiae — CHANGES_REQUESTED** [review]
The shim inserted for sputils seems to be causing some deprecation warnings to sneak through. Here's a snippet from the failing tests:

```
scipy/sparse/sputils.py:48: in __getattr__
    warnings.warn(f"Please use `{name}` from the `scipy.sparse` namespace, "
E   DeprecationWarning: Please use `matrix` from the `scipy.sparse` namespace, the `scipy.sparse.sputils` namespace is deprecated.
        name       = 'matrix'
=========================== short test summary info ============================
ERROR scipy/cluster/tests/test_vq.py - DeprecationWarning: Please use `matrix...
ERROR scipy/interpolate/tests/test_interpolate.py - DeprecationWarning: Pleas...
ERROR scipy/linalg/tests/test_decomp.py - DeprecationWarning: Please use `mat...
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
```

**Comment by czgdp1807** [comment]
@rgommers @perimosocordiae The CI passes now. Let me know if anything else is to be done.

**Review by rgommers — APPROVED** [review]
Looks good now, thanks @czgdp1807!

**Pull request merged**
