### PR TITLE
ENH: signal: remezord implementation

### PR DESCRIPTION
**Pull request by nils-werner**
Rebased remezord implementation as mentioned in #1002

### CODE REVIEW

**Comment by larsoner** [comment]
@nils-werner are you interested in coming back to this? It looks like you force pushed an update four years ago that nobody saw (GitHub does not notify for force push updates). If the comments above are addressed and you're still interested in working on this we can review. If not perhaps we should close?

**Comment by nils-werner** [comment]
Yes, I would be interested to give this another go.

**Comment by luxedo** [comment]
Any updates on this? I can give it a try since it looks like mostly bureaucracy.

- [ ] code needs unit tests.
- [ ] all functions except remezord need to start with an underscore.
- [ ] the docstrings for remlplen_* repeat the same text 3 times. The 2nd and 3rd docstring can refer to the first one. The references to papers should all be moved to the remezord docstring.
- [ ] the code needs some PEP8 cleanup (spaces around operators etc.)
- [ ] the Hz parameter is missing from the docstring.
- [ ] docstring format: See should be See Also, typo in Paramters, remove blank lines right below section headings.
- [ ] An example in the docstring would be very useful.
- [ ] remezord should be added to the function listing in signal/__init__.py.

**Comment by rgommers** [comment]
I think that would indeed be nice, thanks @luxedo.

**Comment by j-bowhay** [comment]
continued in https://github.com/scipy/scipy/pull/20983

**Pull request closed without merging**
