### PR TITLE
BUG: Do not catch and silence KeyboardInterrupt

### PR DESCRIPTION
**Pull request by eric-wieser**
Bare `except`s are only correct when trying to capture and forward exceptions - in all other cases, `except Exception` should be used to avoid catching `KeyboardInterrupt`

This only touches the code that is user-facing, not any of the tooling or tests

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Looks sensible at first glance. I restarted the stalled linux build. Mac OS failure unrelated.

I think I've also seen this done as:

```python
    except KeyboardInterrupt:
        raise
    except:
```

**Comment by larsoner** [comment]
```
 except KeyboardInterrupt:
        raise
    except:
```
IIRC this will also catch `SystemExit`, which is most often probably not what is desired.

**Comment by larsoner** [comment]
Now that this is in, I think there is some style checker we can reconfigure to ensure we don't get new ones. I'll look into it unless someone else beats me to it. Should be a simple change.

**Comment by eric-wieser** [comment]
@larsoner: Maybe, although I left all the ones alone in the tests

**Pull request merged**
