### PR TITLE
MAINT: 1.6.0 rc2 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
* update the SciPy `1.6.0` (rc2) release notes following
    backports to the maintenance branch

 * I've added Matti Picus to the author list because
    they made essential contributions to the wheels repo
    that were not picked up by our automated scripts

 * backports included for rc2 (so far):
    gh-13226
    gh-13249
    gh-13253
    gh-13260
    gh-13269

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Thanks Tyler. All of those LGTM and all green, so I'll merge.

**Comment by rgommers** [comment]
I removed the backport label from these. There's still 13 PRs with a backport label left, but it looks like those are all stale labels and could be cleared, right?

**Comment by tylerjereddy** [comment]
yeah, I should double check and clear those labels

**Comment by tylerjereddy** [comment]
Ok, there no longer any merged PRs with backport labels (I checked them all and cleared them).

`1.6.0rc2` wheels are building now so perhaps I'll get that out this evening, depending on the wheel build queues.

**Pull request merged**
