### PR TITLE
DOC: stats.{circmean, circvar, circstd}: improve accuracy/clarity

### PR DESCRIPTION
**Pull request by fancidev**
#### Reference issue
Toward gh-20240.

#### What does this implement/fix?
Improves the accuracy and/or clarity of the doc of the `circmean`, `circvar`, and `circstd` functions.

### CODE REVIEW

**Comment by j-bowhay** [comment]
Friendly reminder that for documentation-only PRs we can save some compute by adding `[docs only]` to the commit message
https://docs.scipy.org/doc/scipy/dev/contributor/continuous_integration.html#skipping

**Comment by fancidev** [comment]
@dschmitz89 If you could take a look when you have time it would be great!

**Comment by dschmitz89** [comment]
Thanks for the PR @fancidev . This looks good to me. Could you add a reference, for example [Wikipedia](https://en.wikipedia.org/wiki/Circular_mean)? Then I would merge.

**Comment by fancidev** [comment]
> Thanks for the PR @fancidev . This looks good to me. Could you add a reference, for example [Wikipedia](https://en.wikipedia.org/wiki/Circular_mean)? Then I would merge.

Thanks for taking a look @dschmitz89 ! Let me locate the definition of those functions in Mardia and Jupp (1999) and add references accordingly.

**Comment by fancidev** [comment]
Reference added! @dschmitz89

**Comment by dschmitz89** [comment]
Thanks @fancidev .

**Comment by fancidev** [comment]
Thank you @dschmitz89 !

**Pull request merged**
