### PR TITLE
MAINT: add benchmark and improve docstring for signal.lfilter

### PR DESCRIPTION
**Pull request by rgommers**
```
[100.00%] ··· Running signal_filtering.Lfilter.time_lfilter                                          ok
[100.00%] ···· 
               =========== ========= ========= ==========
               --                     numtaps            
               ----------- ------------------------------
                n_samples      9         23        51    
               =========== ========= ========= ==========
                  1000.0    78.28μs   90.33μs   114.57μs 
                 50000.0     1.66ms    2.42ms    3.46ms  
                1000000.0   37.49ms   51.61ms   73.77ms  
               =========== ========= ========= ==========
```

### CODE REVIEW

**Comment by rgommers** [comment]
@ewmoore this is the benchmark for your ``lfilter`` speed improvements from gh-4628, do you want to have a look at this?

**Comment by ewmoore** [comment]
Since `lfilter` knows about FIR vs. IIR, we should have a test path for both.  This can be as simple as using `[1.0, 0.0]` for the `b` array.

**Comment by ewmoore** [comment]
I'm inclined to take this.  Enhancements to the benchmarks can come in another PR.

**Comment by ewmoore** [comment]
Okay let's take this.

**Comment by rgommers** [comment]
@ewmoore sorry about not updating this one, I kind of overlooked it.

**Comment by argriffing** [comment]
This PR was marked with [ci skip] and is causing unrelated PRs to fail because of whitespace style issues.

**Comment by rgommers** [comment]
hmm, sorry about that. guess we should stop using ``skip ci`` unless we're really not touching anything that goes through our CI machinery (which is less and less these days).

**Comment by argriffing** [comment]
I'd be OK with removing some CI style requirements. It's easy to argue on the side of keeping these assertions, because of course you want the code to conform to good style.

**Comment by ewmoore** [comment]
Sorry about making work for others with this.

**Comment by argriffing** [comment]
Just for fun, here's a PR removing the whitespace check that caused the CI to fail https://github.com/scipy/scipy/pull/5730. The idea isn't to disagree with the idea of continuous integration or with the PEP8 guidelines but rather to deliberately resist the ratcheting effects that can afflict successful mature open projects and to facilitate new contributions.

**Pull request merged**
