### PR TITLE
CI: update OpenBLAS to 0.3.18 in Azure jobs

### LINKED ISSUE #15308: BUG: OpenBLAS 0.3.18 support
### Describe your issue.

Observed in gh-15249, doesn't appear to be due to changes in PROPACK (I could be convinced otherwise though).  Might be a new release of OpenBLAS that we're not accounting for.

Logs: https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=15649&view=logs&j=e3555eda-5afc-5d78-d2e9-cf9756f98375&t=220e105d-2d02-5073-9f3b-414490a3ddd5

### Reproducing Code Example

```python
Linux_Python_38_32bit_full
Run 32-bit Ubuntu Docker Build / Tests
```

### Error message

```shell
OpenBLAS get_config returned b'OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Nehalem MAX_THREADS=64'
b'OpenBLAS 0.3.17'
Traceback (most recent call last):
  File "tools/openblas_support.py", line 335, in <module>
    test_version(args.check_version)
  File "tools/openblas_support.py", line 312, in test_version
    assert check_str in res, f'{expected_version} not found in {res}'
AssertionError: 0.3.17 not found in b'OpenBLAS 0.3.18 DYNAMIC_ARCH NO_AFFINITY Nehalem MAX_THREADS=64'
```
```


### SciPy/NumPy/Python version information

scipy-1.9.0.dev0/numpy-1.18.5-cp38-cp38-manylinux1_i686.whl/Python38

### PR DESCRIPTION
**Pull request by mckib2**
#### Reference issue

Closes gh-15308

#### What does this implement/fix?

- bumps OpenBLAS in CI from 0.3.17 to 0.3.18

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM, thanks @mckib2 

CI is happy and picks up the new version:
```
target path: C:\agents\2.195.2\openblaslib\openblas.a
Downloading 30740780 from https://anaconda.org/multibuild-wheels-staging/openblas-libs/v0.3.18/download/openblas-v0.3.18-win_amd64-gcc_8_1_0.zip
Saving to file
target path: C:\agents\2.195.2\openblaslib\openblas64_.a
Downloading 30305805 from https://anaconda.org/multibuild-wheels-staging/openblas-libs/v0.3.18/download/openblas64_-v0.3.18-win_amd64-gcc_8_1_0.zip
Saving to file

Finishing: Download / Install OpenBLAS
```

New OpenBLAS versions have been useful recently in resolving problems. My impression is: more fixes, fewer regressions (thanks @martin-frbg!).

@mckib2 any reason why you didn't go straight to `0.3.19`? I'll merge this since it fixes something, but I do see `0.3.19` builds at https://anaconda.org/multibuild-wheels-staging/openblas-libs/files that we should probably upgrade to.

**Comment by mckib2** [comment]
> @mckib2 any reason why you didn't go straight to 0.3.19? I'll merge this since it fixes something, but I do see 0.3.19 builds at https://anaconda.org/multibuild-wheels-staging/openblas-libs/files that we should probably upgrade to.

I only chose 0.3.18 because that's what the assertion error in the issue complained about. I don't see why we couldn't move to the latest greatest

**Comment by tylerjereddy** [comment]
Note that this shouldn't have changed the version of OpenBLAS that gets downloaded, only the string value that gets used for the check in `openblas_support.py --check_version`, which is only done on Linux at the moment for other messy reasons (runtime checking of the OpenBLAS version was problematic on Windows).

So, the CI should have been failing for 32-bit Linux before this PR for that reason, but the version of OpenBLAS actually used on Linux and Windows should not have changed in this PR.

**Comment by tylerjereddy** [comment]
I'm only confused because the code review above cites Windows paths like ` C:\agents\2.195.2\openblaslib\openblas.a`, which isn't really related.

**Comment by tylerjereddy** [comment]
By the way, if you do bump to `0.3.19` to fix PROPACK stuff, we'll need to backport the changes to `openblas_support.py` so it gets leveraged in wheels repo.

**Pull request merged**
