### PR TITLE
BENCH: Added 'trust-constr' to minimize benchmarks

### PR DESCRIPTION
**Pull request by mdhaber**
#### What does this implement/fix?
`'trust-constr'` was missing from the lists of `minimize` methods benchmarked in `/benchmarks/benchmarks/optimize.py`; this adds it.

#### Additional information
Haven't tested locally yet; should do that before merging.

### CODE REVIEW

**Comment by andyfaff** [comment]
The benchmarks don't get run on any of the CI's, as far as I know. If you run the optimize benchmarks on your own computer and everything runs, and you see the trust-constr in the output, then I'm happy for this to be merged.

**Review by andyfaff — APPROVED** [review]

**Comment by mdhaber** [comment]
I have run benchmarks on this branch and `trust-constr` results are reported in the table.

**Comment by tylerjereddy** [comment]
> The benchmarks don't get run on any of the CI's

There is an `asv check` run in Travis, to check for basic problems.

**Comment by antonior92** [comment]
Sorry for the late response. Anyway, thank you very much for fixing this @mdhaber.  Happy to see this merged.

**Pull request merged**
