### PR TITLE
MAINT: Check that scipy.linalg.lapack functions are documented

### PR DESCRIPTION
**Pull request by larsoner**
Would have caught an error I only saw in #10741 by manually checking the docs, and caught an existing doc error introduced in #10537.

### CODE REVIEW

**Comment by ev-br** [comment]
I wonder why refguide_check does flag it. Maybe need to opt in scipy.linalg.lapack and .blas?

**Comment by larsoner** [comment]
> I wonder why refguide_check does not flag it. 

Probably because `scipy.linalg.lapack.__all__ == ['get_lapack_funcs']`. Maybe this, too, is a bug.

**Comment by ev-br** [comment]
In fact, `linalg.blas` and `.lapack` are specifically excluded: https://github.com/scipy/scipy/blob/master/tools/refguide_check.py#L120

Since this PR adds a test for them to be present, maybe avoid duplication and just add these names to `__all__` and stop excluding them instead?

**Comment by larsoner** [comment]
Yeah that sounds like a better approach

**Comment by ev-br** [comment]
I briefly looked into this (https://github.com/scipy/scipy/compare/master...ev-br:refguide-lapack?expand=1) and I take my suggestion back.

Making refguide-check pass would require that all the `linalg.lapack` names are listed in the `linalg` docstring. And that is not desired, `scipy.linalg` docstring should keep listing the high-level stuff instead of being cluttered with low-level lapack names.

So, +1 for this PR from me.

**Comment by ilayn** [comment]
Indeed I was hoping to keep track of these additions (I also noticed lots of missing entries and added in #10075) but failed in the last PRs. Also +1 from me. As a bonus I have some stuff to do from that PR which I will add now.

**Comment by larsoner** [comment]
Sounds good to me, feel free to merge in that case

**Comment by ilayn** [comment]
Merged, thanks @larsoner !

**Pull request merged**
