### PR TITLE
fix the regression in circmean

### LINKED ISSUE #6420: circmean() changed behaviour from 0.17 to 0.18
[Commit 6f799a807bde2b4391857 ](https://github.com/scipy/scipy/commit/6f799a807bde2b4391857136fd3cbf87321710f1) appears to have changed the behaviour of `scipy.stats.circmean()`.
Yet I can't find this documented anywhere.
Is this correct?

For example, using the following code
```python
import numpy as np
from scipy.stats import circmean
print(circmean(np.arange(-2, 0, 0.1), np.pi, -np.pi),
      circmean(np.arange(0, 2, 0.1), np.pi, -np.pi))
```

produces different results before and after this commit:

```
# master
# -1.05 -5.33318530718

# git checkout 6f799a807bde2b4391857
# -1.05 -5.33318530718

# git checkout 4f9be64594970103e245cf5
# -1.05 0.95
```

### PR DESCRIPTION
**Pull request by ev-br**
Rebase of gh-6424.

closes gh-6424, closes gh-6420

### CODE REVIEW

**Comment by rgommers** [comment]
Merged, thanks @ev-br.

**Comment by rgommers** [comment]
We'll overlook the variable names ``M1``, ``M2`` for once.....

**Comment by ev-br** [comment]
backported in gh-6557, commits 75915eb9b10e2c3c2f2e7f8d56170c0cd336740d and 9996ae69c2b35d7933c11520e9a482ae19ef1f62

**Comment by ev-br** [comment]
> We'll overlook the variable names M1, M2 for once.....

yeah :-(. Will send a PR

**Pull request merged**
