### PR TITLE
ENH:sparse.linalg: Update vendored ARPACK version to 3.9.1

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Closes #10375
Closes #14786 

#### What does this implement/fix?
Updates the vendored ARPACK from https://github.com/opencollab/arpack-ng version to 3.9.1 while we are rewriting ARPACK ourselves. I don't know what it fixes or fixes anything at all but better to have an up-to-date version to get rid of the obvious ones. Possibly closes other issues and will be added if this PR goes through.

#### Additional information
Pauli has a comment about OSX ABI mismatch requirement with a Perl script in `README.scipy` but not sure if it is still needed as we worked on those wrappers recently.

### CODE REVIEW

**Comment by ilayn** [comment]
Well that perl script is still needed apparently.

**Comment by ilayn** [comment]
The "Starting vector is 0" is now a known issue in ARPACK upstream. See 2nd item in their FAQ https://github.com/opencollab/arpack-ng?tab=readme-ov-file#faq

We can skip the test or provide nonzero initial values to the vector. Either way, it is not an issue for us.

**Comment by rgommers** [comment]
Thanks @ilayn!

> Pauli has a comment about OSX ABI mismatch requirement with a Perl script in `README.scipy` but not sure if it is still needed as we worked on those wrappers recently.

We still need our wrappers for these functions in general, however it turns out that arpack-ng only used `cdotc` and `zdotc`, and it replaced its usage of those by its own wrappers `ccdotc` and `zzdotc` in 3.9.0 (see https://github.com/opencollab/arpack-ng/pull/346), which is great. Hence, trying to apply our changes again is a no-op. It'd be good to add a comment to that effect to `README.scipy`.

Aside from that and resolving the "starting vector is 0" failures, this looks good to go to me.

**Comment by ilayn** [comment]
Apparently, this `second.f` is indeed not working so probably that's why we did not use it in the first place. In `ifx` it is called a portability function https://www.intel.com/content/www/us/en/docs/fortran-compiler/developer-guide-reference/2024-2/etime.html

We have bigger problems with ARPACK than measuring time anyways so I don't think it's worth trying to detect compilers and what not. I'll remove the `second.f`.

**Comment by rgommers** [comment]
That's why https://github.com/scipy/scipy/pull/10375/commits/7f09715c87f409b919862a0a116ed2aa051e6cd7#diff-28602384c24eac593be817ec46e265538f8701660066889a631a7468f594ccc0 removed the two `ETIME` usages.

**Comment by ilayn** [comment]
Ah, OK. Thanks for that, don't know how I missed it.

**Comment by ilayn** [comment]
I'll merge this one since I've gone through the additions since v3.3.0; other than the forcing initial vector to be in the image of OP there is nothing functional added. Most of the changes are the changes to indices for printing. Hence probably it will not be solving too many issues we have.

**Pull request merged**
