### PR TITLE
ENH: Handling of NotImplemented part in binary operators in sparse.compressed.py

### PR DESCRIPTION
**Pull request by ashwinpathak20**
This is in reference to issue #4819.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
This change seems to be mostly duplicate effort: we're already testing the type of `other` in the `_inequality` method, and currently raise a `ValueError` if it's not scalar, dense, or sparse. If I understand the goal correctly, we should just change that exception to instead `return NotImplemented`.

**Comment by perimosocordiae** [comment]
TravisCI failed because of the extra blank line in your diff.

We should have a test for the intended behavior enabled by this PR. For example, a user should be able to write:

```python
class Something(object):
    def __gt__(self, other):
        return 'pass'

a = scipy.sparse.random(5, 5)
b = Something()
assertEqual(a <= b, 'pass)
```

**Comment by ashwinpathak20** [comment]
Where should I include these tests? @perimosocordiae

**Comment by perimosocordiae** [comment]
They should be added to `scipy/sparse/tests/test_base.py`, as they apply to all sparse formats.

**Comment by ashwinpathak20** [comment]
@perimosocordiae I am new to writing tests , I was not able to understand what exactly should be written in order to test the pr and how to execute these tests... Can you help me?

**Comment by ilayn** [comment]
I'll close this for housekeeping reasons but feel free to reopen it after cleaning the git rebases.

**Pull request closed without merging**
