### PR TITLE
DOC: document return_all arguments

### LINKED ISSUE #11638: better documentation for 'return_all' option in minimize(Nelder Mead)
My issue is about ... dummy 'return_all' option in scipy.optimize.minimize(method=’Nelder-Mead’)
Basically, the **minimize** function returns an object of class *OptimizeResult*. This has no attribute which would enable it to return the function values at each iteration. This in contrast with the corresponding `retall` parameter in  scipy.optimize.fmin which **minimize** is proposed to replace.
#### Reproducing code example:

```
from scipy.optimize import minimize, rosen, rosen_der
from numpy import array
x0 = array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='Nelder-Mead', 
               options={'return_all': False},
               tol=1e-6)
dir(res)
```
#### output message:
```
['final_simplex', 'fun', 'message', 'nfev', 'nit', 'status', 'success', 'x']

```
while 
```
res = minimize(rosen, x0, method='Nelder-Mead', 
               options={'return_all': True},
               tol=1e-6)
dir(res)
```
#### output message:
```
['allvecs',
 'final_simplex',
 'fun',
 'message',
 'nfev',
 'nit',
 'status',
 'success',
 'x']
```
There seems to be no documentation on allvecs, other special attributes anywhere.
At least not on [OptimizeResult docs](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.OptimizeResult.html)

#### Scipy/Numpy/Python version information:
Scipy 1.4.1
Numpy 1.18.1
Python  sys.version_info(major=3, minor=6, micro=10, releaselevel='final', serial=0)

### PR DESCRIPTION
**Pull request by andyfaff**
Documents return_all for several minimize methods. 

Closes #11638

### CODE REVIEW

**Comment by andyfaff** [comment]
closes #11638

**Comment by ilayn** [comment]
The "closes, fixes" things apparently need to be in the starting box for some reason

**Comment by andyfaff** [comment]
> The "closes, fixes" things apparently need to be in the starting box for some reason

one lives and learns.

**Comment by TejasAvinashShetty** [comment]
We may need to change the documentation of OptimizeResult to include the explanations of what would be sent as `all_vecs` (type of sequence, dimensions, etc)

**Comment by andyfaff** [comment]
@TejasAvinashShetty `OptimizeResult.allvecs` will be a list of numpy arrays, each of which represents the solution at successive iterations.

**Pull request merged**
