### PR TITLE
PERF: Avoid np.zeros when custom initialization is needed anyway

### PR DESCRIPTION
**Pull request by alexhenrie**
Requesting an uninitialized array from NumPy (instead of requesting that NumPy initialize the array to zero) saves a little time if the array has to be initialized to other values anyway.

To facilitate code review, in this pull request I have only changed the calls to np.zeros that are clearly safe to replace.

### CODE REVIEW

**Comment by rgommers** [comment]
TravisCI status reporting seems to have some issues today. The only failure is in ARPACK which isn't touched in this PR.

**Review by peterbell10 — APPROVED** [review]
I took a look through the context for each, and can't see anywhere that would be left uninitialized.

**Comment by rgommers** [comment]
Looks like a good idea to me, so in it goes. Thanks @alexhenrie, and thanks @peterbell10 for the review.

**Comment by alexhenrie** [comment]
Thank you!

**Pull request merged**
