### PR TITLE
DEP: remove tol & max_intervals from NumericalInverseHermite

### LINKED ISSUE #15749: DEP: remove tol from `NumericalInverseHermite`
Deprecated in https://github.com/scipy/scipy/pull/14703, warning does not [mention](https://github.com/scipy/scipy/blob/v1.8.0/scipy/stats/_unuran/unuran_wrapper.pyx.templ#L1717-L1719) a timeframe. Maybe the warning should be sharpened? Tentatively adding to 1.10 milestone.

CC @tirthasheshpatel

### PR DESCRIPTION
**Pull request by j-bowhay**
#### Reference issue

Closes #15749
#### What does this implement/fix?

Executes deprecation of `tol` and `max_intervals` from `NumericalInverseHermite`. Also removes deprecated way of importing 
`NumericalInverseHermite`.

### CODE REVIEW

**Review by tupui — APPROVED** [review]
LGTM, thank you @j-bowhay. I will let @tirthasheshpatel have a look before.

**Review by tirthasheshpatel — APPROVED** [review]
Looks good, thanks @j-bowhay! `NumPy main 3.11-dev` job is failing (seems new). @tupui Is it a transient issue? I have rerun, let's see if it passes.

(FYI about the deprecation @chrisb83)

**Comment by tupui** [comment]
Thanks @tirthasheshpatel. Yes this is new but not linked to this PR. And it was passing on another PR. I did not investigate but seems gone by itself.

**Comment by tupui** [comment]
ok I was under the impression you wanted to wait a bit for feedbacks from Christoph 😅

**Pull request merged**
