### PR TITLE
DEP: deprecate args usage in xdist

### PR DESCRIPTION
**Pull request by apbard**
- usage of positional args is now deprecated
- added kwargs to support custom metrics
- simplified cdist/pdist code
- updated doc

2nd part of #6974, already rebased on #7628

### CODE REVIEW

**Comment by apbard** [comment]
@rgommers, @perimosocordiae, @jaimefrio Rebased this PR on master.

**Comment by rgommers** [comment]
The current ``pdist``/``cdist`` signatures are not pretty either, with three parameters that are specific to one metric (`w`` will be used by all metrics soon). So while I think this PR doesn't improve things as is, it doesn't make it much worse either.

@perimosocordiae, @jaimefrio thoughts on this now?

@apbard your one argument for ``partial`` not being sufficient was about adding string-based metrics as standard metrics (see https://github.com/scipy/scipy/pull/6974#issuecomment-316040086). Do you have concrete plans to do that?

**Review by perimosocordiae — APPROVED** [review]
I'm +1 to merge this for 1.0, pending test and maybe benchmark results.

**Comment by apbard** [comment]
> The current pdist/cdist signatures are not pretty either, with three parameters that are specific to one metric

Also, order of arguments is different: pdist-> ['p', '**w**', 'V', 'VI']  | cdist -> ['p', 'V', 'VI', '**w**']

> Do you have concrete plans to do that?

It it something I would like to do (or happy to review if someone else volunteer), but it is not among my top priorities. So currently I do not have a real schedule/"deadline" for this.

**Comment by rgommers** [comment]
> I'm +1 to merge this for 1.0, pending test and maybe benchmark results.

Tests all green, and I've run the ``spatial.Cdist`` benchmarks and that all looks good. For size 10 this PR gives a consistent marginal slowdown of ~1 us or so, for larger arrays results look the same.

Okay, going to hit the green button then. Thanks @apbard @perimosocordiae

**Pull request merged**
