### PR TITLE
MAINT: linalg.interpolative: normalize rng argument (SPEC7)

### PR DESCRIPTION
**Pull request by j-bowhay**
Many of the functions in `linalg.interpolative` accept a generator via a `rng` argument. This pr normalizes this argument with `np.random.default_rng` as per SPEC7.

### CODE REVIEW

**Comment by mdhaber** [comment]
Wow, so all of the public functions had the `rng` argument already, and they didn't accept `RandomState`s, etc.
Does this change any behavior (maybe in some cases allowing `rng` to be an `int`?) or just refactor to normalize in the public functions (rather than in every private function)?

**Comment by j-bowhay** [comment]
> Wow, so all of the public functions had the `rng` argument already, and they didn't accept `RandomState`s, etc.

Yes according to the documentation 

> Does this change any behavior (maybe in some cases allowing `rng` to be an `int`?) or just refactor to normalize in the public functions (rather than in every private function)?

Previously the `rng` argument was not passed through `np.random.default_rng` so this pr makes two changes to the behaviour: (1) as you mention ints can now be passed and (2) there is now some form input validation as previously the `rng` was just used directly. The only case which was handled explicitly was `rng=None` in which case the private function would set `rng = no.random.default_rng()`.

**Comment by rkern** [comment]
I concur. This seems like a straightforward (welcome) expansion of the existing behavior and not a breaking change.

**Review by mdhaber — APPROVED** [review]
Looks good but I just want to check that the private functions are always called with keyword args (since the argument order changed).

**Comment by j-bowhay** [comment]
> Looks good but I just want to check that the private functions are always called with keyword args (since the argument order changed).

I could make the argument kwarg only and this would instantly root out any issues?

**Comment by mdhaber** [comment]
> I could make the argument in the private function kwarg only and this would instantly root out any issues?

Sure that sounds great, if you're willing. Or if there's not a great place to put the `*`, maybe just put it right before `rng` and test locally. It doesn't even need to be committed as long as it's checked.

**Comment by ilayn** [comment]
This was a byproduct of interpolative Fortran rewrite. So all are brand new hence I did what I thought it should be but please go ahead and fix accordingly

**Comment by j-bowhay** [comment]
> > I could make the argument in the private function kwarg only and this would instantly root out any issues?
> 
> Sure that sounds great, if you're willing. Or if there's not a great place to put the `*`, maybe just put it right before `rng` and test locally. It doesn't even need to be committed as long as it's checked.

Done



> This was a byproduct of interpolative Fortran rewrite. So all are brand new hence I did what I thought it should be but please go ahead and fix accordingly. Actually I think we should deprecate this submodule altogether but that's a different story

No worries, in fact these are probably the easiest functions so far to convert to follow SPEC7

**Comment by mdhaber** [comment]
Thanks all!

**Pull request merged**
