### PR TITLE
DOC: example for ndimage.minimum_position

### PR DESCRIPTION
**Pull request by rafalalgo**
Reference to: https://github.com/scipy/scipy/issues/7168

### CODE REVIEW

**Comment by rafalalgo** [comment]
@ilayn probably it also can be merge. This is another example in documentation

**Comment by ilayn** [comment]
I think you need more empty lines to make it render correctly https://5723-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.ndimage.minimum_position.html#scipy.ndimage.minimum_position

In general think of these printed in the terminal you don't wish to have them cramped too much because it's very difficult to read where things start and end.

**Comment by ilayn** [comment]
Also some context about the particular examples would be nice (not much but just general one liners)

**Comment by rafalalgo** [comment]
Ok, now I think it should render correctly.
I also change format of matrix, now it is multiline.

**Comment by rafalalgo** [comment]
@ilayn everything is ok?

**Comment by ilayn** [comment]
@rafalalgo Thanks!

**Pull request merged**
