### PR TITLE
MAINT: Removed deprecated NumPy C api from `sparse`

### PR DESCRIPTION
**Pull request by Smit-create**
#### Reference issue

* References: https://github.com/rgommers/scipy/issues/30
* Using `numpy_nodepr_api` and removing `Wno-cpp` flags

#### Additional information

cc @rgommers

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Looks great, thanks @Smit-create!

**Comment by tupui** [comment]
@rgommers I don't see how this could be related, but the logo started to not appear on the devdoc after this got merged (I just went through the CI artifacts from the list here...)

**Comment by tupui** [comment]
Found it, it's an update of Sphinx, I will open an issue...

**Comment by rgommers** [comment]
> Found it, it's an update of Sphinx, I will open an issue...

Always the first thing I do - check release dates of all the usual suspects on PyPI:)

**Pull request merged**
