### PR TITLE
DOC: Add example to scipy.ndimage.zoom

### PR DESCRIPTION
**Pull request by MartinThoma**
See issue #8172 

Current docs: https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.ndimage.zoom.html#scipy.ndimage.zoom

### CODE REVIEW

**Comment by MartinThoma** [comment]
Is there a possiblity to show why `prefilter` is necessary? For the given example, I can't see a difference.

**Comment by rgommers** [comment]
Rendered version https://4957-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.ndimage.zoom.html#scipy.ndimage.zoom looks fine.

@MartinThoma no idea about your questions, haven't used `zoom` that much. Not sure if anyone else has an answer, if not then I suggest to merge as is, since it's an improvement.

**Comment by rgommers** [comment]
Okay, let's get this in. Thanks @MartinThoma

**Comment by rgommers** [comment]
@MartinThoma maybe worth opening a new issue with your two unanswered questions? Would be good to keep track of them.

**Comment by MartinThoma** [comment]
Thank you :-)

https://github.com/scipy/scipy/issues/8209 and https://github.com/scipy/scipy/issues/8210 are now opened

**Pull request merged**
