### PR TITLE
DOC: add section on global optimizers to tutorial

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by rgommers** [comment]
CI results are passing now, only issue is the already solved PyPy test failure on a warning from `signal.stft`.

**Comment by rgommers** [comment]
Here is a link to the built docs: https://10289-1460385-gh.circle-artifacts.com/0/html-scipyorg/tutorial/optimize.html#global-optimization

Should be good to merge. @andyfaff want to have a look?

**Comment by rgommers** [comment]
This is a straightforward tutorial improvement, I'll merge it soon if there are no comments.

**Review by tylerjereddy — APPROVED** [review]
Tutorial-only change & rendered docs look pretty. No other comments from reviewers, so in it goes.

**Comment by tylerjereddy** [comment]
Thanks Ralf

**Comment by tylerjereddy** [comment]
Added a very brief "Other changes" release note--not sure if appropriate.

**Comment by rgommers** [comment]
> Added a very brief "Other changes" release note--not sure if appropriate.

That's fine I think. Would be useful if we do that more often then. E.g. for this release one thing I can think of is the rework of the `stats.distributions` tutorials.

**Pull request merged**
