### PR TITLE
DOC: fft.dct: Improve example documentation for DCT

### LINKED ISSUE #21198: DOC: Better documentation for orthonormalization in scipy.fft for DCT
### Issue with current documentation:

Related to GitHub issue #15033 .

Scipy warns
> For type in {1, 2, 3}, norm="ortho" breaks the direct correspondence with the direct Fourier transform. To recover it you must specify orthogonalize=False.

This is a cryptic warning. Furthermore, as mentioned [here](https://github.com/scipy/scipy/pull/15102#issuecomment-983664469), having the two flags `ortho` and `orthogonalize` is somewhat confusing.

The descriptions that follow descripe the normalization effects on the coefficients that the `ortho` flag has, and the symmetry between the forward and inverse transforms. As a result, users are led to thinking that specifying `ortho="norm"` is simply one of the many normalization choices that will not affect the harmonic fit to a signal so long as the inverse transformation with the proper normalization is applied. This is however not true, and dangerous, for the reasons stated in GitHub issue #15033.

The current explanation is misleading, and I consider it a bug. Please explain this more thoroughly by adding the following example code and plot.  User should be aware of the significant error that can result if they do not specify `orthogonalize=False`.

### Idea or request for content:

```python
import matplotlib.pyplot as plt
import numpy as np
from numpy.polynomial.chebyshev import chebpts2
from scipy.fft import dct, idct

m = chebpts2(5)
n = chebpts2(m.size * 10)
normalize = np.sqrt((n.size - 1) / (m.size - 1))

f = m
sf_orthogonalize = (
    idct(dct(f, norm="ortho", type=1), n=n.size, norm="ortho", type=1) * normalize
)
sf_fourier = (
    idct(
        dct(f, norm="ortho", type=1, orthogonalize=False),
        n=n.size,
        norm="ortho",
        type=1,
        orthogonalize=False,
    )
    * normalize
)

plt.plot(m, f, label="truth", linestyle="--", linewidth=3, color="black", marker="o")
plt.plot(n, sf_orthogonalize, label=f"Type 1 DCT. orthogonalize=True.")
plt.plot(n, sf_fourier, label=f"Type 1 DCT. orthogonalize=False.")
plt.legend()
```

### Additional context (e.g. screenshots, GIFs)

scipy

### PR DESCRIPTION
**Pull request by unalmis**
#### Reference issue
Resolves #21198.

### CODE REVIEW

**Comment by lucascolley** [comment]
Thanks for looking at this. Quick tip: if you include `[docs only]` in your commit message (ideally on a new line), only the CI workflows relevant to docs will run

**Comment by j-bowhay** [comment]
@unalmis is the ready for review or is there more you had planned here?

**Comment by unalmis** [comment]
Sorry, got busy with other responsibilities.  I think the better option is to do what is mentioned on the linked issue
> Perhaps it's better to place the example here https://docs.scipy.org/doc/scipy/tutorial/fft.html and add a link to it from all the warnings. The explanations there also seem to just focus on normalization and don't comment that the transformations behave differently, so placing the example there would clarify that too.

If anyone wants to take over feel free to

**Comment by j-bowhay** [comment]
Thanks for the quick response, I will close this for now then

**Pull request closed without merging**
