### PR TITLE
MAINT: stats: fix `gibrat` name

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-15723

#### What does this implement/fix?
@josef-pkt noted that the `gilbrat` distribution likely has a typo in the name; this adds the alias `gibrat` and removes `gilbrat` from the documentation.

There is one reference to "Gilbrat" that I've found that seems independent of SciPy:
image
from [here](https://books.google.com/books?id=D_XKBQAAQBAJ&pg=PA1194&lpg=PA1194&dq=%22gilbrat+distribution%22&source=bl&ots=Cdm3PXyfVB&sig=ACfU3U1K7QqublwH8drIOWJ1pPPhlxvDCQ&hl=en&sa=X&ved=2ahUKEwi73rGE4vH2AhUhDkQIHY1gCLIQ6AF6BAgeEAM), but that seems to have been changed to Gibrat [on MathWorld](https://mathworld.wolfram.com/GibratsDistribution.html) (online). Ever other mention of "Gilbrat's" distribution I see online, including a reference in [an academic article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6636719/), seem to be based on SciPy's use of the name "Gilbrat".

_Gibrat_, though, was a person that actually had a lot to do with the lognormal distribution:
image

so "Gilbrat" is probably just a typo. 

#### Additional information
Feel free to close if we're happy to have coined the name Gilbrat for this distribution. Even though Gibrat was definitely associated with the lognormal distribution, "Gibrat Distribution" does not seem to be a common way to refer to this special case of lognormal, either.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
Seems like a reasonable change to make.

**Review by tupui — APPROVED** [review]
LGTM as well. Don't we want to deprecate the old name so that we can remove it in a few releases?

**Comment by mdhaber** [comment]
We could, but it's not harmful, so I thought the effort involved in deprecating it now would outweigh the sum of effort in the future involved with leaving it in : ) 
Maybe I'm missing something that would make it easy
 How would you go about it?

**Comment by tupui** [comment]
Sure, I would maybe just have used `gilbrat = np.deprecate(gibrat, ...)`. Nothing more and IMO no extra test needed for such thing

**Comment by mdhaber** [comment]
I don't think that's working; these are instances of a class, but `np.deprecate` is for functions. This example is a little backwards because I don't have the branch checked out right now, but here's the idea. The last line shows the problem:
```python3
from scipy.stats import gilbrat
gibrat = np.deprecate(gilbrat, 'gilbrat', 'gibrat')
gilbrat()  # OK
gibrat() # DeprecationWarning:     `gilbrat` is deprecated, use `gibrat` instead!
gilbrat.pdf(1)  # 0.3989422804014327
gibrat.pdf(1)  # AttributeError: 'function' object has no attribute 'pdf'
```

**Comment by tupui** [comment]
Ark ok I see. I don't know right now how to do. We can do this later.

**Comment by mdhaber** [comment]
> Ark ok I see. I don't know right now how to do. We can do this later.

The way I considered doing it would be the obvious one - copy the `gibrat_gen` class or subclass it and raise the deprecation warning in all the subclass methods : / That's why I thought I'd just leave it. Not too much work for the person who is copying and pasting, but harder to review.

**Comment by tupui** [comment]
Yeah not a fan of such duplication. @h-vetinari since you are the master of DEP now 😉, any ideas?

Anyway, nothing prevents the merge now so going ahead.

**Comment by h-vetinari** [comment]
I don't think the duplication here is too bad. Having one `_gen` method generate both wrappers seems like a fine approach. The only thing missing here seems to be the deprecation of `gilbrat`? If that was our typo, I'd definitely deprecate it.

**Comment by tupui** [comment]
@h-vetinari This is the question, how do we go about the deprecation.

**Comment by h-vetinari** [comment]
Ah, OK, sorry I didn't get that right away. Can we not override the inherited `__new__` and/or `__init__` in `gibrat_gen` to emit the deprecation if `name=gilbrat`...?

**Comment by mdhaber** [comment]
That would be emitted to everyone when the module is loaded because `gilbrat` is an instance of class `gilbrat_gen` that is created when stats is loaded. We want the warning to be emitted only to users that attempt to use `gilbrat`.

**Comment by h-vetinari** [comment]
Ah yes, it's already _instantiating_ the class at import time - sigh...

> We want the warning to be emitted only to users that attempt to use `gilbrat`.

Then I don't see much of a different possibility other than overriding the methods of the class. Here's a drafty solution that seems to work in my testing.
```
import warnings
from scipy.stats import gilbrat

def mydeco(func):
    def wrapper(*args, **kwargs):
        warnings.warn("Say something!", DeprecationWarning)
        return func(*args, **kwargs)
    return wrapper

# documented methods from https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gilbrat.html
method_names = [
    "cdf", "entropy", "expect", "fit", "interval", "isf", "logcdf", "logpdf",
    "logsf", "mean", "median", "moment", "pdf", "ppf", "rvs", "sf", "stats",
    "std", "var"
]

for m in method_names:
    setattr(gilbrat, m, mydeco(getattr(gilbrat, m)))
```

This yields:
```
>>> gilbrat.pdf(1)
<stdin>:3: DeprecationWarning: Say something!
0.3989422804014327
```

**Comment by h-vetinari** [comment]
Upon further thought, we can also replace the custom wrapper by using `np.deprecate` directly for each of the methods:
```python
import warnings
from scipy.stats import gilbrat
import numpy as np

# documented methods from https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gilbrat.html
method_names = [
    "cdf", "entropy", "expect", "fit", "interval", "isf", "logcdf", "logpdf",
    "logsf", "mean", "median", "moment", "pdf", "ppf", "rvs", "sf", "stats",
    "std", "var"
]

for m in method_names:
    wrapper = np.deprecate(getattr(gilbrat, m), f"gilbrat.{m}", f"gibrat.{m}",
                           "Please replace all uses of the distribution class "
                           "`gilbrat` with the corrected spelling `gibrat`!")
    setattr(gilbrat, m, wrapper)
```

Result:
```
gilbrat.pdf(1)
<stdin>:1: DeprecationWarning:         `gilbrat.pdf` is deprecated, use `gibrat.pdf` instead!
        Please replace all uses of the distribution class `gilbrat` with the corrected spelling `gibrat`!
0.3989422804014327
```

In either case, WDYT about this approach @mdhaber?

**Comment by mdhaber** [comment]
Yes, I think that looks good!

**Pull request merged**
