### PR TITLE
ENH: sparse.linalg: further LGMRES cleanups

### PR DESCRIPTION
**Pull request by pv**
Some further lgmres cleanups / corner-case bugfixes:
- Remember the well-known fact that the residual of the Arnoldi LSQ problem is known without solving the problem, so move the QR triangular solve out from the inner loop.
- Be more careful with the "exact solution" special case and denormals; fixes a bug if the RHS vector was numerically exact eigenvector of the matrix.

Moving trtrs outside gives minor speedup:

```
    before     after       ratio
  [3deede3a] [f30505b8]
+    1.13ms     1.19ms      1.06  sparse_linalg_solve.Bench.time_solve(10, 'minres')
-  593.07μs   560.31μs      0.94  sparse_linalg_solve.Bench.time_solve(6, 'lgmres')
-    1.19ms     1.12ms      0.94  sparse_linalg_solve.Lgmres.time_inner(1000, 10)
-    2.05ms     1.93ms      0.94  sparse_linalg_solve.Bench.time_solve(16, 'minres')
-  722.58μs   676.08μs      0.94  sparse_linalg_solve.Lgmres.time_inner(50, 10)
-  710.87μs   661.77μs      0.93  sparse_linalg_solve.Lgmres.time_inner(50, 180)
-  712.41μs   662.99μs      0.93  sparse_linalg_solve.Lgmres.time_inner(50, 30)
-    3.89ms     3.59ms      0.92  sparse_linalg_solve.Lgmres.time_inner(1000, 30)
-   12.68ms    11.72ms      0.92  sparse_linalg_solve.Bench.time_solve(40, 'lgmres')
-   17.87ms    16.50ms      0.92  sparse_linalg_solve.Lgmres.time_inner(1000, 90)
-  716.74μs   661.12μs      0.92  sparse_linalg_solve.Lgmres.time_inner(50, 60)
-    6.48ms     5.94ms      0.92  sparse_linalg_solve.Bench.time_solve(25, 'lgmres')
-  723.36μs   661.16μs      0.91  sparse_linalg_solve.Lgmres.time_inner(50, 90)
-  893.23μs   816.19μs      0.91  sparse_linalg_solve.Lgmres.time_inner(100, 10)
-    1.06ms   962.73μs      0.91  sparse_linalg_solve.Lgmres.time_inner(100, 90)
-    1.04ms   947.32μs      0.91  sparse_linalg_solve.Lgmres.time_inner(100, 30)
-    9.85ms     8.96ms      0.91  sparse_linalg_solve.Lgmres.time_inner(1000, 60)
-   57.98ms    52.63ms      0.91  sparse_linalg_solve.Lgmres.time_inner(1000, 180)
-    1.05ms   948.43μs      0.91  sparse_linalg_solve.Lgmres.time_inner(100, 180)
-    1.07ms   957.76μs      0.89  sparse_linalg_solve.Lgmres.time_inner(100, 60)
-    1.26ms     1.12ms      0.89  sparse_linalg_solve.Bench.time_solve(10, 'lgmres')
-  379.98μs   289.10μs      0.76  sparse_linalg_solve.Lgmres.time_inner(10, 10)
-   31.82ms    23.88ms      0.75  sparse_linalg_solve.Bench.time_solve(100, 'minres')
-  114.80ms    74.30ms      0.65  sparse_linalg_solve.Bench.time_solve(100, 'lgmres')
SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
```

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I just recently pulled from `master` and had a failure on `scipy.test('full')` on MKL:
```
======================================================================
ERROR: test__root.TestRoot.test_tol_parameter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/custombuilds/nose/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/tests/test__root.py", line 34, in test_tol_parameter
    sol1 = root(func, [1.1,1.1], jac=jac, tol=1e-4, method=method)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/_root.py", line 198, in root
    **options)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/_root.py", line 301, in _root_nonlin_solve
    raise_exception=False)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/nonlin.py", line 309, in nonlin_solve
    dx = -jacobian.solve(Fx, tol=tol)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/nonlin.py", line 1457, in solve
    sol, info = self.method(self.op, rhs, tol=tol, **self.method_kw)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/lgmres.py", line 255, in lgmres
    dx = ws[0]*y[0]
IndexError: list index out of range
```
Do you think it's related?

I'll try this branch and see if it's fixed.

**Comment by pv** [comment]
@Eric89GXL: it may be related.

**Comment by Eric89GXL** [comment]
This PR indeed fixes that failure. I do have two others having to do with `test_nonlin.TestNonlin` but I'll open an issue for those separately.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @pv

**Pull request merged**
