### PR TITLE
MAINT: Remove _lib/_numpy_compat.py

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
We now require at least numpy 1.13.3, which contains all the
functions that were in _numpy_compat.py.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
This might be simpler to do as two PRs, with the warning suppression in one and the rest of the changes in another.

Also, I think it would be nice to keep the _numpy_compat.py file around with a comment explaining what it's there for, even if we remove all the actual code from it.

**Comment by larsoner** [comment]
I'm happy enough with this as is, it was pretty quick to review even though it was 70+ files.

> Also, I think it would be nice to keep the _numpy_compat.py file around with a comment explaining what it's there for, even if we remove all the actual code from it.

Why should we do this? It's in a private namespace so we should be able to kill it without any issue.

**Review by larsoner — APPROVED** [review]

**Comment by WarrenWeckesser** [comment]
> Also, I think it would be nice to keep the _numpy_compat.py file around with a comment explaining what it's there for, even if we remove all the actual code from it.

I thought about that, but there is nothing magical or difficult in that file, so it is trivial to make a new one if we need it again.

**Comment by WarrenWeckesser** [comment]
The second commit was a quick fix for what appeared to be a Python crash on the ppc64le platform on Travis-CI.  I don't know why that platform was crashing, and I'm still a little worried about that.

**Comment by rgommers** [comment]
> The second commit was a quick fix for what appeared to be a Python crash on the ppc64le platform on Travis-CI. I don't know why that platform was crashing, and I'm still a little worried about that.

Ah nice catch with the missing seed. We should find one that crashes though and open an issue for that. That intermittent crash is one we'd been ignoring.

**Comment by WarrenWeckesser** [comment]
> Ah nice catch with the missing seed. We should find one that crashes though and open an issue for that. That intermittent crash is one we'd been ignoring.

Adding the seed was a shot in the dark.  For this PR, that was the test that appeared to be triggering the failure.  But in a new PR (https://github.com/scipy/scipy/pull/11252, which is just master with a bunch of tests removed), there was also crash on the Travis-CI ppc64le platform, but at a different function in linalg.  So maybe I was just lucky that the crash didn't occur when I added the seed in this PR.

**Comment by rgommers** [comment]
Merged, thanks @WarrenWeckesser

**Pull request merged**
