### PR TITLE
TST: skip `test_heequb`, it fails intermittently.

### PR DESCRIPTION
**Pull request by rgommers**
See gh-11902 for details.

### CODE REVIEW

**Comment by rgommers** [comment]
@tylerjereddy I think this should still go into 1.5.0

**Comment by ilayn** [comment]
+1 from me. But the reason is that only python 3.7 dbg is picking up some openblas version. So it's a platform issue not the test (I literally went over the whole Fortran code and submitted bug reports to both Reference lapack and OpenBLAS).

**Comment by rgommers** [comment]
Okay thanks, I'll amend `reason=`

**Comment by rgommers** [comment]
and make it `skip` rather than `xfail` then

**Comment by ilayn** [comment]
Hopefully since https://github.com/xianyi/OpenBLAS/pull/2635 is merged this will go away by itself.

**Comment by rgommers** [comment]
Ah, very nice, thanks for hunting that down!

**Comment by tylerjereddy** [comment]
Ok, if you want this in the second release candidate make sure it has been merged with `1.6.0` milestone and retains a backport label. @ilayn seems to suggest it may not be needed? I have not seen the failure affecting the wheels repo for 1.5.x so far.

**Comment by ev-br** [comment]
> submitted bug reports to both Reference lapack and OpenBLAS)

Mind linking to these bug reports here, for future reference?

**Comment by ilayn** [comment]
Let's get this in to ease of the pain of the PRs. Thanks Ralf and all.

**Pull request merged**
