### PR TITLE
BENCH: selection of linalg solvers to facilitate expansion

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

In this PR, some condition expression is simplified, so it will be more convenient adding new solvers.

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Thanks @zhaog6 for the PR. I am personally "allergic" to `eval`, but if others are fine with it why not.

**Comment by zhaog6** [comment]
> I am personally "allergic" to `eval`, but if others are fine with it why not.

Thank you @tupui ‘for your review. Yes, `eval` is an unsafe function when it comes to those system operations. Because we only parse the `params` in the class `Bench` and instead of directly outputting/return `eval(solver)`, it makes a function call.

**Comment by zhaog6** [comment]
> If you want to avoid the `if: elif:` chain, then I recommending making a `dict` mapping the names to the functions.

Ok, `dict` looks like a good choice, I'll try it. Thanks Robert and Pamphile.

**Comment by zhaog6** [comment]
Dear @tupui @rkern , I have updated this PR. Please check it.

**Review by tupui — APPROVED** [review]
LGTM, thanks @zhaog6

**Pull request merged**
