### PR TITLE
FIX: Make scipy.odr.ODR ifixx equal to its data.fix if given

### LINKED ISSUE #9140: odr.Data `fix` assignment is not passed through to odr.ODR as `ifixx` assignment
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

I am using `scipy.odr` to fit an implicitly defined function. It seems that I have to assign directly to `ifixx` when creating an `odr.ODR` object instead of relying on my earlier assignment to `fix` when creating the `odr.Data` object that I pass to `odr.ODR`. Perhaps defining `fix` in odr.Data objects should simply be removed, because this duplicated functionality is somewhat confusing and doesn't seem to work as expected with `odr.ODR`. Otherwise, if this is the intended behavior, then perhaps this requirement to specify both `fix` and `ifixx` should be better documented.

### Reproducing code example:
Input:
```Python
import scipy.odr as odr

# Some noisy data solving x2 = x1**2
x1 = [-2.01, -0.99, -0.001, 1.02, 1.98]
x2 = [3.98, 1.01, 0.001, 0.998, 4.01]
fix = np.vstack((np.zeros_like(x1, dtype=int), np.ones_like(x2, dtype=int)))

# Fixing x1 via the odr.Data object
odr_data = odr.Data(np.vstack((x1, x2)), y=1, fix=fix)

# Define the odr.Model object with an implicit model
odr_model = odr.Model(lambda beta, x: x[1, :] - beta[0] * x[0, :]**2., implicit=True)

# Prep and run the model WITHOUT specifying ifixx in odr.ODR object construction
odr_odr = odr.ODR(odr_data, odr_model, beta0=np.array([1.]))
odr_sol = odr_odr.run()
print(odr_sol.beta)

# Prep and run the model WITH specifying ifixx in odr.ODR object construction
odr_odr = odr.ODR(odr_data, odr_model, beta0=np.array([1.]), ifixx=fix)
odr_sol = odr_odr.run()
print(odr_sol.beta)
```
Output:
```
[1.00205273]
[1.00277605]
```
(I think the output should be the second output in both cases.)

### Error message:
N/A

### Scipy/Numpy/Python version information:
```
Python version: 3.6.5
Numpy version: 1.14.5
Scipy version: 1.1.0
```

### PR DESCRIPTION
**Pull request by t5**
- `scipy.odr.ODR` objects do not make use of their given `scipy.odr.Data` object's `fix` argument, even when not given an `ifixx`.
- solves this by using `ifixx` when given, and the `data.fix` when not.

Closes #9140.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
I agree that this seems confusing and may also need a doc adjustment to clarify; the data object docs do indicate that `fix` should be equivalent to `ifixx`, but certainly don't make it clear that one has to actually provide the same argument to both. Is the natural assumption that if both are provided but not the same, that this requires a warning or exception handling? Or that the ifixx overrides?

Also, if another reviewer agrees with the fix (no pun intended..) you've suggested here, I suspect we'll need a unit test for the behavior--the example provided in the linked issue has a contained example with expected output so that's a good starting point for a unit test.

**Comment by rkern** [comment]
I think the PR's behavior is the desired one. Specifying `ifixx` should override the `data.fix` silently.

LGTM, pending test case.

**Comment by pv** [comment]
Test case should go in [scipy/odr/tests/test_odr.py](https://github.com/scipy/scipy/blob/master/scipy/odr/tests/test_odr.py)

**Comment by t5** [comment]
Thank you for comments! I added the test case, does it look alright?

**Review by tylerjereddy — APPROVED** [review]
Yes, thanks for adding the test. You could also add a comment in the test about the issue it fixes, but I suspect that's not crucial.

I see you used the code in the linked issue for the unit test, which is also sensible.

+1 to merge from me

**Review by jeffyancey — APPROVED** [review]

**Comment by rgommers** [comment]
Positive reviews and all green, merging. Thanks @t5, all.

**Pull request merged**
