### PR TITLE
TST: DeprecationWarnings in stats on python 3.5 closes #5885

### LINKED ISSUE #5885: DeprecationWarnings in stats on python 3.5
```
/home/br/repos/scipy/build/testenv/lib/python3.5/site-packages/scipy/stats/tests/test_stats.py:101: DeprecationWarning: Please use assertRaisesRegex instead.
```

Apparently, `assertRaisesRegexp` was renamed to `assertRaisesRegex`:  https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegexp

### PR DESCRIPTION
**Pull request by andyfaff**

### CODE REVIEW

**Comment by pv** [comment]
The function doesn't appear to exist on Numpy 1.7.2.

**Comment by rgommers** [comment]
Maybe just take the cleaned up implementation of ``assert_raises_regex`` from https://github.com/numpy/numpy/pull/7636 and put it in ``scipy/_lib/_numpy_compat.py`` to fix the version issue.

**Comment by rgommers** [comment]
Marked this for 0.18.0 - since Python 3.6 is coming out in the summer, we need to fix all 3.5 deprecation warnings I think.

**Comment by andyfaff** [comment]
Hopefully this is suitable now.

**Comment by ev-br** [comment]
Thanks Andrew

**Pull request merged**
