### PR TITLE
DOC: add cobyqa website reference (#20841)

### PR DESCRIPTION
**Pull request by andyfaff**
Backport: added Zaikunzhang as co-author to make sure he appears in commit history.

### CODE REVIEW

**Comment by andyfaff** [comment]
@rgommers, hopefully this is done right.

- I checked out maintenance/1.14.x
- I created a feature branch off the maintenance branch
- I cherry picked the commit that added the link
- I interactively rebased to reword the commit message (co-authored-by)
- I made this PR of the feature branch onto the maintenance branch.

**Review by rgommers — APPROVED** [review]
Thanks @andyfaff. Yes, that all sounds right. This works as intended - running `$ python tools/authors.py v1.13.1..HEAD` shows that the contribution count increases by one person, and the authors log includes `* Zaikun ZHANG (1)`.

I'll leave it to @tylerjereddy to merge this, since I'm not sure if it's preferred to include the updated release notes in this PR or separately before the final release.

**Comment by andyfaff** [comment]
Accidentally deleted the branch on my fork.

**Comment by zaikunzhang** [comment]
Thank everyone for doing this. It is highly appreciated. 
- Zaikun

**Review by tylerjereddy — APPROVED** [review]
Rendered doc update looks good, fine to update the authors this way too I think. I usually update the release notes after a batch of backports.

**Pull request merged**
