### PR TITLE
BLD: update minimum Cython version to 3.0.8

### PR DESCRIPTION
**Pull request by rgommers**
Needed for `const memoryview` with fused types, which we just started using (xref gh-20195).

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
LGTM

**Comment by ev-br** [comment]
Thanks Ralf, Lucas. Merged.

**Comment by matusvalo** [comment]
A little late. There is already Cython 3.0.9 which also allows to reduce binary size. See https://github.com/cython/cython/issues/6034#issuecomment-1962861384

**Comment by rgommers** [comment]
Thanks @matusvalo. We'll actually automatically build with the latest release, so we'll get the improvements for our wheels. But I'd rather not set the lower limit to a version released yesterday unless it's a hard necessity. We're going to do a release within a couple of weeks, so 3.0.8 is a nicer lower bound for now.

**Pull request merged**
