### PR TITLE
fix docstring typo: valdiation to validation

### PR DESCRIPTION
**Pull request by daguiam**
Fixed typo in `_fft_helper` docstring

### CODE REVIEW

**Comment by daguiam** [comment]
I see that other helper functions keep the stackoverflow references. These might give some hindsight on the implementation of the function, and guide new users who are browsing the source code for the first time, such as me.
Is there a trend towards removing these stackoverflow references from other helper functions in SciPy?
I am of the opinion of keeping these and other references in the documentation. Either as a reference or as a comment in the code.

**Comment by ilayn** [comment]
References are of course fine and valuable but this has no relevance to FFTs or other properties of the original function. It is not even cited but only mentions the stride trick. If you look at the implementation you will probably go to NumPy documentation anyways or search on SO. 

We had the same discussion #7833 about these type of references, coincidentally, again about strides.

**Comment by daguiam** [comment]
I understand the argument and have removed the `References` sections pointing to stackoverflow.
I searched the scipy code repository for stackoverflow answers and these are, at best, inline comments.

**Comment by ilayn** [comment]
Nice. Thank you @daguiam

**Pull request merged**
