### PR TITLE
TST: silence runtime warnings for some corner cases in `stats` tests.

### PR DESCRIPTION
**Pull request by aeklant**
see issue #4734.

### CODE REVIEW

**Comment by aeklant** [comment]
I tried to keep the context limited to the line where we know the `RuntimeWarning` is raised (except for `test_nanmedian_scalars` where the test implementation wouldn't allow it) in order to only silence explicitly where we have detected a problem. I wouldn't want to inadvertently silence any warning that may alert of other possible issues in the future.

**Comment by rgommers** [comment]
Keeping the part inside the context manager as limited as possible is the right approach. This PR looks good to me. I'll test it with latest numpy locally, if that's OK and TravisCI is green then this can go straight in.

**Comment by ev-br** [comment]
As  a data point, `stats` tests are clean for me locally with a recent numpy:

```
$ python runtests.py -s stats -m full
Building, see build.log...
Build OK
Running unit tests for scipy.stats
NumPy version 1.10.0.dev0+0752872
NumPy relaxed strides checking option: True
NumPy is installed in /home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy
SciPy version 0.16.0.dev0+c65ff98
SciPy is installed in /home/br/installs/scipy/build/testenv/lib/python2.7/site-packages/scipy
Python version 2.7.3 (default, Sep 26 2013, 20:03:06) [GCC 4.6.3]
nose version 1.3.4
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K............K..........................................................................................................................................................S...........S......................................................................................................................................................................................................................................................................................................................................................................................................................................KKKKK.......................................................................................KKKK.....................................................................................................................................................KKKKK............................................................................................................................................................................................................................................................................................................K.........................................K...........................S................................................................S...............................................................................................................................S.......................................................................................................................................................................................................K.KK...............KK.K..................K....K......K.K.K..K.K.........K..K.K....K.........................................................................................................................................S..S...............................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 3193 tests in 150.791s

OK (KNOWNFAIL=35, SKIP=7)
```

**Comment by aeklant** [comment]
Thanks @ev-br.

**Comment by rgommers** [comment]
All green, so in it goes. Thanks @aeklant

**Pull request merged**
