### PR TITLE
ENH: Use quick_select for PyArray_OrderFilterND instead of qsort.

### LINKED ISSUE #1345: ND order filter should use qselect rather than qsort (Trac #818)
_Original ticket http://projects.scipy.org/scipy/ticket/818 on 2008-12-18 by @thouis, assigned to unknown._

PyArray_OrderFilterND in signal/sigtoolsmodule.c finds the Kth smallest element in an array by calling qsort() and then extracting the Kth element.  It should use a qselect() routine.  One could be generalized from the QUICK_SELECT macro in signal/medianfilter.c

(Or, with more work, it could use methods similar to those in "Median Filtering in Constant Time", Perreault, S. & Hebert, P., IEEE Trans. on Image Processing, Sept. 2007)

### PR DESCRIPTION
**Pull request by DWesl**
#### Reference issue

Closes #1345

#### What does this implement/fix?

Moves the `quick_select` code from `scipy/signal/_medianfilter.c` to `scipy/signal/_sigtoolsmodule.c` and makes it a function building on the already existing comparison-function code in that file (based on [@thouis's suggestion on #1345](https://github.com/scipy/scipy/issues/1345#issuecomment-1151068810)).  Replaces the `quick_select` instantiations in `scipy/signal/_medianfilter.c` with small wrapper functions using the implementations from `scipy/signal/_sigtoolsmodule.c`.

#### Additional information

The `scipy.signal` tests pass, but I haven't run benchmarks, so I don't know if this is practically faster as well as theoretically faster.  I can't think of a reason for a slowdown in PyArray_OrderFilterND, but the median filtering code redirects comparisons through a function pointer instead of using '<' with float, double, and unsigned byte arguments.  The compiler might decide to inline everything and keep the speed, or keep the size down and accept the speed hit.

### CODE REVIEW

**Comment by DWesl** [comment]
The CircleCI failure seems to be "click isn't installed on the runner", which I don't think is related.

The Azure failures seem to fall into two camps:
- MSVC has no idea how to handle `int8_t var[n_elem];` in a function that takes `size_t n_elem` as an argument
- MSVC has no idea how to handle the `restrict` keyword

I could fix the first problem by making that bit of memory a constant 256 bits so it fits every NumPy type, and the second by `#define`ing `restrict` to nothing on MSVC or non-GCC compilers.

**Comment by DWesl** [comment]
MS Visual Studio still complained about `restrict`, so I removed all references to that keyword.  There's an excellent chance the compiler could figure that information out on its own.

EDIT: Apparently the problem with `void * restrict` is with the `void *` part, not the `restrict` part.  I have no idea what MSVC wants from me.

**Comment by DWesl** [comment]
The CircleCI error is still `ModuleNotFoundError: No module named 'click'`, which is probably unrelated.

**Comment by DWesl** [comment]
Where would I look for those?

**Comment by thouis** [comment]
I'm on vacation this week, but can review it when I return.

**Comment by thouis** [comment]
For benchmarking, performing a large 2d order filter (signal.order_filter) using an also-large all-1s domain should help tease out if there are significant improvements in this code.

There's very little test coverage of signal.order_filter, that I see.  Adding at least the [examples](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.order_filter.html) would be an easy start, though it's also worth adding a slightly more complicated (asymmetric) domain to that test, as well as other data types.

Changes look good to me.

**Comment by DWesl** [comment]
I added a benchmark and tried running it with this branch and `main`, but it showed no difference.  I'm trying a different way to run the benchmarks to see if the results are different.

**Comment by thouis** [comment]
How long did the benchmarks take?  If it's not up in the dozens of seconds, there may be no visible difference.

**Comment by DWesl** [comment]
I made a new version of the benchmark filtering a smaller array using a larger mask.  Results for this branch:
```bash
$ PYTHONPATH=build/testenv/lib/python3.9/site-packages/ python -m asv run --config=benchmarks/asv.conf.json --python=/usr/bin/python3.9 --bench 'OrderFilter2D.time_orderfilter'
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Benchmarking existing-py_usr_bin_python3.9
[ 50.00%] ··· Running (signal_filtering.OrderFilter2D.time_orderfilter--).
[100.00%] ··· signal_filtering.OrderFilter2D.time_orderfilter                                                                                                                                                   ok
[100.00%] ··· ============= =============
               filter_size
              ------------- -------------
                    1        16.1±0.01ms
                    11         549±3ms
                   101        41.6±0.03s
              ============= =============
```
and for the system-installed version:
```bash
$ python -m asv run --config=benchmarks/asv.conf.json --python=/usr/bin/python3.9 --bench 'OrderFilter2D.time_orderfilter'
· No `environment_type` specified in asv.conf.json. This will be required in the future.
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
[  0.00%] ·· Benchmarking existing-py_usr_bin_python3.9
[ 50.00%] ··· Running (signal_filtering.OrderFilter2D.time_orderfilter--).
[100.00%] ··· signal_filtering.OrderFilter2D.time_orderfilter                                                                                                                                                   ok
[100.00%] ··· ============= =============
               filter_size
              ------------- -------------
                    1        16.1±0.05ms
                    11         552±3ms
                   101         50.5±4s
              ============= =============
```
Increasing the size of the data to be filtered to 300x401 reduced the differences to a few percent, which I am willing to chalk up to differences in load (45ms, 1.6s, 2.2m for the three `filter_size`s).

**Comment by j-bowhay** [comment]
If there is no appreciable speed up then unfortunately closing this (and the original issue) might be the best option

**Comment by tylerjereddy** [comment]
This comment worries me a bit:

> There's very little test coverage of signal.order_filter, that I see. Adding at least the [examples](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.order_filter.html) would be an easy start, though it's also worth adding a slightly more complicated (asymmetric) domain to that test, as well as other data types.

I can't quite tell if that's a request for more testing in this PR vs. a follow-up PR, but obviously if test coverage is lacking I'm a bit hesitant to merge this just before branching a new release. @thouis thoughts?

If the experts here are indeed confident, and activity resumes on this PR before we branch ~middle of next week, we can of course add the milestone back if it gets merged on time, but this has been inactive for 3 months now.

**Comment by thouis** [comment]
If the code isn't faster, there's not much motivation to try to merge any time soon.  If it's not faster, and the code isn't much simpler, there's probably no need to change it at all.

In any of the cases, more test coverage would be a good thing - that may be another PR, though.

**Comment by j-bowhay** [comment]
@DWesl it might be worth open a separate pr for those additional tests so they are not dependent on the fate of this pr.

**Comment by DWesl** [comment]
Made a tests-only PR at #17531

**Comment by j-bowhay** [comment]
xref: #18341

**Comment by j-bowhay** [comment]
This code is now deprecated and slated for removal, regardless thank you for your efforts looking into this @DWesl

**Pull request closed without merging**
