### PR TITLE
MAINT: lint: ignore E501 (line length) by subpackage

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue

Towards gh-19479.

#### What does this implement/fix?

- Ignore E501 (max line length 88 chars) by submodule instead of project wide

### CODE REVIEW

**Comment by lucascolley** [comment]
@mdhaber here are the changes to just `lint.toml`

**Review by mdhaber — APPROVED** [review]
The lint check isn't failing, and the changes seem to fit with the rest of the file, so this LGTM. That said, I haven't confirmed that the lint check starts failing when one of these exceptions is removed, and I try to avoid changing or reviewing configuration files. @j-bowhay would you be willing to take a look/merge?

**Comment by lucascolley** [comment]
The lint check won't actually fail unless you remove one of the exceptions _and_ make a change in one of impacted files. To apply `ruff` to the whole codebase without having to make spoof changes you can run `ruff check . --config='tools/lint.toml'`

**Review by j-bowhay — APPROVED** [review]
Checked locally and all seems fine. Thanks @lucascolley

**Pull request merged**
