### PR TITLE
MAINT: fix sparse matrix comparison operator overloading

### LINKED ISSUE #4819: Comparison operator overloading doesn't work with sparse matrices
I'm the developer of a modeling framework for optimization problems called cvxpy. I'd like to support operator overloading between scipy sparse matrices and cvxpy objects.

Currently operator overloading works for arithmetic operations, but I also need it to work for comparison operators. The issue is that all comparison operators route through the `_inequality` function in `scipy/sparse/compressed.py`, and there's no code path in that function that returns `NotImplemented`. 

Could you add some code path that returns `NotImplemented` like in the arithmetic operators? That way the reflection will be called on the cvxpy object. For example, if `A` is a sparse matrix and `x` is a cvxpy variable, the expression `A <= x` will first call `A.__le__(x)`. This needs to return `NotImplemented` so Python calls `x.__ge__(A)`, which creates a cvxpy constraint object.

The same issues apply to the `__eq__` method in `scipy/sparse/compressed.py`. There should be some code path that returns `NotImplemented`.

Another solution would be to check `__array_priority__` like in Numpy. The object with the higher `__array_priority__` would have its comparison operator called first.

### PR DESCRIPTION
**Pull request by bhushan-borole**
closes gh-4819

### CODE REVIEW

**Comment by rgommers** [comment]
@bhushan-borole I edited your title and description so it's clear what this is about. It would be good if you could add a description of why this is the right fix, and add a test.

**Comment by bhushan-borole** [comment]
@rgommers  This is my first time contributing to any open-source-systems, Can you please help me as where and how add description and tests.

**Comment by rgommers** [comment]
Hi @bhushan-borole, of course. The tests go in `scipy/sparse/tests/test_base.py`. Search for "overloading" in that file, there are already tests. The idea is you add some small piece of code that would fail without your changes in this PR, but work with it.

Description, just here - either in a new comment or by editing the description at the top.

**Comment by bhushan-borole** [comment]
This fix seems to solve the problem, because it is a fix for operator overloading for comparison operators.
Code path for ```NotImplemented``` is added for comparison operators that routes through ```_inequality```.

**Pull request closed without merging**
