### PR TITLE
MAINT: additional 1.6.3 backport

### PR DESCRIPTION
**Pull request by tylerjereddy**
- gh-13890 was blocking the SciPy `1.6.3` release so backport the attempted fix + update release notes accordingly
- I could have probably just hit the "restart" button for the flaky test and published the release, but perhaps best not to *intentionally* release with a stochastic/flaky test

### CODE REVIEW

**Comment by rgommers** [comment]
Pushed a fix for the failing benchmarks CI.

**Comment by pmla** [comment]
@tylerjereddy What is the timeline for this release? I have a bugfix for `disjoint_set` I would perhaps like to include. I haven't made an issue or PR for it yet though.

**Comment by tylerjereddy** [comment]
@pmla I was planning to just release as-is, but various snags have slowed me down; looks like benchmarks are timing out in CI

**Comment by rgommers** [comment]
All green now.

**Comment by tylerjereddy** [comment]
I updated the release notes accordingly--if it remains green we should be good to merge.

**Pull request merged**
