### PR TITLE
ENH: Added normal-inverse-gamma distribution (#6528)

### LINKED ISSUE #6528: Add Normal-inverse-gamma distribution
Right now the [Normal-inverse-gamma distribution](https://en.wikipedia.org/wiki/Normal-inverse-gamma_distribution) is missing in `scipy.stats`. I think it qualifies as useful addition since it is the [conjugate prior](https://en.wikipedia.org/wiki/Conjugate_prior) of the normal distribution in case mean and variance are unknown. Therefore the Normal-inverse-gamma distribution is important for Bayesian inference which has been for years and still is a trending topic in the domain of data science.

### PR DESCRIPTION
**Pull request by MatteoRaso**
The distribution has methods for logpdf, pdf, cdf, sf, entropy, and rvs.

#### Reference issue

Closes gh-6528
#### What does this implement/fix?

Adds the normal-inverse-gamma distribution.
#### Additional information

I wasn't able to get Sphinx working, so I'm not totally confident that the code will render correctly on the website. As for the entropy method, I couldn't find a formula online, so I derived it myself. The formula passes the tests and the math looks good to me, but it wouldn't hurt for somebody else to review it. 
[A_Short_And_Simple_Derivation_of_The_NIG_Entropy.pdf](https://github.com/scipy/scipy/files/10903970/A_Short_And_Simple_Derivation_of_The_NIG_Entropy.pdf)

### CODE REVIEW

**Comment by MatteoRaso** [comment]
@tirthasheshpatel Here's the PR for the normal-inverse-gamma distribution, as we discussed a month ago. Also, @dschmitz89 , the entropy method for this distribution ties into #17748, so you might want to take a look at it.

**Comment by dschmitz89** [comment]
Thanks for the PR @MatteoRaso. The linked issue clearly received a lot of traffic, so looks like a definite improvement.

One general comment before an actual review.

What is implemented here looks like the 2D case for me (see [Wikipedia](https://en.wikipedia.org/wiki/Normal-inverse-gamma_distribution#Probability_density_function)):

image

scipy's other multivariate distributions are n-dimensional, so I am a bit sceptical if this is a good API. Was this discussed on the mailing list?

Going a step ahead: would you potentially be up to implementing the n-dimensional generalization instead? From 10km above, I guess that at least some code from Wishart/multivariate normal distributions could be reused.

**Comment by MatteoRaso** [comment]
>scipy's other multivariate distributions are n-dimensional, so I am a bit sceptical if this is a good API. Was this discussed on the mailing list?
Not on the mailing list from what I know, but in the linked issue, member @josef-pkt said it should be put with the multivariate distributions. There was a failed PR that also put this distribution in _multivariate.py, and there were no concerns about that.
>would you potentially be up to implementing the n-dimensional generalization instead?
I plan to in the distant future, but I only want to work on one distribution at a time. I already wrote the code for the NIG distribution, so that might as well be the one I work on.

**Comment by rkern** [comment]
We don't need the n-dimensional-`x` variant to make this distribution multivariate. The fact that both `x` and $\sigma^2$ are in the domain of the distribution (and not just shape parameters) make this multivariate.

That said, what's implemented here mostly seems to treat `sig2` as a shape parameter for a univariate distribution over the domain variable `x` (at least in some methods; I haven't checked for complete consistency). For example, `rvs()` needs to return both the generated `x` and `sig2`, not just `x`. I think the old PR gh-6739 did this more consistently.

**Comment by tirthasheshpatel** [comment]
It looks like the distribution is an oddball - it doesn't fit our univariate distribution infrastructure or the multivariate distribution infrastructure. @MatteoRaso Thanks for the PR but I'd avoid working on this until further discussion on #6528.

To summarize (from #6739 and #6528), here's where we stand on the issue:

- From https://github.com/scipy/scipy/pull/6739#issuecomment-261706648: Julia's [`ConjugatePriors.jl`](https://github.com/JuliaStats/ConjugatePriors.jl) package considers both `x` and `sig2` as random variates while R's [`PIGShift`](https://cran.r-project.org/web/packages/PIGShift/PIGShift.pdf) package considers only `x` as the random variate. Should SciPy follow the former or the latter convention?
- From https://github.com/scipy/scipy/pull/6739#issuecomment-344051109: Would the implementation of the distribution be useful? The marginal distributions for `x` and `sig2` are already implemented in SciPy and it's easy to compute the full distribution using those.
- From https://github.com/scipy/scipy/pull/6739#issuecomment-344051109: The CDF on Wikipedia seems incorrect. Probably best to avoid implementing it before confirming the closed form is correct.

To start, I am leaning more towards considering this a multivariate distribution with `x` and `sig2` themselves being univariate random variates. We can iterate over it to allow multivariate `sig2`. As far as the usefulness of the distribution is concerned, I think it has gotten more user requests and attention than most other distributions. So, usefulness seems justified. But it would be nice to get some more opinions on these points.

I think that covers the major points discussed on the issue and on the PR. Feel free to add to the above list in the original issue (#6528) if I missed anything. I am closing this right now since there are also some conflicts with the main branch. We can get back once we have enough opinions on the points above.

**Pull request closed without merging**
