### PR TITLE
ENH: support non-float input in stats.chisquare

### PR DESCRIPTION
**Pull request by kaushik-p9**
f_obs and f_exp now support unsigned and large values in chisquare

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
Thanks, @kaushik-p9.  It is a simple change, but it still needs unit tests.

The relevant test file is scipy/stats/tests/test_stats.py.  Since the bug only effects the function `chisquare`, we don't have to add tests for the more general `power_divergence` function.  I suggest adding a function like this just before the test function `test_chisquare_masked_arrays`:

```
@pytest.mark.parametrize("n, dtype", [(200, np.uint8), (1000000, np.int32)])
def test_chiquare_data_types(n, dtype):
    # Regression test for gh-10159.
    obs = np.array([n, 0], dtype=dtype)
    exp = np.array([n // 2, n // 2], dtype=dtype)
    stat, p = stats.chisquare(obs, exp)
    assert_allclose(stat, n, rtol=1e-13)
```

That will test the two failure modes that I described in https://github.com/scipy/scipy/issues/10159.

The commit message should be updated to follow our conventions.  In this case, that means change the commit message to "BUG: stats: [your description here]".   You can also add another line that says  "Closes gh-10159".  That will trigger github to automatically close gh-10159 when the pull request is merged.

**Comment by WarrenWeckesser** [comment]
@kaushik-p9, will you have time to add a unit test and finish up this pull request?

**Comment by pharshalp** [comment]
@kaushik-p9 if you don't have time, I can take this over if it is ok with you.

**Comment by rgommers** [comment]
continued in gh-11097, so closing. thanks all

**Pull request closed without merging**
