### PR TITLE
BUG: Accept anything np.dtype can handle for a dtype in sparse.random

### PR DESCRIPTION
**Pull request by ewmoore**
Fix a tiny irritation.

### CODE REVIEW

**Comment by larsmans** [comment]
LGTM. As a side effect, this also one produce float16 random matrices (although conversion from COO to CSR casts those into float32s).

**Comment by ewmoore** [comment]
Ah good point about float16.  I guess I can change it to `if dtype.char not in 'fdg':`

**Comment by ewmoore** [comment]
Updated.

**Comment by larsmans** [comment]
Merged, thank you!

**Pull request merged**
