### PR TITLE
CI: fix temporary wrong brew version from GitHub

### LINKED ISSUE #13850: CI: Homebrew is failing due to bintray
Homebrew is transitioning from Bintray to github. Currently there is a maintenance and all CI will fail.

Following this discussion: https://github.com/Homebrew/discussions/discussions/691#discussioncomment-600559, the way to fix it would be to set the Homebrew action instead of relying on the latest image.

cc @rgommers Shall I/someone change this?

### PR DESCRIPTION
**Pull request by tupui**
Closes #13850

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
Seems ok based on the discussion over at homebrew; there are a few typos in the comment that was added here but the change does get CI passing again with MacOS jobs <= 30 minute run times.

**Comment by tylerjereddy** [comment]
One more comment--the feature branch you use here was pushed to the main repo instead of your fork--probably best to avoid that.

**Comment by tylerjereddy** [comment]
thanks @tupui

**Comment by tupui** [comment]
> One more comment--the feature branch you use here was pushed to the main repo instead of your fork--probably best to avoid that.

Sorry about that and the typo. I did this on my phone in a hurry to fix the issue 🙇‍♂️

**Pull request merged**
