### PR TITLE
TST: ndimage: fix test skip typo

### PR DESCRIPTION
**Pull request by j-bowhay**
https://github.com/scipy/scipy/pull/22130#discussion_r1894348309

### CODE REVIEW

**Review by lucascolley — CHANGES_REQUESTED** [review]
I think the correct change here is just to `exceptions=["cupy"]`, leaving the CuPy xfail alone - right @crusaderky ?

**Comment by j-bowhay** [comment]
> I think the correct change here is just to `exceptions=["cupy"]`, leaving the CuPy xfail alone - right @crusaderky ?

I wasn't entirely sure either, this seemed consistent with other tests such as
```
    @skip_xp_backends(
        np_only=True, reason='inplace out= arguments are numpy-specific'
    )
    def test_binary_erosion28(self, xp):
```

**Review by ev-br — APPROVED** [review]
Thanks Jake

**Comment by lucascolley** [comment]
https://github.com/scipy/scipy/pull/22130#discussion_r1896807930

**Pull request merged**
