### PR TITLE
MAINT: interpolate: A bit of clean up in interpolate/src/_interpolate.cpp

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by ev-br** [comment]
Test failure is unrelated, merging. Thanks Warren.

**Comment by ev-br** [comment]
I actually wonder what these functions are. They seem to be tested, but not documented, are not used anywhere in scipy, and I wonder if they are actually used in the wild. 

Looking through the git logs does not bring much: `src/_interpolate.cpp` was added by Travis in 2008 (d107863f9440c874c0b2a07cae6753dd366d48af) and have only received maintenance changes since then. Functionality mostly duplicates what is available via `np.interp` and `interpolate1d`. All in all it looks like an unfinished part of something larger, long since forgotten. Maybe it's time to deprecate it? OTOH, there's not much maintenance work to just keep it indefinitely.

**Comment by pv** [comment]
I would deprecate and remove them, as it indeed looks like bits and 
pieces --- it's undocumented and "relatively new addition" so probably 
not that widely used.

**Comment by ev-br** [comment]
PR to deprecate it: https://github.com/scipy/scipy/pull/7187
I'll ask on the mailing list, too.

**Comment by WarrenWeckesser** [comment]
Thanks Evgeni.   I didn't look beyond the warnings that I saw during the build.

**Pull request merged**
