### PR TITLE
ENH: Add matrix normal distribution to stats

### PR DESCRIPTION
**Pull request by drpeteb**
I wrote a scipy-compatible implementation of the matrix normal distribution for a recent project. Would this be a good addition for the stats module?
### Some Notes
- The matrix normal distribution is useful for inference or sampling tasks involving unknown matrices. See e.g http://users.isy.liu.se/en/rt/schon/Publications/WillsSLN2012.pdf
- The matrix normal distribution generalises the multivariate normal distribution (because a vector is an `m x 1` matrix). However, separate implementations are appropriate because the vector case can be done more efficiently, and because the array dimensions would be different.
- Matrix normal sampling and pdf evaluation can be done by vectorising the `m x n` matrix into a `mn` vector and just using the vector distribution, and so implemented with a wrapper around the `multivariate_normal` classes. However, this is really inefficient, requiring us to handle a `mn x mn` covariance matrix. But it's useful for testing.
- Singular matrix normal distributions are well defined, but not supported here. They suffer from the same stability issues as the multivariate normal distribution. See https://github.com/scipy/scipy/issues/5286

### CODE REVIEW

**Comment by argriffing** [comment]
The idea looks good to me and in scope for scipy, in my opinion. I see there is a wikipedia page https://en.wikipedia.org/wiki/Matrix_normal_distribution.

**Comment by rgommers** [comment]
Looks like a good addition to me as well. @drpeteb could you propose this addition on the scipy-dev mailing list (that's where we decide on adding new features) so interested people can comment?

**Comment by josef-pkt** [comment]
Looks like a fine addition to me also.
I tried a bit to read through the code, but realized that I never tried to figure out the entire multivariate distribution implementation.

I never used matrixvariate normal, but in econometrics we have a similar structure with the multivariate normal and kronecker covariance structure.

Based on the Wikipedia article, I think adding a `transform_affine` would be useful for affine transformation of the matrixvariate normal distribution that returns also a distribution.

**Comment by ev-br** [comment]
A superficial comment: it'd make sense to clearly document the behavior w.r.t. singular matrices, also the relation to the multivariate normal.

**Comment by ev-br** [comment]
Merging it, thank you @drpeteb!
Doc improvements can be done in a separate PR.

**Pull request merged**
