### PR TITLE
DEP: deprecate ``stats.f_value*`` and ``mstats.f_value*`` functions.

### LINKED ISSUE #650: Statistics Review: f_value_wilks_lambda (Trac #123)
_Original ticket http://projects.scipy.org/scipy/ticket/123 on 2006-04-02 by @rkern, assigned to @rkern._

The function `f_value_wilks_lambda` in file source:trunk/Lib/stats/stats.py needs review.

Please look over the StatisticsReview guidelines and add your comments below.

### LINKED ISSUE #660: Statistics Review: f_value (Trac #133)
_Original ticket http://projects.scipy.org/scipy/ticket/133 on 2006-04-02 by @rkern, assigned to @rkern._

The function `f_value` in file source:trunk/Lib/stats/stats.py needs review.

Please look over the StatisticsReview guidelines and add your comments below.

### LINKED ISSUE #662: Statistics Review: f_value_multivariate (Trac #135)
_Original ticket http://projects.scipy.org/scipy/ticket/135 on 2006-04-02 by @rkern, assigned to @rkern._

The function `f_value_multivariate` in file source:trunk/Lib/stats/stats.py needs review.

Please look over the StatisticsReview guidelines and add your comments below.

### PR DESCRIPTION
**Pull request by aeklant**
closes gh-650; closes gh-660; closes gh-662

### CODE REVIEW

**Comment by aeklant** [comment]
I couldn't find any test coverage (direct or indirect) so no warnings were silenced.

**Comment by rgommers** [comment]
LGTM. Let's give this at least 3-4 more days before hitting the green button.

**Comment by aeklant** [comment]
Are the errors shown in TravisCI normal? I am seeing more and more of the "exceeds 50m time limit" error (although it might just be because I'm doing more PRs) but there is also this:

```
$ tools/validate_runtests_log.py $TESTMODE < runtests.log Traceback (most recent call last):
File "tools/validate_runtests_log.py", line 59, in <module>
    if found_it:
NameError: name 'found_it' is not defined
```

which seems like something internal, not related to the PR.

**Comment by ev-br** [comment]
Py 3.2 build failed somewhere in building scipy, I've restarted it. The full test run regularly exceeds 50 min cutoff :-(.

**Comment by rgommers** [comment]
Mailing list thread: http://article.gmane.org/gmane.comp.python.scientific.devel/19793

No objections after 7 days, so hitting the green button.

**Pull request merged**
