### PR TITLE
Fix tolerance specification in sparse.linalg iterative solvers

### LINKED ISSUE #7624: allow setting both absolute and relative tolerance of sparse iterative solvers
Currently a single tolerance (`tol` argument) is used, which is impractical, when using an iterative solver as a preconditioner. In that case it is desirable to set a relative tolerance to some not-so-small value (e.g. 1e-2), without caring about the absolute tolerance. The current behaviour prevents that, as something like setting `tol=1e-2` often leads to absolute convergence in iteration zero of the preconditioner, hence no preconditioning done at all.

This behaviour breaks the IMHO very good `lgmres` solver. For example, the following happens when using `lgmres` with `cg` (`tol=1e-2`) as a preconditioner for symmetric positive definite diagonal blocks:

```
<snip>
sfepy: cg-s: iteration 1
sfepy: cg-s: iteration 2
sfepy: cg-s: iteration 3
sfepy: cg-s: iteration 4
sfepy: cg-s: iteration 5
sfepy: cg-s: iteration 6
sfepy: cg-s: cg convergence: 0 (successful exit)
rhs norm: 8.751133e-02, solution norm: 4.484927e+00
sfepy: iterative-s: iteration 4: |Ax-b| = 2.323006e-03
sfepy: cg-s: iteration 1
sfepy: cg-s: cg convergence: 0 (successful exit)
rhs norm: 4.101975e-04, solution norm: 0.000000e+00
sfepy: cg-s: iteration 1
sfepy: cg-s: cg convergence: 0 (successful exit)
rhs norm: 2.286502e-03, solution norm: 0.000000e+00
Traceback (most recent call last):
<snip>
  File "....local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/lgmres.py", line 145, in lgmres
    "|v| ~ %.1g, |M v| = 0" % rnorm)
RuntimeError: Preconditioner returned a zero vector; |v| ~ 0.002, |M v| = 0
```

This happened because the rhs norm was 2.286502e-03 < 1e-2 (see the line above the traceback), so no solution was attempted.

So I propose having both `rtol` and `atol` arguments (or allow `tol` to be a tuple), and possibly adding a `tol_mode` argument - either 'and' or 'or', defaulting to 'or', that tell whether both tolerances have to be met ('and' mode) or a single one is enough.

I can make a PR implementing this for `lgmres`, as it is written in Python. I am not sure if I am brave enough to dive into the legacy fortran of the other solvers.

### PR DESCRIPTION
**Pull request by pv**
The sparse.linalg iterative solvers treat the `tol` parameter in an inconsistent way. This PR rectifies the situation preserving backward compatibility, and adds deprecation warnings preparing the way for more sane defaults in future Scipy releases.

The fortran-based solvers have the `'legacy'` behavior: `tol` is considered as the tolerance relative to norm(b), and also as the absolute tolerance for the initial residual (but not subsequent ones!). For `lgmres`, `gcrotmk`, the legacy behavior is to consider `tol` both as an absolute and relative tolerance. These legacy behaviors are wonky, and for most cases not what is wanted. The usually needed interpretation for `tol` would be the relative tolerance only.

This PR makes it possible to specify both relative and absolute tolerances, by adding an `atol=` keyword argument. If only `tol=` is specified, we emit a DeprecationWarning and follow the legacy behavior. In the future, we may want to change the default behavior to `atol=0`.

Moreover, this PR fixes the behavior of the tolerance parameters when there is left-preconditioning. Previously, `gmres` applied these inconsistently in the stop condition and inner loop stop condition. The new behavior is to consider the tolerances to apply to the *non-preconditioned* residual.

The inner loop still only knows about the preconditioned residual, so an adaptive tolerance control mechanism is added (also to `lgmres`). This kicks in only when there is a mismatch between the two conditions (i.e. possible with preconditioning, or when running into rounding error).

I also had to adjust the default tolerances ARPACK uses in iterative inversion --- it wants to run GMRES at tol ~ eps, but it's not necessarily possible to achieve such relative tolerance due to rounding error. So bump the tolerance upwards.

There may be changes in behavior when running at very small tolerances where the solver runs into rounding error, or when dealing with preconditioned problems. Previously, these solvers could exit when the required tolerance was not satisfied, and with the stricter checking they may now exit signaling non-convergence in such cases. However, this is my opinion bug.

Closes gh-7624

@rc: ping

### CODE REVIEW

**Comment by pv** [comment]
Not ready yet --- forgot to check with the left-preconditioning...

**Comment by pv** [comment]
ok, should be ready to go now

**Comment by pv** [comment]
An arguable point here is whether gmres should simply check only the preconditioned residual for termination (the other solvers don't) rather than trying to satisfy the requirement for the unpreconditioned result. In this case, only relative tolerance is useful, however.

**Comment by rgommers** [comment]
This should go into 1.1.x I think. @rc if you have time to review, that would be great. If not, I'll give it a go

**Review by rc — APPROVED** [review]

**Comment by rc** [comment]
I have checked the new code with my preconditioning problem (see #7624) and it work like a charm, thanks! I have also looked at the changes, and they seems fine, although I did not analyze _every_ line.

+1 for merging.

**Comment by person142** [comment]
> it works like a charm

Great! I also looked through the changes a while back and was happy, so it looks like we're at merge.

**Comment by rgommers** [comment]
Awesome!

**Pull request merged**
