### PR TITLE
MAINT: add spatial.transform to refguide check; complete some __all__ dicts

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by ev-br** [comment]
Refguide-check errors look real.

**Comment by rgommers** [comment]
Hmm, very odd. Passes for me locally. And arrays have different shapes, so it's not just a printing thing.

**Comment by rgommers** [comment]
@adbugger do these failures make sense to you?

```
=======================
scipy.spatial.transform
=======================

scipy.spatial.transform.Rotation
--------------------------------

File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 345, in Rotation
Failed example:
    r2.as_euler('zyx', degrees=True)
Expected:
    array([[-90.,   0.,   0.],
           [-45.,   0.,   0.]])
Got:
    array([[-90.        ,   0.        ,   0.        ],
           [  0.        , -45.        ,   0.        ],
           [-68.94827556, -10.1820674 , -63.89986122]])


File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 1234, in Rotation.apply
Failed example:
    r.as_dcm()
Expected:
    array([[[ 7.07106781e-01, -7.07106781e-01,  0.00000000e+00],
            [ 7.07106781e-01,  7.07106781e-01,  0.00000000e+00],
            [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],
Got:
    array([[[ 7.07106781e-01, -7.07106781e-01,  0.00000000e+00],
            [ 7.07106781e-01,  7.07106781e-01,  0.00000000e+00],
            [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]],
    <BLANKLINE>
           [[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
            [ 0.00000000e+00,  2.22044605e-16, -1.00000000e+00],
            [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16]]])


File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 532, in Rotation.from_dcm
Failed example:
    dcm
Expected:
    array([[-0.38461538, -0.92307692,  0.        ],
           [ 0.92307692, -0.38461538,  0.        ],
           [ 0.        ,  0.        ,  1.        ]])
Got:
    array([[[ 0., -1.,  0.],
            [ 1.,  0.,  0.],
            [ 0.,  0.,  1.]],
    <BLANKLINE>
           [[ 1.,  0.,  0.],
            [ 0.,  0., -1.],
            [ 0.,  1.,  0.]]])


File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 1492, in Rotation.random
Failed example:
    R.random().as_euler('zxy', degrees=True)
Expected:
    array([ 94.9508862 ,  35.38168732, 148.80576945])
Got:
    array([-86.43844753,  10.09686435, 162.61329516])


File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 1497, in Rotation.random
Failed example:
    R.random(5).as_euler('zxy', degrees=True)
Expected:
    array([[  97.65185987,  -30.18238967,   48.56690829],
           [  27.39232994,  -58.77440039, -137.96008356],
           [ 139.4463782 ,   16.19756587,  -48.6823144 ],
           [ -25.35339309,    8.00660013,  -39.14435328],
           [  63.83774224,  -34.47187095,  -47.75580405]])
Got:
    array([[-21.94085704, -57.56623127, 172.28335157],
           [126.87173763, -38.69334179,  97.62677909],
           [115.11742511,  -4.36836782, 152.2384415 ],
           [-39.52760088, -39.07273569,  68.71741342],
           [-23.09502003,  49.16857495, -13.08030382]])

scipy.spatial.transform.Slerp
-----------------------------

File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 1560, in Slerp
Failed example:
    key_rots.as_euler('xyz', degrees=True)
Expected:
    array([[154.88487585, -10.37207323, 116.95075648],
           [ 68.5886485 ,  34.23557992,  28.64650139],
           [ 95.2872057 , -18.74934318, 125.606599  ],
           [142.26836558,  17.4416704 , 121.67989988],
           [141.86531587, -15.10753215, 102.01807079]])
Got:
    array([[105.09432624, -47.8346124 ,  55.69510568],
           [103.40979889,  36.90473947,  76.30077614],
           [165.9820184 , -11.25921402,  91.99129195],
           [138.18825266, -42.56214668,  27.4859996 ],
           [117.67807471,  35.48262514,  88.09833733]])


File "build/testenv/lib/python3.5/site-packages/scipy/spatial/transform/rotation.py", line 1570, in Slerp
Failed example:
    interp_rots.as_euler('xyz', degrees=True)
Expected:
    array([[154.88487585, -10.37207323, 116.95075648],
           [124.8757228 ,  27.88355379,  85.77711413],
           [142.99736719,  10.71021057, 104.39685307],
           [ 68.5886485 ,  34.23557992,  28.64650139],
           [ 94.83106037,  13.07930201,  82.57369554],
           [ 95.2872057 , -18.74934318, 125.606599  ],
           [130.49684909,   8.28607205, 119.80428161],
           [142.26836558,  17.4416704 , 121.67989988],
           [141.096957  ,   9.34664151, 116.61979789],
           [140.67373323,  -2.08694364, 109.87862761],
           [141.86531587, -15.10753215, 102.01807079]])
Got:
    array([[105.09432624, -47.8346124 ,  55.69510568],
           [100.20005858,  -5.51542236,  66.71071404],
           [101.26447336, -26.76907012,  62.23299115],
           [103.40979889,  36.90473947,  76.30077614],
           [138.10060263,  14.74446527,  91.59549712],
           [165.9820184 , -11.25921402,  91.99129195],
           [141.70736221, -32.32012971,  44.00662955],
           [138.18825266, -42.56214668,  27.4859996 ],
           [123.47251464, -25.61581085,  48.1612411 ],
           [115.33217301,   2.36790127,  67.26784245],
           [117.67807471,  35.48262514,  88.09833733]])


ERROR: refguide or doctests have errors
```

**Comment by adbugger** [comment]
The first error is due to a typo in the docstring. [This](https://github.com/scipy/scipy/blob/master/scipy/spatial/transform/rotation.py#L344) line should read `r2 = r1.inv()` instead of `r.inv()`.

**Comment by rgommers** [comment]
Thanks @adbugger! For the second one, this is probably the best option: 

    >>> r.as_dcm()  #doctest: +SKIP

The alternatives are to add an explicit `<BLANKLINE>` in the array output (very ugly), or to just not do the doctest at all by adding it to [this list](https://github.com/scipy/scipy/blob/master/tools/refguide_check.py#L109) of skipped functions.

**Comment by pv** [comment]
You can just omit the blank lines --- the checker should be ok with that, ie.
```
    array([[[ 0., -1.,  0.],
            [ 1.,  0.,  0.],
            [ 0.,  0.,  1.]],
           [[ 1.,  0.,  0.],
            [ 0.,  0., -1.],
            [ 0.,  1.,  0.]]])
```

**Comment by pv** [comment]
Thanks, tests pass so merged.

**Pull request merged**
