### PR TITLE
ENH: sparse randn

### PR DESCRIPTION
**Pull request by argriffing**
This PR adds a function to sample sparse matrices whose nonzero entries have normally distributed values, alongside the existing function that samples uniformly distributed values on the unit interval.  Of course if many more of these functions are to be added, the code should be re-organized.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Why not add `function_name` as a kwarg to the existing `rand` function and default it to `'rand'`?

That would let the user choose from any of the available distributions without having to add new public methods for each one.

**Comment by argriffing** [comment]
> Why not add `function_name` as a kwarg to the existing `rand` function and default it to `'rand'`?

The reason was for consistency with `numpy.random` where [`np.random.rand`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html) specifically means uniform random numbers over the unit interval, and other sampling functions are like `np.random.randn` as opposed to using notation like `np.random.rand(function_name='randn')`.

> That would let the user choose from any of the available distributions without having to add new public methods for each one.

I was not planning to add more than this second distribution.  But if we want to immediately generalize to allow all distributions available from `numpy.random.*` then I agree that the implementation in this PR is not ideal and should not be merged.  To me, the most intuitive interface would be something like `scipy.sparse.random.*` (in analogy to `np.random.*`) instead of either `scipy.sparse.construct.*` or `scipy.sparse.construct.rand(function_name='*')`.

**Comment by perimosocordiae** [comment]
I'm conflicted. One on hand, I agree that matching APIs with numpy will make things easier for users.
On the other, a `scipy.sparse.random` module seems overkill for what would essentially be one function that performs `self.data[:] = np.random.*(self.data.shape)` and a bunch of aliases to that function.

**Comment by ev-br** [comment]
Maybe `sparse.construct.random(m, n, density=0.01, format="coo", dtype=None, random_function=np.random.rand)` where `random_function` is supposed to be a method of a (possibly custom) instance of `np.random.RandomState`. 

This looks clean and simple to me, avoids adding more kwargs to existing functions, gives a user full flexibility for using/creating their own RandomState instances, and only requires minimal changes to the `_random` function from this PR.

**Comment by argriffing** [comment]
@ev-br I had been considering something like that, but the random construction uses not just random data samples but also random permutations and random integer choices.  So your `sparse.construct.random` call signature would not be sufficient as written, but maybe it could be modified somehow?

**Comment by ev-br** [comment]
So your worry is that a user does `sparse.construct.random(...., random_function=np.random.shuffle)` and then gets surprised by the result, correct?

IMO this should be documented, maybe even some clearly wrong functions could be blacklisted, but in general I'd say <s>garbage in garbage out</s> it's one more reason to keep this in `sparse.construct` namespace rather than top-level `sparse` namespace.

**Comment by argriffing** [comment]
> So your worry is that a user does `sparse.construct.random(...., random_function=np.random.shuffle)` and then gets surprised by the result, correct?

No, sorry I was not clear.  The random sparse matrix construction function does essentially two  separate things.  The first thing is to make a random sparsity pattern.  This step uses either random permutation or random integer choice depending on some hardcoded threshold, and it uses the random state object provided by the user.  I am not suggesting to change this part or to allow any extra user input for this step.  The second thing that the random sparse matrix construction does is to sample some random data for the nonzero entries.  Currently in scipy this second step is hardcoded to sample uniformly from the unit interval, but I would like to add some small amount of flexibility here (as your suggestion also adds).  A complication that causes your suggestion to not quite work as written (but which is fixable with some small modification) is that under your suggestion the first of the two steps no longer has access to a user-provided random state object.

**Comment by ev-br** [comment]
I see! 
Would using `__self__` work? 
(googling shows http://stackoverflow.com/questions/4679592/how-to-find-instance-of-a-bound-method-in-python)

**Comment by argriffing** [comment]
> Would using `__self__` work?

Yes it looks like I was wrong, and that technically this would let you use the function signature you suggested.  `__self__` doesn't seem to have been used at all in scipy, except in the `six` library which uses it to provide `get_function_self` which itself is not used in scipy.

**Comment by josef-pkt** [comment]
If you have a `random_function` keyword argument, then this might be just a callable and not a RandomState method. For example it could be a partial function or a lambda function.

How do you handle arguments for the random number generator, shape, loc, scale arguments?
"I want Poisson with mean 25."

**Comment by ev-br** [comment]
Ok, indeed, I was wrong. One parameter is not enough, one really needs two. Then I guess my suggestion is to basically,

* leave `rand` be for backwards compat
* have `_random` function from this PR accept a callable instead of a string name, for forward compatibility, and
* make `_random` from this PR public

I hate to be the one who derails the discussion so I'll stop bikeshedding in this PR :-).

**Comment by argriffing** [comment]
@ev-br Thanks, I've made some changes according to my interpretation of your suggestions and I'm waiting for TravisCI.  I think these discussions about scope, or discussions about how to design the API to not paint itself into a corner, are less trivial than what is usually meant by bikeshedding!

**Comment by ev-br** [comment]
Bikeshedding or not, a docstring example or two of using these two parameters could be useful, I guess, to show usage of both a method of random_state object and a custom callable (eg, Josef's example of Poisson with mean 25 or something like that). But this might be a separate doc-only PR as well. In any case, LGTM.

**Comment by perimosocordiae** [comment]
The latest changes look good to me. I can see myself passing `np.ones` as the data source, which would be quite convenient for some of my use cases. 

Would this put the existing `rand` function on the deprecation path?

**Comment by argriffing** [comment]
> a docstring example or two of using these two parameters could be useful, I guess, to show usage of both a method of random_state object and a custom callable (eg, Josef's example of Poisson with mean 25 or something like that).

Added in the most recent commit.  The example I chose might be too 'cute'...

> I can see myself passing np.ones as the data source, which would be quite convenient for some of my use cases.

Good point!  I could see using this as well.

> Would this put the existing rand function on the deprecation path?

I don't really have an opinion about this... I still kind of like the idea of copying the numpy random interface, but I see that I'm in the minority.

**Comment by ev-br** [comment]
> I still kind of like the idea of copying the numpy 
> random interface, but I see that I'm in the 
> minority.

I thought the current version is quite close, how would you do it?

**Comment by argriffing** [comment]
> I thought the current version is quite close, how would you do it?

I think the most recent version in the PR is OK.  In my comment that you were responding to, I was just referring to the hypothetical idea of `scipy.sparse.random.*`.  In that hypothetical scenario `scipy.sparse.random.rand` would be a thing, and it would not be deprecated.  But the answer to @perimosocordiae's question is less clear to me in the less-hypothetical scenario currently implemented in this PR.  Just to be clear, I'm not trying to make an argument for `scipy.sparse.random.*`.

**Comment by argriffing** [comment]
just as a reminder to myself, I think that
```python
j = np.floor(ind * 1. / m).astype(tp)
i = (ind - j * m).astype(tp)
```
can be replaced by
```python
j, i = np.unravel_index(ind, (n, m))
```
after this PR has been settled.

**Comment by ev-br** [comment]
I don't have an opinion on relative merits of sparse.random vs sparse.construct.random, so this PR looks good to me as is. Maybe this discussion happen in gh-4687?

**Comment by argriffing** [comment]
OK thanks, I will merge it!

**Comment by ev-br** [comment]
Is https://github.com/scipy/scipy/issues/4557 relevant for the new `random`?

**Comment by argriffing** [comment]
@ev-br I'm not sure, but thanks for pointing that out.  I'm currently running tests for another PR that could possibly cause even worse problems under exotic sizes of types and pointers, where 'exotic' means anything different from my development environment. (https://github.com/scipy/scipy/pull/4689).

**Pull request merged**
