### PR TITLE
ENH: Do not create a throwaway class at every function call

### PR DESCRIPTION
**Pull request by ales-erjavec**
The namedtuple class creation is expensive and can dominate the
execution time. Move the class creation out of stat functions
into module namespace.

From an example ipython session

```
In [1]: import scipy.stats, numpy.random

In [2]: %%timeit
   ...: scipy.stats.mannwhitneyu(
   ...:     numpy.random.normal(0, size=30),
   ...:     numpy.random.normal(1, size=30),
   ...: )
   ...: 
1000 loops, best of 3: 810 µs per loop
```

before the change, improved to

```
1000 loops, best of 3: 280 µs per loop
```

after

### CODE REVIEW

**Comment by ev-br** [comment]
Ugh. This is a fixed cost, right? So that the relative perf hit decreases with the amount of work done in a function and the size of the input arrays.
There was some discussion as to whether to create them at the module level or within functions (I for one was on the second side).

I actually wonder what are the ℅timeit implications for using `Bunch`es,  https://github.com/scipy/scipy/issues/3665#issuecomment-125678397. This is the direction we probably want to move in.

**Comment by ev-br** [comment]
```
In [33]: %%timeit                                                              
    SkewtestResult = namedtuple('SkewtestResult', ('statistic', 'pvalue'))
s = SkewtestResult(np.nan, np.nan)
   ....: 
1000 loops, best of 3: 1.08 ms per loop

In [34]: %timeit b = Bunch(('statistic' , 'pvalue'), (np.nan, np.nan))
The slowest run took 7.51 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 6.66 µs per loop
```

**Comment by pv** [comment]
The actual `s = SkewtestResult(np.nan, np.nan)` is however probably around 1µs.

**Comment by ev-br** [comment]
This PR fixes a performance regression introduced in scipy 0.16. Code-wise it looks good to me.

OTOH, once these namedtuples are replaced by Bunches, this would likely also fix the same perf regression.

Since scipy 0.16.1 is brewing, I'd think that the best course of action would be to backport this PR to the maintenance/0.16.x branch; and change namedtuples to Bunches in master instead (i.e., for scipy 0.17). 

On backporting, I'd defer to @rgommers. On Bunches, would you be interested in working on this @ales-erjavec?

**Comment by ales-erjavec** [comment]
> There was some discussion as to whether to create them at the module level or within functions

Was the reason for choosing to create them in functions in order to 'hide' the implementation?

It might be better to prefix the module level attributes with an underscore e.g.
```
_SkewtestResult = namedtuple('SkewtestResult', ('statistic', 'pvalue'))
```
The namedtuples are not listed in ``__all__`` but still if they will eventually be replaced, it might be better
to hide them some more.

Also it seems, I missed quite a lot of uses of this pattern in scipy/stats/morestats.py mstats_basic.py, ...

**Comment by ev-br** [comment]
> Was the reason for choosing to create them in functions in order to 'hide' the implementation?

Yes, the reason was mostly hiding them, and we did not time the namedtuple creation (mea culpa). 
Here's the PR which added them: https://github.com/scipy/scipy/pull/4709. It has the discussion about where to place them.

With regards to underscoring the names, I'm still inclined not to. My reasoning from the PR linked above still stands (even though I admit being mistaken on several counts): if a user interacts with something, this something is not private even if the class name of this something is not a part of the API. (This is a slight preference, and I don't think we should spend too much on this, so if there are strong opinions, I'm fine either way).

At this point in time however, I further think it's not worth it to change the names. For a bugfix to be considered to 0.16.1 (again, the decision is up to the RM) the fix should be minimal, so best just move the definitions to the module level and that's it.

**Comment by ev-br** [comment]
I'll gently ping @rgommers on this one re backporting this.

**Comment by rgommers** [comment]
thanks @ev-br, forgot about this one. Still just in time - I just finished the 0.16.1 commit but haven't pushed anything yet. Note that the 2 things I check before a release is if anything is under the 0.16.1 milestone or the "backport-candidate" label. Feel free to add anything you like to those - I can always remove it again.

**Comment by rgommers** [comment]
I agree with @ev-br that leaving the names without underscores is fine.

**Comment by rgommers** [comment]
As @ales-erjavec remarked, this PR still misses quite a few places where ``namedtuple`` is used:

    ./_binned_statistic.py:
        7 : from collections import namedtuple
      149 :     BinnedStatisticResult = namedtuple('BinnedStatisticResult',
      241 :     BinnedStatistic2dResult = namedtuple('BinnedStatistic2dResult',
      452 :     BinnedStatisticddResult = namedtuple('BinnedStatisticddResult',
    ./morestats.py:
        9 : from collections import namedtuple
       87 :     Mean = namedtuple('Mean', ('statistic', 'minmax'))
       88 :     Variance = namedtuple('Variance', ('statistic', 'minmax'))
       89 :     Std_dev = namedtuple('Std_dev', ('statistic', 'minmax'))
     1210 :     AndersonResult = namedtuple('AndersonResult', ('statistic',
     1434 :     Anderson_ksampResult = namedtuple('Anderson_ksampResult',
     1485 :     AnsariResult = namedtuple('AnsariResult', ('statistic', 'pvalue'))
     1580 :     BartlettResult = namedtuple('BartlettResult', ('statistic', 'pvalue'))
     1692 :     LeveneResult = namedtuple('LeveneResult', ('statistic', 'pvalue'))
     2087 :     WilcoxonResult = namedtuple('WilcoxonResult', ('statistic', 'pvalue'))
    ./mstats_basic.py:
       47 : from collections import namedtuple
      288 :     ModeResult = namedtuple('ModeResult', ('mode', 'count'))
      451 :     SpearmanrResult = namedtuple('SpearmanrResult', ('correlation', 'pvalue'))
      487 :     KendalltauResult = namedtuple('KendalltauResult', ('correlation', 'pvalue'))
      623 :     PointbiserialrResult = namedtuple('PointbiserialrResult', ('correlation',
      666 :     LinregressResult = namedtuple('LinregressResult', ('slope', 'intercept',
      718 :     Ttest_1sampResult = namedtuple('Ttest_1sampResult', ('statistic', 'pvalue'))
      727 :     Ttest_indResult = namedtuple('Ttest_indResult', ('statistic', 'pvalue'))
      749 :     Ttest_relResult = namedtuple('Ttest_relResult', ('statistic', 'pvalue'))
      817 :     MannwhitneyuResult = namedtuple('MannwhitneyuResult', ('statistic',
      839 :     KruskalResult = namedtuple('KruskalResult', ('statistic', 'pvalue'))
     1598 :     DescribeResult = namedtuple('DescribeResult', ('nobs', 'minmax', 'mean',
     1655 :     SkewtestResult = namedtuple('SkewtestResult', ('statistic', 'pvalue'))
     1690 :     KurtosistestResult = namedtuple('KurtosistestResult', ('statistic',
     1702 :     NormaltestResult = namedtuple('NormaltestResult', ('statistic', 'pvalue'))
     2039 :     F_onewayResult = namedtuple('F_onewayResult', ('statistic', 'pvalue'))
     2104 :     FriedmanchisquareResult = namedtuple('FriedmanchisquareResult',

I'll merge this and go fix the rest right now, so it can still go into 0.16.1.

**Comment by rgommers** [comment]
follow-up in gh-5414

**Pull request merged**
