### PR TITLE
BUG: special: Restore missing line of code in the function cchg().

### LINKED ISSUE #20797: BUG: special.hyp1f1: broken for complex argument
### Describe your issue.

Since 1.10, the `scipy.special.hyp1f1` is computed by Boost. The change was introduced by #17302. However, the computations by Boost are wrong. Take:

```python
scipy.special.hyp1f1(-0.25, 0.5, 1+2j)
```

I have tested it with SciPy 1.8.0 and 1.13.1. The results are:

- 1.8.0: `(1.1814553180903438-1.2792130661292982j)`
- 1.13.1: `(1+0j)`

The latter one is obviously incorrect answer! Wolfram Alpha shows 1.18146 - 1.2792 _i_.

Please revert #17302!

### Reproducing Code Example

```python
import scipy.special

print(scipy.special.hyp1f1(-0.25, 0.5, 1+2j))
```

### Error message

```shell
(1+0j)
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/intel/oneapi/mkl/latest/include
    lib directory: /opt/intel/oneapi/mkl/latest/lib/intel64
    name: mkl-dynamic-lp64-seq
    openblas configuration: unknown
    pc file directory: /opt/intel/oneapi/mkl/2023.2.0/lib/pkgconfig
    version: '2023.2'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/intel/oneapi/mkl/latest/include
    lib directory: /opt/intel/oneapi/mkl/latest/lib/intel64
    name: mkl-dynamic-lp64-seq
    openblas configuration: unknown
    pc file directory: /opt/intel/oneapi/mkl/2023.2.0/lib/pkgconfig
    version: '2023.2'
  pybind11:
    detection method: pkgconfig
    include directory: /usr/lib/pkgconfig/../..//include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -march=x86-64, -mtune=generic, -O2, -pipe, -fno-plt, -fexceptions, -Wp,-D_FORTIFY_SOURCE=2,
      -Wformat, -Werror=format-security, -fstack-clash-protection, -fcf-protection
    commands: ccache, cc
    linker: ld.bfd
    linker args: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now, -march=x86-64,
      -mtune=generic, -O2, -pipe, -fno-plt, -fexceptions, -Wp,-D_FORTIFY_SOURCE=2,
      -Wformat, -Werror=format-security, -fstack-clash-protection, -fcf-protection
    name: gcc
    version: 13.2.1
  c++:
    args: -march=x86-64, -mtune=generic, -O2, -pipe, -fno-plt, -fexceptions, -Wp,-D_FORTIFY_SOURCE=2,
      -Wformat, -Werror=format-security, -fstack-clash-protection, -fcf-protection,
      -Wp,-D_GLIBCXX_ASSERTIONS
    commands: ccache, c++
    linker: ld.bfd
    linker args: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now, -march=x86-64,
      -mtune=generic, -O2, -pipe, -fno-plt, -fexceptions, -Wp,-D_FORTIFY_SOURCE=2,
      -Wformat, -Werror=format-security, -fstack-clash-protection, -fcf-protection,
      -Wp,-D_GLIBCXX_ASSERTIONS
    name: gcc
    version: 13.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    linker args: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
    name: gcc
    version: 13.2.1
  pythran:
    include directory: ../../../../../../../usr/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /usr/bin/python
  version: '3.12'
```

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
The line appears to have gone missing in the translation from Fortran to C++.

Added new tests, which revealed that hyp1f1 can still be very inaccurate.

Closes gh-20797.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
In the new set of parametrized tests, there are two cases that are commented out.  One of those parameter sets is from an existing test that I moved from `test_specfun.py` to `test_hypergeometric.py`.  The old reference value was very inaccurate.  The new reference value for that case was computed with mpmath and double-checked with Matlab. Even after fixing the missing line, our hyp1f1(0.1, 1, 7-24j) gives only 2-3 digits of precision.  The other commented-out case is a=10, b=250, z=10-15j.  hyp1f1 returns garbage in that case--no digits correct.

I haven't gone over the entire translated code line by line, so I don't know if there are other mistakes hidden in there, but I did grab the original Fortran code, and created a main program to call it with the parameters a=0.1, b=1, z=7-24j:

```
program main

use, intrinsic :: iso_fortran_env, only: sp=>real32, dp=>real64
implicit none

real(dp) :: a, b
complex(dp) :: z, h

a = 0.1D0
b = 1.0D0
z = (7.0D0, -24.0D0)

call cchg(a, b, z, h)

print *, real(h), imag(h)

end program main
```
It prints

```
  -3.7659844658567994        4.9703113598516468     
``` 
and `hyp1f1(a, b, z)` gives almost the same values:

```
In [2]: a = 0.1; b = 1; z = 7.0-24.0j

In [3]: hyp1f1(a, b, z)
Out[3]: (-3.7659844658568047+4.9703113598516495j)
```
The point of that comparison is that I don't think the inaccuracy is because of another mistake in the C++ code.  I suspect it is a limitation of the original algorithm.

So I think we can consider merging this PR to fix the translation mistake, and anyone currently working on `special` might want to start looking for an alternative to the specfun code for `hyp1f1`.  Julia often has pretty high quality libraries that are license-compatible with SciPy, so that might be a place to start looking.

**Comment by ilayn** [comment]
Indeed that '7+24j' value test was me trying to enter different branches of the code and probably I introduced the erroneous missing line and failed to catch it. 

@steppi is overhauling these hypergeometric functions piece by piece hence probably this will be addressed at some point.

But thank you for the quick save regardless. I'll let him push the button

**Review by steppi — APPROVED** [review]
Looks good. Thanks @WarrenWeckesser. I tried to review the translation pretty carefully, but it looks like this one slipped by. One suggestion about marking those failing cases as `xfail` rather than just commenting them out. I'll look into the second failing case. I know why the first one fails.

**Comment by steppi** [comment]
Thanks @WarrenWeckesser! The test failure was unrelated.

**Pull request merged**
