### PR TITLE
MAINT: backports for SciPy 1.5.4

### PR DESCRIPTION
**Pull request by tylerjereddy**
SciPy `1.5.4` contains some high-priority fixes, including wheels for Python 3.9 and the actual fix for building on XCode 12.

This PR contains a number of backports and an update to the `1.5.4` release notes.

### CODE REVIEW

**Review by rgommers — APPROVED** [review]
LGTM modulo the `lint_diff` failure

**Comment by tylerjereddy** [comment]
I think we may be getting rather `shallow` `git` clones in Travis, because the `lint_diff` command works for this feature branch locally. In this case, I'm pushing in a one-line attempted fix based on the Travis CI docs here and will forward-port if it works.

See: https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth

**Comment by tylerjereddy** [comment]
Ok, here we go finally.. Travis was heavily backed up

**Comment by adamjstewart** [comment]
I can confirm that `maintenance/1.5.x` builds for me on macOS 10.15.7 with Apple Clang 12.0.0 and Python 3.8.6! Thanks for the backport!

**Comment by tylerjereddy** [comment]
Wheel builds have started this evening. I'll see if I can get `1.5.4` out on Nov. 4th or 5th, assuming no further bottlenecks.

**Pull request merged**
