### PR TITLE
CI: ccache for osx Closes #7646

### LINKED ISSUE #7646: Use ccache on travis for OSX.
Now that we have testing for OSX on travis we should aim to use ccache to speed up the build. This issue continues the discussion from #7640.

### PR DESCRIPTION
**Pull request by andyfaff**
Enable ccache for OS X platform on Travis

### CODE REVIEW

**Comment by pv** [comment]
I'm not sure it's working --- if you look at the log (of your previous 
builds with USE_SDIST=1) you see the scipy build is using clang and not 
gcc --- and ccache doesn't seem to be enabled for clang.

**Comment by andyfaff** [comment]
If I use the same setup/softlinking (including softlinking the clang/clang++) on my own computer (apart from using multibuild) I see a 3 fold speedup in build time.

**Comment by pv** [comment]
Did you try the exact same commands locally, i.e., install using 
sdist+pip? Pip builds stuff in some temporary directory (unless told 
otherwise with --build option) with a random name, which may throw ccache.

**Comment by andyfaff** [comment]
No. I was using `python setup.py build` locally.

**Comment by pv** [comment]
The --build option is unfortunately apparently broken in pip, see 
https://github.com/pypa/pip/issues/4242 So it would need to be something 
along the lines of
.
pip install --build=$PWD/builds --upgrade "file://`echo -n 
$PWD/dist/scipy-*`#egg=scipy" -v
.
In asv, where this pip + ccache problem also appears, we build the 
project with "python setup.py build; pip wheel .; pip install $WHEEL"

**Comment by pv** [comment]
Or, removing "USE_SDIST=1" should also work...

**Pull request closed without merging**
