### PR TITLE
API: Rename dcm to (rotation) matrix in Rotation class

### PR DESCRIPTION
**Pull request by nmayorov**
#### Reference issue

#10959

#### What does this implement/fix?

As discussed in #10959  the term "Direction Cosine Matrix" is not very common and "Rotation Matrix" is a better alternative. So here I introduce `from_matrix/as_matrix` methods whereas `from_dcm/as_dcm` are marked as deprecated. Only "rotation matrix" is mentioned in the docstrings and in the code now.

### CODE REVIEW

**Review by larsoner — COMMENTED** [review]
Looks reasonable to me. Should we add anything to the `np.deprecate` messages about when the names will be removed?

**Comment by larsoner** [comment]
Failure appears to be real:

https://travis-ci.org/scipy/scipy/jobs/603826016#L1102-L1123

**Comment by nmayorov** [comment]
> Looks reasonable to me. Should we add anything to the np.deprecate messages about when the names will be removed?

I think we should. Is 1.5.0 suitable for that?

**Comment by larsoner** [comment]
That's okay with me

**Comment by nmayorov** [comment]
@larsoner 

Everything seems in order now.

**Comment by rgommers** [comment]
> I think we should. Is 1.5.0 suitable for that?

we always leave deprecations in for 2 releases (sometimes more if it's a high-impact change), so should be 1.6.0

**Comment by nmayorov** [comment]
> we always leave deprecations in for 2 releases (sometimes more if it's a high-impact change), so should be 1.6.0

I changed that. 

I suggest we merge this after all checks are passing.

**Comment by larsoner** [comment]
Thanks @nmayorov

**Comment by matthew-brett** [comment]
Thanks from me too ...

**Comment by tylerjereddy** [comment]
Helpful if you can update the 1.4.0 [release notes wiki](https://github.com/scipy/scipy/wiki/Release-note-entries-for-SciPy-1.4.0) for this because a deprecation is involved.

**Comment by nmayorov** [comment]
> Helpful if you can update the 1.4.0 release notes wiki for this because a deprecation is involved.

Done!

**Pull request merged**
