### PR TITLE
DOC: Typo fix scipy/cluster/hierarchy.py

### PR DESCRIPTION
**Pull request by vrishank97**
Replaces icoords and dcoords with icoord and dcoord

### CODE REVIEW

**Comment by perimosocordiae** [comment]
This looks like a code change, not a documentation change.

I'm not sure I see the benefit of renaming these parameters.

**Comment by vrishank97** [comment]
FIxes #7785

**Comment by vrishank97** [comment]
I'm new to contributing to scipy, so I'm not sure but this was labeled as an easy-fix so I figured I'd work on this.

**Comment by perimosocordiae** [comment]
The original issue was already fixed, so this PR isn't needed. Sorry for the confusion, and please continue to look for ways to contribute!

**Pull request closed without merging**
