### PR TITLE
BLD: fix a lot of configuration warnings by using `fs.copyfile`

### PR DESCRIPTION
**Pull request by rgommers**
Warnings looked like (~100x):
```
WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
WARNING: custom_target '_dummy_init_cyoptimize' has more than one output! Using the first one.
```

Note that `fs.copyfile` is new in Meson 0.64.0, so this cannot be backported.

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
LGTM, though I'm not a `meson` expert. When I tried this branch it had some config warnings left, but far less warnings of this nature than `main` does with latest `meson`. Combined with ~100 less lines of code to maintain it seems like a fairly obvious win.

**Comment by rgommers** [comment]
> When I tried this branch it had some config warnings left,

Yes, the remaining ones are for the `_generate_pyx.py` scripts in 3 submodules, those can't be changed - we need an upstream improvement there for supporting `custom_target` with multiple outputs better. There's an open issue for it. Will revisit once the more important stuff is done.

**Comment by doronbehar** [comment]
Now updating to v1.10.0, I still get warnings like these:

```
WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
WARNING: custom_target 'cython_special' has more than one output! Using the first one.
WARNING: custom_target '_stats_gen_pyx' has more than one output! Using the first one.
```

And these lines repeat themselves, as before.

**Comment by rgommers** [comment]
@doronbehar yes there's some left - about 50% of the number of warnings that were present before this PR. The ones that are left are these three, they will need a much more elaborate approach to fix, which is not a priority right now.

**Pull request merged**
