### PR TITLE
ENH: add MCS as another derivative-free optimization method

### PR DESCRIPTION
**Pull request by mnasini**
this code aim at providing a relevant first step in implementing the algoritm MCS (multilevel coordinate search)
#### Reference issue
relevant first step for #14750

#### What does this implement/fix?
 implements the initialisation step  of the algorithm as written in the main paper:
[https://www.mat.univie.ac.at/~neum/ms/mcs.pdf](https://www.mat.univie.ac.at/~neum/ms/mcs.pdf) (pages 1 to 8)

#### Additional information
see the attached report for additional information about the algorithm and the implementation.
I'm planning to update this pull request in the following days 

[mcs.pdf](https://github.com/scipy/scipy/files/7652784/mcs.pdf)

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
I think a good first step is defining `__minimize_mcs(fun, x0)` in your file, then adding it like `Nelder-Mead` here:
https://github.com/scipy/scipy/blob/3da3fb3de8beffc79797b7b62ea3c98cc8075d2e/scipy/optimize/_minimize.py#L668-L670
And adding a simple test like: 
https://github.com/scipy/scipy/blob/2fc2458c2f46dd59d9900d500a8dddd5066a4d71/scipy/optimize/tests/test_optimize.py#L319-L348

**Comment by mdhaber** [comment]
@mnasini thanks for the contribution. Would you like to finish this up so it can be merged? There is a review waiting for you.

**Comment by mdhaber** [comment]
@AtsushiSakai that is a good suggestion for local minimizers, but since this is a global optimizer, there is precedent for having its own function. I think that's a good place to start. `minimize` has gotten somewhat cluttered, so I think it's OK for this to have the API that is best for this optimizer.

@mnasini thanks, and please let us know if you're still interested.

**Comment by lesshaste** [comment]
Did this get closed because of lack of activity? It's a shame if so as MCS would be great to have in scipy (or accessible in Python at all).

**Pull request closed without merging**
