### PR TITLE
Migrate ruff.toml configuration to lint.toml

### PR DESCRIPTION
**Pull request by charliermarsh**
#### Reference issue

See: #18347.

#### What does this implement/fix?

Per #18347, SciPy currently contains two Ruff-related configuration files: `./tools/ruff.toml` and `./tools/lint.toml`. (For context: Ruff used to require that configuration files were named `tools/ruff.toml`, even if they were explicitly provided on the CLI; this restriction was removed after SciPy adopted Ruff.)

It seems that `tools/lint.toml` contains the desired rule set (`tools/ruff.toml` is slightly more expansive), but `tools/ruff.toml` is the file that's _actually_ being used via `tools/lint.py`.

This PR thus cleans up `tools/lint.toml` and points the appropriate tooling to that configuration file instead.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Running `ruff . --config tools/lint.toml` yields 40 existing errors. I'm happy to fix those in this PR, or in a separate PR as appropriate.

**Comment by charliermarsh** [comment]
\cc @stefanv

**Comment by stefanv** [comment]
Thanks, @charliermarsh! This looks great.

FWIW, to the SciPy devs, the UP rules are a good way to keep code up to date with latest standards, so it is something we may want to consider introducing eventually.

**Review by rgommers — APPROVED** [review]
Thanks @charliermarsh, much appreciated! And thanks @stefanv too. This LGTM and CI is happy, so in it goes.

> FWIW, to the SciPy devs, the UP rules are a good way to keep code up to date with latest standards, so it is something we may want to consider introducing eventually.

I'd suggest treating that like the previous style change: if the benefit is large enough, make the case, clean up things in one go (with use of `git-blame-ignore-revs`), and then enable the relevant error code(s).

What is never good is to have a style check fail CI on code that a contributor didn't touch in their PR - that leads to confusion and unnecessary rework on PRs. I'm hoping that E and F codes will not give such changes in behavior for new `ruff` versions - should be pretty stable. If that does start to happen, we should pin `ruff` in CI just like we pinned `mypy` (mypy is notoriously unstable though, ruff seems a lot better).

**Comment by lucascolley** [comment]
> FWIW, to the SciPy devs, the UP rules are a good way to keep code up to date with latest standards, so it is something
> we may want to consider introducing eventually.

> I'd suggest treating that like the previous style change: if the benefit is large enough, make the case, clean up things in one > go (with use of git-blame-ignore-revs), and then enable the relevant error code(s).

@stefanv are you interested in making a case for introducing the UP rules? [This branch](https://github.com/lucascolley/scipy/tree/lint-UP) gets us from 389 to 0 errors.

**Comment by stefanv** [comment]
Yes, the UP rules are sensible. Since you have the branch ready, why don't you make a PR, and also add another commit adding the *first commit hash* to `.git-blame-ignore-revs`. The description can be something along the lines of:

> The [Ruff PyUpgrade rules](https://docs.astral.sh/ruff/rules/#pyupgrade-up) ensure that SciPy uses modern Python constructs that work with all support Python versions.
> While the linter only runs on files touched in any given PR, we have the option to apply these rules wholesale each time we drop support for another version of Python.
> This keeps our code current, at low cost to maintainers.

**Pull request merged**
