### PR TITLE
let find_peaks_cwt accept numbers and all iterables for `widths`

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by larsmans** [comment]
Could you add a unit test?

**Comment by MaxNoe** [comment]
You mean for the function in general?

**Comment by pv** [comment]
For the change you made. The function has a number of existing tests in test_peak_finding.py

**Comment by rgommers** [comment]
@MaxNoe are you still planning to update this PR?

**Comment by clementkng** [comment]
@MaxNoe @rgommers I can try to finish this up.

**Comment by rgommers** [comment]
@clementkng please go for it.

**Comment by MaxNoe** [comment]
As scipy introduced the new, much nicer find_peaks, I guess we can close this

**Pull request closed without merging**
