### PR TITLE
BUG: Fixed bug with Laguerre and Legendre polynomials

### PR DESCRIPTION
**Pull request by evgenyzhurko**
#7247 #7248

### CODE REVIEW

**Comment by pv** [comment]
thanks!

**Comment by adivijaykumar** [comment]
This does not fix the problem with the LEgendre, does it?

**Comment by pv** [comment]
maybe, but that bug doesn't seem to be present in master branch currently

**Comment by evgenyzhurko** [comment]
This fix for Legendre and Languerre. 
Example after fix: 
```
>>> from scipy.special import legendre
>>> from scipy.special import genlaguerre
>>> genlaguerre(1, 1, monic=True)
poly1d([ 1., -2.])
>>> genlaguerre(1, 1, monic=False)
poly1d([-1.,  2.])
>>> genlaguerre(1, 1, monic=True)(0)
-2.0
>>> genlaguerre(1, 1, monic=False)(0)
2.0
>>> legendre(5).coeffs
array([  7.87500000e+00,   0.00000000e+00,  -8.75000000e+00,
        -4.37150316e-16,   1.87500000e+00,   0.00000000e+00])

```

**Pull request merged**
