### PR TITLE
MAINT: Consistently mark BLAS/LAPACK routines as threadsafe

### PR DESCRIPTION
**Pull request by Kai-Striega**
#### Reference issue
see the discussion in #12436 

#### What does this implement/fix?
This PR marks all (almost) BLAS/LAPACK routines as ``threadsafe``.

f2py releases the GIL with the ``threadsafe`` keyword. This translates to the macros ``Py_BEGIN_ALLOW_THREADS`` and ``Py_END_ALLOW_THREADS`` being wrapped around the routine being called. ``threadsafe`` is applied inconsistently and it appears that we assume a routine is safe inconsistently.

#### Additional information

* The routines ``?gees`` excluded as a test `/scipy/linalg/tests/test_decomp.py::TestSchur::test_sort` segfaults on my system. This could be due to it using an external function but I need to investigate it a bit more
* Several other routines use similar functions but do not lead to test failures.
* It could be that multi-threaded calls to those functions are not tested at all. 

I'd like to try and run this against our full test suite to see if it picks up on any similar cases before I put the work into fixing ``?gees``

### CODE REVIEW

**Comment by Kai-Striega** [comment]
I'm not sure how the failing test case should be handled. It fails ``TestSchur::test_sort`` for real cases -- there are no tests for complex cases -- but I don't know enough about Schur to look into it properly. If the test is skipped all other tests pass so it's not having an effect elsewhere.

@ilayn would you please take a look at this?  Apart from the one test all others pass as expected.

**Comment by ilayn** [comment]
Sure, will do later today I hope.

**Comment by ilayn** [comment]
I am not sure where the test failed since it looks like it passed here. On your system could you please let me know which sorting condition failed and what it says during the segfault?

**Comment by Kai-Striega** [comment]
My apologies, it looks like I removed the threadsafe markers from the wrapper to make sure all the other wrappers work as expected. I've updated the branch and it should now fail on the CI too. 

It looks like I made a git mistake somewhere; let's see if we can figure out why it segfaults then I'll fix the git part.

**Comment by ilayn** [comment]
I think because we are calling external user functions within `?gees` they should not be thread-safe to not to mess with the sorting race. But I know next to nothing about these things (and happily so). @sturlamolden @pv Thoughts?

**Comment by sturlamolden** [comment]
This PR has 206 commits and changes 143 files. Is this intentional or did you do a Git mistake?

**Comment by ilayn** [comment]
It's a mistake. The question is whether `?gees` wrappers should have `threadsafe` or not since they accept callbacks from users and sorting is involved.

**Comment by pv** [comment]
As long as we support numpy versions where f2py has the threadsafety bug, we probably shouldn't mark such routines threadsafe.

**Comment by rgommers** [comment]
> As long as we support numpy versions where f2py has the threadsafety bug, we probably shouldn't mark such routines threadsafe.

For future reference: that's numpy 1.20.0 (not yet released).

**Comment by sturlamolden** [comment]
> > As long as we support numpy versions where f2py has the threadsafety bug, we probably shouldn't mark such routines threadsafe.
> 
> 
> 
> For future reference: that's numpy 1.20.0 (not yet released).


Note that we can query the Fortran module to see if it has the threadsafety bug, as it now reports the NumPy/f2py version used to build the module. If it is there we can serialize access with a global threading.RLock.

**Pull request closed without merging**
