### PR TITLE
DOC: stats.burr12: fix typo

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-14003

#### What does this implement/fix?
Obvious typo in `burr12` distribution documentation.

#### Additional information
Please consider double-checking recently-merged changes from gh-14003. I went ahead and corrected/merged that myself, but it would be good to have someone else looking since there was some confusion there.

### CODE REVIEW

**Review by tupui — APPROVED** [review]
LGTM, not sure I get what you want to check on the other PR. I am merging this one now, we can discuss other things later.

**Comment by mdhaber** [comment]
Looks like it rendered fine:
image

**Comment by tupui** [comment]
(I just have my phone until Monday, so hard to check things). I don't think it's related, on some logs I see: `WARNING: py:obj reference target not found: matplotlib.pyplot`. Maybe there was an update with Sphinx.

**Comment by mdhaber** [comment]
I agree. I opened gh-15666 to investigate.

**Pull request merged**
