### PR TITLE
MAINT: integrate, special: remove unused R1MACH and Makefile

### PR DESCRIPTION
**Pull request by larsmans**
Removes a few hundred lines of unused Fortran code from two places in SciPy.

The same places also have a `D1MACH` that, similar to `R1MACH`, performs all kinds of runtime (!) checks to figure out which piece of museum hardware it's running on. I've tried to replace it by the C code listed in the same file that does the same at compile time, but I couldn't get it to work.

Is there a portable way to get the `<float.h>` constants into Fortran code?

### CODE REVIEW

**Comment by larsmans** [comment]
Test failure is a timeout, as usual.

**Comment by ewmoore** [comment]
For scipy an answer is to use `dlamch` and `slmach` from lapack.   Otherwise fortran95 and on provide a variety of intrinsics for these purposes such as  [huge](http://fortranwiki.org/fortran/show/huge).

**Comment by larsmans** [comment]
Using `dlamch` is an option, but I'm not sure I know enough Fortran to pull it off, so don't wait for me to figure out how to call and link with it.

**Comment by rgommers** [comment]
Also no idea about the Fortran question. Always +1 for removing dead code though.

**Comment by ewmoore** [comment]
This has had plenty of time for comment and only removes unused code.  In it goes. Thanks @larsmans!

**Pull request merged**
