### PR TITLE
TST: Fix some Fedora 25 test failures.

### PR DESCRIPTION
**Pull request by charris**
There are two fixes:

* relax atol in TestFiltFilt.test_basic
* allow bad_count == 20 in test_degenerate_barycentric_transforms.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
SOS changes are fine for me.

**Comment by charris** [comment]
I don't know enough about the qhull test to say if a `bad_count == 20` is permissible.

**Comment by charris** [comment]
There is also this warning (printed?)
```
scipy/signal/filter_design.py:1452: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)
```

**Comment by Eric89GXL** [comment]
Not sure about that one without being able to look... feel free to take a stab at fixing it here if you want. Or just suppress the warning with a `warnings.catch_warnings(record=True)` context manager.

**Comment by pv** [comment]
I don't see the qhull issue on fedora 25 myself, but 20 vs 21 shouldn't matter --- the test is stressing qhull's numerical stability in a bad case so the results probably vary per floating point error variations.

**Comment by charris** [comment]
IIRC, I've seen the qhull failure before, but it was not 100% repeatable. Don't know what was up with that...

**Pull request merged**
