### PR TITLE
MAINT: sparse: add missing dict methods to DOK and tests

### LINKED ISSUE #20156: BUG: sparse.dok_matrix throws KeyError for valid pop(key) since v-1.12.0
### Describe your issue.

sparse.dok_matrix throws KeyError for valid `pop(key)` since v-1.12.0. Worked well until 1.11.4.

### Reproducing Code Example

```python
import scipy.sparse
S = scipy.sparse.dok_matrix((2,2))
S[0, 1] = 1
print('keys', list(S.keys()))
S.pop((0, 1))
```

### Error message

```shell
Traceback (most recent call last):
  File "tmp.py", line 5, in <module>
    S.pop((0, 1))
KeyError: (0, 1)
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.4 sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.8",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.15.0",
      "include directory": "../../tmp/pip-build-env-wkrrblds/overlay/lib/python3.11/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.1",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp311-cp311/bin/python",
    "version": "3.11"
  }
}
```

### PR DESCRIPTION
**Pull request by dschult**
A few `dict` methods are not being overloaded by the DOK sparse format. Most are likely due to new features added to `dict` in recent years. But others such as `pop` and `fromkeys` have recently been missed by users. (see Issue #20156 which this fixes and `dok.array.fromkeys` which was recently fixed in #20154).

This PR adds all the missing methods from dict (which otherwise call dict.method() on the sparse dok class and that often doesn't work).  The methods are:
```
pop()
__reversed__
__or__, __ror__, __ior__,
```
It also adds tests of all the dict methods to `sparse/tests/test_dok.py`.  Those tests are not meant to be exhaustive, but check that the methods exist and work for typical cases.

Fixes #20156 

This can be merged before or after the other open PR for DOK format:  #19715 since the rebase/merge is simple. That PR is ready to merge with 2 approvals and now rebased on main. This one is fairly short so maybe quick to review.  When either is merged, I will update the other.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Branching is imminent, so I've bumped the milestone. If you and CJ tell me this needs to be in `1.13.0` after I branch, we'll deal with it then.

**Review by perimosocordiae — APPROVED** [review]

**Comment by yoch** [comment]
Hi @dschult 

The pop implementation differs from the `dict` one, in can the user don't provide default value, in your case it return `None` instead of raising an exception.

**Comment by dschult** [comment]
Rats -- I understand. I think a cleaner way to handle that case is:
```python
    def pop(*args):
        return self._dict.pop(*args)
```
Do you see anything not working with that code?

I'll also add a test to make sure that is working. Thanks!

**Comment by yoch** [comment]
Yeah, it's fine. I think you have to add `self` in the  function parameters.

**Pull request merged**
