### PR TITLE
WIP, MAINT: 1.10.2 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
I think `scikit-learn` folks had some interest in a release that patches the read-only Cython memoryview stuff. This backport branch still needs work, local testing suggests meson build issues, perhaps because of various merge conflicts/evolution of the build config vs. the maintenance branch. Also of note is that gh-18034, which was marked for backport, had such large merge conflicts that I just gave up on it, for now.

Backports included:

1. gh-17993
2. gh-18011
3. gh-18121
4. gh-18124
5. gh-18153
6. gh-18154
7. gh-18159
8. gh-18169
9. gh-18177
10. gh-18192
11. gh-18211
12. gh-18220

### CODE REVIEW

**Comment by rgommers** [comment]
> Also of note is that [gh-18034](https://github.com/scipy/scipy/pull/18034), which was marked for backport, had such large merge conflicts that I just gave up on it, for now.

That's okay I think - the packagers that need this are already carrying a patch for it.

**Comment by tylerjereddy** [comment]
I pushed in a fix for an incorrectly-resolved merge conflict related to Cygwin meson builds. After that, I ended up with 1 failure in test suite locally on Ubuntu, below the fold. I'm almost certain that I'm still missing other useful backports here anyway, but I'd like to see what the CI complains about after my recent patch.

<details>

```
[gw5] linux -- Python 3.10.6 /home/tyler/python_310_scipy_dev_work/bin/python
scipy/stats/tests/test_distributions.py:1491: in test_fit_gh_18176
    _assert_less_or_close_loglike(stats.logistic, data)
E   TypeError: _assert_less_or_close_loglike() missing 1 required positional argument: 'func'
        data       = array([-459,   37,   43,   45,   45,   48,   54,   55,   58,   59,   59,
         59,   61,   61,   61,   61,   61,   61,   61,   61,   61])
        self       = <scipy.stats.tests.test_distributions.TestLogistic object at 0x7f5fac4b0f40>

```

</details>

**Comment by tylerjereddy** [comment]
A subset of jobs have Cython versions that are way too old, so I'll need to deal with that in addition to checking for a likely missing backport or merge conflict on the single failing Linux test.

**Comment by tylerjereddy** [comment]
Updating `_assert_less_or_close_loglike()` to match its state on the `main` branch appears to fix the Linux CI failure locally, we'll see if the CI agrees. It appears that one of the `stats` backports added a new test that used the new call signature, and updating seems pretty safe to me.

**Comment by tylerjereddy** [comment]
Now I see: `meson.build:1:0: ERROR: Cython compiler 'cython' cannot compile programs`, but this is also visible on `main` PRs recently per gh-18390. I'm pretty sure I know which dependency is causing that, so if pin something on `main` I can backport it here perhaps...

**Comment by tylerjereddy** [comment]
I've closed/reopened to flush CI again now that the dust should have settled with the `pythran` and `gast` breakage. That said, I've seen a lot of traffice related to `const` usage in Cython & related issues so I'm actually not so confident I have a complete understanding of what (if anything) we'd want to backport related to that stuff.

**Comment by tylerjereddy** [comment]
Eh, `pythran 0.12.1` is still being picked up in some cases, maybe I'll revisit this another day, though some of the other CI failures can still be checked in the meanwhile I suppose.

**Comment by rgommers** [comment]
Maybe a caching issue? The requirement in `pyproject.toml` is `pythran>=0.12.0,<0.13.0` and 0.12.2 landed on PyPI over an hour ago.

**Comment by tylerjereddy** [comment]
The `Meson build (3.10)` job was failing because of Cython `0.29.32` getting pulled in, which is too old. I've incremented the `CACHE_NUMBER` since the `environment.yml` is already set to pull latest Cython. Locally on a Mac, build/test suite look fine with newer Cython (well, apart from the known issues from gh-18308).

I'll start chipping away at this a bit more now that I'm switching gears back to release management...

**Comment by tylerjereddy** [comment]
I don't think `1.10.2` makes sense at this time, things have gotten busy enough on the `1.11.x` series.

I'll probably aim to close this and the 16 outstanding merged backport PRs will have their labels removed in a few days, if I don't hear any objections. I'd like to keep the backport list fairly clean for the `1.11.x` series and focus energy there.

**Comment by rgommers** [comment]
That plan sounds fine to me. Thanks Tyler.

**Pull request closed without merging**
