### PR TITLE
MAINT: Reorganize flapack.pyf.src file

### PR DESCRIPTION
**Pull request by ilayn**
The `flapack.pyf.src` source file is exceedingly long and difficult to navigate. Moreover, if there are simultaneous PRs touching this file then merge conflicts can occur. 

This PR reorganizes it and creates separate files according (almost) to the specifications that is given at http://www.netlib.org/lapack/explore-html/

What is left inside `flapack.pyf.src` file is the generic BLAS variants. It also makes it easier to identify what has been wrapped and what is missing. This has been briefly discussed in the mailing list before (item 2)

https://mail.python.org/pipermail/scipy-dev/2017-December/022281.html

### CODE REVIEW

**Comment by rgommers** [comment]
Overall seems fine. Two minor things:
- It's unclear why there are still functions left in `flapack.pyf.src` itself (anything not categorizable I'd expect in `_other`). Would be useful to add a comment at least.
- There are two files without a newline at the end of the file.

**Comment by ilayn** [comment]
Thanks @rgommers, now they are moved and files end with linebreaks. 

One side effect of this reorganization I have noticed is that, now when the subfiles are modified the compiler doesn't track them and assumes nothing changed. Would that be an issue or can we tell compiler to watch for the subfiles too?

**Comment by rgommers** [comment]
> One side effect of this reorganization I have noticed is that, now when the subfiles are modified the compiler doesn't track them and assumes nothing changed. Would that be an issue or can we tell compiler to watch for the subfiles too?

You can just add all the files to the `depends=` list in `linalg/setup.py`.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @ilayn

**Comment by j-bowhay** [comment]
@ilayn do you mind if I move the tridiagonal eigenvalue routines from `other` to `tri` so they're easier to find?

**Comment by ilayn** [comment]
No objections from me, organize as you see fit.

**Pull request merged**
