### PR TITLE
MAINT: remove asfarray usage

### PR DESCRIPTION
**Pull request by andyfaff**
@tylerjereddy, I started down the road of a creating a complete `asfarray` replacement, but thought better of it.

I think this PR does what is required. I apologise if there was extra work created for you by backing out your changes.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Looks more careful than my initial attempt--should we perhaps double check with @h-vetinari re: dropping `asfarray` a little sooner than the code comments suggest we were going to? I don't know that we have much choice though, unless we want to provide it and re-export it, which might be a bit much. (context: `asfarray` is now gone in NumPy `main`)

Is there any way to guard against the somewhat-cavalier approach (coerce to `float64`) I was proposing initially? Maybe out of scope here, but perhaps there is some test where the number of iterations or some output is sensitive to the floating point type width? Or does it just affect performance? (`asv` perhaps)

**Comment by j-bowhay** [comment]
> Looks more careful than my initial attempt--should we perhaps double check with @h-vetinari re: dropping `asfarray` a little sooner than the code comments suggest we were going to?

I think this is fine, usage would have emitted a deprecation warning for ages (it was recently changed to be a bit more specific hence the version in the comment)

**Comment by h-vetinari** [comment]
Yeah, I agree with @j-bowhay, this is fine.

**Comment by andyfaff** [comment]
> Is there any way to guard against the somewhat-cavalier approach (coerce to float64) I was proposing initially?

The minimize methods are by no means float width clean. I think there is a long way to get there, and it's not clear as to how long it will take, or how hard it'll be. It's also not clear to me that respecting float width is always helpful.

However, there are things that can help. One of them is to not introduce automatic float64 casts when we're making modifications (i.e. slow convergence towards target). Adding tests to check float width on operations are worth adding, but probably as part of a converted push for each minimizer.

**Comment by andyfaff** [comment]
I have no idea why an end user would be using asfarray from scipy, instead of using it from numpy.

**Comment by andyfaff** [comment]
Merging to free up cp312 and downstream wheels

**Pull request merged**
