### PR TITLE
Vectorization of Anderson-Darling computations.

### PR DESCRIPTION
**Pull request by anntzer**
Results in >1000x acceleration of scipy.stats.anderson_ksamp for
datasets of N~1000.

### CODE REVIEW

**Comment by rgommers** [comment]
that's a nice speedup:)

**Comment by rgommers** [comment]
Would be good to add a benchmark for this function, so we'll detect any regressions. Should be easy to do - example: gh-4621

**Comment by josef-pkt** [comment]
just out of curiosity: What's the usecase with N=1000?  
I always thought of k-sample tests as test with just a few, like 3 to 10, samples.

**Comment by anntzer** [comment]
Actually I just wanted to run a 2-sample test, but with a large number of data points in each sample.  Moreover, the differences between the distributions would be mostly in the tail region, suggesting the use of something else than the KS test.

**Comment by josef-pkt** [comment]
I mixed up k and N in my reading, so large N (total nobs)  is not a surprise.

**Comment by rgommers** [comment]
Thanks @anntzer, merged.

**Pull request merged**
