### PR TITLE
MAINT: Install `sparse.linalg._eigen` tests and fix test failures

### PR DESCRIPTION
**Pull request by Smit-create**
Presently, `sparse.linalg._eigen.tests` aren't installed and so the tests failures may go unnoticed. This was highlighted while I was working on https://github.com/rgommers/scipy/pull/93#issuecomment-973971066

cc @rgommers

### CODE REVIEW

**Comment by rgommers** [comment]
So the test failures do reproduce in CI. The next step is looking at the test case, and if the input are really too small as the warning says, decide whether to update those tests to use larger input arrays, or to remove the tests or skip them for `lobpcg`. See https://github.com/scipy/scipy/pull/14868#issuecomment-964738134.

**Comment by Smit-create** [comment]
There were 93 test failures(user warnings which were added in gh-14868) in `eigen/tests/test_svds.py`. Also, referring from gh-14868, I added `pytest.warns` flags to suppress the user warnings.

**Comment by rgommers** [comment]
That approach looks good to me. 

Other test failures are relevant to fix up too. Mypy:
```
scipy/sparse/linalg/_eigen/tests/test_svds.py:652: error: List item 0 has incompatible type "float"; expected "int"  [list-item]
scipy/sparse/linalg/_eigen/tests/test_svds.py:652: error: List item 1 has incompatible type "str"; expected "int"  [list-item]
```

PROPACK tests:
```
E   TypeError: PROPACK complex-valued SVD methods not available for 32-bit builds
```

**Comment by Smit-create** [comment]
@rgommers Can you please restart the failing test since all other tests have passed? I guess that is some internal error again.

**Comment by rgommers** [comment]
> @rgommers Can you please restart the failing test since all other tests have passed? I guess that is some internal error again.

That's okay, that job regularly times out after 60 minutes. We can just ignore it here, all other jobs are green.

**Review by rgommers — APPROVED** [review]
All LGTM, thanks @Smit-create!

**Comment by rgommers** [comment]
Can you make the matching change for Meson @Smit-create?

**Comment by Smit-create** [comment]
> Can you make the matching change for Meson @Smit-create?

Yes, sure.

**Pull request merged**
