### PR TITLE
Fix up ccache usage on Travis + try enabling on OSX

### PR DESCRIPTION
**Pull request by pv**
Fix up ccache usage on USE_SDIST and USE_WHEEL targets.
Pip by default builds in a directory with random name, which throws off the compiler result caching.

Also try to enable the caching on OSX, based on gh-7647 which was quite close.

Finally, add and use some tools for suppressing the huge output from scipy build commands
in the USE_SDIST and USE_WHEEL targets.

### CODE REVIEW

**Comment by andyfaff** [comment]
I was still going on the PR, I just closed it to prevent travisCI pollution and spurious emails to devs. Anyway, from my latest test run on https://travis-ci.org/andyfaff/scipy/builds/256840423 I see a reduction from a 15min build (`python setup.py build`) time to ~4 minutes. So I'm hopeful that this approach works here.

**Comment by pv** [comment]
Ok, it's not using ccache on osx with my config. Probably best to just 
copypaste yours...

**Comment by pv** [comment]
Ok, seems to work now.

**Comment by andyfaff** [comment]
Do you see speedup in Linux builds?

**Comment by pv** [comment]
ccache -s shows about 300 cache hits from the build, so it works, both on
linux and osx. Osx has only few cache misses, but the linux builds had 80
or so. This is regardless of wheel/sdist so it's not related to this PR.

The recent precise to trusty transition seems to have changed something.
Unclear what.

26.7.2017 0.31 "Andrew Nelson" <notifications@github.com> kirjoitti:

**Comment by pv** [comment]
Thanks for the help with this @andyfaff.

**Comment by andyfaff** [comment]
I'm very impressed with the speed of the OS X build/test.

**Pull request merged**
