### PR TITLE
ENH: linalg: Allow supplying a sequence of matrices to linalg.expm

### LINKED ISSUE #12838: Accept multiple matrices in `scipy.linalg.expm`
**Is your feature request related to a problem? Please describe.**
I would like to compute exponentials of many matrices at once. I have a composite matrix of shape `(M, N, N)` and want the exponentials of the matrices in the last 2 dimensions (of shape `(N, N)`).
`scipy.linalg.expm` accepts only a single matrix, so a for loop or parallelized for loop can be used.

**Describe the solution you'd like**
Supporting multiple matrices as in [`numpy.linalg.eig`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig) for example.
Many functions in `numpy.linalg` support multiple matrices.

**Describe alternatives you've considered**
[tf.linalg.expm](https://www.tensorflow.org/api_docs/python/tf/linalg/expm)

**Additional context (e.g. screenshots)**
https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.expm.html

### PR DESCRIPTION
**Pull request by DCtheTall**
#### Reference issue

Fixes [#12838](https://github.com/scipy/scipy/issues/12838).

#### What does this implement/fix?

This PR allows users to supply a sequence of square matrices to `linalg.expm` which before only accepted a single square matrix as an argument. The implementation simply checks if the input is 3-dimensional and if so, iterates over the topmost indexing and recursively calls the function on each of the arguments.

Right now this extension only works on sequences of matrices that are _all_ the same size, but if the project maintainers prefer to support sequences of matrices with different sizes I can change the code to do so 😄

### CODE REVIEW

**Comment by DCtheTall** [comment]
@pvanmulbregt friendly ping. Also pinging @tylerjereddy since he reviewed my last PR.

**Comment by DCtheTall** [comment]
@rgommers friendly ping, is this PR something you guys are interested in accepting? If not I can close it.

**Comment by rgommers** [comment]
Thanks for the ping @DCtheTall. I replied on gh-12838, let's discuss there if we want this feature.

**Comment by DCtheTall** [comment]
Closing due to the fact that since `expm` is already a pure function, this cannot be implemented for a sequence of matrices any faster than a native for loop. Refactoring `expm` to be in place is quite an effort, something this feature probably doesn't merit.

**Pull request closed without merging**
