### PR TITLE
speed improvment in _distn_infrastructure.py

### PR DESCRIPTION
**Pull request by kokorev**
replace built-in sum function with numpy one for better performance. See https://github.com/scipy/scipy/issues/7011 for details.

### CODE REVIEW

**Comment by kokorev** [comment]
CI failing for Python 3.5 only, similar to other recent PR. Not sure what is going on here.

**Comment by ev-br** [comment]
CI failure is indeed unrelated.  There's something going on with numpy master branch, hmm...

**Comment by WarrenWeckesser** [comment]
When `a` is a numpy array, a more appropriate replacement for `sum(a)` is `a.sum(axis=0)`.  For example, here `a` is a 2-d numpy array:

```
In [8]: a
Out[8]: 
array([[10, 20, 30],
       [40, 50, 60]])

```
`sum(a)` sums only the first dimension:
```
In [9]: sum(a)
Out[9]: array([50, 70, 90])
```
`a.sum()` sums *all* the elements.  We need `axis=0` to reproduce the result of `sum(a)`.
```
In [10]: a.sum()
Out[10]: 210

In [11]: a.sum(axis=0)
Out[11]: array([50, 70, 90])
```

I haven't looked too closely at the context here.  Perhaps the sum overall all the elements is actually correct, and the use of `sum(cond0)` is an undiscovered bug.

The difference only occurs when `cond0` has more than one dimension.  Can this function ever be called with an array with more than one dimension?   If so, are there tests for that case?

**Comment by charris** [comment]
> CI failure is indeed unrelated. There's something going on with numpy master branch, hmm...

For reference
```
======================================================================
FAIL: test_continuous_basic.test_cont_basic(<scipy.stats._continuous_distns.genextreme_gen object at 0x7f5e20f8ccc0>, (-0.1,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/stats/tests/common_tests.py", line 109, in check_edge_support
    npt.assert_equal(distfn.cdf(x, *args), [0.0, 1.0])
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 342, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 852, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 725, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(shapes (2, 1), (2,) mismatch)
 x: array([[ 0.],
       [ 1.]])
 y: array([ 0.,  1.])
```
I don't recall anything obvious that could have changed the shapes...

**Comment by perimosocordiae** [comment]
Looking at the context of this line a bit, it seems like the correct fix is to replace the `sum` call with `np.count_nonzero`.

**Comment by kokorev** [comment]
Thanks for the help everyone, I suggest to use n`p.count_nonzero(cond0, axis=0)`, however, I not sure if `axis=0` should be here, since it implies that cond0 could be a 2-d but I think it should never be the case. If I understand correctly, the code will fail on the very next line if cond0 will be a 2-d array
```
        n_bad = np.count_nonzero(cond0, axis=0)
        if n_bad > 0:
```
I still used `axis=0` argument, because it duplicates `sum(cond0) `behaviour

**Comment by josef-pkt** [comment]
my guess is that axis handling in the `nnlf` and `fit` related methods is an incomplete, untested feature. partially intended to work with explicit axis=0, but broken overall.

I think none of the optimizers in fit would be able to handle non-scalar nnlf, and the data is ravelled.

**Comment by ev-br** [comment]
The fit infrastructure might indeed use a bit of a cleanup. The current version however seems to relay the intent, so let's merge it. Thanks @kokorev and congrats for what I believe is your first SciPy commit. Keep the coming! Thanks to all the reviewers, too.

@kokorev for future ones, it'd help to use the NumPy format for commit messages

**Pull request merged**
