### PR TITLE
correct bounds pass in run_dualannealing for benchmarks/optimize.py

### LINKED ISSUE #11438: run_dualannealing passes bounds incorrectly in benchmarks/optimize.py
I was trying to run the optimization benchmarks on the dual annealing algorithm, when I was getting this error:
```
in dual_annealing
lu = list(zip(*bounds))
TypeError: type object argument after * must be an iterable, not NoneType
```
It turns out [run_dualannealing](https://github.com/scipy/scipy/blob/40a5c7cd6235bab123c38c89715a3b9261b63803/benchmarks/benchmarks/optimize.py#L191) in benchmarks/benchmarks/optimize.py isn't correctly passing the optimization bounds to dual_annealing. 

The code is:
```python
        res = dual_annealing(self.fun,
                             None,
                             self.bounds)
```

However it should be

```python
        res = dual_annealing(self.fun,
                             self.bounds)
```

### PR DESCRIPTION
**Pull request by cjekel**
#### Reference issue
closes https://github.com/scipy/scipy/issues/11438

#### What does this implement/fix?
fixes scipy optimize benchmarks for dual_annealing function

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
LGTM; seems like a clear fix based on the function signature.

I suspect `optimize` folks will be happy to merge as-is; I'll let CI run anyway.

**Comment by andyfaff** [comment]
This one can be merged (not much point running the CI's because the benchmarks are touched by CI).
However, the optimize benchmarks aren't runnable at the moment, there are other issues.

**Comment by tylerjereddy** [comment]
The benchmarks are probed a little by CI for major issues with `asv check` and `pycodestyle`, but obviously not sufficient to detect the original issue.

**Comment by mdhaber** [comment]
Thanks @cjekel! If you'd like your name added to [THANKS.txt](https://github.com/scipy/scipy/blob/master/THANKS.txt), please make an entry [here](https://github.com/scipy/scipy/wiki/*THANKS.txt-additions-modifications-for-1.5.0*).

**Pull request merged**
