### PR TITLE
Class-Based Levenberg-Marquardt Fitter

### PR DESCRIPTION
**Pull request by tecki**
This is the same pull request as 
https://github.com/scipy/scipy/pull/88
rebased onto the current master. The current
master already contains qr_multiply, and
this this pull request gets much more readable.

This pull request contains a new Class-Based
Levenberg-Marquardt fitter. It is the original minpack
lmder/lmdif algorithm translated to python and
strongly pythonised. It features:
- a cool class-based interface
- a function based interface if you don't like it so cool
- the possibility to tell the algorithm that it went too
  far with the parameters while optimizing
- the possibilty to stop fitting from another thread

The reason we used to have leastsq in FORTRAN 
was that: first, it was already there, and 2nd, it is
fast. But this speed comes at a cost: when we
call python from FORTRAN, a lot of magic has to
be done. This magic prevents us, for example, to
properly pass exceptions through the FORTRAN
code.

The speed disadvantage from using Python is 
marginal: since all numerical functions (this is
where most of the time is spent) are still in
FORTRAN, we don't loose much. I even re-coded
the last remaining inner loop which has no 
simple FORTRAN equivalent in cython so we
also don't loose there. In the end, the Python code
could even be faster, as it uses LAPACK code,
which is typically pretty well optimized thanks to
ATLAS, while MINPACK still does everything by
hand, which might be sub-optimal (especially on
multi-core machines which are used very efficiently
by ATLAS).

Python also has the advantage of being much better
readable, and thus adopting for your needs is much
simpler. This is why I was able to add the "Parameter
ran away!" functionality.

### CODE REVIEW

**Comment by sturlamolden** [comment]
MINPACK (used for ```leastsq```) uses an unoptimized QR factorization derived from LINPACK. It is a major botteneck. I would not be surprised if a plain Python implementation that calls LAPACK is faster. We could also reuse the recent Cython code for updating QR factorizations. Another problem is that the MINPACK Fortran 77 code is not reentrant. The advantage of the MINPACK version is that is well-tried and known to be very numerically stabile.

SVD does not make a lot of sense as the diagonal bias added to the covariance matrix ensures that it is not ill-conditioned. If it is, Levenberg-Marquardt will detect it (residual sum of squares increases due to rounding error) and more bias is added to the diagonal.

**Comment by rgommers** [comment]
@sturlamolden are you aware that @nmayorov will start a GSoC that's very much related to this PR soon? See https://stackedit.io/viewer#!provider=gist&gistId=d806ad6048c7e3df4797&filename=GSOC_proposal.md and https://nmayorov.wordpress.com/.

**Comment by sturlamolden** [comment]
No, I was not, but that is good to hear :)

**Comment by dashesy** [comment]
Great to hear about the GSoC project! I think many people will be happy. Would be interesting to compare this with `lmfit` (which works great) in terms of performance and accuracy of fit. Also the api of `lmfit` is very intuitive, so another point of comparison would be the api design.

**Comment by sturlamolden** [comment]
```lmfit``` is just a wrapper for the optimizers already in SciPy.

**Comment by dashesy** [comment]
@sturlamolden It is not too trivial, working around the bounds requires some transformation before *and after* the fit, it is not a simple bound check because that would throw off the gradient. Also mathematical expression can be used using `ast` for constraints (that is non-trivial). Even if it was just a nice api It would be more useful if the new Levenberg-Marquardt algorithm could help `lmfit` to be simpler (native support for bounds) and faster. Using LAPACK will definitely help because of the matrix decompositions for example. In addition the api of lmfit is nice and mature now, so I thought a comparison (when GSoC project is done) would be nice.

**Comment by charris** [comment]
It would be helpful if all those interested could review and comment on Nikolay's work as it progresses. You can follow some of his plans at https://nmayorov.wordpress.com/

**Comment by ev-br** [comment]
OK, the main part of the GSoC work has been merged, gh-5044.

**Comment by nmayorov** [comment]
Perhaps it's time to close this PR :)? By the way it is the oldest one currently.

**Comment by rgommers** [comment]
> Perhaps it's time to close this PR :)? By the way it is the oldest one currently.

@nmayorov I agree. The algorithmic part here is still potentially useful, but by closing this PR that doesn't get lost. So if anyone wants to use that code still, they can still grab it. Hence closing.

**Pull request closed without merging**
