### PR TITLE
DOC: resample example

### PR DESCRIPTION
**Pull request by endolith**
Add an example of resample, showing how it is circular.

### CODE REVIEW

**Comment by endolith** [comment]
actually `from scipy import signal` isn't necessary, right?

**Comment by ev-br** [comment]
Without it, (1) the code in example is not runnable as is, and (2) the plot will not render in the online docs.

**Comment by rgommers** [comment]
I quite like this example, demonstrates periodicity but also that you get interesting/smooth behavior when resampling between two data points. Without reading the docstring I think most people would expect ``resample`` to be OK for downsampling but show naive behavior (like linear interpolation) when upsampling.

**Comment by rgommers** [comment]
Merged, thanks @endolith

**Pull request merged**
