### PR TITLE
MAINT: _differentialevolution now uses _lib._util.check_random_state

### PR DESCRIPTION
**Pull request by andyfaff**
`_differentialevolution` had its own version of `_lib._util.check_random_state`. It doesn't make sense to use two different versions of the same thing, so I've deprecated the version in `_differentialevolution.py` and changed the differential evolution code to use the version in `_lib._util`. I also added some tests to check that `check_random_state` is returning the right output.

### CODE REVIEW

**Comment by andyfaff** [comment]
The tests are failing in `test__differential_evolution.TestDifferentialEvolutionSolver.test_best_solution_retrieval`. The test `uses assert_equal`, when it should probably use `assert_almost_equal`. The population array contains values between 0 and 1, which are then scaled to values between the lower and upper bounds for each parameter. `test_best_solution_retrieval` is a round trip test for this scaling/unscaling. The following is an example, the `assert_equal` has a ~2.5% mismatch.

    import numpy as np
    from numpy.testing import assert_equal, assert_almost_equal
    limits = np.array([(-10, 10)])
    limits = np.array(limits, dtype='float').T
    scale_arg1 = 0.5 * (limits[0] + limits[1])
    scale_arg2 = np.fabs(limits[0] - limits[1])

    def scale_parameters(trial):
        """
        scale from a number between 0 and 1 to parameters.
        """
        return scale_arg1 + (trial - 0.5) * scale_arg2

    def unscale_parameters(parameters):
        """
        scale from parameters to a number between 0 and 1.
        """
        return (parameters - scale_arg1) / scale_arg2 + 0.5

    val = np.random.random(100000)
    parameters = scale_parameters(val)
    trial = unscale_parameters(parameters)
    assert_equal(val, trial)

**Comment by andyfaff** [comment]
open/close to restart CI

**Comment by dlax** [comment]
I'm not sure it's worth deprecating things in a private method of a private class.

Also, your commit contains two unrelated changes (the one concerning tests of `_lib._util.check_random_state` and the one concerning differential evolution), so there should be two distinct commits.

**Comment by andyfaff** [comment]
Split into two commits. Removed private function from `_differentialevolution.py`

**Comment by dlax** [comment]
The split is not correct since the second commit contains removal of the test of `_differentialevolution._make_random_gen` which should be in the first commit.

Also CI is failing, didn't checked why though.

**Comment by andyfaff** [comment]
Hopefully this is split properly now. CI was failing because the added test had a bug.

**Pull request merged**
