### PR TITLE
MAINT: Fix pypy timeout

### PR DESCRIPTION
**Pull request by larsoner**
Pypy is at it again. On `master` and all PRs we are getting a pypy timeout:

https://circleci.com/gh/scipy/scipy/11189

I'm going to see if I can identify and fix it.

### CODE REVIEW

**Comment by ilayn** [comment]
I am wondering if it might have something to do with Circle CI specifically. The choking pattern is often quite strange.

**Comment by larsoner** [comment]
Okay CircleCI seems to build reliably. This is ready for review/merge from my end.

**Review by tylerjereddy — APPROVED** [review]
This appears to be the most portable / conservative approach based on the plugin docs so let's give it a try since it seems to make our CI more reliable.

**Comment by tylerjereddy** [comment]
Thanks @larsoner

**Comment by larsoner** [comment]
We got a timeout on a differential evolution test at 22% complete, but still ended up with "too long with no output" around 90% complete, so it looks like `pytest-timeout` has failed us :(

https://circleci.com/gh/scipy/scipy/11239

It has failed with this too-long-with-no-output on many recent `master` builds, but it does not seem to do it on the PRs. I have no idea why this would be because it does not look like the workflows should differ. The only remaining idea is have is that it's perhaps some cache issue.

We could also try removing `-n 3` to stop using `pytest-xdist` on CircleCI. At least in a PR we could see if it makes things take much longer. If it doesn't, we could try merging to see if it's fixed in `master`, eventually reverting this (and maybe `pytest-timeout`, too?) if it does not work. Thoughts?

**Comment by larsoner** [comment]
Unfortunately it did not fix the ~90% error:

https://circleci.com/gh/scipy/scipy/11266

But hopefully it fixes the other (differential evolution) timeout problem.

**Comment by larsoner** [comment]
And then [this one](https://circleci.com/gh/scipy/scipy/11268) had an interesting output:
```
......s.............................s................................... [ 26%]
................[gw1] node down: Not properly terminated
fReplacing crashed worker gw1
gw0 [15605] / gw3 ok / gw2 [15605]. [ 26%]
gw0 [15605] / gw3 [15605] / gw2 [15605]. [ 27%]
..................s...............s................s..........s..ss..... [ 27%]
```
Not sure if it's related or not.

**Comment by andyfaff** [comment]
I have an idea, could you try commenting out the `test_parallel` from differential evolution? If pypy starts working regularly, getting past the 90%, then we may find out that the `test_parallel` is causing more issues than we first thought.

**Pull request merged**
