### PR TITLE
DOC: Note that morlet and cwt don't work together

### PR DESCRIPTION
**Pull request by endolith**
See http://dsp.stackexchange.com/a/18104/29

http://stackoverflow.com/q/23730383/125507

### CODE REVIEW

**Comment by endolith** [comment]
by the way, there's an apparently-abandoned CWT implementation at 

http://www.phy.uct.ac.za/courses/python/examples/moreexamples.html#wavelet-analysis-continuous-wavelet-transform

and a slightly-modified mirror at https://github.com/emanuele/cwt/blob/master/Wavelets.py that might make sense to take over as part of scipy.signal?  it has more wavelet functions built-in than any other implementation I've found, and is BSD licensed.

**Comment by rgommers** [comment]
Merged, thanks @endolith

**Comment by rgommers** [comment]
The link to a CWT implementation above should probably be added to a new or existing issue on CWT to not lose it. @aaren or @Dapid may be familiar with it already.

**Comment by endolith** [comment]
Actually I found aaren's wavelet implementation today that might be as good or better, I haven't installed it yet https://github.com/aaren/wavelets

**Comment by aaren** [comment]
I'd not seen the code linked above before. There are a number of CWT implementations around and they mostly end up looking quite similar (including mine). Not sure about licensing with others but I can say that mine was written from scratch.

`signal.cwt` is due a sort out, but I'm not sure how much we want to think about api compared to the planned `scipy.wavelets` (currently [pywt](https://github.com/PyWavelets/pywt)).

**Comment by endolith** [comment]
Pywt is only discrete wavelets though, right?

**Comment by aaren** [comment]
That's right, pywt is only discrete. It might make sense to keep CWT separate and in signal, but I'm not sure on that.

**Pull request merged**
