### PR TITLE
BLD fix msvc compile errors

### PR DESCRIPTION
**Pull request by cgohlke**

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @cgohlke!

**Comment by rgommers** [comment]
@sturlamolden how did you manage to build with MSVC?

**Comment by sturlamolden** [comment]
Because my Windows computer did not have an internet connection. So when I pushed from git on my Mac I forgot to correct the typo again. Sorry :disappointed:

**Comment by rgommers** [comment]
Makes sense, no worries. It does show that we really need to get some Windows CI set up soon.....

**Comment by rgommers** [comment]
Merged, and forward ported to master in c574d7c. Thanks Christoph.

**Comment by sturlamolden** [comment]
Thank you :)

**Pull request merged**
