### PR TITLE
STY: Align tables to the left

### LINKED ISSUE #10642: DOC/WEB: special: Strange indentation for some functions.
In the online documentation, the list of "Faster versions of common Bessel Functions" is indented 16 or so characters, unlike the rest of the functions.  Take a look at https://docs.scipy.org/doc/scipy/reference/special.html#bessel-functions

That web page is generated by Sphinx from the module docstring in https://github.com/scipy/scipy/blob/master/scipy/special/__init__.py.  I don't see anything obviously different in the section on the faster Bessel functions.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #10642

### CODE REVIEW

**Comment by larsoner** [comment]
All better

https://14621-1460385-gh.circle-artifacts.com/0/html-scipyorg/special.html#bessel-functions

**Comment by person142** [comment]
Thanks Eric.

**Comment by WarrenWeckesser** [comment]
Thanks Eric!

Now, if we could just get the first cell in the table to have top alignment to handle the rare cases where the second cell requires more than one line... 😄

**Comment by larsoner** [comment]
This is probably doable in CSS, is there an example on that page? If not, can you link to one?

**Comment by WarrenWeckesser** [comment]
`kolmogorov` and `multigammaln`, for example.

**Comment by WarrenWeckesser** [comment]
Actually, all you have to do is make the width of your browser small enough to force many of the "one-line" descriptions to require more than one line in the table.

**Comment by larsoner** [comment]
@WarrenWeckesser yes I had to do this even after your suggestion :)

https://github.com/scipy/scipy-sphinx-theme/pull/14 probably fixes it but I'd like to set up CircleCI over there so that artifacts can be viewed with the changes before we `submodule update` over here

**Pull request merged**
