### PR TITLE
BUG: Include Python.h before system headers.

### LINKED ISSUE #20491: BUG: Cannot find `OpenBLAS` on Cygwin
### Describe your issue.

While I try to use `pip3 install maryam` to install `maryam` in Cygwin, it keeps throwing the following error:
`../scipy/meson.build:169:9: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake`
because `maryam` depends on `scikit-learn` which depends on `scipy` ...

### Reproducing Code Example

Although I could reproduce the issue with `pip3 install maryam`, it is simpler to reproduce it with `pip3 install scipy` as follow.

<details>

```
yutta@SurfacePro9 /cygdrive/c/Users/yutta/eclipse-workspace/Maryam
$ pip3 list
Package                       Version
----------------------------- -------
attrs                         23.2.0
Babel                         2.12.1
build                         1.0.3
cffi                          1.16.0
chardet                       4.0.0
Cython                        0.29.33
docutils                      0.18.1
html5lib                      1.1
hypothesis                    6.35.0
idna                          3.3
imagesize                     1.3.0
iniconfig                     2.0.0
Jinja2                        3.1.2
lxml                          4.7.1
MarkupSafe                    2.1.2
meson                         1.2.3
nose3                         1.3.8
numpy                         1.21.4
olefile                       0.46
packaging                     21.3
Pillow                        8.4.0
pip                           24.0
pkgconfig                     1.5.5
platformdirs                  4.2.0
pluggy                        1.0.0
ply                           3.11
py                            1.11.0
pycparser                     2.21
Pygments                      2.10.0
pyparsing                     3.0.6
pytest                        7.3.0
python-dateutil               2.8.2
pytz                          2023.3
railroad-diagrams             3.0.1
requests                      2.31.0
setuptools                    69.2.0
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        4.4.0
sphinxcontrib-serializinghtml 1.1.5
toml                          0.10.2
urllib3                       1.26.7
webencodings                  0.5.1

yutta@SurfacePro9 /cygdrive/c/Users/yutta/eclipse-workspace/Maryam
$ pip3 install scipy
```

</details>

### Error message

```
      ../scipy/meson.build:163:9: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake
```

Full output:

<details>

```
Collecting scipy
  Using cached scipy-1.13.0.tar.gz (57.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      + meson setup /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83 /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83/.m
esonpy-y6vwx62o -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83/.mesonpy-y6vwx62o/meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83
      Build dir: /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83/.mesonpy-y6vwx62o
      Build type: native build
      Project name: scipy
      Project version: 1.13.0
      C compiler for the host machine: gcc (gcc 11.4.0 "gcc (GCC) 11.4.0")
      C linker for the host machine: gcc ld.bfd 2.42
      C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (GCC) 11.4.0")
      C++ linker for the host machine: c++ ld.bfd 2.42
      Cython compiler for the host machine: cython (cython 3.0.10)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Program python found: YES (/usr/bin/python3.9.exe)
      Found pkg-config: YES (/usr/bin/pkg-config) 2.2.0
      Run-time dependency python found: YES 3.9
      Program cython found: YES (/cygdrive/c/Users/yutta/AppData/Local/Temp/pip-build-env-kikt09he/overlay/bin/cython)
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 11.4.0 "GNU Fortran (GCC) 11.4.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.42
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: YES
      Program tools/generate_f2pymod.py found: YES (/usr/bin/python3.9.exe /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83/tools/generate_f2pymod.py)
      Program scipy/_build_utils/tempita.py found: YES (/usr/bin/python3.9.exe /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83/scipy/_build_utils/tempita.py)
      Program pythran found: YES 0.15.0 0.15.0 (/cygdrive/c/Users/yutta/AppData/Local/Temp/pip-build-env-kikt09he/overlay/bin/pythran)
      Found CMake: /usr/bin/cmake (3.28.3)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency xsimd found: NO (tried pkgconfig and cmake)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      pybind11-config found: YES (/cygdrive/c/Users/yutta/AppData/Local/Temp/pip-build-env-kikt09he/overlay/bin/pybind11-config) 2.12.0
      Run-time dependency pybind11 found: YES 2.12.0
      Run-time dependency scipy-openblas found: NO (tried pkgconfig)
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)

      ../scipy/meson.build:163:9: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake

      A full log can be found at /cygdrive/c/Users/yutta/AppData/Local/Temp/pip-install-mkkespja/scipy_16c06cfb07e24d2391b8c36c833c7d83/.mesonpy-y6vwx62o/meson-logs/meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

### SciPy/NumPy/Python version and system information

I install Cygwin in Windows 11 arm 64. For openblas, my Cygwin only has three packages: `libopenblas` , `openblas-debuginfo`, and `openblas-doc` with all version 0.3.25-1 . For Python, the `python39` package with version 3.9.16-1 install the following python and pip:
```
yutta@SurfacePro9 /cygdrive/c/Users/yutta/eclipse-workspace/Maryam
$ type python3.9
python3.9 is /usr/bin/python3.9

yutta@SurfacePro9 /cygdrive/c/Users/yutta/eclipse-workspace/Maryam
$ type pip3     
pip3 is hashed (/usr/bin/pip3)
```

### PR DESCRIPTION
**Pull request by DWesl**
#### Reference issue

Closes #20491

#### What does this implement/fix?

Python.h needs to be included before any system header: `_fmm_core.hpp` does, but is not first.

#### Additional information

The script from #20149 would not catch this.  I might need to add `pybind11::` to the regex.

### CODE REVIEW

**Comment by j-bowhay** [comment]
cc @alugowski

**Review by tylerjereddy — APPROVED** [review]
Glancing at the includes at the top of `fast_matrix_market/types.hpp` this seems obviously correct since https://docs.python.org/3/c-api/intro.html#include-files clearly notes:

> Since Python may define some pre-processor definitions which affect the standard headers on some systems, you must include Python.h before any standard headers are included.

Since the author of this C++ source actively helps us and has been pinged I'll leave it open for a bit.

**Comment by DWesl** [comment]
Found a few more trying to get everything built on Cygwin.

**Comment by DWesl** [comment]
DWesl/scipy#5 has a script to check for this and sets up a CI job to do so.  I've dropped the most likely false positives, leaving one instance in highspy that has since been removed in the upstream repository.  Should I add those changes to this PR, replace this PR with that one (possibly after telling it to ignore hishspy), squash-merge that PR onto the branch for this one, or something else?

**Comment by rgommers** [comment]
Thanks @DWesl! Could you please rebase?

Cc @steppi @izaid for visibility, since most of the issues were recently introduced in `scipy.special`. Please keep in mind that `Python.h` must always be included before any system headers.

**Comment by ev-br** [comment]
Just bumped into this recently: clang-format reorders the includes, and puts Python.h somewhere in the middle. At least with the  .clang-format file from scope/special/special

**Comment by izaid** [comment]
> Just bumped into this recently: clang-format reorders the includes, and puts Python.h somewhere in the middle. At least with the .clang-format file from scope/special/special

Yep, unless there is a line break between `Python.h` and other includes. Then it doesn't get reordering.

**Comment by rgommers** [comment]
Something is still unhappy:
```
[125/1443] Compiling C++ object scipy/special/_special_ufuncs.cp310-win_amd64.pyd.p/_special_ufuncs.cpp.obj
FAILED: scipy/special/_special_ufuncs.cp310-win_amd64.pyd.p/_special_ufuncs.cpp.obj 
"c++" "-Iscipy\special\_special_ufuncs.cp310-win_amd64.pyd.p" "-Iscipy\special" "-I..\scipy\special" "-Iscipy\_lib" "-I..\scipy\_lib" "-I..\scipy\_build_utils\src" "-IC:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\numpy\core\include" "-IC:\hostedtoolcache\windows\Python\3.10.11\x64\Include" "-fvisibility=hidden" "-fvisibility-inlines-hidden" "-fdiagnostics-color=always" "-D_GLIBCXX_ASSERTIONS=1" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c++17" "-O2" "-g" "-D__USE_MINGW_ANSI_STDIO=1" "-DMS_WIN64=" "-DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION" "-DSP_SPECFUN_ERROR" -MD -MQ scipy/special/_special_ufuncs.cp310-win_amd64.pyd.p/_special_ufuncs.cpp.obj -MF "scipy\special\_special_ufuncs.cp310-win_amd64.pyd.p\_special_ufuncs.cpp.obj.d" -o scipy/special/_special_ufuncs.cp310-win_amd64.pyd.p/_special_ufuncs.cpp.obj "-c" ../scipy/special/_special_ufuncs.cpp
In file included from ../scipy/special/_special_ufuncs.cpp:6:
../scipy/special/ufunc.h:19:13: error: redefinition of 'bool SpecFun_Initialize()'
```

**Comment by DWesl** [comment]
`Redefinition of function` errors tend to mean a header gets executed twice.  I removed the second include from the mentioned file and stuck a header guard in in case there's another.

**Comment by izaid** [comment]
> `Redefinition of function` errors tend to mean a header gets executed twice. I removed the second include from the mentioned file and stuck a header guard in in case there's another.
> 
> The recent trend seems to be toward `#pragma once` as a header guard, rather than `#ifndef SPECIAL_UFUNC_H`/`#define SPECIAL_UFUNC_H`, correct? Does the style guide prefer one over the other?

Yes, that's correct. I don't know where ufunc.h is getting included twice, but if putting `#pragma once` at the top fixes it then great.

**Comment by DWesl** [comment]
> I don't know where ufunc.h is getting included twice, but if putting `#pragma once` at the top fixes it then great.

It was `special/_special_ufuncs.cpp`, but that's gone now.  I could likely adapt the script in DWesl/scipy#5 to check for duplicate includes.

**Comment by charris** [comment]
> clang-format reorders the includes

NumPy .clang-format deals with putting the includes in the correct order. It is messy.

**Review by rgommers — APPROVED** [review]
LGTM and CI is all green now - in it goes. Thanks @DWesl & reviewers.

**Pull request merged**
