### PR TITLE
BENCH: add sparse null slice benchmark

### PR DESCRIPTION
**Pull request by argriffing**
Add a benchmark confirming the speedup of https://github.com/scipy/scipy/pull/4660.  In the following asv benchmarking output, the 'BEFORE' column is after the changes in that PR.

This PR also modifies the cython version number in the benchmarking config.

```
BENCHMARK                                    BEFORE      AFTER     FACTOR
sparse.NullSlice.time_3_cols(0.05)          19.34ms    66.46ms   3.43594979x
sparse.NullSlice.time_100_cols(0.05)        24.88ms    71.69ms   2.88185582x
sparse.NullSlice.time_3_cols(0.01)           6.19ms    15.95ms   2.57929385x
sparse.NullSlice.time_100_cols(0.01)         8.83ms    18.75ms   2.12319417x
sparse.NullSlice.time_10000_rows(0.05)       3.64ms     7.33ms   2.01544398x
sparse.NullSlice.time_10000_rows(0.01)       1.33ms     2.17ms   1.62602304x
sparse.NullSlice.time_3_rows(0.05)         334.09μs   423.13μs   1.26650273x
sparse.NullSlice.time_3_rows(0.01)         353.53μs   439.92μs   1.24438080x
```

### CODE REVIEW

**Comment by larsmans** [comment]
LGTM. Note: Cython version change is also in #4753, but the change is the same so Github should be able to figure out the merge.

**Comment by argriffing** [comment]
Is it generally agreed to move to Cython 0.22? If so, I'll merge this soon.

**Comment by rgommers** [comment]
I didn't see anyone not agreeing, so since we have 2 PRs to make the change it's the easiest thing to do now. So I'd say green button it if no one stops you in the next day or so.

**Comment by larsmans** [comment]
Merged, since this only changes the Cython requirement for the benchmark. That's sensible since 0.22 has quite a few new optimizations.

**Pull request merged**
