### PR TITLE
MAINT: Fix a couple mistakes in .pyf files.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Review by larsoner — APPROVED** [review]

**Comment by WarrenWeckesser** [comment]
Don't merge this yet.  There are a few more fixes for .pyf files that I'll add to this pull request.

**Comment by WarrenWeckesser** [comment]
OK, there were not as many additional changes as I thought, so this is ready.  Of course, the travis-ci test using numpy master will fail for unrelated reasons.

There is one other f2py/crackline issue, but one requires some more investigation.  I'll open up a separate issue for it.

**Comment by WarrenWeckesser** [comment]
@larsoner FYI: I snuck in another commit after you approved the PR.

**Comment by charris** [comment]
@WarrenWeckesser Do these fixes need a backport?

**Comment by WarrenWeckesser** [comment]
@charris No backport needed, I think.  f2py ignores the C-style comment (I guess it would ignore any line it doesn't understand), and in the case of the missing `end interface`, it treats the `end` as implied.

**Comment by ilayn** [comment]
LGTM. Clicked the button.

**Pull request merged**
