### PR TITLE
Pyodide patches : low-hanging fruits

### PR DESCRIPTION
**Pull request by ev-br**
#### Reference issue

gh-17413

#### What does this implement/fix?

Apply three easy-fix patches from those pyodide carries for scipy. 

#### Additional information

There are three independent commits, all attributed to @hoodmane who authored the patches

- the scipy.stats file rename looks specific for the pyodide process, but does not seem to cause us any harm, so why not.
- the id_decompositon patch: why on Earth it needs an extra `END` is beyond me, but again --- if it fixes the build for pyodide and does not cause us harm, why not.
- the odepack error handling patch is also a bit weird. The whole xerrwv.f code looks very much Fortran'66 (also walks and quacks like Fortran'66). The int-to-character conversion IIUC predates characters in strings in Fortran (yes); This is the first time I see `character m*1` --- was used to `character*1 m` but this link seems to claim the two forms are identical
https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn7r/index.html

Strictly speaking, the last change is also not entirely correct: it is used with more than one character. However, this was not causing harm anywhere before, so let’s keep the minimal patch which makes it build on pyodide.
ODEPACK does not seem to have an active upstream, so just apply the patch

cc @hoodmane @rgommers

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
> the scipy.stats file rename looks specific for the pyodide process, but does not seem to cause us any harm, so why not.

I'd like to know more about this.  Why does pyiodide require a trailing underscore for this particular filename?  As you say, it is probably harmless, but it makes *our* process subject to a unexplained external constraint, which seems undesirable.

**Comment by ev-br** [comment]
https://github.com/hoodmane/pyodide/blob/main/packages/scipy/patches/0009-Rename-_page_trend_test.py-to-prevent-test-unvendori.patch

mentions some "unvendoring"; looks like they remove files with names ending in _test. Shrug.

**Comment by WarrenWeckesser** [comment]
I don't know what that means.  Are they trying to filter out unit tests from their installation?  In the absence of more information, I'd say let pyodide deal with such quirks in their build system.  Or, let's get an explicit explanation of what the problem is, so we can evaluate if it makes sense for us to adopt a filename policy that helps projects such as pyodide (ping @hoodmane).

**Comment by hoodmane** [comment]
Hi @ev-br thanks for doing this. I am not sure that I am in favor of these patches being upstreamed because there is a decent argument that they are incorrect.

1. The issue is indeed that we want to minimize download size so we have a dumb script to remove test files. I think we ought to make our build system more flexible but in the ~150 packages we ship this file is the only file we're renaming so we haven't bothered yet. Still doesn't mean scipy should upstream it...
2. No clue here this is some strange bug in f2c which I've never made any attempt to understand. I make PR  #15954 making this change before but it was rejected as incorrect. I think this was the correct thing to do.
3. We use CLAPACK which has been manually stripped of fortran_len arguments emitted by f2c so most string arguments need to be changed to int. But a few functions are exceptions and need to have their int arguments converted to char for reasons I cannot recall... I think I triangulated this by making many different changes and looking at the emitted c code until it looked right. For whatever reason this works.


The way that someone described Pyodide's process for compiling fortran is we point f2c at it and then bang our heads on our keyboards until the errors go away. I would say that:
1. There are good arguments that the scipy project should not accept these patches.
2. Upgrading takes hours of keyboard head banging. Migrating these patches only takes a few minutes. Our horrible upgrade process can only be fixed with a working llvm fortran compiler.

So I appreciate the help but I don't think these patches ought to be upstreamed.

**Comment by WarrenWeckesser** [comment]
@hoodmane, thanks for the feedback.

Your comment about https://github.com/scipy/scipy/pull/15954 prompted me to take another look.  It turns out that the addition of the final `end` in a file of subroutines such as `prini.f` is acceptable to both `gfortran` and `ifort`.  (I added a [comment](https://github.com/scipy/scipy/pull/15954#issuecomment-1312762767) about this in that PR.)  And the fact that all the tests for this PR passed means that it is, in fact, a harmless change for SciPy.  Perhaps the main reason for not making the change now is that it is a change to a vendored library, and we have a preference for minimizing the number of such changes.

**Comment by ev-br** [comment]
Okay, thanks for the discussion @WarrenWeckesser and @hoodmane. Let's reject this PR then. I'll update the tracker gh-17413, would be nice if you comment on the other ones in there @hoodmane

**Pull request closed without merging**
