### PR TITLE
BUG: sparse: Ensure correct dtype for sparse comparison operations.

### PR DESCRIPTION
**Pull request by perimosocordiae**
Fixes gh-8833. The first commit updates the tests to verify that the bug exists.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Test failures are unrelated:

```
scipy.stats.linregress
----------------------
File "build/testenv/lib/python3.5/site-packages/scipy/stats/_stats_mstats_common.py", line 59, in linregress
Failed example:
    print("r-squared:", r_value**2)
Expected:
    r-squared: 0.08040226853902833
Got:
    r-squared: 0.08040226853902838
==================
scipy.stats.mstats
==================
scipy.stats.mstats.linregress
-----------------------------
File "build/testenv/lib/python3.5/site-packages/scipy/stats/mstats_basic.py", line 744, in linregress
Failed example:
    print("r-squared:", r_value**2)
Expected:
    r-squared: 0.08040226853902833
Got:
    r-squared: 0.08040226853902838
ERROR: refguide or doctests have errors
```

**Comment by WarrenWeckesser** [comment]
FYI: I created https://github.com/scipy/scipy/pull/8839 to deal with those unrelated refguide test failuers.

**Comment by WarrenWeckesser** [comment]
Several of the lines now exceed 79 characters.  Could you fix those?  Other than that, this looks good.  Thanks!

**Comment by WarrenWeckesser** [comment]
Thanks CJ.

Just curious: why is your first commit under the name "CJ Carey", but the next two are under "perimosocordiae"?  Was that intentional?

**Comment by perimosocordiae** [comment]
I made the first commit from a new machine before setting up my global git
email/username. I'm not sure if it's worth trying to reattribute that
commit to my GitHub account.

**Comment by WarrenWeckesser** [comment]
Maybe a git guru will know a quick way to update that name, so I'll give this a day or so before merging.

**Comment by ilayn** [comment]
I think if you squash and merge then it will be squashed to the last commit and disappear.

**Comment by pv** [comment]
Thanks, merged.

**Pull request merged**
