### PR TITLE
MRG: Add circle-CI

### LINKED ISSUE #6129: ENH: CircleCI for doc building
The CircleCI service can be used to build docs for each PR, leaving behind artifacts like doc build results. See from a PR build for another repo:

https://circle-artifacts.com/gh/mne-tools/mne-python/907/artifacts/0/home/ubuntu/mne-python/doc/_build/html/index.html

It seems like it would make reviewing PRs that touch docs (e.g., #3954) easier to review.

I'm up for trying to implement this if people think it's worthwhile.

### PR DESCRIPTION
**Pull request by larsoner**
Add CircleCI doc building, with an artifact of the new docs. This should hopefully make it easier for e.g. @rgommers to critique my mediocre docstring plots.

Closes #6129.

Produces this:

https://circle-artifacts.com/gh/Eric89GXL/scipy/27/artifacts/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.signal.remez.html#scipy.signal.remez

### CODE REVIEW

**Comment by rgommers** [comment]
That looks good, thanks Eric!

1500 build minutes a month may be borderline, but we'll see how far we get with a free account I guess.

**Comment by Eric89GXL** [comment]
I've been using it on another repo for a couple of months with fewer PRs/commits but probably longer build times and so far we've been okay, so I'm optimistic. I'll go ahead and merge and activate in a couple of days unless there are other comments.

**Comment by rgommers** [comment]
For reference, here is the TravisCI artifacts support: https://docs.travis-ci.com/user/uploading-artifacts/. Summary: it doesn't store artifacts, only supports uploading to Amazon S3. Hence CircleCI is better in this regard.

We currently only build the docs after a PR is merged (to update the dev docs on docs.scipy.org).

**Comment by rgommers** [comment]
in it goes, thanks @Eric89GXL

**Comment by Eric89GXL** [comment]
@rgommers can you enable CircleCI on their website? I don't think I have sufficient permissions

**Comment by rgommers** [comment]
done, building at https://circleci.com/gh/scipy/scipy/1 now

**Comment by rgommers** [comment]
Eh, make that failed at https://circleci.com/gh/scipy/scipy/1

    Reading state information... Done

    Note, selecting 'libpng12-dev' instead of 'libpng-dev'
    libatlas-base-dev is already the newest version.
    libatlas-dev is already the newest version.
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     liblapack-dev : Depends: liblapack3 (= 3.5.0-2ubuntu1) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

    sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libfreetype6-dev libpng-dev zlib1g-dev texlive-fonts-recommended returned exit code 100

    Action failed: sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libfreetype6-dev libpng-dev zlib1g-dev texlive-fonts-recommended

**Comment by Eric89GXL** [comment]
Oh yeah, can you also set it to use 14.04 instead of 12.04? It's in the
settings for the project on CirceCI

**Comment by Eric89GXL** [comment]
Looks like I had permission to change it, so I did. Next build will hopefully work.

**Comment by Eric89GXL** [comment]
I rebased and push forced https://github.com/scipy/scipy/pull/5989 so hopefully we see it work there

**Comment by rgommers** [comment]
Worked like a charm this time.

**Comment by pv** [comment]
Doesn't seem to be working now:
https://circleci.com/gh/scipy/scipy/5
https://circleci.com/gh/scipy/scipy/8

**Comment by pv** [comment]
Or maybe it just needs rebases.

**Comment by Eric89GXL** [comment]
Yeah it looks like it doesn't build the merge version which is surprising.

**Pull request merged**
