### PR TITLE
Fix typos in comments, docs and test names

### PR DESCRIPTION
**Pull request by minho42**

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]
All changes look correct and I don't expect any to affect functionality (unless `testNamedAtributes` was referenced elsewhere with the misspelling).

**Comment by pv** [comment]
The files under `ARPACK`, `SuperLU`, `qhull_src` should preferably not be changed.

**Comment by mdhaber** [comment]
@minho42 if you revert the changes to those files I can merge this.

**Comment by minho42** [comment]
@mdhaber 
I made another PR with typos in bundles libraries reverted.

**Pull request closed without merging**
