### PR TITLE
ENH: Implemented custom mutation / crossover functions for DifferentialEvolution

### PR DESCRIPTION
**Pull request by andyfaff**
replaces #19196

Implements custom user-specified mutation / crossover functions for DifferentialEvolution

@enn-nafnlaus

### CODE REVIEW

**Comment by andyfaff** [comment]
I tried to keep authorship of original work in first commit. I had to squash commits down to make things easier to work with.

**Comment by enn-nafnlaus** [comment]
> I tried to keep authorship of original work in first commit. I had to squash commits down to make things easier to work with.

I greatly appreciate all you did!  :)

**Comment by j-bowhay** [comment]
Perhaps I am overlooking something but I find it slightly confusing to now have two arguments to control the strategy, why could `strategy` not be adapted to take a callable?

**Comment by enn-nafnlaus** [comment]
I'm fine with either approach.

sun., 10. sep. 2023 kl. 14:09 skrifaði Jake Bowhay ***@***.***

**Comment by andyfaff** [comment]
>  why could strategy not be adapted to take a callable?

It can be, but I'm just wary of overloading arguments.

**Comment by andyfaff** [comment]
Thank you @enn-nafnlaus

**Comment by enn-nafnlaus** [comment]
No, thank you!  :)

mán., 11. sep. 2023 kl. 05:39 skrifaði Andrew Nelson <
***@***.***>:

**Pull request merged**
