### PR TITLE
CI: remove .travis.yml, remove codecov from CircleCI

### PR DESCRIPTION
**Pull request by rgommers**
We haven't used TravisCI in 3 months, content has been migrated to Azure and things are working well. So it's time to remove `.travis.yml`.

I also audited all our CI for codecov usage given the recent [Codecov security incident](https://about.codecov.io/security-update). The `codecov` Python package luckily was not affected, see https://github.com/codecov/codecov-python/issues/316. We only use the Bash uploader (which had the security issue) in Azure, but we don't have any SSH keys or tokens there.

Given that we don't use `codecov` in CircleCI, it's still better to remove it there - we do have a deploy key there.

The `runtests.py` flags cleanup is no change in behavior, just a clearer way of spelling the same thing.

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
All sounds good to me, +1 for merge

**Review by ilayn — APPROVED** [review]

**Review by tupui — APPROVED** [review]
Do we plan to have another coverage metric in CI?

**Comment by rgommers** [comment]
> Do we plan to have another coverage metric in CI?

The one we actually use is in Azure, and I am not changing it here.

**Comment by tupui** [comment]
> The one we actually use is in Azure, and I am not changing it here.

Indeed, I did not notice as I did not see it complain yet.

**Review by tylerjereddy — APPROVED** [review]
Clear improvement, so merging, thanks Ralf et al.

**Pull request merged**
