### PR TITLE
MAINT: better UNU.RAN licensing information

### PR DESCRIPTION
**Pull request by tupui**
* Update UNU.RAN following licensing updates from https://github.com/scipy/unuran/pull/4
* Add UNU.RAN to the license bundled file

@tylerjereddy marking this one as well. Same as the other one, up to you to decide what to do in this situation.

### CODE REVIEW

**Review by mdhaber — APPROVED** [review]

**Comment by tirthasheshpatel** [comment]
Submitted https://github.com/scipy/unuran/pull/5

**Comment by mdhaber** [comment]
@tupui if you merge http://scipy/unuran#5 and update the submodule here, I'll merge this one.

**Comment by tupui** [comment]
Done, thanks all for the reactivity 💪

**Comment by tirthasheshpatel** [comment]
Can you run the CI to confirm the UNU.RAN code is still working? I removed the GPL references through a search and replace so, small chances of something slipping through that might have edited unintended source code.

**Comment by mdhaber** [comment]
Prerelease has been timing out. All tests passing, so merging.

**Pull request merged**
