### PR TITLE
DOC: `signal.correlate`: fix typo in correlation formula

### PR DESCRIPTION
**Pull request by ConnorCastleberry**
Fixed typo in docs code snippet. The opening parenthesis was missing when using the function sum().

### CODE REVIEW

**Comment by tupui** [comment]
Hey @ConnorCastleberry 👋 you seem to have an issue with the commit history of your PR. Could you maybe rebase your changes on the current main branch? Alternatively feel free to close this and open a new PR. Thanks 🙏

**Comment by lucascolley** [comment]
In this case, given that the change is just 1 character, it's likely easier to make a new PR :+1:

**Review by j-bowhay — CHANGES_REQUESTED** [review]
Thanks @ConnorCastleberry for your first contribution!

I am not sure this change is quite correct as now there is no closing bracket. I don't think this line is intended to be valid python so I don't know if a change is required. Let's see what other maintainers think

**Comment by ev-br** [comment]
+1 to what Jake said. This was pseudocode and adding a mismatched bracket does not make it that much better. Maybe best is to actually spell out (in pseudocode or a proper math notation) what the summation is over `i_l`. With or without a matching pair of brackets.

**Comment by lucascolley** [comment]
> Maybe best is to actually spell out (in pseudocode or a proper math notation) what the summation is over i_l. With or without a matching pair of brackets.

Yes, this sounds right to me. It looks to me that this is capturing [the following equation](https://en.wikipedia.org/wiki/Cross-correlation#Cross-correlation_of_deterministic_signals) in array notation:

image

Would you like to have a go at rewriting this in [Sphinx Math notation](https://sphinx-rtd-trial.readthedocs.io/en/latest/ext/math.html) @ConnorCastleberry ?

**Comment by j-bowhay** [comment]
@ConnorCastleberry would you be interested in making the suggested changes?

**Comment by j-bowhay** [comment]
Closing for now however you are very welcome to reopen if you return to this

**Pull request closed without merging**
