### PR TITLE
ENH: simplify `gausshyper.pdf`

### PR DESCRIPTION
**Pull request by dschmitz89**
#### Reference issue
Part of #10106 and #17832
 
#### What does this implement/fix?
There is no analytical expression available for the gausshyper distribution PPF. To make things worse, implementing the CDF is not possible without high precision codes for Appel's hypergeometric functions (see #18056). That means that the default random variate generation goes through numerical integration to calculate the CDF and then inverts it via a rootfinder. At least the quadrature integration can be speeded up by providing a lowlevel callable of the PDF in cython.

I pretty much blindly copied the approach from the genhyperbolic distribution implemented in #18134.

#### Additional information

I did not further check the accuracy of the PDF in the tails, here I focussed on performance only. Locally, this passed the generic distribution tests for me at least. Going via the logpdf could be done in a follow up.

Benchmark:

```python
import numpy as np
from scipy import stats
from time import time

a, b, c, z = 1.5, 2.5, 2, 0

gh = stats.gausshyper(a=a, b=b, c=c, z=z)

x = np.linspace(0, 1, 1000)
t0 = time()
cdf_vals = gh.cdf(x)
print(f"Time for 1000 CDF values: {time() - t0}")

t0 = time()
samples = gh.rvs(size=1000)
print(f"Time for 1000 samples: {time() - t0}")
``` 

*This PR*:
Time for 1000 CDF values: 0.03378629684448242
Time for 1000 samples: 1.2594482898712158

*Main*:
Time for 1000 CDF values: 0.8763303756713867
Time for 1000 samples: 8.12756633758545

Sampling is still not "fast" but at least faster. Maybe with a vectorized rootfinder (#17719), the PPF calculation will become much faster in future.

### CODE REVIEW

**Comment by mdhaber** [comment]
[_tanhsinh](https://github.com/scipy/scipy/pull/18650) provides a speedup 3.7x speedup even for individual evaluations of this function's CDF, and it will be vectorized following the approach of [_chandrupatla](https://github.com/scipy/scipy/pull/18728). For vectorized calls, I've seen `_chandrupatla` be [440x faster](https://github.com/scipy/scipy/pull/18728#issuecomment-1612483600) than `scipy.optimize.brent` even though individual evaluations take twice as long. So if we can wait until the end of the summer, during which I'm working on gh-15928, I think we can get a substantial speed boost without any special effort.

**Comment by dschmitz89** [comment]
> 

Sounds like awesome times are coming for `scipy.stats`!

For the fun of it, what effect does changing

`Cinv = sc.gamma(a) * sc.gamma(b) / sc.gamma(a + b) * sc.hyp2f1(c, a, a + b, -z)` to

`Cinv = sc.beta(a, b) * sc.hyp2f1(c, a, a + b, -z)` have on the timing with the new integrator? I thought this could reduce some inaccuracy.

**Comment by mdhaber** [comment]
Actually, we can reduce some inaccuracy just by using `_tanhsinh`. Code comparing against mpmath updated above.
```
Speedup: 7.49806608190174
gmean of relative error (quad): 7.961428032643411e-16
gmean of relative error (tanhsinh): 4.46206718903016e-16
max relative error (quad): 1.1235272457145405e-07
max relative error (tanhsinh): 1.445515587446478e-13
```

**Comment by dschmitz89** [comment]
I will add some tests against the analytical CDF expression implemented in mpmath over the next days as I have started to doubt mpmath's quadrature results sometimes.

**Comment by mdhaber** [comment]
I've seen inaccuracy for entropy calculations when `dps` is not high enough. I do not doubt it in general when the methods agree with one another, `dps` is sufficiently high, and there is convergence as `dps` is increased.

I agree that it may not be fair to compare `_tanhsinh` against `mpmath`'s tanh-sinh implementation. But `_tanhsinh` still has less error when comparing against mpmath's Gauss-Legendre.
```
gmean of relative error (quad): 5.981882710120695e-10
gmean of relative error (tanhsinh): 5.91909957455664e-10
max relative error (quad): 1.1201215834892658e-07
max relative error (tanhsinh): 1.155285199503168e-09
```

Using `beta` is a bit faster.
```
Time for 1000 CDF value (main): 1.1051812999940012
Time for 1000 CDF values (_tanhsinh): 0.1437306999869179
Speedup: 7.689250105193899
```

**Comment by ilayn** [comment]
I can help with the speed up this code, since np.vectorize is a glorified for loop still in Python side. But I'm not sure I understand what the code is doing. The `x` is an array and the rest are doubles? Then we can speed this up much faster. Not sure if you want to though, Matt's comment notwithstanding about the summer work.

**Comment by dschmitz89** [comment]
> I can help with the speed up this code, since np.vectorize is a glorified for loop still in Python side. But I'm not sure I understand what the code is doing. The `x` is an array and the rest are doubles? Then we can speed this up much faster. Not sure if you want to though, Matt's comment notwithstanding about the summer work.

Thanks for the offer. If you have an idea how to speed up the integration more by some cython magic, I am all ears. The `gausshyper.pdf` method is not so performance critical on the other hand.

**Comment by dschmitz89** [comment]
`quad` results in CDF values > 1 for certain parameter regions for this distribution.

```
from scipy.stats import gausshyper

x, a, b, c, z = 0.999999, 1.5, 2.5, 2, -0.5

gausshyper.cdf(x, a, b, c, z)
#1.000000000000055
```

@mdhaber : if the new integrator does better in this case, let's close this PR. I understood that its relative error was anyway much lower .

**Comment by mdhaber** [comment]
I wouldn't consider that a dealbreaker, since the result is very close to one and can just be clipped, but:
```
QuadratureResult(integral=0.9999999999999949, error=2.4863916783069763e-16, feval=130, success=True, status=0, message='The algorithm completed successfully, and the error estimate meets the requested tolerance.')
```

**Comment by mdhaber** [comment]
I vectorized `tanhsinh`. Now, re-running the benchmark with `cdf_vals2 = _tanhsinh2(_pdf, 0, x).integral` in place of the list comprehension:

```python3
Time for 1000 CDF value (main): 1.0867439999710768
Time for 1000 CDF values (_tanhsinh): 0.005081499926745892
Speedup: 213.8628388541589
gmean of relative error (quad): 7.961428032643411e-16
gmean of relative error (tanhsinh): 4.46206718903016e-16
max relative error (quad): 1.1235272457145405e-07
max relative error (tanhsinh): 1.445515587446478e-13
```
That's a factor of 213.86 compared to 25.9 reported in the top post.

Then for the random samples, using the scalar root finder from gh-17719
```python3
from scipy.optimize._zeros_py import _chandrupatla
rng = np.random.default_rng(8346584583456)
f = lambda x, p: _tanhsinh2(_pdf, 0, x).integral - p
tic = perf_counter()
p = rng.random(1000)
res = _chandrupatla(f, 0, 1, args=(p,))
toc = perf_counter()
print(f"Time for 1000 observations: {toc-tic}")
# Time for 1000 observations: 0.05970019998494536

tic = perf_counter()
samples = gh.rvs(size=1000)
toc = perf_counter()
print(f"Time for 1000 observations (main): {toc-tic}")
Time for 1000 observations (main): 10.13877489999868
```
That's a factor of 169.8 compared to 6.45 reported in the top post.

Re: https://github.com/scipy/scipy/pull/18799#issuecomment-1615168197, it is indeed probably possible to beat these pure-Python solutions if the integrand and all the loops are brought into C++, so if that speed is needed, I'd be happy for it to happen. I just thought I should mention the speedups we will get for free pretty soon.

**Comment by tupui** [comment]
Looks like the CDF part might not be wanted then, but what about the PDF and other additions? This still seems to have value no?

**Comment by dschmitz89** [comment]
Doing the whole integration in cython seems unnecessary then definitely.

Regarding @tupui 's comment there are two things that can be done in my opinion:

- easy: replacing `sc.gamma(a)*sc.gamma(b)/sc.gamma(a+b)` by `sc.beta(a, b)` for simplification
- harder: potentially implementing the PDF as a ufunc using the machinery from `special`. That should yield some performance improvement also using the new vectorized integrator.

Any opinions?

**Comment by mdhaber** [comment]
I'd suggest just doing the easy thing for now. The existing tests are (hopefully) strong enough to detect a mistake, so you shouldn't need any tests if the intent is just simplification.
@tirthasheshpatel and @steppi are working on something that will make it much easier to do the harder thing.

>  This still seems to have value no?

The short answer is no, as is. You can see that the PR as-is replaces a natively vectorized PDF with one that uses `@np.vectorize`. That can't be good for the pdf.

**Comment by tupui** [comment]
> > This still seems to have value no?
> 
> The short answer is not really, as-is. You can see that the PR (as-is) replaces a natively vectorized PDF with one that uses `@np.vectorize`. That can't be good for the pdf. The idea of replacing the ratio of gammas with beta is good, but that doesn't really preserve much that's here.

I am really talking about the Cython part here, not the Python.

**Review by mdhaber — APPROVED** [review]
If the style is going to change, I'd prefer to keep it self consistent (e.g. `1.` or `1.0` throughout). It would also be nice to avoid the line continuation, which is easy with a slightly shorter variable name (e.g. `normalization`). It would also be OK to leave them all that alone to reduce the diff. But to avoid further delay, I'll merge once tests finish.

**Pull request merged**
