### PR TITLE
csgraph Dijkstra function description rewording

### PR DESCRIPTION
**Pull request by tretherington**
Having exchanged emails with @jakevdp about this, I'm just suggestion a rewording of the function description to clarify how directionality is controlled.
[Apologies if I'm not following due process - my first ever pull request!]

### CODE REVIEW

**Comment by tretherington** [comment]
Apologies for the style mistake, I've now replaced the tabs with spaces.

**Comment by jakevdp** [comment]
Sorry, quick question: isn't this change a bit redundant? Since i can be any value and j can be any value, why repeat them in a different order?

**Comment by ilayn** [comment]
I guess the text can be a bit less technical but clearer. Something along the lines of 

    directed : bool, optional
        If True, the edges are directed and csgraph[j, i] is not considered for moving
        from j to i. Otherwise, the order does not matter and the shortest path is
        selected between csgraph[i, j] and csgraph[j, i].

I don't know if this is technically correct but actually tells something about the constraint rather than the underlying code indices.

**Comment by tretherington** [comment]
I think this comes down to a difference in the way someone might envisage their graph.

For me, I'm used to doing graph theory through NetworkX, where I initiate a bunch of nodes [i, j, k, ...] and then initiate the edges [(i,j), (j,k), (k,i),...] rather than creating a matrix.  In this approach where I envisage the graph as points connected by lines the node labels are fixed as it were, so when I read "find the shortest path on a directed graph: **only** move from point i to point j along paths csgraph[i, j]" I took that to mean that there could only be a one-way directional relationship between nodes i and j.

Of course, as Jake points out, as the function uses a matrix to define the connectivity, this means that each node becomes i at some point, so there is nothing incorrect with the original description, and rather it was my lack of familiarity with using a matrix approach to describe a graph that caused my problem.

Given my misunderstanding was a result of my own limitations, I sat and thought about this for a while before suggesting a change.  But in the end I thought my experience might be valid to others, and that a little bit of redundancy in the description might be a good price to pay if it increases the clarity of the description of Jake's awesome code for other potential users like me?

**Comment by ilayn** [comment]
That can all be true. Please take my comment only about the sentence flow. It can be as technical as possible if needed. I would think that instead trying to read through the indices it might be easier to explain the boolean instead. If more details are needed `Notes` section is better to perform a more detailed description.

**Comment by tretherington** [comment]
I think @ilayn makes a good suggestion about more detailed descriptions being better positioned elsewhere.  So I have suggested some additions to the csgraph documentation pages instead, that will serve the same purpose but even better as it allows an explicit illustration of how directionality is handled.  I'm also reminded that this is applicable to all the graph functions, so is probably best located in a position 'above' all the functions, rather than within a single one.

(Apologies in advance if my blundering first use of pull requests causes any problems!)

**Comment by rgommers** [comment]
> Apologies in advance if my blundering first use of pull requests causes any problems!

No worries, discussion and subsequent PR updates are expected, all good so far:)

Looking at the commits in your PR, the one thing to change next time is to avoid adding merge commits. Better to just add commits directly to the branch that you sent the PR from.

**Comment by rgommers** [comment]
Added content in module docstring looks clear, and no more comments on the now minor tweak to the `shortest_path` docstring, so merging. Thanks @tretherington, all

**Pull request merged**
