### PR TITLE
Added correct plotting code for two sided output from spectrogram

### PR DESCRIPTION
**Pull request by josephmernst**
The example code only works for one-sided spectrograms.  I added an example for two sided spectrograms.

### CODE REVIEW

**Comment by rgommers** [comment]
@josephmernst why is there noise in the right half of the image in the example plot you linked? The two-sided spectrogram should just be a symmetric version in frequency space of the one-sided plot right?

**Comment by larsoner** [comment]
It looks like the fftshift if being applied along the wrong axis (-1 instead of 0)

**Comment by larsoner** [comment]
I just pushed a tiny commit to fix a PEP8 error. Otherwise looks good, +1 for merge from my end

**Comment by josephmernst** [comment]
great, thanks!

**Pull request merged**
