### PR TITLE
ENH: optimize: Add TFQMR method to approximate the inverse of the Jacobian in "Newton-Krylov" and "root"

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

In this PR, just like GMRES etc., TFQMR method can be used to approximate the inverse of the Jacobian in the process of solving nonlinear equations using Newton-Krylov method and finding root.

### CODE REVIEW

**Comment by zhaog6** [comment]
Dear Andrew @andyfaff , Could you review the PR? Thanks.

**Comment by andyfaff** [comment]
I'm not familiar with that code (or the maths behind it), so I'm not best placed to review this PR. @mdhaber, @pv you'd be better placed than me.

(I note there's no tests with this PR).

**Comment by mdhaber** [comment]
Thanks for the contribution, @zhaog6 , but I am not familiar with it either. Maybe it would help find a reviewer if you would point out where (in code and primary source documents, like the original papers or a texbook) supports this.

**Comment by tylerjereddy** [comment]
A bit of a fishing expedition, but @ev-br and @AtsushiSakai also show up in some flanking lines of the `git blame` so could try asking them.

**Comment by zhaog6** [comment]
Thanks all @andyfaff @mdhaber @tylerjereddy for your suggestions, I added some test cases and I will contact Pauli@pv

**Comment by zhaog6** [comment]
Dear Pauli @pv ,Could you review this PR? Thanks.

**Comment by rgommers** [comment]
Closed because this PR is continued in gh-15981.

**Pull request closed without merging**
