### PR TITLE
BLD: Add const to Cython signatures for BLAS/LAPACK

### LINKED ISSUE #14262: cython_blas does not use const in signatures
Usually, BLAS interfaces for C use function signatures with const qualifiers - examples:
```c
void F77_daxpy( FINT, const double *, const double *, FINT, double *, FINT);
```
```c
F77_NAME(daxpy)(const int *n, const double *da,
		const double *dx, const int *incx,
		double *dy, const int *incy);
```

However, the Cython `pxd` file for `cython_blas` generates the function signatures **without** `const` qualifier:
```python
cdef void daxpy(int *n, d *da, d *dx, int *incx, d *dy, int *incy) nogil
```

Which makes it harder to wrap into existing programs if they are using `const`.

### PR DESCRIPTION
**Pull request by lysnikolaou**
#### Reference issue

Closes gh-14262.

#### What does this implement/fix?

Use regex to parse CBLAS/LAPACK headers to infer whether an argument is const or not.

#### Notes
This uses LAPACK 3.7.1 in order to regenerate all the signatures. As a welcome side-effect, new functions are being wrapped now.

<details>
<summary>New BLAS symbols</summary>

```
xerbla_array
```

</details>

<details>
<summary>New LAPACK symbols</summary>

```
cgejsv
cgelq
cgelqt
cgelqt3
cgemlq
cgemlqt
cgemqr
cgeqr
cgesvdx
cgesvj
cgetrf2
cgetsls
cgges3
cggev3
cgghd3
cggsvd3
cggsvp3
cgsvj0
cgsvj1
chb2st_kernels
chbev_2stage
chbevd_2stage
chbevx_2stage
checon_3
checon_rook
cheev_2stage
cheevd_2stage
cheevr_2stage
cheevx_2stage
chegv_2stage
chesv_aa
chesv_rk
chesv_rook
chetf2_rk
chetf2_rook
chetrd_2stage
chetrd_he2hb
chetrf_aa
chetrf_rk
chetrf_rook
chetri_3
chetri_3x
chetri_rook
chetrs_3
chetrs_aa
chetrs_rook
clahef_aa
clahef_rk
clahef_rook
clamswlq
clamtsqr
clarfy
claswlq
clasyf_aa
clasyf_rk
clasyf_rook
clatsqr
cpotrf2
csycon_3
csycon_rook
csyconvf
csyconvf_rook
csysv_aa
csysv_rk
csysv_rook
csytf2_rk
csytf2_rook
csytrf_aa
csytrf_rk
csytrf_rook
csytri_3
csytri_3x
csytri_rook
csytrs_3
csytrs_aa
csytrs_rook
ctplqt
ctplqt2
ctpmlqt
ctrevc3
cunbdb1
cunbdb2
cunbdb3
cunbdb4
cunbdb5
cunbdb6
cuncsd2by1
cunm22
dgelq
dgelqt
dgelqt3
dgemlq
dgemlqt
dgemqr
dgeqr
dgesvdx
dgetrf2
dgetsls
dgges3
dggev3
dgghd3
dggsvd3
dggsvp3
dlamswlq
dlamtsqr
dlarfy
dlasq5
dlaswlq
dlasyf_aa
dlasyf_rk
dlasyf_rook
dlatsqr
dorbdb1
dorbdb2
dorbdb3
dorbdb4
dorbdb5
dorbdb6
dorcsd2by1
dorm22
dpotrf2
dsb2st_kernels
dsbev_2stage
dsbevd_2stage
dsbevx_2stage
dsycon_3
dsycon_rook
dsyconvf
dsyconvf_rook
dsyev_2stage
dsyevd_2stage
dsyevr_2stage
dsyevx_2stage
dsygv_2stage
dsysv_aa
dsysv_rk
dsysv_rook
dsytf2_rk
dsytf2_rook
dsytrd_2stage
dsytrd_sy2sb
dsytrf_aa
dsytrf_rk
dsytrf_rook
dsytri_3
dsytri_3x
dsytri_rook
dsytrs_3
dsytrs_aa
dsytrs_rook
dtplqt
dtplqt2
dtpmlqt
sgelq
sgelqt
sgelqt3
sgemlq
sgemlqt
sgemqr
sgeqr
sgesvdx
sgetrf2
sgetsls
sgges3
sggev3
sgghd3
sggsvd3
sggsvp3
slamswlq
slamtsqr
slarfy
slasq5
slaswlq
slasyf_aa
slasyf_rk
slasyf_rook
slatsqr
sorbdb1
sorbdb2
sorbdb3
sorbdb4
sorbdb5
sorbdb6
sorcsd2by1
sorm22
spotrf2
ssb2st_kernels
ssbev_2stage
ssbevd_2stage
ssbevx_2stage
ssycon_3
ssycon_rook
ssyconvf_rook
ssyev_2stage
ssyevd_2stage
ssyevr_2stage
ssyevx_2stage
ssygv_2stage
ssysv_aa
ssysv_rk
ssysv_rook
ssytf2_rk
ssytf2_rook
ssytrd_2stage
ssytrd_sy2sb
ssytrf_aa
ssytrf_rk
ssytrf_rook
ssytri_3
ssytri_3x
ssytri_rook
ssytrs_3
ssytrs_aa
ssytrs_rook
stplqt
stplqt2
stpmlqt
zgejsv
zgelq
zgelqt
zgelqt3
zgemlq
zgemlqt
zgemqr
zgeqr
zgesvdx
zgesvj
zgetrf2
zgetsls
zgges3
zggev3
zgghd3
zggsvd3
zggsvp3
zgsvj0
zgsvj1
zhb2st_kernels
zhbev_2stage
zhbevd_2stage
zhbevx_2stage
zhecon_3
zhecon_rook
zheev_2stage
zheevd_2stage
zheevr_2stage
zheevx_2stage
zhegv_2stage
zhesv_aa
zhesv_rk
zhesv_rook
zhetf2_rk
zhetf2_rook
zhetrd_2stage
zhetrd_he2hb
zhetrf_aa
zhetrf_rk
zhetrf_rook
zhetri_3
zhetri_3x
zhetri_rook
zhetrs_3
zhetrs_aa
zhetrs_rook
zlahef_aa
zlahef_rk
zlahef_rook
zlamswlq
zlamtsqr
zlarfy
zlaswlq
zlasyf_aa
zlasyf_rk
zlasyf_rook
zlatsqr
zpotrf2
zsycon_3
zsycon_rook
zsyconvf
zsyconvf_rook
zsysv_aa
zsysv_rk
zsysv_rook
zsytf2_rk
zsytf2_rook
zsytrf_aa
zsytrf_rk
zsytrf_rook
zsytri_3
zsytri_3x
zsytri_rook
zsytrs_3
zsytrs_aa
zsytrs_rook
ztplqt
ztplqt2
ztpmlqt
ztrevc3
zunbdb1
zunbdb2
zunbdb3
zunbdb4
zunbdb5
zunbdb6
zuncsd2by1
zunm22
```

</details>

### CODE REVIEW

**Comment by rgommers** [comment]
It looks like this requires upgrading Cython to `>=0.29.33`, because `const` doesn't work with `memoryview` before (see first entry under https://github.com/cython/cython/blob/0.29.x/CHANGES.rst#bugs-fixed-1). I just ran into that. This requirement is already present in `pyproject.toml`, but not enforced - I'll submit a separate PR for that.

A macOS and a Windows job are choking on `ssyconvf_`, other jobs seem happy. Let's try and figure that one out in https://github.com/rgommers/scipy/issues/143 indeed. Seeing which jobs are failing may also tell us something.

**Comment by rgommers** [comment]
@lysnikolaou what I suggest is to skip the `*syconvf` symbols. The macOS build completes, for me at least, once I remove those. If you note in the script that this is due to a missing exported symbol for `ssyconvf` and xref this PR, I think that's good enough. Those symbols are not present in the signatures today, so there's no real problem in not including them in this PR.

**Comment by rgommers** [comment]
It would also be useful to add to the PR description here which new routines are now wrapped. They're not so easy to spot in between all the ones that were only there and for which `const` is added.

**Comment by lysnikolaou** [comment]
@rgommers Sounds good. I'll do that and mark the PR as ready for review as soon as I've got everything ready.

**Comment by lysnikolaou** [comment]
@rgommers This is now ready for review.

**Comment by rgommers** [comment]
The refguide check CI job has two curious failures:
```
scipy.sparse.linalg.svds
------------------------

File "build/testenv/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 280, in svds
Failed example:
    s_a(u2[:, :1], u[:, :1]) + s_a(u2[:, 1:], u[:, 1:]) > 1e-3
Expected:
    True
Got:
    array([False])

File "build/testenv/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 283, in svds
Failed example:
    (s_a(vT2[:1, :].T, vT[:1, :].T) +
     s_a(vT2[1:, :].T, vT[1:, :].T)) > 1e-3
Expected:
    True
Got:
    array([False])
```
That may be related. We've had issues with those doctests before, they're not particularly robust.

**Comment by rgommers** [comment]
There are a lot of new LAPACK symbols (see PR description). @ilayn, @ev-br or other linalg experts, care to have a look?

**Comment by ilayn** [comment]
I'm not sure if this regex is performing well, there are other ones too but just to give one example, `cher` should be modifying the input array `a`

```
void cher(char *uplo, int *n, const s *alpha, const c *x, const int *incx, const c *a, int *lda)
```
But here it is marked as const. That's not possible since this blas function actually modifies the `a` inplace. In fact the only one that is not `const` is `a`. See for example here for the arg explanations

https://netlib.org/lapack/explore-html/d6/dee/group__complex__blas__level2_gafa73370c613ec8f157771992010809ac.html#gafa73370c613ec8f157771992010809ac

Same with  `ctrsv` which marked input `x` as const but again that is the whole point of `ctrsv` that the solution is overwritten on `x` in place. However it is correctly marking `daxpy` as given in the original issue https://github.com/scipy/scipy/issues/14262#issue-925478126

I am actually suspicious about this. In fact, we should not be even looking at CBLAS/CLAPACK/LAPACKE but the Fortran ones. Or I am missing the point completely. In that case my apologies for the noise.

**Comment by rgommers** [comment]
I just saw the same `svds` refguide failure in another PR, so it's unrelated and can be ignored here.

**Comment by lysnikolaou** [comment]
Thanks @ilayn for the comment!

It's actually not the regex that is the problem in this specific example (although it's totally possible that it might have a bug). It's the fact that the C declaration has a different number of arguments than the implementation in Fortran. I didn't know this was possible, hence the bug. I'll have a more careful look and push a change today.

**Comment by ev-br** [comment]
I wonder if it's possible/easier to parse the fortran implementation/documentation:

https://github.com/Reference-LAPACK/lapack/blob/master/SRC/cgbbrd.f

does not seem to have F90 `intent(in, out)` qualifiers, which would best to parse, but the  online docs seem to have

*> \param[in,out] AB

**Comment by lysnikolaou** [comment]
Yup, since this appears to be agreed upon by everyone, I'll have a look at how we might be able to parse the fortran files instead.

**Comment by lysnikolaou** [comment]
I've pushed a new version of this that uses a simple regex to parse the `/param` doc directive out of the Fortran code itself. I'll need confirmation that the logic used is the correct one, since I'm not really familiar with Fortran. Basically it is the following:

If the `param` directive does not contain `out` in it, the arg is marked as const. Otherwise, it's not.

Note that this means that some signatures (especially in the LAPACK package) are not consistent with the way they're declared in `lapacke.h`.

**Comment by lysnikolaou** [comment]
FYI I'm getting the following error when trying to run tests locally. Not sure whether it's relevant since everything's okay on the CI.

<details>
<summary>Full error</summary>

```python3
scipy/linalg/tests/test_matfuncs.py:22: in <module>
    from scipy.optimize import minimize
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/tests/__pycache__/test_matfuncs.cpython-310.pyc'
        __doc__    = ' Test functions for linalg.matfuncs module\n\n'
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/tests/test_matfuncs.py'
        __loader__ = <_pytest.assertion.rewrite.AssertionRewritingHook object at 0x1120fbd30>
        __name__   = 'scipy.linalg.tests.test_matfuncs'
        __package__ = 'scipy.linalg.tests'
        __spec__   = ModuleSpec(name='scipy.linalg.tests.test_matfuncs', loader=<_pytest.assertion.rewrite.AssertionRewritingHook object at...'/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/tests/test_matfuncs.py')
        _matfuncs_inv_ssq = <module 'scipy.linalg._matfuncs_inv_ssq' from '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/_matfuncs_inv_ssq.py'>
        array      = <built-in function array>
        assert_    = <function assert_ at 0x1128d6290>
        assert_allclose = <function assert_allclose at 0x1128d71c0>
        assert_array_almost_equal = <function assert_array_almost_equal at 0x1128d6c20>
        assert_array_equal = <function assert_array_equal at 0x1128d6b00>
        assert_array_less = <function assert_array_less at 0x1128d6cb0>
        assert_warns = <function assert_warns at 0x1128d7640>
        dot        = <function dot at 0x10f29fbe0>
        expm       = <function expm at 0x1129bd000>
        expm_cond  = <function expm_cond at 0x1129bcb80>
        expm_frechet = <function expm_frechet at 0x1129bc670>
        fractional_matrix_power = <function fractional_matrix_power at 0x1129bcee0>
        functools  = <module 'functools' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/functools.py'>
        funm       = <function funm at 0x1129bd480>
        identity   = <function identity at 0x10f7452d0>
        khatri_rao = <function khatri_rao at 0x1129bd5a0>
        logm       = <function logm at 0x1129bcf70>
        norm       = <function norm at 0x112902830>
        np         = <module 'numpy' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/numpy/__init__.py'>
        pytest     = <module 'pytest' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pytest/__init__.py'>
        random     = <module 'random' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/random.py'>
        scipy      = <module 'scipy' from '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/__init__.py'>
        signm      = <function signm at 0x1129bd510>
        sqrt       = <ufunc 'sqrt'>
        sqrtm      = <function sqrtm at 0x1129bcdc0>
scipy/optimize/__init__.py:411: in <module>
    from ._root import *
        OptimizeResult = <class 'scipy.optimize._optimize.OptimizeResult'>
        OptimizeWarning = <class 'scipy.optimize._optimize.OptimizeWarning'>
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/__pycache__/__init__.cpython-310.pyc'
        __doc__    = '\n=====================================================\nOptimization and root finding (:mod:`scipy.optimize`)\n=====...ration solvers:\n\n.. autosummary::\n   :toctree: generated/\n\n   excitingmixing\n   linearmixing\n   diagbroyden\n\n'
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x17553d420>
        __name__   = 'scipy.optimize'
        __package__ = 'scipy.optimize'
        __path__   = ['/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize']
        __spec__   = ModuleSpec(name='scipy.optimize', loader=<_frozen_importlib_external.SourceFileLoader object at 0x17553d420>, origin='...e_search_locations=['/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize'])
        approx_fprime = <function approx_fprime at 0x174644310>
        bracket    = <function bracket at 0x174644f70>
        brent      = <function brent at 0x174644a60>
        brute      = <function brute at 0x1746452d0>
        check_grad = <function check_grad at 0x1746443a0>
        fmin       = <function fmin at 0x1746441f0>
        fmin_bfgs  = <function fmin_bfgs at 0x174644550>
        fmin_cg    = <function fmin_cg at 0x174644700>
        fmin_ncg   = <function fmin_ncg at 0x174644820>
        fmin_powell = <function fmin_powell at 0x174645120>
        fminbound  = <function fminbound at 0x174644940>
        golden     = <function golden at 0x174644e50>
        line_search = <function line_search_wolfe2 at 0x174610af0>
        minimize   = <function minimize at 0x174645630>
        minimize_scalar = <function minimize_scalar at 0x174672950>
        rosen      = <function rosen at 0x174613e20>
        rosen_der  = <function rosen_der at 0x174613eb0>
        rosen_hess = <function rosen_hess at 0x174613f40>
        rosen_hess_prod = <function rosen_hess_prod at 0x174644040>
        show_options = <function show_options at 0x174645360>
scipy/optimize/_root.py:15: in <module>
    from ._minpack_py import _root_hybr, leastsq
        MemoizeJac = <class 'scipy.optimize._optimize.MemoizeJac'>
        OptimizeResult = <class 'scipy.optimize._optimize.OptimizeResult'>
        __all__    = ['root']
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/__pycache__/_root.cpython-310.pyc'
        __doc__    = '\nUnified interfaces to root finding algorithms.\n\nFunctions\n---------\n- root : find a root of a vector function.\n'
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_root.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x17553d5d0>
        __name__   = 'scipy.optimize._root'
        __package__ = 'scipy.optimize'
        __spec__   = ModuleSpec(name='scipy.optimize._root', loader=<_frozen_importlib_external.SourceFileLoader object at 0x17553d5d0>, origin='/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_root.py')
        _check_unknown_options = <function _check_unknown_options at 0x174613910>
        np         = <module 'numpy' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/numpy/__init__.py'>
        warn       = <built-in function warn>
scipy/optimize/_minpack_py.py:13: in <module>
    from ._lsq import least_squares
        LinAlgError = <class 'numpy.linalg.LinAlgError'>
        OptimizeResult = <class 'scipy.optimize._optimize.OptimizeResult'>
        OptimizeWarning = <class 'scipy.optimize._optimize.OptimizeWarning'>
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/__pycache__/_minpack_py.cpython-310.pyc'
        __doc__    = None
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x17553cc10>
        __name__   = 'scipy.optimize._minpack_py'
        __package__ = 'scipy.optimize'
        __spec__   = ModuleSpec(name='scipy.optimize._minpack_py', loader=<_frozen_importlib_external.SourceFileLoader object at 0x17553cc1...rigin='/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_minpack_py.py')
        _asarray_validated = <function _asarray_validated at 0x1129a05e0>
        _check_unknown_options = <function _check_unknown_options at 0x174613910>
        _contains_nan = <function _contains_nan at 0x1129a1510>
        _getfullargspec = <function getfullargspec_no_self at 0x1129a0b80>
        _lazywhere = <function _lazywhere at 0x1129a01f0>
        _minpack   = <module 'scipy.optimize._minpack' from '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_minpack.cpython-310-darwin.so'>
        asarray    = <built-in function asarray>
        atleast_1d = <function atleast_1d at 0x10f73a170>
        cholesky   = <function cholesky at 0x1129a3130>
        dtype      = <class 'numpy.dtype'>
        finfo      = <class 'numpy.finfo'>
        greater    = <ufunc 'greater'>
        inexact    = <class 'numpy.inexact'>
        inf        = inf
        issubdtype = <function issubdtype at 0x10f6ea200>
        linalg     = <module 'scipy.linalg' from '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/linalg/__init__.py'>
        np         = <module 'numpy' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/numpy/__init__.py'>
        prod       = <function prod at 0x10f738ee0>
        shape      = <function shape at 0x10f72bd90>
        solve_triangular = <function solve_triangular at 0x1129a23b0>
        svd        = <function svd at 0x1129a1fc0>
        transpose  = <function transpose at 0x10f72a5f0>
        triu       = <function triu at 0x10f802950>
        warnings   = <module 'warnings' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/warnings.py'>
        zeros      = <built-in function zeros>
scipy/optimize/_lsq/__init__.py:3: in <module>
    from .lsq_linear import lsq_linear
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/__pycache__/__init__.cpython-310.pyc'
        __doc__    = 'This module contains least-squares algorithms.'
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/__init__.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x17553db10>
        __name__   = 'scipy.optimize._lsq'
        __package__ = 'scipy.optimize._lsq'
        __path__   = ['/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq']
        __spec__   = ModuleSpec(name='scipy.optimize._lsq', loader=<_frozen_importlib_external.SourceFileLoader object at 0x17553db10>, ori...rch_locations=['/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq'])
        least_squares = <function least_squares at 0x1746b1750>
scipy/optimize/_lsq/lsq_linear.py:10: in <module>
    from .trf_linear import trf_linear
        Bounds     = <class 'scipy.optimize._constraints.Bounds'>
        LinearOperator = <class 'scipy.sparse.linalg._interface.LinearOperator'>
        OptimizeResult = <class 'scipy.optimize._optimize.OptimizeResult'>
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/__pycache__/lsq_linear.cpython-310.pyc'
        __doc__    = 'Linear least squares with bound constraints on independent variables.'
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/lsq_linear.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x17553e5f0>
        __name__   = 'scipy.optimize._lsq.lsq_linear'
        __package__ = 'scipy.optimize._lsq'
        __spec__   = ModuleSpec(name='scipy.optimize._lsq.lsq_linear', loader=<_frozen_importlib_external.SourceFileLoader object at 0x1755...n='/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/lsq_linear.py')
        compute_grad = <function compute_grad at 0x1746b0790>
        csr_matrix = <class 'scipy.sparse._csr.csr_matrix'>
        in_bounds  = <function in_bounds at 0x1746b01f0>
        issparse   = <function isspmatrix at 0x1129bf520>
        lsmr       = <function lsmr at 0x1135dfc70>
        norm       = <function norm at 0x10f839990>
        np         = <module 'numpy' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/numpy/__init__.py'>
scipy/optimize/_lsq/trf_linear.py:9: in <module>
    from .givens_elimination import givens_elimination
        OptimizeResult = <class 'scipy.optimize._optimize.OptimizeResult'>
        __builtins__ = <builtins>
        __cached__ = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/__pycache__/trf_linear.cpython-310.pyc'
        __doc__    = 'The adaptation of Trust Region Reflective algorithm for a linear\nleast-squares problem.'
        __file__   = '/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/trf_linear.py'
        __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x17553fe50>
        __name__   = 'scipy.optimize._lsq.trf_linear'
        __package__ = 'scipy.optimize._lsq'
        __spec__   = ModuleSpec(name='scipy.optimize._lsq.trf_linear', loader=<_frozen_importlib_external.SourceFileLoader object at 0x1755...n='/Users/lysnikolaou/repos/python/scipy/build-install/lib/python3.10/site-packages/scipy/optimize/_lsq/trf_linear.py')
        lsmr       = <function lsmr at 0x1135dfc70>
        norm       = <function norm at 0x10f839990>
        np         = <module 'numpy' from '/Users/lysnikolaou/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/numpy/__init__.py'>
        qr         = <function qr at 0x1129a3640>
        solve_triangular = <function solve_triangular at 0x1129a23b0>
givens_elimination.pyx:1: in init scipy.optimize._lsq.givens_elimination
    ???
E   TypeError: C function scipy.linalg.cython_lapack.dlartg has wrong signature (expected void (__pyx_t_5scipy_6linalg_13cython_lapack_d *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, __pyx_t_5scipy_6linalg_13cython_lapack_d *), got void (__pyx_t_5scipy_6linalg_13cython_lapack_d const *, __pyx_t_5scipy_6linalg_13cython_lapack_d const *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, __pyx_t_5scipy_6linalg_13cython_lapack_d *, __pyx_t_5scipy_6linalg_13cython_lapack_d *))
```

</details>

**Comment by rgommers** [comment]
@lysnikolaou do you still see that after `git clean -xdf` and a full rebuild? Maybe it's due to an update to the signatures not being picked up? I just fixed that dependency in gh-18257 a couple of days ago.

**Comment by lysnikolaou** [comment]
Oops, `git clean -xdf` did it. Sorry for the noise.

**Comment by ilayn** [comment]
I have checked the ones I know by heart and I think your latest fix solve the issue. I'll check once again in about 10 hours and this should be ready to go.

**Comment by lysnikolaou** [comment]
@ilayn Friendly ping. (Let me know in case pinging someone in a case like this is not welcome)

**Comment by ilayn** [comment]
Oh I did checked these. So far I couldn't see any issues. Due to the number of signatures, I don't think we can ever be sure but if everybody is OK with this let's click and deal with issues later with a minor version release in case we missed something. 

No problem with the ping, please don't refrain from it.

**Comment by ilayn** [comment]
Well in fact, this has been sitting for some time now anyways and we have some Cython machinery in the pipeline so let's push this in and rebase the other PRs just to make sure. Thank you @lysnikolaou and all, much appreciated!

**Pull request merged**
