### PR TITLE
DOC: Proper .rst formatting for deprecated features and Backwards incompatible changes

### LINKED ISSUE #10292: DOC/REL:  Some sections of the release notes are not nested correctly.
In recent release notes, the sections for the "Deprecated features" and "Backwards incompatible changes" are not nested correctly.  Take a look at

* https://docs.scipy.org/doc/scipy/reference/release.1.2.0.html
* https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html

and note how these sections (if they exist) are indented so that they end up as subsections of the last "improvements" section.

The headings should look like they do in earlier releases, e.g.

* https://docs.scipy.org/doc/scipy/reference/release.1.1.0.html

### PR DESCRIPTION
**Pull request by tapaswenipathak**
#### Reference issue
Fixes https://github.com/scipy/scipy/issues/10292.

#### What does this implement/fix?
Added proper formatting for having `deprecated features` and `backwards incompatible changes` as last improvements.

#### Additional information
None.

### CODE REVIEW

**Review by tylerjereddy — COMMENTED** [review]
Ah yes, the current SciPy release manager should be punished :)

I checked the GitHub renders here and they do seem nicer indeed-- @WarrenWeckesser would you agree, having opened the original issue?

I think the CI failure might be because your feature branch is a little behind the latest master--we have a new `pybind11` dependency that you should pick up if you rebase on latest master, I think.

@rgommers Not sure if we want to "backport" to update the old release notes if people are really annoyed by it--this would be a little different, right, since its the fixed release note proper.

**Comment by rgommers** [comment]
fine to backport I think, it does look better

**Comment by tapaswenipathak** [comment]
@tylerjereddy e062ffb540025463278be319205f5d11b477a34e.

**Comment by tylerjereddy** [comment]
@tapaswenipathak The CI failures don't look related anymore -- I think CI may be failing on master at the moment!?

**Comment by tapaswenipathak** [comment]
@tylerjereddy I think that's creating all CI integration failure issue; the last PR?

**Comment by tylerjereddy** [comment]
Ok, CI is finally working & Ralf is also in favor so in it goes. I'll have some backporting work to do..

Thanks @tapaswenipathak

**Comment by tapaswenipathak** [comment]
Perfect timing @tylerjereddy.

**Pull request merged**
