### PR TITLE
ENH: Reduce operation count in rev. com. iterative solvers.

### PR DESCRIPTION
**Pull request by ewmoore**
The reverse communication interface used by most of the iterative solvers is built around the dgemv interface:

y <- alpha \* A(x) + beta*y

And provides both alpha and beta scalars.  The linear operator interface we have doesn't directly support this operation.  If alpha and beta have special values (1 and 1, or -1 and 0, etc) this operation can be completed without performing as many floating point operations.  This commit removes a number of these redundant floating point operations.

Here this provides a 10-20% reduction in execution time (for gmres and cg at least).  This doesn't change the asymptotic performance, but does reduce the prefactor a bit and cuts down the number of vectors needed to perform the required operation.

### CODE REVIEW

**Comment by ewmoore** [comment]
Test failure is unrelated to the changes here.

**Comment by pv** [comment]
How do I know these changes are correct?
Would it be better to just use `scipy.linalg.blas.*axpy` instead?

**Comment by ewmoore** [comment]
You can check the changes by reviewing the fortran code and looking at the scalars it sets before returning with each job code.   I didn't look, I assume we run these routines in the test suite somewhere as well.  It might be better to use `axpy`.  Doing it that way doesn't quite so tightly couple the fortran to the python. I can change it over if you'd like.

**Comment by ewmoore** [comment]
I'm going to close this.  It works fine here, and I'm not interested in fixing this when that effort would be better served via #5348.

**Pull request closed without merging**
