### PR TITLE
ENH: Add standard deviation of welch

### PR DESCRIPTION
**Pull request by larsoner**
This adds standard deviation output for `scipy.signal.welch` and related functions. Can be useful for getting confidence intervals from the method.

### CODE REVIEW

**Comment by rgommers** [comment]
This made me go look for a ``Bunch`` class again: gh-6335. If that's too much work now, then adding ``std`` with a keyword is fine with me. But at some point we have to stop using ``return_xxx`` keywords.

Test failure is real.

**Comment by e-q** [comment]
I'm something like -1/2 on this. These functions already have a ton of arguments, and this can be calculated simply enough from the spectrogram by users. Returning confidence intervals (as MATLAB can) takes a little more computation, so it makes a little more sense to spare the user that work.

In any case, if we do include this, the docstring for CSD should reflect that it returns the standard deviation of the absolute magnitude of the cross spectrum, since it is generally complex valued.

**Comment by josef-pkt** [comment]
Is this just p.std() ? 
(I don't know what kind of standard errors these are. Are these pointwise or some overall standard errors?)

In general, I like documented functions or options for one-liners if those are difficult to remember.
However, I would rather type `p.std()` than add `return_xxx=True`

**Comment by Eric89GXL** [comment]
> this can be calculated simply enough from the spectrogram by users

@e-q do you know if the output of our spectrogram function is identical to that of the private `_spectral_helper`? If so then I agree is a sample `std` of the spectrogram output. But if `spectrogram` does something differently in terms of options to the private function, or uses different values (e.g., for normalization), then it won't be that simple. I'll have to check.

> Returning confidence intervals (as MATLAB can) takes a little more computation, so it makes a little more sense to spare the user that work.

Maybe we should actually have it give the confidence intervals, instead. That might be more useful for users anyway.

> Is this just p.std()

No, it's the standard deviation across windows used in the estimate. So right now welch returns `x.mean()`, the average of something internal to the function -- this allows returning `x.std()` as well.

**Comment by e-q** [comment]
In fact, `spectrogram` is nothing but a very thin wrapper of `_spectral_helper`. (see https://github.com/scipy/scipy/blob/master/scipy/signal/spectral.py#L514). In addition, the only test that we do for `spectrogram` is to make sure its average is identical to the output of `welch`. (https://github.com/scipy/scipy/blob/master/scipy/signal/tests/test_spectral.py#L809)

It has a different default window than `welch`, though.

**Comment by Eric89GXL** [comment]
Closing since I think we can get away with `spectrogram` instead

**Pull request closed without merging**
