### PR TITLE
TST: adjust to vmImage dispatch in Azure

### PR DESCRIPTION
**Pull request by tylerjereddy**
Try to fix the Azure image dispatch problem based on Microsoft feedback from @ericsciple

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Looks like the API interaction with the CI list has changed -- each job showing up as its own entry now? Can we deactivate that & have a single Azure summary entry?

**Comment by ericsciple** [comment]
@madhurig regarding the job status list

**Comment by ericsciple** [comment]
@tylerjereddy if i'm looking at the correct build, I checked the database and it looks like is getting routed correctly now.

Sorry about the issue. I’ll look into how to avoid the issue going forward. The pool specification is parsed differently than the rest of the file – because any keys are allowed, yet we’re case sensitive.

**Comment by tylerjereddy** [comment]
CI is all green and @chrisrpatterson has confirmed we can't disable the expanded CI list, so I'm removing the WIP tag.

**Comment by tylerjereddy** [comment]
I may self-merge this in a few hours if no objections -- it is a typo fix that alleviates our failing Azure CI & confirmed by a few Microsoft engineers.

**Pull request merged**
