### PR TITLE
FIX:linalg:Use zero arrays for expm scratch arrays

### LINKED ISSUE #18086: BUG: `scipy.linalg.expm` generates inconsistent results between runs
### Describe your issue.

For a custom `(400, 400)` matrix , `scipy.linalg.expm` generates inconsistent results between runs. I understand that the documentation mentions for `n>=400`, some approximation will be applied. However, there are just too much differences between runs, potentially causing backward incompatibility. Is there a way to make it deterministic like `scipy.sparse.linalg.expm` and matlab?

The matrix I used is uploaded here: *removed for security reasons*. 

### Reproducing Code Example

```python
import numpy as np
import scipy
data = np.load("laplacian.npy")
scipy.linalg.expm(data)
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
1.10.0 1.23.4 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/path/to/miniconda3/envs/dlrl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/path/to/miniconda3/envs/dlrl/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Closes #18086 

#### What does this implement/fix?
Changed the np.empty to np.zeros but could not find why this is an issue. Also did some refactoring. I will need to come back to this to get rid of the remaining BLAS usage. 

cc: @steppi in case you want to test

### CODE REVIEW

**Comment by ilayn** [comment]
Yes sorry about that. The failures are very informative since previously these warnings were not available. I'll also have a look tonight

**Comment by ilayn** [comment]
So I'm not sure if this is related to the test itself being problematic or  #19024 relevant or it's what I did here. I will keep investigating but the test seems to be an overkill to solve the optimization problem everytime.

**Comment by ev-br** [comment]
@steppi are you reviewing this? Otherwise I can take a look if you are short on time.

**Comment by steppi** [comment]
> @steppi are you reviewing this? Otherwise I can take a look if you are short on time.

Feel free to take a look, it would be good to have another set of eyes. I haven’t figured out the source of the test failures yet, but planned to take another look this week.

**Review by tylerjereddy — COMMENTED** [review]
In case it helps, this diff probably isn't quite right, but did get me a bit farther along re: 32-bit Linux/old Cython issues here:

```diff
--- a/scipy/linalg/_matfuncs_expm.pyx.in
+++ b/scipy/linalg/_matfuncs_expm.pyx.in
@@ -52,7 +52,7 @@ prefixes = ['s', 'd', 'c', 'z']
 @cython.wraparound(False)
 @cython.boundscheck(False)
 @cython.initializedcheck(False)
-cdef double norm1(lapack_t[:, ::1] A) noexcept:
+cdef double norm1(numpy_lapack_t[:, ::1] A) noexcept:
     """
     Fast 1-norm computation for C-contiguous square arrays.
     Regardless of the dtype we work in double precision to prevent overflows
@@ -67,7 +67,7 @@ cdef double norm1(lapack_t[:, ::1] A) noexcept:
     if not work:
         raise MemoryError('Internal function "norm1" failed to allocate memory.')
     try:
-        if lapack_t in lapack_cz_t:
+        if numpy_lapack_t in lapack_cz_t:
             for j in range(n):
                 temp_cz = A[0, j]
                 work[j] = abs(temp_cz)
@@ -96,7 +96,7 @@ def pick_pade_structure(cnp.ndarray[ndim=3, dtype=numpy_lapack_t] Am):
     cdef:
         Py_ssize_t n = Am.shape[1]
         Py_ssize_t i
-        Py_ssize_t [2] dims
+        cnp.npy_intp [2] dims
         int lm = 0
         int s = 0
         double normA
```

**Comment by ev-br** [comment]
The matmul overflow warning is fixed by  

```diff
$ git diff HEAD^
diff --git a/scipy/linalg/_matfuncs_expm.pyx.in b/scipy/linalg/_matfuncs_expm.pyx.in
index 8dabbbb255..429a180fae 100644
--- a/scipy/linalg/_matfuncs_expm.pyx.in
+++ b/scipy/linalg/_matfuncs_expm.pyx.in
@@ -93,9 +93,9 @@ cdef double norm1(lapack_t[:, ::1] A):
 # ====================== pick_pade_structure : s, d, c, z ====================
 def pick_pade_structure(cnp.ndarray[ndim=3, dtype=numpy_lapack_t] Am):
     cdef:
-        Py_ssize_t n = Am.shape[1]
-        Py_ssize_t i
-        Py_ssize_t [2] dims
+        cnp.npy_intp n = Am.shape[1]
+        cnp.npy_intp i
+        cnp.npy_intp [2] dims
         int lm = 0
         int s = 0
         double normA
@@ -116,7 +116,7 @@ def pick_pade_structure(cnp.ndarray[ndim=3, dtype=numpy_lapack_t] Am):
     dims[0] = n
     dims[1] = n
 
-    work_arr = cnp.PyArray_SimpleNew(1, dims, cnp.NPY_FLOAT64)
+    work_arr = cnp.PyArray_ZEROS(1, dims, cnp.NPY_FLOAT64, 0)
 
     theta[0] = 1.495585217958292e-002
     theta[1] = 2.539398330063230e-001
```

The Py_ssize_t -> npy_intp is probably not a big deal (would be great to hear some definite answer if someone knows it), what is relevant is initializing the work_array for  

```
    # m = 9
    # -------
    # 1-norm of A ** 19
    for i in range(4):
        np.matmul(absA, work_arr, out=work_arr)
    temp = np.max(work_arr)
```

**Comment by ev-br** [comment]
Rebased on main + applied the patch above, and it seems to pass tests on my scipy fork: https://github.com/ev-br/scipy/pull/12 (on linux at least, something's unrelated is wrong with windows). What's the best way to proceed @ilayn ?

**Comment by ev-br** [comment]
> Rebased on main + applied the patch above, and it seems to pass tests on my scipy fork: https://github.com/ev-br/scipy/pull/12 (on linux at least, something's unrelated is wrong with windows). What's the best way to proceed @ilayn ?

https://github.com/scipy/scipy/pull/20234 takes this PR (+a rebase on main to solve a conflict) and adds a work array fix on top.

**Comment by lucascolley** [comment]
superseded by gh-20259

**Pull request closed without merging**
