### PR TITLE
MAINT: stats.truncnorm: simplify remaining methods

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Followup to gh-16593 and gh-16599

#### What does this implement/fix?
Simplifies the remaining `truncnorm` methods along the lines of gh-16586.

#### Additional information
It would be good to compare the benchmarks between this branch and main pre- gh-16586 to see if this is losing anything. I saw in gh-16593 that this `pdf` was a little less accurate in some cases.

### CODE REVIEW

**Comment by steppi** [comment]
@mdhaber I think this approach could be problematic for the pdf, especially when the variance is small. I'd like to take a closer look before merging and hope to have time soon.

**Comment by mdhaber** [comment]
Here is a comparison on the benchmarks on CI before gh-16593 vs with this PR.

<details>

```
Speed Benchmark
                                Pre-gh-16593   This PR
truncnorm            pdf/pmf      5.24±0ms     551±0μs
truncnorm         logpdf/logpmf   5.29±0ms     550±0μs 
truncnorm              cdf        5.10±0ms     906±0μs 
truncnorm             logcdf      5.12±0ms     1.11±0ms 
truncnorm              rvs        954±0μs      1.74±0ms 
truncnorm              fit        166±0ms      209±0ms 
truncnorm               sf        5.22±0ms     1.13±0ms 
truncnorm             logsf       5.66±0ms     1.00±0ms 
truncnorm              ppf        108±0μs      128±0μs
truncnorm              isf        111±0μs      105±0μs
truncnorm             moment        n/a          n/a
truncnorm            stats_s      1.43±0ms     1.22±0ms
truncnorm            stats_v      1.36±0ms     1.24±0ms
truncnorm            stats_m      1.35±0ms     1.63±0ms
truncnorm            stats_k      1.37±0ms     1.24±0ms
truncnorm           stats_mvsk    1.37±0ms     1.21±0ms
truncnorm            entropy      1.63±0ms     4.17±0ms

CDF/PPF and SF/ISF Roundtrip Benchmarks
                Pre-gh-16593               This PR
truncnorm  2.2768245622195593e-14   2.888314587501384e-13  
truncnorm  5.838598105423892e-18    2.687900239433912e-16
truncnorm  1.0842021724855044e-15   3.881443777498106e-14
truncnorm  1.0101757280602149e-16   3.290369363827478e-16  
```
It looks like PDF, CDF, and SF functions are ~10x faster here. RVS, is ~2x slower, entropy is ~2.5x slower, and fit is ~50% slower, and moment is unchanged.
In almost all cases, this will be faster when there are many sets of shape parameters, but that's not what the benchmarks test.

The roundtrip benchmarks are a little less accurate with this PR.

</details>

**Comment by mdhaber** [comment]
Starting with the gist in gh-16593, I performed a little numerical experiment.  I (think I) used Halton to sample:
- the sign of the left truncation point as +1 or -1 with equal probability
- the magnitude of the left truncation log-uniformly distributed from $10^{-3}$ to $10^{3}$
- the magnitude of the truncation range log-uniformly distributed from $10^{-3}$ to $10^{3}$
- the evaluation point log-uniformly distributed within the truncation range

For example, here is the plot of left truncation range $a$ (with sign information) against the truncation range $b-a$ on a log scale:
image

(This is actually a different, smaller sample of 1000 points. The full sample of 10000 is too dense.)

The maximum magnitude of the relative error was `3.7207409574185376e-10`.

Perhaps we can tweak the distribution to target the cases you're concerned about?

<details>

```
import mpmath
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import truncnorm, qmc

mpmath.mp.dps = 80

def truncnorm_delta_cdf(a, b):
    if a > 0:
        delta = mpmath.ncdf(-a) - mpmath.ncdf(-b)
    else:
        delta = mpmath.ncdf(b) - mpmath.ncdf(a)
    return delta

def truncnorm_pdf(x, a, b):
    if a >= b:
        raise ValueError("'a' must be less than 'b'")

    delta_cdf = truncnorm_delta_cdf(a, b)
    if delta_cdf == 0:
        raise RuntimeError("delta_cdf is 0; try increasing mpmath.mp.dps.")

    return mpmath.npdf(x) / delta_cdf

def truncnorm_logpdf(x, a, b):
    return mpmath.log(truncnorm_pdf(x, a, b))


qrng = qmc.Halton(d=4)
sample = qrng.random(10000)
sample = qmc.scale(sample, [0, -3, -3, -6], [1, 3, 3, 0])
sample[:, 1:] = 10**sample[:, 1:]
sign = np.sign(sample[:, 0] - 0.5)
az = sample[:, 1] * sign
bz = az + sample[:, 2] * 2
xz = az + (bz - az) * sample[:, 3]

results = []
for a, b, x in zip(az, bz, xz):
    ref = truncnorm_logpdf(x, a, b)
    res = truncnorm(a, b).logpdf(x)
    rerr = np.float64((res - ref)/ref)
    results.append(rerr)

plt.loglog(np.abs(az[::10]), (bz-az)[::10], '.')
plt.xlabel('a')
plt.ylabel('b - a')

print(np.max(np.abs(results)))
```
</details>

**Comment by steppi** [comment]
Oh, I think this is fine actually. Sorry about that. I didn't have time to really think about it and said that off the cuff. I found this approach didn't work well for the truncated beta distribution when the distribution was peaky, but we are just generating a truncated standard normal distribution, and since it's a location-scale family that's all that's necessary anyway

I'm kind of curious about the slowdown in `rvs` on the benchmark, but if it fixes gh-12370 where there are many sets of shape params, then a 2x slowdown on the benchmarks seems livable.

**Review by steppi — APPROVED** [review]
Looks good to me. The benchmarks look good and the improvement in simplicity is tremendous.

**Comment by tupui** [comment]
Feel free to merge @steppi 😃

**Pull request merged**
