### PR TITLE
CI: Remove 'env' from pytest.ini

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
This fixes the error that we've been getting with pytest 6.0 in recent PRs.

The cancelled Azure run, "scipy.scipy (Windows Python36-32bit-fast)", is weird.  It appears to be a leftover from a previous run of the test suite.  I closed and opened the PR, and the tests ran again, but that cancelled item remained in the list.  Note that there is another entry for "scipy.scipy (Windows Python36-32bit-fast)" that has passed.

I haven't figured out the cause of the Travis CI failure for the platform AMD64 / xenial / "Wheel, Optimised, GCC 4.8".  The end of the log says

> pytest.PytestConfigWarning: assertions not in test modules or plugins will be ignored because assert statements are not executed by the underlying Python interpreter (are you using python -O?)

That test runs with `-OO`.

**Comment by WarrenWeckesser** [comment]
The Travis CI failure on **AMD64 / xenial / "Wheel, Optimised, GCC 4.8"** has occurred on other recent PRs (e.g. https://github.com/scipy/scipy/pull/12889 and https://github.com/scipy/scipy/pull/12899), so it is not related to this PR.  I'm moving this PR out of "draft" mode, as it fixes multiple failures being caused by a change in python 6.0.  We can deal with the remaining failure in a separate PR.

**Comment by sethtroisi** [comment]
@WarrenWeckesser Merging so we can unblock large number of other PRs.

It does seem like we should potentially add `PYTHONHASHSEED=0` back using some other mechanism

**Comment by tylerjereddy** [comment]
This needs to be backported to gh-12906 based on CI fails there, so proceeding with that

**Pull request merged**
