### PR TITLE
CI: Add MacOS to free-threaded wheel release CI

### PR DESCRIPTION
**Pull request by andfoy**
#### Reference issue
See https://github.com/scipy/scipy/issues/20669

#### What does this implement/fix?
Since `cibuildwheel` now allows to build free-threaded Python wheels on MacOS, and NumPy is producing nightly wheels for such platform, SciPy could produce nightly free-threaded MacOS wheels as well. 

#### Additional information

See the corresponding PR in NumPy: https://github.com/numpy/numpy/pull/26664

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @andfoy. This all looks fine at first sight. You didn't run the relevant CI jobs here though - did you run them on your fork, and did they pass?

Reminder of the tags in the commit message for job selection:
```
on the first line: [wheel build]

[skip cirrus] [skip circle]
```

**Comment by andfoy** [comment]
@rgommers, thanks for the pointers regarding CircleCI and Cirrus! I'm still investigating some relocation issues in arm64 (openblas)

**Comment by andfoy** [comment]
@rgommers, there are some mismatches regarding SDK when building on arm64 with OpenBLAS, `wheels.yml` defines the `MACOS_DEPLOYMENT_TARGET` as 12, however, when doing that, `delocate` complains that `libquadmath.0.dylib has a minimum target of 12.3`. 

Such issues are solved when setting `MACOS_DEPLOYMENT_TARGET` to `12.3`, however, the produced wheel has the prefix `cp313-cp313t-macosx_12_3_arm64`, which cannot be tested on `macosx_14_arm64`. Should it be renamed? 

I saw that this matrix entry is being omitted in NumPy, however, I don't know if we must replicate such decision here?

**Comment by rgommers** [comment]
> @rgommers, there are some mismatches regarding SDK when building on arm64 with OpenBLAS, `wheels.yml` defines the `MACOS_DEPLOYMENT_TARGET` as 12, however, when doing that, `delocate` complains that `libquadmath.0.dylib has a minimum target of 12.3`.

Do you have a link to a log for having the deployment target at `12.0`? It works in `wheels.yml`, so I'd expect it to work in the job added here as well. 

Changing the deployment target isn't useful - we should match `wheels.yml` exactly (so use `"12.0"` in the matrix) and if there's a problem with that let's understand what it is - we can drop that build if needed.

**Comment by andfoy** [comment]
> Do you have a link to a log for having the deployment target at 12.0?

https://github.com/andfoy/scipy/actions/runs/9505376302/job/26200145533#step:5:601

**Comment by andfoy** [comment]
I did a line-by-line inspection of the changes, and there are no major differences between the passing build of OpenBLAS on arm64 without free-threading and the failing one under free-threading, besides the installation of nightly distributions of Cython and NumPy. The build is still failing at https://github.com/andfoy/scipy/actions/runs/9551618267/job/26326363006. 

@rgommers, should we skip this configuration?

**Comment by rgommers** [comment]
Thanks for checking in detail @andfoy. Yes, let's skip that build. I don't see the problem either. Dealing with `libgfortran` vendoring is quite fragile and takes a lot of time; this build isn't that important compared to arm64 for macOS >=14, so let's skip it.

**Review by rgommers — APPROVED** [review]
LGTM now, let's give this a go. Thanks @andfoy!

**Comment by rgommers** [comment]
I manually triggered a run in `main` so the new nightlies upload.

**Comment by andyfaff** [comment]
@andfoy I'd like to understand the delocate issue in more detail. As @rgommers said it's not currently an issue in `wheels.yml`. I'm now trying to make wheels for cp313 for the threaded build (i.e. augment `wheels.yml`) and am seeing the same issue.

I wonder if something associated with cp313 has gained the ability to figure out the Python minor version, and so delocate is starting to complain.

**Comment by andyfaff** [comment]
(BTW 12.3 is roughly the oldest version that's supported by the homebrew build chain)

**Comment by rgommers** [comment]
I have no idea what changed, but unfortunately the changed behavior of `delocate` is technically more correct so I guess it's not likely to be changed back. Maybe you happen to know what changed @matthew-brett?

**Pull request merged**
