### PR TITLE
DOC: add Examples for KDTree query_ball_tree and query_pairs

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
fix a part of #7168 

#### What does this implement/fix?
I added Examples for `query_ball_tree` and `query_pairs` of `spatial.KDTree` and `spatial.cKDTree`

### CODE REVIEW

**Comment by peterbell10** [comment]
The example itself looks fine but the plots could be improved I think. It is hard to make out which pairs are linked together. Especially in the cluster on the bottom right. Maybe try fewer points and a larger search radius?

I would also suggest forcing a square `figsize` for the plot so the points are spaced more uniformly in x and y.

**Comment by AtsushiSakai** [comment]
Thank you for your comments. 
> the points are spaced more uniformly in x and y.

I agreed. I will use `axis("equal")`

> Maybe try fewer points and a larger search radius

I tried number of points is 10, and r=0.5, but I'm not sure this is better:
Figure_1

This is original configuration, number of points is 50, and r = 0.1:
Figure_2

What do you think?

**Comment by peterbell10** [comment]
I think in your example the radius has been increased too much, so there are too many pairs to cleanly plot. Here is more what I was thinking of; the clusters are isolated and small, making it easier to identify all the links.

qbp_example

<details>
<summary>Modified Plotting Code</summary>

```python
import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial import cKDTree
np.random.seed(21701)
obstacle_coords1 = np.random.random((15, 2))
obstacle_coords2 = np.random.random((15, 2))
plt.figure(figsize=(6, 6))
plt.plot(obstacle_coords1[:, 0], obstacle_coords1[:, 1], "xk", markersize=14)
plt.plot(obstacle_coords2[:, 0], obstacle_coords2[:, 1], "og", markersize=14)
kd_tree1 = cKDTree(obstacle_coords1)
kd_tree2 = cKDTree(obstacle_coords2)
indexes = kd_tree1.query_ball_tree(kd_tree2, r=0.2)
for i in range(len(indexes)):
    for j in indexes[i]:
        plt.plot([obstacle_coords1[i, 0], obstacle_coords2[j, 0]],
            [obstacle_coords1[i, 1], obstacle_coords2[j, 1]], "-r")
plt.show()
```


</details>

**Comment by AtsushiSakai** [comment]
OK, I fixed code. PTAL.

**Comment by peterbell10** [comment]
What do you think about using `markersize=14` as well? I think it helps when the markers are significantly larger than the line thickness.

**Comment by AtsushiSakai** [comment]
I agree. I fixed it again. PATL

**Review by peterbell10 — APPROVED** [review]
LGTM

**Comment by peterbell10** [comment]
Thanks @AtsushiSakai

**Pull request merged**
