### PR TITLE
MAINT: fix issues with np.matrix as input to functions related to kmeans

### PR DESCRIPTION
**Pull request by argriffing**
Intended to address https://github.com/scipy/scipy/issues/4705.  Tests are included.

### CODE REVIEW

**Comment by argriffing** [comment]
I was tempted to use [`_asarray_validated`](https://github.com/scipy/scipy/blob/master/scipy/linalg/decomp.py#L34) but it is buried in `scipy.linalg.decomp`.  Would it make sense to have a function like this available at a shallower level?  Or is it OK for `scipy.cluster.vq` to reach into `scipy.linalg.decomp` for imports?

**Comment by argriffing** [comment]
50 minute timeout

**Comment by ev-br** [comment]
`_asarray_validated`: maybe move it to `scipy/_lib/_util.py`?

**Comment by rgommers** [comment]
+1 for moving to ``_lib/``, too many cross-submodule imports is undesirable.

**Comment by argriffing** [comment]
OK, I've moved the array validation to `_lib/_util.py` and it is called at the top of most of the public functions of the `vq` module.  An exception is the `k` argument of `kmeans` which seems to have more complicated initialization.  Personally I think that the arguments specifying the number of clusters vs. specifying initial properties of the clusters should not have been combined into a single argument, but changing this would be out of scope here.

**Comment by rgommers** [comment]
LGTM, merged. Thanks Alex.

**Pull request merged**
