### PR TITLE
BUG: optimize: correct `nfev` values

### LINKED ISSUE #5369: fsolve & root incorrect function-call count
The functions in scipy.optimize fsolve and root both return a wrong number function evaluations in the information they return.

Concretely, they fail to count 2 function evaluations they do for checking purposes:
from the minpack code -> es = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
and another that I didn't find (probably in compiled code).

Someone already noticed a few years ago:
https://mail.scipy.org/pipermail/scipy-dev/2010-November/015765.html

So this two extra function evaluations should be counted (or at least added to the documentation as two extra function evaluations for checking purposes).

And related to this: For applications where the cost of the function evaluations is high these function evaluations should be avoided (or optional).

The code that uncovers the bug:

```
from scipy import optimize

counter=0

def zero_f(y):
    global counter
    counter += 1
    return y**2-3

counter=0
x, infodict, ier, mesg = optimize.fsolve(zero_f,100, full_output = True)
print(counter)
print ("func ev: " + str(infodict["nfev"]))

counter=0
optObject = optimize.root(zero_f,100)
print(counter)
print("func ev: " + str(optObject.nfev))
```

### PR DESCRIPTION
**Pull request by TimButters**
The number of function evaluations was incorrect when using the `fsolve` and `root` methods in SciPy.optimize (see #5369). To solve this, the function is wrapped and the number of invocations counted. This value replaces the one returned by the optimizer.

#### Reference issue
Closes #5369

#### What does this implement/fix?
This corrects the count of function invocations (`nfev`) in the `fsolve` and `root` methods of SciPy.optimize. It also adds the `nfev` value to other methods in `root` that previously did not return it (broyden1, broyden2, anderson,                        linearmixing, diagbroyden, excitingmixing, and krylov).

#### Additional information
This is my first PR so constructive feedback is very welcome. I'm happy to work on this further if required.

### CODE REVIEW

**Review by lucascolley — APPROVED** [review]
I'll let Matt take a look but this looks good to me, thanks! The lint failure you can see in CI is not caused by you, it's just because you're the first person to touch that file since the config became more strict. If you could fix that up too here (it's saying line 893 is a character too long), that would be great!

**Comment by TimButters** [comment]
Thanks @lucascolley - I've added a commit to fix the long line issue.

**Comment by mdhaber** [comment]
@lucascolley I don't really have any special connection to this; I just helped to triage it ~18mo ago. You're welcome to merge if it looks good to you!

**Comment by TimButters** [comment]
I'm happy to bind nfev to the wrapper function, that will be a quick change to make. I wasn't sure what the best approach was for this. I'll push an update later today.

**Review by lucascolley — APPROVED** [review]
LGTM, will merge once CI is green

**Comment by lucascolley** [comment]
thanks for your first contribution to SciPy! Keep them coming :)

**Comment by mdhaber** [comment]
Thanks @TimButters @lucascolley!

**Pull request merged**
