### PR TITLE
Add rice cdf and ppf.

### PR DESCRIPTION
**Pull request by argriffing**
This attempts to follow the idea of @josef-pkt in https://github.com/scipy/scipy/pull/4605#issuecomment-77651944. I've made some attempts to activate the automated tests for this distribution, but I'm not sure I've done this correctly.

### CODE REVIEW

**Comment by argriffing** [comment]
ping @efiring

> Regarding the ppf: If I understand correctly, it is being calculated numerically from the cdf, which is in turn being calculated numerically from the pdf. It's slow, but it's hard to see how it could go seriously wrong

**Comment by argriffing** [comment]
50 minute test timeout

**Comment by ev-br** [comment]
OK, tests pass after a restart :-).

LGTM

**Comment by ev-br** [comment]
This has been open for a week without any further comments. Merging, thanks @argriffing!

**Pull request merged**
