### PR TITLE
ENH: sparse: add `fast_lil_matrix` sparse matrix

### PR DESCRIPTION
**Pull request by maciejkula**
This PR adds a new, row-based sparse matrix type for efficient matrix construction. (@rgommers and I had a brief chat about this at PyData Amsterdam).

It works like the LIL matrix, but
1. It's much more memory efficient. Instead of using Python lists for row indices and data, it uses typed C++ vectors, reducing the overhead of using pointers everywhere.
2. It's substantially faster because more operations can be delegated to native code.

With a bit of work this could be the new recommended way of incrementally constructing sparse matrices in scipy.
## Naming

The working name is `fast_lil_matrix` by analogy to `lil_matrix`. However, as neither has anything at all to do with liked lists, maybe another name would be more suitable.

This is a new class (instead of modifying `lil_matrix`) due to backward-compatibility concerns shown in #4691. If this is accepted `lil_matrix` could be progressively phased out.
### Construction

```
Running sparse.Construction.time_construction  

 ============ ========== ========== ==========
 --                        format             
 ------------ --------------------------------
    matrix       lil      fastlil      dok    
 ============ ========== ========== ==========
    Empty       3.36ms    631.39μs   11.98μs  
   Identity    46.39ms    21.59ms    150.47ms 
  Poisson5pt   213.93ms   109.64ms   726.13ms 
 ============ ========== ========== ==========
```
### Conversion

```
Running sparse.Conversion.time_conversion                                                  

 ============= ========== ========== ========== ========== ========== ========== ==========
 --                                             to_format                                  
 ------------- ----------------------------------------------------------------------------
  from_format     csr        csc        coo        dia        lil      fastlil      dok    
 ============= ========== ========== ========== ========== ========== ========== ==========
      csr       356.85ns   266.35μs   290.17μs    5.20ms    17.03ms     1.53ms    25.78ms  
      csc       270.28μs   362.58ns   301.39μs    5.96ms    17.84ms     2.08ms    28.18ms  
      coo        1.15ms     1.23ms    355.22ns    1.90ms    18.12ms     3.18ms    23.87ms  
      dia        2.66ms     2.61ms     1.28ms    352.55ns   19.45ms     4.58ms    29.29ms  
      lil        8.01ms     8.48ms     8.37ms    14.25ms    367.64ns   10.43ms    35.53ms  
    fastlil     211.93μs   822.86μs   480.05μs    5.88ms    17.99ms    353.46ns   27.36ms  
      dok       44.85ms    45.47ms    43.54ms    53.08ms    62.34ms    46.78ms    382.15ns 
 ============= ========== ========== ========== ========== ========== ========== ==========

```
### Getitem/setitem

```
Running sparse.Getset.time_fancy_getitem                                                                                                                                    

 ======= ================= ================= ================= ===================== ================= ============ ============ ============ ================ ============
 --                                                                          sparsity pattern / format                                                                     
 ------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
    N     different / csr   different / csc   different / lil   different / fastlil   different / dok   same / csr   same / csc   same / lil   same / fastlil   same / dok 
 ======= ================= ================= ================= ===================== ================= ============ ============ ============ ================ ============
    1         17.59μs           68.43μs            3.07μs              1.03μs              8.11μs        18.13μs      69.92μs       3.17μs         1.05μs         8.33μs   
    10        50.06μs           112.53μs          64.97μs             64.04μs             61.28μs        50.57μs      106.94μs     60.83μs        60.80μs        59.74μs   
   100        51.82μs           107.37μs          64.43μs             64.61μs             121.45μs       52.73μs      109.53μs     64.90μs        60.95μs        120.43μs  
   1000       58.50μs           114.77μs          85.72μs             68.33μs               n/a          59.29μs      114.88μs     86.20μs        68.27μs          n/a     
  10000       120.64μs          177.27μs          277.64μs            128.02μs              n/a          123.56μs     178.74μs     275.28μs       126.56μs         n/a     
 ======= ================= ================= ================= ===================== ================= ============ ============ ============ ================ ============

Running sparse.Getset.track_fancy_setitem                                                                                                                                   

 ======= ================= ================= ================= ===================== ================= ============ ============ ============ ================ ============
 --                                                                          sparsity pattern / format                                                                     
 ------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
    N     different / csr   different / csc   different / lil   different / fastlil   different / dok   same / csr   same / csc   same / lil   same / fastlil   same / dok 
 ======= ================= ================= ================= ===================== ================= ============ ============ ============ ================ ============
    1         283.96μs          283.00μs          11.92μs              1.48μs              6.58μs        73.91μs      73.91μs       3.48μs         1.29μs         6.48μs   
    10        391.96μs          391.01μs          86.07μs             64.13μs             74.86μs        75.82μs      74.86μs      60.80μs        51.98μs        72.96μs   
   100         1.24ms            1.21ms           101.09μs            74.86μs             91.08μs        78.92μs      78.92μs      67.00μs        53.88μs        99.90μs   
   1000        6.48ms            6.55ms           202.89μs            173.81μs              n/a          109.91μs     109.91μs     139.00μs       68.90μs          n/a     
  10000       12.20ms           12.63ms            1.76ms              1.02ms               n/a          571.01μs     573.87μs      1.27ms        413.89μs         n/a     
 ======= ================= ================= ================= ===================== ================= ============ ============ ============ ================ ============

```
### Slicing

```
Running sparse.NullSlice.time_10000_rows          

 ========= ======== ========= ========= =========
 --                        format                
 --------- --------------------------------------
  density    csr       csc       lil     fastlil 
 ========= ======== ========= ========= =========
    0.05    3.97ms   36.97ms   21.35ms    4.39ms 
    0.01    1.15ms    8.50ms   10.95ms    2.41ms 
 ========= ======== ========= ========= =========
```

```
Running sparse.NullSlice.time_100_cols             

 ========= ========= ======== ========== ==========
 --                         format                 
 --------- ----------------------------------------
  density     csr      csc       lil      fastlil  
 ========= ========= ======== ========== ==========
    0.05    21.32ms   9.33ms   566.16ms   158.25ms 
    0.01     8.50ms   2.32ms   445.80ms   79.32ms  
 ========= ========= ======== ========== ==========
```

### CODE REVIEW

**Comment by pv** [comment]
(1) I think having one matrix assembly oriented opaque sparse matrix class would be enough,
so it would be good to ensure the chosen data storage model is efficient. A different approach here: https://github.com/ev-br/sparr  (uses std::map probably usually a red-black tree).
(2) I think it would be important to optimize the single-element setitem --- here, the code runs partially in Python bytecode still.
(3) As it's c++ code, I would perhaps prefer writing the inner container object in plain templated c++ rather than in c++ flavor Cython.
(4) As it's low-level code, fancy indexing probably could be written in a way that avoids constructing full index arrays.
(5) A relevant target for performance comparisons would be [pysparse](http://pysparse.sourceforge.net/) which has a low-level linked-list implementation.

**Comment by maciejkula** [comment]
Thanks for your feedback! Obviously this is just a start, hopefully we can make this much better.

(1) I am certain the vector-based approach is going to be most efficient memory-wise. I have in the past written code using C++ maps for building huge sparse matrices (textual co-occurrence matrices for the English Wikipedia), and maps have huge overhead.

This article http://info.prelert.com/blog/stl-container-memory-usage suggests that GNU C++ stdlib has 32 bytes of overhead per map entry, making best case space usage in bytes `num_elements * (32 + sizeof(index) + sizeof(value)`. For a (1000 x 1000) matrix with 1000^2 entries (assuming 4 byte indices and elements) this would give `1000 ** 2 * (32 + 4 + 4 + 4) / (1024 * 1024) == 41` MiB.

A vector-based approach uses `(num_elements * (sizeof(index) + sizeof(value)) + num_rows * 16)` bytes of space. For the (1000 x 1000), 1000^2 4-byte entries matrix this gives roughly 7 MiB.

The same holds for Linked-list matrices: each node will have an 8 or 16 byte overhead due to pointers. This is borne out in the benchmarks below.

I've done some quick benchmarking for constructing such a matrix in this gist: https://gist.github.com/maciejkula/17d336eae88d3f3529dc. On my machine, this yields

```
(main)λ deepthought scipy → λ git fast_lil_matrix* → python runtests.py --ipython
Building, see build.log...
Build OK
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import scipy.bench; scipy.bench.run()
Benchmarking: 1000 by 1000 matrix, 5 runs
fast_lil_matrix memory delta (MiB): 8.40390625 --- time 1.22986683846
MapArray memory delta (MiB): 61.14375 --- time 0.411746740341
ll_mat memory delta (MiB): 15.234375 --- time 1.43608613014
lil_matrix memory delta (MiB): 60.25234375 --- time 5.49037780762
dok_matrix memory delta (MiB): 159.175 --- time 6.6607052803
```
(I have included `lil_matrix` and `dok_matrix` for comparison. I've also had some trouble with setting up `pysparse`, it looks abandoned. To build in, I cloned it from https://github.com/optimizers/pysparse.git and added `os.environ['CC'] = 'gcc -w'` in `setup.py` to suppress gcc error.)

(2) Sure, I can move that one level lower.

(3) Unfortunately, I am not a C++ programmer and am fairly confident learning C++ holds low value for me. I could happily write this in Rust, but I doubt that's a good idea distribution-wise.

(4) I have a couple of fast paths for simple common cases. I'd be happy to move it all down with a little help (so far I have found fancy indexing rather incomprehensible).

(5) See benchmarks above.

**Comment by pv** [comment]
For a somewhat sparser result, e.g.,
```
def populate_2(A, size):
    n = int(np.sqrt(size))
    for i in xrange(n):
        for j in xrange(n):
            k = i + n*j
            A[k,k] = 4
            if i > 0:
               A[k,k-1] = -1
            if i < n-1:
               A[k,k+1] = -1
            if j > 0:
               A[k,k-n] = -1
            if j < n-1:
               A[k,k+n] = -1
```
the metrics tilt more heavily for pysparse:
```
Benchmarking: 1000 by 1000 matrix, 1 runs
fast_lil_matrix memory delta (MiB): 0.0 --- time 0.00613403320312
MapArray memory delta (MiB): 0.265625 --- time 0.00135493278503
ll_mat memory delta (MiB): 0.37890625 --- time 0.000796794891357
lil_matrix memory delta (MiB): 0.6171875 --- time 0.0273060798645
dok_matrix memory delta (MiB): 0.66796875 --- time 0.0266079902649
```

**Comment by maciejkula** [comment]
Thanks!

Regarding speed, I think the speed of `fast_lil_matrix` can be improved by pushing it into native sooner as per your point (2). The balance between `ll_matrix` and `fast_lil_matrix` will be governed by density. Linked list traversal is O(n)  add, compared to O(log n) for binary search in sorted vectors.

As for memory, `fast_lil_matrix` is clearly the winner here, just because maps and linked-lists have inherent overhead disadvantages.

While it's important to weigh speed, I personally think memory usage is by far the more important consideration. For the applications I'm familiar with, construction happens once, followed by conversion to csr/csc for further processing. The bottleneck then is the inability to incrementally construct the matrix in the first place due to memory constraints.

**Comment by ev-br** [comment]
First off, this is definitely more feature-complete than my `MapArray` (which does not even have slicing let alone fancy indexing ATM). So if there's a desire to merge it quickly, there's a clear winner :-).

Other than that, a couple of random comments:

* I share Pauli's concern that lower level code is better written in templated C++ rather than Cython/C++ dialect. Both in terms of readability and maintainability and weeding out Python overhead. The current implementation is definitely spending a nontrivial amount of time/memory boxing and unboxing python structures.

* For instance, the MapArray result above (and even more so the microbenchmark from the gist) is likely dominated by the fact that I was lazy and handled negative indices in cython (https://github.com/ev-br/sparr/blob/master/sparr/sp_map.pyx.in#L474) --- try `cython --cplus -a`. This is likely worse for `fast_lil` as written.

* Pauli's benchmark above is straight from PySparse docs IIUC, which might explain somewhat why it's skewed towards it. The takeaway is probably that microbenchmarks are nice, but some larger scale "usage" benchmarks could be helpful.

* You mention Wikipedia link graph as an example of `std::map` being too fat in memory. I vaguely remember someone mentioning exactly the same Wikipedia link graph saying that `std::map` works for storing it :-). Was it @larsmans ?

* One possible advantage of dok-type storage over row-based one is cheap transposes. It's also easier to generalize to higher dimensions if we ever want to.

* An obligatory mention is `khash` for leaner and meaner associative container. Not that I quickly see how to use it with array-valued keys though :-).

**Comment by maciejkula** [comment]
Thanks for more comments :)

- Wouldn't you have to box/unbox (into `PyObject`?) even with pure C++? I admit to being a little ignorant here. In any case, I'll refrain from commenting on C++ as I neither know the language nor do I wish to learn it.
- Not sure what you mean. 
- Yes, better benchmarks are always nice!
- I work on https://github.com/maciejkula/glove-python, which constructs large co-occurrence matrices (this is text, rather than links: you count the number of times any two text tokens occur together in a sliding context window). One of the older versions used `std::map` and `std::unordered_map`, but both were unworkable due to memory usage.

**Comment by ev-br** [comment]
If the goal is only construction with no prior size information followed by conversion to csr or some such, then surely the best format is just an unsorted bag of triplets (`row, col, value` as C structs) which keeps track of its dimensions. Then all operations are `O(N)`, but there memory consumption is at the absolute minimum.

**Comment by maciejkula** [comment]
Re: triplets that's correct if you don't care about set/get (modulo vector space overallocation). I think vec of vecs is a nice middle-of-the road solution.

**Comment by ev-br** [comment]
How does the vector of vectors fare if the insertions are random? --- this is not confrontational, and likely the answer is in the code somewhere where I just missed it.

**Comment by maciejkula** [comment]
I'm guessing speed-wise slightly worse than a linked-list, depending on where the insert happens.

For a vector it takes a O(log n) traversal to find the insertion index, then a move of all elements right of the insertion index one offset down, then insert. I guess that's O(n)?

For a linked-list this would be O(n) traversal to find the insertion index, then an O(1) operation to insert a new node and modify pointers, assuming each node is just `malloc`'ed on its own and they are not stored in some contiguous space where you'd also need to move them.

**Comment by maciejkula** [comment]
Just to try to move this forward, what are the biggest points that need addressing in order for us to have a better idea of how to improve this?

Is it 
1. data structure? linked list vs vector of vectors? or
2. language of implementation?

**Comment by perimosocordiae** [comment]
I think adding an opaque format that optimizes for unknown sparsity patterns is a great idea, but it's also one that we can bikeshed to death. My concrete suggestions are:
 1. Rename this to something like "Vector Of Vectors (vov)" format and commit to the existing storage scheme. This will touch a lot of code, so you might as well rebase on master and squash after making this change.
 2. Tighten up the python side of the class. I have a bunch of minor-to-medium effort comments to make, but I'll hold off until step 1 is done.
 3. Start converting the bulk of the Cython code to templated C++. This sounds daunting, but it shouldn't be too bad. The work done in #4890 should give you an idea of what this will look like, and someone more knowledgeable about C++ can step in at this stage if needed.

After that, it'll be time to benchmark again.

**Comment by maciejkula** [comment]
OK, that sounds like a plan. I'll get on with it and see where it goes.

**Comment by maciejkula** [comment]
Does scipy target a particular version of the C++ standard?

**Comment by pv** [comment]
I don't think we have a fixed standard target version. However, probably best to stick with something old, eg C++03 to ensure compilers on old distros also work.

**Comment by Silmathoron** [comment]
Hi there, I would be interested in this PR and, from what I read, it seems that no major problem exists that would prevent it from being merged. Is there any plan to include this in the next scipy release?

**Comment by lucascolley** [comment]
> it seems that no major problem exists that would prevent it from being merged

It looks like there is still work to be done: https://github.com/scipy/scipy/pull/6004#issuecomment-204154763

> Does scipy target a particular version of the C++ standard?

In case you're interested in returning to this @maciejkula , we currently target C++14, although we just figuring out the move to C++17 right now.

**Comment by perimosocordiae** [comment]
This PR is unlikely to be useful except as reference, so I'll close it now. The points from https://github.com/scipy/scipy/pull/6004#issuecomment-204154763 still apply, for anyone looking to pick up this idea.

**Pull request closed without merging**
