### PR TITLE
DOC: Add some See Also links between similar functions

### PR DESCRIPTION
**Pull request by endolith**
- `special.comb` and `special.binom` do the same thing, but with different options.
- `signal.triang` and `signal,bartlett` are very similar except for the endpoints
- `fftpack.hilbert` and `signal.hilbert` are both related to Hilbert transforms but not the same.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
It looks like none of the cross-submodule docs rendered properly:

https://600-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.special.comb.html#scipy.special.comb
https://600-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.special.binom.html#scipy.special.binom
https://600-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.signal.hilbert.html#scipy.signal.hilbert
https://600-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.fftpack.hilbert.html#scipy.fftpack.hilbert

**Comment by person142** [comment]
Might want to try :func:\`~scipy.submodule.function\`. (Remember it taking me longer than I would like to figure that out...) (Also it might need to be :py:func: though I don't think so.)

**Comment by Eric89GXL** [comment]
It should default to `:py:` already. If it doesn't already someone should add an option to `sphinx` to set a default namespace like `scipy` (for us) so it could just be:
```
:func:`signal.bartlett`
```

**Comment by pv** [comment]
Probably needs full name for cross-module links `scipy.fftpack.bartlett` 
--- probably no need for Sphinx-specific markup.

**Comment by pv** [comment]
Default namespace is set to `scipy.special` in 
`scipy/special/__init__.py` docstring  --- you cannot have two default 
namespaces.

**Comment by endolith** [comment]
> It looks like none of the cross-submodule docs rendered properly:
> 
> https://600-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.special.comb.html#scipy.special.comb

Isn't that one ok?  It's in the same module.

**Comment by endolith** [comment]
Ok fixed except for https://622-1460385-gh.circle-artifacts.com/0//home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.special.binom.html  which I don't understand.  Other things with `add_newdoc` seem to be correct?

**Comment by person142** [comment]
Need to run `generate_ufuncs.py`.

**Comment by endolith** [comment]
So it will be fine in the real documentation but doesn't show up in CircleCI?

**Comment by pv** [comment]
If you change stuff in `scipy/special/add_newdocs.py`, you need to re-run `python generate_ufuncs.py` and commit the changes.

**Comment by endolith** [comment]
Oh right, I've done that before.  Should be fixed now.

**Comment by Eric89GXL** [comment]
Looks like you need a rebase

**Comment by Eric89GXL** [comment]
The doc links now all look good but the diff is *huge*  (+16,630 −16,599). @pv is this expected from running the `python generate_ufuncs.py` function?

**Comment by pv** [comment]
It maybe changed unix-style \n line endings to windows-style \r\n.

**Comment by Eric89GXL** [comment]
Yes indeed, running it on my Unix box made only a few lines changed, thanks @pv

**Comment by Eric89GXL** [comment]
Thanks @endolith

**Pull request merged**
