### PR TITLE
Remove deprecated blas/lapack imports, rename lib to _lib

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by sturlamolden** [comment]
This is an impressive PR.  

I think the renaming of ```scipy.lib``` to ```scipy._lib``` should have been in a different PR, since it can potentially cause problems unrelated to the removal of deprecated BLAS and LAPACK modules.

**Comment by sturlamolden** [comment]
But now that you have it all here...

**Comment by rgommers** [comment]
@sturlamolden thanks, but it really wasn't that difficult. A ``sed`` script makes it easy to change tons of files...

I don't think it's much of an issue having the ``_lib`` commit here, but if others also prefer to move it to a different PR I can do so.

**Comment by larsmans** [comment]
Merge conflict, needs rebase.

**Comment by rgommers** [comment]
rebased

**Comment by rgommers** [comment]
rebased and green now

**Comment by larsmans** [comment]
LGTM, time to merge? (I assume this has been discussed on -dev?)

**Comment by rgommers** [comment]
yep, got a couple of +1's on the list so good to merge.

**Comment by larsmans** [comment]
Done. I love throwing code away :)

**Comment by rgommers** [comment]
me too:)

**Pull request merged**
