### PR TITLE
MAINT: Clarifies `F_onewayConstantInputWarning` documentation

### PR DESCRIPTION
**Pull request by ChrisKeefe**
#### Reference issue

Minor documentation PR - no issue exists AFAIK.

#### What does this implement/fix?

This PR clarifies the phrase "constant array" in the relevant docstring and select code comments. 

#### Additional information

The term "constant array", as used in the [`F_onewayConstantInputWarning` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.F_onewayConstantInputWarning.html) is unclear. 

As used here, a "constant array" is an array in which all values are identical ([source](https://github.com/erheron/scipy/blob/ffafe8724a69be61d1017610e5e3c0e868685037/scipy/stats/stats.py#L3227)). The term "constant" is overloaded in software contexts, generally indicating a literal value (rather than a variable), or an value declared "unchangeable" by the programmer. Some theorem provers (Z3) use "constant array" as it used here, but the other usages are more prevalent in search. More clarity/context was needed.

### CODE REVIEW

**Comment by tupui** [comment]
Why not as the end result is using clearer wording. Did you look into the code base if there was other references like these to constant arrays?

**Comment by rlucas7** [comment]
There are several of these warnings in the public api. We are planning to move these to private, see:

https://github.com/scipy/scipy/issues/13462

For details and further context.

-L

**Comment by ChrisKeefe** [comment]
Happy to keep tinkering with this if that helps, @rlucas7. 

After reading through the issues above, I'd like to confirm I've got the right idea of what we're going for:
- Two public-API warnings: `ConstantInputWarning`, and `NearConstantInputWarning`
- _Keep_ method-specific warnings that subclass these, so that users can filter warnings without message parsing
- The method-specific warnings are _private_ API, and should be dropped from  the `stats.py` `__all__`

**Comment by rlucas7** [comment]
> Happy to keep tinkering with this if that helps, @rlucas7.
> 
> After reading through the issues above, I'd like to confirm I've got the right idea of what we're going for:
> 
>     * Two public-API warnings: `ConstantInputWarning`, and `NearConstantInputWarning`
> 
>     * _Keep_ method-specific warnings that subclass these, so that users can filter warnings without message parsing
> 
>     * The method-specific warnings are _private_ API, and should be dropped from  the `stats.py` `__all__`

@ChrisKeefe that sounds right-I'm not sure about the doc rendering though, that may also need a fixup. To be clear we want:

>     * Two public-API warnings: `ConstantInputWarning`, and `NearConstantInputWarning`

to be public, so those should be in (public facing) docs. The existing Warnings should be removed from public facing docs. I guess we can assume-for now anyway-that the existing, specialized, warnings aren't being used in downstream code bases.

**Comment by mdhaber** [comment]
Thanks @ChrisKeefe. This makes these more clear, so I resolved the merge conflicts and will merge if the lint check passes.
If you're still interested in helping with gh-13462, we'd appreciate it, but that would be another PR. This did what it set out to do.
Also, if you can help with @tupui's suggestion above (other unclear uses of "constant"), please do open another PR.

**Comment by ChrisKeefe** [comment]
Thanks all! This clearly fell off my to-do list months ago. If I can find some time to help out with the issues above I'd love to, but other contributors are absolutely welcome.

**Pull request merged**
