### PR TITLE
Issues with relaxed strides in QR updating routines

### PR DESCRIPTION
**Pull request by ewmoore**
WIP.

### CODE REVIEW

**Comment by ewmoore** [comment]
If this passes Travis and I think it will, lets go ahead and merge this to remove the travis failure from polluting the CI results for everything else.

There are some other things to do here, but they can come in as another  PR.

**Comment by ewmoore** [comment]
The other things are in #4736, but this is green.  I'll let someone else push the button here.

**Comment by argriffing** [comment]
Thanks @ewmoore, I've merged this. My understanding is that not all of the underlying issues have been fixed yet, but that this fixes the TravisCI failure with the existing tests.

**Comment by ewmoore** [comment]
Thanks @argriffing.  Yes that understanding is correct.

**Pull request merged**
