### PR TITLE
Fix missing RuntimeError message

### PR DESCRIPTION
**Pull request by naught101**
Simple fix to add a missing RuntimeError message, missed in a previous PR.

See #12289 for details.

### CODE REVIEW

**Comment by rlucas7** [comment]
@naught101  can you please execute and paste the output of this command here in the PR? 

```
import scipy 
scipy.__version__
```

the reason why I ask is because, as @WarrenWeckesser [noted](https://github.com/scipy/scipy/issues/12289#issuecomment-642180864) over in the associated issue this was fixed in #10480 

I confirmed this by executing:

```
>>> import scipy.stats as ss 
>>> import numpy as np
>>> ss.skewnorm.fit([1,2,np.nan])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py", line 2303, in fit
    raise RuntimeError("The data contains non-finite values.")
RuntimeError: The data contains non-finite values.
```
now when I look at line 2303 I see the `RuntimeWarning` that I added in #10480
I'm guessing you have an older version of scipy running in your environment.

**Comment by WarrenWeckesser** [comment]
@rlucas7, this PR changes line **2402**: https://github.com/scipy/scipy/blob/c5e0ca5be3c3ba9e00d44b7ac455df6d9bc4f720/scipy/stats/_distn_infrastructure.py#L2402

**Comment by rlucas7** [comment]
> @rlucas7, this PR changes line **2402**:
> 
> https://github.com/scipy/scipy/blob/c5e0ca5be3c3ba9e00d44b7ac455df6d9bc4f720/scipy/stats/_distn_infrastructure.py#L2402

I understand which line this PR changes. 
However, when I run the line provided in the issue:

```
>>> import scipy.stats as ss 
>>> import numpy as np
>>> ss.skewnorm.fit([1,2,np.nan])
```
I get a runtime error which looks like it is thrown by the `.fit()` method's runtime error and therefore the change in this PR is not needed? 

Did I miss a different test case somehow?

**Comment by naught101** [comment]
```
In [1]: import scipy  
   ...: scipy.__version__                                                                                         
Out[1]: '1.3.0'
```

Fair enough, perhaps the problem is fixed. I guess it's possible that line is still hit (maybe with other models?), in which case it should change, or it can never be hit, in which case it should be removed, perhaps? I don't know which is more sensible.

**Comment by WarrenWeckesser** [comment]
I interpreted the PR as an additional clean up.  My question for @naught101 is (or would have been, but it looks like the question is already answered in the above comment) do you have an example that triggers the empty `RuntimeError`?

**Comment by naught101** [comment]
The lines @rlucas7 posted trigger it for me in 1.3.0, which is where I noticed it. It does seem to be fixed in 1.4.1. 

But the error is from a different line:

```
In [1]: import scipy.stats as ss                                                                                  

In [2]: import numpy as np                                                                                        

In [3]: ss.skewnorm.fit([1,2,np.nan])                                                                             
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-1ad27629e941> in <module>
----> 1 ss.skewnorm.fit([1,2,np.nan])

~/miniconda3/envs/ana/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py in fit(self, data, *args, **kwds)
   2279 
   2280         if not np.isfinite(data).all():
-> 2281             raise RuntimeError("The data contains non-finite values.")
   2282 
   2283         start = [None]*2

RuntimeError: The data contains non-finite values.
```

Using `np.inf` also triggers the same error now. So maybe just deleting line 2402 is best, because it can never get hit anyway?

**Comment by rlucas7** [comment]
> The lines @rlucas7 posted trigger it for me in 1.3.0, which is where I noticed it. It does seem to be fixed in 1.4.1.
> 
> But the error is from a different line:
> 
> ```
> In [1]: import scipy.stats as ss                                                                                  
> 
> In [2]: import numpy as np                                                                                        
> 
> In [3]: ss.skewnorm.fit([1,2,np.nan])                                                                             
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-3-1ad27629e941> in <module>
> ----> 1 ss.skewnorm.fit([1,2,np.nan])
> 
> ~/miniconda3/envs/ana/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py in fit(self, data, *args, **kwds)
>    2279 
>    2280         if not np.isfinite(data).all():
> -> 2281             raise RuntimeError("The data contains non-finite values.")
>    2282 
>    2283         start = [None]*2
> 
> RuntimeError: The data contains non-finite values.
> ```
> 
> Using `np.inf` also triggers the same error now. So maybe just deleting line 2402 is best, because it can never get hit anyway?

Hmm, not sure how deleting the runtime error would look. We wouldn't want the if/elif/else block to become if/else here b/c there could still be issues internally (this is a "private" function). 

Probably better to leave as is, unless you have a way I'm not seeing (in which case please post your proposal)

**Comment by naught101** [comment]
No, I don't, because I don't see the case where this can get hit. But if there is a case (or if a case shows up later due to calling function changes), then it would still make sense to just accept this PR as is, because it won't break anything, and it would make the error more informative.

**Comment by rlucas7** [comment]
@WarrenWeckesser @rgommers thoughts on merging this? 

I'd have no strong opinion in which direction. 

There is clearly a more informative error messaging, tricky part is if this is now possible to execute or not.

Could also be a backport for prior released versions (say 1.3.x where issue originally surfaced, perhaps 1.2.x long term support as well).

**Comment by tylerjereddy** [comment]
> Could also be a backport for prior released versions (say 1.3.x where issue originally surfaced, perhaps 1.2.x long term support as well).

Ooof, Ralf may have to poke me a bit for that to happen. I was hoping to focus on the `1.5.x` series moving forward since we've just finally removed our reliance on the rackspace infrastructure for asset hosting.

If this needs a `1.5.x` backport I could certainly do that--there's no way we'll get to December 2020 without another release in that series.

**Comment by rlucas7** [comment]
@tylerjereddy

Ah, well that sounds to me like a reason to close?

The different PR already added a different fix in 1.5 so a back port for that wouldn’t be necessary. 

If we did decide to backport this would be a low priority change I’d guess. The error messaging is all that is changed. The prior versions returned an error but with no message so was confusing to users. This PR adds a message. But previous PR (seems to have) obviated the error In this PR whose messaging is added. 

-Lucas Roberts

**Comment by rgommers** [comment]
I don't think this is the kind of thing we'd backport, and definitely not to <1.5.x at this point. I'd say going back more than one minor release is for critical issues (security, segfaults, major correctness issues) only.

It's fixed in 1.5.x already and there is agreement there's no way to trigger the issue anymore, so let's close this. Thanks all.

**Pull request closed without merging**
