### PR TITLE
DOC+MAINT: optimize: lb and ub in the Bounds constructor are not optional

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Also fix a really long line.

### CODE REVIEW

**Comment by mdhaber** [comment]
Do you want to add a test comparing the repr against the expected string?

**Comment by WarrenWeckesser** [comment]
The repr can change over time (e.g. it changed when `lb` and `ub` were passed through `np.asarray` before being saved as attributes), so I don't know if an exact match of the repr to a string is what we want.  How about `eval`ing the repr and checking that we get back what we put in?  Something like


    b = Bounds([1, 2], 100)
    s = repr(b)
    b2 = eval(s)
    assert_array_equal(b.lb, b2.lb)
    assert_array_equal(b.ub, b2.ub)
    assert_array_equal(b.keep_feasible, b2.keep_feasible)

(and another with an explicit `keep_feasible` argument).

**Comment by mdhaber** [comment]
Sure. Sounds good.

**Comment by WarrenWeckesser** [comment]
That was easy... it turns out the tests are already there: https://github.com/scipy/scipy/blob/ac23f85a38e7fa8a4447ff53d7cda079ab09315a/scipy/optimize/tests/test_constraints.py#L171

**Comment by mdhaber** [comment]
OK I'll merge when the last test finishes.

**Comment by mdhaber** [comment]
I don't know if the last test is going to finish.

**Comment by WarrenWeckesser** [comment]
I restarted the stalled job. They're all green now.

**Pull request merged**
