### PR TITLE
Revert to old behaviour for constant cost matrices in `linear_sum_assignment`

### LINKED ISSUE #11602: scipy.optimize.linear_sum_assignment returns reverse diagonal indices for constant arrays in 1.4.1, when it should return normal diagonal indices.
`scipy.optimize.linear_sum_assignment` return reverse diagonal indices for constant arrays in 1.4.1. I found this issue when upgrading scipy from 1.3 to 1.41, where this function yields different results. In 1.3 it returns diagonal indices (e.g. [0,0], [1,1], [2,2] ...) while in 1.4.1 it returns reverse diagonal indices (e.g. for array with shpe [20, 20], the returned indices are [0, 19], [1, 18], [2, 17]...).

#### Reproducing code example:

```
import numpy as np
from scipy.optimize import linear_sum_assignment
row_ind, col_ind = linear_sum_assignment(np.ones([20, 20]))
print("row: ", row_ind)
print("col: ", col_ind)
```
For version 1.3, the above prints:
```
row:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
col:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
```
While version 1.4.1 prints:
```
row:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
col:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
```

#### Scipy/Numpy/Python version information:
The two scipy versions given by the command `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)` are:
```
1.4.1 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```
and
```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by pmla**
#### Reference issue

Closes #11602

#### What does this implement/fix?

This is a cosmetic change which selects the identity matrix as the solution for constant inputs.

### CODE REVIEW

**Comment by pmla** [comment]
@rgommers do you want to take a look here?

**Review by tylerjereddy — APPROVED** [review]
The code change + test looks sensible, thanks Peter. If I understand correctly the same minimized cost would be achieved for any permutation of the column indices with this kind of constant + square input.

**Comment by pmla** [comment]
>  If I understand correctly the same minimized cost would be achieved for any permutation of the column indices with this kind of constant + square input.

Absolutely right. Thanks for the merge.

**Comment by rgommers** [comment]
Thanks @pmla! And thanks @tylerjereddy for reviewing

**Pull request merged**
