### PR TITLE
update cython to 0.28

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by pv** [comment]
It's purposefully old version to check for compatibility.

**Comment by ilayn** [comment]
Related issues #8581 and linked therein

**Comment by rgommers** [comment]
no response and not a change we want/need, so closing. thanks @auvipy

**Comment by glorioushedgehog** [comment]
I don'y know why @auvipy wanted scipy built with Cython 0.28, but I could really use it because of this bug: https://github.com/cython/cython/issues/1953#issuecomment-398128940
Cython 0.28 fixes it, but I can't find any downloads of scipy built with cypthon 0.28. Is this available anywhere? It would be really great if I could avoid setting up the environment for building scipy on my own.

**Comment by andyfaff** [comment]
Bumping cython will also be required for supporting Python3.7.

**Comment by pv** [comment]
Everything in scipy 1.1.0 is already built with Cython 0.28.2. The official locations are https://pypi.org/project/scipy/ and https://github.com/scipy/scipy/releases --- for everything else, you'll need to deal with the third party from which you are downloading stuff.

**Pull request closed without merging**
