### PR TITLE
DOC: Removing old forwarding file to roadmap

### LINKED ISSUE #17229: BUG: link to roadmap broken
### Describe your issue.

The link to the roadmap in this file is broken:
https://github.com/scipy/scipy/blob/main/doc/ROADMAP.rst.txt

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
404 :)
```

### SciPy/NumPy/Python version information

main

### PR DESCRIPTION
**Pull request by bjorges**
#### Reference issue

Closes #17229 

#### What does this implement/fix?

Remove redundant file.

#### Additional information

My first hacktoberfest PR

### CODE REVIEW

**Comment by tupui** [comment]
Hi @bjorges, thank you for making a PR. Note that we do not participate, nor want to participate in Hacktoberfest.

Still, the change might be integrated once we decide on what to do.

**Comment by bjorges** [comment]
No problem, just wanted to give something back. Have been helping scientists a lot and many use your tool.

**Comment by bjorges** [comment]
Just realized that OP also was new to contributing. Feel free to just reject my PR if he would like to learn how to contribute to OSS too.

**Review by melissawm — APPROVED** [review]

**Comment by melissawm** [comment]
@bjorges @janusheide thanks both - if you are interested we do host [community meetings and monthly new contributor meetings](https://scientific-python.org/calendars), if you need to ask questions or figure out where your contributions would fit. Feel free to reach out!

**Pull request merged**
