### PR TITLE
CI: speed up continuous integration builds

### PR DESCRIPTION
**Pull request by pv**
- Drop the second Python 2.7 build on Travis, running full test suite on Python 3.6

- Parallelize Cython generation. This takes a non-negligible chunk of the total build time, so parallelization could save some minutes.

- Turn on build parallelization (has an effect if numpy >= 1.10)

- Don't build html docs on travis. Instead, upload the already built docs to scipy/devdocs from circleci (ssh deploy key for that specific repository, similarly as it was on travis).

### CODE REVIEW

**Comment by ev-br** [comment]
Circle CI fails with
```
  File "/home/ubuntu/scipy/tools/cythonize.py", line 232, in find_process_files
    for result in pool.starmap(process, jobs):
AttributeError: 'ThreadPool' object has no attribute 'starmap'
```

**Comment by pv** [comment]
fix'd, forgot python 2...

**Comment by pv** [comment]
Moved doc build+scipy/devdocs upload, which is run after merges, from travis from circleci (which already has the docs built), as it's pushing the build over 50 min.

**Comment by rgommers** [comment]
> (ssh deploy key for that specific repository, similarly as it was on travis).

We kept the TravisCI ssh key for this in this repo (removed in this PR), but there's no CircleCi one added here. So would be good to document where that's stored and how it was created (presumably in the CircleCI UI?).

**Comment by rgommers** [comment]
LGTM, merging. Thanks Pauli!

**Comment by rgommers** [comment]
Build for this merge running at https://circleci.com/gh/scipy/scipy/3566, will check that that updates http://scipy.github.io/devdocs correctly

**Comment by pv** [comment]
Deploy step didn't seem to work, because apparently `cd` doesn't carry 
over to multiple commands on circleci.
.
It should use a multiline command (on circleci this is `- >` instead of 
`-|` as on travis, see 
https://discuss.circleci.com/t/cd-command-ignored-in-test-section/357) 
since apparently each `-` command entry is run in a separate shell.
.
Also, the `make html-scipyorg` command could be removed since it's 
already run.

**Comment by pv** [comment]
Sorry, wrong circleci discussion link: 
https://discuss.circleci.com/t/writing-a-multiline-command-in-configuration-file/3042/4

**Comment by pv** [comment]
The deploy key is managed using circleci's "SSH deploy keys" 
https://circleci.com/docs/1.0/configuration/#ssh-keys
.
In the settings the "Pass secrets to fork builds" option is turned off, 
so it's only available to merges to main repository, as it should be.

**Pull request merged**
