### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by uniontech-lilinjie**
Signed-off-by: lilinjie lilinjie@uniontech.com
fix typo

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
@tupui, could you provide a link to the relevant documentation?  There is the note in https://docs.scipy.org/doc/scipy/dev/hacking.html#maintaining-existing-code, which applies to code style changes (e.g. whitespace tweaks and other PEP-8 adjustments), but this PR is fixing something that is clearly wrong, and *should* be fixed.  We should not reject such PRs.

Sure, *ideally* it would be better if the contributor combined of bunch a similar small fixes into one PR, but not doing that should not stop us from accepting such an obvious improvement.  What if they can't find similar small fixes?

I think it would be better to accept it, while also suggesting that, in the future, the ideal case would be to combine several small changes into one PR.  We can also explain then how to use the commit message markup to avoid running the full CI suite on what is a doc-only change.

**Comment by tupui** [comment]
@WarrenWeckesser I disagree.

> clearly wrong, and should be fixed

There is just a single letter missing and it does not change the meaning, so I would say this has absolutely 0 impact. On some projects they even deliberately introduce typos like that to discourage people to send typo fixes.

I argue that it's really counter productive to accept to deal with such PRs, it's like styling. We keep fighting over and over while saying we don't care. Closing without merging sends a stronger signal to everyone looking to "score a PR" (I am not implying this is the case here and it does not matter, I refer to things like Hacktoberfest and other OSS programs from some schools which only focus on having a contribution regardless of any quality.)

**Comment by WarrenWeckesser** [comment]
The number of characters is not relevant.  The incorrect spelling is.  As far as zero impact--well, I don't know how to respond to the suggestion that spelling mistakes should not be corrected because "it does not change the meaning".

> On some projects they even deliberately introduce typos like that to discourage people to send typo fixes.

That's ridiculous. Do you have a link?

I've submitted small typo corrections to several projects, and the response has *always* been "Thanks!".  We should be just as welcoming.

> I argue that it's really counter productive to accept to deal with such PRs, it's like styling. 

This is *not* styling, so the comparison is not relevant.  This is a clear, unambiguous mistake.  It should be fixed.

**Comment by tupui** [comment]
> That's ridiculous. Do you have a link?

I cannot find it now. I read a few general articles about making intentional mistakes. Besides what I outlined above, there are a few motives to do so: from moving the discussion away from the topic at hand, trying to get more attention by initially writting something false, to trying to remove the image of perfection to something to lower some social barriers.

What I could quickly find is a big project asking people to not sent typo fixes: TypeScript
https://github.com/microsoft/TypeScript/blob/21db2ae9a2cb8ba88f9b10ac11d3bbd928bde3b1/.github/pull_request_template.md?plain=1#L13

> We should be just as welcoming.

I honestly think I was being welcoming. I started by thanking the new contributor for openning a PR, then continued on explaining why we could not consider the contribution and finally gave a possible path for improvement so we can in the future reconsider it.

If you felt differently @uniontech-lilinjie, I sincerely apologise. It is true that I usually try to add a smiley or two and make this a bit lengthier to try to better convey my emotions. Which I simply forgot to do here.

> The number of characters is not relevant. The incorrect spelling is. As far as zero impact--well, I don't know how to respond to the suggestion that spelling mistakes should not be corrected because "it does not change the meaning".
> ...
> This is not styling, so the comparison is not relevant. This is a clear, unambiguous mistake. It should be fixed

This is not what I am saying nor implying and I agree that this mistake should ultimately not stay there. What I am saying instead is that we should not accept, nor send a message, saying we accept, PRs that solely focus on fixing small typos.

I could as well write a bot that would make a PR to fix typos (hopefully I will not give some ideas saying that.) That might sounds ridiculous, but that could easily happen, even more if some kind of automated process is involved and misconfigured. Then following your logic we should accept all these contributions and say thank you.

**Comment by rkern** [comment]
> What I am saying instead is that we should not accept, nor send a message, saying we accept, PRs that solely focus on fixing small typos.

You have been [reminded before](https://github.com/scipy/scipy/pull/16578#event-6981789382) that while this may be your personal preference, it is not the project's policy. Please do not claim that our contributor guidelines say this; [they say the opposite](http://scipy.github.io/devdocs/dev/contributor/rendering_documentation.html).

**Review by rkern — APPROVED** [review]

**Pull request merged**
