### PR TITLE
ENH: Release the GIL while computing KDE kernel estimate

### PR DESCRIPTION
**Pull request by mobiusklein**
#### What does this implement/fix?
The computationally intensive part of the `scipy.stats.gaussian_kde.evaluate` involves calling `gaussian_kernel_estimate`, which has a triply nested for-loop, but does not release the GIL. This loop could be parallelized by OpenMP as well, but lacking a guide on when and how `scipy` controls this, I opted to just release the GIL and leave it to the user to call it from multiple threads.

This should have a negligible impact on existing code but enable future code to evaluate KDEs while other code occupies the GIL. I doubled the speed of my algorithm using three threads using `concurrent.futures.ThreadPoolExecutor` instead of the singly threaded implementation. 

#### Additional information
I'm unable to build `scipy` from source locally, and hope that the continuous integration system can exercise the full test suite. I have extracted the logic into a separate Cython module and tested it in isolation.

This change does open the possibility that user code might mutate the memory buffers behind the attributes of the `scipy.stats.gaussian_kde` object while concurrently using those buffers in another thread. Fortunately, no API code appears to modify attributes in-place.

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Thank you @mobiusklein for the PR. We don't allow usage of OpenMP in SciPy for various reasons.

The change seems good otherwise. I am wondering if we could not put more operations in the nogil statement. And also maybe moving the hot part to a cdef could bring additional performance?

@jjerphan this might interest you.

**Comment by mobiusklein** [comment]
@tupui I moved the loops to a `cdef` function that runs without the GIL and just invoke that inside the nogil block. This may be a little bit slower in the trivial case because now we have to pass and acquire five buffers, but shouldn't make the performance that much worse.

**Review by jjerphan — APPROVED** [review]
LGTM, thank you @mobiusklein.

To follow-up on your comment:

> This may be a little bit slower in the trivial case because now we have to pass and acquire five buffers, but shouldn't make the performance that much worse.

The cost of using a dedicated `cdef` and `nogil` function, especially if this function is `inline`-qualified, really is negligible.

**Comment by jjerphan** [comment]
To answer your questions, @tupui:

> I am wondering if we could not put more operations in the nogil statement.

Calling the numpy Python API and raising errors:
https://github.com/scipy/scipy/blob/88e68004b078c6d503e5c77a09d144decedee7b7/scipy/stats/_stats.pyx#L742-L751

necessitate interacting with the CPython interpreter. Hence no other operation in `gaussian_kernel_estimate` can be move in the `nogil` context.

> And also maybe moving the hot part to a cdef could bring additional performance?

That's right. It's a necessary condition for optimal performance but not a sufficient one (in particular it's still possible to be bound to the GIL in a `cdef` function).

**Comment by tupui** [comment]
Thanks @jjerphan for the precisions.

About moving more things, I was referring to the dot products and the type casting. But yes if that's better to keep this in Python no problem.

```python
points_ = np.dot(points, whitening).astype(dtype, copy=False) 
xi_ = np.dot(xi, whitening).astype(dtype, copy=False) 
values_ = values.astype(dtype, copy=False)
```

**Comment by jjerphan** [comment]
Ah yes, it's possible to perform them in a `nogil` context (e.g. via calls to BLAS directly) but one still need to allocate buffers for them, so keeping those in Python makes sense.

**Review by mdhaber — COMMENTED** [review]
@jjerphan @mobiusklein @tupui I merged upstream/main here after changes to the way "whitening" is done. I don't have much experience with Cython so I'm not sure if the copying of `cho_cov` to `cho_cov_` is needed, but it was the quick way of getting Cython to find a "suitable method" during compilation. Please fix!

Re: Black - IMO we can do that when SciPy converts to Black. I don't see that this function deserves special treatment. You're welcome to change it back if you want, but since resolving merge conflicts required some work, I reverted to the usual style of formatting (personal taste under the constraints of PEP8, for better or for worse).

Otherwise, is this ready to go? I believe that the algorithmic code has been copied over to the `gaussian_kernel_estimate_inner` function correctly, so if you can confirm that the Cython is what we want and demonstrate the impact on speed (e.g. [`asv compare`](https://asv.readthedocs.io/en/stable/commands.html#asv-compare) on the benchmarks would be ideal), I can merge.

**Comment by mobiusklein** [comment]
@mdhaber 
The `cho_cov_ = cho_cov.astype(dtype, copy=False)` step is correct. The conversion logic in this function is obtuse because Cython can't infer fused type specializations from buffer types and we are passing five buffers which can all be different numerical types with different widths but want to do all of the computation on a single type.

I can't actually _build_ `scipy` locally, so unless https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=20229&view=logs&j=ede89041-5e8e-5201-ce5c-f68c2cbf02dd&t=88295f8e-e8a1-53ce-523a-c740e2f72a8d runs the `asv` tests you are referring to, I can't check this formally.

If that is a blocker, what are alternatives?

**Comment by mdhaber** [comment]
> If that is a blocker, what are alternatives?

Well, we need to see something that demonstrates that this is an improvement. [Here](https://github.com/scipy/scipy/blob/cc63003326b7ae2e9dd41cd6af0e6e3079c32b95/benchmarks/benchmarks/stats.py#L431) is the benchmark code. As an executable snippet, it's something like this:

```python3
import numpy as np
from scipy import stats

rng = np.random.default_rng(12345678)
n = 2000
m1 = rng.normal(size=n)
m2 = rng.normal(scale=0.5, size=n)
xmin = m1.min()
xmax = m1.max()
ymin = m2.min()
ymax = m2.max()

X, Y = np.mgrid[xmin:xmax:80j, ymin:ymax:80j]
positions = np.vstack([X.ravel(), Y.ravel()])
values = np.vstack([m1, m2])
kernel = stats.gaussian_kde(values)

kernel.pdf(positions)
```

Timing just that last line using `%timeit`, I get:
```
137 ms ± 147 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # main
147 ms ± 211 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)  # PR
```

The benchmark size was reduced recently, and I thought it might need a larger size to shine, so I bumped it back up to the original:
```python3
X, Y = np.mgrid[xmin:xmax:200j, ymin:ymax:200j]
```

And I see:
```
852 ms ± 855 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)  # main
922 ms ± 1.57 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # PR
```

Is there a larger size problem at which I'd expect to see a performance improvement, or will I just not benefit from this on my machine?
I'm curious what others get here. 

|      | 80x80  | 200x200 |
|------|--------|---------|
| main | 137 ms    | 852 ms    |
| PR   | 147 ms | 922 ms  |

**Comment by mobiusklein** [comment]
On its own, my changes don't make `gaussian_kde.evaluate` faster. What they do is release the global interpreter lock while doing the time consuming triply nested for-loop of numerical operations so that while that's happening, another thread can occupy the Python interpreter (or that function may be called from multiple threads).

```python
import numpy as np
from scipy import stats

rng = np.random.default_rng(12345678)
n = 2000
m1 = rng.normal(size=n)
m2 = rng.normal(scale=0.5, size=n)
xmin = m1.min()
xmax = m1.max()
ymin = m2.min()
ymax = m2.max()

X, Y = np.mgrid[xmin:xmax:80j, ymin:ymax:80j]
positions = np.vstack([X.ravel(), Y.ravel()])

values = np.vstack([m1, m2])
kernel = stats.gaussian_kde(values)

from isolated_c_extension import evaluate_gaussian_kde

def reference():
    return kernel.pdf(positions)

def single_thread_modified():
    return evaluate_gaussian_kde(kernel, positions)

%timeit reference()
%timeit single_thread_modified()
```
These singly threaded executions on my box give me:
```
# master, singly threaded
131 ms ± 922 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
# PR, singly threaded
141 ms ± 654 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Now, I spin up a small thread pool in Python
```python
from concurrent import futures

executor = futures.ThreadPoolExecutor(3)

def multi_thread_reference():
    jobs = []
    step_size = positions.shape[1] // 3
    for i in range(3):
        chunk = positions[:, i * step_size:(i + 1) * step_size]
        jobs.append(
            executor.submit(
                kernel.pdf,
                chunk
            )
        )
    return [j.result() for j in jobs]

def multi_thread_modified():
    jobs = []
    step_size = positions.shape[1] // 3
    for i in range(3):
        chunk = positions[:, i * step_size:(i + 1) * step_size]
        jobs.append(
            executor.submit(
                evaluate_gaussian_kde,
                kernel,
                chunk
            )
        )
    return [j.result() for j in jobs]

%timeit multi_thread_reference()

%timeit multi_thread_modified()
```
Again, timing on my box with that thread pool (which drains completely between each execution of the benchmark)
```
# master, three threads
130 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
# PR, three threads
48.5 ms ± 631 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
So by running the function in chunks over three threads I get a ~260% speed up on the same data. This never quite reaches the # of threads because the memory allocation and buffer type conversion operations that are done up-front are still holding the GIL.

In my use case, I actually have four independent KDEs I need to evaluate dozens of times per iteration on a potentially large (10k+ points) dataset, this lets me evaluate them all concurrently rather than wait for each to run in sequence.

**Comment by mdhaber** [comment]
OK, I see now. To me that sounds like enough of a potential improvement - to those who seek it - to justify the slight regression in the usual case. @tupui @jjerphan please let me know if you think that's right. In the meantime, I'll go ahead and merge.

**Comment by tupui** [comment]
All good to me 👍

**Comment by jjerphan** [comment]
LGTM. :+1: 

Potentially, there might be subscription with the above proposal proposed in https://github.com/scipy/scipy/pull/16758#issuecomment-1234985423 if it is being used in user-code with another layer of parallelism.

[`threadpoolctl`](https://github.com/joblib/threadpoolctl/) might help prevent such problems, but this would add another dependency to SciPy.

**Comment by tupui** [comment]
> [`threadpoolctl`](https://github.com/joblib/threadpoolctl/) might help prevent such problems, but this would add another dependency to SciPy.

It might yes. We are discussing parallelism architecture in general as part of the NASA Roses Grant (Thomas from scikit-learn is there as well). So let's wait for this group to make a community RFC.

**Comment by jjerphan** [comment]
Oh, that's nice to know! To me, @scientific-python comes at the perfect place to coordinate on such subjects across projects generally. What do you think?

(cc @jeremiedbb and @ogrisel who might be interested in such coordination.)

**Comment by tupui** [comment]
As Thomas is leading this on Scikit-learn's side, I would suspect everyone to already be in the loop internally 😉

Yes Scientific Python will be used but at a later stage. I think it's too early to involve a larger audience.

**Comment by jjerphan** [comment]
> As Thomas is leading this on Scikit-learn's side, I would suspect everyone to already be in the loop internally wink

Here is [a recent document from Thomas](https://thomasjpfan.github.io/parallelism-python-libraries-design/) which recaps parallelism in the Scientific Python ecosystem, the current issues (especially regarding shipping code and shared libraries on PyPI), and some proposals to resolve them. I think this document comes as a preliminary to the work for NASA Roses Grant @tupui mentioned.

**Comment by andyfaff** [comment]
The document seems like a really good description. However, there's a few biggish things that aren't covered.

1. The document is focused on parallelism in BLAS. There are several places in the codebase that are parallelised (or could be parallelised) with multiprocessing or other threading models. The `workers` keyword in `optimize.differential_evolution` is one such example. I think the document needs to be expanded to cover parallelism in non-BLAS situations. The whole parallelism hierarchy is important because those situations could end up eventually calling threaded BLAS routines.
2. The document doesn't cover parallelism and design choices in extension code. One example might be the `prange` possibilities in cython that were being discussed above.

**Comment by jjerphan** [comment]
Thank you for your additions, @andyfaff.

Should we pursue discussions on [the source repository](https://github.com/thomasjpfan/parallelism-python-libraries-design) issue tracker rather than on this issue? (I've asked @thomasjpfan if he welcomes pull requests for additions to this document.)

**Comment by andyfaff** [comment]
See https://github.com/thomasjpfan/parallelism-python-libraries-design/issues/1

**Pull request merged**
