### PR TITLE
MAINT: fix shapes of Wishart/Inverse Wishart samples

### PR DESCRIPTION
**Pull request by dschmitz89**
#### Reference issue
Part of #16278

#### What does this implement/fix?
Tries to fix edge cases of the samples generated by `wishart`, `invwishart`. Specifically, these arguments for `size` are tested:
* `None`
* `(1, )`
* `1`
* `()`

#### Additional information
The code is admittedly messy but a generic solution to this seems very hairy to me.

### CODE REVIEW

**Comment by mdhaber** [comment]
@dschmitz89 I'd suggest that we not do this right now. Please see the history with `dirichlet` tracked in gh-16278.

**Comment by dschmitz89** [comment]
@mdhaber : closing seems to make sense then. Could that issue be marked in some way though? Looks like I wasted my precious morning coffee time ;).

I had a look at the fitting PRs. The math looks exhausting, but I will see what I can do!

**Comment by mdhaber** [comment]
Sorry about that! scikit-learn has Easy, Medium, and Hard labels. We might consider that.
In the meantime, I've assigned it to myself and added a note at the top of gh-16278. Does that look appropriate?

**Comment by dschmitz89** [comment]
Message in that thread looks good. Let's also mark are other issues like that to avoid that other contributors get trapped in the same rabbit hole.

**Pull request closed without merging**
