### PR TITLE
MAINT: Removed an unused import in scipy/constants.

### PR DESCRIPTION
**Pull request by pvanmulbregt**
#### Reference issue
Further work on gh-11529

#### What does this implement/fix?
Removed an unused import in scipy/constants.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
While I'm skeptical that the AppVeyor failure is real, the name of the failing test is slightly disturbing given the context:

```
================================== FAILURES ===================================
_________________ _build_utils/tests/test_circular_imports.py _________________
[gw0] win32 -- Python 3.7.5 C:\Python37-x64\python.exe
worker 'gw0' crashed while running '_build_utils/tests/test_circular_imports.py::test_importing_submodules'
```

**Comment by jakobjakobson13** [comment]
There were previous pull request concerning the scipy.constants module (#11345 and #11343 by @pv). They use the imported `sqrt` function as far as I can see.

**Comment by pvanmulbregt** [comment]
When `Lib/sandbox/constants/codata.py` was added in 2006, it it did indeed use the `sqrt`
```
'characteristic impedance of vacuum': (sqrt(mu0/epsilon0), 'ohm', 0.0),
```
but it was removed in @jakobjakobson13's  gh-10920.
If gh-11345 and gh-11343 by @pv are going to be accepted and merged soon, then there is no point to remove `sqrt` now, and that is the only change in the PR.

**Comment by pvanmulbregt** [comment]
Closing as only removing one symbol which will be needed again in gh-11343 gh-11345

**Pull request closed without merging**
