### PR TITLE
MAINT: interpolate: Fix a few build warnings.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
A couple more easy wins in Warren's war on warnings. 😄

### CODE REVIEW

**Comment by rgommers** [comment]
thanks!

**Comment by person142** [comment]
p.s. I love seeing these warnings getting fixed!

**Comment by ilayn** [comment]
Same here. My inner ocd thanks you!

**Comment by WarrenWeckesser** [comment]
There are many more warnings waiting to be fixed!  Go ahead, share the love, indulge your inner ocd...

I would be thrilled if we could get to where the build has zero warnings, but there are probably a few big obstacles to that goal.  In the meantime, there are many warnings that will be trivial to fix.

**Comment by ilayn** [comment]
Actually only two warnings left `?gees`/`?gges` on the lapack part of the build and a lot of them are still in BLAS about using * instead of the actual dimension of the input. I don't know if we should fix them in case someone is actually using random length arrays over them. Most warnings are from gfortran dummy variable warnings though. 

Maybe we should turn off that warning instead? Because we don't do anything about them in the 3rd party libs.

**Comment by rgommers** [comment]
> I don't know if we should fix them in case someone is actually using random length arrays over them

Is that something that is specific to `gees/gges` or is it just that we happened to leave in `?` only for those functions? I'm not sure of the details, but if it's just an inconsistency then we may as well fix it.

**Comment by ilayn** [comment]
This is mostly a BLAS issue and it is a bit confusing for me too. Currently our BLAS wrappers (mostly level 1) uses the `*` argument for leaving the length of the array to runtime detection. This is beneficial for plugging an arbitrary array and form a subarray by indicating "take every third element in this array 10 times" to get the actual data even though the original array might be 400 element long. Such that you can pack a lot of data into a single array. In the second call you can provide a 200 element long array and all would be working fine since the input array size unspecified (as long as the strides jumps are within the bounds)

However when the compiler sees this (probably due to some flag) it goes "I can't detect the dimension of this array and I'll assume 0 for now" and emits the warnings. On LAPACK side we use definite paramaters `n, m` for the input array size hence no warnings are emitted. That's what I meant by I don't know if we fix the input array size.

**Comment by rgommers** [comment]
Thanks for the explanation. I haven't seen that used in the wild, but it could be. No idea what is best here ...

**Pull request merged**
