### PR TITLE
MAINT: Simplify floats in constants.py

### PR DESCRIPTION
**Pull request by jakobjakobson13**
Simplify floats in constants.py

### CODE REVIEW

**Comment by NickHilton** [comment]
This also changes the `dtype` of the constants from `float` to `int` which is maybe not desired

`type(5) == int`
`type(5.) == float`

**Comment by jakobjakobson13** [comment]
> This also changes the `dtype` of the constants from `float` to `int` which is maybe not desired
> 
> `type(5) == int`
> `type(5.) == float`

That's true, but I guess the writing of the floats as `5.` comes from the python2 when `2/3` equaled `0`. In python3 it is not really necessary to write floats as`2/3` equals now `0.6666...` .
Furthermore I could not find any import of any constant in the `scipy.constants` module except phi which is used in the `_rotation_group` module. So there should not be any harm except any user imported manually a constant and checked its type.

**Comment by rgommers** [comment]
> So there should not be any harm except any user imported manually a constant and checked its type.

There's also the possibility of changing some array to an integer type and causing overflow somewhere. There's only small chances of this happening, but with 10M users someone is likely to run into this. They're also unnecessary changes, so no need to take small chances. I'm fine with the temperature related ones (those stay floats), but can you please revert the others?

**Comment by rgommers** [comment]
Merged, thanks @jakobjakobson13

**Pull request merged**
