### PR TITLE
BUG/TST: numpoints not updated for incremental Voronoi

### LINKED ISSUE #4791: BUG: scipy.spatial: incremental Voronoi doesn't increase size of point_region array
Something about the incremental mode of Voronoi diagrams is wrong, because the `point_region` array doesn't expand when more points are added.

Here's a simple test case, running on scipy master:

```
In [1]: from scipy.spatial import Voronoi

In [2]: import numpy as np

In [3]: v = Voronoi(np.random.random((5,2)), incremental=True)

In [4]: v.npoints
Out[4]: 5

In [5]: v.point_region
Out[5]: array([0, 4, 2, 3, 1])

In [6]: v.add_points(np.random.random((3,2)), restart=False)

In [7]: v.npoints
Out[7]: 8

In [8]: v.point_region
Out[8]: array([0, 5, 4, 1, 3])
```

Expected behavior (which we get with `restart=True`) is that `v.point_region` will have 8 elements.

### PR DESCRIPTION
**Pull request by perimosocordiae**
This adds a test and fixes #4791.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Travis failed twice: one timeout and one relaxed strides segfault. Should I close and reopen to run again?

**Comment by rgommers** [comment]
I've restarted it, no need to close/reopen.

**Comment by perimosocordiae** [comment]
Thanks, Travis is happy now.

**Comment by pv** [comment]
LGTM

**Pull request merged**
