### PR TITLE
Backports for 0.17.1

### PR DESCRIPTION
**Pull request by ev-br**
<s>This still needs a fix for https://github.com/scipy/scipy/issues/6134</s>

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@ev-br we should probably also backport #6135

**Comment by Eric89GXL** [comment]
Tests pass for me (Ubuntu 64-bit, MKL) other than those related to #6135.

**Comment by pv** [comment]
The Travis tests apparently found a bug in pyflakes :)

**Comment by ev-br** [comment]
Cherry-picked the commits from gh-6135 to this branch. 
The pyflakes glitch is amusing indeed :-).

**Comment by argriffing** [comment]
links related to this pyflakes bug:
https://bugs.launchpad.net/pyflakes/+bug/1560134
https://github.com/pyflakes/pyflakes/pull/61

**Comment by ev-br** [comment]
All green apart from pyflakes, merging. Thanks all.

**Pull request merged**
