### PR TITLE
ENH: stats.ansari: add axis / nan_policy / keepdims support

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Toward gh-14651

#### What does this implement/fix?
Adds axis / nan_policy / keepdims support to `scipy.stats.ansari`.

#### Additional information
The one thing I noticed is that currently, for Nd input, `ansari` returns a scalar result. However, the result seems to be garbage - it's different from `axis=None` / raveling the arrays before passing them to the function. So I think it's safe to let `axis=0` be the default since there's no useful behavior to maintain.

### CODE REVIEW

**Comment by rgommers** [comment]
Two CI failures are unrelated, I'll open a PR for those now.

**Comment by tirthasheshpatel** [comment]
<details>

<summary>Slightly modified code to test the ansari func:</summary>

```python

```

</details>

For 2D arrays, Ansari seems to be raveling the arrays, so I think passing `default_axis=None` in the decorator would resolve this:

```
2D Array, no axis
AnsariResult(statistic=array([10., 10., 10., 10., 10., 10.]), pvalue=array([1., 1., 1., 1., 1., 1.]))
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
vs (master)
AnsariResult(statistic=-52.0, pvalue=0.41830285225706465)
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
```


Ansari didn't respect masks before, so different results here:

```
1D Masked array, one masked
AnsariResult(statistic=6.5, pvalue=0.7670968684102772)
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
vs (master)
AnsariResult(statistic=10.0, pvalue=1.0)
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
```

```
1D Masked array, all masked
<class 'ValueError'>: Not enough other observations.
vs (master)
AnsariResult(statistic=6.5, pvalue=0.7670968684102772)
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
```

```
1D Masked array, all but one masked
AnsariResult(statistic=1.5, pvalue=0.6547208460185769)
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
vs (master)
AnsariResult(statistic=6.5, pvalue=0.7670968684102772)
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
```

One dtype discrepancy:

```
2D Masked Array, float32, axis=1
AnsariResult(statistic=array([15.5, 21. , 15.5, 21. ]), pvalue=array([0.85895492, 1.        , 0.85895492, 1.        ]))
<class 'scipy.stats._morestats.AnsariResult'> float64 float64
vs (master)
<class 'TypeError'>: ansari() got an unexpected keyword argument 'axis'
```

**Comment by mdhaber** [comment]
> For 2D arrays, Ansari seems to be raveling the arrays, so I think passing default_axis=None in the decorator would resolve this:

Please see top post.

**Review by tirthasheshpatel — APPROVED** [review]
Played around a bit with this and can't find any obvious issues. So, LGTM!

**Pull request merged**
