### PR TITLE
ENH: stats: Improve behavior of genextreme.sf and genextreme.isf

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
Added the methods genextreme._sf and genextreme._isf to improve numerical
precision in the tails.

### CODE REVIEW

**Comment by argriffing** [comment]
Some of the continuous stats functions use lazywhere instead of `where`, would that make sense for this function too?

**Comment by WarrenWeckesser** [comment]
@argriffing Yes, it would make sense.  Currently a spurious warning is generated when `c` is 0 (a preexisting condition, actually).  I thought about it just before creating the PR, but I ended up being too lazy to add the `lazywhere`s.  I'll update the PR within the next day or so.

**Comment by WarrenWeckesser** [comment]
Updated to use `_lazywhere` in the new methods.

The other methods (`_pdf`, `_cdf`, etc) should also use `_lazywhere`, but I'm not going to have time to update all the existing methods.  I would be happy if someone took over this pull request and made those changes, or it could be done in a separate pull request.

**Comment by argriffing** [comment]
Maybe add more test coverage? I changed `x` to `2*x` in the degenerate branch and it still passed tests...

I think it's OK to leave other functions alone. They can be updated to use `_lazywhere` in a different PR.

**Comment by argriffing** [comment]
Thanks @WarrenWeckesser!

**Comment by WarrenWeckesser** [comment]
@argriffing You're too fast!  You are right that I should have included some more tests--I *am* getting lazy!

I'll create a new pull request with another test or two.  I'd say "in the next day or so", but these days my time estimates often end up into the next higher unit of measurement (i.e. it becomes "in the next week or two").

**Comment by WarrenWeckesser** [comment]
Of course, I won't complain if *you* do it. 😄 (#6178)

**Pull request merged**
