### PR TITLE
MAINT: ckdtree codebase clean up

### PR DESCRIPTION
**Pull request by rainwoodman**
- refactor two distance headers to distance.h and distance_box.h
- move the side_distance calculation into distance.h
- clean up nodeinfo
- better support of 0 in boxsize (disabling the boundary) added test case.
- bigger tests for query_ball_point and query_knn

The main remaining issue is that query_knn uses a queue but the rest uses recursion. Maybe they shall all be converted to queues.

The code has no major noticeable slowdowns, though
- it is strange that p=1 is slower than p=2 or p=inf (has been so in master). 
- the periodic case is slightly slower by about 5%. I am stuck here.  boxsize=0 case has the same speed. So the difference is due to BoxDist1D::side_distance_from_min_max. But  the code is essentially the same code written in a shorter form.

Here is the benchmark; the before commit contains only bug fixes on zero boxsizes (some are from @jmbr 's branch)

```
· Running 2 total benchmarks (2 commits * 1 environments * 1 benchmarks)
[  0.00%] · For scipy commit hash fbdce9e4:
[  0.00%] ·· Building for py2.7-Cython0.23.4-Tempita0.5.2-numpy1.8.2-six.................................................................................................................................
[  0.00%] ·· Benchmarking py2.7-Cython0.23.4-Tempita0.5.2-numpy1.8.2-six
[ 50.00%] ··· Running spatial.Query.time_query                                                                                                                        ok
[ 50.00%] ···· 
               =================== ===== ========== ============ ========== =========== ========== ===========
               --                                                  boxsize / leafsize                         
               ------------------------- ---------------------------------------------------------------------
                    (m, n, r)        p    None / 8   None / 128   0.0 / 8    0.0 / 128   1.0 / 8    1.0 / 128 
               =================== ===== ========== ============ ========== =========== ========== ===========
                 (3, 10000, 1000)    1     1.55ms      2.85ms      1.78ms      3.16ms     2.00ms      3.45ms  
                 (3, 10000, 1000)    2     1.09ms      1.52ms      1.51ms      2.81ms     1.55ms      2.41ms  
                 (3, 10000, 1000)   inf    1.19ms      2.22ms      1.33ms      2.46ms     1.47ms      2.58ms  
                 (8, 10000, 1000)    1    48.97ms     59.93ms     53.97ms     66.85ms    194.59ms    196.23ms 
                 (8, 10000, 1000)    2    10.76ms     11.28ms     18.48ms     24.49ms    71.61ms     81.75ms  
                 (8, 10000, 1000)   inf    7.28ms     10.32ms      8.19ms     11.37ms    30.08ms     38.16ms  
                (16, 10000, 1000)    1    745.01ms    360.08ms    808.40ms    417.07ms    1.14s      663.14ms 
                (16, 10000, 1000)    2    310.69ms    127.32ms    446.25ms    265.73ms   781.30ms    326.83ms 
                (16, 10000, 1000)   inf   63.15ms     58.91ms     69.39ms     64.95ms    550.38ms    243.10ms 
               =================== ===== ========== ============ ========== =========== ========== ===========

[ 50.00%] · For scipy commit hash 36e03290:
[ 50.00%] ·· Building for py2.7-Cython0.23.4-Tempita0.5.2-numpy1.8.2-six.....................................................................................................................................
[ 50.00%] ·· Benchmarking py2.7-Cython0.23.4-Tempita0.5.2-numpy1.8.2-six
[100.00%] ··· Running spatial.Query.time_query                                                                                                                        ok
[100.00%] ···· 
               =================== ===== ========== ============ ========== =========== ========== ===========
               --                                                  boxsize / leafsize                         
               ------------------------- ---------------------------------------------------------------------
                    (m, n, r)        p    None / 8   None / 128   0.0 / 8    0.0 / 128   1.0 / 8    1.0 / 128 
               =================== ===== ========== ============ ========== =========== ========== ===========
                 (3, 10000, 1000)    1     1.61ms      2.83ms      1.79ms      3.17ms     2.00ms      3.40ms  
                 (3, 10000, 1000)    2     1.09ms      1.54ms      1.54ms      2.72ms     1.57ms      2.31ms  
                 (3, 10000, 1000)   inf    1.24ms      2.27ms      1.36ms      2.46ms     1.49ms      2.60ms  
                 (8, 10000, 1000)    1    49.61ms     59.60ms     55.11ms     67.15ms    191.33ms    186.09ms 
                 (8, 10000, 1000)    2    10.68ms     11.09ms     18.48ms     23.90ms    70.76ms     77.38ms  
                 (8, 10000, 1000)   inf    7.32ms     10.44ms      8.12ms     11.32ms    30.03ms     36.56ms  
                (16, 10000, 1000)    1    739.27ms    360.11ms    813.93ms    419.03ms    1.11s      632.60ms 
                (16, 10000, 1000)    2    308.90ms    123.74ms    448.28ms    263.50ms   776.20ms    321.78ms 
                (16, 10000, 1000)   inf   64.40ms     58.74ms     69.27ms     64.03ms    540.12ms    228.59ms 
               =================== ===== ========== ============ ========== =========== ========== ===========

BENCHMARK                                    BEFORE      AFTER     FACTOR
...ery((16, 10000, 1000), inf, 1.0, 128)   228.59ms   243.10ms   1.06346950x
..._query((8, 10000, 1000), 2, 1.0, 128)    77.38ms    81.75ms   1.05642608x
````

### CODE REVIEW

**Comment by sturlamolden** [comment]
I wonder if the increased performance of p=2 is due to ignoring the upperbound. I think we should try to hoist all the
```
if (r>upperbound)
    return r;
```
out of the inner loop and see what happens. It might be that all these excessive conditional checks just slows things down. Maybe it makes sense for the general Minkowski distance as ```std::pow``` is slow, but probably not for the special cases.

**Comment by sturlamolden** [comment]
Also for ```query_knn```we should get rid of the excessive run-time checks for ```p```. This has been long due for clean-up. We can just add some ```static const``` members to the ```MinMaxDist``` template classes and branch on those instead of the run-time value of ```p```.

**Comment by rainwoodman** [comment]
1. It appears those early termination would help when the dimension is huge and when the nodes are very an-isotropic (is it the right word to use?). In that case the loop terminates sooner.

2. I've squashed most of the `if`s in query_knn. The remaining is one for converting the output (one per query) and converting `eps`. They look sufficiently innocent in terms of efficiency -- maybe we'd merge some of those to distance.h as well, for the sake of clarity?

**Comment by sturlamolden** [comment]
Good, you have squashed the important ```if```s from query_knn. The remaining ones are innocent, so I suggest we just leave them :)

As for the early termination: For common use cases such as 2 to 4 dimensions (e.g. computer graphics), early termination is not needed. If we manually unroll the loop it is possible to do the early termination check for e.g. every 4th dimension, and thus never for the common low-dimensional cases. This would possibly be faster even for high-dimensional data.

**Comment by sturlamolden** [comment]
Actually I changed my mind on the early termination check. It prevents (auto)vectorization of the distance computation because more than one register is needed for the summation. Thus there will be no running sum during the computation, but an early termination check requires it. Using an early termination check will therefore prevent the compiler from autovectorizing with SIMD instructions.

**Comment by rgommers** [comment]
I can't quite tell if @sturlamolden's comments on the early termination check require changes to this PR or a next one. Other than that this looks ready to go - just let me know when to hit the green button.

**Comment by sturlamolden** [comment]
@rgommers It does not have to be in this PR.

**Comment by rgommers** [comment]
In it goes then! Thanks @rainwoodman, @sturlamolden

**Comment by rainwoodman** [comment]
Thanks for merging.

do we still want to port spatial's distance function to distance.h; the
qhull based routines will have to use a separate code path anyways. In that
perspective these distance functions are local in ckdtree.

**Pull request merged**
