### PR TITLE
fix a performance issue with a sparse solver

### LINKED ISSUE #4391: spsolve becomes extremely slow with large b matrix
I'm solving a large number of sparse systems where my b matrix is (4839x9224).  This takes about 13 minutes to solve.  However, if I instead solve in chunks of 25 columns and aggregate the result vectors it takes 15 seconds.  It appears that the line 166 in the profiling is quadratic with the amount of columns.  This is with 0.14.0.  See below for some more information:
```
In [1]: import scipy.sparse.linalg as linalg
In [2]: import cPickle
In [3]: import numpy as np
In [4]: with open('/mnt/home/gfr/SparseMatrices.pkl', 'r') as f:
   ...:     A, b = cPickle.load(f)
   ...:     
# Chunking
In [5]: %%timeit
   ...: res = []
   ...: for i in range(0, 1024, 25):
   ...:    end = min(i+25, 1024)
   ...:    res.append(linalg.spsolve(A, b[:,i:end]).todense())
   ...: r = np.hstack(res)
   ...: 
1 loops, best of 3: 2.71 s per loop

# Default
In [7]: %timeit x = linalg.spsolve(A, b[:,:1024])
1 loops, best of 3: 9.15 s per loop

In [11]: %lprun -f linalg.spsolve linalg.spsolve(A, b[:,:1024])

   159                                           
   160      1025         3589      3.5      0.0              for j in range(b.shape[1]):
   161      1024       478053    466.8      4.9                  col = b[:, j].toarray()
   162      1024      1136856   1110.2     11.5                  xj = Afactsolve(ravel(col))
   163      1024        45517     44.5      0.5                  w = nonzero(xj)[0]
   164      1024         8693      8.5      0.1                  tempj.fill(j)
   165      1024        37741     36.9      0.4                  x = x + A.__class__((xj[w], (w, tempj[:len(w)])),
   166      1024      8128170   7937.7     82.5                                      shape=b.shape, dtype=A.dtype)
   167                                           
   168         1            1      1.0      0.0      return x


In [12]: %lprun -f linalg.spsolve linalg.spsolve(A, b[:,:512])

   159                                           
   160       513         1705      3.3      0.1              for j in range(b.shape[1]):
   161       512       229857    448.9      8.0                  col = b[:, j].toarray()
   162       512       528005   1031.3     18.5                  xj = Afactsolve(ravel(col))
   163       512        22177     43.3      0.8                  w = nonzero(xj)[0]
   164       512         4129      8.1      0.1                  tempj.fill(j)
   165       512        17300     33.8      0.6                  x = x + A.__class__((xj[w], (w, tempj[:len(w)])),
   166       512      2032841   3970.4     71.2                                      shape=b.shape, dtype=A.dtype)
   167                                           
   168         1            1      1.0      0.0      return x
```

### PR DESCRIPTION
**Pull request by argriffing**
This is intended to close https://github.com/scipy/scipy/issues/4391, but it could use more scrutiny because I've only tested it with toy matrices, not with the matrices used in the reported issue.

Although the sparse solver has many unit tests, there are also many possible combinations of sizes, shapes, sparsities, dtypes, array-like variants, and sparse matrix types for `A` and for `b` in the equation `Ax=b`, and some of these combinations may have less coverage than others in the `spsolve` tests.

Original performance:

```
   dense vs. sparse solve of Ax=b with 900 rows
==============================================================
   columns | repeats |      operation     |   time   
           |         |                    | (seconds)
--------------------------------------------------------------
      10   |    10   |        dense solve |   1.32 
      10   |    10   |       sparse solve |   0.99 
      30   |    10   |        dense solve |   1.46 
      30   |    10   |       sparse solve |   2.27 
     100   |    10   |        dense solve |   1.61 
     100   |    10   |       sparse solve |   5.53 
     300   |    10   |        dense solve |   1.85 
     300   |    10   |       sparse solve |   8.50 
    1000   |    10   |        dense solve |   3.34 
    1000   |    10   |       sparse solve |  29.61 
    3000   |    10   |        dense solve |   6.99 
    3000   |    10   |       sparse solve | 185.54 
```

Performance after these changes:

```
    dense vs. sparse solve of Ax=b with 900 rows
==============================================================
   columns | repeats |      operation     |   time   
           |         |                    | (seconds)
--------------------------------------------------------------
      10   |    10   |        dense solve |   1.52 
      10   |    10   |       sparse solve |   0.69 
      30   |    10   |        dense solve |   1.54 
      30   |    10   |       sparse solve |   1.55 
     100   |    10   |        dense solve |   1.53 
     100   |    10   |       sparse solve |   4.21 
     300   |    10   |        dense solve |   1.85 
     300   |    10   |       sparse solve |   6.20 
    1000   |    10   |        dense solve |   3.44 
    1000   |    10   |       sparse solve |  10.48 
    3000   |    10   |        dense solve |   6.35 
    3000   |    10   |       sparse solve |  22.55 
```

### CODE REVIEW

**Comment by rockg** [comment]
This looks promising.  I updated the timings from the original issue with this Pull Request.  Below ``spsolve`` is the current version, ``spsolveChunk`` is the code I had in the initial issue and ``spsolveNew`` is with this PR, ``spsolveChunkUmfPack`` is iterating through the vectors calling UmfPack solver rather than LU (this last timing is surprising given that umfpack is supposed to be faster and both algorithms are effectively iterating through the columns).  As you can see, the new code is the best in the two cases.

```
%timeit x = spsolve(A, b[:,:1024], use_umfpack=False)
1 loops, best of 3: 9.85 s per loop
%timeit x = spsolveChunk(A, b[:,:1024])
1 loops, best of 3: 2.85 s per loop
%timeit x = spsolveNew(A, b[:,:1024], use_umfpack=False)
1 loops, best of 3: 1.55 s per loop
%timeit x = spsolveChunkUmfPack(A, b[:,:1024])
1 loops, best of 3: 14.4 s per loop

%timeit x = spsolveChunk(A, b)
1 loops, best of 3: 28.4 s per loop
%timeit x = spsolveNew(A, b, use_umfpack=False)
1 loops, best of 3: 16.8 s per loop
```

**Comment by argriffing** [comment]
> (this last timing is surprising given that umfpack is supposed to be faster and both algorithms are effectively iterating through the columns).

This might be a dumb question but have you checked that your code is actually using umfpack?  I don't have umfpack on my system, although I see that it may be available on pypi.  I'm not sure if the scipy continuous integration testing includes it, but I would guess not.

The umfpack logic in `spsolve` seems a bit convoluted.  It looks like it is used if "b is a vector" and the `use_umfpack` flag is `True` and the global umfpack availability flag is `True`.  In this context, "b is a vector" means that `b` has `ndim == 1` or it has `ndim == 2` and `shape[1] == 1`, after having been converted to an ndarray if it was not originally a sparse matrix. The global umfpack availability flag is initialized to `True` if there is no import error when attempting to import `scikits.umfpack`, but it can be subsequently overridden directly or by calling the `use_solver()` function.

Also, I hope that the umfpack stuff could be considered a separate issue for the purposes of reviewing this PR.

**Comment by rockg** [comment]
I debugged to ensure that it was using the umfpack code path and it was.  Maybe all those checks/conversion end up making it slower.  It definitely is a separate issue, just something I found strange in the timings as umfpack that was always touted as a way to get better performance.

**Comment by argriffing** [comment]
@rockg I've added the umfpack issue as https://github.com/scipy/scipy/issues/4432.

**Comment by pv** [comment]
I'm not sure what's your spsolveChunkUmfPack, but if it just calls spsolve for each column, it will be slower because umfpack needs to factorize the matrix every time rather than just once.

**Comment by rockg** [comment]
Yes, it is just calling for each column so that makes sense.

**Comment by argriffing** [comment]
I may merge this in a few days if there are no more comments.

**Comment by pv** [comment]
LGTM

**Pull request merged**
