### PR TITLE
BUG: Explicit dtype specification in _upfirdn.py

### LINKED ISSUE #11128: OverflowError in resample_poly (upfirdn)
scipy.signal.resample_poly fails if the output vector length would be greater than 2^31-1.

```
Traceback (most recent call last):

  File "<ipython-input-1-ac5d2b0a1632>", line 11, in <module>
    yy = resample_poly(y, 128, 1)

  File "F:\Programs\Miniconda3\lib\site-packages\scipy\signal\signaltools.py", line 2424, in resample_poly
    y = upfirdn(h, x, up, down, axis=axis)

  File "F:\Programs\Miniconda3\lib\site-packages\scipy\signal\_upfirdn.py", line 183, in upfirdn
    return ufd.apply_filter(x, axis)

  File "F:\Programs\Miniconda3\lib\site-packages\scipy\signal\_upfirdn.py", line 82, in apply_filter
    output_shape[axis] = output_len

OverflowError: Python int too large to convert to C long
```

output_shape is created on the previous line (81):
`output_shape = np.asarray(x.shape)`

With an unspecified dtype it appears to get np.int32 by default, which is inadequate for specifying large array shapes.

This could be fixed by explicitly specifying the dtype:
`output_shape = np.asarray(x.shape, dtype=np.int64)`

### PR DESCRIPTION
**Pull request by peytondmurray**
Issue: By default, the shape of the output array created by `scipy.signal.upfirdn` was specified by an array with the default `dtype` of  `np._int`, which on some platforms is equal to `np.int32`. As a result, `upfirdn` would fail when passed a (large) signal array `x` if any dimension had length > 2^32-1.

#### Reference issue
Closes #11128.

#### What does this implement/fix?
This fix explicitly sets the `dtype` of the array which specifies the shape of the array returned by `upfirdn` to `np.int64`.

#### Additional information
See https://github.com/numpy/numpy/issues/9464 for additional details.

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The CI failures don't look related---I've restarted the individual matrix entries that were failing.

Not sure if a unit test can be written easily here, but reviewers may ask for that :)

**Comment by tylerjereddy** [comment]
I know @pv has done some work adding 64-bit integer testing in another context in NumPy. I don't know if the case here is strong enough to warrant the effort to guard against the memory issues and so on, but I think this is the reference PR: https://github.com/numpy/numpy/pull/15021

**Comment by larsoner** [comment]
Maybe a one-liner comment/hint saying why `np.int64` is used would be sufficient in this case to help prevent us from introducing a regression.

**Comment by peytondmurray** [comment]
> The CI failures don't look related---I've restarted the individual matrix entries that were failing.

@tylerjereddy They didn't look related to me, either. In any case, they're all passing now :)

> Not sure if a unit test can be written easily here, but reviewers may ask for that :)

You're absolutely right. I thought about implementing a test, but decided that much memory was probably a lot to ask for what shouldn't be _that_ large of a test. But given the new tools in https://github.com/numpy/numpy/pull/15021, I'd be happy to make use of `numpy.testing._private.utils.requires_memory`, except `requires_memory` is so new that we'd need `numpy >= 1.18.0rc1`. I'd still be happy to implement this test, but I'm assuming that bumping to the absolute bleeding edge of `numpy` isn't going to happen.

@larsoner Totally agree. I've added a little comment which explains the reasoning for the change.

**Comment by tylerjereddy** [comment]
Yeah, you/we could eventually write a test that is conditional on the version of NumPy available at runtime, I think, but perhaps overkill for now.

**Review by larsoner — APPROVED** [review]
LGTM +1 for merge

**Comment by rgommers** [comment]
LGTM too, merging. Thanks @peytondmurray & reviewers

**Pull request merged**
