### PR TITLE
 BUG: optimize: partial fix to linprog fails to detect infeasibility #8664

### PR DESCRIPTION
**Pull request by mdhaber**
Commit 87bbd71 is not intended to be part of this. It is part of #8641.
I accidentally branched from my `origin/master` instead of `upstream/master`, and I accidentally added a commit to my `origin/master` previously. Ugh. I'll try not to make this mistake in the future. And next time if it does happen, I'll remove the unwanted commit on my end before pushing. 

In any case, this is a partial fix to #8664. It doesn't actually detect the infeasibility with presolve turned off - but that is what presolve is for. Ideally the solver will give the correct output with presolve off or on, sparse or dense. But for now requiring that the user leave on the default presolve should be sufficient.

### CODE REVIEW

**Comment by pv** [comment]
Test failures on windows 32-bit. Maybe some accuracy issue?

**Comment by mdhaber** [comment]
If I'm reading correctly, it's that on this architecture there is an error that occurs due to NaNs before my code checks for the NaNs. It is not so surprising. I was aware that this patch would not fix the behavior for `sparse: True` because that errors on my system due to division by zero.

I suppose that's why I called it a partial fix. The inconsistency in the way division by zero and NaN arithmetic is handled makes it difficult to provide a complete fix that doesn't mask other issues.  It's difficult to predict all the different places and ways this issue could manifest itself on different architectures and with different solvers. I could wrap the whole function up in a try/except, but I don't think that's a good strategy.

**Comment by pv** [comment]
What to do depends on what you think the correct behavior is.

If it's intended that linprog raises an error when encountering nans in this part of the code, then it's necessary to catch this exception in the test  --- you then need to decide whether the test should succeed, or emit a known failure via `pytest.xfail("...")` in the except: block.

If it's not intended that linprog raises, then the issue should be detected in the linprog code.

**Comment by mdhaber** [comment]
@pv I think this is all set.

**Pull request merged**
