### PR TITLE
DOC: fix typo on main page

### PR DESCRIPTION
**Pull request by davidgilbertson**

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Thank you for the PR @davidgilbertson.

I am afraid I will have to close it.

We don't encourage PR only fixing typos unless it changes the meaning or it is included alongside other work. We have limited reviewer and also we want to keep a sensible history on a line change.

**Comment by tupui** [comment]
@davidgilbertson, it's definitely the case for some other packages in the PyData ecosystem. Some projects even advertise that they purposely made typos to inform people that the doc has typo and that it is expected and normal. Explicitly so that people don't focus on that.

As I said, we don't encourage this as it tends to create a huge amount of PRs. E.g. some school ask people to make open source contributions, hacktoberfest, etc. These kind of things have in the past generated a lot of small PRs like this one. While the change IS correct, it's just too much of an overhead for us. We have a limited time to focus on SciPy or other projects. So it's either we take some non negligible time to review small typo PRs (CI still needs to pass which burns some CI credit which is not infinite, we have to go over the change, etc.), or we give some time to fix actual bug, add features, add a tutorial, etc.

The git history is way more important than what you are implying. We have examples where on the same line we have 2-3 commits only doing typo changes, so if we are looking at why something changed in terms of code or explanation, we have to hunt further down. It's a lot of extra work for nothing.

**Comment by rkern** [comment]
We actually do [positively invite people to contribute typo fixes](https://github.com/scipy/scipy/blame/main/doc/source/index.rst#L82).

**Comment by davidgilbertson** [comment]
Thank you @rkern!

Should I carry on submitting fixes to typos as I read through the docs, or are @tupui's concerns shared by the whole team? My habit is to [fix anything I find](https://github.com/pulls?q=is%3Apr+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc+is%3Amerged), but my goal is to help, not be a pain.

**Comment by rgommers** [comment]
Thanks everyone! Let me answer this question with what I think is the most common or consensus opinion. There's some tension here:
- on the one hand, clearly it'd be quite nice if our docs were completely typo-free,
- on the other hand, the amount of notifications (300+ people watching this repo), CI runs (O(10 hours of CI time for this PR), etc. that a PR for a single typo generates are on average too high a cost,

So it'd be great if you could accumulate doc changes rather then send typo fixes one by one if possible, and also try to use the correct commands to skip CI - in this case `[skip github] [skip azp]`.

There's a related topic on _codestyle-only_ PRs; those have an even worse cost-benefit balance (plus it's often just a matter of taste) and that's where we say that we do not want pure style-change PRs.

**Comment by rkern** [comment]
I think those are good rubrics that would be good to add to our contributing guides; the specific advice to accumulate typo fixes is a good one. [NumPy has a bit on this](https://numpy.org/doc/stable/dev/howto-docs.html#contributing-fixes), and we can probably take the opportunity to get similar wording for the policies of both projects, as I don't think there is too much daylight between them.

**Comment by davidgilbertson** [comment]
In case you weren't aware, you can define your GitHub actions to only run when required (based on paths of the changed files of a PR), so you can avoid running unnecessary actions.  https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore.

**Comment by melissawm** [comment]
I have created a specific issue for that discussion, feel free to participate there: #16603

**Pull request merged**
