### PR TITLE
Use real names when loading MATLAB opaque objects.

### PR DESCRIPTION
**Pull request by anntzer**
Loading MATLAB objects (i.e., instances of classdefs) from a .mat now
uses the objects actual names, instead of defaulting to "None", which
led to overwriting issues when multiple objects are in the same file,
cf. #3591.

Tests are missing (some help would be welcome).

### CODE REVIEW

**Comment by pv** [comment]
I think this is pending confirmation on what matlab versions this works, or whether it is generally safe to do.

**Comment by anntzer** [comment]
My personal needs are now covered by http://github.com/anntzer/matloader (which is a drop-in replacement with full object loading ability, at the cost of decreased speed) so I won't bother with this PR anymore.  If someone wants to take over, some attempts at figuring out which versions of MATLAB work are mentioned in #3591.

**Comment by melissawm** [comment]
Hello, @anntzer - at this point it is not clear how this PR can move forward, so I am closing. Feel free to submit a new PR if this is still useful to you. Cheers!

**Comment by anntzer** [comment]
Actually the PR is was still good to go (perhaps up to a PR lint issue) even though it isn't really that useful to me personally anymore.  Can this be reopened?  Or I can open a new PR, whatever you prefer.

**Comment by rgommers** [comment]
The issue is still open and the TODO is given in gh-3591, so perhaps better to not reopen unless you want to finish it? If someone does have the need and energy to work on this, they can always take this PR as a starting point.

**Comment by anntzer** [comment]
I think I can finish this PR, as it should be really close.  Note that this doesn't fully implement #3591, just the name-loading part.

**Comment by rgommers** [comment]
Great, then let's reopen!

**Comment by rgommers** [comment]
Okay, that does not work if a branch was force-pushed to after closing - a new PR it is

**Pull request closed without merging**
