### PR TITLE
MAINT: change download site from SF to Github, forward port 0.16.0 release notes

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-4939

### CODE REVIEW

**Comment by rgommers** [comment]
Going to merge this soon if no one objects.

**Comment by matthew-brett** [comment]
All looks good to me - thanks.

**Comment by rgommers** [comment]
Thanks Matthew, in it goes then.

**Comment by rgommers** [comment]
And made a tiny follow-up commit (same change in ``bento.info`` and ``pavement.py``) in 3da51e3

**Pull request merged**
