### PR TITLE
BUG: fix a sparse.dok_matrix set/get copy-paste bug

### LINKED ISSUE #4428: dok.__setitem__ problem with negative indices
example:
```
a = dok_matrix((3,10), dtype=float)
a[0,-4] = 1.

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-35-e19ac43a5f68> in <module>()
----> 1 a[0,-4] = 1.

/Users/franzi/anaconda/lib/python2.7/site-packages/scipy/sparse/dok.pyc in __setitem__(self, index, x)
    267         if min_j < -self.shape[0] or j.max() >= self.shape[1]:
    268             raise IndexError('index (%d) out of range -%d to %d)' %
--> 269                              (j.min(), self.shape[1], self.shape[1]-1))
    270         if min_j < 0:
    271             j = j.copy()

IndexError: index (-4) out of range -10 to 9)
```

I think the problem is the check `min_j < -self.shape[0]`, which should be `min_j < -self.shape[1]`

### PR DESCRIPTION
**Pull request by argriffing**
Closes https://github.com/scipy/scipy/issues/4428.

### CODE REVIEW

**Comment by pv** [comment]
The test should go in the "_TestGetset" class

**Comment by argriffing** [comment]
OK I've done this.  I put extra newlines before and after the nested function because of the pep8 bot.

**Comment by larsmans** [comment]
LGTM, merged.

**Comment by pv** [comment]
Btw, please set the milestone of pull requests to the next release when they are merged.
(Ditto for fixed bugs.)

**Comment by larsmans** [comment]
Will do next time!

**Pull request merged**
