### PR TITLE
DOC: signal: Use impulse instead of impulse2 in the impulse example :)

### PR DESCRIPTION
**Pull request by WarrenWeckesser**

### CODE REVIEW

**Comment by ilayn** [comment]
I think also the ODE has a typo missing the first derivatives, it should read -> `x''(t) + 2*x'(t) + x(t) = u(t)`. Would be nice to guard it with code blocks too.

**Review by ilayn — APPROVED** [review]

**Review by tylerjereddy — APPROVED** [review]
Makes sense. I see `Artifact not found` when I try to use the CircleCI links to do the preview of the rendered docstring for `impulse`. Some pages work, and others don't--not sure why but obviously not related. Was just curious to see if the new plot looked substantially different.

Anyway, merging with two approvals on docstring change.

**Comment by tylerjereddy** [comment]
Thanks both

**Comment by WarrenWeckesser** [comment]
@ilayn wrote

> I think also the ODE has a typo missing the first derivatives, ...

Fixed in https://github.com/scipy/scipy/pull/11873

**Pull request merged**
