### PR TITLE
MAINT: linalg: run `dos2unix` on `cython_lapack_signatures.txt`

### PR DESCRIPTION
**Pull request by hoodmane**
It has dos style line endings for some reason.

### CODE REVIEW

**Comment by hoodmane** [comment]
This was produced from `_cython_signature_generator.py` I guess. Is `file.writelines()` platform dependent? Maybe explicitly joining the lines with `"\n"` would be better.

**Comment by ilayn** [comment]
Yes I was about to mention the same thing. But why do you need to change it? Typically as long as it is consistent and only one format, it should be OK. Is it causing trouble somewhere?

**Comment by lucascolley** [comment]
Apparently `writelines` does not add separators - indeed in the strip `\n` is already added manually to the end of each element being joined by `writelines`. So I don't think that should cause a problem? https://docs.python.org/3/library/io.html#io.IOBase.writelines

**Comment by hoodmane** [comment]
Well `git format-patch` does not correctly handle dos line endings (it always puts unix line endings on the patch) and gnu patch is picky about the line endings matching. It isn't super important but I just spend 30 minutes investigating this.

**Comment by ilayn** [comment]
Does `--keep-cr` help for you? I mean I don't think anybody cares about the format so we can regenerate the file on a linux box and be done with it.

**Comment by mdhaber** [comment]
> I mean I don't think anybody cares about the format so we can regenerate the file on a linux box and be done with it.

Do I understand that the to-do here is to open the original file on a Linux machine, save it, and push that instead of what is here?

**Comment by andyfaff** [comment]
In my personal repos I have in my `.gitattributes`:

```shell
# Auto detect text files and perform LF normalization
*.py text=auto eol=lf
*.pyx text=auto eol=lf
*.cpp text=auto eol=lf
*.h text=auto eol=lf
*.rst text=auto eol=lf
*.txt text=auto eol=lf
*.yml text=auto eol=lf
*.md text=auto eol=lf
```

Makes it easier to have everything matching.

**Comment by ilayn** [comment]
I guess this won't hurt anyways until someone else comes and fixes back. Thanks @hoodmane ,all!

**Pull request merged**
