### PR TITLE
ENH: special: Use boost for a couple ufuncs.

### LINKED ISSUE #12758: BUG: special: erfinv(y) is inaccurate for small abs(y).
`erfinv(y)` is implemented as `ndtri(0.5 * (y+1)) * NPY_SQRT1_2` (where `NPY_SQRT1_2` is `1/sqrt(2)`).  This limits the precision that can be obtained for small `abs(y)`, because for any `y` such that `abs(y)` is less than ~1e-16, `y + 1` is `1`.  So, for example, `erfinv(1e-20)` returns 0, but the correct result is `8.86226925452758e-21`:
```
In [45]: erfinv(1e-20)  # incorrect result                                                          
Out[45]: 0.0

In [46]: erf(8.86226925452758e-21)                                              
Out[46]: 1e-20
```
Octave and Boost return the correct value; we should too.

Octave:
```
octave:3> format long
octave:4> erfinv(1e-20)
ans =    8.86226925452758e-21
```
Boost
```
#include <iostream>
#include <boost/math/special_functions/erf.hpp>

using boost::math::erf_inv;
using namespace std;


int main()
{
    double p = 1e-20;
    double x = erf_inv(p);
    cout << scientific << setprecision(15) << x << endl;
    // 8.862269254527580e-21
}
```

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
ENH: special: Use boost for a couple ufuncs.

* Add the ufunc `powm1(x, y)` to compute `x**y - 1`.  This function
  is useful when `y` is close to 0, or when `x` is  close to 1.
* The implementation of `erfinv(x)` is switched to use the Boost
  function `erf_inv(x)`.  The Boost version is more accurate than
  our current implementation (see the updated tests).

Tests have been added or updated in `special/tests/test_erfinv.py`
and `special/tests/test_powm1.py`.

Closes gh-12758.

### CODE REVIEW

**Comment by WarrenWeckesser** [comment]
A few notes:

* `mpmath` also has an implementation of `powm1(x, y)`, so this is not an unusual or highly specialized function.  If both Boost and `mpmath` have it, it is probably a good idea to have it in `scipy.special`.
* When the script `tools/gen_boost_special_function_wrappers.py` is run, it prints instructions for what to do with the generated code.  The process is not completely automated.  Currently the code that is generated is to be checked in with the rest of the source code.  Generating the wrappers is not part of the standard build.
* I expect the code generation script for wrapping Boost functions will evolve.  There are a lot of things that it *could* do but it  doesn't do now.
* Boost has several options for error handling; the default is to throw C++ exceptions.  The code that is generated keeps the default behavior, and the wrappers include code to catch all exceptions generated by the C++ code.  No C++ exceptions should escape to CPython.

**Comment by person142** [comment]
> mpmath also has an implementation of powm1(x, y), so this is not an unusual or highly specialized function.

Yup, seems good to have it!

**Comment by WarrenWeckesser** [comment]
Closing for an overhaul.

**Comment by WarrenWeckesser** [comment]
I have updated the PR and marked it as ready for review.  The one test failure is the lint check in the file `_add_newdocs.py` because of the indentation.  I followed that pattern that is used in all the other docstrings.  (It would probably be worthwhile to fix the indentation of *all* the strings in a separate PR, so we don't have to see and ignore this lint failure every time we touch the ufunc docstrings.)

**Comment by WarrenWeckesser** [comment]
I just noticed some issues with edge cases and function domains that I need to address, so I'm marking this as *draft* again while I work out the details.

**Comment by WarrenWeckesser** [comment]
I simplified the PR, so now the two changes are:

* add the new ufunc `scipy.special.powm1`,
* update the existing ufunc `scipy.special.erfinv`.

`gamma_ratio` and `gamma_delta_ratio` can be added in another PR, if there is interest.

**Comment by rgommers** [comment]
This looks pretty good, +1 for adding these.

@mckib2 could you check the Boost error handling here? Just asking because we've had some trouble with those checks, and prevention is better than curing in this case:)

**Review by person142 — APPROVED** [review]
Very cool to see the boost.

**Comment by WarrenWeckesser** [comment]
Merged main to resolve a conflict.  The CircleCI failure has occurred in at least one other recent pull request, and is not related to the changes here.

**Review by mckib2 — APPROVED** [review]
LGTM -- the exceptions are handled differently than we did in stats (i.e., by changing the error handling policy to use custom handling functions), but the simple cases here are well-handled and appear to do the right thing

**Comment by mckib2** [comment]
We've got two maintainers' approvals and passing CI, so in it goes!

**Pull request merged**
