### PR TITLE
DOC: updated incorrect sentence about subpackage imports. See #19836 [docs only]

### LINKED ISSUE #19836: DOC: remove incorrect sentence about subpackage imports
### Issue with current documentation:

https://scipy.github.io/devdocs/tutorial/index.html#subpackages says that "SciPy subpackages need to be imported separately". This is no longer true! see https://scientific-python.org/specs/spec-0001/

### Idea or request for content:

Remove the incorrect guidance. The lines are https://github.com/scipy/scipy/blob/e7c6a0d1ce504c528ab00d19ddac6bdb1ae1cb36/doc/source/tutorial/index.rst?plain=1#L43-L46

### Additional context (e.g. screenshots, GIFs)

image

### PR DESCRIPTION
**Pull request by aadityab7**
Made changes in tutorial (user guide) according to the updates pointed out in issue "DOC: remove incorrect sentence about subpackage imports #19836"

Closes gh-19836

[docs only]

### CODE REVIEW

**Comment by aadityab7** [comment]
I am sorry for all the mess with Opening and closing of this pull request, I was trying to add the tag [docs only] - to skip all but the CircleCI checks and the linter according to [skipping](http://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#skipping)

**Comment by lucascolley** [comment]
Hi @aadityab7 , for future reference, an easy way to do that now would be:

```
git commit --amend
# edit the commit message to put [docs only] on a new line
git push -f
```

But don't worry, this PR is fine as it is!

**Comment by aadityab7** [comment]
Okay thank you very much @lucascolley, I will keep that in mind next time

**Comment by lucascolley** [comment]
Actually, could you do that now @aadityab7 ? The docs build check failed since the PR was closed after it was opened. A force push will restart the check.

**Comment by aadityab7** [comment]
@lucascolley I did as you suggested, can you please check if the change was made correctly? Thank you for all your help and patience.

**Review by lucascolley — APPROVED** [review]
thanks, the docs preview looks good to me!

**Comment by lucascolley** [comment]
added the backport-candidate label since the text before this PR is false, but not a big deal if it waits for 1.13.

**Comment by lucascolley** [comment]
pulling this in now, thanks for your first contribution to SciPy @aadityab7 !

**Pull request merged**
