### PR TITLE
FIX: change "func -> fun" of scipy.optimize _root.py to solve #5309

### LINKED ISSUE #2744: BUG: optimize: '**kw' argument of 'newton_krylov' is not documented
The signature for `optimize.newton_krylov` includes `**kw`, but `kw` is not documented in the `Parameters` section of the docstring.  The docstring should explain what is allowed, or at least explain how to find out (e.g. "Additional keyword arguments are passed to `foo`; see the `foo` docstring for more details.").

### LINKED ISSUE #5309: Documentation of 'hybr' and 'lm' inconsistent in optimize.root
'lm':
http://docs.scipy.org/doc/scipy/reference/optimize.root-lm.html#optimize-root-lm

options contain `func` which I guess is redundant since `fun` is already in the signature of `root()`.
The user really should not be allowed to specify both `fun` and `func`

'hybr':
http://docs.scipy.org/doc/scipy/reference/optimize.root-hybr.html#optimize-root-hybr

same thing applies here, and here the documentation talks about a parameter `fprime`
https://github.com/scipy/scipy/blob/master/scipy/optimize/minpack.py#L176

which is not visible in the signature in the documentation (another name for the Jacobian callback `jac`).

EDIT: furthermore, `hybr` has an undocumented option `full_output`

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
To fix #5309

#### What does this implement/fix?
change "func -> fun" of scipy.optimize _root.py to solve #5309

### CODE REVIEW

**Comment by AtsushiSakai** [comment]
@rgommers Can you review this?

**Comment by EverLookNeverSee** [comment]
@AtsushiSakai You have an untracked file in **scipy/special/** named _ufuncs.pyi

**Comment by AtsushiSakai** [comment]
@EverLookNeverSee Hi. Thank you for your review. I'm sorry I don't understand what should I do for the _ufuncs.pyx. Could you give me your advice?

**Comment by EverLookNeverSee** [comment]
@AtsushiSakai I think probably issue above is related to my local development version of scipy. I am trying to fix it.

**Comment by rgommers** [comment]
LGTM, merged. Thanks @AtsushiSakai.

CI failures were unrelated.

**Pull request merged**
