### PR TITLE
BUG:special:cdflib: Correct cdftnc Cython bugs

### LINKED ISSUE #19896: BUG: `special.nctdtr` broken in main
### Describe your issue.

`special.nctdtr` does not relturn correct values in main.  Likely cause is incorrect wrapping in #19560.

Additional small bug introduced is that the cythonized code is also returning the incorrect types, e.g., what should be a python `float` (scalar) is being returned as `np.float64` (numpy float64 scalar).

### Reproducing Code Example

```python
froms scipy import special
special.nctdtr(58, -3.8, 1.67)


return `nan`, when is should return something on the order of `0.9999999675827712`
```

### Error message

```shell
No error, just a wrong result bug.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0.dev0+1181.2353b15 2.0.0.dev0+git20240113.d2f60ff sys.version_info(major=3, minor=12, micro=0, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../opt/python/cp312-cp312/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```
```

### PR DESCRIPTION
**Pull request by ilayn**
#### Reference issue
Closes #19896

Thanks to  @bashtage 

Let's quickly fix these obvious ones and then we can start writing similar `itertools.product` based various domains of the parameters of the public functions. I would appreciate the definition of the tricky domains of the functions. 

cc @steppi

### CODE REVIEW

**Comment by steppi** [comment]
It looks like the same bug persists in the bounds of the domain for other `cdftnc_whichX` functions

https://github.com/scipy/scipy/blob/730010e77319606718b3d50a8fc402ba9cc629bc/scipy/special/_cdflib.pyx#L3604
https://github.com/scipy/scipy/blob/730010e77319606718b3d50a8fc402ba9cc629bc/scipy/special/_cdflib.pyx#L3647

**Comment by steppi** [comment]
> Let's quickly fix these obvious ones and then we can start writing similar `itertools.product` based various domains of the parameters of the public functions. I would appreciate the definition of the tricky domains of the functions.

Agreed on fixing these obvious ones ASAP, and sure thing, I can help with the hot spots in the domains.

**Comment by ilayn** [comment]
Oh no, I sent out the wrong branch... apologies. Got a bit too anxious apparently.

**Comment by ilayn** [comment]
Let's not waste this round of CI, the rest is not tested anyways but if this round passes then we can include the remaning pnonc bounds.

**Comment by ilayn** [comment]
> Agreed on fixing these obvious ones ASAP, and sure thing, I can help with the hot spots in the domains.

That would be great. If you can come up with the domains, I can fix the resulting failures. A majority of the code is traversed with the other cdf functions during their tests anyways hence we are in a much better shape there.

**Comment by ilayn** [comment]
Tweaked the tolerance because 32bit linux job failed but the rest passed. So if this passes please feel free to click the button otherwise I'll do it in the morning.

**Review by steppi — APPROVED** [review]
Looks good.

**Comment by ilayn** [comment]
Thanks @steppi !

**Pull request merged**
