### PR TITLE
CI: do not fail on E303 (too many blank lines)

### PR DESCRIPTION
**Pull request by argriffing**
This is probably too controversial to merge, but I just thought I'd put it here.

### CODE REVIEW

**Comment by ev-br** [comment]
-0 FWIW.
I agree the bot *is* somewhat annoying, but for this particular one I don't feel it's that big of a deal. OTOH, each of the rules to enforce is not that big of a deal on its own :-).

**Comment by argriffing** [comment]
closing https://mail.scipy.org/pipermail/numpy-discussion/2016-January/074810.html

**Comment by rgommers** [comment]
After https://github.com/scipy/scipy/pull/4515#discussion_r51242622 I think I came to the conclusion that at some point we need to bite the bullet and fix up many more PEP8 issues in the codebase. It's basically almost impossible right now for new contributors to figure out if their code is actually PEP8 compliant.

**Comment by ev-br** [comment]
FTR and FWIW, I do not think it's that big of a problem or that fixing pep8 violations in older codebase  would be a reasonable way of spending efforts on.

**Comment by I--P** [comment]
@rgommers Once you told me that I should use flake8 and not pep8 it became much easier to try to be pep8 compliant, and it is not that difficult to remember roughly on which lines your new code is and filter out the flake8 output. Maybe you should just write this somewhere in a beginner's guide
 ?
Also checking the docstring compliance is not an easy task at all, I managed to get a quick check/preview process by simlinking the files I'm working on in a clean sphinx working-directory but I took my quite some time to figure how to get this working. That's also the kind of thing which is quite frustrating...

**Comment by pv** [comment]
@I--P: docstring checks can  be run with `python runtests.py --refguide-check -s signal`

**Comment by I--P** [comment]
Thanks but it's a long enough process to be annoying when you're writing docstring on a trial and error basis as I do :-)

**Pull request closed without merging**
