### PR TITLE
MAINT: A bit of pyflakes-driven cleanup.

### PR DESCRIPTION
**Pull request by WarrenWeckesser**
There is more to do, if anyone has a moment or two.  Ideally, we should be running pyflakes on any changed files in a pull request before it is merged.

### CODE REVIEW

**Comment by pv** [comment]
We do run Pyflakes, cf https://travis-ci.org/scipy/scipy/jobs/63493154
Some of the warnings have however been disabled on purpose.

**Comment by WarrenWeckesser** [comment]
I'm just reminding and encouraging everyone (myself included!) to run pyflakes manually to catch the issues that we're ignoring on TravisCI.

**Comment by rgommers** [comment]
Agreed, that would be useful.

**Comment by WarrenWeckesser** [comment]
By the way, when I said "there is more to do", I meant in additional pull requests, not this one.

**Comment by rgommers** [comment]
LGTM, merged. Thanks Warren.

**Pull request merged**
