### PR TITLE
ENH: many lobpcg() algorithm improvements

### PR DESCRIPTION
**Pull request by rc**
This PR adds fixes and improvements (mostly by @lobpcg, small fixes by @rc) introduced and tested within scikit-learn, see https://github.com/scikit-learn/scikit-learn/pull/12319

### CODE REVIEW

**Comment by lobpcg** [comment]
@rc thanks for submitting this PR! Please remember to synchronize the changes here into scikit-learn/scikit-learn#12319

**Comment by lobpcg** [comment]
The fixes and improvements in this PR are editorial, i.e. do NOT change the core numerical algorithm of LOBPCG, to my recollection. They were required in  scikit-learn/scikit-learn#12319 mostly to pass style and formatting tests.

**Comment by rc** [comment]
Just rebased onto the master branch...

**Comment by rc** [comment]
The  Build #20190128.4 has failure corresponds to  Windows Python36-32bit-full, the error is due to failing to build scipy, which seems unrelated to this PR.

**Comment by lobpcg** [comment]
@rc great, thanks! 

@rc I've double-checked against /sklearn/utils/lobpcg.py in https://github.com/scikit-learn/scikit-learn/pull/12319 and found only 2 differences (other than a few in comments): 

1) There is a comment line 10 replaced with
from __future__ import division, print_function, absolute_import

2) In line 191: there is an extra space in front of 4:
array([ 4.,  5.,  6.])
Unsure which way is correct...

**Comment by rc** [comment]
Ad 1, the import statement is probably related to the fact that from this year, NumPy (and hence SciPy, I assume) will support only Python 3.

Ad 2, IMHO somewhere around numpy 1.12. the array output changed in this respect - the "right" (or recent) way is that without the leading space.

I can see some additional differences in the lobpcg() docstring - do you have the latest version in both scikit-learn and scipy? The scipy version docstring has some additional fixes.

**Comment by lobpcg** [comment]
@rc 
> Ad 1, the import statement is probably related to the fact that from this year, NumPy (and hence SciPy, I assume) will support only Python 3.
The line 
`from future import division, print_function, absolute_import`
thus can probably be removed here? It's not present in  /sklearn/utils/lobpcg.py in scikit-learn/scikit-learn#12319

> Ad 2, IMHO somewhere around numpy 1.12. the array output changed in this respect - the "right" (or recent) way is that without the leading space.

Could you please then delete the leading space? It's not present in  /sklearn/utils/lobpcg.py in scikit-learn/scikit-learn#12319

> I can see some additional differences in the lobpcg() docstring - do you have the latest version in both scikit-learn and scipy? The scipy version docstring has some additional fixes.

I attach the complete diff file for the current PRs
[diff_lobpcg.txt](https://github.com/scipy/scipy/files/2805026/diff_lobpcg.txt)

Some differences are to shorten too long lines to 79, to my recollection, characters in sk-learn.

It would probably be ideal if the only difference  would be 2 lines on the top of /sklearn/utils/lobpcg.py in scikit-learn/scikit-learn#12319 like: 

# sk-learn copy of scipy\sparse\linalg\eigen\lobpcg\lobpcg.py ver. 1.3.0
# to be deleted after scipy 1.3.0 becomes a dependency in sk-learn 

@rc, would you please be able to fully synchronize this PR with  /sklearn/utils/lobpcg.py in scikit-learn/scikit-learn#12319 while keeping all check green for both sk-learn and scipy ?

**Comment by ev-br** [comment]
> The line `from __future__ import division, print_function, absolute_import` thus can probably be removed here?

Please keep this line, it should be present in all source files in scipy until we clean up all py2 workarounds. Which is going to be at least a couple of releases.

**Comment by rc** [comment]
Doing that.. wait a moment.

**Comment by lobpcg** [comment]
> 
> 
> > The line `from __future__ import division, print_function, absolute_import` thus can probably be removed here?
> 
> Please keep this line, it should be present in all source files in scipy until we clean up all py2 workarounds. Which is going to be at least a couple of releases.

@ev-br thanks for your advice! 

@rc - I have just added it to /sklearn/utils/lobpcg.py in scikit-learn/scikit-learn#12319 for consistency, along with modifying the hearer. But I see now that you are also editing. I'll leave it up to you then.

**Comment by lobpcg** [comment]
@rc As soon as  module-level docstring changes passes all tests in both packages, I am happy :-) Thanks!

**Comment by rc** [comment]
@lobpcg, we shall see in a few minutes :)

**Comment by rc** [comment]
@lobpcg Finally... BTW. do you agree with the removal of the code authors from the module docstring and their replacement by references? One can use git to see code origins (the only exception might be mention of Nils Wagner proposing some of the testing examples - IIRC it was me adding them).

**Comment by lobpcg** [comment]
>  do you agree with the removal of the code authors from the module docstring and their replacement by references? 

I have no opinion myself. Whatever is the "standard." In my sk-learn codes, I just followed examples.

**Comment by rgommers** [comment]
> The fixes and improvements in this PR are editorial, i.e. do NOT change the core numerical algorithm of LOBPCG, to my recollection. They were required in scikit-learn/scikit-learn#12319 mostly to pass style and formatting tests.

All the style and doc changes look good. The only algorithmic changes are related to the handling of `if B is not None:`, correct? It would be good to explain what that does exactly. All I can tell from the sklearn PR is that it somehow seems important in order to add lobpcg as an SVD solver option for PCA and TruncatedSVD.

**Comment by rc** [comment]
@rgommers Thanks for merging! I hope to get to #9275 soon.

**Pull request merged**
