### PR TITLE
DOC: add Examples add see also sections for LinearNDInterpolator, NearestNDInterpolator, and CloughTocher2DInterpolator

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
fix a part of #7168 

#### What does this implement/fix?
I added Examples add see also sections for LinearNDInterpolator, NearestNDInterpolator, and CloughTocher2DInterpolator

### CODE REVIEW

**Comment by ev-br** [comment]
Nice. 
These could use non-random input, a tabulation of some smooth function maybe. But this can be a further enhancement, so let's merge this as is to keep the ball rolling. Thanks @AtsushiSakai

**Comment by sethtroisi** [comment]
I had to add `import numpy as np`, otherwise examples run and generate pretty plots
Screenshot from 2020-07-22 11-21-27

**Comment by AtsushiSakai** [comment]
Should we add numpy import in Examples section? It looks like many examples omit numpy import.

**Comment by rgommers** [comment]
That's on purpose. It would be the same `import numpy as np` 1000+ times. The introduction section of the docs explains this import is assumed for all examples.

**Pull request merged**
