### PR TITLE
remove leftover `nose` imports

### PR DESCRIPTION
**Pull request by ev-br**
Convert nose imports to equivalent pytest imports. With this, `$ python runtests.py` passes the collection stage if nose is not present. Tests still fail because of gh-7776.

### CODE REVIEW

**Comment by ev-br** [comment]
Updated the branch. Since the semantics of `np.testing.assert_raises` and `pytest.raises` is the same, search-and-replace is easy. There is also `assert_raises_regex`, where the spelling is slightly different. For these, manually converted them to  the recommended `pytest` idiom,  https://docs.pytest.org/en/latest/assert.html

Also removed nose from Travis CI. What's left: locally, there' s a single failure in netcdf, which still needs to be tracked down; make sure AppVeyor does not use nose. Help appreciated.

**Comment by rgommers** [comment]
Still an unhappy netcdf test

**Comment by rgommers** [comment]
All changes LGTM

**Comment by pv** [comment]
You can remove nose from tools/ci/appveyor/requirements.txt

**Comment by ev-br** [comment]
Updated with a fix for the netcdf test, a refguide-check fix (an explicit `pytest` import in the docstring of `sc.errstate`), and the appreveyor/requirements.txt fix (thanks for the pointer Pauli). Locally all tests pass, let's see what the CI says.

**Comment by pv** [comment]
Thanks, lgtm, merged.

**Pull request merged**
