### PR TITLE
MAINT: Remove fortran fftpack library in favour of pypocketfft

### LINKED ISSUE #1739: Single precision FFT insufficiently accurate. (Trac #1212)
_Original ticket http://projects.scipy.org/scipy/ticket/1212 on 2010-06-27 by @rgommers, assigned to unknown._

For some input sizes (factoring into large prime numbers) the accuracy of single precision fft is not good enough. For details see http://thread.gmane.org/gmane.comp.python.scientific.devel/13834.

In the 0.8.x branch the problem is circumvented by switching to double precision except for sizes that are composites of factors 2, 3 or 5.

### LINKED ISSUE #2233: fftpack segfault with big arrays (Trac #1714)
_Original ticket http://projects.scipy.org/scipy/ticket/1714 on 2012-08-01 by trac user serbanul, assigned to @cournape._

Hello!

I use scipy 0.10.1 with numpy 1.6.2 on a Slackware 13.37 32bit box (gcc 4.5.2, glibc 2.13, python 2.6.6) and experience segfaults when using big arrays with fftpack's fft2. This does not happen when the array is obviously too big to fit the memory (4GB nominaly), in which case I receive an MemoryError exception, as it should be. It happens when the size of the array goes beyond a certain limit, which for 64bit floats is approximately 4.55e7 elements. Please find the appropriate code snippet and the back trace for a relevant array size within the attached files. At the end of the file with the backtrace, there is also an example for the case in which a MemoryError exception is raised.

Best regards,

Serban Udrea

### LINKED ISSUE #2629: FFTpack is unacceptably slow on non power of 2
FFT on len 262144 = 20m/s
FFT on len 257144 = 8000m/s

It actually seems quite erratic. Some will only take say 60m/s, others several hundred and if you go for an odd number I normally end up killing it after a few minutes

### LINKED ISSUE #3528: Segfault on test_djbfft (possibly MKL-related?)
Hello there,

I installed the master version of numpy (1.8.1 was failing some tests and I'm trying to debug a segfault in scipy - FYI this is the same segfault as with 1.8.1) and the master version of scipy, and I get a segfault on `test_djbfft`. All numpy tests pass.

```
$ python -c 'import scipy; scipy.test(verbose=10)'
Running unit tests for scipy
NumPy version 1.9.0.dev-52d5d10
NumPy is installed in /projects/ps-yeolab/software/lib/python2.7/site-packages/numpy
SciPy version 0.15.0.dev-f14f8bd
SciPy is installed in /projects/ps-yeolab/software/lib/python2.7/site-packages/scipy
Python version 2.7.5 (default, Feb  4 2014, 17:34:21) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
nose version 1.3.0
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Excluding tests matching ['f2py_ext', 'f2py_f90_ext', 'gen_ext', 'pyrex_ext', 'swig_ext']
test_linkage_cophenet_tdist_Z (test_hierarchy.TestCopheneticDistance) ... ok
test_linkage_cophenet_tdist_Z_Y (test_hierarchy.TestCopheneticDistance) ... ok
... more test results ...
test_constants.test_lambda_to_nu ... ok
test_constants.test_nu_to_lambda ... ok
test_definition (test_basic.TestDoubleFFT) ... ok
test_djbfft (test_basic.TestDoubleFFT) ... Segmentation fault
```

Full debug log/site.cfg/ installation here: https://gist.github.com/olgabot/10069866

How Numpy was installed:

```
git clone git@github.com:numpy/numpy
git clone git@github.com:scipy/scipy
cd numpy
cp ~/.numpy.site.cfg .

emacs numpy/distutils/intelccompiler.py 
# In "IntelEM64TCCompiler", changed:
# self.cc_exe = 'icc -m64 -fPIC'
# to:
# self.cc_exe = 'icc -m64 -fPIC  -O3 -g -fp-model strict -fomit-frame-pointer -openmp -xhost'

emacs numpy/distutils/fcompiler/intel.py
# In "IntelEM64TFCompiler", changed:
#    def get_flags_opt(self):
# #       return ['-i8 -xhost -openmp -fp-model strict']
#        return ['-xhost -openmp -fp-model strict'] 
# to:
#    def get_flags_opt(self):
#        return ['-i8 -xhost -openmp -fp-model strict']
# #        return ['-xhost -openmp -fp-model strict']

CC=icc F77=ifort python setup.py config --compiler=intelem build_clib --compiler=intelem build_ext --compiler=intelem build
export LD_LIBRARY_PATH=
source /opt/intel/composer_xe_2013.1.117/bin/compilervars.sh intel64
source /opt/intel/composer_xe_2013.1.117/mkl/bin/mklvars.sh intel64
export LD_RUN_PATH=/opt/intel/composer_xe_2013.1.117/mkl/lib/intel64:/opt/intel/composer_xe_2013.1.117/compiler/lib/intel64
CC=icc F77=ifort python setup.py install
```

How Scipy was installed:

```
cd ../scipy
cp ../numpy/site.cfg .
rm -rf build
CC=icc F77=ifort python setup.py config --compiler=intelem --fcompiler=intelem build_clib --compiler=intelem --fcompiler=intelem build_ext --compiler=intelem --fcompiler=intelem build
CC=icc F77=ifort python setup.py install
```

### LINKED ISSUE #10488: ENH: DCTs/DSTs for scipy.fft
Currently, `scipy.fft` falls back to `scipy.fftpack` for discrete sine and cosine transforms. This is problematic for performance reasons, but even more for accuracy reasons:
1) `scipy.fftpack`'s real-valued FFT (which is used internally by the DCTs/DSTs) tends to be very inaccurate for lengths containing large prime factors.
2) DCTs/DSTs of type I and IV use recurrences which further reduce accuracy (see, e.g. footnote 4 at http://www.fftw.org/fftw3_doc/Real-even_002fodd-DFTs-_0028cosine_002fsine-transforms_0029.html for further information)

I have added experimental support for DCTs/DSTs to `pypocketfft` (see the `sincos` branch at https://gitlab.mpcdf.mpg.de/mtr/pypocketfft). Switching to this implementation fixes issue 1) (and improves performance), but issue 2) is only addressed partially so far:
- transforms of type I are now very accurate, but use a double-length FFT internally, which makes them slower.
- transforms of type IV still use the recurrence since I have not found an alternative algorithm yet.

I'd be happy about feedback how to proceed: does it make sense to switch `scipy.fft` to the new implementation now, or should this wait until `pypocketfft`'s sine and cosine transforms are finalized?

The longer term goal (in my view) would be that `scipy.fftpack` can use `scipy.fft` internally. This would give a performance/accuracy benefit to all `scipy` users who are not actively switching from `scipy.fftpack` to `scipy.fft` for their existing codes (probably the vast majority).

### PR DESCRIPTION
**Pull request by peterbell10**
#### Reference issue
Fixes gh-1739, fixes gh-2233, fixes gh-2629, fixes gh-3528
Closes gh-10488

#### What does this implement/fix?
This removes most of `scipy.fftpack`'s code in favour of calls to `scipy.fft._pocketfft`. Additionally, this:
- adds a wrapper to `_pocketfft` for the `r2r_fftpack` function
- rewrites `fftpack.convolve` in cython so it can call pypocketfft instead of fortran FFTPACK
- Reorganizes helper functions so that `scipy.fft` never imports from `fftpack`

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
Looks reasonable to me, love all the red lines! Hopefully the CIs are happy, the remaining `fftpack` tests will hopefully be good enough to make sure we don't cause any regressions.

I noticed that things like `scipy.fftpack._fftpack.zfft` are gone now, but these only lived in the private namespace so should be okay.

**Comment by larsoner** [comment]
From Travis:

> ERROR: objects in scipy.fftpack.convolve.__all__ but not in refguide::
>    r2r_fftpack

Should be private?

**Review by grlee77 — COMMENTED** [review]
Great job, Peter!

As far as I can tell the main new code is in `convolve.pyx` which looks okay to me. There do not appear to be direct tests for those functions, but that was also the case prior to this PR.  They do get tested indirectly via `fftpack/tests/test_pseudo_diffs.py`.

**Comment by andyfaff** [comment]
Are there any performance gain to using convolve from pypocketfft?
At the moment I use `np.convolve` for linear convolution of two ~1000 element arrays, but am wondering if I can get a speed boost somewhere. I seem to remember that np.convolve was faster than the scipy convolution functions, but perhaps this has changed now.

**Comment by peterbell10** [comment]
>Are there any performance gain to using convolve from pypocketfft?

I wouldn't recommend using `fftpack.convolve`. It's really just an implementation detail of `fftpack`'s pseudo-differential operators and shouldn't have been public. It may even be deprecated soon.

>I seem to remember that `np.convolve` was faster than the scipy convolution functions, but perhaps this has changed now.

It seems that `signal.convolve` has some serious overhead somewhere. Using the convolution theorem directly gives a 5x speedup:

```python
In [5]: %timeit np.convolve(x, y)
151 µs ± 2.87 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
In [6]: %timeit signal.convolve(x, y)
201 µs ± 5.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [7]: %timeit fft.irfft(rfft(x) * rfft(y), len(x))
39 µs ± 1.84 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

I'll have a look into this as it might be similar to #10490

**Comment by peterbell10** [comment]
>There do not appear to be direct tests for those functions, but that was also the case prior to this PR. They do get tested indirectly via `fftpack/tests/test_pseudo_diffs.py`.

The tests in `test_pseudo_diffs` are also definitely written to exercise the corner cases of convolve. e.g. odd and even sized inputs.

**Comment by mreineck** [comment]
First of all, thanks a lot @peterbell10 for your great work!

Concerning FFT convolution, I think that there is still room for optimization, in a lot of different situations. For example, a fairly typical case is probably convolving a (large) 2D image with a (small) kernel. If I read `signal.fftconvolve` correctly, both arrays are brought to the same size, FFT'd, multiplied and then transformed back. Using many smaller, overlapping transforms may be much faster, for example.

**Comment by larsoner** [comment]
> In [7]: %timeit fft.irfft(rfft(x) * rfft(y), len(x))

Keep in mind this will be a circular convolution, if you want equivalence with the `convolve` code you need to zero pad:
```
n = len(x) + len(y) - 1
%timeit fft.irfft(rfft(x, n) * rfft(x, n), n)
```
But even with this it's possible that `signal.convolve` is slower due to some overhead that could be avoided, I haven't looked.

> Are there any performance gain to using convolve from pypocketfft?

Agreed with @peterbell10 about `fftpack`'s convolve function, it's not meant for public use. `scipy.signal.convolve` function triages between doing time domain convolution and frequency domain multiplication, but see #10427 where we talk about needing to update it now that we use `scipy.fft`'s pocketfft instead FFTPACK.

> Concerning FFT convolution, I think that there is still room for optimization, in a lot of different situations. For example, a fairly typical case is probably convolving a (large) 2D image with a (small) kernel. If I read signal.fftconvolve correctly, both arrays are brought to the same size, FFT'd, multiplied and then transformed back. Using many smaller, overlapping transforms may be much faster, for example.

There is a mailing list post about overlap add convolution. It would indeed be nice to have. It is also in issue form in #1364 but the discussion there is limited.

**Comment by peterbell10** [comment]
>Keep in mind this will be a circular convolution, [...]
But even with this it's possible that signal.convolve is slower due to some overhead that could be avoided

I had noticed that from looking at the code and yes, there's still considerable overhead compared to doing the ffts yourself
```python
n = len(x) + len(y) - 1
N = fft.next_fast_len(n)
%timeit fft.irfft(rfft(x, N) * rfft(x, N), N)[:n].copy()
# 72 µs ± 2.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit signal.fftconvolve(x, y)
# 185 µs ± 1.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by larsoner** [comment]
I don't think there is any problem with removing this code, but out of an abundance of caution @peterbell10 can you email the `scipy-dev` listserv letting people know we plan to remove this old Fortran code? Then I'll plan to merge Monday or Tuesday, barring any complaints.

**Comment by larsoner** [comment]
Thanks @peterbell10 ! Now onto some fun rebases :)

**Comment by peterbell10** [comment]
I've added a small release note:

`scipy.fftpack` now uses pypocketfft to perform its FFTs, offering the same speed and accuracy benefits listed for `scipy.fft` above but without the improved API.

**Comment by larsoner** [comment]
Looks good to me

**Pull request merged**
