### PR TITLE
ENH: sparse.linalg/lobpcg: change .T to .T.conj() to support hermitian matrices

### PR DESCRIPTION
**Pull request by lgdouglas**
Changed [.T] to [.T.conj()] to add hermitian matrices compatibility as per issue #979

Fixes gh-979

### CODE REVIEW

**Comment by pv** [comment]
Thanks! Please add also corresponding tests for complex matrices.

**Comment by Astrofysicus** [comment]
I'm not sure how to write the tests but I could try if pointed on the right direction

**Comment by pv** [comment]
Along these lines: https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/lobpcg/tests/test_lobpcg.py --- add a new function called `test_<something>` to the end, and check lobpcg produces same results as eig for complex-valued test matrices.

**Review by pv — APPROVED** [review]
Ok, went it through. I also remove two remaining astype(float64) parts and fixed up the test (it's necessary to test k < size, because it just calls eigh for k==size...)

**Pull request merged**
