### PR TITLE
ENH: remove noprefix.h, change code appropriately

### PR DESCRIPTION
**Pull request by mattip**
It seems SciPy is still old NumPy names, and including a header that redefines the old names to the new ones. This PR removes the header and adjusts the code accordingly.

### CODE REVIEW

**Comment by mattip** [comment]
xref PR numpy/numpy#12475 to warn this header should go away in NumPy 1.17, and 
numpy/numpy#12402 to actually remove the header

**Comment by rgommers** [comment]
Thanks @mattip, LGTM.

@tylerjereddy despite the build error on the first commit, I think this would be relatively safe to put into 1.2.0rc2 if that's still possible (not sure how far you are with that). Could be quite useful, even if this header doesn't go away in 1.17 but say in 1.18.

**Comment by rgommers** [comment]
All green, in it goes. Thanks Matti!

**Comment by rgommers** [comment]
Hmm, it does look like it. Puzzling that CI here passes but wheel builds don't. Yeah, makes sense to revert then in 1.2.x and sort this out after - this PR is not a blocker. I probably should have known better than suggest to include this ....

**Comment by tylerjereddy** [comment]
Hopefully someday we can unify the CIs or at least reduce their dissonance for the most part.

Now I realize why it would have been useful not to squash!

**Comment by rgommers** [comment]
Reverted for 1.2.x in gh-9572. 

> Hopefully someday we can unify the CIs or at least reduce their dissonance for the most part.

That would be nice. For now I'll open an issue and see if I can figure out what was going on.

**Comment by mattip** [comment]
Can you link to the wheel failures or the wheel commands that resulted in failures?

**Comment by rgommers** [comment]
That's in the issue, gh-9574. Don't worry too much about this one for now though. Should disappear when my open PR on dropping older NumPy versions is merged.

**Pull request merged**
