### PR TITLE
REV: minimal revert of "DEP: `lsim2` deprecated in favor of `lsim` (#15929)"

### PR DESCRIPTION
**Pull request by h-vetinari**
Reverts functional changes of 5acb9564989ea45706e1d175dfd7a49479d359f9, but leaves the refactored tests unchanged where possible.

For unknown reasons, #15929 broke the docs build. Let's see if reverting the changes fixes it again.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Failures (from what I've seen so far) are from not being able to download from http://azure.archive.ubuntu.com

**Comment by FranzForstmayr** [comment]
@h-vetinari the doc stuff was fixed in  d6de9eca07501c6fb3a3b46b55ca30710e3d731c on the other branch, however I reverted as it was unrelated.

**Comment by h-vetinari** [comment]
> @h-vetinari the doc stuff was fixed in [d6de9ec](https://github.com/scipy/scipy/commit/d6de9eca07501c6fb3a3b46b55ca30710e3d731c) on the other branch, however I reverted as it was unrelated.

Ah, sorry. https://github.com/scipy/scipy/pull/15929 had a long history, I've forgotten that. Could you please open a PR with that commit and we'll see if it fixes things? 🙏

**Comment by FranzForstmayr** [comment]
Yes I can make this PR today evening. (Europe)

**Pull request closed without merging**
