### PR TITLE
BLD: remove build_sphinx support from setup.py

### LINKED ISSUE #3284: build_sphinx weirdness
Usually I only interact with scipy development through `runtests.py` but I just ran `python setup.py build_sphinx` directly within the root `scipy/` directory.

I'm not sure if this is the preferred way to build the docs, but it's mentioned in a few places and this method is only a year or so old so I thought I'd mention some weirdnesses.

First, it took a painfully long time to build, so it must not be smart about the ccache.  At the end of this long build it raised an exception which I deciphered as meaning that it wants a numpydoc python package/module to be installed.  I'm using ubuntu so I `apt-get install`ed `python-numpydoc` and ran the setup.py again.  This was more or less successful.  But it shows some old/weird things.  For example it says `2008-2009` which I guess is in a sphinx conf file.  The built sphinx docs also show the scipy version as `1.7.1` which is my installed numpy version.  I guess this is not a coincidence.  Also in the docs there are no links to source.

After more googling I see that these are probably some of the weirdnesses alluded to in https://github.com/scipy/scipy/pull/3240#issuecomment-33227108 as older-looking htmls with weird errors here and there.  If this isn't the preferred way to build the scipy docs then maybe it would make sense to change some of the READMEs and build docs?

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-3284

### CODE REVIEW

**Comment by tylerjereddy** [comment]
The circleci `build_docs` job failure might be an unfortunate coincidence--IIUC the deleted machinery wasn't being used for the doc build there anyway, and I saw one of those "matplotlib rebuilding fontcache" type messages, so it may have been a timeout caused by that. So, restarting..

**Comment by rgommers** [comment]
> IIUC the deleted machinery wasn't being used for the doc build there anyway, 

correct

> and I saw one of those "matplotlib rebuilding fontcache" type messages, so it may have been a timeout caused by that. So, restarting..

yeah it's been failing for a couple of days, no time to look into it today unfortunately

**Comment by V0lantis** [comment]
Hello, I have been looking through it yesterday a lot, but I must admit  didn't find much. 
The failure in CI always occurred while building documentation. CircleCi output is as follow : 
```
waiting for workers...
Makefile:127: recipe for target 'html-scipyorg' failed
make: *** [html-scipyorg] Hangup
```
I tried to reproduce it on local using docker, and every time, I ended up with the same following errors (for the sake of readability, I am posting a screenshot, and the line at the end of this comment) : 
Capture d’écran 2021-02-07 à 12 18 04
Capture d’écran 2021-02-07 à 12 18 14

Executing the command `make -Cdoc PYTHON="/workspace/venv/bin/python" html-scipyorg latex SPHINXOPTS="-j2"`
ended up with the same errors output. If you have some advices or paths to follows, I will be glad to help

here is the output log from docker execution
```
/workspace/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr.rst:10: WARNING: autosummary: stub file not found 'scipy.odr.odr'. Check your autosummary_generate setting.

looking for now-outdated files... none found

pickling environment... done

checking consistency... done

preparing documents... done

writing output... [ 36%] generated/scipy.linalg.lapack.spptrf .. generated/scipy.linalg.lapack.ztpttf

docstring of _odrpack.odr:16: WARNING: py:obj reference target not found: ODRed/scipy.optimize.LinearConstraint

docstring of _odrpack.odr:28: WARNING: py:obj reference target not found: ODR

/workspace/build/testenv/lib/python3.7/site-packages/scipy/odr/__init__.py:docstring of scipy.odr:29:<autosummary>:1: WARNING: py:obj reference target not found: scipy.odr.ODR

release/1.6.0-notes.rst:47: WARNING: py:obj reference target not found: scipy.odr.ODR9;00m


waiting for workers...

generating indices... genindex py-modindex done

writing additional pages... search done

copying images... [ 3%] generated/../../build/plot_directive/generated/scipy-interpolateolve_ivp-1.png

copying images... [ 10%] generated/../../build/plot_directive/generated/scipy-ndimage-fourier_ellipsoid-1.png

copying images... [ 13%] generated/../../build/plot_directive/generated/scipy-ndimage-rotate-1_00_00.png

copying images... [ 20%] generated/../../build/plot_directive/generated/scipy-signal-convolve-1.png

copying images... [ 27%] generated/../../build/plot_directive/generated/scipy-signal-gausspulse-1.png

copying images... [ 34%] generated/../../build/plot_directive/generated/scipy-signal-peak_prominences-1_00_00.png

copying images... [ 41%] generated/../../build/plot_directive/generated/scipy-signal-welch-1_01_00.png

rated/

copying images... [ 47%] generated/../../build/plot_directive/generated/scipy-signal-windows-hamming-1_00.png

copying images... [ 54%] generated/../../build/plot_directive/generated/scipy-spatial-tsearch-1.potationSpline-1_02_00.png

copying images... [ 61%] generated/../../build/plot_directive/generated/scipy-stats-binned_statistic_dd-1.png

copying images... [ 68%] generated/../../build/plot_directive/generated/scipy-stats-genhalflogistic-1.png


copying images... [ 75%] generated/../../build/plot_directive/generated/scipy-stats-loggamma-1.png

copying images... [ 81%] generated/../../build/plot_directive/generated/scipy-stats-randint-1_00_00.png


copying images... [ 88%] ../build/plot_directive/optimizctive/generated/scipy-stats-zipfian-1_00_00.png

copying images... [ 95%] tutorial/../../build/plot_directive/tutorial/signal-5.png

copying images... [100%] tutorial/../../build/plot_directive/tutorial/stats/plots/mgc_plot4.png

copying static files... done

copying extra files... done

dumping search index in English (code: en)... done

dumping object inventory... done

build finished with problems, 5 warnings.

Makefile:127: recipe for target 'html-scipyorg' failed

make: *** [html-scipyorg] Error 1

make: Leaving directory '/workspace/doc'

Traceback (most recent call last):

File "runtests.py", line 565, in <module>

main(argv=sys.argv[1:])

File "runtests.py", line 214, in main

subprocess.run(cmd, check=True)

File "/usr/local/lib/python3.7/subprocess.py", line 468, in run

output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['make', '-Cdoc', 'PYTHON="/workspace/venv/bin/python"', 'html-scipyorg', 'latex', 'SPHINXOPTS="-j2"']' returned non-zero exit status 2.
```

**Comment by rgommers** [comment]
Thanks @V0lantis! Given that it's unrelated to this PR, could you open a new issue for it?

The critical part is this probably:
```
build finished with problems, 5 warnings.
```
CI is set up to error when there are any warnings, so we keep the build clean. Those warnings will be higher up, so you may want to attach the full build log for that CI step (that's doable either as a gist, or with a foldout as I just did to your comment above - surround the code block with `<details> .... </details>`).

**Comment by rgommers** [comment]
CI issue resolved, all green now - I'll merge this in a day or two unless there's more comments.

**Comment by larsoner** [comment]
Looks straightforward so I'll merge, thanks @rgommers

**Pull request merged**
