### PR TITLE
ENH: sparse.linalg: The solution is zero when R.H.S. is zero

### PR DESCRIPTION
**Pull request by zhaog6**
#### What does this implement/fix?

Update some files in `sparse.linalg.isolve` so that the solution of the algebraic systems is zero when R.H.S equals zero.

### CODE REVIEW

**Comment by tupui** [comment]
Thanks for the PR. Can you add some tests to cover your proposal?

**Comment by zhaog6** [comment]
> Thanks for the PR. Can you add some tests to cover your proposal?
Dear Pamphile, the PR just avoids further iterations when R.H.S. is zero, and the related tests have existed in the function `test_zero_rhs` in `sparse.linalg.isolve.tests.test_iterative`.

**Comment by zhaog6** [comment]
@tupui Could you change the label for me with the PR. `enhancement` ~~`scipy.signal`~~ --> `scipy.sparse`. Thanks.

**Comment by tupui** [comment]
> Dear Pamphile @tupui , the PR just avoids further iterations when R.H.S. is zero, and the related tests have existed in the function `test_zero_rhs` in `sparse.linalg.isolve.tests.test_iterative`.

But I am not sure how to verify that your change is producing what you intent to do.

**Comment by zhaog6** [comment]
> But I am not sure how to verify that your change is producing what you intent to do.

Currently, just to verify the correctness of result obtained. The verification of the point you mentioned may be a little difficult because we need to know if the Krylov iterations are zero out of these called functions.

**Comment by akhmerov** [comment]
Are you sure this provides a significant speedup? Iterative solvers should converge within about 1 iteration if the rhs is zero.

**Comment by zhaog6** [comment]
> Are you sure this provides a significant speedup? Iterative solvers should converge within about 1 iteration if the rhs is zero.

The PR is not for **"a significant speedup"**, it's a process that should be handled before iterations, especially when your right-hand side is zero, the process avoids redundant(meaningless) operations more or less (this feature should be provided in the iterative solvers, not for **"a significant speedup"**).

**Review by rgommers — APPROVED** [review]
This LGTM, thanks @zhaog6

**Comment by mdhaber** [comment]
There are some failures in master that may be associated with this PR. Can you take a look? E.g. see failures in gh-14684 CI.

**Comment by rgommers** [comment]
I'll have a look now.

**Comment by zhaog6** [comment]
> There are some failures in master that may be associated with this PR. Can you take a look?

> I'll have a look now.

@mdhaber @rgommers , my bad, `lsqr.py` don't need to deal with the case of  `bnorm == 0` because of `arnorm`.

> The special-casing isn't needed here, because if `bnorm` is zero, then `arnorm` is also zero and the early exit is already fine.

Yes, Thanks.

**Pull request merged**
