### PR TITLE
DOC: special: small tweaks to the `zetac` docstring

### PR DESCRIPTION
**Pull request by person142**
#### Reference issue

None

#### What does this implement/fix?

- Remove the line about limitations of the function for negative
  arguments as they have been addressed in https://github.com/scipy/scipy/pull/8515
- Add a reference

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
Rendering looks good

https://14343-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.special.zetac.html

+1 for merge from me, and looks like a straightforward doc fix so I'll put it in. Thanks @person142

**Comment by WarrenWeckesser** [comment]
@larsoner, how do you get the link to the rendered docs?

**Comment by mdhaber** [comment]
@WarrenWeckesser I saw that! : P

**Comment by WarrenWeckesser** [comment]
@mdhaber, yeah, I had forgotten that I'd asked about viewing the artifacts on circle-ci before.  It requires signing in with circle-ci, and that means giving them read/write access to *my* github account ("This application will be able to read and write all public and private repository data."), which I (still) don't want to do at the moment.

**Comment by mdhaber** [comment]
There is another way to get the link, and I had written it in the developer documentation before it was suggested that I remove it:
Visit ``https://circle-artifacts.com/gh/scipy/scipy/13179/artifacts/0/html-scipyorg/index.html`` after replacing ``13179`` with your CircleCI job number.

**Comment by WarrenWeckesser** [comment]
Great, I was just looking to see if the URL could be inferred from circle-ci test results, so thanks!

**Comment by mdhaber** [comment]
Should I put it back?

**Comment by WarrenWeckesser** [comment]
I assume that whoever suggested taking it out had a good reason, and I don't think this PR is the place to start second-guessing that decision.  You could ask about it in your dev. docs. PR.

**Comment by larsoner** [comment]
It was probably me suggesting that people sign in. It's easier for people willing to do it. I'm fine with listing both methods.

**Pull request merged**
