### PR TITLE
ENH: Extending _distance_pybind with additional distance metrics

### PR DESCRIPTION
**Pull request by czgdp1807**
#### Reference issue

#14077

#### What does this implement/fix?

In this PR following metrics will be ported to `_distance_pybind11`,

- [x] dice
- [x] hamming
- [x] jaccard
- [x] kulsinski
- [x] matching
- [x] rogerstanimoto
- [x] russellrao
- [x] sokalmichener
- [x] sokalsneath
- [x] yule

The remaining distance metrics (tricky and potential blocker ones) are being dealt with in https://github.com/scipy/scipy/pull/14611

Please feel free to leave your reviews.

#### Additional information

Benchmark results.

```python
       before           after         ratio
     [453aad79]       [24897be1]
     <master>         <pybind11_dist_framework>
+     1.59±0.02ms      1.98±0.04ms     1.24  spatial.Xdist.time_pdist(1000, 'dice')
+     3.20±0.01ms      3.89±0.02ms     1.21  spatial.Xdist.time_cdist(1000, 'dice')
+     31.9±0.07μs       38.5±0.5μs     1.21  spatial.Xdist.time_cdist(100, 'dice')
+     17.0±0.07μs      20.2±0.06μs     1.19  spatial.Xdist.time_pdist(100, 'dice')
+     1.90±0.01ms      2.19±0.03ms     1.15  spatial.Xdist.time_pdist(1000, 'yule')
+     3.85±0.02ms      4.40±0.07ms     1.14  spatial.Xdist.time_cdist(1000, 'yule')
+     20.2±0.07μs       23.0±0.3μs     1.14  spatial.Xdist.time_pdist(100, 'yule')
+     38.3±0.02μs       43.2±0.2μs     1.13  spatial.Xdist.time_cdist(100, 'yule')
+     19.9±0.07μs       22.0±0.3μs     1.11  spatial.Xdist.time_pdist(100, 'jaccard')
+      38.0±0.2μs      41.6±0.06μs     1.09  spatial.Xdist.time_cdist(100, 'jaccard')
+     1.35±0.01ms      1.47±0.02ms     1.09  spatial.Xdist.time_pdist(1000, 'russellrao')
+     1.94±0.01ms      2.10±0.03ms     1.08  spatial.Xdist.time_pdist(1000, 'jaccard')
+     2.73±0.03ms       2.95±0.1ms     1.08  spatial.Xdist.time_cdist(1000, 'sokalmichener')
+     3.94±0.03ms       4.23±0.1ms     1.07  spatial.Xdist.time_cdist(1000, 'jaccard')
+     14.7±0.04μs      15.6±0.04μs     1.06  spatial.Xdist.time_pdist(100, 'sokalmichener')
-     31.9±0.05μs       30.2±0.1μs     0.95  spatial.Xdist.time_cdist(100, 'sokalsneath')
-     2.33±0.02μs      2.20±0.01μs     0.94  spatial.Xdist.time_pdist(10, 'jaccard')
-     3.04±0.01μs      2.84±0.07μs     0.94  spatial.XdistWeighted.time_pdist(20, 'euclidean')
-     2.39±0.02μs      2.19±0.04μs     0.91  spatial.Xdist.time_pdist(10, 'sokalmichener')
-     2.46±0.01μs      2.21±0.02μs     0.90  spatial.Xdist.time_pdist(10, 'yule')
-     2.40±0.02μs      2.15±0.02μs     0.90  spatial.Xdist.time_pdist(10, 'kulsinski')
-     2.39±0.02μs      2.14±0.02μs     0.89  spatial.Xdist.time_pdist(10, 'dice')
-     2.94±0.03μs      2.61±0.01μs     0.89  spatial.Xdist.time_cdist(10, 'yule')
-     2.78±0.04μs      2.46±0.04μs     0.88  spatial.Xdist.time_cdist(10, 'russellrao')
-     2.43±0.01μs      2.12±0.01μs     0.87  spatial.Xdist.time_pdist(10, 'sokalsneath')
-     1.14±0.01ms         990±10μs     0.87  spatial.Xdist.time_pdist(1000, 'hamming')
-     2.41±0.01μs      2.09±0.07μs     0.87  spatial.Xdist.time_pdist(10, 'rogerstanimoto')
-     2.86±0.02μs      2.47±0.01μs     0.86  spatial.Xdist.time_cdist(10, 'sokalsneath')
-     2.86±0.01μs      2.46±0.01μs     0.86  spatial.Xdist.time_cdist(10, 'kulsinski')
-        2.41±0μs      2.07±0.04μs     0.86  spatial.Xdist.time_pdist(10, 'russellrao')
-     2.83±0.01μs      2.42±0.05μs     0.86  spatial.Xdist.time_cdist(10, 'sokalmichener')
-      27.3±0.3μs       23.2±0.3μs     0.85  spatial.XdistWeighted.time_cdist(100, 'hamming')
-     2.89±0.04μs      2.44±0.04μs     0.84  spatial.Xdist.time_cdist(10, 'dice')
-     2.83±0.02μs      2.38±0.04μs     0.84  spatial.Xdist.time_cdist(10, 'rogerstanimoto')
-        18.4±1μs      13.1±0.07μs     0.71  spatial.XdistWeighted.time_pdist(100, 'hamming')
-      26.9±0.1μs      18.6±0.04μs     0.69  spatial.Xdist.time_cdist(100, 'hamming')
-      16.8±0.1μs      10.5±0.03μs     0.63  spatial.Xdist.time_pdist(100, 'hamming')
-     7.81±0.02μs      3.57±0.02μs     0.46  spatial.XdistWeighted.time_cdist(20, 'hamming')
-     7.43±0.09μs      2.99±0.01μs     0.40  spatial.XdistWeighted.time_pdist(20, 'hamming')
-     7.14±0.09μs      2.84±0.02μs     0.40  spatial.XdistWeighted.time_cdist(10, 'hamming')
-     7.11±0.08μs      2.66±0.02μs     0.37  spatial.XdistWeighted.time_pdist(10, 'hamming')
-     6.85±0.06μs      2.37±0.05μs     0.35  spatial.Xdist.time_cdist(10, 'hamming')
-     6.59±0.09μs      2.08±0.01μs     0.32  spatial.Xdist.time_pdist(10, 'hamming')
-         251±7μs      2.63±0.06μs     0.01  spatial.XdistWeighted.time_pdist(10, 'russellrao')
-         335±3μs      2.68±0.01μs     0.01  spatial.XdistWeighted.time_pdist(10, 'jaccard')
-         510±2μs      2.84±0.03μs     0.01  spatial.XdistWeighted.time_pdist(10, 'yule')
-         533±1μs      2.91±0.02μs     0.01  spatial.XdistWeighted.time_cdist(10, 'russellrao')
-       513±0.8μs      2.61±0.02μs     0.01  spatial.XdistWeighted.time_pdist(10, 'sokalmichener')
-         517±5μs      2.60±0.03μs     0.01  spatial.XdistWeighted.time_pdist(10, 'rogerstanimoto')
-         540±1μs      2.68±0.03μs     0.00  spatial.XdistWeighted.time_pdist(10, 'kulsinski')
-         551±5μs      2.66±0.04μs     0.00  spatial.XdistWeighted.time_pdist(10, 'sokalsneath')
-         740±7μs      2.96±0.03μs     0.00  spatial.XdistWeighted.time_cdist(10, 'jaccard')
-         688±7μs      2.66±0.01μs     0.00  spatial.XdistWeighted.time_pdist(10, 'dice')
-     1.04±0.01ms      3.08±0.02μs     0.00  spatial.XdistWeighted.time_pdist(20, 'russellrao')
-     1.13±0.02ms      3.33±0.09μs     0.00  spatial.XdistWeighted.time_cdist(10, 'yule')
-     1.16±0.02ms      2.90±0.04μs     0.00  spatial.XdistWeighted.time_cdist(10, 'rogerstanimoto')
-     1.22±0.01ms      3.02±0.02μs     0.00  spatial.XdistWeighted.time_cdist(10, 'kulsinski')
-     1.14±0.01ms      2.82±0.01μs     0.00  spatial.XdistWeighted.time_cdist(10, 'sokalmichener')
-     1.24±0.01ms      3.02±0.08μs     0.00  spatial.XdistWeighted.time_cdist(10, 'sokalsneath')
-     1.44±0.01ms      3.41±0.05μs     0.00  spatial.XdistWeighted.time_pdist(20, 'jaccard')
-     1.53±0.01ms      2.98±0.03μs     0.00  spatial.XdistWeighted.time_cdist(10, 'dice')
-     2.16±0.03ms      3.94±0.04μs     0.00  spatial.XdistWeighted.time_pdist(20, 'yule')
-     2.16±0.03ms      3.78±0.02μs     0.00  spatial.XdistWeighted.time_cdist(20, 'russellrao')
-     2.93±0.04ms      4.54±0.03μs     0.00  spatial.XdistWeighted.time_cdist(20, 'jaccard')
-     2.16±0.03ms      3.14±0.05μs     0.00  spatial.XdistWeighted.time_pdist(20, 'sokalmichener')
-     2.17±0.01ms      3.13±0.08μs     0.00  spatial.XdistWeighted.time_pdist(20, 'rogerstanimoto')
-     2.31±0.01ms      3.22±0.02μs     0.00  spatial.XdistWeighted.time_pdist(20, 'kulsinski')
-     2.31±0.02ms      3.19±0.06μs     0.00  spatial.XdistWeighted.time_pdist(20, 'sokalsneath')
-     4.55±0.06ms      5.57±0.08μs     0.00  spatial.XdistWeighted.time_cdist(20, 'yule')
-     2.90±0.02ms      3.36±0.04μs     0.00  spatial.XdistWeighted.time_pdist(20, 'dice')
-     4.51±0.03ms      3.84±0.08μs     0.00  spatial.XdistWeighted.time_cdist(20, 'rogerstanimoto')
-     4.73±0.04ms      3.99±0.07μs     0.00  spatial.XdistWeighted.time_cdist(20, 'kulsinski')
-     4.77±0.03ms      3.98±0.06μs     0.00  spatial.XdistWeighted.time_cdist(20, 'sokalsneath')
-     4.54±0.05ms      3.75±0.01μs     0.00  spatial.XdistWeighted.time_cdist(20, 'sokalmichener')
-     6.22±0.07ms      4.34±0.01μs     0.00  spatial.XdistWeighted.time_cdist(20, 'dice')
-      36.2±0.3ms      24.8±0.03μs     0.00  spatial.XdistWeighted.time_pdist(100, 'jaccard')
-        55.1±1ms       37.2±0.2μs     0.00  spatial.XdistWeighted.time_pdist(100, 'yule')
-      72.5±0.1ms       46.7±0.4μs     0.00  spatial.XdistWeighted.time_cdist(100, 'jaccard')
-         111±1ms       71.0±0.7μs     0.00  spatial.XdistWeighted.time_cdist(100, 'yule')
-      26.1±0.2ms       16.2±0.2μs     0.00  spatial.XdistWeighted.time_pdist(100, 'russellrao')
-      52.2±0.3ms       29.4±0.4μs     0.00  spatial.XdistWeighted.time_cdist(100, 'russellrao')
-      58.9±0.6ms       19.7±0.3μs     0.00  spatial.XdistWeighted.time_pdist(100, 'kulsinski')
-      73.8±0.3ms       23.7±0.2μs     0.00  spatial.XdistWeighted.time_pdist(100, 'dice')
-      59.0±0.2ms       18.9±0.1μs     0.00  spatial.XdistWeighted.time_pdist(100, 'sokalsneath')
-         118±1ms      35.8±0.06μs     0.00  spatial.XdistWeighted.time_cdist(100, 'kulsinski')
-       149±0.8ms       44.9±0.2μs     0.00  spatial.XdistWeighted.time_cdist(100, 'dice')
-      55.3±0.7ms       16.3±0.2μs     0.00  spatial.XdistWeighted.time_pdist(100, 'sokalmichener')
-      55.8±0.4ms       16.4±0.2μs     0.00  spatial.XdistWeighted.time_pdist(100, 'rogerstanimoto')
-         118±2ms       34.0±0.1μs     0.00  spatial.XdistWeighted.time_cdist(100, 'sokalsneath')
-       113±0.4ms       29.9±0.3μs     0.00  spatial.XdistWeighted.time_cdist(100, 'rogerstanimoto')
-       112±0.7ms       29.6±0.3μs     0.00  spatial.XdistWeighted.time_cdist(100, 'sokalmichener')

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

### CODE REVIEW

**Comment by h-vetinari** [comment]
Should check how `hamming` / `sokalmichener` / `rogerstanimoto` stand w.r.t. to the issues summarized about them in [this](https://github.com/scipy/scipy/issues/14077#issuecomment-899031445) comment.

**Comment by czgdp1807** [comment]
Hi. Dropping in. I am a bit focussed on other project right now. I will get back to this issue in a couple of weeks.

**Comment by czgdp1807** [comment]
> Should check how `hamming` / `sokalmichener` / `rogerstanimoto` stand w.r.t. to the issues summarized about them in [this](https://github.com/scipy/scipy/issues/14077#issuecomment-899031445) comment.

Should I remove these three for now from this PR?



> Edit: and `kulsinski` has been superseded by point 5. of that linked comment as well.

Yes. May be I should `kulczynski1` instead `kulsinski`?

Please let me know your thoughts. @h-vetinari

**Comment by h-vetinari** [comment]
> Should I remove these three for now from this PR?

Not necessarily. If their behaviour stays the same as currently, then I think it's good if it's consistent with the other distances. The The comment I was referring to points out some potential behavioural issues.

> Yes. May be I should `kulczynski1` instead `kulsinski`?

Yes, please do.

**Comment by czgdp1807** [comment]
`hamming` metric when passed to `distance.pdist` and `distance.cdist` behave similarly with strings for Python and C++ versions here. 

And yes, in C++ code `sokalmichener` and `rogerstanimoto` have the same implementation in C++ version here. In fact, `SokalmichenerDistance` has one extra attribute `ntt` which is never used in the projection function. See `distance_metrics.h` file for the implementations. Let me know if I should I remove one of these from the implementation.

**Comment by jjerphan** [comment]
Hi @czgdp1807,

Do you still have time to continue working on this PR as-well? :slightly_smiling_face:

**Comment by jjerphan** [comment]
If @peterbell10 can't, I can.

**Comment by rgommers** [comment]
This looks pretty close. I'll bump the milestone though, because the 1.10.x branch creation date is in 5 days. If it gets in by then, great - but it's not blocking for the release.

**Comment by jjerphan** [comment]
@rgommers: I've opened https://github.com/scipy/scipy/pull/17522 to follow-up and have those changes integrated.

**Comment by tylerjereddy** [comment]
Superseded by gh-17538, which I've now merged.

**Pull request closed without merging**
