### PR TITLE
MAINT: follow up to gh-15741 fix examples

### PR DESCRIPTION
**Pull request by j-bowhay**
#### What does this implement/fix?

After gh-15741 was merged I noticed Id failed to update some of the subsequent documentation, apologies, this pr rectifies this.
@tupui

### CODE REVIEW

**Review by tupui — COMMENTED** [review]
Thanks @j-bowhay. I saw it but I don't think we can remove this like that. In this case it was an alias and not raising any warnings. So if want to remove some aliases, we should decide first on the ones to keep and do a deprecation cycle.

There is this issue #14039 I opened some time ago to discuss it. Feel free to raise this again.

**Comment by h-vetinari** [comment]
> In this case it was an alias and not raising any warnings.

I'm not sure I follow; it was decorated with `np.deprecate` and raising a warning since 1.0.0:
```
>>> import scipy
>>> scipy.__version__
'1.8.0'
>>> from scipy.spatial.distance import matching
>>> matching([1, 0, 0], [0, 1, 0])
<stdin>:1: DeprecationWarning:     `matching` is deprecated!
    spatial.distance.matching is deprecated in scipy 1.0.0; use spatial.distance.hamming instead.
0.6666666666666666
```

**Comment by j-bowhay** [comment]
@tupui thanks yes I think it is probably fine to leave matching as an alias and close this pr

**Comment by tupui** [comment]
@h-vetinari You're confusing the call to `cdist` with the call to `matching` directly. In case of `cdist` using the method `matching` does not raise anything as `matching` itself is not being called.

@j-bowhay Thanks I will close this then.

**Pull request closed without merging**
