### PR TITLE
DOC: add a note in poisson distribution when mu=0 and k=0 in pmf method

### LINKED ISSUE #12113: scipy.stats.poisson docs for rate = 0
I noticed that the docs for [scipy.stats.poisson](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html) are not clear about the intended behaviour when `\lambda = 0 `. 

Strictly speaking, the pmf for the Poisson is ill-defined at `\lambda = 0`; however, the `\lambda \to ` limit of a Poisson seems to me well-defined and intuitive,

    P(n | \lambda = 0) = { 1 if n = 0
                         { 0 otherwise
The mean and variance are `$E(n) = Var(n) = \lambda = 0$` as expected. The Poisson is implemented this way (requring only non-negative rate paramater) in [R](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Poisson.html), which should give some confidence that it isn't an obviously silly thing to do.

Indeed, the current behaviour appears to be just this,
```
>>> from scipy.stats import poisson
>>> poisson.pmf(1, 0.)
0.0
>>> poisson.pmf(0, 0.)
1.0
```

so, can we add a note to the docs that this is the intended treatment?

See https://github.com/scikit-hep/pyhf/issues/293#issuecomment-627207254 where this issue arose indirectly.

### PR DESCRIPTION
**Pull request by tirthasheshpatel**
#### Reference issue

Fixes #12113 

#### What does this implement/fix?

I have added a note in poisson distribution docs to warn that the pmf will return 1.0 at quantile k = 0. when rate = 0.

### CODE REVIEW

**Comment by andrewfowlie** [comment]
it says

> returns `1.0` instead of the expected value `0.0`.

why is 0. the expected value? *if* this behavior is intended and won't be broken in future, it can just say returns 1. No need to say anything about what was expected.

**Comment by tirthasheshpatel** [comment]
Thanks @andrewfowlie. Changed it!

**Review by andrewfowlie — APPROVED** [review]

**Comment by andrewfowlie** [comment]
I think this is helpful and should be merged

**Comment by rlucas7** [comment]
The fail in travis is the ppc that is happening frequently (on other PRs too) and is unrelated. 
I can confirm the docstring change describes current behavior on master:

```
>>> from scipy.stats import poisson
>>> poisson.pmf(1, 0.)
0.0
>>> poisson.pmf(0, 0.)
1.0
>>> poisson.pmf(0.1, 0.)
0.0
>>> import scipy
>>> scipy.__version__
'1.6.0.dev0+c5e0ca5'
>>> 
(scipy-dev) Lucass-MacBook:scipy rlucas$ git log -n 2 --oneline
c5e0ca5be (HEAD -> master, origin/master, origin/HEAD) MAINT: Cleanup unneeded void* cast in setlist.pxd
ec8763fe0 Merge pull request #12186 from pmla/spherical-voronoi-generalize-tests
(scipy-dev) Lucass-MacBook:scipy rlucas$ 
```

Thanks @tirthasheshpatel can you rebase this PR off master and remove the `[MRG]` part from the commit message as that isn't a convention we follow in SciPy? 

Feel free to either ping me once complete or select the "request review" and request me here in the PR, and I'll merge.

**Comment by tirthasheshpatel** [comment]
@rlucas7  Seems like I messed up the rebase. Sorry! Should I open a new PR?

**Comment by rlucas7** [comment]
> @rlucas7 Seems like I messed up the rebase. Sorry! Should I open a new PR?

No worries, sorry that happened. Yes, go ahead and open a new PR.

I used to think I understood why this happens but now I'm no longer sure, don't get discouraged by it, it happened to me several times while learning the git rebase process.

**Comment by tirthasheshpatel** [comment]
Thanks @rlucas7! Closing this in favor of #12486

**Pull request closed without merging**
