### PR TITLE
Doc: fix docstring of scipy.spatial.chebyshev

### LINKED ISSUE #11442: Chebyshev weights
It seems that the chebyshev distance weights are not used in the calculation, or i am doing something wrong but looking at the following source code, i think there is an omission
```
def chebyshev(u, v, w=None):
    u = _validate_vector(u)
    v = _validate_vector(v)
    if w is not None:
        w = _validate_weights(w)
        has_weight = w > 0
        if has_weight.sum() < w.size:
            u = u[has_weight]
            v = v[has_weight]
    return max(abs(u - v))
```
for example:
```
from scipy.spatial import distance
distance.chebyshev([10, 0, 0], [0, 1, 0], w=np.array([1,20,1]))
10
```
i was expecting it to return 20

### PR DESCRIPTION
**Pull request by AtsushiSakai**
#### Reference issue
To fix #11442 

#### What does this implement/fix?
fix docstring of scipy.spatial.chebyshev based on the discussion in #11442

### CODE REVIEW

**Review by tylerjereddy — APPROVED** [review]
This looks like a straightforward approval -- same wording Ralf used in the issue :)

**Comment by rgommers** [comment]
LGTM too, merged. Thanks @AtsushiSakai

**Comment by fancidev** [comment]
I came across this PR and the referenced issue when I was reading the code of spatial. I think the PR may not be correct and the original text seems more accurate.

Since Chebyshev distance is the Minkowski distance with $p$ toward $+\infty$, I expect the behavior of “weighted” Chebyshev to agree with the limiting behavior of weighted Minkowski as $p$ tends to $+\infty$.

Numerical experiment shows that the limiting behavior of weighted Minkowski distance as $p$ goes to $+\infty$ is exactly how the weighted Chebyshev distance is coded in distance_metrics.h and distance.py — it is the max difference among positions where the weight is positive. So the implementation is correct.

In this sense, the weights *are* used, rather than unused as the PR suggests. Just that the weights don’t have a “linearish” effect on the result, like many other metrics. This appears to be a mathematical consequence of the infinite norm, though I don’t know how to prove it mathematically.

@tylerjereddy

**Comment by tylerjereddy** [comment]
@fancidev can you provide a concrete example where providing the weights currently affects the returned distance?

I did some testing with `hypothesis` and the weighted and unweighted examples always agreed:

```diff
--- a/scipy/spatial/tests/test_distance.py
+++ b/scipy/spatial/tests/test_distance.py
@@ -46,6 +46,8 @@ from numpy.testing import (verbose, assert_,
                            assert_almost_equal, assert_allclose,
                            break_cycles, IS_PYPY)
 import pytest
+from hypothesis import given, strategies as st
+from hypothesis.extra.numpy import arrays
 
 import scipy.spatial.distance
 
@@ -64,6 +66,8 @@ from scipy.spatial.distance import (braycurtis, canberra, chebyshev, cityblock,
                                     sokalsneath, sqeuclidean, yule)
 from scipy._lib._util import np_long, np_ulong
 
+array_strategy = arrays(dtype=np.int64, shape=(3,), elements=st.integers(1, 90000000))
+
 
 @pytest.fixture(params=_METRICS_NAMES, scope="session")
 def metric(request):
@@ -2265,3 +2269,12 @@ def test_immutable_input(metric):
     x = np.arange(10, dtype=np.float64)
     x.setflags(write=False)
     getattr(scipy.spatial.distance, metric)(x, x, w=x)
+
+
+@given(weights=array_strategy)
+def test_chebyshev_weight_ignore(weights):
+    arr1 = [10, 0, 0]
+    arr2 = [0, 1, 0]
+    expected = chebyshev(arr1, arr2, w=None)
+    actual = chebyshev(arr1, arr2, w=weights)
+    assert_allclose(actual, expected)
```

**Comment by tylerjereddy** [comment]
Also, if you do find such a case, please do go ahead and open a new issue.

**Comment by fancidev** [comment]
@tylerjereddy Please find an example below:

```
In [2]: from scipy.spatial.distance import cdist, chebyshev

In [3]: x = [3,5]

In [4]: y = [0,0]

In [5]: w = [1,0]

In [6]: chebyshev(x, y)
Out[6]: 5

In [7]: chebyshev(x, y, w=w)
Out[7]: 3

In [8]: cdist([x], [y], 'chebyshev')
Out[8]: array([[5.]])

In [9]: cdist([x], [y], 'chebyshev', w=w)
Out[9]: array([[3.]])
```

Let me make a PR to refine the doc next week if the test case looks ok!

**Comment by fancidev** [comment]
Here is a proof that the weights for Chebyshev distance matter, but only up to being zero or not.

Let $(u_1, \cdots, u_n)$, $(v_1,\cdots,v_n)$, and $(w_1,\cdots,w_n)$ be real vectors, such that $w_i \ge 0$, $i=1,\cdots,n$. The weighted Chebyshev distance $d$ is defined by

$$
d := \lim_{p\rightarrow +\infty}\left( w_1 |u_1-v_1|^p + \cdots+w_n|u_n-v_n|^p\right)^{1/p}
$$

To compute this, first remove all terms where $w_i=0$ or $u_i=v_i$, because they don’t contribute to the sum for any fixed $p$. If there are no terms left, then $d=0$. Otherwise, suppose without loss of generality that $n$ terms remain that all satisfy $w_i > 0$ and $u_i\ne v_i$.

Next,

**Pull request merged**
