### PR TITLE
MAINT: 1.9.0rc2 backports

### PR DESCRIPTION
**Pull request by tylerjereddy**
Backport PRs (below) and update release notes. I have my eye on gh-16446 as well, though we may delay that to `1.9.1` depending on scheduling. @h-vetinari does this look "ok" from `conda-forge` side now? Note that some PRs were separately merged to the maintenance branch and are not explicitly listed below.

- gh-15235
- gh-16444
- gh-16482
- gh-16484
- gh-16485
- gh-16493
- gh-16507

### CODE REVIEW

**Comment by h-vetinari** [comment]
> @h-vetinari does this look "ok" from `conda-forge` side now? Note that some PRs were separately merged to the maintenance branch and are not explicitly listed below.

Nothing suspicious from my POV as far as I can tell. I'm not very fussed about having the exact number of commits reflected in the release notes, but thanks for fixing it anyway!

**Comment by rgommers** [comment]
There are two failures in the pre-release job. One can be fixed by backporting gh-16393, which is worth doing (can be in the next batch). The other one is a flake (gh-16523).

**Review by rgommers — APPROVED** [review]
LGTM, thanks @tylerjereddy.

**Comment by rgommers** [comment]
> Backport PRs (below) and update release notes. I have my eye on [gh-16446](https://github.com/scipy/scipy/issues/16446) as well, though we may delay that to `1.9.1` depending on scheduling

There's nothing to do there in SciPy itself, it just needs a new `meson-python` release.

**Pull request merged**
