### PR TITLE
MAINT: Rewrite Lfilter in CXX

### PR DESCRIPTION
**Pull request by ghost**
The CXX templating syntax is much nicer than numpy's templates (I personally had significant trouble understanding what was happening because it seemed to be nonstandard). Also, C++ should allow future improvements to type and memory safety.

### CODE REVIEW

**Comment by larsoner** [comment]
C++ templating is not my area of expertise, but from what I see it looks reasonable to me.

How difficult would it be to take care of #7991 here?

**Comment by xoviat** [comment]
If my suspicions are correct, the INT64 case appears not to be handled. I'm going to take a wild guess and see whether that fixes the problem.

**Comment by ewmoore** [comment]
This is probably fine.

FWIW, the templates used in the old version are used extensively in numpy so are not really non-standard in that regard these code bases. If this is reworked, I admit a slight preference for moving this to Cython and using its fused types instead.  If we feel that the current templates are difficult to approach, I'm not sure that moving to C++ is really an improvement.  I suppose that one benefit of this approach is bug for bug compatibility with what is currently available and with Cython that might be difficult.

I do think that we may want a smaller patch that simply fixes gh-7991 and doesn't do anything else.  That patch is then a trivial backport candidate where this probably isn't, but @rgommers should probably weigh in about how necessary he thinks that is.  Making a smaller patch ought not be too difficult since there is already code that ought to be checking for this issue, but doesn't seem to be running.  (see [these lines in lfilter.c.src](https://github.com/scipy/scipy/blob/master/scipy/signal/lfilter.c.src#L182-L188))

**Comment by xoviat** [comment]
@ewmoore Agreed. The patch to fix gh-7991 is checking the dtype correctly in Python. I don't think the type checking in lfilter ever worked.

**Comment by xoviat** [comment]
I'll close this and maybe come back with a patch later that uses fused types. There's not really any work here that can be reused, so I'll just delete the branch.

**Comment by rgommers** [comment]
> I do think that we may want a smaller patch that simply fixes gh-7991 and doesn't do anything else. That patch is then a trivial backport candidate where this probably isn't, but @rgommers should probably weigh in about how necessary he thinks that is.

PR is already closed, but for the record: this isn't a regression and not super critical, so would not want to backport to 1.0.x at this point.

**Comment by xoviat** [comment]
@rgommers I was never considering backporting this. The backport was for the segfault.

**Pull request closed without merging**
