### PR TITLE
MAINT/DEV: rename `skip_if_array_api` to `skip_xp_backends`

### PR DESCRIPTION
**Pull request by lucascolley**
#### Reference issue
Discussion in gh-20285 @mdhaber 

#### What does this implement/fix?
Renames the marker and the fixture to avoid confusion.

#### Additional information
Open to suggestions for a better name.

### CODE REVIEW

**Comment by lucascolley** [comment]
I can't immediately see the CI failure on other PRs - strange...

**Comment by mdhaber** [comment]
Doesn't look related, though. I'll give others a bit to suggest names, but LGTM (assuming the CI failure is indeed unrelated), and I can merge if you remind me : )

**Review by tylerjereddy — APPROVED** [review]
Although I'm neutral on the name change, and not interested in debating if it makes Matt/folks happier, the diff seems "ok," and I did check a few extra things here:

1. This branch does not fail any tests locally on x86_64 Linux (in contrast with the one in CI) in any of these scenarios: NumPy `2.0.0b1` from PyPI, latest NumPy `main` built from source, and the pre-release nightly wheel currently available. I also tried building against latest NumPy `main` then downgrading to `1.26.4` at test time--the full suite still passed. So I'd say "unrelated," yeah.
2. The branch has the same GPU/array-api test suite footprint as `main` for me locally: `5 failed, 48902 passed, 10659 skipped, 153 xfailed, 13 xpassed in 58.53s` from `SCIPY_DEVICE=cuda python dev.py test -j 32 -b all`

As for using `.git-blame-ignore-revs`, I guess you could, though I suspect the history around the array API transformations on these functions is already full of simple mechanical changes made in bulk.

**Comment by lucascolley** [comment]
thanks for the thorough review as always Tyler :)

> As for using .git-blame-ignore-revs, I guess you could, though I suspect the history around the array API transformations on these functions is already full of simple mechanical changes made in bulk.

I also think that the blame is not much use to anyone around these lines at the minute, so this probably won't change things.

**Comment by tylerjereddy** [comment]
I think it is "ok" to put this in now. It wouldn't really matter that much if we needed to change it again anyway, it is just internal-facing development stuff, but hopefully there are diminishing returns for a second name change.

**Comment by tylerjereddy** [comment]
thanks Lucas

**Pull request merged**
