### PR TITLE
ENH: Add cepstrum functions and minimum phase reconstruction. - WIP

### PR DESCRIPTION
**Pull request by FRidh**
This adds
- complex_cepstrum         -- Compute the complex cepstrum of a real sequence.
- real_cepstrum            -- Compute the real cepstrum of a real sequence.
- inverse_complex_cepstrum -- Compute the inverse complex cepstrum of a real sequence.
- minimum_phase            -- Compute the minimum phase reconstruction of a real sequence.

### CODE REVIEW

**Comment by FRidh** [comment]
To do:

- [ ] Add more references
- [ ] Add tests. 
- [ ] Add examples.

What do you think about the names of the functions? I'm not so much a fan of short names but rather be explicit of what a function does.

For the implementation I used the documentation of Matlab, which describes the steps to be taken quite well. I suppose this is okay? Can this be added as a reference? 

I've added one test but I guess it would be good to add more. Any suggestions for tests? I did validate the results against Matlab for a couple of sequences (was also a good way to find the cases they do not document...)

cc @rgommers @WarrenWeckesser @endolith @ewmoore

**Comment by rgommers** [comment]
``cepstrum`` - my noun of the week:)

Why not combine the real and complex functions? Signatures are the same, so can't you simply switch the code path based on the dtype of the input?

What is the reason to only have an inverse function for complex and not for real?

**Comment by rgommers** [comment]
Please don't add a reference to the Matlab version. What you can do is mention the matlab function name corresponding to the Python version in the ``Notes`` section. An article or book as a reference would be useful.

You can read Matlab docs and learn from them, as long as you do not look at any Matlab source code.

**Comment by FRidh** [comment]
The real and complex cepstrum are different. Both operate on a real-valued sequence, and return a real-valued sequence. However, the real cepstrum uses only the magnitude of the DFT of the input, whereas the complex cepstrum uses both magnitude and phase angle.

Because the real cepstrum discards the phase angle it is impossible to reconstruct the original signal, and therefore no `inverse_real_cepstrum` exists.

I've added a use-case for the `complex_cepstrum` as an example. If you have a signal consisting of harmonics it allows you to determine the fundamental frequency. This is actually what I use it for.

**Comment by FRidh** [comment]
Note that Travis failed because the test exceeded the 50 minutes limitation.

**Comment by srvanrell** [comment]
+1 for this enhancement. @FRidh Do you need any help?

**Comment by larsoner** [comment]
We now at least have `scipy.signal.minimum_phase`. @FRidh are you interested in coming back to this? If so it might be best to start from scratch based on what `scipy.signal.minimum_phase` already provides.

It looks like the last commit was 4 years ago with no response to a ping 3 years ago, so I'll go ahead and close. But @FRidh I'm happy to reopen if you want to work from this branch again!

**Pull request closed without merging**
