### PR TITLE
MAINT: fix mypy complaints

### LINKED ISSUE #22031: BUG: mypy failure in main
### Describe your issue.

Mypy is failing in main, e.g. gh-22024, perhaps due to new release.

### Reproducing Code Example

```python
See CI logs, e.g. https://github.com/scipy/scipy/actions/runs/12227904923/job/34105328001?pr=22024
```

### Error message

```shell
scipy/optimize/_isotonic.py:147: error: Incompatible types in assignment (expression has type "ndarray[tuple[int, ...], dtype[signedinteger[_64Bit]]]", variable has type "ndarray[tuple[int], dtype[signedinteger[_64Bit]]]")  [assignment]
scipy/stats/tests/test_stats.py:6056: error: Incompatible types in assignment (expression has type "list[float | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")  [assignment]
scipy/stats/tests/test_stats.py:6057: error: Incompatible types in assignment (expression has type "list[float | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")  [assignment]
scipy/stats/tests/test_stats.py:6058: error: Incompatible types in assignment (expression has type "list[float | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")  [assignment]
scipy/stats/tests/test_stats.py:6059: error: Incompatible types in assignment (expression has type "list[float | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")  [assignment]
scipy/stats/tests/test_stats.py:6060: error: Incompatible types in assignment (expression has type "list[float | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")  [assignment]
scipy/stats/tests/test_stats.py:6061: error: Incompatible types in assignment (expression has type "list[float | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")  [assignment]
```

### SciPy/NumPy/Python version and system information

```shell
main
```

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
Closes gh-22031

#### What does this implement/fix?
Mypy is failing in main, e.g. https://github.com/scipy/scipy/pull/22024, perhaps due to new release. This attempts to fix the issue.

#### Additional information
@lorentzenchr Thoughts on a better fix for this line in isotonic (besides ignoring mypy)?

### CODE REVIEW

**Comment by lorentzenchr** [comment]
You can use a new variable name instead of reusing the same `r`. I also had my troubles with this behaviour of mypy.

**Comment by lucascolley** [comment]
cc @jorenham fyi

**Comment by jorenham** [comment]
> cc @jorenham fyi

This looks like a consequence of one of those "many improved annotations" that came with yesterday's NumPy 2.2.0 release, and there's a good chance I'm to blame for this 😅. But luckily there appears to be a reasonable workaround. You could even argue that this `np.nan` "workaround" should be preferred over `None` in these cases 🤷🏻.

**Comment by mdhaber** [comment]
Thanks @lorentzenchr. I suppose is easy to fix, but I prefer how it is written now.
Yes, @jorenham I think `np.nan`s are fine there.

**Comment by tylerjereddy** [comment]
I'll add a tentative backport label

**Comment by mdhaber** [comment]
I think this does the trick, so it's ready IMO.

**Review by lucascolley — APPROVED** [review]

**Pull request merged**
