### PR TITLE
CI: fix prerelease job to use numpy 2.0, and add a second job to test ABI compat

### LINKED ISSUE #19846: CI: pre-release Linux job isn't using NumPy pre-release anymore
Check a recent passing example like from https://github.com/scipy/scipy/pull/19842

Log: https://github.com/scipy/scipy/actions/runs/7460685402/job/20299264968?pr=19842

Grep on the raw log to see that `matplotlib` requiring NumPy `< 2` overrides our pre-release use of NumPy:

`grep -E -i -n "numpy-" raw_pre_rel_log.txt`; you'll see `2.0.0.dev0` removed and replaced with `numpy-1.26.3` near the end.

I don't read the logs for fun, I just noticed that in the release branch at gh-19797, the pre-release job doesn't get rejected because of the NumPy version range (it should, that branch disallows `2.0.0` series).

As for how to fix it, well you could swap the order like this to install after `maplotlib`:

```diff
--- a/.github/workflows/linux_meson.yml
+++ b/.github/workflows/linux_meson.yml
@@ -306,8 +306,8 @@ jobs:
     - name: Install Python packages
       run: |
         python -m pip install cython pythran ninja meson-python pybind11 click rich_click pydevtool
-        python -m pip install --pre --upgrade --timeout=60 -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
         python -m pip install --pre --upgrade pytest pytest-cov pytest-xdist mpmath gmpy2 threadpoolctl pooch matplotlib hypothesis
+        python -m pip install --pre --upgrade --timeout=60 -i https://pypi.anaconda.org/scientific-python-nightly-wheels/simple numpy
         # TODO: once the scipy_ symbol prefix issue is fixed, install
         # scipy-openblas32 from the pre-releases bucket again (see gh-19640)
         python -m pip install "scipy-openblas32<=0.3.23.293.2"
```

But I think you'll get a few test failures because we have optional `maplotlib` tests that will choke on the combo of `matplotlib` and NumPy 2.x series. Perhaps just removing `matplotlib` might be "ok" for that pre-release job for now, if they don't have a `2.0.0` dev branch for us to play with (I didn't check).

### PR DESCRIPTION
**Pull request by rgommers**
Closes gh-19846

The new job added is the same as the old job, except that it builds against numpy 2.0-dev, then downgrades numpy to 1.22.4, and then runs the tests. This will surface potential issues with ABI compatibility. We may not need that job forever, but it'll be useful insurance during the 2.0 release period.

### CODE REVIEW

**Review by larsoner — APPROVED** [review]
Agreed this is a good idea, +1 for merge when green from me

**Comment by tylerjereddy** [comment]
The Windows 3.11 CI failure is unrelated, and is actually useful for me to see, as I now know it isn't specific/blocker for release branch (see: gh-19852).

**Review by tylerjereddy — APPROVED** [review]
LGTM as well, and I checked the `numpy-` version strings in the two affected CI logs by hand.

**Comment by tylerjereddy** [comment]
thanks Ralf

**Pull request merged**
