### PR TITLE
Minkowski Distance Type Fix (issue #10262)

### PR DESCRIPTION
**Pull request by jdriscoll7**
Fixed minkowski_distance_p function, removed redundant lines in minkowski_distance function, and added test cases for minkowski_distance function that address issue #10262.

### CODE REVIEW

**Comment by rgommers** [comment]
This code hasn't been touched in 8 years, and the functions look slow and not robust against corner cases like the one fixed in this PR. There doesn't seem to be any functionality not covered by `spatial.distance` (`distance.minkowski` and `distance.cdist` should be all).

We should probably consider deprecating this. Thoughts?

**Comment by jwd0023** [comment]
What do you mean by "There doesn't seem to be any functionality not covered by `spatial.distance`"?

But I agree - these functions look pretty slow and could be pretty easily improved. If I get around to it today, I can make a few easy/quick improvements.

No idea if it should be deprecated - I feel like it was put in there for some reason, even though I don't know why.

**Comment by rgommers** [comment]
@jwd0023 try comparing these minkowski distance functions in `kdtree.py` with `minkowski` in `spatial.distance`. The latter is more comprehensive and way faster than the former. 

The same goes for `spatial.distance_matrix` vs. `spatial.distance.cdist`. 

`kdtree.py` and `distance.py` were developed in parallel it looks like, and put in in Oct-Nov 2008. The `kdtree` functions have seen little use or maintenance since, and we'd forgotten that they even existed (at least I had). It looks to me like there's no point keeping around duplicate functionality or spend effort on these functions.

**Comment by jwd0023** [comment]
@rgommers Yep this is probably an easy fix. Probably can just do `from . import distance`, and replace all of the `minkowski_distance` and `minkowski_distance_p` calls with `minkowski`.

Thanks for the elaboration - I 100% agree with you.

**Comment by pv** [comment]
Merging --- the PR itself looks ok, deprecation cf gh-10419

**Pull request merged**
