### PR TITLE
MAINT: make runtest.py --bench-compare use asv continuous and not store results

### LINKED ISSUE #4592: runtests.py --bench-compare seems to assume that benchmarks do not change
This is probably a user error / UI enhancement request.

Found while trying to measure the overhead in gh-4486

I wrote a trivial benchmark to measure the evaluation time for a PPoly object. Ran 
`$ python runtests.py --bench-compare master interpolate.BenchPPoly`, which worked fine. 

Then I decided to tweak the benchmark, to make the size of some arrays smaller etc. So I change the benchmark code, commit, and...

```
$ python runtests.py --bench-compare master interpolate.BenchPPoly
· Fetching recent changes
· Creating environments
·· Creating virtualenv for py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six.
·· Cloning project
· Installing dependencies.....................
· Discovering benchmarksException RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
..
·· Uninstalling from py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six
·· Building for py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six.............................................................................................................................................................................
·· Installing into py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six..
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)
· Fetching recent changes
· Creating environments
· Installing dependencies..
· Discovering benchmarksException RuntimeError: RuntimeError('cannot join current thread',) in <Finalize object, dead> ignored
..
·· Uninstalling from py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six..
·· Installing into py2.7-Cython0.21.1-Tempita0.5.2-numpy1.8.2-six..
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)

All benchmarks:

    before     after       ratio
  [e3f5273f] [a1ebeb91]
-  671.37μs    30.13μs      0.04  interpolate.BenchPPoly.time_evaluation
```

I don't know what these RuntimeErrors are, but a 22x speedup is completely spurious. I'd guess the result from `master` got cached somewhere with the old parameters, while the feature branch benchmark was actually run anew.

### PR DESCRIPTION
**Pull request by pv**
Fixes gh-4592

### CODE REVIEW

**Comment by rgommers** [comment]
The diff LGTM.

I'm working out the kinks still in running the benchmarks (``run.py publish`` is now creating a virtualenv with numpy 1.8.2??), but I'd say let's merge benchmark PRs a bit quickly now to keep things moving forward.

**Comment by rgommers** [comment]
<created a new label Benchmarks>

**Comment by pv** [comment]
Yes, the benchmarks use a fixed numpy version.
`publish` needs in some cases to build scipy so that it can use it to import the `benchmarks` module.

**Comment by rgommers** [comment]
Good to know, thanks.

**Pull request merged**
