### PR TITLE
make p0 (initial values) required for curve_fit() instead of defaulting to 1

### PR DESCRIPTION
**Pull request by newville**
This PR changes the behavior of `curve_fit()` to *require* initial values for parameters.  The current behavior of allowing `p0=None` meaning to set all initial values to 1.  

It trips up too many new and inexperienced users who do not recognize that setting initial values is an important part of curve-fitting.   Furthermore, the value selected (1), like any other value is arbitrary and cannot possibly be mathematically justified.  

In a word, the current behavior of `curve_fit()` is wrong.

### CODE REVIEW

**Comment by ev-br** [comment]
Would you bring this on the scipy-dev mailing list please? Changes this radical should certainly be proposed over there.

**Comment by WarrenWeckesser** [comment]
If we did decide to do this, we would have to phase it in with a deprecation cycle.

**Comment by ilayn** [comment]
I am -1 on this. Entering initial values is a very annoying task from a UX point of view which also forces random numbers to be entered anyways if the user has no idea what they should be. 

If I don't enter them, it means I don't care hence 1. or any other value is fine. There is no mathematical justification required for this. So I don't agree about this behavior being wrong.

**Comment by rgommers** [comment]
I agree in principle that requiring an initial guess is better. All other optimization functions do this. We'd need a long-ish deprecation cycle though I think

**Comment by newville** [comment]
Based on mailing list discussion, I updated this PR to 

 -  allow`p0=None` but issue a RuntimeWarning and add strong discouragement in docstring.
 -  update example in docstring to *not* use `p0=None`, but to provide initial values, and to show how to report estimated stderr on best-fit values.
 - change `p0=None` from using initial values of 1 (subject to bounds) to a randomly selected value (subject to bounds).

I have to admit I am ambivalent about this.

**Comment by WarrenWeckesser** [comment]
Changing the default `p0` to random initial values is an API change, and would need a deprecation cycle.  

I didn't get the impression from the mailing list discussion that such an approach was preferred.  Personally, I don't think it is a good idea.  It makes the API a bit more complicated, and it makes the result of the function explicitly nondeterministic.  And if this approach was adopted, there is a chance that we would have to make the API even more complicated in the future.  We (well, I, anyway) have learned that when a function uses random values internally, eventually users will want more control over the random number generator, and that leads to adding a `random_state` parameter to the function.

**Comment by newville** [comment]
@WarrenWeckesser  The default value for `p0` is `None`, which is unchanged from the current version.   What the function does with that default *is* changed.  The most important change in behavior, and the only behavior that should be relied with `p0=None` is that a `RuntimeWarning` is raised.  As a side-effect, a fit will be attempted with initial values chosen by the function.

FWIW, in the current master version, the docstring for `p0` says that `if None,  then the initial values will all be 1`, which is true only when all bounds are infinite.  That is, the algorithm uses `p0=None` to select initial values for parameters based on the other input to `curve_fit()`.   The behavior is complex and should not be relied upon.  This PR changes the details, but not the complexity. 

If a future user complains about the behavior or asks for more control over the random state for selecting initial values when `p0=None`, the correct response is "supply initial values for p0".

**Comment by perimosocordiae** [comment]
I'd like to add another -1 from the peanut gallery for using random values here. It's bound to cause headaches for users, and (I believe) it's no more likely to be useful than all ones.

We should definitely clean up the docstring to explain the complexity here, though.

**Comment by newville** [comment]
@perimosocordiae  I agree that randomly selecting starting values is bound to cause headaches.  That is a feature of this PR.  `p0=None` is incorrect and users should not be misled that it is ever acceptable.

**Comment by WarrenWeckesser** [comment]
>  The default value for p0 is None, which is unchanged from the current version. What the function does with that default is changed. 

Right, that's the change that I was talking about; sorry I wasn't specific enough.  By "default value", I mean the value that is used when `p0=None`.  Any change from all 1s will require a deprecation cycle.

**Comment by newville** [comment]
lost interest in helping scipy `curve_fit`.

**Comment by ev-br** [comment]
Hi Matt. Just wanted to say that your work is very much appreciated, even if not always accepted into scipy.optimize. Dissenting opinions are actually most valued! And special thanks for lmfit, which *is* the package to reach to when curve_fit runs out of steam.

**Comment by newville** [comment]
@ev-br um, then why did a very large fraction of scipy developers and commenters here insist on `curve_fit` continuing to be incorrect?  It is completely indefensible that `curve_fit` allows a user to *not* provide initial values.  It is mathematically incorrect.   The PR here was not "I think this would be better", it is a fix to a mathematical error.  You chose to refuse the fix and have the code continue to be incorrect.   That's a disservice to your users.

**Comment by ev-br** [comment]
@newville I think we disagree here. The optimization procedure is well defined even if the initial approximation is selected automatically. Whether this initial guess is sensible a different question. 

So this is basically a question of UI. The `curve_fit` UI may well be suboptimal, and newer code does require the initial guess (e.g. `least_squares`). However for `curve_fit` I suspect backwards compatibility wins over. 

Note that I'm speaking for myself here, not the scipy project or anyone else, just myself. And for the record I'm only -0 on the change. And changing the default here would definitely need to brought up on the mailing list.

**Comment by newville** [comment]
On Sun, Nov 8, 2020 at 9:04 AM Evgeni Burovski <notifications@github.com>
wrote:

> @newville <https://github.com/newville> I think we disagree here. The
> optimization procedure is well defined even if the initial approximation is
> selected automatically. Whether this initial guess is sensible a different
> question.
>

Hm OK. Thanks for confirming.

The code has allowed  `p0=None` for a very long time.  This is
mathematically wrong and is indefensible.  Along with a model function and
data (or, more generally, an objective function), initial values are always
required for non-linear least-squares and curve-fitting problems.   Initial
values are not optional.  There cannot be a default set of finite initial
values that is sensible.  Disagreeing with this demonstrates a failure to
understand the algorithm.

The PR here was more than 18 months old (submitted around v1.2).
`scipy.optimize` continues to have changes made, and this error has not
been fixed.  Let's not kid ourselves: this error is not going to be fixed,
the code will continue to be wrong.  To me, that raises alarm bells about
the development and review process and quality assurance for the rest of
scipy.

So this is basically a question of UI. The curve_fit UI may well be
> suboptimal, and newer code does require the initial guess (e.g.
> least_squares). However for curve_fit I suspect backwards compatibility
> wins over.
>

OK, then. Backwards compatibility wins over the code being correct.

Note that I'm speaking for myself here, not the scipy project or anyone
> else, just myself. And for the record I'm only -0 on the change. And
> changing the default here would definitely need to brought up on the
> mailing list.
>

This was discussed. A fix was made available more than 18 months ago. The
scipy developers have chosen for this error to persist.

**Pull request closed without merging**
