### PR TITLE
DOC: fix issues in `svds` docstring examples that were failing in CI

### LINKED ISSUE #18381: BUG: refguide check failure in sparse svd code
### Describe your issue.

Lately I have seen the refguide job failing in CI multiple times in some sparse svd section: https://app.circleci.com/pipelines/github/scipy/scipy/19755/workflows/7be1af01-79dc-459c-92c4-d4a6d72c2471/jobs/66447

Thought I would raise attention with a separate issue.

Slightly related: it looks like the Fortran sparse SVD libraries are very painful to maintain. One unfortunately license incompatible alternative could be [Spectra](https://github.com/yixuan/spectra), ARPACK rewritten in C++. Are there any thoughts on replacements for the old PACKs?

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
File "build-install/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 280, in svds
Failed example:
    s_a(u2[:, :1], u[:, :1]) + s_a(u2[:, 1:], u[:, 1:]) > 1e-3
Expected:
    True
Got:
    array([False])

File "build-install/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 283, in svds
Failed example:
    (s_a(vT2[:1, :].T, vT[:1, :].T) +
     s_a(vT2[1:, :].T, vT[1:, :].T)) > 1e-3
Expected:
    True
Got:
    array([False])
```

### SciPy/NumPy/Python version and system information

```shell
N/A
```

### PR DESCRIPTION
**Pull request by rgommers**
Also address some readability issues (imports at top, no weird abbreviations like `s_a`).

Closes gh-18381

[skip cirrus] [skip actions]

### CODE REVIEW

**Review by h-vetinari — APPROVED** [review]
I'm not sure why we need 39 digits for seeds in a doctest, but other than that, LGTM, thanks a lot for fixing this!

**Comment by rgommers** [comment]
> I'm not sure why we need 39 digits for seeds in a doctest

I'm following the guidance in http://scipy.github.io/devdocs/dev/contributor/rendering_documentation.html#examples-and-randomness for using explicit seeds. Given the persistent flakiness of these tests, I'd prefer using explicit seeds in that docstring, to exclude the possibility of doctest machinery being involved somehow (it's supposed to "fill in" missing seeds, and I think it works fine - it's hard to prove or reuse during debugging though).

**Comment by rgommers** [comment]
Okay, approval is in and fixes CI failures, so I'll go ahead and merge.

**Comment by h-vetinari** [comment]
OK, the "discourage users from copying this" is a reasonable argument of course.

**Pull request merged**
