### PR TITLE
ENH: Make special C++ implementations work on CUDA (and beyond!)

### PR DESCRIPTION
**Pull request by izaid**
#### Reference issue

[RFC 19404](https://github.com/scipy/scipy/issues/19404)

#### What does this implement/fix?

This is the next step in the C++ migration of sp.special. What it does in particular is update the new C++ lambertw to work on CUDA. This required a bit of extra work and boilerplate, but after that was done the code looks almost the same. By doing this now, we'll make more special functions CUDA-compatible (and array API compatible more generally) as we go.

What you will note is that NVRTC lacks some of the standard library. People are aware of that and there are many ways to work around it. What I've done, and will advocate for here, is a simple config.h file that checks to see if certain std include headers exist. If they don't, we either alias existing functions or types, or simply add them ourselves. A small amount of work can take us a long way here. I have chosen to define them directly in `std`, rather than declare some other namespace, and we can talk more about that if people want.

NVIDIA is working on this more generally, see https://github.com/nvidia/cccl

### CODE REVIEW

**Comment by izaid** [comment]
cc @steppi @mdhaber @tirthasheshpatel

**Comment by ev-br** [comment]
A huge thank you for this! 

(had recently to copy-caste some cephes code into https://github.com/cupy/cupy/tree/main/cupyx/scipy/special --- would be great to avoid copy-pasting going forward)

**Comment by izaid** [comment]
> A huge thank you for this!
> 
> (had recently to copy-caste some cephes code into https://github.com/cupy/cupy/tree/main/cupyx/scipy/special --- would be great to avoid copy-pasting going forward)

That is the plan! I believe @steppi has his 👀 on all of Cephes, possibly quite soon.

**Comment by steppi** [comment]
Very nice @izaid!

One small thing; can you put the formatting changes in a separate commit so it’s easier to look at the diffs?  

For the test, I think we can just add a test in `scipy/special/tests` that gets skipped if CuPy isn’t available. I’ll give

**Comment by izaid** [comment]
@steppi I have reverted the formatting, and will save that for a follow-up PR.

I have some thoughts on how to test sensibly, but I'd actually like to leave that also for a follow-up PR. It will require some effort, and I'd like to get these C++ changes in so as to not conflict with your and others work. Of course, there is already testing in this PR by virtue of the host code being the default SciPy implementation.

**Comment by steppi** [comment]
> @steppi I have reverted the formatting, and will save that for a follow-up PR.
> 
> I have some thoughts on how to test sensibly, but I'd actually like to leave that also for a follow-up PR. It will require some effort, and I'd like to get these C++ changes in so as to not conflict with your and others work. Of course, there is already testing in this PR by virtue of the host code being the default SciPy implementation.

Ok. I can accept adding the CuPy tests later as long as this PR doesn’t break anything in SciPy.

**Comment by steppi** [comment]
I’m seeing relevant test failures due to redefinitions of constants.

**Comment by steppi** [comment]
Nice. Looks like that did it.

**Review by steppi — APPROVED** [review]
I had a synchronous conversation with @izaid, who explained how all of this works, since I don't have experience with CUDA programming.

In summary, when run on CUDA, we need to add `__host__` and `__device__` to the function signatures to tell the compiler we want them to be able to run on CPU and GPU respectively. There are also constants and standard library functions that are missing on CUDA, so if the preprocessor detects these are missing, the code defines them. [Thrust](https://github.com/NVIDIA/cccl/tree/main) is used for missing standard library functions, and only those actually needed for `lambertw` are included. We'll add more as they are needed. It will be up to downstream users of this library to ensure the needed dependencies are available and linked.

This PR has no impact on the behavior of this code on the SciPy side, so I think it's fine for us not to add new tests. izaid has verified that this code will work with CuPy locally.

Amazing work izaid, really happy to see this!

**Comment by jrhemstad** [comment]
Howdy, I lead the team that maintains https://github.com/NVIDIA/cccl

I wanted to follow up with deferring to Thrust for the missing standard library functionality.

I'd highly recommend using libcudacxx instead of Thrust as libcudacxx is intended specifically for this kind of use case where you want a heterogeneous C++ Standard library implementation that works with NVRTC. 

So instead of `thrust::complex` you use `cuda::std::complex` or instead of `std::numeric_limits`, `cuda::std::numeric_limits`.

**Comment by jakirkham** [comment]
> Right now, the priority is making things work with CuPy, so we need to explore whether `cuda::std` is available there.

cc @leofang (who may know)

**Comment by jrhemstad** [comment]
Happy to help any way I can! Let me know if you want to set up a time to chat more in depth and I'd be happy to answer any questions or explain where we're going.

**Pull request merged**
