### PR TITLE
MAINT: size 0 vector handling in cKDTree range queries

### PR DESCRIPTION
**Pull request by sturlamolden**
Special cases handling of size-0 `std::vector` in `cKDTree` range query methods. Adds test cases for all possible cases where queries find no matches and return len-0 containers. Closes issue #5639.

### CODE REVIEW

**Comment by sturlamolden** [comment]
Backport candidate for 0.17.x

**Comment by sturlamolden** [comment]
Meh, it seems my Mac stored a unicode character that causes problems on Python 2.

**Comment by sturlamolden** [comment]
Ping @rgommers

**Comment by rgommers** [comment]
Thanks Sturla, merged.

**Comment by rgommers** [comment]
I would not recommend backporting to 0.17.x, because it's not really required to make that release and it's enough of a change that it could require another RC.

**Pull request merged**
