### PR TITLE
ENH: add Normal Inverse Gaussian (nig) distribution to scipy.stats (distributions.py)

### PR DESCRIPTION
**Pull request by sdrap**
The Normal Inverse Gaussian distribution gains quite a lot of momentum in the last years as a fat tail distribution (finance, Levy processes, extreme values, etc. see http://en.wikipedia.org/wiki/Normal-inverse_Gaussian_distribution)

I am mathematician and newbee in Python. Out of curiosity I coded with scipy a method to compute risk measures with nig distribution. Therefore, I added the nig ppf to the library of continuous distribution functions in distributions.py. This was not difficult, I copied the code used for other distributions. However, being new to python, this may be not optimal.

I crossed checked with Matlab and R and so far it matches the result obtained there.

I am still thinking about a method to compute the cdf as well as the ppf since there are no close form for them and the performance are very poor in comparison with the equivalent in R or Matlab (This is central for our applications).

Being new to python, git and all the stuff I hope that I did the things at least halfway right.

### CODE REVIEW

**Comment by chrisb83** [comment]
Hi,

I looked a bit into the NIG Distribution. In my view, the random variates can be generated via V + sqrt(V)*X where X is standard normal and V is inverse gaussian (using suitable parameters). This way, one would not need to invert the CDF but rely on the invgaussian already implemented in scipy. However, invgaussian also has problems with the CDF for certain Parameters (mu <= 0.0028 does not work according to https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.invgauss.html#scipy.stats.invgauss)

For the CDF, potentially the approach above could help as well: one could write the CDF as the convolution of the Gaussian CDF and the gaussian inverse density. I would need to test if this is faster. 

To complete this pull request, what would be required? would it be enough if rvs can be generated in a fast way whereas the cdf is still "suboptimal" (i.e. "slow")

**Comment by chrisb83** [comment]
Writing the CDF as a convolution is even slower, so that does not help. 

However, the rvs method should be fine now, see https://github.com/chrisb83/scipy/tree/norminvgaussian

If this is considered to be enough to have a useful implementation, I would write tests for the distribution.

One would also Need to decide if the current implementatin of _cdf using some kind of optimization should be kept or if one simply want to rely to the inherited cdf method (slower, but more simple).

Feedback welcome...

**Comment by rgommers** [comment]
> However, the rvs method should be fine now, see https://github.com/chrisb83/scipy/tree/norminvgaussian

Nice. 

My memory on this topic is a bit fuzzy. This PR and gh-6739 are competing right? IIRC this one was in better shape (did not double check that). Opening a new PR with your changes is probably the best way to go about reviewing your code.

> If this is considered to be enough to have a useful implementation, I would write tests for the distribution.

I'd say it depends on how slow `cdf` is; just annoyingly slow is a lot better than unusably slow.

**Comment by vyasr** [comment]
I believe that this pull request was implemented in pull request #8171 and can be closed.

**Comment by chrisb83** [comment]
Yes, let's close it

**Comment by rgommers** [comment]
Ah missed that. Thanks @vyasr!

**Pull request closed without merging**
